### ISSUE TITLE
Asahi Linux: Rust 1.62 reports out of memory

### ISSUE THREAD

**Issue by docbobo** [rust-lang/rust#100180]
I just installed Asahi Linux on my Mac Mini M1 and wanted to compile a Rust-based application using `cargo build --release`. However, that fails immediately with the following error output:

```
error: process didn't exit successfully: `rustc -vV` (signal: 6, SIGABRT: process abort signal)
--- stderr
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
LLVM ERROR: out of memory
Allocation failed
```

**Comment by workingjubilee** [comment]
Hello!
I assume you have an installation via Rustup?
Can you run the following and show me the output?
```sh
for dir in "${HOME}"/.rustup/toolchains/* ; do { for libs in "$dir"/lib/* ; do file "$libs"; ldd "$libs"; done; }; done
```

**Comment by docbobo** [comment]
Valid assumption - but wrong. I had been using the ArchLinux package.  With the rustup install, everyhing works :facepalm:

**Comment by workingjubilee** [comment]
Hmm. Usually, installing Rustup from the ALARM repos and using that to get rustc is generally the recommended flow for Arch Linux (on ARM). Can you link me to the PKGBUILD for the ALARM package you were using?

**Comment by workingjubilee** [comment]
Oh, I see. This is covered as an issue by the wiki for Asahi Linux:
https://github.com/AsahiLinux/docs/wiki/Broken-Software

https://github.com/rust-lang/rust/issues/100180

**Comment by jannau** [comment]
I'm thinking if it wouldn't make sense to fix this problem in rust itself. The problem is not limited to Arch Linux ARM but will affect every distribution which enables jemalloc and builds on systems with 4k page size. Based on https://github.com/jemalloc/jemalloc/issues/467 it seems to be unrealistic to expect jemalloc to ever work with dynamic page sizes.
So it would make sense t ensure within rust that jemalloc is build with `JEMALLOC_SYS_WITH_LG_PAGE=16`/`--with-lg-page=16` for the maximal supported page size of 64k on aarch64. Since https://github.com/jemalloc/jemalloc/pull/769 it will work on systems with a smaller page size.
