### ISSUE TITLE
Support for Python 2.7 should be dropped

### ISSUE THREAD

**Issue by rbanffy** [rust-lang/rust#100269]
Considering Python 2.7 is no longer maintained, it'd be wise to start winding down support for it in `x.py` and issuing a warning discouraging its use.

**Comment by Mark-Simulacrum** [comment]
In general, we don't currently have any significant pain due to maintaining support for python 2.7 in the very small amount of Python code that we use to bootstrap the build system (x.py/bootstrap.py). That makes any plan to remove support largely just hurt some fraction of users who do want/need it, and not really benefit us, so I don't think it makes sense. The user may also be using a supported version of 2.7 (e.g., from a distro with a long LTS).

**Comment by gimbles** [comment]
Gotta wait another decade to painlessly drop support for 2.7... and then get an issue that something broke somewhere ;)

Jokes aside, 2.7 is still [unfortunately] in use by some ancient scripts, probably best to not drop support for it, or get bombarded with "Aaa something broke in X company I work at!" issues 😄

**Comment by rbanffy** [comment]
Makes sense. The amount of Python is really tiny. I guess this janitorial work can be safely postponed until the last LTS that supports Python 2 gets finally EOL'ed. We should probably tag this to a future release so that it revives in a good couple years.

**Comment by jyn514** [comment]
I would like to add an FAQ about this somewhere; people have repeatedly brought it up because the issue tracker makes it hard to find the past issues.
