### ISSUE TITLE
"using `_` for array lengths is unstable" error should suggest the number of elements

### ISSUE THREAD

**Issue by Kampfkarren** [rust-lang/rust#100448]
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fe35b2f5f585f0303661ac61e880d1fe

```rust
const NUMBERS: [i32; _] = [
    1, 2, 3
];
```

The current output is:

```
error[[E0658]](https://doc.rust-lang.org/stable/error-index.html#E0658): using `_` for array lengths is unstable
 --> src/lib.rs:1:22
  |
1 | const NUMBERS: [i32; _] = [
  |                      ^
  |
  = note: [see issue #85077 <https://github.com/rust-lang/rust/issues/85077>](https://github.com/rust-lang/rust/issues/85077) for more information

error: in expressions, `_` can only be used on the left-hand side of an assignment
 --> src/lib.rs:1:22
  |
1 | const NUMBERS: [i32; _] = [
  |                      ^ `_` not allowed here

For more information about this error, try `rustc --explain E0658`.
error: could not compile `playground` due to 2 previous errors
```

Ideally, the output should suggest that this should be [i32; 3].

**Comment by WaffleLapkin** [comment]
This can use [diagnostic stashing](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/diagnostic_builder/struct.DiagnosticBuilder.html#method.stash) in [ast lowering](https://github.com/rust-lang/rust/blob/cc65e1a548abee1d664113abd117b79055532ffa/compiler/rustc_ast_lowering/src/lib.rs#L2239), so that later, in type check, when we can infer the infer constant we can provide a better diagnostic. I haven't found where in type check to do this yet :')
