### ISSUE TITLE
let_chains desugaring is wrong

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#100513]
I tried this code: [playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=c1ff3da556b18b34f63727a9db54540f)

```rust
struct LoudDrop(&'static str);

impl Drop for LoudDrop {
    fn drop(&mut self) {
        println!("Dropped! {}", self.0);
    }
}

fn get_drop(str: &'static str) -> Option<LoudDrop> {
    Some(LoudDrop(str))
}

fn main() {
    println!("1");
    if get_drop("first").is_some() && get_drop("1.5").is_some() && let None = get_drop("last") {
        println!("2");
    } else {
        println!("2");
    }
    println!("3");
}
```

This prints
```
1
Dropped! 1.5
Dropped! last
2
Dropped! first
3
```

According to [RFC 2497](https://rust-lang.github.io/rfcs/2497-if-let-chains.html), it should desugar to this: [playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=314b080d0eb54cd4561cdd6bfc7dada7)
```rust
fn main() {
    println!("1");
    'FRESH_LABEL: {
        if get_drop("first").is_some() {
            if get_drop("1.5").is_some() {
                if let None = get_drop("last") {
                    break 'FRESH_LABEL { println!("2") }
                }
            }
        }
        { println!("2") }
    }
    println!("3");
}
```
But this prints
```
1
Dropped! first
Dropped! 1.5
Dropped! last
2
3
```

### Meta
Wrong on the current beta
```
1.64.0-beta.1

(2022-08-09 56714e5332f5f21c39d7)
```

**Comment by Nilstrieb** [comment]
This also causes issues like #99852 and #100276

**Comment by joshtriplett** [comment]
Yeah, that definitely looks wrong; we will have to roll this back and try again for 1.65.

**Comment by Nilstrieb** [comment]
I've opened a [zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/fixing.20let_chains/near/293442089) about fixing them,

**Comment by Nilstrieb** [comment]
That's was a misclick 😆

**Comment by Manishearth** [comment]
@joshtriplett given https://github.com/rust-lang/rustfmt/pull/5203#issuecomment-1206802238 , can we use this opportunity to also ensure that there is a style decision put forth by the lang team in place before restabilizing so that rustfmt is able to merge formatting for let_chains?

**Comment by CrimsonVoid** [comment]
I'm not sure if this is the right place to provide feedback, but has there been any consideration on disabling 'irrefutable pattern' warnings for cases like `if let _ = rx.read_exact(&mut buf).await? && buf != info_hash`. I find myself repeating this pattern often enough that the compiler warnings are starting to get be kind of much.

I'd like to piggyback on @Manishearth's comment on possibly revisiting syntax for let chains, preferably in favor of either comma (`,`) or semicolon (`;`). Again, just speaking personally, most of my uses of let chains involve declaring some sort of pre-op and then checking the results of that operation, and both comma and semicolon feel like they express sequencing more clearly than boolean and. Also consider the visual noise of introducing `&&` in an already somewhat noisy language.

**Comment by T-Dark0** [comment]
This isn't the proper place to discuss the feature, to my knowledge. That would probably be an IRLO thread (internals.rust-lang.org), or a Zulip one

**Comment by est31** [comment]
Note that one doesn't have to follow the RFC, what gets stabilized in the end can sometimes deviate from the things that an RFC decides upon. I'm not saying that the current drop order is good for stabilization though, it isn't. One could e.g. drop temporaries more early on, as in, before the `else` block runs. Then stuff accessed in the if expression can safely be re-used from the `else` block.

**Comment by est31** [comment]
> I'm not sure if this is the right place to provide feedback, but has there been any consideration on disabling 'irrefutable pattern' warnings for cases like `if let _ = rx.read_exact(&mut buf).await? && buf != info_hash`.

The irrefutable pattern lint was specifically extended to let chains in #94951 , after my [comment](https://github.com/rust-lang/rust/pull/94927#issuecomment-1067078300) on the tracking issue received only positive responses (see the thumbs up reactions). As for the right place to provide feedback, it is let chains related I would say, but despite that, this specific thread is the wrong place to discuss it, as it is about the desugaring and not about let chains in general.

Personally I don't think it should be changed because the lint was made in a way that if it fires, there exists a way to move the irrefutable pattern out of the let chain. Your particular code would work with `read_exact(&mut buf).await?; if buf != info_hash` for example. This is similar to how `if let _ = foo() { bar(); }` lints on current master today because you can write that as `let _ = foo(); bar();` (and remove the _ if the function is not `#[must_use]`).

Again, so far this lint has only received positive feedback.

**Comment by CrimsonVoid** [comment]
> Again, so far this lint has only received positive feedback.

Ah yes, the [black swan theory](https://en.wikipedia.org/wiki/Black_swan_theory) of RFCs. Well, consider this to be your first black swan.

> but despite that, this specific thread is the wrong place to discuss it

Well that puts me in a tough spot; either I reply to your comment here and continue to derail the thread or let you have the last word. 🦆

**Comment by est31** [comment]
> either I reply to your comment here and continue to derail the thread or let you have the last word.

The third option is do what was suggested: open a zulip thread, github issue, or internals thread, or such where you can make your case. You could have made that instead of making that comment to complain on how I have the last word. I didn't open a thread because that's your responsibility: you are the person who has the complaint, not me, and so far you haven't delivered convincing points why a change would make sense. I replied to you because that did feel like my responsibility, as I was the person who implemented the lint.

**Comment by nikomatsakis** [comment]
Discussed in lang-team meeting. We are removing the nomination. The current behavior seems clearly surprising and also not in accordance with the RFC.

**Comment by est31** [comment]
Now that the first nightly with #102998 is out, I've tried running again the snippet from above. The snippet now prints:

```
1
Dropped! 1.5
Dropped! first
Dropped! last
2
3
```

This is not 100% what the desugaring from the RFC prints (should be "first", "1.5", "last"). It's closer than what is seen at the top of the issue's thread, but not quite it. Over at #102998 , @cjgillot has brought up [similar concerns](https://github.com/rust-lang/rust/pull/102998#discussion_r996017194).

So maybe this issue should be reopened?

**Comment by Nilstrieb** [comment]
I agree, I think this issue should only be closed once T-lang decided on a desired drop order and the compiler implements it.

**Comment by Nilstrieb** [comment]
Although actually I have to say that my desugaring might be be fully correct. I split up a normal `&&` into two nested ifs which is probably wrong. If it is let together, we should the current output.

**Comment by est31** [comment]
Yeah it doesn't have to match it 100%, one always deviate in the end from the RFC. What is important is that the details are well understood and approved. #102998 has greatly improved the state but we aren't there yet I think.

## What is currently implemented

So in order to figure out what the current desugaring is doing, I've extended the drop_order.rs test that you added:

<details>


```Rust
        if self.option_loud_drop(4).is_some()
            && self.option_loud_drop(1).is_some()
            && self.option_loud_drop(2).is_some()
            && self.option_loud_drop(3).is_some()
            && let Some(_d) = self.option_loud_drop(19)
            && let Some(_e) = self.option_loud_drop(18)
            && let Some(_e) = self.option_loud_drop(17)
            && self.option_loud_drop(5).is_some()
            && self.option_loud_drop(6).is_some()
            && self.option_loud_drop(7).is_some()
            && self.option_loud_drop(8).is_some()
            && let Some(_e) = self.option_loud_drop(16)
            && let Some(_e) = self.option_loud_drop(15)
            && let Some(_e) = self.option_loud_drop(14)
            && self.option_loud_drop(9).is_some()
            && self.option_loud_drop(10).is_some()
            && self.option_loud_drop(11).is_some()
            && self.option_loud_drop(12).is_some() {
                self.print(13);
        }
```

And:

```Rust
        if let Some(_d) = self.option_loud_drop(8)
            && let Some(_e) = self.option_loud_drop(7)
            && let Some(_e) = self.option_loud_drop(6)
            && self.option_loud_drop(1).is_some()
            && self.option_loud_drop(2).is_some()
            && self.option_loud_drop(3).is_some()
            && self.option_loud_drop(4).is_some() {
                self.print(5);
        }
```

Compare this with normal if chains:

```Rust
        if self.option_loud_drop(5).is_some()
            && self.option_loud_drop(1).is_some()
            && self.option_loud_drop(2).is_some()
            && self.option_loud_drop(3).is_some()
            && self.option_loud_drop(4).is_some() {
            self.print(6);
        }
```

And nested ifs:

```Rust
        if let Some(_d) = self.option_loud_drop(4) {
            if let Some(_e) = self.option_loud_drop(3) {
                if let Some(_e) = self.option_loud_drop(2) {
                    self.print(1);
                }
            }
        }
```


</details>

So nested if let's drop in reverse definition order after their body. On the other hand, let-free ifs with && drop in reading order, except for the first condition, which gets droped last (and all conditions drop before their body). Let's call this the "twist".

For let chains, the current implementation seems to:

1. Drop all let conditions after the then body, but before the else body
2. Drop all non-let conditions before the then/else body
3. Drop let conditions in reverse definition order
4. Drop non-let conditions *mostly* in definition order, but with a special version of the twist: if there is a block of non-let conditions right at the start of the if chain, then the first non-let condition is dropped after all other non-let conditions that are part of that leading block, but still before any possible non-let conditions that come after the first let condition.

## What behaviour should look like

Personally, I agree a lot with the current implementation, except for that weird exception in rule number 4.

Rules 1 and 3 make sense because you need to keep the bindings around for the stuff that possibly uses them, which can be either the subsequent let conditions or the body. We deviate here from if let in that we drop before the `else`, IMO a very good change.

Rule 2 makes sense because ideally you drop stuff as quickly as possible. Same goes for rule 4, except the twist.

**My proposal would be to remove the twist and:**

1. Drop all let conditions after the then body, but before the else body
2. Drop all non-let conditions before the then/else body
3. Drop let conditions in reverse definition order
4. Drop non-let conditions in definition order

What do you think?

An alternative proposal would drop everything in reverse order, after the body. This rule would be simpler, but you would keep around the temporaries for way too long.

_____

*(Side note: Ideally the twist would also be eliminated from normal if's but I'm not sure if we can do this due to backwards compatibly. This step would make bool-only && chains them associative wrt drop order though, and also if let chains associative, at least when we consider a hypothetical extension that allows ()s in let chains. I'm not sure if there are issues about this, and if not, maybe I should file one)*

**Comment by nathanwhit** [comment]
One note:
> 1. Drop all let conditions after the then body, but before the else body

This is not quite accurate, in the current implementation it's inconsistent -- if the `let` is leading then it will drop after the `else` body, but if it is trailing it will drop before the `else` body. ([example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=295ed471b352a5ce7a6635cea4dbdbef), which at time of writing prints `1,2,` then `2,1,`). 

This is the result of the same bug that causes #100276. After #103034, `let` conditions will always drop after the `else` body, just like with normal `if let` (so the aforementioned [example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=295ed471b352a5ce7a6635cea4dbdbef) would print `1,2,` then `1,2,`).

**Comment by est31** [comment]
@nathanwhit thanks! I've edited my comment.

Regarding #103034, I wonder if it's possible to change it so that it always drops before `else`? Keeping around the references for the `then` block makes sense, but `else` doesn't need any of them, and it would be nice if you could re-access stuff in the `else` block that `if let` was accessing. The same holds for `if let` too, see #103108 which also contains an example of code that is currently not compiling due to the behaviour of dropping before the `else` drop order. It might be possible that `if let` can't be changed any more, but it would be great IMO if let chains would start with the better behaviour.

**Comment by est31** [comment]
I've filed an issue for let chains else dropping behaviour: #103248

**Comment by est31** [comment]
PR filed to get rid of the && drop order twist in all Rust: #103293
