### ISSUE TITLE
armv7-unknown-linux-gnueabihf toolchain has wrong types for some ffi functions

### ISSUE THREAD

**Issue by mladedav** [rust-lang/rust#100632]
I tried this code (I know it is not correct to pass a pointer obtained this way to the function, but the type should be correct):

```rust
    let buffer = Vec::<i8>::new().as_mut_ptr();
    unsafe {
        _ = CString::from_raw(buffer);
    }
```

I expected it to compile. (this happens on `x86_64-pc-windows-msvc` and `x86_64-unknown-linux-gnu`)

Instead, it does not compile on `armv7-unknown-linux-gnueabihf` with the following error:
```
error[E0308]: mismatched types
   --> src/main.rs:7:31
    |
7   |         _ = CString::from_raw(buffer);
    |             ----------------- ^^^^^^ expected `u8`, found `i8`
    |             |
    |             arguments to this function are incorrect
    |
    = note: expected raw pointer `*mut u8`
               found raw pointer `*mut i8`
note: associated function defined here
   --> /rust/lib/rustlib/src/rust/library/alloc/src/ffi/c_str.rs:397:19
    |
397 |     pub unsafe fn from_raw(ptr: *mut c_char) -> CString {
    |                   ^^^^^^^^
```

According to [documentation](https://docs.rs/rustc-std-workspace-std/1.0.1/std/ffi/struct.CString.html#method.from_raw) these functions should take `*mut i8`, but the docs are platform-specific. I haven't found docs for other platforms than x86_64 and i686 though.

My problem is with building a cross-platform library. From the docs I am under the impression that there is an issue with the armv7 compiler but if not, I would need to conditionally cast to the correct types based on the platform (where I don't even know which platforms expect which types without trying it out).

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: x86_64-pc-windows-msvc
release: 1.63.0
LLVM version: 14.0.5
```

**Comment by cuviper** [comment]
You're looking at docs for `rustc-std-workspace-std`, which is a kludgy implementation detail.

The normal docs for [`CString::from_raw`](https://doc.rust-lang.org/alloc/ffi/struct.CString.html#method.from_raw) show this signature:

```rust
pub unsafe fn from_raw(ptr: *mut c_char) -> CString
```

The unfortunate truth is that `c_char` may be signed or unsigned, `i8` or `u8`, depending on the target platform.

---

Note that a `Vec::new` pointer is not a sufficient input for this, because it needs to be `'\0'`-terminated even for an empty string. `CString::from_raw` also wants a pointer it can **own**, so the `Vec` doesn't double-free, and 

> ```rust
>     let buffer = Vec::<i8>::new().as_mut_ptr();
>     unsafe {
>         _ = CString::from_raw(buffer);
>     }
> ```

Even setting aside the `c_char` type, there are multiple problems here. Your `buffer` pointer is immediately dangling, because the temporary `Vec` will be dropped, but you aren't getting an error from the borrow checker since it's a raw pointer. `CString::from_raw` needs a `'\0'`-terminated pointer to memory that it can **own** and free when it drops. You could use `CStr::from_ptr` if you want a borrowed version, but you still need a `'\0'` and care for the lifetime.

**Comment by mladedav** [comment]
Right, thanks. I didn't know about  `rustc-std-workspace-std` and all the building details around it so I've been looking at the wrong docs (where some platform-specific details seem to be filled in). The thing that confused me the most is that rust-analyzer also shows `*mut i8` instead of `*mut c_char` in the docs in IDE but I'll try to raise that with them.

I realize that the example I provided is broken, I just wanted something succinct and the only problem I wanted to talk about are the types. My actual usecase uses `CString::new`, `CString::into_raw`, and friends so the lifetimes and `NUL` termination are ok. Next time I'll try to come up with something with less problems. Thanks for the insights though.
