### ISSUE TITLE
Some error messages are invisible in Solorized Light

### ISSUE THREAD

**Issue by Helltraitor** [rust-lang/rust#101045]
In some cases, rust compiler doesn't provide full error information:
Here, all is fine: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=44b2e8f8c231c6475a366c84f25f4ecd

```
Compiling playground v0.0.1 (/playground)
error[E0614]: type `u64` cannot be dereferenced
 --> src/main.rs:6:5
  |
6 |     *value.field = 10;
  |     ^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0614`.
error: could not compile `playground` due to previous error
```

[Example on FreeImage.host](https://freeimage.host/i/4q7JuR)
This issue appears on Windows terminal, but also I think that this is platform independed.

Consider to make error message color red as in playground

Apologize section:
Probably that issue is not so useful (because it's just a color), but I want to help to rust community
As for me, it was very unexpected to get this issue. I was thinking that something wrong in compiler, but thankfully it's not

**Comment by the8472** [comment]
Assuming the compiler uses standard 8x2 ansi colors (8 colors x 2 brightness levels) and not RGB values then this is an issue with the terminal configuration. You have to set up your color scheme so that those 16 colors are distinct.

**Comment by Helltraitor** [comment]
> Assuming the compiler uses standard 8x2 ansi colors (8 colors x 2 brightness levels) and not RGB values then this is an issue with the terminal configuration. You have to set up your color scheme so that those 16 colors are distinct.

I'm not quite understand what I can or must do. Windows terminal supports RGB (or I don't get your message):
https://www.reddit.com/r/Batch/comments/k5iprq/the_windows_console_apparently_now_supports_rgb/

**Comment by the8472** [comment]
There are multiple ways to tell a terminal to show a color. Either is to set explicit RGB values (which can be problematic if one uses an RGB value as foreground which matches the user-defined background) or as a 16-color palette that is user-configurable.

As far as I can tell rustc only [uses the latter](https://github.com/rust-lang/rust/blob/42fa8ac7236f4f78a82aeea543bdd445a59f02e0/compiler/rustc_errors/src/emitter.rs#L2497-L2544). Which means it will use the colors configured in the windows terminal color scheme: https://chrisyeh96.github.io/2020/03/28/terminal-colors.html#windows-colors
The foreground colors should be set up so that all colors except the first are visible on the chosen default background color.

**Comment by ChrisDenton** [comment]
This is a known issue with the solarized colour scheme: https://github.com/microsoft/terminal/issues/6997. It is recommended to either use another theme or to override the invisible colours manually.

**Comment by Helltraitor** [comment]
Thanks, I will choose another theme.
