### ISSUE TITLE
Strange capture behaviour with `let _ = `

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/rust#101090]
I tried this code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1cdcf0a1b37c60649eadac9dae68a847)):

```rust
use std::{thread, rc::Rc, time::Duration};

fn main() {
    fn send_anything(t: Rc<i32>) {
        println!(" In the function: {}", Rc::strong_count(&t));
        thread::spawn(move || {
            thread::sleep(Duration::from_millis(500));
            let _ = t; // move t to thread and ignore it.
        });
    }

    let x = Rc::new(5);
    send_anything(x.clone());
    println!(" before thread: {}", Rc::strong_count(&x));
    thread::sleep(Duration::from_secs(1));
    println!(" after thread: {}", Rc::strong_count(&x));
}
```

I expected to see this happen: Compile error, because `Rc` is not send.

Instead, this happened: Compiled, drop happened in the main thread.

**Comment by ehuss** [comment]
I believe this is intentional behavior. As part of edition 2021, closures now minimally capture only what is necessary. Values that are not "read" are not captured, and thus ignored.  There's more information [here](https://doc.rust-lang.org/nightly/edition-guide/rust-2021/disjoint-capture-in-closures.html#wild-card-patterns) in the edition guide.

**Comment by HKalbasi** [comment]
Thanks! I think I now understand how it works.
