### ISSUE TITLE
Support for showing explicit enum discriminant values in rustdoc

### ISSUE THREAD

**Issue by Enselic** [rust-lang/rust#101337]
Currently, enum discriminant values are not included in the HTML output. The code

```rust
pub enum E {
    V = 42,
}
```

renders like this:
<img width="353" alt="187080081-aa71e5f4-8304-4574-8de1-a16a7aefccd4" src="https://user-images.githubusercontent.com/115040/188211722-21f88777-3404-44b6-b87d-9ae1f8e902cd.png">

However, it is easy to imagine a public API where the discriminant value matters. For example, some lib code could look like this:

```rust
#[repr(u8)]
pub enum Key {
    A = 65, // the value is the ASCII code for 'A'
}
```

and client code like this:

```rust
let key = std::io::stdin().bytes().next().unwrap().unwrap();
if key == Key::A as u8 {
    println!("A was typed")
}
```

In this example, the enum discriminant value is part of the public API of the library, so it would make sense to somehow make rustdoc include enum discriminant values in the rendered HTML.

Depending on the context, it is however perfectly reasonable to consider enum discriminant values to be an implementation detail, even explicit enum discriminant values. So it should also be supported to make sure they are NOT displayed.

The exact mechanism for this is still to be decided. See [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Enum.20discriminant.20values.20in.20HTML.20output) for some discussion on this. But most likely rustdoc should *never* show the enum discriminant value if they are not explicitly defined.

@rustbot label T-rustdoc

**Comment by jsha** [comment]
One of the most common situations where the enum discriminants should be documented is when using IntoPrimitive/TryFromPrimitive, as mentioned in the example from https://github.com/Enselic/cargo-public-api/issues/121.

```
#[derive(num_enum::IntoPrimitive, num_enum::TryFromPrimitive)]
#[repr(u32)]
```

One way to achieve the desired effect for this subset of primitives would be to add to the TryFromPrimitive derive macro so that it adds a `#[doc()]` attribute to each enum variant that documents its value. The values would then show up under the Variants section as documentation. This would be a great way to experiment with documenting enum values without needing new attributes from rustdoc.
