### ISSUE TITLE
`'static` lifetime requirement on generic in order for container type to implement `'static` when using `PhantomData` 

### ISSUE THREAD

**Issue by MaderNoob** [rust-lang/rust#101453]
I tried this code:

```rust
use std::marker::PhantomData;

struct Marker<T>(PhantomData<T>);

fn assert_static_marker<T>(marker: Marker<T>) {
    assert_static(marker)
}
fn assert_static<O: 'static>(_o: O) {}

```

I expected the code to compile without any errors, since `Marker` doesn't really hold a `T`, so it doesn't matter if `T` is `'static` or not for `Marker` to be `'static`.

Instead, i got a compilation error:
```
error[E0310]: the parameter type `T` may not live long enough
 --> src/main.rs:9:5
  |
9 |     assert_static(marker)
  |     ^^^^^^^^^^^^^^^^^^^^^ ...so that the type `T` will meet its required lifetime bounds
  |
help: consider adding an explicit lifetime bound...
  |
8 | fn assert_static_marker<T: 'static>(marker: Marker<T>) {
  |                          +++++++++

For more information about this error, try `rustc --explain E0310`.
```

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (289279de1 2022-09-04)
binary: rustc
commit-hash: 289279de116707f28cf9c18e4bbb8c6ec84ad75b
commit-date: 2022-09-04
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```
</details>

This was also tested on stable and the result was the same. The stable version information:
```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: x86_64-unknown-linux-gnu
release: 1.63.0
LLVM version: 14.0.5
```

**Comment by steffahn** [comment]
It’s working as intended with `PhantomData`. If I recall correctly, there’s some long-term plans to try allowing the type `fn() -> T` to be `'static` though, regardless of `T`’s lifetime. Not a trivial endeavor at all, since it’s easy to run into unsound language design when working with lifetime bounds, especially around implied bounds; if such developments come to fruition however, then you’d be able to use `PhantomData<fn() -> T>` as a marker type :-)

@rustbot label -C-bug, +C-enhancement

**Comment by MaderNoob** [comment]
Ok thanks for the help
