### ISSUE TITLE
Clarify and document region nesting rules

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#10151]
We currently [infer some special relationships between regions based on region nesting][nesting]. i.e., if you have `fn foo<'a,'b>(x: &'a &'b int)`, we infer that `'a <= 'b`. This is important for type checking impls, though it will become less so (and possibly irrelevant even) after DST (#6308) lands. In any case, in the meantime, as part of formalizing the type system, we should clarify precisely which kinds of nesting relationships yield subtyping relations. I have a FIXME in the code for the spot where this ought to be done.

[nesting]: http://smallcultfollowing.com/babysteps/blog/2013/04/04/nested-lifetimes/

**Comment by steveklabnik** [comment]
I'll need some help to document this...

**Comment by nikomatsakis** [comment]
@steveklabnik let's talk ;)

**Comment by steveklabnik** [comment]
Okay, so after some discussions, this ticket feels like something we'd want well-defined for a formalism, but rarely comes up when you're writing Rust code. as such, i'm going to close it, because once we start formalizing, we'll want a systematic attack, but for now, random issues about it aren't helpful.
