### ISSUE TITLE
Windows Mutex implementation should be reevaluated on modern Windows targets

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/rust#101621]
Currently the windows `Mutex` implementation has [this comment](https://github.com/rust-lang/rust/blob/98f3001eecbe4cbd091c10ffab45b4c164bb507b/library/std/src/sys/windows/locks/mutex.rs#L7-L8) at the top talking about its locking approach (using `SRWLock` instead of `CriticalSection`) with the justification that `SRWLock` performs better on Windows 7 and Windows 8.  
However, in the (seven) years since, [Microsoft has ended their Windows 7 support in 2020](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962), Windows 10 became the dominant windows version and Windows 11 was released in 2021.
In light of these massive shifts in the windows ecosystem, our mutex implementation's speed should probably be reevaluated on the more modern Windows 10 and 11 platforms

**Comment by ChrisDenton** [comment]
For background, there's some [old history here](https://docs.microsoft.com/en-us/archive/msdn-magazine/2012/november/windows-with-c-the-evolution-of-synchronization-in-windows-and-c). Firefox and Chrome switched to SRWLOCK [circa 2017](https://bugzilla.mozilla.org/show_bug.cgi?id=1364624).

It would be good to have some modern benchmarks.

**Comment by ChrisDenton** [comment]
cc @m-ou-se for tips on benchmarking mutex implementations.

**Comment by thomcc** [comment]
SRWLOCK was still faster in win10 when I checked a while ago (using a modification of the parking_lot benchmarks (which themselves are a port of webkits mutex benchmarks). This was with InitializeCriticalSection rather than one of the initializers that configures a spin count, so that may impact things.

FWIW, CRITICALSECTION doesn't have a static initializer (AFAIK), and can't be moved (according to <https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-initializecriticalsectionex>), so we might have to use lazy initialization like on pthreads.

I think the comment is just a bit stale, but it doesn't hurt to re-evaluate.

---

That said, I would be interested in seeing how the futex-based locks perform compare to SRWLOCK, since windows does have futex operations and could plausibly use them.

**Comment by ChrisDenton** [comment]
Closing this as we've now switched to using futex-based locks due to [an issue](https://github.com/rust-lang/rust/issues/121949) with the OS SRWLOCK.
