### ISSUE TITLE
rustc doesn't seem to acknowledge llvm-args's dwarf-version flag

### ISSUE THREAD

**Issue by yehuthi** [rust-lang/rust#101892]
I'm trying to get DWARF version 3 in my binary with `rustc main.rs -o ./out -g -Cllvm-args="--dwarf-version=3"` but it doesn't seem to work:

```shell
$ readelf --debug-dump=info ./out | grep -A 2 'Compilation Unit @' | grep Version
   Version:       5
   Version:       5
   Version:       5
   Version:       5
   Version:       4
   Version:       4
   Version:       4
   Version:       4
   Version:       4
   Version:       4
   Version:       4
   Version:       4
   Version:       4
   Version:       4
   Version:       4
   Version:       4
   Version:       4
   Version:       4
   Version:       4
   Version:       5
```

For context: the reason I want to do this is because I want to use the [Coz profiler](https://github.com/plasma-umass/coz) with Rust and it seemingly doesn't like DWARF version 5 which Rust generates (its dying words are: `unknown compilation unit version 5`), so I want to compile with version 3 because that's what [the Coz README specifies](https://github.com/plasma-umass/coz#:~:text=with%20debug%20information%20(-,%2Dg%20%2Dgdwarf%2D3,-).%20You%20do%20not). See also Coz issues [#193](https://github.com/plasma-umass/coz/issues/193), [#107](https://github.com/plasma-umass/coz/issues/107).

A few notes:
- I also tried adding `-C link-arg=-gdwarf-3` as mentioned in the first [comment](https://github.com/plasma-umass/coz/issues/193#issuecomment-1016513806) to the first issue above which didn't help.
- I got the idea to try the `dwarf-version` flag from `rustc -Cllvm-args="--help"`.
- I'm not sure if this is a case of user error since I'm oblivious to the inner working of rustc and I apologize in advance. I'm also not sure if what I'm trying to do is deliberately impossible and if so I might consider this an issue in the `rustc` help message informing of the option, rather than the code-generation.
- Minimal example [here](https://github.com/yehuthi/rustc_dwarf_version).

I'm on x86_64 Arch Linux and rustc 1.65.0-nightly (1d37ed661 2022-09-09).

**Comment by Urgau** [comment]
I believe setting the dwarf version with `-Cllvm-args` is not supported because `rustc` always sets the version in the LLVM-IR.

However there is a nightly flag [`-Zdwarf-version`](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/dwarf-version.html) to set the dward version.
You should be able to set version 3 like this: `-Zdwarf-version=3`.

**Comment by Urgau** [comment]
> Thanks @Urgau, `-Zdwarf-version=3` does seem to help it, 6 units have version 3, but most units still have versions 4 and 5:

This is probably because the one how are not at version 3 comes from the pre-compiled standard libraries. Those are not affected by your `-Zdwarf-version=3` and are compiled with the default settings.

> Is this an incorrect behavior for the flag or is it permissive towards the code-gen in this way?

I don't think it's a incorrect behavior because it's doing what you told him to do. Which is the compile the your crate and it's dependencies (if they are not already compiled, like for core, alloc, std, ...) with the flags your provide. So if one if these dependency has another dwarf version it will simply be merged with the other one.

---

If you compile the standard libraries yourself with `cargo` [`build-std`](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std) feature, you should have all the units with the correct dwarf version:
```
RUSTFLAGS="-Zdwarf-version=3" cargo +nightly -Zbuild-std build
```

NOTE: I have not tested this, I may be wrong.
