### ISSUE TITLE
E0477 triggered with current nightly

### ISSUE THREAD

**Issue by geeklint** [rust-lang/rust#101951]
I discovered that some code I had previously been using no longer compiles with the current nightly.  It gives E0477 which, as other issues have pointed out, is incorrectly described as "no longer emitted by the compiler".

### Code

[Link to Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4978275d01d9462b7fd8d5487350ccbb)

I expected to see this happen: *The code compiles successfully*

Instead, this happened: *I get this compiler error:*

```
error[E0477]: the type `PrettyCondo<'_>` does not fulfill the required lifetime
  --> src/lib.rs:41:5
   |
41 |     fn add_building(&mut self, _building: &mut PrettyCondo<'_>) {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: type must outlive the anonymous lifetime as defined here
  --> src/lib.rs:41:21
   |
41 |     fn add_building(&mut self, _building: &mut PrettyCondo<'_>) {
   |                     ^

For more information about this error, try `rustc --explain E0477`.
error: could not compile `e0477-test` due to previous error
```

### Result of cargo-bisect-rustc

searched nightlies: from nightly-2022-08-08 to nightly-2022-09-17
regressed nightly: nightly-2022-08-10
searched commit range: https://github.com/rust-lang/rust/compare/f03ce30962cf1b2a5158667eabae8bf6e8d1cb03...34a6cae28e7013ff0e640026a8e46f315426829d
regressed commit: https://github.com/rust-lang/rust/commit/63e4312e6bd50ec9859c363402209809fb8155d5

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 
```
</details>

**Comment by steffahn** [comment]
The error message behaves funny, too, with the ˋtype must outlive the anonymous lifetime as define hereˋ part. If you change the ˋimplˋ to use ˋadd_building<'s>(&'s self, ...)ˋ then it points to the next anonymous lifetime in the signature. If you change it to also use explitic ˋ&'t mut Pretty...ˋ in the second argument it points to the ˋ'_ˋ. Once you've eliminated all of the elided lifetimes, it points to the whole signature instead.

The problem seems to be related to the question whether or not there's an outlives-relation between the two elided lifetimes in ˋ&mut PrettyCondo<'_>ˋ or ˋ&mut <<T as ConstructionFirm>::Builder as BuilderFn<'_>>::Outputˋ. If all lifetimes are made explicit in the trait definition and impl, and there's an explicit outlives-relation in the trait definition and impl, then [the code compiles](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=015c9aff8ee575efda6ce7fc019625de).

Should be nightly regression, judging by the regressing commit, @rustbot label -regression-untriaged, +regression-from-stable-to-nightly.

Some more labels, @rustbot label A-lifetimes, A-traits, T-compiler

**Comment by inquisitivecrystal** [comment]
CC @lcnr as the author of the relevant PR.

**Comment by lcnr** [comment]
it's caused by this line:
https://github.com/rust-lang/rust/blob/503e19d01e941b88bf6d5b28e9108d046abcfa2d/compiler/rustc_typeck/src/check/compare_method.rs#L277

region check is also bad at dealing with ambiguity so it now fails because it probably has two "equally valid" assumed bounds to choose from, so it just chooses neither

going to look into this a bit deeper now

**Comment by inquisitivecrystal** [comment]
Assigning priority in accordance with [the discussion of the Prioritization Working Group](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23101951.20E0477.20triggered.20with.20current.20nightly/near/299365464).
