### ISSUE TITLE
LLVM ERROR since beta 1.65

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#102105]
### Code

```Rust
#![crate_type = "lib"]
#![feature(rustc_attrs)]

#[rustc_allocator]
pub fn allocator() -> *const i8 {
  std::ptr::null()
}
```

This code compiles fine with stable  `1.63.0 (4b91a6ea7 2022-08-08)` but with beta `1.65.0-beta.1 (2a65764f2 2022-09-19)` or nightly, you get an llvm error:

````
Attribute after last parameter!
ptr @_ZN41_0c34bf1b914b0e835c46e4f7f73be047514103529allocator17h7fb349a1bdaf661aE
in function _ZN41_0c34bf1b914b0e835c46e4f7f73be047514103529allocator17h7fb349a1bdaf661aE
LLVM ERROR: Broken function found, compilation aborted!
````

**Comment by nikic** [comment]
This is because your `allocator()` method has an invalid signature. For correct signatures, see https://github.com/rust-lang/rust/blob/46c59bbb79b3fa99950e2a7eaaeb161990561b8b/library/alloc/src/alloc.rs#L22.

At best, this is a diagnostics issue, if someone cares to improve diagnostics for an unstable, rustc-internal attribute.

**Comment by Nilstrieb** [comment]
closing as [wontfix](https://github.com/rust-lang/compiler-team/issues/620)
