### ISSUE TITLE
Bad codegen for array::map-based code

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#102202]
`array::map` results in a bad codegen compared to manually unrolled code. This issue can be demonstrated by the following code: https://rust.godbolt.org/z/T7bnTE398

Relevant issue: #86912

**Comment by newpavlov** [comment]
A more straightforward implementation of `array::map` makes codegen identical: https://rust.godbolt.org/z/a9csPcnob But it's unclear how to properly make it panic-safe in regards to `f`, i.e. we need a way to properly drop created `U`s after `f` has panicked.

**Comment by the8472** [comment]
We could special-case based on `needs_drop::<T>`?

**Comment by veber-alex** [comment]
There is another issue here, the simple `map` function produces very bad assembly on nightly.

**Comment by newpavlov** [comment]
@the8472 
No, I think we simply need something like [`ReadBuf`](https://doc.rust-lang.org/std/io/struct.ReadBuf.html) to track number of initialized elements. With no-drop types the additional code should get eliminated.

@veber-alex 
It looks like a clear nightly regression. I will open an issue for it.

**Comment by the8472** [comment]
> I think we simply need something like [ReadBuf](https://doc.rust-lang.org/std/io/struct.ReadBuf.html) to track number of initialized elements

The [Guard](https://github.com/rust-lang/rust/blob/master/library/core/src/array/mod.rs#L865-L868) type does just that. 
The thing is that the surrounding code is super-generic and relies heavily on the optimizer. That it runs on two loop conditions (`0..N` and `iter.next()`) probably doesn't help, LLVM is bad at optimizing that kind of thing.

**Comment by newpavlov** [comment]
I wrote [variation](https://rust.godbolt.org/z/MrrWGznPa) of the `Guard` and it properly compiles into expected assembly. Dunno what exactly makes the difference.

**Comment by InBetweenNames** [comment]
What would it take to get @newpavlov's variation upstreamed?  When dealing with vectorized code, it would be really nice to not have to unroll everything manually and use just use `map`.

**Comment by memoryruins** [comment]
Testing with `rustc 1.67.0-nightly (e1d819583 2022-12-05)`, the initial example using `<[T; N]>::map`  in `foo2` produces the same codegen as the manually unrolled code. Whichever change improved its codegen has not reached `beta` yet.

**Comment by HadrienG2** [comment]
array::map also isn't inline, while it is on the critical path of array::from_fn which itself often shows up in my profiles. I think it should be inline.

**Comment by newpavlov** [comment]
The code gets compiled into expected assembly on beta, so I think this issue can be closed? Or should we wait for 1.68 to be released?

@HadrienG2 
Can you provide a small example which would demonstrate this issue? I thought that because of monomorphization (`array::map` is generic over both `N` and `F`) `#[inline]` on generic functions is generally redundant.

**Comment by HadrienG2** [comment]
@newpavlov Monomorphization does not help you if two functions (which may be e.g. two instances of the same generic function) end up calling array::from_fn with the same callable. I'll roll out a little godbolt later, am on a phone right now.

**Comment by HadrienG2** [comment]
After struggling a while to reproduce this with godbolt, I realized that I couldn't because godbolt uses --emit-asm and --emit-asm forces codegen-units = 1, whereas this is a problem that requires multiple codegen units to reproduce.

So here's something that works locally:

1. Create a tiny lib with this code

```rust
#[inline(always)]
fn round_trip(input: [usize; 4]) -> [usize; 4] {
    let mut iter = input.into_iter();
    std::array::from_fn(|_| iter.next().unwrap())
}

pub fn make_array(input: [usize; 4]) -> usize {
    round_trip(input)[1]
}

pub fn make_array_again(input: [usize; 4]) -> usize {
    round_trip(input)[0]
}
```

2. Compile with multiple codegen units (I reproduced this with 16, but you probably need much less).

Although round_trip is correctly inlined, no inlining of the array::map inside array::from_fn is performed.

**Comment by HadrienG2** [comment]
I suspect the issue here might be that codegen-units splits code into compilation units based on how complex it is before optimization, whereas in the case of iterator-based code (or more generally from_fn or map with callables that use sufficiently complex optimizations), the code is pretty complex before optimization but will become very simple afterwards.

Which might explain why codegen-units tends to break "zero-cost abstractions" in my code unless inline is used very liberally in their implementation: these abstractions only turn into efficient code after optimization passes.

Resolving this true underlying issue that keeps biting me over and over again would be a largely separate issue that would require a mechanism to feed back information about compiled machine code to the compiler frontend so that in release mode + incremental builds, it can take more informed decisions about upfront splitting into codegen units. Think PGO, but without execution. That's likely very complex to implement though, so for now #[inline] on everything that should be a zero cost abstraction + transitively called functions is a Good Enough Hack.

**Comment by newpavlov** [comment]
I will close this issue, since the particular problem referenced by the OP got resolved on Beta (I assume by a newer LLVM version). But in some situations codegen for `array::map` can be still quite suboptimal as discussion here and the stack usage issue demonstrate.

@HadrienG2 
I think you should open a separate issue with request to add inline attributes on the methods.
