### ISSUE TITLE
`array::from_fn` behavior is unclear from documentation

### ISSUE THREAD

**Issue by jgao222** [rust-lang/rust#102609]
### Location

https://doc.rust-lang.org/std/array/fn.from_fn.html and https://doc.rust-lang.org/core/array/fn.from_fn.html

### Summary

The documentation for `from_fn` states
> Creates an array [T; N] where each array element T is returned by the cb call.
>
> Arguments
> - cb: Callback where the passed argument is the current array index.

It is not clear what "current array index" refers to, since the function description doesn't necessarily indicate that there is iteration happening to create the resulting array.

Additionally, the first line summary doesn't actually reflect the behavior of the function at all. It mentions "the cb call" -- as if there is only one call to `cb`.

I think would be more clear if the documentation somehow mentioned that the `i`-th element in the output array is the result of calling `cb(i)`.

The function `try_from_fn` is similarly unclear. Anyone have thoughts on this?

**Comment by vacuus** [comment]
I'm not sure if the `Arguments` section helps, since it separates the description of the callback somewhat. I think it should all be at the same visual level. Juxtaposing `T` next to "array element" also seems weird. How about:

Creates an array `[T; N]`, where each array element is the result of calling `cb` with that element's index.

(Maybe "returned value" instead of "result"?)

**Comment by vacuus** [comment]
I don't know about how best to document the type inference in the other issue (though, to throw my 2¢ in, I'm not sure it needs documentation :), but you raise a good point about `impl FnMut` and ordering. Assuming the guarantee of the order of arguments:

Creates an array of type `[T; N]`, where each element is the result of calling `cb` with that element's index. It is guaranteed that the index ranges from 0 to the end of the array.

Is "the end of the array" interchangeable with `N - 1`? Is `N - 1` clearer? I'm also unsure about explicitly mentioning the index 0 because of zero-length arrays. Instead of explicitly using numbers, maybe an analogue of iteration can be described. I'm not sure if accurately describing that can avoid expose implementation details and/or uninitialized memory, though.

**Comment by phimuemue** [comment]
> For example, this should probably get a guarantee of the _order_ in which the items are generated, since it takes `impl FnMut`, and a corresponding example, though additional guarantees like that take a libs-api sign-off.

I was just trying to find out if `from_fn` actually guarantees that the function is called with 0, 1, ..., N *in that order*. Is there currently any such guarantee? (It seems that for [`array::map`](https://doc.rust-lang.org/std/primitive.array.html#method.map) there is, and `from_fn` is afaik implemented in terms of `array::map`.)
