### ISSUE TITLE
internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by nowakf** [rust-lang/rust#102739]
Unfortunately, I can't reproduce the bug. I tried to create a minimal reproduction, but the compiler stopped crashing, even when I reverted the source to the state it was when it crashed.

Attached is rustc output, with RUST_BACKTRACE=1.

[compiler_bug.txt](https://github.com/rust-lang/rust/files/9725192/compiler_bug.txt)

**Comment by saethlin** [comment]
I am closing this because it is an incremental compilation ICE related to a component of rustc that has gotten a fair few tweaks recently; it is entirely possible that the root cause of this issue has been fixed.

If you see a crash like this again on Rust 1.70 or later please do not hesitate to open a new issue.
