### ISSUE TITLE
Better messages for `next` inside `for` loops

### ISSUE THREAD

**Issue by lylythechosenone** [rust-lang/rust#102972]
Given the following code: 
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=521fa77822c348df75f29034633aa31d)

```rust
fn main() {
    let mut chars = "HHeelllloo,,  wwoorrlldd!!".chars();
    for c in chars.by_ref() {
        print!("{}", c);
        chars.next(); // Skip next
    }
}
```

The current output is:

```
error[[E0499]](https://doc.rust-lang.org/stable/error-index.html#E0499): cannot borrow `chars` as mutable more than once at a time
 --> src/main.rs:5:9
  |
3 |     for c in chars.by_ref() {
  |              --------------
  |              |
  |              first mutable borrow occurs here
  |              first borrow later used here
4 |         print!("{}", c);
5 |         chars.next(); // Skip next
  |         ^^^^^^^^^^^^ second mutable borrow occurs here
```

Ideally the output should look like:

```
error[[E0499]](https://doc.rust-lang.org/stable/error-index.html#E0499): cannot borrow `chars` as mutable more than once at a time
 --> src/main.rs:5:9
  |
3 |     for c in chars.by_ref() {
  |              --------------
  |              |
  |              first mutable borrow occurs here
  |              first borrow later used here
4 |         print!("{}", c);
5 |         chars.next(); // Skip next
  |         ^^^^^^^^^^^^ second mutable borrow occurs here
 note: a for loop advances the iterator for you. The result is stored in `c`.
 help: if you want to call `next` within the loop, consider `while let`.
```
or similar. The note and/or help are both subject to changes, this is just a basic idea.
We could also conceivably rewrite the error message to expand on what the note says, like so:
```
error[[E0499]](https://doc.rust-lang.org/stable/error-index.html#E0499): cannot call `next` inside a for loop, as this results in two mutable borrows of `chars`.
 --> src/main.rs:5:9
  |
3 |     for c in chars.by_ref() {
  |              --------------
  |              |
  |              first mutable borrow occurs here
  |              first borrow later used here
4 |         print!("{}", c);
5 |         chars.next(); // Skip next
  |         ^^^^^^^^^^^^ second mutable borrow occurs here
 note: a for loop advances the iterator for you. The result is stored in `c`.
 help: if you want to call `next` within the loop, consider `while let`.
```

**Comment by lyming2007** [comment]
```
fn main() {
    let mut chars = "HHeelllloo,,  wwoorrlldd!!".chars();
    for c in chars.by_ref() {
        print!("{}", c);
        chars.next(); // Skip next
    }
}
```
It's hard to get 'c' in line 3 during the context where the compiler errors out the second mutable borrow message, because the mutable borrow happens between `chars.by_ref() and chars.next()`

**Comment by BGR360** [comment]
I don't think it's critical to mention `c` in the diagnostic. We shouldn't let the difficulty of doing that stop us from trying to improve the message.

@rustbot label +D-newcomer-roadblock

**Comment by lylythechosenone** [comment]
I'd love to try to fix this, but sadly I'm not familiar with the internals of rustc. If someone could point me towards the section where this error is, I could give it a try.

**Comment by BGR360** [comment]
Hi @lylythechosenone !

Whenever I try to dive into fixing a problem with rustc, I usually start with a search through the codebase. In this case, I'd search for strings that come from the error message: `"mutable more than once at a time"`, `"first mutable borrow occurs here"`, or `"second mutable borrow occurs here"`:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/13339928/201433824-0cbe3d1c-0ce0-4cc4-a002-da8313148914.png">

And that leads me to here:

https://github.com/rust-lang/rust/blob/7d85104b96fb2ffe7b638ffbfb1794ef5652bdcf/compiler/rustc_borrowck/src/borrowck_errors.rs#L36-L84

So then I'd use rust-analyzer to try to find all the usages of that method. In this case, turns out there's only one:

https://github.com/rust-lang/rust/blob/7d85104b96fb2ffe7b638ffbfb1794ef5652bdcf/compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs#L814-L830

And there we see that there is already some conditional suggestion being made; it calls `Self::suggest_split_at_mut_if_applicable`. And it seems there's a family of those `suggest_*_if_applicable`. So I think it would make sense to try to write your own `explain_iterator_advancement_in_for_loop_if_applicable` or something like that.

You'll need to figure out how to sort of "back track" from the MIR back to the HIR or the AST so you can figure out whether you're inside a `for` loop. I would study the code in `compiler/rustc_borrowck/src/diagnostics/` to try to figure out how to do that.

And don't forget to write a handful of regression tests in `src/test/ui/` somewhere, maybe in `src/test/ui/iterators/`: https://rustc-dev-guide.rust-lang.org/tests/ui.html

It might also be possible to perform this check at a higher level, say, in `rustc_hir_analysis`. If you can figure out that you're in a for loop, and that the user is trying to call `.next()` on the iterator, then you could raise the error then.
