### ISSUE TITLE
Expose task, and scheduler name information to debuggers

### ISSUE THREAD

**Issue by sstewartgallus** [rust-lang/rust#10302]
Currently, when debugging my heavily concurrent Rust program all I get is blanks in the name fields. It'd be really nice if my debugger could show the name I set using the task builder API.

This sort of relates to issue https://github.com/mozilla/rust/issues/2891?source=cc but is a different view on the topic.

CC @jdm

**Comment by vojtechkral** [comment]
@thestinger I had a look as to how this could be implemented and it's actually not so easy, as there is no POSIX-ly standard way to set a thread's name. All the *nixes do this in a bit different way with the most annoying one being OS X where you only can set the name from _within_ the thread and the function is only available since OS X 10.6. It seems Linux and BSDs are okay though.

Source: [this SO thread](https://stackoverflow.com/questions/2369738/can-i-set-the-name-of-a-thread-in-pthreads-linux).
