### ISSUE TITLE
regression: attributes on expressions are experimental

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#103244]
Seems like something about our detection here changed, doesn't look like the cases here *should* be errors at a glance.

* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/emily-signet.sleepyhead-kdl/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/mozilla.rust-parsepatch/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/sampersand.quest2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/over-0.6.5/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/parsepatch-0.2.9/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/rlxc-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/snapshots-0.2.8/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/cismute-0.1.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/vipers-2.0.6/log.txt

**Comment by ehuss** [comment]
This seems to be caused by #100232 (cc @cjgillot).

Here's a little repro:

```rust
macro_rules! foo {
    () => {
        #[allow(unreachable_patterns)]
        {
            123i32
        }
    };
}

fn main() {
    let _ = foo!().abs();
}
```

Technically the error is correct, the attribute is being used in an expression in this example. Due to the [strange rules](https://doc.rust-lang.org/nightly/reference/expressions.html#expression-attributes) for when attributes are allowed on expressions, I'm guessing that self was previously being rewritten to be an argument, which does allow attributes.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23103244.20regression.3A.20attributes.20on.20expressions.20are.20experimen.E2.80.A6)).

@rustbot label -I-prioritize +P-critical
