### ISSUE TITLE
regression: associated consts cannot be referenced in patterns

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#103242]
Really bad spans in all of these (not related to this bug, I expect), but still a pretty wide ranging regression.

* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/ChenYunShu-01.substrate-ink/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/MSghais.flat_contract_mmr/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/Mrhealer.erc20_rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/apemon.ink-amm-demo/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/forgetso.ink-events-debug/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/kmcodesdev.Increaser--Contract/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/ljl222.ink_erc20/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/marlowl.ink-voter-contract/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/accumulate-3.0.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/erc1155-3.0.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/erc721-3.0.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/flipper-3.0.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/incrementer-3.0.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/trait_erc20-3.0.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/zkink-0.0.1/log.txt

**Comment by boulanlo** [comment]
Hi! A bit new to Rust contributing, but I saw this got a "needs bisection" label and thought I'd try to help. I picked the crate from the last log in the list (`zkink`).

I've managed to run the `cargo-bisect-rustc` tool up to the actual nightly that regressed (`nightly-2022-09-09`), but couldn't go further due to weird download issues with the actual commits.

Here's the list of relevant commits the tool has found:
```text
found 9 bors merge commits in the specified range
  commit[0] 2022-09-07UTC: Auto merge of #101544 - matthiaskrgr:rollup-4urx917, r=matthiaskrgr
  commit[1] 2022-09-07UTC: Auto merge of #94075 - mikebenfield:wip-enum, r=oli-obk
  commit[2] 2022-09-08UTC: Auto merge of #101303 - jyn514:jnelson/handle-cycle-enum, r=cjgillot
  commit[3] 2022-09-08UTC: Auto merge of #101504 - lqd:rust-lld-fix, r=petrochenkov
  commit[4] 2022-09-08UTC: Auto merge of #101560 - Dylan-DPC:rollup-8m8yr89, r=Dylan-DPC
  commit[5] 2022-09-08UTC: Auto merge of #98900 - lcnr:region-stuff, r=jackh726
  commit[6] 2022-09-08UTC: Auto merge of #101467 - nnethercote:shrink-hir-Ty-Pat, r=spastorino
  commit[7] 2022-09-08UTC: Auto merge of #101577 - Dylan-DPC:rollup-l9xw7i7, r=Dylan-DPC
  commit[8] 2022-09-08UTC: Auto merge of #101437 - compiler-errors:erase-normalize-ordering, r=tmandry
```

Out of all of these, I think #98900 looks like the culprit the most, seeing it has something to do with associated consts. I may be wrong though, and I didn't investigate the actual error.

(I hope that I bisected correctly; since I am on NixOS, I've ran into some trouble getting patched executables when bisecting, and since I'm seeing a PR about lld in the commit list, I'm afraid I messed up somehow!)

**Comment by Mark-Simulacrum** [comment]
Cc @lcnr as author of #98900

**Comment by compiler-errors** [comment]
This is also fixed by #103243.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23103242.20regression.3A.20associated.20consts.20cannot.20be.20referenced.20.E2.80.A6)).

@rustbot label -I-prioritize +P-critical

**Comment by compiler-errors** [comment]
1.65 is released
