### ISSUE TITLE
`let_chains` introduces an error in move analysis 

### ISSUE THREAD

**Issue by mchernyavsky** [rust-lang/rust#103784]
The following code runs without errors:

```rust
fn main() {
    struct S;
    let x: Option<S> = Some(S);
    if let Some(s) = x { Some(s) } else { x };
}
```

But the following code produces an error:
```rust
#![feature(let_chains)]
fn main() {
    struct S;
    let x: Option<S> = Some(S);
    if let Some(s) = x && true { Some(s) } else { x };
}
```

```
error[E0382]: use of partially moved value: `x`
 --> src/main.rs:5:51
  |
5 |     if let Some(s) = x && true { Some(s) } else { x };
  |                 - value partially moved here      ^ value used here after partial move
  |
  = note: partial move occurs because value has type `S`, which does not implement the `Copy` trait
help: borrow this field in the pattern to avoid moving `x.0`
  |
5 |     if let Some(ref s) = x && true { Some(s) } else { x };
  |                 +++
```

I expected to see the same result for the second case because `&& true` part doesn't affect move analysis.

### Meta

`rustc --version --verbose`:
```
rustc 1.67.0-nightly (77e57db38 2022-10-30)
binary: rustc
commit-hash: 77e57db384aca99444c3b5f6a9c86bc58a804d89
commit-date: 2022-10-30
host: x86_64-apple-darwin
release: 1.67.0-nightly
LLVM version: 15.0.4
```

**Comment by wwylele** [comment]
I think this is expected behavior. 

First of all, the value of an expression, even known at compile time, shouldn't affect move analysis, so `&& true` and `&& black_box_bool()` should give the same analysis.

Then let's see `let Some(s) = x && black_box_bool()`. This chain can evaluate to `false` when `let Some(s) = x` is `true` but `black_box_bool()` is `false` (forget that you actually wrote `true` there, because again the value doesn't affect move analysis). In this case, `x` has already been moved into `Some(s)`, so it can't be used in the `else` branch.

**Comment by mchernyavsky** [comment]
@wwylele Thanks for the explanation!
