### ISSUE TITLE
The `Any` trait should not use virtual calls for type checks

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#10382]
These are slow and should be unnecessary. They are showing up in Servo profiles.

**Comment by Yoric** [comment]
If someone is willing to mentor me on this, I'd be interested in giving it a try.

**Comment by eddyb** [comment]
@Yoric It's a design problem, i.e. how do you represent the `TypeId` in `Any` such that it's a load of a vtable field?

I was going to go with "associated constant" a while back, but now that trait objects work by having the compiler implement `Trait` for `Trait`, with each method that is available (i.e. not those with `where Self: Sized`) forwarding through the vtable, there is a problem:

Anything that has to look up the vtable needs access to `self`, and this rules static methods and associated constants.
I would be happy with a compromise, such as `trait_object.CONST` which doesn't go through the `Trait` impl for `Trait` shim, but I doubt others would like that.

**Comment by Yoric** [comment]
Right, and I take it that we want to ensure that there is no vtable even when we don't monomorphize.

How would `trait_object.CONST` work? I may be missing something, but that looks much more like duck typing than any kind of polymorphism I have seen in Rust.

**Comment by eddyb** [comment]
> Right, and I take it that we want to ensure that there is no vtable even when we don't monomorphize.

I don't understand what you mean here. This issue is about avoiding a virtual call, not the entire vtable, which is necessary (and having `TypeId` as a field in the vtable is probably the best we can do).

> How would `trait_object.CONST` work? I may be missing something, but that looks much more like duck typing than any kind of polymorphism I have seen in Rust.

Assuming the following definition compiles, `Trait` should be object-safe:
```rust
trait Trait {
    fn method(&self) -> char;
    const CONST: char where Self: Sized;
}
```
Then one could imagine the vtable to also contain `CONST`, i.e.:
```rust
struct VtableForTrait {
    dtor: unsafe fn(*mut u8),
    size: usize,
    align: usize,
    method: unsafe fn(*const u8) -> char,
    // The above fields are present in current Rust, only CONST below is new:
    CONST: char
}
```

And let's add some impls:
```rust
struct A;
impl Trait for A {
    fn method(&self) -> char { 'A' }
    const CONST: char = 'A';
}
struct B;
impl Trait for B {
    fn method(&self) -> char { 'B' }
    const CONST: char = 'B';
}
```

`<Trait as Trait>::CONST` would still be missing, because there's no way to supply the actual trait object to get the original `CONST` value from the `impl` (of `Trait` for `A` or `B`, in this case).

Methods don't have this problem: we could call `method` via `trait_object.method()`, which is really sugar for `<Trait as Trait>::method(trait_object)`, and that will go through the vtable of `trait_object`.

However, we don't want the cost of calling a method through a vtable, especially if we can just load `CONST` instead, so what we're missing is a way to get `CONST` from `trait_object` (of type `&Trait`).

And what I'm proposing is to just use `trait_object.CONST`:
```rust
let trait_objects: [&Trait; 2] = [&A, &B];
assert_eq!(trait_objects[0].CONST, 'A');
assert_eq!(trait_objects[1].CONST, 'B');
```

**Comment by eddyb** [comment]
Thinking more about this, it's effectively a feature request for accessing constants on trait objects, or a similar feature, allowing `Any` to read a vtable field instead of calling a virtual method.

Therefore, I believe it belongs on the RFCs repo, as an issue in this form, or a fully fledged RFC.

cc @rust-lang/lang

**Comment by aturon** [comment]
@eddyb I agree. I'm actually working with @nikomatsakis on a related RFC in the near future :)

**Comment by Yoric** [comment]
> I don't understand what you mean here. This issue is about avoiding a virtual call, not the entire vtable, which is necessary (and having TypeId as a field in the vtable is probably the best we can do).

Sorry, I meant a virtual dispatch.

**Comment by Yoric** [comment]
I'm not up-to-date in how traits and vtables are represented, so please bear with me if I stumble upon this like a complete noob, but wouldn't it be as simple to somehow use the address of the vtable implementing `Any` as a typeid? If so, we could replace pure virtual `get_type_id` with an implementation uniform across all implementations of `Any`.

Or is this a problem because of @Kimundi 's [earlier comment](https://github.com/rust-lang/rust/issues/10382#issuecomment-28199846) on eliminating duplicate vtables?

**Comment by eddyb** [comment]
@Yoric we do not *and cannot* (AFAIK) deduplicate vtables to make that work.

**Comment by Yoric** [comment]
@eddyb Out of curiosity, how/when do we end up with vtables that would need to be deduplicated?

**Comment by eddyb** [comment]
@Yoric More than one crate. If you want to make it even more complicated, add generics that you monomorphize in different crates with different parameters.

**Comment by Yoric** [comment]
Right, that makes sense. In theory, a unique identifier per type could be deduplicated either at link-time or during startup, but I suspect that we want to do neither.

**Comment by nikomatsakis** [comment]
@eddyb another option would be to special-case this some, and just have all vtables include a `TypeId` -- or at least those that extend `Reflect` -- we could then use unsafe code to extract it. :)

**Comment by Yoric** [comment]
That doesn't sound very different from my suggestion, except for the mangling part.

**Comment by aturon** [comment]
Closing, since our preferred approach here would require [an RFC](https://github.com/rust-lang/rust/issues/10382#issuecomment-176484942).
