### ISSUE TITLE
Tracking Issue for `const_arguments_as_str`

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#103900]
Feature gate: `#![feature(const_arguments_as_str)]`

This is a tracking issue for const `fmt::Arguments::as_str`.
Note that the original PR didn't create a tracking issue.

### Public API

```rust
// core::fmt

impl<'a> Arguments<'a> {
    #[stable(feature = "fmt_as_str", since = "1.52.0")]
    #[rustc_const_unstable(feature = "const_arguments_as_str", issue = "103900")]
    pub const fn as_str(&self) -> Option<&'static str>;
}
```

### Steps / History

- [x] Implementation: #86655
- [x] Mention tracking issue in feature gate: #103901
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by RalfJung** [comment]
The function list in the issue description is outdated, this feature gate now also includes
```rust
impl<'a> PanicMessage<'a> {
    pub const fn as_str(&self) -> Option<&'static str>;
}
```
(For some reason I can't edit the issue description...)

@rust-lang/libs-api  Given that this has been regular-stable for a while, is there any reason not to make them const-stable as well? The implementations are trivial, and in fact they are already indirectly exposed on stable via the const panic machinery (specifically, it gets called in `const_panic_fmt`).

The main reason not to do this is that these functions cannot be actually called in `const fn` since you can't construct `Arguments`/`PanicMessage` in const context.  But if that's the argument then IMO we should turn this into an internal feature gate that doesn't need a tracking issue (and `PanicMessage::as_str` can be fully de-constified).

**Comment by dtolnay** [comment]
>  these functions cannot be actually called in `const fn` since you can't construct `Arguments`/`PanicMessage` in const context.

This is usually not a compelling counterargument because `const` is still relevant for cases like:

```rust
const fn f(thing: Option<&Arguments>) {
    ...
    if let Some(thing) = thing {
        thing.as_str() ...
    }
    ...
}
```

and not having `const` on `as_str` can necessitate needlessly complicated workarounds.

@rust-lang/libs-api: this feature requires making the commitment that future designs of `core::fmt::Arguments` will not involve putting the string message from `format_args!("...")` behind a virtual function call, as in `pub struct Arguments<'a> { repr: &'a dyn FmtRepr<'a> }`.

@rfcbot fcp merge

**Comment by RalfJung** [comment]
> this feature requires making the commitment that future designs of core::fmt::Arguments will not involve putting the string message from format_args!("...") behind a virtual function call, as in pub struct Arguments<'a> { repr: &'a dyn FmtRepr<'a> }.

Or if we do add such an indirection then it has to be `dyn const FmtRepr` or so -- something like that could conceivably exist.

**Comment by RalfJung** [comment]
Stabilization PR is up: https://github.com/rust-lang/rust/pull/132511
