### ISSUE TITLE
Suboptimal code generated for `<[u32]>::ends_with` for RISC-V

### ISSUE THREAD

**Issue by eduardosm** [rust-lang/rust#104166]
The following code
```rust
pub fn f(x: &[u32]) -> bool {
    x.ends_with(&[0])
}
```

compiles to the following assembly:
```
example::f:
        beqz    a1, .LBB0_2
        slli    a1, a1, 2
        add     a0, a0, a1
        lbu     a1, -3(a0)
        lbu     a2, -4(a0)
        lb      a3, -1(a0)
        lbu     a0, -2(a0)
        slli    a1, a1, 8
        or      a1, a1, a2
        slli    a2, a3, 8
        or      a0, a0, a2
        slli    a0, a0, 16
        or      a0, a0, a1
        seqz    a0, a0
        ret
.LBB0_2:
        li      a0, 0
        ret
```
where the latest value from the slice is read byte-by-byte, as it would do for an unaligned read.

Godbolt link: https://godbolt.org/z/WKvhr58Yn

**Comment by nikic** [comment]
Looks like no alignment gets inferred on the bcmp arguments, and even if it did, it doesn't get preserved during SDAG lowering: https://github.com/llvm/llvm-project/blob/e4889c0a046e251bfaf27a637df606112659be89/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp#L7975

Though I believe this particular problem is already fixed in LLVM 16, because the RISCV data layout was changed to `n32:64`, which means that u32 is now considered a legal integer and this will get expanded by InstCombine already.

**Comment by eduardosm** [comment]
Optimal code is generated since Rust 1.70

```
example::f:
        beqz    a1, .LBB0_2
        slli    a1, a1, 2
        add     a0, a0, a1
        lw      a0, -4(a0)
        seqz    a0, a0
        ret
.LBB0_2:
        li      a0, 0
        ret
```
