### ISSUE TITLE
`#[derive(Copy)]` isn't quite right for types with PhantomData<T>

### ISSUE THREAD

**Issue by rickwebiii** [rust-lang/rust#104264]
Rust's `#[derive(Copy)]` doesn't appear to work quite correctly under types using `PhantomData`. Consider the following code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6b845765dc255630b63c4a3227674749)):

```rust
use std::marker::PhantomData;

#[derive(Clone, Copy)]
pub struct Nope<T> {
    _phantom: PhantomData<T>
}

pub struct Inner {}

fn foo(a: Nope<Inner>) {
    foo(a);
    foo(a);
}
```

gives the following error:
```
error[[E0382]](https://doc.rust-lang.org/stable/error-index.html#E0382): use of moved value: `a`
  --> src/lib.rs:12:9
  error[[E0277]](https://doc.rust-lang.org/nightly/error-index.html#E0277): the trait bound `T: Clone` is not satisfied
 --> src/lib.rs:8:9
  |
8 | impl<T> Copy for Nope<T> {}
  |         ^^^^ the trait `Clone` is not implemented for `T`
  |
note: required for `Nope<T>` to implement `Clone`
 --> src/lib.rs:3:10
  |
3 | #[derive(Clone)]
  |          ^^^^^
note: required by a bound in `Copy`
  = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider restricting type parameter `T`
  |
8 | impl<T: std::clone::Clone> Copy for Nope<T> {}
  |       +++++++++++++++++++
```

Manually implementing `Copy` and `Clone` seems to [work](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5dc0ee00456a8ae1ccdbe792b88422f9).

Making `Inner` `Copy + Clone` appears to work.

Possibly related, this snippet [fails](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=67ed0b33a7ac44cb40165e94b47ea49b) as well:
```rust
use std::marker::PhantomData;

#[derive(Clone)]
pub struct Nope<T> {
    _phantom: PhantomData<T>
}

impl<T> Copy for Nope<T> {}

pub struct Inner {}

fn foo<Inner>(a: Nope<Inner>) {
    foo(a);
    foo(a);
}
```

It complains that the `Nope<T>` doesn't implement `Clone`, despite using `#[derive()]` to do so.

### Meta

Repros on playground nightly.

**Comment by BGR360** [comment]
This is because the code that rustc generates for your derived `Clone` and `Copy` impls is:

```rust
impl<T: Clone> Clone for Nope<T> {
    #[inline]
    fn clone(&self) -> Nope<T> {
        Nope {
            _phantom: self._phantom.clone(),
        }
    }
}

impl<T: Copy> Copy for Nope<T> {}
```

This is generally how the derives work for any type with generic parameters. So I hesitate to call this a bug.

In fact, I might even call it a feature of `PhantomData`. Much of the usefulness of `PhantomData<T>` comes from the fact that it makes your type behave as if it contained a field of type `T`.

If you just want `PhantomData` so you can have an unused generic parameter, and not because you want the type to act like it has a field of that type, then I do believe the thing you have to do is manually implement the traits.

@rustbot label -C-bug

I'm taking the bug label off this. If you like, you can relabel it as a `C-enhancement` and put it under the `A-diagnostics` category if you think there's a better error message we could show here.

**Comment by jhpratt** [comment]
Duplicate of #26925.

**Comment by rickwebiii** [comment]
@jhpratt Given this is a dup, I'll close as not planned. Thanks!
