### ISSUE TITLE
Remove allow(rustc::potential_query_instability) in rustc_trait_selection

### ISSUE THREAD

**Issue by CastilloDel** [rust-lang/rust#104212]
Related to https://github.com/rust-lang/rust/issues/84447, https://github.com/rust-lang/rust/pull/103723 and https://github.com/bluss/indexmap/issues/242

`rustc_trait_selection` still has some potential query instabilities, however, trying to remove them caused regressions. This issue tracks this problem after https://github.com/rust-lang/rust/pull/103723 was merged. The idea is to wait until the `drain_filter` method is eventually added to `IndexMap` which would make the change easier and hopefully solve the regression.

**Comment by ndrewxie** [comment]
Correct me if I'm wrong, but the only place I see `drain_filter` being used on the `map` field of `ProvisionalEvaluationCache` is the following piece of code:

`for (fresh_trait_pred, eval) in
    self.map.borrow_mut().drain_filter(|_k, eval| eval.from_dfn >= dfn)
{
    debug!(?fresh_trait_pred, ?eval, "on_completion");
}`

This looks like it could just be replaced with a .retain, right? Because debug doesn't *need* to own the value

**Comment by ndrewxie** [comment]
Alright this appears to be resolved - can someone please close this issue? Thanks! (I messed up the wording of the PR and didn't link the issues properly)

**Comment by jyn514** [comment]
Sure thing, glad you got this working :)
