### ISSUE TITLE
UB in arc_from_vec_opt test

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#104565]
Miri reports UB in the new `arc_from_vec_opt` test:

```
  0.145300   test arc::arc_from_vec_opt ... error: Undefined Behavior: `ptr_offset_from` called on pointers into different allocations
  0.000096      --> alloc_miri_test/../library/alloc/tests/arc.rs:222:13
  0.000025       |
  0.000018   222 |             arc.as_ptr().cast::<u8>().offset_from(addr),
  0.000016       |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `ptr_offset_from` called on pointers into different allocations
  0.000016       |
  0.000016       = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
  0.000016       = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
  0.000016       = note: BACKTRACE:
  0.000143       = note: inside `arc::arc_from_vec_opt` at alloc_miri_test/../library/alloc/tests/arc.rs:222:13
  0.000020   note: inside closure at alloc_miri_test/../library/alloc/tests/arc.rs:215:23
  0.000007      --> alloc_miri_test/../library/alloc/tests/arc.rs:215:23
  0.000008       |
  0.000007   214 | #[test]
  0.000006       | ------- in this procedural macro expansion
  0.000007   215 | fn arc_from_vec_opt() {
  0.000007       |                       ^
```
On first sight, the error seems legitimate.

That test got added in https://github.com/rust-lang/rust/pull/104205.
Cc @clubby789

**Comment by RalfJung** [comment]
Probably what happens is that in Miri, `Global.shrink` will always move the data to a new allocation, and then the way the test checks whether that happened causes UB. You should not call `offset_from` unless you are already 100% sure that both pointer point to the same allocation -- and in this case, you cannot be sure of that, since allocators do not promise that `shrink` keeps the same allocation.

In fact, it might be the case that even if `shrink` succeeds, the allocation has a new provenance -- it is considered a new allocation at the same location, but all old pointers are invalid now and must be 'refreshed'. I recall this was discussed somewhere at some point but forgot where... Cc @rust-lang/wg-unsafe-code-guidelines

**Comment by RalfJung** [comment]
> In fact, it might be the case that even if shrink keeps the data in-place, the allocation has a new provenance

Yeah, the C standard is quite explicit about this, so for now we should follow suit. Opened https://github.com/rust-lang/rust/pull/104568.

**Comment by clubby789** [comment]
Might it be a good idea to `cfg(not(miri))` the pointer comparison itself, so that Miri can check the actual implementation, even if it can't check the final assertion.

I did suspect that other platforms might not have this behaviour - #104563 seems to show this. It might be best to feature gate the test and opt to only platforms with allocators that work like this.

**Comment by RalfJung** [comment]
Yes, but to be clear there are two bugs here:
- the test can fail in some platforms, such as Miri, when realloc doesn't shrink in-place
- the test has UB on *all* platforms

**Comment by clubby789** [comment]
Is the `v.as_ptr().addr()` comparison still UB? I'm currently working on a patch that
- Uses the `.addr()` cast for comparison
- Turns off this feature for non-GNU targets (since that's the only one I know for sure has the shrink-in-place behaviour)
- Disables the test on non GNU, and the *comparison* itself on Miri

With that in mnd though, I'm wondering if this opt should just be removed entirely. The perf wins I got in testing were pretty small for the amount of maintenance headache this seems likely to cause

**Comment by RalfJung** [comment]
`addr()` returns regular integers, you can compare them in whatever way you want.
