### ISSUE TITLE
rustdoc --json output format, crate.paths does not contain all items

### ISSUE THREAD

**Issue by makspll** [rust-lang/rust#104651]
https://github.com/rust-lang/rust/issues/76578

### Code

Running 
`$ rustup run nightly-2022-11-20 cargo rustdoc -p bevy_asset@0.9.0  --  -Zunstable-options --output-format json`
generates a json file whose `paths` mapping does not contain many of the internal structures such us:
AssetPathId, SourcePathId, HandleId, LabelId etc.

Not sure if this is intended, but without this mapping there is no way as far as I am aware to retrieve the original import paths to these things.

### Version it worked on
nightly-2022-08-01

### Version with regression
nightly-2022-11-20

**Comment by GuillaumeGomez** [comment]
Do you have a minimized example of the regression by any chance?

**Comment by Enselic** [comment]
> Not sure if this is intended, but without this mapping there is no way as far as I am aware to retrieve the original import paths to these things.

Due to re-exports, a single item can have many paths. And the path to the "real" item may be inaccessible behind a private mod. To learn about all the paths to an item, you must traverse the items from the root. You must also take into account renames (`pub use foo as bar`).

If you want to look at (one way) of doing that you can look at https://github.com/Enselic/cargo-public-api/blob/main/public-api/src/item_processor.rs

The `paths` structure is something that will be removed long term. Because it is not really useful. It contains internal paths, and only one path. Long term, all items shall be part of the `index`. And the items you mention are already part of the `index` I think? You can check with `cargo public-api`:

```
$ cargo install cargo-public-api
$ rustup install nightly
$ git clone https://github.com/bevyengine/bevy.git ; cd bevy
$ cargo public-api -p bevy_asset  | grep AssetPathId
[...]
pub struct bevy_asset::AssetPathId(_, _)
[...]
```

`cargo public-api` parses the rustdoc JSON, so if `cargo public-api` finds an item, it is part of rustdoc JSON.

**Comment by makspll** [comment]
Hmm, thanks everyone, it seems that there is a way then to retrieve import paths which I am happy with. Closing and will re-open if there are any issues with this.

**Comment by GuillaumeGomez** [comment]
Maybe we could provide some methods in the `rustdonc-json` crate to make it easier for our users to get this information?

**Comment by makspll** [comment]
That would be very useful indeed, for context I use these to import structures for which I am generating wrappers

**Comment by GuillaumeGomez** [comment]
Then please open another issue (linking to this one) with a short example of your problem so we can provide you a function to make it easier. ;)

**Comment by Enselic** [comment]
@GuillaumeGomez I think you meant to say "the [`rustdoc-types`](https://crates.io/crates/rustdoc-types) crate" rather than "the [`rustdoc-json`](https://github.com/Enselic/rustdoc-json/issues/1#issue-1465461591) crate", right?

@makspll The "source" for `rustdoc-types` is here: https://github.com/rust-lang/rust/tree/master/src/rustdoc-json-types.

**Comment by GuillaumeGomez** [comment]
Yes absolutely. Sorry, confused the names.

**Comment by Boscop** [comment]
@makspll Hm, how can I actually output the JSON to stdout?
If I try `cargo +nightly rustdoc -- --output-format json -Z unstable-options -o -`, it says:
> error: Option 'out-dir' given more than once

**Comment by makspll** [comment]
Hi @boscop I don't think you can, since the command hooks into the compiler and runs per crate it puts the output in the target folder

**Comment by Boscop** [comment]
@makspll But only one output json file is being produced.
So why can't it output to stdout instead of to this one JSON file (?)

**Comment by aDotInTheVoid** [comment]
@Boscop I think it might not be possible to output to stdout when invoking cargo via rustdoc. Consider opening a new issue for this.

Also: please don't use unrelated issues for questions like this. It's less likely to be seen, and makes this issue much harder to read.
