### ISSUE TITLE
The dependencies of the backtrace crate in libstd are outdated.

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#104960]
`library/std/Cargo.toml` contains:
```
addr2line = { version = "0.16.0", optional = true, default-features = false }
miniz_oxide = { version = "0.4.0", optional = true, default-features = false }
```

`library/backtrace/Cargo.toml` has:
```
addr2line = { version = "0.17.0", default-features = false }
miniz_oxide = { version = "0.5.0", default-features = false }
```

(and current master of the backtrace-rs repo has even different versions)

It seems to me backtrace should have its own rustc-dep-of-std feature, which would avoid libstd enabling the feature on stale dependencies.

It's worth noting that the dependencies in `crates/as-if-std/Cargo.toml` in backtrace-rs match what's currently in libstd, although I'm not sure what that's testing considering there is no dependency on the backtrace crate in there...

**Comment by bjorn3** [comment]
> It seems to me backtrace should have its own rustc-dep-of-std feature, which would avoid libstd enabling the feature on stale dependencies.

rustc-dep-of-std wouldn't work for backtrace. It isn't used as regular dependency, but directly included in libstd using `#[path = "../../backtrace/src/lib.rs"] mod backtrace_rs;`. This is necessary because backtrace depends on libstd for reading files, while libstd depends on backtrace for the `std::backtrace` module and for panic messages. To break this cyclic dependency both have been merged into the same crate. `crates/as-if-std` emulates the same inclusion mechanism outside of libstd to test that it doesn't break.

**Comment by MoskalykA** [comment]
Hi, is this exit no longer valid? The two dependencies have the same version on both Cargo.toml 
https://github.com/rust-lang/backtrace-rs/blob/4245978ca8169c40c088ff733825e4527f7b914c/Cargo.toml#L40
https://github.com/rust-lang/rust/blob/2f5e6bb817c115c067ff47453eb9aa89a0a31358/library/std/Cargo.toml#L28

**Comment by workingjubilee** [comment]
Effectively resolved, yes. Will be fully resolved by https://github.com/rust-lang/rust/pull/113176
