### ISSUE TITLE
PGO example in `rustc` book not operational with the new `llvm-profdata-15`?

### ISSUE THREAD

**Issue by SkBlaz** [rust-lang/rust#105178]
Hello `rustc` community,

first of all, great work with the compiler, works really well + is super robust. I've recently tested the [Profile-guided optimization example](https://doc.rust-lang.org/rustc/profile-guided-optimization.html); where, however, I encountered some issues. Specifically, the main sample reads as:

```
# STEP 0: Make sure there is no left-over profiling data from previous runs
rm -rf /tmp/pgo-data

# STEP 1: Build the instrumented binaries
RUSTFLAGS="-Cprofile-generate=/tmp/pgo-data" \
    cargo build --release --target=x86_64-unknown-linux-gnu

# STEP 2: Run the instrumented binaries with some typical data
./target/x86_64-unknown-linux-gnu/release/myprogram mydata1.csv
./target/x86_64-unknown-linux-gnu/release/myprogram mydata2.csv
./target/x86_64-unknown-linux-gnu/release/myprogram mydata3.csv

# STEP 3: Merge the `.profraw` files into a `.profdata` file
llvm-profdata merge -o /tmp/pgo-data/merged.profdata /tmp/pgo-data

# STEP 4: Use the `.profdata` file for guiding optimizations
RUSTFLAGS="-Cprofile-use=/tmp/pgo-data/merged.profdata" \
    cargo build --release --target=x86_64-unknown-linux-gnu

```

On Ubuntu 20, the first issue I encountered was there was no `llvm-profdata` available as such. After installing the LLVM via the [suggested route](https://apt.llvm.org/) I observed there are `llvm-profdata-15` and `llvm-profdata-10`. Upon running 

```
RUSTFLAGS="-Cprofile-generate=/tmp/pgo-data" cargo build --release

..some runs with the obtained binary follow..
```

I see that `pgo-data` contains a bunch of `*.profraw` files, which seems expected. To use this in the final compilation step, as

```
# create a single merge - this works fine with no warnings
llvm-profdata-15 merge -o /tmp/pgo-data/merged.profdata /tmp/pgo-data;

# re-compile with the file above
RUSTFLAGS="-Cprofile-use=/tmp/pgo-data/merged.profdata" cargo build --release
```

However, I'm getting the 

```
warning: /tmp/pgo-data/merged.profdata: unsupported instrumentation profile format version
```

Is this a known issue? Am I doing something apparent wrong here? Appreciate the help, thanks!

**Comment by SkBlaz** [comment]
Wondering if `lpo` related (true in my case)

**Comment by lqd** [comment]
My understanding is that one should use the same `llvm-profdata` as the LLVM version used by rustc. Therefore, not installing via apt, but using `llvm-profdata` from the rustup `llvm-tools` component of the given release. The system LLVM may have a different profiling format, and that could sometimes not work.

Since CI does PGO on x64 linux, it also serves as a test to ensure it still works, which is why it'd be surprising if it regressed this way without anyone noticing.

---

And after writing the above, I looked at the documentation you linked and that's indeed the preferred way of doing it described there as well. 

Can you try it this way and report back ?

**Comment by SkBlaz** [comment]
It appears llvm alignment was indeed the issue.  Closing this, thanks once more!
