### ISSUE TITLE
Vec::split_off could be dangerous.

### ISSUE THREAD

**Issue by bigspider** [rust-lang/rust#105297]
Hello, as I'm still a Rust beginner, I apologize if the issue is known, or void for some reason I don't yet see.

I read in the documentation of [Vec::split_off](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.split_off):

> Splits the collection into two at the given index.
> 
> Returns a newly allocated vector containing the elements in the range [at, len). After the call, the original vector will be left containing the elements [0, at) with its previous capacity unchanged.
> 

I think this is a potentially dangerous default behavior. I would expect a Vector implementation to guarantee the following in its default usage (that is, when not explicitly tampering with the _capacity_):
- The amortized update cost is O(1) per element
- The memory occupation is O(n) _in the worst case_

The behavior of `split_off` of leaving capacity unchanged (instead of _possibly_ shrinking it according to the default capacity management strategy) doesn't allow to _guarantee_ both the above properties at the same time:
- splitting off all-but-the-first element permanently leaves a large, unused capacity. If this action is repeated on the remaining elements, this could leave O(n^2) memory occupation on a program with O(n^2) running time, instead of O(n) memory occupation.
- if the programmer realizes the problem, they might think that calling `shrink_at_capacity` is a solution, and it indeed solves the memory issue − but it now becomes O(n^2) to split-off elements in small chunks (say, one by one).

In fact, it doesn't seem that there is a way of triggering the shrinking strategy after `split_off` (except hacks like pushing and popping a dummy element), so one might have to avoid using it completely.
The reason I think the default behavior is especially dangerous is that realizing the problem in a real program requires non-trivial algorithmic thinking, and it only happens _in the worst case_, e.g. it might not be detected until some malicious crafted input is fed to the program.

**Comment by workingjubilee** [comment]
Per `Vec<T>`'s documentation:
> `Vec` will never automatically shrink itself, even if completely empty. This ensures no unnecessary allocations or deallocations occur. Emptying a Vec and then filling it back up to the same [`len`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.len) should incur no calls to the allocator. If you wish to free up unused memory, use [`shrink_to_fit`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.shrink_to_fit) or [`shrink_to`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.shrink_to).

To shrink may cause significant performance penalties, as most allocators do significant memory management on freeing (which "reallocate to smaller" is akin to), so as to minimize the work done to allocate. In some contexts, costing additional time is also "dangerous". However, neither is meaningfully "dangerous" in terms of Rust's language semantics.

I do not think we will be changing `Vec`'s longstanding operational intent that has been part of its API documentation since Rust 1.0, so please use a different type if you want something that doesn't have this clause. And please take discussion (as opposed to bug reports) to another forum like https://internals.rust-lang.org/
