### ISSUE TITLE
Broken MIR in encoding_rs related to MIR inlining + DestProp

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#105428]
This was originally https://github.com/rust-lang/rust/issues/105344#issuecomment-1340153677

---

Trying to compile https://github.com/hsivonen/encoding_rs `5931e21bc20bad0335964f441da0c4309401107a` with these flags:
```
$ RUSTFLAGS="-Zmir-opt-level=3 -Zvalidate-mir -Zinline-mir=yes" cargo +nightly test
```

Produces this:
```
error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:1315 ~ encoding_rs[5e1f]::utf_16::{impl#0}::decode_to_utf16_raw), const_param_did: None }) (before pass SimplifyCfg-final) at bb218[0]:
                                encountered overlapping memory in `Call` terminator: _454 = bswap::<u16>(move _454) -> bb163
  --> src/utf_16.rs:85:21
   |
85 |                     dest.copy_utf16_from::<LittleEndian>(&mut source)
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:784:26
```

Removing `-Zinline-mir=yes` or `-Zmir-opt-level=3` removes the ICE.

---

searched nightlies: from nightly-2022-01-01 to nightly-2022-12-05
regressed nightly: nightly-2022-11-28
searched commit range: https://github.com/rust-lang/rust/compare/80a96467ec5675e9f69683b5c075a8b15950c341...1eb62b1235fd77200e6bd967d70e83c0f2497233
regressed commit: https://github.com/rust-lang/rust/commit/0e9eee68111ec742c3d60bb96078994c494a59fb

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --script script --start 2022-01-01 --end 2022-12-05 
```
</details>

**Comment by RalfJung** [comment]
@tmiasko I am trying to understand what happened here. The test case added in https://github.com/rust-lang/rust/pull/105420 looks like maybe the analysis done by DestProp is smart enough to ignore dead code and that's why it can introduce UB in dead code?

However the code at the top of this issue looks quite different. Looking at [it's source](https://github.com/hsivonen/encoding_rs/blob/c19edf7f9e942f8a746b8c053a343bfef2387ca6/src/utf_16.rs#L85), I can't see how ignoring dead code would lead to introducing overlapping calls?
