### ISSUE TITLE
std::io::copy should take Read and Write traits by value

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#105643]
This was suggested by @alexcrichton [way back in 2015](https://github.com/rust-lang/rust/pull/27531#issuecomment-128047127):
```Rust
mod std::io {
    fn copy<R: Read, W: Write>(r: R, w: W) -> io::Result<u64> { ... }
}
```

but it wasn't done as it regressed 3 (root) crates in a crater run. Still, ideally if the API breakage policy is ever revisited, it would be better to take `Read` and `Write` by-value, as a type impl'ing `Read` transmits this property to `&mut` references of it.

@rustbot label T-libs-api rust-2-breakage-wishlist

**Comment by est31** [comment]
For the libs team meeting, see #111063 with crater runs for the suggested change as well as my [analysis of the results](https://github.com/rust-lang/rust/pull/111063#issuecomment-1537192835).

**Comment by dtolnay** [comment]
The proposed change breaks reborrows. For example in the following code:

- https://github.com/Byron/gitoxide/blob/24dcba44abbea979aec609274d4327ab61f18048/gix-config/src/file/includes/mod.rs#L88-L102

the error is:

- https://github.com/rust-lang/rust/pull/111063#issuecomment-1530534617

because against the current `copy` signature, the following is a **reborrow** of `buf`:

```rust
let buf: &mut Vec<u8> = ...;
io::copy(..., buf)?;  // IMPLICIT REBORROW equivalent to `&mut *buf`

// buf remains usable here
```

whereas in the proposed new `copy` signature it is a **move** of `buf`.

As far as I know, there is no inherent reason it has to be this way. If you have `fn old_copy<W: ?Sized + Write>(w: &mut W)` and `fn new_copy<W: Write>(w: W)`, then `old_copy::<Vec<u8>>` and `new_copy::<&mut Vec<u8>>` have the same signature. Both of them take an argument of type `&mut Vec<u8>`. One could imagine wanting Rust's reborrow behavior to be identical between these two identical signatures. I don't currently know any reason that it would be a breaking change to perform reborrowing for both.

For now the crater breakages are beyond where I think we can push this change through. But if a future smarter borrow checker is able to do reborrows for an argument of type `&mut T` even when the formal parameter's type is a generic type, then I would love to reconsider this change at that point.

@rfcbot fcp close
