### ISSUE TITLE
Missing ICE info after some compiler panics

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#105637]
Several panic messages changed recently:
* With the panic in #105632, the output now ends immediately after the stack trace. The information about how to report an ICE is missing, and the query stack is also missing.
* With the panic in #105321, the output now includes "panic in a function that cannot unwind"

### Missing output example

As an example, here's the post-stack-trace output when testing #105632 with an older build:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-nightly (657eefe2d 2022-12-11) running on x86_64-apple-darwin

query stack during panic:
#0 [typeck] type-checking `bar`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
```

</details>

### Regression

Seems to be a regression from bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4 (#103647) (@lqd)

### Version

```
rustc 1.68.0-nightly (bdb07a8ec 2022-12-11)
binary: rustc
commit-hash: bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4
commit-date: 2022-12-11
host: x86_64-apple-darwin
release: 1.68.0-nightly
LLVM version: 15.0.6
```

**Comment by jruderman** [comment]
Requesting prioritization because affects the quality of bug reports and may interfere with bisection.

@rustbot prioritize

**Comment by compiler-errors** [comment]
@jruderman do you test on an x86_64 mac? otherwise, I'm curious how you bisected this to #103647.

**Comment by jruderman** [comment]
Yes, this is all on x86_64 mac.

**Comment by lqd** [comment]
I'm not sure why this would affect ICEs so I've posted the https://github.com/rust-lang/rust/pull/105646 revert to allow time for some investigation.

**Comment by lqd** [comment]
This issue isn't platform-specific, and happens on all nightlies built with ThinLTO:
- on x64 mac, via #103647 starting with nightly-2022-12-12 (being reverted in #105646)
- on x64 msvc, via #103591 starting with the same nightly-2022-12-12
- on x64 linux, via #101403 starting with nightly-2022-10-24, and which lands on stable 1.66 in 2 days. 

Examples:

1. On the most recent nightlies, where ThinLTO is enabled on the main targets above: #105632 linked in the OP

```rust
#![feature(associated_const_equality)]
#![allow(dead_code)]

trait TraitWAssocConst {
        const A: usize;
}

fn foo<T: TraitWAssocConst<A = 1>>() {}

fn bar<T: TraitWAssocConst<A = 0>>() {
        foo::<T>();
}

fn main() {}
```

And we can see [on the playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=dee83dd38dd8f284fdb4c48df4eeb9db) that the usual ICE post-trace output is missing.

Note that this ICE was not present on `nightly-2022-10-24`, and is most useful for bisecting on win/mac, not linux: the following example should be usable for that.

2. An ICE whose existence crosses the #101403 linux merge date, so you can see the above and after (this ICE happens in 1.66 and is fixed in 1.67): #103748

```rust
struct Apple((Apple, Option(Banana ? Citron)));

fn main() {}
```

We can see the ICE is missing the post trace output on the current beta (1.66.beta.2) [on the playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=46a6cc9c7184fd3ac1fde1736cc0b26e), and the output changed in `nightly-2022-10-24`, it is present in `nightly-2022-10-23`.

---

Since this is useful output for reporting issues, debugging and bisection, should we do something about ThinLTO landing on stable on linux in 2 days (e.g. disabling `rust.lto=thin` on the x64 linux dist builder on beta) ? I'm not sure anyone will have the time to investigate and land a fix by then.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23105637.20Missing.20ICE.20info.20after.20some.20compiler.20panics)).

@rustbot label -I-prioritize +P-critical

**Comment by lqd** [comment]
https://github.com/rust-lang/rust/pull/105800 should fix the `-Zdylib-lto` bug causing this issue, so we shouldn't need to revert the `rust.lto = thin` config on the dist builders.

**Comment by Nilstrieb** [comment]
Can this be closed now?

**Comment by lqd** [comment]
Probably. The fix has landed on nightly and beta, but the PR is still stable-nominated. It's not really critical to do such a backport unless someone experiences issues on 1.66 or the triage WG sees too many bug reports they don't like.

**Comment by apiraino** [comment]
As @lqd says - the stable backport was discussed but ultimately kept "[on hold](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-12-22/near/317389918)" to see how the patch behaves in the beta channel. A stable backport sometimes means a point release and that's up to `T-infra` to decide.

Ok if you prefer to close this issue, we can always re-open *if* a stable backport will be approved (that will be discussed probably next week)

**Comment by jyn514** [comment]
This is several months old at this point, I think it's safe to say there won't be a stable backport 😄
