### ISSUE TITLE
--edition should tell what the default edition is

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#106041]
rustc --edition: `error: Argument to option 'edition' missing`

rustc --edition=help: ``error: argument for `--edition` must be one of: 2015|2018|2021|2024. (instead was `help`)``

rustc --help

````
        --edition 2015|2018|2021|2024
                        Specify which edition of the compiler to use when
                        compiling code.
````

The default is not mentioned anywhere. I assume it is 2015?

**Comment by fmease** [comment]
The default is indeed 2015. It should probably not only mention the default (2015) but also the latest *stable* edition (2021).

**Comment by jyn514** [comment]
Mentoring instructions: modify https://github.com/rust-lang/rust/blob/65a6e22668c32c81dbe6a996a7012270c01eb114/compiler/rustc_session/src/config.rs#L1345 to include `DEFAULT_EDITION` and `LATEST_STABLE_EDITION` somewhere.

**Comment by sigaloid** [comment]
What is the best way to insert the values for `DEFAULT_EDITION` and `LATEST_STABLE_EDITION` into the string? `opt::opt_s` only takes `&'static str`'s and I don't see an easy way to create one while inlining those variables. Neither `concat!` nor `format!` works - former only accepts literals rather than the static variable, and the latter would create a &str, but then drop a temporary variable.

I don't believe it would be a good idea to simply write the value of these variables into the string, so I'm wondering what other options I have. However, if that's the way forward, I can do so.

**Comment by jyn514** [comment]
> `opt::opt_s` only takes `&'static str`'s

Where does that requirement come from? Seems fine to loosen it.

**Comment by jyn514** [comment]
ah I see, the string ends up stored in RustcOptGroup.

Honestly, given that this is only used once and the string is tiny, using `Box::leak` seems fine.
