### ISSUE TITLE
Typo "probihibited"

### ISSUE THREAD

**Issue by irww** [rust-lang/rust#106018]
### What needs to be fixed?
Typo "probihibited"

### Page(s) Affected
https://docs.rs/icu/latest/icu/collator/struct.CollatorOptions.html

**Comment by compiler-errors** [comment]
@Manishearth shouldn't this be filed against icu4x? I'm not understanding why you transferred this to rust-lang/rust.

**Comment by Manishearth** [comment]
@compiler-errors oh, because it was filed on rust-lang/www.rust-lang.org, and when i see someone file a bug that has an obvious docs link in it i immediately transfer here (you cannot transfer across org anyway). It's pretty common for people to file bugs in the stdlib docs on the website repo.

I have no idea why someone filed a bug about _ICU4X_ on the repo for the _rust_ website.

**Comment by Manishearth** [comment]
For some reason ICU4X got two PRs with typo fixes and this issue filed way out in a completely different repo in the span of 2 hours, I have no idea why.
