### ISSUE TITLE
Tidy should detect unreachable modules in `compiler/`

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/rust#106206]
We shouldn't probably ever have unreachable modules in `compiler/`, so we should implement a tidy lint against them. 

Would've probably caught some super stupid module file duplications that happened due to a failed module rename (twice!!) in 3b9daac6a27159bbe08e39fbc2722f40e91941d7, resulting in the clean-up PR: #106205

**Comment by obeis** [comment]
@rusbot claim

**Comment by Mark-Simulacrum** [comment]
Ultimately a fix here is very likely to look like https://github.com/rust-lang/rust/issues/28711, which is a long-standing bug. I'm not sure scoping to just compiler/ helps here.

I think it makes sense to close this in favor of that issue since any implementation ought to at least aim to address the full scope, even if it falls short (as many tidy lints do).
