### ISSUE TITLE
Rustdoc reports non accessable items in blocks with `--document-private-items`, even with `#[doc(hidden)]`

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#106373]
```rust
#![allow(unused_macros, dead_code)]

#[doc(hidden)]
const _: () = {
    macro_rules! stry {
        () => {};
    }

    struct ShouldBeHidden;

    impl Bar for Foo {
        fn bar(&self) {
            struct SHouldAlsoBeHidden;
        }
    }
};

pub struct Foo;

pub trait Bar {
    fn bar(&self);
}
```

Produces with `rustdoc +nightly src/lib.rs --document-private-items`

![image](https://user-images.githubusercontent.com/28781354/210250888-4f2617d8-a528-4279-8439-2cd2e55a6e9f.png)

which erroniously includes `stry`, `ShouldBeHidden`, and `ShouldAlsoBeHidden`.

Stable (1.66.0) gets this right

![image](https://user-images.githubusercontent.com/28781354/210250823-ebfc2081-8385-424e-93db-34e4f6402e88.png)

It's debatable what the semantics of `--document-private-items` should be for items in blocks without `#[doc(hidden)]` [^me], but here, we're just wrong.

We also can't just ignore all items in `#[doc(hidden)]` blocks, as this would break a load of users, eg serde.

[*Zulip Discussion*](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Bad.20output.20for.20.60nightly_rustc.60.20crates)

[^me]: FWIW, I think they should still be hidden, as their not accessible outside the block.

Probably, caused by #104889, cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Tricky indeed. I see two ways of handling this problem:

1. Hide all items inside the block: if we pick this way, then how to unhide items which are declared into a block like this if you only want to hide the "block owner" and not the items in the block.
2. Keep the current behaviour and only hide items which have `#[doc(hidden)]` and their direct children, therefore excluding blocks since they're not children of the item.
