### ISSUE TITLE
Low memory footprint vector

### ISSUE THREAD

**Issue by MeirShpilraien** [rust-lang/rust#106586]
Hey,

I am working on refactoring some of our C code into rust, one of the components that I am currently replacing is our [trie](https://en.wikipedia.org/wiki/Trie) implementation. I found out that the rust implementation I am building is consuming much more memory. One of the reasons is that the rust Vector size and capacity are both usize (I used vector to save the children list in each node in the trie so it is widely used and consuming a lot of memory). The thing is that the children list can not grow to more than 256 values so it would be enough to use u8 to save the size and the capacity.
I can implement such a vector myself in my project but I was wondering if you will accept a PR and add it to the standard library? If you will, I will be happy yo take :).

**Comment by NobodyXu** [comment]
>  I can implement such a vector myself in my project but I was wondering if you will accept a PR and add it to the standard library? If you will, I will be happy yo take :).

Not rust contributor here, the process of adding a new api to stdlib is:
 - Open a PR to https://github.com/rust-lang/libs-team
 - Open a PR to rust-lang/rust implementing the feature as unstable
 - Once the previous two steps are done and the previous step is merged, you can request for FCP from the libs-team to stablise the features

However, I don't think you PR will be merged in since it's not very general and often don't bring much value.

If the users know that `Vec::size` is less than `u8::MAX`, then they can simply use `u8` to store index instead of `usize`.

For `Vec<T>`, using `u8` to store size/cap instead of `usize` would instead reduce size from 24B to 16B on 64bit platform and from 12B to 8B on 32bit platform, but that doesn't seem like a lot unless you really create a lot of `Vec`.

**Comment by the8472** [comment]
> I can implement such a vector myself in my project but I was wondering if you will accept a PR and add it to the standard library?

There's a bunch of crates like that already. So an argument would have to be made about the benefits of having this in the standard library. Considering that there are many ways to skin this cat (various size types, inline storage for very small values, thin vs. fat  vecs, tradeoffs around niches etc.) I'm skeptical.

**Comment by Dylan-DPC** [comment]
Closing this as it's not really a feature request and better off to start with a crate and then see how things can be taken from there.
