### ISSUE TITLE
Implement `Hash` for `HashSet` and `HashMap` if `Hash + Ord` are implemented for the key type

### ISSUE THREAD

**Issue by not-my-profile** [rust-lang/rust#106901]
I think it would make sense to add the following implementations to the standard library:

```rs
impl<T: Hash + Ord> Hash for std::collections::hash_set::HashSet<T> { ... }

impl<K: Hash + Ord, V: Hash> Hash for std::collections::hash_map::HashMap<K, V> { ... }
```

What do you think of that idea?

**Comment by Nilstrieb** [comment]
This can't really be implemented well. The naive implementation would be to iterate over all the entries and hash them, but this would be wrong. Since their iteration order is unspecified sets/maps with the same entries (that are equal according to their `PartialEq` and `Eq` impl) could have different hashes, violating the contract for `Hash`.
You would need a way to hash them all in a defined order, which `HashMap` and `HashSet` do not have.
[`BTreeMap`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#impl-Hash-for-BTreeMap%3CK%2C%20V%2C%20A%3E) does have a `Hash` implementation since its iteration order is well-defined.

**Comment by not-my-profile** [comment]
Did you miss the `Ord` requirement I mentioned in the issue title and the code block?

**Comment by Nilstrieb** [comment]
That would require extra allocations, which seems pretty surprising in a `Hash` implementation.

**Comment by not-my-profile** [comment]
Ah yes ... good call :) Closing this.

**Comment by tavianator** [comment]
Java's `Set`/`Map` specify that the `hashCode()` is the sum of the hashes of the entries, which ensures that the iteration order doesn't affect the result.  It's too bad that trick doesn't really work with Rust's `Hash`/`Hasher` interface.  This hacky approach could work though:

```rust
impl<T: Hash> Hash for std::collections::hash_set::HashSet<T> {
    fn hash<H: Hasher>(&self, state: &mut H) {
        let mut sum = 0_u64;
        for item in self {
            let mut hasher = DefaultHasher::new();
            item.hash(&mut hasher);
            sum = sum.wrapping_add(hasher.finish());
        }
        state.write_u64(sum);
    }
}
```

Hardcoding `DefaultHash` is unfortunate though.  It would be nice if we had `trait Hasher: Default` or something.
