### ISSUE TITLE
Unclear example in io::Error

### ISSUE THREAD

**Issue by jbaublitz** [rust-lang/rust#106937]
### Location

The unclear example is located [here](https://doc.rust-lang.org/std/io/struct.Error.html#method.kind).

### Summary

I originally interpreted this example to mean that constructing an error from a raw error code always resulted in `ErrorKind::Uncategorized`. I think it might help to be explicit that no error has occurred yet and that is the reason that this shows up as uncategorized.

**Comment by amab8901** [comment]
can you give us a running example to help us reproduce the issue?

**Comment by jbaublitz** [comment]
I've never reported a doc issue before. Can you clarify what you mean by a running example? Do you mean the command to build the docs highlighted in the link?

**Comment by workingjubilee** [comment]
The variant is `#[doc(hidden)]`, I assume quite deliberately. There is an argument that we should not be mentioning it in the documentation at all. It certainly is confusing, I agree.

**Comment by ChrisDenton** [comment]
To summarise the above points, the relevant part of the example is the following:

```rust
fn main() {
    // Will print "Uncategorized".
    print_error(Error::last_os_error());
```

This is weird for two reasons:

* `Uncategorized` is hidden and unstable.
* It's not actually defined what happens when calling `last_os_error()` without first calling an OS function that failed (this will be highly system specific or may even be affected by pre-main shenanigans but will likely be a success code, hence `Uncategorized`).

Maybe the example could use `from_raw_os_error` with a note that the returned kind will depend on how that error code is interpreted by the OS.
