### ISSUE TITLE
[performance][windows][stdio] `write_valid_utf8_to_console` should almost certainly call `MultiByteToWideChar`

### ISSUE THREAD

**Issue by strega-nil-ms** [rust-lang/rust#107092]
(and similarly, `read_u16s()` should call `WideCharToMultiByte`)

Windows provides these nice functions which performantly implement utf-8 <-> utf-16 conversions. We should probably call them in the standard library when possible.

**Comment by the8472** [comment]
Do we get measurable performance wins that make calling more unsafe C APIs worth it? Especially with the inlining barrier across languages.
And I would assume console printing is bottlenecked on the console rendering part anyway, not on string conversions.

**Comment by ChrisDenton** [comment]
Do we have any good benchmarks for console I/O perf?

**Comment by the8472** [comment]
A simple main writing 100MB worth of lines to std and measuring the time it takes should do?

**Comment by ChrisDenton** [comment]
For sure. I was just wondering if we had something already. I mean, we'd probably want to be testing a few different languages as well to make sure we're not just optimizing for ASCII.

**Comment by the8472** [comment]
I don't think we do because most benchmarks suppress console output.

**Comment by strega-nil-ms** [comment]
I did do a benchmark, and interestingly, ASCII text was about twice as fast with `MultiByteToWideChar` as with rust-native code; however, Chinese text was slightly slower. Given that most of the actual cost of printing to the screen is in the actual printing, I no longer think it's a good idea to do this.

See benchmarks at [strega-nil/rust-bench-cvt-utf8-utf16][].

[strega-nil/rust-bench-cvt-utf8-utf16]: https://github.com/strega-nil/rust-bench-cvt-utf8-utf16

**Comment by the8472** [comment]
Just to check my understanding: The utf16 conversion only happens when one writes to an actually rendered console. There isn't some stuff like virtual consoles that act more like NUL where speeding up the conversion could help because the data will be discarded by the OS. And output to file is binary anyway.

**Comment by ChrisDenton** [comment]
There are now (since Windows 10, 1809) [pseudo consoles](https://learn.microsoft.com/en-us/windows/console/pseudoconsoles) which are consoles without the rendering part. Though the intent would be for the rendering to be implemented by another program, it would also be possible to skip or delay (e.g. by writing a log) rendering.

**Comment by the8472** [comment]
In that case a speedup may be useful, but is the optimization potential of the built-in conversion already squeezed dry?

**Comment by strega-nil-ms** [comment]
Mmh, thanks @ChrisDenton! I'll also push some benchmarks for testing other cases later, since there are plenty of other cases than just "bulk-converting a bunch of text". Thanks!

Nicole
