### ISSUE TITLE
#[macro_export(hello, world)]

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/rust#107231]
I tried this code:

```rust
#[macro_export(hello, world)]
macro_rules! foo {
    () => {}
}
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=9c40221c498bdc99beb7022d53fdb086

I expected to see this happen: it shouldn't compile

Instead, this happened: it compiles

### Meta

`rustc --version --verbose`:
```
N/A
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by fmease** [comment]
For anyone who would like to work on this, the following code needs to be extended to check if the meta-item list is empty or the identifier `local_inner_macros` (i.e. only allowing the attribute to be `#[macro_export]` and `#[macro_export(local_inner_macros)]`:

https://github.com/rust-lang/rust/blob/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/compiler/rustc_passes/src/check_attr.rs#L2010

Due to backward compatibility concerns, probably only a *future-incompat warning* should be issued if the verification fails.

@rustbot label A-attributes

**Comment by blyxyas** [comment]
First rust-lang/rust contribution I hope this goes well
