### ISSUE TITLE
rustdoc: decrease SEO rank of integer modules / deprecated items

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#107579]
Is there anything that can be done to decrease the SEO rank of deprecated pages? The impetus for this was linking to deprecated `std` modules such as numbers:

![image](https://user-images.githubusercontent.com/13724985/216189306-f63a60ca-47dd-45ef-8672-dc81a8a70c0e.png)

but it is likely worth doing for `docs.rs` as well if not too difficult. I am unsure whether there is a separate repo dedicated to the infrastructure of `docs.rust-lang.org` (please direct me if so) but figured any discussion here would also be valid there.

cc @jsha since you seem to be the resident expert based on rust-lang/docs.rs#1438

This parallels https://github.com/rust-lang/rust/issues/98759 for internal rustdoc sorting. Relevant zulip thread: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Deprecation.20of.20std.3A.3Au32.20shells

**Comment by jsha** [comment]
One small and easy tweak would be to remove the deprecation-TBD warning from the [_modules_](https://doc.rust-lang.org/src/core/num/shells/u64.rs.html#13) but keep it on [the constants](https://doc.rust-lang.org/src/core/num/shells/int_macros.rs.html#41). Per the Reddit thread above it seems like the deprecation notice for the _modules_ may be causing the most confusion, because it causes a warning to show up in the parent page (https://doc.rust-lang.org/std/#modules).

**Comment by tgross35** [comment]
Thanks for putting all the context together. I linked your comment in #107587, the PR where we can discuss changes on the lib side some more.

I think that from your answers here I've gleaned that there's not much that can be done on the SEO side of things, neither for numbers specifically nor for anything else deprecated. So I think this is good to close (woohoo! 8858 open issues instead of 8859!)
