### ISSUE TITLE
Inner closure move in function call does not move outer values

### ISSUE THREAD

**Issue by nvzqz** [rust-lang/rust#107623]
I tried this code:

```rust
struct Func<F>(F);

fn new_func<F: Fn()>(f: F) -> Func<F> {
    Func(f)
}

fn main() {
    let s: String = "hola".to_owned();

    let outer = new_func(move || {
        let inner = move || println!("{s}");
        inner()
    });
}
```

I expected to see this happen: construct a `Func<impl Fn()>` that owns the `String` in the `inner` `Fn`.

Instead, this happened:

```
error[E0507]: cannot move out of `s`, a captured variable in an `Fn` closure
  --> src/main.rs:11:21
   |
8  |     let s: String = "hola".to_owned();
   |         - captured outer variable
9  |
10 |     let outer = new_func(move || {
   |                          ------- captured by this `Fn` closure
11 |         let inner = move || println!("{s}");
   |                     ^^^^^^^            -
   |                     |                  |
   |                     |                  variable moved due to use in closure
   |                     |                  move occurs because `s` has type `String`,
   |                     |                  which does not implement the `Copy` trait
   |                     move out of `s` occurs here
```

Note that this works fine when removing the `Fn` bound from `new_func` or changing `Fn` to `FnOnce`. However, this is not a sufficient substitute because I do not want to expose type internals nor do I want to change the `Fn` bound at the callsite.

This also works when binding `inner` outside and moving it into `outer`:

```rs
let inner = move || println!("{s}");
let outer = new_func(move || inner());
```

However, this is also not a sufficient substitute.

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0 (69f9c33d7 2022-12-12)
binary: rustc
commit-hash: 69f9c33d71c871fc16ac445211281c6e7a340943
commit-date: 2022-12-12
host: aarch64-apple-darwin
release: 1.66.0
LLVM version: 15.0.2
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by erikdesjardins** [comment]
Closures are values, so in the following:

```rs
let s: String = "hola".to_owned();

let outer = new_func(move || {
    let inner = move || println!("{s}");
    inner()
});
```

a new `inner` closure is constructed, and then dropped; and hence `s` is moved into `inner`, and then dropped, every time `outer` is called. Since `s` can only be moved once, `outer` must be `FnOnce`.

This is a fundamental part of how closures work. I doubt it can be changed.

---

Consider these edge cases as well:

In the following code (which compiles today if `outer` is `FnOnce`), what would happen under the proposed semantics? Presumably we can't move `s` twice, into both closures, in order to perform the captures up front.

```rs
let s: String = "hola".to_owned();

let outer = move |cond| {
    if cond {
        let inner = move || println!("{s}");
        inner()
    } else {
        let inner = move || println!("{s}");
        inner()
    }
};
```

In the following code, `inner2` depends on `val`, which is not present when `outer2` is constructed. What happens then?

```rs
let s: String = "hola".to_owned();

let outer2 = move |val| {
    let inner2 = move || println!("{val} {s}");
    inner2()
};
```

**Comment by jieyouxu** [comment]
Triage: no recent discussions, closing as inactive.
