### ISSUE TITLE
Is an invalid value immediately replaced considered a produced value?.

### ISSUE THREAD

**Issue by axos88** [rust-lang/rust#107791]
### Location

https://doc.rust-lang.org/reference/behavior-considered-undefined.html

### Summary

This may be a bit hair-splitting, but what do we consider *produced* in `Producing an invalid value, even in private fields and locals. `?. There seem to be a lot of confusion and fear around this topic, and it's unarguably better to avoid more code than to hit UB because we did not avoid a case, it would be better to be as precise as possible to prevent actions based on fear rather than facts.

Do we consider a value that is first initialized as invalid, and then overwritten with a valid value as soon as possible, but provably before it is accessed?

I firmly believe that writing a bunch of bytes to a memory area that is overwritten without access to it cannot influence the behaviour of the program, and shouldn't be considered a produced value at all. Guaranteeing that it is not accessed is another thing and undoubtedly a can of worms, but the clarification would be welcome nonetheless, so that UB could be better understood and constrained.

I agree that this is a VERY dangerous area, but with the necessary attention and guarantees, 

Does the following code actually trigger UB, with the following restrictions:

   * Please, no suggestions on how this should be done to avoid this arguably gray-area, I'm interested in the actual answer to this case, both from a theoretic and a practical point of view.
  * No code accesses the GLOBAL_MUT variable before main runs.
  * When main runs, code still runs on a single thread, on a single CPU (embedded environment)
  * No interrupts, signals or alike can interrupt the first unsafe block, it is executed atomically.
  * All futher accesses to GLOBAL_MUT will be reads (although this is unimportant, since all accesses must be unsafe {} anyways)
  * https://www.ralfj.de/blog/2020/07/15/unused-data.html was an interesting read, however that still covers the case when seemingly unused memory might actually be used due to compiler optimizations. In this case that cannot happen, as AFAIK accesses CANNOT be moved through an assignment. (So any accesses happening after an assignments can only be rearranged to happen after the reassignment).
  * Possibly another rewrite of this without using the MaybeUninit API, just returning uninitialized memory in the static definition.
  * Can the intermittently produced invalid value actually influence the behaviour of the compiler or the resulting binary and trigger UB, provided that the invalid value is never actually read, and it is overwritten as soon as the entry point code finishes running, and calls main? Can something I never know about influence me?
```

#![feature(const_size_of_val)]
#![feature(const_ptr_write)]

static mut GLOBAL_LAZY_MUT: MyStructThatCannotBeInitiedInConst = unsafe {
    // Copied from MaybeUninit::zeroed() with minor modifications, see below
    let mut u = MaybeUninit::uninit();

    let bytes = mem::size_of_val(&u);
    write_bytes(u.as_ptr() as *const u8 as *mut u8, 0xA5, bytes); //Trick the compiler check that verifies pointers and references are not null.

    u.assume_init() //Or replace the whole thing with some other method of producing an invalid value in const-time.
};

(...)

fn main() {
    // First instruction in main, atomic execution.
    unsafe {
        let mut v = MyStructThatCannotBeInitiedInConst::new();
        libc::memcpy(&mut v as *mut _, &mut GLOBAL_LAZY_MUT as *mut _, mem::size_of_val(&v)); 
        mem::forget(v);
    }
}
```

See this discussion here: https://users.rust-lang.org/t/is-this-ub-or-not/88739/15

**Comment by ChrisDenton** [comment]
> There seem to be a lot of confusion and fear around this topic, and it's unarguably better to avoid more code than to hit UB because we did not avoid a case, it would be better to be as precise as possible to prevent actions based on fear rather than facts

I think the docs here accurately represents the current rules. "Produced" means what it says. Using (or potentially using) a value does not enter into the equation at all. You can't make values that are invalid for the type. That's the simple, unambiguous, rule. If people do temporarily want invalid values then they have to explicitly indicate that using a wrapper type. 

Maybe one could argue for more complicated rules here. But, as you say, it's better to make it easier for people to avoid UB. Having complicated rules with tricky exceptions would be harder for people to follow. Having one simple rule with one simple get out clause is much easier.

**Comment by workingjubilee** [comment]
> Producing an invalid value, even in private fields and locals. "Producing" a value happens any time a value is assigned to or read from a place, passed to a function/primitive operation or returned from a function/primitive operation.

I am pretty sure "Any time a value is assigned to **or** read from a place" means what it says. I am curious what you think would make this more precise?

> I firmly believe that writing a bunch of bytes to a memory area that is overwritten without access to it cannot influence the behaviour of the program, 

I believe this is a point of disagreement between you and Rust. From the perspective of Rust, the value _is_ used. It's used to write a bunch of bytes to a location in memory.

Consider this similar program: [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=61bc8d803d12bbd874a422efba9068e6). I picked some details and replaced `memcpy` with `copy_nonoverlapping`.

Nonetheless, trying to compile it gets an error:
```
error[[E0080]](https://doc.rust-lang.org/nightly/error-index.html#E0080): it is undefined behavior to use this value
  --> src/main.rs:26:1
   |
26 | static mut GLOBAL_LAZY_MUT: MyStruct = unsafe {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value at .some_bits.<enum-tag>: encountered 0xa5, but expected a valid enum tag
   |
   = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
   = note: the raw bytes of the constant (size: 1, align: 1) {
               a5                                              │ .
           }
```

That UB would _materialize a problem_ is not what UB means. UB means what happens next is not defined. This _may_ be used to justify compiler optimizations, but it's not much different from a CPU instruction that leaves some FLAGS register in an undefined state after execution, according to the ISA designer. Maybe the architecture's implementer will pick a value, or maybe it switches values on boot. Maybe it changes for reasons not even the implementer is aware of, as it wasn't tested for. It was not defined, so you can no longer rely on it.

But in this case, according to current understanding of UB, since your example is visible during compilation, a valid Rust compiler may opt to replace your program with `ud2`, `halt`, or a similar instruction, as a courtesy, since it immediately triggers UB. From time to time, LLVM likes to do this.

**Comment by axos88** [comment]
Well, to be fair it also states that `the rules on what exactly is undefined behavior aren't clear, so this check might be overzealous.`, and the error message states that it is undefined behaviour to **use** this value. But it's not used, which the compiler is probably unable to verify.

**Comment by workingjubilee** [comment]
You perform assignment by defining the last value in the `static`'s block expression to be an invalid value that you use `.assume_init()` on. Assignment is producing the value. To "use" need not be to read it again, and the fact that it is a `static` definitionally makes it available to read from pretty much anywhere in the program. In fact, if it is a fully `pub static`, you no longer are aware of what programs are reading it or when it is read.

Yes, if you replace the CPU with one that is incredibly constrained, even by embedded standards, as many embedded CPUs nowadays support RTOS which allow interleaving programs, or are fully multicore, and then _never link in any other code_ which also accesses the same symbol, you can still be confident that no one else will read it. But Rust's semantics are designed to enable local instead of global reasoning, including enabling program composition. Thus, we have two choices. Either we make all `static mut` also implicitly `MaybeUninit<T>`, or we put the responsibility of initializing a valid type on you, the one initializing it in the first place. As anyone can simply write `static mut NAME: MaybeUninit<T>` if that is what they meant, it seems unreasonable to put the burden of proving the `unsafe` is correct on the reader.

**Comment by workingjubilee** [comment]
Ah, I almost missed it. You also use the value by giving it to `mem::forget`. Yes, it removes things and doesn't drop them, but a valid implementation of `mem::forget` is currently, as I understand things:

```rust
pub fn forget<T>(forgetting: T) {
    if forgetting.is_magically_determined_to_be_ub() {
        // SAFETY: But of course, this will never happen.
        // ...or will it?
        unsafe { summon_nasal_demons!() }
    };
}
```

If you have something about the above you wish to be clarified, please go ahead and ask, but at least in that forum thread you mentioned, I do not think there is "a lot of confusion and fear around this topic", merely confidence in different views. They also mention the [Const UB RFC](https://rust-lang.github.io/rfcs/3016-const-ub.html) which explicitly says that if this is UB at const time then it is simply UB and running the program is not required: the compiler may immediately emit nasal demons.

For the specific example I offered, it should probably not say "this check might be overzealous" since, as I understand it, defining that behavior would destroy several other optimizations like the null-pointer optimization, so it is probably correct to change the diagnostics in this case.

**Comment by axos88** [comment]
Thanks for all the input
