### ISSUE TITLE
Breaking change in macro_rules ty fragment parsing in version 1.68

### ISSUE THREAD

**Issue by zakarumych** [rust-lang/rust#107796]
I tried this code:

```rust
macro_rules! impl_primitive {
    ($ty:ty) => { impl_primitive!(impl $ty);};
    (impl $ty:ty) => { fn a(_: $ty) {} }
}

impl_primitive! { u8 }
```
[link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=57f5abcdf559eb5655565be8bb7f49a2)

I expected to see this happen:
Macro is expanded to `fn a(_: u8) {}`

Instead, this happened:
On stable `1.67` it works as expected.
On beta `1.68` and nightly `1.69` it fails with the following error

```
error: expected a trait, found type
 --> src/lib.rs:6:19
  |
2 |     ($ty:ty) => { impl_primitive!(impl $ty);};
  |      ------ while parsing argument for this `ty` macro fragment
...
6 | impl_primitive! { u8 }
  |                   ^^
```

It is probably caused by `ty` fragment that now treats `impl` as a start of `impl Trait` type.
So makes sense. But breaks existing code :)

**Comment by compiler-errors** [comment]
searched nightlies: from nightly-2022-06-01 to nightly-2023-02-01
regressed nightly: nightly-2023-01-18
searched commit range: https://github.com/rust-lang/rust/compare/4781233a77e879e49cb5ce3c98d2abba6a6ade7a...3984bc5833db8bfb0acc522c9775383e4171f3de
regressed commit: https://github.com/rust-lang/rust/commit/85357e3e2ed5f4ae4760d4418bbeab9985a784aa

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --access github --timeout 30 --start 2022-06-01 --end 2023-02-01 --regress error 
```
</details>


I think I see where the issue is, I'll fix it.

@rustbot claim

**Comment by apiraino** [comment]
IIRC issues with a backport pending should stay open to track the backport process (not 100% sure tho)

**Comment by apiraino** [comment]
beta backport in https://github.com/rust-lang/rust/pull/108037
