### ISSUE TITLE
Why does a function local variable grow up the stack？Are there any advantages to this design？

### ISSUE THREAD

**Issue by zc24** [rust-lang/rust#107825]
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/61010755/217695426-16775f4e-e1d0-402b-8edb-723b3081ee8d.png">

**Comment by workingjubilee** [comment]
This is a cute code-size optimization by LLVM.
Note that if you add another argument, we get more expected output ([Godbolt](https://rust.godbolt.org/z/b1MqacjYE)):
```asm
example::main:
        sub     rsp, 12
        mov     dword ptr [rsp], 1
        mov     dword ptr [rsp + 4], 2
        mov     dword ptr [rsp + 8], 3
        add     rsp, 12
        ret
```

So this is all normal, really. LLVM is avoiding using the red zone, here, for reasons I am not sure of (perhaps debuggability, since `-Cdebuginfo=2`? Nothing even gets emitted otherwise...). LLVM here is using `push rax` because it has a shorter encoding by 1 byte (since it's just the opcode byte, and not an opcode + the ModR/M byte) than "move the stack pointer down by an immediate", and because the contents of `rax` aren't important (but are probably 0, atm) for "move the stack down 8 bytes".
