### ISSUE TITLE
`.\x fmt std` panics

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rust#107944]
Doing `x test std` will run the std's tests.

Doing `x fmt std` results in:

```
thread 'main' panicked at 'entry failed with std: The system cannot find the file specified. (os error 2)', format.rs:257:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Doing `x fmt library/std` works but I expected `fmt` to work similarly to `test`.

**Comment by jyn514** [comment]
Fixing this for std isn't hard, but fixing it in a general way is somewhat tricky because we don't have Steps to look at for `format`. I think we should only support shortcuts for directories, and only three directories deep to avoid making the search too expensive (I picked three so that tools in src/tools will be supported).

Relevant code: https://github.com/rust-lang/rust/blob/d0940161283216ade541946474c759621b6997c5/src/bootstrap/format.rs#L198

**Comment by jieyouxu** [comment]
I would like to give this a try
@rustbot claim
