### ISSUE TITLE
Intrinsics like `_mm_undefined_si128` should clarify what "undefined" means to them

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#107945]
When these were added to clang, they apparently meant `undef` in the LLVM sense.  But it sounds like they were later changed to just be zero'd <https://github.com/llvm/llvm-project/issues/31524#issuecomment-980975545>.

It would be good for those methods and the related types (like [`__m128i`](https://doc.rust-lang.org/core/arch/x86/struct.__m128i.html)) to clarify how they interact with Rust's rules around undefined values.

Can they have `poison`/`undef` in a lane?  Or is it insta-UB to do that, like it is for primitives?

**Comment by workingjubilee** [comment]
...we should probably simply deprecate the methods and recommend use of `MaybeUninit<T>` for them.

**Comment by scottmcm** [comment]
The compiler strenuously disagrees right now, at least:
```text
warning: the type `std::arch::x86_64::__m128i` does not permit being left uninitialized
 --> src/lib.rs:5:9
  |
5 |         std::mem::MaybeUninit::uninit().assume_init()
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |         |
  |         this code causes undefined behavior when executed
  |         help: use `MaybeUninit<T>` instead, and only call `assume_init` after initialization is done
  |
  = note: integers must be initialized
```
<https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=7bb6a4c66601d20eda0c3204e1e703fb>

Today they do `mem::zeroed()`, not `uninit`:
```llvm
; playground::make_undef
; Function Attrs: mustprogress nofree norecurse nosync nounwind nonlazybind readnone willreturn uwtable
define void @_ZN10playground10make_undef17hdcb3256a81ec5e58E(ptr noalias nocapture noundef readnone sret(<2 x i64>) dereferenceable(16) %0) unnamed_addr #0 {
start:
  ret void
}

; playground::make_undef_intrin
; Function Attrs: mustprogress nofree nosync nounwind nonlazybind willreturn uwtable
define void @_ZN10playground17make_undef_intrin17h301d7039825564c2E(ptr noalias nocapture noundef writeonly sret(<2 x i64>) dereferenceable(16) %0) unnamed_addr #1 {
start:
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 16 dereferenceable(16) %0, i8 0, i64 16, i1 false), !alias.scope !2
  ret void
}
```

(And we probably shouldn't deprecate any platform intrinsics, since they're there to be used same as one could in C.)

**Comment by workingjubilee** [comment]
Well... IMO, "the compiler mentions that the intrinsic you are calling is effectively fake as it will devolve to `mem::zeroed()`, not `mem::uninitialized()`, and you actually want `MaybeUninit::uninit()`" kinda is desirable behavior, but I'm not going to Take A Stand on that, since I agree that it doesn't really matter in e.g. the direct transpilation case.

We've been discussing implementing `MaybeUninit` support for portable SIMD, so I guess this is a motivation to do that.

**Comment by scottmcm** [comment]
You certainly have a point that right now it's exactly the same as `_mm_setzero_si128`.

We could also implement them as `MaybeUninit::frozen().assume_init()`, though, I think?  Dunno if it'd ever really matter for optimizations.

(And we'd need to even have `freeze` in the first place, but the version of freeze that doesn't care about existing content and can always be implemented as just `zero` is much less scarier semantically, though still hard to check for misuse in MIRI.)

The problem with `MaybeUninit<__m128i>` is that you then can't call any of the other intrinsics with it.  The obvious code to follow-up from `_mm_undefined_si128` is  `_mm_insert_epi64`/`_mm_insert_epi8`/etc, but you can't call those with a `MaybeUninit<__m128i>`.

Unless we overloaded those intrinsics, I guess?  But that sounds like a horrible idea 😅  Clang appears to get away with zeroinit, so I guess we should just do that too?

**Comment by workingjubilee** [comment]
Yeah, you're right, it'd be kind of useless as a recommendation unless we changed something else.

Regarding: "What is `__m{128,256,512}{bh,d,i}` relative to uninit?"
I believe the appropriate way to define these types is as having any valid bitpattern.
They should be seen as just a bag of bits.
It should not even be seen as the case that `__m128i` is e.g. considered `i32x4`. It could also be an `i8x16`! It doesn't matter. It barely "is" anything. The only clear thing is that it's 128 bits (or 16 bytes, since Rust doesn't really care about individual bits at the moment).

So if we exposed a `freeze` intrinsic in Rust, yes. `_mm_undefined_si128` would return such a frozen vector where you cannot rely on the contents but you hopefully don't care to, so it doesn't matter.

However, `xor reg, reg` on x86 is often an _optimization_. It is rarely going to be the case that you don't actually want to do that when materializing one of these vectors, as it signals to the CPU to allocate a renamed register, breaking previous dependencies. So I think that's part of clang's rationale here.

**Comment by scottmcm** [comment]
Well, I don't know if other optimizations could take advantage of it before it gets to this step, but apparently today <https://llvm.godbolt.org/z/M7G6bnE7E> LLVM will optimize `ret freeze <2 x i64> undef` to `ret <2 x i64> zeroinitializer` anyways, since that's the cheapest reified pattern, so as you say it's probably very rare that it'd even matter that it has more freedom than starting from zeroed in the first place.

**Comment by workingjubilee** [comment]
https://github.com/rust-lang/stdarch/pull/1410 has landed in stdarch so that will hit whenever the main Rust repo is updated, closing this.
