### ISSUE TITLE
Integer methods (e.g. `checked_sub`) do not mention underflow-ing

### ISSUE THREAD

**Issue by lesurp** [rust-lang/rust#108305]
### Location

In the documentation for primitives' methods (such as https://doc.rust-lang.org/std/primitive.u32.html), many methods mention the behavior when overflow occurs, but they never mention underflow, e.g. `0u32.checked_sub(1)` cannot even overflow, but the doc says it is overflow-proof, with no mention of the possible underflow behavior.

### Summary

Shouldn't the doc be changed to reflect this? Many operations are described in terms of overflowing (e.g. `checked_sub` for unsigned types) even if they cannot ever overflow.

This would be a minor change (would love to do it myself as a first contribution!) but I am curious to know whether this is an oversight, or whether "underflow" is simply not differentiated from "overflow" in the documentation (and do we ever want to specify those differently)?

**Comment by SkiFire13** [comment]
AFAIK that's not the meaning of underflow. 
Underflow occurs when a floating point variable gets a value that's too small to represent (i.e. it's value is smaller in absolute value than the smallest floating point value near 0).
Overflow instead happens when you try to produce a variable outside the range of representable values, be it both positive or negative.
As such the wording in the documentation looks correct to me.

**Comment by lesurp** [comment]
Hmm it seems you are right, I apparently got my definitions mixed-up!
