### ISSUE TITLE
Hexadecimal pretty formatting count leading 0x as leading zeros

### ISSUE THREAD

**Issue by t-lintanf** [rust-lang/rust#108527]
I tried this code:

```rust
  println!("{:#02x}", 2u8);
```

I expected to see this happen: 
```bash
$ cargo run
0x02
```

Instead, this happened: 
```bash
$ cargo run
0x2
```

When trying with a larger number of leading zeros, I discover a that the leading 0x is counted as leading zeros. The work around for my use case is then to use 0x04x but I find it intuitive from a code reading perspective.

I did not test with every integer type but the same behavior appear each of the one I tested (u8, u16, i32).
This behavior is shared between lower and upper hex.

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-unknown-linux-gnu
release: 1.65.0
LLVM version: 15.0.0
```

<details><summary>Backtrace</summary>
<p>

```
 None
```

</p>
</details>

**Comment by tdelabro** [comment]
This is the expected behaviour.

The number you are inputting (here 2), is not the number of 0 you want to see, but the minimal total width of the generated string, once padded.

It also work with other padding characters
`println!("{:#>2x}", 2u8);` will print `#2`. A string of width `2` padded with  `#` 

You can read more about this here: https://doc.rust-lang.org/std/fmt/#sign0

**Comment by ChrisDenton** [comment]
As per the above, closing as expected behaviour.
