### ISSUE TITLE
`+outline-atomics` violates "core shall not depend on libc"

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rust#109064]
There is a policy that Rust's `core` does not depend on the libc implementation for a given target. This has caused us quite a deal of heartache in the past, and it is about to cause us more, but I believe it is and has been the right choice. Rust code relying only on our core library should not really _require_ participation from any other toolchain or library beyond our own code. We should be able to have "pure Rust" targets without being entangled with implementation details. We should be able to, in the long run, build and link our own code. And we should not close the door on that, certainly not at this stage where people are actually building pure Rust runtime libraries and operating systems.

In https://github.com/rust-lang/rust/pull/83655 I made a mistake that violated this policy. I was not familiar with how the function definitions would be resolved, and I thought they only depended on the linker somehow. It had not occurred to me, at the time, that it induced a dependency on glibc, and I was somehow not tipped off by the other bugs that started showing up. It has caused recurring issues even until relatively recently:
- https://github.com/rust-lang/rust/issues/89626#issuecomment-1242636038
- https://github.com/rust-lang/rust/issues/101172
- https://github.com/rust-lang/wg-cargo-std-aware/issues/74

I have personally also run into this in another project, even with _very_ recent compilers.
A lot of work has been done to make my mistake compile anyways, and it's _still not enough_.
Obviously, this deeply hurts our ability to implement things like `-Zbuild-std`.

Fortunately, it is easily corrected: simply remove the feature from the aarch64-unknown-linux-gnu target spec unless and until we arrive at an implementation that does not require participation from glibc. This will lead to a performance regression using atomic instructions in some cases, but that's an acceptable loss if the alternative is continually trashing everyone's ability to build Rust code.

This may require retouching code in compiler-builtins as well.

**Comment by jyn514** [comment]
to be clear, #101172 is not caused by this issue, but fixing it exposes a latent bug caused by this issue (compiler_builtins has a hard dependency on LLVM's compiler-rt on that target: https://github.com/rust-lang/rust/pull/101833#issuecomment-1270191721).

**Comment by workingjubilee** [comment]
Yeah there's a lot of "the problems are so weird and arcane that issues are rarely about them but the problems get mentioned in passing comments" which is why I felt posting a separate issue was necessary.

**Comment by apiraino** [comment]
Assigning a priority label to keep awareness high on this issue (bits of [discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23109064.20.60.2Boutline-atomics.60.20violates.20.22core.20shall.20not.20depend.20.E2.80.A6)). The relevant team will decide how to work on this

@rustbot -label:I-prioritize +label:P-high

**Comment by workingjubilee** [comment]
Note re: this football: T-libs took a look at it. As Thom expresses, from the libcore perspective it's purely an optimization and we can disable it, and even though it has to do with how libcore functions, it has to do with how compiler targets work and how they are built. We enable it explicitly for certain targets, but LLVM also enables it implicitly. And as long as this remains an issue, this breaks a lot of ways to compile for a lot of (all?) tier 3 targets, making it much harder to use the compiler.

So, T-libs thinks T-compiler should take a look at it!

**Comment by jyn514** [comment]
T-compiler [said](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-03-16/near/342338747) they need to
1. Agree that "core shall not depend on libc" is actually the policy. There seemed to be consensus that it's a *good* policy, but the title of this issue is the first time most of the team had heard it exists.
2. Make an MCP for ripping out `+outline-atomics` from `aarch64-unknown-linux-gnu`. @workingjubilee has graciously offered to write this up. I believe this will also include a proposal to codify 1.

**Comment by Amanieu** [comment]
Also somewhat related, some targets (notably, Android) use emulated TLS for `#[thread_local]` which makes `compiler-builtins` depend on pthreads from libc. This is a concern if we ever want to stabilize `#[thread_local]` as a core language feature available in `#![no_std]`.

**Comment by sebpop** [comment]
`getauxval` is supported in musl in all versions after 1.0.0:
https://www.openwall.com/lists/musl/2020/02/16/3
So the fix in llvm/compiler-rt should be to detect at build time whether `getauxval` is supported in the libc.

**Comment by workingjubilee** [comment]
That assumes we want to have to depend on libc or indeed even compiler-rt to build for a target. The intent of compiler-builtins is pretty explicitly to not have to depend on compiler-rt.

**Comment by thomcc** [comment]
Regardless of whether or not `core` depends on the system C library (I'd prefer it did not, but it may be unavoidable), it is quite problematic for us to have a dependency on shims provided only by the `compiler-rt` C code that don't have shims in `compiler-builtins`, which is the current state of things on aarch64.

This is because:
1. We don't always have those sources available when compiling `compiler-builtins`.
2. Even if we *do* have the compiler-rt sources, we might not be able to build them (note that it's much harder to cross-compile C code than pure Rust code -- you need headers for that target, a C cross compiler, ...).
3. On other targets, compiling these sources is entirely optional (for these reasons), as `compiler-builtins` can provide all the non-optional functionality (sometimes with less efficient implementations).

It's bad because it breaks:
1. Cross-compiled `cargo (build|check) -Zbuild-std --target=aarch64-unknown-linux-gnu`[^and_no_std] (and several other `aarch64` targets), unless the user has both:
	1. A configured C cross compilation toolchain (including the system headers, a C cross compiler, the target's ranlib/ar, and so on)
	2. *And* also has a checkout of the `compiler-rt` sources somewhere on their machine, *and* sets the `RUST_COMPILER_RT_ROOT` path to that location (and even then there might be some other requirement needed).
2. `x check --target=...` in many cases (probably way more of them than it likely needs to, honestly -- this is currently the main reason it doesn't happen to work most of the time IIUC).
3. Probably other stuff too.

Anyway, this is at best pretty annoying, and is something that (IMO) we'll need to address even if we decide "yep core can require libc".

---

I think the most straightforward approach to fix those issues (without totally giving up `outline-atomics`) is probably for us to implement versions of the outline-atomic functions in Rust inside the `compiler-builtins` crate, for use as a fallback (in cases where we don't have the `compiler-rt` C code, or don't have a cross compiler).

This is straightforward in principal, but I don't know if it's practical for us to port the runtime feature detection aspect to Rust. Specifically adding a dependency on `libc`-the-crate into `compiler-builtins` seems... non-trivial to me to get working with the linker in all cases (maybe I'm mistaken, and it won't be an issue?)

That said, `compiler-builtins`-without-`compiler-rt` is already missing a bunch of other optimizations, so maybe not having support for runtime feature detection in the `compiler-builtins` fallback code would be fine.

If so, it's presumably straight-forward to port to Rust (the hard part is probably figuring out when to turn on the fallback without breaking anything...)

**Comment by sebpop** [comment]
> to port the runtime feature detection aspect to Rust

Following the ARM Architecture Reference Manual, the detection of the LSE atomic instructions can be done in assembly by reading the value of the "AArch64 Instruction Set Attribute Register 0" `ID_AA64ISAR0_EL1` register, and checking that the value of bits [23:20] is equal to `0b0010`.
Here's how golang does the CPU feature detection: 
https://github.com/golang/go/blob/33d8cdeedc4e69cd2d4eae10f024af826a73ce47/src/internal/cpu/cpu_arm64.s#L8-L12
https://github.com/golang/go/blob/33d8cdeedc4e69cd2d4eae10f024af826a73ce47/src/internal/cpu/cpu_arm64.go#L66-L69

**Comment by AGSaidi** [comment]
The above only works for Linux because Linux emulates these instructions from user-space starting in 4.11 which i believe is above the minimum supported Linux kernel version for Rust. 

That said, i really want to see outline-atomics not get dropped of the large performance delta it can bring.

**Comment by taiki-e** [comment]
@sebpop 

It works only with relatively new versions of some OSes ([go uses it only on FreeBSD](https://github.com/golang/go/blob/33d8cdeedc4e69cd2d4eae10f024af826a73ce47/src/internal/cpu/cpu_arm64_freebsd.go#L11), [rust as well](https://github.com/rust-lang/stdarch/tree/master/crates/std_detect#platform-support)). 

Also, AFAIK, it does not work on some environments regardless of OS versions. [Here](https://github.com/taiki-e/portable-atomic/blob/2de49c55db5b3053ed0ee1aaf7cfe26668df61a2/src/imp/atomic128/detect/aarch64_aa64reg.rs#L21-L28) is a record of a test I did a while back.

> - On Linux, this approach requires a higher kernel version than Rust supports, and also does not work with qemu-user (as of QEMU 7.2) and Valgrind. (Looking into HWCAP_CPUID in auxvec, it appears that Valgrind is setting it to false correctly, but qemu-user is setting it to true.)
> - On FreeBSD, this approach does not work on FreeBSD 12 on QEMU (confirmed on FreeBSD 12.{2,3,4}), and we got SIGILL (worked on FreeBSD 13 and 14).

In any case, on Linux, HWCAP_CPUID should be checked first to know if it is available.

> checking that the value of bits [23:20] is equal to `0b0010`.

FWIW, `0b0011` (FEAT_LSE128) also means FEAT_LSE is implemented.

https://developer.arm.com/documentation/ddi0601/2022-12/AArch64-Registers/ID-AA64ISAR0-EL1--AArch64-Instruction-Set-Attribute-Register-0?lang=en

**Comment by jyn514** [comment]
@workingjubilee now that compiler-builtins supports outline-atomics natively, does it make sense to close this issue? I tested in https://github.com/rust-lang/rust/pull/102579/commits/04555d1bc3def00f4804d79e06b2b6f586274f57 that it fixed https://github.com/rust-lang/rust/pull/101833#issuecomment-1270191721.

**Comment by workingjubilee** [comment]
Ah, thank you so much!

**Comment by tgross35** [comment]
Aware that this a dead thread, but to square the last circle here: https://github.com/rust-lang/rust/pull/144705 will add the runtime-dispatched LSE to our `outline-atomics` implementation, but it will only be enabled as part of `std`'s startup code. This means we can just use `is_aarch64_feature_detected` there, and `core` has no dependency on `getauxval`.
