### ISSUE TITLE
Suggest `..=` when someone tries to create an overflowing range

### ISSUE THREAD

**Issue by D4v1d-L4u** [rust-lang/rust#109529]
I tried this code:
```rust
for i in 0..256 as u8 {
        println!("{}", i);
}
```

I expected to see this happen: 
printing all numbers from 0 to 255 (inclusive)

Instead, this happened: 
```
error: literal out of range for `u8`
  --> src/main.rs:10:17
   |
10 |     for i in 0..256 as u8 {
   |                 ^^^
   |
   = note: the literal `256` does not fit into the type `u8` whose range is `0..=255`
   = note: `#[deny(overflowing_literals)]` on by default
```

`rustc --version --verbose`:
```
rustc 1.68.0 (2c8cc3432 2023-03-06)
binary: rustc
commit-hash: 2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74
commit-date: 2023-03-06
host: x86_64-unknown-linux-gnu
release: 1.68.0
LLVM version: 15.0.6
```

**Comment by scottmcm** [comment]
You can run that code if you want, by allowing the lint: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1d23a2e2a27104c5b6cb6351d5ad6722>

But if you do you'll see that it will print nothing because the `256` overflows and becomes `0`, so it's `in 0..0` which is empty.

Examples like this where allowing the literal overflow would do something you don't want are exactly why this lint is deny-by-default 🙂

**Comment by scottmcm** [comment]
I've renamed this issue because the lint is correct.  If there's anything to be done here, it would be to add a range-specific suggestion for this situation to help guide towards the correct code.
