### ISSUE TITLE
Macro with empty expansion in expression position causes an "unexpected <eof>" error

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#10951]
``` rust
macro_rules! foo ( () => () );
fn main() { foo!() }
```

```
expand.rs:1:0: 1:0 error: unexpected token: `<eof>`
expand.rs:1 macro_rules! foo ( () => () );
            ^
```

(Moving the `foo!()` outside `main` works.)

**Comment by Charlesetc** [comment]
This is still happening
```
% rustc --version                                                                                                                           
rustc 1.5.0-dev (0be1bcd06 2015-10-24)
```

**Comment by brson** [comment]
Still happening.

**Comment by brson** [comment]
@jseyfried just pinging you to make you aware and spark your interest.

**Comment by jseyfried** [comment]
The issue here is that `foo!()` is an expression position, so we expect it to be exactly one expression.
If it were `foo!();` or `foo! { }`, then it would be in a statement(s) position and would compile.

This distinction isn't ideal, but I've already cleaned it up about as much as possible given back-compat constraints (see #34660), so I'm not sure there's much we can do about it now.

cc @nrc
