### ISSUE TITLE
f64::cbrt has different result  in different operation-systems

### ISSUE THREAD

**Issue by loyispa** [rust-lang/rust#110132]
I tried this code:

```rust
    println!("{}",-0.055605003447049994_f64.cbrt())
```

macos returns: *-0.3816845880251514*

linux returns: *-0.3816845880251513*  [rust-playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a8774b7c79a63cff8db0062fd703ac55).

Seems  like macos is more accurate,  is this a bug or allowed in rust?  

### Meta

`rustc --version --verbose`:
```
rustc 1.68.2 (9eb3afe9e 2023-03-27)
binary: rustc
commit-hash: 9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0
commit-date: 2023-03-27
host: aarch64-apple-darwin
release: 1.68.2
LLVM version: 15.0.6
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by quaternic** [comment]
For `cbrt`, Rust is just delegating to the system libc, which explains a difference in behaviour. E.g. linking to musl instead of glibc has the same difference: [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:'%0Afn+main()+%7B%0A+++++println!!(%22%7B%7D%22,-0.055605003447049994_f64.cbrt())%3B%0A%7D'),l:'5',n:'0',o:'Rust+source+%231',t:'0')),k:48.58903912873804,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:executor,i:(argsPanelShown:'1',compilationPanelShown:'0',compiler:r1680,compilerName:'',compilerOutShown:'0',execArgs:'',execStdin:'',fontScale:14,fontUsePx:'0',j:2,lang:rust,libs:!(),options:'-O+--target+x86_64-unknown-linux-gnu',source:1,stdinPanelShown:'1',wrap:'1'),l:'5',n:'0',o:'Executor+rustc+1.68.0+(Rust,+Editor+%231)',t:'0')),header:(),l:'4',m:41.10787172011662,n:'0',o:'',s:0,t:'0'),(g:!((h:executor,i:(argsPanelShown:'1',compilationPanelShown:'0',compiler:r1680,compilerName:'',compilerOutShown:'0',execArgs:'',execStdin:'',fontScale:14,fontUsePx:'0',j:3,lang:rust,libs:!(),options:'-O++--target+x86_64-unknown-linux-musl',source:1,stdinPanelShown:'1',wrap:'1'),l:'5',n:'0',o:'Executor+rustc+1.68.0+(Rust,+Editor+%231)',t:'0')),header:(),l:'4',m:58.89212827988338,n:'0',o:'',s:0,t:'0')),k:51.410960871261985,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

To consider glibc specifically, quoting their [documentation](https://www.gnu.org/software/libc/manual/html_node/Errors-in-Math-Functions.html):

> Except for certain functions such as sqrt, fma and rint whose results are fully specified by reference to corresponding IEEE 754 floating-point operations, and conversions between strings and floating point, the GNU C Library does not aim for correctly rounded results for functions in the math library, and does not aim for correctness in whether “inexact” exceptions are raised.

It then goes on to list the properties that you *may* expect, and there's a table of largest known errors for each function. For x86_64, cbrt for double-precision is listed at 4 ulp so the example in this issue is well within that, so most likely not considered a bug by glibc.

**Comment by scottmcm** [comment]
This is non-ideal, but is absolutely allowed.  The same happens with `tan`, and essentially everything outside the basics.  See conversations like <https://users.rust-lang.org/t/constant-trigonometry/58565/6?u=scottmcm>.

An Intel presentation: https://www.nccs.nasa.gov/images/FloatingPoint_consistency.pdf

Determinism across platforms and processors *is* possible, but you'll need to be very careful about it and bring your own math library: <https://gafferongames.com/post/floating_point_determinism/>.

**Comment by scottmcm** [comment]
In this case, remember that `-0.055605003447049994_f64` is actually [*exactly*](https://float.exposed/0xbfac78424e991cb0) -5.560500344704999431399983222945593297481536865234375​×10⁻².

So the true answer [is](https://www.wolframalpha.com/input?i=cbrt%28-5.560500344704999431399983222945593297481536865234375%E2%80%8B%C3%9710%E2%81%BB%C2%B2%29) -0.3816845880251513579871013534574844660176779950763845233540552209703024223113400382916139662737764452421775768188871681807613..., which of course needs to be rounded.

```text
-0.381684588025151316781347077267128042876720428466796875​ (-0.3816845880251513_f64)
-0.38168458802515135798710135345748446601767799507638452335405522097…
-0.3816845880251513722924983085249550640583038330078125​ (-0.3816845880251514_f64)
```

So it's within ±1ULP, which is about as good as you can hope for outside the basics (+-* etc).

**Comment by Dylan-DPC** [comment]
Closing this issue as the behaviour is intended
