### ISSUE TITLE
`--format=junit` doesn't include stdout / test failure reason

### ISSUE THREAD

**Issue by ssbr** [rust-lang/rust#110336]
I tried this code:

```rust
#[test]
fn it_breaks() { panic!("PANICCC"); }
```

I expected to see this happen: the string `PANICCC` in the test output, when running `cargo test -- --format=junit -Zunstable-options`.

Instead, this happened:

```xml
<?xml version="1.0" encoding="UTF-8"?><testsuites><testsuite name="test" package="test" id="0" errors="0" failures="1" tests="1" skipped="0" ><testcase classname="crate" name="it_breaks" time="0"><failure type="assert"/></testcase><system-out/><system-err/></testsuite></testsuites>
```

### Meta

`rustc --version --verbose`:
```
rustc 1.68.2 (9eb3afe9e 2023-03-27)
binary: rustc
commit-hash: 9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0
commit-date: 2023-03-27
host: x86_64-unknown-linux-gnu
release: 1.68.2
LLVM version: 15.0.6
```

</p>
</details>

**Comment by Manishearth** [comment]
Note that this works fine under other message formats

**Comment by Manishearth** [comment]
Ah, it seems like the JSON backend emits this as a "stdout" entry https://github.com/rust-lang/rust/blob/5546cb64f6fbba70529582bbe58a40ba4a8ed9fc/library/test/src/formatters/json.rs#L139-L144


Whereas the junit backend [does not](https://github.com/rust-lang/rust/blob/5546cb64f6fbba70529582bbe58a40ba4a8ed9fc/library/test/src/formatters/junit.rs#L61)



The test runner maintains a distinction between `TrFailed` and `TrFailedMsg`, except that the latter is only for failures with messages that come from _the test suite_ (as opposed to panic messages). The testsuite doesn't distinguish between panic messages and otherwise, though it can for `should_panic` tests.

The simplest thing to do is probably just dump stdout inside the `failure` text body. I'm not sure if that's ideal, it would be nice if we could get it into `message` instead.
