### ISSUE TITLE
Cannot call static methods on type aliases, "module wasn't actually a module!"

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#11047]
Compile this:
```rust
pub mod foo {
    pub mod bar {
        pub mod baz {
            struct Qux;

            impl Qux {
                pub fn new() {}
            }
        }
    }
}

fn main() {
    type Ham = foo::bar::baz::Qux;
    let Foo = foo::bar::baz::Qux::new();  // works fine
    let Bar = Ham::new();  // oops!
}
```
```
$ rustc ty.rs
!!! (resolving module in lexical scope) module wasn't actually a module!
ty.rs:16:14: 16:22 error: unresolved name
ty.rs:16     let Bar = Ham::new();
                       ^~~~~~~~
ty.rs:16:14: 16:22 error: use of undeclared module `Ham`
ty.rs:16     let Bar = Ham::new();
                       ^~~~~~~~
!!! (resolving module in lexical scope) module wasn't actually a module!
ty.rs:16:14: 16:22 error: unresolved name `Ham::new`.
ty.rs:16     let Bar = Ham::new();
                       ^~~~~~~~
error: aborting due to 3 previous errors
task 'rustc' failed at 'explicit failure', /root/catacombs/scrap/rust/src/libsyntax/diagnostic.rs:102
task '<main>' failed at 'explicit failure', /root/catacombs/scrap/rust/src/librustc/lib.rs:392
```
I can't imagine that this is intentional, as it greatly limits the utility of type aliases.

**Comment by gavinb** [comment]
I keep bumping into #19130 and this issue, and keep referring to the docs assuming it's a mistake.

It would seem that one of the most common reasons to use a type alias would be for generics, however due to this issue, the `type` feature is of rather limited use.

The official docs on [type alias](http://doc.rust-lang.org/reference.html#type-aliases) only show an example of a tuple type alias, and no mention is made of traits or generic types. The [Rust by Example docs on type alias](http://rustbyexample.com/type/alias.html) only alias ordinal types, but it does mention aliasing generic types in passing at the end.

It seems very natural to want to write:

    type StringVec = Vec<String>;
    // ...
    let mut sv = StringVec::new();

but you get the rather ambiguous error:

    error: failed to resolve. Use of undeclared type or module `StringVec`

when the type declaration is *right there*, and then have to write this instead, which rather defeats the purpose:

    type StringVec = Vec<String>;
    // ...
    let mut sv: StringVec = Vec::new();

Anyway, I guess this is a big +1 for this issue.

**Comment by vadimcn** [comment]
@pcwalton, @alexcrichton, @pnkfelix : Was this bug ever triaged?   I think this should be considered for 1.0 nomination.

**Comment by alexcrichton** [comment]
I'll renominate to make sure we see this. My personal recommendation though is that if the only bug is generating more errors than we should then this isn't a 1.0 issue.

**Comment by pnkfelix** [comment]
This is a nice-to-have, not a 1.0 block.  Marking as P-high.

**Comment by LukasKalbertodt** [comment]
I would agree that type aliases are pretty useless when you can't use them as first class types. If I can do `Foo::stuff()` I want to be able to do `type Bar = Foo; Bar::stuff()`... 
I think it's important.

**Comment by matthieu-m** [comment]
@LukasKalbertodt I believe we all agree on this; however 1.0 does not mean "finished" but "backward compatible" and calling static methods on type aliases is not necessary for backward compatibility since all programs without will continue to compile once it is implemented (the converse would not be true). Therefore, while I personally value this improvement, I understand that it is not necessary for 1.0.

**Comment by arielb1** [comment]
This seems to work on 1.3+.

**Comment by gavinb** [comment]
Verified this works on 1.3. I created a test for this issue. https://github.com/rust-lang/rust/pull/28703/files
