### ISSUE TITLE
Easy compliance with trademark policy

### ISSUE THREAD

**Issue by dullbananas** [rust-lang/rust#110697]
When creating modified versions of Rust, we must be able to easily comply with the trademark policy and know exactly what changes need to be made in the modified codebase. Until this is the case, Rust might be non-libre. The possibility that I am using a non-libre compiler is shocking and disappointing.

Richard Stallman said this: "Rust has a legal problem as well: the trademark licenses of Rust is unclear, and I can't determine whether Rust is free software. It is potentially harmful for anyone to use Rust at all as long as that
remains the case. The Rust developers could cure that one problem by explaining concretely what that license requires, specifically for how to remove the Rust and Cargo trademarks from the compiler. I asked them over a year ago, but they never responded." (https://lists.gnu.org/archive/html/emacs-devel/2023-01/msg00463.html)

One possible solution is to do this:
* Add a script that makes all trademark replacements that are needed.
* In the trademark policy, say that running this script is enough to comply.

**Comment by Nilstrieb** [comment]
The foundation is currently in the process of revamping the trademark policy because of the unclarity you mentioned: https://foundation.rust-lang.org/news/rust-trademark-policy-draft-revision-next-steps/

You're best off waiting for results there.

This issue tracker isn't really the place for this. This issue tracker is for problems with code in this repository, not meta issues like the foundation trademark. You're better off asking the foundation directly (though as I said, progress on the trademark issue is happening, so you should wait for that).

**Comment by Menus74** [comment]
Richard Stallman always on the side of freedom. I love it.

**Comment by the8472** [comment]
Closing as offtopic. Please use other discussion platforms and the feedback form.

**Comment by FrostKnight** [comment]
@the8472 this is exactly the kind of response that makes people not want to trust people like you.

The foundation is being a bully and needs to make mega compliance easier, otherwise, its very clear you want people to use this but at the same time, you might open  a can of worms when people least expect it purely for self gratification in the form of money. Long story short, its not off topic. Your trademark restrictions are hurting hurting the mission the rust foundation claims to believe in. 

You are your own worst enemy rust foundation.

**Comment by the8472** [comment]
You're directing your discontent at the wrong person here. I'm not even a member of the foundation, just a rust contibutor.

This specific issue tracker (`rust-lang/rust`) is for rustc development, not for policy discussion. That's all.

**Comment by FrostKnight** [comment]
@the8472 Fair point, I probably was talking to the wrong person, but its good to know that the feedback was received. 

Thanks for the info anyhow.
