### ISSUE TITLE
Tracking Issue for the x86 `ud2` intrinsic

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/rust#111193]
Feature gate: `#![feature(stdarch_x86_ud2)]`

This is a tracking issue for an x86 intrinsic for the `ud2` instruction.

### Public API

```rust
// core::arch::{x86,x86_64}

fn ud2() -> !
```

### Steps / History

- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by jyn514** [comment]
Hmm, don't we already expose this as `core::intrinsics::abort`? What advantage does the new function have?

**Comment by Amanieu** [comment]
I'm just adding tracking issues to all unstable functions in stdarch.

For this one specifically I'd be in favor of just removing it. But let's wait for me to actually finish tagging everything with tracking issues first.

**Comment by asquared31415** [comment]
`core::intrinsics::abort` doesn't guarantee that it will become a UD2, or have any specific codegen at all, even on a particular arch, it's implementation defined.

> On Unix, the process will probably terminate with a signal like SIGABRT, SIGILL, SIGTRAP, SIGSEGV or SIGBUS. The precise behaviour is not guaranteed and not stable.

Since this function is simply exposing a instruction, we could remove in in favor of `asm!`.  This function is perhaps convenient, since it returns a `!` and is less to write.  But I think that since it's *one* instruction, the stable `asm!` exposes more than enough.

Side note: if we keep this function, does it need a safety requirement along the lines of "there must not be a UD2 handler that returns execution", since it's defined as ` -> !`?

**Comment by chorman0773** [comment]
> if we keep this function, does it need a safety requirement along the lines of "there must not be a UD2 handler that returns execution", since it's defined as  `-> !`?

A handler is not a problem here, since the C Standard on `signal` function states
> If the user defined function returns when handling [SIGFPE](https://en.cppreference.com/w/c/program/SIG_types), [SIGILL](https://en.cppreference.com/w/c/program/SIG_types) or [SIGSEGV](https://en.cppreference.com/w/c/program/SIG_types), the behavior is undefined.

However, you could SIG_IGN `SIGILL`, which is problematic. On posix, you could also block the signal.

**Comment by asquared31415** [comment]
This function is in `core::arch::x86_64` and on certain x86_64 targets, such as no-OS targets, handling a #UD is not only allowed, but *expected*.  It's possible to write a #UD interrupt handler that returns as if it were a no-op.  So there are external requirements on the state of things for this signature to be correct.

Not that it matters anymore, since it's being removed.

**Comment by JohnTitor** [comment]
The stdarch submodule should have https://github.com/rust-lang/stdarch/commit/277a0b5c9af7cf755319358ad3b2ab8e308a69f9 now, could we close this issue?
