### ISSUE TITLE
unexpected rustdoc result about auto-trait

### ISSUE THREAD

**Issue by bvanjoi** [rust-lang/rust#111126]
code: 

```rust
pub struct Inner<T>(T);

trait MyTrait {
    type MyItem;
}

trait OtherTrait {}

impl<T> Unpin for Inner<T>
where
    T: MyTrait<MyItem = bool>,
{
}

pub struct Foo<K> {
    inner_field: Inner<K>,
}
```

because `Unpin` is not implement for `Foo` explicitly, I expected to see this happen after execute `rustdoc` :

![image](https://user-images.githubusercontent.com/30187863/235889575-d625ad2f-44af-4098-9aa1-698fb142688f.png)

Instead, this happened:

![image](https://user-images.githubusercontent.com/30187863/235889636-d7b1b66c-d2b7-4366-bb9f-47480174db97.png)

I am not sure the rendered if right or not, so I created the issue to seek some answer.

> related https://github.com/rust-lang/rust/issues/110740

**Comment by fmease** [comment]
This is the intended output (as far as I am aware).

> because `Unpin` is not implement for `Foo`

I'm not sure what you mean by that. `Unpin` is implemented for `Foo<K>` for all types `K` where
the type of field `inner_field` `Inner<K>` implements `Unpin` (since no explicit impl exists).
Whether a struct impls an auto-trait doesn't depend on the generic parameters (as your 1st picture shows)
but on the field types. You can read more about that [here](https://doc.rust-lang.org/beta/unstable-book/language-features/auto-traits.html).

So technically, the synthetic impl of `Unpin` for `Foo` looks like

```rs
impl<K> Unpin for Foo<K>
where
    Inner<K>: Unpin
```

but since one can argue that the constraint `Inner<K>: Unpin` is not that helpful (“actionable”) to the reader, we simplify the constraint. In this case `Inner<K>: Unpin` is *implied by* the explicit impl `impl<T> Unpin for Inner<T>` *as long as* the constraint `where T: MyTrait<MyItem = bool>` holds. Thus we *propagate* that constraint and end up with the synthetic impl as seen in your 2nd screenshot.

**Comment by fmease** [comment]
`impl<K> Unpin for Foo<K> where K: MyTrait<MyItem = bool>` is not “more correct” than
`impl<K> Unpin for Foo<K> where Inner<K>: Unpin` (what the compiler actually sees), it's
simply a different way to display the constraint.

`impl<K> Unpin for Foo<K> where K: Unpin` on the other hand is not correct in this case
*because of* the existence of the explicit impl `impl<T> Unpin for Inner<T> …`. If you were
to remove it, then that synthetic impl would be correct since

1. forall types `K`, `Foo<K>: Unpin` is implied by
2. forall types `K`, `Inner<K>: Unpin` is implied by
3. forall types `T`, `T: Unpin` (where `T` corresponds to the type of field `0` of the tuple struct `Inner`

**Comment by jyn514** [comment]
It looks like this isn't a bug, so I'm going to close the issue.
