### ISSUE TITLE
components missing from beta

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#111340]
`$rustup update`

```
info: latest update on 2023-05-08, rust version 1.70.0-beta.4 (2013813b6 2023-05-07)
error: some components unavailable for download for channel 'beta': 'clippy' for target 'x86_64-unknown-linux-gnu', 'rustfmt' for target 'x86_64-unknown-linux-gnu'If you don't need the components, you could try a minimal installation with:
error:
error:     rustup toolchain add beta --profile minimal
```

**Comment by matthiaskrgr** [comment]
https://github.com/rust-lang/rust/pull/111201 
cc @Mark-Simulacrum  /  @krasimirgg

**Comment by wiktor-k** [comment]
FWIW I also encountered this issue via my crate's CI matrix build (stable/beta/nightly; breaks only on beta).

**Comment by Mark-Simulacrum** [comment]
Thanks for flagging this! This is due to optimizations in promote-release, https://github.com/rust-lang/promote-release/pull/68 should resolve this (may need a future iterations). We'll probably also need to manually produce a new beta ~tonight once that lands, since we'll otherwise skip the extra release due to already having artifacts shipped for the latest commit.

**Comment by Mark-Simulacrum** [comment]
We should have a new beta which doesn't have this problem in 40ish minutes.

**Comment by Mark-Simulacrum** [comment]
Should be fixed. Thanks for filing an issue!
