### ISSUE TITLE
borrowck doesnt convert lifetime params to vars in generic_const_exprs

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#111434]
See bottom of description of #111215. `const-arg-in-const-arg.rs`, `in-closure.rs`, and `simple.rs` were revealed to be broken in that PR and need to be fixed (and test readded for const-arg-in-const-arg).

**Comment by BoxyUwU** [comment]
the issue literally links to the PR with all of the possible context you could ever need on the broken code

**Comment by BoxyUwU** [comment]
this issue also includes the two other broken pieces of code that regressed

**Comment by Nilstrieb** [comment]
> @BoxyUwU sorry, your "bug report" is kinda garbage, please try to at least include
> 
> 1. literal source code that helps reproduce the problem (some random filenames dont help because because files can be renamed, might be removed from the repo in a couple months etc)
> 2. the compiler version that is known to reproduce the problem
> 3. some sort of backtrace that can help to understand the problem.
> 
> Closing in favor of #111433 which has all these things. Feel free to add additional comments there 🙂

I agree that it would be nice to attach a source code example here. The issue does actually precisely specify the compiler version, namely every version after that PR. Having the version number is important for issues for random people where it allows you to check whether it's the latest one, but here we have the precise context of the version, which is even better.
Having a backtrace is also usually useful but here it doesn't matter that much because the title already describes the problem very well (way better than just the ICE message) and we know that it's not a duplicate. Backtraces are also not that critical because when fixing the issue, it will be reproduced locally anyways where you'll get an even nicer backtrace thanks to debuginfo.

**Comment by BoxyUwU** [comment]
dont give a shit to argue this anymore
