### ISSUE TITLE
Move assert! panic to cold function 

### ISSUE THREAD

**Issue by PSeitz** [rust-lang/rust#111866]
We can probably assume that `assert!` panics are never in the hot path. They are usually placed at the top of a function to catch invalid arguments.

Currently the panic is inlined into the code (https://godbolt.org/z/oPzcK9zYG), so if a function is called, there's a bunch of bunch bytes in the caches that are seldom used.
I saw this impacting performance negatively in several places.

[`copy_from_slice`](https://doc.rust-lang.org/std/primitive.slice.html#method.copy_from_slice) uses a function which is marked as `cold` and  `inline(never)` to avoid this issue.

Ideally `assert!` would always apply the same technique. I'm not sure how to handle picking a function name or if that can be avoided. 

```rust
pub fn copy(src: &[u8], dst: &mut [u8]) {
    #[inline(never)]
    #[cold]
    #[track_caller]
    fn len_mismatch_fail(dst_len: usize, src_len: usize) -> ! {
        panic!(
            "source slice length ({}) does not match destination slice length ({})",
            src_len, dst_len,
        );
    }

    if src.len() != dst.len() {
        len_mismatch_fail(src.len(), dst.len());
    }
    // My code starts at the beginning of the function

}


pub fn copy2(src: &[u8], dst: &mut [u8]) {

    assert!(src.len() == dst.len(), "source slice length ({}) does not match destination slice length ({})",
            src.len(), dst.len());
    // My code comes after the inlined assertion stuff
}
```

`copy2` macro expanded code:
```rust

pub fn copy2(src: &[u8], dst: &mut [u8]) {
    if !(src.len() == dst.len()) {
            {
                ::std::rt::panic_fmt(format_args!("source slice length ({0}) does not match destination slice length ({1})",
                        src.len(), dst.len()));
            }
        };
}
```

**Comment by saethlin** [comment]
> We can probably assume that `assert!` panics are never in the hot path.

It is a common technique to use `assert!` in the hot path to hoist or coalesce bounds checks. So I think it would be a dramatic regression to shunt all of `assert!` into a `#[cold]` function, but there is a useful project here in getting the _formatting_ part of it outlined.

The tricky part of this is handling the captures. I tried cooking this up at one point using a `#[cold]` closure, but I was focusing more on code size growth due to logging. At that time I concluded that using captures to do this didn't result in the wins I was looking for, but it looks like in the example you have it does!

https://godbolt.org/z/819rh65Ye

Note that this needs `-Copt-level=3` to fully optimize to what we want, just `-O` looks like it's missing an optimization, we have some extra `mov`s before the cold call.

So I think since the closure trick works, this is a _relatively_ simple change to the expansion of `assert!`.

**Comment by PSeitz** [comment]
> 
> It is a common technique to use `assert!` in the hot path to hoist or coalesce bounds checks. So I think it would be a dramatic regression to shunt all of `assert!` into a `#[cold]` function, but there is a useful project here in getting the _formatting_ part of it outlined.
> 

Yes, you are right. I meant the actual panic call is not in the hot path.

> The tricky part of this is handling the captures. I tried cooking this up at one point using a `#[cold]` closure, but I was focusing more on code size growth due to logging. At that time I concluded that using captures to do this didn't result in the wins I was looking for, but it looks like in the example you have it does!
> 
> https://godbolt.org/z/819rh65Ye
> 
> Note that this needs `-Copt-level=3` to fully optimize to what we want, just `-O` looks like it's missing an optimization, we have some extra `mov`s before the cold call.
> 
> So I think since the closure trick works, this is a _relatively_ simple change to the expansion of `assert!`.

That's really nice, I didn't know these attributes can also be applied to a closure. The assembly looks good.

I tested a little bit with name collisions, but this seems to be fine since the closure doesn't see itself.
Even something like this compiles:
```rust
pub fn copy2(src: &[u8], dst: &mut [u8]) {
    if src.len() != dst.len() {
        let src = #[inline(never)] #[cold] #[track_caller] || {
            panic!(
                "source slice length ({}) does not match destination slice length ({})",
                src.len(), dst.len(),
            );
        };
        src();
    }
}
```
