### ISSUE TITLE
[Missed Optimization] opportunity for bitshift is not used

### ISSUE THREAD

**Issue by alexpyattaev** [rust-lang/rust#112099]
The following function can safely be optimized with bitshift to right (since u32 should not overflow). 
``` rust
pub fn half(index: u32) ->u32 {
     return index* 3/6;
}
```
The actual assembly produced with -O3 is:
``` asm
example::half:
        lea     ecx, [rdi + 2*rdi]
        mov     eax, 2863311531
        imul    rax, rcx
        shr     rax, 34
        ret
```
The desired assembly would be:
``` asm
example::half:
        mov     eax, edi
        shr     eax
        ret
```

**Comment by Urgau** [comment]
> The following function can safely be optimized with bitshift to right (since u32 should not overflow).

I don't think this is true, it does overflow for large enough numbers, `half(u32::MAX / 2)` overflows [in the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9eabf2aae31a86a1bf3e5057e46730a8):

<details>

```rust
pub fn half(index: u32) ->u32 {
     return index* 3/6;
}

fn main() {
    //dbg!(half(4));
    dbg!(half(u32::MAX / 2));
}
```

```
thread 'main' panicked at 'attempt to multiply with overflow', src/main.rs:2:13
```

</details>

**Comment by alexpyattaev** [comment]
All correct, but is it not true that overflow on u32 is not allowed in release? As such, the optimizer should assume it does not happen and apply optimizations accordingly.

**Comment by Urgau** [comment]
> All correct, but is it not true that overflow on u32 is not allowed in release? As such, the optimizer should assume it does not happen and apply optimizations accordingly. Or is it that overflow is explicitly defined to wrap when used on u32?

Rust defines overflow as panicking is debug mode and wrapping in release mode (see [Reference - Behavior not considered unsafe](https://doc.rust-lang.org/reference/behavior-not-considered-unsafe.html)). This means that there is no undefined-behavior (or well-defined behavior for that matters) that the optimizer can take advantage of here.

**Comment by workingjubilee** [comment]
> Bottom line is, no matter how it is defined, in debug build this function will panic when fed an overflowing value, and as a result optimizer can assume it would not overflow in release either.

It is, unfortunately, not acceptable in terms of Rust semantics to base optimizations of safe code on the assumption that tests exist that would panic and thus reject the code in question. The programmer, after all, can simply skip running tests by building and executing the binary instead. Thus, what you are thinking of requires things like the experimental [`unchecked_mul`](https://doc.rust-lang.org/std/primitive.u32.html#method.unchecked_mul) (which is really just a sweetened way to write y21's example).

Closing. If there is a related missed optimization please open a new issue.

**Comment by alexpyattaev** [comment]
So is it like 100% fixed in stone sort of thing or is there a process to potentially consider making what unchecked_math does the default for release builds? Bottom line is, in order to actually experience the wrapping overflow, one would need to BOTH
 1.  never run the code in debug (ever), and
 1.  actually rely on the overflow happening instead of using overflowing_mul. 

I'd argue very few rust developers would ever satisfy both of these requirements.
So it may be feasible to change this to essentially assume overflow never happens in release mode & get faster binaries as a result. Or am I missing something important here?

**Comment by nikic** [comment]
You are missing that safe rust code never exhibits undefined behavior.

**Comment by workingjubilee** [comment]
No, I would not call it fixed in stone!

I would call it forged in titanium.

That safe code, which `x + y` is, cannot cause UB, is a fundamental principle underpinning the entire Rust language. It also would be a breaking change to somehow make invoking those operators require `unsafe {}`. The "panic on overflow" behavior is really just a lint. You can even disable it via compiler configuration, albeit slightly differently than most lints.

> I'd argue very few rust developers would ever satisfy both of these requirements.

"very few" is not good enough when we want a guarantee.

**Comment by y21** [comment]
Making integer overflow UB has (as far as I understand `unchecked_math`) other unsafe implications too (beyond just possibly getting an incorrect value on overflow), since UB infects the whole program.
For example this code segfaults in release mode, because the compiler assumed that `slice.len() <= index` is never true as a result of integer overflow (of course, this is with unsafe, but the described behavior would presumably make this possible in safe code?):
```rs
fn add(a: u32, b: u32) -> u32 {
  if a.checked_add(b).is_none() {
    // Let's make overflowing a + b UB
    unsafe { std::hint::unreachable_unchecked() };
  }
  a + b
}

fn get_unchecked(slice: &[u8], index: usize) -> u8 {
  if slice.len() <= index {
    add(u32::MAX, 1); // u32::MAX + 1, this code path is now unreachable
  }

  // `slice.len() <= index` can never be true, bounds check gets optimized out
  slice[index]
}

fn main() {
  let s = Vec::new();
  dbg!(get_unchecked(std::hint::black_box(&s), 0));
}
```
I *might* be wrong on this though, it seems like `unchecked_math` is not as aggressive as `unreachable_unchecked()` (in terms of optimizations), but it is UB at the end of the day so it seems like that could be a valid implementation of `unchecked_add()`.

In fact, this implementation does exactly what the safety comment of `unchecked_add` says:
> This results in undefined behavior when `self + rhs > i32::MAX` or `self + rhs < i32::MIN`, **i.e. when [checked_add](https://doc.rust-lang.org/stable/std/primitive.i32.html#method.checked_add) would return None.**

I realize I'm getting kinda offtopic, but it makes me wonder if *this* is a missed optimization, or if it's intentionally not as aggressive because it would break way too much code relying on this with no real gain other than to break people's code (esp. if this is part of LLVM, which gets used by C implementations where signed int overflow is UB)?
(Also I realized I talked about `unchecked_add` instead of `unchecked_mul`, but I'm pretty sure all of what I said could also apply to multiplication)

**Comment by alexpyattaev** [comment]
Well, so the question here is not whether optimization is missed (it is, and we understand why). The question now is what should be done about it. I'd argue that this can become a code generator option (off by default) that folks can set if they want to squeeze that extra tiny bit of performance out of their programs. Then folks working with bevy engine and other performance-critical code can play with it, and if it turns out not to brick anything, it can be made default. Thoughts?

**Comment by workingjubilee** [comment]
You are welcome to do the work to demonstrate that this affects real programs of substantial size, where far more information on ranges is available, instead of the singular function that you presented, and that this is not compensated for by the existence of branch predictors in real CPUs.

**Comment by alexpyattaev** [comment]
Would you say that following this guide https://rustc-dev-guide.rust-lang.org/mir/optimizations.html I should be able to get a build of rustc that would implement this optimization? I'll give it a try once I have some spare time on my hands.
