### ISSUE TITLE
Create default object in loop.

### ISSUE THREAD

**Issue by Anderson0xFF** [rust-lang/rust#112118]
When creating an object in the default loop, the object has the same address, even moving it into a vector it still has the same address
I tried this code:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=30e54bcdaad228ad9ec487f55f85a394

```rust

#[derive(Default)]
struct Banana{
    value: i32
}

fn main(){
    let mut mapa = Vec::new();

    for _ in 0..2 {
        let banana = Banana::default();
        mapa.push(banana);    
    }

    for v in mapa {
        println!("Banana: {:p}", &v);
    }
}




```

I expected to see this happen: *explanation*
  Banana: 0x2fff80ba6210
  Banana: 0x8fff80ba6289
   ....
Instead, this happened: *explanation*
  Banana: 0x7fff80ba6210
  Banana: 0x7fff80ba6210
  
### Meta

It also happens in versions:

beta-x86_64-unknown-linux-gnu installed - rustc 1.71.0-beta.1 (eff24c06d 2023-05-29)
nightly-x86_64-unknown-linux-gnu installed - rustc 1.72.0-nightly (498553fc0 2023-05-29)

`rustc --version --verbose`:
```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-unknown-linux-gnu
release: 1.69.0
LLVM version: 15.0.7

```

**Comment by CraftSpider** [comment]
This is expected behavior for the code you posted - the address you're printing is that of the stack slot `v` used in the `for` loop, since iterating over a vector consumes it. To see different addresses, you'd instead want something like `for v in &vec { println!("{:P}", v) }`, which would print the location of items while they're in the vector.

**Comment by Anderson0xFF** [comment]
> This is expected behavior for the code you posted - the address you're printing is that of the stack slot `v` used in the `for` loop, since iterating over a vector consumes it. To see different addresses, you'd instead want something like `for v in &vec { println!("{:P}", v) }`, which would print the location of items while they're in the vector.

So when I move an object, does its pointer change too?
Is it not the same as before?

**Comment by CraftSpider** [comment]
Most of the time, when an object is moved, its location in memory changes, yes. This fact is actually why Rust references do not remain valid across moves of an item - since a move may invalidate all previous pointers, it invalidating all references falls out naturally.

A warning though that you cannot rely on this - Rust is free to optimize out actually moving the object in memory in some situations. The actual address of things have relatively few guarantees. If you do want objects to keep a consistent address, you should use `Box` - it allocates objects on the heap, and while it follows the same move rules as any other object, what actually moves is the `Box` itself, not the object it owns. So the following code will work:
```rs
let a = Box::new(1);
let a_addr = (&*a) as usize;
let b = a;
let b_addr = (&*b) as usize;
assert_eq!(a_addr, b_addr);
```

**Comment by jyn514** [comment]
The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/
