### ISSUE TITLE
Rust 1.70 release mode changed the behaviour of unsafe code

### ISSUE THREAD

**Issue by fxdave** [rust-lang/rust#112381]
Rust version 1.70 raised this issue:
https://github.com/EmbarkStudios/poll-promise/issues/18

Only the release mode has problems. Debug mode works.
It most recently worked on: Rust 1.69

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23112381.20Rust.201.2E70.20release.20mode.20changed.20the.20behaviour.20of.20uns.E2.80.A6)).

@rustbot label -I-prioritize +P-critical +T-compiler +A-LLVM

**Comment by joboet** [comment]
[The code in question](https://docs.rs/poll-promise/0.2.0/src/poll_promise/promise.rs.html#322-329) is unsound, mutating through a shared reference is **never** allowed, not even after casting it to a mutable pointer. This was fixed in EmbarkStudios/poll-promise#14, but that has not been released yet.

**Comment by apiraino** [comment]
Ah I see, I've now checked using the latest commit of the `poll-promise` crate and it indeed does not reproduce this issue. So, unsure what `rustc` could or should do here?

(sorry for the noise)

**Comment by fxdave** [comment]
Thanks for the quick answers, and sorry, I didn't know that is not allowed.

**Comment by joboet** [comment]
I think this is actually a nice example of LLVM using Rust's semantics to make things go fast: as the data cannot be mutated (according to the rules around shared references), LLVM correctly optimizes the `match` away and always jumps into the `unreachable!()` branch, hence the panic. So this is completely intentional from a rustc perspective.
