### ISSUE TITLE
unfriendly error diagnostic when using expressions in pattern

### ISSUE THREAD

**Issue by ShE3py** [rust-lang/rust#112593]
### Code

```Rust
struct Foo(String);

fn bar(foo: Foo) -> bool {
    match foo {
        Foo("hi".to_owned()) => true,
        _ => false
    }
}
```

### Current output

```
Compiling playground v0.0.1 (/playground)
error: expected one of `)`, `,`, `...`, `..=`, `..`, or `|`, found `.`
 --> src/lib.rs:5:17
  |
5 |         Foo("hi".to_owned()) => true,
  |                 ^
  |                 |
  |                 expected one of `)`, `,`, `...`, `..=`, `..`, or `|`
  |                 help: missing `,`

error[E0531]: cannot find tuple struct or tuple variant `to_owned` in this scope
 --> src/lib.rs:5:18
  |
5 |         Foo("hi".to_owned()) => true,
  |                  ^^^^^^^^ not found in this scope

error[E0023]: this pattern has 2 fields, but the corresponding tuple struct has 1 field
 --> src/lib.rs:5:13
  |
1 | struct Foo(String);
  |            ------ tuple struct has 1 field
...
5 |         Foo("hi".to_owned()) => true,
  |             ^^^^ ^^^^^^^^^^ expected 1 field, found 2

Some errors have detailed explanations: E0023, E0531.
For more information about an error, try `rustc --explain E0023`.
error: could not compile `playground` (lib) due to 3 previous errors
```

### Desired output

```
Compiling playground v0.0.1 (/playground)
error[E0164]: expected tuple struct or tuple variant, found associated function `<&str as ToOwned>::to_owned`
 --> src/lib.rs:5:13
  |
5 |         Foo("hi".to_owned()) => true,
  |             ^^^^^^^^^^^^^^^ `fn` calls are not allowed in patterns
  |
  = help: for more information, visit https://doc.rust-lang.org/reference/patterns.html

For more information about this error, try `rustc --explain E0164`.
error: could not compile `playground` (lib) due to previous error
```

### Rationale and extra context

This error occured while I was doing an `assert!(matches!(...))` for a struct that doesn't implement `Eq`.

Using `String::new` gives better messages;
```
error[E0164]: expected tuple struct or tuple variant, found associated function `String::new`
 --> src/lib.rs:5:20
  |
5 |         Foo { bar: String::new("hi") } => true,
  |                    ^^^^^^^^^^^^^^^^^ `fn` calls are not allowed in patterns
  |
  = help: for more information, visit https://doc.rust-lang.org/book/ch18-00-patterns.html
  ```

Clippy gives the same error messages.

### Other cases

```Rust
struct Foo { bar: String }

fn bar(foo: Foo) -> bool {
    match foo {
        Foo { bar: "hi".to_owned() } => true,
        _ => false
    }
}
```

rustc output:
```
   Compiling playground v0.0.1 (/playground)
error: expected `,`
 --> src/lib.rs:5:24
  |
5 |         Foo { bar: "hi".to_owned() } => true,
  |         ---            ^
  |         |
  |         while parsing the fields for this pattern

error: could not compile `playground` (lib) due to previous error
```

Similar errors when using expressions such as `Foo(1 + 2)`.

**Comment by clubby789** [comment]
Looks like the same issue as #112593 (dot being recovered as a comma)

**Comment by Nadrieril** [comment]
I have limited experience with parsing but I know where I'd start on this.

[This](https://github.com/rust-lang/rust/blob/f45631b10f2199a7ef344a936af9eb60342c16ee/compiler/rustc_parse/src/parser/expr.rs#L3105-L3110) is where the pattern of a match arm is parsed. The idea would be, in the error case, to try to parse an expression and emit a better error message if that succeeds. [This code](https://github.com/rust-lang/rust/blob/f45631b10f2199a7ef344a936af9eb60342c16ee/compiler/rustc_parse/src/parser/expr.rs#L2991-L3007) is an example of "try to parse X and emit better error if that works". You want to do something similar, but try to parse an expression instead (I'm guessing with `self.parse_expr_res`). You'll also have to define a diagnostic struct (like `MissingCommaAfterMatchArm` in the example) with an appropriate message in [messages.ftl](https://github.com/rust-lang/rust/blob/f45631b10f2199a7ef344a936af9eb60342c16ee/compiler/rustc_parse/messages.ftl). (diagnostic structs are documented [in the dev-guide](https://rustc-dev-guide.rust-lang.org/diagnostics/diagnostic-structs.html)).

@clubby789 which issue did you mean? You accidentally linked to this one

@TaKO8Ki I'm unassigining you because it's been a few months, feel free to reassign yourself

**Comment by Nadrieril** [comment]
Great work @ShE3py! Thanks for taking the time to fix this
