### ISSUE TITLE
Associated const equality conflicts with associated type equality

### ISSUE THREAD

**Issue by mversic** [rust-lang/rust#112560]
I tried this code and it compiled:
```rust
trait Trait2 {}

trait Trait1 {
    const A: u32;
    type A;
}

impl<T: Trait1<A = u32>, const N: usize> Trait2 for [T; N] {}

fn main() {}
```
Then I tried this code and it didn't compile:

```rust
#![feature(associated_const_equality)]

trait Trait2 {}

trait Trait1 {
    const A: u32;
    type A;
}

impl<T: Trait1<A = 12>, const N: usize> Trait2 for [T; N] {}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (37998ab50 2023-06-11)
binary: rustc
commit-hash: 37998ab508d5d9fa0d465d7b535dc673087dda8f
commit-date: 2023-06-11
host: aarch64-apple-darwin
release: 1.72.0-nightly
LLVM version: 16.0.5
```

<details><summary>Backtrace</summary>
<p>

```
error: expected associated type bound, found constant
  --> src/main.rs:10:16
   |
10 | impl<T: Trait1<A = 12>, const N: usize> Trait2 for [T; N] {}
   |                ^^^^^^
   |
note: associated type defined here
  --> src/main.rs:5:5
   |
5  |     type A;
   |     ^^^^^^

error: could not compile `proba2` (bin "proba2") due to previous error
```

</p>
</details>

### Explanation

Rust allows for associated const parameter and associated type parameter to have the same name. So, I expected there would be some way to disambiguate which one I'm referring to when setting the equality constraint but haven't found a way to do so.

This problem is related to [Associated Const Equality](https://github.com/rust-lang/rust/issues/92827)

**Comment by fmease** [comment]
Added T-compiler since this particular code could be accepted by making the `AssocKind` passed to `trait_defines_associated_item_named` dependent on the term kind (type or constant) of the binding in `<dyn AstConv<'_>>::add_predicates_for_ast_type_binding`.

Added T-lang since in the future, we might want to allow `Trait<Const = path::to::Const>` (i.e., allowing the user to omit the curly braces and allowing paths to resolve to *either* type *or* const) in which case, it would very much become ambiguous.

**Comment by Jules-Bertholet** [comment]
Perhaps a `const` prefix could be required to disambiguate? (`T: Trait1<A = u32, const A = 16>`)

**Comment by mversic** [comment]
IMHO I would disallow types and consts to have the same name as in this example:
```rs
trait Trait1 {
    const N: u32;
    type N;
}
```

since this is not allowed:
```rs
trait Trait1<N, const N: usize> {}
```
