### ISSUE TITLE
Should associated type bounds on supertraits be implied?

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/rust#112573]
I tried [this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=937d5a302838df7e7e1fdcf4ddee579a):

```rust
#![feature(associated_type_bounds)]

trait Trait: Super<Assoc: Bound> {}

trait Super {
    type Assoc;
}

trait Bound {}

fn foo<T>(x: T) where T: Trait {}
```

And this happened:

```
error[E0277]: the trait bound `<T as Super>::Assoc: Bound` is not satisfied
  --> src/lib.rs:13:8
   |
13 |     T: Trait,
   |        ^^^^^ the trait `Bound` is not implemented for `<T as Super>::Assoc`
   |
note: required by a bound in `Trait`
  --> src/lib.rs:3:27
   |
3  | trait Trait: Super<Assoc: Bound> {}
   |                           ^^^^^ required by this bound in `Trait`
help: consider further restricting the associated type
   |
13 |     T: Trait, <T as Super>::Assoc: Bound
   |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0277`.
```

I'm not exactly sure whether this should be implied or not! Nominating this for T-lang for discussion, I'd like to know whether this is expected behavior or not.

### Argument for the code failing

For non trait aliases, we don't imply currently any where clauses for non-supertrait bounds. In this case, supertrait bounds are precisely trait and associated type bounds which have `Self` as their self type. Since we can interpret `Self: Super<Assoc: Bound>` as two bounds -- `Self: Super` and `<Self as Super>::Assoc: Bound` -- it's consistent why the latter is not implied.

Fixing this complicates the code even more.

### Argument for the code compiling

The concept of "supertraits" from a language perspective (and not a types perspective) is not very well specified -- one may argue again that it could mean anything that comes after the colon in `trait Trait: ...` or `Self: ...`, for example. Whether or not that's more intuitive, 🤷 

It's also just annoying that this doesn't compile, and who knows if associated type bounds (which I'm personally motivated to compile) becomes more frustrating and/or less useful without these bounds being implied.

---

Related to #112568, which is essentially the same question but for return type notation.

**Comment by fmease** [comment]
#110512 may also provide some additional background information.

(Not that I have any say in this but I found implying the assoc type bounds on super trait quite useful and intuitive. In a project of mine, https://github.com/fmease/lushui, I used to make use of this until the aforementioned PR removed them. I had to enable & use trait aliases to achieve the same level of conciseness)

**Comment by compiler-errors** [comment]
Sorry about that @fmease 😆  -- #110512 was intended to fix pretty bad ICEs with the associated-type-bounds feature, and it intentionally regressed the code which is given in my examples above because I didn't really want to take a firm stance on the question above.

**Comment by tmandry** [comment]
The RFC for associated type bounds chose a [particular desugaring](https://rust-lang.github.io/rfcs/2289-associated-type-bounds.html#the-desugaring-for-associated-types) when they are used in associated types to [so that they would have](https://rust-lang.github.io/rfcs/2289-associated-type-bounds.html#an-alternative-desugaring-of-bounds-on-associated-types) "implied bounds" behavior, so that's evidence that this kind of behavior is desired.

We also have the RFC for full [implied bounds](https://rust-lang.github.io/rfcs/2089-implied-bounds.html) which is further evidence that it's _desired_, and I think the question then becomes whether we want to stabilize this before all of implied bounds.

@compiler-errors My understanding is that general implied bounds is blocked behind implementation feasibility, and it seems we don't have those same issues with this feature, correct?
