### ISSUE TITLE
Implement ConstParamTy for Option<T> where T: ConstParamTy

### ISSUE THREAD

**Issue by haennes** [rust-lang/rust#113075]
Disclaimer: This is the first time opening an issue in a project this big. I am not a native speaker.

I found it quite unintuitive when working with const parameters that ConstParamTy is not implemented for the Option type.
Would it make sense to derive it similar to how it is done with most of the core types?

Hope this isn´t a dumb idea. If so feel free to just close this issue.

**Comment by compiler-errors** [comment]
cc @BoxyUwU

**Comment by workingjubilee** [comment]
@BoxyUwU Is `adt_const_params` ready to consider extension via new implementations of the relevant marker trait at this time?

**Comment by BoxyUwU** [comment]
Implementation wise there's no reason why `Option<T>` couldn't implement `ConstParamTy` when `T` does too, infact it probably makes sense to have this impl eventually.

Personally I would like to avoid having stabilization of `adt_const_params` also involve stabilizing a bunch of impls on std types so I think that we should not add this impl. Also right now we might still change how `ConstParamTy` works and doing so might require changing all impls of the trait which would be really annoying to do if there are a tonne of std impls, so at minimum adding lots of std impls should likely wait until closer to stabilization.

If it was possible to feature gate impls then I think it'd be nice to have a `adt_const_params_plus_std_impls` gate or something but right now that's not possible.

**Comment by workingjubilee** [comment]
I see! Sounds like we should not do this then, since it sounds like `ConstParamTy` might not even exist a month from now, and if it does, it might look different enough any decisions we make now don't necessarily carry over to that version. Closing! We can discuss this as part of an [API expansion proposal](https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&projects=&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29) later.
