### ISSUE TITLE
Raw pointer cast triggers "lifetime may not live long enough"

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-lang/rust#113257]
I tried this code:

```rust
struct Foo<'a>(&'a ());

fn foo(v: *const Foo<'_>) -> *const Foo<'static> {
    v as *const Foo<'static>
}
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=f2f7b3d9c228a4d9d77a711a5cae6691).

I expected to see this happen: it compiles, since raw pointer casts should be allowed even for completely different types.

Instead, this happened: it fails with:
```
error: lifetime may not live long enough
 --> src/lib.rs:4:5
  |
3 | fn foo(v: *const Foo<'_>) -> *const Foo<'static> {
  |        - has type `*const Foo<'1>`
4 |     v as *const Foo<'static>
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ type annotation requires that `'1` must outlive `'static`
```
It looks like for some reason the compiler creates a lifetime obligation here.

Strangely, it works with `cast()`:
```rust
fn foo(v: *const Foo<'_>) -> *const Foo<'static> {
    v.cast::<Foo<'static>>()
}
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=3e808e171876b9cd2d0c7bb2a190b5a3).

**Comment by Nilstrieb** [comment]
I've looked into this. The issue is that typeck considers this cast to be a "coercion cast", because typeck thinks that you could replace the function body with just `v` since the types are the same (it also triggers the `trivial_casts` lint (allow-by-default)). HIR typeck isn't aware of lifetimes. So then THIR building and MIR building build MIR that doesn't contain a `PtrToPtr` cast but instead just assigns one to the other. The borrow checker is rightfully not pleased.

The bug here is that the THIR does not contain an explicit cast anymore. I'm not sure how to best fix this, as the current logic for "is this a no-op cast (called coercion cast in the code)" is just "try to coerce the types in the same way that happens on coercion sites and if it works it has to be useless". Which is wrong in the presence of lifetimes.

It seems like the current strategy works this way because it reuses some code in THIR building.

Thinking about it a little more, this is very special to pointer casts, because only pointer casts are allowed to change the type like this. Maybe THIR building should just special case pointer casts to always be emitted?

**Comment by RalfJung** [comment]
Unfortunately due to this bug there is [a `transmute` in the standard library](https://github.com/rust-lang/rust/blob/852bf4e51bf260550cd1a280d2146f1c0641b1e8/library/std/src/thread/mod.rs#L565-L567) that should be turned into a raw pointer cast, but we cannot.

**Comment by Nilstrieb** [comment]
I think that's a different case, these are boxes and not raw pointers, and box->box casts are not allowed to do arbitrary changes (and are in fact coercion casts, so the `as` doesn't actually do anything). The error there is correct and this needs a transmute.

**Comment by RalfJung** [comment]
@Nilstrieb I'd like to replace the transmutes by raw pointer casts, which IMO is much preferable, similar to https://github.com/rust-lang/rust/pull/114799. But this bug is in the way of that.

**Comment by fmease** [comment]
Duplicate of #27214 (2015) :P I will close the OG as fixed :)
