### ISSUE TITLE
Suggest ".clone" for "use of moved value" if the thing is cloneable

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#11345]
This might help alleviate some confusion.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
