### ISSUE TITLE
rustc can't read files with more than one dot in filename

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#113981]
```bash
echo "pub fn main() {}" > a.b.rs
rustc a.b.rs
```
```
error: invalid character `'.'` in crate name: `a.b`
```

Why would rustc think this is related to crates when I just pass a simple path into it?

**Comment by ehuss** [comment]
Rustc has to infer the crate name when you don't specify it with `--crate-name`, or with `#![crate_name="…"]`. It is not as important for a binary compared to a library (since you can't directly import a binary), but it still appears in some circumstances like symbols, debuginfo, some diagnostics, and macros, and still needs to be well-formed.

**Comment by matthiaskrgr** [comment]
Hmm, so it assumes `{crate_name}.rs` which would in this case be "a.b" which is not a valid crate name?
It would be nice to have some help message for the a.b.rs case which hints to usage of either `--crate-name` or `#![crate_name="…"]` :slightly_smiling_face:
