### ISSUE TITLE
Broken MIR in DropGlue when compiling anyhow with -Zvalidate-mir

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#114437]
`cargo bisect-rustc` says this but I'm not sure I believe it:

Regression in https://github.com/rust-lang-ci/rust/commit/cda7b6d23b278697bf0cb457e00d594dd4a8a33b

searched nightlies: from nightly-2023-07-01 to nightly-2023-08-02
regressed nightly: nightly-2023-08-01
searched commit range: https://github.com/rust-lang/rust/compare/a17c7968b727d8413801961fc4e89869b6ab00d3...db7ff98a72f3e742b641f9cb16d0e8c285e87e9b
regressed commit: https://github.com/rust-lang/rust/commit/dfc9d3fee67c1323c396b001197126dbcfa9890e

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2023-07-01 --end 2023-08-02 --script script --regress ice 
```
</details>

The script is just
```
RUSTFLAGS=-Zvalidate-mir cargo install cargo-deny --force
```

[rustc-ice-2023-08-03T21:06:49.028857617Z-2267460.txt](https://github.com/rust-lang/rust/files/12255264/rustc-ice-2023-08-03T21.06.49.028857617Z-2267460.txt)

```
error: internal compiler error: broken MIR in DropGlue(DefId(2:2152 ~ core[d518]::ptr::drop_in_place), Some(std::backtrace::Inner)) (after pass AbortUnwindingCalls) at bb2[0]:
                                Field projection `PlaceRef { local: _1, projection: [Deref, Downcast(Some("Captured"), 2)] }.0` specified type `std::sync::LazyLock<std::backtrace::Capture, [closure@std::backtrace::lazy_resolve::{closure#0}]>`, but actual type is `std::sync::LazyLock<std::backtrace::Capture, std::backtrace::LazyResolve>`
   --> /home/ben/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:497:1
    |
497 | pub unsafe fn drop_in_place<T: ?Sized>(to_drop: *mut T) {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:76:25
```

**Comment by matthiaskrgr** [comment]
duplicate of https://github.com/rust-lang/rust/issues/114375 ?

**Comment by lukas-code** [comment]
> `cargo bisect-rustc` says this but I'm not sure I believe it:

Bisect points to https://github.com/rust-lang/rust/pull/109075, because that's where [this TAIT pattern](https://github.com/rust-lang/rust/issues/114375#issuecomment-1662836185) got added to std.

Bisecting the reduced example points me to https://github.com/rust-lang/rust/pull/112777.

<details>

Regression in https://github.com/rust-lang-ci/rust/commit/9cf74a0f380df8ffc43534bd52e8c35e16339873

searched nightlies: from nightly-2023-06-13 to nightly-2023-08-02
regressed nightly: nightly-2023-06-20
searched commit range: https://github.com/rust-lang/rust/compare/2d0aa57684e10f7b3d3fe740ee18d431181583ad...fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2
regressed commit: https://github.com/rust-lang/rust/commit/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc -- rustc -- -Z validate-mir 
```
</details>

</details>

**Comment by saethlin** [comment]
This was a duplicate, and it's fixed.
