### ISSUE TITLE
Compiler ignores `'static` bound on associated type

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-lang/rust#114801]
I tried this code:

```rust
pub trait Callback<T> {
    type CallbackResult: 'static;

    fn call(self, v: T) -> Self::CallbackResult;
}

trait MyTrait {
    fn func<C>(&self, callback: C) -> <C as Callback<&i32>>::CallbackResult
    where
        C: for<'a> Callback<&'a i32>;
}

struct MyStruct {}
impl MyTrait for MyStruct {
    fn func<C>(&self, callback: C) -> <C as Callback<&i32>>::CallbackResult
    where
        C: for<'a> Callback<&'a i32>,
    {
        let v = 42;
        callback.call(&v)
    }
}
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d0134081714865054ba306eb723dc55c).

I expected to see this happen: the code compiles successfullly, since `CallbackResult` cannot borrow from the argument as it is `'static`

Instead, this happened: an error:
```
error: cannot return value referencing local variable `v`
  --> src/lib.rs:20:9
   |
20 |         callback.call(&v)
   |         ^^^^^^^^^^^^^^--^
   |         |             |
   |         |             `v` is borrowed here
   |         returns a value referencing data owned by the current function
```

**Comment by smessmer** [comment]
More details: https://stackoverflow.com/questions/76895814/tell-the-compiler-that-a-generic-return-type-doesnt-borrow-any-references-to-ar

**Comment by compiler-errors** [comment]
The type that the expression `callback.call(&v)` evaluates to is `<C as Callback<&'v i32>>::CallbackResult`, where we can call the lifetime of the `&v` borrow "`'v`".

The return type of the function is `<C as Callback<&'s i32>>::CallbackResult`, where `'s` is the lifetime of the `&self` parameter in the function signature.

When you return the expression, its type is equated[^1] with the return type. All trait (and GAT) generics are invariant, so this requires that the lifetimes `'v == 's`. 

This raises an error in borrowck, since the lifetime of the temporary `&v` borrow cannot be as long as `'s`, which must live longer than the function. That's what it's trying to summarize in "cannot return value referencing local variable", since it tries to find something to call that `'v` lifetime since it's not explicitly nameable, and in this case, we just call it the variable the borrow comes from.

---

The fact that the associated type must outlive `'static` doesn't change much, since the issue here is with relating associated types and their generics. The solution to this problem is to introduce a new type parameter:

```
pub trait Callback<T> {
    type CallbackResult: 'static;

    fn call(self, v: T) -> Self::CallbackResult;
}

trait MyTrait {
    fn func<C, R>(&self, callback: C) -> <C as Callback<&i32>>::CallbackResult
    where
        C: for<'a> Callback<&'a i32, CallbackResult = R>;
}

struct MyStruct {}
impl MyTrait for MyStruct {
    fn func<C, R>(&self, callback: C) -> <C as Callback<&i32>>::CallbackResult
    where
        C: for<'a> Callback<&'a i32, CallbackResult = R>,
    {
        let v = 42;
        callback.call(&v)
    }
}
```

To fix this at the type system level, we would need to get a lot more sophisticated with the variance computation for associated types, for example, considering facts like `type Ty: 'static` to "disqualify" generics in scope from being captured by the associated type. I don't think this is possible, or at least doesn't seem feasible without a lot of correctness reasoning and work in the type system.

[^1]: actually subtyped, but this doesn't matter bc invariance
