### ISSUE TITLE
error: manifest path `/public/home/litz/mysw/rust-31032ecb1550a402a726e9c244f6a716b214cc9d/src/tools/cargo/Cargo.toml` does not exist

### ISSUE THREAD

**Issue by lukin35** [rust-lang/rust#115041]
here are what I have done to install rust from source, and I am new in rust. can someone offer me some help about this error and give me detailed instruction on  how to install rust from source correctly?
1. I download the zip file to /public/home/litz/mysw
2. unzip the zip file in the same dir
3. `cd ./rust-31032ecb1550a402a726e9c244f6a716b214cc9d`
4. `./configure --set install.prefix=/public/home/litz/mysw/rust`
5. `./x.py build && ./x.py install`
6. exit with the error
```
error: manifest path `/public/home/likun/mysw/rust-31032ecb1550a402a726e9c244f6a716b214cc9d/src/tools/cargo/Cargo.toml` does not exist
thread 'main' panicked at 'command did not execute successfully: RUSTC_BOOTSTRAP="1" "/public/home/litz/mysw/rust-31032ecb1550a402a726e9c244f6a716b214cc9d/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "metadata" "--format-version" "1" "--no-deps" "--manifest-path" "/public/home/litz/mysw/rust-31032ecb1550a402a726e9c244f6a716b214cc9d/src/tools/cargo/Cargo.toml"
```

**Comment by gemesa** [comment]
did you check out the submodules? i encountered a similar error message and it solved my issues:

```
git submodule init
git submodule update
```

**Comment by onur-ozkan** [comment]
It seems like you are downloading the source as a zip file without using Git. During the bootstrapping, we fetch the submodules before invoking Cargo on those paths. However, in your case, since your source doesn't have Git, you don't get the submodules. We should definitely provide better error message for such situations. Thanks for reporting this!

> How to install rust from source correctly?

If you haven't read, there is https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html?highlight=build#get-the-source-code.

If you don't want to use git, then you can download dist tarballs from static.rust-lang.org(e.g., `wget "https://static.rust-lang.org/dist/2023-08-24/rustc-1.72.0-src.tar.xz`) which includes submodules out of the box(so you don't need to fetch them with git).
