### ISSUE TITLE
`opt-level=z` fails to remove bounds checks/panics even if every other opt-level succeeds

### ISSUE THREAD

**Issue by thomcc** [rust-lang/rust#115463]
If compiling with `-Copt-level=z` we fail to remove bounds checks and panicking branches in code like this (godbolt <https://godbolt.org/z/YsoMszxPe>):

```rust
pub fn read_up_to_8(buf: &[u8]) -> u64 {
    if buf.len() < 4 {
        // actual instance has more code.
        return 0;
    }
    let lo = u32::from_le_bytes(buf[..4].try_into().unwrap()) as u64;
    let hi = u32::from_le_bytes(buf[buf.len() - 4..][..4].try_into().unwrap()) as u64;
    lo | (hi << 8 * (buf.len() as u64 - 4))
}
```

Unfortunately, while `-Copt-levels=[123s]` all manage to remove the panic branches, `-Copt-level=z` does not, leading to a lot more code and significantly worse performance.

Note that we do manage to remove it in cases where the function does less stuff -- it's removed entirely in simple examples that do nothing other than load the value from a slice. However, in real code, (perhaps after a layer of inlining) you tend to have a couple of these in a function, and this issue seems to crop up again[^1].

[^1]: Although not 100% reliably -- having trouble reproducing on godbolt, but it seems like it's happening in real-world code.

Given that this pattern is more or less the recommended "safe" way to read a u32 out of a &[u8], this seems unfortunate to me.

**Comment by scottmcm** [comment]
I see two problems here:

1. It looks like the `unwrap` isn't inlined, and the *check* part of an unwrap probably always should be -- looking at the discriminant of a Result/Option is trivial, and would probably optimize out enough to be worth doing even in `-Oz`, with just the `cold` part of triggering the panic outlined.

2. We need better methods for getting arrays out of slices.  For example, writing this with `first_chunk` and `last_chunk` (<https://godbolt.org/z/9qx3o9b76>) from #111774, instead of the manual length check, makes it work.

**Comment by thomcc** [comment]
Is there a reason to assume `s.first_chunk::<4>().unwrap()` would optimize better than `s.try_into().unwrap()`? It isn't clear to me why this would be.

**Comment by scottmcm** [comment]
If there's an `unwrap` in both, then no, I'm not super-confident in it.  But if it can be rephrased to not need the unwrap at all -- replacing the length check that needs deduping with the `if let Some(` -- then yes, I'd expect it to work better.

Have you perchance looked at `-Os`?  I don't really know what the difference is between `s` and `z` for us or for LLVM, but it also wouldn't surprise me if `z` is incredibly unwilling to inline stuff.

**Comment by thomcc** [comment]
Yes -Os is fine (I mentioned as much above). The only two opt-levels with issues here are 0 (which is expected) and z (which is not).

Note that in practice using if-let is viable for this version of the function, but it usually is not viable for this pattern.

**Comment by scottmcm** [comment]
(Since I ended up on this many moons later) [`as_chunks`](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.as_chunks) and [`first_chunk`](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.first_chunk) and friends are now stable, so using those avoid the `.try_into().unwrap()` steps entirely.
