### ISSUE TITLE
Officially provide the Rust logo

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/rust#11562]
There is some interest in handing out things with the Rust logo, see https://mail.mozilla.org/pipermail/rust-dev/2014-January/007987.html

Please provide a page with the Rust logo in SVG and a suitable copyright notice.
There is http://en.wikipedia.org/wiki/File:Rust_programming_language_black_logo.svg taken from http://www.rust-lang.org/logos/rust-logo-blk.svg
A copyright/license statement is missing though.

Are people allowed to print their own T-shirts and stickers?

**Comment by zsiciarz** [comment]
+1 for a documented name and logo usage policy. For example - if I wanted to create a logo for a Rust user group, can it be derived from, say, https://github.com/rust-lang/rust-www/blob/gh-pages/logos/rust-logo-blk.svg? As @brson mentions it's CC-BY so I guess it's ok as long as I state that the original logo comes from the Rust project. However a page similar to [Python Software Foundation trademark usage policy](https://www.python.org/psf/trademarks/) would be great in making that clear in such cases.

**Comment by ddamko** [comment]
Ok so I created a t-shirt for the Rust community on Teespring http://teespring.com/rust . 100% of profits will be donated to Mozilla. I need to find out if this is Ok with Mozilla otherwise I need to stop the campaign. Please point me to some one who might have some advice from legal on this.

If I do need to stop this. I would like to get this shirt out there for the community but I cannot afford the printing costs myself. What other options could there be?

**Comment by dherman** [comment]
Hi all, sorry we've let this go unresolved. Trademark (not the same as copyright) is important because it protects the community from inappropriate uses of official Rust names and logos. Uses of the trademark do have some constraints in order to protect against these cases, which unfortunately sometimes means restrictions on good faith, well-intentioned uses.

I'm working with the core team and Mozilla's trademark folks to provide better clarity around these questions, and we're intending to put together a web page that explains Rust's specific policies for trademark. We'll post updates here.

**Comment by BigBoneDaddy** [comment]
@dherman Do you have good update for us?

**Comment by steveklabnik** [comment]
There's a bug filed with Mozilla's legal team, they've been slow to respond though :(

**Comment by edunham** [comment]
Also I just noticed that a modified version of the Rust logo is being sold in the StickerMule marketplace: https://www.stickermule.com/marketplace/3726-rust-logo . According to the byline of the marketplace, "The Sticker Mule marketplace is the easiest way to buy and sell stickers. All of our customers can sell their stickers at no cost. We ship directly to buyers and you keep the profit." 

Just another reason we need to clarify the guidelines on whether people are allowed to remix the logo and profit from merchandise of it.

**Comment by sethlopezme** [comment]
Just wanted to point out that the Rust logo does now appear in the [List of Mozilla Trademarks](https://www.mozilla.org/en-US/foundation/trademarks/list/), so I would assume the [Mozilla Trademark Policy](https://www.mozilla.org/en-US/foundation/trademarks/policy/) applies.

**Comment by BigBoneDaddy** [comment]
@sethlopezme Maybe we have confirmation from Mozilla instead of assume? @steveklabnik can you use influence at Mozilla to get answer faster?

**Comment by shmerl** [comment]
Is there an SVG version of the brown Rust logo? Above only b&w version is listed in SVG format.

**Comment by dpc** [comment]
So what's the status of this? I'm thinking of buying a Rust laptop sticker  from stickermule, and I'm wondering if it's cool with everyone or not.

**Comment by Facens** [comment]
Hi all, I represent www.unixstickers.com which already manufactures stickers with the most popular logos and designs. All the designs we use are licensed and we already have deals with most of the unix/sw/opensource projects. We have a lot of request for Rust stickers and we actually have the Rust stickers launch scheduled for this Thursday since from this topic –  when we checked – commercial use seemed to be allowed. Our stickers will use the original logo without modifications. Can you confirm this to be legit? Can anyone get in touch (andrea@unixstickers.com) to understand how we could collaborate? Also let us know if we should have the modified sticker removed from Sticker Mule, as our team works closely with Sticker Mule and we're 100% available to do anything necessary to respect your rights : )

**Comment by steveklabnik** [comment]
The status is, we have a proposed draft we're working on, but we're not quite ready for it yet.

**Comment by aturon** [comment]
Cross-posted from [discuss](https://internals.rust-lang.org/t/rust-trademark-policy/2592). Sorry for the long wait on this!

====

The core team has been working for some time to hammer out a policy for Rust's trademarks -- which are distinct from the *copyright* policy surrounding the code and logos. In particular, while copyright governs how an artifact can be copied and modified, trademark talks about ways that a particular "brand" can be applied. (Look [here](http://www.ifosslr.org/ifosslr/article/view/11/38) if you want a long read about open source and trademarks.)

You can read our policy [here](https://www.rust-lang.org/legal.html).

> Note, the website's new invalidation system may mean you see a stale, misformatted copy of this page. Hopefully the final version will hit all of the caches soon! You can also read directly at https://github.com/rust-lang/rust-www/blob/master/legal.md

The basic news here is that we are adopting a pretty liberal stance around Rust's trademarks, allowing our logos and names to be applied, even in modified form, in many contexts -- so long as the use does not imply official endorsement by or affiliation with the Rust project. (Commercial uses need to check in so we can confirm this is the case, before money is ever involved.)

That's the TL;DR, but please read the full policy to understand the role that trademark plays, and the nuances of our approach.

====

I'm going to close this issue, because we're now officially providing the logos from the site, as well as the various legal policies surrounding them. However, I'm glad to keep the discussion going about these policies, both here, on discuss, or via email.

**Comment by aturon** [comment]
Also, we've reached out in response to all pending requests about usage, as far as I know, but if you have unanswered questions on this topic, please let me or another core team member know!

**Comment by jhpratt** [comment]
@aturon @brson Any chance there's a "shell" logo svg, which is just the gear and no "R"? All that's linked above is one with the ® and the teeth separate.

**Comment by JounQin** [comment]
No official Rustaceans logo?
