### ISSUE TITLE
regression: concrete type differs from previous defining opaque type use

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#115781]
```
[INFO] [stdout] error: concrete type differs from previous defining opaque type use
[INFO] [stdout]    --> src/execution.rs:222:13
[INFO] [stdout]     |
[INFO] [stdout] 222 |             impl Iterator<Item = Node<'tree>> + 's,
[INFO] [stdout]     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout]     |             |
[INFO] [stdout]     |             expected `impl Iterator<Item = tree_sitter::Node<'tree>> + 'tree`, got `impl Iterator<Item = tree_sitter::Node<'s>> + 's`
[INFO] [stdout]     |             this expression supplies two conflicting concrete types for the same opaque type
```

https://crater-reports.s3.amazonaws.com/beta-1.73-1.2/beta-2023-09-10/reg/tree-sitter-graph-0.11.0/log.txt

**Comment by apiraino** [comment]
this regressed in 0dd5730e0f2cb73ff673c3cd0c9897bc2b5d6425:

- #112995 (Check for `<&NotClone as Clone>::clone()` calls and suggest to add Clone trait appropriately)
 - https://github.com/rust-lang/rust/pull/113578 (Don't say that a type is uncallable if its fn signature has errors in it)
 - https://github.com/rust-lang/rust/pull/113661 (Double check that hidden types match the expected hidden type)
 - https://github.com/rust-lang/rust/pull/114044 (factor out more stable impls)
 - https://github.com/rust-lang/rust/pull/114062 (CI: split nested GHA groups instead of panicking)

The exact commit is not available anymore (`0ae3a8e2ad80d9e375cb8f391bfb0e5e57d10515`) but by reading the tests of #113578 I think this is where it originated and (if I understand) is the intended behaviour i.e. introduce an error to fix an unsoundness (cc @oli-obk )

**Comment by oli-obk** [comment]
hmm... that PR was only supposed to fix a type_alias_impl_trait unsoundness, not have any effect on stable crates and RPIT. I'll investigate

**Comment by apiraino** [comment]
@oli-obk my apologies! I mistyped the PR that I thought was the source of the regression. Commit `0ae3a8e2ad80d9e375cb8f391bfb0e5e57d10515` leads to #113661 as it can be inferred by the perf build results of the rollup merge in [comment](https://github.com/rust-lang/rust/pull/114076#issuecomment-1650788008) (a trick I've learned today).

**Comment by oli-obk** [comment]
beta backported a fix in https://github.com/rust-lang/rust/pull/116044
