### ISSUE TITLE
1.72.1 is not released on GitHub

### ISSUE THREAD

**Issue by sksat** [rust-lang/rust#115976]
The 1.72.1 release was announced: https://blog.rust-lang.org/2023/09/19/Rust-1.72.1.html
Actually, this tag exists: https://github.com/rust-lang/rust/releases/tag/1.72.1

However, this version does not seem to exist in GitHub Releases: https://github.com/rust-lang/rust/releases
It seems that this operation is usually done by a [bot](https://github.com/rustbot), so is there some problem with the automated release procedure?

**Comment by Mark-Simulacrum** [comment]
I suspect we need to copy the release notes to master.

**Comment by fmease** [comment]
https://github.com/rust-lang/rust/releases/tag/1.72.1

**Comment by frederikrothenberger** [comment]
@fmease: Why is the release not marked as `latest`? What is the authoritative source of the `latest` version?

**Comment by fmease** [comment]
Good catch! At the moment, 1.71.1 is flagged as `latest` presumably since the release notes for 1.71.1 (#115997) were merged several hours *after* the ones for 1.72.1 (#115978).

I'm not a T-release member and I'm not super familiar with GitHub releases.
@Mark-Simulacrum, is there a simple way to mark 1.72.1 as `latest`?

**Comment by Mark-Simulacrum** [comment]
Should be fixed.
