### ISSUE TITLE
error[E0599]: the function or associated item `new` exists for struct `Box<dyn Display>`, but its trait bounds were not satisfied

### ISSUE THREAD

**Issue by kzhui125** [rust-lang/rust#116095]
this compile:

```rs
let bp: Box<dyn Display> = Box::new(Point(30, 40));
```

this compile error:

```rs
let bp = Box::<dyn Display>::new(Point(30, 40));
```

I think they are the same, should all compile.

**Comment by kadiwa4** [comment]
They are not the same. In the first example, you create a `Box<Point>` by calling `Box::<Point>::new` and then it gets unsize-coerced into a `Box<dyn Display>`. In the second example you try to do the unsize-coercion first and then try to pass the unsized value into `Box::<dyn Display>::new`. But you can't, because function arguments always have to be `Sized`, hence there is a (hidden) `T: Sized` trait bound on the function.

**Comment by kzhui125** [comment]
thanks @kadiwa4
