### ISSUE TITLE
decl_macro. no field `0` on type. a field with a similar name exists: `0`

### ISSUE THREAD

**Issue by planetoryd** [rust-lang/rust#116334]
I tried this code:

https://github.com/planetoryd/rust_bug_missing_field

```rust
#![feature(decl_macro)]

make_struct!(Uh);

macro make_struct ($id:ident) {
    pub struct $id(pub i32);
}

fn main() {
    let k = Uh(2);
    println!("{}", k.0);
}
```

The equivalent code without macro works.

```rust
hash@hash-pc /s/e/missing_field (master)> cargo b
   Compiling missing_field v0.1.0 (/space/experim/missing_field)
error[E0609]: no field `0` on type `Uh`
  --> src/main.rs:11:22
   |
11 |     println!("{}", k.0);
   |                      ^ help: a field with a similar name exists: `0`

For more information about this error, try `rustc --explain E0609`.
error: could not compile `missing_field` (bin "missing_field") due to previous error
warning: build failed, waiting for other jobs to finish...
```

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0-nightly (e0d7ed1f4 2023-10-01)
binary: rustc
commit-hash: e0d7ed1f453fb54578cc96dfea859b0e7be15016
commit-date: 2023-10-01
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: **17.0.2**
```

**Comment by planetoryd** [comment]
Methods don't work either.

**Comment by fmease** [comment]
This works as intended, this is [macro hygiene](https://en.wikipedia.org/wiki/Hygienic_macro) at play. The tuple field `0` declared inside the `macro` is *invisible* to the outside world.

Typically if you'd like to make such an identifier accessible, you'd turn it into a parameter like `$field:ident`. However, for tuple structs, I don't actually know if there's a way to do that :/

To elaborate, the (implicit) identifier `0` inside `macro` is different from the identifier `0` found in `main`, the differ by *syntactic context*. For example, [in this playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4f03d367489caa608ec233159f8b7510) I seemingly define a struct with two (!) fields `field` which works because they live in a different context.

**Comment by fmease** [comment]
If you're fine with changing your tuple struct into a normal struct, then you can fix your code like this: [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=db4a4c03d4e674b5818720f9e4406df4).

Alternatively, you can turn the macro 2.0 into a `macro_rules!` macro which follows different hygiene rules.
