### ISSUE TITLE
Add contributors section in readme.md file

### ISSUE THREAD

**Issue by kaustab28** [rust-lang/rust#116544]
I want to add the list of contributers in the Readme.md file.

And also add a "back to top" button at the bottom of readme which will scroll to top on clicking.

**Comment by matthiaskrgr** [comment]
There are around 5.000 contributors, this is not anything that should be put into a readme, I also doubt anyone is going to read this from top to bottom.

https://thanks.rust-lang.org/rust/all-time/ exists for this purpose

**Comment by fmease** [comment]
Thanks for your interest in contributing to rust-lang/rust! As matthiaskrgr has mentioned, we already have https://thanks.rust-lang.org/ for this purpose which is strictly supervisor since it updates almost live and includes not only this repository but several others, too.

Using the README for this purpose isn't feasible since it would need to be continuously updated and it would worsen the time takes to fully render the front page of this repo.

Closing
