### ISSUE TITLE
OpenBSD socket address is padded with zeroes

### ISSUE THREAD

**Issue by notgull** [rust-lang/rust#116523]
I tried this code on my Linux machine:

```rust
use std::os::unix::net::UnixListener;

fn main() {
    let listener = UnixListener::bind("/tmp/rust-uds.sock").unwrap();
    println!("{:?}", listener.local_addr().unwrap());
}
```

I got this output:

```
"/tmp/rust-uds.sock" (pathname)
```

However, on OpenBSD 7, I got this output:

```
"/tmp/rust-uds.sock\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0" (pathname)
```

I expected the output to be the same as Linux: not padded with zeroes like this.

### Meta

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.63.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-openbsd
release: 1.63.0
LLVM version: 13.0.0
```

**Comment by notgull** [comment]
This is an OpenBSD bug. I've reported it here: https://marc.info/?l=openbsd-bugs&m=170105481926736&w=2

Still, we should work around it in the standard library.

**Comment by cjeker** [comment]
Just to be clear, this is not an OpenBSD bug. OpenBSD decided to return always the full `struct sockaddr_un`. 
This is all within the specification of `getsockname` imposed by POSIX.
The embedded path `sun_path` inside `struct sockaddr_un` is always a valid C string (NUL terminated).
There is therefor no need to look at the `address_len` argument as long as the passed `sockaddr` buffer is at least `sizeof(struct sockaddr_un)` bytes. Developers are highly encouraged to use `struct sockaddr_storage` to ensure there is no clipping. The reason for this behavior is to reduce the risk of bugs because of the scary `getsockname` spec.
