### ISSUE TITLE
#116787 broke ui-fulldeps on stage1

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#116867]
Since https://github.com/rust-lang/rust/pull/116787
I ran `x test` with
```toml
profile = "compiler"
change-id = 115898

[llvm]
assertions = true
download-ci-llvm = true

[rust]
debuginfo-level = 1
incremental = false
debug = false
debug-logging = false
```

```
Testing stage0 compiletest suite=ui-fulldeps mode=ui (x86_64-unknown-linux-gnu)

running 54 tests
iiiiiiiiiiiiiiiiiiiiiiiiii........F...................

failures:

---- [ui] tests/ui-fulldeps/internal-lints/span_use_eq_ctxt.rs stdout ----

error: ui test compiled successfully!
status: exit status: 0
command: RUSTC_ICE="0" "/home/ben/rust/build/x86_64-unknown-linux-gnu/stage0/bin/rustc" "/home/ben/rust/tests/ui-fulldeps/internal-lints/span_use_eq_ctxt.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/home/ben/.cargo" "--sysroot" "/home/ben/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/home/ben/rust/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/internal-lints/span_use_eq_ctxt" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/home/ben/rust/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/ben/rust/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/internal-lints/span_use_eq_ctxt/auxiliary" "-Z" "unstable-options"
stdout: none
--- stderr -------------------------------
warning: unknown lint: `rustc::span_use_eq_ctxt`
  --> /home/ben/rust/tests/ui-fulldeps/internal-lints/span_use_eq_ctxt.rs:5:9
   |
LL | #![deny(rustc::span_use_eq_ctxt)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unknown_lints)]` on by default

warning: 1 warning emitted
------------------------------------------



failures:
    [ui] tests/ui-fulldeps/internal-lints/span_use_eq_ctxt.rs

test result: FAILED. 27 passed; 1 failed; 26 ignored; 0 measured; 0 filtered out; finished in 3.13s

Some tests failed in compiletest suite=ui-fulldeps mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
Build completed unsuccessfully in 0:03:15
```

**Comment by compiler-errors** [comment]
#116009 was supposed to prevent this :(

**Comment by a-lafrance** [comment]
Oh no, anything I can do to help fix this? Whether or not it's directly related to my changes, I'm happy to help with a fix.

**Comment by saethlin** [comment]
At a glance, it looks like the test for this is only run in PR CI? If that's true, then running the test there doesn't prevent this situation. If it's wrong, a good step would be bisecting or just going through all the commits in that rollup to see if anything jumps out when you run `x test ui-fulldeps`.

**Comment by a-lafrance** [comment]
My understanding is that that's caused by stage1 `ui-fulldeps` actually running the stage0 compiler, not the stage1 compiler, which is why we're getting the unknown lint error (the first line in your test output seems to indicate this as well). I'm assuming there's a reason for this? I don't think it's a bug -- I can't remember where but at some point I read that that's expected behavior, I think.

I'm not sure how to proceed given that, though. If running stage0 instead of stage1 is a workaround to avoid some underlying issue, maybe it's worth trying to fix that, but other than that I'm not sure if there's a way to fix this other than waiting for stage0 to be updated for that PR. Not to say there isn't a way, I'm just not experienced enough to know it. If there's something that can be done, I can take care of it with a push in the right direction.

Thoughts?

**Comment by lqd** [comment]
> At a glance, it looks like the test for this is only run in PR CI

I believe it's the opposite, it's supposed to only run on merges not on PRs. The fun fact is that this test indeed failed https://github.com/rust-lang-ci/rust/actions/runs/6551562742/job/17793020957#step:24:18909
