### ISSUE TITLE
extend --dep-info flag with variant that emits just the list of files to stdout

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#11702]
For whipping up a quick makefile, I would prefer to be able to just call the command to generate the list of filenames.

The current workaround, AFAICT, would be to generate the dep-info to a temporary file, and then parse the that output to remove the `target-filename: ` prefix that comes before the list of deps.

**Comment by steveklabnik** [comment]
The original motivation here has been subsumed by Cargo, is this still something we would want?

**Comment by SiegeLord** [comment]
> The original motivation here has been subsumed by Cargo, is this still something we would want?

Not sure how, as Cargo can't generate makefiles. In many ways, a makefile is still easier/less intrusive than creating a cargo project. Additionally, cargo isn't something that will be accepted in places like Debian which are very conservative about what build systems are allowed (although maybe not, if cargo is bundled with rustc).

To the extent that --dep-info still exists, it's behaviour is still a bit annoying. In some ways it's gotten worse, as it now appends a pointless '.d' to the output file name.

**Comment by Jurily** [comment]
Cargo is actively hostile to being used as/with a system package manager: rustc can't link to `/usr/lib` when installed there because it completely ignores the FHS, distros will never accept an ecosystem that builds its own set of C libraries for *that* reason alone, and even if they did, they won't package it because Cargo doesn't even plan to support offline/restricted builds for use in build bots and source-based package managers where you're verboten to touch anything outside the build tree, including the network.

If Rust is ever going to become a Systems Language(tm) in the sense that we implement system libraries to be built, installed and depended on with standard system utilities, Cargo will need a serious overhaul.

**Comment by huonw** [comment]
Triage: nothing has happened here for a long time; @pnkfelix, do you still think this would be useful?

**Comment by pnkfelix** [comment]
yeah I'll just close this.

I still think there's a good case that this problem should be fixed, but its probably part of a more general overhaul to integrate better with tools *other than* `cargo`.
