### ISSUE TITLE
[homebrew] rust 1.73.0 failed to build on 12-arm

### ISSUE THREAD

**Issue by chenrui333** [rust-lang/rust#117299]
We've got a weird error while trying to upgrade rust to 1.73.0. The error seems only happened in 12-arm build:

```
  thread 'main' panicked at 'could not read dir "/private/tmp/rust-20231026-5378-1tb0p4o/rustc-1.73.0-src/build/aarch64-apple-darwin/stage0/lib/rustlib/aarch64-apple-darwin/codegen-backends": Os { code: 2, kind: NotFound, message: "No such file or directory" }', lib.rs:1714:25
```

Some host toolchain:

```
Clang: 14.0.0 build 1400
macOS: 12.6.3-arm64
```

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6660485676/job/18101828627?pr=149754
relates to https://github.com/Homebrew/homebrew-core/pull/149754

**Comment by chenrui333** [comment]
Any takes on this? Thanks!

**Comment by Bo98** [comment]
This regressed in https://github.com/rust-lang/rust/commit/bb8c497566e2ec14af0faca0cbad70c1bd090dbf but it appears to have been fixed in amongst the various bundled fixes of https://github.com/rust-lang/rust/commit/db3e2bacb69c068fd9262a3aadd961ea2f7f940e#diff-5a1e05f2688d271039171a547d407d0c8a96715ee64d35562fc76b4c9a874303L595.

It is not clear to me why it only failed on macOS 12 (earlier versions untested), but it does seem to be fixed now.

If possible, it might be worth backporting the small relevant part of that change to `beta`.

**Comment by chenrui333** [comment]
on top of what @Bo98 said, we have incorporated the build patch in https://github.com/Homebrew/homebrew-core/pull/154526 

(gonna close this issue now)
