### ISSUE TITLE
Cargo fix will rename unused idents in macros even when used elsewhere

### ISSUE THREAD

**Issue by gfaster** [rust-lang/rust#117284]
### Problem

Consider the following `src/main.rs` file in a cargo package:
```rust
macro_rules! make_var {
    ($struct:ident, $var:ident) => {
        let $var = $struct.$var;
    };
}

#[allow(unused)]
struct MyStruct {
    var: i32,
}

fn main() {
    let s = MyStruct { var: 42 };
    make_var!(s, var);
}
```
Cargo will warn that `var` is not used. Upon running `cargo fix`, cargo will change the second parameter from `var` to `_var`, making the compilation fail. Even worse, if `MyStruct` contained a field `_var` then `cargo fix` would change the variable without producing any warning. 

### Steps

1. Initialize a new cargo binary project with the above snippet in `main.rs`
2. Run `cargo fix` (presumably with `--allow-dirty`)

### Version

```text
cargo 1.73.0 (9c4383fb5 2023-08-26)
```

**Comment by ehuss** [comment]
Transferred to rust-lang/rust, since the suggestions are generated by the compiler.

**Comment by chenyukang** [comment]
@Muscraft 
Yes, this issue comes from rustc.
The lint is emit from here https://github.com/rust-lang/rust/blob/160fd3ceb5143100d4e06f324b02af1f9e786372/compiler/rustc_passes/src/liveness.rs#L1660

Maybe we only point out that there is an unused variable coming from `var`, but without the suggestion? I'm not sure what is a proper lint for this test case.
@estebank any thoughts on it?

**Comment by estebank** [comment]
The quick and straightforward way to fix this would be to only emit the suggestion in this lint if the span has the root context, but then a subset of valid suggestions wouldn't be emitted. I had an older PR that I'm having trouble finding that would automatically do that for every diagnostic, but IIRC it had some negative perf impact when not implementing it very simplistic.
