### ISSUE TITLE
collect for hashmap

### ISSUE THREAD

**Issue by Arian-p1** [rust-lang/rust#117760]
I tried this code:

```rust
use std::collections::HashMap;

fn main() {
    println!("{:?}", maping(5));
}

fn maping(size: u32) -> HashMap<u32, Vec<u32>> {
    let j: Vec<u32> = (1..size + 1).into_iter().map(|i| i).collect();
    let map: HashMap<u32, Vec<u32>> = (1..size + 1).into_iter().map(|i| (i, j.clone())).collect();
    map
}
```

I expected to see this happen: *{1: [1, 2, 3, 4, 5], 2: [1, 2, 3, 4, 5], 3: [1, 2, 3, 4, 5], 4: [1, 2, 3, 4, 5], 5: [1, 2, 3, 4, 5]}*

Instead, this happened: *{3: [1, 2, 3, 4, 5], 1: [1, 2, 3, 4, 5], 2: [1, 2, 3, 4, 5], 4: [1, 2, 3, 4, 5], 5: [1, 2, 3, 4, 5]}*

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (84dd17b56 2023-04-14)
binary: rustc
commit-hash: 84dd17b56a931a631a23dfd5ef2018fd3ef49108
commit-date: 2023-04-14
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 16.0.2
```

**Comment by 0xdeafbeef** [comment]
The behavior you're seeing is because a `HashMap` in Rust does not guarantee any particular order of its elements. The order in which key-value pairs are stored and returned is essentially arbitrary.

When you create a `HashMap` and insert elements into it, the elements are not stored in the order in which they were inserted. Instead, they are stored based on their hash values, which are computed from the keys. This is why when you print the `HashMap`, the elements may appear in a different order than the one in which you inserted them. Moreover, this order will change between runs because [hasher](https://doc.rust-lang.org/std/hash/trait.BuildHasher.html) has a random seed.

If you need to maintain the order of elements, you should use a different data structure - btreemap or indexmap.

**Comment by asquared31415** [comment]
Note that https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.iter says
> An iterator visiting all key-value pairs **in arbitrary order.**

(emphasis mine)

**Comment by Arian-p1** [comment]
but why even it use RandomState

**Comment by TennyZhuang** [comment]
If you want a determined result, you can pass your own state.

**Comment by Arian-p1** [comment]
hmm now its clear thanks
