### ISSUE TITLE
Add a lint for catching `clone()` auto(de)ref confusion.

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/rust#11818]
Due to auto(de)ref, there are situations where calling `clone()` on a `&T` either clones the `T`, or the `&T`, depending on whether `T` has a `Clone` implementation or not.

This leads to confusing error messages in case of a missing `Clone` impls, __especially__ in combination with `#[deriving(Clone)]`.

### Example
~~~rust
struct Foo; 
let x: Foo = (&Foo).clone();
~~~
Fails with
~~~
error: mismatched types: expected `main::Foo` but found `&main::Foo` (expected struct main::Foo but found &-ptr)
~~~

While this works:

~~~rust
struct Foo; 
impl Clone for Foo { fn clone(&self) -> Foo { Foo } }; 
let x: Foo = (&Foo).clone();
~~~

### Lint

The proposed lint should catch situations where there are type errors arising from a `clone()` or `deep_clone()` call returning `&T` where `T` is expected, and recommend implementing `Clone` or `DeepClone` for `T`.

**Comment by steveklabnik** [comment]
Triage: nothing has changed. I share skepticism that this is super useful.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
