### ISSUE TITLE
Figure out final solution for volume-relative windows paths

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#11856]
As extensively documented in #11579, volume-relative paths on Windows are a relic of the past. We either need to remove support for it, or we need to figure out how `ls`, etc running in cmd.exe are emulating volume-relative cwds and teach `getcwd()` about that.

If we remove support for volume-relative paths, we should probably not make it a condition, because that's pretty crappy. We may want to just treat it as a path without a prefix.

**Comment by steveklabnik** [comment]
@aturon @alexcrichton how did this fall out with path reform?

**Comment by retep998** [comment]
This issue isn't done yet, because we still need to implement a way to turn volume relative paths into true absolute paths. This means getting the current working directory for that drive and joining the paths.

While `cmd.exe` has a variable current directory for each drive, Win32 has only a single variable current directory. Unfortunately Win32 still has immutable current directories set at process startup for each drive which it respects when interpreting volume relative paths.

At first I thought we were doomed because `GetCurrentDirectory` only returns that single current directory and not the drive specific current directories. Furthermore if we don't want to be limited by `MAX_PATH` we can't call `GetFullPathName` with the full path. As it turns out, however, we can simply call `GetFullPathName` with just the prefix like `C:` and it'll give us the correct current directory on which to join the rest of the path.

**Comment by aturon** [comment]
@retep998 Would you be interested in taking this project on?

**Comment by retep998** [comment]
@aturon Sure. Just point me at what functions need doing and I'll do them.

**Comment by huonw** [comment]
Has anything happened here?

**Comment by retep998** [comment]
There was a PR to turn relative paths and absolute paths into verbatim paths. https://github.com/rust-lang/rust/pull/27916
There were lots of concerns in it regarding various edge cases.
I think what should happen at this point is someone should develop such a function in an outside crate first and then it can be pulled into std once people seem satisfied by how it handles various edge cases.

**Comment by aturon** [comment]
I agree with @retep998. I'm going to close this issue, and we can address it via an eventual addition to `std` as @retep998 is suggesting.
