### ISSUE TITLE
use real vtable type in the trait object representation

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#11915]
There's no reason to be casting to and from an opaque type as it confuses LLVM and breaks devirtualization and other optimizations. I think it will involve some pain to have `trans::meth` spit out the vtable type without generating one though.

**Comment by steveklabnik** [comment]
Triage: no change. `TraitObject` still looks like

```
pub struct TraitObject {
    pub data: *mut (),
    pub vtable: *mut (),
}
```

**Comment by steveklabnik** [comment]
Triage: no real changes here, and I'm not aware of any plans to. Given no real comments since 2014, I'm going to give this one a close, as I don't think it's likely to ever be prioritized.

If anyone feels passionate about changing this, ping @rust-lang/compiler to see if they think it's still viable.

**Comment by eddyb** [comment]
This has nothing to do with `TraitObject`, although I'm not sure LLVM is limited by this anymore.
