### ISSUE TITLE
`assert_unsafe_precondition` and/or `is_aligned_and_not_null` do not work?

### ISSUE THREAD

**Issue by alexschrod** [rust-lang/rust#119314]
I tried this code:

```rust
let y: u64 = unsafe { core::ptr::read(1 as *const _) };
```

I expected to see this happen: `core::ptr::read` has this bit of code in it:
```rust
assert_unsafe_precondition!(
    "ptr::read requires that the pointer argument is aligned and non-null",
    [T](src: *const T) => is_aligned_and_not_null(src)
);
```

Since this pointer is *definitely* unaligned for an `u64` read, I expected this assert to trigger before we ever got to the actual attempt to read.

Instead, this happened: The program crashes with segfault (Linux) or `STATUS_ACCESS_VIOLATION` (Windows) when compiled in debug mode and "works" in release mode (i.e. if you try to print `y` after the read you get some random number printed.)

Same thing happens with an attempted null read (i.e. `core::ptr::read(core::ptr::null())`) as well.

### Meta

Happens on all current playground versions:
```
1.74.1
1.76.0-beta.1 (2023-12-21 0e09125c6c3c2fd70d7d)
1.77.0-nightly (2023-12-24 bf8716f1cd6416266807)
```

**Comment by bjorn3** [comment]
assert_unsafe_precondition only worls when the standard library itself is compiled with debug assertions enabled. You can use something like cargo-careful to handle that for you.

**Comment by alexschrod** [comment]
> assert_unsafe_precondition only worls when the standard library itself is compiled with debug assertions enabled. You can use something like cargo-careful to handle that for you.

Ah. Wonder if/how I could have discovered that on my own. 🤔 It certainly wasn't obvious to me, as the creation of this issue clearly indicates. 😅

**Comment by saethlin** [comment]
You _might_ have been able to work this out by examining the implementation of `assert_unsafe_precondition`. But again that would only help if you know that the standard library is special and distributed in a precompiled form, unlike probably every other crate you use. The fact that the standard library is precompiled solves some hard problems but with annoying side effects like this one. I've been chipping away at a strategy to fix _some_ of these issues, and though I might manage to get some runtime UB checks working, the current implementation strategy for `assert_unsafe_precondition` is never going to be toggleable after-the-fact with a precompiled standard library.

I'm closing because the issues is "resolved" as "they work as much as they're supposed to", but if you have further questions about this topic don't let the issue status stop you.
