### ISSUE TITLE
Pointer casts allow switching trait parameters for trait objects, which can be unsound with raw pointers as receiver types under `feature(arbitrary_self_types)`

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#120217]
~~_This particular exploitation is possible since #113262. I’m not certain if there wasn’t any way to convince the compiler to do such casts before that; if there wasn’t, then that PR was definitely a lot _more_ than “a bugfix”._~~

_Edit:_ Turns out, there is a way, see my first answer below. (Does this mean the regression label should be removed, since the regression only extended the scope of the issue a bit? So this becomes an issue for `F-arbitrary_self_types` in general then? Should we also add `requires-nightly` label?)

---

So apparently, the compiler doesn’t care about lifetimes for trait object metadata when checking casts between pointers. This means I can coerce `*const dyn Foo<'a>` into `*const dyn Foo<'b>` without restrictions. Since vtables logically contain function pointers, like for example a vtable for `trait Foo<'a> { fn foo(&self) -> &'a str }` logically contains something like `unsafe fn(*const ()) -> &'a str` this results in casting the _types_ of these function pointers.

Now one could argue “it’s fine, they are raw pointers, you can’t do anything with `*const dyn NotQuiteTheRightTrait`”, but as far as I’m aware, the story on that is that you _can_, vtables _must_ be valid (at least as a soundness invariant, not necessarily promising instant UB), and we should not break `arbitrary_self_types`’s soundness this way, for now.

And with `arbitrary_self_types`, unsoundness there is!
```rs
#![feature(arbitrary_self_types)]

trait Static<'a> {
    fn proof(self: *const Self, s: &'a str) -> &'static str;
}

fn bad_cast<'a>(x: *const dyn Static<'static>) -> *const dyn Static<'a> {
    x as _
}

impl Static<'static> for () {
    fn proof(self: *const Self, s: &'static str) -> &'static str {
        s
    }
}

fn extend_lifetime(s: &str) -> &'static str {
    bad_cast(&()).proof(s)
}

fn main() {
    let s = String::from("Hello World");
    let slice = extend_lifetime(&s);
    println!("Now it exists: {slice}");
    drop(s);
    println!("Now it’s gone: {slice}");
}
```
```
Now it exists: Hello World
Now it’s gone: @7
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e7c367f4db1c17373bb978a8efdc849e))

@rustbot label +I-unsound +F-arbitrary_self_types +A-lifetimes +A-coercions +A-trait-objects +requires-nightly

**Comment by steffahn** [comment]
Uhm… perhaps nevermind on that recent regression point, I guess? Apparently we can also do the following _just fine™_ since around Rust `1.2`
```rs
#![allow(bare_trait_objects)]

trait Trait<T> {}

fn foo(x: *const Trait<u8>) -> *const Trait<u16> {
    x as *const Trait<u16>
}
```


(Let me work on a better code example.)

**Comment by Nilstrieb** [comment]
Requiring pointers to have valid vtables while allowing these casts seems pretty conflicting and impossible. cc @rust-lang/opsem @rust-lang/lang who have previously been discussing whether raw pointers should have valid vtables.

**Comment by RalfJung** [comment]
This wasn't just discussed, it was decided that raw ptrs have valid vtables as a safety invariant as part of dyn trait upcasting.

However, this being about safety invariants, it's more a @rust-lang/types question than an opsem one.

**Comment by Nilstrieb** [comment]
If a safety invariant can be broken by safe code that's uh, not good.

**Comment by adetaylor** [comment]
Agreed - IMO if arbitrary self types supports calls into `*[const|mut] dyn Trait` then these should need to be `unsafe` since it involves dereferencing some data that can be arbitrarily manipulated.

**Comment by RalfJung** [comment]
Ideally we can fix things so that safe code can't arbitrarily manipulate this.

https://github.com/rust-lang/rust/issues/120222 is another issue caused by vtable manipulation. Let's see how that one gets resolved (it's a lot more critical since the feature it affects almost got stabilized in 2 weeks), then we can use that to decide what to do about arbitrary-self.

**Comment by QuineDot** [comment]
> This wasn't just discussed, it was decided that raw ptrs have valid vtables as a safety invariant as part of dyn trait upcasting.

Issue #101336 for anyone looking.

**Comment by apiraino** [comment]
@steffahn can you help me getting a bit more context (maybe I missed some comments and don't have the global picture): how does (if at all) the revert of #118133 (in PR #120233) affect this? Does that "fix" it, at least partially? Thanks :)

**Comment by lukas-code** [comment]
@apiraino Both `feature(arbitrary_self_types)` and `feature(trait_upcasting)` are individually unsound, because we allow casts like `*const dyn Trait<u8>` -> `*const dyn Trait<u16>`. But the features are otherwise completely unrelated, so the revert of `trait_upcasting` does not affect the soundness of `arbitrary_self_types` at all.

The unsoundness of `arbitrary_self_types` is tracked in this issue and the unsoundness of `trait_upcasting` is tracked in https://github.com/rust-lang/rust/issues/120222.

Both issues could be fixed by disallowing casts like `*const dyn Trait<u8>` -> `*const dyn Trait<u16>` (https://github.com/rust-lang/rust/issues/120222#issuecomment-1903999820 / https://github.com/rust-lang/rust/pull/120248), but that would regress stable code.

An alternative set of fixes is to change the vtable layout to fix `trait_upcasting` (https://github.com/rust-lang/rust/issues/120222#issuecomment-1904152546) and to make dispatch on `*const dyn Trait` unsafe to fix `arbitrary_self_types` (https://github.com/rust-lang/rust/issues/120217#issuecomment-1904313835).

**Comment by steffahn** [comment]
@apiraino The summary from @lukas-code above is already good. As for what the revert of stabilization of `trait_upcasting` in its current form achieved: all it did was making #120222 from a `regression-from-stable-to-beta` issue into a `requires-nightly` issue (which has already been reflected in the labels).

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23120217.20Pointer.20casts.20allow.20switching.20lifetimes.20of.20trait.20ob.E2.80.A6/near/417136378)).

@rustbot label -I-prioritize +P-medium

**Comment by traviscross** [comment]
This is believed to be fixed by:

- https://github.com/rust-lang/rust/pull/120248
