### ISSUE TITLE
LLVM 18 issue: tests/run-make/target-specs and rustdoc-target-spec-json-path broken after  https://github.com/rust-lang/rust/commit/46652dd254bc9c413d14cec637c7f21ac6601e05

### ISSUE THREAD

**Issue by krasimirgg** [rust-lang/rust#120492]
The commit  https://github.com/rust-lang/rust/commit/46652dd254bc9c413d14cec637c7f21ac6601e05 added a check that stars firing due to the changes to the default target layouts in LLVM 18 (https://github.com/rust-lang/rust/pull/116672):
https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/25552#018d505f-51d2-4820-8258-2f7b1b2ba0be/849-862
```
error: data-layout for target `my-awesome-platform-11748080347047929107`, `e-m:e-p:32:32-p270:32:32-p271:32:32-p272:64:64-f64:32:64-f80:32-n8:16:32-S128`, differs from LLVM target's `i686-unknown-linux-gnu` default layout, `e-m:e-p:32:32-p270:32:32-p271:32:32-p272:64:64-i128:128-f64:32:64-f80:32-n8:16:32-S128`
```

**Comment by kennystrawnmusic** [comment]
Having this issue on `x86_64-unknown-none` as well:

```
error: data-layout for target `i686-stage-3-15880981762407934716`, `e-m:e-i32:32-f80:128-n8:16:32-S128-p:32:32`, differs from LLVM target's `i386-unknown-none` default layout, `e-m:e-p:32:32-p270:32:32-p271:32:32-p272:64:64-f64:32:64-f80:32-n8:16:32-S128`
```
Why it's trying to compile for a 32-bit target is clearly beyond me because I'm using an entirely 64-bit host ― since @phil-opp happens to be the author of the crate this is failing on (namely, the 32-bit BIOS version of the bootloader crate which I explicitly avoid depending on for my intendedly UEFI-only kernel), pinging him for assistance.

**Comment by phil-opp** [comment]
@kennystrawnmusic I think this issue thread is about some failing tests in the Rust repo. Your issue seems to be specific to the `bootloader ` crate, which required some updates to the custom targets it is using. I published a new version already, which should fix the issue.

If you still have issues with the `bootloader` crate after a `cargo update`, please open an issue in the https://github.com/rust-osdev/bootloader repository.
