### ISSUE TITLE
rustdoc: Long type names result in weird-looking documentation

### ISSUE THREAD

**Issue by Andrewp2** [rust-lang/rust#120595]
Crates with long type names result in a strange-looking error, see [https://docs.rs/async-stripe/0.31.0/stripe/](https://docs.rs/async-stripe/0.31.0/stripe/)

![image](https://github.com/rust-lang/rust/assets/22418741/bdf66414-99ae-44cd-8fbf-b1ecc3bfec4c)

I've tested this on Chrome and Firefox, and by building the docs locally from [https://github.com/arlyon/async-stripe](https://github.com/arlyon/async-stripe)

I believe the text is rendering vertically due to long type names like [https://docs.rs/async-stripe/0.31.0/stripe/enum.PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceEnterpriseFeaturesIncrementalAuthorizationIncrementalAuthorizationStatus.html](https://docs.rs/async-stripe/0.31.0/stripe/enum.PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceEnterpriseFeaturesIncrementalAuthorizationIncrementalAuthorizationStatus.html) which are auto-generated from OpenAPI.

Link to original issue [https://github.com/arlyon/async-stripe/issues/488](https://github.com/arlyon/async-stripe/issues/488)

**Comment by Urgau** [comment]
The issue is related to the `overflow-wrap: break-word` rule which prevents breaking anywhere in the type name. Unfortunately using `overflow-wrap: anywhere` breaks [`core::arch`](https://doc.rust-lang.org/core/arch/x86_64/index.html).

We even have a comment about the weird behaviour in the code, not sure how to fix this.

https://github.com/rust-lang/rust/blob/befabbc9e5f6e82e659f9f52040ee0dd40593d8a/src/librustdoc/html/static/css/rustdoc.css#L881-L904
