### ISSUE TITLE
Make unsafe_op_in_unsafe_fn warn-by-default starting in 2024 edition

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rust#120535]
The lang team recently discussed whether we should turn on the unsafe_op_in_unsafe_fn lint by default, and whether this should be done over an edition. The consensus we came to was that we should make the lint warn-by-default and do it over an edition.

Both of these are to help mitigate the disruptiveness of the change. We don't want to discourage too strongly the use of blanket allow in crates where nesting an `unsafe` block inside every `unsafe fn` is entirely redundant and unhelpful. We also would like to make use of the edition migration mechanism to help rewrite people's code and gather feedback over time as people migrate, rather than making a big change all at once.

It is possible that after gaining more experience we will want to strengthen the lint to error-by-default or to warn in all editions, but those are not part of this proposal.

**Comment by tmandry** [comment]
@rfcbot fcp merge

**Comment by Urgau** [comment]
Wasn't this already FCP-ed in https://github.com/rust-lang/rust/issues/71668#issuecomment-1189396860 ?

Because that FCP was used in https://github.com/rust-lang/rust/pull/112038 to make the lint warn-by-default in the 2024 edition:
https://github.com/rust-lang/rust/blob/11f32b73e0dc9287e305b5b9980d24aecdc8c17f/compiler/rustc_lint_defs/src/builtin.rs#L2763

**Comment by traviscross** [comment]
@rustbot labels +I-lang-nominated

@Urgau raises a compelling point that we seem to have already agreed to do this and in fact landed a PR in Rust 2024 to this effect.  Considering again my [earlier question](https://github.com/rust-lang/rust/issues/71668#issuecomment-1913714172):

> Given the resolution of #119823, let's discuss what else (if anything) needs to happen to land this in Rust 2024.

That would suggest that the answer is in fact, "nothing, this is all set for Rust 2024."

If this FCP merge completes, that action would of course be idempotent.  Let's nominate so that if this FCP is still outstanding next week that we discuss it.

**Comment by tmandry** [comment]
Thanks for pointing that out, @Urgau. On the basis of the earlier FCP, I'll check the boxes of everyone who checked that FCP and leave the 10-day window for any final objections to be raised.

FYI @joshtriplett @pnkfelix

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

As @tmandry suggested, in our call we agreed that we had already decided on this and that people had relied on that decision to land this in Rust 2024, so we'll idempotently let this FCP complete.

Given that the impl for this has landed, it looks like this is done and ready for Rust 2024, which is exciting.

We'll unnominate, but if any concerns do come up, please nominate for those.

**Comment by tmandry** [comment]
Let's close this in favor of https://github.com/rust-lang/rust/issues/123916.
