### ISSUE TITLE
rustdoc regression: inter-crate links not being generated where they previously were

### ISSUE THREAD

**Issue by tarcieri** [rust-lang/rust#120983]
We recently received multiple reports in the @RustCrypto project of missing links in the docs.rs documentation, and did manage to find a somewhat minimal illustration of the problem/

We previously had documentation which linked to types in the `generic-array` crate: https://docs.rs/digest/0.10.1/digest/type.Output.html

<img width="1021" alt="Screenshot 2024-02-12 at 12 41 31 PM" src="https://github.com/rust-lang/rust/assets/797/901ed419-0e75-4dcf-ad8c-9bcec28bf7be">

At some point those links broke. Here is where I first observed it: https://docs.rs/digest/0.10.2/digest/type.Output.html

<img width="1015" alt="Screenshot 2024-02-12 at 12 43 32 PM" src="https://github.com/rust-lang/rust/assets/797/895d716f-2b95-4beb-8a62-a44bfd1c0abc">

Not sure how to properly file this issue, especially as I often experience these links not working on local rustdoc builds but being present on docs.rs. I can at least confirm I reproduced how the v0.10.2+ docs.rs builds appear via a local rustdoc build.

**Comment by JustAnotherCodemonkey** [comment]
I see that this needs a mcve. The provided example seems relatively minimal. What would constitute a mcve and how would one go about testing this without playing around with an actual crate on docs.rs?

**Comment by fmease** [comment]
> I see that this needs a mcve. The provided example seems relatively minimal. What would constitute a mcve […]?

@JustAnotherCodemonkey, while the example is a nice reproducer, it's far from minimal: The incorrectly documented item `Output` is defined in a 2K SLoC crate, `digest`, which has several (transitive) dependencies amounting to 165KB in size. Most notably it depends on `typenum` which is 6K SLoC. An MCVE only consists of a single (if the bug can be reproduced with a single crate) or two files (if the bug is a cross-crate re-export bug) containing only a few items (like 1 – 12). That's why I tagged this with https://github.com/rust-lang/rust/labels/E-needs-mcve.

Note that @GuillaumeGomez wrote [here](https://github.com/rust-lang/rust/issues/120993#issuecomment-1959109516) that they will look into a very similar (if not a duplicate of this) issue. They may or may not try to the find a reproducer themself now. An MCVE isn't always necessary to find the root cause but it's still necessary to be able to add a regression test.

Sometimes someone very familiar with the code base may already have a hunch what went wrong even without an MCVE or they may remember a recent PR that touched relevant parts of the code base or they may bisect a commit range to search for a regressing commit.

> […] how would one go about testing this without playing around with an actual crate on docs.rs?

Well typically you download or git-clone (with a depth of 1) the relevant crate and try to minimize it which is a bit of an art form or trial-and-error. Check out http://blog.pnkfx.org/blog/2019/11/18/rust-bug-minimization-patterns/ for example (not that `-Z unpretty=everybody_loops` used in the article no longer exists). There are also several minimization tools: E.g., https://github.com/Nilstrieb/cargo-minimize, https://github.com/langston-barrett/treereduce

**Comment by tarcieri** [comment]
@fmease I'd agree the problem looks related to `typenum`: we're experiencing similar problems with crates using `hybrid-array`, a `generic-array` alternative, which would seem to rule out `generic-array` itself.

**Comment by GuillaumeGomez** [comment]
The problem shows up with `cargo rustdoc` and with `cargo doc --deps`. Since it doesn't have other crates information, it doesn't generate links to their items. Normally, `-Zrustdoc-map` should allow to go around this limitation, checking why it's not the case.

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/rust-lang/cargo/pull/13481, it should fix this issue.

**Comment by tarcieri** [comment]
It looks like that PR is merged. Can I expect the changes to be live on docs.rs then?

**Comment by GuillaumeGomez** [comment]
If the new cargo nightly has been released, you should be able to.

**Comment by newpavlov** [comment]
I think this issue can be closed? We probably should ask the docs.rs team to re-generate docs, but I wonder if it can be done automatically (i.e. all dependencies of `generic-array` published in the affected date range), since it will be hard to create a full list manually.

**Comment by GuillaumeGomez** [comment]
Indeed! Closing then.
