### ISSUE TITLE
Add a `config.toml` option to set `RUSTC_WRAPPER`, for building `rustc` with `sccache`

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#122122]
`config.toml` currently has an option to use ccache for LLVM. Add a `rustc-wrapper` or similar config option that will pass the value to `RUSTC_WRAPPER` when invoking Cargo.

This will make it easy to build the compiler with [`sccache`](https://github.com/mozilla/sccache) locally.  Rustc builds with sccache in CI, so that serves as a good reference.

@rustbot label +E-easy +T-bootstrap

**Comment by tgross35** [comment]
To work properly, sccache also needs incremental compilation disabled https://github.com/mozilla/sccache?tab=readme-ov-file#rust

**Comment by Mark-Simulacrum** [comment]
Can you say more about usage in CI? I'm not aware of any caching attempts of the rustc part of the build with sccache, and I would be surprised if it's cache key is accurate out of the box given how much customization we do and necessity of working around problems in cargo's cache key in some cases.

It also seems unlikely to be commonly helpful, since the full crate graph changes so much - and crates.io dependencies are (at least in my experience) a very small portion of the build.

**Comment by tgross35** [comment]
I must be mistaken, I thought we used sccache for the Rust side too but I guess that is only for LLVM.

My use case is just with changing branches back and forth locally, nothing CI-specific - though in theory it could be.

**Comment by onur-ozkan** [comment]
I don't think it's worth supporting. Since we manipulate cargo's caching in the bootstrap, I believe this could lead to some bugs that may be quite hard to detect.

> No strong need so feel free to close if you feel applicable. 

:+1:
