### ISSUE TITLE
Bootstrap: `llvm-bitcode-linker` adds unnecessary recompilation

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/rust#122491]
The `llvm-bitcode-linker`, which is enabled by default in the `compiler` config, is recompiled everytime I try to run tests:
```
$ python3 x.py test tests/run-make/hir-tree/
Creating a sysroot for stage1 compiler (use `rustup toolchain link 'name' build/host/stage1`)
Building tool llvm-bitcode-linker (stage0 -> stage1, x86_64-unknown-linux-gnu)
   Compiling once_cell v1.19.0
   Compiling cfg-if v1.0.0
...
Building tool rustdoc (stage0 -> stage1, x86_64-unknown-linux-gnu)
   Compiling cfg-if v1.0.0
   Compiling once_cell v1.19.0
...
$ python3 x.py test tests/run-make/hir-tree/
Creating a sysroot for stage1 compiler (use `rustup toolchain link 'name' build/host/stage1`)
Building tool llvm-bitcode-linker (stage0 -> stage1, x86_64-unknown-linux-gnu)
   Compiling once_cell v1.19.0
   Compiling cfg-if v1.0.0
...
Building tool rustdoc (stage0 -> stage1, x86_64-unknown-linux-gnu)
   Compiling cfg-if v1.0.0
   Compiling once_cell v1.19.0
...
```

The recompilation also causes further recompilation of `rustdoc` (if I disable the bitcode linker, rustdoc is not recompiled).

**Comment by workingjubilee** [comment]
cc @kjetilkjeka

**Comment by kjetilkjeka** [comment]
Oh, that's not good. Thanks for reporting. I will look at it tomorrow.

**Comment by kjetilkjeka** [comment]
I have tracked it down to this `ensure`. If I comment out that code it wont trigger the recompilation.

https://github.com/rust-lang/rust/blob/ee03c286cfdca26fa5b2a4ee40957625d2c826ff/src/bootstrap/src/core/build_steps/compile.rs#L1847-L1855

From the documentation of ensure it say 
> This will cache the step, so it is safe (and good!) to call this as often as needed to ensure that all dependencies are built.

Also the definition of `LlvmBitcodeLinker` is done with the `tool_extended` macro. That makes me think that it's related to something like the `build_compiler` invalidating the caching. I'm currently exploring that a bit further.

**Comment by kjetilkjeka** [comment]
The stuff above seems to work fine as building the `llvm-bitcode-linker` (without rustdoc)  works fine. 

The problem seems to be that `rustdoc` and `llvm-bitcode-linker` breaks the cache for each other. I suspect that means something is off in feature resolution between those modules.

**Comment by kjetilkjeka** [comment]
I now know what the problem is. I will need some help to figure out the correct way to solve it.

### The problem
`impl Step for Rustdoc` uses a very specifc cargo invocation which manually sets `rustflags` if a parallell compilation can be used.

https://github.com/rust-lang/rust/blob/accc516128b21e960b1a7af45393e9acdd184890/src/bootstrap/src/core/build_steps/tool.rs#L483-L485

This causes common dependencies between the LLVM bitcode linker and Rustdoc to be rebuilt when one is called after the other. Since Rustdoc builds the bitcode linker (presumably through the `Assemble` step) this will always happen when `Rustdoc` is built.

### The questions I need resolved to fix it

Is it correct/ethical of rustdoc to set `rustflags` like this? Or should rustflags be handled more centrally so every cargo invocation will end up with the same set of rustflags and this cache invalidation cannot occur?

If it is important for rustdoc to use its own set of rustflags, should it then use a different build directory to other tools/steps using cargo?

**Comment by kjetilkjeka** [comment]
I see that @m-ou-se added this in [c7f443a6e3320b4cb70da5af08810f1dd60e146c](https://github.com/rust-lang/rust/pull/104754/commits/c7f443a6e3320b4cb70da5af08810f1dd60e146c). Maybe she knows more about this?

**Comment by onur-ozkan** [comment]
> Is it correct/ethical of rustdoc to set rustflags like this? Or should rustflags be handled more centrally so every cargo invocation will end up with the same set of rustflags and this cache invalidation cannot occur?

We can't have same set of rustflags for every `Step`, in most cases we want the opposite; setting step specific rustflags. What about adding `--cfg=parallel_compiler` to `llvm-bitcode-linker` tool?

**Comment by kjetilkjeka** [comment]
That seems to work well in the scenario described above and in other scenarios I tested for. I think I just imagined that this was more frequently occurring problem if all tools share build folder and are able to set rustflags separately and adding this to `llvm-bitcode-linker` would cause a conflict with something else (which it doesn't seem to do).

Anyway, as this at least is improving the issue I'm creating a MR with this solution now
