### ISSUE TITLE
Can't define a function name using concat_idents!()

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#12249]
I want `mymacro!(bar)` to expand to `fn foo_bar() { }`.

~~~ .rs
#[feature(macro_rules)];

macro_rules! mymacro( ($x:ident) => (
    fn concat_idents!(foo_, $x)() { }
))

mymacro!(bar)

fn main() {
    foo_bar();
}
~~~

gives

~~~
foo.rs:4:21: 4:22 error: expected `(` but found `!`
foo.rs:4     fn concat_idents!(foo_, $x)() { }
~~~

on

~~~
rustc 0.9 (d3b3c66 2014-01-12 19:44:26 -0700)
host: x86_64-unknown-linux-gnu
~~~

**Comment by SkylerLipthay** [comment]
In case anyone wants a slightly saner solution to this problem while waiting for better macros, I made a syntax plugin that's sure to break once after each nightly release: [interpolate_idents](https://github.com/SkylerLipthay/interpolate_idents)

**Comment by retep998** [comment]
This is an issue that I find frustrating when working on `winapi`, making macros needlessly more complicated with extra parameters just because `concat_idents!` is completely useless. This is by far the most common deficiency of macros I see people run into, and I think it would be worth the additional complexity to support this sort of thing.

We've already had a [working PR](https://github.com/rust-lang/rust/pull/14266) that was closed due to needing an RFC and then an [RFC](https://github.com/rust-lang/rfcs/pull/215) that was closed due to trying to avoid jamming up the macro system with 1.0 approaching.

Now that Rust has had several stable versions and the magical new macro system that people are heralding is nowhere in sight still, maybe we can consider opening an RFC for allowing macros in ident positions and actually having a discussion instead of just shutting it down immediately.

**Comment by nrc** [comment]
macro reform is in the works right now, expect an internals post soon addressing things to fix (although a plan will take a bit longer). Concatenating identifiers is definitely on the agenda. It is a hard problem though - hygiene considerations means there is no easy solution.

**Comment by WChargin** [comment]
Awesome, thanks for working on this. Definitely a :+1: from me. Looking forward to it.

**Comment by steveklabnik** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/29599
