### ISSUE TITLE
rustdoc shows associated type in supertrait bound twice when both Deref and DerefMut have a `Target` bound

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#122928]
This is visible [here](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_const_eval/interpret/trait.AllocBytes.html):
```rust
pub trait AllocBytes: Clone + Debug + Eq + PartialEq + Hash + Deref<Target = [u8], Target = [u8]> + DerefMut {
```
Compared to the actual sources, the `Target = [u8]` is duplicated at `Deref` but missing at `DerefMut`.
```
pub trait AllocBytes:
    Clone + fmt::Debug + Eq + PartialEq + Hash + Deref<Target = [u8]> + DerefMut<Target = [u8]>
```
(On `DerefMut` the constraint is redundant, that is likely what is throwing rustdoc off.)

Cc @rust-lang/rustdoc

**Comment by fmease** [comment]
I've been aware of flaws like this for a long time (your issue is an instance of the more general #113015) and I generally know how to fix this but work has stalled (e.g. this tangentially related PR #116735) because the way data is represented in rustdoc (`rustdoc::clean::types`) makes this unnecessarily hard to implement (if not impossible) with respect to correctness and performance.

**Comment by fmease** [comment]
I really want to fix issues like this though, let me take another look.

**Comment by RalfJung** [comment]
Thanks!

Closing in favor of https://github.com/rust-lang/rust/issues/113015 then.
