### ISSUE TITLE
x.py should check host's version of libstdc++ before defaulting to download-ci-llvm

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#123037]
Spawned off of https://github.com/rust-lang/rust/issues/110472#issuecomment-1864047805:

> Per https://pkgs.org/search/?q=libstdc%2B%2B it looks like Amazon Linux 2 uses libstdc++ 7, which is ABI incompatible with the libLLVM.so for download-ci-llvm. I believe you need at least libstdc++ 8.
> 
> Possibly the build system should check the version.

I'm not 100% sure what would be involved in such a check here, but it seems like a good thing to investigate, because the nature of the resulting bootstrap failures is super frustrating.

(I'll admit, I don't know if the right thing would be to hard error out of all uses of download-ci-llvm for potentially-incompatible libstdc++, or only to hard error out for defaulting uses... but a *warning* seems warranted in any such cases.

**Comment by Mark-Simulacrum** [comment]
I guess the problem here is that we're compiling the [Rust LLVM wrapper code](https://github.com/rust-lang/rust/tree/master/compiler/rustc_llvm/llvm-wrapper) locally and linking that against the downloaded toolchain. A check like suggested here makes sense to me in the meantime, but I suppose long-term the "right" fix here is to get rid of any C++ code we need to separately compile by upstreaming C bindings into LLVM proper, and then we can just call those on the Rust side without any ABI issues.

**Comment by Mark-Simulacrum** [comment]
You mean always print a warning? I don't think that's a good idea, it's noisy and we generally expect that people are happy using download CI LLVM. I don't think a warning is helpful here if we can't scope it down to where it matters (in which case it can probably be an error).

**Comment by onur-ozkan** [comment]
Not always, only once while downloading it.

**Comment by Mark-Simulacrum** [comment]
I think that falls in the same "not particularly helpful" case. Most users will miss the message, and even if they don't it's not clear how they should respond. I at least don't know how to check whether my machine has everything setup right. If we could check then we could limit the warning, in which case I'm broadly in favor of making it perhaps even a hard error.
