### ISSUE TITLE
Tracking Issue for fn const BuildHasherDefault::new()

### ISSUE THREAD

**Issue by krtab** [rust-lang/rust#123197]
Feature gate: `#![feature(build_hasher_default_const_new)]`

This is a tracking issue for a new `new` class method for BuildHasherDefault. It allows creating a BuildHasherDefault in const contexts.
Because HashMap::with_hasher constness is being stabilized in #118427 this will in turn allow creating empty `HashMap<K,V,BuildHasherDefault<H>>` in const context for any `H: Default + Hasher`.

### Public API

```rust
impl<H> BuildHasherDefault<H> {
    pub const fn new() -> Self;
}
```

### Steps / History

- [x] Implementation: #123198
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

@rustbot claim

**Comment by RalfJung** [comment]
@rust-lang/libs-api with https://github.com/rust-lang/rust/pull/132541 on its way into the compiler, we are quite close to stabilizing https://github.com/rust-lang/rust/issues/102575. However, actually creating a `HashMap` in const context with just that feature is kind of awkward:
```rust
    struct MyBuildDefaultHasher;
    impl BuildHasher for MyBuildDefaultHasher {
        type Hasher = DefaultHasher;

        fn build_hasher(&self) -> Self::Hasher {
            DefaultHasher::new()
        }
    }

    const H: HashMap<(), (), MyBuildDefaultHasher> = HashMap::with_hasher(MyBuildDefaultHasher);
```

So, I propose that we also stabilize `BuildHasherDefault`, tracked right here, so that this can instead be written as:
```rust
    const H: HashMap<(), (), BuildHasherDefault<DefaultHasher>> =
        HashMap::with_hasher(BuildHasherDefault::new());
```

**Comment by m-ou-se** [comment]
@rfcbot merge
