### ISSUE TITLE
regression: no name for DefPath ICE

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#123274]
```
[INFO] [stdout] error: internal compiler error: compiler/rustc_middle/src/ty/mod.rs:1582:13: item_name: no name for DefPath { data: [DisambiguatedDefPathData { data: ValueNs("hello_struct"), disambiguator: 0 }, DisambiguatedDefPathData { data: AnonConst, disambiguator: 0 }], krate: crate0 }
```

https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/reg/hello_bash_plugin-0.1.0/log.txt

**Comment by matthiaskrgr** [comment]
might be related to https://github.com/rust-lang/rust/issues/123243

**Comment by compiler-errors** [comment]
Yep, this is due to #121644, cc @oli-obk.

Specifically, it's kind of sketchy that the static allocations inherit the codegen flags from their parent statics -- in *this* case (see the issue @matthiaskrgr linked), we have an static allocation who inherits the `#[no_mangle]` flag from the parent; however, the allocation doesn't actually have an item name to use for `#[no_mangle]`.

This should also affect other attrs like `#[export_name]`, `#[link_name]`...

I'm gonna put up a fix PR.

**Comment by cuviper** [comment]
Backported in #123466.
