### ISSUE TITLE
Add .clang-format file

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rust#123510]
> Is it possible to add a .clang-format file to configure the whole llvm-wrapper? The exists code does not fit any preset styles of clang-format. I have asked at discord but get no response about what code convention the cpp code follows.

_Originally posted by @Lambdaris in https://github.com/rust-lang/rust/issues/123437#issuecomment-2036184138_

@Zalathar mentioned we have no such automated infra in place. We have many open issues for removing this C++ code by effectively upstreaming our wrappers to LLVM, but I agree, we could start by enforcing a style.

**Comment by DianQK** [comment]
I would like to add a check that follows to the LLVM style and run this check on CI.

I'm uncertain about adding a check locally, since most people won't be modifying the C++ code. It would require users to install `clang-format` on their local machines. Perhaps we could skip the check locally or only run it if `clang-format` is detected in the user's `$PATH`.

@rustbot claim

**Comment by Zalathar** [comment]
I wonder if it would be worthwhile to build `clang-format` as part of our LLVM build, and use that.

Obviously that doesn't help in cases where LLVM is downloaded (unless we also include it in the download), but maybe it's fine to skip the local check in those cases.

**Comment by workingjubilee** [comment]
As long as our C++ code doesn't introduce additional barriers to contributing to the Rust code.

**Comment by DianQK** [comment]
Currently, there are no clang-related builds here. Typically, we don't need to ensure that `clang-format` uses the same version of the code. I think that a local warning would be sufficient.

**Comment by durin42** [comment]
For Mercurial we found we had to be pretty particular about what version of `clang-format` we used in our test coverage, or some things would be fussy in some corner cases. I imagine that would be the case for us too, and it makes sense to me to take `clang-format` from the LLVM build so it's a consistent version...

**Comment by DianQK** [comment]
If the cost is low, I would opt for a consistent version. In upstream LLVM practices, using version 16 of clang-format is also compatible with developing LLVM 18/19. Since we have very little C++ code, I don't think it's worth distributing clang-format. :) 

Of course, to ensure consistent formatting results, I will add the corresponding checks to the CI. I think we could initially implement a non-blocking CI check for a while to see if we encounter any inconsistencies.

**Comment by DianQK** [comment]
After some attempts, I agreed to add `clang-format` to our LLVM build, primarily because I found differences between `clang-format-15` and `clang-format-18`. Additionally, it's challenging to have both Python 2.7 and `clang-format-18` on the CI simultaneously. Fortunately, adding `clang-format` is much easier than adding `clang`. We don't need to worry about the various header file lookup issues. I will prepare an MCP for this change.

**Comment by workingjubilee** [comment]
cool, thanks for implementing this!
