### ISSUE TITLE
Regression: invalid memory reference

### ISSUE THREAD

**Issue by zeroflaw** [rust-lang/rust#124117]
### Code

I tried this code:

```rust
    let buf: &[u8]  = &[];
    let v = unsafe{ buf.as_ptr().cast::<u16>().read_unaligned() };
```

I expected to see this happen: perform an unsafe memory read returning a u16 (even if the value is nonsense) in both release and debug.

Instead, this happened: (signal: 11, SIGSEGV: invalid memory reference) (failure in debug only)

### Version it worked on

rustc 1.79.0-nightly (1cec373f6 2024-04-16)

### Version with regression

rustc 1.79.0-nightly (becebb315 2024-04-17)

**Comment by the8472** [comment]
This is intended behavior. Reading from [invalid pointers is undefined behavior](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) and therefore any outcome is possible. Often it leads to silent corruption due to aggressive optimizations by the compiler, but in debug some cases can be detected and result in errors or process aborts instead.

**Comment by zeroflaw** [comment]
In that case should the following not fail for the same reason, but it works.

```rust
    let buf: &[u8]  = &[0];
    let v = unsafe{ buf.as_ptr().cast::<u16>().read_unaligned() };
```

**Comment by zeroflaw** [comment]
I understand, however it is far more performant to fetch from memory and then correct. Compared to conditionally fetching only valid memory.

The SIGSEGV in debug only, means I would have to write a debug  only implementation.

**Comment by the8472** [comment]
> I understand, however it is far more performant to fetch from memory and then correct.

You're giving the compiler license for arbitrary miscompilations, which can result in subtle corruption. Just because it runs doesn't mean it's correct. Plus reading from the zero-address page (where a dangling pointer might point to) will result in a segfault anyway.

What you want is a loads where the OOB parts are masked. On x86 this will require AVX512 instructions.
If you stay within the boundary of a valid page then using assembly to perform load-then-mask may work. But touching an invalid page will still segfault.
