### ISSUE TITLE
Document minimum supported versions for apple operating systems to platform documentation

### ISSUE THREAD

**Issue by simlay** [rust-lang/rust#124215]
In https://github.com/rust-lang/rust/pull/124089#pullrequestreview-2013141782, it was pointed out that there's not an easy way to know the minimum version of an apple OS that is supported. One must kind of grep for `*_DEPLOYMENT_TARGET` and then parse the output to retrieve an answer and get an answer.

If I read the source correctly, the minimum supported versions currently are:
* [watchOS 5.0](https://github.com/rust-lang/rust/blob/54692c3d0b873a5dc055f2f35081d0d6a2410a49/compiler/rustc_target/src/spec/base/apple/mod.rs#L369)
* [tvOS 10.0](https://github.com/rust-lang/rust/blob/54692c3d0b873a5dc055f2f35081d0d6a2410a49/compiler/rustc_target/src/spec/base/apple/mod.rs#L354C4-L354C76) 
* [visionOS 1.0](https://github.com/rust-lang/rust/blob/54692c3d0b873a5dc055f2f35081d0d6a2410a49/compiler/rustc_target/src/spec/base/apple/mod.rs#L384)
* [macOS 10.12 for non arm and 11.0 for arm macOS](https://github.com/rust-lang/rust/blob/54692c3d0b873a5dc055f2f35081d0d6a2410a49/compiler/rustc_target/src/spec/base/apple/mod.rs#L264-L276)
* [iOS 14 for arm64e, 13.1 for mac catalyst and 10.0 otherwise](https://github.com/rust-lang/rust/blob/54692c3d0b873a5dc055f2f35081d0d6a2410a49/compiler/rustc_target/src/spec/base/apple/mod.rs#L320-L329)

The versions are occasionally bumped up as in https://github.com/rust-lang/compiler-team/issues/556 and so it would be good write them down in a more human readable form.

This has lead to various [code comments about version support for various platforms being a little inconsistent](https://github.com/rust-lang/rust/blob/453ceafce32ef8108c604bca5e165ab41d3d6d8c/library/std/src/sys/pal/unix/fd.rs#L248-L251). It is possible this comment is to mean "minimum version of this syscall" but that is unclear.

I will admit that I'm not certain as to the best way to do this. Adding these to [the platform support docs](https://doc.rust-lang.org/rustc/platform-support.html) seems like the right choice. Perhaps also in [the specific platform support page](https://doc.rust-lang.org/rustc/platform-support/apple-tvos.html)

Some of the tier 3 pages list a minimum and some do not. [`arm64e-apple-ios` for example lists 12.0+](https://doc.rust-lang.org/rustc/platform-support/arm64e-apple-ios.html) and [`arm64e-apple-darwin` lists 11+](https://doc.rust-lang.org/rustc/platform-support/arm64e-apple-darwin.html) however [watchOS](https://doc.rust-lang.org/rustc/platform-support/apple-watchos.html) and [tvOS](https://doc.rust-lang.org/rustc/platform-support/apple-tvos.html) do not.

Perhaps related: I am unfamiliar with target triples `arm64e-apple-ios` and `arm64e-apple-darwin`. Are these actually used?

CC: @madsmtm

**Comment by madsmtm** [comment]
We give the `arm64e-apple-*` triples a higher default deployment target since the hardware is only supported on those newer OS versions. It's technically the same story with `x86_64h-apple-darwin`, although there the version is macOS 10.8, which is lower than the minimum Rust already requires.

I think it's a good idea to add to the platform support docs, I was considering splitting it into the following pages / "categories":
- `*-apple-darwin`
- `*-apple-ios`
- `*-apple-tvos`
- `*-apple-watchos`
- `*-apple-visionos`
- `*-apple-ios-macabi` (Mac Catalyst is sufficiently different from iOS that it makes sense to document it separately)
- `x86_64h-apple-darwin` (Documents only the things relating to `x86_64h`, links to `*-apple-darwin` for the rest)
- `arm64e-apple-*` (Same idea as above)

Do you think that's a good idea? In any case, I'd like to do this work:
@rustbot claim

CC @Nilstrieb who is [working on target docs](https://github.com/rust-lang/rust/issues/120745)
CC @thomcc 

@rustbot label O-macos O-ios O-tvos O-watchos O-visionos

**Comment by madsmtm** [comment]
Related: `cc` [might require setting the deployment target when cross-compiling these platforms from non-macOS](https://github.com/rust-lang/cc-rs/pull/1009), so maybe it makes sense to have a top-level `*-apple-*` page explaining these targets in general, including cross compilation stuff?

**Comment by Nilstrieb** [comment]
The platform support docs are the right place for this, yes. I think adding it to the platform support docs and then also leaving a comment next to them linking to DEPLOYMENT_TARGET and the other way around should ensure that they stay in sync.
