### ISSUE TITLE
lint for matches with a single case

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#12447]
Some of these are still around from when `let` patterns were totally broken. It'd also be nice from a pedagogical perspective.

**Comment by steveklabnik** [comment]
Traige: this lint still does not exist.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
