### ISSUE TITLE
regression: cannot find macro in scope

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#125201]
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/stusmall.bowbend/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/xupea.rust-cargo-neo/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/bitmap-font-0.3.0/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/dora-operator-api-types-0.3.0/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/mls-rs-ffi-0.2.0/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/pacaptr-0.20.1/log.txt

```
[INFO] [stdout] error: cannot find macro `stringified_module_code` in this scope
[INFO] [stdout]   --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/safer-ffi-0.1.4/src/libc.rs:9:10
[INFO] [stdout]    |
[INFO] [stdout] 9  | #![doc = stringified_module_code!()]
[INFO] [stdout]    |          ^^^^^^^^^^^^^^^^^^^^^^^ consider moving the definition of `stringified_module_code` before this call
[INFO] [stdout]    |
```

**Comment by compiler-errors** [comment]
searched commit range: https://github.com/rust-lang/rust/compare/4d570eea025a19564429eb52b34ec34e14659f55...aed2187d53b8789e3a37f50ae36f894a2a679077
regressed commit: https://github.com/rust-lang/rust/commit/35194e76b769d57ecb243b202228cce24158041b

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2024-04-01 
```
</details>

Did this regress in #124382? cc @petrochenkov

**Comment by compiler-errors** [comment]
Specifically 7517a4f882083a46593417560cdd19c10c3fc5cf seems suspicious due to title alone, didn't look into it much though.

**Comment by dtolnay** [comment]
This was reported by one of the affected crate authors in https://github.com/rust-lang/rust/issues/124535.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23125201.20regression.3A.20cannot.20find.20macro.20in.20scope/near/439128819)).

Since these crates regressed, it could probably be good to keep this on the radar (release in 15 days)

@rustbot label -I-prioritize +P-high

**Comment by petrochenkov** [comment]
I plan to fix it later this week (https://github.com/rust-lang/rust/issues/124535 is assigned to me).

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/125734.

**Comment by danielhenrymantilla** [comment]
Thanks @petrochenkov! FWIW, I've since submitted a new version of `safer-ffi` which does not rely in this AST ordering quirk: maybe that way in a few months this "breakage" can take place? I wouldn't want `safer-ffi` to embody the following xkcd:

![image](https://github.com/rust-lang/rust/assets/9920355/a1ba6854-4503-4b81-96e4-61f51e6e391c)

**Comment by petrochenkov** [comment]
@danielhenrymantilla 
I plan to fix this properly in https://github.com/rust-lang/rust/pull/125741 after the initial regression is addressed (maybe with a temporary deprecation lint), so fixing crates exploiting this bug still make sense.

**Comment by lqd** [comment]
Reopening to track beta backport

**Comment by Mark-Simulacrum** [comment]
Closing, backported to beta.
