### ISSUE TITLE
It's not clear from the documentation when particular features were inctoduces or deprecated

### ISSUE THREAD

**Issue by yurivict** [rust-lang/rust#125281]
### Location

I am looking at the ```stdsimd``` feature documentation [here](https://doc.rust-lang.org/std/simd/index.html).

It looks like this is a current feature based on this page: there are no deprecation notices.

But rust-nightly-1.80.0.20240507 doesn't have this feature:
```
error[E0635]: unknown feature `stdsimd`
  --> /wrkdirs/usr/ports/lang/frawk/work/frawk-0.4.7/cargo-crates/ahash-0.7.6/src/lib.rs:33:42
```

It isn't obvious whether it was deprecated or not and not obvious where to get this information in a centralized way.

### Summary

Documentation doesn't say when particular features are introduces or deprecated.

**Comment by workingjubilee** [comment]
@yurivict the `std::simd` module, AKA `feature(portable_simd)`, has no relationship to `feature(stdsimd)`, due to a quirk of history.

Nightly features are unstable experiments and are subject to total removal if the experiment they represent does not pan out. You must update the ahash version to build that crate with a recent nightly compiler, or use a stable compiler, as the reason that ahash generates that error is because it tries to enable features by automatically detecting a nightly compiler, without those features explicitly being enabled.
