### ISSUE TITLE
How to enable rust-lld on stable?

### ISSUE THREAD

**Issue by kpp** [rust-lang/rust#125449]
The blogpost https://blog.rust-lang.org/2024/05/17/enabling-rust-lld-on-linux.html contains a solution how to disable rust-lld on nightly:

> If that happens, you can revert to the default linker with the -Z linker-features=-lld flag. 

However there is no instructions how to enable it on stable.

For example, the mold linker has a receipt for a rust/cargo project:

```
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
```

Is there such a receipt for rust-lld?

**Comment by lqd** [comment]
I'm not sure why you would do this compared to installing lld and doing what you did for lld instead of mold.

But if you want details: it's still unstable because we're still working on it. This is why it's not as easy to enable on stable, compared to nightly. For example, we'll move and rename the location where rust-lld is stored within the sysroot, but it's basically only doing:
- `-fuse-ld=lld`
- `-B` to a folder within the sysroot, which you can *currently* find via e.g. `find ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/ -name gcc-ld`.

This will break when we move/rename that folder, so I would advise not doing it, much like https://nnethercote.github.io/perf-book/build-configuration.html#linking describes using system lld. And when time comes for stabilization you'll have nothing to do, rust-lld will be enabled by default.

But if you only wanted to know, now you know ^^.

(I'll close this issue as it's not really a bug or feature request we need to track)

**Comment by petrochenkov** [comment]
Also, `RUSTC_BOOTSTRAP=1 rustc -Clinker-features=+lld -Clink-self-contained=+linker`, if the corresponding features reached stable channel.
(With obvious lack of stability guarantees, of course.)

**Comment by lqd** [comment]
with a `-Zunstable-options`
