### ISSUE TITLE
Doc and rustdoc cross-document cross-references

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#12554]
Right now every piece of documentation we have is self-contained, without an easy way to write hyperlinks between them. As we ramp up our documentation efforts it's important that we be able to link our docs together.

I'm thinking the first step is to unify our pandoc and rustdoc toolchains (#11392), then teach rustdoc some way to do links between documents.

**Comment by steveklabnik** [comment]
This is not likely to get fixed anytime soon, as Markdown doesn't have any kind of standard for how to mark up something like this. As it would be a pretty big extension / change, I'd imagine this would go through the RFC process, since Rustdoc is part of the Rust distribution, and so I'm going to give it a close here. In practice, writing manual links leads to breakgage sometimes, but it's not too hard to fix, and we have other bugs open to try to and keep up with 404s more generally.
