### ISSUE TITLE
Extend dead code detection to cover files that are not loaded

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#12565]
If I have a whole tree of `*.rs` files and one of them is not included in the compilation, that is probably an error on my part. I propose a new lint to this effect.

When compiling without `cfg(test)`, I suggest that files named `test.rs` or `tests.rs` and the contents of directories named `test` or `tests` be ignored.

To suppress this lint for individual files, we would add an attribute such as `#[allow_unloaded_file = "foo.rs"]`. That could go on a module in the appropriate place in the filesystem or on the crate itself.

This occurred to me when I found `src/librustc/middle/typeck/infer/test.rs` with a few syntax errors (#12564).

**Comment by fhahn** [comment]
I've started working on a compiler [plugin](https://github.com/fhahn/rust-unused-files/blob/master/src/lib.rs) that adds a lint to detect unused files. At the moment, it only analysis a single crate (e.g. `src/lib.rs`) and all files in subdirectories of the crate root.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
