### ISSUE TITLE
"--json-output" is ignored by tool builds

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#125666]
When doing something like `./x.py build miri --json-output`, then the errors/warnings in Miri itself are still reported in the normal, human-readable form, and not as JSON.

I assume something somewhere [around here](https://github.com/rust-lang/rust/blob/4c075c622cd929c1561fcbfc369813aceefb86f1/src/bootstrap/src/core/build_steps/tool.rs#L114) has to use a different function for running cargo, e.g. [this one](https://github.com/rust-lang/rust/blob/28ce76eba429603624455e13f52a0dca8147ae8e/src/bootstrap/src/core/build_steps/compile.rs#L1901).

Cc @onur-ozkan

**Comment by onur-ozkan** [comment]
For tools, we handle the build results later even if they fail: https://github.com/rust-lang/rust/blob/7717a306b2678ba9ece19b723c76a6b3a89ba931/src/bootstrap/src/core/build_steps/tool.rs#L114-L134

`compile::run_cargo` doesn't provide that interface, but we can modify it to do so (since it uses `compile::stream_cargo` under the hood, which returns the command result without panicking).

**Comment by RalfJung** [comment]
All this toolstate stuff is not needed any more, though. We only use toolstate for books these days, so the tools can be cleaned up.

**Comment by RalfJung** [comment]
Thanks for the fix :)
