### ISSUE TITLE
Strange TcpStream TTL type implementation (set_ttl/ttl)

### ISSUE THREAD

**Issue by cavivie** [rust-lang/rust#126592]
According to the [IPv4 RFC][0] and the [IPv6 RFC][1], both IPv4 (time to live) and IPv6 (hop limit) should have a size of u8, but the Rust [implementation](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.set_ttl) uses u32. I don't know why it is implemented this way, and there is no documentation.

[0]: https://datatracker.ietf.org/doc/html/rfc791#autoid-9
[1]: https://datatracker.ietf.org/doc/html/rfc2460#autoid-3

**Comment by tbu-** [comment]
Can't be changed in a backward compatible manner.

The full number is passed to the kernel which will likely error if the number greater than 255.

I have verified that Linux errors in the above case.

I think this can be closed since it won't be changed due to the backward compatibility constraints and the problem isn't too bad.

**Comment by cavivie** [comment]
Can this be solved by adding an api and marking this api as deprecated?

**Comment by tbu-** [comment]
I'm not a person in charge of creating new APIs. You'd need to ask the libs team for that. I'd create a pull request for that.

Looking at the source code of the Linux kernel, IPV6_HOPLIMIT only accepts 32-bit integers (and then checks that they're between 1 and 255). I wouldn't change the API if the kernel itself deals with 32-bit integers.

**Comment by tbu-** [comment]
Can this be closed?

**Comment by cavivie** [comment]
Yes,plz
