### ISSUE TITLE
integer_decode() for float: example usage in docs doesn't make sense

### ISSUE THREAD

**Issue by AdamSlayer** [rust-lang/rust#126610]
### Location

float.rs line 1867, in this "example usage" code:

```
use num_traits::Float;

let num = 2.0f32;

// (8388608, -22, 1)
let (mantissa, exponent, sign) = Float::integer_decode(num);
let sign_f = sign as f32;
let mantissa_f = mantissa as f32;
let exponent_f = num.powf(exponent as f32);

// 1 * 8388608 * 2^(-22) == 2
let abs_difference = (sign_f * mantissa_f * exponent_f - num).abs();

assert!(abs_difference < 1e-10);
```

### Summary

This code only works when `num = 2.0`. With `num` having almost any other value, the `assert!` at the end fails. For example, with `let num = 2.5f32;`, instead of `let num = 2.0f32;`, the abs_difference is `2.4815533`. I think the problem is not in the function itself, but in the example code provided in the documentation.

**Comment by jhorstmann** [comment]
Not too familiar with the implementation, but I guess `num.powf(exponent as f32)` should be `2_f32.powf(exponent as f32)`, regardless of the input number. Choosing `2.0` also as the input for this example is indeed confusing.

**Comment by mtilda** [comment]
I believe this issue was posted in the wrong repository, as this relates to the crate [num-traits](https://docs.rs/crate/num-traits/0.2.19). I recommend opening a new issue at [github.com/rust-num/num-traits](https://github.com/rust-num/num-traits).

The example referenced in this issue can be found at [num_traits::float::Float::integer_decode](https://docs.rs/num-traits/0.2.19/num_traits/float/trait.Float.html#tymethod.integer_decode).

The source code is located at [src/float.rs#L1863-L1881](https://github.com/rust-num/num-traits/blob/7ec3d41d39b28190ec1d42db38021107b3951f3a/src/float.rs#L1863-L1881).
