### ISSUE TITLE
Main thread thread-local destructors are not always run

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#126858]
Simplified testcase:
```rust
struct Foo;

impl Drop for Foo {
    fn drop(&mut self) {
        println!("Foo dtor");
    }
}

thread_local!(static FOO: Foo = Foo);

fn main() {
    FOO.with(|_| {});
}
```

This should print `Foo dtor`, but prints nothing on some targets:
- [ ] musl (e.g. i686-unknown-linux-musl, x86_64-unknown-linux-musl)
- [ ] android (e.g. arm-linux-androideabi)
- [ ] Linux with [glibc before 2.18](https://github.com/rust-lang/rust/pull/126829#issuecomment-2187674002)
- [ ] Maybe more?

Here's a more complicated testcase that also involves initializing a destructor while destructors are being run; ideally this will be added to the test suite at some point:
```rust
struct Bar;

impl Drop for Bar {
    fn drop(&mut self) {
        println!("Bar dtor");
    }
}

struct Foo;

impl Drop for Foo {
    fn drop(&mut self) {
        println!("Foo dtor");
        // We initialize another thread-local inside the dtor, which is an interesting corner case.
        thread_local!(static BAR: Bar = Bar);
        BAR.with(|_| {});
    }
}

thread_local!(static FOO: Foo = Foo);

fn main() {
    FOO.with(|_| {});
}
```

**Comment by bjorn3** [comment]
For musl the thread-local destructors registered with `pthread_key_create` seem to get run by `__pthread_tsd_run_dtors`, which is only called from `pthread_exit`. For bionic (Android's libc) they get run from `pthread_key_clean_all`, which too is only called from `pthread_exit`. It doesn't seem to be documented anywhere officially if exiting the main thread without `pthread_exit` should invoke thread-local destructors. Several stack overflow posts say it doesn't which is the behavior observed for musl and bionic, while glibc has been calling them since 2004 (https://github.com/bminor/glibc/commit/3fa21fd813ac323f2890812b99663d7cf17578eb).

**Comment by workingjubilee** [comment]
[What](https://www.youtube.com/watch?v=F_LJGnfatd0).

**Comment by RalfJung** [comment]
Closing in favor of the original, https://github.com/rust-lang/rust/issues/28129.
