### ISSUE TITLE
gmtime and localtime aren't thread-safe so using them is unsound

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#12693]
It's unclear if these wrappers in rust_builtin.c are actually used anywhere, but the code should be removed either way.

**Comment by deokjinkim** [comment]
As I know, gmtime and localtime are thread-safe on Windows(Microsoft) because such functions use static output area per thread.
And for other platform, gmtime_r and localtime_r are thread-safe version.
So I think current usage of above function is not problem.
Do you mean timezone variable(TZ) for localtime may cause thread-safety issue?

**Comment by klutzy** [comment]
The relevant code is `rt/rust_builtin.c`. `libtime` used them via `rust_{gm,local}time` but libtime has been moved out of tree.
cc #20861

**Comment by klutzy** [comment]
#21391 removed time wrappers. Fixed!
