### ISSUE TITLE
spurious ci failure: `The process cannot access the file because it is being used by another process`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#127126]
See https://github.com/rust-lang/rust/pulls?q=is%3Apr+%22The+process+cannot+access+the+file+because+it+is+being+used+by+another+process%22+is%3Aclosed 

seems to happen on `x86_64-msvc-ext`a lot
```
[RUSTC-TIMING] miri test:false 64.073
[RUSTC-TIMING] miri test:false 2.939
    Finished `release` profile [optimized] target(s) in 0.39s
thread 'main' panicked at src/lib.rs:1697:17:
failed to copy `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1-tools\x86_64-pc-windows-msvc\release\miri.exe` to `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1-tools-bin\miri.exe`: The process cannot access the file because it is being used by another process. (os error 32)
##[endgroup]
Build completed unsuccessfully in 0:00:11
  local time: Sat, Jun 29, 2024  5:48:11 PM
  network time: Sat, 29 Jun 2024 17:48:11 GMT
```

**Comment by ChrisDenton** [comment]
The bootstrap code that panics hasn't changed in years: https://github.com/rust-lang/rust/blob/d1b7355d3d7b4ead564dbecb1d240fcc74fff21b/src/bootstrap/src/lib.rs#L1697 so I doubt that's the cause but a workaround would be to add a retry loop.

It would be interesting to know what's changed recently to cause this. "os error 32" is a sharing violation, which is usually because the file is locked in certain way. But, as far as I'm aware, we don't do that kind of locking. Maybe someone who knows bootstrap well has some ideas.
