### ISSUE TITLE
rustdoc json output on stdout ?

### ISSUE THREAD

**Issue by gl-yziquel** [rust-lang/rust#127165]
Hi.

As of today, it seems that there is no out of the box way to get rustdoc json output on stdout. I see no way to augment the `rustdoc src/lib.rs -Zunstable-options --output-format json` invocation to handle output on stdout.

This is a shame as I'd like to perform rustdoc -> some jq or better for preprocessing -> tera templating -> makeinfo for texinfo generation, all of that through pipes.

As of today, the only piece of code that doesn't support piping in the above is rustdoc.

Being kind of a dinosaur, I like to get things done the old unixish way, with one tool doing something and only that, and having pipe support would allow to generate my texinfo manual from rustdoc json output without having to go jumping through hoops using temporary files.

**Comment by chenyukang** [comment]
I also want this feature in our project.

Seems we already have the json render backend:
https://github.com/rust-lang/rust/blob/6292b2af620dbd771ebb687c3a93c69ba8f97268/src/librustdoc/lib.rs#L828

but currently does not enable it in command line options:
https://github.com/rust-lang/rust/blob/6292b2af620dbd771ebb687c3a93c69ba8f97268/src/librustdoc/lib.rs#L224

@jyn514 do you know the the reason?

link https://github.com/rust-lang/rfcs/pull/2963

**Comment by jyn514** [comment]
an rfc being accepted does not automatically stabilize the feature. the tracking issue is https://github.com/rust-lang/rust/issues/76578, as linked in this rfc.

i am not sure how that's related to this issue, which is asking for json on stdout. html is stable and does not support stdout; they are independent issues.

finally, i have a "busy" indicator for a reason; i no longer work on rust. please do not ping me in random rust issues.

**Comment by aDotInTheVoid** [comment]
@chenyukang, due to Historical Reasons (TM) (#32773), rustdoc support `rustdoc --output-format=html` on stable, but `rustdoc --output-format=json` requires nightly.

See [here](https://github.com/rust-lang/rust/blob/2db4ff40af2b9f93b6240dbd67ed7f2f34b19776/src/librustdoc/config.rs#L434-L442) and [here](https://github.com/rust-lang/rust/blob/2db4ff40af2b9f93b6240dbd67ed7f2f34b19776/src/librustdoc/config.rs#L689-L702) for how this is implemented. You can totally use rustdoc-json on nightly today, either with [cargo](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#output-format-for-rustdoc), or [rustdoc directly](https://doc.rust-lang.org/nightly/rustdoc/unstable-features.html#-w--output-format-output-format).

However, both of these only support writing the output json to disk. What this issue is asking for is for is supporting outputting to `stdout`, instead of the filesystem.

**Comment by gl-yziquel** [comment]
@aDotInTheVoid @chenyukang Yes. This is about stdout json output. To be able to chain stuff the old unixish way using pipes and all.

**Comment by GuillaumeGomez** [comment]
I think it's a good idea. Adding it.
