### ISSUE TITLE
Use of match ergonomics affect borrow checking

### ISSUE THREAD

**Issue by hniksic** [rust-lang/rust#127238]
This code fails to compile due to a borrow check error:

```rust
fn insert(v: &mut Option<u32>) -> Option<&u32> {
    if let Some(r) = &v {
        return Some(r)
    }
    *v = next_token();
    v.as_ref()
}

fn next_token() -> Option<u32> {
    unimplemented!()
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1a0102bc967ac3cd4cdb6ef902b4809c)

The compiler complains that "cannot assign to `*v` because it is borrowed", which is a [well-known borrow checker limitation](https://blog.rust-lang.org/2022/08/05/nll-by-default.html#looking-forward-what-can-we-expect-for-the-borrow-checker-of-the-future). However, I was surprised to [discover](https://www.reddit.com/r/rust/comments/1dt7crv/comment/lb9brv9/) that it compiles using `ref` matching in `if let`:

```rust
fn insert(v: &mut Option<u32>) -> Option<&u32> {
    if let Some(ref r) = v {
        return Some(r)
    }
    *v = next_token();
    v.as_ref()
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b62f9bc55d8276e28514b7b97e62fefc)

I would expect the former code to desugar to the latter, as per ["match ergonomics"](https://rust-lang.github.io/rfcs/2005-match-ergonomics.html). In other words, I'd expect both examples to be accepted by the compiler, or both to be rejected (ideally the former).

This issue is **not** intended as a report regarding the borrow checker limitation that will be fixed by Polonius. It is about the perceived equivalence of match-ergonomics match and the manually written one, which I'd expect to lead to the same borrow-checking outcomes.

### Meta

This is on rustc 1.79.

**Comment by SNCPlay42** [comment]
The problem here is the `&` in `&v`, not anything else, as indicated by the first error emitted (which I believe is correct):

```
error[E0515]: cannot return value referencing function parameter `v`
 --> src/lib.rs:3:16
  |
2 |     if let Some(r) = &v {
  |                      -- `v` is borrowed here
3 |         return Some(r)
  |                ^^^^^^^ returns a value referencing data owned by the current function
```

Even if you avoid the well-known borrow check limitation, [the code still won't compile](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=be35f06765a06ff736fdcd51661a388b).

The second code sample also lacks that `&`, [and breaks in the same way if you add it](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=666c96d00a9edab6b32865380bf06b28) so I don't think the match ergonomics has anything to do with it.

**Comment by hniksic** [comment]
@SNCPlay42 Thanks for the explanation. Closing accordingly.
