### ISSUE TITLE
Generated assembly contains duplicated instructions

### ISSUE THREAD

**Issue by ChaiTRex** [rust-lang/rust#127641]
I tried this code:

```rust
#[inline(never)]
pub fn next_back_1(len: &mut u8, bits: &mut u16) -> Option<u8> {
    if *len == 0 {
        None
    } else {
        *len -= 1;
        let result = *bits as u8 & 1;
        *bits >>= 1;
        Some(result)
    }
}
```

I expected to see this happen: *Generated assembly doesn't contain duplicated code.*

Instead, this happened: *Generated assembly does contain duplicated code.*

On `x86_64-unknown-linux-gnu`, notice that the three instructions above and the three instructions below `.LBB0_1` are identical, which means that the latter instructions can be removed if the label is moved up three instructions, reducing code size:

```asm
bug::next_back_1:
 movzx   eax, byte, ptr, [rdi]
 test    al, al
 je      .LBB0_1
 lea     ecx, [rax, -, 1]
 mov     byte, ptr, [rdi], cl
 movzx   ecx, word, ptr, [rsi]
 mov     edx, ecx
 and     dl, 1
 shr     ecx
 mov     word, ptr, [rsi], cx
 test    al, al
 setne   al
 ret
.LBB0_1:
 test    al, al
 setne   al
 ret
```

On `aarch64-apple-darwin`, the same thing occurs with the `LBB0_2` label:

```asm
bug::next_back_1:
 ldrb    w8, [x0]
 cbz     w8, LBB0_2
 sub     w9, w8, #1
 strb    w9, [x0]
 ldrh    w9, [x1]
 mov     x10, x1
 and     w1, w9, #0x1
 lsr     w9, w9, #1
 strh    w9, [x10]
 cmp     w8, #0
 cset    w0, ne
 ret
LBB0_2:
 cmp     w8, #0
 cset    w0, ne
 ret
```

### Meta
<details><summary><code>rustc --version --verbose</code></summary>

```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7
```
```
rustc 1.80.0-beta.5 (e5da71fca 2024-07-06)
binary: rustc
commit-hash: e5da71fca9bed167576232912271d7366e29bbc6
commit-date: 2024-07-06
host: x86_64-unknown-linux-gnu
release: 1.80.0-beta.5
LLVM version: 18.1.7
```
```
rustc 1.81.0-nightly (5315cbe15 2024-07-11)
binary: rustc
commit-hash: 5315cbe15b79533f380bbb6685aa5480d5ff4ef5
commit-date: 2024-07-11
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7
```
```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: aarch64-apple-darwin
release: 1.79.0
LLVM version: 18.1.7
```
```
rustc 1.80.0-beta.5 (e5da71fca 2024-07-06)
binary: rustc
commit-hash: e5da71fca9bed167576232912271d7366e29bbc6
commit-date: 2024-07-06
host: aarch64-apple-darwin
release: 1.80.0-beta.5
LLVM version: 18.1.7
```
```
rustc 1.81.0-nightly (5315cbe15 2024-07-11)
binary: rustc
commit-hash: 5315cbe15b79533f380bbb6685aa5480d5ff4ef5
commit-date: 2024-07-11
host: aarch64-apple-darwin
release: 1.81.0-nightly
LLVM version: 18.1.7
```

</details>

I get a different bug using Godbolt (#127640).

**Comment by eggyal** [comment]
Doesn't repro on Godbolt, neither for [`-O --target=x86_64-unknown-linux-gnu`](https://godbolt.org/z/73d4Pa9W3):

```asm
example::next_back_1::h48bde1edbc0e4b8a:
        movzx   eax, byte ptr [rdi]
        test    al, al
        je      .LBB0_1
        lea     ecx, [rax - 1]
        mov     byte ptr [rdi], cl
        movzx   ecx, word ptr [rsi]
        mov     edx, ecx
        and     dl, 1
        shr     ecx
        mov     word ptr [rsi], cx
        jmp     .LBB0_3
.LBB0_1:
.LBB0_3:
        test    al, al
        setne   al
        ret
```

nor [`-O --target=aarch64-apple-darwin`](https://godbolt.org/z/14ex7z4cW):

```asm
__ZN7example11next_back_117ha5e5b29a87ac44fdE:
        ldrb    w8, [x0]
        cbz     w8, LBB0_2
        sub     w9, w8, #1
        strb    w9, [x0]
        ldrh    w9, [x1]
        mov     x10, x1
        and     w1, w9, #0x1
        lsr     w9, w9, #1
        strh    w9, [x10]
        b       LBB0_3
LBB0_2:
LBB0_3:
        cmp     w8, #0
        cset    w0, ne
        ret
```

**Comment by pacak** [comment]
Unrelated, but this output looks like something produced by `cargo-asm` which is unmaintained. Try `cargo-show-asm` for a maintained alternative.

**Comment by bjorn3** [comment]
They do get folded together when optimizing for size. According to llvm-mca, the `-Copt-level=3` version with duplicate instructions takes 287 cycles for 100 repeats, while the `-Copt-level=s` version takes 313 cycles. In other words the version with duplicate instructions is supposedly faster: https://rust.godbolt.org/z/bdxPfxMrW Presumably LLVM decided not to deduplicate because of this.

**Comment by lukaslueg** [comment]
Although I can't point to the actual implementation and how/if this relates here, my strong guess is that this (and #127640) is due to branch-target-alignment: Depending on the specifics of the targeted CPU, it may be advantageous to ensure that the target of a branch-instruction is aligned to certain boundaries; e.g. Intel used to recommend that branch-targets are aligned to 16-byte-boundaries due to how the uops-cache works. LLVM (and gcc, etc.) implement this by injecting idempotent instructions (e.g. `jmp +0`, `nop`) or repeating blocks which could theoretically be merged.

With the example above, LLVM assumes the branch to execute slower if `.LBB0_1` was placed directly after `mov word, ptr, [rsi], cx`, at the cost of more instructions.

**Comment by workingjubilee** [comment]
Yes, what lukaslueg said is correct. And CPUs also take great interest in any `test` or `setne` instruction, I can tell you that much.

I'm going to close this: sorry, but sometimes compilers can do better than human assembly writers precisely because they emit such "strange-looking" code with apparent redundancies. Anyways, we don't have a benchmark that **shows the code is slower**, and we have evidence that suggests the result will indeed be faster, possibly especially so when considering larger programs. If either of these changes, then please feel free to reopen with new information.

Note also that I am closing it *because LLVM handles this case correctly when optimizing for size*, at which point that concern should override performance.
