### ISSUE TITLE
Duration Add and Sub impls panic in release mode

### ISSUE THREAD

**Issue by kushudai** [rust-lang/rust#127644]
Duration does not have the same overflow/underflow behavior as unsigned integers in release mode.

I tried this code:

```rust
use std::time::Duration;

fn main() {
    println!("{}", sub_u32(0, 1));
    println!("{}", add_u32(u32::MAX , 1));
    
    // These panic
    println!("{:?}", sub_duration(Duration::from_secs(0), Duration::from_secs(1)));
    println!("{:?}", add_duration(Duration::MAX , Duration::from_nanos(1)));
}

fn sub_u32(x: u32, y: u32) -> u32 {
    x - y
}

fn add_u32(x: u32, y: u32) -> u32 {
    x + y
}


fn add_duration(x: Duration, y: Duration) -> Duration {
    x + y
}

fn sub_duration(x: Duration, y: Duration) -> Duration {
    x - y
}
```

Link to playground: https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=bc49a172b2b37f5b6d5986733c5a79c9

I expected to see this happen: 
I expected Duration to wrap around like unsigned integers do.
They only panic in debug mode.

Instead, this happened:
Panic at runtime in release mode :(

### Meta
The behavior is the same in `master`: https://github.com/rust-lang/rust/blob/b286722878e18db29a7fbe672be7c4d3b02e8e4d/library/core/src/time.rs#L1128-L1153

`rustc --version --verbose`:
```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7
```

Backtrace
```
Finished `release` profile [optimized] target(s) in 1.03s
     Running `target/release/playground`
thread 'main' panicked at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/time.rs:1126:31:
overflow when subtracting durations
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::option::expect_failed
   4: playground::main
```

**Comment by eggyal** [comment]
I could understand if you wanted to eliminate the checked arithmetic in release mode at the cost of potentially having a wrapped result, but I can't think of any reason one would ever *want* to have wrapped arithmetic on `Duration`.  Could you provide more detail of your use case?

**Comment by kushudai** [comment]
Hi, thank you for looking at this :)
I am actually quite okay with eliminating checked arithmetic in release mode if we get wrapped results. The behavior would violate the principle of least surprise I guess.

My gripe is mainly the panic in release mode. I expect that behavior to be consistent with unsigned primitives.
Perhaps because I think of Duration as effectively a tuple of unsigned primitives but I guess that's an implementation detail.

**Comment by eggyal** [comment]
My point was that the *reason* default integer arithmetic wraps in release mode is purely a performance optimisation (otherwise it would be checked, which is quite costly).  I could understand if the issue here was similar: "*checked arithmetic on `Duration` is too costly performance-wise, so please could we not do by default that in release mode?*".

However that does not appear to be your point?  If I've understood correctly, you're saying that you expect it to reflect integer arithmetic not for performance reasons but instead because the current behaviour violates your expectations?  But I'm struggling to think of any situation where wrapped arithmetic on `Duration` is ever anything but an error (whereas wrapped integer arithmetic is sometimes actually desirable, which is why explicit wrapping methods exist for integers but I note do not exist for `Duration`).

Perhaps this is simply a documentation bug: `Duration` should clearly document that overflow will panic by default, and the `checked` or `saturating` methods should explicitly be used if different behaviour is desired?  That should help to correctly set expectations?

**Comment by Nilstrieb** [comment]
Yeah, we're not gonna make our bug checking behavior worse for the sake of consistently having bad bug checking behavior.

**Comment by oli-obk** [comment]
I was working on a branch documenting that (https://github.com/oli-obk/rust/pull/new/duration_checked_math), but I don't think we should even document that. Even for builtin types *it is considered a bug* if you overflow in release mode. As mentioned, the point of disabling checks in release mode is performance, not the fact that we consider overflow correct and just want to help you in debug mode.

We'd effectively would have to add this kind of documentation to every type that has some math operator created for it.

So... I'm just going to close this issue. If you think this should be documented, the best place would probably be the Rust reference section on builtin math ops

**Comment by kushudai** [comment]
That makes sense. That said, it would be awesome if the trait impls for Sub/Add/Mul/Div documented the panic on the `Duration` type. I am happy to make a new issue or a PR if that is preferred if I could be pointed in the right direction.

**Comment by Nilstrieb** [comment]
no, what oli suggested is having docs that say "this is generally expected to panic on overflow unless there are performance requirements that would forbid this, which is for example true for integers in release mode"

**Comment by kushudai** [comment]
Okay that makes sense. Thanks! I'll try to figure out where I should be making a PR. Appreciate the eyes folks!
