### ISSUE TITLE
Lint for redundant lifetimes.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#12805]
Sometimes refactorings can leave behind needlessly generic functions, like in this case:
```rust
fn foo<'a>(foo: &'a Foo<'a>) {...}
```
becomes
```rust
type Foo<'a> = &'a FooStruct<'a>;
fn foo<'a>(foo: Foo<'a>) {...}
```
If the lifetime `'a` is not used anywhere else in `foo`, it isn't any different from an anonymous lifetime.

**Comment by steveklabnik** [comment]
Full example:

```
struct Foo<'a>;
fn foo<'a>(foo: &'a Foo<'a>) { }

fn main() {}
```

**Comment by Toby-S** [comment]
@steveklabnik this is [an error](http://is.gd/YuLPO8) as of pre-1.0, so I think this can be closed?

**Comment by eddyb** [comment]
@Toby-S No, @steveklabnik's example is unrelated to the actual issue.

**Comment by Toby-S** [comment]
@eddyb thanks.

Full example:

```rust
struct FooStruct<'a>{
    val: &'a u8
}

type Foo<'a> = &'a FooStruct<'a>;
fn foo<'a>(foo: Foo<'a>) { } // could be: fn foo(foo: Foo) { }

fn main() { }```

**Comment by jonas-schievink** [comment]
Doesn't clippy have a Lint for non-elided lifetimes?

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
