### ISSUE TITLE
Regression in `type annotations needed for` check between 1.79 and 1.80

### ISSUE THREAD

**Issue by Fishrock123** [rust-lang/rust#128242]
### Code

I tried this code:

```toml
[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
time = { version = "=0.3.34", features = ["formatting"] }
```

```
cargo check
```

Code in question for this version: https://github.com/time-rs/time/blob/f11f9b2a0c8d17badd96a8a9167d81466a3fa39b/time/src/format_description/parse/mod.rs#L66-L87

This existing source code should continue to work fine between Rust 1.79 and 1.80.

Instead, this happened:

```
error[E0282]: type annotations needed for `Box<_>`
  --> /Users/jsenkpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```

### Version it worked on

It most recently worked on: 1.79

### Version with regression

`rustc --version --verbose`:
```
rustc 1.80.0 (051478957 2024-07-21)
binary: rustc
commit-hash: 051478957371ee0084a7c0913941d2a8c4757bb9
commit-date: 2024-07-21
host: aarch64-apple-darwin
release: 1.80.0
LLVM version: 18.1.7
```

-----

I think the issue was fixed by this change in `time` for `0.3.35`. However, it should still not fail between regular Rustc version upgrades.

_Apparent_ fix in `time @ 0.3.35`: https://github.com/time-rs/time/commit/5b0c627366babea1636b35db641c0fec964ddbd1 - https://github.com/time-rs/time/pull/671

</p>
</details>

**Comment by lqd** [comment]
See https://github.com/rust-lang/rust/issues/127343 and https://github.com/rust-lang/rust/issues/127343#issuecomment-2218261296

**Comment by tgross35** [comment]
To add some context: type inference is one of the few behaviors that is not covered by Rust's stability guarantees, partially because adding new library items can break it. Obviously no regressions is _always_ the goal, but it does mean that sometimes we accept inference regressions for things that objectively make Rust better - like here.

Being able to specify the type means that there is always a fix that works for all rust versions. Also, `time` has already accounted for this - just needs an update.
