### ISSUE TITLE
Permit library-only and binary-only dependencies

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust#128220]
Rust permits a package to contain both a library and a binary. However, any dependencies are necessarily shared, which is frequently undesirable. The only available alternative is to split the package in two, at which point the name (on crates.io) must be different.

My specific use case is avoiding deps like `clap` for anyone building a library, which adds needless overhead when building (even if only in non-incremental builds).

How feasible would it be to have `[bin-dependencies]` and `[lib-dependencies]` sections? These sections would extend the existing `[dependencies]` for backwards compatibility. Alternatively, a dependency could be specified with `{ bin = true, lib = false }` or similar.

**Comment by lqd** [comment]
This issue should probably be moved to cargo's repository.

**Comment by Skgland** [comment]
As the binary implicitly depends on the lib I don't think `[lib-dependencies]` would be necessary, as they would implicitly be transitive dependencies of the bin.
One could make the binary only dependencies optional dependencies and [require a feature](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-required-features-field) for the binary that enables these dependencies.

Note that there is https://github.com/rust-lang/cargo/issues/1982 that is basically a dupplicate, and there was https://github.com/rust-lang/cargo/issues/10409 which was closed due to significant overlap with https://github.com/rust-lang/cargo/issues/4663

**Comment by jhpratt** [comment]
I forgot cargo was its own repo. Closing in favor of that long-standing issue.
