### ISSUE TITLE
Rust version conflicts for vxworks

### ISSUE THREAD

**Issue by biabbas** [rust-lang/rust#128335]
To build and ship rust for vxworks, 
1. I get the 1.80.0 sources
2. I apply a patch for library/std
3. I build libraries with command `x build -i 10 --target=some_vxworks_target`

the problem is the libraries are compiled with rust 1.80.0-dev as the stage 1 compiler rustc is of version 1.80 dev. But I want the libraries to be compiled with rust 1.80.0.

**Comment by tgross35** [comment]
You can pass `./x build --stage 0 library` to build only the library, using the beta compiler at that snapshot. If you need something more specific, you can set the key in config.toml https://github.com/rust-lang/rust/blob/66e5852c3bd022e2a589a089a0bc8392f8b291e1/config.example.toml#L216-L224.

**Comment by biabbas** [comment]
I used 
[rust]
channed="stable" 
I've encountered errors with compiler buitins now. Thank you.

**Comment by tgross35** [comment]
The standard library is really only guaranteed to build with the version of Rust that it ships with, since it has a lot of implementation details.

If you want something for distribution, the usual way is to `./d.py dist —target …` which is what CI uses (takes a while). Or `./x build library —target …` if you only want the standard library.

I am not sure what you are trying to gain by building with a specific version but it seems unlikely to be worth it.

**Comment by biabbas** [comment]
@tgross35 For distribution we ship standard libraries of all vxworks targets with rustup stable toolchains. If the standard libraries are build with 1.80-dev, We'll get a mismatch when we use rustup provided stable 1.80.0 rustc. 
Right now, the libraries are successfully built when the channel is dev.
But I get error in compiler builtins when I try to build it with stable channel.

**Comment by workingjubilee** [comment]
@biabbas Yes, you must use a nightly/dev rustc to build the standard library, and build the stable compiler with that standard library.

**Comment by workingjubilee** [comment]
The only supported way of generating a toolchain is via [bootstrap](https://github.com/rust-lang/rust/tree/master/src/bootstrap), and what you are doing sounds like an ad-hoc reimplementation of such. You can read more in the [rustc-dev-guide on building targets for cross-compilation](https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html#building-targets-for-cross-compilation).

The relevant key for setting in the config.toml is this:

https://github.com/rust-lang/rust/blob/83dcdb3a5dad0ed1e3e1fadc848d3f7727b41aa5/config.example.toml#L203-L210

I am going to close this because this issue is unrelated to VxWorks and will not be fixed. I suggest asking on Zulip if you need further help.
