### ISSUE TITLE
bootstrap: `core::config::tests::detect_src_and_out` test fails if checkout is not under `C` drive

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#129188]
On native Windows:

```
---- core::config::tests::detect_src_and_out stdout ----
thread 'core::config::tests::detect_src_and_out' panicked at src\core\config\tests.rs:72:13:
assertion `left == right` failed
  left: "E:\\tmp"
 right: "C:\\tmp"
```

**Comment by ChrisDenton** [comment]
This looks sus:
```rust
test(parse("build.build-dir = \"/tmp\""), build_dir);
```

That's a `/tmp` which is an absolute Unix path. On Windows it will be interpreted relative to the root of the current directory. For example, if your current directory is `R:\path\to\rust` then it'll be `R:\tmp`.

(Also it'd be nice to use raw strings here because the `\"\"` is confusing in the context of paths)
