### ISSUE TITLE
Lifetime elision behaves differently when using Cell

### ISSUE THREAD

**Issue by Kither12** [rust-lang/rust#129151]
This compiles:

```rust
pub struct Foo<'a> {
    s: &'a str,
}

impl<'a> Foo<'a> {
    pub fn do_sth(&'a self, s: &'a str) {}
}

fn bar(s: &str, foo: &Foo) {
    foo.do_sth(s);
}

```
but this doesn't 
```rust
pub struct Foo<'a> {
    s: Cell<&'a str>,
}

impl<'a> Foo<'a> {
    pub fn do_sth(&'a self, s: &'a str) {}
}

fn bar(s: &str, foo: &Foo) {
    foo.do_sth(s);
}
```
```
error: lifetime may not live long enough
  --> src/main.rs:12:5
   |
11 | fn bar(s: &str, foo: &Foo) {
   |           -     --- has type `&Foo<'2>`
   |           |
   |           let's call the lifetime of this reference `'1`
12 |     foo.do_sth(s);
   |     ^^^^^^^^^^^^^ argument requires that `'1` must outlive `'2`
   |
help: consider introducing a named lifetime parameter
   |
11 | fn bar<'a>(s: &'a str, foo: &Foo<'a>) {
   |       ++++     ++               ++++


```
It also doesn't work when replacing Cell with RefCell, UnsafeCell, ...
I'm not sure if it's a bug or not, but I think it should compile in both cases.

**Comment by hanna-kruppe** [comment]
Not a bug: lifetime elision works the same in both cases, i.e., bar has multiple lifetime parameters (‘1 and ‘2 in the compiler error message). In the first case that doesn’t cause problems because Foo is covariant with respect to its lifetime parameter so the do_sth call works with a shortened borrow for its ‘a. The version with Cell doesn’t work because there Foo is (and must be, for soundness) invariant with respect to its lifetime parameter. For a somewhat dated (explaining lifetimes as regions of code) but essentially correct explanation of variance, see https://doc.rust-lang.org/nomicon/subtyping.html

**Comment by Kither12** [comment]
Ah thank you so much, this is the first time I've heard about lifetime variance. I thought the nomicon is only about unsafe rust so didn't read it :(( thanks you so much btw.
