### ISSUE TITLE
multiple platforms incorrectly impl `thread::sleep` with `Duration::as_micros`

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rust#129212]
Multiple targets currently use `Duration::as_micros` to implement conversion from a Duration to a value in microseconds. However, `thread::sleep` currently reads as so:

> Platforms which do not support nanosecond precision for sleeping will have `dur` rounded up to the nearest granularity of time they can sleep for.

*Up*. Note this [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b1d51bbe397c3efce26c2aed33752479) which means `Duration::as_micros` is **not** a valid implementation of this spec.

Note that this is not the only problem that espidf poses with respect to its std implementation: https://github.com/rust-lang/rust/issues/129136

### Meta

`rustc --version --verbose`:
```
rustc 1.82.0-nightly (2c93fabd9 2024-08-15)
binary: rustc
commit-hash: 2c93fabd98d2c183bcb3afed1f7d51b2517ac5ed
commit-date: 2024-08-15
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0
```

**Comment by workingjubilee** [comment]
cc @ivmarkov @mabezdev @SergioGasquez

I must unfortunately reiterate my recommendation from #127747 re: auditing code, but without restriction to the `unsafe` qualifier.

**Comment by workingjubilee** [comment]
Same bug: https://github.com/rust-lang/rust/blob/0f26ee4fd95a1c046582dfb18892f520788e2c2c/library/std/src/sys/pal/hermit/thread.rs#L78-L83

cc @stlankes @mkroening

**Comment by ivmarkov** [comment]
> First found on espidf:
> 
> https://github.com/rust-lang/rust/blob/0f26ee4fd95a1c046582dfb18892f520788e2c2c/library/std/src/sys/pal/unix/thread.rs#L268-L272
> 
> cc @ivmarkov @MabezDev @SergioGasquez

@workingjubilee 

Agreed - problem is clear and I'll and will fix shortly - thanks for noticing!

An interesting question here is whether it is allowed - in `thread:sleep` - to busy-wait for sleeping? Because this is exactly what would happen on the ESP IDF [if the supplied duration is less than 10ms (milliseconds) - i.e. the smallest FreeRTOS sys-tick](https://github.com/espressif/esp-idf/blob/d7ca8b94c852052e3bc33292287ef4dd62c9eeb1/components/newlib/time.c#L201). Given that the `thread:sleep` documentation is silent in this regard, I suggest to keep the current behavior (i.e. busy-waiting for durations < 10ms) as that allows callers of `thread::sleep` to "at least do some sleep - busy-looping or not".

> Note that this is not the only problem that espidf poses with respect to its std implementation: https://github.com/rust-lang/rust/issues/129136

I don't think this is a problem on the ESP IDF, [as it does not support POSIX signals in the first place](https://www.esp32.com/viewtopic.php?t=8910). Or processes thereof.

**Comment by workingjubilee** [comment]
Yes, I believe busy-waiting is a valid implementation of sleep, and especially in particular, if we were to have a hypothetical `fn sleep_can_sleep_for_this_long(dur: Duration) -> bool` that returned false, I would expect busy-waiting to be on the other side of the if/else almost every single time.
