### ISSUE TITLE
Making default case always the last case in a `match` expression

### ISSUE THREAD

**Issue by sitetester** [rust-lang/rust#129549]
1.
```
fn check_number(input: i8) {
    match input {
        _ => println!("Positive."),
        0 => println!("Zero."),
        n if n < 0 => println!("Negative."),
    }
}

fn main() {
    let vec = vec![-1, 0, 1];
    for v in vec {
        check_number(v);
    }
}

```
It runs successfully with a warning: unreachable pattern
=> 
```
Positive.
Positive.
Positive.
```

Can we rather make the default case `_` always the last case ? 

We understand that It could be a logic error to write such code, but language still allows this.
As putting `_` at the top will eventually make all following cases as void & none of them will be executed either, so what's the point of having `_` at the top in a `match` expression ? 

---
2. 
I thought to report another similar issue also, just in case we are fixing it someday, we could address this one too, to not allow repeated match patterns or `unreachable pattern`
```
fn main() {
    let true_or_false = true;

    match true_or_false {
        true => println!("It's true - 1"),
        false => println!("It's false"),
        true => println!("It's true - 2"),
    }
}
```

**Comment by RalfJung** [comment]
Thank you for your report!

Match arms are checked in the order they are given. It would be very confusing to add some special cases here that *sometimes* deviate from that order. For instance, what if I have a `Some(_)` arm before a `Some(0)` arm -- should those also be magically reordered? This gets very messy very quickly. So no, we won't treat `_` differently here. We have warnings that tell you that the program likely does not behave the way you intend it to behave, which hopefully can lead you towards fixing the code so that it matches your intent.

I don't see a bug here so I'll close this. If you have suggestions for how the diagnostics could be improved to make it more clear what happens, we can reopen this as a diagnostics issue.

**Comment by workingjubilee** [comment]
> As putting _ at the top will eventually make all following cases as void & none of them will be executed either, so what's the point of having _ at the top in a match expression ?

```rust
match x {
    _ if y => expr,
    X::V(v) => v,
    _ => todo!(),
}
```
