### ISSUE TITLE
RISC-V Extension P intrinsics use invalid instruction format 

### ISSUE THREAD

**Issue by dingxiangfei2009** [rust-lang/rust#129593]
I tried this code:

```rust
pub fn foo(x: usize) -> usize {
    core::arch::riscv64::clrs8(x)
}
```

I expected to see this happen: it should compile

Instead, this happened: LLVM codegen rejects the inline assembly

```
error: operand must be a symbol with %lo/%pcrel_lo/%tprel_lo modifier or an integer in the range [-2048, 2047]
   --> /home/xxx/rust2/library/core/src/../../stdarch/crates/core_arch/src/riscv_shared/p.rs:886:15
    |
886 |         asm!(".insn i 0x77, 0x0, {}, {}, 0xAE0", lateout(reg) value, in(reg) a, options(pure, nomem, nostack))
    |               ^
    |
note: instantiated into assembly here
   --> <inline asm>:1:29
    |
1   |     .insn i 0x77, 0x0, a0, a0, 0xAE0
    |                                ^

error: aborting due to 1 previous error
```

## State of support in LLVM RISC-V ASM parser

I don't think there is yet an appropriate format that is admitted by the parser for now. Partly it could be because the [extension](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#78-clrs8-simd-8-bit-count-leading-redundant-sign) is not yet ratified.

For CLRS8, one quick fix here is to rewrite `0xAE0` to `-0x2e0` but it is hacky to be honest. :sweat: 

I also suspect that we need to fix all of `CLRS*`, `CLZ*` and `KABS*`, too.

### Meta

Nightly as of 1a94d839be8b248b972b9e022cb940d56de72fa1

**Comment by workingjubilee** [comment]
cc @kito-cheng @michaelmaitland @robin-randhawa-sifive

**Comment by topperc** [comment]
cc @Amanieu 

I'm not sure LLVM has ever allowed 0xAE0 there. What testing was done when p.rs was added?

**Comment by topperc** [comment]
Changing the `0xAE0` to `%lo(0xAE0)` works

**Comment by sequencer** [comment]
P-ext is still in discussion the opcodes, non of specification, emulator, hardware is ready, why there are Extension P intrinsic in Rust now?

**Comment by workingjubilee** [comment]
@sequencer Because the Rust compiler has strict feature stability controls. These intrinsics are an unstable feature that are subject to change at any time. As a result, especially for architecture-specific API surface, we often are happy to agree to have something on a trial basis, so that they can be experimented with. The compiler's contract with its users is that they can try things out and ask us for stabilizing it, but until then, we could also just delete all of these tomorrow.

Because, you know, the advantage of software is that you can just... do that.
