### ISSUE TITLE
Module resolution in `tests` directory differs from `src` directory

### ISSUE THREAD

**Issue by cyrgani** [rust-lang/rust#130298]
Both `src` and `tests` contain the same module structure, but only the compilation of `src` suceeds.

This is the full file structure:
```
├── Cargo.toml
├── src
│   ├── main.rs
│   ├── thing
│   │   └── a.rs
│   └── thing.rs
└── tests
    ├── main.rs
    ├── thing
    │   └── a.rs
    └── thing.rs
```

When building `tests`, it gives the following error:

```Shell
error[E0583]: file not found for module `a`
 --> tests/thing.rs:1:1
  |
1 | mod a;
  | ^^^^^^
  |
  = help: to create the module `a`, create file "tests/a.rs" or "tests/a/mod.rs"
  = note: if there is a `mod a` elsewhere in the crate already, import it with `use crate::...` instead
```

Essentially, the files in both directories look like:
```rust
// main.rs
mod thing;

// thing.rs
mod a;

// thing/a.rs is empty
```

Reproduction repository: https://github.com/cyrgani/modules-issue

**Comment by ehuss** [comment]
Hi, thanks for the report! This is intentional behavior. Cargo's [implied directory layout](https://doc.rust-lang.org/cargo/guide/project-layout.html) has different rules for different directories. In the `src` directory, it auto-discovers the root files of targets as:

* `src/lib.rs`
* `src/main.rs`
* `src/bin/*.rs`
* `src/bin/*/main.rs`

In the tests directory, it is:

* `tests/*.rs`
* `tests/*/main.rs`

In your case, `tests/thing.rs` is treated as a root, and being compiled as a separate test crate, whereas in `src` the only root is `src/main.rs`.

You can disable the auto-discovery and configure targets manually with the [auto*](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#target-auto-discovery) options.

**Comment by aDotInTheVoid** [comment]
Closing as working-as-intended.
