### ISSUE TITLE
Dead code not eliminated when inline option is enabled

### ISSUE THREAD

**Issue by GWDx** [rust-lang/rust#130694]
Compiling this file in release mode does not eliminate dead code.

```rust
fn simulate() -> i32 {
    // dead code
    let mut sum = 0;
    let mut cnt = 0;
    while sum < 1000 {
        sum += if cnt == 0 { 2 } else { 1 };
        cnt += 1;
    }
    200
}

fn main() {
    let n = 10000000;

    let mut all_cnt = Vec::new();
    for _ in 0..n {
        all_cnt.push(simulate());
    }
    let mean = all_cnt.iter().map(|x| *x as i64).sum::<i64>() as f64 / n as f64;
    println!("{}", mean);
}
```

#### Reproduction Steps

1. Create a package

```bash
cargo new test-rust
```

2. Paste the code into `src/main.rs`

3. Run the code in release mode

```bash
time cargo run --release
```

#### Observation

- The code takes about 4 seconds to run.
- By removing the dead code from the `simulate()` function, or inserting `#[inline(never)]` at the beginning, the runtime decreases to under 1 second.

I tested on versions `1.63.0` and `1.81.0`, and the issue exists on both versions.

**Comment by bjorn3** [comment]
For me adding `#[inline(never)]` to `simulate` doesn't help even if I remove the `let mean = all_cnt.iter().map(|x| *x as i64).sum::<i64>() as f64 / n as f64; println!("{}", mean);`. LLVM in that case moves the return value out of `simulate` directly to the use site, but still leaves the loop in `simulate` and calls `simulate. I suspect LLVM isn't able to prove that the loop always finishes due to pass ordering reasons.

Is this a reduced version of a real issue you had, or an intentional attempt at trying to get the compiler to not optimize? Any heuristics based optimizer had cases where it seems like it should be trivial to optimize some code away, but for compile time reasons had to give up on further optimizing before it could prove that removing the code is safe. Any non-heuristics based optimizer however would be way too slow to be usable for real life programs and is really only usable for optimizing tiny snippets: https://en.wikipedia.org/wiki/Superoptimization.

**Comment by nikic** [comment]
LLVM generally doesn't have much support for IVs with a loop-variant increment. I think it would be easy enough to support some basic max exit count calculation for the case here, but yeah, I wouldn't do that if there isn't a real-world use case.

**Comment by GWDx** [comment]
> Is this a reduced version of a real issue you had, or an intentional attempt at trying to get the compiler to not optimize?

> I wouldn't do that if there isn't a real-world use case

At first, I was trying to simulate a problem related to random walks, and the `simulate()` function was initially written as follows.

```rust
fn simulate_init() -> i32 {
    let mut sum = 0;
    let mut cnt = 0;
    while sum < 1000 {
        sum += if rand::random() { 2 } else { 1 };
        cnt += 1;
    }
    cnt
}
```

By chance, I changed the return value to a constant, and replaced `rand::random()` with a deterministic expression. I found the compiler did not optimize in this case.

I'm not sure if removing this dead code has any real-world use. This might require discussion.



Additionally, I noticed that GCC and Clang can optimize the following C code. [godbolt link](https://gcc.godbolt.org/z/nW8rfaoje)

```c
int simulate() {
    // dead code
    int sum = 0;
    int cnt = 0;
    while (sum < 1000) {
        sum += (cnt == 0) ? 2 : 1;
        cnt++;
    }
    return 200;
}
```

**Comment by bjorn3** [comment]
> Additionally, I noticed that GCC and Clang can optimize the following C code.

The only difference in LLVM IR right before the LoopDeletionPass between rustc and clang is that rustc uses `add` instead of `add nuw nsw` for incrementing `cnt` (because in C signed overflow is UB). If I use `unsigned int` as type for `cnt` however, the only difference is the order of the phi nodes for sum and cnt. With clang the cnt phi node is first, while for rustc sum is first.

```llvm
; Rustc

; Preheader:
start:
  br label %bb2

; Loop:
bb2:                                              ; preds = %start, %bb2
  %sum.sroa.0.04 = phi i32 [ 0, %start ], [ %1, %bb2 ]
  %cnt.sroa.0.03 = phi i32 [ 0, %start ], [ %2, %bb2 ]
  %0 = icmp eq i32 %cnt.sroa.0.03, 0
  %. = select i1 %0, i32 2, i32 1
  %1 = add nuw nsw i32 %., %sum.sroa.0.04
  %2 = add i32 %cnt.sroa.0.03, 1
  %_3 = icmp ult i32 %1, 1000
  br i1 %_3, label %bb2, label %bb6

; Exit blocks
bb6:                                              ; preds = %bb2
  ret i32 200
```

```
; Clang

; Preheader:
entry:
  br label %while.body

; Loop:
while.body:                                       ; preds = %entry, %while.body
  %cnt.05 = phi i32 [ 0, %entry ], [ %inc, %while.body ]
  %sum.04 = phi i32 [ 0, %entry ], [ %add, %while.body ]
  %cmp1 = icmp eq i32 %cnt.05, 0
  %cond = select i1 %cmp1, i32 2, i32 1
  %add = add nuw nsw i32 %cond, %sum.04
  %inc = add i32 %cnt.05, 1
  %cmp = icmp ult i32 %add, 1000
  br i1 %cmp, label %while.body, label %while.end

; Exit blocks
while.end:                                        ; preds = %while.body
  ret i32 200
```

**Comment by nikic** [comment]
In C this can be optimized due to the forward progress guarantee (mustprogress attribute on the function).

**Comment by the8472** [comment]
Changing it to `cnt = unsafe { cnt.unchecked_add(1) };` does eliminate the loop
