### ISSUE TITLE
improper_ctypes lint allows all "Option-like" enums, but we only guarantee this specifically for Option

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#130652]
Ever since [its introduction](https://github.com/rust-lang/rust/commit/25f953437d2bc3983b03c0d17cf56de40acec45b), the FFI safety lint has accepted `MyOption<Box<T>>` as FFI safe even if `MyOption` is not the "official" `Option` type from libcore. This was originally done because "being sound but slightly incomplete is acceptable". However, it doesn't quite reflect today's approaches any more, and IMO the lint should be adjusted to match the documented guarantees -- which AFAIK only cover specifically `Option`, and not all "Option-like" types.

Cc @rust-lang/opsem @workingjubilee @Noratrieb

**Comment by workingjubilee** [comment]
@RalfJung Frankly, the `improper_ctypes` lint has so many false positives that I cannot honestly countenance adding more BS to it.

**Comment by workingjubilee** [comment]
It also cannot be modified because even the smallest change, to not eagerly warn on things that are _not_ a problem, is deferred to a T-lang decision, e.g. https://github.com/rust-lang/rust/pull/116863

**Comment by workingjubilee** [comment]
I already actively recommend to people to simply silence the lint, in direct communication, when it proves to be the slightest problem. I will feel forced to more proactively recommend silencing the lint if this is done, in venues like "the documentation for FFI libraries used by many corporations".

Yyyes, it's kind of silly that we don't guarantee this quality for non-Option, non-Result enums that nonetheless "look like" Option and Result. But I already have enough trouble encouraging people to use the compiler correctly when things "don't cause problems in practice" (read: their code is actively UB but it hasn't visibly miscompiled yet). In this case, we actually do know it doesn't cause problems in practice.

If we fix literally every other problem with `improper_ctypes` first?

...well, that'll be a while, but then I'd endorse such an action: https://github.com/rust-lang/rust/issues?q=state%3Aopen%20label%3A%22L-improper_ctypes%22

Though, I'd probably file an RFC to extend the `Option` and `Result` guarantees first to all enums with similar repr. Because I feel like we do want to guarantee this for them, and the main reason we haven't is that we aren't completely sure we want to close that door yet, or do something like give `Option` and `Result` their own `repr` annotation that would guarantee this repr.

**Comment by RalfJung** [comment]
I don't think we need t-lang to make the lint fire on more cases. And it's not a false positive - those layouts are literally not guaranteed. Enum layout is very underspecified and adjusting the lint should come *after* specifying it more, if that is something someone is interested in pursuing.

**Comment by lolbinarycat** [comment]
I was under the impression that the null pointer optimization was guaranteed for all "Option-like" enums, but i can't find a normative reference for that

closest i can find is this:
https://rust-lang.github.io/unsafe-code-guidelines/layout/enums.html#discriminant-elision-on-option-like-enums

**Comment by RalfJung** [comment]
Cc @chorman0773

**Comment by chorman0773** [comment]
It is, in fact, only guaranteed for `Option<T>` and now `Result<T,E>`/`Result<S,T>` for a 1zst E or S.

**Comment by RalfJung** [comment]
The FCP [here](https://github.com/rust-lang/rust/pull/60300) seems to have established a guarantee for all Option-like types?

**Comment by chorman0773** [comment]
Interesting. It's not been documented outside of the UCG from what I can tell.

**Comment by chorman0773** [comment]
I would agree with Jubilee also - even if this is a false negative, I'd very much prefer we fix the inordinate false positives before addressing false negatives... the lint is IMO useless as is, because of its false positives, so making it lint on more things (even things it should be linting on) isn't going to make it any more useful (can't catch a bug if the lint has been blanket allowed due to FP).

**Comment by workingjubilee** [comment]
Noting in passing this T-lang decision that specifically permits `rustc_nonnull_optimization_guaranteed` to include `-1`, for extra fun: https://github.com/rust-lang/rust/issues/97122

**Comment by RalfJung** [comment]
Interesting -- this was never put into any docs it seems, only the lint "knows" about this.

**Comment by the8472** [comment]
> The FCP [here](https://github.com/rust-lang/rust/pull/60300) seems to have established a guarantee for all Option-like types?

That didn't update the [layout chapter](https://doc.rust-lang.org/reference/type-layout.html) in the rust reference though. In fact the reference still doesn't mention niches at all, even the ones guaranteed in `core`.

If a guarantee is made in an FCP and it's nowhere to be read, does that constitute a spec?

🌲🔉

**Comment by RalfJung** [comment]
@rust-lang/lang since this is a t-lang FCP (from five years ago), we'd be interested in your take on this. :)

The the behavior of the improper_ctypes lint, where all option-*like* enums are accepted for the null pointer layout guarantee, constitute a stable guarantee that we should properly document somewhere, or not?

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this in the triage meeting today and agreed that we meant what was in the FCP in #60300, that we're still OK with it, that it is (and has been) a language guarantee, and that we're OK with documenting it.

Note that this guarantee will be subsumed by the one that we're making now via FCP in:

- https://github.com/rust-lang/rust/pull/130628
