### ISSUE TITLE
core::error::Error has incorrect stabilization version

### ISSUE THREAD

**Issue by balt-dev** [rust-lang/rust#130765]
### Location

https://doc.rust-lang.org/nightly/core/error/trait.Error.html

### Summary

Within this page, the stabilization version of `Error` is set as `1.0.0`, when `Error` in `core` has only just recently been stabilized.

**Comment by jieyouxu** [comment]
This might be a bit tricky because you can't just change the feature gate on `core::error::Error`:

AFAICT `std::error::Error` is an re-export of `core::error::Error`, which is stability-gated by

```rs
#[stable(feature = "rust1", since = "1.0.0")]
pub use core::error::Error;
```

But the `core::error::Error` trait itself is currently also gated by

```rs
#[stable(feature = "rust1", since = "1.0.0")]
pub trait Error: Debug + Display { ... }
```

If I change the stability attribute on `core::error::Error` to be gated via `error_in_core`, it unfortunately propagates that to the re-export `std::core::Error` which means that while `core::error::Error` docs will appear as 1.81.0, std docs for `std::core::Error` will then show up as stabilised in 1.81.0 which is not quite correct either.

Stabilization of `error_in_core` actually changes the `core::error` the module to be stable thereby making `core::error::Error` stable-as-publicly-reachable, not `core::error::Error` which is already stable-in-itself just not stable-as-publicly-reachable.

**Comment by a1phyr** [comment]
Note that `core::error` has the right version: https://doc.rust-lang.org/nightly/core/error/index.html

**Comment by lukas-code** [comment]
I've put up a PR to change the displayed stability in rustdoc: https://github.com/rust-lang/rust/pull/130798
