### ISSUE TITLE
Owned Reference will not Deref

### ISSUE THREAD

**Issue by Android789515** [rust-lang/rust#131338]
I tried this code:

```rust
     // arguments[1] is &String

let filter = arguments.get(1).map(Emails::parse_filter);

// Signature
pub fn parse_filter(input: &str) -> MailFilter
```

I expected to see this happen: arguments[1] should deref to &str

Instead, this happened:
```
type mismatch in function arguments
expected function signature `fn(&std::string::String) -> _`
found function signature `fn(&str) -> _`
(E0631)
```

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0 (eeb90cda1 2024-09-04)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: x86_64-unknown-linux-gnu
release: 1.81.0
LLVM version: 18.1.7
```

<details><summary>Backtrace</summary>
<p>

```
warning: unused import: `MailFilter`
 --> src/lib.rs:9:5
  |
9 |     MailFilter,
  |     ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0631]: type mismatch in function arguments
    --> src/lib.rs:126:63
     |
126  | ...                   let filter = arguments.get(1).map(Emails::parse_filter);
     |                                                     --- ^^^^^^^^^^^^^^^^^^^^ expected due to this
     |                                                     |
     |                                                     required by a bound introduced by this call
     |
    ::: src/email.rs:51:5
     |
51   |     pub fn parse_filter(input: &str) -> MailFilter {
     |     ---------------------------------------------- found signature defined here
     |
     = note: expected function signature `fn(&std::string::String) -> _`
                found function signature `fn(&str) -> _`
note: required by a bound in `std::option::Option::<T>::map`
    --> /home/zucken/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1107:12
     |
1105 |     pub fn map<U, F>(self, f: F) -> Option<U>
     |            --- required by a bound in this associated function
1106 |     where
1107 |         F: FnOnce(T) -> U,
     |            ^^^^^^^^^^^^^^ required by this bound in `Option::<T>::map`
help: consider wrapping the function in a closure
     |
126  |                             let filter = arguments.get(1).map(|arg0: &std::string::String| Emails::parse_filter(/* &str */));
     |                                                               ++++++++++++++++++++++++++++                     ++++++++++++

For more information about this error, try `rustc --explain E0631`.
warning: `email-cl` (lib) generated 1 warning
error: could not compile `email-cl` (lib) due to 1 previous error; 1 warning emitted
```

</p>
</details>

**Comment by ChayimFriedman2** [comment]
There is no room for coercion to take place. You passed a function item with an exact signature, the compiler will not generate a shim.

@rustbot label -C-bug -C-needs-triage +C-discussion +A-coercions

**Comment by Android789515** [comment]
Why not?  I have two choices at the moment, write more verbose code or make my function less flexible.

**Comment by ChayimFriedman2** [comment]
Technically yes, it can, but this comes at a cost and needs to be extensively discussed (like every language change). Creating a closure is just few more letters: `|it| Emails::parse_letters(it)`.

**Comment by workingjubilee** [comment]
@Android789515 What do you propose would be the lifetime of the `&'a str` that would be produced?

Do you want to be the one to figure out whether this code is allowed under this new regime?
```rust
let arguments = ["lol", "whatever", "text"].map(|s| s.to_string());
let filters = arguments.into_iter().map(map(Emails::parse_filter);
```
Or perhaps this?
```rust
let filters = arguments.iter().map(map(Emails::parse_filter);
```
Or the versions of that program that then `.collect()`?

What if `MailFilter` has a lifetime?

And do you want to solve these problems for all possible Rust programs?

Can you explain why your solution is correct and why all Rust programs using it remain sound?

Do you have ideas for how to address compilation slowdowns that might be induced by applying dereference to this new site? Or do you wish to investigate whether this new strategy might actually compile faster than the "just use a closure" variant?

...If you can do all this and more, I will happily help you write up the bureaucratic elements of your proposal... basically, taking it presentable to the language team in the formats they usually expect, or drafting the RFC parts of it. Otherwise... I hope you can see that working through this "simple" proposal is actually kinda nontrivial.

**Comment by Android789515** [comment]
> Technically yes, it can, but this comes at a cost and needs to be extensively discussed (like every language change). Creating a closure is just few more letters: `|it| Emails::parse_letters(it)`.

That makes sense, then.  Thanks for clarifying.

**Comment by workingjubilee** [comment]
The reason I noted those cases is because this:
```rust
fn main() {
    let arguments = ["lol", "whatever", "text"].map(|s| s.to_string());
    let filters = arguments.into_iter().map(|s| &*s).map(parse_filter);

    struct MailFilter<'s> {
        s: &'s str,
    }
    pub fn parse_filter(s: &str) -> MailFilter<'_> {
        MailFilter { s }
    }
}
```
doesn't compile today, whereas this very similar program does:
```rust
fn main() {
    let arguments = ["lol", "whatever", "text"].map(|s| s.to_string());
    let filters = arguments.iter().map(|s| &**s).map(parse_filter);

    struct MailFilter<'s> {
        s: &'s str,
    }
    pub fn parse_filter(s: &str) -> MailFilter<'_> {
        MailFilter { s }
    }
}
```

So there are a number of cases that might require some kind of "lifetime extension" rule to make "try to repeatedly apply deref until you get the argument type" a desirable rule. The resulting language, with or without also adding a lifetime extension rule, might be experienced as more inconsistent and non-obvious than the current language with this admittedly quirky rule.

**Comment by Android789515** [comment]
> The reason I noted those cases is because this:
> 
> fn main() {
>     let arguments = ["lol", "whatever", "text"].map(|s| s.to_string());
>     let filters = arguments.into_iter().map(|s| &*s).map(parse_filter);
> 
>     struct MailFilter<'s> {
>         s: &'s str,
>     }
>     pub fn parse_filter(s: &str) -> MailFilter<'_> {
>         MailFilter { s }
>     }
> }
> 
> doesn't compile today, whereas this very similar program does:
> 
> fn main() {
>     let arguments = ["lol", "whatever", "text"].map(|s| s.to_string());
>     let filters = arguments.iter().map(|s| &**s).map(parse_filter);
> 
>     struct MailFilter<'s> {
>         s: &'s str,
>     }
>     pub fn parse_filter(s: &str) -> MailFilter<'_> {
>         MailFilter { s }
>     }
> }
> 
> So there are a number of cases that might require some kind of "lifetime extension" rule to make "try to repeatedly apply deref until you get the argument type" a desirable rule. The resulting language, with or without also adding a lifetime extension rule, might be experienced as more inconsistent and non-obvious than the current language with this admittedly quirky rule.

That's good to know.  Wasn't sure exactly how deref worked under the hood.

**Comment by Android789515** [comment]
I guess this will require some kind of language change, so I'll close for now.
