### ISSUE TITLE
Bootstrap: cargo-miri is called "cargomiri" for check builds

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#131592]
When I do `./x.py check`, it says:
```
Checking stage0 cargomiri artifacts (x86_64-unknown-linux-gnu)
```

Strangely, when I do `./x.py test miri`, it uses the correct name:
```
Building tool cargo-miri (stage0 -> stage1, x86_64-unknown-linux-gnu)
```

No idea how it is even possible for this tool to have two different names inside bootstrap...

**Comment by jieyouxu** [comment]
I think this is just because cargo-miri's tool check step is generated through a macro

https://github.com/rust-lang/rust/blob/fb20e4d3b96d1de459d086980a8b99d5060ad9fe/src/bootstrap/src/core/build_steps/check.rs#L478

this macro generates the check message via

https://github.com/rust-lang/rust/blob/fb20e4d3b96d1de459d086980a8b99d5060ad9fe/src/bootstrap/src/core/build_steps/check.rs#L444

there's a `to_lowercase` in there. The build step has a different name because that macro explicitly asks for a display name

https://github.com/rust-lang/rust/blob/fb20e4d3b96d1de459d086980a8b99d5060ad9fe/src/bootstrap/src/core/build_steps/tool.rs#L1094

**Comment by jieyouxu** [comment]
If I make the macro use a display name,

```
Checking stage0 cargo-miri artifacts (x86_64-pc-windows-msvc)
```

**Comment by RalfJung** [comment]
Ah, I didn't realize those two steps were defined entirely independently.

**Comment by jieyouxu** [comment]
Anyway, #131597 should make this more consistent.
