### ISSUE TITLE
download-rustc has no effect when running run-make tests

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#131947]
reproduction steps:
1. set `rust.download-rustc = true` in config.toml
2. run `./x test --stage 1 tests/run-make`

expected behavior: rustc is downloaded

actually behavior: rustc and cargo are built from source

**Comment by Noratrieb** [comment]
Why do you want to run tests on the downloaded compiler?

**Comment by jieyouxu** [comment]
I don't quite understand this use case. `COMPILETEST_FORCE_STAGE0=1 ./x test --stage 0 tests/run-make` will run tests on a downloaded beta compiler, or otherwise a user-provided initial rustc (such as a previous stage2 compiler as part of opt-dist step). And even that is not an explicitly supported use cases -- many run-make tests *will* fail and it's not guaranteed to be supported. Having `download-rustc = true` mean even the stage 1 rustc downloaded makes no sense to me.

**Comment by bjorn3** [comment]
If you only modified the standard library and want to run run-make tests to see if your change broke something, I would expect download-rustc be enough to avoid having to recompile the compiler itself. There is no need to recompile the compiler in that case as it wasn't modified.

**Comment by jieyouxu** [comment]
I see

**Comment by lolbinarycat** [comment]
> Why do you want to run tests on the downloaded compiler?

in my case, i was trying to modify compiletest, but it also would be useful if you're modifying the tests themselves.

**Comment by jieyouxu** [comment]
> in my case, i was trying to modify compiletest

For compiletest specifically, compiletest is a stage0 bootstrap tool, so you can just `./x test src/tools/compiletest --stage 0` to make it build (and run its unit tests). But yes, it could be helpful to have `download-rustc` working with the test suite as well.

**Comment by onur-ozkan** [comment]
Added to [Tracking Issue for download-rustc improvements](https://github.com/rust-lang/rust/issues/131744).

**Comment by onur-ozkan** [comment]
Fixed with https://github.com/rust-lang/rust/pull/132006.
