### ISSUE TITLE
"Use after free" bug with Implied bounds on nested references

### ISSUE THREAD

**Issue by rucsesec** [rust-lang/rust#132405]
I tried this code:

```rust
fn f<'a, 'b>(_: &'a &'b(), arg: &'b str) -> &'a str {
    arg
}

fn foo() -> &'static str {
    let local = String::from("abc");
    let bar: fn(_, &str) -> &'static str = f;
    bar(&&(), &local)
}

fn main() {
    let res = foo();
    let _unrelated = String::from("UAF!");
    println!("{}", res);
}
```

This is clearly another instance of [#25860](https://github.com/rust-lang/rust/issues/25860), where nested borrowings lead to implicit boundaries that allow access to local variables even after they have been dropped. Such issues are so severe, what is the current progress in addressing these types of problems? Where can I obtain the latest information on such issues?
If this is an inconvenience, I apologize, thank you for your answer.
- Demo: [on current playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=9a25df2b91add467f7ec39415a7372e3)

**Comment by saethlin** [comment]
https://github.com/rust-lang/rust/issues/25860 was locked because too many comments on it were making it hard to navigate. Opening a duplicate issue and trying to have a conversation here instead is not an improvement. As the comment says at the bottom of that issue, you can ask on Zulip.

Or, in the sidebar of the original issue, you can see that T-types has decided that fixing this soundness hole is blocked on on `-Ztrait-solver=next`.
