### ISSUE TITLE
Our 32-bit Sparc handling isn't quite correct yet

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rust#132585]
See:
- https://github.com/rust-lang/rust/issues/130172
- https://github.com/rust-lang/rust/pull/131222
- https://github.com/rust-lang/rust/pull/132552

We need to, for compiling for 32-bit SPARC, distinguish when we should use the appropriate Elf Machine for V8 vs. V8+. This is necessary because this is the primary way of detecting instruction incompatibility for the architecture: providing a CPUID via instruction or register read at runtime hadn't become fashionable yet.

**Comment by taiki-e** [comment]
An additional complication here is that LLVM also works differently in different versions for this.

- LLVM 18 always uses EM_SPARC ([code](https://github.com/llvm/llvm-project/blob/llvmorg-18.1.0/llvm/lib/Target/Sparc/MCTargetDesc/SparcELFObjectWriter.cpp#L26))
- LLVM 19 uses EM_SPARC32PLUS if the v9 feature (which is also a feature that indicates whether certain instructions are available) is enabled, otherwise EM_SPARC ([code](https://github.com/llvm/llvm-project/blob/llvmorg-19.1.0/llvm/lib/Target/Sparc/MCTargetDesc/SparcELFObjectWriter.cpp#L27-L28))
- LLVM 20 (unreleased) uses EM_ SPARC32PLUS if the v8plus feature (which is an independent feature not tied to any other feature) is enabled, otherwise EM_SPARC ([code](https://github.com/llvm/llvm-project/blob/390300d9f41df6ad71f0f4196ef4885d4bd5dc48/llvm/lib/Target/Sparc/MCTargetDesc/SparcELFObjectWriter.cpp#L28))

https://github.com/rust-lang/rust/pull/131222 implements the behavior of LLVM 19 somewhat imperfectly, and the feature will be added in https://github.com/rust-lang/rust/pull/132552 can be used to make it exactly match LLVM 19.

The behavior of LLVM 20 is consistent with that of GCC (that [-mcpu=v9 does not imply -mv8plus](https://godbolt.org/z/dq8ab5d4G)), and I think eventually we will need to match it. (See https://github.com/rust-lang/rust/pull/132552#issuecomment-2453399715 for the motivation for this behavior.)

IIUC, my patch mentioned in https://github.com/rust-lang/rust/pull/132552#issuecomment-2453463726 (https://github.com/rust-lang/rust/commit/08493569fc414f010bbc114bf3e53b1d90a115bd) works the same way as LLVM in each LLVM version. (Of course, the problem with that patch is that it behaves differently depending on the LLVM version (until LLVM 20 is the minimal LLVM version).)
