### ISSUE TITLE
Weird formatting on documentation of "Summary" button

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#132564]
location: https://doc.rust-lang.org/nightly/std/#how-to-read-this-documentation

I believe this issue comes from using an `svg` element inside a `code` element.

![Image](https://github.com/user-attachments/assets/562db078-0f03-4a08-973f-9fe78b1278ae)

**Comment by uellenberg** [comment]
This is due to "Summary" having a newline in it. You can see the newline in https://github.com/rust-lang/rust/blob/82c24eccadc216cac4365ce83ac6a36ef72ff1a3/library/std/src/lib.rs#L35-L36 , where code is on a different line than the SVG.

I'm going to send in a modification, but I'm not sure how to document why that change is being made, so it doesn't happen again. A quick search through the code confirms that this is the only place where we have an <svg> inside a <code> in a Rust source file.

@rustbot claim

**Comment by lolbinarycat** [comment]
> I'm not sure how to document why that change is being made, so it doesn't happen again.

you can put a non-doc comment (`//`) next to the doc comment.

**Comment by uellenberg** [comment]
> > I'm not sure how to document why that change is being made, so it doesn't happen again.
> 
> you can put a non-doc comment (`//`) next to the doc comment.

Good idea!

**Comment by lolbinarycat** [comment]
another option is coding a check into `tidy` that prevents putting newlines inside inline html elements (as opposed to block html elements, which can have newlines without much issue)
