### ISSUE TITLE
global_asm "mov eax, label" compiles to the same as "mov eax, [label]"

### ISSUE THREAD

**Issue by CodingVoid** [rust-lang/rust#134356]
I tried this code:

asm.rs
```rust
use std::arch::global_asm;

global_asm!(include_str!("asm.rs.S"));

extern "C" { fn baz() -> u64; }

pub fn main()
{
	let a:u64 = unsafe { baz() };
	print!("0x{:x}\n", a);
}
```
asm.rs.S
```asm
.text
data:
	.8byte 0x12345678
.global baz
baz:
	mov eax, data
	ret
```
asm.rs.S (to compare)
```asm
.text
data:
	.8byte 0x12345678
.global baz
baz:
	mov eax, [data]
	ret
```

I compiled it like this:
```
rustc -Clink-arg=-no-pie asm.rs
```

I expected to see this happen:
It should print the address of data in the first assembly code and the data itself (0x12345678) in the second example.

Instead, this happened:
In both assembly cases it prints out 0x12345678

### Meta

`rustc --version --verbose`:
```
rustc 1.85.0-nightly (d4025ee45 2024-12-12)
binary: rustc
commit-hash: d4025ee454169fbd22f5773f54348310ab6a47bb
commit-date: 2024-12-12
host: x86_64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.5
```

I am not particularly sure if I am doing something obviously wrong, but if I do I can't see it.

**Comment by zachs18** [comment]
I know for GNU `as` in `.intel_syntax noprefix` mode, `mov eax, symbol` and `mov eax, [symbol]` are equivalent[^1]. I assume LLVM's asm is the same(?)

You could use `mov eax, OFFSET data` or `lea eax, [data]` or `lea eax, [rip + data]` to load the address of `data` instead.

(Also, note that `eax` is 32 bits. Loading `data` into `eax` works here since its value fits in `u32` and x86 is little-endian, but if `data` did not fit in `u32`, then loading into `eax` would truncate it to 32 bits. Similarly, loading `data`'s address into `eax` would work because you are using `-no-pie`, so things are being placed in the low 4GiB of the address space, but in other cases, you would need to use `rax` for addresses on x86_64)

[^1]: except when `symbol` is defined using `.equ` or similar: https://stackoverflow.com/questions/39355188/distinguishing-memory-from-constant-in-gnu-as-intel-syntax

**Comment by CodingVoid** [comment]
I only checked nasm and there it is not the same (after trying it out). I didn't try GNU as though. If this is intended it renders this issue mood.
Thanks for your quick reply and for suggesting the alternatives.

(The code in question is only running in x86 protected mode so I actually have to use the 32 bit versions of the registers)
