### ISSUE TITLE
statics are null on x86_64-unknown-linux-none

### ISSUE THREAD

**Issue by m-mueller678** [rust-lang/rust#134763]
when compiling for `x86_64-unknown-linux-none`, the static items in the following code snippet have null pointers as address. The inline versions work as expected. The exit code of the program is `10`.

```rust
#![no_std]
#![no_main]

use syscalls::Sysno;

static SLICE: &[u8; 5] = b"hello";
static STRING:&str = "hello";

#[no_mangle]
pub extern "C" fn _start() -> ! {
    let static_slice = SLICE.as_ptr().is_null()  as usize;
    let inline_slice = b"hello".as_ptr().is_null() as usize;
    let static_str = STRING.as_ptr().is_null() as usize;
    let inline_str = "hello".as_ptr().is_null() as usize;
    let exit_code = static_slice<<3|inline_slice<<2|static_str<<1|inline_str;
    unsafe {
        syscalls::syscall1(Sysno::exit,exit_code).unwrap();
    }
    loop{}
}


#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop{}
}

```
### Meta
`rustc --version --verbose`:
```
rustc 1.85.0-nightly (409998c4e 2024-12-24)
binary: rustc
commit-hash: 409998c4e8cae45344fd434b358b697cc93870d0
commit-date: 2024-12-24
host: x86_64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.6

```

cargo config:
```
[build]
target = "x86_64-unknown-linux-none"

[unstable]
build-std = ["core"]
```

**Comment by Noratrieb** [comment]
Your code sample does not compile, it has a syntax error and depends on a crate that you didn't specify in the cargo.toml. After adding the semicolon and removing the syscall (and also specifying panic=abort explicitly because this is incorrectly a panic=unwind target, fixed in #meow) I got a program.
The ELF is of type DYN, making it a position-independent executable. There are two relocations, probably for the statics.
With the default configuration, you're gonna have to implement a dynamic loader yourself to resolve these relocations. You can use the `-Crelocation-model=static` rustc flag to change this.
With that, the relocations are gonna, it's no longer a PIE, and you should be able to run it without implementing a dynamic loader.
Maybe that should be the default too for the target.

**Comment by Noratrieb** [comment]
Opened #134765 to change the defaults to more appropriate ones that should make your program work.

**Comment by jieyouxu** [comment]
UPD: https://github.com/rust-lang/rust/pull/134765 opts to instead documents PIE as default target behavior and mentions using `-Crelocation-model=static` if position-dependent is desired instead.

**Comment by Noratrieb** [comment]
I'm closing this, since the problem should be fixed with the relocation model. The docs now mention this, but the default is still PIC, so people might run into this again, but there's not that much we can do about it.
If relocation model static doesn't fix your issue please comment again or open a new issue.
