### ISSUE TITLE
If-Let-Else and Let-Else doesn't produce same result which creates UB.

### ISSUE THREAD

**Issue by Azvanzed** [rust-lang/rust#134766]
I tried this code:

```rust
static MUTEX: spin::Mutex<Option<fn()>> = spin::Mutex::new(None);

// SAMPLE A
fn main() {
    let Some(value) = *MUTEX.lock() else {
         unreachable!("Mutex not set");
     };

     value();
 }

// SAMPLE B
fn main() {
    if let Some(value) = *MUTEX.lock() {
        value();
    } else {
        unreachable!("Mutex not set");
    }
 }

```

I expected to see this happen: 
A. calls the value function then the mutex unlocks.  (IDA decompilation)

![Image](https://github.com/user-attachments/assets/3d4a7509-fbe9-423e-ab80-f3d5a0ad82b3)

Instead, this happened: 
B. mutex unlocks then calls the value function. (IDA decompilation)

![Image](https://github.com/user-attachments/assets/de9ff9b3-2ce6-4a9e-89f5-57aa93cc7cad)

### Meta

The bug does occur in nightly.

`rustc --version --verbose`:
```
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: x86_64-pc-windows-msvc
release: 1.83.0
LLVM version: 19.1.1
```

<details><summary>Backtrace</summary>
<p>

```
Not needed since this is visible statically.
```

</p>
</details>

**Comment by traviscross** [comment]
This isn't a bug in `rustc`.  In your code, since you didn't separately assign the mutex guard to some binding, it's just a temporary, and those don't generally outlive the statement in which they are created (with some caveats about tail expressions).  See, e.g.:

- https://github.com/rust-lang/rust/pull/133605

That said, we agree this is an unfortunate discrepancy between `if-let` and `let-else`, and it's something we're thinking about.  If we were to change it (over an edition), it would likely be in the direction of making `if-let` more like `let-else`, i.e. continuing the direction we [took](https://doc.rust-lang.org/nightly/edition-guide/rust-2024/temporary-if-let-scope.html) in Rust 2024 to shorten the scope of temporaries.

In any event, it's probably advisable in cases like this to assign the mutex guard to a binding so as to be more explicit about the intended scope.

**Comment by Azvanzed** [comment]
Interesting; I've never looked at it this way but now that you've explained it it makes more sense.

Either way making it more similar to each other would be neat to avoid someone else falling in the same mistake i did.

Thanks!
