### ISSUE TITLE
Move "miscellaneous language-construct benchmarks" out of core::mem

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/rust#13642]
In `std::mem` there are some benchmarks regarding to miscellaneous language constructs (such as pattern matching and method dispatch). Since they have nothing to do with memory and the functions defined in this file, I think they should be moved to another place.

I thought it was reasonable to move them to `src/test/bench`, but it looks like this is not very convenient (see https://github.com/mozilla/rust/pull/13553#issuecomment-40876663).

**Comment by dtolnay** [comment]
Reopening because I don't think this was ever finished. The benchmarks were moved from std to core and from src to benches, but as of Rust 1.20 they are in [`libcore/benches/mem.rs`](https://github.com/rust-lang/rust/blob/1.20.0/src/libcore/benches/mem.rs) which is still confusing because as commented above, they have nothing to do with memory or the functions in core::mem.

**Comment by Mark-Simulacrum** [comment]
It looks like https://github.com/rust-lang/rust/pull/44943 did indeed move the benchmarks out of libcore (and into librustc), so closing this.
