### ISSUE TITLE
non_camel_case_types lint check should ignore enum variants

### ISSUE THREAD

**Issue by tommit** [rust-lang/rust#14599]
Given that enum variants are not types, it doesn't make sense to have a lint named ```non_camel_case_types``` be checking the naming of those.

Add another lint named ```non_camel_case_enum_variants``` to check those.

**Comment by steveklabnik** [comment]
Triage: no change.

I think it's fine to use 'type' in this context, but maybe it could be renamed to something else.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
