### ISSUE TITLE
Remove raw_pointer_deriving lint

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#14615]
After examination, it doesn't appear that deriving raw pointers presents any kind of safety problem (no derivings dereference unsafe pointers). Most people seem to believe that the original justification presented in https://github.com/mozilla/rust/issues/13032 isn't sufficient.

**Comment by frewsxcv** [comment]
Worth pointing out that `raw_pointer_deriving` was recently renamed to `raw_pointer_derive` https://github.com/rust-lang/rust/pull/20511

**Comment by kmcallister** [comment]
> I'm not in favour of removing it... how many instances of `#[deriving]` with a raw pointer give the desired implementation?

Most of them, if you understand raw pointers to be plain old data.  For example, a struct which wraps an FFI object could `#[derive(PartialEq, Eq, PartialOrd, Ord, Hash)]` to be usable as a collection key.  We treat the raw pointer as an opaque ID for the FFI object.  Of course, `Eq` won't compare the structural fields behind that pointer (which are defined in foreign code anyway), and the ID is only unique over *currently-existing* objects, i.e. address can be reused.  Anyone using raw pointers should already understand this.  If someone is badly confused about what raw pointers are, and derives `Eq` expecting structural equality, then I don't think this lint will help them much anyway.

> I would think the lint should be hit rather rarely.

People hit it all the time and get confused on IRC because it's warning them that they're getting exactly the behavior they expect.  We have the lint disabled in 5 Servo modules, as well.

> Eq or Ord can say "ignoring raw pointer field"

But they aren't ignored, they're just treated as plain old data, which (to me anyway) is the only thing you might possibly expect.  People should know that raw pointers may be NULL, may point to structures whose layout/size is not known in Rust, and can't be dereferenced willy-nilly from safe code.  If you're confused on that then you need to read the unsafe programming chapter, not a single lint message.

**Comment by tbu-** [comment]
`#[deriving(Clone)]` on raw pointers is probably an error though. If there's an object coupled to it, this will likely lead to use after free.

**Comment by tbu-** [comment]
Also this can probably be closed, because #29882 already landed.
