### ISSUE TITLE
Pretty printing should use \r\n on Windows.

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#14808]
On Windows the preferred line ending is \r\n, not \n like it is on posix platforms.
Unfortunately using --pretty with rustc outputs \n newlines.
For comparison clang-format outputs \r\n on Windows.

**Comment by rprichard** [comment]
Did anyone ever consider having stdout convert LF to CRLF automatically on Windows?

**Comment by tamird** [comment]
#24696 generated enough resistance that I think we should not pursue this. I'm not sure how to get to a decision, but it'd be nice to lock this down.

**Comment by steveklabnik** [comment]
Triage: no changes in the last two years. @rust-lang/compiler and @rust-lang/lang , do you have any thoughts here? There was a PR for this, but it was closed in favor of gaining some kind of consensus.

**Comment by nikomatsakis** [comment]
I personally don't have any problem emitting `\r\n`, but I'm not a big fan of offering the pretty printer at all, mostly because it's a complex, little-used piece of code. It's definitely handy for debugging macros though and we don't really have a good alternative right now, so it seems like it'd be good if it integrated more smoothly with windows.

That said, I think the proper comparison for `clang --format` is really `rustfmt`, right? The pretty-printer is basically a (crude) macro-debugging tool at this point.

**Comment by retep998** [comment]
The pretty printer is incredibly useful for debugging macros, but that's really about it. I don't care anymore about the choice of line ending for pretty printing, and rustfmt takes care of formatting code. I just want the pretty printer to be polished as a proper macro debugging tool, the equivalent of preprocessing only in C++.

**Comment by Havvy** [comment]
Which team does the decision needed fall to for this?

**Comment by Mark-Simulacrum** [comment]
Closing. I personally think this is not something that we should settle on long-running issues and it seems no one cares too much about this today.
