### ISSUE TITLE
make runtime library loading safer

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#15040]
We [currently have an interface for runtime library loading](http://doc.rust-lang.org/std/dynamic_lib/index.html), using the dynamic linker, but it has the problem that it interacts poorly with name mangling and is *entirely* unsafe. Figure out how to make it type-safe, and preferably memory-safe too.

**Comment by mzabaluev** [comment]
Code trust issues aside, an operation certainly unsafe for the process image integrity is *un*loading of libraries. The problems and and the per-platform variability here are such that all cross-platform programming environments I've seen that allow loading of arbitrary dynamic libraries have chosen to disable or discourage unloading. There hasn't been much demand for the feature either; memory is cheap, and in systems supporting dynamic libraries it is almost certainly virtually mapped. Being able to change parts of the program at runtime is neat, but I don't think it is compatible with what Rust aims to be otherwise.

To be safely unloaded, a module and the program using it must ensure that none of the in-image data it adds to the process is referenced elsewhere. This extends to any dynamic libraries the module might be linked to as the single consumer in the process, because the libraries are unloaded together with it (any alternatives to this behavior are not portable to the best of my knowledge). Even if Rust provides a solution for safe code with lifetimes, I expect the issues with foreign libraries will be too numerous and hard to debug. Heaven help you if any of those libraries is in C++; implementations of its _language features_ there are not safe with regard to unloading.

I think it best for everyone's sanity if the unload operation is kept unsafe, or not provided at all. This will remove the problem with soundness of `'static`, because any in-binary data added to the process image is assumed to stay there forever.

**Comment by Kimundi** [comment]
Yeah, supporting unloading for arbitrary libraries is a tricky issue for sure. But I still think it could be made safe in controlled environments like Rust-only libraries explicitly compiled as unloadable plugins.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#661
