### ISSUE TITLE
rustdoc: make static functions stand out better

### ISSUE THREAD

**Issue by o11c** [rust-lang/rust#15070]
Both me and some random guy on IRC today were reading the docs, and completely missed the fact that certain functions were static. They should visually stand out, even while just skimming.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by steveklabnik** [comment]
Triage: still no changes. @rust-lang/rustdoc do we ever plan on implementing this?

**Comment by GuillaumeGomez** [comment]
If we do this, we'll have to think **a lot** about how we'll do it (on the UI side).

**Comment by QuietMisdreavus** [comment]
it could be as simple as sorting non-`self` functions above the rest, but that would probably surface another issue for items with multiple impl blocks. Since rustdoc currently groups methods together by their impl block (since they could have different conditions attached to them, different trait bounds or type parameters, or just being written in different files), it just grabs the impl as a whole. However, i think reordering the items within the impl will still get the majority of cases.

**Comment by GuillaumeGomez** [comment]
We should maybe just re-order items alphabetically in the first place.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as we don't have consensus (and, I, for one don't even think we should do anything here).
