### ISSUE TITLE
rustup.sh could pass a prefix to install.sh if the user isn't root

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#15187]
... so we could stop giving people a `curl ... | sudo sh` commandline and can suggest something like `curl ... | sh -s -- --prefix=~/rust' instead.

This sorta depends on our current rpath setup, but even if we have to suggest a bunch of LD_LIBRARY_PATH magic, it's probably still good to have something to tell people who are uneasy about sudo.

**Comment by mkpankov** [comment]
I think I'll take a look at this.

The complication is updating `${PATH}` and `${LD_LIBRARY_PATH}` though. And poking `man` in the right direction, since for me it doesn't pick up stuff installed in `$HOME/install/*`.

I intend to match the `${SHELL}` variable to know what file to inspect for `PATH` and `LD_LIBRARY_PATH` assignments. Then if there are no `$HOME/install/bin` in `$PATH` I'd update the assignment and put that into appropriate `.*rc` file.

**Comment by steveklabnik** [comment]
This should be filed against https://github.com/rust-lang/rustup if it's still an issue.
