### ISSUE TITLE
Make it easy to attach LLVM attributes to Rust functions

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#15180]
[Lots of good stuff there.](http://llvm.org/docs/LangRef.html#function-attributes)

**Comment by steveklabnik** [comment]
Triage: no update specifically.

**Comment by alexcrichton** [comment]
It's unlikely that this would end up ever being stabilized because we don't want to tie ourselves so closely to LLVM, and we already export a good number of the useful attributes from LLVM. We can add more over time but a general mechanism to just forward everything through is pretty scary from a backwards-compatibility perspective, so I'm going to close this for now. Any missing attributes we're not using in LLVM can certainly have attributes added for them though!
