### ISSUE TITLE
Explicitly define the evaluation order/"sequence points" etc.

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#15300]
From this [stackoverflow question](http://stackoverflow.com/q/24508640/1256624).

I may just not be searching for the right terms, but I don't believe this is mentioned in the manual. It would be good to have this clearly defined.

There is possibly some subtlety with issues like https://github.com/rust-lang/rust/issues/6268, where it may make sense to evaluate the receiver last.

**Comment by alexcrichton** [comment]
cc @steveklabnik, could this move to the RFCs repo?

**Comment by oli-obk** [comment]
Wouldn't it force more readable code if such constructs were forbidden? I mean, the borrow checker already forbids simultaneous mutable and immutable references. Why not also forbid simultaneous mutable and immutable usage?

I have to carefully lay out the steps happening in my mind, even if the eval-order is specified. I don't think anyone considers the following to be readable.

```rust
fn main() {
    let mut a = 5;
    let b = (a, a = 6, a, a * (a, a = 7).0);
    println!("{:?}", b);
}
```

or logical (even the compiler is confused about what's going on...):

```
<anon>:3:35: 3:36 warning: value assigned to `a` is never read, #[warn(unused_assignments)] on by default
<anon>:3     let b = (a, a = 6, a, a * (a, a = 7).0);
                                           ^
(5, (), 6, 42)
```

Sequence points are a major issue in c/c++, not just because they cause undefined behavior, but also because not everyone is an expert on the evaluation order. If you give a piece of code to a group of non-experts on sequence points, you get a quite a number of different suggestions of what the outcome should be. There won't be less confusion just because the evaluation order is defined. Most likely there'll just be a number of "good practices" about how to write readable expressions.

Things like `v.truncate(v.len() - 1)` are a different issue, as that is hierarchical an therefor there cannot be a confusion about the order.

**Comment by steveklabnik** [comment]
After talking with @nikomatsakis , we're not quite ready to define these things yet. Given that that will take a lot of work, I'm going to be giving this issue a close, as it's really more of an RFC type of thing, but 

> I think we will be I think we will be nailing down pretty precisely as part of the MIR construction work,
nailing down pretty precisely as part of the MIR construction work,

and so documenting all that would fall under that work anyway.

**Comment by bluss** [comment]
The borrow checker thinks it's left to right:

```rust
let mut data = vec![1, 2, 3];

anyfunction(data.clear(), &mut data);  // Ok
anyfunction(&mut data, data.clear());  // Not Ok
```
