### ISSUE TITLE
Add option to include private definition in the documentation.

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#15347]
Please add an option for rustdoc such that rustdoc creates a proper documentation for private definitions. 

While it is in general a good idea to hide these private definitions, as a crate developer it would be very valuable to have a good internal documentation of private types and functions.

**Comment by drewcrawford** [comment]
+1.  Writing a library, would benefit from being able to see private documentation while I work.

**Comment by drewcrawford** [comment]
It does look like the workaround

```
--no-defaults --passes "collapse-docs" --passes "unindent-comments"
```

works.  (Need multiple invocations for "passes").

Recommend close.

**Comment by SimonSapin** [comment]
@drewcrawford are these `rustdoc` arguments? Can `cargo doc` be made to use them?

**Comment by drewcrawford** [comment]
They're `rustdoc` arguments.  `cargo doc` can't be taught them, but I'd encourage you to comment in https://github.com/rust-lang/cargo/issues/331 on that topic.

**Comment by SimonSapin** [comment]
We turned this on on http://doc.servo.org/ . It’s better, but not ideal: all `use` and `extern crate` statements show up as well. It’s pretty noisy.

**Comment by SimonSapin** [comment]
@alexcrichton, could you edit https://github.com/rust-lang/rust/issues/15347#issuecomment-47828041 ?

`--passes "collapse-docs unindent-comments"` causes `ERROR:rustdoc: unknown pass collapse-docs unindent-comments, skipping` which I ignored at first since docs still seem to be generated, but all doc-comments are truncated to their first line for a reason I don’t understand. https://github.com/servo/servo/pull/6668

It should be `--passes collapse-docs --passes unindent-comments`, with only one value per `--passes`.

**Comment by gnzlbg** [comment]
Would it be possible to always generate a "Developer documentation" section for crates that contains the docs of private items alongside the documentation for the public API ? Both should obviously be separated, but I think it is valuable to have both, and for users to _always_ be able to read both.

**Comment by KalitaAlexey** [comment]
I agree with gnzlbg. Sometimes it is good to be able to search.

**Comment by Razican** [comment]
It's something that does not change how official documentation is handled, but that could help a bunch of us.

**Comment by gnzlbg** [comment]
I don't see why it shouldn't be provided for the official documentation as well,  the split between public API and developer documentation would jut need to be made very clear. Say somebody properly documented some internal standard library function, and I want to read its documentation because I think doing so is FUN.

Do I really need to read it online in the source file? Or do I need to get a copy and generate it my self? 

Seems like unnecessary hassle and probably is contraproductive. 

Having easier ways to get people to know the internals of libraries, including the standard library is_good_. It helps people become contributors, it gets more eyes on the libraries internals and their implementation, it finds bugs if someone goes "wait a second, that doesn't make sense", or improves performance if somebody else goes "why are they using this algorithm, this other one is way better!".

**Comment by AlbertMarashi** [comment]
+1

As both a user and maintainer of library it would be valauable to have a full "developer" section.

I'd argue that many users would benefit from also understanding internals directly from docs, even if they are not going to directly use them.

**Comment by jyn514** [comment]
Please do not leave comments on this issue - you can document private definitions with `--document-private-items`, this issues isn't meant to track all issues related to private items. If you'd like a better UI for it that distinguishes private and public items, feel free to comment on https://github.com/rust-lang/rust/issues/68022 with the UI you think would be helpful.
