### ISSUE TITLE
Generic functions with "C" ABI

### ISSUE THREAD

**Issue by o11c** [rust-lang/rust#15513]
I need to pass a callback function pointer to C, and there's no reason a generic function shouldn't be able to do this. The only problem with generic functions is that they would _mangle_ all to the same name, but I don't care about the mangling.

**Comment by steveklabnik** [comment]
Triage; no change here.

**Comment by Mark-Simulacrum** [comment]
The below compiles, so at least basically, this does work. I'm uncertain if the code I came up with is what the author wants, but due to the age of this request and the lack of a code sample within the request, I will close this. Please reopen with a code sample that fails to work (or indicate why mine doesn't) if necessary.

```rust
fn main() {}

extern "C" fn foo<F: Fn(i32) -> usize>(f: F) -> usize {
    f(10)
}

extern "C" fn bar<T: Clone>(f: fn(i32) -> usize) -> usize {
    f(10)
}
```
