### ISSUE TITLE
Rustdoc: List impl interface before describing impl methods

### ISSUE THREAD

**Issue by gsingh93** [rust-lang/rust#15642]
Lots of languages have documentations where you can see the entire interface of the class before digging deeper and finding out what the methods do. For example, look at how the Java documentation is structured (C++ docs on multiple mainstream sites are similar): http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html

There is a high level overview of the class, a list of methods with one line descriptions, followed by the same function list with more detailed descriptions. The list of methods links to the more detailed descriptions.

This structure allows a user who doesn't know the exact name of the method they're looking for quickly find the method. Contrast this with the current way rustdoc does things. Look at this page: http://doc.rust-lang.org/std/vec/struct.Vec.html

I have to sift through all the functions and their descriptions as I look for the function I want. The functions aren't alphabetized either, so if I am looking for a function, I can't find it alphabetically.

I don't know whether it would be good to show Traits methods in this list or not.

**Comment by killkrt** [comment]
As I wrote in this [post](https://users.rust-lang.org/t/doc-have-a-clear-visual-indication-for-struct-implementing-copy-trait/2876) in my opinion it would be great to have a quick indication whether a struct implements the `Copy` trait, since it is a very important information in Rust.
Furthermore I agree with @gsingh93, it would be better if the documentation was alphabetised, also having clear section for *builder* (function of form `fn method(not self) -> Self`) methods would be great.

**Comment by steveklabnik** [comment]
Triage: 

> Its mostly resolved. I think the fact the functions aren't alphabetized is a related pain point for searching for methods.

Given that we want to totally re-think rustdoc, and this hasn't had any comments in a very long time, and is basically all resolved, I'm going to give this one a close, as I don't think we need to track it down to this level of detail. Thanks!

**Comment by gsingh93** [comment]
Is there a thread somewhere where the redesign of rustdoc is being discussed?
