### ISSUE TITLE
References have no primitive page in rustdoc

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#15654]
E.g. there's no http://doc.rust-lang.org/master/std/uint/primitive.uint.html for `&` or `&mut`.

**Comment by tomjakubowski** [comment]
What sorts of impls would be expected on this page? Listing impls for every `clean::BorrowedRef` (`<T> &T`, `<T> &Vec<T>`, `&Foo`) might be excessive, although of course it's better to err on the side of documenting too much than not enough :-)

**Comment by steveklabnik** [comment]
It might be, yeah. In principle, there should at least be some kind of page I can put some text on, even if it says "Most of the methods aren't shown on this page because it's too primitive" or something.

**Comment by nagisa** [comment]
At least inherent methods should be listed now.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by QuietMisdreavus** [comment]
Since i just did function pointers (#43529), i'll add this while the details are fresh in mind.

@rust-lang/docs: What details should go here? `&T: Copy`? Using `&*` for reborrowing and Deref? Copy/paste details from either edition of the book? Leave it as a skeleton and fill it out later?

As for what impls to include, my initial thought was to only include impls where it's a reference to a generic. Otherwise it'll show up on the referent's page, like it is now.
