### ISSUE TITLE
Model lexer doesn't handle ... something?

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#15881]
Tracking issue for the lexer test failing `test/run-pass/issue-2185.rs`

**Comment by fhahn** [comment]
This issue seems fixed. `DOTDOTDOT` is already part of the tokens and since the conflict with float literals was resolved when  #15877 was fixed it works now as expected.

Note that `test/run-pass/issue-2185.rs` does not contain any `...` any more, but `test/run-pass/match-range.rs` does. I used this file for testing.

**Comment by cmr** [comment]
@fhahn cool! Can you add a run-pass test for this explicitly for the purpose of regression testing this?

**Comment by fhahn** [comment]
Should I just create a test which contains a match with a range with a name that refers to this issue?

**Comment by cmr** [comment]
Yeah.

On Wed, Jan 14, 2015 at 6:07 PM, Florian Hahn <notifications@github.com>
wrote:

> Should I just create a test which contains a match with a range with a
> name that refers to this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang/rust/issues/15881#issuecomment-70011032>.
>



-- 
http://octayn.net/
