### ISSUE TITLE
doc, explicit Result types

### ISSUE THREAD

**Issue by jxs** [rust-lang/rust#16096]
regarding #16075 
currently in std doc there are methods which return Result, which can be confusing at first sight. 
Would be great if the function showed upfront the Result<T, E>

**Comment by tomjakubowski** [comment]
I don't understand what this issue is about. Is it that types like `fmt::Result` should appear qualified by their module name, because they might be confused with other `Result` types?

One solution might be a pass that walks the crate and finds any types in signatures that have the same name but different definitions, and figuring out how many levels of modules are needed to qualify each of their names until there's no ambiguity.

**Comment by steveklabnik** [comment]
I believe that it's about `Result<Foo, Bar>` rather than `Result<T, E>` appearing in type signatures, but I'm not sure.

**Comment by tomjakubowski** [comment]
Reading the linked issue it looks like my understanding was right. There's another issue like that (substituting type parameters in default methods) #14072

**Comment by alexcrichton** [comment]
Yes this issue has to do with prefixes not being displayed, even when they're present in the source. For example [you only see `Result<usize>` here](http://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read)

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/42066; which is more general than this. Thanks!
