### ISSUE TITLE
Add a default directory to RUST_TARGET_PATH

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#16351]
It's possible that we want some sort of system-wide installation of target specifications.

**Comment by steveklabnik** [comment]
Would this change need an RFC? I'm inclined to say so, but I'm not sure.

**Comment by cmr** [comment]
No, this is purely a rustc thing. Target specs can't ever be part of the language spec.

**Comment by steveklabnik** [comment]
Triage: not aware of a change here.

**Comment by kevinmehall** [comment]
What if it tried `<sysroot>/lib/rustlib/<target name>/target.json` instead of or in addition to a fixed directory? That way you could install a target specification and the associated libraries by unpacking a single directory.

**Comment by cmr** [comment]
This was clarified in a recent PR, let me find it.

**Comment by cmr** [comment]
https://github.com/rust-lang/rust/pull/31117

**Comment by xobs** [comment]
This issue is mentioned in src/librustc_target/spec/mod.rs:1271 as being a FIXME.  There still doesn't appear to be any sort of sane default search path.

I like @kevinmehall 's approach, which tucks the `target.json` inside the sysroot, making it easy to distribute.  I'd also vote for adding `.` to the list.

Should this issue be reopened, since it was closed without any solution?
