### ISSUE TITLE
add a lint for preventing all known sources of address leaks

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#16516]
Rust now uses full ASLR by default, but it's possible to expose the randomized base in *safe code* by leaking a single address. An optional lint could check for conversions from raw pointers to integers. An attribute for marking functions like the `to_uint` method on raw pointers would also be necessary. Some of these functions could also be removed to discourage patterns prone to leaking addresses.

One common usage of addresses is for unique identifiers, but this is possible *without* converting raw pointers to integers. An identifier can be stored as `*const ()` and then compared with other pointers.

**Comment by steveklabnik** [comment]
Triage: not aware of any change.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
