### ISSUE TITLE
Remove the `assert_eq!` macro in favor of special-casing a check for equality in the `assert!` macro

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#16633]
We currently have four macros for runtime assertions: `assert!`, `assert_eq!`, `debug_assert!`, and `debug_assert_eq!`. See https://github.com/rust-lang/rust/blob/master/src/libcore/macros.rs#L50 for their definitions, which are all quite simple. The reason for having the `_eq` form for both `assert!` and `debug_assert!` is because equality checks are the most common kinds of assertions (`assert_eq!` is found 7100 times in the Rust repo, vs 4600 for `assert!`) and that by encoding the intent of the assertion we can produce a better error message, like so:
```rust
assert!(1 == 2);  // task '<main>' failed at 'assertion failed: 1 == 2'
assert_eq!(1, 2);  // task '<main>' failed at 'assertion failed: `(left == right) && (right == left)` (left: `1`, right: `2`)', assert.rs:2
```
However, I don't see a reason for the existence of this extra macro. I propose that we leverage our existing `macro_rules!` facilities to special-case the form `assert!(a == b)` such that it implements the current logic of `assert_eq!`. In non-tested copy-pasted code:
```rust
macro_rules! assert(
    ($cond1:expr == $cond2:expr) => ({  // literally just the inner bit of the assert_eq! definition
        let c1 = $cond1;
        let c2 = $cond2;
        if c1 != c2 || c2 != c1 {
            fail!("expressions not equal, left: {}, right: {}", c1, c2);
        }
    })
    ($cond:expr) => (  // the current assert! definition starts here
        if !$cond {
            fail!(concat!("assertion failed: ", stringify!($cond)))
        }
    );
    ($cond:expr, $($arg:tt)*) => (
        if !$cond {
            fail!($($arg)*)
        }
    );
)
```
Does anyone see any problems with this?

**Comment by alexcrichton** [comment]
In light of https://github.com/rust-lang/rfcs/pull/550 (implemented in https://github.com/rust-lang/rust/pull/20563), this is unfortunately no longer possible.

The `==` token is not in the follow set of the `expr` matcher for macros, and it's likely we won't make it so (due to ambiguities), so I'm going to close this issue as "not possible today".

**Comment by Gankro** [comment]
Does "not possible today" suggest "maybe possible eventually", or does this change preclude such a design from ever working?

**Comment by alexcrichton** [comment]
To allow this design I believe we would have to add `==` to the follow set of expressions in macros, but then this would be ambiguous:

```rust
assert!(foo == bar == baz)
```

For that macro invocation, what's `$lhs` and what's `$rhs`? As a result, I don't think that we can ever add `==` to the follow set of expressions, so I don't think that we'll ever be able to implement this.

**Comment by pczarn** [comment]
It can be implemented as a syntax extension. However, the change to `assert!` _might_ be breaking, because it doesn't currently check for `right == left`.

> If it could be done in a way that it outputs intermediate results of compound expressions, I would basically have the author's child.

How could you detect whether a compound expression's type implements `Show`? It's going to be possible with negative bounds.

There's an issue with intermediate results of compound expressions like these:
```rust
assert!(consume(foo) == bar)
```
In this example, `consume` moves the value out of `foo` which can't be printed after the check.
