### ISSUE TITLE
Closure kind inference: infer whether a closure is `Fn`, `FnMut`, etc

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#16640]
# Updated description

Closure kind inference: infer whether a closure is `Fn`, `FnMut`, etc

# Original Description

`Fn(int) -> int`, etc.

Nominating for 1.0, P-backcompat-lang.

**Comment by aturon** [comment]
Nominating; we should consider the beta milestone here IMO.

**Comment by pnkfelix** [comment]
Assigning 1.0-beta milestone to try to force this to get implemented for the beta.

**Comment by aturon** [comment]
Note: this is likely required to nix the `:` specifier syntax on closures.

**Comment by jroesch** [comment]
cc me

**Comment by nikomatsakis** [comment]
As of https://github.com/rust-lang/rust/pull/21805 this is almost complete. The major to do item is described in that PR:

"The interaction with instantiating type parameter fallbacks leaves something to be desired. This is mostly just saying that the algorithm from rust-lang/rfcs#213 needs to be implemented, which is a separate bug. There are some semi-subtle interactions though because not knowing whether a closure is Fn vs FnMut prevents us from resolving obligations like F : FnMut(...), which can in turn prevent unification of some type parameters, which might (in turn) lead to undesired fallback. We can improve this situation however -- even if we don't know whether (or just how) F : FnMut(..) holds or not for some closure type F, we can still perform unification since we do know the argument and return types. Once kind inference is done, we can complete the F : FnMut(..) analysis -- which might yield an error if (e.g.) the F moves out of its environment."

**Comment by nikomatsakis** [comment]
cc https://github.com/rust-lang/rust/pull/21843
