### ISSUE TITLE
Warning at use site for #[repr(C)] type that contains non-#[repr(C)] types

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#16719]
```rust
#![allow(dead_code)]

struct Foo;
#[repr(C)]
struct Bar { x: Foo }

extern { fn whatever(x: Bar); }

fn main() {}
```

```
<anon>:7:25: 7:28 warning: found type without foreign-function-safe
                                             representation annotation in foreign module, consider adding a #[repr(...)] attribute to the type, #[warn(ctypes)] on by default
<anon>:7 extern { fn whatever(x: Bar); }
                                 ^~~
```

This could either be a warning on `Bar`, that `Foo` isn't FFI safe; or not a warning at all. (Or, at the very least, a note pointing to the `x` field, to help diagnose the problem.)

**Comment by frewsxcv** [comment]
Triage comment: the warning has not changed

[playpen link](http://is.gd/2V7vZX)

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
