### ISSUE TITLE
DynamicLibrary::prepend_search_path not very useful on Linux

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#16901]
From the dlopen(3) man page:

> - If, at the time that the program was started, the environment variable LD_LIBRARY_PATH was   defined to contain a colon-separated list of directories, then these are searched. (As a security measure this variable is ignored for set-user-ID and set-group-ID programs.)

My reading of this is that changes to `LD_LIBRARY_PATH` made while the program is running do not affect the search path. This also seems to be the case in practice when using `DynamicLibrary` on my Linux machine.

**Comment by davvid** [comment]
If this function is intended for users then implementing the dlopen logic would be helpful because, yes, changing LD_LIBRARY_PATH after program startup has no effect on Linux, and ditto DYLD_LIBRARY_PATH on Darwin.

But DynamicLibrary::prepend_search_path() would not be a good API because it's a global static function.  A more useful API would be a non-static struct, e.g. DynamicLibraryLoader, which can be instantiated in user code.

The benefit is that it would allow users to create instances with differing search paths.  An instance of a DynamicLibraryLoader could have an add_search_path() that actually works because it would implement the search-path logic itself.  I wouldn't call it nasty or error-prone; the logic is pretty simple.

At first I thought that DynamicLibrary::search_path() could be consulted when constructing a DynamicLibraryLoader's initial search path, breathing a little more life into DynamicLibrary's utility.  In that world the global prepend_to_search_path() would serve a useful purpose -- it can be used to setup the default search path that's present when creating new instances.  But, thinking it through, global state is bad, and coupling these two structs would also be a bad idea, so, yeah, prepend_search_path() is kind of a useless API and should probably be documented as having caveats on most non-Windows platforms.

**Comment by apasel422** [comment]
Is this actually a libs issue? It appears that `prepend_search_path` is defined in `librustc_back`.

**Comment by sfackler** [comment]
It used to live in libextra. Closing, since this is no longer publicly exposed.
