### ISSUE TITLE
duplicate warning for unused mut variable

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#17525]
Oops, pressed enter too early.

```
fn main() {
    let mut x = 2u;
}
```

yields:

```
dupun.rs:2:9: 2:14 warning: unused variable: `x`, #[warn(unused_variable)] on by default
dupun.rs:2     let mut x = 2u;
                   ^~~~~
dupun.rs:2:9: 2:14 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
dupun.rs:2     let mut x = 2u;
```

The second warning is redundant after the first one (it's not mutated because it's not used at all), so there shouldn't be two.

**Comment by frewsxcv** [comment]
Both warnings still appear with the latest Rust, this issue is still valid.

**Comment by steveklabnik** [comment]
Updated code:

```
fn main() {
    let mut x = 2usize;
}
```

While it's true that these warnings are related, I'm not sure that there's any value in tying two lints together such that we remove the others because they logically follow from other lints. Given that this isn't _wrong_, and nobody else has said anything, and it's been over a year, I'm going to give this a close as "wontfix".
