### ISSUE TITLE
rustdoc: show macro interface but not implementation

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#17616]
e.g. http://doc.rust-lang.org/std/macro.bitflags!.html has 120 lines of macro code before anything useful.

**Comment by kmcallister** [comment]
> A better solution to that problem in my opinion would be to only show the arms of the macro that provide information about how to invoke it, not what it generates.

Agreed. If we move some code around, we can parse into LHSes and RHSes on macro definition, and then have rustdoc display only the former.  I think I can get this in place for 1.0-stable.

**Comment by kmcallister** [comment]
Not going to have time to work on this for 1.0-final, sorry.

**Comment by nixpulvis** [comment]
FWIW I also had the exact same thought when looking at the documentation for `bitflag!` as well. The proposed change to only show the left arm of the macro would look like this.

```rust
macro_rules! bitflags {
    ($(#[$attr:meta])* flags $BitFlags:ident: $T:ty {
        $($(#[$Flag_attr:meta])* const $Flag:ident = $value:expr),+
    }) => ...
    ($(#[$attr:meta])* flags $BitFlags:ident: $T:ty {
        $($(#[$Flag_attr:meta])* const $Flag:ident = $value:expr),+,
    }) => ...
}
```

A welcome change.

**Comment by m4rw3r** [comment]
I have a similar issue, though it cannot easily be solved by just showing the left arm of the macro since there are multiple internal rules and they refer to each other: https://github.com/m4rw3r/chomp/blob/60cb0fb111e079c472c02821cee5e82b0eef2b82/src/macros.rs#L71

If we just go with the left arm of the macro it will result in a lot of nonsensical entrypoints:
```rust
macro_rules! parse {
    ( @RET($i:expr); @ $t_ty:ty , $e_ty:ty : $e:expr ) => { ... };
    ( @RET($i:expr); $e:expr ) => { ... };
    ( @ERR($i:expr); @ $t_ty:ty , $e_ty:ty : $e:expr ) => { ... };
    // ...
    ( $i:expr ; err $($tail:tt)+ ) => { ... };
    // ...
    ( $i:expr ) => { $i };
}
```
And skipping the internal rules will make the macro even more incomprehensible since the entrypoints themselves just parse a bit of the tokens for each invocation.

For my case I would think that just hiding the whole macro definition would solve the problem (maybe with some button to expand the definition), since I have to explain how the macro is used anyway since it by itself says nothing unless people are very experienced with rust macros.

As a workaround I have defined a hidden macro which contains the actual definition: https://github.com/m4rw3r/chomp/blob/5016d0b9e636156927e514f430e33510d9fa94f7/src/macros.rs#L76
