### ISSUE TITLE
Allow LintPasses to run after trans

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#17642]
We currently have one lint `VARIANT_SIZE_DIFFERENCE` that's hard-wired into trans. We should generalize this and make it available to lint plugins.

**Comment by steveklabnik** [comment]
Traige: looks like no change.

**Comment by steveklabnik** [comment]
Triage: still no change

**Comment by rkruppe** [comment]
Some relevant changes since the OP:

- `VARIANT_SIZE_DIFFERENCES` isn't hardwired into trans any more as of #34755
- lint plugins are on the way out, the Right Way is a custom driver now
- we don't even keep HIR around at codegen time any more, let alone walk it

There might still be use cases for emitting lint warnings from monomorphized MIR (if we can find a way to accurately preserve the `allow(..)`, `deny(..)`, etc. annotations in metadata) but AFAIK that's hypothetical and I believe custom drivers can already achieve it by hooking into the relevant queries.

**Comment by oli-obk** [comment]
> monomorphized MIR

**Comment by rkruppe** [comment]
> That's not a thing. We don't monomorphize MIR

Sorry, I should have been more clear, I meant the (generic MIR, substs) pair that codegen item collection produces.

> I think we should just close this issue. It's very problematic to only report lints in case the trans backend decides on doing something, especially once we get to MIR-only rlibs

That's always been the case, but yeah it's very sensitive to improvements to the collector or even MIR optimizations. I think it might be OK for some desirable warnings that are impossible to emit pre-monomorphization but YMMV and certainly requires more motivation than is given here.
