### ISSUE TITLE
Lifetime suggestion hint interacts weirdly with closures

### ISSUE THREAD

**Issue by P1start** [rust-lang/rust#17811]
``` rust
fn main() {
    let closure = |x: &uint| -> &uint { x };
}
```

Produces:

```
<anon>:2:41: 2:42 error: cannot infer an appropriate lifetime for automatic coercion due to conflicting requirements
<anon>:2     let closure = |x: &uint| -> &uint { x };
                                                 ^
<anon>:1:1: 3:2 note: consider using an explicit lifetime parameter as shown: fn main<'a>()
<anon>:1 fn main() {
<anon>:2     let closure = |x: &uint| -> &uint { x };
<anon>:3 }
error: aborting due to previous error
```

This is suggesting to put a lifetime on the `main` function, which certainly is not going to solve the problem here. The real solution is to give `closure` an explicit type declaration: `let closure: <'a>|&'a uint| -> &'a uint = ...;`.

Incidentally, is lifetime elision supposed to work on closures, too? Evidently it does not.

**Comment by bombless** [comment]
```rust
fn main() {
    let closure = |x: &u32| -> &u32 { x };
}
```
Same issue today.
Seems relatively easy to fix, I'll work on it.

**Comment by bombless** [comment]
https://github.com/rust-lang/rust/blob/8a60e5667fa77c4a7a4e13bf7ab4ad6f1d033ca9/src/librustc/middle/infer/error_reporting.rs#L820
Given the name `give_suggestion` here which sounds too general, I think we'd better stop giving advice for this case, but I'm not sure.

In real coding I may try to make a helper function to retrieve the context by reference or even use a macro if I'm in a good mood (which I know might not really be a Rust way). Of course, better to avoid a closure here since lifetimes work better in real context rather than being used as arguments.

**Comment by bombless** [comment]
I think it's also a valid option that we refactor the error_reporting.rs here to use proper method names, as this "give_suggestion" is not the only method name that looks misleading here.

**Comment by bombless** [comment]
maybe related: https://github.com/rust-lang/rust/issues/25005

**Comment by Manishearth** [comment]
#25005 is probably not related. ast_map's parenting is conceptually broken, but the current rustc code basically relies on this broken code (It uses `get_parent` to mean "get the parent item or fn")

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by Mark-Simulacrum** [comment]
I don't see any errors after changing uint to u32 today; closing.
