### ISSUE TITLE
fail_ and fail_bounds_check lang items don't belong to libcore

### ISSUE THREAD

**Issue by farcaller** [rust-lang/rust#17886]
Both `fail_` and `fail_bounds_check` are platform-dependent and the default implementation in libcore makes it impossible to override those.

I can expect fail to be infinite loop or `bkpt` instruction, it must not pull in error strings and chunks of `fmt` that are never doing to be displayed.

At least it's reasonable to cfg-guard the implementations, so cross-tool users could build libcore without them.

**Comment by steveklabnik** [comment]
Since this bug was filed, `fail` was changed to `painc`. There is no `panic_` lang item, I don't know if that was also changed. There is a `panic_bounds_check`, but it calls out to `panic_fmt`, which is a "weak lang item", meaning that while libcore declares it, it does not define it. A `no_std` yes `core` crate which uses panics must define `panic_fmt`.

As such, I *believe* this bug can be closed. Let me know if I've missed something!
