### ISSUE TITLE
Add a CSS reset to the docs

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#17929]
Both the text and the background are black in the steam ingame browser.

**Comment by steveklabnik** [comment]
we are already using http://necolas.github.io/normalize.css/3.0.0/normalize.css

**Comment by tomjakubowski** [comment]
It doesn't really matter that we're using a CSS reset because CSS resets won't do what was originally asked in this issue.

If you set body/headline text color, then you have to set the background color too; otherwise you get conflicts with user and user agent stylesheets, like with Steam's browser. CSS resets don't usually set background or text colors on main elements, and they shouldn't.

**Comment by frewsxcv** [comment]
A screenshot of what this issue is:

![screen shot 2015-02-23 at 6 01 03 pm](https://cloud.githubusercontent.com/assets/416575/6339686/51fdbdc0-bb86-11e4-9990-7d77ffcaef51.png)
