### ISSUE TITLE
SIMD floating point calculations will not match x86 results in many cases

### ISSUE THREAD

**Issue by Ryman** [rust-lang/rust#17976]
I feel this is expected behaviour, but I ran into this when debugging the mandelbrot benchmark for x86.

When compiling on x86 it's choosing to use x87 for floating point calculations rather than sse, which leads to 80bit intermediates which leads to diverging results. 

It will work and get the same results for x86 and x64 if we pass `-C target-feature=+sse2` to rustc during compilation as a workaround but obviously this doesn't help if the target doesn't support sse2. Perhaps there's a better flag to use here?

Either way, I think we should call this out in the docs as it could be a real pain for end users if they need deterministic calculations.

**Comment by rkruppe** [comment]
This remains an issue, but only when explicitly giving `-C target-feature=-sse` (or `-sse2`). At some point between October 2014 and now, codegen must have changed to assume SSE2 by default on x86 (or at least on `i686-unknown-linux-gnu`), but one can explicitly disable it. I don't know if this was intentional but apparently it didn't cause enough problems for anyone to investigate and revert it.

**Comment by steveklabnik** [comment]
Given that this issue has been open for so long of a time, and nobody else has run into this, I'm going to give it a close. SSE stuff is still undergoing a lot of churn.

**Comment by rkruppe** [comment]
The story for using SIMD instructions is going through churn, but this is about what CPU features rustc assumes, and consequently which instructions LLVM will emit for perfectly ordinary, scalar calculations (just `f32`/`f64`, no vectors or even intrinsics).

The story here is unchanged since my last comment (rustc assumes SSE2 on the usual 32 bit x86 targets), with the caveat that there are extra targets (`i386-...`) for people who need to run on pre-SSE2 hardware. And by now this is not a temporary accident, but a long-standing policy.

I do agree with closing the issue, it's unlikely many people will ever encounter the joys of the x87 FPU, since rustc defaults to SSE2.
