### ISSUE TITLE
extern "C" functions are not internalized with -C lto

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#18134]
When marking public functions with `#[no_mangle]` and then linking to the crate with the functions using `-C lto`, the functions will be exported in the output.

This can result in errors about duplicate definitions (when linking things linked with `-C lto` together) and also prevents the removal of unused functions.

**Comment by drbo** [comment]
One case where this would be useful is where is using lto so that cross-language optimizations can take place.  For instance, one can (or should be able to) inline a small C function compiled with Clang into Rust code, or inline a Rust function into C code.  In both cases, the function may be private to the combined library.

**Comment by Zoxc** [comment]
It appears extern functions are removed now due to a recent change (tested on 3210fd5c20ffc6da420eb00e60bdc8704577fd3b). However doing so isn't always the right thing either. This breaks [rlibc](https://github.com/alexcrichton/rlibc).

**Comment by Mark-Simulacrum** [comment]
@alexcrichton So we first made extern "C" functions stay around with LTO, but now we no longer do this, so I'm not sure -- should we close this issue? It's not clear whether we want or don't want this.

**Comment by alexcrichton** [comment]
I believe bugs have been fixed in the meantime, it looks like this issue is no longer applicable.
