### ISSUE TITLE
add an off-by-default lint for catching constant statics

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#18312]
Crates not concerned about providing a stable ABI for global variables should be able to opt-in to a lint to deny constant statics. This would catch regressions due to the removal of inlining and insignificant addresses for constant `static` variables (#18311).

**Comment by steveklabnik** [comment]
Traige: no change.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
