### ISSUE TITLE
mark C ABI functions as nounwind

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#18512]
It's explicitly undefined to unwind past an FFI boundary, so these functions can be considered `nounwind`. The soundness hole allowing safe Rust code to unwind past FFI boundaries should be fixed first (https://github.com/rust-lang/rust/issues/18510).

**Comment by bstrie** [comment]
As far as I can tell, the resolution to this bug was originally implemented in https://github.com/rust-lang/rust/pull/21186 , which was postponed while waiting for the decision on the RFC at https://github.com/rust-lang/rust/pull/21186 , which was eventually rejected in favor of https://github.com/rust-lang/rfcs/pull/1236 , which is now implemented and stabilized. @aatch, do you think we can make progress here now?

**Comment by Aatch** [comment]
Looks like C functions are marked `nounwind` now.
