### ISSUE TITLE
Allow transitive coercions

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#18602]
See [RFC 401](https://github.com/rust-lang/rfcs/blob/master/text/0401-coercions.md).

Part of #18469

**Comment by steveklabnik** [comment]
and here https://github.com/rust-lang/rust/issues/18469

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by Enselic** [comment]
Triage: I'm a bit confused. RFC 401 seems implemented since https://github.com/rust-lang/rust/issues/18469 is closed. Does this issue track something ("transitive coercions") that didn't make it into RFC 401? If yes, then it seems like "transitive coercions" deserves its own RFC and that this issue can be closed due to lack of details? If no, then I think we can close this issue as obsolete?

It seems like regardless of if the answer is "yes" or "no", this issue should be closed. So let's close. If I am confused, of course feel free to re-open after clarifying the situation.

**Comment by Enselic** [comment]
This seems to be an example of something transitive coercions would allow BTW: https://github.com/rust-lang/rust/issues/52075
