### ISSUE TITLE
Tag and version convention

### ISSUE THREAD

**Issue by l0kod** [rust-lang/rust#18815]
There is currently Git tags prefixes "release-" (old ones I guess) and "0.".
It would probably be more readable to switch to a "v" (or "rust-") prefix for version tags (like for the Linux repository). This way, it's easier to filter version tags (e.g. with "git tag -l v\*"). It's especially useful when there is other tags than for version (e.g. local tags).

**Comment by edunham** [comment]
@l0kod the [current versioning scheme](https://github.com/rust-lang/rust/tags) is x.y.z, sometimes suffixed by `-alpha` or `-beta`. 

Annoyingly, `git tag -l` uses `fnmatch` (aka shell globbing) rather than full regex, so the current most concise way to list only the version number tags (no alphas, betas, old release- tags, or local descriptive tags) seems to be `git tag -l | grep -v [a-zA-Z]` 

Do you think that the versioning scheme enstated by the release channels RFC is sufficient to resolve this issue?
