### ISSUE TITLE
Lint for unused syntax variables in macros

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#18820]
E.g.

```rust
macro_rules! foo {
    ($func: ident) => { () } // warning: unused syntax variable `func`
}
```

**Comment by frewsxcv** [comment]
Visiting for triage: this is still an issue

http://is.gd/jfjxWe

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
