### ISSUE TITLE
Problem downloading from static.rust-lang.org using python urllib

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#18930]
Servo has a script using urllib to download nightlies and it's failing during the HTTPS handshake: https://github.com/servo/servo/issues/3582#issuecomment-62939342

**Comment by edunham** [comment]
Current Python 2.x is 2.7.10, which according to @SimonSapin's comment linked above, supports SNI. The [requests library FAQ](http://docs.python-requests.org/en/latest/community/faq/#what-are-hostname-doesn-t-match-errors) confirms this, and links to [this stackoverflow answer](https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484) for some workarounds if for some reason a pre-2.7.9 Python is required. 

Closing this since the Servo issue it mirrors is now resolved.
