### ISSUE TITLE
Closure tries to borrow &mut to entire struct, when only a field is required

### ISSUE THREAD

**Issue by mihneadb** [rust-lang/rust#19004]
Offending code:

``` rust
struct Foo {
    b: i32,
    v: Vec<i32>
}

fn incr(x: &mut i32) {
    *x += 1;
}

fn main() {
    let mut f = Foo { b: 0, v: vec![1, 2, 3] };

    f.v.iter().map(|s| {
        incr(&mut f.b);
        println!("{}: {}", f.b, s);
    }).last();
}
```

Error: `error: cannot borrow `f` as mutable because `f.v` is also borrowed as immutable`

On playpen: http://is.gd/PTXhJq

Version info:

```
rustc 0.13.0-nightly (d91a015ab 2014-11-14 23:37:27 +0000)
binary: rustc
commit-hash: d91a015ab4c538f02fbbc03dfb08193a381c2e3b
commit-date: 2014-11-14 23:37:27 +0000
host: x86_64-unknown-linux-gnu
release: 0.13.0-nightly
```

Thanks @bjz for helping me submit this.

**Comment by joshtriplett** [comment]
I just ran into this one today, with 'f' being 'self'; that seems like a rather common case, which will come up any time you write self.somefield.method(|| { ... self.otherfield.method(...) ... }) (and at least one of the methods wants a &mut).

Based on some discussion in the #rust IRC channel, this seems potentially feasible to fix.  The closure desugaring just needs to recognize references to fields and capture the field in that case, rather than capturing the entire top-level label.

**Comment by Diggsey** [comment]
Capturing the individual fields rather than "self" would significantly increase the size of the closure. It should be possible to internally capture just the "self" pointer, but make it appear for all intents and purposes that the fields were captured individually.

**Comment by steveklabnik** [comment]
Triage: no updates in almost two years.

Personal note: this code still compiles with the original error today. Neat! Not too much pre-1.0 stuff left that does that...

**Comment by oli-obk** [comment]
I don't think we should change this.

1. There's an easy workaround when you actually want to borrow only a part of the struct.
2. I actually like this, because it makes me think about what I'm doing.

What should be done imo is to add a suggestion to the error that gives the solution of borrowing the field into a new binding and then using that binding inside the closure.

**Comment by Diggsey** [comment]
@oli-obk That's fine if you're only borrowing one field, but it's a fair amount of boilerplate when you're borrowing say, all but one of the fields in the struct. It also produces a larger closure than necessary, which could be the difference between having to allocate the closure on the heap, vs being able to store it inline, if anyone writes a `std::function` equivalent for rust.

**Comment by oli-obk** [comment]
@Diggsey ah, so you are suggesting to store the pointer to the struct, but the borrowchecker will still forbid accessing already borrowed fields?

**Comment by Diggsey** [comment]
Yep :)

**Comment by samsartor** [comment]
+1

This is fine:
```rust
let _a = &mut foo.a;
&mut foo.b; // ok!
```

So is this:
```rust
let _a = &mut foo.a;
loop { &mut foo.b; } // ok!
```

Why should closures be treated differently? It seems inconstant with the rest of the language.
```rust
let _a = &mut foo.a;
|| &mut foo.b; // cannot borrow `foo` as mutable more than once at a time
```

Does this require an RFC, or is it minimal+non-breaking enough to just be fixed outright?

**Comment by Diggsey** [comment]
> this would entirely be a change to the borrow checker

Might have to be careful not to hint to LLVM that this is an exclusive reference?

**Comment by arielb1** [comment]
@samsartor 

This is enough of a feature to require an RFC.

**Comment by samsartor** [comment]
Working on an RFC now...
