### ISSUE TITLE
Spurious test failures

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#19120]
Our builders are susceptible to *a lot* of spurious test failures, and I've been keeping some of this knowledge in my head for far too long, so I'd like to write it down. I'm writing this to be a metabug, but I expect other bugs to be spawned off from it as well. Sometimes it's just a lot easier to add a bullet than a whole new bug!

If you add to this, please don't link directly to buildbot logs as they disappear over time. Instead please link to a gist with the relevant information pasted in. I also typically peruse http://buildbot.rust-lang.org/grid?branch=auto&width=10 for build failures

## Spurious test failures

* [x] stdtest deadlocks on windows once a TCP test fails [(logs)](https://gist.github.com/alexcrichton/c012d72c5057db4cbaa7#file-gistfile1-txt-L5634-L5636) [(test)](https://github.com/rust-lang/rust/blob/f0f7ca27de6b4e03f30012656dad270cda55a363/src/libstd/net/tcp.rs#L377)
* [ ] stdtest spuriously segfaults on freebsd [(logs)](https://gist.github.com/alexcrichton/f3edae4628f2254446f2). The segfaults decreased in frequency when freebsd was upgraded, it may just need to be upgraded again.
* [ ] stdtest deadlocks [(logs)](https://gist.github.com/alexcrichton/d6adb945645f5de5a83e)
  * [ ] `thread_local::dtors_in_dtors_in_dtors` deadlocks on OSX [(logs)](https://gist.github.com/alexcrichton/2443712cf90cda1fdf11)
* [ ] `io::process::tests::test_kill` spuriously fails [(logs)](https://gist.github.com/alexcrichton/572c88320680659585ba)
* [x] run-pass-fulldeps/issue-13560.rs [(logs)](https://gist.github.com/aturon/8d2bf1ee254ea6348e91)
* [x] wait-forked-but-child-failed [(logs)](https://gist.github.com/alexcrichton/8a61005a025c25533ac9)
* [x] src/test/run-pass/issue-12684 [(logs)](https://gist.github.com/alexcrichton/e0d234326cade54e7200)

## Spurious failure behvaior

* [x] windows git failures lead to corruption of all future builds. I think @brson fixed this as I haven't seen it recently.
* [x] windows thinks failed processes exit with a 0 exit status https://github.com/rust-lang/rust/issues/18981
* [x] windows will sometimes leave a test process running after the build finishes, preventing any future builds from overwriting the executable. This is not specific to any particular test. [(logs)](https://gist.github.com/alexcrichton/b240e4abcacc924b744a)
* [x] windows `make clean` randomly fails due to some arbitrary object file not being able to be overwritten. [(logs)](https://gist.github.com/alexcrichton/331bfc0714b106ae6721)
* [x] windows bots fail to upload stability metrics randomly sometimes https://github.com/rust-lang/rust/issues/19079

**Comment by klutzy** [comment]
#20677 auto-win-32-nopt-t test [failed](http://buildbot.rust-lang.org/builders/auto-win-32-nopt-t/builds/2697/steps/test/logs/stdio). The only difference between the output list and current `src/test/run-pass` is `unwind-resource`, so I assume it hanged.

Collected some more `command timed out: 1200 seconds without output, attempting to kill` -> `collect2.exe: error: ld returned 1 exit status` logs. (The latter occurs because the hanged process is still alive during next build)

-   [auto-win-32-opt 2649](http://buildbot.rust-lang.org/builders/auto-win-32-opt/builds/2649/steps/test/logs/stdio)/[2650](http://buildbot.rust-lang.org/builders/auto-win-32-opt/builds/2650/steps/test/logs/stdio): extern-stress, extern-yield, tcp-accept-stress, threads
-   [auto-win-32-opt 2646](http://buildbot.rust-lang.org/builders/auto-win-32-opt/builds/2646/steps/test/logs/stdio)/[2647](http://buildbot.rust-lang.org/builders/auto-win-32-opt/builds/2647/steps/test/logs/stdio): extern-stress, tcp-accept-stress, threads, unique-send-2
-    [auto-win-32-opt 2603](http://buildbot.rust-lang.org/builders/auto-win-32-opt/builds/2603/steps/test/logs/stdio): extern-yield, issue-9396, tcp-accept-stress, threads
-    [auto-win-32-nopt-t 2609](http://buildbot.rust-lang.org/builders/auto-win-32-nopt-t/builds/2609/steps/test/logs/stdio)/[2610](http://buildbot.rust-lang.org/builders/auto-win-32-nopt-t/builds/2610/steps/test/logs/stdio): drop-trait-enum

All hanged test uses `Thread::spawn()`.

**Comment by alexcrichton** [comment]
@klutzy yes I've reached the same conclusion as well, and that set of tests all look quite familiar! When I removed `std::task` I was hoping this would all "go away" because `Thread::spawn` implicitly joined, but then we changed it again!

I'll switch those tests over to `scoped`.

**Comment by Manishearth** [comment]
Filed a separate bug for the rather common windows failure

https://github.com/rust-lang/rust/issues/22628

**Comment by alexcrichton** [comment]
New windows spurious failure I've seen:

* stdtest deadlocks on windows once a TCP test fails [(logs)](https://gist.github.com/alexcrichton/c012d72c5057db4cbaa7#file-gistfile1-txt-L5634-L5636) [(test)](https://github.com/rust-lang/rust/blob/f0f7ca27de6b4e03f30012656dad270cda55a363/src/libstd/net/tcp.rs#L377)

(added to list above)

**Comment by Manishearth** [comment]
From https://github.com/rust-lang/rust/pull/24053

```
thread '<unnamed>' panicked at 'assertion failed: !p.wait().unwrap().success()', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/old_io/process.rs:1139
test old_io::process::tests::test_kill ... FAILED
```

http://buildbot.rust-lang.org/builders/auto-mac-64-nopt-t/builds/4378

**Comment by alexcrichton** [comment]
I think that this bug has somewhat outlived its lifespan, any new spurious failures can have follow-up bugs.
