### ISSUE TITLE
Unboxed closures with no or only-Copy captures should be Copy

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#19128]
Right now no unboxed closures are Copy, but there's no reason that 0-size closures or those with only copy captures couldn't be Copy.

**Comment by Vaelden** [comment]
So apparently the changes to make the trait Copy opt-in for closures have been implemented, which means that the code above doesn't work any more.
But can somebody explain how I can actually opt-in for the Copy trait when declaring a closure?

**Comment by steveklabnik** [comment]
Triage: closures aren't copyable again, but I am not sure if they're intended to be or not. @rust-lang/lang?

**Comment by bluss** [comment]
They were deliberately made non-copy in issue #19817

**Comment by huonw** [comment]
>  But can somebody explain how I can actually opt-in for the Copy trait when declaring a closure?

There's a few possible ways to have duplicatable closures (all aren't great, unfortunately):

- pass a `&` reference instead of the closure itself (`&F` implements `Fn` when `F` itself does), which implements `Copy`
- use `Rc<F>` (possibly a trait object), similar to the above, but this can be stored/returned (only implements `Clone`
- write `fn foo<F, G>(f: F) where F: Fn() -> G, G: Fn(...) -> ...` instead of `fn foo<F>(f: F) where F: Fn(...) -> ...`, where the `F` closure creates new instances of the actual closure of interest (`G`), effectively behaving as the `clone` function. I suspect this often works as just `foo(|| |actual| closure)`, i.e. just add `||` at the start of the closure.

These have various downsides e.g. the first two only work for `Fn` (not `FnMut` or `FnOnce`), the first cannot be returned from functions/stored inside return values, the second doesn't integrate with generics quite as well as others, and the third is rather ugly.

**Comment by steveklabnik** [comment]
Thanks @bluss !
