### ISSUE TITLE
Warn on encountering unknown doc-attributes

### ISSUE THREAD

**Issue by qrlpx** [rust-lang/rust#19219]
Like for allow/warn/forbid, there should be a warning when compiling code like `#[doc(foo)]`.

version: rustc 0.13.0-nightly (81eeec094 2014-11-21 23:16:48 +0000)

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
