### ISSUE TITLE
Do we have a central document with the Rust grammar?

### ISSUE THREAD

**Issue by icorderi** [rust-lang/rust#19278]
Hey guys, we are trying to revamp the CodeMirror definition for Rust given that it is a bit out of date and doesn't parse Rust code correctly anymore. Here is the [issue](https://github.com/codemirror/CodeMirror/issues/2937) on CodeMirror.

Do we have a document outlining the Rust language grammar? I've seen bits and pieces all over the [reference](http://doc.rust-lang.org/reference.html) document. 

Who in the Rust community can help with this?

**Comment by brson** [comment]
The makefiles may still need to be updated to render the docs, and a link placed somewhere.

**Comment by marijnh** [comment]
Assuming that http://doc.rust-lang.org/grammar.html reflects the current state of the grammar, there's still a lot of FIXMEs and missing rules. Is there an issue tracking the completion of an actual full grammar?

**Comment by pnkfelix** [comment]
@marijnh I agree that having an issue for the full grammar is important, so I filed #22445.

(I chose spawning a new issue over reopening this ticket, because I think the most interesting part of this ticket was choosing an tool for documenting the grammar and incorporating an invocation of that tool into our build process, yay!)
