### ISSUE TITLE
Move automation off mac minis, onto macstadium

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#19286]
Physical hardware sucks.

**Comment by edunham** [comment]
I talked with the Servo team today and they're currently using Macstadium for their OSX CI. This means it's definitely possible, though I've yet to investigate pricing and Buildbot integration.

**Comment by edunham** [comment]
Related to #17269

**Comment by edunham** [comment]
There are also a few alternatives to macstadium. I've taken some notes on https://ethersheet.org/s/osx-cloud-hosting . Choosing the best one for our needs will require assessing the utilization of the current macs, which is on my list of things that can wait until after Whistler.

**Comment by edunham** [comment]
Update: We have the budget for this. Macstadium can only invoice Moz if we have over 10 minis, which we'd be close to between Rust and Servo. Otherwise, we can keep using credit cards then expensing it per-project.

I talked to several people from various companies at MacITConf last month, and confirmed my impression that Macstadium is the closest to AWS for OSX that we can currently get.

**Comment by brson** [comment]
This is done.
