### ISSUE TITLE
Tracking issue for RFC 459 - Disallow type/lifetime parameter shadowing

### ISSUE THREAD

**Issue by nick29581** [rust-lang/rust#19390]
[discussion](https://github.com/rust-lang/rfcs/pull/459)

cc @nikomatsakis

**Comment by nick29581** [comment]
I suggest we leave it and go straight for the lint (as we plan to do eventually with the lifetime version). Then no backwards compatibility issues. Also, since type shadowing is allowed in every other language it is going to really surprise people if it is forbidden in Rust. And, it is the shadowed lifetimes which were causing the motivating confusion.

**Comment by mrhota** [comment]
just for future visitors, type parameter shadowing (like the example in the RFC) does, in fact, produce a clear compiler error.

The comments above and lack of linked "type parameter shadowing" PRs might otherwise suggest that type parameter shadowing was left as a lint rather than a compiler error.
