### ISSUE TITLE
Rustdoc should be able to show which crates are required to use a particular crate

### ISSUE THREAD

**Issue by scialex** [rust-lang/rust#19423]
When doing embedded/OS-dev work it is useful to pull in some rust std-lib crates. To do this, however one needs to make sure we have all the crates it requres. It would be useful if we could have a link/section that shows what crates are pre-requisites of any particular crate in rustdoc.

**Comment by alexcrichton** [comment]
This sounds like something that's solve by Cargo, not by rustdoc?

**Comment by alexcrichton** [comment]
After thinking a little more about this, I think that Cargo has basically subsumed this. All dependencies can be viewed online at crates.io, and otherwise the set of dependencies is in general a private aspect of a crate that rustdoc probably doesn't want to be documenting (as it's not a public interface). As a result, I'm going to close this.
