### ISSUE TITLE
Classify "result-only" operations and warn on ignoring their results

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#19446]
Things like:
    - struct field access
    - comparisons and other operator applications

should warn if their results are ignored, for instance in `x == y;` or `x.y;`.

This could probably use the existing `#[must_use]` infrastructure somehow.

**Comment by kmcallister** [comment]
I think it is totally reasonable for `==` to use interior mutability in a way that doesn't change semantics.  Some data structures rebalance on every traversal.  It would be great to *prove* that the semantics aren't changed, but this is far outside the scope of Rust's type system.

I think the lint is a good idea though, because there's no need to call `x == y;` *only* for the side effects.  If you really need it, say in your test cases for `Eq`, then `let _ = ...` is the solution.

**Comment by frewsxcv** [comment]
Visiting for triage: we still don't give warnings for the things mentioned earlier

[playpen link](http://is.gd/h8YEde)

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
