### ISSUE TITLE
Forbid object types which are not object safe

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#19482]
We currently only check for object safety when coercing a concrete object to a trait object. We should prevent the programmer writing object types which are not object safe.

**Comment by steveklabnik** [comment]
Traige: we did this, didn't we?

**Comment by jonas-schievink** [comment]
Looks like #21953 is a duplicate which was closed

**Comment by bluss** [comment]
Is `FnOnce` object safe? Its methods can't be called through an object. `Add` is the same way (currently object safe but not callable).

**Comment by steveklabnik** [comment]
@jonas-schievink yup!

**Comment by nikomatsakis** [comment]
@bluss `FnOnce` is considered object safe. Basically, the restriction against calling `call_once(self)` is enforced on the *caller* side by requiring that callee be `Sized` (and hopefully we will lift this restruction eventually). Put another way, if I write `fn foo<T:FnOnce()>(t: T)`, I can't have `T=FnOnce()` anyway because `T: Sized` would not hold. If I write `fn foo<T:FnOnce()+?Sized>(t: T)`, then `T=FnOnce()` is possible, but `t()` will fail to compile because `T: Sized` does not hold. So it works out either way.
