### ISSUE TITLE
Formatters for collections

### ISSUE THREAD

**Issue by themasch** [rust-lang/rust#19670]
Hi, 

I think the formatting traits from std::fmt should be implemented for collections too. 
Here is a minimal example of the issue:  (play: http://is.gd/9wbLkg )

```rust
fn main() {
    let a: u8 = 42;
    let b: [u8, ..6] = [ 1, 2, 4, 8, 16, 32 ];
    println!(" Works: {:X} does not work: {:X} ", a, b);
}
```

Tried this with play.rust-lang.org & local with "0.13.0-nightly (6f4c11be3 2014-12-05 20:23:10 +0000)" 

Beeing able to easily print &[u8] as hex for example would make debugging stuff more easy.

**Comment by skullzzz** [comment]
Yep. Haven't had a lot of time to work on this, sorry. I've got a WIP branch [here](https://github.com/skullzzz/rust/commits/collections_formatter)

I think I've got the hang of it though, so I should be able implement a bunch of fmt traits for all the collections I can find this weekend.

**Comment by ruud-v-a** [comment]
I agree with @lfairy, `[u8]` with the `:x` or `:X` formatters should print as a single string, two characters per byte. So `[1u8, 2, 42]` should print as `01022a`. Printing a slice of bytes in this way is quite common: tools like `sha1sum` print their output in this way, uuids are printed in this way (albeit with dashes), Git formats its hashes in this manner, and data in http digest authentication is encoded in this way, just to name a few. I suspect that printing individual bytes hexadecimally is far less common. I do agree with the consistency argument, but I think that in this case the benefits of being able to format a byte slice directly outweigh the inconsistency. Otherwise, every program that wishes to print a byte slice in this manner has to add its own `[u8] -> String` function, whereas printing individual bytes is likely to be used for debugging purposes only. Having to implement `[u8] -> String` manually is not that big of a deal, but it is one of those papercuts that we could fix.

**Comment by lfairy** [comment]
@ruud-v-a Note that we already have a method that does that, in [`serialize::hex`](http://doc.rust-lang.org/rustc-serialize/rustc-serialize/hex/trait.ToHex.html).

**Comment by ruud-v-a** [comment]
@lfairy Ah, I missed that one, thanks for pointing out!

**Comment by thelink2012** [comment]
So what is the status of this? @skullzzz ?

**Comment by skullzzz** [comment]
Since the requirements of this task have changed, I don't think I'll be able to continue working on this. For anyone else wishing to work on this, refer @alexcrichton 's closing comment in #25319 .

**Comment by alexcrichton** [comment]
Ah yes thanks for the reference @skullzzz, as [I commented](https://github.com/rust-lang/rust/pull/25319#issuecomment-110858842) I believe this feature would want some broader discussion or perhaps an RFC behind it before adding, so I'm going to close this.
