### ISSUE TITLE
Rust requires llvm.assume intrinsic and hence LLVM 3.6

### ISSUE THREAD

**Issue by anguslees** [rust-lang/rust#20010]
The rust ./configure LLVM version check is only for 3.[2-6], yet https://github.com/rust-lang/rust/pull/18080 adds a requirement on llvm.assume intrinsic.  This intrinsic only appears in LLVM 3.6.

I think the version check needs to be updated accordingly - or only use the new optimisation intrinsic conditionally on building against newer LLVM.

**Comment by lucab** [comment]
Just as a note, current rust also fails to build against latest (external) stable LLVM 3.5.1 due to a newer EngineBuilder() signature picked-up by rustllvm/ExecutionEngineWrapper.cpp. 
I didn't follow latest discussion about tracking LLVM releases, but I think the timing is good to decide which LLVM releases we want to target with 1.0.

**Comment by lucab** [comment]
Some discussion on this at http://discuss.rust-lang.org/t/targeted-llvm-for-1-0/1371/1. I may give a shot at this if I have some time.

**Comment by tamird** [comment]
Can this be closed now that LLVM 3.5.2 is out?

**Comment by anguslees** [comment]
rustc needs at least LLVM 3.6 rc4 (afaik).

This issue is regarding the LLVM version check in ./configure, which is still 3.[2-6] (and the error message says "bad LLVM version: ... need >=3.0svn".

I believe the ./configure test should be tightened to >=3.6

**Comment by sanxiyn** [comment]
configure check was updated to >=3.5 in #23362 and it is still the case today. Rust successfully bootstraps against LLVM 3.5.2 release now.
