### ISSUE TITLE
Make it possible to stop running #[bench] functions multiple times

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#20142]
`#[bench]` functions are run multiple times. Some benchmark functions might depend on some runtime initialisation which may fail. For example:

``` rust
#[bench]
fn bench_this(b : &mut Bencher) {
    if let Ok(val) = WillFailOnEvenHour::new() {
        b.iter(||{ var.current_hour_is_not_even() });
    } else {
        // nothing to bench here? Maybe print an error?
        println!("Benchmarks on even hours are forbidden!");
    }
}
```

Will print “Benchmarks on even hours are forbidden!” a lot of times. If one opts to not report set-up failure, the benchmark function just keeps processor hot for a while without actually benchmarking anything (and reporting 0ns/iter anyway).

Would it be sensible to (one of possible solutions):
- Not run the same `#[bench]` function multiple times, since iteration is done by `.iter`;
- Not run the same `#[bench]` again if `Bencher::iter` is not called at least once;
- Provide a method on `Bencher` to cancel all subsequent runs of the `#[bench]` function?

Or maybe my approach is incorrect?

**Comment by briansmith** [comment]
For [crypto-bench](https://github.com/briansmith/crypto-bench), we want to run `cargo bench` on the CI infrastructure to ensure all the tests build. However, we don't want to actually benchmark on the CI infrastructure, because the CI infrastructure isn't reliable enough for benchmarking. Thus, doing more than one iteration on the CI infrastructure just wastes time.

And, that time, in particular the wall time, negatively affects my other repos, because generally CI services like Travis CI and Appveyor only allow one project to build at a time, for their free open source tiers.

Further, even out side of CI infrastructure, we want contributors to run the benchmarks before sending PRs. But, it's not reasonable to expect them to wait through many minutes of perf tests before asking for a PR.

Here are three ideas:

1. Add a `--max-seconds n`  that overrides the default targeted benchmark execution time so that we can write `--max-seconds 0` to run tests once. 
2. Add a `--max-iterations n` so we can write `--max-iterations 1`.

I prefer #1 because that also might help with https://github.com/rust-lang/rust/issues/11010.

**Comment by briansmith** [comment]
> or crypto-bench, we want to run cargo bench on the CI infrastructure to ensure all the tests build.

Never mind. I just learned that `cargo test --release` will do exactly what I want: run the benchmarks once each.

**Comment by Craig-Macomber** [comment]
This was bugging me, so I implemented the first proposed option:
> Not run the same #[bench] function multiple times, since iteration is done by .iter;

As this is my first real rust code, I imagine its pretty bad quality. A fist attempt is here: https://github.com/Craig-Macomber/rust/commit/adcb0fc81ec7292a05b02352e8bf4137063098b8

**Comment by gbip** [comment]
Does anyone have an example on how to use this feature ? I'd like to run a benchmark only once.

**Comment by sunjay** [comment]
@gbip [Looks like there is no way.](https://github.com/rust-lang/rust/pull/38779#issuecomment-273379199) :frowning_face:
