### ISSUE TITLE
Multiple globs are basically unusable.

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#20461]
A recent change broke this code:

```rust
use a::*;
use b::*;

mod a { pub fn foo() {} }
mod b { pub fn foo() {} }
```

This gives an error:

```
test.rs:4:5: 4:10 error: a value named `foo` has already been imported in this module
test.rs:4 use b::*;
```

This makes globs *a lot* less useful than they were before. If globs are going to be only useful in isolation, why have them as a feature at all?

**Comment by thestinger** [comment]
Haskell has a hiding clause for imports to avoid this problem. Code using wildcard imports tends to break on upgrades though, and the hiding clause needs to be actively applied to fix the issues.

**Comment by chris-morgan** [comment]
For `pub use` globs, I most certainly wouldn’t want anything else.

For `use` globs, I would really not consider this a bug—some will prefer it one way, others will prefer it another.

**Comment by SiegeLord** [comment]
I'd prefer the overlapping symbols to be automatically hidden or for there to be an option of manually hiding them. The current way it works benefits nobody.

**Comment by nick29581** [comment]
This was part of the shadowing RFC. The benefits are that order of imports are irrelevant, and you don't get weird at-a-distance effects of removing names from a module where that name is hidden. The current policy is for there to be no shadowing at all of any imports, and I think any change to that would need an RFC.

To answer the original question, globs are useful more than just in isolation, but only if there are no duplicate names. If there are duplicate names, then the importer should probably be forced to think about that.

I have a half-finished tool to help with this kind of thing, but progress is slow because of 1.0 priorities.

Closing this issue for now. If anyone thinks this could be improved somehow, you should open an issue on the RFCs repo. (I'm assuming any change would admit more code and therefore would be backwards compatible)
