### ISSUE TITLE
Turn on --disable-debug for distribution?

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#20713]
Currently we do not set this flag on nightly/beta/stable, but with overflow checking it will have a more pronounced, though yet unmeasured, performance impact. Seems like we will likely want to turn off overflow checks in std for distributed binaries.

**Comment by brson** [comment]
Nominating because this could have a big impact on perception.

**Comment by pnkfelix** [comment]
@brson can you clarify: The title makes it sound like you want to literally "turn off --disable-debug"; that's a double-negative that means the same as "leave debug mode on", which would imply leaving in overflow checks.

But the description makes it sound like you actually want to turn off the overflow checks so that the distributed binaries are more performant?

**Comment by brson** [comment]
@pnkfelix Oops. 'off' -> 'on'

**Comment by brson** [comment]
https://github.com/rust-lang/rust/pull/20715

**Comment by nikomatsakis** [comment]
cc https://github.com/rust-lang/rfcs/pull/563

**Comment by pnkfelix** [comment]
@alexcrichton says this is effectively done now.
