### ISSUE TITLE
Playpen links from code snippets on doc.rust-lang.org contain wrong code

### ISSUE THREAD

**Issue by Valloric** [rust-lang/rust#20732]
For example, the code snippet for [`std::str::StrExt::split`](http://doc.rust-lang.org/std/str/trait.StrExt.html#tymethod.split) shows an arrow in the top-right when hovered over with the mouse. The arrow [is a link to the following page](http://play.rust-lang.org/?code=fn%20main()%20%7B%0A%20%20%20%20let%20s%20%3D%20%22Do%20you%20know%20the%20muffin%20man%2C%0A%20%20%20%20The%20muffin%20man%2C%20the%20muffin%20man%2C%20...%22.to_string()%3B%0A%20%20%20%20%0A%20%20%20%20assert_eq!(s.replace(%22muffin%20man%22%2C%20%22little%20lamb%22)%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22Do%20you%20know%20the%20little%20lamb%2C%0A%20%20%20%20The%20little%20lamb%2C%20the%20little%20lamb%2C%20...%22.to_string())%3B%0A%20%20%20%20%0A%20%20%20%20%2F%2F%20not%20found%2C%20so%20no%20change.%0A%20%20%20%20assert_eq!(s.replace(%22cookie%20monster%22%2C%20%22little%20lamb%22)%2C%20s)%3B%0A%7D) with suspicious muffin-related content. This seems to be the snippet for the [`std::str::StrExt::replace`](http://doc.rust-lang.org/std/str/trait.StrExt.html#tymethod.replace) function (which is also the first function on the page with example code). All other code snippets on the page lead to the same muffin code.

This is on Chrome 39.0.2171.95 (64-bit) on Mac OS X 10.10.1.

![muffins](http://i.imgur.com/Vmwc8Mx.png)

**Comment by estsauver** [comment]
It looks like this is caused by rustdoc rendering all of the examples with the same id. 

If you look at the playpen js code in rustdoc: https://github.com/rust-lang/rust/blob/5b3cd3900ceda838f5798c30ab96ceb41f962534/src/librustdoc/html/static/playpen.js

you see that it depends on all the same ids being different. However, if you look at the source of the StrExt example you linked, you see they all have "rust-example-rendered-0" as the id. 

I think the error comes from somewhere in here,

https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/markdown.rs#L196

but it's not obvious to me how to fix it. I'll look into the issue, but this is my first little bit of work on rust so it may take a second/I'd appreciate insight as to what the problem might be.

**Comment by Gankro** [comment]
nominating for I-muffins
