### ISSUE TITLE
Rustc does not to recognize array as a locally defined type.

### ISSUE THREAD

**Issue by georgschoelly** [rust-lang/rust#20742]
I stumbled upon strange behaviour of rustc (1.0.0-nightly 2015-01-06). It seems to treat `[uint; 5]` differently from `[SomeStruct; 5]`.

> the type `[uint; 1]` does not reference any types defined in this crate; only traits defined in the current crate can be implemented for arbitrary types [E0117]

Is this expected behaviour or a bug in the compiler?

#### Code 1 (does not compile):
```rust
use std::default::Default;

type AnArray = [uint; 1];

impl Default for AnArray {
    fn default() -> AnArray {
        [0; 1]
    }
}

fn main() {}
```

#### Code 2 (compiles):

```rust
use std::default::Default;

struct UnitStruct;

type AnArray = [UnitStruct; 1];
    
impl Default for AnArray {
    fn default() -> AnArray {
        [UnitStruct; 1]
    }
}

fn main() {}
```

**Comment by kmcallister** [comment]
The `type` synonym is just a transparent alias, so it has no bearing on this.

It's expected behavior that you can't implement `Default` for `[uint; 1]`, when both are from the standard library. This is part of the "coherence" rules on traits.  One reason for the restriction is that another crate might have a conflicting implementation, and this would cause problems when those crates are used together.
