### ISSUE TITLE
Rust test suite has too many files in one directory

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#20796]
This causes warnings in GitHub code browser. Browsing [src/test/run-pass](https://github.com/rust-lang/rust/tree/master/src/test/run-pass) warns "Sorry, we had to truncate this directory to 1,000 files. 862 entries were omitted from the list."

**Comment by kmcallister** [comment]
They are still findable through GitHub's file finder (press `t` on the main repo page).  I don't think browsing the enormous list online is a compelling use case to justify complicating our directory layout.

**Comment by eddyb** [comment]
@steveklabnik AFAIK, @nikomatsakis has been working on turning the test directories into trees.

**Comment by nikomatsakis** [comment]
We now have the capability to fix it, yes, but I'm not yet sure of the optimal organization. Having subdirectories is good but I've often found also that there are tests which span categories. Using `foo-bar-baz` names allowed me to handle that by having both categories in the name. Nonetheless, it seems obvious that we could start by making directories for the existing groupings, like `regions-*` or whatever.

Longer term I have a strong desire to have things organized such that we can easily answer the question "is there a test covering this scenario"? As far as I am concerned, our test-base right now is effectively "write only". This is however a very challenging problem -- and not one we will be to answer with just file names and directory conventions.

Anyway, a couple of thoughts:

1. I think it is generally speaking **wrong** to have test structure match the compiler's structure. That is, I wouldn't want to have to move tests around just because we made a new crate or something.
2. But having directories for "major passes" in the compiler makes sense to me (privacyck, typeck, borrowck, etc).
3. We should probably move all the `issue-123` tests into a `regression` directory.
4. Only mildly related, but I'd like to merge run-pass and compile-fail into one concept someday. :)

**Comment by alexcrichton** [comment]
I believe compiletest has since been refactored to support subdirectories, so now this is just a PR away from trimming down the number of tests! Since this doesn't seem to actively be causing problems, though, I'm going to close.
