### ISSUE TITLE
ToOwned trait is not imported by default

### ISSUE THREAD

**Issue by bollu** [rust-lang/rust#20867]
Hey, in the rust nightly, it appears that the [ToOwned](http://doc.rust-lang.org/std/borrow/trait.ToOwned.html#tymethod.to_owned) is not imported by default. I think it should be because it seems to be a core language feature.

**Comment by reem** [comment]
If this is going to be The Way to go from &str -> String efficiently then it should be in the prelude. cc @alexcrichton

**Comment by alexcrichton** [comment]
This is currently intentional, and an RFC is required to make changes to the prelude.

As [past experiments have shown](https://gist.github.com/alexcrichton/182ccef5d8c2583a2423) ([RFC](https://github.com/rust-lang/rfcs/blob/master/text/0526-fmt-text-writer.md)) the `to_string` function is ripe for optimization and is pretty reasonable in performance as-is today. The next route for optimization is to add size hints to the `String`/`Show` traits.

Due to the requirement of an RFC to modify the prelude, however, I'm closing this issue.
