### ISSUE TITLE
__MSABI_LONG not declared building LLVM on Windows

### ISSUE THREAD

**Issue by sivadeilra** [rust-lang/rust#20900]
Just pulled and ran configure and make.  Compilation of LLVM fails:

```
llvm[2]: Compiling ErrorHandling.cpp for Release+Asserts build
/c/src/rust/src/llvm/lib/Support/ErrorHandling.cpp: In function ‘std::error_code llvm::mapWindowsError(unsigned int)’:
/c/src/rust/src/llvm/lib/Support/ErrorHandling.cpp:151:21: error: ‘__MSABI_LONG’ was not declared in this scope
     MAP_ERR_TO_COND(ERROR_ACCESS_DENIED, permission_denied);
                     ^
/c/src/rust/src/llvm/lib/Support/ErrorHandling.cpp:146:8: note: in definition of macro ‘MAP_ERR_TO_COND’
   case x:                                                                      \
        ^
```

**Comment by cyderize** [comment]
It appears to be working for me - make sure you've followed the readme or the [wiki](https://github.com/rust-lang/rust/wiki/Note-getting-started-developing-Rust).

I got that same error when accidentally using w32api headers, but it works correctly with x86_64-w64-mingw32 headers (I'm building on 64-bit Windows, BTW).

**Comment by bombless** [comment]
I did not notice that it requires MSYS 32-bit to compile rustc, so I got the same error.
I tried to compile with `MinGW-w64 Win32 Shell` just now then got another error:
```
C:/users/bombless/rust-src/src/llvm/lib/Support/raw_ostream.cpp:40:23: fatal error: sys/uio.h: No such file or directory
 #  include <sys/uio.h>
                       ^
compilation terminated.
```
I guess using MSYS 32-bit to compile is the only solution.
@cyderize Thanks for your comment otherwise it may take me more time to realize the negligence :smiley:

**Comment by cyderize** [comment]
I got that error as well, but then I restarted msys (using mingw64-shell) and it worked afterwards... Very strange behaviour - but I'm glad it works for me, even if I can't figure out why!

**Comment by bombless** [comment]
Yeah I installed a fresh MSYS2, followed  [those instructions](https://github.com/rust-lang/rust/wiki/Note-getting-started-developing-Rust)  and it compiled with on error.
(not really exactly the same commands though because I had to execute `pacman -S mingw-w64-x86_64-toolchain` several times to actually download needed files through my horrible Internet connection)

I guess the key problem for `MinGW-w64 Win64 Shell` is that the header files it use are not fully prepared.

**Comment by vadimcn** [comment]
Looks like this was just due to an old Mingw?  In fact, I don't think we support building Rust with Mingw32 anymore, only with Mingw-w64.

**Comment by bombless** [comment]
I guess it's because the configurate script mixed header files from different versions of gcc.

**Comment by alexcrichton** [comment]
We've updated LLVM a few times in the past few months and I haven't seen this recently, so I'm going to assume this was fixed.

**Comment by cramertj** [comment]
I just got this error when running "make" in MINGW64.

**Comment by valarauca** [comment]
I also get this error while building (in the latest version of msys64 on windows7 x86_64)
