### ISSUE TITLE
Lint for parameters that could be ?SIzed

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#20945]
Generic parameters being `?Sized` is more flexible than them being the default of `Sized`, so we could detect the cases when `?Sized` is likely to work to assist library authors in being as inclusive as possible.

(This likely would've detected https://github.com/rust-lang/rust/pull/20744.)

**Comment by apasel422** [comment]
This would also have detected #29263.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
