### ISSUE TITLE
Include line numbers in backtraces

### ISSUE THREAD

**Issue by gsingh93** [rust-lang/rust#20978]
When a binary compiled with -g `panic`s, and `RUST_BACKTRACE=1`, line numbers should be given along with the backtrace.

**Comment by brooksbp** [comment]
It looks like backtrace_pcinfo() could be used instead of _Unwind_FindEnclosingFunction() + backtrace_syminfo().  I'll attempt it.

**Comment by lifthrasiir** [comment]
I have almost working version of this and am working on a PR. Some caveat I've discovered:

* It will only work in non-Android POSIX as it depends on libgcc *and* libbacktrace.
* We really need `_Unwind_GetIPInfo` instead of `_Unwind_GetIP` to determine if given IP is a non-signaling frame (thus the IP is *after* the calling instruction). GCC 4.2.0 or later has this, so it should be fine, but we need a workaround for non-libgcc paths.
* `backtrace_pcinfo` can be called multiple times for inlined calls. For the convenience I have 32 calls limit right now.
* Macros somehow replaces the file/line information for given frame, which makes a test quite annoying. `panic!()` for example will replace the last user frame with `<std macros>:3` instead of a line invoking the macro. Really an issue at its own.

**Comment by brooksbp** [comment]
I was having difficultly ramping up on Rust's FFI and did not make much progress on this.  @lifthrasiir Looking forward to your work.

**Comment by pornel** [comment]
Oops, I've filed a duplicate #24346, because it doesn't work for me in rustc 1.0.0-nightly (6436e348e 2015-04-08) (built 2015-04-08)
