### ISSUE TITLE
Allow passing plugin arguments through -Z extra-plugins

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#21072]
We may want to tweak the `#[plugin(...)]` arguments feature at the same time.  See also #21043.

**Comment by steveklabnik** [comment]
Triage: I am not 100% sure, but pretty sure there's been no change here.

**Comment by djrenren** [comment]
So I know this issue is really old, but this feature would be incredibly helpful for what I'm working on. (Extracting syntax & cross-reference information from arbitrary codebases so I can't rely on `#[plugin(...)]`) Has anyone thought about what it might take to implement this, and what the primary concerns would be?

**Comment by steveklabnik** [comment]
Triage: same as in 2016

**Comment by Mark-Simulacrum** [comment]
I don't think we want to be expanding plugin scope at all today since they're slated for removal as soon as we get Servo off of them; closing.
