### ISSUE TITLE
Borrow lifetime incorrectly inferred when using generics.

### ISSUE THREAD

**Issue by Nemikolh** [rust-lang/rust#21136]
A couple days ago, it has been reported a [bug in the borrow checker](http://discuss.rust-lang.org/t/borrow-checker-failing-when-providing-trait-object-as-type-parameter). It seems to me that this is more precisely a problem of an incorrect lifetime inferred.

As a memo, this is the reference situation that compiles fine:
```rust
struct NonGenericStruct;

impl NonGenericStruct {
    fn bar(&self, _: &mut Trait) {}
}   

trait Trait{}

struct FooBar;
impl Trait for FooBar{}

fn main() {
    let mut foobar = FooBar;

    {    // No problem when using non generic struct
        let foo = NonGenericStruct;
        foo.bar(&mut foobar);
        foo.bar(&mut foobar);
    }
}
```
And this is the problematic situation where the lifetime of `GenericStruct` is incorrectly inferred:

```rust
struct GenericStruct<T>;

impl <T> GenericStruct<T> {
    fn bar(&self, _: T) {}
}

trait Trait{}

struct FooBar;
impl Trait for FooBar{}

fn main() {
    let mut foobar = FooBar;
    {
        let foo = GenericStruct::<&mut Trait>;
        {   
            foo.bar(&mut foobar);   // First borrow passes ...
        }   
        {   
            foo.bar(&mut foobar);   // This fails as "foobar" is already borrowed
        }
    }
}
```
As you can see the only place using the type T is the function, so the lifetime should be bound to the function call and not the object `foo`.

* Is it a limitation of generic in this context ?
* Does that mean that the user has no other option than using a macro here  to emulate the template code generation?
(That seems a bit odd IMO. It would partially solves the case and make the type `GenericStruct` really hard to use)

**Comment by bombless** [comment]
```Rust
struct GenericStruct<T: ?Sized>;

impl <T: ?Sized> GenericStruct<T> {
    fn bar(&self, _: &mut T) {}
}

trait Trait{}

struct FooBar;
impl Trait for FooBar{}

fn main() {
    let mut foobar = FooBar;
    {
        let foo = GenericStruct::<Trait>;
        foo.bar(&mut foobar);   // First borrow passes ...
        foo.bar(&mut foobar);   // Second borrow
    }
}
```
Maybe this one is a better idea.

**Comment by Nemikolh** [comment]
This one is a better idea and is a solution to my examples.

However I do believe there's a problem here.
I just don't think anymore that it is "Lifetime" related.

Why would this code compile fines:
```rust
struct GenericStruct<T>;

impl <T> GenericStruct<T> {
    fn bar(&self, _: &mut T) {}
}

struct FooBar;

fn main() {
    let mut foobar = FooBar;
    let foo = GenericStruct;
    foo.bar(&mut foobar);   // First borrow passes ...
    foo.bar(&mut foobar);   // Second borrow
}
```
while this one does not:
```rust
struct GenericStruct<T>;

impl <T> GenericStruct<T> {
    fn bar(&self, _: T) {}
}

struct FooBar;

fn main() {
    let mut foobar = FooBar;
    let foo = GenericStruct;
    foo.bar(&mut foobar);   // First borrow passes ...
    foo.bar(&mut foobar);   // Second borrow
}
```

The only difference is the **&mut** added to the type T to the function bar.
It seems to me that the borrow checker or a part of the parser is annotating the AST wrongly, resulting in this strange behavior.

Whatever in the compiler does this, it does it very strangely.

**Comment by bombless** [comment]
I don't know but with simple `T` you can hardly do any thing, that said, you can not even tell whether `T` is some kind of `&mut U`, `&U`, or if methods related to `GenericStruct` can copy `T` or something. And at the compiler's view the lack of bounds also makes it know little of GenericStruct.
And the fact that GenericStruct is defined in the same crate doesn't help at all since the compiler only check the conditions on bounds, it won't look deep into that `GenericStruct` too see what exactly happended, otherwise it is a failure of the language design, because it either make Rust unsafe or can only tell if the generic method is safe by checking those who actually calles it, that will be as bad as C++ templates, in which case should be avoided.

So I don't really see the point here.


Maybe give `T` some bounds and play with both `&mut` and `&`  types will better show your idea.

Though I do believe that Rust prevents some codes which actually do no harm.
And personally I think it can be considered as a way to adapt future extension of the language.

By the way have you tried `std::any::Any`? I have feelings that it may solve some of your problems. I don't know, but if it doesn't, just take it as another blue sky thinking of mine.

At last, maybe these words is just bullshit for a Rust expert. If this make anyone bad please let me know, I will delete this comment.

And maybe this comment should not appear in this kind of issue, let me know as well in that case.

**Comment by Nemikolh** [comment]
> I don't know but with simple T you can hardly do any thing

That's right but I kept the examples as simple as possible.

> it won't look deep into that GenericStruct to see what exactly happended, otherwise it is a failure of the language design, because it either make Rust unsafe or can only tell if the generic method is safe by checking those who actually calls it, that will be as bad as C++ templates, in which case should be avoided.

I do understand your point, but I don't understand how this relate to the *borrow* part. 

> Maybe give T some bounds and play with both &mut and & types will better show your idea.

Bounds are not contributing to the borrow scope, aren't they ?

## To be clear

* The problem I'm talking about here is a *borrow lifetime* problem not an *object lifetime* problem.

 (you didn't mention that but I wanted to be sure everyone understand)
* As far as I know, in the example B `foobar` should be borrow only for the duration of `bar`

## Problem

The part I don't understand is why when the compiler see
```rust
foo.bar(&mut foobar);
```
It does infers different borrow scopes for the example A and B I've given. 

If you play with scope, you'll see in the example that 
* `foobar` is borrowed for the *object lifetime* duration of `foo`.
* `foo` is immutable, so can't possibly without writing unsafe code borrow `foobar` for more than the duration of the call to `bar`

**Comment by Nemikolh** [comment]
Closing the issue as now we have to use explicitly `PhantomData` to use a type parameter on a GenericStruct (which is a good thing).

The updated examples would look like:
```rust
use std::marker::PhantomData;

struct GenericStruct<T> {
    marker: PhantomData<T>
}

impl <T> GenericStruct<T> {
    // or fn bar(&self, _: &mut T) {}
    fn bar(&self, _: T) {}                   // <--- Only change
}

struct FooBar;

fn main() {
    let mut foobar = FooBar;
    let foo = GenericStruct { marker: PhantomData };
    foo.bar(&mut foobar);
    foo.bar(&mut foobar);
}
```

And both compiles.
