### ISSUE TITLE
We should forbid type parameters from shadowing other types

### ISSUE THREAD

**Issue by erickt** [rust-lang/rust#21301]
This is a weird case that we should probably not allow:

```rust
mod T {
    pub type Type = i32;
}

trait Trait {
    type Type;
}

impl Trait for i32 {
    type Type = i8;
}

struct Baz<T: Trait> {
    a: T::Type,
}

fn main() {
    let x: Baz<i32> = Baz { a: 0i8 };
}
```

The rule appears to be that the `<T: Trait>` has precedence over the module, it would be easiest if we just errored out in this circumstance.

**Comment by kmcallister** [comment]
Nominating (back compat)

**Comment by kmcallister** [comment]
(Though adding a lint would be back-compat, aiui)

**Comment by nikomatsakis** [comment]
I for one am not convinced we should disallow this. We disallow type parameters from shadowing one another specifically because it came up very frequently. This seems less likely to arise frequently (it relies on not following our suggested naming conventions for type parameters and modules, for one thing).

**Comment by nikomatsakis** [comment]
(Even if it did come up frequently, I'd probably rather just work on the error messages that result.)
