### ISSUE TITLE
StaticSemaphore and SEMAPHORE_INIT missing from std::sync?

### ISSUE THREAD

**Issue by aldanor** [rust-lang/rust#21416]
`Mutex` -> `StaticMutex`, `MUTEX_INIT`
`Condvar` -> `StaticCondvar`, `CONDVAR_INIT`
`RwLock` -> `StaticRwLock`, `RWLOCK_INIT`

Should there be a static initializer for semaphores too (with count = 0?) and an associated static type? (unless they are missing from `std::sync` on purpose)

**Comment by alexcrichton** [comment]
Currently a static semaphore is unimplemented because it would ideally take an input for the initial count rather than defaulting to 0. The constructors of mutexes, condvars, and rwlocks somewhat take less of an argument (synchronization beyond protecting data is still important).

Note, however, that the static variants and initializers are all unstable (and will likely remain so). When we sort out our story for static initialization I suspect we'll deal with static semaphores at the same time. As a result, I'm going to close this for now. Thanks for the issue though!
