### ISSUE TITLE
Naming of mut_/_mut is inconsistent

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#21415]
I don't get rules around `mut` prefix/suffix naming, if there are any. When I try to guess where `_mut_` will be in a method name, I most often get it wrong.

There's `.as_mut_ptr()`, but there's also `ptr::null_mut()`. Shouldn't one of them be `ptr::mut_null()` or `.as_ptr_mut()`?

There's plenty of prefix methods `as_mut_something()`, e.g. `.as_mut_slice()`, but there's also suffix `.get_mut`, `.iter_mut()` and [`.last_mut`](http://doc.rust-lang.org/collections/slice/trait.SliceExt.html#tymethod.last_mut). Then why not `.as_something_mut()`? (like [`.mut_edge_data`](http://doc.rust-lang.org/rustc/middle/graph/struct.Graph.html#method.mut_edge_data))

**Comment by huonw** [comment]
cc @aturon

**Comment by P1start** [comment]
These naming conventions came from [RFC 344](https://github.com/rust-lang/rfcs/blob/master/text/0344-conventions-galore.md#referring-to-types-in-method-names). Basically, mutable versions of methods always end in `_mut`. The reason why `as_mut_ptr` and `as_mut_slice` are so named is because `mut_ptr` and `mut_slice` are single ‘units’, i.e., they mean ‘mutable pointer’ and ‘mutable slice’. To put it another way: converting methods are usually of the form `as_<something>`, where `<something>` is the type being converted to; so to name a method that converts something to a mutable slice, `<something>` is `mut_slice`. (It could be `slice_mut`, but that reads less naturally than `mut_slice`.)

**Comment by Gankro** [comment]
Honestly I've grown to feel that unconditional `_mut` would be easier to deal with than having to ask "is `mut` part of the type here?" 

Although I'm sure there are degenerate cases to worry about.

**Comment by steveklabnik** [comment]
@P1start has a good answer here. In general, name conventions go through the RFC process, and so this should really go on the RFC repo, if anything.
