### ISSUE TITLE
In some situations, type of a match expression is tried to resolve as () like a match statement.

### ISSUE THREAD

**Issue by Kroisse** [rust-lang/rust#21425]
[Example](http://is.gd/Nj7hSr)

```rust
fn check1() -> bool {
    let a = match 42 { _ => true };
    a && true
}

fn check2() -> bool {
    (match 42 { _ => true } && true)
}

fn check3() -> bool {
    match 42 { _ => true } && true  // problematic
}

fn check4() -> bool {
    true && match 42 { _ => true }
}

fn main() {}
```

Result:
```
<anon>:11:5: 11:27 error: mismatched types:
 expected `()`,
    found `bool`
(expected (),
    found bool)
<anon>:11     match 42 { _ => true } && true
              ^~~~~~~~~~~~~~~~~~~~~~
<anon>:11:28: 11:35 error: mismatched types:
 expected `bool`,
    found `&&bool`
(expected bool,
    found &-ptr)
<anon>:11     match 42 { _ => true } && true
                                     ^~~~~~~
error: aborting due to 2 previous errors
```

Using parenthesis (see `check2()`) can solve it. swapping both operands (`check4()`) also does.

I'm not sure it's a syntax ambiguity, or an issue that can be resolved.

**Comment by alexcrichton** [comment]
This is actually working as intended due to the way we parse statements and expressions. In a statement context we'll parse the match statement early on and then look for an expression afterwards, so the problematic case above fails to parse. In all other situations we know we're parsing an expression so we can look for `&&` afterwards. As this is working as intended, though, I'm going to close.
