### ISSUE TITLE
Missing play.rust-lang.org links in TRPL book

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust#21553]
http://doc.rust-lang.org/book/ is supposed to "run these examples on play.rust-lang.org by clicking on the arrow that appears in the upper right of the example when you mouse over the code" but these arrows don't seem to appear in any of the code samples.

**Comment by steveklabnik** [comment]
My understanding is that `rustdoc` should be adding these, unsure why it's not.

**Comment by jatinn** [comment]
Looked into this and saw a few things incase anyone else is looking into it.

1. ```"--markdown-playground-url=http://play.rust-lang.org".to_string(),``` is missing from the `rustdoc_args` in `src/rustbook/build.rs`. Adding this however does not get it to work because of the next items.

2. The template used to render the rustbook is from `src/librustdoc/markdown.rs` where as for the documentation it is in `src/librustdoc/html/layout.rs`. This is important as the template in `layout.rs` includes the `playpen.js`.

3. I tried to include `playpen.js` into the output but this still did not work, it is missing the tag from which it gets the code. This seems to be because ```s.push_str(&format!("<span class='rusttest'>{}</span>", Escape(&test)));``` line does not get executed in `src/librustdoc/html/markdown.rs`

Hope this helps.
