### ISSUE TITLE
Regression in integer fallback

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#21595]
This code compiled fine before 1.0.0-nightly (4be79d6ac 2015-01-23 16:08:14 +0000):

```rust
fn main()
{
	for i in 0..100
	{
		i as f32;
	}
}
```

But with that version, it now gives this error:

```
<anon>:5:3: 5:11 error: the type of this value must be known in this context
<anon>:5 		i as f32;
         		^~~~~~~~
```

**Comment by emanueLczirai** [comment]
changing `0` to `0u32` should work, I stumbled upon the same thing and the doc seems to be updated: http://doc.rust-lang.org/book/looping.html (see at the very bottom)

**Comment by SiegeLord** [comment]
That's just a workaround to a bug (not sure if that was implied). `i` should fall back to being `i32` as per the existence of the integer fallback.

**Comment by nikomatsakis** [comment]
I don't necessarily expect this to work. Fallback comes late in the progress, once all constraints are known, but `as` (like method dispatch) requires the type being cast to be known immediately.

**Comment by nikomatsakis** [comment]
It's plausible we could make it work since we know that the type is integral (I imagine that's how it ever worked, not sure what would have changed that, though it might have been something I did). It occurs to me though that this is somewhat forward-hostile to the idea of integer literals ever being used for anything other than plain ints (but enabling such a feature may well wind up requiring opt-in anyway).

**Comment by nikomatsakis** [comment]
(Though really it's sort of silly that `as` requires the type to be known immediately, so I guess fixing *that* would be another way to ease the forward compat fears.)

**Comment by emanueLczirai** [comment]
I thought this was a feature because it's saying that it doesn't know if it's `u32` or `i32` for example. Would it assume it's unsigned only if it contains negative numbers in the range?

But I might be missing something because this doesn't output anything from `for`:
```
fn main() {
  for i in -1u32..3 {
    if i % 2 == 0 {
      print!("*");
    }
    print!("{}",i);
  }
  println!("");
}
```

```
$ rustc main.rs && ./main 
main.rs:2:12: 2:17 warning: negation of unsigned int literal may be unintentional, #[warn(unsigned_negation)] on by default
main.rs:2   for i in -1u32..3 {
                     ^~~~~

```
There's no output from `for`, unless using `-1i32`
