### ISSUE TITLE
Impl reachability rules bug?

### ISSUE THREAD

**Issue by vadimcn** [rust-lang/rust#21687]
```rust
use std::default::Default;

trait AAA {}
trait BBB<T> {}
struct SSS<T>(T);

impl<T,U> AAA for SSS<T> where T:BBB<U>, U:Default {}
```
```
<anon>:7:8: 7:9 error: the type parameter `U` is not constrained by the impl trait, self type, or predicates [E0207]
<anon>:7 impl<T,U> AAA for SSS<T> where T:BBB<U>, U:Default {}
                ^
<anon>:7:8: 7:9 help: you can temporarily opt out of this rule by placing the `#[old_impl_check]` attribute on the impl
<anon>:7 impl<T,U> AAA for SSS<T> where T:BBB<U>, U:Default {}
                ^
```
I don't understand why I get the error, since U *is* constrained by the where predicate.

**Comment by japaric** [comment]
cc @nikomatsakis

**Comment by nikomatsakis** [comment]
Where predicates do not count as a constraint of `U` unless `U` appears in an associated type binding. The point is that, at various points, the compiler is presented the trait reference (`AAA for SSS<T>`) and asked to derive everything else from the impl -- in order to pick the impl of `BBB<U> for T`, it would have to know the value of `U`, which it doesn't. Short of that, it must infer -- but infer from what? The set of impls that exist is not a realiable thing to infer from, since as more crates are written and linke in, that set will grow.

**Comment by nikomatsakis** [comment]
Closing because this test is working as expected.

**Comment by vadimcn** [comment]
So is there a way to encode "I want `AAA` to be implemented for instances of generic type `SSS<T>`, if `T` implements `BBB<U>` and `U` implements `Default`" ?

**Comment by Diggsey** [comment]
@vadimcn Did you ever find a way to do this?

**Comment by nikomatsakis** [comment]
@vadimcn sorry, I missed your question -- the answer is that no, there is no way to encode that, because the question is potentially ambiguous. What if `T` implements `BBB<U>` for multiple `U` -- how is the compiler to choose which impl you wanted?

However, you can ask a slightly different question, where `AAA<U>` is implemented for instances of generic type `SSS<T>` if T: BBB<U>` and `U: Default`.

**Comment by nikomatsakis** [comment]
The other option is to make the `U` in `BBB` an associated type.
