### ISSUE TITLE
Consider closure autoref

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#21699]
We could have a `||` expression expand to `&F` or `&mut F` where `F : Fn()` (`FnMut`, etc), and not just `F`. This would make it easier to write code that accepted boxed closures:

```rust
fn foo(x: &mut FnMut()) { ... }
foo(|| ...)
```

whereas today it is required to write:

```rust
foo(&mut || ...)
```

This seems like a pretty small delta and might go a long way towards improving ergonomic impact of the new closure design.

**Comment by nikomatsakis** [comment]
Nominating for beta.

**Comment by nikomatsakis** [comment]
cc @aturon

**Comment by japaric** [comment]
(Assume that `impl<F: ?Sized> FnMut for &mut F where F: FnMut` is in the stdlib)

If you have a function `fn foo<F: FnMut>(_: F)` and you call `foo(|| { .. })`, would the compiler *prefer* to pass the unboxed closure by value? Because it could pass either `F` or `&mut F` (or even &mut FnMut) in this case, right?

**Comment by nikomatsakis** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/pull/756

**Comment by nikomatsakis** [comment]
@japaric I'll answer your question over in the RFC
