### ISSUE TITLE
Warn when division of integer literals has a remainder

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#21737]
fn main() {
        println!("{}", 1/2 * 30)
    }

I've been bitten by this in many programming languages. It would be nice to avoid having Rust be one of them :)

**Comment by steveklabnik** [comment]
I'm not sure how you'd be able to do this without evaluating arbitrary things at compile time...

**Comment by reem** [comment]
@steveklabnik He wants this only for literals, and we already have static evaluation of basic arithmetic.

**Comment by hirschenberger** [comment]
I have a patch, but what is the desired behaviour? Should we enforce casting to float and back if integer division is intended?

With my patch, I get an error when campiling duration.rs:

```
rust/src/libstd/time/duration.rs:58     secs: i64::MIN / MILLIS_PER_SEC - 1
```

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
