### ISSUE TITLE
Expose begin_unwind somewhere besides libstd

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#21880]
It used to be in librustrt but that's gone now.  This is currently blocking my ability to enable `derive(Rand)` and `derive(Rustc{En,De}codable)` for no-std crates.

**Comment by Gankro** [comment]
CC @aturon was this intended?

**Comment by aturon** [comment]
We haven't had a great stabilization story for this usage, and this was a byproduct of moving rustrt into std.

It should be easy enough to expose something on an experimental basis, but will take more thought to develop a long-term, stable design.

@kmcallister If you wanted to make a PR just making this stuff public under `std::rt`, I'd be open to that.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Due to recent changes to stability lints we now have two stable functions: 

* http://doc.rust-lang.org/std/rt/unwind/fn.begin_unwind.html
* http://doc.rust-lang.org/std/rt/unwind/fn.begin_unwind_fmt.html

I believe, however, that the motivation for this issue is to mirror the same structure in libstd as it is in libcore to allow `#[macro_reexport]` in the standard library. Both these deriving modes, however, rely on libraries that depend on the standard library, so I'm not sure how much more relevant the motivation is any more.

**Comment by steveklabnik** [comment]
begin_unwind is gone entirely, and i believe that panic handlers cover this use-case today. Is this still a valid bug?

**Comment by alexcrichton** [comment]
Nah I don't think this is valid any more
