### ISSUE TITLE
Parallel `make check` doesn't run in the right order

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#22021]
I ran `make check -j7`, and some of the tests were failing because the `syntax` and `rustc` libs in `$target/stage2/lib/rustlib/....../lib/` hadn't been built yet.

I guess the makefile needs some tweaks?

**Comment by kmcallister** [comment]
I've seen this too.  I usually do `make -j8 all && make check` but it'd be great if this worked.

**Comment by Manishearth** [comment]
This seems to be specific to the pretty tests. Goes away with `make rustc-stage2 && make check-stage2`, so I assume a make dep is missing.

**Comment by pnkfelix** [comment]
cc me

**Comment by rprichard** [comment]
@pnkfelix AFAICT, the `PRETTY_DEPS$(1)_H_$(3)_pretty-...` definitions in [this commit](https://github.com/rust-lang/rust/commit/b26972e28bfc1b797e2dfa14435b551685cb180b) are not defining the expected variables, because the definitions are outside any function, so $(1) and $(3) expand to nothing.

`make -pn` shows this line:
```
PRETTY_DEPS_H__pretty-rpass-full = $$(HLIB$(1)_H_$(3))/stamp.syntax $$(HLIB$(1)_H_$(3))/stamp.rustc
```

I'll work on a fix.

**Comment by rprichard** [comment]
@pnkfelix Do you have a preference on how to fix the `run-make/simd-ffi` test with parallel `make check`?

I have a fix now, but it's not successfully tested.

Parallel `make check` now fails because the `run-make/simd-ffi` test is run in parallel, and it has multiple phony targets that generate the same output file.  I think it's easy to fix that test.  Alternatively, we could disable parallelism for `run-make` tests by modifying `src/etc/maketest.py` somehow: (1) add `-j 1` to the command-line or (2) filter/clear `MAKEFLAGS`.  I'm leaning towards `-j 1` if we want to disable parallelism.  I think we require GNU make, so I would think `-j 1` wouldn't break anything.

**Comment by rprichard** [comment]
I fixed `run-make/simd-ffi`.  I'll leave `maketest.py` alone for now.
