### ISSUE TITLE
Silently fail when adding int and usize within a for loop

### ISSUE THREAD

**Issue by compmstr** [rust-lang/rust#22155]
Nothing is output from this, but it compiles/runs

    let x: usize = 5;
    for dx in -1..2 {
      println("{}", dx + x);
    }

When I do:

    ((dx as int) + x) as usize

it works fine, but there is no error or message other than the 'using core' warning with the original code.

**Comment by nagisa** [comment]
What’s the `dx`?

**Comment by compmstr** [comment]
Sorry, fixed/edited, it was the loop varriable

**Comment by nagisa** [comment]
The behaviour is expected then: 
* `dx` is inferred to have usize because you’re adding yet unknown type with an usize → 
* `-1..2` must yield elements of type usize, therefore it must be `Range<usize>` → 
* infers starting end ending indexes to `-1us..2us` → 
* `-1us` is a very big number (such as 18446744073709551615 on 64 bit systems) → 
* range is actually `<a very big number>..2` → 
* this range has no elements, because first index is bigger than the second one → 
* no iterations are executed →
* nothing is printed.

**Comment by alexchandel** [comment]
A `negative signed->unsigned` implicit cast is often desired.

But there should be a lint for every interpretation of a negative literal as an unsigned variable.

**Comment by steveklabnik** [comment]
Yes, this is currently 'working as intended', though it could be improved with the change in intenrals.

**Comment by compmstr** [comment]
That makes sense.  A message that this is happening would make it a lot clearer.
