### ISSUE TITLE
Result for search term "term::stdout" in Rust docs (std) is a link to a non-existent page (404)

### ISSUE THREAD

**Issue by doomrobo** [rust-lang/rust#22168]
Entering the above search term or just going [here](http://doc.rust-lang.org/std/?search=term%3A%3Astdout) and clicking the first (and only) search result leads you to a Github Pages 404 page.

Note that [this](http://doc.rust-lang.org/term/term/fn.stdout.html) link works just fine.

**Comment by tomjakubowski** [comment]
If you search from the "nightly" docs at http://doc.rust-lang.org/nightly/std/?search=term%3A%3Astdout the correct URL is returned.

I'm pretty sure this isn't a rustdoc bug. It might be caused by something like a stale search index, which in turn may have been caused by rebuilding the std docs in a previously used directory without cleaning. 

More evidence: on http://doc.rust-lang.org/std/ there is a link on the sidebar to the `term` crate at `../term/index.html`. This is a placeholder page that just has a redirect to the canonical location for that crate's docs, at <http://doc.rust-lang.org/term/term/index.html>.

**Comment by tomjakubowski** [comment]
cc #20096 and @alexcrichton

**Comment by alexcrichton** [comment]
This problem is actually a little more subtle! The search index contains information about the in-tree `term` crate, but the `doc.rust-lang.org/term` url actually refers to the external `term` crate (we have a redirection rule locally). As a result the in-tree link (when browsing `doc.rust-lang.org/std`) is incorrect, but when browsing `/nightly/std` it's correct. 

We shouldn't be generating this documentation regardless, however so I'm going to solve it that way :)

**Comment by SimonSapin** [comment]
@alexcrichton This issue was marked closed in ed276caeec64033f38a18dbe796dc78ce3c57c6a, but I can still reproduce it though the steps in the original message.

**Comment by steveklabnik** [comment]
I can too

**Comment by doomrobo** [comment]
No longer reproducible
