### ISSUE TITLE
Make Rust work with emscripten

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#2235]
I've spent some time poking at this problem and rustc now generates code that emscripten can translate, but the compiled javascript fails when it hits a runtime function. The next step is to start building the runtime using `emcc` as the compiler. Stub out all the things that don't build behind `EMSCRIPTEN` ifdefs.

Emscripten is adding a way to treat inline assembly as javascript, so all the parts of the runtime that don't build with emscripten can be implemented inline with javascript.

Alternately, we could reimplement the runtime piecemeal in javascript and not bother compiling it from C++ at all. This approach isn't recommended.

**Comment by ibdknox** [comment]
As an update, when I compile hello world with emscripten that has now been updated to 3.5, I'm getting the following:

```
Value:   %28 = call fastcc { i8, [0 x i8], [0 x i8] } @_ZN3fmt5write20h2c56fdda0b308d94DFAE({ i8*, void (i8*)** }* noalias nocapture dereferenceable(8) %arg.i, %"struct.core::fmt::Arguments[#3]"* noalias nocapture readonly dereferenceable(24) %__args31), !noalias !22
LLVM ERROR: Unrecognized struct value
Traceback (most recent call last):
  File "/Users/chris/Downloads/emsdk_portable/emscripten/incoming/emcc", line 1259, in <module>
    shared.Building.llvm_opt(final, link_opts)
  File "/Users/chris/Downloads/emsdk_portable/emscripten/incoming/tools/shared.py", line 1401, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations:
```

Here's how I'm compiling:

```
rustc --target i686-apple-darwin -C lto --emit ir foo.rust
emcc -v foo.ll -o test.html
```

Things that don't seem to bring in fmt generally seem to work, though.

**Comment by mzgoddard** [comment]
I've been spending my free time this last week looking into this.  I read rust's book sometime between the summer and now and really liked the mechanics of the language but only recently started implementing something with it. I'm only as knowledgable about the rust compiler of what I learned this week but hope I can contribute.

So I guess the first thing to note of what I learned (but that took me a few evenings to notice) is that Rust moved to LLVM 3.6 in July. So the current versions of Rust and emscripten-fastcomp are incompatible.

I tried compiling rust with --llvm-root pointing to emscripten-fastcomp 1.29.2 and got this error:

```
rustc: x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/libcore
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: self.raw.hash != self.hashes_end', /Users/zen/Code/rust/src/libstd/collections/hash/table.rs:776


make: *** [x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/stamp.core] Error 101
```

To get to this error I configured and built emscripten-fastcomp with

```shell
```

Once I found that Rust had moved to LLVM 3.6 I looked up the last branch on rust-lang/llvm that was LLVM 3.5

**Comment by mzgoddard** [comment]
I've been spending my free time this last week looking into this.  I read rust's book sometime between the summer and now and really liked the mechanics of the language but only recently started implementing something with it. I'm only as knowledgable about the rust compiler as to what I learned this week but hope I can contribute.

So I guess the first thing to note of what I learned (but that took me a few evenings to notice) is that Rust moved to LLVM 3.6 in July. So the current versions of Rust and emscripten-fastcomp are incompatible.

I tried compiling rust with --llvm-root pointing to emscripten-fastcomp 1.29.2 and got this error:

```
rustc: x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/libcore
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: self.raw.hash != self.hashes_end', /Users/zen/Code/rust/src/libstd/collections/hash/table.rs:776


make: *** [x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/stamp.core] Error 101
```

To get to this error I configured and built emscripten-fastcomp with

```sh
../configure --enable-optimized --disable-assertions --enable-targets=host,js,arm,aarch64,mips
```

Instead of the recommended

```sh
../configure --enable-optimized --disable-assertions --enable-targets=host,js
```

Though Rust doesn't need to be built for all targets, it currently always links against LLVM with CPU support compiled for all targets. This is a workaround for a problem that could be fixed in the future so we may not need to always compile emscripten-fastcomp with that configuration.

Once I found that Rust had moved to LLVM 3.6 I looked up the last branch on rust-lang/llvm that was LLVM 3.5. https://github.com/rust-lang/llvm/tree/rust-llvm-2014-07-24 I compiled against that instead of emscripten-fastcomp, curious to see what would turn out. I got the same exact error when compiling against emscripton-fastcomp recent move to LLVM 3.5. I take this to mean that Rust is in some way incompatible with LLVM 3.5 now and I wouldn't really expect otherwise.

So now we wait or have to get emscripten-fastcomp to LLVM 3.6 :wink:

Its worth mentioning that I downloaded an archived 0.11 copy and was able to produce LLVM IR for hello world that `emcc` understood but then reached the problem of linking. It was pretty exciting to see it get past understanding the byte code but actually getting it linking is going to need work in the rust code base.

I took a peek at merging rust-lang/llvm into emscripten-fastcomp. At the time there 117 conflicting sections over 43 files.

I mentioned getting Rust 0.11 and emcc 1.29.2 to get to the linking stage. This is the specific result:

```sh
$ emcc -v hello.ll -o hello.js
INFO     root: (Emscripten: Running sanity checks)
WARNING: Linking two modules of different data layouts: '/Users/zen/.emscripten_cache/libc.bc' is 'e-p:32:32-i64:64-v128:32:128-n32-S128' whereas '/tmp/tmpv_yB8E/hello_0.o' is 'e-p:32:32-f64:32:64-f80:128-n8:16:32'
WARNING: Linking two modules of different target triples: /Users/zen/.emscripten_cache/libc.bc' is 'asmjs-unknown-emscripten' whereas '/tmp/tmpv_yB8E/hello_0.o' is 'i686-apple-darwin'
warning: incorrect target triple 'i686-apple-darwin' (did you use emcc/em++ on all source files and not clang directly?)
warning: unresolved symbol: _ZN2io5stdio12println_args20h0caae70b0e2eb347Iol7v0_11_0E
warning: unresolved symbol: _ZN10lang_start20h70f93b7d0a75f99atre7v0_11_0E
```

Seems emcc/fastcomp replaces dots in symbols with underscores while Rust expects to prefix with another underscore but I'm not too sure about this. The first unresolved symbol appears as __ZN2io5stdio12println_args20h0caae70b0e2eb347Iol7v0.11.0E in libstd in the i686-apple-darwin. Even if I could get emcc to know how to find this symbol in the built libraries, I'm guessing that the libs contain machine code while emcc will need LLVM byte codes. I think I recall someone mentioning needing to compile the standard library for emscripten. This would be part of the need for that.

So here are the next steps I'm looking to try and work on if anyone wants to take a shot at them themselves. (Or can let me know how right or wrong I am.)

- Merge rust-lang/llvm into emscripten-fastcomp
- Build rust with merged fastcomp without JS backend support
- Add emscripten's triple to Rust and build it
- Implement missing system interfaces

**Comment by aidanhs** [comment]
"Merge rust-lang/llvm into emscripten-fastcomp"

You might now want to do this - Emscripten is based on pnacl-llvm/pnacl-clang so you're creating a fork with patches on patches, which will probably be painful. If you're interested, you can see some detail of the branching in the investigation I did for the Emscripten merge from r33 -> r34 at https://github.com/kripken/emscripten-fastcomp/issues/51#issuecomment-62323164.

I hear that pnacl is planning on tracking upstream a bit closer than before but I can't see any relevant issue in the pnacl issue tracker so it may be a while...I guess you could create an issue? If you decide against your own Emscripten fork, I see two options - waiting for pnacl or helping Emscripten get off pnacl and onto upstream.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#604
