### ISSUE TITLE
Has unsafe_destructor landed? It's still needed.

### ISSUE THREAD

**Issue by diwic** [rust-lang/rust#22362]
According to rust-lang's [latest blog post](http://blog.rust-lang.org/2015/02/13/Final-1.0-timeline.html), the unsafe_destructor reform has landed, so I should not need to use unsafe_destructor. But still, with Rust nightly (2015-02-13 21:15:39) I still get an error for simple cases like this: 

    struct B<'a> {
       z: &'a str,
    }
    
    impl<'a> Drop for B<'a> {
       fn drop(&mut self) {
           println!("{}", self.z);
       }
    }

**Comment by tomjakubowski** [comment]
The blog post was a little misleading; the RFC landed but not the changes to the compiler.

The specific issue for removing `#[unsafe_destructor]` is #22196

**Comment by steveklabnik** [comment]
This is what I thought, but wasn't sure. Thanks tom!

**Comment by pnkfelix** [comment]
To be precise (and also accurate):
 * The analysis that supports the removal of `#[unsafe_destructor]` has landed in the compiler, and is applied to *all* destructors (including those that currently use the `#[unsafe_destructor]` attribute.
 * but
 * until we gain more confidence in the results, we are still requiring the use of the `#[unsafe_destructor]` attribute to implement `Drop` on generic types.

The is what #22196 is meant to convey, but the phrase "but not the changes to the compiler" in @tomjakubowski I thought might be a little confusing to people, since the vast bulk of the necessary changes to the compiler have not only landed, but are also turned on!

**Comment by diwic** [comment]
Ok, that makes sense! Thanks for the clarification.
