### ISSUE TITLE
std::fs::create_dir* should take permissions

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#22415]
The new `fs` module does not provide a way to create a directly with given permissions, which is especially painful for `create_dir_all`. It should.

The [RFC](https://github.com/rust-lang/rfcs/blob/e21c3726aaf410f865d306e8984b4781c6f371ac/text/0517-io-os-reform.md) specified that these functions should resemble those in `old_io` except for a generic bound, so it's not clear why the permission argument was droppped.

**Comment by aturon** [comment]
cc @alexcrichton @mahkoh

**Comment by nagisa** [comment]
We can create a `File` with provided permissions via `OpenOptions`. I suggest extending this struct to also provide a method to create a directory.

**Comment by aturon** [comment]
@nagisa Hm, but the problem is that methods like `create_dir_all` are convenience which actually create a whole host of directories. The old API just took a permissions argument; why not do so here?

**Comment by nagisa** [comment]
If I remember correctly there was a lot of discussion regarding Permissions, because they are not quite supported on Windows and should only be exposed as an extension in respective sys modules.

**Comment by nagisa** [comment]
This is a [relevant comment thread](https://github.com/rust-lang/rfcs/pull/517#discussion_r21760618)

**Comment by aturon** [comment]
@nagisa Oh yes, this was definitely a big part of the RFC effort.But the result was that we *have* permissions, we just don't expose very much of them at the `std::fs` level. 

That is, the `Permissions` structure is pretty opaque -- but we absolutely can use it in a cross-platform way, and platform-specific extensions allow to to interact with it in a richer way.

**Comment by aturon** [comment]
Nominating for 1.0-beta P-backcompat-libs.

**Comment by mahkoh** [comment]
It seems that both `Permissions` and `OpenOptions` is unusable right now. There is no way to cross-platform create files that are not-world-readable/writable or executable.

I've checked Go and Python (and C via mingw) and neither of those seem to have this problem.

This seems to be a serious oversight in the RFC.

**Comment by alexcrichton** [comment]
@mahkoh you can't really compare to what other languages do because they all ignore the mode argument on windows (at least from what I've found). For example here's the source for [Go](http://golang.org/src/syscall/syscall_windows.go#L377) and [Python](https://github.com/python-git/python/blob/715a6e5035bb21ac49382772076ec4c630d6e960/Modules/posixmodule.c#L2446-L2462).

I also encourage you to be a little more specific instead of saying that the structures are "unusable right now". When you say "there is no way to cross-platform create files that are not-world-readable/writable or executable" it's because there isn't one in the manner of permission bits on posix. I would also encourage you to explore the [`std::os::unix`](http://doc.rust-lang.org/std/os/unix/) module to see that you can [set the mode on `Permissions`](http://doc.rust-lang.org/std/os/unix/trait.PermissionsExt.html) and [on `OpenOptions`](http://doc.rust-lang.org/std/os/unix/trait.OpenOptionsExt.html).

I would certainly believe that we could add a few more unix-specific extension traits, but I would encourage you to be a little more constructive in what you're requesting.

**Comment by mahkoh** [comment]
I am not talking about unix specific code. Functions that use std::os::unix will not compile on Windows, I assume. I'm talking about cross platform code that doesn't need platform specific functions.

>@mahkoh you can't really compare to what other languages do because they all ignore the mode argument on windows (at least from what I've found).

Why does this mean that it cannot be compared?

**Comment by pnkfelix** [comment]
1.0 beta, needs-decision, P-backcompat-libs

**Comment by aturon** [comment]
I'm going to close this issue. The plan is to instead follow a design similar to opening a file, where we can provide conveniences with reasonable per-platform defaults for `create_dir` and `create_dir_all`, and then have a builder-style API (`CreateDirOptions` or some such) that allows per-platform customizations of things like permissions or security attributes, etc.

@alexcrichton will be following up with an eventual RFC before 1.0.

**Comment by alexcrichton** [comment]
I have opened an issue [in the RFC repo](https://github.com/rust-lang/rfcs/issues/939) to track this functionality.
