### ISSUE TITLE
Tracking issue:  Add back `Vec::from_elem` (RFC 832)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#22414]
https://github.com/rust-lang/rfcs/pull/832

**Comment by Gankro** [comment]
Super easy to implement for anyone interested. The implementation in the RFC is sound, although it should the new code should be abstracted out into a function that the macro calls for inline and macro-sanity reasons. The function needs to be marked as public/stable, but should otherwise be marked as #[doc(hidden)], as it is not intended to be called directly -- only by the macro.

**Comment by Gankro** [comment]
Willing to mentor on details.

**Comment by msiemens** [comment]
I'd like to give it a shot :)

**Comment by msiemens** [comment]
By the way: The [documentation for `vec!`](http://doc.rust-lang.org/std/macro.vec!.html) seems very sparse. If it's okay, I'd expand that a bit while I'm on it, or should that go into a seperate PR?

**Comment by Gankro** [comment]
Yeah, that's totally reasonable to do at the same time!

**Comment by msiemens** [comment]
Great! What would be the preferred place where to put the new function? I've added it to `libcollections/vec.rs` as `pub fn from_elem<T: Clone>(elem: T, n: usize) -> Vec<T>` for now (currently compiling it)

**Comment by Gankro** [comment]
Since it's supposed to only be used by the `vec!` macro (and will be doc(hidden)), it makes sense to me to put it in macros.rs. Putting it in vec.rs makes sense, too, though.

**Comment by msiemens** [comment]
vec.rs has a section labeled "Internal methods and functions" that seemed to fit well.
