### ISSUE TITLE
A better error message for misplaced doc comments

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#22547]
This code:

```
enum Option<T> {
    None,    /// No value
    Some(T),    /// Some value `T`
}
```

yields this error:

```
 error: expected ident, found `}`
 }
 ^
```

I was writing an example to show this erorr, and _still_ didn't realize this was the correct error for this problem.

**Comment by qwertie** [comment]
Can't we use an alternate syntax to document things on the right? e.g. `//< Description`

**Comment by steveklabnik** [comment]
I would not be in favor of adding yet another kind of comment, personally.

**Comment by bjeanes** [comment]
New syntax doesn't feel needed for differentiating the types of comments. Either `///` is preceded by whitespace or by content. It seems like a reasonable rule that comments following content apply to that content, not to something on the next line.

**Comment by tshepang** [comment]
@bjeanes what would happen if we had this:

```rust
enum Option<T> {
    /// No value
    None,    /// I mean there really is No value
    Some(T),    /// Some value `T`
}
```

**Comment by jtianling** [comment]
I can't agree with @qwertie  more, what's a surprise that a comment would cause a syntax error.

**Comment by swsch** [comment]
How about calling `///` *documentation* instead of *documentation comment*?

`///` provides documentation for the following identifier. If you provide documentation for the following identifier and that item is missing, it is a) an error and b) the message makes perfect sense.

**Comment by lilinjn** [comment]
I wholeheartedly agree with @swsch... More radically, it seems to me a nice feature for any new language would be to provide a way to stop conflating the various overloaded usages of old-school comments and instead provide dedicated syntax for 1) documentation directed toward end users, 2) documentation directed at maintainers (e.g. a comment next to a tricky piece of logic) and 3) syntax to have the parser ignore arbitrary fragments of code.

**Comment by malnormalulo** [comment]
I think @swsch and @lilinjn are on the right track here. Comments are, traditionally, dead text; they do nothing. Rust's doc comments not only have semantic rules coupling them to code objects, but their contents are even _compiled_ in some cases. What's more, their usefulness is not, like a traditional comment, found in marking up code as you look at it -- they are instead a wholly separate product, existing mostly so that you _don't_ have to look at the code.

They are, in short, an entirely different thing than the comments denoted by that ubiquitous C syntax, and should not be shackled to that syntax or terminology simply because their Javadoc forebears are.

As for the immediate issue, I think @bjeanes's solution is elegant.

**Comment by andyg0808** [comment]
@tshepang What would you think of treating documentation on the same line as code as if it was written immediately above the code? That is,
```rust
enum Option<T> {
    /// No value
    None,    /// I mean there really is No value
    Some(T), /// Some value `T`
}
```
would be treated as if it were
```rust
enum Option<T> {
    /// No value
    /// I mean there really is No value
    None,
    /// Some value `T`
    Some(T),
}
```

**Comment by adambadawy** [comment]
@andyg0808 What then would happen with this?:
```rust
/// This is documentation for `Foo`
enum Foo { /// And I guess more docs for `Foo`?
    A,
    B,
}
```

It's not a hard issue to resolve, but I'm pointing out that it looks weird. Not just after a brace, but in your original example, too, in my opinion.

**Comment by vitoreiji** [comment]
@adambadawy, it does look weird, I agree. But it also solves a corner case, it's predictable and sort of makes sense.

An alternative would be a syntax error saying you can have either one or the other style, but not both. This would prevent this weirdness much more effectively than simply frowning upon the undesired behavior. Come to think of it, this is my favorite option.

**Comment by adambadawy** [comment]
> An alternative would be a syntax error saying you can have either one or the other style, but not both. This would prevent this weirdness much more effectively than simply frowning upon the undesired behavior. Come to think of it, this is my favorite option.

The reason this issue was opened up is because there is a poor error message for a misplaced doc comment. Now we're discussing a design with more kinds of doc comments and more ambiguity, which could lead to

- poorer docs, in the case of a doc comment that should have been a normal comment now being implicitly appended to the docs above it
- poorer error messages, since if a doc comment could have documenting an item before _or_ after it, it's more complex to tell the user where we expected an item
- and more error messages, since we can't use both styles

depending of course on the chosen design. I am strongly against adding another kind of documentation comment; it will buy us very little (choosing the position of the documentation in source code) and complicate the involved tooling needlessly.

**Comment by steveklabnik** [comment]
My feelings have basically entirely changed since opening this bug. Or rather, while it's an unfortunate error, I don't see how we can do any better without introducing more problems.

**Comment by adambadawy** [comment]
> My feelings have basically entirely changed since opening this bug. Or rather, while it's an unfortunate error, I don't see how we can do any better without introducing more problems.

It seems simple enough to me? If we find a doc comment and then something unexpected, the error message can be changed to something like "expected documentable item after doc comment".

**Comment by HeyImAlex** [comment]
Maybe to avoid ambiguity we could make it so that a doc comment can't share a line with anything but whitespace? A grep (`^.*[^[:space:]\/].*\/\/\/.*$`) on this repo shows that it's not being done anywhere right now, and I can't think of a good reason why it would be, but maybe I'm missing something. Right now this compiles but is incorrect:

```rust
enum Option<T> {
    Some(T), /// Some value `T`
    None,
}
```

It's kind of contrived but I can imagine it happening in the wild. Sorry if there's some other reason this can't be done, I just noticed a reference to this issue in the rust book!

**Comment by cooperra** [comment]
:+1:

I like forcing documentation comments to be on their own line to eliminate ambiguity. Right now end-of-line ones are unintuitive: they cause an error or, worse, describe the wrong item. I think we should either get rid of them or fix them. 

In the short term, we can just write a better error message (as @adambadawy suggested) and force documentation comments to be on their own line. It would avoid a lot of complexity. But it would be nice to ultimately allow end-of-line documentation comments. Sometimes it's more convenient to describe something on the same line. Plus it's intuitive; people will probably attempt to do it anyway. 

I like @vitoreiji's suggestion if we decide to keep end-of-line documentation comments:

1. Documentation comments on their own line describe what appears on the next line.
2. Documentation comments that share a line with anything else describe that content.
3. It's illegal to describe something by using both forms.

In the error message, complain that multiple documentation comments describe the content and suggest that one of them should become a normal comment.

It's another error message, but it's one that people will rarely encounter if ever. Is there any reason one would want to use both forms at once?

Examples:

OK:

    enum Option<T> {
        /// Describes Some(T)
        Some(T),
        None,
    }

OK:

    enum Option<T> {
        Some(T), /// Describes Some(T)
        None,
    }

Bad:

    enum Option<T> {
        /// Describes Some(T)
        Some(T), /// Also attempts to describe Some(T)
        None,
    }

The only downside I can think of is it would silently break comments that rely on the weird existing behavior. 

If we force them to stand alone first, then they would break loudly. Then, once everyone has fixed those errors and moved the comments to their own lines, we could add the proper end of line comments. This way, nothing would quietly break.

**Comment by steveklabnik** [comment]
Yes, this would be a breaking change; though I'm not sure there's any code that is correct that it would actually break.

That path would _certainly_ require an RFC though.

**Comment by AlexKnauth** [comment]
But changing the error message like @adambadawy suggested in https://github.com/rust-lang/rust/issues/22547#issuecomment-157769714 wouldn't be a breaking change. An error message like "expected documentable item after doc comment" is much easier to understand.

**Comment by Timmmm** [comment]
I have actually read this issue twice before and it *still* took me around 10 minutes to figure out why I was getting this error. Specifically I had this code:

```
struct Foo {
};

impl Foo {

    /// bar does something
    fn bar(&self) {
        // ...
    }

    /// baz does another thing
    /* fn baz(&self) {
        // ...
    } */
}
```

That is, normal code but I had commented out one function. It gives this error:

    error: expected one of `const`, `default`, `extern`, `fn`, `pub`, `type`, or `unsafe`, found `}`

This is *really* confusing. Would it really be that hard to have the error say something like this?

    error: expected documentable item (one of `const`, `default`, `extern`, `fn`, `pub`, `type`, or `unsafe`) after documentation comment, found `}`

And then point to the `///` comment that triggered it. This would be a huge improvement and I guarantee it will save many people a lot of time. And Happy Christmas!

**Comment by mgeisler** [comment]
For completeness, let me add that the error message has been updated at some point. You now see:
```
error[E0585]: found a documentation comment that doesn't document anything
  --> src/lib.rs:10:17
   |
10 |     Some(T),    /// Some value `T`
   |                 ^^^^^^^^^^^^^^^^^^
   |
   |
   = help: doc comments must come before what they document, maybe a comment
     was intended with `//`?
```
for the example given in the first comment. This is with Rust 1.17.

Also, it was suggested a couple of times above to allow documentation following the item it's documenting. I think that is a bad idea because it doesn't _scale_ very well. Basically, you quickly end up with very long lines. Go uses that system for the so-called struct tags and in my experience, it's been awkward to use.

Vertical space is cheaper than horizontal space, so I think it's good if Rust at least makes that the default way to format things.
