### ISSUE TITLE
Different code snippets from the same doc string mixed up in playpen

### ISSUE THREAD

**Issue by glacjay** [rust-lang/rust#22615]
For example, http://doc.rust-lang.org/std/cell/index.html, when I click the top right arrow of the first code snippet, there are not only code from this snippet, but also the following snippets, one followed the other.

**Comment by killercup** [comment]
Just ran into this at the docs for [HashMap](http://doc.rust-lang.org/std/collections/struct.HashMap.html).

Looks like [this line of JavaScript](https://github.com/rust-lang/rust/blob/68740b405404a3f885e388c8d31722797d519c30/src/librustdoc/html/static/playpen.js#L18) selects to much code when building the code for the playpen link. I guess it should be `prev` instead of `siblings`. I'll look into writing a short PR.
