### ISSUE TITLE
"Calling a function with a bad signature!"' failed.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#22663]
I was able to crash compiler (rustc 1.0.0-nightly (522d09dfe 2015-02-19) (built 2015-02-21)
) :

```
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/Instructions.cpp:281: void llvm::CallInst::init(llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&): Assertion `(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"' failed.
```

with:  https://github.com/dpc/rhex/tree/0dbf5b7f861638e59f367170b21b6b5ee9b286f7

and it turned out that this is a small change:

https://github.com/dpc/rhex/commit/17487b873c05ad15fde6bbae5c6f69b79a2f61aa

that fixes the crash. I hope it's helpful.

**Comment by dotdash** [comment]
Thanks for the bug report!

Reduced testcase:
````rust
pub fn fail(x: Option<& (Iterator+Send)>) -> Option<&Iterator> {
    inner(x)
}

pub fn inner(x: Option<& (Iterator+Send)>) -> Option<&(Iterator+Send)> {
    x
}

fn main() {}
````

The problem is that LLVM gets distinct types for `Option<&Trait>` and `Option<&(Trait+Bound)>` and sees the call as invalid.

FWIW, you could also have changed your `At::item()` function to return `Option<&'a (Item+Send+Sync)>` to make the error go away
