### ISSUE TITLE
No way to portably find if OsStr has a particular prefix

### ISSUE THREAD

**Issue by jmesmon** [rust-lang/rust#22741]
This is essentially the operation provided by `starts_with()` on String, str, and slice.

Right now, this can only be done by either:

 - requiring the OsStr to be utf-8 (and converting it to str/String)
 - Or depending on the unix-only `as_bytes()` method on OsStrExt

**Comment by alexcrichton** [comment]
This is a fundamental limitation of `OsString` and how it represents two different encodings on Unix and Windows. It is certainly possible to add many more APIs over time to perform various operations on an `OsStr` such as looking for prefixes, splitting, etc.

> Or depending on the unix-only as_bytes() method on OsStrExt

There is also an `encode_wide` function on Windows for performing this sort of operation.

This issue, however, boils down to requesting more functionality be added to `OsStr` (new APIs), and belongs in the RFC repo instead of the `rust-lang/rust` repo. Would you be ok opening an issue over there instead?

**Comment by jmesmon** [comment]
I'm not sure it's worth asking if I'm "ok" with it if that is the location I'm required to open a ticket. Next time just tell me what needs to happen.

**Comment by alexcrichton** [comment]
Issues for new APIs and/or functionality in the standard library now belong in the RFC repository as they will require an RFC to be added.

Closing in favor of https://github.com/rust-lang/rfcs/issues/900
