### ISSUE TITLE
Can't use HashMap<T, V> with T being an enum.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#22756]
http://is.gd/PvCLA6

```
use std::collections::HashMap;

#[derive(Debug)]
enum Y {
    Y1,
    Y2,
}

#[derive(Debug)]
struct X {
    items : HashMap<Y, i8>,
}
```

**Comment by huonw** [comment]
[`HashMap`](http://doc.rust-lang.org/nightly/std/collections/struct.HashMap.html) has bounds on its first parameter (look at the "Methods" section): `K: Eq + Hash`. The slightly confusing error message is because the `derive`d `Debug` implementation for `X` is trying to use the `Debug` implementation for `HashMap`, which has these bounds:

```rust
impl<K, V, S> Debug for HashMap<K, V, S> where K: Eq + Hash + Debug, V: Debug, S: HashState
```

That is, your enum needs to implement those two traits, which can be done with `derive`:

```rust
use std::collections::HashMap;

#[derive(Debug, PartialEq, Eq, Hash)]
enum Y {
    Y1,
    Y2,
}

#[derive(Debug)]
struct X {
    items : HashMap<Y, i8>,
}

fn main()
{
    println!("Hello, world!")
}
```

Closing, but thanks for filing nonetheless!

**Comment by arie-itecho** [comment]
Can we maybe include this as a question & answer on Stack Overflow. It'll be helpful for beginners who learn through Googling their problems.
