### ISSUE TITLE
Converting [char] to String

### ISSUE THREAD

**Issue by remram44** [rust-lang/rust#22868]
There should be a way to convert [char] to String. This can't be done in-place like [u8] to &str (with [std::str::from_utf8](http://doc.rust-lang.org/nightly/std/str/fn.from_utf8.html)) but should still be available.

Maybe something like this?
```rust
impl ToString for [char] {
    fn to_string(&self) -> String {
        let mut s = String::with_capacity(self.len()); // capacity? char != byte
        for c in self {
            s.push(c.clone());
        }
        s
    }
}
```
http://is.gd/neQ0XH

**Comment by Kimundi** [comment]
Hi, feature requests for added functionality rather than bug reports should go to https://github.com/rust-lang/rfcs/issues now, so I'm closing this.

However, given that you can collect a iterator of `char`s into a `String`, and have the size hint apply so that it allocates the right size already, I don't think this is strictly needed at this point.

It is also not clear whether `['a', 'b'].to_string()` should produce `"ab"` or `"['a', 'b']"`.

**Comment by remram44** [comment]
I see.

For future reference, the approach mentioned is `array.iter().cloned().collect::<String>()`.

**Comment by mcandre** [comment]
+1 Would be really helpful if Rust stdlib could convert between its own types.

**Comment by mihneagogu** [comment]
UPDATE: you can now collect an iterator of chars into a string, so that's all sorted out
