### ISSUE TITLE
Pointers can't opt into Send and Sync anymore

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#22967]
Some days ago it was possible to
```rust
unsafe impl Send for *mut T { }
```
but now you have to
```rust
unsafe impl Send for (*mut T,) { }
```
and then send a `(t,)`. For what purpose?

**Comment by kmcallister** [comment]
This is expected behavior. You're meant to use [`Unique<T>`](http://doc.rust-lang.org/std/ptr/struct.Unique.html) or another wrapper that makes the ownership/borrowing explicit.

**Comment by mahkoh** [comment]
The pointer is shared and synchronization happens in the c library. There is no wrapper for that so why can't the person who wraps the C library indicate that by making the pointer Send?

**Comment by kmcallister** [comment]
So it doesn't own the C object, which means you'll need some wrapper type to make it safe — either with lifetimes or something else like refcounting.  You can `impl Send` on that.

**Comment by mahkoh** [comment]
I have all that, but to give the user access to the raw pointer for if they want to do things I haven't wrapped, the raw pointer has to be Send. Or I have to do funny things like sending `(T,)`.

**Comment by mahkoh** [comment]
This worked perfectly fine two weeks ago. Raw pointers were not Send but you could opt into Send when you knew that that's safe. There seems to be no reason to remove that feature.

**Comment by kmcallister** [comment]
For features like sound generic drop, the compiler needs to know which pointers are owning and which are borrowing.  We don't want to arbitrarily say that `*mut T` is owning for some `T` and borrowing for others.  That's a global decision for each `T`, but most types of objects can in fact be owned in some contexts and borrowed in others.

> Or I have to do funny things like sending `(T,)`.

The non-funny version of this is your own newtype struct with a pub field that exposes the raw pointer.  You'd impl `Send` on that struct. Then you're saying that pointers generated *a specific way* are safe to send, rather than any `*mut` that happens to point to a `T`.

> There seems to be no reason to remove that feature.

If you still feel that way after reading this comment then please read [RFC 769](https://github.com/rust-lang/rfcs/blob/master/text/0769-sound-generic-drop.md).

**Comment by kmcallister** [comment]
And [RFC 738](https://github.com/rust-lang/rfcs/blob/master/text/0738-variance.md).

**Comment by mahkoh** [comment]
The RFCs you linked seem to be completely unrelated to Send and the PR that implemented this restriction only referred to the OIBIT RFC. In the OIBIT RFC it says:

```
1. move Send and Share out of the language entirely and into the standard library
```

How would a pure library trait in any way affect a language item such as the Drop trait?

**Comment by kmcallister** [comment]
This is not the appropriate place to discuss it further. Please submit an RFC if you would like to revert this quite intentional change to the language.
