### ISSUE TITLE
Tracking issue for Replace `Vec::drain` by a method that accepts a range parameter (RFC 574)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#23055]
https://github.com/rust-lang/rfcs/pull/574

cc @mahkoh

**Comment by paulp** [comment]
The rfc says

> Where Trait is some trait that is implemented for at least Range<usize>, RangeTo<usize>, RangeFrom<usize>, FullRange, and usize.

It also includes an example which depends on usize:
```rust 
fn remove(x: &mut Vec<u8>, index: usize) -> u8 {
    x.drain_range(index).next().unwrap()
}
```
However RangeArgument only implements the first four. Furthermore as things stand it does not appear possible to accept RangeArgument<usize> and usize simultaneously, because dispatch doesn't consider the trait bound and reports that conflicting implementations exist.

**Comment by bluss** [comment]
@paulp Yes, #24781 was explicit about these issues. I forsee a new RFC to finish off drain and maybe the RangeArgument trait.

**Comment by alexcrichton** [comment]
I believe this has [since been implemented](http://doc.rust-lang.org/std/vec/struct.Vec.html#method.drain)
