### ISSUE TITLE
Consider if we want to bundle rustc source code in docs

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/rust#23061]
Currently generated `doc/src` directory is 26MB without compiler docs and 48MB with them. This becomes the largest directory inside generated docs once #23060 lands (`doc/rustc` is over 90MB before that patch, for the reference). It will also interfere with #2206, as we would no longer have source codes to dump.

It takes about 5MB in the gzipped tarball, so this is not negligible size. We can instead link to the source code in static.rust-lang.org or, possibly, Github with a permalink.

**Comment by steveklabnik** [comment]
It's also useful for plugins like Racer.

**Comment by lifthrasiir** [comment]
@steveklabnik But only if we have *raw* source code, right? I don't think Racer can consume HTMLized source code files.

**Comment by steveklabnik** [comment]
That's what I thought the title was talking about: '`rustc` source code"

**Comment by lifthrasiir** [comment]
Ugh, I think @kmcallister has misunderstood the issue ;) I meant the source code linked from the `[src]` button, which might or might not be useful. We can, as a middle ground, make it optional and link to `doc.rust-lang.org` when unavailable.

**Comment by kmcallister** [comment]
> I meant the source code linked from the `[src]` button

Yes, that's what I meant as well. Feel free to change the title again if you think it's unclear.

**Comment by steveklabnik** [comment]
Traige: I thought @brson had an issue on rustup.rs for this, but could not find it.

**Comment by brson** [comment]
It looks to me like there have been people talking cross-purposes in this issue. This is quite an old issue, and it originally appears to be discussing whether the compiler sources (not std) are included with the docs, assuming that the compiler API docs are even included with the docs (which they no longer are).

I'd suggest that since we don't actually distribute the compiler docs at all, this entire issue is subsumed by https://github.com/rust-lang/rust/issues/29893 (distribute the compiler docs).
