### ISSUE TITLE
Bounds seem to be ignored in negative impls

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#23072]
``` rust
#![feature(optin_builtin_traits)]

use std::marker::MarkerTrait;

unsafe trait Pod: MarkerTrait {}
unsafe impl Pod for .. {}

trait Bound: MarkerTrait {}

// it seems that the bound is ignored here, i.e. this gets treated as `impl<T> !Pod for T {}`
impl<T: Bound> !Pod for T {}

fn is_pod<T: Pod>(_: T) {}

fn main() {
    is_pod(0i32);  // `i32` doesn't implement `Bound`, so it should be `Pod`
    is_pod(&0i32);  // likewise here
}
```

``` rust
rustc 1.0.0-nightly (3b3bb0e68 2015-03-04) (built 2015-03-05)
```

cc @nikomatsakis @FlaPer87

**Comment by nikomatsakis** [comment]
Yeah, hmm, this is caused by the way that trait dispatch picks a concrete impl if its the only thing available without recursively evaluating the bounds. Hmm. It makes sense for positive impls but for negative impls doesn't seem quite right. 


Niko

-------- Original message --------

**Comment by nikomatsakis** [comment]
This turns out to be a deeper issue. We should hold off on removing feature-gate for negative impls until it is resolved. The core issue that that negative impls with extra bounds become effectively negative bounds:

    trait NegFoo : MarkerTrait { }
    impl NegFoo for .. { }
    impl<T:!Foo> !NegFoo for T { }

Now `T:NegFoo` is effectively `T:!Foo` from https://github.com/rust-lang/rfcs/pull/586. I am very nervous about introducing such unbounded negativity into the trait system (see e.g. #23086). I would like to (for now) limit negative impls in OIBIT so that they can't carry where-clauses -- or at least not more where-clauses than are needed for their types to be well-formed.

**Comment by kdeeee** [comment]
error still persist in `rustc 1.11.0 (9b21dcd6a 2016-08-15)`
error message
```
default trait implementations are experimental and possibly buggy
default trait implementations are experimental and possibly buggy

```

**Comment by Manishearth** [comment]
triage: OIBITs cannot have bounds anymore. yay.
