### ISSUE TITLE
Type inference in a closure modifying an iterable object

### ISSUE THREAD

**Issue by yann-ledu** [rust-lang/rust#23092]
Implementing a closure that doubles the elements of an iterable object in-place.

```rust
fn main(){
// This works
let mul2cl = |v:&mut [_]| for el in v {*el*=2;};

// This fails, requiring to annotate the type of el
let mul2cl = |v:&mut _| for el in v {*el*=2;};

// This also fails, but would be very nice if it didn't!
let mul2cl = |v| for el in v {*el*=2;};
}
```

**Comment by nikomatsakis** [comment]
Unfortunately, the design of Rust's type checker currently requires that enough type information be available at certain times -- so, in this case, when type-checking `*el`, we have to have some idea what `el` is. For that to happen, we have to know, the type of `v` (since `el` is derived by iterating through `v`). Fixing this would be a major project and in some cases isn't even possible. Closing for now, but thanks for the suggestion!
