### ISSUE TITLE
UdpSocket is missing the shutdown method

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#23194]
Should be easy enough to implement! Good first bug for anyone and I'd be willing to mentor.

**Comment by aatxe** [comment]
I've made an attempt at implementing this that builds, but the information I've found on the matter seems to indicate that shutting down a UDP socket doesn't really make sense. That being said, resources indicate that `shutdown` does work on UDP sockets. So, I'm admittedly rather confused.

## It's not useful. ##
See step 5: https://www.cs.rutgers.edu/~pxk/417/notes/sockets/udp.html
https://lists.apple.com/archives/macnetworkprog/2008/Jan/msg00002.html

## It works. ##
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740481(v=vs.85).aspx
http://linux.die.net/man/3/shutdown

**Comment by LorenVS** [comment]
I think the goal here is a way to terminate a thread that is dedicated to reading from a UDP socket. Currently, recv_from blocks indefinitely and there is no way to signal it to terminate for a clean shutdown. I believe setting Shutdown::Read would cause the currently blocking recv_from to return with an error, which could be handled to implement clean shutdown.

There was a similar discussion on #14926 regarding close_read/close_write. I believe the agreement was that Shutdown::Write isn't horribly useful for UDP sockets. Even if you have a dedicated thread for sending out of a UdpSocket, you are more likely to signal termination by dropping the channel which sends data to that thread, rather than shutting down the socket itself.

**Comment by KiChjang** [comment]
I'd like to give this one a try. I have a basic understanding of how UDP works, but I still don't understand where everything is in the source code.

**Comment by alexcrichton** [comment]
@aaxte yes as @LorenVS mentioned it may not have the best semantics in all situations, but it definitely does something on supported platforms and we largely want to expose it for symmetry with the TCP primitives.

@KiChjang the methods would be added to [`src/libstd/net/udp.rs`](https://github.com/rust-lang/rust/blob/master/src/libstd/net/udp.rs) and you could follow similar delegation patterns to add the implementations themselves to [`src/libstd/sys/common/net2.rs`](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/common/net2.rs). You could then do basically the same as `TcpStream::shutdown` in that file, although I would recommend refactoring into a helper method.

**Comment by alexcrichton** [comment]
Given the outcome of https://github.com/rust-lang/rust/pull/23214 it looks like we may not actually want to implement this at this time. @aatxe's investigation didn't turn up many reliable use cases for doing this, so we can probably hold off until we have a motivating example.

**Comment by flaub** [comment]
In my experience, simply closing the fd/handle of the socket is enough to cause blocking recv calls to return with a failure (which is different on each platform). This implies that a `UdpSocket` might be in a state of `Active` vs `Inactive` depending on whether the fd has been closed or not. This is essential for being able to cancel pending recv calls.
