### ISSUE TITLE
Potential error in error (warning) message

### ISSUE THREAD

**Issue by homebru** [rust-lang/rust#23224]
I am too new at rust to know if this is really an issue or not.

I was trying to get the sample "guess" program to work. At one point I got this warning:
> warning: pattern binding `Less` is named the same as one of the variants of the type `core::cmp::Ordering` [E0170]

So I change my namespace to use '**core**' and I got this error:
> error: failed to resolve. Use of undeclared type or module `core::cmp::Ordering`

In the end, the solution was to use "**std**::cmp::Ordering::Less" - so the bug(?) is the warning message steering me to the wrong namespace.

**Comment by jakub-** [comment]
This is a general problem with paths in error messages and somewhat related to https://github.com/rust-lang/rust/issues/13065.

What we should be doing is for each resolved definition of an item, find the publicly accessible path to that item. Such a path will always exist due to the restriction on exposing private types. This may or may not be a non-trivial change to `resolve`, though.
