### ISSUE TITLE
Can't 'use' from an 'extern crate' defined in a function

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#23314]
I never realized this before:

```
fn main() {
    extern crate core;

    // Can't write this because 'self' refers to the outer module.
    use self::core::str;
}
```

Seems pretty strange.

**Comment by shepmaster** [comment]
I believe this to be the root cause of #27301.

A doc test with

```
/// ```
/// extern crate bignum;
/// use bignum::inits::Zero;
///
/// let a = bignum::BigNum::new(Zero::zero());
/// ```
```

becomes

```rust
fn main() {
    extern crate bignum;
    use bignum::inits::Zero;

    let a = bignum::BigNum::new(Zero::zero());
}
```

Which then suggests to use `self::bignum::...`, but that also fails to work due to this issue. It then suggests to use `self::self::bignum::...`, which is crazier.

**Comment by steveklabnik** [comment]
Triage: this is https://github.com/rust-lang/rfcs/issues/959, and we'd need an RFC to change this stuff, so I'm going to give it a close.

**Comment by shepmaster** [comment]
@steveklabnik do you want to close #27301 as well then?

**Comment by steveklabnik** [comment]
Let's leave it open for now; I believe we could fix this by changing where the `fn main` is inserted, no?
