### ISSUE TITLE
stdio: Handle unicode boundaries better on Windows

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#23344]
The stdio support on windows has two separate modes. One is when stdout is not a console and implies byte orientation, the other is when stdout is a console and implies [u16] orientation. In the stdout-is-a-console case we require that all input and output to be valid unicode so we can translate [u8] to [u16].

In this console case, however, our translation may not be quite right for a number of scenarios:
- When reading data, the console will give us a block of u16's which we need to translate to UTF-8. In theory the console can give us half of a surrogate pair (with the next half available on the next call to read), but we do not handle this case well currently. This should be fixed by simply adding a "buffer of size 1" to hold half of a surrogate pair if necessary.
- When reading data, we require the entire set of input to be valid UTF-16. We should instead attempt to read as much of the input as possible as valid UTF-16, only returning an error for the actual invalid elements. For example if we read 10 elements, 5 of which are valid UTF-16, the 6th is bad, and then the remaining are all valid UTF-16, we should probably return the first 5 on a call to `read`, then return an error, then return the remaining on the next call to `read`.
- When writing data, we require that the entire block of input is valid UTF-8. We should instead take a similar approach as above where we try to interpret as much of the input as possible as UTF-8, but we simply ignore the rest for that one call to `read` (returning an error if the first byte is invalid UTF-8).
- When writing data, we don't handle the case where a multibyte character straddles calls to `write`. Like the reading case, this could be alleviated with a 4-byte buffer for unwritten-but-valid-utf8 characters.
- When writing, we translate a block of valid UTF-8 to a block of UTF-16. Upon writing this UTF-16, however, not all characters may be written. There are two problems here:
  - We need to translate a length of UTF-16 characters to a number of UTF-8 bytes that were written.
  - If half of a surrogate pair is written, the other half should be "buffered" and the length of UTF-8 written should include the half-written character (as the extra data is buffered).

At this time I'm not sure what sort of guarantees Windows actually gives us on these APIs. For example does windows never deal with only half of a surrogate pair on a read/write? If Windows were to guarantee various properties like this (or that it always writes the entire buffer, for example), our lives would be a lot easier! For now, though, it is unclear what we can rely on, so this issue is written as if we rely on nothing.

**Comment by alexcrichton** [comment]
cc @retep998, @aturon

**Comment by alexcrichton** [comment]
The code for all this currently lives in `src/libstd/sys/windows/stdio.rs`, but it may move over time.

**Comment by retep998** [comment]
The Windows console just deals with an opaque sequence of `WCHAR` so it offers no guarantees regarding how it gives you surrogates.

**Comment by bluss** [comment]
Some notes on Stdin as it is today:

There seem to be some inefficiencies, the [allocation of a 4 kB vector](https://github.com/rust-lang/rust/blob/9c3ba763891b0fe626adefc19ad7908b0862a41c/src/libstd/sys/windows/stdio.rs#L97) can possibly be turned into an array on the stack. A new String is then allocated again from that result.

The [MemReader comment should go,](https://github.com/rust-lang/rust/blob/9c3ba763891b0fe626adefc19ad7908b0862a41c/src/libstd/sys/windows/stdio.rs#L115) it used to talk about an unwrap that's no longer there.

**Comment by alexcrichton** [comment]
As reported in #30399, an easy way to trigger this:

```rust
    let v = vec![255u8; 5000];
    let s = String::from_utf8_lossy(&v);
    // println!("Len {}", s.len());
    println!("{}", s);
```

**Comment by retep998** [comment]
I just ran into this issue while doing `cargo list --tree` in one of my projects presumably because it prints out some box drawing characters and one of them straddled a write boundary.

**Comment by luser** [comment]
This is a real bummer because you can't write non-UTF-8 data to stdout via the std::io APIs, which is not a limitation in C. The simplest example here would be a program that wants to write arbitrary binary data to stdout (expecting it to be piped somewhere), but I hit this today with my program that runs a command, captures its stdout, and then later writes that data to its own stdout. If the stdout from the command was not valid UTF-8 that fails. (The program in question was the Visual C++ installed with the French locale running in a Windows VM with the system locale set to US English.)

**Comment by luser** [comment]
I gather this code is written this way because we want to be able to write Rust strings (which can contain Unicode) to the console, but it's kind of limiting.

**Comment by alexcrichton** [comment]
@luser unfortunate (as I'm led to believe) that's actually a somewhat impossible operation on Windows. The captured output is all byte-oriented as that's how the stdout pipes are set up for a spawned program, but when printing that to a console (not a pipe) it's expected to be a u16-oriented stream, so a conversion needs to happen.

I'm not sure if there's a system API for writing bytes to a console, however, other than just the u16 units we're doing today.

**Comment by retep998** [comment]
Sure you can write bytes to the console by calling `WriteConsoleA` instead of `WriteConsoleW`, but it'll be interpreted as whatever the current code page is. While you can change the console output code page using `SetConsoleOutputCP`, trying to use UTF-8 will still suffer as it also has issues with multi byte codepoints straddling write boundaries. Trying to use `SetConsoleCP` to read UTF-8 is even worse as multi byte codepoints simply do not work. Rust takes the approach of trying to be as unicode friendly as possible by using wide functions. If you don't like that default and think unicode is a waste of time, then by all means feel free to call the appropriate system functions and write to stdout yourself in whatever manner you feel like.

> The simplest example here would be a program that wants to write arbitrary binary data to stdout (expecting it to be piped somewhere),

If stdout _is_ piped then Rust won't check that what you're outputting is UTF-8 and will gladly just throw those bytes through the pipe. The only time it matters is when you're interacting with the Windows Console which is a __terrible__ place to read/write arbitrary binary data, and if your program tries to spew binary data to the console then that's just bad design.

**Comment by luser** [comment]
I think it's unfortunate that the issue I ran into (run a subprocess, capture its output, write that to stdout) doesn't work reliably out-of-the box, and I think that's pretty legitimate.

**Comment by retep998** [comment]
It is working as reliably as it can. If you pass it UTF-8 data it does the conversion to UTF-16 and everything works fine. If you pass it data that isn't UTF-8, well now what? It certainly can't losslessly convert it to UTF-16, so that's out. As for writing it out with `WriteConsoleA`, well, what code page do you want to use? In C it "works" because it simply writes out the bytes using `WriteConsoleA` and doesn't care what the current code page is. That means what glyph your characters will display as depends on what the current code page is, thereby completely butchering unicode.

In your case, if the program you're capturing the output of is not outputting UTF-8 but rather some other code page, then the solution is for you to figure out which code page it is and use a crate like https://github.com/lifthrasiir/rust-encoding to convert it to UTF-8 before writing it out. If the output is binary, why the heck are you trying to write binary data to the console?

**Comment by luser** [comment]
Presumably the output is already in the system codepage, but `std::process::Output`'s `stdout` member is a `Vec<u8>`, just bytes, and the `Write` trait takes a `&[u8]`, which is usually just bytes, so yes, it's surprising that somewhere in the middle there something is trying to treat the data as UTF-8.

And yes, I understand that system codepages are a mess, and the historical legacy of "everything is ASCII" in C is terrible, but this seems like a fairly straightforward use case, and to do what would be 2 lines in C I'll have to jump through a number of hoops in Rust.

**Comment by retep998** [comment]
Rust has to default to using the wide versions so that Rust strings, which are known to always be UTF-8, can be written to the console correctly. Changing this behavior would be a serious regression for all the people that currently rely on unicode in the console.

Maybe one day libstd will have a more extensive API for interacting with stdout, including choosing how to deal with code pages, but that will take time and likely an RFC (feel free to create one if you can think of a good design), but until then your best option is to call [WriteConsoleA](https://retep998.github.io/doc/kernel32/fn.WriteConsoleA.html) yourself or create a library that does so for you, or even just call the libc functions if you really want.

**Comment by alexcrichton** [comment]
@luser yeah it's true that that this is unfortunately harder to do than in C, but it's unfortunate fallout from our decision to be much more principled about UTF-8 (especially in strings). The interface here is "write an arbitrary blob of bytes to stdout" rather than "write this process's output to stdout". The former doesn't have much of an interpretation if it's *not* unicode, but the latter should almost always be possible to ferry through without incident.

It may be worth exploring attempting to interpret the input as unicode and wherever that fails call the ansi functions which take bytes instead. That way you may be interleaving calls to the byte and wide apis, but maybe it'd work out? That'd at least get us to an infallible `write` implementation, although may give incorrect results.

**Comment by retep998** [comment]
It would most definitely give incorrect results when your input is in a code page that doesn't match the ascii portion of UTF-8, as during wide calls those bytes would be interpreted as UTF-8, while if some invalid UTF-8 is encountered it would do a narrow call and interpret those bytes as whatever the console code page is. I'd really prefer if we had separate APIs for writing unicode data and writing arbitrary blobs in the current code page.
