### ISSUE TITLE
Type inference error message not clear

### ISSUE THREAD

**Issue by yann-ledu** [rust-lang/rust#23412]
I was trying to see the type inferred

```rust
fn main()
{
    let u = 4;
    let ru = &u;
    ru(); // Did that to force the compiler to give me the type of ru. Ok, this compiler message is understandable
    let mru = ru*3;
    mru(); // I did that to see the type of mru, but what's that message ? Why is it so different from the error message for ru() above ?
}
```

**Comment by nagisa** [comment]
For reference: 

```
<anon>:5:5: 5:9 error: expected function, found `&_`
<anon>:5     ru();
             ^~~~
<anon>:7:5: 7:8 error: the type of this value must be known in this context
<anon>:7     mru();
             ^~~
```

The thing is that your method to check the inferred type is not correct, because it influences the inference itself.

Now, `ru` is a reference and no references are callable this way. `mru`, on the other hand, is not a reference to anything which causes conflicting requirements for type inference: `mru` must satisfy Mul<integral type, Output=something callable> because you call it, but we have many types of callables (fn, Fn trait, FnMut trait) and many types of integral types, at which point inference just gives up and asks you to explicitly annotate the type, hence the “unclear” message.

**Comment by yann-ledu** [comment]
I see. Many thanks.
