### ISSUE TITLE
`rustdoc --test` fails for simple examples in macro doc-comments.

### ISSUE THREAD

**Issue by insaneinside** [rust-lang/rust#23571]
[This gist](https://gist.github.com/insaneinside/0cacc9634cc3bbb936e1) contains a short, sweet, and simple reduced case.

**Comment by bstrie** [comment]
This is really a documentation bug. First, we need to document that you have to explicitly link your macros when writing doctests for them. Second, because linking can only be done at a crate root and because rustdoc will implicitly wrap your test in a `main`, you have to encapsulate your tests in your own main in order to disable this.

**Comment by bstrie** [comment]
Here's how the original gist looks when updated with the changes described above: https://gist.github.com/bstrie/653bc834aa871b8f45fa

Doubly misleading is that it's no use reading the stdlib when trying to figure out the cause of this test failure, because the implict linking of the std macros masks the need for manual linking.
