### ISSUE TITLE
There are very few tests for -Z unpretty expansion

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#23616]
**See https://github.com/rust-lang/rust/issues/23616#issuecomment-484999901 for a current issue description. The original description follows below.**

---

Pretty-expanded source that results in unstable code can't build. After it becomes illegal to not declare features this is going to cause a bunch of expanded source to not build.

**Comment by brson** [comment]
I'm going to be adding `no-pretty-expanded` to a bunch of tests.

**Comment by steveklabnik** [comment]
at least expanded is unstable, yeah?

**Comment by alexcrichton** [comment]
Unfortunately I think that this is just a fundamental limitation. We have a number of problems that make it such that expanded source cannot actually compile at all:

* `#[allow_internal_unstable]` make it such that macros can use unstable features without declaration
* `#[no_std]` which is injected is unstable
* Hygiene (e.g. a macro's local variable `foo` is very different than the outer variable `foo`)

I would also be fine just assuming that tests cannot be pretty printed when expected unless there is an explicit opt-in directive.

**Comment by brson** [comment]
Perhaps I will switch compiletest to support `pretty-expanded` and add that to a bunch that are passing now.

**Comment by nikomatsakis** [comment]
can we just disable the pretty-printing tests for the beta branch or something like that?

**Comment by nikomatsakis** [comment]
(Does that make sense?)

**Comment by steveklabnik** [comment]
Triage: not aware of any specific issue here, though I haven't heard about anyone running into this in practice in the last year.

**Comment by steveklabnik** [comment]
Triage: lots of FIXMEs referring to this issue still remain.

**Comment by jethrogb** [comment]
Ran into this while looking at the compiletest framework and was thoroughly confused. As far as I can tell, this is the situation as of early 2019:

Certain parts of the Rust test suite can be run in “pretty” mode. This will test the pretty-printing output of `rustc`. One of the pretty-printing outputs of `rustc` is the `expanded` mode, which may result in code that can't subsequently be compiled, that is what this issue is about. Tests that were in 2015 known to work with expanded mode have the `pretty-expanded` attribute to test that mode. Since the attribute is off by default and things just work if you don't test it, people have not been adding the `pretty-expanded` annotation to new tests even if it would work. Now, everyone has basically forgotten about this attribute. Additionally, all `pretty-expanded` annotations are marked with “FIXME #23616”, but this is misleading: the tests that have the attribute don't need to be fixed, it's the tests that *don't* have the `pretty-expanded`/FIXME annotation that are blocked on this issue.

I think it was a mistake to replace `no-pretty-expanded` with `pretty-expanded` in #23598, because the test coverage of expanded pretty printing has basically stagnated.

**Comment by jieyouxu** [comment]
compiletest triage: we have a dedicated `tests/pretty` test suite now (as of Dec 2024). Test coverage isn't perfect, but there's some. The FIXMEs linking to this issue has been removed in #133470 as the `pretty-expanded` directive in ui tests have become completely defunct and no-op over the years.
