### ISSUE TITLE
Replace UnixStream

### ISSUE THREAD

**Issue by Binero** [rust-lang/rust#23647]
There is some functionality in old_io marked as deprecated, that hasn't gotten a replacement.

UnixStream, isn't implemented anywhere outside of old_io. It is far from optimal having to keep using old_io just because UnixStream isn't available in the new io, nor under Unix. There probably is more symbols like this. 

http://doc.rust-lang.org/std/old_io/net/pipe/struct.UnixStream.html

**Comment by steveklabnik** [comment]
/cc @alexcrichton 

Not everything in old_io has a replacement.

**Comment by alexcrichton** [comment]
This is currently intentional, we haven't had the time to flesh out a design for unix sockets and named pipes on windows, so we are leaving this as a future extension to the standard library. New features such as this now currently belong in the RFC repo for inclusion into the standard library.

In the meantime, however, @sfackler has written up a nice [`unix_socket`](https://crates.io/crates/unix_socket) crate to connect unix sockets to the new I/O modules. I'm also sure he'd be willing to accept PRs to enhance its functionality in the meantime!

**Comment by lulcat** [comment]
hmmm. I just came across Rust yesterday precisely for Unix sockets :/ Wow, talk about confusion. I am so lost between this old_io, extern crates (nix? unix_socket? which one) git... sigh.. and they don't even have same methods and so on.. but ah well... I guess it's teething issues. But from what I was reading, Rust intended to be 'safe to upgrade' aka stable, not very stable eh.. spent hours compiling a nightly (not sure why it was so slow), just to allow some features, to discover much was deprecated .. anyway, didn't even realise windows is still used in 2016... and that is why 'functionality has been downgraded'?

Strange.
