### ISSUE TITLE
Incremental recompilation

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#2369]
I want to be able to recompile only dependencies (rather than everything in a crate), like SML's compilation manager or GHC's `--make` mode. I don't really care about the approach so long as it works and the outcome is that adding one `#debug` call in one file doesn't trigger recompilation of 100 other files in the same crate :-) I am volunteering to work on this after 0.3, but suggestions are welcome. Patrick suggested a good place to start would be to generate a (visualizable) graph of item dependencies, which makes sense to me.

**Comment by suhr** [comment]
To be notified: there's also [tup](http://gittup.org/tup/) with a somewhat different [approach](http://gittup.org/tup/build_system_rules_and_algorithms.pdf).

**Comment by nh2** [comment]
Hi, let me give some pointers to the Haskell world. GHC has this solved - and probably the best working incremental recompilation engine on the planet.

It can do:

* recompilation avoidance for module **imports** (easy for any language that doesn't implement imports by *string concatenation* - hi C++ 
* recompilation avoidance **within** Haskell packages (equivalent to crates)
* recompilation avoidance **across** Haskell packages
* recompilation avoidance on a **semantic** level (changing a comment doesn't invalidate downstream modules like it would in `make`)
* recompilation avoidance at **function granularity** (changed function not used => don't need to recompile downstream if the includer doesn't use that very function)
* recompilation avoidance even if TemplateHaskell (AST modifying macro language) is involved
* detection of **compilation flag changes**

GHC has documented its approach in high detail, and highlighted what the problems are. See here:

https://ghc.haskell.org/trac/ghc/wiki/Commentary/Compiler/RecompilationAvoidance

I believe that Rust has 

> Manually deleting the hidden files should never be required

**Comment by ebassi** [comment]
An important side effect of incremental recompilation that was not mentioned, and I think it's more important than building environment enablement, is enabling tooling (like IDEs) to perform operations like on-the-fly code analysis and prompt the user for warnings, code completion, etc.

**Comment by da-x** [comment]
The problem with 99% of build tools out there is that they duplicate the dependency management by either letting the user specify dependencies prior to target execution and/or by scanning them heuristically with prior knowledge over the type of executed target, and often doing so wrongly, failing to duplicate intrinsic logic, resulting in broken or failed builds. The builds are sometimes slower than they could be because the developer forsakes on specifying dependencies in favor of safe but slow re-execution, to avoid the aforementioned broken builds.

I suggest that you look into [a newer approach](https://github.com/ElastiLotem/buildsome), where dependencies are detected reliably for any kind of intermediate. The developer only needs to worry about target invocation itself. So, if you neatly split the build process to a DAG of separate process invocations, even with extremely complicated dependencies, this tool can track them easily.

**Comment by huonw** [comment]
This was RFC'd: https://github.com/rust-lang/rfcs/blob/master/text/1298-incremental-compilation.md

**Comment by nh2** [comment]
@huonw Is this issue the right place to discuss the RFC?

**Comment by nh2** [comment]
Even if not, I'll ask some questions here:

> the compiler will always parse and macro expand the entire crate

Why was this chosen? Wouldn't it make sense to include source files in the dependency graph as well, so that you can skip parsing and even reading the file contents if the file modification time suggests that the file has not changed?

> Optimization and codegen units

I'm not familiar with codegen units, and where their boundaries would be set, but if it's typically on the library/crate level, that could make some inlining problematic. Take for example Haskell's [`Data.Bits`](https://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Bits.html) module in the `base` package. You would definitely want functions like bitwise-or to be inlined. If the inlining boundary was at the library level, this would not be possible. GHC solves this by using a heuristic on the size of the function; if it's small (or otherwise inline-worthy), an "unfolding" (IR syntax tree) is put into the Interface File `Data/Bits.hi` (on which GHC's incremental compilation works) so that other modules can inline the unfolding. If `Data.Bits` was updated to a different implementation of bitwise-or, incremental compilation would "just work": The Haskell file would be detected as being changed, the Interface File would be updated, and all users of that unfolding would be recompiled.
It is not clear to me if the current RFC permits this type of cross-library inlining or not.

**Comment by nikomatsakis** [comment]
@nh2 

> Why was this chosen? Wouldn't it make sense to include source files in the dependency graph as well, so that you can skip parsing and even reading the file contents if the file modification time suggests that the file has not changed?

Eventually perhaps yes. But for the initial versions, we're targeting the things in compilation that are most expensive: LLVM and type-checking. Hashing the HIR also means that we can avoid doing recompilation for smaller, trivial changes, like tweaking a comment -- at least in some cases (it turns out that because that affects the line/col number of all statements, we would need to change at least debuginfo, but we can hopefully isolate the effects of that in the future.)

There are also just practical concerns. It's much easier to reduce the amount of the compiler we have to instrument.

> I'm not familiar with codegen units, and where their boundaries would be set, but if it's typically on the library/crate level, that could make some inlining problematic.

Users can always add `#[inline]` manually to indicate things that should be inlined widely (e.g., across crates).

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/34956 :confetti_ball:

**Comment by nh2** [comment]
@nikomatsakis Thanks for your explanation.

**Comment by brson** [comment]
@michaelwoerister is this still the best tracking issue for incremental? What's the current status?

**Comment by nikomatsakis** [comment]
I forgot this issue existed. The preferred tracker is https://github.com/rust-lang/rust-roadmap/issues/4. In fact, I'm just going to close this issue.

**Comment by kmcallister** [comment]
@nh2: It's frustrating (and hardly uncommon) for people to show up and say we "just need to copy Haskell" while ignoring the very real differences between the languages. In this case, the most important difference is that a whole Rust crate is semantically a single compilation unit, in fact a single syntax tree. Any `.rs` file in a crate can use stuff from any other `.rs` file, without any kind of forward declaration. This simply isn't true for the `.hs` files in a Haskell package. Mutually recursive imports will give you an error:

```
$ ghc --make Main.hs
Module imports form a cycle:
         module ‘Foo’ (./Foo.hs)
        imports ‘Bar’ (./Bar.hs)
  which imports ‘Foo’ (./Foo.hs)
```

The only way around this is the tedious and error-prone approach of writing a [hs-boot file](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/separate_compilation.html#how-to-compile-mutually-recursive-modules), equivalent to writing header files in C. In practice almost nobody does this; they simply structure their programs so the module dependency graph is acyclic. In terms of the build system (*not* in terms of packaging / versioning), this is like placing every `.rs` file into its own crate.

So, most of the features you highlight in `ghc --make` are present in Rust -- but they're features of Cargo, not rustc! True incremental compilation, within a single unit of mutually-referential stuff, is to my knowledge not a problem GHC tries to solve.
