### ISSUE TITLE
Unable to chain-access tuple types

### ISSUE THREAD

**Issue by ustulation** [rust-lang/rust#23694]
{Copying from here: http://stackoverflow.com/questions/29250677/unable-to-chain-access-tuple-types}
Given:
```
struct NameType([u8;64]);
name: (NameType, NameType);
```
i can do:
```
let def = &name.0   OR   &name.1
```
but i cannot do:
```
let def = &name.0.0   OR   &name.1.0
```
to access the internals. I have to do it twice:
```
let abc = &name.0;
let def = &abc.0;
```
why am i unable to chain it to access inner sub-tuples, tuple-structs etc?
```
rustc 1.0.0-nightly (ecf8c64e1 2015-03-21) (built 2015-03-22)
```

**Comment by rprichard** [comment]
`&name.0.0` doesn't work because `0.0` is a floating-point literal.  Either `(&name.0).0` or `&name.0 .0` works.

The compiler prints a help notice for `&name.0.0`:
```
test.rs:9:24: 9:24 help: try parenthesizing the first index; e.g., `(foo.0)`
```

Issue #20287 requested that `&name.0.0` work, but it was closed.  That issue has relevant links (e.g. the tuple indexing RFC and the [weekly minutes](https://github.com/rust-lang/meeting-minutes/blob/master/weekly-meetings/2014-08-26.md#tuple-indexing) where this issue was discussed).

**Comment by steveklabnik** [comment]
Yes, this is currently not a bug, as @rprichard mentions.
