### ISSUE TITLE
Write impl on Vec<u8> is easy to misuse

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#23768]
```rust
use std::io::{Write};

fn main() {
    let mut vec = b"a".to_vec();
    let _ = write!(&mut vec, "b");
    println!("{:?}", vec);
    // [97, 98]

    let _ = write!(vec, "b");
    println!("{:?}", vec);
    // [98, 98]
}
```

**Comment by sfackler** [comment]
For clarity, the second call to `write!` ends up using the `Write` impl on `&mut [u8]`.

cc @erickt I had concerns about this kind of thing when these impls were being introduced but I thought I convinced myself that this kind of thing couldn't happen. Did something change in the way we designed these impls since then?

**Comment by sfackler** [comment]
Possible solutions are to either remove the impl for `&mut [u8]` or update `write!` to prevent it from invoking `DerefMut`. Seems to me like the second is the better approach.

**Comment by kballard** [comment]
I believe the reason for the `&mut *$dst` was because it was considered a good thing to require callers to explicitly pass `&mut` references. I think we've actually gone back and forth on that a few times. Are we committed now to allowing callers to just say `write!(someValue, "...")?
