### ISSUE TITLE
Improve docs differentiating `Borrow` and `AsRef`

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#24163]
Spawned of off #24140

> This should be better documented, but there's definitely a reason that things are set up this way.
> ...
> ... it may be worth opening a separate issue for improved documentation and missing impls on AsRef.

**Comment by steveklabnik** [comment]
Notes from talking to @aturon 

borrow is used in things like hashmap, where you have a key, and the map needs to store the owned version, but you want to look things up by the borrowed version. `HashMap<String, i32>`, but you want to look up by string literals: `&str`.

for most types, you want T and &T. but for things that take slices, there's a few different slice types. Borrow is good for this

it's more restrictive than asref, because the assumption is the borrow is the same wrt hashing or comparison: String, &str, and &String all hash to the same value.

AsRef: you can get a different reference out of this. that's it. a conversion, not an equivalence.

anything htat impls borrow should implement asref, but no blanket because of coherence
