### ISSUE TITLE
AtomicPtr Can't Point To Unsized Types

### ISSUE THREAD

**Issue by njwhite** [rust-lang/rust#24223]
rustc fails to compile the code below:

````
pub trait A {
	fn a(&self);
}
struct B {
	b: i32
}
impl A for B {
	fn a(&self) {}
}

fn main() {
	let mut b = B {b: 1};
	let mut a: &mut A = &mut b;
	let ptr = std::sync::atomic::AtomicPtr::new(a);
}
````
With the error:
````
demo.rs:16:12: 16:26 error: the trait `core::marker::Sized` is not implemented for the type `A` [E0277]
demo.rs:16 	let ptr = AtomicPtr::new(a);
           	          ^~~~~~~~~~~~~~
demo.rs:16:12: 16:26 note: `A` does not have a constant size known at compile-time
demo.rs:16 	let ptr = AtomicPtr::new(a);
           	          ^~~~~~~~~~~~~~
error: aborting due to previous error
calc.git $ rustc --test demo.rs 
demo.rs:14:12: 14:45 error: the trait `core::marker::Sized` is not implemented for the type `A` [E0277]
demo.rs:14 	let ptr = std::sync::atomic::AtomicPtr::new(a);
           	          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
demo.rs:14:12: 14:45 note: `A` does not have a constant size known at compile-time
demo.rs:14 	let ptr = std::sync::atomic::AtomicPtr::new(a);
           	          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
````
Shouldn't an atomic pointer be able to point to something with a given trait? (i.e. shouldn't the bounds on AtomicPtr be <unsized T>?)

**Comment by Thiez** [comment]
That would be a nice feature, but since unsized types and trait objects are both twice as large as a normal pointer it can't work that way. Both x86 and x64 have atomic instructions that are wide enough to operate on 64 and 128 bits respectively, but as far as I'm aware ARM does not have that. In general I think the widest atomic instructions on most platforms tend to be 1 pointer wide.

**Comment by alexcrichton** [comment]
Yes as @Thiez pointed out this is currently intentional as it would require expanding the set of atomic intrinsics required, which we currently have not done!

**Comment by alexcrichton** [comment]
@bholley if `T` is not a sized type (like `str`), then `*mut str` is actually 2 pointers large instead of 1 (unlike `*const String`, which is one pointer large).

In that sense the implementation of `AtomicPtr` is radically different for `T: ?Sized`, which is what's not implemented yet (doubleword atomics)

**Comment by bholley** [comment]
Right, I get that - I'm suggesting that we make that constraint explicit in the API [1], since currently the |T| in |AtomicPtr<T>| is not constrained to be |Sized|.

[1] https://doc.rust-lang.org/std/sync/atomic/struct.AtomicPtr.html

**Comment by apasel422** [comment]
@bholley It actually is constrained to be `Sized`; [type parameters default to `Sized` unless given the `?Sized` bound](https://doc.rust-lang.org/book/unsized-types.html#sized).

**Comment by bholley** [comment]
Oh I see! Thanks for the explanation and sorry for the confusion. :-)

**Comment by ryoqun** [comment]
Just found this issue recently. :)

Quick question. Because rustc nightly has AtomicU128 on some platforms, that means we theoretically can implement nightly `AtomicPtrUnsized` or `AtomicSlice` for that platforms?
