### ISSUE TITLE
Don't allow exporting types from crates unless all arguments of impl functions are also exported

### ISSUE THREAD

**Issue by gsingh93** [rust-lang/rust#24299]
When writing a library I realized that I had exported some types so that they could be used outside the library, but some of the functions in the impl contained arguments that weren't exported. While I believe it's still possible to call functions like this, there should probably still be a warning.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!

**Comment by gsingh93** [comment]
Can you use high five bot to move this over to the RFCS repo?
