### ISSUE TITLE
`include_bytes!` should add file dependencies like `include_str!`

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#24348]
This causes cargo to misbehave: https://github.com/rust-lang/cargo/issues/1510

Tagging as E-easy, since @tomaka [has tracked down](https://github.com/rust-lang/cargo/issues/1510#issuecomment-92031760) the appropriate fix.

**Comment by tbelaire** [comment]
I'm going to try and fix this.

**Comment by tbelaire** [comment]
After reading the files `libsyntax/ext/source_util.rs` and `libsyntax/coremap.rs`, I have come up with a plan.
This is a little bit tricky, since with `include_str!`, we know that we are including utf-8 content, so it's safe to store the source as a String in a `FileMap`.  We don't know that for `include_bytes!`, but I don't think we actually need to track the contents anyways, so I'm passing `""` to `new_filemap`.
Currently building, I'll see if that fixes it.

**Comment by tamird** [comment]
This should have been closed by #24423. Can someone with power close?

**Comment by alexcrichton** [comment]
Indeed!
