### ISSUE TITLE
It's no longer possible to implement From in certain cases

### ISSUE THREAD

**Issue by nstoddard** [rust-lang/rust#24359]
I'm working on a linear algebra library where I have generic vectors and I use the `From` trait to convert between different types of vectors. I have code similar to the following:

```
struct Vec2<T> {x: T, y: T}

impl<T, U: From<T>> From<Vec2<T>> for Vec2<U> {
  fn from(x: Vec2<T>) -> Self {
    Vec2{x: From::from(x.x), y: From::from(x.y)}
  }
}
```

(The real code uses `NumCast` for the bound on U, instead of `From`, but I've changed it so the code is simpler and doesn't require external libraries.)

This used to work fine, but at some point in the past couple weeks, it stopped working and now gives this error:

```
main.rs:3:1: 7:2 error: conflicting implementations for trait `core::convert::From` [E0119]
main.rs:3 impl<T, U: From<T>> From<Vec2<T>> for Vec2<U> {
main.rs:4   fn from(x: Vec2<T>) -> Self {
main.rs:5     Vec2{x: From::from(x.x), y: From::from(x.y)}
main.rs:6   }
main.rs:7 }
main.rs:3:1: 7:2 note: conflicting implementation in crate `core`
main.rs:3 impl<T, U: From<T>> From<Vec2<T>> for Vec2<U> {
main.rs:4   fn from(x: Vec2<T>) -> Self {
main.rs:5     Vec2{x: From::from(x.x), y: From::from(x.y)}
main.rs:6   }
main.rs:7 }
```

Edit: it appears that my impl is conflicting with `impl<T> From<T> for T`. Is there a way to write my impl in a way that doesn't conflict with this one?

**Comment by alexcrichton** [comment]
Unfortunately it's not possible to write an impl such as this because you would need to inform the compiler that `T` != U` which is not currently expressible. This would likely be served by a language feature called specialization where multiple overlapping implementations would be allowed but they'd be prioritized accordingly.

This is working as expected, though, so I'm going to close this. Thanks regardless for the bug report!
