### ISSUE TITLE
Rustdoc output slightly nondeterministic

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#24473]
There's a bit of nondeterminism in rustdoc output across runs even when the source doesn't change: https://github.com/sfackler/rust-openssl/commit/1cb83ffe9b974980704b7e809aa7279cf02a7252 I'm guessing it's due to randomized HashMap iteration order.

It'd be nice to switch to a non keyed Hasher or maybe just TreeMaps in rustdoc to avoid "phantom" documentation updates.

**Comment by jakub-** [comment]
May be as simple as changing `HashMap` to `rustc::util::FnvHashMap` in https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/render.rs.

**Comment by Gankro** [comment]
Using @jakub-'s solution barring catastrophe

**Comment by sfackler** [comment]
This still appears to be present in other contexts than the one that was fixed: https://github.com/sfackler/rust-openssl/commit/bca2a367e456a90c355d4745d3ddb282a1466961

**Comment by est31** [comment]
PR #35984 has been first included in the 1.13 release. Still, there is some non-determinism left, inside the search index. See [this diffoscope output](https://tests.reproducible-builds.org/debian/dbd/testing/amd64/rustc_1.14.0+dfsg1-3.diffoscope.html#rust-doc_-.--.--dfsg---_all.deb-data.tar.xz-data.tar-.-usr-share-doc-rust-doc-html-search-index.js-js-beautify---).

I think the issue is that the search index gets sorted by the order in which rustdoc finishes the build of the crates. We'd need a better mechanism in order to get determinism. Maybe a final pass to sort by the crate name?

**Comment by est31** [comment]
Hmm, as of 1.14 it didn't sort, but since commit #38105 which was first included in 1.15, it does sort. So this sub-issue can be viewed as fixed.

**Comment by kzys** [comment]
Yep. I couldn't reproduce the issue on master (786ccc336d).

The only concern I have is that tests.reproducible-builds.org still shows `rust-​doc_1.​28.​0+dfsg1-​2_all.​deb` is different.
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/arm64/diffoscope-results/rustc.html

**Comment by kzys** [comment]
searchindex.js is generated by mdbook, not rustdoc. I think we can close this issue.

**Comment by mnd** [comment]
@kzys Issue from 1.28.0 release already solved in rust-lang-nursery/mdBook#692 
Currently I working on Rust 1.28.0 package for GuixSD and I without rust-lang-nursery/mdBook#692 patch I got same reproducibility issue.

**Comment by kzys** [comment]
Awesome! I am not sure how Debian gets docs, but maybe we need to upgrade mdbook here?

https://github.com/rust-lang/rust/blob/b7c6e8f1805cd8a4b0a1c1f22f17a89e9e2cea23/src/tools/rustbook/Cargo.toml#L11
