### ISSUE TITLE
Warn when transmuting between non-#[repr(C)] structs

### ISSUE THREAD

**Issue by P1start** [rust-lang/rust#24545]
```rust
fn main() {
    struct Foo(u16);
    struct Bar(u8, u8);
    unsafe { std::mem::transmute::<Foo, Bar>(Foo(1)); }
}
```

Since struct layout is undefined, this code is technically incorrect, as the representation of `Foo` and/or `Bar` could change in future versions of Rust. It would be nice if a lint could detect this sort of thing and warn about it.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
