### ISSUE TITLE
Name collision between extern "C" functions can cause undefined behavior in safe code

### ISSUE THREAD

**Issue by dgrunwald** [rust-lang/rust#24561]
I'm generating `extern "C"` functions using macros. Since it's currently not possible to use `$concat_ident` for function names, I can't give these functions unique names.

I was hoping for rust's name mangling to take care of the issue; but unfortunately this doesn't work if the macro is used twice in the same function. This usually results in internal compiler errors for me, but on the playpen machine it's possible to produce undefined behavior in safe code:

    fn main() {
        {
            extern "C" fn test(a: &mut i32) {
                println!("a: {:?}", a);
                *a = 1;
            }
        }
        {
            extern "C" fn test(b: &i32) {
                println!("b: {:?}", b);
            }
            test(&1);
        }
    }

Expected output: `b: 1`
Actual output: `a: 1`
`playpen: application terminated abnormally with signal 4 (Illegal instruction)`

**Comment by alexcrichton** [comment]
Hm this sounds like a bug, the compiler should be giving each of these `extern` functions a different symbol...

**Comment by nagisa** [comment]
On the nightlies it is an ICE: 

error: internal compiler error: symbol `_ZN4main4test10__rust_abiE` already defined
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace

This issue is a duplicate of https://github.com/rust-lang/rust/issues/16403

**Comment by ruud-v-a** [comment]
Not sure if it is the same bug, but this also ICEs:

```
fn main() {}

mod foo {
    extern {
        fn main();
    }
}
```

**Comment by mattico** [comment]
I believe I'm having the same issue with nightly-2016-02-22. I posted a backtrace over here https://github.com/SkylerLipthay/interpolate_idents/pull/7 and I'll be trying to debug this sometime soon. Unless the issue is very simple I won't have the ability to fix it, but I should be able to identify what the problem is.

**Comment by dgrunwald** [comment]
Closing in favor of #26201, that issue has a more up-to-date title.
