### ISSUE TITLE
The `Drop` flag is a footgun for `#[repr(C)]`

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#24585]
(imported from improperly closed bug #18380)

As suggested by @huonw:

> the `improper_ctypes` lint should check for `repr(C)` on the RHS of a `Drop` impl. ``"warning: implementing Drop changes the representation of the type, conflicting with `repr(C)`"``.
>
> (It should presumably also check for `#[unsafe_no_drop_flag]` and not warn if it exists.)

Until #5016 is done, we really should lint for this scenario.  [People have run into it](http://internals.rust-lang.org/t/priorities-after-1-0/1901/67)

**Comment by pnkfelix** [comment]
triage: P-low

**Comment by pnkfelix** [comment]
oops.

triage: P-high

(but nonetheless not 1.0)

**Comment by geofft** [comment]
I feel like this should be stronger than a medium-priority lint. I feel like rustc should reject programs that attempt to `impl Drop` on a `#[repr(C)]` struct, for as long as that changes the size of that struct.

In particular, not fixing this by 1.0 would foreclose the ability to change the drop flag after 1.0, since that would change the size / ABI of `#[repr(C)]` structs, right? Or is ABI stability not a guarantee of `#[repr(C)]`?

**Comment by pnkfelix** [comment]
Yeah this label got auto renamed.   I'm up'ing the priority

**Comment by pnkfelix** [comment]
triage: P-high 

I'll assign to self too

**Comment by pnkfelix** [comment]
( @geofft I'm pretty confident we could fix this post 1.0, e.g. adding new warnings is allowed, and the representation issue would be "just a bug to be fixed."  Nonetheless I I do I do want I do want to fix.)
