### ISSUE TITLE
std::convert docs mention the "to" convention, but don't implement it

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#24712]
The [std::convert docs](https://github.com/rust-lang/rust/blob/6790b0e51967b1487728d155e0800a1ed03a30d3/src/libcore/convert.rs#L13-L14) say:

> They follow the standard Rust conventions of as/**to**/into/from.

(emphasis mine)

However, there isn't a `To` trait, and none of [`AsMut`](http://doc.rust-lang.org/std/convert/trait.AsMut.html) / [`AsRef`](http://doc.rust-lang.org/std/convert/trait.AsRef.html) / [`From`](http://doc.rust-lang.org/std/convert/trait.From.html) / [`Into`](http://doc.rust-lang.org/std/convert/trait.Into.html) implement a `to` method. Not sure if this is a typo or an oversight resulting in a missing trait.

**Comment by steveklabnik** [comment]
Typo, I think. /cc @aturon

**Comment by shepmaster** [comment]
I'd guess that `Into<Foo> for &Bar` is really the equivalent of the old `Bar::to_foo(&self)`, while `Into<Foo> for Bar` is the equivalent of `Bar::into_foo(self)`. If correct, maybe that's what can be added somewhere.

**Comment by aturon** [comment]
Yes, this comment was left in from the initial implementation, which included `To`.

What we found eventually was that bounding by `To` doesn't make a lot of sense; as @shepmaster points out, `Into` can cover both the `to` and `into`-style conversions, and using `Into` instead gives the caller more flexibility (since they can pass in an owned object of the target type, or one that requires conversion).
