### ISSUE TITLE
staticlib is ridiculously large.

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#24764]
An empty `main.rs` compiled with `$ rustc main.rs --crate-type=staticlib -Copt-level=3 -Clto -Cdebuginfo=0` results in `libmain.a` which is a whopping 3,669 KB.
For comparison the `.rlib` is only 4 KB.

**Comment by nagisa** [comment]
staticlib must include all its rust dependencies. Use `--emit=obj` to produce object file without bundled dependencies.

**Comment by alexcrichton** [comment]
@nagisa is correct in that a staticlib must include all rust and native dependencies, so if we take a look at the actual contents of the archive (for me it's 1.9MB) we get:

* `main.o` - 163K, the public symbols here being `rust_begin_unwind`, `rust_eh_personality`, `rust_eh_personality_catch`, and `rust_stack_exhausted`. Some of these are required by `morestack.o`, but in general this is not a source of much bloat (although in this specific case some of them could probably be optimized away). Note that because of LTO this is the only rust code in the archive.
* libbacktrace - 208K
* compiler-rt - 1012K
* jemalloc - 976K
* assorted libstd deps - 30K

So the "ridiculously large" aspects of this are the compiler-rt and jemalloc libraries. This will all be stripped away as necessary by the linker when producing a final library, and it is always why we recommend `--gc-section` wherever possible. 

In general I don't think that this bug is super actionable, but some concrete steps we could take are:

* Add the ability to select jemalloc or the system malloc at link-time
* Add the option to omit libbacktrace (it's only used for `RUST_BACKTRACE=1`)
* Somehow pre-link compiler-rt so we don't have to include the entire library

I don't think any of these will necessarily reap a large benefit.

**Comment by steveklabnik** [comment]
Yup, closing as not exactly actionable. Improvements like Alex is talking about could be nice, but should probably be thier own tickets, rather than some sort of general heading, especially when it's not clear that they'll be a significant improvement.
