### ISSUE TITLE
In core::ptr, weird thing about impl<T: ?Sized>

### ISSUE THREAD

**Issue by GBGamer** [rust-lang/rust#24794]
So the implementation itself is for T: ?Sized, but the actual functions themselves are for T: Sized.

i.e.

```rust
#[lang = "const_ptr"]
impl<T: ?Sized> *const T {
    #[inline]
    pub fn is_null(self) -> bool where T: Sized {
        self == 0 as *const T
    }
}
```
This makes absolutely no sense. First: why would you `impl<T: ?Sized>` and then not allow you to call any functions on `T: !Sized`. Second, why can you only call `is_null` on `T: Sized`? Makes absolutely no sense.

**Comment by alexcrichton** [comment]
This is actually currently intentional! The `T: ?Sized` means that the `impl` block is maximally generic by default (we only have one). Each method then adds bounds as necessary, and in this case the `is_null` method currently requires that `T` is sized. 

At the time this function was written, it was an ICE if `T` was not sized (hence `*const T` was a fat pointer). It is intended that one day that ICE and/or restriction will be lifted so this method will not have a `T: Sized` bound.

**Comment by GBGamer** [comment]
Ah okay cool. We should probably make a comment about that?

**Comment by alexcrichton** [comment]
I'd be down with that!
