### ISSUE TITLE
Unable to infer type when inside a trait implementation

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#25029]
This code: 

``` rust
trait Foo<T> {
    fn f1(&self);
    fn f2(&self);
}

struct Bar;

impl<T> Foo<T> for Bar {
    fn f1(&self) {
        self.f2();
    }

    fn f2(&self) {
    }
}
```

Produces:

```
<anon>:9:14: 9:18 error: unable to infer enough type information about `_`; type annotations required [E0282]
<anon>:9         self.f2();
                      ^~~~
```

Replacing `self.f2()` with `Foo::<T>::f2(self)` removes the error, but I think Rust is supposed to understand where `f2` should come from.

**Comment by nikomatsakis** [comment]
The problem is not that Rust doesn't know where `f2` comes from, but that the type parameter `T` on that impl (and trait) is completely unconstrained. That is, you can call `Foo::<X>::f2(self)` for ANY `X` in this example, so the compiler is refusing to guess that you happened to mean `T` in this case. I think this is working as designed, modulo the fact that this error message is so unclear.

**Comment by steveklabnik** [comment]
Triage: closing since this is correct behavior.
