### ISSUE TITLE
Traits which mention `Self` in `?Sized` locations should be object safe

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#25042]
Repro: http://is.gd/4sRWGT

Inline:

```rust
struct X<T: ?Sized>(Box<T>);

trait SpecialFnBox {
    fn do_boxed(self: Box<Self>, X<Self>);
}

impl<F: FnOnce(X<F>)> SpecialFnBox for F {
    fn do_boxed(self: Box<F>, x: X<F>) {
       (*self)(x)
    }
}

fn main() {
  let x: Box<SpecialFnBox> = Box::new(|x| { });
}

// Rustc should generate this entirely valid impl and allow SpecialFnBox objects.
impl SpecialFnBox for SpecialFnBox {
    fn do_boxed(self: Box<SpecialFnBox>, x: X<SpecialFnBox>) {
        self.do_boxed(x)
    }
}
```

The above code (without the "generated" impl) should compile without error, but instead errors, saying that `SpecialFnBox` is not object safe.

**Comment by P1start** [comment]
I don’t think this could be allowed. `SpecialFnBox` assumes that `self` and `x` have the same type (if we pretend that `X` == `Box`), but that guarantee can’t be upheld when `Self` turns into a trait object type—the two `SpecialFnBox` types passed to `do_boxed` could be different types underneath the trait object.

**Comment by kballard** [comment]
I'm confused as to what `?Sized` has to do with anything. The trait isn't object-safe because it references `Self`, not because `Self` has a compile-time size. In the compiler-synthesized `impl SpecialFnBox for SpecialFnBox`, what is it supposed to do? You have it taking an `X<SpecialFnBox>`, but it can't use that to call the `.do_boxed()` method of the underlying concrete value because that method takes an `X<Self>`, not an `X<SpecialFnBox>`. It can't convert the` X<SpecialFnBox>` to `X<Self>` because it may be a boxed object *of a different implementation*.

**Comment by reem** [comment]
I'm convinced.
