### ISSUE TITLE
Repeated and incorrect "Implementors" items

### ISSUE THREAD

**Issue by murarth** [rust-lang/rust#25061]
The docs pages for [Send](http://doc.rust-lang.org/std/marker/trait.Send.html) and [Sync](http://doc.rust-lang.org/std/marker/trait.Sync.html) show duplicated and incorrect items in the "Implementors" section.

Specifically, an incorrect positive impl for `Rc` is present and the correct negative impl is present twice.
Also, impls for `Arc` and `ArcInner` appear multiple times, with and without trait bounds and `where` clauses, with `Arc` having three appearances:

``` rust
impl<T> Send for Arc<T> where T: Send + Sync
impl<T: Sync + Send> Send for Arc<T>
impl<T> Send for Arc<T>
```

**Comment by bluss** [comment]
Also noting that ArcInner is private and should not appear.

**Comment by defuz** [comment]
Not only marker traits. From the bottom of [Iterator doc page](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.collect):

```
...
impl<'a> Iterator for Utf16Items<'a>
impl<I> Iterator for Utf16Encoder<I> where I: Iterator<Item=char>
impl<'a> Iterator for SplitWhitespace<'a>
impl Iterator for ToLowercase
impl Iterator for ToUppercase
...
impl<'a> Iterator for Utf16Items<'a>
impl<I> Iterator for Utf16Encoder<I> where I: Iterator<Item=char>
impl<'a> Iterator for SplitWhitespace<'a>
impl Iterator for ToLowercase
impl Iterator for ToUppercase
impl<I: Iterator<Item=u16>> Iterator for DecodeUtf16<I>
```

**Comment by mulkieran** [comment]
It should be noted (and I expect is related), that entries appear in what seems to be a completely random order.

**Comment by mulkieran** [comment]
It should also be noted that some entries have links where others do not, see example in: https://github.com/rust-lang/rust-www/issues/841.

**Comment by QuietMisdreavus** [comment]
Update: this is still a bit of a thorn, though some of it has been fixed. The repetition is because of a thing rustdoc likes to do where dependent crates can fill out a javascript "implementors" file to let their implementations show up on the trait's page, even though the struct is being documented later than the trait. However, this does not take into account whether the trait or the struct have been re-exported. So in std, where several traits and structs come from other crates and are re-exported to be part of std as well, these implementations show up in both the regular render *and* the implementors javascript file.

On a brighter note, it looks like rustdoc prints the trait bounds on all these impls now, so at least that part's been fixed.

**Comment by mizuno-gsinet** [comment]
Maybe off-topic, but what's the point of these JavaScript-generated items being wrapped in tables?

https://github.com/rust-lang/rust/blob/26373fb4baa9c5b8a7a1e2821fcfa930a85d327d/src/librustdoc/html/static/main.js#L2087-L2092

**Comment by jsha** [comment]
Related: #85418

**Comment by fmease** [comment]
I can no longer reproduce this: Only *one* impl is shown for `Arc` on pages of [`Sync`](https://doc.rust-lang.org/std/marker/trait.Sync.html) & [`Send`](https://doc.rust-lang.org/std/marker/trait.Send.html).
