### ISSUE TITLE
TCPStream API should work with strings too

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#25066]
See: http://www.reddit.com/r/programming/comments/34obhi/where_rust_really_shines/cqwsvxs (not the first time I've seen people complaining about TCP)

Not everyone cares about having to allocate backing byte buffers; many prefer to work with Strings. `TCPStream` lets you read a string, but not write one -- we should have utility methods in `Read`/`Write` or utility methods on `TCPStream` itself.

cc @aturon @alexcrichton 

Also, an API like http://golang.org/pkg/bufio/ would be nice. (For buffered reading of lines, etc)

**Comment by alexcrichton** [comment]
I think this issue is more appropriate for the RFC repo as it sounds like you're interested in expanding the core `Read`/`Write` traits (it's highly unlikely to special-case `TcpStream` here. Could you open an issue over there instead?

> Also, an API like http://golang.org/pkg/bufio/ would be nice. (For buffered reading of lines, etc)

Note that many of these niceties are provided by the `BufRead` trait, you just must explicitly create a buffered reader/writer.
