### ISSUE TITLE
Make panic! error output compatible with GCC error message

### ISSUE THREAD

**Issue by krig** [rust-lang/rust#25151]
This is what I see right now when a test fails running `cargo test`:

```
running 1 test
test basic_conversion ... FAILED

failures:

---- basic_conversion stdout ----
    thread 'basic_conversion' panicked at 'assertion failed: &roman(2015) == "MMXIV"', src/main.rs:34
```

When running this for example via the emacs `compile` feature, if the location was printed at the start of the line instead of the end, the key bindings for jumping to the error location would work. There are numerous other tools that also understand the GCC error format.

It'd be a nice feature to reorder the output so that `src/main.rs:34` appeared at the beginning of the line instead of the end.

**Comment by steveklabnik** [comment]
Triage: https://github.com/rust-lang/rust/pull/25152 was closed in favor of https://github.com/rust-lang/rfcs/pull/1100, which ended up closed. However, it was closed in order to merge https://github.com/rust-lang/rfcs/pull/1328, which is being tracked at https://github.com/rust-lang/rust/issues/30449. Which is closed because it's been implemented.

So, it seems like all of the prerequisite work is done here.

**Comment by krig** [comment]
Oops, I forgot to close this when creating #25152. Closing, thank you.
