### ISSUE TITLE
Cannot express never returning closure (FnOnce() -> !)

### ISSUE THREAD

**Issue by diwic** [rust-lang/rust#25325]
Here's a minimal example that shows the problem:

    fn never_return<F: FnOnce() -> !>(f: F) -> ! {
        f();
    }

which fails with:

    error: expected type, found `!`
         fn never_return<F: FnOnce() -> !>(f: F) -> ! {

...AFAICS, there's no good reason this syntax is not allowed.

**Comment by pnkfelix** [comment]
The reason is the combination of : 

 * `F(A, B) -> T` is shorthand for `F <(A, B), T>`
 * `!` is itself not a type; it cannot be plugged into the `A` `B` nor `T` above.

If we were to readd it as a type (and note that some effort did go into removing it), that would probably require an RFC.  (And also, I'd want a `?Marker` on such type parameter analogous to `?Sized`; something like `?Converge`...)

**Comment by pnkfelix** [comment]
(Alternatively we could make a special case for the `F(A, B) -> T` shorthand where `F(A, B) -> !` would expand in some entirely different way -- but again, that would require an RFC.)

**Comment by steveklabnik** [comment]
Agreed with @pnkfelix .
