### ISSUE TITLE
`str::contains` is very slow for substring checks

### ISSUE THREAD

**Issue by netvl** [rust-lang/rust#25483]
Originally found in [SO question](http://stackoverflow.com/questions/30272751/generate-strings-and-identify-substrings-in-rust).

This Rust code
```rust
fn main(){

    let needle   = (0..100).map(|_| "b").collect::<String>();
    let heystack = (0..100_000).map(|_| "a").collect::<String>();

    println!("Data ready.");

    for _ in 0..1_000_000 {
        if heystack.contains( &needle ) {
            // Stuff...
        }
    }

}
```
Executes for up to three minutes on my machine (even with `-C opt-level=3`), while the equivalent Ruby or Python code:
```ruby
needle   = 'b' * 100
heystack = 'a' * 100_000

puts 'Data ready.'

1_000_000.times do
    heystack.include? needle
end
```
finishes in several seconds. Java variant finishes almost instantly (but that seems to be due to JIT optimizations).

It looks like that pattern searching for substrings could be severely optimized.

**Comment by bluss** [comment]
StrSearcher has a lot of panic branches that can probably avoided (slicing and unwrapping that will never happen).

**Comment by ArtemGr** [comment]
I wonder wether LLVM can move the comparison out of the loop and if not, why?

**Comment by huonw** [comment]
I think this is fundamentally algorithmic problem, since `StrSearcher` is performing a [naive string search](https://github.com/rust-lang/rust/blob/8fdb3a4ad902162f3f6809e007a79342c2ce19db/src/libcore/str/pattern.rs#L404-L414) at the moment. Eliminating unnecessary panics etc should probably wait until that problem is resolved (I could be wrong).

**Comment by bluss** [comment]
Oh wow, I thought that was something that we had already fixed.

**Comment by gereeter** [comment]
The algorithmic problem was fixed, but this fix got disabled in the switch to the pattern API. The two-way search code is [still present](https://github.com/rust-lang/rust/blob/8fdb3a4ad902162f3f6809e007a79342c2ce19db/src/libcore/str/mod.rs#L873-1166) as dead code.

**Comment by DanielKeep** [comment]
For comparison, I just did a straight translation of a [C implementation of BMH](http://en.wikipedia.org/wiki/Boyer%E2%80%93Moore%E2%80%93Horspool_algorithm#Example_implementation_.28C.29).  Results for the test in the SO question were:

```
test tests::boyermoore_horspool_memmem::case_tasos  ... bench:      5241 ns/iter (+/- 222)
test tests::naive::case_tasos                       ... bench:   1567384 ns/iter (+/- 64776)
test tests::std_str_find::case_tasos                ... bench:    864885 ns/iter (+/- 45622)
```

Where `naive` is just a 100% naive char-by-char search.

**Comment by alexcrichton** [comment]
triage: I-nominated

**Comment by bluss** [comment]
@DanielKeep Can it be adapted to the pattern API?

**Comment by DanielKeep** [comment]
@bluss I don't see why not; the signature is just `(&str, &str) -> Option<usize>`, but given that there's already a (not being used) higher-performance searcher in the stdlib, it'd probably make more sense to restore that *first* and then consider further improvements independently.  So long as what's there isn't pathologically bad, it'll still be a considerable improvement.  :)

(Not that my BMH implementation is likely to be an improvement: it was *literally* just copy, pasted, and translated from the C reference code.  Hell, it uses... *indexing*.  I was in a hurry.  :P)

**Comment by Kimundi** [comment]
Yeah, after implementing the pattern API I haven't found the time to reintegrate the old fast searcher code yet. Part of the issue why I haven't done it directly is that the fast string searcher only supports unidirectional search, while with the Pattern API you'd want bidirectional search.

One way to resolve this is to just hack the naive and the fast search together into a hybrid that uses the fast search for forward iteration (which is all that happened before anyway), and the naive for backwards iteration, but due to me not fully understanding the fast algorithm I was reluctant to do that immediately..

**Comment by alexcrichton** [comment]
triage: P-medium

**Comment by bluss** [comment]
This is allegedly a very interesting improvement upon our two-way search algorithm. http://drops.dagstuhl.de/opus/volltexte/2011/3355/
