### ISSUE TITLE
Support search by return type in rustdoc

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#25511]
The idea came from [here](https://github.com/rust-lang/rust/issues/19956#issuecomment-102607371). For example, to find types which return [`Chunks`](https://doc.rust-lang.org/std/slice/struct.Chunks.html) I would expect you would search `fn: -> Chunks` in the rustdoc search bar.

cc @pornel @tomjakubowski

**Comment by pornel** [comment]
It's good to have an advanced option, but in my original case it probably wouldn't have helped me, because I didn't know the search supported advanced syntax at all.

Something more discoverable would have helped me, e.g. if search for "Chunks" by default also matched return types. If that's too noisy, then it could be a sort of faceted search letting me choose whether I want function names, argument types or return types.

**Comment by mitaa** [comment]
This seems to kind of work currently (["-> box"](http://doc.rust-lang.org/nightly/std/?search=-%3E%20box), ["-> usize"](http://doc.rust-lang.org/nightly/std/?search=-%3E%20usize)), though I think this should be improved since the type-name in the search index seems to be very trimmed-down or omitted in most cases for some reason. (i.e. the original example doesn't work; ["-> Chunks"](http://doc.rust-lang.org/nightly/std/?search=-%3E%20Chunks))

**Comment by bluss** [comment]
`-> Chunks` only matches functions with 0 input arguments, because it matches the input arguments exactly too with that search.

**Comment by mitaa** [comment]
@bluss 
Thanks, it seems like it shouldn't be too hard to extend the syntax for this use-case then. Something like `... -> Chunks` or `* -> Chunks` maybe.

**Comment by mitaa** [comment]
This has now been implemented in #31639 using `* -> T`

**Comment by bluss** [comment]
nice, I'll have to try it out.

**Comment by bluss** [comment]
Fixed in #31639
