### ISSUE TITLE
Introduce DST-enabled Rc as unstable under a feature flag

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#25531]
It's irresponsible not to do it.

See #25515.

**Comment by Thiez** [comment]
Must we really have feature flags for everything? If the bug turns out to have an easy fix, surely just fixing the bug would be preferable to introducing *yet another* feature flag. Let's wait for a day so the bug can get discussed, and if it turns out to be a very hard problem the feature flag can always be introduced then. Alternatively, temporarily change the line
```rust
impl<T: ?Sized+Unsize<U>, U: ?Sized> CoerceUnsized<Rc<U>> for Rc<T> {}
```
to
```rust
impl<T: ?Sized+Copy+Unsize<U>, U: ?Sized> CoerceUnsized<Rc<U>> for Rc<T> {}
```
because the `Copy` bound will prevent types with a `Drop` implementation from being coerced for now (why don't we have a `Pod` trait anymore?), and removing the bound is probably backwards compatible.

**Comment by bluss** [comment]
We have feature flags for everything that's unstable. That's not really the problem, I just want it to be unstable while in development. We only have 6-week cycles now and why rush out something that's broken?

**Comment by alexcrichton** [comment]
The current system of stability attributes is known to not be bullet proof and doesn't cover the stability of `impl` blocks, for example, so I don't think we need to make sure that *everything* comes in under a feature gate, adding functionality like this is fine to land without it. Although there may be bugs no one's going to rely on the bug of double-drop, for example.

**Comment by bluss** [comment]
I think I'm overreacting a bit, I'm sorry for that. Especially given that the bug is not in Rc-DST at all!

**Comment by bluss** [comment]
Another data point: see bug #26352.

The feature is broken in the beta, which is unfortunate. With a feature flag we could have quality assured it before we stabilized it.

**Comment by apasel422** [comment]
`Rc` is DST-enabled:
```rust
use std::rc::Rc;

fn main() {
    let x: Rc<[i32]> = Rc::new([1, 2, 3]);
}
```
I think this can be closed.

**Comment by steveklabnik** [comment]
Yup, this should have been okay as of 1.2.
