### ISSUE TITLE
genders of the philosophers and inclusiveness

### ISSUE THREAD

**Issue by Licenser** [rust-lang/rust#25650]
I am a bit shocked by this decision and there is a part of the discussion that was put under the rug and I find it quite disappointing. I feel the merge made the situation worst, and less inclusive then it was before.

In short the it went from a 'crime of omission' to actively and knowingly being exclusive. Prior to the merge someone took a quote and put it in the docs (we can argue if that's good or bad and if quotes should be changed or not but that's not the issue I want to rise here). The quote had male pronouns instead of neutral ones, I see why that is something to consider to change. But at that point the worst the rust community can be blamed for is an oversight or if you want to go out of your way ignorance but not hostility.

Now with the merge there was a decision made, the decision was to use female pronouns despite it having been brought up that gender neutral ones were more appropriate. And no this is not going down the road 'but meh meh it's discriminating against dudes' - not the point. But it was brought up and bluntly ignored that there are people who identify with neither gender, not female nor male and that part of the demographic is often way worst of then female not to mention males.

So in the bottom line this merge moves a bit of ignorance in the docs to knowingly and purposefully being exclusive towards that part of the population.

In my eyes not a good move.

**Comment by pnkfelix** [comment]
@Licenser There has been significant discussion of the matter on the follow-up PR #25640 .

**Comment by Licenser** [comment]
damn how did I overlook that :( sorry mate, I only checked for issues on the topic not on new PR's..

**Comment by pnkfelix** [comment]
In particular we have some parties arguing like so: https://github.com/rust-lang/rust/pull/25640#issuecomment-103837654 and like so: https://github.com/rust-lang/rust/pull/25640#issuecomment-103860230 which seem to be fundamentally in opposition to the stance that you are taking in your own post.

I suspect that the project is going to need to establish formal guidelines for how to deal with gender, especially when writing documentation.  (It also seems like there is unlikely to be any solution that fails to offend someone...)

**Comment by pnkfelix** [comment]
(also, for those following along, AFAICT the original description is referring to PR #25585 ; there are particular comments in that thread that provide more context.)

I would cite particular comments, but I worry that citing them would be interpreted as implicitly supporting their content, which is not my intent.  (Rather, my intent would be to try to illustrate the variety of viewpoints that have led to the current situation.)  So, for now I will settle for linking to the whole PR.

**Comment by Licenser** [comment]
I totally understand, I mostly opened this issue since it looked like the part of the discussion was mostly left out.

**Comment by pnkfelix** [comment]
@Licenser can I politely request that you post your concerns to the ongoing diversity thread on internals?

 https://internals.rust-lang.org/t/diversity-on-the-governance-teams/2048/120

I suspect the discussion on that thread is likely to heavily weigh on any hypothetical policy or guidelines that the community establishes w.r.t. gender.

----

Also, would PR #25640 as currently written serve to resolve this issue?  My suspicion is that it may not, but I do not want to put words in your mouth.  I ask because I am trying to determine if this issue (#25650) can be tagged as fixed by #25640.

**Comment by CrisBRM** [comment]
How about you stop wasting valuable programmer time with your crappy non-issues that have no effect on the end result? Fork it if you don't like it, it has no bearing on how well it performs.

People like you are actually doing your kind a disservice by being so obnoxious and self-entitled.

**Comment by codyharrington** [comment]
Hey guys, we're bike-shedding here. Lets just focus on Rust, and not the genders of non-existent people in documentation.

**Comment by RubenAstudillo** [comment]
This is bikeshedding

**Comment by Licenser** [comment]
+1

**Comment by BurntSushi** [comment]
@CrisBRM Please respect the [code of conduct](http://www.rust-lang.org/conduct.html). It's OK to disagree, but please do so *constructively*. In particular, we should seek to not minimize the concerns of others. Thanks!

I'm locking this thread because further discussion should happen on our forums: https://internals.rust-lang.org/t/diversity-on-the-governance-teams/2048/120
