### ISSUE TITLE
Tracking issue for Ord::{min, max}

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#25663]
It's seems inconsistent that [floating-point types have a `min` method](https://doc.rust-lang.org/std/primitive.f64.html#method.min), but integer types don't.

And there's a standalone `min()` function that works with integer types, but it's [not defined for floating-point types](https://github.com/rust-lang/rfcs/issues/852).

I don't have a strong preference for either style, but I'd prefer that at least one way of computing min/max was available for both floating point and integer types alike.

**Comment by Aatch** [comment]
@aturon thoughts? Seems like adding an inherent method to integer types is the easiest way forward here.

Note that there are `partial_min` and `partial_max` functions for types that only implement `PartialOrd`.

**Comment by bluss** [comment]
The types are simply different since floats don't impl Ord and `cmp::min` is restricted to Ord. It seems to be in line with the design?

**Comment by aturon** [comment]
+1 for an inherent method. I think this is just an oversight.

**Comment by alexcrichton** [comment]
I believe @bluss commented to this effect already, but the idea here is that there is "one true `min` method" at `cmp::min`, but the floating point types use a slightly different algorithm (e.g. different guarantees about order and whatnot), hence they have their own methods.

I wouldn't be totally opposed to adding an inherent method, but we'd want to clearly document that it's just an alias to `cmp::min`

**Comment by nagisa** [comment]
-1 for an inherent (or any other, really) method. Float’s min and max are just bindings to libm f{min.max}{f,}, while `cmp::partial_{min,max}` have their own, sane if you will, semantics. Adding inherent methods for integral types will make many-ways-to-do-the-same problem worse.

**Comment by frewsxcv** [comment]
Ignoring the "many-ways-to-do-the-same problem" for a second, couldn't `min` and `max` just be generic 'provided methods' on the `Ord` trait?

**Comment by pornel** [comment]
For me this is a practical problem, because changing type needlessly changes syntax.

```rust
let a = 1.0;
let b = 2.0;
let c = a.max(b); // c = std::cmp::max(a,b)
```

I can't change `a = 1; b = 2` without rewriting the third line.

I often write performance-sensitive graphics code, which I prototype on floats for ease of writing, and then where appropriate change to use integers for speed/memory efficiency. 90% of calculations just work, and `max` is one of the warts that doesn't.

**Comment by Mark-Simulacrum** [comment]
@rust-lang/libs: Looks like this needs some thought; I've nominated. Possibly interesting for libz blitz discussion, too, since it relates to number types in wider library set; for example [`serde_json::Number`](https://docs.rs/serde_json/1.0.2/serde_json/struct.Number.html) doesn't implement min/max inherently, but should it?

I think that the things that have been brought up are:
 - Rewriting code to use integers when floats were used previously is made needlessly difficult because of this (https://github.com/rust-lang/rust/issues/25663#issuecomment-267128640)
 - Adds to the "many ways" to do this (https://github.com/rust-lang/rust/issues/25663#issuecomment-112873405)
 - Maybe we could just have these be provided by Ord by-default (https://github.com/rust-lang/rust/issues/25663#issuecomment-267113565)

**Comment by aturon** [comment]
We discussed this in triage today, and the libs team is in favor of adding these methods to `Ord`

**Comment by Mark-Simulacrum** [comment]
[De-nominating]

**Comment by aturon** [comment]
We're pretty much committed to this.

@rfcbot fcp merge
