### ISSUE TITLE
manpage out of date

### ISSUE THREAD

**Issue by rillian** [rust-lang/rust#25689]
In the 1.0.0 release (and master) the rustc and rustdoc man pages say they document version '0.13.0 March 2014'.

Looks like some of the contents are stable as well, e.g. the rust manpage suggests '-C target-cpu=help' for which rustc --help gives 'llc -mcpu=help'.

**Comment by cmr** [comment]
@rillian would you like to send a PR updating the man page (they're in https://github.com/rust-lang/rust/tree/master/man), or should someone else?

**Comment by rillian** [comment]
I prepared pull requests. We should probably figure out a way to update or generate these as part of the build though.

**Comment by brson** [comment]
Yeah, it least using a template to plugin the version number automatically would help.

**Comment by steveklabnik** [comment]
Changing to A-build as the immediate documenation situation has been addressed.

**Comment by sanmai-NL** [comment]
Current `master` has a man page title as if it's still Rust 1.2.0.
https://github.com/rust-lang/rust/blob/a76698b5eecb4b8addc43a4a58a739da39bcbaaa/man/rustc.1#L1

@steveklabnik, is there perhaps work underway, planned or desired to autogenerate the man pages?

**Comment by brson** [comment]
sanmai-NL, there's no such effort underway.

As a first step, I'd be interested in a patch that just fills in the version automatically.

In the long-term I'm not sure if producing the full man pages is desirable or not, but relates to the problem of man pages being useless on windows.

A reason the man pages aren't updated much may be that they are rarely seen. If this information was written as part of the published documentation, so more people could use it, then converted to man pages it may get more contributions.

**Comment by steveklabnik** [comment]
IIRC, there was some work in Cargo to do generated manpages.

**Comment by sanmai-NL** [comment]
@brson, see my PR #34254.

Reasons to keep the man pages:
1. The man pages are there, removing them is a bit of lost work then. If they're not desired because of Windows, then creating them should've been given more thought at the outset.
2. I think they are expected by users on Unix for utilities with so many command line options, such as `rustc`. Having them can be considered necessary for feature parity with `gcc`, `ocamlc`, basically any popular compiler.

I agree that writing man pages manually is undesirable. Have you seen [Docker Engine's man page production workflow](https://github.com/docker/docker/blob/9a8affb0ffdf6010fca6a1c8fb00c9e0a38845d6/man/README.md)? I personally would prefer that you'd start using [Asciidoctor](http://asciidoctor.org/docs/user-manual/#man-pages), since that basically the best OSS technical documentation system around, and it can render man pages as well as DocBook, responsive (X)HTML5, PDF, etc.

What about thinking differently, not along the lines of superseding the man pages with ‘the published documentation’ but rather considering them part of ‘the documentation’ and accounted for as such.

**Comment by steveklabnik** [comment]
The recent man page work on cargo first used ASCIIDOC, but we rejected it in favor of keeping the consistency of Markdown everywhere.
