### ISSUE TITLE
char::{to_uppercase, to_lowercase} are broken and should not be marked stable

### ISSUE THREAD

**Issue by niconii** [rust-lang/rust#25729]
The description of [`char::to_uppercase`](https://doc.rust-lang.org/std/primitive.char.html#method.to_uppercase) reads:
> The case-folding performed is the common or simple mapping: it maps one Unicode codepoint to its uppercase equivalent according to the Unicode database. The additional [`SpecialCasing.txt`] is not yet considered here, but the iterator returned will soon support this form of case folding.

Similarly, [`char::to_lowercase`](https://doc.rust-lang.org/std/primitive.char.html#method.to_lowercase) reads:
> The case-folding performed is the common or simple mapping. See `to_uppercase()` for references and more information.

Right now, `char::to_uppercase` and `char::to_lowercase` disregard graphemes whose lowercase codepoints do not map one-to-one with their uppercase codepoints. For example, [`U+FB02 ﬂ LATIN SMALL LIGATURE FL`](https://codepoints.net/U+FB02), a single codepoint, maps to two characters: 'F' and 'L'. Yet, when we try [converting it to uppercase in Rust](http://is.gd/M4Fkn8)...
```rust
fn main() {
    let uppercase_flavor = "ﬂavor".chars()
        .flat_map(char::to_uppercase)
        .collect::<String>();
    
    println!("{}", uppercase_flavor);
}
```
...rather than the expected "FLAVOR", we get "ﬂAVOR", an incorrect result.

As the description of `char::to_uppercase` explains, this behavior is expected to change. However, currently `char::to_uppercase`, `char::to_lowercase`, and their associated iterators `std::char::ToUppercase` and `std::char::ToLowercase` are all marked stable, yet fixing this behavior would be a breaking change.

**Comment by alexcrichton** [comment]
Thanks for the report! This sort of change is definitely planned, however, and has yet to be implemented. The switch from returning just a plain `char` to returning an iterator of characters reflects this. A minor update such as this will not be considered a breaking change, especially because of the way the documentation is currently worded. As a result I'm going to close this issue for now in favor of https://github.com/rust-lang/rust/issues/25800, which reflects the current plan.
