### ISSUE TITLE
Calling trait method of non-imported trait should not compile

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/rust#25795]
The following code should not compile:

```
mod hidden {
    pub trait TestTrait {
        fn do_something(&self);
    }
    
    pub struct TestStruct;
    
    impl TestTrait for TestStruct {
        fn do_something(&self) { println!("Hello world"); }
    }
    
    impl TestStruct {
        pub fn boxed() -> Box<TestTrait> { Box::new(TestStruct) as Box<TestTrait> }
    }
}

fn main() {
    use hidden::TestStruct;
    let x = TestStruct::boxed();
    x.do_something();
    // ^~ this should be a compile error, since the trait is not in scope
}
```

**Comment by oli-obk** [comment]
This is perfectly fine. You are using a `Box<TestTrait>`, so you can find the `do_something` function on that trait.

What you were expecting is the failure in the following code. But that failure happens because there is no `do_something` function on `TestStruct`, only on `TestTrait` which isn't in scope.

```rust
mod hidden {
    pub trait TestTrait {
        fn do_something(&self);
    }

    pub struct TestStruct;
    
    impl TestTrait for TestStruct {
        fn do_something(&self) { println!("Hello world"); }
    }
}

fn main() {
    let x = hidden::TestStruct;
    x.do_something();
}
```

><anon>:15:7: 15:21 error: type `hidden::TestStruct` does not implement any method in scope named `do_something`
<anon>:15     x.do_something();
                ^~~~~~~~~~~~~~
<anon>:15:7: 15:21 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
<anon>:15:7: 15:21 help: candidate #1: use `hidden::TestTrait`

**Comment by aochagavia** [comment]
Then this should compile, but it doesn't:

```
fn main() {
    use hidden::TestStruct;
    let x = Box::new(TestStruct);
    x.do_something();
}
```

**Comment by oli-obk** [comment]
No it should not compile. You only know about `TestStruct` because you explicitly requested that type. But that type does not have a `do_something` function. Since `TestTrait` is not in scope, the current code doesn't know about `TestTrait` and its `do_something` function

**Comment by aochagavia** [comment]
Hmmm you are right... Then I guess I'll close this. Thanks for your explanation!

BTW, would you mind looking at [this](http://stackoverflow.com/questions/30448596/how-can-i-change-the-return-type-of-this-function) question on stack overflow? I think it is related to a bug, but I am not able to reduce it.
