### ISSUE TITLE
Implement full to_{upper,lower}case algorithms

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#25800]
Right now we always return an iterator over one character, but the iterator is being returned so one day we can return many characters. This has all yet to be implemented, and this issue will track this implementation.

**Comment by bitborn** [comment]
A couple friends and I dug into this issue as part of a mini-sprint. _We'd love a mentor or some guidance to work on this_.

As we understand it right now:
- Unicode case conversions are done using raw text tables from [unicode.org](http://www.unicode.org/Public/UNIDATA/UnicodeData.txt)
- The raw tables are exported as rust slices in [tables.rs](https://github.com/rust-lang/rust/blob/f14d289d71fd8e4956e7214bda3af15cd50898fe/src/librustc_unicode/tables.rs) using a python script [unicode.py](https://github.com/rust-lang/rust/blob/f14d289d71fd8e4956e7214bda3af15cd50898fe/src/etc/unicode.py)
- The current `to_uppercase` methods use a binary search over the single character conversion tables ignoring the multiple character `compatibility_table`

So what needs to happen then is:
- Either join the two tables or search both of them. 
- `to_upper` and `to_lower` in [tables.rs](https://github.com/rust-lang/rust/blob/f14d289d71fd8e4956e7214bda3af15cd50898fe/src/librustc_unicode/tables.rs) then need to be changed to return a slice rather than a single `char`
- `to_uppercase` and `to_lowercase` need to use that slice for the iterators it returns

_Is that an accurate summary?_

Also, we noted there are [several external but related crates for unicode](http://unicode-rs.github.io/) but couldn't find any indication on whether these crates were moving into the standard lib or whether the standard lib was moving out.

**Comment by alexcrichton** [comment]
@bitborn that all sounds pretty good! I think we may not want to encode the exact return value of each character (that's a lot of space). It'll be a balancing act to figure out how to encode the data on unicode.org in as compact a form as possible but still having a fast lookup for case conversions.
