### ISSUE TITLE
Generics: ! and ? are undocumented

### ISSUE THREAD

**Issue by genodeftest** [rust-lang/rust#25980]
I couldn't find anything useful on ` !Typename` and ` ?Typename` in Reference and Rust book.
the ` ?` is e.g. used in std::marker::PhantomData. ` !` in alloc::rc::Rc.

**Comment by steveklabnik** [comment]
? is http://doc.rust-lang.org/stable/book/unsized-types.html#?sized

I cannot find ! at the moment. It is only usable for Send and Sync, IIRC.

Both have very specialized usage.

**Comment by eddyb** [comment]
`!` is for negative impls:
```rust
trait Good {}
impl Good for .. {}

struct Bad;
impl !Good for Bad {}
```

**Comment by steveklabnik** [comment]
So, implementing all of this is behind the `opt_in_built_in_traits` flag right now. We're trying to be sensitive to the amount of jargon we use, and it's not clear that OIBIT is something we want to propagate. I'm not keeping issues open for documenting nightly features right now, and since `?`'s stable usage is documented, I'm going to give this a close.

When the feature becomes stable, I'll write up docs.
