### ISSUE TITLE
Poor error when using single quotes with `println!`

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#26101]
```
fn main() {
    println!('{}', 5);
}
```

This error leaves much to be desired:

```
hello.rs:2:14: 2:16 error: unterminated character constant: '{
hello.rs:2     println!('{}', 5);
                        ^~
```

The issue is that you need double quotes. 

originally found in http://joelmccracken.github.io/entries/a-simple-web-app-in-rust-pt-2b/ /cc @joelmccracken

**Comment by bstrie** [comment]
Consider changing the title, because this isn't println-specific. The following code exhibits the same error message:
```rust
fn main() {
    'abc';
}
```

**Comment by joelmccracken** [comment]
I was wondering about this -- I assumed this is a string thing. The way it is worded made me think that it was caused by some fancy println macroings.

**Comment by birkenfeld** [comment]
The current error is `error: character literal may only contain one codepoint: '{`

**Comment by Mark-Simulacrum** [comment]
Looking at the code, there doesn't appear to be a current way to add a help message to this diagnostic, though adding one shouldn't be too hard. Could someone familiar with the parser, perhaps @jseyfried or @nrc, type up a quick mentoring summary for adding a `help: Maybe use double quotes (") instead of single quotes (')`? It looks like ultimately `self.sess.span_diagnostic.struct_span_fatal` needs to be called with the appropriate parameters.
