### ISSUE TITLE
-Awarnings does not inhibit #![deny(warnings)]

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#26171]
Cargo passes `-Awarnings` to rustc when building dependencies, to make the build less noisy.

One dependency of a package I maintain has `#![deny(warnings)]` on their crate, as a way to force themselves to keep their build warning-free. This is fine when building that package itself, but it also applies when I use it as a dependency. My build was recently broken because they happen to use a method from `std` that was recently deprecated.

Should `-Awarnings` "win" over `#![deny(warnings)]`? Or is there a way to have `#![deny(warnings)]`, except when that crate is being built as a dependency? (The latter might be relevant to Cargo rather than rustc.)

CC @alexcrichton

**Comment by alexcrichton** [comment]
Right now the lint system is designed to be hierarchical, having the "most recent" level setting apply to any lint warning location, so this seems like quite a natural fallout to me. Otherwise I believe the specific case here is covered by https://github.com/rust-lang/rfcs/issues/1029, so I'm going to close this in favor of that.
