### ISSUE TITLE
No null check for CommandLineToArgvW

### ISSUE THREAD

**Issue by Veedrac** [rust-lang/rust#26196]
I'm looking at #22709, and trying to find out the thread-safety of [`libstd/sys/windows/os.rs`](https://github.com/rust-lang/rust/blob/f76d9bcfc2c269452522fbbe19f66fe653325646/src/libstd/sys/windows/os.rs)'s [`Args`](https://github.com/rust-lang/rust/blob/f76d9bcfc2c269452522fbbe19f66fe653325646/src/libstd/sys/windows/os.rs#L286-L289).

Along the way, I noticed that [`CommandLineToArgvW` isn't NULL-checked](https://github.com/rust-lang/rust/blob/f76d9bcfc2c269452522fbbe19f66fe653325646/src/libstd/sys/windows/os.rs#L321-L322), despite [the documentation I found recommending it.](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776391%28v=vs.85%29.aspx)

I'm allergic to Windows, so I've no idea what might cause this dangerous return value.

**Comment by alexcrichton** [comment]
While it may be nice to have a comment to this effect, I don't think that this is a problem. The only time we actually look at the pointer is during iteration, and that only happens if the count/range returns an item. In the case that NULL is returned the count will be 0, so the pointer is never looked at. Additionally, `LocalFree` ignores NULL pointer arguments, so I don't think that there's actually a problem here.

All that being said, though, a comment would be nice.
