### ISSUE TITLE
signatures of String::from_utfXX() are inconsistent

### ISSUE THREAD

**Issue by colin-kiegel** [rust-lang/rust#26276]
**impl String** (source: https://doc.rust-lang.org/std/string/struct.String.html)
```rust
fn from_utf8(vec: Vec<u8>) -> Result<String, FromUtf8Error>
fn from_utf8_lossy(v: &'a [u8]) -> Cow<'a, str>
fn from_utf16(v: &[u16]) -> Result<String, FromUtf16Error>
fn from_utf16_lossy(v: &[u16]) -> String
```

1.  **String::from_utf8** takes a **vector**, while all other functions take **slices** (especially the utf16 counterpart). I think it should be slices consistently for all four.
2. Also the return value of **String::from_utf16_lossy** differs from **String::from_utf8_lossy** . I think the return value should be String, too.

**Comment by steveklabnik** [comment]
Unfortunately, these methods are all stable, and so can't really be changed.

**Comment by alexcrichton** [comment]
Yeah @steveklabnik mentioned, these are stable so they can't change, but the rationale is:

* The `String::from_utf8` function takes ownership of the underlying bytes, hence taking a `Vec`. This is a performance optimization to avoid unnecessary allocations. The sister function is `str::from_utf8` which does not take an owned vector. The `Result` returned here has an error payload specific to decoding utf-8 bytes
* The `from_utf8_lossy` function takes a *slice* of bytes as it tries to not allocate (a performance optimization). This also explains the `Cow` return type (because sometimes you don't have to allocate) and it lives on `String` as it may allocate to return a `String`.
* The UTF-16 functions take slices of u16 because it can't do anything extra by taking ownership, and both return a `String` as there's no way to not allocate.

Overall, to address your points:

> I think it should be slices consistently for all four.

Taking a `Vec` in `from_utf8` is a performance optimization, and the slice-taking variant is `str::from_utf8`.

> I think the return value should be String, too.

No returning a `String` is also a performance optimization as sometimes `from_utf8_lossy` doesn't have to allocate.
