### ISSUE TITLE
Sub requiring Ownership? 

### ISSUE THREAD

**Issue by Binero** [rust-lang/rust#26476]
While creating a simple program I discovered that the `Sub` trait requires ownership of itself and the thing that's being subtracted from it. Here is the implementation: https://doc.rust-lang.org/src/core/ops.rs.html#240-248

This can leads to quite complicated structures when trying to implement it for a type which you cannot get ownership of: http://is.gd/BAhDYf

Why is it that Sub requires ownership? Why cannot it just work with a reference?

**Comment by arielb1** [comment]
Because Rust requires an `&` in most places when borrowing (you can just use `&x + &y`).

**Comment by Gankro** [comment]
You can `impl<'a, 'b> Sub<&'a Foo> for &'b Foo` if you want reference semantics.

**Comment by durka** [comment]
@Gankro but then you can't access Foo's members if they are not Copy, because self is borrowed.

**Comment by durka** [comment]
To be clearer, I mean if you want to use a Sub impl on Foo's members, you can't because it has to take ownership, but you are borrowing the Foo so you can't.

**Comment by Binero** [comment]
@Gankro Why does it not always use a reference, instead if having to implement it for the reference type?

**Comment by Gankro** [comment]
@Binero because some things *do* want to be by-value. Or rather, some things can be Especially Effecient in a by-value context. For instance `BigNum + &BigNum` is strictly more efficient to perform than `&BigNum + &BigNum`.

&Foo + &Foo can be expressed in term of by-value semantics (the "values" are &Foo), but Foo + Foo cannot be expressed in terms of by-reference semantics. The current design is strictly more flexible.

@durka I don't understand what you mean?

```
use std::ops::Sub;

#[derive(Debug)]
struct Foo(u8);
#[derive(Debug)]
struct Bar(Foo, Foo);

impl<'a, 'b> Sub<&'a Foo> for &'b Foo {
    type Output = Foo;
    fn sub(self, lhs: &'a Foo) -> Foo {
        Foo(self.0 - lhs.0)
    }
}

impl<'a, 'b> Sub<&'a Bar> for &'b Bar {
    type Output = Bar;
    fn sub(self, lhs: &'a Bar) -> Bar {
        Bar(&self.0 - &lhs.0, &self.1 - &lhs.1)
    }
}

fn main() {
    let a = Bar(Foo(10), Foo(20));
    let b = Bar(Foo(5), Foo(7));
    println!("{:?}", &a - &b);
}
```

**Comment by Binero** [comment]
@Gankro Then why aren't Sub and Add by-value?

**Comment by Gankro** [comment]
@Binero they are.

**Comment by durka** [comment]
@Gankro if Sub is implemented for Foo and not &Foo (let's say it's outside your crate, so you can't fix that) then it seems impossible: http://is.gd/3SV2fp

**Comment by Binero** [comment]
@Gankro My bad, I meant Eq and PartialEq.

**Comment by Gankro** [comment]
@durka Yes, if an upstream crate doesn't expose a sufficient API then you have little recourse but to file against them. This is simply true of all APIs. 

In this case you can Almost Always fall back to `clone`  Bar(self.0.clone() - lhs.0.clone(), self.1.clone() - lhs.1.clone()).

@Binero `Add` and `Sub` being more effecient is a consequence of being able to reuse e.g. an allocation by mutating the LHS in place. Eq and PartialEq are "observation only" ops so it doesn't matter.

**Comment by durka** [comment]
I think being able to reuse the allocation is the reasoning that answers my question, thanks. Although it still seems to me there should be an option to implement ops by-reference, since you don't normally think of addition as modifying its operands (for example, in C++ you'd expect `+=` to modify the LHS but not `+`)... but maybe it's not possible to implement that option without type conflicts.

**Comment by Binero** [comment]
@durka As it's by-value, it doesn't actually modify the LHS. It modifies a copy of the LHS.

@Gankro I see.
