### ISSUE TITLE
E310 could be provided with a more helpful error message

### ISSUE THREAD

**Issue by kali** [rust-lang/rust#26538]
```
struct S<M> where M: Fn(usize) -> usize { m:&'static M }
```

http://is.gd/z6q9JD

The message suggests adding a lifetime bound where it already is, missing the actual point: it should be in the where clause.

**Comment by steveklabnik** [comment]
This now suggests `  = help: consider adding an explicit lifetime bound `M: 'static`...`, with no span. I can't see what the original error was because it wasn't in this ticket, but it sounds like a bad span that was fixed to me. I'm going to give this a close, @kali , if this is still confusing, please let me know!
