### ISSUE TITLE
Unused import warning issued on renamed imports prefixed with underscore

### ISSUE THREAD

**Issue by patrickjm** [rust-lang/rust#26585]
Example: if unused, `use std::io::Error as _IoError` will issue the `unused_imports` warning. This is inconsistent with the `dead_code` warning which will not issue if the name starts with an underscore.

Is this intentional or a small oversight?

**Comment by sanxiyn** [comment]
Why would one want to do this?

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
