### ISSUE TITLE
build failure on latest llvm 3.7

### ISSUE THREAD

**Issue by tamird** [rust-lang/rust#26632]
```
$ brew install llvm --HEAD
$ ./configure --llvm-root=$(brew --prefix llvm) --disable-docs --disable-valgrind --enable-debug --enable-optimize --enable-optimize-tests
...
configure: using custom LLVM at /usr/local/opt/llvm
configure:
configure: found ok version of LLVM: 3.7.0svn
...
$ /usr/bin/make check-stage1
compile: x86_64-apple-darwin/rt/rust_try.o
/usr/local/opt/llvm/bin/llc: /Users/tamird/src/rust/src/rt/rust_try.ll:27:29: error: expected instruction opcode
    landingpad { i8*, i32 } personality i8* bitcast (i32 (...)* @rust_eh_personality_catch to i8*)
                            ^
make: *** [x86_64-apple-darwin/rt/rust_try.o] Error 1
```
cc @alexcrichton

**Comment by richo** [comment]
I have a patch for this https://github.com/richo/rust/commit/c29eeb94ffd70dfe1285f7e5961bf62a7afd2486

But it faults in LLVMBuildLandingPads and I haven't gotten to the bottom of it. You could try cherry picking my patch and see if you make any ground though (I would love to get llvm updated so I can play with safe stacks)

**Comment by tamird** [comment]
Yeah, I ended up with the same patch locally and hit a segfault. How did you work out that the problem is in `LLVMBuildLandingPads`?

**Comment by tamird** [comment]
Oh, my LLVM must be compiled without assertions. Urgh.

**Comment by richo** [comment]
This is partially from memory, I mostly just wanted to share state to hopefully avoid duplicating work (Looks like I was a bit late for that!)

My LLVM was also without assertions, I got as far as running `rustc` in a debugger, and had a quick look at the crash. I've long since blown away that tree, but one sec I can give you some context for the crash on my machine, on the offchance it helps.

**Comment by richo** [comment]
This is partially from memory, I mostly just wanted to share state to hopefully avoid duplicating work (Looks like I was a bit late for that!)

My LLVM was also without assertions, I got as far as running `rustc` in a debugger, and had a quick look at the crash. I've long since blown away that tree, but one sec I can give you some context for the crash on my machine, on the offchance it helps.

**Comment by tamird** [comment]
Well it turns out having assertions on doesn't help, still just a segfault.

**Comment by richo** [comment]
Are you faulting on a `cmp [rcx],0x0` as well?

I didn't dig very far into it, but rcx being not null stuck out as weird. I'll build with symbols now and see if I get anything more, happy to collaborate if you like (I'm `richo` on irc)

**Comment by richo** [comment]
Ok, I tracked down the bug. The signature of LLVMBuildLandingPad has changed, hence a value that makes no sense as the functions name.

@alexcrichton Is there machinery for generating this file? If not I can just go through and update it by hand.

**Comment by richo** [comment]
ok, I have a branch with as far as I'm going to get tonight. This fixes landing pad construction, but fails when trying to process IR because codegen doesn't know that it needs to move the landing pad decl onto the function. Would love to pair with someone to get this along the line!

My branch is here: https://github.com/richo/rust/tree/richo-llvm-upgrade

**Comment by alexcrichton** [comment]
Ah yeah I noticed that this syntax change happened soon after we landed the LLVM upgrade. I'm going to close this bug because we're not really guaranteeing that we work with an arbitrary LLVM commit at any point in time, but @richo is right in that the "fix" for this would be to upgrade LLVM.

@richo I suspect that we'd just need to find where the personality function is added to a function declaration, and then we'd just modify how that's called. We only have one personality function globally anyway, so there shouldn't be too much extra logic around setting it.

**Comment by richo** [comment]
Closing the issue seems entirely reasonable, but I'm going to keep dumping state here if that's ok, since it seems as reasonable place as any. I dug a fair bit further into this on that same branch (Which now has a lot of yolo printf debugging in it).

I got as far as finding out that putting a personality on functions without landing pads is entirely broken, and discovering that the functions that need them are called `unwind_`, although it's unclear where they come from, since there's no obvious place they come from (no hits from git grep for `unwind_` or `"unwind` that look coherent).

Uploading the IR made gist pretty angry, but here's what I get trying to build libcore with the compiler as it stands on the tip of that WIP branch: https://gist.github.com/richo/ceae595c0170f6e49d7c

My grand plan for this was to ideally get everything working and then refactor around a working case to avoid regressing, but it seems like it's kinda unavoidable to just do the refactoring now. The obvious place to start is to stop trying to lazily load the personality fn in declare_fn and eagerly do it when building a CrateContext, which ought to mean we can drop most of the really heinous hacks I introduced. I'm sort of at a loss for where these unwind_* fns come from, although I suspect that if I start grepping in llvm they'll stick out. The other thing I haven't yet dug into is where the heuristic for a function having a landing pad is, although increasingly it looks like the only explicitly created fns in rustc that actually need landing pads attached to them have them spelled out in rust_try.ll already.

**Comment by richo** [comment]
I did a tiny bit more refactoring this morning, but I also thought about it a lot more overnight. My plan for this evening is to go back and instrument the implementation on master to panic when it tries to attach a personality to a landingpad, which will hopefully give a meaningful stack trace that elucidates the conditions under which we need to attach to a function in the new world.

**Comment by tamird** [comment]
Good stuff, I'll be following along :)

**Comment by tamird** [comment]
@richo I got this working, pretty minimal changes in the end. https://github.com/tamird/rust/tree/llvm-upgrade

**Comment by tamird** [comment]
Wait, spoke too soon! Linking failure.

**Comment by richo** [comment]
@alexcrichton has a very similar branch as well. I can have a look at the linking error tonight probably. (I built his branch, saw the linking error and want to bed)

**Comment by alexcrichton** [comment]
After we update LLVM I've found that two commits are needed to get the bootstrap working on linux-64:

* https://github.com/alexcrichton/rust/commit/7f68575c7db02dfa03fc1d18f8ae1522d737b2f7
* https://github.com/alexcrichton/rust/commit/050bc8a89a1b282d106d7a1db74d72d9e97ca490

I haven't tested out other platforms yet. Unfortunately a debuginfo tests fails after the update, so I haven't been able to test it super thoroughly yet.

**Comment by mikosdikos** [comment]
Hi,
I was going to try building the latest rustc on an old 32bit debian box - is using the installed llvm kosher? 
I'd like to shorten the build time but not get any nasty suprises afterwards.

Thx
