### ISSUE TITLE
Type parameter defaults are not checked correctly

### ISSUE THREAD

**Issue by Tobba** [rust-lang/rust#26633]
This typechecks:

``` rust
pub trait Foo {
    fn foo<E=<Self as Bar>::A>(_: E) { }
}

pub trait Bar {
    type A;
}

fn main() { }
```

Which doesn't really make a lot of sense and seems like it could be a backwards compatibility footgun.

**Comment by jroesch** [comment]
Can you clarify what you are expecting here? this looks fine to me. You are allowed to declare that default and it will be manifested at a call site to `Foo::foo`.

**Comment by eddyb** [comment]
@jroesch the default depends on `Self: Bar` but that is implicit (due to a use of `<Self as Bar>` projection).
I am not sure that is actually a problem, as it will get type-checked at call sites (not in that specific form, though, not yet. would need defaults to be used in inference for that default to be instantiated).

**Comment by jroesch** [comment]
@eddyb yeah that was my point, currently we don't actually check implied constraints like that in most places. You can do similar things in trait declarations but will receive a type error at a call site.

**Comment by steveklabnik** [comment]
Triage: so is this a problem or not?

**Comment by eddyb** [comment]
cc @rust-lang/lang I am a bit worried about this.

**Comment by Mark-Simulacrum** [comment]
@rust-lang/lang didn't comment on this; I'm going to nominate.

**Comment by nikomatsakis** [comment]
I believe we intentionally deprecated this with #36887 -- we can probably just close this issue, in my opinion.
