### ISSUE TITLE
DST coercions are prevented by phantom data

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#26905]
This prevents Rc from having a sound definition with respect to dropcheck

```rust
#![feature(unsize, coerce_unsized)]

use std::marker::{Unsize, PhantomData};
use std::ops::CoerceUnsized;

struct MyRc<T: ?Sized> {
    ptr: *const T,
    _boo: PhantomData<T>,
}

impl<T: ?Sized + Unsize<U>, U: ?Sized> CoerceUnsized<MyRc<U>> for MyRc<T>{ }

fn main() {}
```

```text
<anon>:11:1: 11:77 error: the trait `CoerceUnsized` may only be implemented for a coercion between structures with one field being coerced, but 2 fields need coercions: ptr (*const T to *const U), _boo (core::marker::PhantomData<T> to core::marker::PhantomData<U>) [E0375]
<anon>:11 impl<T: ?Sized + Unsize<U>, U: ?Sized> CoerceUnsized<MyRc<U>> for MyRc<T>{ }
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

**Comment by Gankro** [comment]
CC @nrc @eddyb

**Comment by nrc** [comment]
I think DST coercions should just ignore all zero-sized fields

**Comment by eddyb** [comment]
@nrc the only immediate solution would be ignoring `PhantomData`. Actually, that's still problematic.
I guess would could ignore `PhantomData<T> -> PhantomData<U> where T: Unsize<U>`.
Otherwise, it's possible to construct a type where coercing can modify its properties in an incompatible way.
Although, could it lead to memory safety, if no unsafe code is used with it?

**Comment by arielb1** [comment]
@eddyb 

I don't think `PhantomData` serves as a witness today (and you have to implement `Unsize` for this to be important).
