### ISSUE TITLE
Alias for Box of Arrays not working properly

### ISSUE THREAD

**Issue by debris** [rust-lang/rust#26949]
I cannot use `my_alias::new` when box is wrapping an array.

I tried this code:

```rust
type Value = Box<u8>;
type Values = Box<[u8]>;

fn test() {
  let a = Box::new(0); // works
  let b = Value::new(0); // works
  let c = Box::new([0u8, 8]); // works
  let d = Values::new([0u8, 8]); // doesn't work
}
```

I expected alias `Values` to work properly.

Instead, I got error:

```
error: no associated item named `new` found for type `Box<[u8]>` in the current scope
```

## Meta

`rustc --version --verbose`:

```
rustc 1.1.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 1.1.0
```

os: osx 10.10.3

**Comment by eefriedman** [comment]
The important part of the error message is ``note: the method `new` exists but the following trait bounds were not satisfied: `[u8] : core::marker::Sized` ``.  (Translation: `Box<[u8]>::new` doesn't exist because `[u8]` is unsized, as opposed to `Box<[u8; 8]>::new`.)

This isn't really a bug, but the error message could be a bit better.

**Comment by arielb1** [comment]
I don't see how can we improve this situation.

**Comment by bluss** [comment]
@debris `Values::new` doesn't make sense, it is in fact not implemented, because the requirement `T: Sized` is not fulfilled. It needs to be created as a `Box<[u8; 8]>` first and then cast or coerced into `Box<[T]>`.
