### ISSUE TITLE
Wrong code with assignment in match body

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#26996]
```rust
fn main() {
    let mut c = (1, "".to_owned());
    match c {
        c2 => { c.0 = 2; assert_eq!(c2.0, 1); }
    }
}
```
```
thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `2`, right: `1`)', <anon>:4
playpen: application terminated with error code 101
```

**Comment by Thiez** [comment]
Actually what happens here is the following:

The tuple you create in `c` is moved, because it is not `Copy`. When you perform the `match` you move *out* of `c`, into `c2`, leaving `c` uninitialized. Your assignment to `c.0` is basically to uninitialized memory, and doesn't have an effect. When you perform the assertion you see the old value of `c.0`, because your assignment to `c.0` had no effect.

The whole thing is confusing because Rust does not warn when you perform useless assignments to moved variables, and it probably should. The whole thing becomes obviously when you add a statement that uses `c` in the match arm:

```rust
fn main() {
    let mut c = (1, "".to_owned());
    match c {
        c2 => { println!("{}", c.0); c.0 = 2; assert_eq!(c2.0, 1); }
    }
}
```

**Comment by mitaa** [comment]
> Your assignment to c.0 is basically to uninitialized memory, and doesn't have an effect. When you perform the assertion you see the old value of c.0, because your assignment to c.0 had no effect.

Don't we see the new value `c.0 = 2;`, even though we're accessing `c2.0`, when performing the assertion, which causes it to fail?

Doing this without a match statement passes the same assertion sucessfully:
```rust
fn main() {
    let mut c = (1, "".to_owned());
    let c2 = c;
    c.0 = 2;
    assert_eq!(c2.0, 1);
}
```

**Comment by Thiez** [comment]
Oops, you are correct, I am mistaken :(

**Comment by Aatch** [comment]
@Thiez heh, I made the same mistake. Typed out most of a response and then realised that I'd mis-read the code.
