### ISSUE TITLE
Pattern guards should run at most once

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#26998]
```rust
use std::cell::Cell;
fn main() {
    let i : Cell<i32> = Cell::new(0);
    match 1 {
        1 | _ if { i.set(i.get() + 1); false } => {}
        _ => {}
    }
    assert_eq!(i.get(), 1);
}
```
```
thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `2`, right: `1`)', <anon>:9
playpen: application terminated with error code 101
```
Granted, putting expressions with side-effects into pattern guards is a little dubious, but the behavior here doesn't seem intuitive.

**Comment by Aatch** [comment]
Pattern guards need to be run multiple times in order to match mulitple patterns in the same arm with the same guard:

```rust
match foo {
  (Some(x), _) |
  (_, Some(x)) if cond(x) => { ... } 
}
```

We actually do limit a fair amount of behaviour in pattern guards, but to limit it any further would make it useless.

Anyway changing this behaviour would be a **massive** backwards compatibility break, so I'm closing this.

**Comment by eefriedman** [comment]
Oh, right... sorry about the noise.
