### ISSUE TITLE
Linkage regression in servo with 1.2

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#27043]
See https://github.com/servo/servo/pull/6591#issuecomment-121256880

After some tweaks to how rustc drives the linker Servo no longer links. We should decide whether this is intentional and acceptable.

**Comment by brson** [comment]
cc @pcwalton @larsbergstrom

**Comment by larsbergstrom** [comment]
This is particularly painful for us because it disallows multiple references to the same library. We had to use those multiple references in order to force a deterministic link order on platforms where symbol availability is based on the order in which libraries are listed.

I assume that Rust and Cargo now provide enough control that we should be able to remove that usage pattern now, but this change had some pretty far-rippling effects for us, even to fix it on just OSX and just the case where we're producing a shared library.

**Comment by alexcrichton** [comment]
I think Servo's now working after upgrading and otherwise I've transferred tags to #26869 (the PR in question)
