### ISSUE TITLE
Warn if result of a comparison is not used

### ISSUE THREAD

**Issue by WiSaGaN** [rust-lang/rust#27107]
Currently Rust will not warn if the result of an "==" comparison is not used like " is_file_set == true; ".
It would be very useful to have that warning.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rfcs/pull/886

**Comment by Aatch** [comment]
@petrochenkov yeah, that'd probably work nicely. Though I wonder if a `#[pure]` attribute for the purposes of marking a "pure" function would be more general. The issue here is less "not using the result is probably an error" and more "not using the result of a pure operation is pointless". The attribute would only be for the purpose of linting, but the naming might give people the wrong impression.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
