### ISSUE TITLE
make all semicolons optional, there is no need in them

### ISSUE THREAD

**Issue by antonkulaga** [rust-lang/rust#27116]
Modern languages like Scala and Groovy do not enforce users to write semicolons. I think it is a right decision, because in fact semicolons are nothing more than just a redundant typing. 
I've been a scala developer for many years and I only needed semicolons when putting several lines of code in one line to fit the code in the slide=)

**Comment by Gankro** [comment]
This was actually implemented last month! :fireworks: 

https://github.com/mystor/slag

**Comment by antonkulaga** [comment]
@Gankro thank you! I did not know about that

**Comment by makoConstruct** [comment]
:disappointed: those fat arrows.. It seems to me that it'd be possible to do a syntax that is very very similar to Rust's primary syntax but where all braces and semicolons are optional(or, only used when needed, EG, when indentation isn't sufficient)

One of the reasons the current situation makes this difficult:
We would like to parse
```rust
fn do_things(a:u32 b:u32)-> u32 { a*b + a }
fn main()
    do_things(1 2)
    do_things(3 4)
```

into




, blocks that are expected to return unit must end with a Semi(Expr) (expression with semicolon) or an Expr(Expr) that has type unit. That means we couldn't just automatically parse every statement in a block into a Semi(Expr) and leave the last one as Expr(Expr), because if the block expects unit then that Expr(Expr) would cause a type error.

I read somewhere that allowing all types to coerce to unit had been considered(tried, even?), but it was rejected. Having difficulty finding the discussion. I can't see why it's considered useful to tell the programmer off for leaving the semicolon off of the last (non-unit)expression in a block that returns unit. For every case where a programmer wrongly expects the last expression to transmit its value out of the block, there is a receiver. If the transmission is interrupted by a coercion to unit, the error will be pointed out at the receiver's end, when it gets unit instead of whatever it was expecting. Requiring it to be pointed out at the transmitter's doesn't seem helpful.

**Comment by makoConstruct** [comment]
@apasel422 sorry for the confusion, I accidentally hit ctrl+enter before I'd finished writing it. Should be comprehensible now.
