### ISSUE TITLE
Internal crates are documented for stable but not nightly

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#27149]
https://doc.rust-lang.org/stable/std/ documents many crates including rustc and syntax, whereas https://doc.rust-lang.org/nightly/std/ only has std and its dependencies. This seems backwards, and opposite of what the commit message for e64b677ca66d742e7c06738bacf3a160cba827a7 / #23848 says.

CC @cmr

**Comment by pnkfelix** [comment]
@SimonSapin from reading the dialogue on #23848, it seems like the purpose of that PR shifted over time: at first it was turning off doc-generation for a broad class of crates, both the compiler-internal ones and the ones hidden behind the `std`-facade.

But it was determined that turning off doc-generation for the crates behind the `std`-facade caused links to break, so that doc-generation was turned back on.

So, the end net result of #23848 (if you count the backout commit that landed later) seems to be just to turn off doc generation for the compiler crates alone, I think?

**Comment by SimonSapin** [comment]
> turn off doc generation for the compiler crates alone

That sounds fine, but doing it on nigthly but not on stable?

**Comment by SimonSapin** [comment]
https://doc.rust-lang.org/stable/std/ does not include compiler-internal crates anymore which is at least consistent, but I still think that their documentation is useful when e.g. developing compiler plugins or working on the compiler itself.

I’m not the only one: https://internals.rust-lang.org/t/documentation-for-libsyntax-friends/2498

**Comment by brson** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/29893.
