### ISSUE TITLE
Rust and C use different in-struct f64 alignment on x86 linux

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#27195]
In particular the x86 linux C ABI has f64 aligned to 8 bytes normally, but only 4 bytes while in a struct. Rust gives f64 an unconditional 8 byte alignment. In addition, the Rust struct is not padded for its size to be a multiple of its alignment, meaning that the struct's alignment requirements will not be respected by e.g. an array. This may or may not cause exotic problems. Although it should be noted that it is "fine" to load an f64 on a 4 byte alignment (as C clearly does this).

```rust
#[repr(C)]
struct S {
    i: i32,
    d: f64
}

fn main() {
    println!("{} {}", std::mem::size_of::<f64>(), std::mem::size_of::<S>());
    println!("{} {}", std::mem::align_of::<f64>(), std::mem::align_of::<S>());
}
```

```
8 12 
8 8
```

```cpp
#include <iostream>

struct S {
  int i;
  double d;
};

int main() {
  std::cout << sizeof(double) << ' ' << sizeof(S) << '\n';
  std::cout << alignof(double) << ' ' << alignof(S) << '\n';
}
```

```
8 12
8 4
```

**Comment by Gankro** [comment]
The person I had test this just noticed they were using an outdated compiler, and today Rust spits out:

```
8 12 
4 4
```

So we instead unconditionally have f64 aligned to 4 bytes. I'm not sure if this will cause any problems for C calling into a rust function that uses f64s.

**Comment by bluss** [comment]
Did this account for that `align_of` has changed its meaning? `min_align_of` was always the correct one for Rust, and now `align_of` is the same as `min_align_of`.

**Comment by nagisa** [comment]
Still `8 12` and `4 4`.

**Comment by eddyb** [comment]
LLVM doesn't distinguish between "in a `struct`" and otherwise, AFAIK.
Is there a possibility preferred alignment is being used instead of ABI alignment by C `alignof`?
E.g. the ABI alignment of `long long` on 32-bit x86 is `4` while the preferred alignment is `8`.

A few minutes later: @nagisa confirmed on IRC `alignof(long long)` is `8`, which means it's "preferred".
Rust only exposes "ABI alignment", i.e. only `min_align_of`. So this is a non-issue AFAIK.
