### ISSUE TITLE
Expressions involving blocks do not parse well

### ISSUE THREAD

**Issue by barosl** [rust-lang/rust#27477]
```rust
0; // OK
0 + 1; // OK
{0} + 1; // Error: unexpected token: `+`
({0} + 1); // OK
```

@copy and @durka found this issue on IRC. I baked cookies for them!

Also, @tsion found this interesting corner case:

```
// Is `*` a multiplication? Or a dereference? Currently it parses as the latter.
if true { 1 } else { 2 } * n;

// However, written like below, it is recognized as a multiplication.
(if true { 1 } else { 2 } * n);
```

This could be quite surprising.

**Comment by nagisa** [comment]
Sounds pretty critical.

**Comment by Aatch** [comment]
I'm not sure if it this is actually fixable. At best I think some more intelligence regarding error messages is possible, but it's due to the way we treat certain structures as statements instead of expressions. Specifically, "block" expressions (including `if` and similar) are treated as statements if they start an expression. Any "fix" here would be a massively breaking change.

It's easy to come up with cases like those, but when you split the lines up like so:

```rust
if foo {
    1
} else {
    2
}
*n
```

it becomes more obvious that "fixing" it isn't feasible. The only proper fix is to require that **all** statements be terminated with a semicolon. Since that isn't going to happen, we have to work with these edge cases.

I'm not sure what we're supposed to do about this, it's the way Rust parses and can't be changed without breaking most code out there. I'm going to close this as not-a-bug, feel free to re-open if you disagree.

**Comment by barosl** [comment]
Actually, I once wondered why `if` and others do not end with `;`. Now I know the answer!

Requiring them to end with `;` would have brought more consistency, but that would have also been less ergonomic, I think... Was this option considered in the early history of Rust?
