### ISSUE TITLE
A block evaluated as a function is not directly callable

### ISSUE THREAD

**Issue by barosl** [rust-lang/rust#27478]
``` rust
fn f() {}

f(); // OK
{f}(); // Error: expected `()`, found `fn()`
let a = {f}; a(); // OK
```

Another corner case found here!

**Comment by muja** [comment]
```rust
({f})(); // OK
```

This also doesn't work in JavaScript (for example): `function(){ }()`, instead, you have to wrap it around parentheses: `(function() { })()`, as well as in Rust.

**Comment by nagisa** [comment]
AFAIR we at least in multiple locations suggest adding parens around the function, if necessary. This is probably another missed case.

**Comment by Aatch** [comment]
Note that this is expected as `{f}()` is parsed as a statement then an expression, basically the same as:

```rust
{
  f
}
()
```

which should hopefully make it more clear. Wrapping it parentheses makes the block statement an expression.

**Comment by steveklabnik** [comment]
tagging as diagnostics because i have similar feels to @nagisa

**Comment by bluss** [comment]
@aatch but we also have the case where `{[1, 2]}[0];` and `{(1, 2)}.0;` compile, so subscripting and accessing fields are ok.

**Comment by Aatch** [comment]
@bluss the indexing case doesn't work in the same context, and for the same reason. `[0]` is a valid expression by itself. The field-access case works because `.0` isn't actually a valid expression by itself. While we treat `.` as an operator sometimes, it actually isn't and the parser doesn't parse it as one either, hence why it parses fine while `{5} + 5` doesn't.

**Comment by steveklabnik** [comment]
Triage: no changes

**Comment by Mark-Simulacrum** [comment]
I would not expect this to work; we generally do not permit calling an expression's result without parens wrapping the expression.
