### ISSUE TITLE
End of macro invocation before expected produces EOF

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/rust#27569]
``` rust
fn main() {
    let message = "world";
    println!("Hello, {}", message/);
}
```

This gives the following compile error:

```


<anon>:3:34: 3:35 error: unexpected token: `<eof>`
<anon>:3     println!("Hello, {}", message/);
                                          ^
```

I think this is slightly misleading: it's not an EOF at the position where the caret is.

**Comment by Aatch** [comment]
This is because of the macro. For `message/` there the token stream is literally just `message` and `/`, so the expression parser hits an "EOF", as it can only parse the tokens inside the macro. It's an unfortunate error message, but technically correct, from the perspective of the parser anyway.

There should probably be something to catch "EOF" errors in macro/syntax extension expansion and turn them into something more accurate.

**Comment by gchp** [comment]
@Wilfred @Aatch I'd like to take a look at this issue.

What do you think would be a good message for the example above?

**Comment by estebank** [comment]
Current output:

```
error: expected expression, found `<eof>`
 --> src/main.rs:3:34
  |
3 |     println!("Hello, {}", message/);
  |                                  ^ expected expression
```
