### ISSUE TITLE
Tracking issue for `path_ext` stabilization

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#27725]
The `PathExt` trait provides a number of methods on paths that conveniently connect it to the `std::fs` API.

While these methods are largely fine, there is some question as to how many of them there should be; the rationale for the exact selection of methods is currently a bit muddy.

Given that the trait can grow over time with default methods, it may be worth stabilizing the portion we feel confident we want, and then adding more over time.

cc @alexcrichton @brson

**Comment by alexcrichton** [comment]
This trait was also [recently tweaked](https://github.com/rust-lang/rfcs/blob/master/text/1044-io-fs-2.1.md#tweaking-pathext) to have a bit of a more coherent design, so we may just want to decide whether that strategy is appropriate or not.

**Comment by aturon** [comment]
Nominating: this should at least be discussed for possible FCP in the 1.5 cycle.

**Comment by alexcrichton** [comment]
This issue is now entering its cycle-long FCP for stabilization in 1.5

On final question about this issue is whether we continue to have an extension trait or fold the functionality to inherent methods on `Path`. Some points of note are:

* This provides a nice boundary for methods on Path that do I/O and not.
* This makes it a little easier to migrate Path to libcore and PathBuf to libcollections, but it's unclear what that use case is.
* This design pattern exists nowhere else in the standard library (e.g. an extension trait available everywhere, just requires importing the trait).

**Comment by dhardy** [comment]
I don't know about migration to libcore, but folding into `Path` makes sense for most use cases (saves an import).

I'm not sure if there are any users of `Path` where basics like `is_file()` are not needed? Would `Path` be used for paths inside zip files or web URLs? I doubt it.

**Comment by aturon** [comment]
It's also worth noting that this trait originated when there was a separate `io` module hierarchy, so `Path` felt more "outside" of IO in some sense.

I'm increasingly convinced that treating this as an extension trait is not actually buying us anything, and winds up being a papercut for newcomers.

**Comment by retep998** [comment]
I'm pretty much okay with the methods that `PathExt` provides and I think it would be better if the methods were simply inherent methods on `Path` rather than using an extension trait.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and the decision was to stabilize as inherent methods on `Path`.
