### ISSUE TITLE
Tracking issue for `iter_order` stabilization

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#27737]
The `iter` module has an `order` submodule for performing comparisons on iterators. Ideally, these would instead just be implementations of e.g. the `PartialOrd` trait, but that trait passes by shared reference, and iterators must be mutated to be compared.

It'd be good to explore this design space, and perhaps write an RFC, before stabilization.

cc @bluss

**Comment by bluss** [comment]
One thing of note is that the origin of this API was to help libcollections, so that the collections didn't all have to reimplement correct PartialOrd eq, le, gt, etc handling*. With time, most of the collections maybe(?) will develop their own specialized versions and make it obsolete.

As noted in #26884, these methods are inferior for *equality* checking since they cannot assume that the two iterators are of equal length.

*Due to PartialOrd weirdness, every collection must implement all of lt, le, gt, ge.

**Comment by sfackler** [comment]
It seems like these should really be methods on `Iterator`:

```rust
pub trait Iterator {
    ....
    fn eq<E, I>(self, other: I) -> bool where Self::Item: Eq<E>, I: Iterator<Item = E> { ... }
    // etc
}
```

**Comment by sfackler** [comment]
Would like to stabilize these in the next cycle.

**Comment by SimonSapin** [comment]
> ```rust
> fn eq<E, I>(self, other: I) -> bool where Self: Sized, Self::Item: Eq<E>, I: Iterator<Item = E> { ... }
> ```

By the way, is this the same as
```rust
fn eq<I>(self, other: I) -> bool where Self: Sized, Self::Item: Eq<I::Item>, I: Iterator { ... }
```
?

**Comment by sfackler** [comment]
Your version's basically how it was actually defined when implemented: https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.cmp.

**Comment by alexcrichton** [comment]
This issue is now entering its cycle-long FCP for stabilization in 1.5

**Comment by nagisa** [comment]
Can’t these be implementations of PartialEq/PartialOrd instead?

**Comment by SimonSapin** [comment]
These traits take `&self`, while we need at least `&mut self` to consume the iterators here.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and the decision was to stabilize.
