### ISSUE TITLE
Tracking issue for `float_extras` stabilization

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#27752]
There are a number of floating point methods that are reexported from cmath, without a strong naming convention on the Rust side, or a clear rationale for which methods are included and which are not.

Ideally, someone who works with floating point, and these methods in particular, could offer advice/an RFC laying out a good vision for these methods.

**Comment by pyfisch** [comment]
For a CBOR serializer crate I used the `f32::ldexp` method, I hope to push this discussion forward so my crate will eventually work on stable in the future :grin: 

The unstable methods of `f64` are:
* `fn integer_decode(self) -> (u64, i16, i8)`
* `fn ldexp(x: f64, exp: isize) -> f64`
* `fn frexp(self) -> (f64, isize)`
* `fn next_after(self, other: f64) -> f64`

The unstable methods of `f32` are:
* `fn integer_decode(self) -> (u64, i16, i8)`
* `fn to_degrees(self) -> f32`
* `fn to_radians(self) -> f32`
* `fn ldexp(x: f32, exp: isize) -> f32`
* `fn frexp(self) -> (f32, isize)`
* `fn next_after(self, other: f32) -> f32`

I wonder why `to_degrees()` and `to_radians()` are stable for `f64` but not for `f32` since both implement the same trigonometric functions so they are equally usefull on both types.

The `ldexp` function should use `i32` instead of `isize` since it does not deal with memory locations. In C ldexp is defined as `double ldexp (double x, int exp);` so it also uses only four bytes. Since it carries the exponent the value will always be much smaller than `i32::MAX`. #22098 is a discussion about if `ldexp` should become a method or stay a function. Since all other operations for floats take self as the first argument I would change `ldexp` to a method.

`frexp` is the counterpart of `ldexp` and should use the same types.

I don't know what should happen with `integer_decode`. C does not have a corresponding function and I also do not know what the use case for this function is. Can somebody please give me a hint?

`next_after` is a rust port of the `nextafter` C function. I am unsure if it should be stabilized now.

**Comment by rkruppe** [comment]
`ldexp` and `frexp` are C-isms. I suspect these functions are the way they are not because it's the best design but because the C standard doesn't guarantee anything about the implementation of `float` and `double`. Take my opinion with a grain of salt, I never had to use those functions in Rust nor in C.But most people that I've heard talk about those functions, they pitch it as a way to manipulate the mantissa and the exponent directly. If that is indeed the primary use case, then I believe it is better served with something closer to `integer_decode`.

@pyfisch Could you elaborate what you're using `ldexp` for?

**Comment by pyfisch** [comment]
@rkruppe: I use them to decode half floats to f32: https://github.com/pyfisch/cbor/blob/master/src/de.rs#L173

**Comment by rkruppe** [comment]
Oh, so you're also using `ldexp` in lieu of a proper API for disassembling and reassembling IEEE 754 floats. As I said before, I think `integer_decode` (after a substantial overhaul) and a hypothetical inverse `integer_encode`. I am not wedded to the names and the tuple return type (a proper struct may be better), but in any case it should be explicit about what it does.

**Comment by Lisoph** [comment]
Personally, I haven't written a single program, in which I wouldn't have needed the radian / degree conversion methods. Seeing the f32 versions being stabilized would be a bliss.

**Comment by aturon** [comment]
@Lisoph D'oh! That seems to just be an oversight; the ones on `f64` are stable. Are you interested in writing a stabilization PR? If not, I can do it.

**Comment by Lisoph** [comment]
@aturon I submitted [an issue](https://github.com/rust-lang/rfcs/issues/1438), was that the right thing to do? I'm new to Rust's RFC culture so I'm wondering.

**Comment by aturon** [comment]
@Lisoph That's fine -- if you'd like, you can also submit a PR to stabilize it. If not, I or someone else from the libs team will take care of it soon!

**Comment by brson** [comment]
+1 to any resolution to these. Don't care much at this point about the naming question or the exact functionality. Let's just decide.

**Comment by rkruppe** [comment]
If the choice is to stabilize or deprecate now, I would plead for deprecating them. The current interface is sub-par, designing a good one is hard, and this functionality can easily be implemented with `transmute` or by using a crate such as `ieee754`.

**Comment by alexcrichton** [comment]
🔔 This issue is now entering its **final comment period** 🔔 

The libs team was unfortunately a little late on stabilizations this cycle, but we're thinking of probably doing a backport of stabilizations partway through the beta cycle. We were somewhat ambivalent if I remember correctly on whether to stabilize or deprecate these functions. The functionality is likely needed by *someone*, but the names are unfortunately sub-par wrt the rest of the module.

**Comment by pyfisch** [comment]
I think they should be deprecated since they are not used often enough. Maybe some will be reintroduced in the future with better names.

**Comment by alexcrichton** [comment]
The libs team discussed this issue during triage yesterday and the decision was to **deprecate**. We realize that the FCP for this issue was pretty short, however, so please comment with any objections you might have! We're very willing to backport an un-deprecate for the few APIs we have this cycle.

**Comment by jethrogb** [comment]
I was integer_decode to [compute an integer's next-highest power of 2](https://graphics.stanford.edu/~seander/bithacks.html#RoundUpPowerOf2Float)

**Comment by nathanaeljones** [comment]
next_after is extremely useful for unit testing with floats...
