### ISSUE TITLE
Tracking issue for collection append methods

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27765]
This is a tracking issue for the unstable `append` feature in the standard library. It's somewhat unclear if these methods *need* to be stabilized, but it's also fairly clear that they're not going to change from their current form. They will likely go into FCP soon.

cc @Gankro.

**Comment by Gankro** [comment]
`foo.append(bar)` is semantically `foo.extend(bar.drain(..))`. Pretty specific, but ripe for optimization. In particular it was motivated by LinkedList which can just mangle some pointers instead of actually moving anything. It's also stable on LinkedList.

In principle, specialization "solves" this function in a much more flexible way.

**Comment by alexcrichton** [comment]
This feature is now entering its final comment period for stabilization.

**Comment by alexcrichton** [comment]
@hartsantler's [thoughts](https://github.com/rust-lang/rust/issues/28223#issue-104815082):

Coming from Python, as many others probably are, i find the method name `append` to be misleading.
From the rust docs:
http://doc.rust-lang.org/std/vec/struct.Vec.html#method.append

__Moves all the elements of other into Self, leaving other empty.__

This is similar to the `extend` method in Python, but still a little different because it moves the elements into self.  I think it makes much sense to call the method something like: `merge` or `move_from`
