### ISSUE TITLE
Tracking issue for collection split_off methods

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27766]
This is a tracking issue for the unstable `split_off` feature in the standard library. It's somewhat unclear if these methods need to be stabilized, but it's also fairly clear that they're not going to change from their current form. They will likely go into FCP soon.

cc @Gankro.

**Comment by Gankro** [comment]
`foo.split_off(x)` is semantically `foo.drain(x..).collect()`. Pretty specific, but ripe for optimization. In particular it was motivated by LinkedList which can just mangle some pointers instead of actually moving anything. It's also stable on LinkedList.

In principle, specialization "solves" this function in a much more flexible way.

**Comment by alexcrichton** [comment]
This feature is now entering its final comment period for stabilization.
