### ISSUE TITLE
Tracking issue for unix::FileTypeExt

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27796]
This is a tracking issue for the unstable `file_type_ext` feature in the standard library.

I think this is basically good to go, it'll likely expand over time but otherwise it's pretty self explanatory.

**Comment by alexcrichton** [comment]
Nominating for 1.5 resolution

**Comment by lfairy** [comment]
Since the file types are mutually exclusive, would it be better to return an enum instead?

Though I think the primary use case would be "is the type of this == X" so the current API would be fine.

**Comment by SimonSapin** [comment]
`std::os::unix::fs::FileTypeExt` only exists on Unix platforms, and is deliberately a trait (rather than conditionally-compiled inherent methods) so that you have to import it to use it, and see (with the `os::unix` bit) that you’re using something platform-specific. I don’t know if the same separation would be possible with enum variants.

**Comment by alexcrichton** [comment]
This issue is now entering its cycle-long FCP for stabilization in 1.5

**Comment by alexcrichton** [comment]
The libs team discussed this today and the decision was to stabilize.
