### ISSUE TITLE
Tracking issue for extra linked list methods

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27794]
This is a tracking issue for the unstable `linked_list_extras` methods in the standard library.

cc @Gankro, perhaps you can fill this in some more? The specific methods in question are:
- `IterMut::insert_next`
- `IterMut::peek_next`

**Comment by Gankro** [comment]
This is basically a lame version of cursors, which is what we should use instead imo. It's not 1:1 though -- this api lets you have all the elements yielded at once. Classic iterator tradeoff.

**Comment by steveklabnik** [comment]
Triage: these are still unstable.

**Comment by dtolnay** [comment]
There are some ideas for a more complete `IterMut` API in https://github.com/rust-lang/rust/issues/39148#issuecomment-273612068.

**Comment by dtolnay** [comment]
`IterMut::peek_next` seems misnamed. Doesn't it do exactly what we call `peek()` elsewhere?

**Comment by Amanieu** [comment]
I'm going to echo @Gankro's thoughts:

> This is basically a lame version of cursors, which is what we should use instead imo.

An iterator conceptually represents a (double-ended) range of elements. The only operation that it supports is popping an element off the end of that range.

A cursor on the other hand represents a **position** in a collection, and can be moved backwards or forwards in the collection. The cursor can be used to insert or remove an element at any given position in the collection.

I strongly oppose adding insertion/deleting methods to `IterMut` since they do not fit at all with existing iterator usage patterns (`for` loops and functional-style methods).

As I mentioned in the linked thread, a design based on the [`Cursor`](https://amanieu.github.io/intrusive-rs/intrusive_collections/linked_list/struct.Cursor.html) and [`CursotMut`](https://amanieu.github.io/intrusive-rs/intrusive_collections/linked_list/struct.CursorMut.html) types in `intrusive-collections` could be used.

**Comment by Amanieu** [comment]
Since we now have cursors, I think these methods should be removed.

**Comment by Amanieu** [comment]
Reopening since we only deprecated the methods instead of removing them. I'd say give it about 2 weeks then remove them.
