### ISSUE TITLE
Vec::reserve and Vec::reserve_exact examples should be differentiated 

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#27852]
`Vec::reserve` and `Vec::reserve_exact` are two different methods that do slightly different things

* https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.reserve
* https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.reserve_exact

Right now, both of their examples are virtually identical.

```rust
let mut vec = vec![1];
vec.reserve(10);
assert!(vec.capacity() >= 11);
```

```rust
let mut vec = vec![1];
vec.reserve_exact(10);
assert!(vec.capacity() >= 11);
```

Considering these two methods have different behavior, ideally the examples would demonstrate more clearly how they differ. That said, I haven't though of anything good yet, but I thought I might as well open this. If the differences are too subtle to demonstrate in an example, this can be closed.

**Comment by steveklabnik** [comment]
The hard part about writing an example for this is that what they affect isn't something you can see directly: the amount of memory that may or may not get allocated. `reserve` _might_ do the same thing, but also might not, and is deliberately under-specified so that different allocators can choose what to do.

 I'm also open to improving any example, but without a concrete suggestion, I don't think we can move forward here. If you (or anyone finding this ticket later) can think of something, please leave a note and I'll re-open!
