### ISSUE TITLE
Pipe character in rustdoc markdown tables can not be escaped

### ISSUE THREAD

**Issue by m4rw3r** [rust-lang/rust#27862]
Attempting to use the pipe symbol in tables in doc-comments does not work as it will be interpreted as a table-separator even when attempting to escape it. Attempts to use html-entities also fails (ie. ``&#124;``) and they end up escaped.

Example:
```markdown
Test  | Table
------|-----------
t = b | id = |x| x
```

This causes only ``f = `` to be rendered in the right cell instead of the expected ``f = |x| x``.

Looking at Hoedown it seems like they fixed this in commit https://github.com/hoedown/hoedown/commit/e7bcbe3fa62165d3d6c6f4fe619ecfb38122293a , which would enable us to write this:

```markdown
Test  | Table
------|-------------
t = b | id = \|x\| x
```

**Comment by alexcrichton** [comment]
I think all we probably need to do here is update the hoedown submodule and double-check the FFI bindings didn't change, other than that it should just work after that!

**Comment by greyblake** [comment]
In 2023, I seem still to experience this issue.

**Comment by vallentin** [comment]
I just encountered this as well, which confused me, as it is [mentioned in the rustdoc book](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html#tables)

**Comment by vallentin** [comment]
Correction. In my case, it rendered incorrectly due to `pulldown-cmark` not supporting tables being indented.

Issue: https://github.com/raphlinus/pulldown-cmark/issues/656

E.g. if I had the following doc comment:

```rust
//! Foo
//!
//! | A | B |
//! |---|---|
//! | 1 | 2 |
```

Then the table renders correctly:

![image](https://github.com/rust-lang/rust/assets/17464404/a5b609bf-2f72-4817-af10-1e7cf60aeb48)

However, if the table is indented, then it renders as plain text. This can occur if another line is not indented correctly, e.g.:

```rust
//!Foo
//!
//! | A | B |
//! |---|---|
//! | 1 | 2 |
```

Notice how `Foo` is not indented with 1 space. Thus the table is indented by 1 space relative to the "Foo" text. This caused the table to render incorrectly for me:

![image](https://github.com/rust-lang/rust/assets/17464404/e3398b99-5038-4e10-9d47-1919641c5cdc)
