### ISSUE TITLE
dining philosophers does not actually exhibit deadlock

### ISSUE THREAD

**Issue by mjhoy** [rust-lang/rust#27932]
In the Dining Philosophers doc page, the `eat` function is implemented:

```
fn eat(&self, table: &Table) {
    let _left = table.forks[self.left].lock().unwrap();
    let _right = table.forks[self.right].lock().unwrap();

    println!("{} is eating.", self.name);

    thread::sleep_ms(1000);

    println!("{} is done eating.", self.name);
}
```

The problem is this will not deadlock even when Foucault is right-handed: the implementation given solves the problem in another way, which is that philosophers take both left and right forks at the same time. In fact the left fork should be taken first, and then only after some time is given to the philosopher to grab food, the right fork should be taken. Something like:

```
fn eat(&self, table: &Table) {
    let _left = table.forks[self.left].lock().unwrap();

    println!("{} is grabbing food.", self.name);

    thread::sleep_ms(400);

    let _right = table.forks[self.right].lock().unwrap();

    println!("{} is eating.", self.name);

    thread::sleep_ms(1000);

    println!("{} is done eating.", self.name);
}
```

Now the problem will deadlock if Foucault is right-handed (and Foucault being left-handed is now a real solution).

**Comment by dotdash** [comment]
The original code _can_ deadlock, it is just extreme unlikely, because each philosopher only eats once and there's an offset between the threads (because starting a thread takes non-zero time). The offset makes it happen that the first philosopher gets to eat before the second one gets to pick up the first fork. The theoretical possibility for a dead lock is still there though.

The issue I have with your suggestion is that it ends up with a pretty deterministic deadlock, because the window for it is so huge. And IMHO that gives a wrong impression WRT the general case. If you want to demonstrate the deadlock in practice, I'd suggest to remove the `sleep_ms()` calls all together and loop in the thread, so that the philosophers try to eat all the time and not just once. That gives you a program that will usually deadlock really really quick, but the "eating trace" you get looks different every time.

**Comment by mjhoy** [comment]
> The issue I have with your suggestion is that it ends up with a pretty deterministic deadlock

Still, it doesn't seem to accurately represent the description, of a philosopher grabbing a left fork, taking some time to reach for the food, and only then grabbing the right fork (and then taking some time to eat).

It seems to me that the purpose of that section was to set up a (mostly) deterministic deadlock, and then find a way of solving it. In any case I was a little confused. I think removing the sleep calls as you suggest and looping would make it more clear.

**Comment by steveklabnik** [comment]
We've ended up adding some stuff that fixes this.
