### ISSUE TITLE
Binary releases of Rust targeting musl

### ISSUE THREAD

**Issue by jimmycuadra** [rust-lang/rust#27933]
The [Rust 1.1.0 blog post](http://blog.rust-lang.org/2015/06/25/Rust-1.1.html) said that nightly binary releases of Rust using musl instead of glibc on Linux were coming. I am not spotting any in [this distribution index](https://static.rust-lang.org/dist/index.html). Is this still planned for the near future? Once musl support is no longer "experimental" will binary distributions for it be featured as an alternative choice for Linux on https://www.rust-lang.org/install.html?

**Comment by SimonSapin** [comment]
It [looks like](https://github.com/rust-lang/rust/pull/24777) musl is treated as just another [cross-compilation](http://blog.rust-lang.org/2015/08/14/Next-year.html#cross-compilation) target. So rather than separate downloads for the entire distribution I’d expect downloads of only libstd for various targets and some tooling (maybe in Cargo?) to fetch them automatically when needed.

**Comment by steveklabnik** [comment]
@jimmycuadra since this isn't a bug, would you mind opening this discussion over at https://internals.rust-lang.org? It's better for things like this.

**Comment by jimmycuadra** [comment]
@SimonSapin You need a version of the compiler built with musl support enabled to do this. What I am hoping for is an official distribution of that build so you don't have to compile rustc yourself on every new release.

Discussion continued here, per Steve's request: https://internals.rust-lang.org/t/static-binary-support-in-rust/2011
