### ISSUE TITLE
Lifetime in trait method declaration affects RFC 1214 checks

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#27987]
``` rust
trait Test {
    fn f<'a>(&self) where PartialEq<i32> : std::fmt::Display {}
}
trait Test2 {
    fn f<'a>(&self) where (PartialEq<i32> + 'a) : std::fmt::Display {}
}
fn main() {
}
```

Currently, Test1 triggers an "error", but Test2 doesn't.  I would expect them to be treated the same way.

**Comment by arielb1** [comment]
this is because `middle::traits::normalize_param_env` both
  * registers all predicates as obligations
  * adds all non-global predicates (these that don't contain lifetimes or type-variables) to the param-env where-clauses list

for this reason, predicates that contain lifetimes or type parameters can be used to satisfy themselves, while others can't. This is only an RFC1214 error because you did it in a trait method.

Type-less predicates being allowed can indeed cause ICEs:
```Rust
struct S;
impl S {
    pub fn f<'a>(&self, f: &'a f32) where u32: PartialEq<&'a f32> {
        4==f;
    }
}
fn main() {}
```

**Comment by nikomatsakis** [comment]
This has to do w/ the [early- vs late-bound lifetime distinction][1]. I'd like to ease and remove that distinction, but it'll take more effort to get there. 

[1]: http://smallcultfollowing.com/babysteps/blog/2013/11/04/intermingled-parameter-lists/

**Comment by arielb1** [comment]
@nikomatsakis 

No it doesn't. Nothing changes if you force `'a` to be early-bound - e.g. by adding `&'a (): Sized`. This is just an consequence of the global-predicate-ignoring restriction.

**Comment by nikomatsakis** [comment]
@arielb1 ah I see, yes, I stand corrected.

**Comment by steveklabnik** [comment]
1. @arielb1 's example no longer ICEs.
2. `Test2` now compiles, `Test` does not.

I don't know what this means regarding the bug.

**Comment by arielb1** [comment]
The ICE was fixed by me in #42797, the "global predicate" thing is still present.

**Comment by Enselic** [comment]
Triage: This has been marked P-low for 6 years, and during that time has had no updates at all. Note in particular the lack of "duplicate of" or "I also have this problem" comments. It seems very unlikely this issue will ever get fixed. Rather than keeping this open forever, let's close it as "won't fix".

**Comment by oli-obk** [comment]
Both function pass with `#![feature(trivial_bounds)]` (as suggested by the diagnostic). So linking to https://github.com/rust-lang/rust/issues/48214 which is the tracking issue for that feature.

I don't think we need this issue specifically to track such behaviour
