### ISSUE TITLE
Anomalous unstable feature annotations

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#28037]
After submitting #28031, I ran a [script](https://gist.github.com/durka/a5243440697c780f669b) on the rest of src/ and I found several feature annotations that seem anomalous. A few I thought were obvious and I submitted another PR #28038.

This short list contains the ones that I'm not sure about -- either features that reference issue 0, or where the feature name is inconsistent with other annotations referencing the same issue.

I skipped any feature names containing the word "internals", and a few other clear false positives, because I figure those are never meant to be stabilized, so they are allowed to reference issue 0.

- [src/liballoc/boxed.rs](../blob/master/src/liballoc/boxed.rs)
    - line 480: feature "fnbox" points to issue 0
    - lines 88 and 95: feature "box_heap" is supposedly deprecated (#26914)
    - line 127: feature "placement_in" should maybe be "placement_new_protocol"
- [src/libcore/iter.rs](../blob/master/src/libcore/iter.rs)
    - line 2188: feature "step_trait" should maybe be "step_by"
- [src/libstd/error.rs](../blob/master/src/libstd/error.rs)
    - line 80: feature "error_type_id" should maybe be "get_type_id"

**Comment by alexcrichton** [comment]
Yeah issue 0 == "this probably won't ever be stabilized",  and FnBox currently falls into that category (it's just a stopgap for now). Otherwise we don't require issues on deprecated features (as the decision on that feature is already made).

Finally, the feature names specific are a bit nebulous but it's not intended that all features pointing at the same issue have the exact same feature name. We still want the ability to move things around and stabilize subsets if possible.

For now I believe these are all intentional, though, so closing, but thanks for doing the audit!

**Comment by durka** [comment]
@alexcrichton I re-ran the audit checking for `#![unstable(...)]` and I found two more:

- "enum_set" in libcollections has no issue. Seems like it ought to point at #18424 (unless EnumSet has been dropped since then? Pretty old RFC).
- "core_simd" in libcore/simd_old has no issue. Should it point at rust-lang/rfcs#1199 or is this file just outdated?

**Comment by alexcrichton** [comment]
Ah it's ok for those two as they're both deprecated at this point, so they won't need a tracking issue

**Comment by durka** [comment]
All right, that's what I figured even though I didn't see a deprecation annotation. The EnumSet one is a bit confusing, because you can come across it in the docs and it sounds like it's awaiting stabilization, but it's just a relic I guess. Thanks for putting up with my nitpicking!

**Comment by alexcrichton** [comment]
Oh no problem, thanks for the thorough investigation!
