### ISSUE TITLE
Command::{spawn, status, output} take &mut self unnecessarily

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#28127]
All three are used to actually run the command, and simply delegate to `spawn_inner`, which only requires `&self`.

This is confusing because it appears that a `Command` is intended to be reusable, but taking a `&mut self` prevents the command being shared, and suggests that a past run may modify the `Command` itself in some way, which it can't.

**Comment by alexcrichton** [comment]
This is actually currently intentional to make way for future improvements. One day we may want to allow passing in custom I/O handles into a `Command` for stdio handles, and in that case `spawn` will want to `take()` the fields most likely in which case a mutable reference will be needed.

As this is intended, however, I'm gonna close this.
