### ISSUE TITLE
Extend unused_parens lint to cover plain range literals

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust#28121]
For example match `for x in (1..10) { .. }`, but not `for x in (1..10).step_by(2) { .. }`, because in the latter case, the parenthesis are actually needed.

This should match expression nodes against `ExprParen(ref inner)` where `inner.node` is a `ExprRange(..)`, and the parent node isn't a synthesized method call (the `span` should have the required info).

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
