### ISSUE TITLE
HIR: separate AST and HIR lints

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#28145]
Lints are a pain at the moment because they operate on the AST but need type info which belongs to the HIR. We should have two kinds of lints - purely syntactic ones which operate on the (expanded) AST and run early (before AST->HIR lowering) and ones which can access type info and operate on the HIR (in the current position). We probably need to think about how this will interact with the MIR too.

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust/pull/28192 moves lints to HIR so that existing lints can upgrade easily. As a next step we can move that folder to `librustc_front/lint` and restore the original `librustc_lint`. The only builtin lint that needs the AST is the unused parentheses one, and at the moment `ExprParen` exists in the HIR so it's not yet broken.

**Comment by eddyb** [comment]
@Manishearth I'm not sure it's just the parenthesis lint, but at least that one can be moved to an AST lint later, if/when `ExprParen` is gone from the HIR.

**Comment by nrc** [comment]
Closed by #28349
