### ISSUE TITLE
Release versions of Rust need special flags to compile

### ISSUE THREAD

**Issue by radare** [rust-lang/rust#28317]
Looks like distros need to build Rust with some specific flags to get them work as expected. This can be problematic for packagers and users of non-official-builds of Rust, so I think that this must be clearly described somewhere.

Another option would be to just set those options by default when building from tarball

**Comment by radare** [comment]
It seems that current build flags are:
```
../configure --disable-valgrind --enable-llvm-static-stdcpp --release-channel=stable --enable-dist-host-only --build=x86_64-unknown-linux-gnu
               --host=i686-unknown-linux-gnu,x86_64-unknown-linux-gnu
```

**Comment by radare** [comment]
Without the --release-channel=stable, `rustc -v` reports this:
```
$ rustc -vV
rustc 1.2.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.2.0-dev
```

(that -dev implies it's not a release)

**Comment by alexcrichton** [comment]
Unfortunately whatever defaults we choose for `./configure` will inevitably end up being incorrect for *someone* so I don't think there's really a situation we can get to where all our bots and packages pass 0 options and everything "just works". While I'm sure there are incremental improvements possible the current state of the world is working out pretty well for the defaults we have, and the only thing which may want to change is passing `--release-channel=stable` by default. Otherwise all options you've listed aren't required:

* `--disable-valgrind` - this basically doesn't do anything any more
* `--enable-llvm-static-stdcpp` - this is so our binaries work on as many distributions as possible, packagers do not want to pass this as they have other mechanisms for ensuring binary compatibility
* `--enable-dist-host-only` - you probably don't want this if you're not building more than one architecture, it's just a specific flag for us.
* `--build=x86_64-unknown-linux-gnu` - you don't need to pass this, it's automatically inferred
* `--host=i686-unknown-linux-gnu,x86_64-unknown-linux-gnu` - you don't need this unless there's more than one architecture you want to compile for.

As a result I'm going to close this for now (I don't think it's that actionable), but if you think `--release-channel=stable` should be the default could you open a separate issue? Thanks!

**Comment by radare** [comment]
Thanks! done in https://github.com/rust-lang/rust/issues/28322
