### ISSUE TITLE
List of commands and formats for the rustc testing setup?

### ISSUE THREAD

**Issue by christopherdumas** [rust-lang/rust#28367]
I'm trying to come up with some official documentation for the way we test the rust compiler. So far, I know of:

* `~^`, `~^^`, and `~|`
* `HELP`, `ERROR`

I'm a bit foggy on how the error text actually works too.

If anyone has anything to add to this, or any information about this, please post on this issue!

\- Thanks, Christopher

**Comment by jonas-schievink** [comment]
* Similar to `HELP` and `ERROR` there's `WARNING` and `NOTE`. The only one that's handled specially is `SUGGESTION`, which must follow a `HELP`, since suggestions don't print with line numbers.

* Codegen tests run with LLVM's FileCheck, which has its own directives

* Several header comments are understood:
 * `// ignore-X` where X is an architecture, OS or stage will ignore the test accordingly
 * `// ignore-pretty` will not compile the pretty-printed test (this is done to test the pretty-printer, but might not always work)
 * `ignore-test` always ignores the test
 * `ignore-lldb` and `ignore-gdb` will skip the debuginfo tests (I don't know much about this)
 * `min-{gdb,lldb}-version`
 * And everything in [here](https://github.com/rust-lang/rust/blob/99383f8f5c276d8060f2105ff7e678c81bf4df05/src/compiletest/header.rs#L21)
