### ISSUE TITLE
Panic condition documentation consistency

### ISSUE THREAD

**Issue by numberten** [rust-lang/rust#28384]
I noticed that the formatting of panic conditions in the documentation of a lot of functions seems to be inconsistent. Specifically it varies between simple warnings in the description of the function and 'Panics' subheaders with the panic condition listed below.

A good example being the difference between `split_at` and `chunks_mut` [here](https://doc.rust-lang.org/std/vec/struct.Vec.html).

I like that headers make it very explicit (visually) where the panic conditions in a function call are, but they can also lead to confusion since the same header used multiple times on a given page makes any links to them (via url#Header) direct to the topmost 'Panic' header.

**Comment by steveklabnik** [comment]
In general, they should all be with the header, yes. At this point, since we're still doing a lot of work on the std docs, I'm doing this as I go, rather than trying to do a whole audit of every function. So I've submitted a PR for `split_at`, and if you can enumerate any other places, I'm happy to knock them out.
