### ISSUE TITLE
Meaningless `pub` lint.

### ISSUE THREAD

**Issue by nixpulvis** [rust-lang/rust#28456]
I would expect a lint warning about `pub` declarations which aren't needed or meaningful.

```rust
mod a {
    struct A;
    
    impl A {
        pub fn x() { }
    }
}
```

This simple example would warn about a meaningless `pub` for the function `x`.

**Comment by retep998** [comment]
Note that it may be difficult to determine whether `pub` is meaningless, because if `A` is somehow re-exported to be accessible to outside modules, then the `pub` on `x` becomes meaningful.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
