### ISSUE TITLE
Negative blanket OIBIT impl treated as positive

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#28475]
`impl !Pod for .. {}` looks like it produces a positive impl.

[(playpen)](https://play.rust-lang.org/?gist=6b188c2bb938c1d831fc&version=nightly)

``` rust
#![feature(optin_builtin_traits)]

unsafe trait Pod {}

unsafe impl !Pod for .. {}

struct Foo<X, Y>(X, Y);

fn is_pod<T: Pod>(_: &T) { }

fn main() {
    is_pod(&Foo(0, 0));
}
```

cc @nikomatsakis 

OIBIT tracker issue: #13231

**Comment by arielb1** [comment]
Negative impls are only supposed to work if they are nominal (`impl<U,V,W> !Foo for Bar<U,V,W>`). We should however decide what this means.

**Comment by nikomatsakis** [comment]
`impl !Pod for ..` is certainly not legal, in any case.

**Comment by lcnr** [comment]
What exactly has to be done to close this issue?

The example given here doesn't seem to compile.

**Comment by jonas-schievink** [comment]
`impl Trait for ..` syntax doesn't exist anymore, so it's impossible to write this sort of impl now.

**Comment by nikomatsakis** [comment]
Yeah, that syntax never made sense, and has been replaced with "auto trait" (or is it `#[auto] trait`). Probably this issue is just "outmoded".

One thing is that I think we should not permit a negative impl like `impl<T> !Foo for T` -- i.e., negative impls should always be implemented for specific types. The truth is that we have to write out the specific rules at some point.
