### ISSUE TITLE
Lifetime of fn() converted to &Fn() isn't long enough

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#28546]
``` rust
fn double(x: i32) -> i32 { x * 2 }
fn get_double_func() -> &'static (Fn(i32) -> i32)
{
    // Works
    const GET_DOUBLE_FUNC: &'static (Fn(i32) -> i32) = &double;
    GET_DOUBLE_FUNC
}
fn get_double_func_2() -> &'static (Fn(i32) -> i32)
{
    // Error message
    &double
}
fn main() {}
```

It would be nice if the lifetime of `&double` were the same in all contexts.

**Comment by arielb1** [comment]
An `&'static Fn(i32) -> i32` is represented as a `(shim vtable, pointer-to-pointer-to-function)`

**Comment by krdln** [comment]
arielb: Note that double's type is `fn(i32) -> i32 { double }`, not just `fn(i32) -> i32`. In this case both the vtable and pointer-to-function are allocated in a static memory and the only change needed to fix that bug is making the lifetime `'static`.

Casting arbitrary `fn()` function pointers to a `'static Fn()` is a harder case, but it could be done too.

[Discussion on reddit](https://www.reddit.com/r/rust/comments/3n6izx/why_cant_you_cast_fn_to_static_fn/)

**Comment by nikomatsakis** [comment]
Seems related to https://github.com/rust-lang/rfcs/pull/1414. I agree it'd probably be nice for this to work.

**Comment by brson** [comment]
Tracking issue https://github.com/rust-lang/rust/issues/38865

**Comment by nikomatsakis** [comment]
Closing in favor of #38865. I'll copy the example over there.
