### ISSUE TITLE
[Rustonomicon] Show how to convert a trait object into concrete type 

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#28571]
Last night somebody asked how to convert a trait object where they knew the concrete type into the concrete type. I tried looking for the answer in the Rustonomicon, but alas, no answer was found. Should this be in there?

The answer has to do with transmuting into `std::raw::TraitObject`. Even if it's just a link to that type from the transmutation page, I think it's important to explicitly show that it is possible. One issue though, is that std::raw::TraitObject is currently unstable as per issue #27751.

**Comment by Gankro** [comment]
I was under the impression that the lang team (cc @nikomatsakis -- can't ping lang myself) wasn't happy with std::raw::TraitObject, so I'm kinda iffy about talking about it. Especially because this is a really specific usecase that's kinda sketchy right now. IDK. Maybe @aturon's inheritance stuff is the way forward?

**Comment by steveklabnik** [comment]
That's what I was under the impression of too

**Comment by aturon** [comment]
Yes, we don't have a stable, recommended way to do this at the moment.

Ultimately, we plan to support "upcasting" in traits (so that if you have `trait Foo: Any` you can go from `&Foo` to `&Any`). That will allow you to inherit from `Any` to get the kind of downcasting you want. It shouldn't be too hard, but it's not on anyone's plate at the moment.

**Comment by steveklabnik** [comment]
Okay! Giving this a close, then.
