### ISSUE TITLE
rustdoc searching doesn't clear list of results when X is pressed

### ISSUE THREAD

**Issue by trolleyman** [rust-lang/rust#28696]
When you search for something on the online docs (which I assume are generated using cargo doc) a list of results comes up. When you clear the search bar/press the X button it probably should clear the results to allow you to view the original page. Anyone know how to fix this?

**Comment by steveklabnik** [comment]
I don't believe that we have anything set up for that. Is there an "X" button? I don't see it anywhere. Regardless, clearing the box or pressing escape or something should probably clear it, for sure.

**Comment by trolleyman** [comment]
![image](https://cloud.githubusercontent.com/assets/4435960/10124789/f756a308-6555-11e5-920b-7ed2282d20b1.png)

**Comment by nagisa** [comment]
Search field is `type="search"` and therefore it might have various user agent specific functionality.

Simpler way to reproduce in a cross-UA way would be to follow these steps:

1. Enter a search query;
2. Clear the *whole* query at once by highlighting it and clicking backspace, delete or any other relevant button;
3. Observe Result list not changing.

---

We could go back to the page that was open before the search field was used to fix this. Note that we do know what page it was, because we simply append `?search=query` to the URI of the page we start the search at.

**Comment by nagisa** [comment]
I took a shot at it and in the half an hour I dedicated to it, all I found that search code is a complete mess and this might be harder to fix *correctly* than it might appear at a first glance.
