### ISSUE TITLE
Shouldn't the book be in a separate repo ?

### ISSUE THREAD

**Issue by tulio-albuquerque** [rust-lang/rust#28834]
I think that with this separation we could make the book more like the progit2 book and so make it more easy translate it in various languages

**Comment by steveklabnik** [comment]
The book also serves as a test suite as well.

We've talked about maybe doing this before, but there are too many good reasons not to. If you feel really strongly about this, let's talk about it over in internals.rust-Lang.org, but since this decision has been made, this isn't a bug, so I'm gonna give it a close. Thanks!

**Comment by tulio-albuquerque** [comment]
Ok, the topic is [here](https://internals.rust-lang.org/t/shouldnt-the-book-be-in-a-separate-repo/2724?u=tuco)
