### ISSUE TITLE
Build fails on Windows/MSYS2

### ISSUE THREAD

**Issue by nesteruk** [rust-lang/rust#28843]
Your Windows build instructions are out of date. First of all, the set of commands doesn't install GCC, so that has to be done separately. But even after that, there are plenty of issues that prevent compilation.

Please verify compilation on Windows and update the build instructions accordingly.

**Comment by jonas-schievink** [comment]
GCC is `mingw-w64-x86_64-gcc`, which is contained in the `mingw-w64-x86_64-toolchain` group, so it will be installed if you follow the instructions. Can you be a bit more specific? What exactly is the error you're getting?

**Comment by petrochenkov** [comment]
Sounds like you are trying to build it from "MSYS2 Shell" and not "MinGW-w64 Win64 Shell"

**Comment by nesteruk** [comment]
Yes, I'm building from the MSYS2 shell. Will try the mingw shell now.

On 5 October 2015 at 14:54, Vadim Petrochenkov <notifications@github.com>
wrote:

> Sounds like you are trying to build it from "MSYS2 Shell" and not
> "MinGW-w64 Win64 Shell"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang/rust/issues/28843#issuecomment-145504906>.
>



-- 
Dmitri Nesteruk
dmitrinesteruk@gmail.com
skype: dmitri.nesteruk

**Comment by nesteruk** [comment]
Here is the output I'm getting

llvm[3]: Building Release Archive Library libLLVMAnalysis.a
C:\Dropbox\Programs\msys64\mingw64\bin\ranlib.exe: unable to rename 'C:/Dropbox/Projects/Open-Source/rust/x86_64-pc-windows-gnu/llvm/Release/lib/libLLVMAnalysis.a'; reason: File exists
/c/Dropbox/Projects/Open-Source/rust/src/llvm/Makefile.rules:1279: recipe for target '/c/Dropbox/Projects/Open-Source/rust/x86_64-pc-windows-gnu/llvm/Release/lib/libLLVMAnalysis.a' failed
make[3]: *** [/c/Dropbox/Projects/Open-Source/rust/x86_64-pc-windows-gnu/llvm/Release/lib/libLLVMAnalysis.a] Error 1
make[3]: Leaving directory '/c/Dropbox/Projects/Open-Source/rust/x86_64-pc-windows-gnu/llvm/lib/Analysis'
/c/Dropbox/Projects/Open-Source/rust/src/llvm/Makefile.rules:939: recipe for target 'Analysis/.makeall' failed
make[2]: *** [Analysis/.makeall] Error 2
make[2]: Leaving directory '/c/Dropbox/Projects/Open-Source/rust/x86_64-pc-windows-gnu/llvm/lib'
/c/Dropbox/Projects/Open-Source/rust/src/llvm/Makefile.rules:880: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/c/Dropbox/Projects/Open-Source/rust/x86_64-pc-windows-gnu/llvm'
/c/Dropbox/Projects/Open-Source/rust/mk/llvm.mk:89: recipe for target '/c/Dropbox/Projects/Open-Source/rust/x86_64-pc-windows-gnu/llvm/Release/bin/llvm-config.exe' failed
make: *** [/c/Dropbox/Projects/Open-Source/rust/x86_64-pc-windows-gnu/llvm/Release/bin/llvm-config.exe] Error 2

**Comment by mingwandroid** [comment]
Are you actually building inside your Dropbox folder? If so it's likely that googledrivesync.exe is interfering files as the build process is attempting to modify them. Antivirus software can also do this.

**Comment by nesteruk** [comment]
No, that's definitely not it - I tried taking the files out of the folder. Also, `googledrivesync`, that has nothing to do with dropbox.

**Comment by mingwandroid** [comment]
Yeah, I needed more caffeine when I wrote `googledrivesync`, obviously I meant the `dropbox` client.

**Comment by nistvan86** [comment]
I'm trying to build rust with 64bit MSYS2 on Windows10 with the steps described in README.MD by installing a separate MingW GCC 4.9 based toolchain. However MingW cannot be installed right now, since the MingW installer fails to download repositories.txt (this bug reappers with MingW from time to time, the last instance is here: https://sourceforge.net/p/mingw-w64/bugs/528/)

Is there any way to get around it? Maybe using the mingw-get utility which works? Which packages should i choose in mingw-get to get the same environment? Or what about using Cygwin which is known to have a more stable installer? I'm using it's derivate called Babun daily in my work and I'm really satisfied with it.

(Just as a side note, I've tried downloading compiler suites from http://www.drangon.org/mingw/ but I'm getting various errors with that way too, and I'm not so experienced with GNU toolset compiling to know exactly if it's not my error. Also i like to stay with the GNU way since i would like to build rust in the end with `--target=arm-unknown-linux-gnueabi` using the Linaro ARM Windos toolchain in place).

**Comment by petrochenkov** [comment]
Build instructions for Windows were rewritten several times and the old build system is removed.
Please, open a new issue if something suspicious still happens.
