### ISSUE TITLE
Adding more information can make type inference fail.

### ISSUE THREAD

**Issue by Thiez** [rust-lang/rust#28943]
I think the case is best illustrated by an example:

```rust
fn test() -> Vec<u8> {
    let result = Some(5).into_iter().collect();

    // Introducing any of the commented out lines will make type inference fail.
    // &*result;
    // result.clone();
    // &result[..];

    result
}
```

Note that adding a type hint to the collect, (`collect::<Vec<_>>()`) will make all commented-out lines work as expected.

**Comment by arielb1** [comment]
@Thiez 

This is not adding more information, but rather using `result` before its type is known.

**Comment by Thiez** [comment]
I was under the impression that type inference took into account the entire function context, such as in this case:

```rust
fn test() -> Vec<u8> {
    fn print<T: std::fmt::Debug>(t: T) { println!("{:?}", t); }
    let x = 5;
    print(x);
    let y = x + x;
    vec![y]
}
```

Why does type inference even have a concept of 'before'? A type can't change.

**Comment by arielb1** [comment]
@Thiez 

Because of overloading and type-directed lookup, rustc can't figure out which function named `clone` you meant unless it knows enough about the type.

**Comment by Thiez** [comment]
Okay, so the real problem here is that Rust type inference is dumber than it could be, because it fails to take future information into account even though it easily could because types do not change? Should I rename the issue or create a new one?

**Comment by arielb1** [comment]
@Thiez 

This is a design limitation that is *really* unlikely to be fixed in the future, especially as coercion etc. work eagerly.

**Comment by Thiez** [comment]
What I'm trying to say is that there *is* sufficient information present to unambiguously determine the type of `result`. Could you please explain where the eager coercions could come in and how they affect type inference in this case? Because to me it just looks like the compiler chooses to remain ignorant about information 'in the future' even though types cannot change.

Could you please explain why the following function compiles while the original does not, and what coercions have to do with that?

```rust
fn test() -> Vec<u8> {
    let result = Some(5).into_iter().collect();
    if false { return result; }
    &*result;
    result.clone();
    &result[..];
    result
}
```

**Comment by arielb1** [comment]
@Thiez 

The return inside the "if false" informs rustc about the type to be assigned to `collect`.

**Comment by rkjnsn** [comment]
@arielb1

I am also a bit confused as to why this should fail:

    fn test() -> Vec<u8> {
        let result = Some(5).into_iter().collect();
        &*result;
        result
    }

but this should succeed:

    fn test() -> Vec<u8> {
        let result = Some(5).into_iter().collect();
        if false { return result; }
        &*result;
        result
    }

Both examples impose the exact same constraints on "result" by returning it.

> The return inside the "if false" informs rustc about the type to be assigned to collect.

This is true, but the return at the end of the function provides the *exact same* information, and is present in both examples.

It seems to me that it shouldn't make any different whether or not the return happens "before" (in terms of function execution) since, as @Thiez notes, types are fixed and to not change as the function execution progresses. What I would expect to happen would be for the compiler to look at all of the usages of a value such as `result` in the function (the order of those usages wouldn't matter), and build up a set of constraints on the type. Only if the constraints conflicted or if they still left the type ambiguous would I expect to see an error.
