### ISSUE TITLE
Rust book Ownership copy section seems wrong

### ISSUE THREAD

**Issue by barryp** [rust-lang/rust#28996]
In the Ownership page, under the Copy Types section, there's this (problematic part bolded):

> In this case, v is an i32, which implements the Copy trait. This means that, **just 
> like a move, when we assign v to v2, a copy of the data is made**. But, unlike a 
> move, we can still use v afterward.

I thought the whole point of moving is that you *don't* make a copy of the data.  If the sentence is wrong as I suspect, I'll suggest this:

> In this case, v is an i32, which implements the Copy trait. This means that, **unlike 
> a move, when we assign v to v2, a copy of the data is made and** we can still use
> v afterward.

**Comment by rkruppe** [comment]
This aspect of move semantics is tricky and can be hard to explain without being either imprecise or confusing. On the one hand, semantically you move the existing value instead of creating a new value. On the other hand, the physical reality is that the bits representing the value start off at memory location A and need to go into memory location B. This happens by copying the bits, no way around it. This is a shallow copy (e.g. when you move a `Vec`, you don't move the heap-allocated items of the `Vec`) and doesn't invoke `.clone()`, but it's still a copy in a certain sense. Just (as the text says) a "copy" where you aren't allowed to use the source of the "copy" afterwards.

As you can see, it takes rather many words to give an unambiguous account of the matter. I'm not sure whether it makes sense to explain these finer points in that part of the book. If so, it needs at least a separate paragraph. Otherwise, perhaps one can avoid the whole terminology question and just say that the operation is implemented the same as a move (or rather, a move is implemented the same way as a copy) and the only difference is whether you can use the moved/copied thing afterwards.

**Comment by steveklabnik** [comment]
Yes, it's very important to understand that moves and copies are the same, the only difference is the usage afterward.

**Comment by steveklabnik** [comment]
Given that this specific issue is a misunderstanding, I'm going to give this a close. I plan on expanding and re-wording this stuff in the future, and so this text is going to change anyway.
