### ISSUE TITLE
API Docs: convert

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29349]
Part of https://github.com/rust-lang/rust/issues/29329

http://doc.rust-lang.org/std/convert/

Here's what needs to be done to close out this issue: 

- [x] [the module documentation](https://doc.rust-lang.org/std/convert/) is great, but has a lot of abbreviations, so the wording could be cleaned up a bit.
- [x] [`AsMut`](https://doc.rust-lang.org/std/convert/trait.AsMut.html) should compare itself to `AsRef`, and should show a sample implementation.
- [x] [`AsRef`](https://doc.rust-lang.org/std/convert/trait.AsRef.html) needs far better docs, as it is one of the most misunderstood traits in Rust. Specifically it should talk about its relationship with `Borrow`. It also needs an example implementation.
- [x] [`From`](https://doc.rust-lang.org/std/convert/trait.From.html) needs a lot of work; it should talk about its usage in `?`, it should show an example implementation, and general improvement.
- [x] [`Into`](https://doc.rust-lang.org/std/convert/trait.Into.html) is mostly fine, but "generic impls" should say "implementations" and it should be above examples.

**Comment by steveklabnik** [comment]
I am happy to mentor anyone who wants to tackle this issue.

**Comment by maccoda** [comment]
I would be keen to give this one a go @steveklabnik

**Comment by steveklabnik** [comment]
Awesome, @maccoda ! Let me know if I can help you help me in any way 😄

**Comment by maccoda** [comment]
Hey @steveklabnik ,
Just a couple of questions:

1. In the issue description for the `Into` trait you say to have the generic implementations above the examples, 
> and it should be above examples.

It turns out all of the traits have the examples above the generic implementations. Should I move the generic implementations above the examples for all of the traits?

2. In adding sample implementation do you like to make a generic example or use a common example from the std lib? I only ask because I have become familiar with `AsRef` through the usage within the `fs` package in creating paths and was thinking of using this as an example. What are your thoughts?

3. The `AsRef` relationship with `Borrow` is where I am having a bit of trouble explaining this concisely. Are we wanting to have a brief summarization of the section in the book and do we need to reciprocate or align with the documentation for the `Borrow` trait? I only ask as I feel to explain the difference I am describing the `Borrow` trait a bit and do not want to introduce a second differing description.

Thanks :smile:

**Comment by steveklabnik** [comment]
Hey @maccoda !

> Should I move the generic implementations above the examples for all of the traits?

Yes, that'd be great!

> In adding sample implementation do you like to make a generic example or use a common example from the std lib?

Ideally, we'd have both: one extremely simple example for people to be able to copy/paste, and one more realistic example. Feel free to submit one or both 😄 

> The AsRef relationship with Borrow is where I am having a bit of trouble explaining this concisely.

yes it's tough!

> Are we wanting to have a brief summarization of the section in the book and do we need to reciprocate or align with the documentation for the Borrow trait?

The second edition of the book does not have that chapter; synchronizing these API docs is the right way to go 👍

**Comment by maccoda** [comment]
OK great :smile:  I will hopefully have something in today to start picking apart. :+1:

**Comment by maccoda** [comment]
Hey @steveklabnik ,
I had a look at the [RFC] mentioned in the contribution guide and couldn't find anything on the guidelines for line length. I only ask as one of the Travis builds failed due to the line exceeding 100 chars, so was wondering what I should be aiming for.

Thanks again! :smile: 


[RFC]: https://github.com/rust-lang/rfcs/blob/master/text/1574-more-api-documentation-conventions.md#appendix-a-full-conventions-text

**Comment by steveklabnik** [comment]
Standard library docs are wrapped to 80 characters. :)

**Comment by lawliet89** [comment]
@steveklabnik For `From needs a lot of work; it should talk about its usage in ?, it should show an example implementation, and general improvement.`, would the following be what you are looking for?

- Example of usage with `?` or `try!`: would something like [this](https://github.com/lawliet89/biscuit/blob/66fd3043c871343b56d63daf5026a6f338e958e6/src/errors.rs#L65-L79) without the macros, and some example usage with fns returning `Result<_, Error>` work?

 - An example implementation of `From` for some user-defined struct to something else, and then also show that `Into` is implicitly implemented.

**Comment by steveklabnik** [comment]
This is now done! 🎊
