### ISSUE TITLE
Regression: x86_64-pc-windows-msvc: can't find crate for `std` [E0463]

### ISSUE THREAD

**Issue by briansmith** [rust-lang/rust#29418]
I have a script that installs Rust on Windows the following way (on Appveyor):

1. Downloads https://static.rust-lang.org/dist/%RUST_TAR_GZ_BASE%.tar.gz
2. Extracts the file, leaving the Rust distribution in build/%RUST_TAR_GZ_BASE%
3.  SET PATH=%cd%\build\%RUST_TAR_GZ_BASE%\rustc\bin;%cd%\build\%RUST_TAR_GZ_BASE%\cargo\bin;%PATH%

Then, I could successfully build with `cargo build`. This worked fine through rustc 1.5.0-nightly (d3f497861 2015-10-18) / cargo 0.6.0-nightly (1a6d6c4 2015-10-18). However, as of rustc 1.5.0-nightly (7275d3d36 2015-10-20) / cargo 0.6.0-nightly (65f50e7 2015-10-19), this has stopped working with the error "can't find crate for `std` [E0463]"

I think this is likely due to https://github.com/rust-lang/rust/pull/29009 or related changes. cc @alexcrichton.

**Comment by briansmith** [comment]
Also, this works fine when you install using the MSI installer, as tested with rustc 1.5.0-nightly (7beebbe56 2015-10-22) / cargo 0.6.0-nightly (e1ed995 2015-10-22).

**Comment by alexcrichton** [comment]
Yeah we've split the standard library into a separate package now, so if RUSTC_TAR_GZ_BASE is the "rustc-nightly-$target" package then it won't have the standard library and you'll also need to download the "rust-std-nightly-$target" package. 

For now I'd recommend using the standard "rust-nightly-$target" installers as they should always work for getting a full installation

**Comment by briansmith** [comment]
Thanks! I believe I was using the .tar.gz because at one time not every channel had MSI/EXE installers for the -msvc targets.

In case somebody else had a similar issue as the one reported here, here is how I switched from using the .tar.gz to the MSI installer on AppVeyor: https://github.com/briansmith/ring/commit/6dc50ec6e6b40b7e0f99665053829113de5b80d9.

**Comment by retep998** [comment]
There is actually a .tar.gz for "rust-nightly-$target" for the windows targets although you need an MSYS environment to run the install.sh.

**Comment by cup** [comment]
https://github.com/rust-lang/rust/issues/33933

**Comment by cup** [comment]
https://github.com/rust-lang/rust/issues/29418
https://github.com/rust-lang/rust/issues/33933
https://github.com/rust-lang/rust/issues/60335

**Comment by cup** [comment]
I have solved this. Obviously the MSI files here:

https://forge.rust-lang.org/other-installation-methods#standalone-installers

are installers. However the TAR.GZ files are also installers. So to work with
the TAR.GZ, you need to do this:

~~~sh
./install.sh --verbose --prefix=/tmp \
--components=rustc,rust-mingw,rust-std-x86_64-pc-windows-gnu
~~~

or alternatively this:

~~~sh
cp -r -s "$PWD"/rust-std-x86_64-pc-windows-gnu/lib rustc
cp -r -s "$PWD"/rust-mingw/lib rustc
~~~

I disagree with the decision to make the TAR.GZ archives require installation:
the whole distributing an archive over an installer is so that users can extract
and go.
