### ISSUE TITLE
FFI write strange standard output

### ISSUE THREAD

**Issue by adjivas** [rust-lang/rust#29422]
Hello.

I tried this code:
```rust
#[cfg(any(unix))]
extern "C" {
    pub fn write(fd: i32, buf: *const i8, len: i32) -> i32;
}

macro_rules! write {
    ($text: expr) => ({
        let mut result: bool = false;

        for len in 0i32..std::i32::MAX {
            if unsafe {
                *$text.offset(len as isize)
            } == 0u8 {
                result = write!($text, len, 1);
                break ;
            }
        }
        result
    });
    ($text: expr, $len: expr, $out: expr) => ({
        match unsafe {
            write (
                $out as i32,
                $text as *const i8,
                $len as i32,
            )
        } {
          -1 => false,
          _ => true,
        }
    });
}

fn main() {
    write!("hello\n".as_ptr());
    write!(b"world\n".as_ptr());
}
```
I expected to see this happen:
```shell
hello
world

Program ended.
```
Instead, this happened:
```shell
hello
world
world

Program ended.
```

**Comment by huonw** [comment]
Rust strings aren't nul-terminated by default, so looking for one with a loop like that won't work, this code is hence undefined behaviour (the `offset`s are running off the end of the strings in memory) and its just random chance that the output is so close to what you expect. You can see the output change if you compile with optimisations (one good indicator of undefined behaviour).

The fix is to instead not rely on a nul-terminator, or make sure it is there (e.g. using `CStr` or `CString` in `std::ffi` or even manually putting a `\0` in the literal).
