### ISSUE TITLE
Mir: Trans Constant Operands

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#29572]
Translating constant operands in MIR is only partially implemented. We don't support it in all modes, and there are various kinds of constants that are unimplemented. See `librustc_trans/trans/mir/operand.rs` and `librustc_trans/trans/mir/constant.rs`

**Comment by nagisa** [comment]
It seems like there’s only `ConstVal::Function` in `librustc_trans/trans/consts.rs` left. Everything else seems to be implemented.

The problem is that, AFAIR, @oli-obk moved `trans_constval` from mir-specific code to `trans::consts`, but to translate `ConstVal::Function` you need code from `trans::mir::did`. So either we move `trans_constval` back into MIR-specific trans code, or attempt to find a place outside MIR-code for functions in `mir::did`.

**Comment by oli-obk** [comment]
it should be trivial to move back. I think it was only important to move it into its own function, it can reside in `trans::mir` without any troubles
