### ISSUE TITLE
404 link in std docs

### ISSUE THREAD

**Issue by benw** [rust-lang/rust#29584]
The link to "FullOps" on this page is broken: https://doc.rust-lang.org/std/primitive.u32.html

**Comment by rkruppe** [comment]
Background for anyone who wants to tackle this:

- `FullOps` is an unstable trait defined in a `doc(hidden)` module of `core` (specifically in `core::num::bignum`). It is an implementation detail that should not leak out.
- Because of the above, the fix is to not list the trait on the implementing type's page, **not** to generate a doc page for `FullOps`.
- Other examples of such traits are `RawFloat` and `DecodableFloat` on `f32` and `f64`, which are also listed on the respective pages with dead links.

**Comment by cdvv7788** [comment]
I want to give it a try, however i don't know what is the right way to test changes. How can i build only the related docs?
Make docs rebuilds everything, so it takes a while (even with the flag). How can i quickly test the html output for the docs without rebuilding everything?
I tried rustdoc 'path/to/file' too, but it is not able to compile the doc for that given file

**Comment by steveklabnik** [comment]
>  How can i quickly test the html output for the docs without rebuilding everything?

Unfortunately, this kind of change is just going to take forever to test. :/

>  I tried rustdoc 'path/to/file' too, but it is not able to compile the doc for that given file

You have to point it at a crate root, not just any rust file.

**Comment by cdvv7788** [comment]
:(
I will give a try to rustdoc once more. Compilations on my machine take around 1 hour, so i don't know if i can fix something that way.

**Comment by Ketsuban** [comment]
I believe I have an explanation.

The `#[doc(hidden)]` annotation on the modules ensures no documentation is created for the module or any traits or similar contained within it. However, when assessing whether `impl`s should be hidden on *other* pages the documentation compiler considers *only the hiddenness of the `impl` itself*, not its containing module.

I suspect the existing behaviour is working as intended—consider the case of someone putting their `impl Add<Foo> for Bar` (given public types Foo and Bar) in a doc-hidden module and then wondering where the `impl` went. I recommend the simple fix of putting `#[doc(hidden)]` on the `impl`s of the public-not-public traits.

**Comment by rkruppe** [comment]
@Ketsuban Thanka for tracking this down! You are right that impls in private modules should generally be displayed since they are public in a sense. But I think the current state of affairs is very unsatisfying, since Rustdoc generates broken docs for perfectly valid code. Shouldn't it at the very least somit links that will wind up dead? And if both trait and implementing type are dic(hidden), as is the case here, it seems like a reasonable heuristic to treat the impl as hidden too. I'm less sure about hidden traits in public types (e.g., RawFloat and f64) but if it's overridable it also seems sensible.

**Comment by Ketsuban** [comment]
Putting my real-world-concerns hat on, I think this is really just a corner case where `pub` and “public” don't coincide. The Right Thing is to propagate `#[doc(hidden)]` from traits to `impl`s of those traits; I don't know how difficult that is to do, so I opted for recommending a simple fix which I'd confirmed to work.
