### ISSUE TITLE
Tracking issue for `on_unimplemented` feature

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#29628]
The `on_unimplemented` feature provides the `#[rustc_on_unimplemented]` attribute, which allows trait definitions to add specialized notes to error messages when an implementation was expected but not found.

**WARNING:** This attribute, as all other `rustc_` attributes, is an internal implementation detail of `rustc` and is not meant to become stable.

**Comment by seanmonstar** [comment]
I think this would be 'private' to rustc.

**Comment by aturon** [comment]
@seanmonstar You may well be right, although it may be a useful feature for tailoring error messages around complicated user-space trait setups as well.

**Comment by sgrif** [comment]
As someone creating a library with complicated user-space trait setups, this would be an enormously useful feature. However I did notice an issue while using it, due to blanket impls.

When adding [this line](
https://github.com/sgrif/yaqb/blob/67337521b7febc67cb0e6dd387b70364238d3cf3/src/expression/mod.rs#L30), I would expect [this compile fail test](https://github.com/sgrif/yaqb/blob/67337521b7febc67cb0e6dd387b70364238d3cf3/tests/compile-fail/find_requires_correct_type.rs#L20) to contain "collections::string::String cannot be used in an expression of type yaqb::types::Serial". However, it doesn't even mention the annotated trait, since due to [this blanket impl](https://github.com/sgrif/yaqb/blob/67337521b7febc67cb0e6dd387b70364238d3cf3/src/expression/mod.rs#L37-L43), it doesn't even mention the annotated trait. Only the one that would satisfy the constraints of that blanket impl. (This is likely another manifestation of https://github.com/rust-lang/rust/issues/28894).

Also worth noting that it's impossible to test these w/ compile-fail at the moment, but that's tangential to this feature.

**Comment by SimonSapin** [comment]
Is it possible to improve the default diagnostics, without an opt-in feature?

**Comment by steveklabnik** [comment]
Triage: no real change. apparently servo uses this.

**Comment by SimonSapin** [comment]
Update: I’m moving usage of nice to have but not really required (optimizations, compiler diagnostics like this, …) unstable features in Servo behind an optional Cargo feature flag.

**Comment by Centril** [comment]
I would like to see an RFC for getting custom errors a la https://ghc.haskell.org/trac/ghc/wiki/Proposal/CustomTypeErrors in Rust.

**Comment by nvzqz** [comment]
What needs to be done to get this or something similar stabilized?

As some of you may know, `static_assertions` can have some gnarly error messages. So, I'm going to use this for https://github.com/nvzqz/static-assertions-rs/issues/24 under a `nightly` feature flag so then I can get much nicer errors:

```txt
error[E0277]: static assertion failed
  --> tests/messages.rs:14:1
   |
14 | assert_impl_one!(Foo: A, B, C);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   | |
   | `Foo` must implement exactly one of the given traits
   | required by `_::{{closure}}#0::AmbiguousIfMoreThanOne::some_item`
   |
   = help: the trait `_::{{closure}}#0::AmbiguousIfMoreThanOne<_>` is not implemented for `Foo`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

It would be wonderful if everyone who uses this crate can get decent error messages.

**Comment by Centril** [comment]
This is an internal `rustc_` attribute only for use by rustc. You should not rely on it. (In fact, this tracking issue should probably not exist -- @varkor should we make the the issue number to 0 and close this issue?)

**Comment by nvzqz** [comment]
Ah, I wasn't aware it was meant to be internal-only. @estebank had recommended it to me earlier today, so I figured it was fair game. What's the path to make something like this publicly usable?

**Comment by Centril** [comment]
> What's the path to make something like this publicly usable?

An elaborate RFC. :) The current implementation is an ad-hoc one based solely on what the needs of rustc is and any design would need to make sure to handle errors holistically (e.g. taking into account const generics, GHCs way of doing things, etc.) and not be too tied to rustc nor rustc too tied to the attribute. At any rate, this is not a priority and I don't think the language team has the bandwidth to make it one.

**Comment by varkor** [comment]
I'm surprised this is feature gated behind anything other than `rustc_private` (and hence that it has a tracking issue at all). This isn't intended to ever be stabilised (in its current form) and any work towards making it user-definable would require an RFC. I think it would be appropriate to close this issue, and if people want such a feature in non-rustc crates, a new feature request issue could be opened.

**Comment by Centril** [comment]
@varkor Yeah I agree; let's move it into `rustc_attrs` (I think that's the right feature gate).
