### ISSUE TITLE
Implement PartialEq for std::process::Command

### ISSUE THREAD

**Issue by rgardner** [rust-lang/rust#29631]
Currently, `Command` does not implement `Eq` or `PartialEq`. The implementation of `Command` is private so users are unable to write their own comparison function.

The tests in [src/std/process.rs](http://doc.rust-lang.org/src/std/process.rs.html) spawn actual programs and test their output. I'm writing a shell that hopes to support input/output file redirection, running processes in the background, and of course running commands with arguments. I'd like to be able to test that user input parsed correctly by comparing two Commands without running them.

A reasonable equality would be that the program name, argument lists (order (in)dependent), environments, and current_dir are the same at the time of the comparison. I'm not sure what comparing stdin/stdout/stderr would look like.
### Potential Issues

After some discussion on #rust, @talchas identified potential equivalence issues around `uid|gid` platform extensions, as well as comparing file descriptors. Reasonable defaults could be to compare `uid|gid` if they both exist, otherwise return false. For file descriptors, a reasonable rule could be to return false for duped file descriptors.
### Example

``` rust
use std::process::Command;

fn main() {
    let mut c = Command::new("prog");
    c.arg("arg");

    let mut other = Command::new("prog");
    other.arg("arg");
    assert_eq!(c, other);
}
```

[Playpen](http://is.gd/yiflXQ)

**Comment by jFransham** [comment]
The `Command` struct looks like this:
```rust
pub struct Command {
    inner: /*target-specific module*/::Command,
    stdin: Option<Stdio>,
    stdout: Option<Stdio>,
    stderr: Option<Stdio>,
}
```

`/*target-specific module*/::Command` looks to be comparable on Windows, but on Unix it contains `uid_t` and `gid_t` types, and I don't know if they are comparable. `Stdio` also doesn't implement `PartialEq`, so you would either have to ignore `stdin`, `stdout` and `stderr`, or implement `PartialEq` for `Stdio` (and `StdioImp`, which is the type that actually holds the data), but then you have to either implement `PartialEq` for `RawStdio` (which seems nonsensical for Windows, since it is a wrapper around a handle, and I believe handles are non-comparable in general. I think the same is true for Unix file descriptors but I am less sure about this) or alternatively alternatively just always pretend that `RawStdio`s are either always equal or never equal.

This last one is pretty horrible since in general Rust avoids making guarantees that are not completely true.

I am not extensively familiar with OS internals, and my assumption that Windows handles and Unix descriptors are non-comparable based on the fact that I believe that you cannot guarantee that two handles/descriptors refer to the same logical space just because they share an integer value. It's possible that there is a reliable way to check equality of these. I would very much like to be fact-checked on everything here.

**Comment by talchas** [comment]
Yes, you would need to implement PartialEq all the way down.

"you cannot guarantee that two handles/descriptors refer to the same logical space just because they share an integer value"

This is logically nonsensical, given the same context OS-wise (ie fd 0 of two different processes can certainly be different, but within a process it obviously is the same). Now, what exactly the boundaries of that are on windows I'm not certain (though I suspect it's process for handles), but if it's smaller than that you're already screwed because you've moved a Command across that boundary and changed the meaning.

Now, the /other/ direction is where you have issues - fd 0 and fd 1 can refer to the same kernel "file description" and thus are effectively the same (and I suspect there are similar issues on windows). Still, I think PartialEq via simple comparison is entirely reasonable for fds at least - a Command copying stdout and one copying stderr are logically different even if stdout and stderr happen to be redirected together this invocation. Windows is less clear if this /completely/ makes sense - it looks more common to DuplicateHandle than it is to dup(), but it is probably unlikely to be that surprising.

The point I was making about uid/gid is basically the same as stdin == Inherit vs Raw(0) - these may be the same thing but it's probably simpler to leave them as comparing different, and unlikely to be that shocking. (For uid/gid in particular, you could in theory setuid() and that shouldn't change Command equality).

**Comment by jFransham** [comment]
So if I understand correctly, could you just `#[derive(PartialEq)]` all the way down and get reasonably meaningful results?

**Comment by talchas** [comment]
Yeah, I think so.

**Comment by dtolnay** [comment]
From the discussion it sounds like the motivation of this would be to make it easier to write tests for a command line shell. It isn't clear to me that we could arrive at a definition of PartialEq that would make sense across a variety of use cases, especially when it comes to uid/gid and stdin/stdout/stderr. I am going to close this and recommend refactoring the shell in a way that allows you to test exactly what you want to test.

#### Before

```rust
fn parse_the_command(inputs: Inputs) -> Command { /* ... */ }

fn main() {
    let child = parse_the_command(/* ... */).spawn()?;
}

#[test]
fn test_parse_the_command() {
    let expected = /* ... */;
    let actual = parse_the_command(/* ... */);
    assert_eq!(expected, actual);
}
```

#### After

```rust
#[derive(PartialEq)]
struct Parse {
    cmd: OsString,
    args: Vec<OsString>,
}

fn parse_the_command(inputs: Inputs) -> Parse { /* ... */ }

fn main() {
    let parse = parse_the_command(/* ... */);
    let child = Command::new(parse.cmd).args(parse.args).spawn()?;
}

#[test]
fn test_parse_the_command() {
    let expected = /* ... */;
    let actual = parse_the_command(/* ... */);
    assert_eq!(expected, actual);
}
```
