### ISSUE TITLE
Tracking issue for `custom_attribute` features

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#29642]
Part of [RFC 572](https://github.com/rust-lang/rfcs/pull/572). This issue tracks stabilization/deprecation.

**Comment by brson** [comment]
Is this feature ever going to be stabilized?

It is currently used by Rocket: https://github.com/SergioBenitez/Rocket/issues/19#issuecomment-269052006. Does Rocket have alternatives?

**Comment by steveklabnik** [comment]
Isn't this part of macros 2.0? that is `#[proc_macro_attribute]` https://github.com/rust-lang/rfcs/blob/master/text/1566-proc-macros.md

**Comment by beamspease** [comment]
Just found this ticket as serde's main documentation says to use it...
https://serde.rs/enum-representations.html

**Comment by thijsc** [comment]
It seems like serde relies on this feature a lot, see: https://serde.rs/attributes.html

Is the plan to stabilize this?

**Comment by scottmcm** [comment]
If this is no longer for `rustc_attrs`, I think there should be a PR to the gate list and unstable book to stop pointing here, and say why.

**Comment by nikomatsakis** [comment]
Discussed in the @rust-lang/lang meeting:

We believe we should **remove** the `custom_attribute` feature gate from the compiler. If I'm not mistaken, it allows the older behavior where you could use any attribute `#[foo]` anywhere.  We don't — afaik — intend to go back to that world. Moreover, removing this feature would probably let us give more definitive and clear error messages that guide people towards using procedural macros.

I think this is the main chunk of code that would change:

https://github.com/rust-lang/rust/blob/daa53a52a2667533d5fe59bfcc5b8614b79c3d31/src/librustc_resolve/macros.rs#L316-L322

Nominating for @rust-lang/compiler mainly to see if anybody wants to follow-up or mentor this.

**Comment by nikomatsakis** [comment]
There are some *applicable* mentoring instructions here:

https://forge.rust-lang.org/stabilization-guide.html

However, these instructions are oriented towards **stabilizing** a feature. We want to **remove** the feature.

The main question mark for me is what sort of error we want to give. @cramertj had some ideas here.

Also: cc @dtolnay in case you can think of any problems with removing this. =)

**Comment by SimonSapin** [comment]
This does **not** include `rustc_plugin::registry::Registry::register_attribute`, right? (Servo still uses that, for [a custom lint](https://github.com/servo/servo/blob/866fd55ded6ded98b49862a29951d746a7846f64/components/script_plugins/lib.rs).)

**Comment by petrochenkov** [comment]
The way `custom_attribute` is implemented now (fallback from unresolved attributes) is certainly not appropriate for stabilization and even for keeping in unstable form.

If you search the rust codebase for `custom_attribute` though you'll see a lot of uses, most of them in the test suite.
Since it's useful for internal testing and similar things, I had an alternative idea in mind:
- Support explicitly registering custom inert attributes with a crate-level attribute `#![custom_attributes(attr1, attr2, ...)]`, still under the `custom_attribute` feature.
- Remove fallback-based custom attributes in its favor.
- Remove `rustc_plugin::registry::Registry::register_attribute` in its favor.
- Never stabilize it (possibly rename to `rustc_custom_attributes`), or, alternatively, stabilize it if it's still necessary in a couple of years or so.

>The main question mark for me is what sort of error we want to give

A usual error about unresolved name?

(I'll happily do the necessary work, it's already in my work queue.)

**Comment by Centril** [comment]
@petrochenkov 

> * Support explicitly registering custom inert attributes with a crate-level attribute `#![custom_attributes(attr1, attr2, ...)]`, still under the `custom_attribute` feature.

Interesting; could you elaborate a bit on the semantics of this?

**Comment by petrochenkov** [comment]
@Centril 
Same semantics as `Registry::register_attribute` - you get a name in prelude that refers to an inert attribute.

**Comment by dtolnay** [comment]
Thanks for the ping @nikomatsakis. I don't know of any code using custom_attribute and I don't have any reason to keep it.

**Comment by Centril** [comment]
@nikomatsakis 

> But that wouldn't accommodate the `register_attribute` use case. OTOH, I think the way we _want_ that to work is for the lint API to somehow declare the attributes that it may use, right? (Similar to custom derive)

Is this "lint API" for user defined lints? Can you elaborate on that (examples would be nice...)?

**Comment by nikomatsakis** [comment]
It is. It is also nowhere near stable, of course. I don't really remember the details -- basically there is some hook and you can invoke some methods to inject lints that the compiler will later run. Here is the example that @SimonSapin gave:

https://github.com/servo/servo/blob/866fd55ded6ded98b49862a29951d746a7846f64/components/script_plugins/lib.rs#L38-L46

(I presume that Clippy doesn't use any custom attributes? cc @oli-obk @Manishearth)

**Comment by Manishearth** [comment]
Oh, it doesn't, my bad. But they do have a use case there.

Either way, we _could_ scope them.

**Comment by petrochenkov** [comment]
Clippy can use "tool attributes" `clippy::foo` right now, because `clippy` and `rustfmt` are hard-coded in rustc in accordance with the tool attributes RFC.

In the future such attributes are supposed to be enabled though command line like `--tool clippy` (again, in accordance with the tool attributes RFC).
Non-clippy lints could use the same mechanism, like `--tool servo` + `#[servo::must_root]`.

**Comment by Centril** [comment]
@nikomatsakis 

> https://github.com/servo/servo/blob/866fd55ded6ded98b49862a29951d746a7846f64/components/script_plugins/lib.rs#L38-L46

Hmm... even if we had an API for defining lints, would that actually be of use since this depends on the HIR (and the type system... from what I can see, or at least it needs to operate on more than syntax?) ?

(also I was hoping for a more "here is what I think using the API would look like for an end user on stable..." =P )

**Comment by petrochenkov** [comment]
I submitted https://github.com/rust-lang/rust/pull/57921 to move this story further.

**Comment by pnkfelix** [comment]
> If this is no longer for `rustc_attrs`, I think there should be a PR to the gate list and unstable book to stop pointing here, and say why.

We probably should address the `rustc_attrs` question separately from how we resolve the custom_attributes matter in general.

(Unless our plan is to somehow use the same new machinery for both cases...?)

**Comment by petrochenkov** [comment]
Second attempt: https://github.com/rust-lang/rust/pull/66070.
