### ISSUE TITLE
Unfold

### ISSUE THREAD

**Issue by erip** [rust-lang/rust#29707]
I'm porting a library from Python to Rust and found [this](http://doc.rust-lang.org/std/iter/struct.Unfold.html) while looking for a substitute for generator functions in Python.

Is there a reason why it was removed? I noticed the comment about "not gaining enough traction" - what does this mean exactly?

I also found [iterators](http://rustbyexample.com/trait/iter.html) as an alternative, but Unfold seems more natural.

**Comment by Gankro** [comment]
We generally have a policy of keeping the standard library pretty lean because something that's stabilized is stabilized for life. These more exotic iterator adaptors didn't seem to be a big enough win to keep around. Thankfully, crates.io means it's trivial to pull in an external crate to get this kind of thing when we decide against it.

Unfold lives on in itertools: http://bluss.github.io/rust-itertools/doc/itertools/struct.Unfold.html

**Comment by Gankro** [comment]
Note that iterators aren't an "alternative" to Unfold. Unfold *is* an iterator.
