### ISSUE TITLE
Tracking issue for `no_debug` feature

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#29721]
Tracks stabilization of `#[no_debug]`.

**Comment by eefriedman** [comment]
The `#[no_debug]` suppresses debug info for the marked function (so the function is always compiled as if `-g` is turned off).

If we want to let people avoid stepping into a particular function, something like gcc's "artificial" function attribute is a better idea.  I can't think of any other good reason to suppress debug info.

If we do decide to stabilize this, we need some checks to make sure the attribute is only applied in places where it's actually supported.

**Comment by nrc** [comment]
Is anyone using this? What is the motivation for it existing?

Nominating for discussion/FCP (my opinion: deprecate unless someone really wants this).

**Comment by jonas-schievink** [comment]
A quick GitHub search finds no use of this

**Comment by petrochenkov** [comment]
>Is anyone using this? What is the motivation for it existing?

I use it as a workaround for https://github.com/rust-lang/rust/issues/35566.

**Comment by nikomatsakis** [comment]
**Hear ye, hear ye!** This unstable issue is now entering **final comment period** with the inclination to **deprecate and remove** -- basically because nobody seems to really want it.

@rust-lang/lang members, please check off your name to signal agreement. Leave a comment with concerns or objections. Others, please leave comments. Thanks!

- [x] @nikomatsakis
- [ ] @nrc 
- [ ] @aturon 
- [ ] @eddyb 
- [ ] @pnkfelix (on vacation)

**Comment by alexcrichton** [comment]
Deprecated in #37128, so closing.

**Comment by SimonSapin** [comment]
The deprecation landed on 2017-10-27. Can this feature be removed? (It still has an entry at https://doc.rust-lang.org/unstable-book/language-features/no-debug.html.)

**Comment by nikomatsakis** [comment]
@SimonSapin do it

**Comment by nikomatsakis** [comment]
(Or someone else :) )

**Comment by JohnTitor** [comment]
@nikomatsakis Removal is still valid? I've prepared the branch: https://github.com/JohnTitor/rust/tree/no-debug
