### ISSUE TITLE
Passing object with trait bounds stricter than needed fails to compile

### ISSUE THREAD

**Issue by alexbool** [rust-lang/rust#29831]
```rust
use std::sync::Arc;

struct DontNeedSend {
    f: Arc<Box<Fn()>>,
}

fn main() {
    let my_fn = Arc::new(Box::new(|| {}) as Box<Fn() + Send + Sync + 'static>);
    DontNeedSend {
        f: my_fn,
    };
}
```

```
<anon>:10:12: 10:17 error: mismatched types:
 expected `alloc::arc::Arc<Box<core::ops::Fn() + 'static>>`,
    found `alloc::arc::Arc<Box<core::ops::Fn() + Send + Sync>>`
(expected no bounds,
    found `Send + Sync`) [E0308]
<anon>:10         f: my_fn,
                     ^~~~~
<anon>:10:12: 10:17 help: see the detailed explanation for E0308
error: aborting due to previous error
```

Seems like this should compile, but it doesn't.
I reproduced this on all three release channels.

**Comment by eefriedman** [comment]
The conversion you're proposing is safe... but the reasoning required is kind of subtle: specifically, this is safe because Arc doesn't provide interior mutability.  (Converting from `Arc<Mutex<Box<Fn() + Send>>>` to `Arc<Mutex<Box<Fn()>>>` is not safe.)

This is probably more appropriate to file at https://github.com/rust-lang/rfcs/issues because it's a request for an addition to the language.

**Comment by arielb1** [comment]
@eefriedman 

The problem is that there is no subtyping relation between `Fn() + Send` and `Fn()`. It is an intentional design decision to limit subtyping to lifetimes. You may want to open an RFC issue, but changing this is low priority.
