### ISSUE TITLE
Where should cross-platform types go?

### ISSUE THREAD

**Issue by dimbleby** [rust-lang/rust#29926]
On Windows, the recent `libc` revamp moved quite a few types to `winapi`.  The result is that to write cross-platform code using such a type, I'm pretty much required to write my own boiler-plate module something like this:

```rust
#[cfg(windows)]
mod windows {
    extern crate winapi;
    pub type1 = winapi::type1;
    pub type2 = winapi::type2;
    ...
}

#[cfg(unix)]
mod unix {
    extern crate libc;
    pub type1 = libc::type1;
    pub type2 = libc::type2;
    ...
}

#[cfg(windows)]
pub use self::windows::*;

#[cfg(unix)]
pub use self::unix::*;
```

See for example [here](https://github.com/dimbleby/rust-c-ares/blob/master/src/ctypes.rs).

Not exactly the end of the world, but surely not ideal either:
- It's a little annoying for me to have to write this stuff
- It's more annoying for lots of authors to have to write this stuff.  
  - Sooner or later we'll have a `crate_a::type1`, a `crate_b::type1`, and a `crate_c::type1`; which all just seems to be noise that would be better avoided.

So can we do better?

Suggestions:

- Put the common types in `std::os::raw`
  - I don't know whether this is a good idea or not, because I don't understand what the intended purpose of `std::os::raw` is.  
  -  Currently it seems simply to duplicate stuff that's in `libc`.  Or perhaps `libc` is duplicating stuff that should be defined in `std::os::raw`?
  - Still if the intention is that `std::os::raw` is 'a place for useful and truly cross-platform types' then this sounds like a good plan.
- Release another crate to do the re-unification
  - Also seems like a reasonable plan, so long as the new crate is sufficiently blessed and publicised that it actually gets used
- Restore types to `libc`
  - I understand that there were good reasons for making the change in the first place
  - I mention this possibility only for completeness.
- Something else?
  - Not least: perhaps the current situation is in fact fine and I should stop worrying about it.

**Comment by alexcrichton** [comment]
Note that this was an [explicit drawback](https://github.com/rust-lang/rfcs/blob/master/text/1291-promote-libc.md#loss-of-windows-bindings) of the libc RFC, but otherwise this all generally jives with the current design today. 

The standard library currently doesn't strive to have an exhaustive set of bindings in `std::os::raw` but rather purely what's needed for the standard library itself. It was also definitely a possibility laid out in the libc RFC to have another umbrella crate which reexports all the shared types here and there, but that's currently out of the scope of the design of libc.

For now I'm going to close this, but feel free to open an issue against liblibc!
