### ISSUE TITLE
Merge commit messages don’t include PR titles

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#29958]
In a merge commit made by @bors, the commit message is:

* A first line containing the PR number, source repository and branch, and reviewer
* The PR message

The PR *title* is missing. In 2228bacd62ca8970a7a59401e78d0c5a34fc0f87 for example, the message starts with "Corresponds directly to llvm's inline-threshold." which doesn’t make much sense without the context of #29943’s title "Add -C inline-threshold".

This has been an issue for a long time, but it’s been fixed for Servo: compare https://github.com/servo/servo/commit/a5babb89a02b9b84a8cd62554a5ceef9efb0d481 and https://github.com/servo/servo/pull/8595.

Does the copy of bors/homu used by Rust need to be updated?

CC @edunham @pnkfelix

**Comment by Manishearth** [comment]
It's ancient. https://github.com/barosl/homu/commit/15ea10b8226a0544d92e4c3f8065705eae51b957

https://github.com/edunham/ansible-rust-infra/blob/e59bcf4e1c8cd40bc3a7089323d6511e2eb95802/roles/buildmaster/tasks/main.yaml#L47

**Comment by Manishearth** [comment]
Note that there have been a bunch of breaking changes in homu since then (grepping the git log will help for upgrading).

The other option is to blow away the venv and sqlite db, compare the config with the sample one and add any new compulsory keys, and re-run homu. This may lead to the current PR being tested going in a state of limbo, but otherwise works fine. You may have to hit the synchronize button on the queue afterwards.

**Comment by alexcrichton** [comment]
We updated homu, so I think this is taken care of now
