### ISSUE TITLE
BufReader example fails to compile

### ISSUE THREAD

**Issue by lojic** [rust-lang/rust#29957]
I tried compiling the first example for BufReader on this page:

https://doc.rust-lang.org/stable/std/io/struct.BufReader.html

I get the following:

```
$ cargo build --verbose
   Compiling pg_rust v0.1.0 (file:///Users/badkins/sync/clients/SebastianDehnel/aoc/pg_bench/pg_rust)
     Running `rustc src/main.rs --crate-name pg_rust --crate-type bin -g --out-dir /Users/badkins/sync/clients/SebastianDehnel/aoc/pg_bench/pg_rust/target/debug --emit=dep-info,link -L dependency=/Users/badkins/sync/clients/SebastianDehnel/aoc/pg_bench/pg_rust/target/debug -L dependency=/Users/badkins/sync/clients/SebastianDehnel/aoc/pg_bench/pg_rust/target/debug/deps`
src/main.rs:5:1: 5:4 error: expected item, found `let`
src/main.rs:5 let mut f = try!(File::open("log.txt"));
              ^~~
Could not compile `pg_rust`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name pg_rust --crate-type bin -g --out-dir /Users/badkins/sync/clients/SebastianDehnel/aoc/pg_bench/pg_rust/target/debug --emit=dep-info,link -L dependency=/Users/badkins/sync/clients/SebastianDehnel/aoc/pg_bench/pg_rust/target/debug -L dependency=/Users/badkins/sync/clients/SebastianDehnel/aoc/pg_bench/pg_rust/target/debug/deps` (exit code: 101)
```

**Comment by steveklabnik** [comment]
A few things:

1. I _think_ this error message happens because you don't have a `main()` function.
2. If you did wrap it in main, you'd still get an error, due to the `try!`, as `main()` doesn't return a `Result`.

The example does work, so I'm going to give the issue a close, but we can keep talking about it until you get it to work!

**Comment by lojic** [comment]
I don't have a main function because the example doesn't have a main function. I expected to be able to copy the example to a file, and compile it.

For what definition of "work" does the example work?

**Comment by steveklabnik** [comment]
Right, so, in API examples, we're often trying to just show how to use that API, not to write a full program. Almost none of the API documentation is just copy/paste-able into a random file, it's meant to be used in the context of other code. Showing `fn main() {` in every single example would waste space.

If you click the little arrow in the upper right of the examples (it's a larger run button on beta/nightly, hasn't hit stable yet), it will take you to a playpen link that has the full code.

In the case of this example, we take the code:

```
use std::io::prelude::*;
use std::io::BufReader;
use std::fs::File;

let mut f = try!(File::open("log.txt"));
let mut reader = BufReader::new(f);

let mut line = String::new();
let len = try!(reader.read_line(&mut line));
println!("First line is {} bytes long", len);
```

And put it in `main()`:

```
fn main() {
    use std::io::prelude::*;
    use std::io::BufReader;
    use std::fs::File;

    let mut f = try!(File::open("log.txt"));
    let mut reader = BufReader::new(f);

    let mut line = String::new();
    let len = try!(reader.read_line(&mut line));
    println!("First line is {} bytes long", len);
}
```

But, because of the `try!`, as I mentioned, this doesn't work. We have two options: remove the `try!` with `unwrap()`:

```
fn main() {
    use std::io::prelude::*;
    use std::io::BufReader;
    use std::fs::File;
    
    let mut f = File::open("log.txt").unwrap();
    let mut reader = BufReader::new(f);
    
    let mut line = String::new();
    let len = reader.read_line(&mut line).unwrap();
    println!("First line is {} bytes long", len);
}
```

This example will work, but will panic if there's an error, which isn't considered best practice. Instead, we can use a function that returns an `io::Result`:

```
fn main() {
    let result = try_read();

    if result.is_err() {
        println!("there was an error!");
    }
}

fn try_read() -> std::io::Result<()> {
    use std::io::prelude::*;
    use std::io::BufReader;
    use std::fs::File;

    let mut f = try!(File::open("log.txt"));
    let mut reader = BufReader::new(f);

    let mut line = String::new();
    let len = try!(reader.read_line(&mut line));
    println!("First line is {} bytes long", len);

    Ok(())
}
```

Of course, you may want to handle the error in `main()` differently, or only move some of this stuff into a function, or anything else. But that's why we don't show the boilerplate: it depends on what you're doing with your code.

**Comment by lojic** [comment]
Thanks for the help Steve! Sorry for the snarky comment previously - inappropriate frustration venting on my part.

**Comment by steveklabnik** [comment]
It's totally okay. This is a tough choice we've had to make: basically, the API docs kind of assume you're already familiar with Rust and know how to make things work. There's a balance between showing repetitive boilerplate and making it easy for people who are getting started... it's hard.

**Comment by lojic** [comment]
I think you made the right choice. I wouldn't want *every* example cluttered with boilerplate. There may be a way to set proper expectations for newbies, but there is the big "Run" button already, so it's probably fine.
