### ISSUE TITLE
Copy doesn't work for a closure argument

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust#29996]
I would expect this code [1] to work:

    (0..5).flat_map(|i| (0..5).map(|j| i + j)).collect::<Vec<_>>()

since `i` is `Copy`. But `rustc` complains with 
    
    error: `i` does not live long enough

I could use `move`, but in the real code it would take ownership of too much. Shouldn't variables be copied if necessary and what's a succinct workaround?

[1] https://play.rust-lang.org/?gist=3ef7699396e1b712ccd4&version=stable

**Comment by Gankro** [comment]
It sounds like what you're really asking for is 

* more aggressive inference of captures to enable "move" inference
* hybrid by-value/by-ref capturing closures

Note that the second bullet can be hacked as follows:

```rust
let to_cap_by_ref = 0;
let to_cap_by_val = 0;

let explicit_ref = &to_cap_by_ref;
foo.map(move |x| {
    to_cap_by_val + *explicit_ref;
});
```

Instead of closing over some variables by-reference, we're instead capturing references to those variables by-value.

**Comment by yongqli** [comment]
Thanks for the workaround. I was also able to solve my particular problem using `iproduct!` instead of `flat_map`.

**Comment by yongqli** [comment]
It looks like there's some related discussions here: https://internals.rust-lang.org/t/on-the-topic-of-inferring-move-closures/1438

**Comment by Gankro** [comment]
This is definitely a feature request that would need an RFC.
