### ISSUE TITLE
panic!("{}") doesn't error out on compilation

### ISSUE THREAD

**Issue by mkpankov** [rust-lang/rust#30026]
Playground: http://is.gd/jaT7YG

IMO the behavior should be consistent with `println!`.

**Comment by tsion** [comment]
This happens since [`panic!`](http://doc.rust-lang.org/stable/std/macro.panic!.html) special cases the one-argument case to not go through `format_args!`. It would be nice to have the message checked in this case anyway to make sure it doesn't have any un-escaped `{}`s, but it's not clear to me how we should do that.

**Comment by jonas-schievink** [comment]
Duplicate of #22932
