### ISSUE TITLE
rustdoc fails on `ignore`'d code

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#30032]
This doc example:

``````
/// ```ignore
/// let heart = '❤️';
/// ```
``````

compiles and passes with `rustdoc --test`, but not just generating documentation.

**Comment by fhahn** [comment]
I took a look at this and it seems like your char literal contains another (apparently invisible) code point, which means it is no valid Rust code.

 The problem seems to be that rustdoc tries to highlight the code regardless of the ignore annotation, as it only ignores the snippet when running tests. And AFAIK rustdoc uses  `libsyntax`'s parser to do that, which will complain about the additional codepoint.

While the error is confusing (because there is no visible additional code point), I think the behavior of `rustdoc` is OK. Otherwise we would also have to exclude `ingore`d code from the documentation, which means `ignore`d code in docs would be rather pointless.

Finally this code should work with `rustdoc`, because both hearts are single codepoints

    /// ```ignore
    /// let foo = '♥'; // U+2665
    /// let foo = '❤'; // U+2764
    /// ```
    pub fn this_is_a_function() {}

**Comment by steveklabnik** [comment]
> I took a look at this and it seems like your char literal contains another (apparently invisible) code point, which means it is no valid Rust code.

Yes. That's why it's in `ignore`.

**Comment by fhahn** [comment]
I think it would still make sense to have an annotation which excludes the code from the tests but highlights it in the docs, e.g. for nice looking example code, which does not have to include every little detail to make it compile.

If one would like to include code that should not be highlighted and not be used when testing, wouldn't it be possible to just add it as normal text, not in a code block?

**Comment by steveklabnik** [comment]
Triage: looks like https://github.com/rust-lang/rust/pull/33510 didn't happen

**Comment by kadiwa4** [comment]
Triage: rustdoc outputs this:
```
warning: could not parse code block as Rust code
 --> src/lib.rs:1:5
  |
1 |   /// ```ignore
  |  _____^
2 | | /// let heart = '❤️';
3 | | /// ```
  | |_______^
  |
help: `ignore` code blocks require valid Rust code for syntax highlighting; mark blocks that do not contain Rust code as text: ```text
 --> src/lib.rs:1:5
  |
1 | /// ```ignore
  |     ^^^
  = note: error from rustc: character literal may only contain one codepoint
  = note: `#[warn(rustdoc::invalid_rust_codeblocks)]` on by default
```

but in the generated docs, it uses correct syntax highlighting on the broken code.

I think that's pretty optimal. If I understand correctly, this issue was filed because rustdoc used to abort doc-generation on encountering something like this?

**Comment by steveklabnik** [comment]
> this issue was filed because rustdoc used to abort doc-generation on encountering something like this?

I believe so, but to be honest, that diagnostic output looks great to me, so as far as I'm concerned, I don't personally feel this is an issue anymore, so happy to close it :)
