### ISSUE TITLE
println! uses "\n", not platform specific line ending

### ISSUE THREAD

**Issue by jmquigs** [rust-lang/rust#30048]
A literal "\n" is embedded in println

https://github.com/rust-lang/rust/blob/22e31f10c22112b486f4999f90e4ba9c7e23b9b6/src/libstd/macros.rs#L119

I would expect that to use "\r\n" on windows.  Its not a big deal for me since I'm used to dealing with line ending conversions, but I suppose its technically incorrect.

Also, as far as I can tell there is no "newline" constant in the standard library, maybe I just missed it though.

**Comment by alexcrichton** [comment]
This is currently intentional as it provides platform-agnostic output down to the bytes and it can always be opted into on Windows via a `print!` or a custom writer impl. I haven't ever actually seen this cause an issue in practice, and it's relatively backwards-incompatible to change this now (e.g. would require an RFC), so I'm going to close this issue in this repo. If you'd like to pursue this, however, feel free to open an RFC!
