### ISSUE TITLE
Const fn causes ICE in a pattern

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#30117]
## STR

```Rust
#![feature(const_fn)]
const fn four() -> u32 { 4 }
const FOUR: u32 = four();
fn main() { match 4 { FOUR => {}, _ => unreachable!() }}
```

at the current version of `play.rust-lang.org`

## ICE

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'internal error: entered unreachable code', ../src/librustc/middle/const_eval.rs:327

playpen: application terminated with error code 101

**Comment by oli-obk** [comment]
The reason this is happening is because the code thinks `four` is an enum variant or a tuple struct.

The code around this is somewhat redundant and would probably better be solved by making enums variants const evaluable and adding a function that translates `ConstVal`s to [`Constructor`](http://manishearth.github.io/rust-internals-docs/rustc/middle/check_match/enum.Constructor.html)
