### ISSUE TITLE
shouldn't pass -nodefaultlibs by default on OS X

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#30147]
It breaks `no_std` programs that don't explicitly link to libc.  The program may not do so because it genuinely doesn't want to use any libc functionality, but the OS X linker insists on linking libSystem anyway (unless producing a static binary, which [isn't supported](https://developer.apple.com/library/mac/qa/qa1118/_index.html) anyway).

    /tmp % cat test.rs
    #![feature(no_std, lang_items, start)]
    #![no_std]
    #[start]
    pub fn start(_: isize, _: *const *const u8) -> isize { 42 }

    #[lang = "eh_personality"] extern fn eh_personality() {}
    #[lang = "panic_fmt"] fn panic_fmt() -> ! { loop {} }

    /tmp % rustc test.rs
    error: linking with `cc` failed: exit code: 1
    note: "cc" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "test.0.o" "-o" "test" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib/libcore-8cf6ce90.rlib" "-l" "compiler-rt"
    note: ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

    error: aborting due to previous error

**Comment by alexchandel** [comment]
Normally `no_std` programs will import `libSystem` anyway because they need to make system calls, which are unsupported when made directly (though they're fairly stable). But it seems there's a corner case where a program could make no libc *or* system calls and return a value in its exit status, and still need libSystem, since exiting requires a single syscall (although `hlt` or `jmp $0` might do in a pinch).

In the case of a Mountain Lion-style dynamic executable with an `LC_MAIN` Mach-O load command, `dyld` directly jumps to your `main` and spoofs the stack so you return to `_start` in `libdyld`, which is part of libSystem and which calls `exit()`. For an older dynamic executable with `LC_UNIXTHREAD`, `dyld` jumps to your `start` (presumably from a statically linked crt1.o). This is similar to a static `LC_UNIXTHREAD` executable, where the kernel jumps to your `start` (possibly from a statically linked crt0.o), except crt1.o will invoke `exit()` from libSystem, while crt0.o makes the system call itself.

Rust programs have an unarticulated dependency on the entry point, which on OS X can be either crt0.o (which has no dependencies but invokes `exit` and so is unsupported), dyld+crt1.o (which needs libSystem), or dyld+libSystem. Technically dyld by itself is also valid, since dyld doesn't require libSystem to be loaded (except with LC_MAIN), but the necessary exit system call makes this unsupported.

As a workaround, since your emitting a dynamic LC_MAIN executable, you could just `#[link(name = "System")] extern { fn extern dlsym(a: usize, b: usize) -> usize }` or something. Really, we need to handle entry points better, since they cause issues with the MSVC target(s) as well. A `libentry` crate that encoded the various dependencies would be ideal.

**Comment by alexcrichton** [comment]
What linker is in use should in theory just be an implementation detail of the compiler, so just because the default OSX linker requires libSystem to be linked by default doesn't mean that others have the same restriction (such as lld perhaps one day). Along those lines the current interface of the compiler is that the linker brings in no system libraries by default and requires crates to link them in to ensure that it all matches up (allowing usage to build low-level utilities and such).

Along those lines I think it's more useful to have a cross platform linker-independent model (e.g. no libs by default) and then using the standard library brings in all the appropriate libraries for each platform all the time.

**Comment by alexchandel** [comment]
@alexcrichton Consider the entry point/exit point combinations on OS X (where the ellipsis is user code):

* `->LC_UNIXTHREAD->...(start)->...->...(start)->syscall`
* `->dyld->LC_UNIXTHREAD->...(start)->...->...(start)->syscall`
* `->dyld->LC_UNIXTHREAD->...(start)->...->...(start)->libSystem(exit)`
* `->dyld->LC_UNIXTHREAD->crt1.o(start)->...(main)->...->crt1.o(start)->libSystem(exit)`
* `->dyld->LC_MAIN->...(main)->...->libSystem(start)->libSystem(exit)`. (nitpick: start is actually in libdyld here, but that's inside libSystem so it's whatev)

Rust doesn't define its own entry point, limiting it to the last two by default. However, rust users can theoretically provide an entry point, so Rust shouldn't mandate libSystem. *However*, Comex also isn't providing an entry point, meaning he expects Rust's default entry point.

Yet when Rust invokes the linker requesting LC_MAIN (the default unless otherwise specified), it doesn't tell it to link libSystem (or an equivalent exit point for LC_MAIN). The linker should not link any libraries without being told to, so this is on Rust.

I think ideally Rust would provide a `libentry`crate comex could use, even if he is using `no_std`, that encodes our dependency on libSystem as an exit point.
