### ISSUE TITLE
Inline does not work with variable-like functions.

### ISSUE THREAD

**Issue by leeopop** [rust-lang/rust#30282]
Functions are not inlined when the function is retrieved from |x:&str| -> function.

I tried this code:
https://play.rust-lang.org/?gist=9542158dd5ca44fbd2f2&version=nightly
with "release" build option.
LLVM IR shows that the function "teeest" is not inlined.

However, if I directly call the function, 
https://play.rust-lang.org/?gist=6fcc6c3c5eb9c13626f9&version=nightly
the function is inlined and disappeared from the IR.

I also found that the source of this problem is not the lambda function.
Same problem occurs with this variant of code.
https://play.rust-lang.org/?gist=d29a7751182e6742a019&version=nightly

As the variable "func" can be discovered at the compile time,
same inline optimization should work.
(The function definition contains "inline always" attribute.)

## Meta

nightly channel from play.rust-lang.org,
2015-12-09 13:00:00 GMT

Backtrace:

---

Similar optimization problem related with the "dummy move statements"
was reported at #29566.

**Comment by dotdash** [comment]
The function was actually inlined. If you check the IR, you'll see that there's no call to `teeest`, neither a direct, nor an indirect one. 

What's happening is that inside the `black_box` call, you have a closure that captures `func`, so the closure environment holds a reference to the `teeest` function. And by putting that into the `black_box` call, you stop the compiler from removing it. So the function is only kept because its address has been taken. It has been properly inlined and it is never actually called.
