### ISSUE TITLE
Assertion failed: (isa(Val) && "cast() argument of incompatible type!"), function cast

### ISSUE THREAD

**Issue by ababo** [rust-lang/rust#30306]
Failing when compiling for Aarch64 bare metal (with core, no std). It happens when I add comparison of two strings (&'static str):

``` rust
if name == self.component {
    ...
}
```

Fails with:

```
Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/llvm/include/llvm/Support/Casting.h, line 237.
Abort trap: 6
```

rustc 1.7.0-nightly (81ae8be71 2015-12-09)

**Comment by luqmana** [comment]
I've tried reproducing this but haven't been able to. What's the exact target triplet you used and target specification json if you have one.

**Comment by ababo** [comment]
Try this [commit](https://github.com/ababo/arwen/tree/f6af2051553b9bb9cefbabf079c2822e2de77266). Just do `./configure.py --arch=aarch64` and `make`. Then remove `to_bytes()` in src/kernel/arch-aarch64/device_tree.rs:197 in both sides of comparison and try to `make` again.

**Comment by Mark-Simulacrum** [comment]
I can't run the configure.py as suggested above (`error: didn't find 'aarch64-elf-objcopy' program`) and my attempts to get this program weren't very fruitful, so closing--this bug is also 2 years old. Please reopen if you're still running into this problem today, and ideally with a smaller example.
