### ISSUE TITLE
"raw pointers cannot be cast to integers in statics" justification is incorrect

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#30705]
```rust
pub static mut X: usize = unsafe { &X as *const _ as usize };
```

```
The value of static and const variables must be known at compile time. You
can't cast a pointer as an integer because we can't know what value the
address will take.
```

This is incorrect as the following code shows:

```rust
pub static mut X: *const u8 = unsafe { &X as *const _ as *const _ };
```

The value of `X` is only known at link time.

**Comment by mahkoh** [comment]
If this were true then statics could not take references to each other. Hence casting pointers to integers should be allowed in statics.

**Comment by arielb1** [comment]
@mahkoh 

First, the extended diagnostic errors are not written by the core Rust team, so inaccuracies are to be expected (we would still like to fix them to some degree).

Of course, the real reason is that we want the values of statics to be known at compile-time, either as an integer or as a known offset from a symbol, and that if you could cast pointers to integers, you could do arithmetic on these integers and end up with values that are neither.

It certainly would have been possible to prohibit the arithmetic instead of the round-tripping, but at the time it seemed to me that it would be just an insufficiently useful overcomplication.

If you have a sensible use-case for a more lenient model, we would like to know about it. Maybe I should rather attach this post to the error message?

**Comment by mahkoh** [comment]
@arielb1 

>you could do arithmetic on these integers

Of course this cannot work.

>If you have a sensible use-case for a more lenient model, we would like to know about it.

I have a single use case namely

```rust
pub static SELF_PTR: usize = &X as *const _ as usize;

let real_to_virt = SELF_PTR - (&SELF_PTR as *const _ as usize);
```

to calculate the difference between the current program counter and the position the linker assumed the program counter to be. This can then be used to create the page tables with the correct virtual to physical address mapping. The advantage of usize is that the static doesn't have to be mut because usize is Sync.

It's not that big of an issue.

**Comment by arielb1** [comment]
Making it work would require some significant modification to the `const_eval` code, but it is going to be refactored soon anyway.

Can't you wrap your pointer with an `SyncRawPtr` wrapper struct (e.g. current libcore's `Unique`)?

**Comment by mahkoh** [comment]
lrs has deprecated Unique in favor of

* NoAliasMemPtr,
* NoAliasMutObjPtr,
* NoAliasObjPtr,
* AliasMemPtr,
* AliasMutObjPtr, and
* AliasObjPtr.

And none of these implement Sync.

In any case, since this pointer is only used once to calculate real_to_virt, I don't think using a wrapper is worth. This is not a big issue and it's certainly not necessary to do any modifications to fix this use case.

**Comment by GuillaumeGomez** [comment]
If you're speaking of E0018, my bad, I'm the one who wrote it. How would you improve the error explanation?

**Comment by zeonin** [comment]
@arielb1 

> If you have a sensible use-case for a more lenient model, we would like to know about it.

Personally, I'd find it very useful for things like descriptor handling in OS dev.

What I would like to be able to do is something like this:

```rust
type InterruptHandler = fn();

#[repr(C, packed)]
struct Descriptor {
    base_low: u16,
    selector: u16,
    flags: u16,
    base_high:u16,

impl Descriptor
    const fn new(handler: &InterruptHandler, selector: u16, flags: u16) -> Descriptor {
        Descriptor {
            base_low: handler as usize & 0xFFFF as u16,
            selector: selector,
            flags: flags,
            base_high: (handler as usize >> 16) & 0xFFFF as u16,
        }
    }
}
```

The architecture defines the format of a `Descriptor`, but it has to refer to a valid interrupt handler. Being able to fully generate the table at compile time in rust would be more convenient than doing so in assembly, and it would be nice to not have to set these structures at runtime.

**Comment by djmcgill** [comment]
I've just been bitten by this as well, so I'm cheating by having my vector table contain `&'static u8` instead of the (more correct) `usize`. Because of this my `_stack_top` extern has to be defined as: `extern pub static __stack: u8;` which makes my code less safe, as I'd ideally like to define the linker variable as having unit type so that it (effectively) can't be written to.

**Comment by mjbshaw** [comment]
Just in case people find this issue via Google or something and aren't sure how to do this, [this is now supported on stable Rust using a union to perform a transmute](https://rust.godbolt.org/z/F84cyO):

```rust
pub union TransmuteHack<T: Copy, U: Copy> {
    from: T,
    to: U,
}

pub static SOME_STATIC_VAR: [u8; 14] = *b"Hello, world!\0";

pub static ADDRESS_OF_STATIC_AS_USIZE: usize = unsafe {
    TransmuteHack { from: &SOME_STATIC_VAR }.to
};
```
