### ISSUE TITLE
HIR lowering relies on AST node IDs

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#30809]
cc @nrc
cc @eddyb

So I was looking at how desugarings work in HIR lowering. Notably, lang items are collected after lowering but it is sometimes desirable to refer to them. @eddyb suggested a side table mapping HIR node IDs to prospective lang items, which would be cross-referenced with the real lang items once they are collected. But this relies on IDs being known during lowering. Currently they are, because they are [copied from the AST IDs](https://github.com/rust-lang/rust/blob/master/src/librustc_front/lowering.rs#L964), but @eddyb was saying that the AST shouldn't have IDs at all. Currently it is needed because lowering [needs to be reproducible](https://github.com/rust-lang/rust/blob/master/src/librustc_front/lowering.rs#L27-L34), but... why? Are these IDs going away, or are they here to stay and usable for this lang item scheme?

**Comment by durka** [comment]
cc #20541

**Comment by nrc** [comment]
I think the ids issue and the lang items issue are orthogonal. We should definitely find a way to use lang items for the HIR lowering.

I would like to remove node ids from the AST and just use them in the HIR. The current situation is mostly because it was easier to implement. Reproducible lowering may be unnecessary. However, ids do make it easy to identify an AST node, we'd want to be sure that we don't this (and that it is not useful for tools or syntax extensions). So lets not just rip them out and see what happens.

**Comment by eddyb** [comment]
@nrc currently we can identify AST nodes by referential equality (i.e. pointers).
Even if we ditch the allocation-heavy trees, we could still have various ways of doing it (think "pre-order iteration index").

**Comment by durka** [comment]
Is this still true?

**Comment by Mark-Simulacrum** [comment]
@eddyb @nrc As @durka asks, do you know if this is still the case?

**Comment by eddyb** [comment]
The "reproductible" lowering is gone but they IDs are still very much reused.
@michaelwoerister did start some work to have different HIR IDs for incremental.

**Comment by oli-obk** [comment]
Now that we use HirIds uniformly, this is fixed, right?

**Comment by bjorn3** [comment]
Can this be closed?
