### ISSUE TITLE
Use Word2Vec when Levenshtein distance fails

### ISSUE THREAD

**Issue by ticki** [rust-lang/rust#30846]
This will improve quality of the typo suggestions.

**Comment by petrochenkov** [comment]
Good word2vec models are pretty large, you'll have to prune them mercilessly unless you want to add a couple hundreds of MBs to the Rust distribution :D
If you somehow have a distribution of words used as (Rust) identifiers (by mining github, for example) you can select top 100 (1000, 10000) and use only them or perhaps hashes can be used instead of whole words, but I'm still not sure if models of acceptable size (<1MB?) will provide enough coverage.

Someone should certainly try to experiment with this!

**Comment by Ticki** [comment]
In my experience, small data sets can create decent word2vec models too, so I don't think a tool big data set would be necessary.

**Comment by petrochenkov** [comment]
I'll close this since it's not something that should be tracked by an issue.
Using word2vec for this task is untypical, but if some proof-of-concept implementation appears, then it could be discussed.
