### ISSUE TITLE
Tracking issue for RangeBounds

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#30877]
This issue tracks the `collections_range` feature which applies to `std::collections::range::RangeArgument`. It used to be lumped in with `drain` (#27711) but that was stabilized while `RangeArgument` may continue to be affected by experiments with inclusive ranges, so here we are.

**Comment by durka** [comment]
I'm currently working on inclusive ranges, which is why I noticed this. A PR to change the issue link is incoming.

**Comment by withoutboats** [comment]
This trait is not actually being exported by `std` right now, meaning this feature can't be used without importing libcollections. I would submit a PR, but I'm not sure if a new range module in `std::collections` is the right place to mount it, or if it belongs under a different path.

**Comment by sfackler** [comment]
The libs team discussed this, and are placing `RangeArgument` into a final comment period to **stabilize**. We will need to tweak the API to support inclusive and exclusive bounds on each side to look something like:

```rust
pub enum Bound<T> {
    Unbound,
    Inclusive(T),
    Exclusive(T),
}

pub trait RangeArgument<T> {
    fn lower(&self) -> Bound<&T>;

    fn upper(&self) -> Bound<&T>;
}
```

**Comment by Stebalien** [comment]
@sfackler shouldn't the new API go though another stabilization period? Also, a way to extract the bounds by-value would be nice (but probably not necessary).

**Comment by sfackler** [comment]
Probably at this point yeah, particularly since we still haven't actually made the change.

**Comment by alexcrichton** [comment]
The libs team discussed this at triage the other day and the conclusion was to punt on stabilization/deprecation because we didn't have time to implement the changes here

**Comment by clarcharr** [comment]
Question: is there a reason why this trait is in `collections` but not `core`?

**Comment by sfackler** [comment]
I don't think there's a good reason for it to not be in core off the top of my head - it should probably move!

**Comment by J-F-Liu** [comment]
Should also impl RangeArgument for usize.
```rust
impl RangeArgument<usize> for usize {
	fn start(&self) -> Bound<usize> { Included(self) }
	fn end(&self) -> Bound<usize> { Included(self) }
}
```

**Comment by SimonSapin** [comment]
@J-F-Liu There’s also a `std::slice::SliceIndex` trait that is implemented for both `usize` and various range types.

**Comment by J-F-Liu** [comment]
@SimonSapin thanks for let me know this, it indicates should impl RangeArgument for usize as well.
SliceIndex is much more complex than RangeArgument, and its name is not obvious for range purpose.

**Comment by clarcharr** [comment]
Would people be willing to accept a PR for moving this to core? Everything would have the same features, and `collections` would re-export them for compatibility.

Only problem I see is that `Bound` is already stabilised but I'm not too worried about that.

**Comment by sfackler** [comment]
Makes sense to move to me!

**Comment by Gankro** [comment]
Can I nominate this for FCP? Seems like it does what it needs to do; fully general.

**Comment by glaebhoerl** [comment]
I've had various ideas w.r.t. the design which I posted and each time the discussion got moved somewhere else, I can't remember what they were and I'm too lazy to look them up, but at least let's call it something like `IsRange` instead of `RangeArgument` because there's nothing limiting it to being used in argument position.

**Comment by sfackler** [comment]
Seems reasonable to FCP for stabilization. I'd be fine renaming as part of that!

@rfcbot fcp merge

**Comment by glaebhoerl** [comment]
I guess one relevant question is, might we want `&mut self -> Bound<&mut T>` methods as well? Even if no need for them has come up so far, adding methods to a trait isn't backwards compatible. Or would those belong in a separate `Mut` trait anyways? (It'd be easy to automatically say "yes" on the basis of widespread precedent in `std`, like `DerefMut` and `IndexMut` and so on, but it's not obvious to me that the character of this trait is the same as that of those -- maybe this one is saying the type *is* a range, while those merely say the type *supports* some operation, and maybe that makes a difference?)

What other types could people *conceivably* want to implement this for, besides the built-in `Range`s in `std`?

**Comment by Gankro** [comment]
I think the trait should really be anchored in the consumers of this trait. In this case everyone who needs a RangeArgument only needs read-only access.

Mutating the bounds of a range seems like a very strange thing, but in the case that you wanted that you *probably* also want to go from `Bound(X)` to `Unbound` or vice-versa. But that can't be supported in general without changing types (`..` is completely immutable).

**Comment by dtolnay** [comment]
@rfcbot reviewed

**Comment by clarcharr** [comment]
I also think that we should rename the trait, and move it to `core` as well. I will rework my PR for moving it soon.

Perhaps `RangeBounds`?

**Comment by aturon** [comment]
I'm on board with this API in general, but agree with @clarcharr that there's a bit of bikeshedding to be done before final stabilization. `RangeBounds` seems pretty good to me!

**Comment by Stebalien** [comment]
Lest we miss a shade:

* `RangeBounds` (ties it in with the range family)
* `Bounds` (shorter)
* `InRange` (I'd expect an `InRange::in_range` method if we called it this)
* `RangeArgument` (current)
* `Span` (could be confusing for new rustc contributors)
* `Interval` (a synonym of range)

(pedantic nit: the unbounded variant (as currently defined) is `Bound::Unbounded` not `Bound::Unbound`.)

**Comment by clarcharr** [comment]
The main reason I chose `RangeBounds` over `Bounds` was that having `Bound` be an enum and `Bounds` be a trait could be confusing.

If we had more hindsight I'd say that `Range` would be the trait and `RangeExclusive` would be the current `Range`, but that's not an option at the moment.

**Comment by scottmcm** [comment]
Meta: I'm confused exactly what's in FCP here.  I see "stabilization", but also "move to core" and "bikeshedding to be done".

Regarding the trait: should it be the home of things like the `Range*::contains` methods ([`range_contains` feature](https://github.com/rust-lang/rust/issues/32311))?  And have an `is_empty` method (like came up in https://github.com/rust-lang/rfcs/pull/1980#issuecomment-301582290)?  Having those on the trait would be more consistent and make pair-of-`Bound` less of a second-class citizen.

If the trait required `T: PartialOrd` those would both be implementable with the existing `start()` and `end()` methods.  And I'm not sure how anyone could meaningfully consume a `RangeArgument` without it -- the rust repro seems not to, only using `RangeArgument<usize>` for random-access or `RangeArgument<K: Ord>` in btree.  But the library does seem averse to constraining types, and `Bound` is unconstrained...

**Comment by Gankro** [comment]
Naming and placement are often decisions made in the final stabilization process, since they're just stylistic and don't affect how the feature actually works.

Making the trait require PartialOrd is a lot more of a change though. I don't think it's necessary. Anything like is_empty/contains could be added with a `where T: PartialOrd` constraint.

**Comment by clarcharr** [comment]
Actual question: is there ever a conceptual reason to have a range of something that doesn't implement `PartialOrd`? I can't think of any.

**Comment by Gankro** [comment]
We generally support lots of things that don't really make sense in practice because someone might have a usecase we couldn't foretell. For instance you can make a Mutex that can't be shared between threads.

**Comment by scottmcm** [comment]
The nicest thing about having the bound would be that it allows adding methods to the trait later with default implementations -- like `clamp` (https://github.com/rust-lang/rfcs/pull/1961), for example.

**Comment by aturon** [comment]
> We generally support lots of things that don't really make sense in practice because someone might have a usecase we couldn't foretell. For instance you can make a Mutex that can't be shared between threads.

Just to elaborate on this: you can use this technique to e.g. make a data structure that is thread safe *if* you put sendable data in it, but also fine to use in a single-threaded context if not. I'm not sure that analogous reasoning applies here, but we've generally taken the approach of constraining as little as possible. (That does produce worse error messages in some cases, since you can construct nonsensical things then get errors when you try to use them).

This calculus may also change if we introduce [implied bounds](http://smallcultfollowing.com/babysteps/blog/2014/07/06/implied-bounds/).

**Comment by withoutboats** [comment]
> We generally support lots of things that don't really make sense in practice because someone might have a usecase we couldn't foretell. For instance you can make a Mutex that can't be shared between threads.

This is worth considering a bit more, especially in light of implied bounds (which makes providing bounds on structs much more useful).

While not Mutex, I literally had a use case for this property of Arc yesterday. I had a type which couldn't be `Send`, but I needed to share it across threads in a wrapper *which only exposed an API that I know is thread safe*. I was able to do this with a wrapper around `Arc` with an unsafe impl of `Send` for that type. I think in general, Send bounds (because its just a marker trait) should not be on the construction of these types.

On the other extreme, I can't think of much you could do with a HashMap with a non-Hash key; the map would *always* be empty. There's no wrapper you can put around it to change that behavior.

This is somewhere in between. On the one hand, partialord does provide behavior (unlike Send), but on the other hand the fields are public (unlike a HashMap), so you can use them even if they don't implement the behavior the methods rely on.

**Comment by Gankro** [comment]
Are implied bounds expected to be proposed For Real any time soon? If not I'd rather not make library design decisions based around its hypothetical inclusion. (and even if so, I expect it wouldn't land within the year given past experience)

I've seen libs design get burned too many times in anticipation of language features that never come.

**Comment by aturon** [comment]
Yes, implied bounds are expected as part of the ergonomics initiative this year.

**Comment by johncf** [comment]
This is a bit out of place, but why do we have so many `Range*` types in the first place? Why don't we simply have a single type like `Interval<T>(Bound<T>, Bound<T>)` and be done with it? There wouldn't be any need to abstract over these types then, since all that this abstraction does is provide an interface to query for `start` and `end` of a range.

Is there any practical difference in performance in doing it [the way](https://github.com/rust-lang/rust/blob/272e77f/src/libcollections/vec.rs#L1566-L1619) [it currently is](https://github.com/rust-lang/rust/blob/00c87a6/src/libcore/slice/mod.rs#L733-L1061), instead of having 9-arm match blocks?

**Comment by Gankro** [comment]
At best it's simply too late to make that kind of change. Bound came later, after Range had already stabilized.

**Comment by Stebalien** [comment]
@Gankro I brought this up pre-1.0 so stabilization wasn't really relevant. It was more a matter of a lack of interest. IIRC, code churn also came up as a concern but I can't find that discussion.

https://github.com/rust-lang/rfcs/pull/952

**Comment by johncf** [comment]
One plausible alternative I could think of, assuming that there is still interest in unifying range types, is to replace `R: RangeArgument<T>` with `R: Into<Interval<T>>`, and then deprecate _explicit mention_ of `Range*` types for a _long_ time. This means that the range syntax would still produce `Range*` typed values, but the consumer should be encouraged to use `R: Into<Interval<T>>` bound instead of `Range*` types. (_Alternative:_ Range syntax could produce `Range*` or `Interval<T>` based on the inferred type, so that use of `Interval<T>` can be suggested instead of the bound `R: Into<Interval<T>>`.)

@Stebalien I wonder why compiler optimizations were not mentioned in those earlier discussions. Avoiding runtime costs due to longer match blocks seems to be a simple enough optimization that any backend that Rust might use in future is highly likely to do it.

**Comment by Stebalien** [comment]
@johncf those kind of optimizations generally rely on a lot of inlining (which is why the discussion moved to traits/generics instead of a single type). Regardless, what's done is done; I just wanted to point out that this *was* discussed prior to stabilizing `Range`.

**Comment by Gankro** [comment]
Yeah sorry if I messed up the sequence of history there -- I mostly just remember that Bound was historically considered "just a hack" until we figured out how to do ranges properly.

The main point stands: it's too late. Range exists, and so a trait that can yield a pair of Bounds seems like the right solution. I'm very biased against `Into` and friends, so I favour the dedicated trait. Dedicated trait would be relying slightly less on optimizations to wipe everything away (mostly relevant to debug builds), but mostly it should optimize just as well as `Into` so it probably doesn't matter.

**Comment by SimonSapin** [comment]
> Actual question: is there ever a conceptual reason to have a range of something that doesn't implement PartialOrd? I can't think of any.

https://docs.rs/url/1.4.1/url/enum.Position.html is a enum with unit variants used in ranges for slicing: `&url[..Position::BeforeFragment]`. Using `RangeArgument` would allow replacing three similar `impl`s with one.  Although the enum could implement `PartialOrd` (there is an ordering that makes sense) it hadn’t occurred to me before to do it, and nobody asked so far.

**Comment by Gankro** [comment]
I would also note that requiring *Partial*Ord is unlikely to be that useful in practice. Most public apis would either use a specific type (usize) or require Ord or some other trait like num::Float.

**Comment by clarcharr** [comment]
Something to note from the discussion in #42268:

I'd very much like to move `RangeArgument` to core, but there's not a good way to do so without either:

1. Moving `collections::Bound` to `core::ops`, duplicating it in `std::collections::Bound` and `std::ops::Bound`.
2. Moving `collections::Bound` to `core::ops`, including it in `collections::Bound`, and explicitly excluding it from `std::ops`.
3. Creating `core::collections` as a module which only contains `Bound`, move `RangeArgument` to `core::ops`.
4. Create `core::collections` which includes `Bound` and `RangeArgument`.

I don't really like any of these options at all. I wanted to do 3 but @alexcrichton made a good point that creating `core::collections` for a single enum is kind of excessive. This doesn't necessarily block stabilisation but I'd like to see what everyone else thinks about these options and which is best. It seems very obvious to me that `RangeArgument` should go in `core::ops` though alongside the other `Range` types.

**Comment by Gankro** [comment]
I'd move Bound to ops and deprecate the Collection re-export

**Comment by sfackler** [comment]
I seem to recall reexport deprecations being a bit iffy, but I'm on board with moving to ops regardless.

**Comment by glaebhoerl** [comment]
We said we were going to rename it?

**Comment by sfackler** [comment]
Was there any kind of consensus on what the new name would be? It seems like there were a few ideas tossed around (`Bounds`, `Interval`, `Span`) but nothing was a particular winner.

**Comment by clarcharr** [comment]
I personally think that `RangeBounds` is better but if we're stuck with `RangeArgument` it's not terrible.

**Comment by glaebhoerl** [comment]
There wasn't an affirmative decision *not* to rename it either, though. I'm just annoyed because this is like the fourth consecutive thread where I've requested "please let's give it a better name" and each time it ends up getting passed over.

**Comment by scottmcm** [comment]
Inspired by @johncf's post above, is `RangeArgument` just a version of the "`Into` [trick](http://www.suspectsemantics.com/blog/2016/11/29/the-into-trick/)"?  Should it just be spelled `Into<(Bound<T>, Bound<T>)>`?

**Comment by sfackler** [comment]
If people want a better name then they should figure out what that better name is. It's not magically going to arrive from on high.

`Into` is an interesting approach - i'm a bit hesitant to just use a 2-tuple though.

**Comment by clarcharr** [comment]
`Into<RangeBounds>` with `struct RangeBounds<T> { start: Bound<T>, end: Bound<T> }` does seem to make a lot of sense

**Comment by sfackler** [comment]
@rust-lang/libs should we revert the stabilization of `RangeArgument`?

**Comment by sfackler** [comment]
Oh - the `Into<Foo>` approach will have troubles with non-copy bounds. `RangeArgument` gets around that by returning `Bound<&T>` which isn't possible with an `Into`-based solution I believe.

**Comment by clarcharr** [comment]
But cloning isn't necessary if you're moving the values directly. And if you couldn't move the values, why not just create a range of references instead?

**Comment by glaebhoerl** [comment]
(I think `RangeBounds` is fine fwiw. I can't really evaluate the appropriateness of the `Into`-based formulations so I'll defer to others on that.)

**Comment by sfackler** [comment]
#42991

**Comment by clarcharr** [comment]
Could you reopen this issue as well @sfackler?

**Comment by aturon** [comment]
I continue to think `RangeBounds` is good, and from a quick re-read of the thread, it seems like most people are at least fine with it (and no other name seems to be getting traction).

@clarcharr @glaebhoerl, either of you want to make a PR renaming and stabilizing?

**Comment by clarcharr** [comment]
@aturon I'll try and get something out today

**Comment by dtolnay** [comment]
There is a PR to stabilize this in #44564 but from the discussion here it doesn't look like we are ready for that yet.

@rfcbot fcp cancel

Here is a summary of what has happened since the FCP:

- Naming? "RangeBounds" seems to be preferred over "RangeArgument" because nothing limits it to being used in argument position.

- Do we want a constraint of T: PartialOrd on the type parameter of RangeArgument? With implied bounds, such bounds are now more useful than they have been in the past. Answer: no.

- Do we need methods like `contains` and `is_empty` on the RangeArgument trait? Answer: no.

- #42268 tried to move alloc::Bound to core::collections::Bound but it didn't work out.

- #42745 moved alloc::Bound to core::ops::Bound and alloc::range::RangeArgument to core::ops::RangeArgument, deprecated std::collections::range in favor of std::ops and alloc::range in favor of core::ops. Also stabilized it all. Reverted in #42991 because it was not ready to stabilize, but with a promise to move things back to core in a subsequent PR.

- #43033 tried to replace alloc::range::RangeArgument trait with a core::ops::RangeBounds struct holding a pair of Bound\<T> with some From impls. Moved alloc::Bound to core::ops::Bound. Deprecated std::collections::range in favor of std::ops and alloc::range in favor of core::ops. PR was one rebase away from being merged but went inactive.

- #44518 is a rebase of the previous. There appears to be a roadblock with borrowed ranges.

**Comment by mbrubeck** [comment]
This Reddit thread points out some limitations/inconsistencies related to borrowed bounds:

https://www.reddit.com/r/rust/comments/7tt70u/btreemapbtreeset_range_api_reduces_elements/

In particular, it's currently impossible to call `range` on a `BTreeSet<&T>` using a `Range<&T>` with a different lifetime.  You have to convert the `Range<&T>` to a `(Bound<&T>, Bound<&T>)`, and then add type annotations to the `range` call.

**Comment by ltratt** [comment]
At the risk of sounding like I'm throwing a tantrum and promising to do no work in return, the lack of stabilisation of this feature seems more confusing than other non-yet-stabilised things I've encountered. That's because its most well known use is in a stable API -- `drain` -- which users reasonably expect to see replicated elsewhere.

However, `drain` is cheating: even though it's marked as stable, it exposes a public type which is unstable. So, for example, in `Vob` https://crates.io/crates/vob I want to add `drain`-like functions, but doing so means I have to make the library nightly only. I have ended up wondering if it would have been better if `drain` didn't use `RangeArgument`, and provided a clunkier API to users, because at least then they wouldn't know that they could be using nice syntax and complaining to me when I can't provide it to them in a library ;)

**Comment by mbrubeck** [comment]
> So, for example, in `Vob` https://crates.io/crates/vob I want to add `drain`-like functions, but doing so means I have to make the library nightly only.

On stable Rust today, you can also write your own `RangeArgument` trait and impls (or even copy the one in libstd into your own code) and use it in your API.

**Comment by ltratt** [comment]
> On stable Rust today, you can also write your own RangeArgument trait and impls (or even copy the one in libstd into your own code) and use it in your API.

Yes, good point -- I hadn't considered that. I'm going to do it even though it feels pretty icky. Despite my griping, thanks for the pointer!

**Comment by Gankro** [comment]
In case anyone else has a collection they want RangeArgument for: https://github.com/Gankro/thin-vec/blob/master/src/range.rs

This is an especially clean case of the unstable trait in public API pattern, as there's very little incentive to implement these traits outside of the like 4-5 std types which do.

**Comment by SimonSapin** [comment]
PR #49163: Rename RangeArgument to RangeBounds, move it and Bound to libcore

**Comment by SimonSapin** [comment]
Assuming this PR is accepted, the only issue in this thread that I feel might not be resolved is the possibility of replacing this trait with a type to be used with `Into<_>`.

@sfackler wrote “the `Into<Foo>` approach will have troubles with non-copy bounds” but I don’t quite understand what this troubles are. `Into::into` takes/moves its `self` argument. Either way, I think that a dedicated trait is fine.

@rust-lang/libs what do you think? If we decide to keep the dedicated trait, should we do another round of FCP or are we good to stabilize? (Again assuming the PR linked above.)

**Comment by SimonSapin** [comment]
The libs team discussed this and consensus was to **stabilize** after renaming the methods to `start_bound` and `end_bound` to avoid name collision with new inherent `start` and `end` methods of `RangeInclusive`.

@rfcbot fcp merge

Affected APIs are:

```rust
pub trait RangeBounds<T: ?Sized> {
    fn start_bound(&self) -> Bound<&T>;
    fn end_bound(&self) -> Bound<&T>;
}

impl<T: ?Sized> RangeBounds<T> for RangeFull {…}
impl<T> RangeBounds<T> for RangeFrom<T> {…}
impl<T> RangeBounds<T> for RangeTo<T> {…}
impl<T> RangeBounds<T> for Range<T> {…}
impl<T> RangeBounds<T> for RangeInclusive<T> {…}
impl<T> RangeBounds<T> for RangeToInclusive<T> {…}
impl<T> RangeBounds<T> for (Bound<T>, Bound<T>) {…}
impl<'a, T: ?Sized + 'a> RangeBounds<T> for (Bound<&'a T>, Bound<&'a T>) {…}
impl<'a, T> RangeBounds<T> for RangeFrom<&'a T> {…}
impl<'a, T> RangeBounds<T> for RangeTo<&'a T> {…}
impl<'a, T> RangeBounds<T> for Range<&'a T> {…}
impl<'a, T> RangeBounds<T> for RangeInclusive<&'a T> {…}
impl<'a, T> RangeBounds<T> for RangeToInclusive<&'a T> {…}
```

**Comment by scottmcm** [comment]
Since the bikeshed was opened: why not `lower_bound` and `upper_bound` if they're going to include the word "bound"?

**Comment by SimonSapin** [comment]
This change is motivated by avoiding collision with the exact `start` and `end` method names of `RangeInclusive` https://github.com/rust-lang/rust/issues/49022, but they’re still strongly related to those as well as the start and end fields of other range types. I think the names should reflect that relation in some way.

**Comment by DDOtten** [comment]
I think a method like `fn into_bounds(self) -> (Bound<T>, Bound<T>)` would be very helpful. Currently `RangeInclusive` implements `into_inner` but other range types do not. (It also is the only range type to implement `new`, `start` and `end` and the only one to where the inner types are not public)

This would give a way to get the inner values without having to use `clone`. I am currently implementing a tree/prefix tree and want to add a `range` function similar to a `BTreeMap`. This function takes something like a `RangeBounds<I>` where `I: IntoIterator<T>`. I would like to avoid an extra `Clone` bound for `I` and cloning these types is less efficient.
