### ISSUE TITLE
type inference quirk with PartialEq

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#30960]
Some operations of the form `x == y.into()` seem to hit a hole in type inference and trait resolution, but can be fixed by swapping the operands (seems like it should be symmetric). [Playpen](http://is.gd/BZJJyV).

Here is the main surprising (to me) part:

```rust
struct A;
#[derive(PartialEq)] struct B;
impl From<A> for B { fn from(_: A) -> B { B } } // trivial conversion

B == A.into(); // ok
A.into() == B; //~ ERROR unable to infer
```

**Comment by jonas-schievink** [comment]
The last line should be more or less equivalent to `A.into().partial_eq(B)`

**Comment by durka** [comment]
Hmm so if someone else implements `struct C; impl From<A> for C { ... } impl PartialEq<B> for C { ... }` then the meaning could change. But that is also possible for the case of `B.partial_eq(A.into())`...

**Comment by jonas-schievink** [comment]
But there's only one impl of PartialEq for B (the derived one), so we already know the type of the second argument. Or at least that's what I think is happening. Who really knows what the type system is up to these days? ;)

**Comment by durka** [comment]
There's only one impl of `PartialEq<Self>` but there could be another impl for `PartialEq<Other>`.

**Comment by jonas-schievink** [comment]
From my limited understanding, what's happening is that `B.partial_eq(A.into())` generates two obligations, `B: PartialEq<$T>` and `A: Into<$T>`. The first one is resolved immediately, because there's just a single impl of `PartialEq` for the type `B` (the derived one). This unifies the type variable `$T` with `B`, since the applied impl is `impl PartialEq<B> for B`. Our second obligation then becomes `A: Into<B>`, which isn't resolved by a "direct" impl, but by selecting the blanket impl `impl<T: From<U>, U> Into<T> for U`. This enqueues the obligation `B: From<A>`, which *can* be directly resolved, and we're done.

In the other case, we have `A.into().partial_eq(B)`, we still have the obligation `A: Into<$T>`, but the other obligation becomes `$T: PartialEq<B>`. We can't do anything with the second obligation because of the type variable, so the first obligation isn't simplified to `A: Into<B>`. But, when we only have `A: Into<$T>`, when we try to use the `From` blanket impl, we'd get `$T: From<A>`. Now we end up with 2 obligations on a type variable and have to give up!

(wow that actually made sense! You might still want to verify my ramblings with someone who actually knows the type system. I'm also pretty sure this issue is already well known by these guys!)

**Comment by jonas-schievink** [comment]
As an additional data point, consider this:
```rust
struct A;
#[derive(PartialEq)] struct B;
impl PartialEq<()> for B {
    fn eq(&self, _:&()) -> bool { false }
}
impl From<A> for B { fn from(_: A) -> B { B } } // trivial conversion

fn main() {
    B == A.into();
}
```

This worked in your example with just one impl, but now fails with the following error, since there are now multiple impls of `PartialEq` that could apply when the type parameter is a type variable:
```
<anon>:9:5: 9:18 error: type annotations required: cannot resolve `B : core::cmp::PartialEq<_>` [E0283]
<anon>:9     B == A.into();
             ^~~~~~~~~~~~~
```

**Comment by arielb1** [comment]
@jonas-schievink 

That is correct. Closing the isuse.
