### ISSUE TITLE
Regression in `BTreeMap` iterator variance

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#30979]
#30426 caused `btree_map::{IntoIter, Iter, Range}` to become invariant in `K` and `V`. They were previously covariant.

CC #30642 @Gankro @gereeter

**Comment by Gankro** [comment]
Oops! I could've sworn we checked up on variance, but I guess these slipped through.

**Comment by gereeter** [comment]
I checked for variance on `BTreeMap` itself, but forgot about the iterators.

**Comment by gereeter** [comment]
This is actually annoyingly tricky, because the invariance comes from `NodeRef`, which is generic in mutability - `NodeRef<Mut, K, V, Type>` should be invariant in `K` and `V`, but I don't think that it is possibly to have the variance of one type parameter depend on another.

Probably the best option is to make `NodeRef` universally covariant, just adding invariance markers to `RangeMut` and `IterMut`.
