### ISSUE TITLE
[MIR] Should translator use LLVM builder more directly?

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#31003]
Currently we use various `build::*` functions in order to build up the function, but many of the checks done by the `build::*` functions are not necessary for us.

Namely, those functions are concerned with checking for termination and unreachability. Both of these concerns are not relevant to MIR – we have well specified terminator system and unreachable blocks are removed before MIR gets to the trans.

Suggestion is to refactor the MIR translator to use the `trans::builder::Builder` directly.

**Comment by Thiez** [comment]
Would this change result in noticeable performance gains when compiling without optimizations?

**Comment by dotdash** [comment]
I'd not expect that. It would just avoid some unnecessary, but probably
very cheap, checks during trans, and stop "repositioning" the builder at
its current position over and over again. Probably a tiny gain in the trans
phase, but nothing spectacular. I'd support the change nevertheless,
because it feels cleaner.

2016-01-20 19:27 GMT+01:00 Thiez <notifications@github.com>:

**Comment by pczarn** [comment]
I'd like to start this tomorrow.
