### ISSUE TITLE
DragonflyBSD build is broken

### ISSUE THREAD

**Issue by dhuseby** [rust-lang/rust#31009]
```
../src/libstd/sys/unix/fs.rs:202:9: 202:28 error: mismatched types:
 expected `u64`,
    found `u32`
(expected u64,
    found u32) [E0308]
../src/libstd/sys/unix/fs.rs:202         self.entry.d_fileno
                                         ^~~~~~~~~~~~~~~~~~~
```

**Comment by tbu-** [comment]
This looks fixed: https://github.com/rust-lang/rust/blob/b5de94fba9a137a1128448f4b703250e7e8ff975/src/libstd/sys/unix/fs.rs#L322-L329. Also, a recent commit claimed to fix the DragonflyBSD build: https://github.com/rust-lang/rust/commit/60c988ec176b9653bc1c3a6d6a738646d15a5ad6, so I guess this issue is fixed as well.
