### ISSUE TITLE
rc::Weak doesn't provide Hash, Eq, PartialOrd

### ISSUE THREAD

**Issue by shahn** [rust-lang/rust#31066]
Looks like these were left out due to an oversight, not actually on purpose.

**Comment by bluss** [comment]
I don't see a way to define these traits, there is no way to handle the case where the Weak is a dud.

Stale pointers could hash and compare differently, but that would mean that a HashMap key can change its hash value while it's in the map (which is not unsound, but it's a logical error in the program).

**Comment by Gankro** [comment]
Well, you can always panic. That's just... not great. Especially if they become dangling after being inserted into a hashmap. Alternatively, you could Hash/Eq/Ord on the address of the Weak, but that would be super confusing since Rc doesn't do that.

These traits were indeed left unimplemented on purpose.
