### ISSUE TITLE
CSS for primitive docs on doc.rust-lang.org/core are broken

### ISSUE THREAD

**Issue by notriddle** [rust-lang/rust#31125]
Open this: <http://doc.rust-lang.org/core/primitive.i16.html>

**Comment by notriddle** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1593513/12520323/1f092e32-c101-11e5-8484-51febbc7705f.png)

**Comment by steveklabnik** [comment]
Looks fine here
![2016-01-22-142323_924x719_scrot](https://cloud.githubusercontent.com/assets/27786/12520630/a2076828-c113-11e5-9411-5be94e6bca7e.png)

**Comment by steveklabnik** [comment]
Can you check your development console, maybe? it looks to me like the CSS didn't get loaded.

**Comment by ollie27** [comment]
I'm getting the same issue. The following line is missing from those pages:
```html
<link rel="stylesheet" type="text/css" href="../rustdoc.css">
```
It looks like these primitive files are leftovers all the way back from 1.2.0 and should be deleted or replaced with redirects to the current docs in `std`.

**Comment by notriddle** [comment]
The console is empty.

**Comment by GuillaumeGomez** [comment]
Broken for me as well. A link seems to be missing like @ollie27 pointed out.

@steveklabnik: If you want I can take a look.

**Comment by steveklabnik** [comment]
Please feel free.

This is also now reproducing for me.

**Comment by ollie27** [comment]
The issue is simply that https://doc.rust-lang.org/ is serving outdated files.

https://doc.rust-lang.org/core/primitive.i16.html is from 1.2 and I guess because it doesn't exist in 1.3 it was never overwritten but remained in place because however the docs are updated it doesn't seem to remove old files. Another example is https://doc.rust-lang.org/book/installing-rust.html which is from 1.5 yet still exists on the server.

The same issue occurs on https://doc.rust-lang.org/stable/ with https://doc.rust-lang.org/stable/core/primitive.i16.html but not on https://doc.rust-lang.org/beta/core/primitive.i16.html or https://doc.rust-lang.org/nightly/core/primitive.i16.html for some reason.

**Comment by brson** [comment]
I'll look into it.

**Comment by brson** [comment]
I've resynced the 1.6 docs to delete the old files and updated the release process so this doesn't happen again. Thanks for the report.
