### ISSUE TITLE
Include FFI example for Clojure in Book

### ISSUE THREAD

**Issue by doubleagent** [rust-lang/rust#31134]
Hi,
I would have submitted a pull request but I was unable to find [this page ](https://doc.rust-lang.org/book/rust-inside-other-languages.html) in the [repo](https://github.com/rust-lang/rust/tree/master/src/doc/book).

I think the following Clojure program fits nicely and would be a good addition.

```clojure
#!/usr/bin/env boot

(set-env! :dependencies '[[org.flatland/classlojure "0.7.1" :exclusions [org.clojure/clojure]]
                          [net.n01se/clojure-jna "1.0.0"]])

(require '[classlojure.core :as cl])
(require '[net.n01se.clojure-jna :as jna])
(require '[clojure.java.io :as io])

(def path (.getAbsolutePath (io/file "target/release/")))

(defn -main [& args]
  (cl/alter-java-library-path! (comp flatten vector) path)
  (System/loadLibrary "embed")
  (time (jna/invoke Long process)))
```

**Comment by steveklabnik** [comment]
Hi @doubleagent !

That's because, as of the next release, that chapter is going away. Specifically because we did not want to play favorites with other languages, and couldn't come up with a good rule for inclusion/exclusion, and how to maintain them over time.

Clojure rocks! It's cool that this works. But since the page no longer exists, this sample won't make it in. :smile:
