### ISSUE TITLE
Tracking issue for CStr::from_bytes_with_nul

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#31190]
Being added in https://github.com/rust-lang/rust/pull/30614, this'll track the unstable status.

* Are these the right names for the functions?
* Do we think they'll be generally useful?
* etc.

**Comment by kamalmarhubi** [comment]
I'm writing a bunch of systems code, and would like this function, along with a couple of related trait impls I forget right now.

One thing that jumps to mind: should the return be `Option`, or a `Result` with something akin `NulError` for `CString`? There's mention of an error at the start of #30614, and the analog in https://github.com/rust-lang/rfcs/issues/1264 also has a `Result`.

**Comment by CasualX** [comment]
I've just bumped into this function and I'd like to add a consideration:

In C/C++ it happens that you get a fixed size buffer eg `char strbuf[128];` which may be filled up to the brim with characters or ended earlier with a nul terminator. You'd manipulate these buffers with the [`strn*`](http://www.cplusplus.com/reference/cstring/) functions.

These days it is not encouraged to do this, but there's plenty of legacy stuff that uses it. In such a case interior nul bytes or not even having an ending nul is not a bug, but expected behaviour.

In this case it would be desired to have a function that can convert these into `CStr` instead of returning an error.

Is there even a use case for when you have a byte slice (char pointer + length) and want it to contain exactly a nul terminated C string? I can only think of unbounded, nul terminated strings (covered by `CStr::from_ptr`) and fixed length char buffers containing a C string of max length.

I'm not sure how to handle the optionality of the ending nul terminator in the fixed

**Comment by arcnmx** [comment]
@CasualX what you describe is not really a C string if it is not null terminted, and should not be used as one. Rust's `CStr` type is essentially "a collection of (non-zero) bytes terminated by a zero byte" and not keeping to that rule results in memory unsafety. A `[u8]` or `[c_char]` seems more appropriate for your case, with perhaps a helper function that will construct the smaller slice if it hits an early zero (or maybe a `Result<&CStr, &[u8]>` or even a `Cow<CStr>` depending on what you want to do with it?)

> Is there even a use case for when you have a byte slice (char pointer + length) and want it to contain exactly a nul terminated C string?

The function generally exists for data coming from a Rust application to be used in an FFI context, its main advantages being:

1. Accepts a native rust slice, as opposed to `CStr::from_ptr(data.as_ptr() as *const libc::c_char)`
2. The unsafe variant carries the additional benefit of avoiding the length check currently associated with `from_ptr`.

Take the implementation of [Deref for CString](https://github.com/rust-lang/rust/blob/0f02309e4b0ea05ee905205278fb6d131341c41f/src/libstd/ffi/c_str.rs#L300) for example; it uses `transmute` because it knows the underlying representation of `&CStr`. Stable code can't rely on that (and in fact the representation may possibly change to a single `*mut c_char` in the future). It comes up when creating strings for FFI purposes. Situations like creating types similar to `CString`, or maybe you're avoiding heap allocations and just can't use it, or whatever else.

It's also useful for other situations too though, like your fixed-size character buffer example. To convert it to a `&CStr`, you need to do the null byte check yourself, so you already know the length of the string at that point; which gives you a nice slice to then create a `&CStr` from.

**Comment by SimonSapin** [comment]
@CasualX What you describe sounds like a different abstraction from `CStr` (which is "nul-terminated with no interior nul"). I’d recommend defining a separate struct to build your own abstraction. `CStr` like the rest of the standard library is written in Rust, you can see it here:

https://github.com/rust-lang/rust/blob/master/src/libstd/ffi/c_str.rs

**Comment by CasualX** [comment]
@SimonSapin

Ah I interpreted Rust's `CStr` as 'be compatible with how C treats strings', but its scope is restricted to just 'nul terminated char arrays'.

I came here because in reading some file formats there's quite a lot of 'fixed length char buffers containing a maybe nul terminated C string' for which I was looking how to easily deal with. A simple scan for nul byte should do the trick, thanks.

I think it would be better to mimic the `std::str::from_utf8` API (ie, a free function):

```rust
fn from_char_buf(buf: &[c_char]) -> &[u8] {
	let len = buf.iter()
		.enumerate()
		.find(|&(_, &byte)| byte == 0)
		.map_or_else(|| buf.len(), |(len, _)| len);
	&buf[..len]
}
```

But I digress as this is off-topic, to atone for bringing up someting unrelated have some on-topic thoughts:

@arcnmx

Ok I see, this API exposes the `CString` -> `&CStr` as a constructor of `&CStr` where you don't start out with a `CString`. This implies that the use case of this API specifically is 'you have something that can't be turned into a `CString` but you wish to create a `&CStr` from regardless.

You suggest two use cases:

* Creating your own `CString`-like abstraction, in that case it should be covered by `CString::new` where it consumes your custom container.

* Creating `&CStr` without heap allocations, essentially a custom container type that uses a fixed-size `u8` array for backing which seems reasonable.

(My use case wouldn't be covered anyway, assuming the upfront length calculation really does go away at some point)

The docs specifically say that the upfront length calculation is an implementation detail that is desired to be changed. Using this as an argument is essentially cementing in the API that the length check is done ahead of time.

As for the API the checked version it should most certainly return a `Result<&CStr, NulError>` to mimic how `CString::new` behaves.

The names mirror their cousins in `CString` and matches the convention used for this sort of thing throughout the stdlib.

**Comment by CasualX** [comment]
If a name is what you want, I suggest `NulErr` ;)

**Comment by alexcrichton** [comment]
🔔 This issue is now entering its cycle-long **final comment period** for stabilization :bell: 

The libs team decided, however, that we should probably return a `Result` here instead of an `Option`

**Comment by alexcrichton** [comment]
The libs team discussed this issue during triage yesterday and the decision was to **stabilize**
