### ISSUE TITLE
Clearly note that unstable items in stable docs may be out of date

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/rust#31204]
People seems to use the stable documentation to look for unstable items that are not available in the stable nevertheless. As per #25863 it is intentional, but then there remains a tough case of out-of-date documentation. In the IRC I have heard of one such example that the `clone_from_slice` method used to accept [different slice lengths](http://doc.rust-lang.org/stable/std/primitive.slice.html#method.clone_from_slice) but since then updated to [panic in such cases](http://doc.rust-lang.org/nightly/std/primitive.slice.html#method.clone_from_slice).

We cannot regenerate the stable documentation every time nightly updates, but we can probably link to the unstable documentation as the best effort. Something like this:

![image](https://cloud.githubusercontent.com/assets/323836/12572285/701b8d7c-c42d-11e5-86bc-28d02067bc5b.png)

**Comment by steveklabnik** [comment]
This also won't universally work, as sometimes, unstable features are removed and renamed. :-1: from me.

**Comment by lifthrasiir** [comment]
@steveklabnik You are right. But you can instead link to the search page as an alternative. Frankly, even the notice that it might *not* be current would be helpful; it is just an idea, after all.

**Comment by ollie27** [comment]
What about just removing unstable items from stable docs? I've never understood why they're included because they're always out of date as shown here and add unnecessary noise.

**Comment by rphmeier** [comment]
@ollie27 That seems reasonable to me. It's not as if you can use unstable features from stable. I suppose the purpose is to inform users that they may have a solution if they are willing to use nightly, but it might create more confusion than it's worth.

**Comment by steveklabnik** [comment]
We kept them in specifically so that you could see that something may be
added in the future and get involved in the conversation if the feature
matters to you.

**Comment by steveklabnik** [comment]
Triage: no changes. Due to the stuff in my previous comments, I still think this is a bad idea, but I'll let @rust-lang/rustdoc decide that.

**Comment by GuillaumeGomez** [comment]
I also think this is a bad idea. It can't be applied generally on the std lib.

**Comment by QuietMisdreavus** [comment]
I generally agree with @steveklabnik and @GuillaumeGomez. It's not worth trying to add mapping information if an unstable item is moved, renamed, or deleted, since the stable docs are generated once, upon release, and never touched afterward. Attempting to add this mapping information would result in noisy backports that only serve to provide information for something that's not useful to stable users anyway.

However, there may be a way to salvage the issue, if we don't have to link to the actual item. Would it suffice to add a generic note like "Please note the item may be different on the \[nightly docs\]," where the link points to the root of the nightly docs, instead of the item itself? That would be much easier to add.

**Comment by Dylan-DPC** [comment]
Closing this as the team is not in favour of this
