### ISSUE TITLE
Confusing unreachable pattern error

### ISSUE THREAD

**Issue by pyfisch** [rust-lang/rust#31221]
This simple code fails to compile because `Other` is not defined. But the error message is `unreachable pattern [E0001]` `Bar => "bar"`. But `Bar` is not the cause it just happens to occur after `Other`.
```rust
enum Foobar {
    Foo,
    Bar,
}

fn main() {
    use Foobar::*;
    let x = Foo;
    println!("{}", match x {
        Foo => "foo",
        Other => "other",
        Bar => "bar",
    });
}
```

http://is.gd/zL6HGt

**Comment by apasel422** [comment]
I agree that this is confusing, though from the compiler's perspective, the error message makes sense. Since `Other` isn't a variant of `Foobar`, `Other` becomes the name of a binding that matches all possible values of `x` other than `Foobar::Foo`. (See https://doc.rust-lang.org/book/patterns.html.) Once that happens, the `Bar` case is indeed unreachable.

**Comment by apasel422** [comment]
Perhaps the error message could point to the match arm that the unreachable arm overlaps with.

**Comment by durka** [comment]
Also if you comment on the Bar arm, you get a snake-case warning on Other, but unfortunately the error happens first.

**Comment by pyfisch** [comment]
Thanks for your coments. Now at least I understand why the compiler printed this error message.

**Comment by nagisa** [comment]
Related: https://github.com/rust-lang/rust/issues/5657
