### ISSUE TITLE
Coercion sites are not consistent between struct tuples and structs

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#31260]
``` rust
pub struct Struct<K: 'static> {
    pub field: K,
}

static STRUCT: Struct<&'static [u8]> = Struct {
    field: &[1]
};

pub struct Tuple<K: 'static>(K);

static TUPLE: Tuple<&'static [u8]> = Tuple(&[1]);
```

`STRUCT` fails to type check, while `TUPLE` succeeds.

```
<anon>:7:40: 9:2 error: mismatched types:
 expected `Struct<&'static [u8]>`,
    found `Struct<&[_; 1]>`
(expected slice,
    found array of 1 elements) [E0308]
<anon>:7 static STRUCT: Struct<&'static [u8]> = Struct {
<anon>:8     field: &[1]
<anon>:9 };
<anon>:7:40: 9:2 help: see the detailed explanation for E0308
```

**Comment by SimonSapin** [comment]
This coercion is important when using `b"…"` byte string literals.

**Comment by eddyb** [comment]
The tuple struct case is actually the function call "expected type" propagation, which would have to be adapted to struct literals as well.

**Comment by nox** [comment]
Yes.

**Comment by SimonSapin** [comment]
Coercion already happens in non-generic struct literals:

```rust
struct Foo { s: &'static [u8] }
static FOO: Foo = Foo { s: b"foo" };
```

**Comment by eddyb** [comment]
@SimonSapin Yes, but the field types are taken from the struct and not combined with the overall expected type for the struct literal.

**Comment by cybergeek94** [comment]
I just discovered this bug/unexpected behavior today (#34240). I would like to see some movement on it because it's surprising that these two don't work the same way.

Here's a workaround I found; it's ugly as hell but I'm using it in a generated file that no human would want to look through anyway: https://is.gd/m9kD9U

I tried type ascription but it seems to not cue coercion, it just moves the type error: https://is.gd/rosoMe

**Comment by nox** [comment]
Any news on this?

**Comment by KalitaAlexey** [comment]
Is anyone working on it?

**Comment by nikomatsakis** [comment]
It seems like @eddyb implemented a **partial** fix in #40398 but suggests that there are backwards incompatibility issues to be considered that preventing him from going further. I'm not quite sure what he had in mind there, perhaps he can elaborate.

**Comment by arielb1** [comment]
Making sure we remember to look at this.

**Comment by eddyb** [comment]
@nikomatsakis What I did is I computed a "light hint" (which becomes "strong hint", i.e. forcing coercion, if it reaches a block, and it's enough to help integer inference for #40355).

This is a common problem with coercion hints, in that unless there's enough type information to prevent them from triggering, they *will* trigger early even if that breaks later.

The thing to try here is to replace [these two lines](https://github.com/rust-lang/rust/blob/838e9c5123b6fdfbfc551e529a178e04e7aacf9a/src/librustc_typeck/check/mod.rs#L3162-L3163) with the simpler:
```rust
self.check_expr_coercable_to_type(&field.expr, field_type_hint)
```

`final_field_type` doesn't even need to be computed if that works, since `field_type_hint` is strictly more specific - AFAICT, we already have that "specificity" with function calls, but since it hasn't been used with struct literals before, crater/cargobomb might reveal regressions.

**Comment by nikomatsakis** [comment]
@eddyb ok, I was mostly wondering if you encountered actual regressions in practice, or just theorize that this might lead to problems.

**Comment by eddyb** [comment]
@nikomatsakis I don't think I got the chance to do a crater run and then I lost track of it.

**Comment by nikomatsakis** [comment]
@arielb1 will open a PR and we can try a crater run at least.

**Comment by burdges** [comment]
There is still a similar problem with the type inference of temporaries when you have an array that should be interpreted as a slice buried in a tuple inside an outer slice.
