### ISSUE TITLE
Make not building "rustc-stage1"; crt2.o is not a directory.

### ISSUE THREAD

**Issue by Jexell** [rust-lang/rust#31293]
Running `make -j4 rustc-stage1` in `msys2` appears to build LLVM for stage 0 before exiting. Running the command a second time results in:
```
cp C:/Program Files/mingw-w64/x86_64-4.9.3-win32-seh-rt_v4-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o x86_64-pc-windows-gnu/rt/crt2.o

cp: target ‘x86_64-pc-windows-gnu/rt/crt2.o’ is not a directory

/home/James/rust/mk/rt.mk:375: recipe for target 'x86_64-pc-windows-gnu/rt/crt2.o' failed
make: *** [x86_64-pc-windows-gnu/rt/crt2.o] Error 1
```
I don't remember what I did differently, but once running the command a second time caused make to complain that it did not know what `rustc-stage1` was.

**Comment by vlsh** [comment]
Do you get same error for single threaded build (i.e. without -j4 flag)? I can confirm that build fails with -j2 flag for me with a similar error. This is on Windows 10 32-bit, MSYS2(with MinGW64 tools in path as recommended by README). It works fine for single-threaded builds, although I have other bugs to report...

`rustc: i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib/libstd

error: linking with `gcc` failed: exit code: 1

note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-Wl,--large-address-aware" "C:\\Src\\rust\\i686-pc-windows-gnu\\stage0\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\dllcrt2.o" "C:\\Src\\rust\\i686-pc-windows-gnu\\stage0\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\Src\\rust\\i686-pc-windows-gnu\\stage0\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib\\std-db5a760f.0.o" "-o" "i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib\\std-db5a760f.dll" "i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib\\std-db5a760f.metadata.o" "-nodefaultlibs" "-L" "i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib" "-L" "i686-pc-windows-gnu/rt" "-L" "C:\\Src\\rust\\i686-pc-windows-gnu\\llvm\\Debug+Asserts/lib" "-L" "C:\\Src\\rust\\i686-pc-windows-gnu\\stage0\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-l" "backtrace" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-l" "gcc_eh" "-l" "gcc_eh" "-l" "ws2_32" "-l" "userenv" "-l" "shell32" "-l" "advapi32" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\libcollections-db5a760f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\liballoc-db5a760f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\librustc_unicode-db5a760f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\librand-db5a760f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\liballoc_system-db5a760f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\liblibc-db5a760f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\libcore-db5a760f.rlib" "-Wl,--no-whole-archive" "-shared" "-l" "compiler-rt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\Src\\rust\\i686-pc-windows-gnu\\stage0\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\rsend.o"

note: gcc.exe: error: C:\Src\rust\i686-pc-windows-gnu\stage0\lib\rustlib\i686-pc-windows-gnu\lib\dllcrt2.o: No such file or directory

error: aborting due to previous error

/c/Src/rust/mk/target.mk:186: recipe for target 'i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib/stamp.std' failed
make: *** [i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib/stamp.std]
 Error 101
`

**Comment by Jexell** [comment]
I get the same error if I run it without the -j4 flag for the second time. I don't know what error I get if I run make without -j4 for the first time though, except that it takes a very long time to run.
 I have a 64 bit version of Windows 7 and, if it makes any difference, my path to mingw has spaces, although mingw tools seem to be callable from the MSYS2 console.

**Comment by mingwandroid** [comment]
From the `MSYS2 Wiki`:

http://sourceforge.net/p/msys2/wiki/MSYS2%20installation/

> They can be installed or extracted to any place on your computer, but you MUST use folder names that consist of only ascii characters and no spaces (also it makes good sense to put it in a path that doesn't use many characters due to PATH_MAX being 260; C:\msys32 or C:\msys64 is ideal).

You've ran into a prime example of why this was written. One of the original motivations for creating MSYS2 was to provide (ok to improve `MSYS`'s) Unix build tools for Windows users. Some Unix tools aren't written to expect paths with spaces. `GNU make` in particular wasn't. A good reference for this is:

http://www.cmcrossroads.com/article/gnu-make-meets-file-names-spaces-them

If `rust` can move away from `GNU make` onto a different generator you'll have more luck, but avoiding paths with spaces altogether is just good advice overall since you'll likely run into more problems down the road.

**Comment by Jexell** [comment]
@mingwandroid Thanks, that solved the problem.
@vlsh Does this solve it for you as well? If it does I'll close this (non)issue.
