### ISSUE TITLE
Panic on None when joining on thread which is called yield_now

### ISSUE THREAD

**Issue by zonyitoo** [rust-lang/rust#31316]
Minimal test case:

```rust
use std::thread;

fn main() {
    let h = thread::spawn(|| {
        thread::yield_now();
    });
    
    h.join().unwrap();
}
```

This piece of code will panic with output:

```
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
playpen: application terminated with error code 101
```

Tested on playpen with stable Rust.

**Comment by alexcrichton** [comment]
I can reproduce this on playpen but not locally unfortunately.

[The assertion being tripped here](https://github.com/rust-lang/rust/blob/9041b930585806b948b4cc68933047ffdc96f6f9/src/libstd/thread/mod.rs#L579) indicates that `pthread_join` returned but the return value of the thread was not filled out, so this is potentially a data race as well (hence tagging with I-nominated and T-libs). This *may* have to do with `pthread_join` returning an error but us not detecting it [because the assertion only happens in debug mode](https://github.com/rust-lang/rust/blob/9041b930585806b948b4cc68933047ffdc96f6f9/src/libstd/sys/unix/thread.rs#L145-L151). A [minimal reproduction of this behavior](https://play.rust-lang.org/?gist=9524015f7de238d22f24&version=nightly), however, does not indicate that `pthread_join` is returning an error.

This would probably be easier to debug if we could reproduce it somewhere where we *could* debug it, but I would also be happy for now just leaving the assertion in place but switching to using `Mutex` or something to prevent a possible data race.

@zonyitoo did you discover this through the playpen itself, or was this something that happened locally?

**Comment by alexcrichton** [comment]
Oh wait after a little more investigation, it looks like [this program](https://play.rust-lang.org/?gist=4a35e4edd2c20a32f8f0&version=nightly) exhibits similar behavior. It looks like `sched_yield causes the thread to be terminated due to playpen considering it a bad system call. 

The behavior here appears to be that the thread is immediately terminated and yet `pthread_join` returns 0 (success). This means that in the standard library we never hit the code that stores the return value of the thread, hence the assertion being hit.

I'm removing the nominated/unsound tags as if the thread is being killed this isn't a safety issue, it seems like it's just a bug that may want a better error message.

**Comment by zonyitoo** [comment]
I discovered it on playpen itself. It seems to works well on my laptop.

**Comment by tbu-** [comment]
In some sense, yes. You could ask the playpen maintainers to add `sched_yield` to the list of safe system calls.

**Comment by zonyitoo** [comment]
Ok, closing and going to ask playpen maintainers to fix this.
