### ISSUE TITLE
extracting dependencies

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#31395]
The following two features are missing from the compiler:

1. Extracting file dependencies
2. Extracting crate dependencies

The first one can be done but only by performing a whole compilation which is very slow. The second one cannot be done at all afaict.

Ideally  both things should be emitted immediately after the parsing.

**Comment by arielb1** [comment]
What are file dependencies? rustc compilation is crate-as-a-unit.

This should also be an RFC rather than an issue - the design is not obvious.

**Comment by mahkoh** [comment]
>What are file dependencies?

>the design is not obvious.

Since you're obviously unaware of the compiler option that allows you to extract file dependencies, you are in no way qualified to decide whether the design is clear.

But I should have realized that such a trivial thing needs a detailed RFC and several months of deliberation. Luckily I've also realized now that I can simply implement this myself in the lrsc driver with little effort, giving lrsc another edge over rustc.

**Comment by arielb1** [comment]
make-style depinfo can already be done through
```
./x86_64-unknown-linux-gnu/stage0/bin/rustc -Z no-analysis --emit=dep-info whatever.rs
```

**Comment by pnkfelix** [comment]
@mahkoh The language of this comment

> Since you're obviously unaware of the compiler option that allows you to extract file dependencies, you are in no way qualified to decide whether the design is clear.

is presumptuous and condescending. It is a violation of the third bullet of the CoC: https://www.rust-lang.org/conduct.html

(The comment also was demonstrated as false by arielb1's reply, but that is outside the domain of the CoC.)

I'm pretty sure you are already aware that it was a violation of the CoC, but I am nonetheless replying here so that other people seeing this understand it is an example of a violation.

**Comment by mahkoh** [comment]
>(The comment also was demonstrated as false by arielb1's reply, but that is outside the domain of the CoC.)

Let's see

1. Don't know something
2. Get called out
3. Learn it
4. Look, I knew it from the start

Huh.

**Comment by arielb1** [comment]
Indeed I was not aware of `--emit=dep-info` (and @mahkoh might not have been aware of `-Z no-analysis`). OTOH I am quite sure that adding crate dependencies to `rustc` requires user-visible design work, and therefore a (small - this is not going to be impl specialization) RFC.

**Comment by steveklabnik** [comment]
> Huh.

Yes, learning can happen without being condescending. Being right or wrong about @arielb1 knowing about this flag is completely irrelevant here, as @pnkfelix said.

**Comment by pnkfelix** [comment]
* Was the original statement ("your lack of knowledge of detail A implies you are not qualified to discuss broader topic B") shown to be false by @arielb1 's reply?

 * In my opinion it was; but really it was a distraction for me to have even mentioned it in that parenthetical, since it invites this sort of quibbling that distracts from the larger issue.

 * I thank @steveklabnik for pointing that out.

(I'll try to avoid such parentheticals in the future, since even with qualifications like "this is outside the domain of the CoC" they are just distractions.)

**Comment by mahkoh** [comment]
>and @mahkoh might not have been aware of -Z no-analysis

I was not and it does indeed somewhat solve the first point. However, even with `-Z no-analysis` the whole process still takes somewhat long mostly due to macro expansion. It's not clear if this can be avoided. However, it does not solve the much more pressing second point.

>OTOH I am quite sure that adding crate dependencies to rustc requires user-visible design work

There is already a process for unstable compiler options, namely the `-Z unstable-options` switch.

>Being right or wrong about @arielb1 knowing about this flag is completely irrelevant here, as @pnkfelix said.

@pnkfelix tried to call me out for being presumptuous regarding @arielb1's knowledge of compiler flags and I called him out form being equally presumptuous. That seem quite relevant.

**Comment by arielb1** [comment]
> There is already a process for unstable compiler options, namely the `-Z unstable-options` switch.

The process for new features is:
1) an RFC is written
2) the RFC is accepted
3) an implementation is written under a feature flag
4) the feature is stabilized, removing the feature flag

If you provide a clear enough description of the feature you want, I have no problem writing the RFC for you.

**Comment by arielb1** [comment]
I was just trying to help you - the rust-lang/rust issue tracker is not the best place for vague feature requests (or feature requests at all).

**Comment by Manishearth** [comment]
> @pnkfelix tried to call me out for being presumptuous regarding @arielb1's knowledge of compiler flags and I called him out form being equally presumptuous. That seem quite relevant.

No, whether or not @arielb1 knew the feature is irrelevant. Ariel mentioned that the issue was unclear (it still is unclear) and closed it for being on the wrong repo. You responded with a very presumptuous and condescending comment. Whether or not your presumption was correct is irrelevant; the rust community does not allow such hostile discourse.

**Comment by mahkoh** [comment]
>the rust community does not allow such hostile discourse.

But it does allow people like you to repeatedly derail threads.

**Comment by arielb1** [comment]
He's on the moderation team. I would prefer for the moderation team to stay out of this discussion.
