### ISSUE TITLE
Resolve reports arbitrarily many identical copies of an error message

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#31402]
The following example reports `error: bar is private, and cannot be reexported [E0364]` four times.

```rust
fn bar() {}
pub use bar as baz;

pub use a::*;
mod a { pub use b::foo; }
mod b { pub use c::foo; }
mod c { pub fn foo() {} }
```
If the glob import is commented out, it only prints the error once.

**Comment by dirk** [comment]
I believe this is because we're generating an error **every time** we encounter this invalid reexport, and in your example that is happening 4 times (once in self, once in `a`, once in `b`, and once in `c`) because we resolve all the imports and exports for the modules (self, `a`, `b`, and `c`). If we reported something like a backtrace for each of these failures it would show that it was happening in each of those modules.
