### ISSUE TITLE
Parser inconsistency in for loop iter expression place

### ISSUE THREAD

**Issue by makoConstruct** [rust-lang/rust#31423]
http://is.gd/4PtH5V

**Comment by huonw** [comment]
This is by design; the `for _ A { i: 3 }.iter() {` version is parsing the `A` (by itself) as the iterator, with the following `{` the start of the body of the loop. This is important to allow things like

```rust
let iter = ...;
for _ in iter { ... }
```

without requiring disambiguating parens: `for _ in (iter) { ... }`. We chose this arrangement because we felt that `for _ in identifier { ... }` and `if identifer { ... }` (etc.) were more common than constructing a struct directly in the iterator/condition.

Thanks for filing!
