### ISSUE TITLE
Warn on redundant closures

### ISSUE THREAD

**Issue by Ticki** [rust-lang/rust#31454]

**Comment by jonas-schievink** [comment]
What do you mean by "redundant closure"? The same thing clippy's beta-reduction lint already warns against?

**Comment by Ticki** [comment]
By "redundant closures", I mean closures which just wrap another function or enum varient constructor, instead of using them directly.

**Comment by jonas-schievink** [comment]
Yeah, I think that's what clippy does as well

**Comment by arielb1** [comment]
That's probably a job for clippy.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!

**Comment by jonas-schievink** [comment]
https://github.com/Manishearth/rust-clippy/wiki#redundant_closure
