### ISSUE TITLE
Create read-only file fails on nightly

### ISSUE THREAD

**Issue by danburkert** [rust-lang/rust#31453]
cc @alexcrichton 

There has recently been a regression introduced to `std::fs`.  The following line results in `Ok` on stable and `Err` on nightly:

```rust
std::fs::OpenOptions::new().read(true).create(true).open("some-file")
```

This regression is affecting Linux, Windows, and OS X.  You can see it in action in recent [fs2](https://github.com/danburkert/fs2-rs) CI builds.

**Comment by alexcrichton** [comment]
This is a known change in behavior implemented in https://github.com/rust-lang/rust/pull/30872 as proposed in [RFC 1252](https://github.com/rust-lang/rfcs/blob/master/text/1252-open-options.md). This case was [specifically disallowed](https://github.com/rust-lang/rfcs/blob/master/text/1252-open-options.md#combination-of-access-modes-and-creation-modes) due to its inconsistent behavior across platforms. Adding `write(true)` should guarantee it works on all platforms and on all versions.

**Comment by alexcrichton** [comment]
nominating for discussion of the fallout, however

**Comment by pitdicker** [comment]
A link in the RFC is broken, but this is from the [OpenBSD mailing list](http://marc.info/?l=openbsd-tech&m=96976914719648). It says it does not work on OpenBSD and Solaris

**Comment by danburkert** [comment]
Ok sounds good.  I didn't realize it wasn't available everywhere.  I'll
update my code accordingly.

**Comment by pitdicker** [comment]
But sorry for the breakage anyway

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and decided that the fallout here is acceptable under the [API evolution RFC](https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md), so closing.

Thanks again for the report though!
