### ISSUE TITLE
doc question: Is Android extensively tested or not?

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang/rust#31547]
Hi,

We started to translate the Rust book (The Rust Programming Language) into Japanese (You can read it [here](https://rust-lang-ja.github.io/the-rust-programming-language-ja/1.6/book/index.html)). And I have got a question about the following sentences:

https://github.com/rust-lang/rust/blob/1.6.0/src/doc/book/nightly-rust.md

> Oh, we should also mention the officially supported platforms:
>
> - Windows (7, 8, Server 2008 R2)
> - Linux (2.6.18 or later, various distributions), x86 and x86-64
> - OSX 10.7 (Lion) or greater, x86 and x86-64
>
> We extensively test Rust on these platforms, and a few others, too, like Android. But these are the ones most likely to work, as they have the most testing.

I am not sure whether Android is extensively tested or not.

Does the above means the followings?

- We *extensively* test Rust on a few other platforms like Android in addition to the officially supported platfolms (Windows, Linux and OS X).
- Extensive test means having the most testing, and they (Android, Windows, Linux and OS X) are likely to work. (Maybe because we are talking about nightly Rust in this chapter?)

Or the followings?

- We *extensively* test Rust on the officially supported platfolms (Windows, Linux and OS X), and they are guaranteed to work.
- We test a few other platforms like Android, but they have the most testing and likely to work (*not* guaranteed to work).

Thanks!

**Comment by alexcrichton** [comment]
Oh wow, awesome work! Right now the support for each platform is best officially explained in the [tiers documentation](http://doc.rust-lang.org/nightly/book/getting-started.html#platform-support), but that unfortunately classifies Android as a tier 2 platform. In reality, the support for Android looks like:

* All PRs run the full test suite on Android, and nothing lands if a test fails
* We are producing nightly binaries for Android every night, and no nightly will be produced if this build fails
* We do not, however, provide a way to easily install the android binaries just yet (as we do for other x86/x86_64 platforms)

Which is to say that Android is *almost* tier 1, it's just not quite there yet. We basically extensively test Android as much as we can, although it will not be as battle-hardened as other platforms as it simply sees less usage.

For now, though, the easiest thing to do will to probably explain the support in terms of tiers. Tier 1 is the only ones guaranteed to build and work, where as tier 2 is just guaranteed to build. Android is "very likely" to work but we haven't yet quite classified it as such due to it being more difficult to download and use.

**Comment by tatsuya6502** [comment]
Thank you for the prompt and detailed reply! I think now I understand what you guys were trying to say in the Nightly Rust page. Android is basically extensively tested but not (yet) be as battle-hardened as tier 1 platforms. Also other aspects (such as lack of installer) are making Android not to be tier 1.

Let me think about a bit more on the sentences in the book. I will try to come up with a doc PR, so we can discuss it further.

I am closing this issue since my question was answered. Thanks again!
