### ISSUE TITLE
Timeout for TcpListener::accept()

### ISSUE THREAD

**Issue by Flaise** [rust-lang/rust#31615]
As best I can tell, there isn't a way to set a timeout for the TcpListener::accept() function without accessing private fields, which the Rust compiler of course won't allow. This makes it very difficult to cleanly terminate a thread that is currently blocking for incoming connections.

**Comment by alexcrichton** [comment]
Thanks for the report! Our runtime way-back-when actually supported this kind of functionality, but this design in libstd currently isn't support, nor does it necessarily fit well. There aren't actually really any private fields of `TcpListener` as on Windows it's just a fancy wrapper around a single `SOCKET` and on Unix it's just a wrapper around `c_int`. You can access both underlying values via the OS-specific extension traits.

In general timing out an accept is actually a relatively nontrivial implementation. On Unix you can do it via `select` most of the time and on Windows you maybe able to as well, but working with `select` isn't always the easiest...

Regardless, if you're doing serious I/O programming for stuff like this, I'd recommend [mio](https://github.com/carllerche/mio), and otherwise I'd just google around how to do this in C and you can likely combine libc + `std::os::*` to do the same!

**Comment by Flaise** [comment]
If there were no private fields on TcpListener, I'd be able to do something like:

`tcp_listener.0.socket().set_timeout(Some(Duration::from_secs(1)), SO_RCVTIMEO);`

From what I've read elsewhere, SO_RCVTIMEO works on server socket accept operations as well as the client socket read operation that you're already using it for. I don't see what the big deal is, though I haven't tried forking and tampering with the implementation of Rust's standard library to test that claim.

If blocking _really_ isn't a good solution to this problem, surely there's some other way this can be done besides having people not use the standard library. Could the file handle be extracted and then closed? Would the accept function return if the thread received an interrupt signal like in Java?

**Comment by alexcrichton** [comment]
Interesting! In that case this may be a good addition to the [net2 extensions](https://github.com/rust-lang-nursery/net2-rs). One point to maybe consider is if this works on Windows as well (I'm not sure)

You can extract the file descriptor on Unix through the `AsRawFd` trait
