### ISSUE TITLE
getaddrinfo may be slow on OS X

### ISSUE THREAD

**Issue by cetra3** [rust-lang/rust#31665]
Tracking down an issue within the [Iron library](https://github.com/iron/iron/issues/423), It appears as though when making a connection, the TTL of the DNS record is not honoured, and each subsequent request to the same URL (host) is met with a DNS lookup.

With a hostname in the URL I get about a half a second delay.  Without, I get normal response times.

If I watch the interface with tcpdump I can see dns request for the host each connection time.

I've double checked the DNS records and while they have a relatively short TTL (5 mins) I don't feel that there should be subsequent requests.

Using Mac OS X

**Comment by nagisa** [comment]
I believe it is the OS’s responsibility to cache DNS requests. We do not produce raw DNS queries either – we’re using the libc getaddrinfo call.

**Comment by Aatch** [comment]
Looking into this it appears that the OS is normally expected to cache DNS requests. I think that adding caching behaviour to the standard library for this is inappropriate and the relevant libraries should handle it, if deemed necessary.

Feel free to re-open if you disagree.

**Comment by cetra3** [comment]
The OS does cache requests correctly, but rust doesn't appear to be using this facility at all.

**Comment by Aatch** [comment]
@cetra3 having done further investigation, it seems like OS X has a history of being weird with `getaddrinfo`. While nothing I have found matches your issue, I'm tempted to think that it's an OS X issue.

**Comment by cetra3** [comment]
@Aatch I have tried this on Ubuntu 14.04 and don't receive the same slowdown so it does appear to be related to OSX.

Appears as though the Kerberos library hit this issue also: https://krbdev.mit.edu/rt/Ticket/History.html?id=1683

Is it possible to use this same workaround in Rust, using `gethostbyname` instead of `getaddrinfo`?

**Comment by Aatch** [comment]
@cetra3 the thing is, that issue is over a decade old now, so I'm reluctant to use that solution. Especially since `gethostbyname` is largely considered obsolete nowadays.

I don't have access to an OS X machine to investigate on, so I'll punt this along to @rust-lang/libs

**Comment by cetra3** [comment]
@Aatch A decade old and still not fixed!  I doubt that Apple would be bothered fixing it if it's gone this long.

**Comment by Aatch** [comment]
@cetra3 it's more that I can't find any new reports that match this issue properly. There's all sorts that have similar complaints but don't apply to us (setting a servname is one, which we don't do). `getaddrinfo` has had some significant work done on it between now and then, so it seems weird that it'd still be slow.

**Comment by tarrant** [comment]
I attempted to replicate this issue on OSX 10.11.1 and Rust 1.6.0 with the following code:

```
extern crate libc;
extern crate time;

use libc::getaddrinfo;
use std::ffi::CString;
use std::ptr;

#[test]
fn it_works() {
    let count = 10000;

    let start = time::now();
    for _ in 0..count {
        call_getaddrinfo("google.com".to_string());
    }
    let end = time::now();

    let diff: time::Duration = end - start;

    println!("End ({0}) - Start ({1}) = {2} / {3} = {4}",
             end.ctime(),
             start.ctime(),
             diff,
             count,
             diff / count);
}

fn call_getaddrinfo(name: String) {
    // Function Signature:
    // pub unsafe extern fn getaddrinfo(node: *const c_char, service: *const c_char, hints: *const addrinfo, res: *mut *mut addrinfo) -> c_int

    let hostname = CString::new(name).unwrap();

    unsafe {
        // let hints_ptr = &hints;
        let mut res = ptr::null_mut();
        let r = getaddrinfo(hostname.as_ptr(), ptr::null(), ptr::null(), &mut res);
        if r < 0 {
            panic!("Error from getaddrinfo");
        }
    };
}
```

My invocation to getaddrinfo appears to match that of [libstd](https://github.com/rust-lang/rust/blob/c4b16384f101bbe28dc4eec0651a61cb9d5274ac/src/libstd/sys/common/net.rs#L123-L124), although I'm calling via crates.io/libc instead of what appears to be the builtin c.

The output of the test program is showing:

>>> End (Mon Feb 15 23:06:01 2016) - Start (Mon Feb 15 23:05:57 2016) = PT4.163779S / 10000 = PT0.000416377S

Which is very acceptable time for a DNS lookup unless I'm completely misreading it. Tcpdump is also not showing anything outside of the normal.

@cetra3 is there any additional info you can provide, osx version etc? I'm rather curious as to what is going on.

**Comment by cetra3** [comment]
@tarrant,

I have tested your code and it works OK with google.com, but not `.local` addresses.  

The local addresses I have do not have ipv6 (AAAA) records, which is what I can see is being requested continously.  My assumption is that `getaddrinfo` is doing something weird in this case.

**Comment by nodakai** [comment]
What happens if you pass `PF_INET` as `ai_family` ?

**Comment by cetra3** [comment]
@nodakai I'm sorry I am not skilled enough to know how to pass in a C const into rust code.  Can you give me info on how to do this?

**Comment by Aatch** [comment]
@cetra3 oh, so you're using local addresses? That changes things. There's tons of reports of OS X doing lookups for `.local` addresses, e.g. http://apple.stackexchange.com/questions/175320/why-is-my-hostname-resolution-taking-so-long & http://www.lists.apple.com/archives/darwin-userlevel/2005/Feb/msg00018.html

There's not really much we can do about it though. Even if we detect the use of `.local` names on OS X, it's not really a good idea to just assume it should return `127.0.0.1`/`[::1]`, nor does it seem like a good idea to do IPv4-only lookups. The only real action we can take is to provide another API that allows more flexibility, which is probably something we should do anyway.

The only real fix here though is to add IPv6 addresses (even if they're just dummy ones) for your `.local` addresses.

**Comment by tarrant** [comment]
@Aatch `.local` adresses often aren't `127.0.0.1`, they are generally mDNS, mutlicast DNS, addresses that are detected via Bonjour. I'm hoping to attempt to replicate the issue when I'm home tonight where I have IPv6 enabled and multiple apple devices with bonjour.

I do agree you that this is likely a system issue. My current theory is that OS X is not caching NXDOMAIN for these quad records. Due to how mDNS works, querying the entire network for someone who responds to the name, the these lookups can be slow.

**Comment by tarrant** [comment]
I played around on my home network with mDNS. It looks like OSX definitely isn't caching it, every request appears to be hitting the network, in addition if you are attempting to lookup a host that isn't responding it gets extremely slow, around five seconds to timeout.

Sadly I have no mDNS broadcasting machines that aren't listening on IPv6 so I can't investigate that specific case.

I'd definitely chalk this up to an OS issue, DNS cache rules are configured and managed by the OS and not by the language or the application. I've personally had no end of issues due to HAPROXY maintaining a permanent DNS cache.

**Comment by tmm1** [comment]
According to https://lists.apple.com/archives/bonjour-dev/2006/Jul/msg00033.html, macOS's getddrinfo() does not integrate with the mDNSResponder cache and will always send queries over the network. I'm seeing similar behavior on the latest version of macOS.

**Comment by tmm1** [comment]
Disregard my previous comment. According to https://emptysqua.re/blog/getaddrinfo-cpython-mac-and-bsd/, as of macOS 10.5 the `getaddrinfo()` call is tied into the system's mdns resolver.

I used a simple test program (http://www.logix.cz/michal/devel/various/getaddrinfo.c) to try resolving mdns hostnames, and it completes within milliseconds.

**Comment by jackh726** [comment]
Seems fixed, but not really sure how to add a test for this. Closing.
