### ISSUE TITLE
Pretty Print DocComment Attribute With Slashes

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/rust#31743]
Should the [libsyntax::print::pprust::print_attribute_inline fn](https://github.com/rust-lang/rust/blob/master/src/libsyntax/print/pprust.rs#L755), given an `Attribute` where `is_sugared_doc` is true print the prefixing `///` or `//!`?

Or are the slashes expected to already be there before printing, in case the string is multiple lines? And if so, is there a helper fn somewhere in `libsyntax` I can use to add them?

**Comment by Mark-Simulacrum** [comment]
It seems that `print_attribute_inline` doesn't print the comments, instead calling `maybe_print_comment` to take care of printing the comment start, which in turn calls [`print_comment`](https://github.com/rust-lang/rust/blob/master/src/libsyntax/print/pprust.rs#L552), which seems to be the answer to your second question.

I'm going to close this since I think that answers your questions.

**Comment by KodrAus** [comment]
Thanks @Mark-Simulacrum! Cleaning up some old outstanding issues? :)

I don't even remember why I asked this...
