### ISSUE TITLE
Missing trait Debug for std::time::Instant

### ISSUE THREAD

**Issue by vi** [rust-lang/rust#31866]
Although 

> There is no method to get "the number of seconds" from an instant.

, I think Debug may leak internal representation which can include those number of seconds (or some other increasing number).

**Comment by durka** [comment]
Debug doesn't have to be derived. `println!("{:?}", Instant::now())` could simply print "Instant".

**Comment by vi** [comment]
But it's not really useful for debugging the code that compares them a lot.

**Comment by Mark-Simulacrum** [comment]
I believe this issue is about the Debug implementation for Instant exposing internal API details, but I don't necessarily see that as a bad thing. I think it's somewhat expected that while Debug may print information, the actual output should not be relied upon (i.e., parsing it would not be acceptable). I'm nominating for the libs team since this general question is interesting for the API guidelines discussion: Can/should Debug impls expose internals in order to aid debugging?

**Comment by alexcrichton** [comment]
We discussed this at trigae today and concluded:

* We should implement `Debug` no matter what
* Exposing internal details is fine here
* Exposing *more* internals (calculated at runtime) would also be ok to get a better debug representation. Sort of like how `TcpStream` prints out the peer/local addrs.

Patches are of course welcome to help implement this!

**Comment by dtolnay** [comment]
I believe this impl has existed since the very beginning of std::time::Instant -- https://github.com/rust-lang/rust/pull/29894 contains `impl Debug for Instant`. This code is stable as of Rust 1.8.0:

```rust
fn main() {
    println!("{:?}", std::time::Instant::now());
}
```

The output is `Instant { tv_sec: 17586727, tv_nsec: 739140298 }` which seems to align with the discussion here.
