### ISSUE TITLE
Lifetime bound error that occurs for `String` but not `str`

### ISSUE THREAD

**Issue by Noctune** [rust-lang/rust#31898]
I'm getting a somewhat odd error for the following code. The lifetime bound error happens only for `String` and not for `str`. I'm really unsure whether this is my understanding of lifetimes that is incorrect or a bug in the compiler.

``` rust
fn main() {
    let doc = "<w>werd</w>".to_owned();

    //Remove this line and it does not work:
    let doc = &doc[..];

    let words = doc.match_indices("<w")
        .filter_map(|(i,_)|
            doc[i..].find(">").and_then(|a|
            doc[i..].find("</w>").map(|b|
            &doc[a + '>'.len_utf8() .. b])));

    for i in words {
        println!("{}", i);
    }
}
```

[Playground link](http://is.gd/HlX7Nz)

```
<anon>:10:39: 11:42 error: `*doc` does not live long enough
<anon>:10             doc[i..].find("</w>").map(|b|
<anon>:11             &doc[a + '>'.len_utf8() .. b])));
<anon>:11:46: 16:2 note: reference must be valid for the block suffix following statement 1 at 11:45...
<anon>:11             &doc[a + '>'.len_utf8() .. b])));
<anon>:12     
<anon>:13     for i in words {
<anon>:14         println!("{}", i);
<anon>:15     }
<anon>:16 }
<anon>:9:13: 11:44 note: ...but borrowed value is only valid for the method call at 9:12
<anon>: 9             doc[i..].find(">").and_then(|a|
<anon>:10             doc[i..].find("</w>").map(|b|
<anon>:11             &doc[a + '>'.len_utf8() .. b])));
error: aborting due to previous error
playpen: application terminated with error code 101
```

**Comment by bluss** [comment]
I think you have found the correct workaround for this. Another way to do it is `let doc = &doc;`

So, what sets the two cases apart? `&String` and `&str` that compile, those are simple `Copy`able references, in the other case `doc` is a `String`.

I think this means that the innermost closure will choose to take its captures as copies (copies of the references) instead of by reference.

**Comment by Noctune** [comment]
I have reduced it a bit:

```
fn main() {
    let v: Vec<usize> = Vec::new();
    let v = &v;
    let w = Some(1).and_then(|_| Some(1).map(|_| &v[..]));
}
```

The above stops working if you remove the `let v = &v` line. Weirdly, the following does not work in either case:

```
fn main() {
    let v: Vec<usize> = Vec::new();
    let v = &v;
    let w = Some(1).and_then(|_| Some(1).map(|_| &v));
}
```

Somehow `&v[...]` has a different lifetime bound than `&v`.

**Comment by Mark-Simulacrum** [comment]
The reduced example now works. I don't think this is really related specifically to `String` vs. `&str`, more so that closures can (and do) copy `Copy` types. With `String`, this isn't possible, so the lifetime of the reference (`&doc[a + '>'.len_utf8() .. b]`) isn't long enough--doc is presumably moved by-value into the closure and as such doesn't live past the iterator's definition, hence, the error.

I'm going to close this because I don't really think it's a bug, or at least not one specific to this case, and while I can't find a specific issue tracking this, I'm fairly certain it exists, so I'll close this.  The lifetime error here is correct, just confusing because closures aren't as explicit about their borrows and as such the diagnostics aren't as nice as in other places within Rust (though lifetime diagnostics in general usually aren't pleasant). If others disagree, please do reopen.
