### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by aseaday** [rust-lang/rust#31935]
commit 9c6a0088fbdae5a6554c39f8db9207c1b878eb05

```
In file included from /Users/bisunday/Source/rust-lang/src/rustllvm/ExecutionEngineWrapper.cpp:11:
/Users/bisunday/Source/rust-lang/src/rustllvm/rustllvm.h:11:10: fatal error: 'llvm/IR/IRBuilder.h' file not found
#include "llvm/IR/IRBuilder.h"
         ^
```
So how could I solve it.

**Comment by sanxiyn** [comment]
Are you passing `--llvm-root` option to `./configure`? If so, don't pass it.

**Comment by aseaday** [comment]
No, I don't pass it .

**Comment by sanxiyn** [comment]
How are you building it? `./configure; make`, as written in README, or something else? Also it would be helpful to have complete build output starting from `./configure`, not just last lines.

Also note that Rust needs internet connection to build at the moment. This is just a guess, but it seems possible some files are missing because they weren't downloaded because of network issues.

**Comment by aseaday** [comment]
I find the problem. Because I terminate build process before. And make clean didn't work well. Thank you !
