### ISSUE TITLE
To define in custom-allocators.md from which version system allocator used for dyn libs by default

### ISSUE THREAD

**Issue by andruhon** [rust-lang/rust#31956]
"Dynamic and static libraries, however, will use alloc_system by default."
It is not clear in this paragraph https://github.com/rust-lang/rust/blob/0672ed4e82abb562660c8a6d7183288c15e4526a/src/doc/book/custom-allocators.md#default-allocator was it always like that or it works like that after some particular version. 

(it seems to me that it is true from 1.6+)

**Comment by steveklabnik** [comment]
Sorry for such a late response to this! 

> was it always like that or it works like that after some particular version. 

In general, the docs for a specific version describe that version. We don't talk much about "from this version to that version" in docs, so you can assume it was from that version forward.

Anyway, since this was really a question, and because the book is being re-written, I'm going to give this one a close. Thanks!
