### ISSUE TITLE
bad error message defining a macro with invalid identifier

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#32026]
``` rust
macro_rules! 1 {}
```

says "expected item, found `macro_rules`" which is not helpful, doesn't even point at the ident which is the problem.

The analogous error message on `fn 1() {}` is much better.

**Comment by jonas-schievink** [comment]
The error is much better when inside a function:
```rust
fn main() {
    macro_rules! 5 {}
}
```
```
<anon>:2:18: 2:19 error: expected ident, found `5`
<anon>:2     macro_rules! 5 {}
                          ^
```

**Comment by birkenfeld** [comment]
This is because the parser looks ahead and wants to have the complete macro beginning - either `macroname! {` or `macroname! ident {`, see https://github.com/rust-lang/rust/blob/0f9ba992910b724bd198a196b5e408785911fdfc/src/libsyntax/parse/parser.rs#L6043

Would it be acceptable to make that function just look ahead one token to match `macroname!` and then commit to parsing a macro invocation?

**Comment by Mark-Simulacrum** [comment]
Today this gives the expected identifier outside a function as well; closing.

```
error: expected identifier, found `1`
 --> test.rs:1:14
  |
1 | macro_rules! 1 {}
  |              ^

error: aborting due to previous error(s)
```
