### ISSUE TITLE
Opportunistically name closures in the output binary

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#32087]
Currently, the symbol names for all closures are based on the containing function name, plus "closure".  In general this is the best that can be done, since closure expressions don't contain names.  However, it's fairly common for them to be immediately and unconditionally assigned to a variable:

```
let foo = |a| a;
```

It would be nice if rustc detected this case and included the variable name in the generated function name.

**Comment by Aatch** [comment]
I don't disagree with the idea, but I think the most common use of closures is actually passing them directly to a function: `opt.map(|a| a + 1)`, so that's something to keep in mind.

**Comment by Mark-Simulacrum** [comment]
Is this for debuginfo? In error messages `[closure@test.rs:2:21: 2:26]` is used, which seems accurate enough--in some ways, better than a name. I'm not sure how helpful encoding names into debuginfo or wherever is, anyway, since presumably the variable foo is encoded and has the type of the closure. Can someone explain what specifically is needed here?

**Comment by steveklabnik** [comment]
Triage: given Mark's last comment, and with no more details, I'm going to give this a close. Thanks!
