### ISSUE TITLE
rustdoc: generated documentation for a block-doc comment includes asterisks when paragraph spans multiple lines

### ISSUE THREAD

**Issue by insaneinside** [rust-lang/rust#32088]
From [a gist that mentions multiple issues](https://gist.github.com/insaneinside/9860327832794128e753):

``` rust
/*!  The generated documentation for a block-doc comment will include asterisks
 * when a paragraph spans multiple lines.
 *
 * Other problems follow.
 */
```

renders to
![Asterisks included](https://i.imgur.com/N8XYn2m.png)

The offending character is actually whatever rustdoc's heuristics decide is the fill-prefix terminator, i.e. not necessarily an asterisk.  Happens on non-outer-scope comments as well.

**Comment by mitaa** [comment]
Isn't that the expected behaviour?

A block-doc comment is written like `/*! ..... */` - the additional `*` on each line look nice for formatting but are actually part of the documentation text itself. AFAIK rustc/rustdoc doesn't handle "fill-prefix terminators" in doc-comments.

This seems like a feature request, which would, I think, rather need to be solved in libsyntax because rustdoc itself operates on already desugared doc-comments (`#[doc="..."]`).

**Comment by insaneinside** [comment]
OTOH, in the vast majority of languages that use C-style block-comments, doing this is common practice.  Rust is indeed its own language, but when appropriating constructs from other languages it's a good idea to consider the conventions that go along with those constructs.

**Comment by Arnavion** [comment]
Indeed, doc generators like JSDoc ignore leading asterisks in block comments.

It may not need to be solved in libsyntax. The desugared doc string still contains newlines, so rustdoc can know which `*` to ignore and which to keep. This is what JSDoc does too.

**Comment by GuillaumeGomez** [comment]
It's nice for formatting but I'd be more inclined to not change the behaviour in here.
