### ISSUE TITLE
mpsc::send returns error once, then success

### ISSUE THREAD

**Issue by jsgf** [rust-lang/rust#32114]
If you close the rx side of a channel pair before sending to it, then the first send will fail with a `SendError` as expected, but a second send will return `Ok(())`.

```rust
use std::sync::mpsc::{channel, SendError};

#[test]
fn doublesend() {
    let (tx, _) = channel();
    
    assert_eq!(tx.send(123), Ok(()));
    assert_eq!(tx.send(123), Err(SendError(123)));
    assert_eq!(tx.send(123), Err(SendError(123)));
}
```

Fails with:
> thread 'doublesend' panicked at 'assertion failed: `(left == right)` (left: `Err("SendError(..)")`, right: `Ok(())`)', <anon>:7

However, if something is successfully sent before the receiver is dropped (even if it never receives the value), then it works as expected:

```rust
use std::sync::mpsc::{channel, SendError};
use std::mem;

#[test]
fn doublesend() {
    let (tx, rx) = channel();
    
    assert_eq!(tx.send(123), Ok(()));
    mem::drop(rx);
    assert_eq!(tx.send(123), Err(SendError(123)));
    assert_eq!(tx.send(123), Err(SendError(123)));
}
```

**Comment by alexcrichton** [comment]
I may be a bit confused, but it looks like everything is working as intended here? In the first example the receiver is immediately dropped (binding via `_`), and the first `send` fails (line 7) with an error appropriately because there is no receiver to receive the message.

The second example also looks correct as when the first message is sent the receiver is still active (could possibly acquire the message), but afterwards it's guaranteed to never be received so the next two sends are errors.

**Comment by bluss** [comment]
The code here demonstrates the problem https://users.rust-lang.org/t/mpsc-sender-send-only-returns-senderror-once-then-succeeds/4894

**Comment by alexcrichton** [comment]
Aha! So to inline the problem:

```rust
use std::sync::mpsc::{channel, SendError};

fn main() {
    let (tx, _) = channel();

    let _ = tx.send(123);
    assert_eq!(tx.send(123), Err(SendError(123)));
}
```

Yes, this is indeed unexpected behavior! It's probably something to do with the upgrade logic in channels.

**Comment by apasel422** [comment]
I think the issue here is that `oneshot::Packet::send` [unconditionally sets the `state` field to `DATA`](https://github.com/rust-lang/rust/blob/b94b15852cd9b14160cce7f85f241691a72c18af/src/libstd/sync/mpsc/oneshot.rs#L109), even when the subsequent match indicates that the state was `DISCONNECTED`. This causes the first `send` to error correctly, but causes the second to succeed.
