### ISSUE TITLE
Broken links in BTreeSet struct documentation

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#32130]
There are broken links when looking at the `BTreeSet` structure. This happens because the structure can be viewed from two locations, both at varying depths of links so the relative links may or may not work:
- [`std::collections::BTreeSet`](http://doc.rust-lang.org/nightly/std/collections/struct.BTreeSet.html) - working
- [`std::collections::btree_set::BTreeSet`](http://doc.rust-lang.org/nightly/std/collections/btree_set/struct.BTreeSet.html) - not working

**Comment by mitaa** [comment]
The same problem also causes the link `[module-level documentation](index.html#insert-and-complex-keys)` on the [insert methods documentation][0] on [`BTreeSet`][btreeset], [`BTreeMap`][btreemap] and [`HashMap`][hashmap] to sometimes refer to the wrong module (the immediate one, instead of [std::collections][module-level-docs]).

[0]: https://doc.rust-lang.org/nightly/std/collections/hash_map/struct.HashMap.html#method.insert
[hashmap]: https://doc.rust-lang.org/nightly/std/collections/hash_map/struct.HashMap.html
[btreemap]: https://doc.rust-lang.org/nightly/std/collections/btree_map/struct.BTreeMap.html
[btreeset]: https://doc.rust-lang.org/nightly/std/collections/btree_set/struct.BTreeSet.html
[module-level-docs]: https://doc.rust-lang.org/nightly/std/collections/index.html#insert-and-complex-keys

**Comment by phungleson** [comment]
@alexcrichton is there anything left to be done here, i can help the rest

**Comment by alexcrichton** [comment]
@phungleson if you can delete [these lines](https://github.com/rust-lang/rust/blob/bae454edc5e18e81b831baf4a7647bf2dda620a8/src/tools/linkchecker/main.rs#L125-L131) and have this command work:

```
./x.py test src/tools/linkchecker
```

Then there's no more work to do! (other than deleting that block)

**Comment by phungleson** [comment]
Thanks @alexcrichton seems like I have to make some fixes

I got a lot of `broken link` after removing those lines lol

**Comment by phungleson** [comment]
While I am here, I wonder if I should format the docs here https://github.com/rust-lang/rust/blob/bae454edc5e18e81b831baf4a7647bf2dda620a8/src/libcollections/btree/map.rs to fit in 80 columns.

Currently it is quite hard to read properly.

![image](https://cloud.githubusercontent.com/assets/93457/22860937/3c7de6a2-f160-11e6-8de9-c6b2bb28e2d5.png)

**Comment by phungleson** [comment]
Sorry for my noop question, every time, I change something and run `./x.py test src/tools/linkchecker` the whole `rustc` get re-complied again and it took at least 15' to 30' to run the thing.

I wonder if there is any less painful way to make changes and test in rust?

**Comment by steveklabnik** [comment]
Hm, that seems bad; I was recently doing this, and it didn't have to do a
full recompile. Was more like 30 seconds each time. Wonder if you've hit a
rustbuild bug?

**Comment by alexcrichton** [comment]
@phungleson you may want to pass `--stage 0` as well, `--stage 2` is the default and goes all the way to the end of the compiler.

Alternatively if you're just changing documentation then after you modify a file you can just use `touch` to move its mtime back in time.

**Comment by phungleson** [comment]
Hey thanks guys, `--stage 0` is not super fast (5-10') but probably ok right now, have been looking into this for a while.

Wonder why `struct.BTreeMap.html` and similar files appear in 2 places? This is impossible to create correct relative links.

I think it is not fixed yet? and what is the correct place things should be?

Thanks

![image](https://cloud.githubusercontent.com/assets/93457/22971085/9782003c-f3c8-11e6-989d-548f58fe78f1.png)

**Comment by alexcrichton** [comment]
Oh yeah I don't think this is fixed yet, hence the bug :)

**Comment by phungleson** [comment]
@alexcrichton which one should we keep, `btree_map` or `btree/map` and do you know where in the code that decides where the files should go?

I can dig a bit but might be faster if you know where it is.

Thanks!

**Comment by alexcrichton** [comment]
Nah unfortunately the details here are pretty out of cache for me :(

**Comment by MaloJaffre** [comment]
This problem also occurs in compiler docs (now built in #46278), where `rustc_data_structures::sync::Lrc` and `rustc_data_structures::sync::RwLock` are aliases to `std` types.

**Comment by ehuss** [comment]
Reopening until the exclusions in the link checker can be removed.

**Comment by jyn514** [comment]
> Reopening until the exclusions in the link checker can be removed.

I wrote this in [a commit message](https://github.com/rust-lang/rust/pull/77253/commits/406584621a4e2d3752b2444c5bed2218447f0bfe) no one will read, so pasting here for visibility:

BTreeMap wants to link to the docs in std::collections, which are very detailed, and not alloc::collections, which is almost empty. But alloc is a dependency of std, so it's not possible to link to it across crates (https://github.com/rust-lang/rust/issues/74481). What we could do instead is have the same documentation in both `alloc::collections` and `std::collections`, so that BTree can link to the alloc version. However the docs for `collections` in turn link to `HashMap`, which are only in `std`. So one way or another, some of the links will be broken.

(I suggested a while ago making HashMap available in alloc, but there wasn't a clear consensus on how to do that: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Why.20is.20HashMap.20in.20std.20and.20not.20alloc.3F)

**Comment by jyn514** [comment]
Triage: this is *almost* working, these are the last broken links left in the standard library: https://github.com/rust-lang/rust/blob/010c2368fa33ef08df3080228498db8d2ba5a93b/src/tools/linkchecker/main.rs#L33-L40

**Comment by jyn514** [comment]
I'm going to mark this as a standard library bug; the rustdoc half of it is tracked at https://github.com/rust-lang/rust/issues/74481.

**Comment by Dylan-DPC** [comment]
Closing this as the exclusions are tracked in #74481
