### ISSUE TITLE
docs: style guide for builders still references `proc()`

### ISSUE THREAD

**Issue by Ryman** [rust-lang/rust#32224]
http://doc.rust-lang.org/nightly/style/ownership/builders.html#consuming-builders

**Comment by steveklabnik** [comment]
Yes, in general the style guide hasn't been touched since just before 1.0, I'm sure there are a few of these. It's why it's not linked anywhere.

**Comment by frewsxcv** [comment]
The style guide [was moved](https://github.com/rust-lang/rust/pull/35124) out of rust-lang/rust (this repository) some time ago to [rust-lang/rust-guidelines](https://github.com/rust-lang/rust-guidelines). Since then, despite the `prop()` call still existing in the guidelines, rust-lang/rust-guidelines [has been become discontinued](https://github.com/rust-lang/rust-guidelines/commit/8a34b0b98198ef335662852ae5163e22c8873150), so I'm going to close this issue as there's not any action to take for this.
