### ISSUE TITLE
Tracking issue for {Vec,String}::splice

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#32310]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1432.

First needs to be implemented, then needs to go through FCP!

**Comment by aturon** [comment]
There's a preliminary implementation [here](https://github.com/rust-lang/rust/pull/32355), which could easily be picked up and brought over the finish line!

**Comment by clarcharr** [comment]
Because this is implemented, is there anything blocking stabilisation?

**Comment by aturon** [comment]
@clarcharr Nope! I'll get the wheels in motion:

@rfcbot fcp merge

**Comment by dtolnay** [comment]
Why would you ever use the return value from String::splice?

1. The String and the replacement str are in scope (start of 'a and 'b).
2. Call `splice`, receive `Splice` struct.
3. The String is exclusively borrowed and unusable.
4. Process the replaced segment one char at a time.
5. Drop the `Splice` struct.
6. Drop the String and the replacement str (end of 'a and 'b, must happen after 5).

Given that 'a and 'b are required to outlive `Splice`, wouldn't it always be simpler and at least as efficient to do this?

1. The String and the replacement str are in scope (start of 'a and 'b).
2. Grab the soon replaced segment &s[range].
3. The String is shared borrowed but otherwise usable.
4. Process the soon replaced segment one char at a time or as an ordinary &str.
5. Call `splice` which eagerly does the replace and returns ().
6. Drop the String and the replacement str (end of 'a and 'b).

@rfcbot concern return value of String::splice

**Comment by dtolnay** [comment]
If IndexAssign (or IndexSet or whatever, https://github.com/rust-lang/rfcs/issues/997) existed today, would we be using that instead? Would we want both?

```rust
let mut s: String = /* ... */;
s[from..to] = "replacement";
```

@rfcbot concern IndexAssign

**Comment by clarcharr** [comment]
I will say that `splice` would still be useful for `Vec`, just not for `String` in that case, because `IndexAssign` still won't be as efficient.

Perhaps going forward the features for `Vec::splice` and `String::splice` could be split, allowing to stabilise the former will keeping the latter unstable?

**Comment by sfackler** [comment]
I'm on board with stabilizing the Vec method, but not String for the reasons mentioned above. I think `IndexSet` is far enough away that I'd be comfortable landing this and then deprecating it in if/when that stabilizes.

**Comment by dtolnay** [comment]
I agree that IndexSet is too far away to block this.

@rfcbot resolved IndexAssign

**Comment by dtolnay** [comment]
I filed #44038 to follow up on changing the signature of String::splice.

@rfcbot resolved return value of String::splice

**Comment by dtolnay** [comment]
The following applies only to Vec::splice.

@rfcbot reviewed

**Comment by kennytm** [comment]
IMO if `String::splice` is not returning the previous data, the method shouldn't be really called `splice`.

**Comment by dtolnay** [comment]
The FCP above applies to Vec::splice. I filed #44643 as the tracking issue for String::splice which remains unstable with its new signature.
