### ISSUE TITLE
Tracking issue for Range*::contains

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#32311]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1434.

Unresolved questions:
 - What to do about `Wrapping` ranges.

Implementation work:
 - Heterogeneous comparisons
 - Should take a reference

**Comment by Ticki** [comment]
I am unsure what part of the rfc was accepted. Is the `contains` method for iterators accepted?

**Comment by alexcrichton** [comment]
The accepted portion of an RFC is the [detailed design](https://github.com/rust-lang/rfcs/blob/master/text/1434-contains-method-for-ranges.md#detailed-design), which in this case only deals with ranges, not iterators.

**Comment by Ticki** [comment]
Well, okay. Fine.

**Comment by Ticki** [comment]
It is in fact also compatible with future extension to iterators.

**Comment by durka** [comment]
Should this be implemented for (unstable) `RangeInclusive` and `RangeToInclusive` as well?

**Comment by alexcrichton** [comment]
For consistency, yeah, seems prudent.

**Comment by Kimundi** [comment]
Hm, I just used this and expected it to take `&Idx` instead of `Idx`, in case you have a range of non-copyable types.

Looking back the RFC, it does not seem to consider this case - was there any discussion for this possibility?

**Comment by josephDunne** [comment]
Hi, This RFC doesn't address `Wrapping` numbers. Is this intended? For example this gist returns false which is not intuitive (albeit correct with regards to `PartialOrd`)

```
#![feature(range_contains)]
use std::ops::Range;
use std::num::Wrapping;
use std::u32;

fn main() {
    let r1: Range<Wrapping<u32>> = Range{ start: Wrapping((u32::MAX - 100)), end: Wrapping(100) };
    println!("{}", r1.contains(Wrapping(u32::MAX)));
}
```
```
false
Program ended.
```

**Comment by ExpHP** [comment]
Hm, my elation turned into sadness today when I added a `contains` method to my own iterator extension trait, only to find that _it somehow shadowed the inherent method on Range:_

    src/grid/hexagonal.rs:63:43: 63:44 note: expected type `&usize` 
    src/grid/hexagonal.rs:63:43: 63:44 note:    found type `usize` 
    src/grid/hexagonal.rs:63:43: 63:44 note: expected &-ptr, found usize 
    src/grid/hexagonal.rs:63 		debug_assert!((0..self.height).contains(r));
                                                                            ^

I can only imagine that method resolution works this way for the sake of backwards compatibility, but... yikes!

Since this change is "compatible with future extension to iterators," I take it that there is a way to implement an `Iterator::contains` which accepts either a `Self::Item` or `&Self::Item`?  If so, then I am glad that I was unable to come up with that signature when I wrote my own!

**Comment by alexcrichton** [comment]
@rfcbot fcp merge 

Seem like nifty methods to stabilize!

**Comment by brson** [comment]
@rfcbot concern previous-questions

I see three previous comments asking about the API here. I don't know anything about this API but it's not obvious it's ready for stabilization.

**Comment by alexcrichton** [comment]
@rfcbot fcp cancel

Ok, sounds like these aren't ready yet.

**Comment by scottmcm** [comment]
A thought on `contains`: should it allow heterogeneous types, if comparable? (I didn't see a discussion in the RFC.)  Like
```
impl<Idx, T> Range<Idx> where T:PartialOrd<Idx>, Idx:PartialOrd<T> {
    pub fn contains(&self, item: T) -> bool {
        (self.start <= item) && (item < self.end)
    }
}
```
So it's totally fine if Idx=T (the two constraints collapse to the current one, and a caller could just require Idx:PartialOrd), but would allow checking a BigRational in a Range<BigInteger> or similar, should they have comparisons defined, without needing to convert one to the other.

**Comment by regexident** [comment]
Any status update on this?

**Comment by Kixunil** [comment]
Ping?

**Comment by alexcrichton** [comment]
The FCP for merge was canceled due to unresolved questions, and it looks like those unresolved questions have not been resolved.

**Comment by regexident** [comment]
@alexcrichton do you happen to have a summary of/link to those unresolved questions by chance?

**Comment by Kixunil** [comment]
The RFC suggests using a trait. I find it nicer. I'd also like something like [what I did recently](https://github.com/Kixunil/fast_escape/blob/master/src/lib.rs#L9).

**Comment by alexcrichton** [comment]
* [Should this take references?](https://github.com/rust-lang/rust/issues/32311#issuecomment-207033015)
* [Should this work with `Wrapping`?](https://github.com/rust-lang/rust/issues/32311#issuecomment-231127364)
* [Do custom types work](https://github.com/rust-lang/rust/issues/32311#issuecomment-238651983)

**Comment by lukaramu** [comment]
With the `RangeArgument` (soon to be `RangeBounds`?) trait nearing stabilization (from what I can tell) (#30877), I don't think this should be stabilized in its current form (even if the other questions are resolved):

All `Range*` structs but `RangeFull` have a `contains` method (and `RangeFull` could (or should?) have a trivial one added, anyway). It seems rather unfortunate to implement something taking a `RangeArgument`, wanting to use `contains`, and then realizing/remembering that it's a method on the `Range*` structs and not on the trait. This is especially unfortunate since you can implement `contains` using just `RangeArgument::start` and `RangeArgument::end`.

If I were to start from scratch, a `Contains<T>` trait (implied by `RangeArgument`) would seem like a good solution to me (especially since other types like `str`, slices, and collections also have `contains` methods). However, I am not sure if that would be doable with regard to stability (since adding it without implementing it for other types with stable `contains` methods seems more confusing than the current situation with `Range*`).

As a (more realistic?) alternative, `Range*::contains` could be moved to `RangeArgument` as a provided method, although I'm not sure how desirable that is if we'd ever want a proper `Contains` trait. I'd still prefer it over the status quo though.

I'm sure there are other ways, too.

**Comment by varkor** [comment]
Just regarding the questions about the current implementation:
1. I would definitely expect `contains` to take a reference — even aside from the issue non-copyable types, this is [what slice::contains](https://doc.rust-lang.org/std/primitive.slice.html#method.contains) does, and we'd expect these to act consistently.
2. Similarly, from a usability standpoint, considering that heterogenous comparisons [are being considered for `slice::contains`](https://github.com/rust-lang/rust/pull/46934) barring compatibility issues, it makes sense to also support them for `Range::contains`.
3. The `Wrapping` behaviour is clearly incorrect. The range should be inverted if `start > end`.

I'd suggest the most reasonable implementation would be something like:
```rust
impl<Idx> Range<Idx> {
    pub fn contains<T>(&self, item: &T) -> bool
            where Idx: PartialOrd, Idx: PartialOrd<T> {
        if self.start <= self.end {
            self.start <= *item && self.end > *item
        } else {
            self.start <= *item || self.end > *item
        }
    }
}
```

1 is going to break existing uses; 2 should be implementable without breaking anything; 3 changes behaviour, so would be a breaking change.

As the current implementation falls short of the expected behaviour, it seems to me like this is a change worth making.

**Comment by varkor** [comment]
Though I still feel it's better to handle the `end < start` case as it's more intuitive, technically this isn't even valid for the semantics of `Range`, which require that any `x` in range satisfies `start <= x < end`. This seems more of a problem with `Wrapping`, whose ordering is unintuitive (and arguably incorrect).

**Comment by Riamse** [comment]
It would be nice if you could make it a trait instead of a directly implemented method so that you can see if a range contains a number without having to worry about whether it's a RangeFull, Range, RangeFrom, etc. It would enable you to do something like

```rust
fn pi_in_range<T: ContainRange>(range: T) -> bool {
    range.contains(3.141592653589793238462643383)
}

// ...

assert!(pi_in_range(0.0 .. 10.0);
assert!(pi_in_range(..10.0);
assert!(!pi_in_range(10.0..);
assert!(pi_in_range(..);
```

**Comment by smmalis37** [comment]
I'd like to second @lukaramu's and others' comments above, I really think this should be moved to be a trait method on RangeArgument instead of implemented on each range type exclusively.

**Comment by Kixunil** [comment]
@lukaramu why you don't believe `Contains<T>` implied by `RangeBounds` wouldn't be good idea? I would love to see it implemented for sets (`HashSet` and `BtreeSets`). I'd agree that implementing it for slices and non-set collections would be weird.

**Comment by smmalis37** [comment]
The two Implementation Work items have now been done. The question about Wrapping types still remains.

**Comment by smmalis37** [comment]
My personal opinion on the question of Wrapping types: If you look at [the new contains implementation](https://github.com/rust-lang/rust/blob/49317cd511fbb60178bd5122e484609568938468/src/libcore/ops/range.rs#L617) it's hard to argue that it could be incorrect in some way. It seems completely reasonable to say that a range contains something iff that something is greater than the start and less than the end. If the Wrapping types don't work within these guidelines that feels to me more like a bug in their PartialOrd implementation.

**Comment by mbrubeck** [comment]
I'd like to suggest this for stabilization.

I agree with the previous comment that the current implementation is fine for `Wrapping` numbers. `Wrapping` has always meant "wraps on arithmethic overflow," and has never had any special effect on ordering or comparisons.

**Comment by mbrubeck** [comment]
cc @SimonSapin

**Comment by SimonSapin** [comment]
The comments above on `Wrapping` sound good to me. Let’s stabilize as-in

@rfcbot fcp merge
