### ISSUE TITLE
we should ship something that draws the module tree

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#32380]
People get confused about the module system, and other people say it's very simple so it can't possibly be confusing.

It's probably true that it's very simple but at the same time it seems to be non-intuitive to a lot of people. I think it would be easier to wrap one's head around how modules work if we had a tool, probably a flag to rustc or something, that gave a visual representation of the module tree of the current crate. It'd make it easy to compare one's mental image of the module structure with rustc's idea of it, and get feedback on experimentation with the module structure more immediately than "now something else is broken!"

**Comment by jonas-schievink** [comment]
Maybe we should pursue better diagnostics (they can be really hard to understand - we need more and more accurate "did you mean"s)

**Comment by Futile** [comment]
Note that the book also uses simple trees to visualize module trees (see [this chapter](https://doc.rust-lang.org/book/crates-and-modules.html),) so the idea definitely has precedent.

**Comment by jonas-schievink** [comment]
Sure, I don't see why we can't do both. I just kinda doubt many people will know that this exists, and even when they do it's likely that they bail out with "ugh the module system sucks" instead of investing time to use this tool. When rustc tells them exactly what's wrong and how to fix it they barely have any work left to do :)

For example, we could try to interpret an unresolved `use` as a relative path and tell the user ``did you mean `use self::XXX`?`` and ``note: `use` paths are absolute, not relative to the module they're used in``

**Comment by nodakai** [comment]
IDEs in general should be very helpful here

[![RustDT auto completion](https://raw.githubusercontent.com/RustDT/RustDT/master/documentation/screenshots/Feature_ContentAssist.png)](https://github.com/RustDT/RustDT/blob/latest/documentation/Features.md#features)

though this screenshot doesn't directly address the OP's issue.

**Comment by steveklabnik** [comment]
https://crates.io/crates/cargo-modules is wondeful, and I'd like to ship it by default eventually. However, this feels more like a Cargo bug.

**Comment by Mark-Simulacrum** [comment]
Yes, I'm going to close this in favor of a Cargo bug if you'd like to pursue this.

**Comment by ben0x539** [comment]
nah thank you im good, not sure what cargo has to do with modules
