### ISSUE TITLE
rustdoc should have a better way to distinguish structs/traits/enums than font colors

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#32473]
Vermilion for structs looks like an alert.  Such a coloring is better suited to [un]stability/deprecation marks. (_cf._ #24617 )

Also, I'm no expert but I think relying on colors can be bad for accessibility:
[![simulated illustration of color-blindness](http://bigsquare.co.uk/wp-content/uploads/2013/01/colour-blindness-types.jpg)](http://bigsquare.co.uk/colour-accessibility/)

Random ideas:
- Overline for traits and underline for structs... Well, this is a terrible idea but it's just a starting point.
- [Javadoc](https://docs.oracle.com/javase/8/docs/api/) has tooltips (`title` attribute) like "interface in java.util" for `List` or "type parameter in LinkedList" for `E`
- [Use advanced CSS such as `::after` and `content` to insert texts and/or icons](http://www.w3schools.com/cssref/tryit.asp?filename=trycss_sel_after)
- Give up the idea of mimicking a valid Rust code and write out `struct Vec<T>`, _etc._ everywhere

**Comment by steveklabnik** [comment]
Triage: with no other comments since 2016, I don't think that this issue is really serving a purpose. We *could* pursue other ways of doing this, but there doesn't seem to be a lot of demand. We've tweaked the colors of rustdoc numerous times for the color-blindness issue since then as well.

If you'd still like to pursue this, I'd suggest talking to @rust-lang/rustdoc via discord to come up with a plan. Thanks!
