### ISSUE TITLE
How to treat imports with empty import list `use foo::{};`?

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#32524]
First of all, these imports are not something practically valuable, so the choice should probably be made based on the amount of code it will allow to remove from rustc.

1) Desugar `use prefix::{a, b, ....};` into `use prefix::a; use prefix::b; ....`. Therefore `use prefix::{};` is desugared into nothing. The `prefix` is not even resolved and can contain arbitrary non-existent or private or unstable paths - anything used in this prefix is harmless because it effectively doesn't exist.
The desugaring should probably be done when AST is lowered to HIR.

2) Prohibit such imports. They are totally useless in manually written code, but can be generated as edge cases by macros. However macro uses generating empty import are probably useless too.

3) Resolve the `prefix` and check it for name resolution errors, privacy, etc. There's some buggy piece of code in `rustc_resolve` doing this - https://github.com/rust-lang/rust/blob/master/src/librustc_resolve/lib.rs#L1722 and some other extra code in other visitors, and I'd like to get rid of it (that's why I created this issue).

cc @jseyfried @nikomatsakis

**Comment by jseyfried** [comment]
@petrochenkov 
I think we treat empty import lists like empty glob imports -- we should continue allowing them but they should be an unused import warning (currently, there is no warning).

I don't think it would be a good idea to desugar import lists before import resolution since this would make it much harder to improve the diagnostics for when the module part of the path is unresolved:
```rust
use foo::{a, b, c}; // We currently report that `foo` is unresolved three times; we should only report this once.
```

I think the cleanest way to fix these diagnostics and remove the buggy code you referenced is to change `ImportDirective` to represent import lists as well as single imports and globs.

**Comment by petrochenkov** [comment]
It seems like the variant 3 was chosen after all, the buggy code is fixed and tested now.
