### ISSUE TITLE
Implement `append` for `BinaryHeap`

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#32526]
This can be done in `O(n + m)` time by appending the underlying vectors and then using the build heap algorithm in the `From<Vec<T>>` impl. Note that in some circumstances this will perform worse than repeatedly `push`ing (as is done in `h1.extend(h2)`), because the time complexity of that approach is `O(m log (m + n))`. In both approaches, `append` should ensure that the larger of the two heaps acts as the "destination" of the merge in order to move as few elements as possible.

`append` should use a heuristic to determine which approach to take. This should be based on the sizes of the two heaps, but may also incorporate the vectors' capacities.

Pseudo-code:

```rust
use std::mem::swap;

fn shouldMergeWithBuildHeap<T>(v1: &Vec<T>, v2: &Vec<T>) -> bool { ... }

impl<T: Ord> BinaryHeap<T> {
    pub fn append(&self, other: &mut Self) {
        if other.is_empty() {
            return;
        }

        if self.is_empty() {
            swap(self, other);
            return;
        }

        if self.len() < other.len() {
            swap(self, other);
        }

        if shouldMergeWithBuildHeap(&self.data, &other.data) {
            self.data.append(&mut other.data.append);
            self.build_heap();
        } else {
            self.extend(other.drain());
        }
    }

    fn build_heap(&mut self) {
        let mut n = self.len() / 2;
        while n > 0 {
            n -= 1;
            self.sift_down(n);
        }
    }
}
```

For now, a simple version that just `extend`s the smaller one into the larger one could suffice:

```rust
impl<T: Ord> BinaryHeap<T> {
    pub fn append(&self, other: &mut Self) {
        if other.is_empty() {
            return;
        }

        if self.is_empty() {
            swap(self, other);
            return;
        }

        if self.len() < other.len() {
            swap(self, other);
        }

        self.extend(other.drain());
    }
}
```

**Comment by xosmig** [comment]
Hello. I think, it's better to add the `extend_from_slice` method first and call it from the `append` method. I'd like to perform it.

**Comment by apasel422** [comment]
@xosmig Cool. Feel free to submit a PR!

**Comment by alexcrichton** [comment]
🔔 This issue is now entering its **final comment period** for stabilization 🔔 

The libs team was unfortunately a little late on stabilizations this cycle, but we're thinking of probably doing a backport of stabilizations partway through the beta cycle. This API also follows existing conventions so should be an easy stabilization!

**Comment by alexcrichton** [comment]
The libs team discussed this issue during triage yesterday and the decision was to **stabilize**. We realize that the FCP for this issue was pretty short, however, so please comment with any objections you might have! We're very willing to backport an un-stabilization for the few APIs we have this cycle.
