### ISSUE TITLE
provide better diagnostic for forgotten semicolon token

### ISSUE THREAD

**Issue by bungcip** [rust-lang/rust#32540]
this code

```
fn main(){
    let value = 20;
    let m = match value {
        20 => true,
        40 => false,
        _ => false
    }

    println!("{}", m);
}
```

give this error message:

```
C:\depot>rustc ex.rs
ex.rs:9:5: 9:12 error: expected one of `.`, `;`, `?`, or an operator, found `println`
ex.rs:9     println!("{}", m);
            ^~~~~~~
error: aborting due to previous error
```

ideally, the error is something like this:

```
C:\depot>rustc ex.rs
ex.rs:7:5: 7:12 error: expected one of `.`, `;`, `?`, or an operator after '}' token
ex.rs:7     }
            ^~
error: aborting due to previous error
```

**Comment by jonas-schievink** [comment]
I'm curious as to why this isn't accepted. Removing the `let m =` makes it parse. Since `match`, similarly to `if`, is one of the expressions that can be used as a statement without being followed by a semicolon, it shouldn't cause many issues if this would be accepted, too (after a corresponding RFC, of course).
