### ISSUE TITLE
Document minimum precision guarantees for the various std::time APIs

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#32626]
https://github.com/rust-lang/rust/pull/29894 talks about what it uses to query time on the various platforms, but that is an implementation detail.

The API documentation should define minimum precision guarantees for these APIs, so the user can make an informed decision whether using these APIs will provide sufficient precision for their use case on all supported platforms.

For example, if a user wanted to use these APIs to limit framerate in a video game, second precision wouldn't cut it, but millisecond precision should be sufficient for most cases, so if these APIs guarantee at least millisecond precision, then they can be used for this purpose.

**Comment by sfackler** [comment]
Should we guarantee precision or document which system APIs these things use?

**Comment by durka** [comment]
I definitely agree this should be documented, at least for major platforms. If it's not documented, all you can do is test the precision, but then you have to make assumptions about future systems.

If we guarantee a precision, that leaves open the question of what to do for a system that can't support such a precision. Panic?

**Comment by mbrubeck** [comment]
We already can't guarantee any particular precision.  Linux for example runs on processors with a wide variety of timing hardware, with all sorts of different precisions.

**Comment by durka** [comment]
Perhaps we need another API to query the precision.

**Comment by crumblingstatue** [comment]
If it's not possible to provide any guarantees, we should at least document the precision for major supported platforms, and explicitly state that there are no guarantees for other platforms.

**Comment by nodakai** [comment]
@crumblingstatue Does "tier-1 platform" include guest Linux on VMWare? Its clock is known to be freaky.

POSIX has [`clock_getres(3)`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/clock_getres.html) and Win32 has [`QueryPerformanceFrequency`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644905(v=vs.85).aspx) which return the (finest) unit of time supported by the system, but they don't guarantee measurements are that accurate. When OSs don't guarantee anything, what can Rust do? Perhaps we can just add a wrapper of these query APIs if that is convenient to somebody.

**Comment by crumblingstatue** [comment]
@nodakai Hrrm. If truly nothing else can be done, then at least let's document the platform APIs we use for at least the major platforms, so the user doesn't have to look them up in the RFCs. That's at least more information about the precision than nothing at all.

**Comment by crumblingstatue** [comment]
Do we aim for at least *some* level of precision where possible? What is the purpose of `Instant`? Does it aim to be suitable for any kind of use? Obviously, if it doesn't aim to be useful for anything, then it's useless.

**Comment by sfackler** [comment]
We aim for the highest precision available on whatever platform you're running on.

**Comment by crumblingstatue** [comment]
@sfackler Then we could put that into the documentation. That's useful information.

**Comment by nodakai** [comment]
I tried adding `Duration::resolution()` etc to libstd, only to find out the libc crate lacks `clock_getres(3)`...

**Comment by steveklabnik** [comment]
Triage: no changes I'm aware of.

**Comment by DevQps** [comment]
@bearcage I see that you mentioned this issue in your PR! You're still interested in picking this up?

**Comment by DevQps** [comment]
@alexcrichton @aturon @dtolnay @KodrAus @SimonSapin @withoutboats @sfackler @Kimundi @BurntSushi @Amanieu Does the Library Team want to establish a minimum guaranteed precision for std::time APIs? Or desires to have platform-specific API calls being mentioned? Otherwise we can close this issue!

I personally think that listing platform-specific APIs is not a good idea since they might change over time and are a hassle to maintain for the docs-team. I don't really think a minimum precision is required either, but can be added if desired.

Ps. Right now I pinged everyone of the libs team (I heard team pings don't work anymore), is there any convention to follow when wanting to get in contact with the libs team on a certain issue?

**Comment by alexcrichton** [comment]
I think at the bare minimum precision with respect to reading time from the system should probably documented (or rather I don't think anyone would object to that). For example Windows you get something like 10ns precision between taking timing samples whereas on Linux it's 1ns (IIRC). 

The precision of `Duration` will always be to the nanosecond.

I think one of the main remaining questions is what the precision of `Instant + Duration` is. Currently `Instant` has a platform-specific representation which means that it has different precisions on different platforms, but this has been considered a bug before by a few issues here and there. I do not think we should document and/or try to guarantee the precision of `Instant` while we're figuring out these bugs. We don't want the documentation to tie our hands one way or another.

**Comment by DevQps** [comment]
@alexcrichton Thanks for your response! So if I understood you correctly the task for this issue is:

Figure out the underlying API calls for [SystemTime](https://doc.rust-lang.org/std/time/struct.SystemTime.html) and documenting the precision for each platform. Do I understand this correctly? I am currently abroad, but I can probably create a PR for this once I get home.

I see that the current [std::time::Duration](https://doc.rust-lang.org/std/time/struct.Duration.html) page already states that it operates on nanosecond precision, so we don't have to change it's documentation.

**Comment by alexcrichton** [comment]
I believe so, yes. As usual though the documentation needs to be careful to indicate what's captured in this thread about how we call some APIs, but those APIs aren't guaranteed to be called. Additionally system configuration may mean the API calls are less precise. (etc, etc)
