### ISSUE TITLE
Macros which pass around types won't compile.

### ISSUE THREAD

**Issue by calebmer** [rust-lang/rust#32657]
I have a trait for my tests, `Context`, which has a static method `get_fixtures` that returns an associated type. When I try to pass implementors of `Context` into my macro and try call static methods, it fails with a syntax error. See the pen below for an exact error.

[Here is](https://play.rust-lang.org/?gist=17a3e311cba498c1b7c031639106f7c2&version=stable) the code I expect to work. The code was also pasted below.

``` rust
trait Trait {
    fn func() -> u32;
}

struct Struct;

impl Trait for Struct {
    fn func() -> u32 {
        5
    }
}

macro_rules! test {
    ($impler:ty) => {
        #[test]
        fn test_true() {
            assert!(true);
        }

        #[test]
        fn test_func() {
            assert_eq!($impler::func(), 5);
        }
    }
}

test!(Struct);
```

**Comment by jonas-schievink** [comment]
You can make it work (well, it fails with a different error because `Struct` isn't defined) by using UFCS (universal function call syntax):

    assert_eq!(<$impler as Trait>::func(), 5);

I'm guessing this is just another side effect of the weird macro implementation. The parser tries to parse an expression but finds a quoted type, which confuses it.

By using UFCS, we say "the method `func` is defined in an `impl` of trait `Trait` for the type `$impler`". Its syntax expects a type after the `<`, and everything works.

I'm guessing you meant to use `Tests` instead of `Struct` at the bottom (it works when I change it).

**Comment by calebmer** [comment]
@jonas-schievink Thanks, that helps and I updated the incorrect names (my bad :blush:). Should I keep this open so the side effect can be fixed?

**Comment by jonas-schievink** [comment]
@calebmer I don't think this will ever get fixed in the current macro system, but you can leave it open if you want (there are numerous open issues like this, but I don't recall a direct duplicate)

**Comment by Mark-Simulacrum** [comment]
The example compiles with current Rust. There's some mention of side effects, but I don't quite follow that. Since the example compiles, I'm going to close.
