### ISSUE TITLE
Automatically insert `\\?\` where needed on Windows

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#32689]
`libstd` should automatically insert `\\?\` when necessary.  The path must be canonicalized first; this can be done using the Windows API function `GetFullPathNameW`.

A necessary condition for needing to call `GetFullPathNameW` is that the path does not begin with `\\?\`.  Afterwards, if the path begins with `\\` but not `\\?\`, the `\\` must be replaced with `\\?\UNC\`.

**Comment by retep998** [comment]
There has already been a desire for something like this, and even [an attempt](https://github.com/rust-lang/rust/pull/27916) at implementing this. However, doing something like this is somewhat complicated due to all [the weird edge cases in how paths are handled on Windows](http://googleprojectzero.blogspot.com/2016/02/the-definitive-guide-on-win32-to-nt.html). The current recommended solution is to create an external crate that handles normalizing paths and once all the kinks have been worked out of it and all the edge cases tested, then we will be able to consider whether to add something like that to libstd.

**Comment by dgrunwald** [comment]
The documentation says that for long filenames, you need to prepend `\\?\` before you're allowed to call `GetFullPathNameW`. So it seems to me that we'd have to re-implement that function without that limitation.

**Comment by retep998** [comment]
@dgrunwald Which is exactly why it is so complicated because that means we have to handle all the weird edge cases ourselves! Hence the desire to have it worked out in an external crate first.

**Comment by nodakai** [comment]
It would be great if we could *properly* implement such a feature in Rust stdlib, but the benefit might be marginal because many Windows tools either don't understand `\\?\`-prefixed paths at all, or cannot properly handle those paths enabled by the `\\?\` prefix, including those longer than `MAX_PATH`.
- The (Windows-standard) file open dialog from notepad.exe can suggest me what files are available under a `\\?\`-prefixed path but notepad.exe itself cannot open it.
- When your cwd is as long as ~250 bytes, Mingw `rustc.exe` can still call `cc.exe` to produce `yourcode.metadata.o` but `rustc.exe` cannot remove it. More oddities can happen regarding the intereaction with the child `cc.exe` processs. Lengthy file names from `make check` taught me the lesson :-(
- `System32\msvcrt.dll` has a fundamental bug with the `\\?\` prefix and Mingw `gcc.exe` is affected by it: https://github.com/rust-lang/rust/blob/master/src/librustc/util/fs.rs
- `SetCurrentDirectory()` doesn't accept paths longer than `MAX_PATH` regardless of the `\\?\` prefix, or paths with the `\\?\` prefix but without a trailing `\`.

**Comment by drbo** [comment]
@nodakai That is still not a good enough reason to implement the best support possible.  Don't take my word for it &ndash; the CoreCLR team had the same decision!  See [this CoreFX issue][1] which was fixed using the same technique I am proposing, and was the inspiration for my suggestion.

[1]: https://github.com/dotnet/corefx/issues/645

**Comment by drbo** [comment]
@dgrunwald This is false.  GetFullPathNameW [does not care][1] about `MAX_PATH`, and since CoreFX ,&ndash; and, through shared code, future versions of the full .NET Framework &ndash; relies on this behavior, it is not likely to change.

[1]: https://github.com/dotnet/corefx/issues/645#issuecomment-73398699

**Comment by retep998** [comment]
I did a quick test and `GetFullPathNameW` does indeed work fine when supplied with paths that are longer than `MAX_PATH`. Therefore I would feel confident in having libstd automatically invoke `GetFullPathNameW` on any non-verbatim paths that are over `MAX_PATH` and add the verbatim prefix before passing the path to any OS functions.

**Comment by DemiMarie** [comment]
Should I try to implement this?

**Comment by retep998** [comment]
@DemiMarie I don't see why not. Feel free to give it a shot.

**Comment by DemiMarie** [comment]
I just realized a problem: `GetFullPathName` has undefined behavior if it is passed a relative path name and another thread is concurrently calling `SetCurrentDirectory` (data race on the current directory).  So does every other Windows API function that takes a relative path name.

This means that Rust must either

- use its own version of the current directory, with proper synchronization
- make all functions that take relative paths `unsafe` to call.

Indeed, the MSDN documentation states that multithreaded programs and all shared libraries should not use relative path names at all.  Presumably, such code should fail if given a relative path name.  MSDN says that relative paths provided by the user should be converted to absolute paths while the program is still single-threaded.

On the other hand, CoreFX _does_ call this function, so I guess it is okay.

**Comment by retep998** [comment]
@DemiMarie What do you mean by undefined behavior? The way it is implemented, all access to the current directory goes through a critical section, specifically `FastPebLock`. Memory unsafe data races do not occur. The reason it is recommended not to use it is because if you set the current directory and intend to do some stuff in that given directory, another thread might come along and change it on you causing your code to behave incorrectly.

**Comment by DemiMarie** [comment]
Sorry, I did not know that.  The MSDN docs seemed to say otherwise.

**Comment by Yomodo** [comment]
On Windows platform, [AlphaFS](https://github.com/alphaleonis/AlphaFS) can help you out.

**Comment by steveklabnik** [comment]
Triage: no changes that I'm aware of
