### ISSUE TITLE
Cross-platform support for specifying owner vs other permissions

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#32690]
It should be possible to specify cross-platform whether a file or directory is only readable (resp. writable) by the current user and the system administrator, or if other users can modify it.  In particular, it should be easy to determine if both a file and all containing directories cannot be written to by any user other than the current user and the system administrator.

**Comment by retep998** [comment]
libstd is avoiding implementing something like this due to questions about how the API should look, along with just how complicated it would be to implement something like this, especially cross platform. At the moment the recommended solution is to create an external crate with the functionality you need, and if it turns out you can get a nice cross platform API that works well, then perhaps an RFC can be in order to make it a rust-lang crate or even maybe integrate it into libstd.

**Comment by dtolnay** [comment]
I agree, a robust implementation on crates.io followed by an [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md) would be the best way to make this happen.
