### ISSUE TITLE
Checked methods on integers should return Result

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#32694]
The `checked_*` methods in primitive integers should return `Result` so they are usable with `?`.

Tag with rust-2-breakage-wishlist

**Comment by bstrie** [comment]
As noted on IRC, there has been some existing desire to make `?` work with `Option` as well, which would achieve this without any breakage.

**Comment by Zoxc** [comment]
@bstrie That wouldn't make it possible to distinguish between different `None` error cases. Like integer overflow, or a value missing from a `HashMap`.

**Comment by timvermeulen** [comment]
@Zoxc Then you could also argue that no API should return an `Option` ever. Having this return a `Result` isn't a silver bullet anyway, because the user may still want to deal with overflow errors in different ways depending on the context.

I think the use of `Option` here is fine, and if the user of the API wants to distinguish between different `None` values they can always do something like
```rust
let c = a.checked_sub(b).ok_or(SomeError)?;
```
