### ISSUE TITLE
Superfluous error message for a private `pub use`

### ISSUE THREAD

**Issue by bfops** [rust-lang/rust#32708]
This causes an error:

```
mod foo {}

mod bar {
  pub use foo; // error: `foo` is private, and cannot be reexported
}
```

Since `foo` is no more accessible than it was before, this doesn't seem like an actual instance of [E0365](https://doc.rust-lang.org/error-index.html#E0365).

**Comment by jonas-schievink** [comment]
I think this is intentional, but a better error message (maybe an additional note or help) seems useful since this often confuses people

**Comment by cgaebel** [comment]
I want to use this to refer to `f` and g as `mod1::f`, `mod1::g` in my crate, but export them as `mod2::f` and `mod2::g` for external use.

**Comment by petrochenkov** [comment]
Long story short: 1) this works as intended, because reasons 2) wait for an implementation of RFC 1422 and write
```
mod foo {}

mod bar {
  pub(super) use foo;
}
```

Links:
https://github.com/rust-lang/rfcs/pull/136
https://github.com/rust-lang/rfcs/pull/200
https://github.com/rust-lang/meeting-minutes/blob/master/weekly-meetings/2014-09-16.md#rfc-public-items
https://github.com/rust-lang/rust/issues/28450
https://github.com/rust-lang/rfcs/pull/1422
