### ISSUE TITLE
Clarify the distinction between str and &str in the book

### ISSUE THREAD

**Issue by groksteve** [rust-lang/rust#32736]
Within the [Strings](https://doc.rust-lang.org/book/strings.html) section in the book there is no clear distinction between `str` and `&str` which causes some confusion further in when it discusses Deref coercions.

The example code here:
```rust
let addr_string = "192.168.0.1:3000".to_string();
TcpStream::connect(&*addr_string); // convert addr_string to &str
```
Fails to mention why we deref `addr_string` then take a reference of the returned `str` value (combining the two operators `&*`).

**Comment by steveklabnik** [comment]
I am not making major changes to the book anymore, or rather, I am doing a second draft. It focuses _extensively_ on `String` vs `&str`, as a means of teaching ownership.

As such, I'm going to give this a close, not because it's bad, but because it's not something I'll be working on. If someone wants to tackle this, feel free to send a PR! But this will eventually be fixed with the new book.
