### ISSUE TITLE
ToTokens is not implemented for a lot of ast types

### ISSUE THREAD

**Issue by JelteF** [rust-lang/rust#32750]
The one I'm currently having trouble with is the TyParam type:
https://manishearth.github.io/rust-internals-docs/syntax/ast/struct.TyParam.html

However, lots of other types have also not implemented TokenTree. This means they can't be used with the `quote_*!` macros.

**Comment by JelteF** [comment]
Others I found:
- `TyParamBound`
- `TraitRef`

**Comment by Mark-Simulacrum** [comment]
I feel like this isn't something we want, and/or this is superseded by the Macros 2.0 discussion. I'm going to close this, but please do let us know if you still need this. Note that libsyntax is entirely unstable, so this isn't necessarily something you can rely on in the long-term. These two crates might be more to your liking, since they have better compile times and performance, and, I think, work on stable Rust: https://github.com/dtolnay/syn and https://github.com/dtolnay/quote.

**Comment by JelteF** [comment]
Yes, by now I've switched to the syn and quote crates
