### ISSUE TITLE
Duplicate path resolution errors in `resolve`

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#32760]
For example,
```rust
mod foo {}

use foo::bar::baz::{}; // This emits 2 errors
fn main() {
    foo::bar::baz(); // This emits 2 errors
    <() as foo::bar>::baz(); // This emits 3 errors
    foo::bar::baz { x: 0 } // This emits 2 errors
}
```

**Comment by Aatch** [comment]
Looks like the errors aren't true duplicates, instead it first complains about not finding `bar` in `foo`, then complains about not being able to resolve `foo::bar::baz`.

The general pattern is where B fails because A fails and B depends on A, we should probably be detecting these cases and silencing the dependent errors.

**Comment by jseyfried** [comment]
Agreed -- I should have been more specific.
