### ISSUE TITLE
Add error explanations for all error codes

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#32777]
This is a reopening of #24407 issue. So I took back what was already there and updated it:

This is a metabug for `rustc --explain` error descriptions.

All the errors in need of descriptions are listed in this spreadsheet. If you'd like to help out, comment with the bunch of errors you'd like to tackle, and list yourself as assigned on the spreadsheet!

Choosing a few errors in the same file is probably a good way to start.
# How to add an error explanation

Error explanations live in:
- [librustc](https://github.com/rust-lang/rust/blob/master/src/librustc/diagnostics.rs)
- [librustc_trans](https://github.com/rust-lang/rust/blob/master/src/librustc_trans/diagnostics.rs)
- [librustc_passes](https://github.com/rust-lang/rust/blob/master/src/librustc_passes/diagnostics.rs)
- [librustc_plugin](https://github.com/rust-lang/rust/blob/master/src/librustc_plugin/diagnostics.rs)
- [librustc_typeck](https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/diagnostics.rs)
- [librustc_privacy](https://github.com/rust-lang/rust/blob/master/src/librustc_privacy/diagnostics.rs)
- [librustc_resolve](https://github.com/rust-lang/rust/blob/master/src/librustc_resolve/diagnostics.rs)
- [librustc_borrowck](https://github.com/rust-lang/rust/blob/master/src/librustc_borrowck/diagnostics.rs)
- [librustc_metadata](https://github.com/rust-lang/rust/blob/master/src/librustc_metadata/diagnostics.rs)
- [librustc_const_eval](https://github.com/rust-lang/rust/blob/master/src/librustc_const_eval/diagnostics.rs)

To add a new explanation you have to delete the error from the register_diagnostics! invocation and add it to the register_long_diagnostics! invocation, along with the explanation. The format for the explanation is 80 characters per line, with a newline at the very start and end of the string.

Please refer to this [RFC](https://github.com/rust-lang/rfcs/pull/1567) when you'll write your error explanation (it can also helps you to start if don't know how to write it).

Once you've added an explanation you can test it out by compiling and running stage1 as follows:

``` shell
$ ./x.py test src/test/ui -- stage1
$ export PATH=x86_64-unknown-linux-gnu/stage1/bin:$PATH
$ export LD_LIBRARY_PATH=x86_64-unknown-linux-gnu/stage1/lib:$LD_LIBRARY_PATH
$ rustc --explain EXXXX
```

You can add `--jobs 4` to use 4 parallel make processes:

``` shell
$ ./x.py build --stage 1 --jobs4
```

Once you're happy with the result, submit a pull request and we'll review it.
# Progress
- [x] E0090
- [ ] E0103
- [ ] E0104
- [ ] E0167
- [x] E0174
- [ ] E0182
- [ ] E0183
- [ ] E0196
- [ ] E0203
- [ ] E0208
- [ ] E0212
- [ ] E0224
- [ ] E0226
- [ ] E0227
- [ ] E0228
- [x] E0230
- [x] E0231
- [ ] E0238
- [ ] E0242
- [ ] E0245
- [x] E0254
- [ ] E0278
- [ ] E0279
- [ ] E0280
- [ ] E0284
- [ ] E0298
- [ ] E0299
- [ ] E0311
- [x] E0312
- [ ] E0313
- [ ] E0314
- [ ] E0315
- [ ] E0316
- [ ] E0320
- [x] E0328
- [x] E0374
- [x] E0375
- [x] E0376
- [ ] E0377
- [ ] E0385
- [x] E0388
- [x] E0389
- [x] E0393
- [x] E0399
- [ ] E0402
- [ ] E0406
- [x] E0408
- [x] E0409
- [x] E0410
- [x] E0414
- [ ] E0418
- [ ] E0420
- [x] E0421
- [x] E0427
- [x] E0429
- [x] E0434
- [x] E0436
- [x] E0453
- [x] E0455
- [ ] E0456
- [ ] E0457
- [ ] E0460
- [ ] E0461
- [ ] E0462
- [ ] E0464
- [ ] E0465
- [x] E0466
- [x] E0467
- [x] E0468
- [x] E0469
- [x] E0470
- [ ] E0471
- [ ] E0472
- [ ] E0473
- [ ] E0474
- [ ] E0475
- [ ] E0476
- [ ] E0477
- [x] E0478
- [ ] E0479
- [ ] E0480
- [ ] E0481
- [ ] E0482
- [ ] E0483
- [ ] E0484
- [ ] E0485
- [ ] E0486
- [ ] E0487
- [ ] E0488
- [ ] E0489
- [ ] E0490
- [x] E0491
- [ ] E0495
- [ ] E0498
- [x] E0500
- [x] E0501
- [x] E0502
- [x] E0503
- [x] E0504
- [x] E0505
- [x] E0506
- [x] E0507
- [x] E0508
- [x] E0509
- [ ] E0513
- [ ] E0514
- [x] E0519
- [x] E0520
- [ ] E0521
- [ ] E0523

cc @steveklabnik

**Comment by marti1125** [comment]
I would like to take this =D How to I can start?

**Comment by GuillaumeGomez** [comment]
@marti1125: I guess the first step is to find one of the listed error codes into the rust source code (github search makes it easy) and then try to span it with rust code. From there, just follow the description of this issue and if you need help, you can always ask (here or on [IRC](irc.mozilla.org) on #rust-docs chan).

**Comment by timothy-mcroy** [comment]
I'm working on E0501.

**Comment by timothy-mcroy** [comment]
I'll open a PR for E0502 tomorrow.

**Comment by cramertj** [comment]
I'll open a PR for E0509 today or tomorrow.

**Comment by GuillaumeGomez** [comment]
@timothy-mcroy, @cramertj: Thanks to both of you! :D

**Comment by cristianoliveira** [comment]
Hey guys. I'll take the E0507. Tomorrow I'm going to work on it (Now is almost 1 am here in Brazil :P)

**Comment by dfockler** [comment]
I'll work on E0374 and E0376

**Comment by cramertj** [comment]
I'll do E0506 next.

**Comment by GuillaumeGomez** [comment]
\o/

**Comment by cristianoliveira** [comment]
Hey @GuillaumeGomez
It seems that E0507 has been done. Take a look here: https://github.com/rust-lang/rust/blob/44b3cd8c462a420ab64a44ef8f70c007001a1f44/src/librustc_borrowck/diagnostics.rs#L317

Please check the E0507 on the list. 

Also, I've verified the entire list and the other seems ok. I just noticed that the E0519 is duplicated. Take a look:

- Here says that it is a Type error:
https://github.com/rust-lang/rust/blob/470ca1c3ff33cd046f71a5453f8f520da4cd387e/src/librustc_lint/types.rs#L35

- Here says that it is a crate error:
https://github.com/rust-lang/rust/blob/44b3cd8c462a420ab64a44ef8f70c007001a1f44/src/librustc_metadata/creader.rs#L259

**Comment by GuillaumeGomez** [comment]
> It seems that E0507 has been done. Take a look here: https://github.com/rust-lang/rust/blob/44b3cd8c462a420ab64a44ef8f70c007001a1f44/src/librustc_borrowck/diagnostics.rs#L317

And the blame says that I am the one who added it haha. Thanks for finding it!

Strange... It corresponds to this [E0519](https://github.com/rust-lang/rust/blob/470ca1c3ff33cd046f71a5453f8f520da4cd387e/src/librustc_lint/types.rs#L350). So I guess the crate error is the "false" one.

However this is a lint error code. I don't know how they're supposed to work... cc @Manishearth

**Comment by Manishearth** [comment]
No idea what's going on there

**Comment by GuillaumeGomez** [comment]
Well... Thanks! :laughing:

**Comment by cristianoliveira** [comment]
<img src="http://i.imgur.com/qhMbkGi.jpg" width="200" />
(Sorry guys, I had to use this meme again... :laughing: :laughing:)

**Comment by cramertj** [comment]
I'm going to start on E0389.

**Comment by cramertj** [comment]
@GuillaumeGomez Just to check your personal preference-- would you rather review commits prior to squashing (my personal preference) or just have us squash as we go? I personally think it's easier to have things laid out in multiple commits to see what changed over the reviewing process, then squash after review.

**Comment by GuillaumeGomez** [comment]
Since it's generally small commits (< 200 lines), I don't really mind. If you didn't squash once everything's done, I'll ask you to do it anyway. So as you prefer. You can squash every time you update or do it at the end. No personal preference here.

**Comment by cristianoliveira** [comment]
Hey @GuillaumeGomez I am not sure if we've reached some conclusion... About E0519, Can I remove the crate one?

**Comment by GuillaumeGomez** [comment]
I have absolutely no clue. If @Manishearth doesn't know, I think it means we're in trouble.

**Comment by cramertj** [comment]
I'm working on E0212, and have gotten a bit stuck. Does anyone have an idea how to simplify [this code](https://play.rust-lang.org/?gist=e94f1322a6d65cb9174688b01bdd651a&version=stable&backtrace=0) to make it more beginner-comprehensible? I've messed with it a bit and haven't managed get the same error with simpler code.

**Comment by shssoichiro** [comment]
Is it possible that some of these error codes are unreachable? E.g. Any attempts I've tried that resemble the description of E0298 or E0299 are covered by E0308 or E0053.

**Comment by timothy-mcroy** [comment]
@cramertj You can safely take out Foo.get.  It may be worthwhile to also switch Display for another trait, like `pub trait X {}` to make it more general. I'm personally a fan of `bar` vs `foo2`. From there, I think it's pretty concise for an example.

It might be worth mentioning that [Higher Ranked Trait Bounds](https://doc.rust-lang.org/nomicon/hrtb.html) are actually in the rustonomicon and are not likely to be encountered by a beginner. If I were in your position, using that link to the rustonomicon to give context, while focusing solely on what's wrong with what they're trying to do.

**Comment by cramertj** [comment]
@timothy-mcroy Thanks! BTW, I added Display so I could add a `println` justifying the exercise in `main`.

**Comment by GuillaumeGomez** [comment]
@shssoichiro: It's absolutely possible. If you can demonstrate that these error codes are never reached, then they can be commented out (and then please open a PR to do so).

**Comment by GuillaumeGomez** [comment]
@cramertj: Nice idea! Don't hesitate to make example longer if it makes the understanding easier.

**Comment by Manishearth** [comment]
Beware that there are errors which may become reachable after a refactor (basically, errors which are actual errors but are caught earlier in the pipeline). We don't want to remove errors entirely and replace them with unreachable!() and cause ICEs in the future if things switch around a bit. In such cases the error code shouldn't be commented out, instead it should just be marked as unreachable, and we don't give it a long explanation.

**Comment by GuillaumeGomez** [comment]
I'm working on E0500.

**Comment by Saser** [comment]
Is the spreadsheet from the old issue still relevant? In that case, you might want to add a link to it from this issue as well. :blush:

**Comment by GuillaumeGomez** [comment]
Why doing so? All error codes without explanation are listed in the issue.

**Comment by cristianoliveira** [comment]
I'm gonna work on E0174

**Comment by mrhota** [comment]
@GuillaumeGomez can you tag this with A-diagnostics?

**Comment by GuillaumeGomez** [comment]
@mrhota: Done.

**Comment by mrhota** [comment]
@GuillaumeGomez it looks like E0090 is subsumed by E0107. "too few lifetime params" and "wrong number of lifetime params" respectively.

E0090: librustc_typeck/check/mod.rs:4649
E0107: librustc_typeck/astconv.rs:2277

**Comment by GuillaumeGomez** [comment]
@mrhota: That's what it seems. I'll take a deeper look. Thanks for notifying!

**Comment by zackmdavis** [comment]
(I've created pull-request #33955 for E0429.)

**Comment by cristianoliveira** [comment]
Next one for me will be E0238.

**Comment by m-decoster** [comment]
I'll open a PR for E0503 today. I'm just waiting for rustc to compile.

**Comment by cynicaldevil** [comment]
gonna be my first contribution to Rust, so I think I will pick **E0406** : undeclared associated type, which seems to be relatively easy imo  :smiley:

**Comment by GuillaumeGomez** [comment]
@cynicaldevil: Good luck!

**Comment by jhod0** [comment]
I am working on errors around E0470

**Comment by GuillaumeGomez** [comment]
@jhod0: Thanks!

**Comment by jhod0** [comment]
I wrote out the `register_long_diagnostics` for a few errors, ran `make rustc-stage1` as described above - but `./x86.../stage1/bin/rustc --explain <error>` says there is no extended information for the error?

All the descriptions I added are in the `rustc_metadata/diagnostics.rs`.

stage1 built without error messages, so I am unsure what the problem is

**Comment by jhod0** [comment]
Ok - It looks like the problem was `rustc_driver` was not loading the diagnostics from `rustc_metadata`!

[This](https://github.com/rust-lang/rust/blob/9f58fb776a74a44f4fcc2cb57084d33c55530aa4/src/librustc_driver/lib.rs#L1081) function only loads diagnostics from a few support libraries, which did *not* include `rustc_metadata`.

Someone else had already written a few diagnostics for `rustc_metadata`, but neither my nightly (1.12) or beta (1.11) rust installs, or a build from source could display them.

This seems concerning to me - Anyone know if other libraries might have their diagnostics missing?

**Comment by jhod0** [comment]
I looked into it more, and it looks like the following libraries' long error messages are not properly registered: 

* `libsyntax`
* `librustc_passes`
* `librustc_plugin`
..However, the `register_long_diagnostics!` declaration in `librustc_plugin` is empty
* `librustc_mir`
* `librustc_lint`
* `librustc_metadata`

i.e. running the following for anny `errno` in the above libraries will fail:
```sh
$ rustc --explain <errno>
error: no extended information for <errno>
```

This may be intentional, though I can't think of a reason why?

@GuillaumeGomez I fixed this for `librustc_metadata` in the PR above (hence the reason for changes to rustc_driver)

**Comment by jhod0** [comment]
Sorry for all the text, but I found something odd: There are two E0519s!

* One in [librustc_metadata](https://github.com/rust-lang/rust/blob/9f58fb776a74a44f4fcc2cb57084d33c55530aa4/src/librustc_metadata/diagnostics.rs#L110)
* And one in [librustc_lint](https://github.com/rust-lang/rust/blob/b5ad2779ea155f6a1b2b61415bc804dcbb23400c/src/librustc_lint/types.rs#L37)

It looks like the one in `lint` is phony - its erroneous code example compiles fine on my machine. So why is it there?

**Comment by GuillaumeGomez** [comment]
I think we had found this earlier and no ones knows actually haha.

@Manishearth: Do you know something about it. I think we already found this issue but don't remember what we said about it.

**Comment by jhod0** [comment]
Great: Just making sure the team is aware of it!

**Comment by zackmdavis** [comment]
@jhod0 good catch on the unregistered diagnostics! Despite @GuillaumeGomez's recollection that this is known, I can't find an existing filed issue, so I've taken the liberty of excerpting your notes into #35284 so that it doesn't get lost in this enormous comment thread.

Are you interested in submitting a PR? If not, I might be able to take a look later. (I think _someone_ should author a patch and get it landed before the eighteenth, so that users of the future 1.12 release will be able to enjoy all of the explanations that have been written.)

**Comment by jhod0** [comment]
@zackmdavis I think Guillaume was referring to the duplicate E0519s - that is mentioned earlier in this comment thread

**Comment by mark-i-m** [comment]
@GuillaumeGomez would it be possible for you to update the original list of error codes? I would like to help, but it is hard a glance to determine which error codes have already been handled or subsumed...

**Comment by GuillaumeGomez** [comment]
@mark-i-m: I think it's more or less up-to-date. I'll check tomorrow.

**Comment by mark-i-m** [comment]
Thanks :)
For now I can just look in https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/diagnostics.rs

**Comment by mark-i-m** [comment]
I can take E0245... though I think the compiler is erroneously returning E0404 sometimes

**Comment by GuillaumeGomez** [comment]
@mark-i-m: If you want to see the current status of error code explanation, you can look here as well: https://doc.rust-lang.org/nightly/error-index.html

**Comment by sjmackenzie** [comment]
Greeting, I just received a E0514. I'm quite curious to see a clear error message for it! Great job so far, thank you!

**Comment by savage13** [comment]
Is this [updated list](https://gist.github.com/savage13/42f77fba8acbf75b9a165b4031e09671) of the unexplained error codes useful ?

**Comment by sjmackenzie** [comment]
well done chaps! It's great!

**Comment by GuillaumeGomez** [comment]
Nice! A lot of them won't get explanations though since they refer to "internal" errors (I did add an explanation for them but it got refused for this reason).

**Comment by liquidnight2** [comment]
# rustc --version
rustc 1.15.0 (10893a9a3 2017-01-19)

error[E0495]: cannot infer an appropriate lifetime for autoref due to conflicting requirements

 https://doc.rust-lang.org/error-index.html#E0495 
Stable rustc --> stable docs.  Where do I find more details ?

**Comment by GuillaumeGomez** [comment]
@liquidnight2: It doesn't have a long error explanation yet. Can you give the code that throws this error please? I'll try to write the long error explanation from it.

**Comment by CaptainKraft** [comment]
In the instructions, it says:

> Please refer to this [RFC](https://github.com/rust-lang/rfcs/pull/1567) when you'll write your error explanation (it can also helps you to start if don't know how to write it).

and that link to the RFC above leads to https://github.com/rust-lang/rfcs/pull/1567.

Perhaps the link should point to the [document](https://github.com/GuillaumeGomez/rfcs/blob/9c9572a63e0e7e3ece5e53392cb78064651e548f/text/0000-long-error-codes-explanation-normalization.md) explaining the RFC instead of the pull request?

It took me a bit of digging to figure out where that document was.

**Comment by marioidival** [comment]
@GuillaumeGomez This issue are closed to contribution yet?

**Comment by GuillaumeGomez** [comment]
@marioidival: If you find any error code not having a long error explanation; then it's not. Either add it yourself or open a new issue please.

**Comment by marioidival** [comment]
@GuillaumeGomez The progress show us that much is still missing.

**Comment by GuillaumeGomez** [comment]
I think it's really outdated.

**Comment by markmmm** [comment]
The following appear to already be documented:
[E0090](https://github.com/rust-lang/rust/blob/29c8276cee4a0eab7e0634ff25c6b47bd9f87c6c/src/librustc_typeck/diagnostics.rs#L1173)
[E0230](https://github.com/rust-lang/rust/blob/bd98fe0c05601d8a318a709adc4263f3348ea8d4/src/librustc/diagnostics.rs#L686)
[E0231](https://github.com/rust-lang/rust/blob/bd98fe0c05601d8a318a709adc4263f3348ea8d4/src/librustc/diagnostics.rs#L718)
[E0328](https://github.com/rust-lang/rust/blob/29c8276cee4a0eab7e0634ff25c6b47bd9f87c6c/src/librustc_typeck/diagnostics.rs#L2672)
[E0399](https://github.com/rust-lang/rust/blob/29c8276cee4a0eab7e0634ff25c6b47bd9f87c6c/src/librustc_typeck/diagnostics.rs#L3242)
[E0414-E0421, E0427 (and others) are commented out - should they be removed from the list](https://github.com/rust-lang/rust/blob/ff2a7c85757542f454934e00605355bbca7bc196/src/librustc_resolve/diagnostics.rs#L1688)
[E0436](https://github.com/rust-lang/rust/blob/29c8276cee4a0eab7e0634ff25c6b47bd9f87c6c/src/librustc_typeck/diagnostics.rs#L3280)
[E0455](https://github.com/rust-lang/rust/blob/dead08cb331343b84564628b139b657f93548320/src/librustc_metadata/diagnostics.rs#L29)
[ E0466](https://github.com/rust-lang/rust/blob/ff2a7c85757542f454934e00605355bbca7bc196/src/librustc_resolve/diagnostics.rs#L1339)
 [E0467](https://github.com/rust-lang/rust/blob/ff2a7c85757542f454934e00605355bbca7bc196/src/librustc_resolve/diagnostics.rs#L1376)
 [E0468](https://github.com/rust-lang/rust/blob/ff2a7c85757542f454934e00605355bbca7bc196/src/librustc_resolve/diagnostics.rs#L1405)
 [E0469](https://github.com/rust-lang/rust/blob/ff2a7c85757542f454934e00605355bbca7bc196/src/librustc_resolve/diagnostics.rs#L1435)
 [E0470](https://github.com/rust-lang/rust/blob/ff2a7c85757542f454934e00605355bbca7bc196/src/librustc_resolve/diagnostics.rs#L1477)
[E0491](https://github.com/rust-lang/rust/blob/bd98fe0c05601d8a318a709adc4263f3348ea8d4/src/librustc/diagnostics.rs#L1534)

**Comment by GuillaumeGomez** [comment]
I updated the list. I also checked the removed ones.

**Comment by markmmm** [comment]
Comments after each link are those extracted from either `diagnostics.rs` or from where the error was raised. My thought is that those would help people identify errors that they may be familiar with and it might help get then resolved :)
*Links are github search links.*


The following are commented out
 - [E0103](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0103)  // 
 - [E0104](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0104)  // 
 - [E0167](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0167)  // 
 - [E0182](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0182)  // merged into E0229
 - [E0196](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0196)  // cannot determine a type for this closure
 - [E0238](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0238)  // renthesized parameters may only be used with a trait
 - [E0242](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0242)  // 
 - [E0245](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0245)  // not a trait
 - [E0298](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0298)  // 
 - [E0299](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0299)  // mismatched types between arms
 - [E0385](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0385)  // {} in an aliasable location
 - [E0402](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0402)  // cannot use an outer type parameter in this context
 - [E0406](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0406)  // merged into 420
 - [E0418](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0418)  // merged into 532
 - [E0420](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0420)  // merged into 532
 - [E0471](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0471)  // constant evaluation error (in pattern)

I couldn't find any reference in git for these (using github search)
 - [E0513](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0513)
 - [E0521](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0521)

Listed in `src/librustc/diagnostics.rs` but not raised anywhere.
 - [E0278](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0278)


These are the remaining items from the list

| Issue | 'Raised' in file | comment 
| --- | --- | ---
| [E0183](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0183) | `src/librustc_typeck/diagnostics.rs` |  
| [E0203](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0203) | `src/librustc_typeck/diagnostics.rs` | type parameter has more than one relaxed default bound, and only one is supported
| [E0208](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0208) | `src/librustc_typeck/diagnostics.rs` |
| [E0212](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0212) | `src/librustc_typeck/diagnostics.rs` | cannot extract an associated type from a higher-ranked trait bound
| [E0224](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0224) | `src/librustc_typeck/diagnostics.rs` | at least one non-builtin train is required for an object type
| [E0226](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0226) | `src/librustc_passes/ast_validation.rs` | only a single explicit lifetime bound is permitted
| [E0227](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0227) | `src/librustc_typeck/diagnostics.rs` | ambiguous lifetime bound, explicit lifetime bound required
| [E0228](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0228) | `src/librustc_typeck/astconv.rs` |  the lifetime bound for this object type cannot be deduced from context; please supply an explicit bound
| [E0279](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0279) | `src/librustc/traits/error_reporting.rs` |  requirement is not satisfied
| [E0280](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0280) | `src/librustc/traits/error_reporting.rs` |  requirement is not satisfied
| [E0284](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0284) | `src/librustc/traits/error_reporting.rs` |  type annotations required: cannot resolve `{}`
| [E0311](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0311) | `src/librustc/infer/error_reporting/mod.rs` |  "{} may not live long enough", labeled_user_string
| [E0313](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0313) | `src/librustc/infer/error_reporting/mod.rs` |  lifetime of borrowed pointer outlives lifetime of captured variable
| [E0314](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0314) | `src/librustc/infer/error_reporting/note.rs` |  closure outlives stack frame
| [E0315](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0315) | `src/librustc/infer/error_reporting/note.rs` |  cannot invoke closure outside of its lifetime
| [E0316](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0316) | `src/librustc/middle/resolve_lifetime.rs` |  nested quantification of lifetimes
| [E0320](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0320) | `src/librustc/traits/query/dropck_outlives.rs` |  recursive overflow during dropck
| [E0377](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0377) | `src/librustc_typeck/coherence/builtin.rs` |  the trait `CoerceUnsized` may only be implemented for a coercion
| [E0456](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0456) | `src/librustc_metadata/creader.rs` |  plugin `{}` is not available for triple `{}` (only found {})", name, config::host_triple(), self.sess.opts.target_triple
| [E0457](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0457) | `src/librustc_metadata/creader.rs` |  plugin `{}` only found in rlib format, but must be available in dylib format"
| [E0460](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0460) | `src/librustc_metadata/locator.rs` | found possibly newer version of crate `..` OR  found possibly newer version of crate `..` which `{}` depends on
| [E0461](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0461) | `src/librustc_metadata/locator.rs` |  couldn't find crate `{}` with expected target triple {}{}" OR couldn't find crate `{}` with expected target triple {} which `{}` depends on
| [E0462](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0462) | `src/librustc_metadata/locator.rs` |  "found staticlib `{}` instead of rlib or dylib{}
| [E0464](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0464) | `src/librustc_metadata/locator.rs` |  multiple matching crates for `{}`
| [E0465](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0465) | `src/librustc_metadata/locator.rs` |  multiple {} candidates for `{}` found", flavor, self.crate_name
| [E0472](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0472) | `src/librustc_passes/ast_validation.rs` | "asm! is unsupported on this target"
| [E0473](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0473) | `src/librustc/infer/error_reporting/note.rs` | dereference of reference outside its lifetime
| [E0474](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0474) | `src/librustc/infer/error_reporting/note.rs` | captured variable `..` does not outlive the enclosing closure
| [E0475](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0475) | `src/librustc/infer/error_reporting/note.rs` | index of slice outside its lifetime
| [E0476](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0476) | `src/librustc/infer/error_reporting/note.rs` | lifetime of the source pointer does not outlive lifetime bound...
| [E0477](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0477) | `src/librustc/infer/error_reporting/note.rs` | the type `..` does not fulfill the required lifetime...
| [E0479](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0479) | `src/librustc/infer/error_reporting/note.rs` | the type `{}` (provided as the value of a type parameter) is not valid at this point
| [E0480](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0480) | `src/librustc/infer/error_reporting/note.rs` | lifetime of method receiver does not outlive the method call
| [E0481](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0481) | `src/librustc/infer/error_reporting/note.rs` | lifetime of function argument does not outlive the function call
| [E0482](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0482) | `src/librustc/infer/error_reporting/note.rs` | lifetime of return value does not outlive the function call
| [E0483](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0483) | `src/librustc/infer/error_reporting/note.rs` | lifetime of operand does not outlive the operation
| [E0484](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0484) | `src/librustc/infer/error_reporting/note.rs` | reference is not valid at the time of borrow
| [E0485](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0485) | `src/librustc/infer/error_reporting/note.rs` | automatically reference is not valid at the time of borrow
| [E0486](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0486) | `src/librustc/infer/error_reporting/note.rs` | type of expression contains references that are not valid during the expression: `{}`
| [E0487](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0487) | `src/librustc/infer/error_reporting/note.rs` | unsafe use of destructor: destructor might be called while references are dead
| [E0488](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0488) | `src/librustc/infer/error_reporting/note.rs` | lifetime of variable does not enclose its declaration
| [E0489](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0489) | `src/librustc/infer/error_reporting/note.rs` | type/lifetime parameter not in scope here
| [E0490](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0490) | `src/librustc/infer/error_reporting/note.rs` | a value of type `{}` is borrowed for too long
| [E0495](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0495) | `src/librustc/infer/error_reporting/mod.rs` | cannot infer an appropriate lifetime due to conflicting requirements
| [E0498](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0498) | `src/librustc_plugin/load.rs` | malformed plugin attribute
| [E0514](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0514) | `src/librustc_metadata/locator.rs` | metadata version mismatch
| [E0523](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=E0523) | `src/librustc_metadata/creader.rs` | found two different crates with name `{}` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.

**Comment by Havvy** [comment]
The following are not listed at all, but are missing:

* 0523, 0524, 0526, 0531, 0533, 0538-0551, 0553, 0555, 0556, 0561. 0563, 0564, 0566-0568, 0573-0578, 0584, 0592, 0594, 0598, 0613, 0623, 0625, 0627-0632, 0634-0637, 0640-0642, 0645, 0648-0657, 0660-0688, 0693, 0694, 0696-0907 (???? at this last range)

**Comment by GuillaumeGomez** [comment]
There is a 907????????

**Comment by GuillaumeGomez** [comment]
I'm fixing those codes...

**Comment by twe4ked** [comment]
Add extended information for E0594 in https://github.com/rust-lang/rust/pull/60193.

**Comment by oli-obk** [comment]
@GuillaumeGomez 	there are new error codes that do not have boxes yet

**Comment by GuillaumeGomez** [comment]
I think this issue is completely out of date since a moment... Should we open a new one instead?

**Comment by Manishearth** [comment]
Yeah, go for it
-Manish Goregaokar

**Comment by GuillaumeGomez** [comment]
Ok!

**Comment by GuillaumeGomez** [comment]
Closing in favor of #61137.
