### ISSUE TITLE
`String::from_utf16_lossy` signature differs from `from_utf8_lossy`

### ISSUE THREAD

**Issue by starkat99** [rust-lang/rust#32874]
`String::from_utf8_lossy` returns a `Cow<'a, str>` while `String::from_utf16_lossy` returns simply `String`. It would be useful for their signature to both match. `String::from_utf16_lossy` should return `Cow<'a, str>` as well, though this is obviously a breaking, but easily solved, change.

**Comment by bluss** [comment]
The conversion from utf-16 can never result in a &str, since the representation of the data changes from using u16 units to u8.

**Comment by nagisa** [comment]
Moreover you can trivially convert an owned datatype to Cow with `into`:

```rust
let x: Cow<str> = String::from_utf16_lossy(&[]).into();
```

**Comment by alexcrichton** [comment]
Yeah unfortunately these signatures can't change (as they're stable), but they're both intended to return "string-like types" in whichever way is most suitable, but perhaps the docs can be bolstered up to emphasize that!

**Comment by Mark-Simulacrum** [comment]
Relabeling as a docs issue since we can't change these APIs. However, I'm not entirely sure what needs to be changed here. Specifically, we should mention that conversion from UTF-16 can never be done without allocating, so we don't return a Cow. I'm personally not sure this is a good idea, but I can see the benefits, since it explains the API inconsistency.

**Comment by frewsxcv** [comment]
Opened a PR for this: https://github.com/rust-lang/rust/pull/44572
