### ISSUE TITLE
rustdoc primitve impl method anchors are not disambiguated

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#32890]
The [page for pointers](http://doc.rust-lang.org/nightly/std/primitive.pointer.html) contains impls for both `*const` and `*mut` but the links to their methods are not disambiguated by pointer type, so http://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.as_ref is used for the anchor of both `as_ref` methods.

**Comment by nagisa** [comment]
cc https://github.com/rust-lang/rust/pull/30036

**Comment by mitaa** [comment]
This is because even though we're generating unique ids, the code that renders the methods ([`render_assoc_item`]) does not know about the allocated id and [creates a naive one itself..][1]

[`render_assoc_item`] takes a
```rust
enum AssocItemLink<'a> {
    Anchor,
    GotoSource(DefId, &'a HashSet<String>),
}
```
where `Anchor` refers to an item on the current page and `GotoSource` refers to the trait pages item (used in the trait implementations section).

I think the best fix would be to change `Anchor` to `Anchor(Option<String>)` and fill it lazily with the allocated id from [`derive_id(..)`][2].

Relevant code is in [src/librustdoc/html/render.rs](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/render.rs).

Label as "E-easy"?

[`render_assoc_item`]: https://github.com/rust-lang/rust/blob/bb66d91c98d83ac5fc453f120ef4a810bc8939a5/src/librustdoc/html/render.rs#L2101
[1]: https://github.com/rust-lang/rust/blob/bb66d91c98d83ac5fc453f120ef4a810bc8939a5/src/librustdoc/html/render.rs#L2117
[2]: https://github.com/rust-lang/rust/blob/bb66d91c98d83ac5fc453f120ef4a810bc8939a5/src/librustdoc/html/render.rs#L2507

**Comment by caipre** [comment]
I'll take a look at this.
