### ISSUE TITLE
make install prefix=/usr/local/stow/rust-git # does not work

### ISSUE THREAD

**Issue by rkitover** [rust-lang/rust#32916]
When using e.g. GNU Stow, the convention for autoconf based systems is to use `./configure --prefix=/usr/local` and then install to the stow directory on `make install`, with e.g. `make install prefix=/usr/local/stow/rust-git`. It seems the rust buid tools do not support this. I am just using `DESTDIR` as a workaround (cmake forces you to do the same thing, unfortunately.)

**Comment by sanliturk** [comment]
./configure --prefix=`pwd`/Installed --local-rust-root=`pwd`/Installed
make -i -k
make -i -k install

With the above statements , during install , it is giving an error about 

ldconfig .... "root" login is required 

for a non-root user .

Since the local directory `pwd` , is not related to "root" authorized directories , the given error message and discontinuing the install is not a proper application .

Mehmet Erol Sanliturk

**Comment by steveklabnik** [comment]
Triage: we don't really use `make` anymore, though it does technically still exist.

@rkitover are you still having this problem?

**Comment by rkitover** [comment]
Haven't tried this in a while, but it's easy to test.

**Comment by bjorn3** [comment]
This can be closed I think.

**Comment by Mark-Simulacrum** [comment]
I don't think we expect passing paths to make (i.e., `make install prefix=...`) to work, and we do have work arounds (DESTDIR, ./configure) which do work, so I agree we can close this.
