### ISSUE TITLE
Genuine issue ignored by some minor functionary

### ISSUE THREAD

**Issue by Evil-Bot-Craython** [rust-lang/rust#32982]
So I reported an issue with the cargo website here:

https://github.com/rust-lang/crates.io/issues/312

Then some clown comes in and closes without a hint of a comment, then locks me out.

One can only hope fools like that are not allowed to touch serious code in this repo, never mind the website!

**Comment by niconii** [comment]
**Moderator note**:

One could easily mistake an issue with the words "Fuck Rust" in the title as being written by a troll. While this may not have been the case, your hostile response to the issue being closed did not help matters, with you directly insulting the person who closed it, and further doing so in this issue here.

I'd like to direct you to the [Code of Conduct](https://www.rust-lang.org/conduct.html), particularly the section regarding being kind and courteous, and the section regarding how insults are not acceptable behavior in this community.

**Comment by retep998** [comment]
To answer your original issue, crates.io performs searches based on the description in the `Cargo.toml` and also in the readme specified. If you look at the [readme for that crate](https://github.com/TeXitoi/rust-mdo/blob/master/README.md) you'll notice it spells out the name of the WTFPL license, hence that is how crates.io finds it via the word "fuck". The word "Rust" also occurs in the description, so looking up "fuck rust" finds both keywords in that crate's description and readme, hence returning it as a search result. Since no other crate happens to have both those words in their description and/or readme, there are no other results.

**Comment by BurntSushi** [comment]
> If you have any ideas on how to improve crates.io's search algorithm, by all means feel free.

I'd like to echo this. Otherwise, this issue doesn't belong here.
