### ISSUE TITLE
Detect homebrew python and fail

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#32992]
Currently, in OS X, if we find homebrew python we'll use it instead of the system python.  Unfortunately, this seems to conflict with the lldb python module.  

We don't warn the users that this is the case, and instead happily configure homebrew and promptly crash when the user tries to run any of the debuginfo-lldb tests.  We should instead warn the user to not use python from homebrew but instead use the system python.

**Comment by alexcrichton** [comment]
Specifically, the error here (that I'm getting at least) is:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 98, in <module>
    import six
ImportError: No module named six
Fatal Python error: PyThreadState_Get: no current thread
```

(the major part being `Fatal Python error: PyThreadState_Get: no current thread`)

I personally have no idea what that error means, but I suspect it's because we're using a *compiled plugin* for lldb which only works against one version of python (presumably) and that version of python is likely the OSX system python.

We should detect this in either or both of the `./configure` script and `src/bootstrap/build/sanity.rs`. Basically on OSX we should only use `/usr/bin/python`, not anything from `/usr/local`. An alternative is to run a smoke test to see if the found python works at all and then just error out if it fails.

cc @michaelwoerister, lldb weirdness!

**Comment by jonathandturner** [comment]
I also tried installing the 'six' package manually, and still was unable to get past the crash with homebrew python.

**Comment by michaelwoerister** [comment]
We could also adapt `compiletest` to always use `/usr/bin/python` for the LLDB debuginfo tests? I'll look into it. Maybe LLDB even comes with its own Python version that we can fall back on.

**Comment by alexcrichton** [comment]
Yeah that may not be a bad idea to just hardcode that for OSX. https://github.com/rust-lang/rust/issues/32994 worries me though and indicates that even that may be wrong, although it could also just be a problem with our script. If LLDB has its own Python version then we should probably definitely be using that!

**Comment by michaelwoerister** [comment]
> Changing the version of Python from the one shipping with OSX is unsupported

from http://stackoverflow.com/a/19642204

**Comment by sanmai-NL** [comment]
LLDB [does not appear to come with a Python distribution](http://lldb.llvm.org/build.html), and explicitly depends on ‘Python 3.5’. I assume they simply depend on the latest minor version of CPython 3.x. Given the proliferation of Python code in the Rust code base, perhaps shipping a minimal Python distribution with a known version that works well across all Python code may cause the least headaches.

**Comment by jonathandturner** [comment]
I'm pretty sure the trouble I was hitting with homebrew was with the 2.x python.  It was the one installed as 'python' in /usr/local/bin.  Likewise, system Python is 2.7.10 for OS X 10.11.4.  I haven't see it use 3.x, yet, though maybe I'm looking in the wrong place?

**Comment by alexcrichton** [comment]
I believe we since fixed this by hardcoding that the system python is used for LLDB tests, so I'm gonna close.
