### ISSUE TITLE
Tracking issue for slice::binary_search_by_key

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/rust#33018]
This was added in #32693.

**Comment by kamalmarhubi** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
Thanks!

**Comment by alexcrichton** [comment]
🔔 This issue is now entering its cycle-long **final comment period** for stabilization 🔔

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to **stabilize**

**Comment by pnkfelix** [comment]
It is unfortunate that the only test that was added here was of a key type that had no interesting lifetime relationship with the records being search over.  Seems like an inadequate exploration of the design prior to stabilization, since if that had been explored, we should have uncovered #34683 sooner.
