### ISSUE TITLE
Allow ignoring matches in macro rules with `_`

### ISSUE THREAD

**Issue by pczarn** [rust-lang/rust#33027]
Example

``` rust
macro_rules! test {
    ($_:expr, $_:expr, $e:expr) => (println!("{}", e))
}
fn main() {
    test!(1, 2, 3);
}
```

Gives errors

```
<anon>:86:11: 86:12 error: expected ident, found `_`
<anon>:86         ($_:expr, $_:expr, $e:expr) => (println!("{}", e))
                    ^
<anon>:86:12: 86:13 error: no rules expected the token `:`
<anon>:86         ($_:expr, $_:expr, $e:expr) => (println!("{}", e))
```

**Comment by TimNN** [comment]
I don't believe this will happen anytime soon (as the exiting macro machinery is already pretty complex, if I remember correctly), especially since you can easily work around this limitation by writing `($_a:expr, $_b:expr, $e:expr) => ...`. In any case I would expect a change like this to need an RFC.

**Comment by steveklabnik** [comment]
Triage: closing in favor of an RFC.
