### ISSUE TITLE
Octal literals

### ISSUE THREAD

**Issue by colonelmo** [rust-lang/rust#33122]
Shouldn't literal numbers that start with a zero (e.g. 0123) be interpreted as octal numbers as they are in many other languages? I believe anyone who is familiar with this notation would expect this behavior.

**Comment by retep998** [comment]
And anyone who isn't familiar with that notation would be surprised when their code breaks or acts differently just because they had a `0` prefix. Rust currently uses `0o` as the octal prefix. To make numbers that start with a `0` interpreted as octal numbers would be a breaking change at this point, so even if you convinced the Rust community that your way was better, we wouldn't be able to do anything about it.

**Comment by colonelmo** [comment]
Very well said. Sounds quite logical to me.

P.s. I'm not trying to "convince" anybody that "my" way is better. I have been surprised by this behavior previously in other languages and I wanted to know what's the deal in rust.

P.p.s. closing
