### ISSUE TITLE
validate target triples before resolving crates

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#33329]
I stared at this for a while

```
$ rustc --target=x86_64_unknown-linux-musl src/main.rs
error: can't find crate for `std` [E0463]
error: aborting due to previous error
```

before realizing I had typod the target triple. If the target had been validated earlier the error would be more obvious.

**Comment by japaric** [comment]
So, I checked this and 

> If the target had been validated earlier the error would be more obvious.

we are already doing this. See:

```
$ rustc --target foo bar.rs
error: Error loading target specification: Could not find specification for target "foo"
```

i.e. validate the target before looking for crates.

The issue here is that `x86_64_unknown-linux-musl` (with underscore) is accepted as a valid target (as `x86_64-unknown-linux-musl`) because of [this function](https://github.com/rust-lang/rust/blob/d80497e628945c3f11ff351030b4c62a8533e01e/src/librustc_back/target/mod.rs#L73-L86) -- it `s/-/_/g` the target name so it can compare it to the module name, which can't have dashes in it.

The fix seems simple because that function is defined in a macro and it also has access to the target names (the ones with dashes). So we have to tweak it to use that instead of the module names (the ones without dashes). I'll look into it.
