### ISSUE TITLE
Tracking issue for `Cell::get_mut` and `RefCell::get_mut`

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#33444]
These methods allow one to obtain a mutable reference to the interior of these cells if you have a mutable reference to the cells themselves.

**Comment by tbu-** [comment]
As stated in https://github.com/rust-lang/rust/pull/32565#issuecomment-217109082, I think that a better name for these methods would be `as_mut`.

**Comment by alexcrichton** [comment]
🔔 This issue is now entering its **final comment period** for stabilization 🔔 

The libs team was unfortunately a little late on stabilizations this cycle, but we're thinking of probably doing a backport of stabilizations partway through the beta cycle. This API also follows existing conventions so should be an easy stabilization!

**Comment by tbu-** [comment]
Looking through the naming convention again, it seems that `get` is only used for conversions or functions that are not cheap or free, e.g. accessing elements of containers, slices, checking the poisoning state of a mutex and returning the element (with the exception of [`Unique::get_mut`](https://doc.rust-lang.org/core/ptr/struct.Unique.html#method.get_mut), which isn't stabilized yet).

However, `as` is often used for this kind of conversion, e.g. [`Option::as_mut`](https://doc.rust-lang.org/core/option/enum.Option.html#method.as_mut).

I don't think `get` fits here.

**Comment by alexcrichton** [comment]
Ah yes I forgot to mention, but the libs team did indeed discuss the name and concluded that `get_mut` is the convention here. The `get_*` prefix is used for containers such as vectors, maps, I/O wrappers, synchronization primitives, etc. The `as_*` prefix is intended for conversions.

Because these are "containers" and these methods aren't performing conversions, we concluded the appropriate name was `get_mut`

**Comment by alexcrichton** [comment]
The libs team discussed this issue during triage yesterday and the decision was to **stabilize**. We realize that the FCP for this issue was pretty short, however, so please comment with any objections you might have! We're very willing to backport an un-stabilization for the few APIs we have this cycle.
