### ISSUE TITLE
"Private" impl functions can leak out of a module when defined on a public type

### ISSUE THREAD

**Issue by deadalusai** [rust-lang/rust#33479]
"Private" impl functions can leak out of a module when defined on a public type. This can allow private types to appear as part of a modules' public interface.

Example on playground: [http://is.gd/aGx2MV](http://is.gd/aGx2MV)

In this example, the type `Private` leaks out of `the_module` via the `impl Public<Private>` impl block. It looks like all functions in that block should be inferred to be private?

[Reddit discussion](https://www.reddit.com/r/rust/comments/4i7nea/private_types_in_public_interfaces/)

**Comment by deadalusai** [comment]
[This issue](https://github.com/rust-lang/rust/issues/30476) seems similar.

**Comment by petrochenkov** [comment]
Yep, incarnation of https://github.com/rust-lang/rust/issues/30476 (although the example is sufficiently different from those given in #30476), one more example of type inference being too smart.

Private-in-public checker assumes that the type `Public<Private>` and therefore its impls are private, because you can't name it or construct its values outside of its module without using `Private`.
However, type inference is able to infer private type parameters in some cases and it's not something generally fixable with private-in-public checker alone.
