### ISSUE TITLE
docs: a better guessing game after learning more

### ISSUE THREAD

**Issue by deepak** [rust-lang/rust#33495]
after completing the [guessing game](https://github.com/rust-lang/rust/blob/01d76099f261abe50342d9261fad618c5323274b/src/doc/book/guessing-game.md) had some questions and suggestions for improvement:

- refactor into smaller functions
- document code and generate docs
- print secret only for debug target not for the optimized build
- write tests
- write benchmarks

for sure, am missing a lot of other stuff.

one suggestion is maybe, refactor the same code after the `Syntax and Semantics` section 
as an improved take on the `guessing game`

**Comment by steveklabnik** [comment]
Hey @deepak ,

Thanks for this! I do think that some expansion of this would be neat, and specifically, refactoring it after Syntax and Semantics makes a lot of sense.

But, I'm not making major additions or changes to the book right now, because I'm doing a second edition that's completely re-written. So, if you (or anyone else) wants to improve the book in this way, I'd be happy to help edit and accept a PR for it, but won't be doing it myself. So I'm going to give this issue a close.

Thank you!
