### ISSUE TITLE
Add flag to opt out one test from parallel testing

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang/rust#33519]
Hi all

I had a problem while testing the threadpool-crate because all test run in parallel and all of them use the whole cpu.
Would it be possible to add a additional flag for test like this? Maybe something like this:

``` rust
#[test]
#[no_parallel]
fn test_heavy_load_on_cpu_or_gpu_or_global_state() {
  // working hard here ...
}
```

The implementation would have to queue these test and run them sequencally.

The flag `no_parallel` seems very expressiv, but I prefere a positive keyword like `single`, `serial` or `individual` or something like this.

What do you think?
Regards

**Comment by arthurprs** [comment]
I think we really need something like this. Like proposed here or some sort of cargo.toml setting.

It's almost always possible to make tests parallel safe but we're making all rust users suffer from that paper-cut over and over again, let's do it once (in core) and save tons of dev hours.

**Comment by doxxx** [comment]
Here's a use-case which may provide some additional context:

I have a number of modules that work with files. Each test uses `fs::DirBuilder::new().recursive(true).create(&dir).unwrap();` to create a directory in which the test files will be created and then `fs::remove_dir_all(dir).unwrap();` at the end to clean it up. Each test uses a different path, `target/debug/tmp/test/<module>/<test>`, but they all share a common prefix.

If one of the shared parent directories does not exist when the tests are run, the recursive directory creation in each of the parallel tests races to create the parent directories. This race sometimes results in one of the tests failing with a panic because the `mkdir` returns an Err indicating that the directory already exists.

I think my only solution is to use a global mutex around the directory creation.

**Comment by nrc** [comment]
There is a work around for this using a Mutex, we would therefore not add this to the current test framework. See https://github.com/rust-lang/rust/pull/42684#issuecomment-314224230 for a little more discussion.
