### ISSUE TITLE
Iterator over entries of Hash*

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#33549]
An iterator over entries of HashMap/Set could be added?

**Comment by eefriedman** [comment]
`HashMap` already has a method `iter_mut()`; could you describe what you want a bit more precisely?

**Comment by nagisa** [comment]
@eefriedman Consider following code which could potentially be a poor-man’s implementation of pop:

```rust
for entry in map.entries() {
    if let Entry::Occupied(o) = entry {
        return o.remove();
    } else { unreachable!() }
}
```

That cannot be implemented with iter_mut() today.

**Comment by apasel422** [comment]
I'm not sure that the current `HashMap` design would support the existence of multiple `OccupiedEntry`s at the same time (due to the relocation of entries during removal), but if such an iterator were added, I expect that its item type would be `OccupiedEntry` rather than `Entry`, as a `VacantEntry` cannot be created without a key.

**Comment by dtolnay** [comment]
I agree with @apasel422 that I don't think this will work with an iterator of entries. The Iterator trait permits the caller to hold on to multiple items at the same time, which in this case would mean multiple items that each have mutable access to the same HashMap.

I think the use case of iterating over key-value pairs and conditionally removing them efficiently is addressed by [`HashMap::retain`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.retain) which was added in #36648, after this issue was opened, so I think this can be considered done.
