### ISSUE TITLE
error_index_generator: doc/error-index.html

### ISSUE THREAD

**Issue by ArrogantWombatics** [rust-lang/rust#33662]
In Rust git 5/15/16 on Linux 4.5.0-sabayon #1 SMP x86_64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz GenuineIntel GNU/Linux
```
cp: x86_64-unknown-linux-gnu/stage2/bin/error_index_generator
error_index_generator: doc/error-index.html
<stdin>:11:10: 11:11 error: unknown start of token: `
<stdin>:11 In here, `jon_snow` is already borrowed by the `nights_watch` closure, so it
                    ^
warning: Backing out of syntax highlighting
note: You probably did not intend to render this as a rust code-block
```

**Comment by apasel422** [comment]
[This line](https://github.com/rust-lang/rust/blob/0f4f51b1738c88fedf0f3e56eb4341752dd64851/src/librustc_borrowck/diagnostics.rs#L393) needs a ``` after it.

**Comment by sanmai-NL** [comment]
Does @apasel422's response suffice to fix your issue?
Could you put your output into a `code` block? Also, please add Rust version info. See [`CONTRIBUTING.md`](/rust-lang/rust/blob/master/CONTRIBUTING.md). This is needed so that people searching the issues history will have an easier time reading your issue.

**Comment by apasel422** [comment]
@sanmai-NL It's not really @ArrogantWombatics's issue; someone needs to submit a PR with the change I suggested.
