### ISSUE TITLE
Can't catch panic!() if main application is in C, causes SIGILL

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#33773]
See https://github.com/sdroege/rust-c-panic-bug for a testcase

If you run "make run", trying to catch the panic!() will fail with a SIGILL. "make run2" will catch it and exit the application cleanly. I'm testing this with rustc 1.8.0.

What happens with "make run" is that main() is from a C application that calls into a Rust function that panics, but where the panic should be caught by the Drop implementation of "PanicGuard". Which will exit() the process if thread::panicking() is true. However before the Drop implementation even runs, the process is killed by a SIGILL while trying to unwind the stack.

The same application with main() being from a Rust application works as intended (make run2).

**Comment by alexcrichton** [comment]
Thanks for the report! This is unfortunately, however, undefined behavior in Rust to unwind across a language boundary. The notion of "unwind" here is more accurately "panicking without a catch in Rust somewhere on the stack" rather than literally unwinding the stack and then being undefined once you hit a C stack frame.

To handle this I'd recommend using the `panic::catch_unwind` API (soon to be stable!) or perhaps compiling with `panic=abort`. This is currently working as intended, however, so I'm gonna close. Let me know if any of that doesn't make sense though!

**Comment by sdroege** [comment]
The goal here is to actually *not* unwind across language boundaries but catch the panic in the Rust code and exit the process cleanly. The SIGILL happens before the Rust function even gets back to C.

**Comment by alexcrichton** [comment]
Ah if that's the intention then you may also be interested in the `panic::set_hook` API which allows you to configure what happens just before a panic is implemented (in this case perhaps exiting the process cleanly). You'll essentially want to avoid unwinding one way or another entirely.

**Comment by sdroege** [comment]
But the panic hook is global, it doesn't seem like a good idea for a library to set something global as other code might set it to something else too.

What is the reason why the unwinding here does not work for the Rust function itself and under which circumstances does this happen? Whenever somewhere in the callstack there is a non-Rust function? Whenever there is no unwind::try() somewhere in the callstack?

**Comment by sdroege** [comment]
If I wrap it in panic::catch_unwind() then the following happens:
1) the Drop implementation of the "PanicGuard" is called
2) Err is returned by catch_unwind() and I can handle it

So my guess is that unwinding (even inside Rust functions) only works if somewhere in the callstack (or before the latest language boundary?) something is catching panics. Otherwise panics will SIGILL instead of doing anything else. If I understand the docs correctly, catch_unwind() is going to be stable with 1.9?

Also would it be possible to add some code to panic!() to catch the SIGILL case and instead make it kill the process with a more meaningful error message?

**Comment by sdroege** [comment]
Ok, it is intrinsics::abort() that gives the SIGILL (on x86-64). So I guess on the Rust side it's all good and llvm (that's what is implementing the intrinsics, right?) does something weird there. See e.g. https://gist.github.com/sdroege/aaffc93918f32f7a5a95ea63e39ca4fc which is also causing a SIGILL. Maybe something to report to llvm?

However, is my understanding correct that unwinding only works if somewhere (or before the next language boundary?) there is something doing unwind::try()?

**Comment by alexcrichton** [comment]
Ah yeah, so to clarify:

1. Unwinding on a panic is only defined behavior if there is a "catch" somewhere on the stack and all stack frames from there to the panic are Rust functions (at least).
2. It *may* work for a Rust catch frame to call C which then calls Rust which panics. This is undefined behavior, however, and panics should always be caught at the language boundary.
3. When there is no catch frame on the stack (this is undefined behavior), the current implementation is to call `rtabort!` which ends up calling `intrinsics::abort` which is in turn implemented in LLVM as the `ud2`, or an illegal instruction. This is what raises SIGILL because an illegal instruction is being executed.
4. To "add code" to a panic is what panic hooks are intended for. You're right that they're global state (like signal handlers), but unfortunately handling panics is generally global state. The combination of `take_hook` and `set_hook` should be enough to make the abstraction composable so long as there aren't too many threads in play.
5. You are correct indeed that `catch_unwind` will be stable in 1.9! That'll even be released this week :)

Does that all make sense?

**Comment by sdroege** [comment]
Thanks, that perfectly makes sense. So my wrong assumption was that unwinding works for Rust functions until the language boundary, and what confused me to think this is a bug was llvm creating a SIGILL to kill the process. Which looked more than a bug than expected behavior, like a SIGABRT would instead.

Thanks for taking all the time to explain that!

**Comment by alexcrichton** [comment]
No problem! We've actually got a PR open to use `abort()` instead of `intrinsics::abort` (which raises SIGABRT instead of SIGILL) to terminate in abonormal situations, so that may become less surprising in the future as well :)
