### ISSUE TITLE
ptr::offset shouldn't be unsafe

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#33813]
The method `offset` on pointers is currently unsafe: https://doc.rust-lang.org/std/primitive.pointer.html#method.offset

The justification is that using the returned value may result in undefined behavior.
However the jurisprudence in this case is that building a pointer is always safe. Only dereferencing one is unsafe.

For consistency I think `offset()` should be safe.

**Comment by huonw** [comment]
`offset` is `unsafe` because it allows more powerful optimisations: the compiler can deduce that a pointer constructed with `p.offset(n)` will have most of the same nice properties as `p` itself, such as aliasing information. It being `unsafe` allows us to compile `offset` to a raw [`getelementptr inbounds`](http://llvm.org/docs/LangRef.html#getelementptr-instruction) in LLVM.

A safe alternative  is to cast to an integer and back, which necessarily doesn't provide all that information to the compiler (and even more). On unstable, [`arith_offset`](http://doc.rust-lang.org/std/intrinsics/fn.arith_offset.html) is safe (i.e. it can be wrapped directly into a safe function, despite intrinsics defaulting to `unsafe`), and doesn't have the extra pessimisations of casting through integers.

**Comment by tomaka** [comment]
Thanks. Also this discussion on IRC:

> <nox> Why is .offset unsafe?
> <eddyb> nox: GEPi semantics
> <benh> it goes faster if its unsafe
> <nox> benh: What?
> <nox> eddyb: I don't understand.
> <eddyb> I' trying to look for the LLVM docs
> <eddyb> http://llvm.org/docs/GetElementPtr.html#what-happens-if-a-gep-computation-overflows
> <eddyb> it looks like you can trigger UB in at least one way
> <eddyb> (address computation overflow)
> <nox> eddyb: Thanks.
> <ubsan> if it's not one past the end or inside the object, basically
