### ISSUE TITLE
Spurious local ambiguity error after empty $($ident),*

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#34030]
``` rust
macro_rules! foo {
    ($($t:ident),*/) => {()};
}

fn main() {
    foo!(a, b/);  // works fine
    foo!(a/);     // works fine
    foo!(/);      // local ambiguity error ☹
}
```

```
error: local ambiguity: multiple parsing options: built-in NTs ident ('t') or 1 other option.
 --> <anon>:8:10
8 |>     foo!(/);
  |>          ^
```

In this case, it should be looking for an ident or a `/`, in which there is no ambiguity.

All channels are affected.

This is affecting my ability to write macros accepting generics using angle brackets, e.g. `$ty:ident<$($x:ident),*>`, with a supporting pattern to turn `Foo` into `Foo<>`.

May be related to #24827.

**Comment by durka** [comment]
In theory there is no ambiguity because an ident can't start with `<`. As far as I can tell the macro evaluator doesn't reason about this at all. It sure is annoying and I hope it can be fixed. I suppose it introduces a forwards compatibility consideration, just like follow sets: if we let macros distinguish between `<` and `:ident`, then `<` can never be added to the ident grammar.

**Comment by chris-morgan** [comment]
@durka: the error is spurious; this is *definitely* a bug. The issue is purely when the repeating group is empty. Hence `foo!(a/);` working.
