### ISSUE TITLE
DwarfUnit.cpp:724: llvm::DIE* llvm::DwarfUnit::getOrCreateTypeDIE(const llvm::MDNode*): Assertion `Ty == resolve(Ty->getRef()) && "type was not uniqued, possible ODR violation."' failed.

### ISSUE THREAD

**Issue by briansmith** [rust-lang/rust#34122]
This breaks the build of *ring* on Nightly. See https://travis-ci.org/briansmith/ring/jobs/135609253. This was using rustc 1.11.0-nightly (1c975eafa 2016-06-05).

**Comment by briansmith** [comment]
See also https://github.com/rust-lang/rust/issues/28233.

**Comment by nagisa** [comment]
A duplicate of https://github.com/rust-lang/rust/issues/28233

**Comment by nagisa** [comment]
As a workaround please do not combine -C lto and -g.

**Comment by briansmith** [comment]
This is not a duplicate of #28233. #28233 is an old issue and this is a regression in the last day or so. Please reopen this.

**Comment by nagisa** [comment]
The underlying issue seems to be the same to me -C lto and -g being used together. Doesn’t removing either one get rid of the ICE?

**Comment by briansmith** [comment]
> The underlying issue seems to be the same to me: -C lto and -g being used together. Doesn’t removing either one get rid of the ICE?

IMO, it doesn't matter, because just four days ago "-C lto" with "-g" was working fine: https://travis-ci.org/briansmith/ring/builds/134868186.

**Comment by briansmith** [comment]
> IMO, it doesn't matter, because just four days ago "-C lto" with "-g" was working fine: https://travis-ci.org/briansmith/ring/builds/134868186.

OK, I've tried it, and things do start to pass again if I remove "-g". However, I think "-C lto -g" is (or should be) a very common configuration, and also it was working just days ago. So, I think we should find out what regressed and then revert that or somehow fix it otherwise.

**Comment by swgillespie** [comment]
Looks like this affects clang too: https://github.com/dotnet/coreclr/issues/5519

**Comment by dotdash** [comment]
This isn't necessarily a regression that you can fix outside of fixing #28233. It might simply be a new `#[inline]` annotation or a generic being used in a new place, or some random change that allows the compiler to optimize something in a different way. Unless you want to bisect that down to a single commit (which might still not tell you what the actual change is that triggers the bug), I don't think there's a structured approach to finding anything to revert here.

Also, the two build logs are for different versions of ring. Are you sure that the change that triggers the bug is in rust's standard lib and not in ring?

**Comment by briansmith** [comment]
OK, let's fix #28233 then.
