### ISSUE TITLE
Tracking issue for `{BTreeMap, BTreeSet}::{append, split_off}`

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#34152]

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/rust/pull/34153, #32466

**Comment by alexcrichton** [comment]
🔔 This issue is now entering its **final comment period** for stabilization 🔔 

The libs team was unfortunately a little late on stabilizations this cycle, but we're thinking of probably doing a backport of stabilizations partway through the beta cycle. This API also follows existing conventions so should be an easy stabilization!

**Comment by alexcrichton** [comment]
The libs team discussed this issue during triage yesterday and the decision was to **stabilize**. We realize that the FCP for this issue was pretty short, however, so please comment with any objections you might have! We're very willing to backport an un-stabilization for the few APIs we have this cycle.
