### ISSUE TITLE
std::io::Error and std::fmt::Error should implement PartialEq

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#34158]
Many Error types in the standard library implement PartialEq, including `std::ffi::NulError`, `std::str::Utf8Error`, and `std::env::VarError`.  This also allows Result types that include those Error types to implement PartialEq as well (since Result<T, E> implements PartialEq if both T and E do).

However, std::io::Error and std::fmt::Error do not implement PartialEq.

Please consider providing an implementation (likely via `derive`).

**Comment by TimNN** [comment]
I don't believe this will be possible for `io::Error`, since it contains a `Box<error::Error+Send+Sync>`, which does not implement `PartialEq`.

**Comment by TimNN** [comment]
`fmt::Error` on the other hand is just an empty struct, so it should indeed be trivial to provide a `ParitalEq` implementation for it.

**Comment by GuillaumeGomez** [comment]
`std::fmt::Error` already implements `PartialEq`: http://doc.rust-lang.org/nightly/std/fmt/struct.Error.html

**Comment by TimNN** [comment]
@GuillaumeGomez: then my local nightly documentation is outdated :D

**Comment by GuillaumeGomez** [comment]
Just take a look into the repo sources. I remember adding it for one of the previous types recently. :wink:

**Comment by joshtriplett** [comment]
@TimNN Ah, I see.  Unfortunate, but I don't see an obvious way around it (short of faking a PartialEq on boxed Error types that don't have one by using Display or Debug and comparing strings).

In that case, feel free to close this if there aren't any other Error types in the standard library that don't implement PartialEq.

**Comment by lambda** [comment]
It seems to me that you could manually implement `PartialEq` for `std::io::Error`, and just never consider `CustomError` to be equal; the whole point of `PartialEq` is that there may be some variants that can't be compared, so `PartialEq` is not reflexive, but there are still plenty of values for which it is meaningful to test equality.

That would allow `#[derive(PartialEq)]` for types containing a `std::io::Error`, which would make it easier to write tests like:

```rust
assert_eq!(err, MyErr::MyVariant)
```

Rather than having to go to the trouble to implement `PartialEq` by hand for your types, and never considering `std::io::Error` equal in the implementation, or using the following somewhat verbose workaround:

```rust
assert!(match err { MyErr::MyVariant => true, _ => false });
```

**Comment by GuillaumeGomez** [comment]
@lambda: Either way is fine. Want to do it?

**Comment by lambda** [comment]
@GuillaumeGomez Sure, testing out my change now, will send a PR if it works locally.

**Comment by GuillaumeGomez** [comment]
Great!

**Comment by tbu-** [comment]
@lambda For the above use case, `assert_matches!` would probably be a better solution, as it works for all `Result`s, even if the `Err` case does not implement `PartialEq`.

**Comment by lambda** [comment]
@tbu- Yes, I mentioned that in the discussion on PR #34192. I'm happy with `assert_matches!` as a solution for my use case.

**Comment by dtolnay** [comment]
As Alex wrote in https://github.com/rust-lang/rust/pull/34192#issuecomment-227477665, we would prefer not to add PartialEq for io::Error so I will close this issue. I would be open to considering an RFC to improve ergonomics of tests that need to assert an error was the one expected.

**Comment by Stargateur** [comment]
I don't really get why this have been closed since it's still an issue ["How to assert io errors in Rust?"](https://stackoverflow.com/q/57234140/7076153), it's have be viewed 12k times I think we should consider this problem.

Maybe a:

```rust
impl<T> Result<T, io::Error> {
    fn kind(self) -> Result<T, io::ErrorKind> {
        self.map_err(|e| e.kind())
    }
}
```

But that only a shortcut. Most user would only need this.

maybe a:

```rust
impl<T> Result<T, io::Error> where T: PartialEq {
    fn compare_kind(&self, other: &Self) -> bool {
        self.map_err(|e| e.kind()) == other.map_err(|e| e.kind())
    }
}
```

should allow `assert(result.compare_kind(&expected))` still a shortcut.

Maybe both.
