### ISSUE TITLE
Order of extern crate/pub mod matters suddenly

### ISSUE THREAD

**Issue by shahn** [rust-lang/rust#34212]
I have code that uses this (works on beta and stable):

    pub mod module1;
    #[macro_use]
    extern crate lazy_static;

On nightly, this fails with an error about lazy_static not being found inside module1. When I switch around the order stuff starts working again. Seems like a regression?

**Comment by TimNN** [comment]
This was probably caused by #34032 (which is also tagged as a `[breaking-change]`).

cc @jseyfried

**Comment by jseyfried** [comment]
@TimNN Yeah, this was caused by #34032 -- thanks for the cc!

@shahn #34032 changed the behavior of `#[macro_use]` on `extern crate`s to match the behavior of `#[macro_use]` on modules. For example, if the `lazy_static` macro were defined in a module `foo`,
```rust
pub mod module1; // it would not be available in this module on stable
#[macro_use] mod foo; // unless this were moved above `module1`
```
This change could be viewed as a regression or a bug-fix, depending on your point of view.

Regardless, I thought the change would be unlikely to cause breakage in practice. I reverted the change (fixing the breakage) in #34239.

cc @nrc

**Comment by shahn** [comment]
@jseyfried, I'm fine with this being a breaking change if it is deemed worth it! No problem at all. Maybe this should be discussed before #34239 gets applied?

**Comment by jseyfried** [comment]
@shahn 
> Maybe this should be discussed before #34239 gets applied?

Agreed. I think I prefer the original behavior since it means the order of items doesn't matter as much, even though the change makes `#[macro_use]` more consistent. The change was more of a side effect of #34032 than a goal.
