### ISSUE TITLE
trait method documentation: Markdown "# header" works, but is missing horizontal rule underneath

### ISSUE THREAD

**Issue by seankerr** [rust-lang/rust#34246]
"# Header Name" works when documenting impl methods, but when documenting a trait method, the result is too small, and it's missing a horizontal rule underneath. This also has the added effect that without an HTML break element, you cannot place an empty line after the header.

**Comment by QuietMisdreavus** [comment]
Current status: `<h1>` headers in trait methods are smaller because the CSS rule for h1 is different depending on whether it's in a `.docblock` that's a direct child of the main document or not. Trait methods are nested two `<div>`s deep, so they get the different, smaller rule. They've both got the bottom border, though.

![image](https://user-images.githubusercontent.com/5217170/47972501-776f4d80-e062-11e8-9cf8-be9136f4d216.png)

**Comment by GuillaumeGomez** [comment]
Problem was fixed a while ago. Closing then.
