### ISSUE TITLE
Consider using stack maps over landing pads for executing destructors

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#34393]
We may be adding LLVM stack map support for GC hooks in the future. It should be possible to leverage the same support to get rid of landing pads.

Currently, during a panic, we jump through a "landing pad" section of the function which runs destructors. We do the same for each frame in the call stack.

LLVM lets us annotate call sites with extra data, which we will use for noting GC roots. This could also be used to note the locations of data which needs dropping, a vtable pointer to the drop trait, and when necessary the location of the drop flag. Thus, when panicking we unwind the stack and call appropriate destructors by looking up the call site in the stack map.

This may be slower, but the speed of panics isn't really important in Rust. It may also increase binary sizes (I'm not sure of this, others seem to think this isn't the case). @nikomatsakis noted that this decreases the .text size, which makes the icache more efficient since in regular usage you won't be hitting the landing pads anyway.

@eddyb had some concerns (which I'm not sure I quite understand): I'm filing this issue so that they can be discussed 😄 

cc @pnkfelix

**Comment by sorear** [comment]
Idle thought: Would we be able to put the unwind stack maps into a separate section and then delete that section if `-C panic=abort` is passed to the final link, avoiding the need to ship two versions of libstd?

**Comment by Manishearth** [comment]
Yeah, that's what I was thinking. They will be in a separate section.

**Comment by Amanieu** [comment]
Couldn't you put the landing pads in a separate section as well? Though this depends on whether LLVM supports splitting a function over multiple sections...

**Comment by Manishearth** [comment]
LLVM may put the variables in a register, or optimize them somehow, so we need to be able to tell LLVM to use the final location. I don't think that's possible in a separate section without stack maps.

**Comment by Aatch** [comment]
My primary concern is that using stack maps may limit overall optimisations. I don't know a huge amount about how stack maps in LLVM work, but it seems possible that stack maps might stop certain optimisations from occurring due to the existence of a stack map.

If this isn't the case, then I'm fine with it, but if LLVM has be conservative about what it can remove because there's references in some opaque system, that'll affect all code, not just the unwind path.

**Comment by Aatch** [comment]
Ok, so I just took a look at this http://llvm.org/docs/StackMaps.html and this http://llvm.org/docs/GarbageCollection.html and it seems that it would potentially kill a lot of optimisations. All the relevant intrinsics for building the stack map act as if they read and write the given location, which almost certainly means that they can't be optimised well.

More generally, I don't think we can actually remove landing pads, since landing pads are the "run this code when you unwind through this frame" code. It's unclear to me how we'd be able to execute any code at all during unwinding without landing pads.

**Comment by nikomatsakis** [comment]
@Aatch I think we would put a pointer to the drop vtable into the stackmap as well, just as (for GC support) we need to put a pointer to some sort of tracing vtable. This would allow us to remove the landing pads.

Whether or not the result would be worse for optimization I am not sure -- keep in mind that LLVM has a wide variety of GC primitives. The newer ones are intended to permit a lot more optimization than the original set, which were fairly conservative. 

Still, it seems like this is probably *largely* an empirical question.

One thing I am also wondering is how this would interact with Window's SEH -- it seems like we might need to keep landing pads for that scenario at least.

**Comment by Aatch** [comment]
@nikomatsakis my question is though, how do you tell the unwinding code to run the destructor(s) for this frame without landing pads? Keeping in mind that this suggestion is for *non-*GC builds. Think about it, the code is chugging along and then it hits a panic, which triggers unwinding. At that point, control is mostly out of our hands and in the hands of the stack unwinder. Without landing pads, how does the stack unwinder know what to do while unwinding?

Simply saying you **can** remove landing pads isn't enough, I'd like to know about the **how**, since either it's not possible, or you know something I don't.

And again, I can't see how LLVM can do anything but keep the pointer around if you've said "by the way, something somewhere will use this pointer", I looked at most of LLVM's GC primitives, and while they seem great for GC support, they very much do not seem appropriate for non-GC usage.

**Comment by Manishearth** [comment]
> how do you tell the unwinding code to run the destructor(s) for this frame without landing pads? Keeping in mind that this suggestion is for non-GC builds. 

This doesn't need to be a GC build, there is no difference in how it's done for a GC build and a non GC build.

Basically, something like libunwind will walk up the stack. It will take each call site, and query the stack map for drop info related to that call site. From this, it will know the drop flag if it exists, where the data is, and a pointer to the drop glue for the type.

> And again, I can't see how LLVM can do anything but keep the pointer around if you've said "by the way, something somewhere will use this pointer", 

I suspect LLVM will be able to optimize this as well, because it knows how the pointer will be used.

**Comment by arielb1** [comment]
This becomes a bit more complicated with non-zeroing drop - how do we share the drop flags between the drop glue and the mutator?

**Comment by Manishearth** [comment]
The stack map contains a stack offset for the drop flag. Same thing as in the GC support.

**Comment by Aatch** [comment]
@Manishearth so we'd have to write our own stack unwinding system? That seems like a lot of work, especially since it also isn't an option on Windows.

> I suspect LLVM will be able to optimize this as well, because it knows how the pointer will be used.

How? How will it know? It can't see the calls, they're happening in this separate system that we'll have to build ourselves. All it knows that the pointer will be used, that's it.

> The stack map contains a stack offset for the drop flag. Same thing as in the GC support.

Oh wow, that just kills optimisations even more then, since each flag is absolutely required to exist at runtime because it will be read (and written) during unwinding.

This entire proposal seems to be based on the assumption that LLVM is magic and will just be able to optimise everything. When in reality, the moment you start hiding stuff from it, it has to assume that basically anything can happen.

I'd like to see something that doesn't just hand-wave away important aspects of the proposal. I get that this isn't an RFC, but I'm getting frustrated with responses that just go "oh, well, it'll just work". How will it work, and what is your evidence that LLVM will be able to perform miracles? Because I looked and the GC/stackmap intrinsics range from "assume anything can happen" to "assume almost anything can happen" in terms of their effect.

**Comment by Manishearth** [comment]
> so we'd have to write our own stack unwinding system? That seems like a lot of work, especially since it also isn't an option on Windows.

Not necessarily. And even if we do, we need to do this anyway for GC.

> Oh wow, that just kills optimisations even more then, since each flag is absolutely required to exist at runtime because it will be read (and written) during unwinding.

I was assuming that's not the case; only for cases where dynamic drop is happening. The map will have entries per-call-site, so we know what is alive and what isn't except in the case of dynamic drop. Again, this is a problem that has to be solved for GC too.

> This entire proposal seems to be based on the assumption that LLVM is magic and will just be able to optimise everything. 

It's not. This is not a concrete proposal, that's all. I am not aware of LLVM internals, this was just an idea I had and Niko/Felix thought it could work. I'm assuming magic where the GC support needs it.

**Comment by 0xpr03** [comment]
I've to disagree with the fact that the speed of panics in rust is unimportant, also we're already hitting some problems with too big binary sizes (for example on embedded systems).

**Comment by Manishearth** [comment]
This wouldn't affect the speed *much* (less than an order of magnitude).  Landing pads take up space too (possibly even less than stack maps!), on embedded usually the recommendation is panic=abort

**Comment by 0xpr03** [comment]
> on embedded usually the recommendation is panic=abort
giving problems if a thread panics, correct me if I'm wrong

**Comment by Manishearth** [comment]
> creating memory leaks on catched thread panics, correct me if I'm wrong

You can't catch a panic with panic=abort.

You shouldn't be catching panics much (is this why you are concerned about the speed of panics?); if you are then you do need landing pads anyway. If stack maps end up bloating the binary size, it will only be a marginal bloat over that for landing pads, so if you're okay with landing pads you should be okay with stack maps.

**Comment by 0xpr03** [comment]
> You can't catch a panic with panic=abort.

Ok, thanks for the correction, then my concern is inappropriate.

> You shouldn't be catching panics much 

I was thinking about crashing web server threads if for example sb tries to send you malicious data. (and ofc floods you). But then again you should probably try at these parts, don't know how it would be for certain FFI's (CGI & co).

**Comment by Manishearth** [comment]
> I was thinking about crashing web server threads if for example sb tries to send you malicious data. (

Right, in which case you pay the cost of landing pads anyway 😄 . Like I said, stack maps won't make it _much_ worse, if at all.

**Comment by eddyb** [comment]
It might be better to somehow convince LLVM to put landing pad blocks in a separate section.

**Comment by Manishearth** [comment]
If that's possible, that works too!

**Comment by steveklabnik** [comment]
Triage: no comments in two years. @rust-lang/compiler is this a feature that we still have any interest in pursuing?

**Comment by bjorn3** [comment]
I think this is fundamentally incompatible with `extern "C-unwind"` and as such should be closed.

**Comment by oli-obk** [comment]
Yea, I don't think this is actionable. Rereading the discussion gives me the impression there are things to be tried here, but without a concrete goal (code that should work?) I'm not sure where to even begin addressing the issue.
