### ISSUE TITLE
rustbuild accepts `-h` but not `--help`

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#34534]
```
$ python ../src/bootstrap/bootstrap.py -h
Usage: rust.py [options]

Options:
    -v, --verbose       use verbose output
        --config FILE   TOML configuration file for build
        --host HOST     host targets to build
        --build BUILD   build target of the stage0 compiler
        --target TARGET targets to build
    -s, --step STEP     build step to execute
        --stage N       stage to build
        --src DIR       path to repo root
    -j, --jobs JOBS     number of jobs to run in parallel
        --clean         clean output directory
    -h, --help          print this help message
$ python ../src/bootstrap/bootstrap.py --help
usage: bootstrap.py [-h] [--config CONFIG] [--clean] [-v]

Build rust

optional arguments:
  -h, --help       show this help message and exit
  --config CONFIG
  --clean
  -v, --verbose
```

**Comment by arielb1** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
Should be an easy fix! Would be quite willing to mentor anyone interested

**Comment by GlenDC** [comment]
I was investigating in fixing this issue, but it seems like `--help` works, while `-h` doesn't work. And it doesn't work because it is filtered out of `sys.argv` before we pass it onto the argument parsing?

You can see this in [`bootstrap.h#L349`](https://github.com/rust-lang/rust/blob/master/src/bootstrap/bootstrap.py#L349): `args = [a for a in sys.argv if a != '-h']`. Why is the `-h` flag filtered out? Also @arielb1 I never see the help/usage description of the first command you posted.

We're talking about the [`rust-lang/rust/src/bootstrap/bootstrap.py`](https://github.com/rust-lang/rust/blob/master/src/bootstrap/bootstrap.py) script, no?

**Comment by alexcrichton** [comment]
Ah I think that'd do it, yeah. We probably just need to filter out both `-h` and `--help` from `sys.argv` in python. The idea is that those flags should be forwarded to the Rust build system rather than the python script (the help printed for `--help`) as the python script doesn't have the full suite of options, just a subset.
