### ISSUE TITLE
Add documentation for all keywords like the primitive types' documentation

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust#34601]
Here's what I would like to be able to do:
- Visit http://doc.rust-lang.org/std/
- In the search box, type any keyword, such as `match`
- Get back comprehensive documentation about `match`'s functionality, similar to the documentation for the primitive types (ex: [pointer](http://doc.rust-lang.org/std/primitive.pointer.html))

For unused but reserved keywords, I would expect to see something along the lines of "This keyword has no current functionality but is reserved for Rust to possibly use in the future."
## Why this is important

Currently, all the details about pattern matching syntax is only documented in [the book](https://doc.rust-lang.org/stable/book/patterns.html), as far as I can tell. In the new version of the book, [we're moving away from trying to be comprehensive towards just covering the most important, most commonly used constructs](https://github.com/rust-lang/book/issues/115). But if we remove documentation about, say, the precedence of `|` and match guards, where will people go to learn about it? ([The Reference doesn't have anything about that stuff either](https://doc.rust-lang.org/nightly/reference.html#match-expressions)).

Furthermore, how is a new rustacean supposed to know that, say, `i32` and `pointer` will return results but `match` and `where` will not?

I'm going to research how the primitive types are documented, but wanted to file this for discussion purposes in the meantime.

**Comment by brson** [comment]
It's hard for me to see how this fits into rustdoc, since rustdoc is primarily for documenting APIs (the primitives are a special case since they *could* be library types). This seems to call for a more integrated set of documentation that is searchable and cross-referable across sources. Which would be great.

**Comment by GuillaumeGomez** [comment]
It's indeed difficult to see how it could be integrated. Maybe an hybrid system: if some specific keywords are entered, we propose a link to the corresponding chapter of "The" Book?

**Comment by carols10cents** [comment]
But this info is being removed from the book, it should go somewhere else.

**Comment by GuillaumeGomez** [comment]
Really? That complicates things a bit. We should then create a glossary for keywords.

**Comment by GuillaumeGomez** [comment]
And while I think about it: cc @steveklabnik

**Comment by GuillaumeGomez** [comment]
So what should we do about it? I extended docs search quite a bit so at this point, I think we could create something similar that for primitives (ie, a tag and then you put your doc on it), and then we'd be mostly done (just a bit of design to conclude). Does that sound good to everyone?

cc @rust-lang/docs 
cc @rust-lang/rustdoc

**Comment by ollie27** [comment]
I'm going to be honest, I not really a fan of this. Keywords aren't like anything else that rustdoc documents so it seems weird to shoehorn them in. Maybe what we really need is a combined search which covers the `std` API, the books, the reference, the error index, etc... Then we could add a new book to cover all the keywords assuming they're not documented sufficiently elsewhere.

**Comment by DevQps** [comment]
@GuillaumeGomez @steveklabnik I guess this issue is kind of resolved? I checked the Rust docs [here](https://doc.rust-lang.org/std/keyword.let.html) and I see that you can already search for keywords (`let`, `struct` and `enum` have documentation for example).

I guess that means we can close this issue now? I did however found out that there are quite some keywords that do now have documentation yet. I went through the entire list of reserved keywords and these do currently not have any documentation.

**Keywords**:
- break
- use
- dyn
- else
- in
- match
- mod
- move
- mut
- pub
- ref
- return
- self
- static
- super
- trait
- type
- unsafe
- while
- where

Reserved for Future Use:
- abstract
- async
- become
- box
- do
- final
- macro
- override
- priv
- try
- typeof
- unsized
- virtual
- yield

Personally I wonder if keywords like `else`, `break` and `while` need some documentation since they are so basic to almost all programming languages. But I'll leave that up to you guys. I do however think that it would be better to create a new issue with a checklist and close this one, since it felt like the whole discussion here was about "how" we were going realize searching for keywords in the docs, instead of actually doing it.

**Comment by ollie27** [comment]
There actually already is a tracking issue for this: #51451. I don't know why both of these issues are open.

FWIW I still don't think adding these docs to the `std` docs was a good idea but I guess that ship has already sailed. Maybe we can turn them into a separate keyword book at some point instead though.

**Comment by DevQps** [comment]
@ollie27 Ahh I guess we can close this one now then. I do think we at least make it more clear somehow that you can also search for keywords there. I mean currently it feels like you can only search for stdlib documentation there, but not for actual keywords.

**Comment by steveklabnik** [comment]
> FWIW I still don't think adding these docs to the std docs was a good idea but I guess that ship has already sailed. Maybe we can turn them into a separate keyword book at some point instead though.

I am also not really a fan but people seemed to like it.

**Comment by pravic** [comment]
It would also be nice to add the list of keywords to the [main std page](https://doc.rust-lang.org/nightly/std/index.html), similar to the [modules](https://doc.rust-lang.org/nightly/std/index.html#modules) and [macros](https://doc.rust-lang.org/nightly/std/index.html#macros) sections.

Because right now is the only way to browse them is to open a documentation page and scroll down to the keywords list in the TOC.

**Comment by GuillaumeGomez** [comment]
@pravic: it's there: https://doc.rust-lang.org/nightly/std/index.html#keywords, or did I misunderstood what you meant?

**Comment by pravic** [comment]
@GuillaumeGomez almost :)

I meant a link in the TOC on the left (the one below the "See all std's items" section).

**Comment by GuillaumeGomez** [comment]
Oh I see! Can you open an issue for this please? (and cc me on it)

**Comment by barkanido** [comment]
would be very happy for formal documentation about `dyn`

**Comment by GuillaumeGomez** [comment]
Can you open a separate PR for it and ping @rust-lang/rustdoc on it please?

**Comment by poliorcetics** [comment]
I checked the keywords in use that now have documentation (in the `master` branch, it may not have reached stable yet):

**Done:**

- as
- async
- await
- break
- const
- continue
- crate
- dyn
- else
- enum
- extern
- fn
- for
- if
- impl
- in
- let
- loop
- match
- move
- pub (very short, basically a link to the reference, when the others are often longer)
- struct
- true
- use
- while

**To do:**

- false (being the logical inverse of `true`, maybe pointing to the docs for `true` is enough ?)
- mod
- mut
- ref
- return
- self
- Self (note the uppercase `S`)
- static
- super
- trait (the current doc uses the word `class of types`, I think it may be confusing to new rustaceans coming from OOP, maybe `group of types with a similar objective` or something along those lines would be better)
- type
- union
- unsafe
- where

**Comment by poliorcetics** [comment]
The last PR for this is #73943 (unsafe keyword), after that it will be done !
