### ISSUE TITLE
Create a toplevel build driver that encapsulates building and testing

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#34665]
Servo uses mach for this (as a thin wrapper around cargo), but we can just use argparse and the rustbuild scripts.

The idea is that everything you do with the build system will be through one script. So, building would be `./rustbuild build`, or `./rustbuild build --stage 1`. Testing would be stuff like `./rustbuild test-all` or `./rustbuild test-rpass`. 

The advantage here is that it's self-documenting. Right now we have make targets that aren't even greppable because they are assembled at runtime. This way, you never have to deal with make, and [you have help pages like this](https://gist.github.com/Manishearth/815349ffdd44b45cc74340caa51bb3ec) which let you find exactly what you're looking for.

cc @jonathandturner

**Comment by alexcrichton** [comment]
I definitely agree! The idea is that the `src/bootstrap/main.rs` build system (rustbuild) is exactly this. That's not callable directly so there's a thin python script `src/bootstrap/bootstrap.py` which is the actual entry point to the build system (downloads and compiles the real build system).

The current long path of `src/bootstrap/bootstrap.py` is horribly unergonomic but it's also because rustbuild hasn't been official enough to have a file at the top of the repo. I hope to move it eventually to basically `b.py` at the top of the repo and then we can say things like:

```
# build rust
$ python b.py

# test rust
$ python b.py test

# ...
```

All of this involves actually designing the CLI as well, which we probably want to put some thought into. Right now rustbuild takes various flags (`--step` being the most important) but it was not designed for ergonomics in mind, just flexibility.

**Comment by Mark-Simulacrum** [comment]
We have `x.py` now, with a relatively ergonomic interface; should this be closed?
