### ISSUE TITLE
rustbuild lacks make install

### ISSUE THREAD

**Issue by Aatch** [rust-lang/rust#34675]
I decided to switch to using rustbuild recently and discovered that there is no `make install` for rustbuild. This is somewhat annoying as it's not very clear how exactly to do a full install of the just-built compiler given what's there.

**Comment by alexcrichton** [comment]
Oh dear, this is a very good point! I ended up doing 90% of the work without going all the way there!  So it turns out that `make install` is actually a [very thin wrapper](https://github.com/rust-lang/rust/blob/master/mk/install.mk#L17-L31) around `make prepare` which in rustbuild is just [`--step dist`](https://github.com/rust-lang/rust/blob/731d37561971d80f5d7ccaba8c2affcf39965917/src/bootstrap/build/step.rs#L563-L583). This should definitely be implemented!

The step for implementing this are likely along the lines of:

* Add an `install` target to [this array](https://github.com/rust-lang/rust/blob/731d37561971d80f5d7ccaba8c2affcf39965917/src/bootstrap/build/step.rs#L42-L147) with the one argument of a `stage.
* Modify [this function](https://github.com/rust-lang/rust/blob/731d37561971d80f5d7ccaba8c2affcf39965917/src/bootstrap/build/step.rs#L320) to say that the dependency of the `install` target is the `dist` target
* Add a case to [this loop](https://github.com/rust-lang/rust/blob/731d37561971d80f5d7ccaba8c2affcf39965917/src/bootstrap/build/mod.rs#L227-L447) to dispatch the to the right step
* Add an `install` function to [`dist.rs` most likely](https://github.com/rust-lang/rust/blob/731d37561971d80f5d7ccaba8c2affcf39965917/src/bootstrap/build/dist.rs) to install local artifacts.
* In the `install` function, extract the tarball created by the `dist` step, run the `install.sh` script for the std pkg, the rustc pkg, and optionally the docs pkg

This shouldn't be *too* hard but I'm not going to tag this with `E-easy` as it's somewhat difficult. Especially around handling `sudo` vs not-`sudo` I think could get a little tricky, but the gist is that we should probably just refuse a bootstrap build or rustbuild build if the `$USER` is `root`, having `make install` [delegate to the right user](https://github.com/rust-lang/rust/blob/731d37561971d80f5d7ccaba8c2affcf39965917/mk/install.mk#L20) to prepare the installation. Then the `make install` target could just make sure to install to the right location regardless of the user.

**Comment by alexcrichton** [comment]
As [pointed out by](https://github.com/rust-lang/rust/issues/34687#issuecomment-231028488) @jirutka we should be careful to respect GNU standards here for environment variables and such when implementing this.

**Comment by alexcrichton** [comment]
Fixed in #35641
