### ISSUE TITLE
BTreeMap/BTreeSet should say clearly how they behave if the comparison function is incorrect

### ISSUE THREAD

**Issue by rocallahan** [rust-lang/rust#34696]
It's not clear what the consequences are if you provide a buggy comparison function. Can that trigger memory unsafety? Infinite loops? Or just incorrect results from methods? Whatever the guarantees are, documentation in the code explaining how they're met would also be helpful.

**Comment by Thiez** [comment]
I think it is undesirable to mandate any particular behavior when preconditions are not met, except that no memory unsafety should occur. However I don't think memory safety should even be mentioned because it is the default in Rust, and mentioning "not meeting the preconditions will not result in memory unsafety" explicitly in one place may cause people to start doubting all the places where this isn't mentioned explicitly (e.g. everywhere else).

**Comment by rocallahan** [comment]
Sounds fair.
