### ISSUE TITLE
Structs can be cloned in impls even when Clone is not derived/implemented

### ISSUE THREAD

**Issue by Luminarys** [rust-lang/rust#34746]
Using `self.clone()` or `self.to_owned()` in an impl function for a struct works even when the trait isn't derived or implemented and returns an improper type.

Example:
```rust
struct S;
impl S {
    fn foo(&self) -> &S {
        self.clone()
    }
}
```
In the example if a `#[derive(Clone)]` is added to the struct, the code fails to compile as the returned type is different from the one specified in the function.

This can be rather frustrating to deal with if you end up forgetting to derive/impl Clone for a struct and subsequently get error messages in an impl about an improper type or borrow checker issues because the bad `.clone()` or `.to_owned()` isn't shown as being unimplemented but rather as returning an `&ptr` rather than an owned copy.

**Comment by sorear** [comment]
`Clone` isn't implemented for `S` in your example, but it is implemented for `&S`: shared references automatically implement `Copy` and `Clone`.  So you're doing a no-op clone on the self *pointer*. If you add a `Clone` impl for `S`, then the compiler will resolve `S::clone` instead of `<&S>::clone`, and then you get the type error.

**Comment by Luminarys** [comment]
Thanks for the clarification, I wasn't aware of the automatic clone implementation. I guess that makes this a non-issue then, so I'll be closing it.
