### ISSUE TITLE
Use only one personality function instead of 2 on Unix

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#34786]
Right now we have two personality functions:

* `rust_eh_personality`
* `rust_eh_personality_catch`

The rationale is described in length [here](https://github.com/rust-lang/rust/blob/3085ec78487712ed77a506d9cba8d69cd3a44684/src/libpanic_unwind/gcc.rs#L11), but the gist is that we're currently "too lazy" to parse DWARF metadata, so we use `rust_eh_personality` for "all Rust functions in the world" and `rust_eh_personality_catch` for the one function allowed to catch a panic. The former personality simply runs all cleanups, and the latter personality simply catches all Rust exceptions.

This split makes it easy for us to define, but when a personality is run it should also have access to DWARF metadata about the call site it's running for. This metadata *should* indicate whether it's intended to catch or not, so we should in theory be able to read out the DWARF metadata and figure out what to do, allowing us to have one personality function instead of two.

The major downside of having two personality functions is that LLVM is unable to inline two functions that have different personalities. This unfortunately means that `catch_unwind` can have [performance problems](https://github.com/rust-lang/rust/issues/34727) if we don't inline enough. We're currently using zero-cost exceptions on Unix, but what we're actually doing unfortunately isn't zero cost!

This is only one piece of the puzzle towards fixing the [performance issues mentioned](https://github.com/rust-lang/rust/issues/34727), but it's an important one!

cc @vadimcn

**Comment by alexcrichton** [comment]
One possible route to an implementation is just using other off-the-shelf personalities, perhaps we could just use a C or C++ one so long as we can find it on all platforms.

**Comment by vadimcn** [comment]
We actually already have most of LSDA parsing code [here](https://github.com/rust-lang/rust/blob/master/src/libpanic_unwind/dwarf/eh.rs#L55).  Currently it's only used for x86_64-pc-windows-gnu.
If we want to use it everywhere, we'll need to implement the rest of [#ifdef'ed stuff](https://github.com/gcc-mirror/gcc/blob/trunk/libgcc/unwind-c.c#L120) in gcc_personality.  I was reluctant to do it because of the big testing matrix this involves, whereas the existing solution seemed to work just fine.   But if there's a compelling reason to do it...

**Comment by alexcrichton** [comment]
I think it'd be also fine to slowly bring platforms online with this strategy, for example we could test it out on 64-bit Linux first and then start doing the same change for other platforms and architectures.
