### ISSUE TITLE
Lint pass to warn about catchall cases

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#3482]
#3481 arose because ```kind::check_expr``` had an ```_``` case in its ```match```, so when ```expr_struct``` got added as a case, the ```_``` case covered it, which is not what was intended. A lint pass to warn about ```_``` cases would be good. It could be less annoying if it only complained about a ```_``` where the scrutinee has an enum type and the ```_``` might match two or more different variants.

Since whether to use ```_```s is a matter of taste, this should be off by default.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
