### ISSUE TITLE
`Fn`s with different arguments should be different types

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#34868]
Currently you can't write something like this:
```rust
pub trait MyTrait {
}

impl<F> MyTrait for F where F: FnMut() {
}

impl<F> MyTrait for F where F: FnMut(usize) -> usize {
}
```
This results in an error about conflicting implementations. This is because there might exist a type that implements both `FnMut()` and `FnMut(usize) -> usize`. In reality such a type will of course never exist.

Potential dupe of #19032 but I'm not sure

**Comment by TimNN** [comment]
Actually, I'm pretty sure that it is easily possible for a type to implement both, since the Fn traits can be implememted for a type like any other traits, ie. you can do `struct A; impl Fn() for A { ... }`.

**Comment by nagisa** [comment]
Once implementing `Fn`-traits is [made stable](https://github.com/rust-lang/rust/issues/29625), what @TimNN said is correct. Such case could also occur once we get something like default arguments, resulting in one value implementing multiple ways to call it – and thus multiple `FnOnce` implementations.

This issue is likely inactionable.

**Comment by arielb1** [comment]
Yea. Not a bug. Implementing `FnOnce` with different input types is intentionally allowed.
