### ISSUE TITLE
.min and .floor operations for f64 types are non-functional on MIPS

### ISSUE THREAD

**Issue by johnnyman727** [rust-lang/rust#34906]
I'm building [Rust code for Tessel 2](https://tessel.io) using some instructions created by @badboy [here](https://gist.github.com/badboy/8b951981aaf8bc1700b4703f9c201484).

Simple scripts compiled on the Rust playground and my personal computer work fine but fail for different reasons on Tessel (which has a MIPS architecture).

```
let testVal: f64 = 546.54;
assert(testVal.float(), 546); // Returns 546.54 instead
assert(testVal.min(0)); // Returns 546.54 instead
```

Let me know if there are any other details I can provide to help debug!

**Comment by nagisa** [comment]
Output of `--emit=llvm-ir,asm` (should output two files with `.ll` and `.s` extensions) would be useful.

> testVal.float()

Contradiction with the issue title. Moreover `assert` is a macro (you’re missing a `!`) and `assert!(testVal.floor(), 546);` wouldn’t compile due to a type error.

**Comment by kevinmehall** [comment]
I suspect this is due to a mismatch of float ABI (Tessel's OpenWrt uses soft float, while Rust's mipsel-unknown-linux-gnu default target uses hard float).

The following program succeeded on Tessel 2 with a [custom target.json](https://gist.github.com/kevinmehall/16e8b3ea7266b048369d#file-tessel2-json). I rebuilt libstd using that target, using a compiler-rt built with the GCC from the OpenWrt build system.

```rust
fn main() {
	let test_val: f64 = 546.54;
	assert_eq!(test_val.floor(), 546.0);
	assert_eq!(test_val.min(0.0), 0.0);
	println!("ok");
}
```

So this isn't really a rust-lang/rust bug, beyond a :+1: for something like [RFC 1133](https://github.com/rust-lang/rfcs/pull/1133) that makes it easier to use customized target options.

**Comment by japaric** [comment]
@kevinmehall Note that you are mixing different ABIs here: The OpenWRT toolchain is using uclibc and the Rust target (`mips*-*-*-gnu`) expects glibc. These two libcs are not ABI compatible (actually, uclibc never became ABI stable). This combination is not guaranteed to *always* work.

(Thought most of the problems you observed are likely caused by the float ABI mismatch.)

**Comment by alexcrichton** [comment]
Thanks for the investigation @kevinmehall! Sounds like this is expected from ABI differences, so I'm going to close.

**Comment by johnnyman727** [comment]
Thanks @nagisa for pointing out the syntax/functional issues with my example. I've updated for posterity's sake.

Thanks @kevinmehall for investigating the ABI.
