### ISSUE TITLE
Add i586-unknown-linux-gnu rustc binaries

### ISSUE THREAD

**Issue by goertzenator** [rust-lang/rust#35045]
Filing this issue as recommended [here](https://github.com/japaric/rust-cross/issues/24).

`rust-std` binaries are provided for i586-unknown-linux-gnu, but not `rustc`.  Can we have `rustc` binaries too?

I am working on an embedded Vortex86 CPU(not quite i686).  I would like to have a `rustc` that targets i586 by default because...
- I was unable to build my own rustc that targets i586 by default.
- It is awkward to integrate `--target` and the resulting target path changes into my build system.

**Comment by ranma42** [comment]
Be aware that even the i586-unknown-linux-gnu target for rust actually requires some features that might not be available on i586-compatible processors, as it basically means i686 (for example it might use CMOV).

**Comment by goertzenator** [comment]
Can you tell me more about this?  I assumed I could use Rust on i586 but maybe that's not the case.  I've got a "hello world" test program running on i586 but it would be very frustrating to hit a brick wall as I write more complex code.

**Comment by petevine** [comment]
@goertzenator
I already verified almost a year ago (before that target was officially available) a locally bootstrapped i586 target was fully compatible with pentium-class processors. 

Can't vouch for the official distribution, of course, but if you were to correctly cross-bootstrap it yourself, you'll be absolutely fine. (otherwise it's a recent bug)

**Comment by ranma42** [comment]
@goertzenator sorry, my bad, I was remembering incorrectly, the unusual target is `i686` (which actually targets pentium4, as per Clang's defaults). The `i586` target requires only a `pentium`-compatible processors (as per @petevine's [PR](https://github.com/rust-lang/rust/pull/31629/files#diff-9918f1f1e58581023cc3a5e20be3252fR19)), thus it should work just fine.

**Comment by goertzenator** [comment]
Thanks for clearing that up.  Panic attack averted.

**Comment by japaric** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
Most of the changes necessary here will be done in https://github.com/rust-lang/rust-buildbot rather than this repository. The changes may not be super easy to do as our 32/64 musl situation is a bit hectic, but [`master.cfg`](https://github.com/rust-lang/rust-buildbot/blob/master/master/master.cfg) is the place to look, namely [this array of targets](https://github.com/rust-lang/rust-buildbot/blob/a35c53e21a789cc782ec51f2fdefc1e3f8767c42/master/master.cfg#L231-L271). 

We have an [existing entry](https://github.com/rust-lang/rust-buildbot/blob/a35c53e21a789cc782ec51f2fdefc1e3f8767c42/master/master.cfg#L253) for this target and it'll need to get `host: True` somehow to get [picked up later](https://github.com/rust-lang/rust-buildbot/blob/a35c53e21a789cc782ec51f2fdefc1e3f8767c42/master/master.cfg#L1811-L1818) when we configure the builders. That *may* just work dropping that configuration in (and enabling rustbuild), but it'd probably want to get tested out locally just to confirm.

**Comment by Mark-Simulacrum** [comment]
Judging by https://forge.rust-lang.org/platform-support.html, I believe that this is a tier 3 target today. @alexcrichton Are we interested in tracking "we want X target"? It feels like the kind of thing where tracking it isn't all that helpful, though I could be wrong.

**Comment by alexcrichton** [comment]
Nah we typically haven't tracked this in the past, although it would be good to know what are the "most popular" candidates for promotion/demotion among tiers

**Comment by Mark-Simulacrum** [comment]
Okay, I'm going to close in that case. If author is still interested, I'd recommend starting a thread on internals.rust-lang.org to gather interest and then propose changes in an issue here with a link.
