### ISSUE TITLE
Tracking issue for global-asm support (RFC 1548)

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#35119]
Tracking issue for `global_asm!` macro rust-lang/rfcs#1548:

**Note that this is intended as a (particularly) experimental feature.** 

Feedback on its design is required, as well as comparisons with [naked fns](https://github.com/rust-lang/rust/issues/32408).

**Comment by jackpot51** [comment]
# Don't take away naked functions!!!!!!!!!!!!!!!!!!!

They are a crucial component of building operating systems in Rust.

Without naked functions, it is impossible to do context switching without moving huge amounts of code into assembler.

**Comment by nikomatsakis** [comment]
@jackpot51 more detailed examples would be great :)

**Comment by nikomatsakis** [comment]
@jackpot51 but rest easy, I don't think we're in any hurry to make firm decisions here. :)

**Comment by ticki** [comment]
@nikomatsakis They're used in anything from interrupt handler to context switches. I would cry for 10 years straight if you removed them.

**Comment by steveklabnik** [comment]
To make this concrete, here is a PR where I went from regular old `asm` to `naked fn`: https://github.com/intermezzOS/kernel/pull/49/files

All that setup code in `src/src/asm/interrupt_handlers.asm` was able to go away; the duplication between the `extern` declarations in `src/interrupts/src/lib.rs` was able to go away... much, much, much nicer.

**Comment by jackpot51** [comment]
Thanks @steveklabnik for showing the potential of `#[naked]`. Our experience in Redox was similar

**Comment by parched** [comment]
Regarding having compile time constants and unmangled labels in it, would it possible to have separate procedural macro that did this? Something like `unmangle!(ident)` and `eval!(expr)` that produced string literals. Or is that not possible?

If a general way like that wouldn't work then something like the way [`armcc`](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0472m/chr1359124254797.html) does it would be good.

**Comment by nagisa** [comment]
I do not see how any naked function is not trivially convertible to a `global_asm!` or vice-versa, though (examples much appreciated). For example, you could have a `naked! { fn peach() { /* asm goes here */ }` which expands to `global_asm!` as an implementation of naked functions. Making `global_asm!` just a wrapper over naked functions seems also plausible to some extent.

Otherwise, I agree with Niko, that nobody is making any decisions anytime soon, but would like to add that  seeing quality of naked function implementation, its future looks bleak.

**Comment by eternaleye** [comment]
@nagisa: I agree with you on naked-functions-over-global_asm, but I actually disagree on the inverse.

In particular, it relies on doing awful Duff's Device-like tricks, where asm that's syntactically inside a function is treated semantically as if it was global. If Rust ever grows a principled handling of asm, that sounds like an immense obstacle and/or footgun.

**Comment by nikomatsakis** [comment]
On Fri, Jul 29, 2016 at 03:49:10PM -0700, eternaleye wrote:
> @nagisa: I agree with you on naked-functions-over-global_asm, but I actually disagree on the inverse.

To clarify: do you mean "simulating global asm using a dummy naked function is a hack"?

**Comment by eternaleye** [comment]
@nikomatsakis
> To clarify: do you mean "simulating global asm using a dummy naked function is a hack"?

In essence, yes.

**Comment by whitequark** [comment]
I am in favor of this feature. My problem is that I need to use ARM EHABI directives inside assembly, however LLVM does not support them inside `call asm` instructions, and there is no workaround (specifically, `.save` must come after `.fnstart` but the context of `call asm` is as-if there was no `.fnstart` so it asserts in the parser; and I cannot specify `.fnstart` inside the `call asm` itself since it would break in a similar way after codegen then).

Of course, this is just one particular bug in LLVM (that I'm not going to fix, personally, I have better things to do). Even if it was fixed, however, I am sure there are other instances where assembly within a naked function does not behave in the same way as module-level assembly, and it would be unwise to assume that all problems related to those can be worked around. If they have to be fixed upstream, then there is at least a year of delay before the fix trickles down and the crate becomes usable on crates.io.

**Comment by mrhota** [comment]
btw, visitors from the future, I'm working on this.

**Comment by mrhota** [comment]
What needs to happen for this feature to become stable?

**Comment by cramertj** [comment]
@mrhota This is blocked on having any form of `asm` stable-- see discussion on https://github.com/rust-lang/rust/issues/29722

**Comment by dvc94ch** [comment]
> This is blocked on having any form of asm stable-- see discussion on #29722

@cramertj can you please explain? As I understand it the inline asm is unstable because the [inline-asm-contraint-string](https://llvm.org/docs/LangRef.html#inline-asm-constraint-string) may change at any time and is also llvm specific which would tie rust to the llvm backend. But I don't see the same issue with global_asm! since it should conform to the architecture's assembler manual and should be possible to implement with any backend.

cc @japaric

**Comment by japaric** [comment]
> But I don't see the same issue with global_asm! since it should conform to the architecture's assembler manual

Does it though? It probably does when it comes to the actual instructions, but, for example, the `global_asm!` syntax (which assume is the same as LLVM's syntax) for ARM directives differs from what's specified in the [ARM Compiler Toolchain Assembler Reference](http://infocenter.arm.com/help/topic/com.arm.doc.dui0489f/DUI0489F_arm_assembler_reference.pdf). In `global_asm!` and in gas (GNU assembler) I would write `.global FOO` whereas the ARM manual says I should write `EXPORT FOO` or `GLOBAL FOO`.

Apart from the syntax around directives I'm a bit concerned about directives letting you do stuff with symbols that you can't do in pure Rust. Setting the section name in `global_asm!` seems OK because it's equivalent to Rust's `link_section` attribute but directives also let you create weak symbols and weak aliases which is not possible to do in pure Rust. Should Rust catch up in terms of symbol manipulation before we stabilize `global_asm!`? If it doesn't people may rely more on `global_asm!` (which we don't have much control over since it's LLVM's code) than if it did and I'm not sure that's a good thing.

It might be worth to preprocess the `global_asm!` string and whitelist some directives and feature gate the others. Mostly to make sure we are not exposing unintended features (like [`.abort`](ftp://ftp.gnu.org/old-gnu/Manuals/gas/html_chapter/as_7.html#SEC68) which gas considers as deprecated).

**Comment by parched** [comment]
@japaric 
> the `global_asm!` syntax (which assume is the same as LLVM's syntax) for ARM directives differs from what's specified in the ARM Compiler Toolchain Assembler Reference.

FWIW that's the old version of the Arm Compiler, version 6+ uses LLVM, so is the same as `global_asm!`

> It might be worth to preprocess the `global_asm!`

Seems reasonable to me.

**Comment by dvc94ch** [comment]
For RISCV there is a wip [assembler manual](https://github.com/riscv/riscv-asm-manual/blob/master/riscv-asm.md) that the gcc and llvm backends intend to follow. Maybe we can enable it for architectures where this isn't a problem? :innocent:

**Comment by whitequark** [comment]
> Maybe we can enable it for architectures where this isn't a problem?

I don't think you can do that, because (as I understand it) e.g. binutils as always recognizes certain extensions that are common to all platforms. So people could write code relying on those and it'll break on e.g. llvm as.

**Comment by maccarro** [comment]
What is blocking this feature from becoming stable?  We're relying on this feature for OS development and would like to be moving towards using a stable toolchain.

**Comment by mark-i-m** [comment]
I might be wrong, but my impression is that we are leaning towards inline asm instead of this...

Personally, I find inline asm + naked fns to be a cleaner solution that composes better and is slightly more portable.

**Comment by mjbshaw** [comment]
I hope `global_asm!` doesn't get abandoned in favor of `asm!`. Unless `asm!` becomes a superset of `global_asm!` that supports stuff like `.p2align`, `.ios_version_min`, `.cfi_*`, custom GCC exception tables, etc.

**Comment by mark-i-m** [comment]
@mjbshaw I’m curious if you can give more details of your use case. It seems like the vast majority of use cases can be served by naked fns and inline assembly, where as global-asm is barely a step away from just using an assembler and linker manually.

What are the concrete advantages to using global-asm instead of writing a .S file and linking it with your program? Is it just convenience?

**Comment by mjbshaw** [comment]
@mark-i-m Convenience is my primary motivation. If `rustc` (and `cargo`) could consume assembly files without build.rs (much like how gcc and clang can consume assembly files) then I would find that to be convenient enough for my own needs.

But convenience aside, there's one issue with using external assembly files: you can't refer to private symbols in the Rust code anymore. For example:

```rust
global_asm! {r#"
  .section  __TEXT,__text,regular,pure_instructions
  .globl  _do_stuff_in_asm
_do_stuff_in_asm:
  # ... code that consumes L_SPECIAL_PRIVATE_SYMBOL ...
  retq

  .section	__TEXT,__special_section
L_SPECIAL_PRIVATE_SYMBOL:
	.asciz	"foo"
"#}

pub fn do_stuff_in_rust() -> &'static [u8; 4] {
  extern "C" {
    #[link_name = "\x01L_SPECIAL_PRIVATE_SYMBOL"]
    static foo: &'static [u8; 4];
  }
  return unsafe { foo };
}
```

In this example, both the Rust code and the global assembly can use `L_SPECIAL_PRIVATE_SYMBOL`. But if the global assembly is separated out into a separate assembly file, then the Rust code can no longer access `L_SPECIAL_PRIVATE_SYMBOL` (unless the symbol is made public instead of private, but that's not really desirable and sometimes isn't feasible depending on the platform and the symbol in question).

**Comment by mark-i-m** [comment]
Yeah, I have felt those pain points too, global asm feels like a bit of a sledge hammer for that use case IMHO.

What if instead one was able to just pass .S files to rustc, and the compiler would give them access to private no_mangle functions without necessarily making them public in the final binary?

Eg `rustc kernel.rs arch/entry.S`

I guess one benefit of global-asm is that it also lets you do conditional compilation to include different asm for different targets...

**Comment by mark-i-m** [comment]
One other data point: I find myself still using a .S file and manually invoking the assembler and linker because I want to position certain sections of the binary at certain locations.

This gives me the idea of turning global asm into  a new attribute:

```rust
#[cfg(target-arch=“x86-64”)]
#[asm(“arch/entry.S”, linker-args=“...”)]
```

**Comment by gz** [comment]
FWIW passing .S files to rustc seems like a good way to go about it, without introducing language features/complexity for such (arguably niche) situations.

**Comment by GuillaumeDIDIER** [comment]
Is there any difference between having global_asm! and having rustc able to eat .S files. I think the issues with either one are the same, and that supporting either or both is probably the same work.

(But I may be mistaken).

Consequently why not support both.

**Comment by Aaron1011** [comment]
How (if at all) does this interact with inline ASM?

**Comment by mark-i-m** [comment]
It seems pretty orthogonal to me. IIUC, it uses a different LLVM feature altogether. I suppose one could define labels in a global asm and reference them from inline asm, though...

**Comment by luojia65** [comment]
This is very useful in operating system development. I may define global constant in producal macros:

```rust
#[proc_macro]
pub fn boot_page_sv39(item: TokenStream) -> TokenStream {
    println!("{:?}", item);

    quote!(
        #[repr(align(4096))]
        #[repr(C)]
        struct __BootPage([usize; 512]);
        #[export_name = "_boot_page"]
        static __BOOT_PAGE: __BootPage = __BootPage([0; 512]);
        global_asm!(".equ _boot_satp_mode, 8");
    ).into()
}
```

Which is not able to be replaced by Rust's `const` by now, and saves `.data` section length (sometimes I have to align to 4K, thus this could be a big difference in storage).

**Comment by Mic92** [comment]
Is it possible to generate position independent code with `global_asm`?

I tried

```rust
#[cfg(target_arch = "x86_64")]
global_asm! {r#"
.global _start
_start:
  mov %rdi, %rsp
  call main
"#}
```

However the `main` address it not position independent which causes a segfault at runtime.
This is possible with naked functions:

```rust
 #[no_mangle]
 #[naked]
 pub unsafe fn _start() {
   // call here is pic
   #[cfg(target_arch = "x86_64")]
   asm!("mov rdi, rsp", "call main");
 }
```

**Comment by Mic92** [comment]
Never mind. my actual issue was is that inline asm is using intel syntax, while `global_asm` is using gas. So this is the fix:

```rust
#[cfg(target_arch = "x86_64")]
global_asm! {r#"
.intel_syntax noprefix
.global _start
_start:
  mov rdi, rsp
  call main
"#}
```

**Comment by jgouly** [comment]
It would be nice if `global_asm!()` could support specifiers like sym/const that the inline `asm!()` does. This would allow using symbol names in `global_asm!()` without using `#[no_mangle]` and using `size_of::<Struct>()` without hardcoding the values.

**Comment by eddyb** [comment]
Noticed the error reporting was suboptimal and filed #81751 (though there might not be anything we can do without changing LLVM).

**Comment by dancrossnyc** [comment]
`global_asm!()` now supports at least `const` parameters, which is really cool, but also surprising if you're using it with `include_str!()` to bring in, say, a `.S` file that has a comment that includes curly braces. It would be really awesome if there were some way to assert that a particularly invocation of the macro didn't need or want expansion....

**Comment by Amanieu** [comment]
@dancrossnyc I've added a `raw` option in #86599 which should address this problem.

**Comment by dancrossnyc** [comment]
Thank you so much!

**Comment by wrenger** [comment]
I am trying to convert my att asm to intel (for use with `global_asm` from 1.56.0-nightly (25b764849 2021-08-04)), but i am not really able to convert the x86 long jump instruction:

```asm
.att_syntax
   	ljmp $0x8, $start_high
```

So far i tried: `jmp 0x8:start_high`, `ljmp 0x8, start_high` or `jmp 0x8, start_high`...

Any ideas?

PS: This is very x86 os specific and it may be an llvm problem. So this discussion maybe the wrong place for that, sry if that's the case.

**Comment by dancrossnyc** [comment]
Note: this doesn't address the question about Intel syntax for a long jmp, but if it's easier, `global_asm!` supports `options(att_syntax)` so that you can continue using AT&T syntax if you like.

**Comment by Amanieu** [comment]
I think the syntax is `jmp far 0x8:start_high`.

**Comment by wrenger** [comment]
> Note: this doesn't address the question about Intel syntax for a long jmp, but if it's easier, `global_asm!` supports `options(att_syntax)` so that you can continue using AT&T syntax if you like.

Well I like the intel syntax more, but I am considering it. Currently I'm switching syntax only for this instruction with `.att_syntax`, which isn't that great either.

> I think the syntax is `jmp far 0x8:start_high`.

Unfortunately this also fails with an `unknown token` error (similar to jmp without far).

```
error: unknown token in expression
   |
note: instantiated into assembly here
  --> <inline asm>:58:13
   |
58 |     jmp far 0x8:start_high
   |                ^
```

**Comment by ketsuban** [comment]
Currently I am using `global_asm` in the simple form documented by the Rust Unstable Book, to include an external assembly file containing [a header whose integrity is checked by the firmware on startup](https://problemkaputt.de/gbatek.htm#gbacartridgeheader) and some initialisation code which calls my main function. It is absolutely the best tool for the job short of `rustc` consuming external assembly files directly - using a naked function, while possible, would be a mess of workarounds since the code never gets called from Rust.

**Comment by phip1611** [comment]
Is there any documentation available on what assembler-flavor `global_asm` is using? In my experiments, it seems that it's the same for all platforms, i.e. Linux and Windows. It looks to me like it's just GAS with intel syntax. Is this true or is it only similar to GAS with intel syntax?

I think there should be better documentation of what assembler flavor is used and a link to additional documentation should be provided. So far I don't know if `rustc` forwards it to the "default assembler compiler of the system" or if LLVM can take care of it.. I'd love to know about this!

**Comment by Amanieu** [comment]
It always uses a GAS-like syntax with intel syntax on x86. This is done using LLVM's internal assembler and not by actually invoking GAS.

The documentation is in the process of being added to the reference [here](https://github.com/rust-lang/reference/pull/1105).

**Comment by joshtriplett** [comment]
@Amanieu Is this the tracking issue being used for the *current* `global_asm!` (that's consistent with `asm!`), or is that being tracked for stabilization elsewhere?

If the latter, we should close this in favor of wherever that's being tracked.

**Comment by Amanieu** [comment]
`global_asm!` is now stable, so this can be closed.
