### ISSUE TITLE
Tracking issue for changes to name resolution (RFC 1560)

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#35120]
Tracking issue for rust-lang/rfcs#1560.

**Comment by nrc** [comment]
Nominating for stabilisation in the next cycle

**Comment by nrc** [comment]
There are potential breaking changes around importing more names in globs, e.g., in `super::*`, because we now import all accessible names, not just the public ones. We should do a Crater run before stabilisation. This is hard to do a warning cycle for. We should advertise the change during stabilisation. I feel like the benefits are so obvious and the breaking change so technical that it should be an easy sell.

**Comment by jseyfried** [comment]
More specifically, without `#[feature(pub_restricted)]` there is breakage if and only if
  - a glob import of an ancestor module (e.g. `use super::*`) imports a non-`pub` name,
  - the name is also imported by another glob import (making it ambiguous), and
  - the name is used (triggering an ambiguity error).

If the name is not used to resolve other imports, then it is simple to emit a warning instead of a hard ambiguity error. I believe this is likely to avoid a large fraction of any breakage in practice.

To avoid the remaining breakage, we will probably need to try re-resolving the crate without `item_like_imports` whenever there are ambiguity errors, which is doable but is fairly invasive and interacts badly with macro modularization.

**Comment by nikomatsakis** [comment]
Can we get started on crater runs now? If we can't do a warning cycle, we should be aggressive about submitting PRs to affected crates to repair problems. (Also, we should investigate whether we can give good errors that link users to an issue explaining what changed and how to fix, even if they are still getting an error.)

**Comment by nrc** [comment]
Sure, I was thinking it was pretty early in the cycle and more breakage could appear later, but I guess there is no harm in doing multiple crate runs.

@jseyfried would you be able to make a PR to un-feature-gate for a Crater run please?

**Comment by jseyfried** [comment]
@nikomatsakis 
> If we can't do a warning cycle

A partial warning cycle is fairly simple and a full warning cycle is possible (see https://github.com/rust-lang/rust/issues/35120#issuecomment-253050153).

> we should investigate whether we can give good errors that link users to an issue explaining what changed and how to fix

The errors we give today already include a suggestion for a fix, e.g. [this gist](https://play.rust-lang.org/?gist=0862890e2659ffab3062ab5be9590a19&version=nightly&backtrace=0). I could make the suggestion more detailed/concrete or improve the error in other ways -- let me know if you have any suggestions.

**Comment by aturon** [comment]
@nrc, we're moving these days to using @rfcbot for FCP proposals -- I'll flag it.

@rfcbot fcp merge

**Comment by bstrie** [comment]
I see that the FCP is complete, but this issue is still open. What's the status?

**Comment by jseyfried** [comment]
RFC 1560 was stabilized in #37127 (currently in beta).

**Comment by shepmaster** [comment]
This code currently fails in stable, but compiles in beta and nightly. I do not think it should:

```rust
struct Outer;

mod foo {
    use super::Outer;
    
    mod test {
        use super::*;
        
        struct Dummy(Outer);
    }
}

fn main() {}
```

Since `use super::Outer;` does not re-export `Outer` from `foo` via `pub`, I don't believe that `foo::test::super::*` should include `Outer`. 

I've skimmed through the [changes to name resolution rules](the https://github.com/rust-lang/rfcs/blob/master/text/1560-name-resolution.md#changes-to-name-resolution-rules) section, but don't see what this would match up with with allowing this. Anyone care to point me in the right direction?

**Comment by petrochenkov** [comment]
@shepmaster 
>I've skimmed through the changes to name resolution rules section, but don't see what this would match up with. 

https://github.com/rust-lang/rfcs/blob/master/text/1560-name-resolution.md#non-public-imports + https://github.com/rust-lang/rfcs/blob/master/text/1560-name-resolution.md#glob-imports-of-accessible-but-not-public-names

**Comment by shepmaster** [comment]
@petrochenkov Thank you. "non-public imports" appears to be the piece I was missing; I was aware of the glob change. I guess I missed it when skimming because it uses a sibling module, not the nested module that my brain was primed for.
