### ISSUE TITLE
json byte position doesn't start at top of file

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#35164]
From the IRC conversation:

> 1:17 AM <killercup> jntrnr: re json compiler output, i totally forgot to ask about byte_{start,end}! it's either not mapping to the byte indices of the source file (is it maybe counting them after after macro expansion or something?) or i'm stupid ;) do you know what's up this that? it'd make rustfix (and editor plugin i imagine) a bit easier to implement if we could use byte indices
> 4:38 AM <eddyb> killercup: you have to look at how they're created
> 4:38 AM <eddyb> src/libsyntax/json.rs:            byte_start: span.lo.0,
> 4:39 AM <eddyb> see, that's wrong
> 4:39 AM <eddyb> that's the byte start _within the crate_
> 4:39 AM <eddyb> without the CodeMap you can't know where the file starts
> 4:39 AM <eddyb> it should subtract the file start
> 4:40 AM <eddyb> assuming the start and end are in the same file

The fix should be to alter the json output so that lo/hi of the span's byte position start at the top of the file rather than at a codemap offset.

**Comment by Mark-Simulacrum** [comment]
As far as I can tell, this hasn't happened. @jonathandturner This feels like it may be an E-easy bug. Could you provide some more instructions, perhaps?

**Comment by jonathandturner** [comment]
@Mark-Simulacrum - it may be, but tbh I totally forgot what I was thinking when I wrote this 😅  It's been a while since I worked on any error message code

**Comment by Mark-Simulacrum** [comment]
Based on the IRC log, I think the problem is that [these lines](https://github.com/rust-lang/rust/blob/master/src/libsyntax/json.rs#L259-L260) need to be something more than they are, going through some sort of `CodeMap` or maybe `CodeMapper`? I'm not familiar with this code, though, so I don't know what exactly needs to happen here.

Would you perhaps know who we could cc for some instructions here?

**Comment by jonathandturner** [comment]
Looks like the compiler team and @killercup sitting down together and figuring it out (if they haven't already)

**Comment by killercup** [comment]
Not sure if anything changed since last year, but I just wrote this small example program that still crashes when the message is in another file: https://github.com/killercup/rustfix/blob/do-byte-indices-work/examples/do-byte-indices-work.rs

You can play around with it by adding unused warnings in various places.
