### ISSUE TITLE
[MIR] handle local variables generically (temps, vars, args, up_vars, return)

### ISSUE THREAD

**Issue by scottcarr** [rust-lang/rust#35262]
Optimizations probably handle the different "kinds" of local variables in the same manner.  MIR should have some way of handling them generically.

This new interface should be reasonably backwards compatible.

**Comment by nagisa** [comment]
There’s `Local`, `Mir::local_index` and `Mir::count_locals`.

**Comment by scottcarr** [comment]
> There’s Local, Mir::local_index and Mir::count_locals. The only thing really missing is going from Local back to Lvalue.

Local doesn't solve the problem, IMHO.  I can't use a Local to index anything, so local_index may as well map each variable to random usize.

Also, the Local -> Lvalue mapping is cumbersome.  The return value should be the parent type of Temp, Var, Arg, etc.  If we have that type why not just have one vector of that type?

**Comment by nagisa** [comment]
> Local doesn't solve the problem, IMHO. I can't use a Local to index anything, so local_index may as well map each variable to a random usize.

Indexing not being implemented does not mean you cannot implement it.

>  The return value of the reverse mapping function should be the parent type of Temp, Var, Arg, etc

That’s what Lvalue is, no?

> If we have that type why not just have one vector of that type?

Because you *do* want to handle variables and arguments and temporaries significantly differently sometimes. Having to iterate through all the locals when you only care about arguments only is just wasteful. 

---

Ultimately my suggestion would be to change `Local` to be `u64` under the covers, and use upper 32 bits to differentiate between variable, argument and temporary in order to implement reverse mapping efficiently.

You’d end up making a fairly small change on top of having a quite efficient forward and backward mapping.

**Comment by scottcarr** [comment]
> Because you do want to handle variables and arguments and temporaries significantly differently sometimes. 

Sure, sometimes you do, but handling generically is (maybe more) common as evidenced by the existence of Local,

and here: https://github.com/rust-lang/rust/blob/master/src/librustc_borrowck/borrowck/mir/gather_moves.rs#L333-L349

and here: https://github.com/rust-lang/rust/blob/master/src/librustc_borrowck/borrowck/mir/gather_moves.rs#L541-L555

and here: https://github.com/rust-lang/rust/blob/master/src/librustc_mir/transform/type_check.rs#L93-L101

and here: https://github.com/rust-lang/rust/blob/master/src/librustc_mir/transform/type_check.rs#L134-L136

and here: https://github.com/rust-lang/rust/blob/master/src/librustc_trans/mir/analyze.rs#L31-L33

and here: https://github.com/rust-lang/rust/blob/master/src/librustc/mir/tcx.rs#L156-L161

and here: https://github.com/rust-lang/rust/blob/master/src/librustc/mir/visit.rs#L266-L276

> Having to iterate through all the locals when you only care about arguments only is just wasteful. 

True.  Maybe only a vector isn't what we want.

**Comment by eddyb** [comment]
Wheeeee this has been the case for several months 🎉🎉🎉
