### ISSUE TITLE
long diagnostics not registered for some internal crates

### ISSUE THREAD

**Issue by zackmdavis** [rust-lang/rust#35284]
In the comments on #32777, @jhod0 [writes](https://github.com/rust-lang/rust/issues/32777#issuecomment-234660618):

> I looked into it more, and it looks like the following libraries' long error messages are not properly registered:
> - libsyntax
> - librustc_passes
> - librustc_plugin
>   - However, the register_long_diagnostics! declaration in librustc_plugin is empty
> - librustc_mir
> - librustc_lint
> - librustc_metadata
> 
> i.e. running the following for any `errno` in the above libraries will fail:
> 
> ```
> $ rustc --explain <errno>
> error: no extended information for <errno>
> ```

**Comment by jhod0** [comment]
@zackmdavis ok, I'll work on a PR

It's a little more complicated than just linking those errors, because linking those errors exposes some failing doctests that need to be fixed.

Fortunately, there aren't all that many error explanations in these crates, and therefore Rust users are not currently missing all that much from them.

**Comment by Mark-Simulacrum** [comment]
Today, I think just `src/librustc_mir/diagnostics.rs` and `src/libsyntax/diagnostic_list.rs` aren't picked up. Either way, closing in favor of https://github.com/rust-lang/rust/issues/34588 and adding a note there.
