### ISSUE TITLE
[MIR] span_mirbug! should be an error

### ISSUE THREAD

**Issue by scottcarr** [rust-lang/rust#35499]
IIUC, span_mirbug! was an warning while MIR was in development.  It's time to make span_mirbug! an error.  (Or if it's really supposed to be a warning, rename the macro)

https://github.com/rust-lang/rust/blob/master/src/librustc_mir/transform/type_check.rs#L29-L36

**Comment by nagisa** [comment]
Not before we’re absolutely sure there’s really no more warnings produced by this.

**Comment by eddyb** [comment]
@nagisa We can check crater after turning them into ICEs.

**Comment by durka** [comment]
@nagisa I'm not 100% sure I understand that logic -- since we're in orbit now, and MIR is really being used, it seems to me that broken MIR _has_ to stop compilation. For example see https://github.com/rust-lang/rust/pull/35883#issuecomment-241473562 -- crash in safe code caused by generating a binary from bad MIR (indicating a bug in typeck).

**Comment by Mark-Simulacrum** [comment]
Can someone give an update here? Should we change mirbug to ICE? It seems reasonable...

**Comment by arielb1** [comment]
This is already done.
