### ISSUE TITLE
Tracking issue for `String::insert_str`

### ISSUE THREAD

**Issue by murarth** [rust-lang/rust#35553]
Tracking issue for `String::insert_str`, introduced in #34771

**Comment by apasel422** [comment]
CC #35554.

**Comment by tshepang** [comment]
why is this not yet stabilised

**Comment by rhysd** [comment]
I made a workaround for this until this API is stabilised.

```rust
pub fn insert(target: &mut String, index: usize, replaced: &str) {
    for c in replaced.chars().rev() {
        target.insert(index, c);
    }
}
```

**Comment by SimonSapin** [comment]
@rhysd This work, but takes O(N × (M + N)) time where N = `inserted.len()` and M = `target.len() - index`. (This is because a single `String::insert` call takes O(M) time, since it needs to move the bytes in `target` after `index` to the right in order to make room for `c`.) But maybe that’s OK for you because N and M are small in your program.

`String::insert_str` uses `unsafe` code to only move bytes once, and so takes O(M + N) time.

**Comment by rhysd** [comment]
@SimonSapin yeah, N is 4 and M is 10~20. Just a workaround for this API.

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

Seems like a consistent API and has baked for awhile!
