### ISSUE TITLE
Tracking issue for the `SliceIndex` trait

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#35729]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1679

The implementations are stable, but the `SliceIndex` trait is not.

**Comment by sfackler** [comment]
This is now implemented and will land in the 1.15 release!

**Comment by sfackler** [comment]
Oh right, this should be the tracking issue for the unstable helper traits...

**Comment by briansmith** [comment]
Could we please stabilize this for the next release (or the next next release)? It seems like it is possible to *use* the new functionality, but it isn't possible to write (transparent) wrappers around it because any reference to the `SliceIndex` trait triggers "use of unstable library feature 'slice_get_slice' (see issue #35729)".

**Comment by alexcrichton** [comment]
@sfackler I forget, was this an intended "never to be stabilized" trait or did we want this on the track to stabilization?

@briansmith note that the trait can be vendored locally for now (if necessary) as it's not unstable to implement it, just to use the libstd version. Now that's a huge PITA (especially in multiple crates), but it at least gets the ergonomics immediately!

**Comment by sfackler** [comment]
I wouldn't call it a "never stabilize" kind of thing, but it's definitely a bit gross in its current form. One suggestion on the RFC was to split out a trait per method which could be a bit cleaner and more extensible in the future.

**Comment by briansmith** [comment]
@alexcrichton I don't know what you mean by "can be vendored." Here's what I'm trying to write:

```rust
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Slice<'a> {
    bytes: &'a [u8]
}

impl<'a> Slice<'a> {
    #[inline]
    pub fn new(bytes: &'a [u8]) -> Slice<'a> {
        Slice { bytes: bytes }
    }

    #[inline]
    pub fn get<I>(&self, i: I) -> Option<&I::Output>
                  where I: std::slice::SliceIndex<u8> {
        self.bytes.get(i)
    }
}
```

The result is "use of unstable library feature 'slice_get_slice' (see issue #35729))."

**Comment by alexcrichton** [comment]
@briansmith oh I just mean that you can add your own `SliceIndex` trait in your own local crate, add the various impls/methods you need, and then use it locally.

That'd work for one crate to get ergonomics, but it wouldn't work at large to continue abstracting over it.

**Comment by clarcharr** [comment]
It'd be nice to see this trait combined with `RangeArgument` somehow.

**Comment by jonhoo** [comment]
@alexcrichton I'm not sure what you mean in your recommendation to @briansmith? I want to take a generic slice index argument (i.e., may be a range), and then use it to index into a slice. If I copy the trait into my own crate, I can't then take something implementing that trait and pass to `slice::get`?

**Comment by alexcrichton** [comment]
@jonhoo oh mean basically just copy/pasting the trait in libstd into your own crate. You wouldn't call `<[T]>::get`, you'd call the local trait's method. Again, good for library consumer ergonomics, bad for library developer ergonomics and generics

**Comment by shepmaster** [comment]
Would adding implementations for `&Range*` be possible / accepted?

**Comment by sfackler** [comment]
Adding a blanket `impl<T> RangeArgument for &T where T: RangeArgument` seems reasonable, yeah.

**Comment by SimonSapin** [comment]
This went through the RFC process and has been in Nightly for over a year. The only concrete concern I read in this issue is @clarcharr’s

> It'd be nice to see this trait combined with `RangeArgument` somehow.

I think it’s worth trying. The `SliceIndex` for range types can probably be unified under generic impls for `T: RangeArgument`. Anyone wants to work on this?

**Comment by SimonSapin** [comment]
@sfackler You wrote this trait is "a bit gross". What do you think would be a better API?

**Comment by clarcharr** [comment]
On second thought, it might make more sense to learn from `TryFrom` and do:

```
pub trait TryIndex<T> {
    type Output: ?Sized;
    type Error;
    fn try_index(&self, index: T) -> Result<&Self::Output, Self::Error>;
}
pub trait TryIndexMut<T>: TryIndex<T> {
    fn try_index_mut(&mut self, index: T) -> Result<&mut Self::Output, Self::Error>;
}

impl<T: ?Sized, I> Index<I> for T
where
    T: TryIndex<I>,
{
    type Output = <T as TryIndex<I>>::Output;
    fn index(&self, index: I) -> &<Self as Index<I>>::Output {
        self.try_index(index).unwrap()
    }
}

impl<T: ?Sized, I> IndexMut<I> for T
where
    T: TryIndexMut<I>,
{
    fn index_mut(&mut self, index: I) -> &mut <Self as Index<I>>::Output {
        self.try_index_mut(index).unwrap()
    }
}
```

Which technically might not be a breaking change.

**Comment by SimonSapin** [comment]
(This is a rant with not much in it that’s actionable now, feel free to ignore.)

I’ve looked some more into this feature’s history, and now I wish I had paid more attention to RFC 1679 when it was being proposed.

The RFC writes:

> The `SliceIndex` trait is unfortunate - it's tuned for exactly the set of methods it's used by. It only exists because inherent methods cannot be overloaded the same way that trait implementations can be. It would most likely remain unstable indefinitely.

I think that perma-unstable traits in public APIs are not acceptable. As people have argued in this thread, it makes impossible to write more similarly-generic API that end up calling on of the `get*` method of slices.

The reason the trait(s) need to reflect the `get*` methods so precisely is that those methods are overloaded to return different types. And that aspect is already stable, we’re stuck with `slice.get(n)` returning `Option<&T>` while `slice.get(n..m)` returns `Option<&[T]>`.

If if checked slicing had been a separate method (named `get_range` or `get_slice`) from indexing (and similarly `_mut` and `_unchecked`) we could have not needed another trait beyond `RangeArgument`.

**Comment by SimonSapin** [comment]
One thing we can still do is revert the `Index` and `IndexMut` impls or slices to be separate for each range type rather than generic based on the `SliceIndex` trait. This would allow removing the `index` and `index_mut` methods of `SliceIndex`.

Also the `str::get_*` methods all return the same respective type regardless of the argument’s type, so they could be based on `RangeArgument` instead. But maybe keeping consistency with `[T]` is preferable.

**Comment by SimonSapin** [comment]
The libs team discussed this and consensus was to **stabilize** as little as possible to enable the use case of generic code forwarding call to e.g. `[T]::get` while itself accepting the same parameter types. Namely:

* Stabilize the `SliceIndex` trait and its `Output` associated type, so that they can be named in other APIs.
* Keep all the method unstable, so that they can still be modified or removed. Mark them permanently unstable: not tracked by any tracking issue and (?) hidden from docs.
* Make use of the sealed trait pattern to prevent impls outside of the standard library: change `pub trait SliceIndex {…}` to `pub trait SliceIndex: Sealed {…}`, where `Sealed` is some private trait.

  A language change (unrelated to this trait) is being discussed to impls of traits for uninhabited types to omit the definitions of method that take `Self` in some form in its parameters, since any call to such a method would be unreachable anyway. If `SliceIndex` were not sealed, this might allow it to be implemented outside of the standard library despite methods being unstable. We recognize that this pattern is an abuse of a limitation in the current implementation of the “no private items in public APIs” language rule, if the language grows a mechanism to disallow impls of a trait outside of the crate defining that trait we should be able to switch `SliceIndex` to that.

@rfcbot fcp merge

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/pull/51147 implements https://github.com/rust-lang/rust/issues/35729#issuecomment-377784884 except `#[doc(hidden)]`, because of https://github.com/rust-lang/rust/issues/13698.

**Comment by joshlf** [comment]
Would it be possible to add a blanket impl for `RangeBounds`? It's been discussed in this thread, but all that ended up going in was a series of impls for the particular `Range` types (`RangeTo`, `RangeFull`, etc).

**Comment by SimonSapin** [comment]
@joshlf Seems reasonable to me, wanna send a PR? With #51147 landed it would need to happen in this release cycle.

**Comment by SimonSapin** [comment]
Oh wait, I just remembered: that would replace specialized code with enum-based dispatch. I don’t know if that ends up being reliably optimized away.

**Comment by joshlf** [comment]
Couldn't we use impl specialization?

**Comment by SimonSapin** [comment]
If this doesn’t simplify the code, why is this blanker impl useful?

**Comment by joshlf** [comment]
It's useful because otherwise you can't write the following code (which I tried to do, which motivated my commenting here):

```rust
fn foo<R: RangeBounds<usize>>(buf: &mut [u8], range: R) {
    bar(&mut buf[range]);
}
```

**Comment by SimonSapin** [comment]
Can you have a bound on `SliceIndex` instead? That’s exactly why we stabilized the trait without stabilizing the methods.

**Comment by joshlf** [comment]
Unfortunately not - some of the code actually makes use of the methods on `RangeBounds`. E.g., this function, which needs the ability to query what the bounds are:

```
use zerocopy::ByteSlice;

/// Extract a range from a slice of bytes.
///
/// `extract_slice_range` extracts the given range from the given slice of
/// bytes. It also returns the byte slices before and after the range.
///
/// If the provided range is out of bounds of the slice, or if the range
/// itself is nonsensical (if the upper bound precedes the lower bound),
/// `extract_slice_range` returns `None`.
pub fn extract_slice_range<B: ByteSlice, R: RangeBounds<usize>>(
    bytes: B, range: R,
) -> Option<(B, B, B)> {
    let lower = resolve_lower_bound(range.start_bound());
    let upper = resolve_upper_bound(bytes.len(), range.end_bound())?;
    if lower > upper {
        return None;
    }
    let (a, rest) = bytes.split_at(lower);
    let (b, c) = rest.split_at(upper - lower);
    Some((a, b, c))
}

// return the inclusive equivalent of the bound
fn resolve_lower_bound(bound: Bound<&usize>) -> usize {
    match bound {
        Bound::Included(x) => *x,
        Bound::Excluded(x) => *x + 1,
        Bound::Unbounded => 0,
    }
}

// return the exclusive equivalent of the bound, verifying that it is in
// range of len
fn resolve_upper_bound(len: usize, bound: Bound<&usize>) -> Option<usize> {
    let bound = match bound {
        Bound::Included(x) => *x + 1,
        Bound::Excluded(x) => *x,
        Bound::Unbounded => len,
    };
    if bound > len {
        return None;
    }
    Some(bound)
}
```

**Comment by SimonSapin** [comment]
… then have two bounds?

**Comment by joshlf** [comment]
That doesn't work because generic code needs to call `extract_slice_range`. The only way to get it to work (which I do now) is to have a function which converts any pair of `R: RangeBounds<usize>` and a slice length into a `Range`. It works, but it's a real hack, and it requires code that looks like `slice_mut(slice, range)` rather than `slice[range]`, where `slice_mut` is itself pretty annoying, and has to be `use`d everywhere.

<details>
<summary>Click to expand</summary>

```rust
    pub fn slice_mut<'a, T, R: RangeBounds<usize>>(slc: &'a mut [T], range: &R) -> &'a mut [T] {
        let lower = resolve_lower_bound(range.start_bound());
        let upper = resolve_upper_bound(slc.len(), range.end_bound()).unwrap();
        &mut slc[lower..upper]
    }

    // return the inclusive equivalent of the bound
    fn resolve_lower_bound(bound: Bound<&usize>) -> usize {
        match bound {
            Bound::Included(x) => *x,
            Bound::Excluded(x) => *x + 1,
            Bound::Unbounded => 0,
        }
    }

    // return the exclusive equivalent of the bound, verifying that it is in
    // range of len
    fn resolve_upper_bound(len: usize, bound: Bound<&usize>) -> Option<usize> {
        let bound = match bound {
            Bound::Included(x) => *x + 1,
            Bound::Excluded(x) => *x,
            Bound::Unbounded => len,
        };
        if bound > len {
            return None;
        }
        Some(bound)
    }
```

</details>

**Comment by joshlf** [comment]
Oh, sorry, I guess you mean have the bound `R: RangeBounds<usize> + SliceIndex`? That works I suppose. It's just ugly, and I suspect other Rust programmers are going to run into this sharp corner a lot. It'd be better if it Just Worked. If we can't get the default impl working, then so be it, but so long as we can get it to work, I feel like it will round off an otherwise sharp corner.

**Comment by SimonSapin** [comment]
Yes, if you want to do with a generic type two things that each require a different trait, have your own code require both traits.

**Comment by joshlf** [comment]
Oh, and one other issue. Since `SliceIndex` takes a type parameter, and we don't support HKT, there's no way to just have `R: RangeBounds<usize> + SliceIndex`, so the caller would have to know the concrete type `T` in `SliceIndex<T>`.

**Comment by SimonSapin** [comment]
This higher-ranked trait bounds rather than types, but yeah, good point.

**Comment by CAD97** [comment]
Is there any chance of providing a way of implementing `SliceIndex` in the future (or telling the coherence checker that the impls won't be expanded)? Because as it stands, it's impossible to have a custom index type and support indexing `str` by `ops::Range*` of the custom index type.
