### ISSUE TITLE
AsciiDoc is superior to Markdown in every way

### ISSUE THREAD

**Issue by SRGOM** [rust-lang/rust#35783]
Comments should support AsciiDoc formatting too

**Comment by steveklabnik** [comment]
Major changes should be made as [RFCs](https://github.com/rust-lang/rfcs), rather than open issues.

However, given [the history of this particular disucssion](https://internals.rust-lang.org/t/rustdoc-restructuredtext-vs-markdown/356/), I'm not confident such an RFC would be accepted. But that's just a personal opinion.

Please file an RFC if you'd like to pursue this! Thanks.
