### ISSUE TITLE
memrchr uses unaligned loads

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#35967]
Due to an arithmetic error, the fallback memrchr (used for non-linux) in libstd uses unaligned loads, the intention was to produce only well aligned pointers of course.

This was suspected to cause a crash using ARMv7, found by @tomaka 

Original code also had the same issue: BurntSushi/rust-memchr/pull/9

I believe that on x86 non-linux platforms, the bug was harmless and the function still produced the correct return value.

**Comment by tomaka** [comment]
> This was suspected to cause a crash using ARMv7, found by @tomaka

The crash is a SIGBUS (which is usually caused by unaligned loads), so this is likely the cause.

If anyone want to reproduce, the exact location is `_ZN3std6memchr7memrchr17hbaa18487c977cd24E+164`, using the rustc nightly from 2016-08-18. I don't know how to introspect the debug infos to find what exactly is the instruction at this location.

**Comment by bluss** [comment]
If you have the time, you can try with the posted PR #35969 to verify the fix.

**Comment by bluss** [comment]
@tomaka how relevant is this platform for stable rust? Should we beta-nominate the fix?

**Comment by tomaka** [comment]
The crash disappeared after the latest nightly.

**Comment by bluss** [comment]
Thank you
