### ISSUE TITLE
The thread park / unpark implementation is suboptimal

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#36209]
The current implementation of thread park / unpark is suboptimal. It currently unconditionally uses a mutex / cvar to implement the functionality. A much improved implementation is able to use an atomic variable to avoid most calls to the mutex / cvar.

An example of how to use this is available in Java's thread park / unpark implementation (the license for this section of the code is compatible).

cc @aturon

**Comment by carllerche** [comment]
This comment in the code provides more info:

> The implementation currently uses the trivial strategy of a Mutex+Condvar with wakeup flag, which does not actually allow spurious wakeups. In the future, this will be implemented in a more efficient way, perhaps along the lines of http://cr.openjdk.java.net/~stefank/6989984.1/raw_files/new/src/os/linux/vm/os_linux.cpp or futuxes, and in either case may allow spurious wakeups.

**Comment by retep998** [comment]
If it wasn't for `park_timeout`, I would have recommended using something like `SuspendThread` and `ResumeThread` on Windows.

I'm sure @Amanieu can come up with something efficient though.

**Comment by Amanieu** [comment]
I have several implementations of thread parking in parking_lot (https://github.com/Amanieu/parking_lot/tree/master/core/src/thread_parker), but they all use precise wakeups and won't generate spurious wakeups.

In general I don't think there is much benefit over just using a mutex & condvar since the majority of the overhead is from calling into the kernel to wakeup/suspend a thread.

**Comment by carllerche** [comment]
The point of the optimization is specifically to avoid yielding to the kernel & going through that overhead when not needed.

**Comment by retep998** [comment]
@carllerche The whole point of thread parking is to yield to the kernel and put the thread to sleep. As long as parking the thread only involves a single syscall then it is optimal.

**Comment by carllerche** [comment]
@retep998 The point of thread park is to put the thread to sleep until unpark was called **if unpark has not already be called**. If thread park is called after unpark the thread is not parked. This is a common occurrence and causing a syscall / context switch is suboptimal. 

An optimization implemented in other thread park / unpark systems (as referenced in the issue and comments in the rust implementation) is to use an atomic variable to prevent the syscall / mutex / context switch in the fairly common case described above.

**Comment by aturon** [comment]
There seems to be some confusion here. The intent of `park`/`unpark` is precisely as @retep998 was saying -- providing direct access to thread blocking/signaling facilities at the kernel level. Things like briefly spinwaiting before parking are intended to be done in a *data structure-specific* way, since the right choice of strategy varies. This is essentially the same as the JVM's model.

The optimization that the comments in the code are talking about is strictly about *how* we talk to the kernel -- preferring to use things like futexes rather than condition variables.

**Comment by RalfJung** [comment]
Given that we already have a loop in the thread parking code that catches spurious wakeups, why do we still say in the docs that spurious wakeups might happen?

Seems like an easy thing to take care of for the parking abstraction.

**Comment by carllerche** [comment]
This issue can be closed as it has been resolved. See https://github.com/rust-lang/rust/blob/6e5e63a48c3be7de2faf914c2a9e194ff7cede9e/src/libstd/thread/mod.rs#L1057
