### ISSUE TITLE
Reordering of attributes passed to `rustc_macro_derive`

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#36211]
(Using rustc from #35957)

Macros 1.1 is reordering attributes in a way that breaks Syntex. If I have the following:

``` rust
#[derive(Serialize, Deserialize)]
#[serde(bound(deserialize = "T::Owned: Deserialize"))]
struct CowT<'a, T: ?Sized + 'a + ToOwned>(Cow<'a, T>);
```

It gets passed to my `#[rustc_macro_derive(Serialize)]` as:

``` rust
#[serde(bound(deserialize = "T::Owned: Deserialize"))]
#[derive(Deserialize)]
struct CowT<'a, T: ?Sized + 'a + ToOwned>(Cow<'a, T>);
```

I would expect the `#[derive(Deserialize)]` to stay above `#[serde(...)]`.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Hm I'm not actually sure how to fix this offhand. When the `#[derive]` syntax extension is running the `#[derive]` attribute has already been removed, and then when we call the first `Serialize` implementation we manually push back on the `#[derive(Deserialize)]`. We could push it at the front instead of the back but I have a feeling that's probably also not the right place :(

Might require a more intrusive change to `#[derive]` to not remove the attribute at the beginning.

**Comment by nrc** [comment]
> We could push it at the front instead of the back but I have a feeling that's probably also not the right place

Why? Putting the remaining derives back where the one we just took out seems like the right thing to do to me.

**Comment by alexcrichton** [comment]
Oh right yeah we should put the `#[derive]` attribute back where we found it, but I don't think that information is available via the kind of syntax extension `#[derive]` is today?

**Comment by dtolnay** [comment]
This only affected syntex and is no longer required as we move our rustc_macro away from syntex (https://github.com/serde-rs/serde/pull/548).

**Comment by dtolnay** [comment]
Without syntex this no longer matters.
