### ISSUE TITLE
Need a bootstrapping solution for distros that does not hit the network

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#36327]
As mentioned in [this PR](https://github.com/rust-lang/rust/pull/36069), some distros appear to be bootstrapping not by using the `--enable-local-rust` flag to find the bootstrap compiler but by using rustbuild's cached stage0 compiler. To do this though they have to patch the build system so that it doesn't hit the network - rustbuild isn't designed for this use case. There is probably a simple solution we can come up with for this but so far haven't found the motivation to do so. I tried to [summarize the situation here](https://github.com/rust-lang/rust/pull/36069#issuecomment-244485676).

**Comment by infinity0** [comment]
Just do what @hasufell does in #36069 except guard it by a `configure` option that hits the network by default, `--assume-local-hashes-are-fresh` or something along those lines. I don't know how rustbuild works though, this wasn't discussed much in that thread.

**Comment by cuviper** [comment]
FWIW, I was doing similar in Fedora, using `--enable-local-rust` when I want `/usr/bin/rustc`, but otherwise just dropping snapshots into `dl/` and patching the download scripts to accept that.  Cargo needed similar manipulation.

For 1.12.0, I'm switching to always use `--enable-local-rust`, either pointing to `/usr` or extracting the snapshot and pointing into that.  Ditto Cargo's `--local-cargo`.  It seems to work fine so far.

**Comment by alexcrichton** [comment]
Implemented
