### ISSUE TITLE
Multine Comments missing in the book

### ISSUE THREAD

**Issue by dccoder84** [rust-lang/rust#36345]
I am speaking about these comments:
/* blabla
   blabla */

According to the rust reference they are available.

**Comment by TimNN** [comment]
This was previously rejected in #17903 and #28411.

**Comment by GuillaumeGomez** [comment]
cc @steveklabnik

**Comment by dccoder84** [comment]
Hmmm...
I don't understand why they are considered bad style. At least they should be mentioned and it should be explained why they are bad style.

**Comment by dccoder84** [comment]
When it is bad style, why are they available at all?

**Comment by steveklabnik** [comment]
The book is not meant to be comprehensive, that's the reference's job. It is meant to cover _almost_ everything, but not always in total detail. It's supposed to guide you down the right path and give you an overview of the language at a high level.

They're valid syntax because they already existed for a long time, and there wasn't enough justification to remove them entirely.

**Comment by steveklabnik** [comment]
(I thought I closed this before, but I didn't. Closing now.)
