### ISSUE TITLE
incr. comp.: Methods should have their own dep-graph nodes

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#36349]
Currently there is only one dependency graph node for all items within a given `impl`. This leads to false positives when detecting changes in methods, that is, changing one method makes the compiler consider the sibling methods to be changed too.

This can be solved by giving each method its own dep-graph node.

**Comment by nikomatsakis** [comment]
I think the right way to do this is to separate out impl/trait items altogether. I'm going to investigate a bit.

**Comment by eddyb** [comment]
FWIW there's some of this already happening on http://github.com/eddyb/rust/commits/lazy-start.
See the test changes in "rustc: introduce `TyIncomplete` for fine grained handling of type cycles.", which is currently https://github.com/eddyb/rust/commit/51c8ba4f5be9d215000aff27f6a9f1bf97a15d18#diff-49e88c9171d1c4d781d4922d6870bcc8L34.
*On top of that*, with a bit of work `CollectItem` can be removed (as all it does is eagerly request types).

**Comment by nikomatsakis** [comment]
I've been working on this. I'm getting close to having a working branch (I'm roughly at the point of getting `make check` to work). I just noticed @eddyb's comment though and I'm not yet sure how the work I'm doing relates to that. =) 

In particular, @eddyb, it seems to me that separating out impl items from the trait is valuable no matter what changes we make, since otherwise changes to the impl item signatures cause the impl's hash to change, no?

**Comment by goffrie** [comment]
So... since #37660 landed, is this not fixed? :D

**Comment by eddyb** [comment]
@goffrie I think it's still blocked on #37712.

**Comment by nikomatsakis** [comment]
It's basically fixed, yeah. But we can wait for #37712

**Comment by michaelwoerister** [comment]
https://github.com/rust-lang/rust/issues/37712 has landed, closing.
