### ISSUE TITLE
[rust-beta] [rust-nightly] Child Hanging & CLOEXEC: Bad File Descripter Error 9

### ISSUE THREAD

**Issue by mmstick** [rust-lang/rust#36398]
Having an issue with the beta and nightly compiler and my Parallel application. I thought that it was my fault until I switched back to the stable compiler and the produced binary never hangs. The CLOEXEC error would occur sometimes when spawning a `Child` with it's stdout and stderr piped, and the program would often hang as it would be stuck looping over 'Bad File Descriptor' when trying to read from the process's `ChildStdout`

```
thread '<unnamed>' panicked at 'the CLOEXEC pipe failed: Error { repr: Os { code: 9, message: "Bad file descriptor" } }', ../src/libstd/sys/unix/process.rs:269
```

You can try it out on your end by compiling my [Parallel program](https://github.com/mmstick/parallel) and executing the following:

``` sh
target/debug/parallel echo ::: 0 1 2 3 4 5 7 8 9
```

With the stable compiler, no hanging. With beta and nightly, lots of hanging.

**Comment by alexcrichton** [comment]
It looks like this may be related to just trans changes, but that in turn causes problems I think because of the usage of [`mem::uninitialized`](https://github.com/mmstick/parallel/blob/1311e5ac4e0f3d42085c27661344658993c280c9/src/main.rs#L218). That'll create a [`Child`](https://github.com/rust-lang/rust/blob/master/src/libstd/process.rs#L63-L78) which contains many I/O handles. If none of those are initialized then when dropped or replaced we're likely to just close arbitrary file descriptors and wreak havoc.

If you avoid `mem::uninitialized` (which I believe is unsafe in this context) does that fix things for you?

**Comment by mmstick** [comment]
If I change `let mut child = unsafe { mem::uninitialized::<Child>() };` to `let mut child: Child`, the compiler will not understand that the value is initialized when `command::get_command_output()` returns an `Ok` or when `command::exec()` returns an `Ok(Grouped)`, which signifies that the value has been set, so it will just produce an error about it possibly being uninitialized and fail to compile.

Although it does work in Nightly+Beta after I restructure everything to pass the `Child` directly back.

**Comment by alexcrichton** [comment]
This is currently undefined behavior, I believe, which I think would explain the difference across channels. With MIR changes in flight it'd certainly change codegen and could just cause LLVM to optimize this differently.

Perhaps `Option<Child>` could be used instead to track whether it's been set or not?

**Comment by Mark-Simulacrum** [comment]
@mmstick Is this still a problem for you?

**Comment by Mark-Simulacrum** [comment]
Closing. Let us know if this is still a problem, and we'll reopen, but it looks to me like the general issue here is unsafe (and wrong) code changing meaning over time -- somewhat expected, I guess.
