### ISSUE TITLE
Addition of debug info to official builds

### ISSUE THREAD

**Issue by larsbergstrom** [rust-lang/rust#36452]
Currently, it's hard to debug some Rust code in Firefox because the standard library does not have symbol information included. That means that all of the code that gets inlined from the stdlib has no source location info. It would be great to generate official builds with symbol info and package that in the official builds.

cc @alexcrichton @froydnj @luser

**Comment by luser** [comment]
There are two related issues here:
1) This makes our crash reports worse, since many frames in a crash report from libstd will be missing function names / source line info. (The exception here is generics.)
2) This makes the debugging story worse. I was trying to [debug an issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1302078) with Rust panics in Firefox on Win64 and it got incomprehensible very quickly, especially since we build with lto, so your simple Rust function winds up with a ton of inlined bits of libstd.

Neither of these are huge issues yet, since we don't have much Rust code. As we pull things like Stylo in, they're going to quickly become a problem.

Rust is in a unique situation here compared to C or C++. With those languages you typically dynamically link the standard library, so you can always get debug symbols for the one you're using after-the-fact. Since Rust always statically links in libstd if you don't have debug symbols at build time you are out of luck.

**Comment by luser** [comment]
Related, Rust omits frame pointers by default, so not having debug symbols in libstd likely means not getting good backtraces through libstd in a debugger. (I suspect this works OK on Linux because rustc does emit `.eh_frame` sections for the object files in libstd, even on x86.)

**Comment by retep998** [comment]
This would really improve the debugging experience on Windows, in particular with msvc. If a function was generated with debuginfo, then VS's debugger is able to display the unmangled name, and can even do step by step debugging through the source code if it is available. When stepping into a function from libstd, all it sees is an opaque mangled symbol which makes it hard to tell what is going on.

**Comment by larsbergstrom** [comment]
cc @vvuk, re: the thread in #servo on name mangling and MSVC.

**Comment by vvuk** [comment]
So I think to do this, we need:
* build with debuginfo=true in a config.toml for a rustbuild
* when installing the various bits into the stage2/ dest dir, make sure the `pdb` files get copied along
* when packaging, either package the `pdb` files directly, or put them in a separate `-debuginfo` component for `rustup`
If someone can give me a pointer on where to look for each of these three things, I can create PRs for this.

**Comment by luser** [comment]
We discussed this on IRC, but I think all we actually need is:
* build with debuginfo=true in a config.toml for a rustbuild

Since the bits of lib{core,std} that people will actually be linking against are rlibs, which should have the debug info embedded in the object files contained within.

**Comment by retep998** [comment]
Copying along and packaging `pdb` files is useful for debugging when you're linking against the dylib crates (which only plugins should ever do), or for debugging `rustc` itself. For applications that statically link `libstd`, just enabling debuginfo in `config.toml` is sufficient.

**Comment by cuviper** [comment]
@retep998 Do you mean enabling debuginfo in your own `Config.toml`?  That only helps for generic or inline-able code from `libstd`.  Anything that was actually compiled to object code in the `rlib` won't have debuginfo that way.  (At least for ELF+DWARF -- I'm not sure how Windows pdbs work with `rlib`.)

**Comment by brson** [comment]
@vvuk It looks to me like we could just pass `--enable-debuginfo` to the configure script on the release builders and that would work fine (or we could just turn that option on by default), though I'm not sure what that will do with pdb files (I suspect they will be packaged along with the libs if they are generated correctly).

If we could persuade rustc to emit debuginfo in a separate file then I'd definitely be in favor of making  a separate debuginfo package. I don't know if LLVM/rustc can generate such files though.

It's probably worth making the simple change to the configuration file and seeing how it affects both total tarball size and build times. If it's a big drag on build times then we might not want to turn it on by default when in the "dev" channel.

**Comment by brson** [comment]
[Here's the line to change in configure](https://github.com/rust-lang/rust/blob/16eeeac783d2ede28e09f2a433c612dea309fe33/configure#L638)

**Comment by cuviper** [comment]
> If we could persuade rustc to emit debuginfo in a separate file 

The Linux way is usually a separate step afterward, something like `strip -g -o foo.debug foo`

**Comment by retep998** [comment]
@cuviper I mean the `config.toml` that rustbuild reads settings from, which is the modern way to build rustc that doesn't involve `configure` or `make`.

**Comment by brson** [comment]
FWIW I don't think we can get away from configure+make as an interface to the build system. It's a standard that unixes expect.

**Comment by alexcrichton** [comment]
I believe @brson is [correct here](https://github.com/rust-lang/rust/issues/36452#issuecomment-254618585) where we just need to pass `--enable-debuginfo` on the MSVC nightly builders. Unfortunately rustbuild (e.g. the Cargo.toml files) do not generate the MSVC distribution right now, so changing them wouldn't actually fix the problem here.

@brson I think we may prefer though to change buildbot config rather than our build script here, right?

I'd also prefer to only do this for MSVC right now as it'd be more of a PITA to run `strip` or other tools for Unixes.

**Comment by brson** [comment]
@alexcrichton why only for windows? I'd prefer to keep feature parity between platforms.

The reason to change configure is that others packaging rust would get debuginfo as well. If that's the experience we want our users to have then doing it by default helps distros get it right.

Why would we need to run strip on the unixes? I was assuming we would just include the debuginfo inside the binaries for now, to get the feature out. If somebody somebody teaches rustc to put the debuginfo beside the bins then we can turn that on.

**Comment by alexcrichton** [comment]
Hm are we 100% sure that this doesn't affect code generation? Or otherwise no negative effects on Unix? I assumed that the story there was somewhat up in the air so we've avoided it in the past.

You can ignore my comment about strip.

**Comment by cuviper** [comment]
GCC does have the option `-gsplit-dwarf` creating separate `.dwo` files, but not as many tools support it.  A similar option for rustc could be nice, but I'd be careful about making it the default.

You need strip if you want the main rust download to stay small, and ship a separate debug component.

I think it does affect codegen though, sadly.  I still do opt+debug for Fedora builds, because this is our policy, but I wish I could rely on it having no overhead, even if that meant worse debuginfo.

**Comment by luser** [comment]
I don't think stripping or shipping separate debug info files is feasible for Rust without a bit of extra work. Since rustc is going to statically link the prebuilt object files from the rlibs, the debug info needs to be in the object files. The alternative would mean teaching rustc to know how to find and link a standalone debug info file. That seems like a sensible future direction, but I don't think it's a thing that exists right now.

**Comment by cuviper** [comment]
The most obvious codegen change is that debuginfo explicitly forces frame pointers.  It's controlled by [`set_frame_pointer_elimination`](https://github.com/rust-lang/rust/blob/16eeeac783d2ede28e09f2a433c612dea309fe33/src/librustc_trans/attributes.rs#L60), referencing #11906, which calls [`must_not_eliminate_frame_pointers`](https://github.com/rust-lang/rust/blob/16eeeac783d2ede28e09f2a433c612dea309fe33/src/librustc/session/mod.rs#L328) to determine the debuginfo state.

**Comment by alexcrichton** [comment]
I've [sent a PR](https://github.com/rust-lang/rust/pull/37280) to enable at least line number information in releases, so we can evaluate the impact from that and see if it works for Gecko.

**Comment by luser** [comment]
If that at least gets us function names and source line info that should be sufficient for crash reporting purposes. We'll likely eventually want full debug info for developers doing actual debugging, but maybe we can figure out something smarter before then.

**Comment by vvuk** [comment]
#37280 isn't sufficient for Windows -- with an Oct 20 nightly build, source information is missing from any standard rust libs.  Additionally, for Windows, we need more than just line numbers unfortunately.  rustc always uses gnu-style mangling, so we need debug info for the symbols to make sense in the debugger (you get `_ZN4test17run_tests_console17h07b8e649031d5e08E` when you want `test::run_tests_console::07b8e...`).

**Comment by alexcrichton** [comment]
@vvuk were you using this nightly?

```
rustc 1.14.0-nightly (f09420685 2016-10-20)
```

If so that doesn't include e4708273b5401cd572d19f8836e121ce39dc2767, the merge commit with #37280

**Comment by vvuk** [comment]
Indeed! Okay, will check with the next one and report again.
