### ISSUE TITLE
Rust book: misaligned ascii art in "Crates and Modules"

### ISSUE THREAD

**Issue by d33tah** [rust-lang/rust#36570]
Have a look here:

https://doc.rust-lang.org/stable/book/crates-and-modules.html#basic-terminology-crates-and-modules

There's a newline missing before "We’ll use this module layout".

**Comment by carols10cents** [comment]
This was [fixed in 98c6770a](https://github.com/rust-lang/rust/commit/98c6770a231d9bbaede40bbcf659218995958d6a) and the fix can be seen in the [nightly](https://doc.rust-lang.org/nightly/book/crates-and-modules.html#basic-terminology-crates-and-modules) and [beta](https://doc.rust-lang.org/beta/book/crates-and-modules.html#basic-terminology-crates-and-modules) versions of the book. The fix just hasn't made it to stable yet :)
