### ISSUE TITLE
Mention how boolean operators like and, or, etc work in Rust in the `if` section of The Book

### ISSUE THREAD

**Issue by adtac** [rust-lang/rust#36597]

**Comment by steveklabnik** [comment]
Thank you! I am, however, re-writing the book over here: https://github.com/rust-lang/book

As such, I'm not making major changes to the existing one. I would happily take a PR if anyone wants to improve this part of the book, but since it's going to be obsoleted by the new book, I'm going to give this ticket a close. Thank you!
