### ISSUE TITLE
rustdoc: run rustfmt on type definitions

### ISSUE THREAD

**Issue by fitzgen** [rust-lang/rust#36654]
When we have a lot of generic parameters and where clauses, it becomes unreadable in rustdoc pretty quickly.

For example:

<img width="968" alt="screen shot 2016-09-22 at 1 20 04 pm" src="https://cloud.githubusercontent.com/assets/74571/18764681/709943e6-80c7-11e6-81ba-90365a06d3bd.png">

**Comment by rkruppe** [comment]
The two PRs backlinked above made me think that perhaps we should rustfmt *all* code-like snippets included in rustdoc's output. I am not 100% sure, since the snippets in API docs aren't always like real code and don't always serve the same function. But since it's generally supposed to look like Rust code, I guess it's reasonable to apply the same style to it as to real code.

**Comment by Mark-Simulacrum** [comment]
Today this looks much better. I think this is effectively "fixed".

![image](https://cloud.githubusercontent.com/assets/5047365/26029431/1bb80140-37f2-11e7-8891-953ef2641d86.png)
