### ISSUE TITLE
Story for C libraries which embed Rust

### ISSUE THREAD

**Issue by mystor** [rust-lang/rust#36770]
There is a bit of an interesting problem with regard to how best to support the use case of traditionally C/C++ libraries which want to implement a feature or component in Rust. Currently this would be handled by building the rust component into a staticlib and linking it into the C library. This means that nothing changes for C consumers, but sucks if any of the consumers of this library, either directly or through other dependencies, want to also use rust, as there is already a copy of the rust standard library embedded in the library.

It would be nice if we could come up with some sort of story for how we can handle this situation well to make rust even more appealing for replacing components of or implementing new features in traditionally C libraries.

My immediate thought would be to allow for a new build target strawman-named "staticlib-nostd" which would not include the stdlib, and allow for rust's standard library to be linked in separately, meaning that the downstream library could share the standard library with the upstream library. I haven't put too much thought into what that would look like. This also doesn't solve any problems with duplicated dependencies other than the standard library.

cc @alexcrichton

**Comment by nagisa** [comment]
> sucks if any of the consumers of this library, either directly or through other dependencies, want to also use rust, as there is already a copy of the rust standard library embedded in the library.

Remember that this standard library may only be used for code generated with exactly the same version of rustc. This means that in general case this bundled standard library is not reusable at all. As far as static libraries with duplicate contents go, linker should be able to deduplicate them just fine.

**Comment by mystor** [comment]
The linker can't deduplicate them if we are using LTO unfortunately :-/

**Comment by alexcrichton** [comment]
This might be best done as an internals thread rather than a rust-lang/rust issue perhaps? Also note that the standard library isn't the only problem here, it's all shared dependencies from crates.io (e.g. libc etc).

I find it helpful to reduce the problem to what happens in C. For example if I publish a C library which depends on another today, how does that work? The answer (as far as I can tell) is that it's just hell for everyone. I don't think there's going to be an easy solution here, but this certainly should be an ongoing discussion to see if we can innovate here.

**Comment by luser** [comment]
Everything in C is sort of terrible, so unfortunately there aren't great examples there. :) The common usage pattern there is "link against a shared library", though, which doesn't translate well to Rust's static linking story. If you were a library and you wanted Unicode support, you'd probably dynamically link against ICU, and then applications using your library could also link against ICU and things would mostly be OK (modulo library versioning issues which are another pile of awfulness).

This is a bit of a complicated use case, but obviously we're hitting it in Gecko already. Our current problem is a little contrived (we link a xul-gtest library that statically links the xul library + some extra testing code, there's Rust code in xul and more Rust code in xul-gtest), but we'll hit this very soon in a non-contrived way when SpiderMonkey adds Rust code because xul statically links SpiderMonkey.

I think this is not as likely to bite the typical open source project--they usually produce shared libraries or dynamically linked binaries. It's only a problem when you're statically linking against something, and then only when both sides contain Rust code.

There was a proposal on #rust-internals the other day from @nagisa which sounded like it would work well. He proposed that if we could give cargo an output mode where it produced object files + the information on what it would link those against, consumers could use that and do the final link themselves. I'm not 100% sure what that would look like in a standalone build system, but in the Gecko build system we already support this exact thing. A while back we stopped producing real intermediate static libraries (they're slow to produce and to link against) and instead produce "library descriptors" for them, which are just text files containing a list of object files and a list of libraries to link against. If cargo could give us object files + linker instructions we could easily write out a library descriptor for each Rust library we want to link.

**Comment by mystor** [comment]
@froydnj also mentioned this in #rust-internals, which is along the same lines, about potentially adding command like APIs to Cargo which expose its dependency resolution and project management system without actually performing the build & linking steps, allowing for that information to be integrated into another build system which the C++ project is using:

```
<froydnj> it would be nice if cargo's separate functions (dependency resolution, build system, and project management) were more separated, or at least the underlying bits exposed more usefully
```

**Comment by alexcrichton** [comment]
Yeah I suspect that something along the lines of cargo dumping a dependency graph would be the "solution" here, but coordinating that across two projects, unioning the two dependency graphs, and getting a workable result sounds... fun!

**Comment by Centril** [comment]
I don't think this tracking issue is actually tracking anything today so I'll close it for now.
