### ISSUE TITLE
Can't install rust from brew (macOS 10.12)

### ISSUE THREAD

**Issue by ojosdegris** [rust-lang/rust#36817]
Trying to install with `brew install rust`

It gets to `make`:

> brew install rust
> ==> Auto-updated Homebrew!
> Updated 1 tap (homebrew/core).
> ==> New Formulae
> compose2kube
> ==> Updated Formulae
> bind            harfbuzz        libphonenumber  ponyc           tbb
> certigo         kapacitor       nsd             rtv
> ==> Deleted Formulae
> caudec
> 
> ==> Using the sandbox
> ==> Downloading https://static.rust-lang.org/dist/rustc-1.11.0-src.tar.gz
> Already downloaded: /Users/vittore/Library/Caches/Homebrew/rust-1.11.0.tar.gz
> ==> ./configure --prefix=/usr/local/Cellar/rust/1.11.0 --enable-clang --release-
> ==> make
> ^C^COne sec, just cleaning up

And sits there for at least 8 hours , tried to do that 3 times already. Then I just ctrl+c

What info you guys need me to provide about my system?

**Comment by alexcrichton** [comment]
Thanks for the report! This is actually a problem where the 1.11 compiler cannot bootstrap on OSX 10.12 due to a [recently fixed bug](https://github.com/rust-lang/rust/issues/34674). I  [commented on](https://github.com/Homebrew/homebrew-core/pull/4960#issuecomment-250295814) a homebrew-related PR recently which has more information, but the tl;dr; is that this'll get fixed in less than 24 hours! 

That is, this'll get fixed with the 1.12 release, which is happening tomorrow.

**Comment by ojosdegris** [comment]
thanks @alexcrichton !
