### ISSUE TITLE
I wonder if chinese developer is a member of rust project's authors

### ISSUE THREAD

**Issue by sawthewhat** [rust-lang/rust#36855]
so I think I need a credits.
or you can reply me with their names.
thanks.

**Comment by pnkfelix** [comment]
You can see a list of people who contributed to each release as part of the release notes.

See for example:

 * https://blog.rust-lang.org/2016/09/29/Rust-1.12.html#contributors-to-112
 * https://blog.rust-lang.org/2016/08/18/Rust-1.11.html#contributors-to-111
 * https://blog.rust-lang.org/2016/07/07/Rust-1.10.html#contributors-to-110
 * https://blog.rust-lang.org/2016/05/26/Rust-1.9.html#contributors-to-19

(and so on)

We don't list the country for origin for each contributor, but since you said names were an alternative, you can go through that list and try to determine where that contributor came from.

**Comment by pnkfelix** [comment]
(also, you might attempt to learn someone's associated country on their github page. For example, the user `bombless`, who is one of the contributors to rust, lists China as their country on their github page.)

**Comment by pnkfelix** [comment]
(closing as no action required.)
