### ISSUE TITLE
Improve compile time of parser combinators such as Combine

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#36918]
Currently, parser combinator libraries such as Combine require a very long time to type-check.  This does not happen with similar Haskell libraries.

This bug can be considered resolved when such libraries do not take too much time to type check.

**Comment by bluss** [comment]
Please make the issue as specific and actionable as possible. It's best to report specific, measurable issues – they often get fixed!

For example the issue could specify a code snippet that uses combine, the version of the crate, the version of the compiler, and how long it takes to compile.

Previous combine issue: #21231 is fixed since Rust 1.11.

Current PR #36917 will have a positive impact.

**Comment by DemiMarie** [comment]
Seeing as the underlying issue https://github.com/Marwes/combine/issues/21 was closed, I will close this ticket.  Thanks!
