### ISSUE TITLE
tidy script no longer checks lang features

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#37013]
[Here's a recent output](https://gist.github.com/brson/5e94ad9ee14a22793da5782fd1a74e5c). This script used to list all features in one place and now it only lists lib features.

**Comment by brson** [comment]
The problem is almost certainly that the script no longer detects the source file containing language features correctly. Update the script (src/tools/tidy/src/fetaures.rs) and add an assert that it found at least some lang feature to prevent this happening again.

**Comment by knight42** [comment]
@brson

The root of problem is that the status of lang features listed in `src/tools/tidy/src/fetaures.rs` were alterned to lowercase in [this commit](https://github.com/rust-lang/rust/commit/ef1de519ff286a21e220d5839a6a5d468d296773#diff-8fe611e80215042c8d89714f4dd6f8baR104), so the lines were all [filtered out](https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/features.rs#L140).

After a fix, the tidy check failed because of the following errors:

```
tidy check stage1 (x86_64-unknown-linux-gnu)
* 454 error codes
* highest error code: E0568
rust/src/libcore/fmt/mod.rs:1359: duplicating a lang feature
rust/src/libcore/fmt/mod.rs:1366: duplicating a lang feature
rust/src/libcore/cmp.rs:709: duplicating a lang feature
rust/src/libcore/cmp.rs:716: duplicating a lang feature
rust/src/libcore/cmp.rs:719: duplicating a lang feature
rust/src/libcore/cmp.rs:726: duplicating a lang feature
rust/src/libstd/macros.rs:287: duplicating a lang feature
thread 'main' panicked at 'some tidy checks failed', src/tools/tidy/src/main.rs:55
```

The feature `never_type` is used multiple times.

**Comment by knight42** [comment]
Perhaps we can put those implementations in a submodule?

**Comment by brson** [comment]
@knight42 Thanks for looking into this. Which implementations do you suggest putting into a submodule, and how will that get the script working again?

I think we can probably just rename the libs features that are violating the check.
