### ISSUE TITLE
Rust recompile when modifying an inner crate

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust#37140]
Hello.
Let's say I have a crate `a` and within this crate directory, I have another crate `b`.
The crate `a` does not depend on crate `b` for some reason (perhaps because crate `b` is loaded at run time).
If I modify the code of crate `b`, `cargo run` executed on crate `a` will recompile even thought it is useless (remember crate `a` does not depend on `crate `b`).
It would be nice to avoid this useless compilation in this specific case.
Thanks.

**Comment by alexcrichton** [comment]
Thanks for the report! I think that this may be a bug for rust-lang/cargo rather than here, so perhaps you can reopen it over there?

You may also want to try setting `RUST_LOG=cargo::ops::cargo_rustc::fingerprint=info` as that should help give some more diagnostic information as to why something was recompiled.

**Comment by antoyo** [comment]
Closing in favor of [#3199](https://github.com/rust-lang/cargo/issues/3199).
