### ISSUE TITLE
Doc tests ignore RUSTFLAGS

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#37330]
I am writing doc examples for the bindings of a C library.
In my `RUSTFLAGS`, I add a search path for the C library using `-L /path/to/lib`. (needed because I am using a custom version of the library that's not installed globally)

`cargo build/run` picks this up fine, and the C library links correctly.
However, doc tests cause a linking error, because `RUSTFLAGS` seem to be ignored when compiling doc examples.

**Comment by alexcrichton** [comment]
Thanks for the report! I think that this may be a bug for Cargo rather than the compiler, however. Perhaps this could be reopened over there?

**Comment by crumblingstatue** [comment]
Ah, didn't realize `RUSTFLAGS` is handled by Cargo. I'll reopen it over at cargo.

**Comment by rkruppe** [comment]
`RUSTFLAGS` is handled by cargo, but I believe the root cause is how rustdoc goes about creating/compiling the doctests. It doesn't generate rust code for Cargo to compile or anything, it does everything in-process using `librustc` APIs &mdash; and simply passing `RUSTFLAGS` to the `rustdoc` invocation won't work because `rustdoc` doesn't accept most `rustc` arguments. (However, it does seem to accept `-L` which would help with this specific use case)

**Comment by alexcrichton** [comment]
Bah you are indeed correct @rkruppe!
