### ISSUE TITLE
Describe semantic differences between Rust and C++ references 

### ISSUE THREAD

**Issue by johnthagen** [rust-lang/rust#37413]
As someone new to Rust but who has had a fare amount of C++ experience, I think one thing that could be helpful for new Rust developers would be a small discussion about how references in Rust differ semantically than what is found in C++.  Since they both use the `&` operator, I incorrectly imposed my C++ expectations onto how the references work in Rust. I think a good place for this would be in the [references and borrowing section](https://doc.rust-lang.org/book/references-and-borrowing.html).

An example to illustrate.

C++:
```cpp
void swap(int &a, int &b) {
    int temp = a;
    a = b;
    b = temp;
    return;
}
```

Rust:
```rust
fn swap(x: &mut i32, y: &mut i32) {
    let temp = *x;
    *x = *y;
    *y = temp;
}
```

I was initially confused by the need for the `*` operator in Rust to dereference a reference since C++ does this implicitly.  This was compounded by the fact that when you call methods on objects with `.`, a `*` isn't required, so I had seen many reference examples without `*`.  In the beginner's chat room a very friendly community member explained to me that `.` automatically dereferences when needed (which I was grateful for!).

I'm happy to submit a PR, but I'm not sure exactly the best way to word this (if this is even something others think would be helpful).  If I totally missed this in the docs already I'm happy to be pointed to it. :)

**Comment by dzamlo** [comment]
Maybe rust references are different enough from other languages that we should call them differently? borrows instead of references.

**Comment by johnthagen** [comment]
Some helpful explanations were explained to me on [the forums](https://users.rust-lang.org/t/why-do-references-need-to-be-explicitly-dereferenced/7770).

**Comment by steveklabnik** [comment]
In general, we don't do very much "compare to language X" in the docs, as 

1. Not everyone knows language X
2. The number of possible Xes is large
3. It has to be worded _very_ carefully, since we don't want to encourage trash talk of other languages.

In addition, two other things:

1. I'm currently [re-writing the book](https://github.com/rust-lang/book), and so I'm not updating the current one.
2. All of this _is_ covered in the book already. In that chapter:

> You'll also notice we added an asterisk (*) in front of y, making it *y, this is because y is a &mut reference. You'll need to use astrisks to access the contents of a reference as well.

and in the deref coercions chapter: https://doc.rust-lang.org/stable/book/deref-coercions.html#deref-and-method-calls

So, if someone wants to do the work to make this more clear _without_ comparing to C++, I'd be happy to accept PRs. But I'm going to give this issue a close, as it's already covered, I'm not updating the book, and it's too broad to be actionable. Thanks!
