### ISSUE TITLE
R_X86_64_PC32 against symbol blocks creation of DSO

### ISSUE THREAD

**Issue by MarkSwanson** [rust-lang/rust#37457]
Am I missing something?

_external_ symbols are incorrectly getting marked as 32-bit relative.
It is not possible to create shared libraries this way because external symbols may be > 32-bits away.

I've created a tiny example that shows how to reproduce the problem here:

https://github.com/MarkSwanson/libfringetest

I've modified libfringe so it compiles to a dylib by adding this to the libfringe Cargo.toml:

[lib]
name = "fringe"
path = "src/lib.rs"
crate-type = ["dylib"]

I put a [replace] section in my test Cargo.toml already.

**Comment by MarkSwanson** [comment]
I created a workaround for this problem - which simply involved me commenting out a Rust #[inline] attribute. It's looking like RustC/LLVM is incorrectly generating the 32-bit relative offset when #[inline] is forced.

You can see the pull request that fixes the problem here:
https://github.com/nathan7/libfringe/pull/60

**Comment by m4b** [comment]
Such wow. @alexcrichton this could be related to some of the changes I/we made with the linker regression before, but I don't know.

I thought this was a quick fix but many different things seem broken :/

so trying:

```toml
[lib]
name = "fringetest"
path = "src/lib.rs"
crate-type = ["cdylib"]
```

compiles for me, but the resulting binary is totally broken on X86_64 linux, as it doesn't even have an soname...:

```
rdr -l libfringetest.so 
ELF X86_64 DYN @ 0x50210
Soname: 
Libraries (5)
	libdl.so.2
	libpthread.so.0
	libgcc_s.so.1
	libc.so.6
	ld-linux-x86-64.so.2
```

Even worse, if I try add `no_mangle` to your lib function:

```rust
#[no_mangle]
pub fn test() {
    let stack = OsStack::new(1 << 16).unwrap();
    let mut gen = Generator::new(stack, move |yielder, mut index| {
        let values = [1, 2, 3];
        loop { index = yielder.suspend(values[index]) }
    });

    println!("{:?}", gen.resume(5));
}
```

I get a broken compile again.  I think this is actually correct, because the no mangle forces the linker to make the function available to consumers (dynamic linkers, etc.), and they're probably not given the correct relocations in the first place is my guess, but it hasn't come up because no one's tried to actually nomangle and then export C library style? Anway, the bad relocation is because it's trying to relocate against an undef symbol, which as you said, could be 64-bits away.

```
objdump -r target/debug/deps/fringetest.0.o | grep _ZN6fringe4arch3imp4swap10trampoline17he5525edeeec5683eE
0000000000000240 R_X86_64_PC32     _ZN6fringe4arch3imp4swap10trampoline17he5525edeeec5683eE-0x0000000000000004
00000000000005b7 R_X86_64_PC32     _ZN6fringe4arch3imp4swap10trampoline17he5525edeeec5683eE-0x0000000000000004
00000000000001ed R_X86_64_PC32     _ZN6fringe4arch3imp4swap10trampoline17he5525edeeec5683eE-0x0000000000000004
00000000000001ff R_X86_64_PC32     _ZN6fringe4arch3imp4swap10trampoline17he5525edeeec5683eE-0x0000000000000004
00000000000002d6 R_X86_64_PC32     _ZN6fringe4arch3imp4swap10trampoline17he5525edeeec5683eE-0x0000000000000004

nm -s target/debug/deps/fringetest.0.o | grep _ZN6fringe4arch3imp4swap10trampoline17he5525edeeec5683eE
                 U _ZN6fringe4arch3imp4swap10trampoline17he5525edeeec5683eE
```

So what worries me (among several things) is that even when it does compile (with no soname), the fringe functions, which should have been statically burned into your dynamic library iirc and rewrapped them:

```
objdump -R target/debug/libfringetest.so | grep fringe.*stack
00000000003171f0 R_X86_64_JUMP_SLOT  _ZN62_$LT$fringe..stack..os..OsStack$u20$as$u20$core..ops..Drop$GT$4drop17h9b06805ccb79bdb0E@@Base
0000000000317aa0 R_X86_64_JUMP_SLOT  _ZN6fringe5stack2os3sys9page_size17h61688e1bae0d3c5aE@@Base
```

have jump slots assigned (i.e., it looks like they're imported functions now).

In other words, the static symbols are given dynamic relocation entries to dynamically resolve them at runtime.  Even stranger, I've messed around with a C program trivially dynamically linking against the dynamic library, and forcing it to bind all symbols, something like:

```
gcc -L. -l:libfringetest.so test.c && LD_DEBUG=all LD_LIBRARY_PATH=. LD_BIND_NOW=all ./a.out 2> out.txt
```

and it resolves the various symbols problematic symbols like `_ZN62_$LT$fringe..stack..os..OsStack$u20$as$u20$core..ops..Drop$GT$4drop17h9b06805ccb79bdb0E` to itself, because they're both listed as jump slot relocations _and_ exported functions :] so because the dynamic linker doesn't find it in other libraries, but itself.  Maybe this works accidentally, but it just doesn't seem right.

Lastly, so I've been compiling goblin as a dynamic library for a while, and it looks similarly broken (no soname, local functions in the jump table, etc.).  I thought this could be a size issue at first, but I've included the dynamic relocations for chromium, which is a big ol' 128 megabyte binary on my system and for comparison:

```
0000000000363be0 R_X86_64_JUMP_SLOT  _ZN6goblin5elf643sym6impure41_$LT$impl$u20$goblin..elf64..sym..Sym$GT$11is_function17hc057ef1decd9a013E@@Base
0000000000363c50 R_X86_64_JUMP_SLOT  _ZN6goblin5elf323dyn6impure10get_needed17h5bfa48fbc82bee6bE@@Base
0000000000363c68 R_X86_64_JUMP_SLOT  _ZN65_$LT$goblin..mach..header..Header$u20$as$u20$core..fmt..Debug$GT$3fmt17h4f6bb3fbd2cfeb8fE@@Base
0000000000363ca0 R_X86_64_JUMP_SLOT  _ZN6goblin5elf326header6impure76_$LT$impl$u20$core..fmt..Debug$u20$for$u20$goblin..elf32..header..Header$GT$3fmt17hb163bd5dd067aacfE@@Base

rdr -l target/debug/libgoblin.so

ELF X86_64 DYN @ 0x5b9c0
Soname: 
Libraries (5)
	libdl.so.2
	libpthread.so.0
	libgcc_s.so.1
	libc.so.6
	ld-linux-x86-64.so.2

objdump -R /usr/lib/chromium/chromium | grep JUMP_SLOT
0000000008b0e7d8 R_X86_64_JUMP_SLOT  geteuid@GLIBC_2.2.5
0000000008b0e7e0 R_X86_64_JUMP_SLOT  rmdir@GLIBC_2.2.5
0000000008b0e7e8 R_X86_64_JUMP_SLOT  pwrite64@GLIBC_2.2.5
0000000008b0e7f0 R_X86_64_JUMP_SLOT  fchmod@GLIBC_2.2.5
0000000008b0e7f8 R_X86_64_JUMP_SLOT  ftruncate64@GLIBC_2.2.5

```

(note chromium has no soname because it's a PIE, but goblin is a `.so` here, so it should _definitely_ have an soname)

The only thing in chromium's jump slot are imported functions from libc, as expected.

BTW, for the record, in your previous post, `file binary.o` doesn't really prove the object file is PIC; you should investigate with something like:

```
objdump -r binary.o
```
and investigate the resulting relocation symbols (but that also doesn't help too much either, you should just try linking it, but then again, all linkers seem to be totally busted these days too so who knows :P)

**Comment by MarkSwanson** [comment]
> but it hasn't come up because no one's tried to actually nomangle and then export C library style?
Fyi I do this in several other projects. Here's the output of a simple test DSO with a nomangle init() Fn:

```
objdump -T ./target/debug/libtest.so
 00000000000039c0 g    DF .text	00000000000007c4  Base        init

objdump -t ./target/debug/libstormlet_hello_world.so | grep init
00000000000039c0 g     F .text	00000000000007c4              init
```

There were no [dynamic] relocation symbols in the dso.

**Comment by MarkSwanson** [comment]
Fyi Amanieu left a comment in libfringe that might help:

https://github.com/nathan7/libfringe/issues/59#issuecomment-257680166

**Comment by m4b** [comment]
Oh god, I didn't realize they were using inline asm. Yea of course... If your asm can't be properly relocated into pic mode yea, nothing linker or rust can do about that...

**Comment by MarkSwanson** [comment]
I think I understand. Amanieu's plt change makes the reference relative to the program counter, which will always work in a DSO.

Reference for anyone that stumbles on this and is wondering what the plt thing is: http://stackoverflow.com/questions/5469274/what-does-plt-mean-here

I appreciate the time you took looking into this.
Maybe some good will come of it - maybe we should open an issue for the missing soname? Or other things you found?
