### ISSUE TITLE
u16 docs have u8 examples

### ISSUE THREAD

**Issue by rustyrazorblade** [rust-lang/rust#37466]
u16 min_value and max_value look like they may have been copies from u8 

```
fn max_value() -> u161.0.0[−]

Returns the largest value that can be represented by this integer type.

Examples

assert_eq!(u8::max_value(), 255);
```

**Comment by steveklabnik** [comment]
I'm on mobile, but there should be a disclaimer at the top of the docs about this.

That is, these are all generated by a macro for all integer types and therefore there's no good way to use each type in the docs. It's technically feasible but would obfuscate things quite a bit...

**Comment by frewsxcv** [comment]
For reference, [this](https://github.com/rust-lang/rust/blob/ea20ab107eb03179e82ff42109d0aaa62aba48b8/src/libcore/num/mod.rs#L178-L1267) is what the macro looks like to generate these docs.

If it's possible to add identifiers into doc comments within macros, then it might be possible to modify the doc comments to use the specific type instead of `u8`/`i8`, though I have a feeling that it's not possible.

**Comment by frewsxcv** [comment]
> If it's possible to add identifiers into doc comments within macros...

Asked about this on IRC, and it seems this might be the only way to accomplish it:

```rust
#[doc("Before, ")]
#[doc(stringify!($i))]
#[doc(", after.")]
fn foo() {}
```

**Comment by durka** [comment]
In theory, yes, you could write the docs like this:

```
/// # Examples
///
/// ```
/// assert_eq!(
#[doc=$int_type]
/// ::min_value(), -128)
/// ```
```

(adding an `$int_type:expr` param since an ident doesn't work there and we don't have macros in attributes yet so you can't call `stringify`)

... but nobody wants to do that and even if you do you get awkward line breaks in the docs: ![](http://www.seas.upenn.edu/~aburka/tmp/Screen%20Shot%202016-10-30%20at%2010.34.21%20PM.png)

**Comment by steveklabnik** [comment]
Marking as p-low; we have no idea how to fix this at this time, and there's already notes in the docs pointing out the strangeness here.

**Comment by GuillaumeGomez** [comment]
Fixed by using macros. You can find the macro [here](https://crates.io/crates/doc-comment) as well.
