### ISSUE TITLE
Traits allow unused generic parameters

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#37496]
Consider this trait:

```rust
trait Foo<'a> {
  fn foo(x: i32, y: i32) -> i32;
}
```

`rustc` will happily let this compile, even though `'a` is never used for anything. The same goes for type parameters. This feels incorrect to me, though I might be wrong.

**Comment by sanxiyn** [comment]
Bear with me if I sound bitter, because I am. No one other than @steveklabnik closed #25871 last February. I will not close this issue, because I am better than him.

**Comment by steveklabnik** [comment]
@sanxiyn that issue was closed as part of a blanket policy on lints, it wasn't anything personal. If this issue were "we should make a lint for this", I wouldn't have made it in the first place.

This issue is "I'm not even sure this code _should_ be valid." If it is, then this should be closed, just as that issue was closed.

**Comment by arielb1** [comment]
I don't see why this should not be valid - for example, marker traits have an unused Self by this standard.

**Comment by steveklabnik** [comment]
@arielb1 would it? Marker traits don't take any generic parameters. Is it that Self is treated as one or something?

**Comment by sanxiyn** [comment]
It was implemented as a lint because unused generic parameters, in general, is not an error. An example is [_assert_error_is_sync_send](https://github.com/rust-lang/rust/blob/7c69b0d5ae8c404c4847fa214126ebd7c0246277/src/libstd/io/error.rs#L515-L518) in libstd. I think it is a legitimate use case.

That said, maybe unused lifetime parameters, or unused generic parameters in traits, are useless. I can easily rebase my PR restricted to these cases.

**Comment by arielb1** [comment]
@steveklabnik 

Sure enough. `Self` is conceptually a generic parameter.

**Comment by eddyb** [comment]
They're not useless, they can have semantic implications, for example `unsafe` traits which may be used to determine the safety of an otherwise problematic operation.
One such trait (although not `unsafe`, as only the compiler can implement it) is `Unsize`.
`T: Unsize<U>` means that any (even smart) pointer to `T` may be coerced to the same pointer to `U`, turning a thin pointer into a fat pointer most of the time.

**Comment by arielb1** [comment]
`Unsize` is a magic trait, but I don't think this is anything more than a Clippy lint.
