### ISSUE TITLE
Passing a RefCell<mem::zeroed> value to ThreadLocalKey causes panic

### ISSUE THREAD

**Issue by valarauca** [rust-lang/rust#37539]
I was passing a reference to an object to unwind my stack and swap threads. This object isn't constructed until I swap to threads. So I need to put a place holder in the localkey. Zeroed seemed appropriate. 

To be clear, I will NEVER have a valid value for this before the RefCell is constructed. 

code to recreate

https://github.com/valarauca/context_bind/blob/master/example/src/main.rs

What is happening is I'm creating a local key I either get a panic in unwrap (when the item is zeroed), or a SIGSEV when the item is uninitialized. But this the item INSIDE of a RefCell so I'm really confused.

Back trace

stable (1.12.0) https://github.com/valarauca/context_bind/blob/master/example/back_trace

nightly (2016-11-01) https://github.com/valarauca/context_bind/blob/master/example/nightly_backtrace

**Comment by sfackler** [comment]
It is undefined behavior to have a zeroed Box.

**Comment by valarauca** [comment]
Yes but what is being passed to the refcell is a Tuple not a Box. Also the RefCell wraps the Tuple.

**Comment by sfackler** [comment]
That doesn't matter. A zeroed `Box` cannot exist, so a tuple with a zeroed `Box` cannot exist, so a `RefCell` with a tuple with a zeroed `Box` cannot exist. In particular, the compiler can and will represent a `None` value of a `Option<RefCell<(Transfer, Box<Fn>)>>` as a value where the bytes corresponding to that `Box` are zeroed. This is what I'd assume is causing the unwrap panic.

The SIGSEGV is probably due to the `drop` implementation of the `Box` trying to look up the `Fn` object's destructor in its vtable.

If you may not have a valid value, use an `Option<Box<Fn()>>` and `None`.

**Comment by valarauca** [comment]
Using `Option<Box<Fn()>>` and initializing on a `None`. Still triggers a panic at the unwrap in site in ThreadLocalKey

[OptionChange](https://github.com/valarauca/context_bind/blob/aca6c93c41dc938efbbb688d5e5a05d7a5d72785/src/lib.rs#L80]

[Backtrace](https://github.com/valarauca/context_bind/blob/aca6c93c41dc938efbbb688d5e5a05d7a5d72785/option_backtrace)

**Comment by sfackler** [comment]
`Transfer` contains a `Context`, which contains a `&'static c_void`, which also must not be zero for the same reason as `Box`.

**Comment by valarauca** [comment]
So effectively no uninitialized pointers can be passed in a local key?

**Comment by sfackler** [comment]
Zeroed Boxes/references cannot exist ever, anywhere. LocalKey is one of many things that will break if you have them around.

**Comment by valarauca** [comment]
Thank for assistance. Sorry to be a pain. I'll lay off the unsafe.

**Comment by sfackler** [comment]
No problem! It can definitely be more subtle than it may seem initially :)
