### ISSUE TITLE
armv7-unknown-linux-gnuhf requires glibc >= 2.15, raspbian only has 2.13

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#37562]
Trying to run `rustc` on rπ with Raspbian installed fails with:

```
rustc: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.15' not found (required by /usr/local/bin/../lib/../lib/librustc_llvm-bb9bb1dd7b0e77fc.so)
```

Raspbian only has 2.13, so it would be great if we built our binary distributions with glibc 2.13 for ARM (v7, at least).

```
$ /lib/arm-linux-gnueabihf/libc.so.6 
GNU C Library (Debian EGLIBC 2.13-38+rpi2+deb7u8) stable release version 2.13, by Roland McGrath et al.
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.6.3.
Compiled on a Linux 3.2.51 system on 2015-03-15.
Available extensions:
	crypt add-on version 2.1 by Michael Glad and others
	GNU Libidn by Simon Josefsson
	Native POSIX Threads Library by Ulrich Drepper et al
	Support for some architectures added on, not maintained in glibc core.
	BIND-8.2.3-T5B
libc ABIs: UNIQUE
For bug reporting instructions, please see:
<http://www.debian.org/Bugs/>.
```

cc @alexcrichton

**Comment by alexcrichton** [comment]
cc @japaric

**Comment by japaric** [comment]
@nagisa Are you using oldstable? I was under the impression that stable Raspbian was already shipping with 2.19; I may be wrong -- I'm not following Raspbian closely.

We upped the glibc version because with an older glibc version our binary releases were broken for all the ARM devices out there. cf #35843

Before that, we were using glibc-2.14 (we can't produce anything older using crosstool-ng) so the binary releases weren't guaranteed to work on glibc-2.13 distros either.

We *could* build the binary releases using the glibc-2.13 toolchain that Raspbian ships with ... But please first confirm that most people is using glibc-2.13. I would expect way more complaints if that were the case.

**Comment by nagisa** [comment]
I’m using Raspbian from about a year ago.

**Comment by locka99** [comment]
I updated an old Raspbian to the new rebranded Raspbian PIXEL just 2 days ago and was able to install 1.12.1 via Rustup and compile a simple program. Could it be an old unupdated dist?

**Comment by sanxiyn** [comment]
Looking at https://repology.org/project/glibc/versions, Raspbian Stable is at glibc 2.24, and even Raspbian Oldstable is at glibc 2.19 now. We build on glibc 2.16. Closing.
