### ISSUE TITLE
Code "all in one file" faster than when imported

### ISSUE THREAD

**Issue by daschl** [rust-lang/rust#37628]
Hi folks,

I'm using `rustc 1.14.0-nightly (5665bdf3e 2016-11-02)` and ran into an issue where the exact same code imported from a crate is slower than if I put all the code in one place.

I've created a repository to checkout and run (I don't want to put all the code in here since its a little more): https://github.com/daschl/optim-repro

This code does tokenization of a `&str` based on a character tokenizer. If you run `cargo +nightly bench` in my case the performance is significantly different:

```
test bench_allinone ... bench:       3,765 ns/iter (+/- 576)

vs.

test bench_imported ... bench:       6,686 ns/iter (+/- 3,608)
```

All I did was copy some of the code for the "allinone" directly into the bench module. I suspect that rust (llvm?) is better at optimzing stuff when its in the same file, but I wanted to raise it since maybe there is an opportunity to improve.

I also found that the performance gets better/worse when I do changes to the `filter: fn(char) -> bool` that is stored in the struct (for example not only giving it the char but rather the more complex tuples in the iterator chain), so maybe this is one of the issues.

**Comment by oli-obk** [comment]
The problem is that there's little optimization happening across crates. You can enable link time optimization (slow!) to fix that or you can add `#[inline]` (just `inline`, no `always` or otherwise) to your non-generic function(s) and see what combination gives you back your speed (don't just spray `#[inline]` everywhere!)

**Comment by KalitaAlexey** [comment]
Dear @oli-obk,
Is there any information about it? I mean what I should read to know details and ways to optimize my code.

**Comment by oli-obk** [comment]
There's no real guide to optimizing code, because that would most likely cause users to heavily do premature optimization (which can actually end up being a pessimization, aka your code is slower). Optimizing Rust code works just like optimizing any other compiled language's code.

In this case, adding `#[inline]` will actually slow down compilation, because it's just as if the code of the function marked `#[inline]` were in the crate using that function. So if your reason for splitting the crate into two was compilation time, then this is potentially a step backwards.

**Comment by daschl** [comment]
@oli-obk even If I set lto = true on the bench profile there is a performance gap. I'll try toying around with inlining and see if it helps.

So do you know if there are plans to address this limitation and/or how to overcome other than trying to work around it with manual inlining and lto?

**Comment by oli-obk** [comment]
@daschl it's a hard problem, there were some discussions on users.rust-lang.org and internal.rust-lang.org

**Comment by bluss** [comment]
Your iterator is using a function pointer — I would avoid that for performance. (I haven't checked if that's what making the difference, though) A function pointer call is indirect and may not be inlined. It's something that the compiler could optimize away, and I can understand if that's not being achieved cross crate.

With closure trait impls being unstable, one way to use closure traits and still have custom nameable types for specific cases (the split whitespace's closure/function) is to use the pattern of a custom trait which is blanket implemented for closures, and implemented separately for specific cases. [Example here](https://github.com/bluss/rust-itertools/blob/59aa2f7801a6efde8a27e5f7c8dd36c25d996f54/src/groupbylazy.rs#L4-L8).

**Comment by daschl** [comment]
@bluss thanks much, changing it to traits AND using lto it is faster now. I think this is because even in the "all in one" case I'm importing the token and the other pieces so there is some assembling needed. see https://github.com/daschl/optim-repro/commit/4cdff20c9610defe0943fc3a9568c271e6b016eb

New numbers blow me away, amazing:

```
test bench_allinone ... bench:       3,608 ns/iter (+/- 1,157)
test bench_imported ... bench:       2,893 ns/iter (+/- 884)
```

I'll close this out since we know how to fix it: avoid function pointers in favor of traits and use lto. Btw without lto its slower still, but I can live with that :)
