### ISSUE TITLE
Rust is very slow in debug builds on Windows

### ISSUE THREAD

**Issue by changm** [rust-lang/rust#37643]
I don't have any benchmarks, but building webrender in debug vs release on Windows feels like it's 10x slower to start gecko w/ webrender than on OS X. Please make rust debug builds as fast as they are on OS X. Thanks!

**Comment by nagisa** [comment]
This issue as written is hardly actionable. First of all the OSes are different enough to make the comparison an apples-to-oranges; Second there’s no steps to reproduce the issue, and seeing the description it involves a fuzzy metric of a HUGE project.

**Comment by sanxiyn** [comment]
Just to be clear, this is about performance of code generated in debug build, not about compile time, right? In general, compile time of debug build and performance of release build have been priorities, and no effort was made to make debug build fast.

**Comment by Mark-Simulacrum** [comment]
I don't believe this is a concrete enough bug to be actionable. If we could at least get a smaller reproduction, that would be great, but I'm also uncertain whether this is really a problem on rustc's side, it might be more of an LLVM problem since the platform specific handling of, for example, landing pads is very different across the two platforms.
