### ISSUE TITLE
Consider reverting atomic types implementing UnwindSafe

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#37674]
@glaebhoerl's argument against this [here](https://github.com/rust-lang/rust/issues/37136#issuecomment-254067201) seems correct to me.

UnwindSafe is for preventing logic errors due to partial state updates that are interrupted by unwinding, and captured atomics allow for that.

**Comment by abonander** [comment]
Isn't this a breaking change now? 

I think the spirit of `UnwindSafe` is to prevent logic errors being introduced when you have interdependent bits of state that you expect to agree with each other after a mutation but which a panic during such a mutation can screw up. This already has to be taken into consideration when using atomics because they can be updated concurrently.

**Comment by aturon** [comment]
@abonander 

> The issue of partial state updates already has to be taken into consideration when using atomics because they can be updated concurrently.

I agree with this entirely -- was just coming to this thread to say the same thing :-)

**Comment by alexcrichton** [comment]
Agree as well that effectively anything which is `Send + 'static` is effectively "unwind safe" because this can be done today:

```rust
fn catch_unwind<F, R>(f: F) -> Result<R> 
    where F: FnOnce() -> R + Send + 'static,
          R: Send + 'static,
{
    thread::spawn(f).join()
}
```

So in that sense, `AtomicUsize` is `Send + 'static`, so it's `UnwindSafe`.

**Comment by glaebhoerl** [comment]
Good points, thanks.

I'm not completely convinced by the "blanket" arguments from `thread::spawn` however. Given that `UnwindSafe` is more of a lint and not enforcing any hard guarantee as it is, the fact that you can already do a particular thing a different way as well seems kind of neither here nor there. This isn't a `mem::forget` situation, in other words. The goal isn't to absolutely forbid shared mutable state being observable after a panic, it's to flag the potential for insidious bugs when using `catch_unwind`. So I think a blanket argument for all `Sync` types or all `Send + 'static` types would need to show that they are inherently, by their nature, not vulnerable to those kind of bugs in the first place. That may well be the case; I haven't thought it through! The other possibility is that they (at least some of them) *do* have the potential for such bugs, which `thread::spawn` isn't flagging, in which case it would still be preferable to flag them for `catch_unwind` than not to.

In the particular case of atomic types, the point that "you have to guarantee that global invariants hold at all times anyway, since the data can be observed concurrently at any point" as @aturon also put it [here](https://www.reddit.com/r/rust/comments/5c00a9/this_week_in_rust_155/d9to7k1/) seems fairly conclusive.
