### ISSUE TITLE
Leaking HashMap Drain Iterator leaves Map in broken state.

### ISSUE THREAD

**Issue by Popog** [rust-lang/rust#37777]
Unlike `Vec::drain`, `HashMap::drain` doesn't take enough precautions against `mem::forget`, leading to a corrupt HashMap

https://is.gd/YktSDH

Unlike `Vec::drain`, setting the size to 0 won't mitigate this, as the buckets would still appear to be full and break future insertions.

The entire `drain` algorithm needs to be replaced with something like what's in my [Pre-RFC](https://internals.rust-lang.org/t/pre-rfc-retain-iterators-api-for-hashset-hashmap-vec-vecdeque/4164)

**Comment by bluss** [comment]
Can this be a memory safety issue?

**Comment by Popog** [comment]
I don't think so.

Items which have been `drained` and thus shouldn't be accessible have been protected by `EMPTY_BUCKET`. 

None of the invariants of **table.rs** are being broken (which is where any `unsafe` code lives), just Robin Hood hashing invariants in **map.rs**.

**Comment by alexcrichton** [comment]
Note that this is basically accepted and find in the mind of the libs team (afaik). That is, leaks can leave objects in invalid states. So long as it's not a memory safety issue then this is fine to have. Leaks are exceedingly rare and bugs that need to be fixed anyway, so the libs team decided that it's not worth bending over backwards or hampering APIs just because it can cause weird behavior (not undefined behavior)

**Comment by Popog** [comment]
If it's OK, I'd like leave this open while my RFC is still pending, as in it's present form, my RFC essentially fixes this at next to 0 runtime cost (basically iterating backwards as opposed to the current forwards, which isn't breaking as no iteration order is guaranteed).

**Comment by alexcrichton** [comment]
Oh yeah fixing this with no cost to hashmaps would be great! I'd be totally down to r+ that :)

**Comment by Mark-Simulacrum** [comment]
Seems like we can probably close this since we're okay with current behavior.
