### ISSUE TITLE
A remote macro cause the program not to compile even if I don't call it

### ISSUE THREAD

**Issue by AndyShiue** [rust-lang/rust#37781]
I'm using nom, and I encountered this strange thing that I suspect is a bug. Here is the minimal example:

```rust
#[macro_use] extern crate nom;
macro_rules! m { ($c:tt) => { /* put anything here */ }; }
named!(f, m!( /* put anything here */ ));
```

I'm using rust 1.13.0 and the version of nom on Github.

**Comment by durka** [comment]
In the future you should include the error output in bug reports. The error I get is:

```
error: no rules expected the token `,`
  --> <nom macros>:20:18
   |
20 | { $ submac ! ( i , $ ( $ args ) * ) } ) ; (
   |                  ^

error: Could not compile `expr`.
```

I'll proceed assuming you see the same thing.

The [documentation for `named!`](https://docs.rs/nom/1.2.4/nom/macro.named!.html) is not the greatest, but looking at the [source](https://docs.rs/nom/1.2.4/src/nom/.cargo/registry/src/github.com-1ecc6299db9ec823/nom-1.2.4/src/macros.rs.html#95-146) the rule that matches is this one (line 116):

```rust
    ($name:ident, $submac:ident!( $($args:tt)* )) => (
        fn $name( i: &[u8] ) -> $crate::IResult<&[u8], &[u8], u32> {
            $submac!(i, $($args)*)
        }
    );
```

So the second argument is `$submac:ident`, to which you are passing `m`, and it's going to be called as `$submac!(i, $($args)*)`, that is, it gets passed an `ident` and whatever other arguments you provided to `named!`. But your macro `m!` only accepts one token, so that isn't going to parse.

**Comment by AndyShiue** [comment]
> In the future you should include the error output in bug reports.

I definitely should and would have done it, but somehow forgot to do so.

It's still surprising for me that even the parsing of a Rust macro invocation can be parsed in another way than actually an invocation, but that must be intended and cannot be changed ... however, is there a workaround?

**Comment by durka** [comment]
The input to a macro is merely a sequence of tokens which the macro can parse however it wants.

**Comment by AndyShiue** [comment]
How can a macro inside another macro normally be parsed, though?

**Comment by durka** [comment]
Well, exactly the way `named!` does it -- you put `$mac:ident ! ( $($args:tt)* )` in the syntax pattern.

**Comment by AndyShiue** [comment]
```rust
fn main() {
    println!("{:?}", vec![0]);
}
```

I mean this one

**Comment by durka** [comment]
Nothing stops the first macro from outputting the second macro exactly as it was given as input, so it will be evaluated in the next iteration of the macro expander.

**Comment by AndyShiue** [comment]
So ... is there simply no workaround? D:

**Comment by durka** [comment]
A workaround for what? I don't understand what you think the problem is.

**Comment by AndyShiue** [comment]
I want to actually call a macro inside `named!`. I've tried calling macro using square brackets, but that didn't seem to work.

**Comment by durka** [comment]
The bracket type has no effect on macro expansion.

Oh, you mean you have a macro whose output you want to pass to `named!`? The only way to do that is to call `named!` in the expansion of your macro:

```rust
macro_rules! m {
    (...) => {
        named!(....)
    }
}
```

**Comment by durka** [comment]
You may also see [this RFC](https://github.com/rust-lang/rfcs/pull/1628), which would let you write `named!(f, $!m(...))`, but only _within another macro_.

**Comment by AndyShiue** [comment]
Yeah, the way it is now seems to break the abstraction; I have to reimplement part of `named!`. A solution would be much better. Can't we just add more `!`s to disambiguate? XD

**Comment by durka** [comment]
As I mentioned somewhere in the long thread of comments to that RFC, more bangs isn't an option because I can currently write a macro pattern like `($m:ident ! ! ! !)`, but the `$!` syntax proposed there works (because it doesn't parse now, so it isn't a backwards compatibility hazard).

Instead of tying `m!` directly to `named!`, you can give it a more general "callback" mechanism to decouple things, at the cost of an auxiliary macro:

```
macro_rules! m {
    (... -> $then:ident!) => {
        $then!(...)
    }
}

macro_rules! then_named! {
    ($($args:tt)*) => {
        named!(f, $($args)*)
    }
}

m!(... -> then_named!);
```
