### ISSUE TITLE
BrokenPipe sometimes not reported

### ISSUE THREAD

**Issue by jorendorff** [rust-lang/rust#37807]
Try piping this program's stdout to `head`. After the first 10 lines, `head` will exit. The pipe is now broken, so the next write should fail, and we should get `thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)'`

Instead, the Rust program keeps running indefinitely. GDB says `SIGPIPE` is "received" (but I guess ignored) by the process every time it tries to write.

Feels like a race condition: if you remove the `sleep` or just change it to be short, `println!` panics as expected.

```rust
// usage: ./yep | head
use std::time::Duration;
use std::thread::sleep;

fn main() {
    loop {
        println!("y");  // should panic after `head` exits
        sleep(Duration::new(0, 250_000_000));
    }
}
```

tested on Linux, `rustc 1.15.0-nightly (0ed951993 2016-11-14)`

**Comment by alexcrichton** [comment]
I believe what's happening here is in [`LineWriter::write`](https://github.com/rust-lang/rust/blob/9d4b6fa51d86ad6141679a5a157fcd9bca48064c/src/libstd/io/buffered.rs#L767-L784). We detect that what's being written (`"y\n"`) has  newline in it and take the first branch. [This write succeeds](https://github.com/rust-lang/rust/blob/9d4b6fa51d86ad6141679a5a157fcd9bca48064c/src/libstd/io/buffered.rs#L772) because the underlying primitive is buffered (e.g. `BufWriter`) but then when `flush` is next called we [ignore the error](https://github.com/rust-lang/rust/blob/9d4b6fa51d86ad6141679a5a157fcd9bca48064c/src/libstd/io/buffered.rs#L773-L776) and return that the bytes were written. If you let the program run long enough the buffer fills up and the error gets propagated through a call to `write` I believe.

Seems kinda weird to me to ignore that error, we should probably do something like this instead:

```rust
if n != i + 1 || { self.flush()?; true } {
    return Ok(n)
}
```

That is, propagate an error in flush if we wrote the entire line.

**Comment by alexcrichton** [comment]
Well...  maybe not. So apparently this behavior changed in https://github.com/rust-lang/rust/pull/32107 to fix https://github.com/rust-lang/rust/issues/32085.

cc @Stebalien, thoughts?

**Comment by jorendorff** [comment]
Interesting. The new code doesn't satisfy the "write-xor-error guarantee" either, though. It does up to three operations on the underlying `BufWriter`, so of course the first can succeed and others can then fail. For example,  `line_writer.write(b"hello\n...1KB without newline...")` could write `hello\n` successfully all the way through, then fail trying to write the rest.

Maybe the guarantee should be weakened to a reasonable-effort sort of thing. It's important in some systems-y cases where the user knows the type of the writer (e.g. a raw `File` being used as a transaction log). It doesn't seem valuable more generally, and I'd expect third-party impls of `Write` to break it more often than not.

**Comment by alexcrichton** [comment]
This also interacts with the [documented semantics of `Write::write`](https://doc.rust-lang.org/std/io/trait.Write.html#errors) which indicates 

> If an error is returned then no bytes in the buffer were written to this writer.

That's probably just an erroneous clause targeted at, for example, file descriptors. With buffered readers and writers (like a line writer) I think we fundamentally just can't uphold that guarantee.

Nominating for @rust-lang/libs discussion as I think we'll want to reword that documentation.

**Comment by jimblandy** [comment]
In some cases, `write`'s caller is counting on the fact that an error means no bytes were written. For example, if an operation returns `WouldBlock`, the caller needs to know where to pick up writing again. 

An abstract interface can't reasonably guarantee that any specific downstream source has received and acknowledged the data. On Unix, even if you do a `write` system call and it succeeds, the kernel might still be buffering the data, so you don't know if it's made it to disk or not. You have to do an `fsync` to find out whether it really made it.

But an abstract interface can and should be expected to let its user keep track of where it needs to continue its work, in the case of an intermittent error condition like `WouldBlock`.

**Comment by Stebalien** [comment]
>> If an error is returned then no bytes in the buffer were written to this writer.

> That's probably just an erroneous clause targeted at, for example, file descriptors. With buffered readers and writers (like a line writer) I think we fundamentally just can't uphold that guarantee.

That clause is actually pretty important. Otherwise, you can't be sure of the state of a writer after it returns an error. For example, the following could would write "abc" twice if interrupted:

```rust
LineWriter::write_all("abc\ncde\n"); 
```



---

When I wrote that patch, I was thinking that the next write after a failed flush would error out but obviously didn't think it though. So, a simple fix would be to record that a flush didn't happen and try to flush before writing anything else (i.e., on the next call to write). Unfortunately, this does mean that writing a newline wouldn't guarantee a flush but I don't think there's much we can do about that at this point.  I believe a `PartialWrite` error was discussed in the past but was rejected as it would make `io::ErrorKind` larger.

Alternatively, as we haven't actually written anything to the underlying file yet, `LineWriter` could just "undo" the write (either by reaching into `BufWriter` or re-implementing `BufWriter`).

**Comment by alexcrichton** [comment]
@jimblandy yeah it's definitely true that it's useful to have this guarantee, and it may just not be possible to relax the guarantee.

@Stebalien yeah on second though retrying the flush on the next `write` sounds like it'd be a good idea (at least for now). I think that we'll need to update `LineWriter::write` no matter what b/c the successfully written bytes are papered over with an error I think if the second write fails, right?

**Comment by Stebalien** [comment]
> I think that we'll need to update LineWriter::write no matter what b/c the successfully written bytes are papered over with an error I think if the second write fails, right?

My point is to flush *first* if the last flush failed, then write if that flush succeeds. If the flush fails, return an error without writing anything (no papering over written bytes). However, the previously written bytes will not have been flushed so the documentation needs to be updated to say that we *try* to flush on newline but that flush *may* fail silently in some cases (and that the user should call `Write::flush()` to be absolutely sure).

**Comment by alexcrichton** [comment]
@Stebalien yeah that sounds good to me!

**Comment by jorendorff** [comment]
Since `LineWriter` and `BufWriter` are friends, I think it's possible to do this so that the first error is not ignored.

**Comment by alexcrichton** [comment]
Yeah that also seems reasonable to me, we could have `LineWriter` reach into internals if necessary.

**Comment by jimblandy** [comment]
Right, `BufWriter` is just an implementation detail of `LineWriter`, so if BW is not giving LW the information it needs, unless there's some more fundamental reason LW can't be implemented as specified, LW's implementation should just change.

**Comment by jorendorff** [comment]
Oh, it turns out my hunch was wrong. `LineWriter::write` inherently needs to do `write` and then `flush` on the underlying writer. If the `write` succeeds, we have to ignore errors from `flush`.

**Comment by alexcrichton** [comment]
I've opened a PR as https://github.com/rust-lang/rust/pull/38062
