### ISSUE TITLE
Dump the AST without converting to JSON

### ISSUE THREAD

**Issue by spinda** [rust-lang/rust#37873]
Like #10485, but using Rust's pretty-printed debug output (`{:#?}`) instead of a JSON encoding. This would be much easier for a human to read when trying to visualize how rustc interprets a particular syntax element (like I am right now). It could also be easily added to play.rust-lang.org as an additional output target, alongside the current ASM, LLVM IR, and MIR options. The output format wouldn't need to be stable or standardized, this would just be a debugging tool.

I imagine this would entail two additional `-Z` options, `ast` and `ast-noexpand`, to match `ast-json` and `ast-json-noexpand`. Am up for preparing a PR if one would be welcomed, implementation appears straightforward at first glance.

**Comment by Nemikolh** [comment]
http://www.jsoneditoronline.org/

**Comment by Mark-Simulacrum** [comment]
It looks like @spinda's PR for this almost went in but was blocked and eventually closed because statements didn't debug print quite as helpfully as desired. I don't know whether the debug statement printing is still the case. This issue seems reasonable (and I *guess* something we, in general, want) so I'm going to keep open. If anyone would like to implement, I think the suggestions I'd have is to look at #38083 (@spinda's PR) and then see if we can modify the debug statements as suggested there -- in particular, making them not pretty print. I'd remove the debug impls to make auditing the cases easier; then re-add them to support this PR. Arguably, the most "correct" thing would probably be to just change all of the current `{:?}` to `{}` for the pretty printing of statements, though I can imagine this being difficult due to being a passed-down state from above somewhere.

**Comment by Mark-Simulacrum** [comment]
In hindsight this seems pretty unlikely as something we actually want to keep an issue open for, since implementing it isn't something we actively want to pursue (though, after some discussion on internals if there's interest I think a PR could be accepted).
