### ISSUE TITLE
Unergonomic error message when specifying invalid stage0 triple in rustbuild

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#37898]
Set an invalid stage0 triple (build = "invalid-something") in config.toml, then you'll get a very strange error:

```
src/bootstrap/bootstrap.py, line 74, in verify
expected, _ = f.readline().split()
ValueError: too many values to unpack
```

**Comment by zackmdavis** [comment]
This is because the when the triple is invalid, we end up downloading the [404 page](https://static.rust-lang.org/dist/2016-09-28/rust-std-beta-invalid-something.tar.gz.sha256) (well, XML blob) for the tarball and checksum, and `.split()`ing the 404 result for the checksum does not result in the expected number of substrings.

One possible solution might be to rewrite `download()` to use Python standard library functionality (which takes care of the platform-dependence for us), rather than shelling out to PowerShell/curl, and actually checking the HTTP status code.
