### ISSUE TITLE
Allow building benchmarks with rustbuild

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#37897]
Rustbuild should allow building / testing / running benchmarks

I imagine rustbuild's approach will be a lot better for benchmark development and running compared to the old makefiles.

Optional parts:

- Allow testing different optimization / compiler flags

**Comment by alexcrichton** [comment]
To clarify, by benchmarks, do you mean the one in libraries? (like `src/libstd` and such).

If that's true then I could totally see this being something like:

```sh
./x.py bench src/libstd
./x.py bench src/libcore
# ...
```

**Comment by bluss** [comment]
Yes, for example src/libcollectionstest/ contains benchmarks that I want to add to & run.

**Comment by alexcrichton** [comment]
Cool! In that case this should be relatively easy to do I think. The steps for this would be:

* Add a new [`Bench` subcommand](https://github.com/rust-lang/rust/blob/fb122199aac1fd4f9a3c133e25791a9fcb2a6b83/src/bootstrap/flags.rs#L41-L56) along with all necessary flag parsing for it
* Add a new [`Bench` kind](https://github.com/rust-lang/rust/blob/fb122199aac1fd4f9a3c133e25791a9fcb2a6b83/src/bootstrap/step.rs#L448-L454) for generating build steps
* Add a [convenience method](https://github.com/rust-lang/rust/blob/fb122199aac1fd4f9a3c133e25791a9fcb2a6b83/src/bootstrap/step.rs#L531-L549) for generating bench rules
* Add a [rule for each crate](https://github.com/rust-lang/rust/blob/fb122199aac1fd4f9a3c133e25791a9fcb2a6b83/src/bootstrap/step.rs#L267-L272) to run benchmarks. Here everything depend on `libtest`
* Add a method to actually run benchmarks [in `check.rs`](https://github.com/rust-lang/rust/blob/fb122199aac1fd4f9a3c133e25791a9fcb2a6b83/src/bootstrap/check.rs). Probably just modify the [existing `krate` method](https://github.com/rust-lang/rust/blob/fb122199aac1fd4f9a3c133e25791a9fcb2a6b83/src/bootstrap/check.rs#L269-L354) to just call `cargo bench` instead of `cargo test`.

And I think that's it! After that `./x.py bench` should run all the benchmarks we've got for all crates, and specific crates could be selected like `./x.py bench src/libcollections`.
