### ISSUE TITLE
Strange error when calling transmute on pointer to Self in trait's default function

### ISSUE THREAD

**Issue by JinShil** [rust-lang/rust#37957]
First, examine the following code, and its resulting error message:
```Rust
fn main() {
    let v64: u64 = 64;
    let v32: u32 = 32;
    
    unsafe {
        println!("{}", mem::transmute::<u32, u64>(v32));
    }
}
```
```
error[E0512]: transmute called with differently sized types: u32 (32 bits) to u64 (64 bits)
  --> <anon>:44:24
   |
 6 |         println!("{}", mem::transmute::<u32, u64>(v32));
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^ transmuting between 32 bits and 64 bits
```
Specifically, notice that the size of each type is listed in the error message:  "u32 (**32 bits**) to u64 (**64 bits**)".

Now, examine this code and its resulting error message:
```Rust
use std::mem;

trait HasAddress {
    fn get_address(&self) -> *const u32 {
        unsafe { mem::transmute::<&Self, *const u32>(self) }
    }
}

fn main() { }
```
```
error[E0512]: transmute called with differently sized types: &Self (pointer to Self) to *const u32 (64 bits)
 --> <anon>:5:18
  |
5 |         unsafe { mem::transmute::<&Self, *const u32>(self) }
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ transmuting between pointer to Self and 64 bits
```

I'm assuming two issues here:

1. In the error message for the last example, the size for `&Self` is printed as "(pointer to Self)" instead of the actual numeric size as was printed in the first example.
2. `&Self` and `*const u32` are both addresses, so I'm assuming they should transmute fine without error.

**Comment by abonander** [comment]
I believe that this is because the size of `&Self` can vary depending on calling context; if this is a trait object, then `&Self` will be two words whereas it would otherwise be just one. 

If you add `where Self: Sized` to the trait method signature, does it fix the error? If so, then that was the issue.

**Comment by arielb1** [comment]
@JinShil 

If `Self` is a non-`Sized` type (e.g. if someone does `impl HasAddress for [u8] {}`), then a pointer to it is a fat pointer, and has size 2 words, so your implementation is correctly detected as invalid. Adding a `Self: Sized` bound fixes the problem.

BTW: You can do `self as *const Self as *const u32` instead of a `transmute`, which works even when `Self` is unsized.

**Comment by JinShil** [comment]
@abonander and @arielb1  Thank you for the explanation.  I understand now.

However, I still see an issue with the error message.  

If `Self` is a fat pointer, and that information is known at compile time, I believe the error message should state the fat pointer size in the error message instead of "(Pointer to Self)".  

If `Self` varies in size with the calling context, then again, the error message should say so instead of "(Pointer to Self)".  In fact, in my experiments, I did see the compiler output such a message once (I think it said "(Variable-size type)"), but it escapes me now how to reproduce it.

Had the compiler output this information in the error message, I probably would not have submitted this issue.
