### ISSUE TITLE
getting parity of signed integer maximum or minimum results in stack overflow

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#37991]
Some examples that cause rustc to overflow its stack:
```rust
assert_eq!(i64::max_value() % 2, 1);
assert_eq!(i64::min_value() % 2, 0);
```

Give error message at compile time:

```
thread 'rustc' has overflowed its stack
```

Gives a stack overflow too if you use `i8`,`i16`,`i32`, but it can't be reproduced with unsigned types.

Also, this doesn't reproduce the stack overflow either:
```rust
let m = i64::min_value();
assert_eq!(m % 2, 0);
```

This dates back to at least rustc 1.12 stable, and is reproducible with recent nightly as well.

**Comment by est31** [comment]
Note that literals don't invoke the bug:

```rust
assert_eq!(127i8 % 2, 1);
assert_eq!(-9223372036854775808i64 % 2, 0);
``

**Comment by est31** [comment]
At least when I look at the stack, it seems to look like a MIR issue...

**Comment by est31** [comment]
The stack trace looks like this:
```
rustc_mir::transform::promote_consts::Promoter::promote_temp
<rustc_mir::transform::promote_consts::Promoter<'a, 'tcx> as rustc::mir::visit::MutVisitor<'tcx>>::visit_lvalue
[...] (lots and lots of these two functions calling each other)
<rustc_mir::transform::qualify_consts::QualifyAndPromoteConstants as rustc::mir::transform::MirMapPass<'tcx>>::run_pass
rustc::mir::transform::Passes::run_passes
rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::{{closure}}
[...] (I hope from here on its the same for each rustc invocation)
```

**Comment by jonas-schievink** [comment]
cc @eddyb

**Comment by eddyb** [comment]
The minimal reproduction is `&(i64::max_value() % 2)`, with `&i64::max_value()` compiling fine.
Any macro that does formatting (including `assert_eq`) should be avoided from minimal examples, as the MIR and LLVM IR they generate for the formatting machinery is much noisier than the buggy part, usually.

The stack trace may suggest some cycle at the MIR level, which would be weird, or accidental recursion.

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by nikomatsakis** [comment]
@eddyb any luck tracking this down?

**Comment by eddyb** [comment]
Found the culprit: [when we don't want to steal the call](https://github.com/rust-lang/rust/blob/fd5dc057936f5d84ccd8c1d5965f60e669b589d8/src/librustc_mir/transform/promote_consts.rs#L235), we're not [taking the destination](https://github.com/rust-lang/rust/blob/fd5dc057936f5d84ccd8c1d5965f60e669b589d8/src/librustc_mir/transform/promote_consts.rs#L244-L248) out of the clone.
I don't think this can succeed, seems like it would always infinitely recurse as the destination is always there, but even if it did, the resulting MIR may have a malformed cleanup edge left around.

The reason the "stealing" case is complex in the first place is to get the `target` for the goto, I think the infinite recursion bug was avoided by accident there, not by design.

**Comment by brson** [comment]
@eddyb will backport for 1.15 on feb 2.

**Comment by nikomatsakis** [comment]
#38408 is a duplicate, so whoever fixes this should check that out too.

**Comment by brson** [comment]
This needs to be fixed and backported soon. Release is feb 2. I'd like this backported by the third week of jan at latest.

**Comment by est31** [comment]
I'll give it a try later today.

**Comment by est31** [comment]
Sorry, I think the code is too unfamiliar to me. I don't want to fix it anymore :) 

@arielb1 do you want to take over?
