### ISSUE TITLE
FlatMap iterator calls next/next_back after they return None

### ISSUE THREAD

**Issue by Veedrac** [rust-lang/rust#37990]
Unfused iterators strike again! Iterators in general cannot have `next` called on them after they return `None`. However, `FlatMap`'s `next` and `next_back` methods poll this repeatedly.

If a `FlatMap` has a non-`None` `backiter`, exhausting the iterable through `next` means calling

    match self.iter.next().map(&mut self.f) {
        None => return self.backiter.as_mut().and_then(|it| it.next()),
        ...
    }

repeatedly after `iter` was exhausted, and vice-versa if it has a `frontiter` and is exhausted backwards.

The most obvious fix is to make the `iter` field fused, though that has a performance penalty.

---

Ugly code sample:

    struct Unfused(u8, u8);

    impl Iterator for Unfused {
        type Item = u8;
        fn next(&mut self) -> Option<u8> {
            if self.0 == self.1 {
                println!("finished (next)");
                return None;
            }

            let x = self.0;
            self.0 += 1;
            Some(x)
        }
    }

    impl DoubleEndedIterator for Unfused {
        fn next_back(&mut self) -> Option<u8> {
            if self.0 == self.1 {
                println!("finished (next_back)");
                return None;
            }

            self.1 -= 1;
            Some(self.1)
        }
    }

    fn main() {
        let mut myiter = Unfused(0, 2).flat_map(|_| (0..2));
        myiter.next_back();
        for _ in myiter {}
    }

This prints `finished (next)` twice, both times from `next`.

**Comment by bluss** [comment]
Fusing `iter` shouldn't be a big problem, since that's not the innermost loop.

**Comment by nagisa** [comment]
> Iterators in general cannot have next called on them after they return None.

Where does this misconception comes from? You can call `next` on any iterator as many times as you want regardless of what they return, except if an iterator itself documents otherwise.

I personally think the current behaviour is correct, primarily because of code such as this:

```rust
use std::net::{TcpListener, TcpStream, SocketAddr};

struct NonBlockingAcceptor(::std::net::TcpListener);

impl Iterator for NonBlockingAcceptor {
    type Item = ::std::io::Result<(TcpStream, SocketAddr)>;
    fn next(&mut self) -> Option<Self::Item> {
        let accept = self.0.accept();
        match accept {
            Err(ref e) if e.kind() == ::std::io::ErrorKind::WouldBlock => None,
            v => Some(v)
        }
    }
}

fn main() {
    let listener = TcpListener::bind("0.0.0.0:8080").unwrap();
    listener.set_nonblocking(true);
    let mut iter = NonBlockingAcceptor(listener).flat_map(Result::ok);
    loop {
    // epoll(listener);
    while let Some((client, peeraddr)) = iter.next() {
        println!("got client {:?}", peeraddr);
        client.shutdown(::std::net::Shutdown::Both);
    }
    }
}
```

if you made `flat_map` fuse the `NonBlockingAcceptor`, then the code would change in purpose and behaviour and flatmap itself wouldn’t make much sense anymore either.

**Comment by bluss** [comment]
I agree that you can call `next` or `next_back` when you want, but they can return what they want after the first `None`.

The current flat map behavior is wrong because it's skipping past the end of the adapted iterator even if .next/.next_back() are only ever called while the flat map has returned Some.

**Comment by bluss** [comment]
Skipping past the end is bad, because it can "reorder" elements. I.e it fetches a new iterable from the adapted iterator before going through the already fetched `self.backiter`.

**Comment by bluss** [comment]
I've written a simple fix using .fuse(). Is there a way to fix this while satisfying both the bug report and nagisa's concerns?

**Comment by bluss** [comment]
A fuse that is only fusing when used with a double ended iterator?

**Comment by Veedrac** [comment]
Fusing dependent on double endedness doesn't seem ideal. Perhaps both cases could be dealt with by making it so that when `iter` returns `None`, and then exhausting `backiter`, the iterator returns `None` once before going back to poll `iter`.

Fusing `iter` can hurt because the inner loop can be as simple as an `if`, if you're using `flat_map` over `Option`s.

**Comment by bluss** [comment]
at least we have fuse specialization, so often fuse is a no-op (more or less).

I don't immediately see how we can do this correctly without either fuse or a state variable inside flat_map (like chain uses one). The benefit of fuse is that it the state goes away by itself, but we could reuse `FusedIterator` for specialization again.

**Comment by nagisa** [comment]
I’ve thought about this extensively and I couldn’t think of a sane behaviour (no, fusing the internal iterator is not sane) for flat_map of double-ended iterators. I had written a long comment about my thoughts, but I’ve lost it since.

I’m starting to have doubts about about having `impl<I, U, F> DoubleEndedIterator for FlatMap<I, U, F> where I: DoubleEndedIterator` at all.

**Comment by bluss** [comment]
First I agree, DEI is a complication with next to no utility. (We can realize that sometimes separate forward/reverse iterators are better than having one double ended thing).

I don't see how fuse could not be sane.

I see it like this, let's look at a sequence of values returned from `Iterator::next()`

```
Iterator::next() -> [Some(1), Some(2), Some(3), None, None, Some(1), None, Some(3), ...]
                     ^---------------------------^
                     The iterator is equivalent to the sequence [1, 2, 3].                
```

The iterator's sequence is the strip of elements until `None` is first returned. `flat_map`'s contract is to flatten that sequence.

**Comment by nagisa** [comment]
@bluss I had a sample like this crafted, which in my opinion hasn’t a sane behaviour if underlying iter is fused:

```
let iter = [2, 2] None [4, 4, 4, 4] [6, 6, 6, 6, 6, 6];
iter.next();
iter.next_back();
iter.next();
iter.next();
// No matter what you do here you won't see 4 yielded.
```

**Comment by bluss** [comment]
Yes. I don't think transmitting 4 at any point is something that's required.

If that would be nice to have, then flat map can reset the fuse just before it returns `None`.

However, I think it's not so bad to instead go for only fuse if the iterator is double ended. A double ended iterator has basically no chance of ever being something else than a range with two ends that meet in the middle.

**Comment by Veedrac** [comment]
@nagisa My option of yielding one `None` per `None` in `iter` would do so. After those calls, running `next()` would yield `[6, 6, 6, 6, 6, 6, None, 4, 4, 4, 4, None, None, ...]`. But TBH that iterator breaks so many conventions and I don't think we even need to guarantee any behaviour wrt. calling `next` after completion (even in the "obvious" case), since it's not documented.

**Comment by bluss** [comment]
For example if we imagine this comes from a double ended iterator ,we have two identical clones of the same iterator. First clone:

```rust
Iterator::next() -> Some([2, 2]), None, Some([4, 4, 4, 4]), Some([6, 6, 6, 6, 6, 6])
```

If we restart that  with the second clone and ask next_back instead it has to say

```rust
Iterator::next_back() -> Some([2, 2]), None
```

otherwise it's not self consistent and it's buggy.

**Comment by bluss** [comment]
In a way this seems like an issue of a technical point actually. Problems only appear if the adapted iterator is double ended and is not acting fused.

The original bug report is using the misleading name `Unfused` for an iterator that behaves like fused (guaranteed to continue to return None). This is quite typical of double ended iterators, almost a requirement since they need the consistency of representing a range with two ends.

**Comment by dtolnay** [comment]
I tend to agree with https://github.com/rust-lang/rust/issues/37990#issuecomment-263065005 that this issue is nothing to be concerned about in real usage. If someone feels strongly that this must be fixed, including a compelling reason from a real use case, I would be open to considering a PR or RFC but I don't think we need to continue to track this issue.
