### ISSUE TITLE
When target_family is None, rustc sets it to unix.

### ISSUE THREAD

**Issue by parched** [rust-lang/rust#38187]
See https://github.com/rust-lang/rust/blob/ebeee0e27e32e212979d9f38d285b1dc2816cd0a/src/librustc/session/config.rs#L946-L952

This is very unhelpful for bare-metal targets where there is no target family. Is there code that relies on it defaulting to unix if it is unspecified?

CC @arcnmx

**Comment by arcnmx** [comment]
All of the built-in `librustc_back` targets probably do, but that's easy to fix. The problem is that `unix` has always been the default, most custom user target specs probably rely on it (as the option was added more recently; a year ago is recent, right?). I'm certainly not a fan of there being any particular default. but I'm not sure that it can be changed if we want target specs to be backwards-compatible.

For embedded targets I'd suggest using a new `target_family` like `"none"` or whatever best describes the platform; that's why the option was added in the first place!

**Comment by parched** [comment]
Ok yes, changing it would break backwards compatibility. Although I wonder how many non unix target specs out there will break when they hit a crate with `#[cfg(unix)]` if we leave it as is (like happened to me with the rustc builtin `*-none-eabi` targets).

If we leave it as is, we should add `target_family = "none"` to the builtin `*-none-eabi` targets and also add a comment for `target_family` that it defaults to unix.

**Comment by parched** [comment]
Also related are `os`, `vendor` and `env`, currently you get the following
```
$ rustc --target=thumbv6m-none-eabi --print cfg
target_env=""
target_family="unix"
target_os="none"
target_vendor=""
```

they should consistently all be `None` of some form, whether that's `"none"` or `""` I'm not sure.

CC @japaric

**Comment by japaric** [comment]
This should have been fixed (the target_family part) in #38401.

**Comment by parched** [comment]
OK, yes that is my preferred fix, but it will probably break some custom target specs as @arcnmx mentions.

**Comment by FenrirWolf** [comment]
I think a project of mine got hit by the fallout of this. Though what's more interesting is that manually setting the `target_family` field back to `unix` in my custom json spec doesn't seem to have any effect.
