### ISSUE TITLE
[rustbuild] Should print what command it couldn’t execute

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#38228]
Rustbuild now prints

```
failed to execute command: No such file or directory (os error 2)
```

which is very not helpful.

**Comment by vadimcn** [comment]
I've hit this one too: When there's a stale config.mk in Rust's root directory, bootstrap reads paths from there and tries to convert them into windows format using `cygpath` (which it, of course, can't find since we are not running in msys shell).

The error message comes from [this line](https://github.com/rust-lang/rust/blob/209308439a1099b285520459f57e380f18793c07/src/build_helper/lib.rs#L66) in build_helper (called from [here](https://github.com/rust-lang/rust/blob/b1da18fe9be180ecfcfb1691c4eb669c496996f5/src/bootstrap/config.rs#L502)).
