### ISSUE TITLE
Automatic library search is crazy!

### ISSUE THREAD

**Issue by Timmmm** [rust-lang/rust#38266]
Suppose I want to link to `libsoundio`. I have a folder containing the MinGW and MSVC builds:

    libsoundio.a
    soundio.lib

In theory, I can specify linking to these files in `.cargo/config` as follows:

```
[target.i686-pc-windows-gnu.libsoundio]
rustc-link-search = ["libsoundio-1.1.0/i686"]
rustc-link-lib = [":libsoundio.a"]

[target.i686-pc-windows-msvc.libsoundio]
rustc-link-search = ["libsoundio-1.1.0/i686"]
rustc-link-lib = ["soundio.lib"]
```

The `:` is to make gcc behave sanely and not try to do automatic `lib`-prepending and all that nonsense. I don't think that is necessary on MSVC because they name libraries sensibly.

Unfortunately, as you can see in [this code](https://github.com/rust-lang/rust/blob/19a39710c494d9300ffdc4e3f40dfda0ef62f7ba/src/librustc_back/archive.rs#L57) Rust does crazy file-name mangling of its own. This is a *really* bad idea and leads to a huge confusing mess.

If I try and compile with the above files and config, I get this build error:

```
.... "libsoundio.lib" ....
  = note: LINK : fatal error LNK1181: cannot open input file 'libsoundio.lib'
```

Ok first wtf. I definitely didn't specify `libsoundio.lib` anywhere. Ok maybe Rust automatically prepends `lib`. That's pretty stupid (what if my file doesn't start with lib?) but ok. I'll rename `soundio.lib` to `libsoundio.lib`. Rebuilding...

```
.... "libsoundio.lib" "ole32.lib" "soundio.lib.lib" ....
  = note: LINK : fatal error LNK1181: cannot open input file 'soundio.lib.lib'
```

Ok. What. I... what do I do now? Maybe this will work?

    rustc-link-lib = ["soundio"]

```
..."libsoundio.lib" "ole32.lib" "soundio.lib"...
  = note: LINK : fatal error LNK1181: cannot open input file 'soundio.lib'

```
So it adds `.lib` to the end? Ok I'll rename my file back to `soundio.lib`.

```
..."libsoundio.lib" "ole32.lib" "soundio.lib" ...
  = note: LINK : fatal error LNK1181: cannot open input file 'libsoundio.lib'
```

Argh! Why is it trying to link two files?! I eventually worked out that removing the `rustc-link-lib` line entirely and naming the file `libsoundio.lib` works.

I would suggest totally removing the magic search code. People are perfectly capable of typing "lib" and it would greatly reduce confusion.

**Comment by retep998** [comment]
>Argh! Why is it trying to link two files?!

Are there any `#[link]` attributes in the code that are trying to link to `libsoundio`? If so, that would be duplicating whatever the build script is doing causing issues with trying to link two files.

>Unfortunately, as you can see in this code Rust does crazy file-name mangling of its own. This is a really bad idea and leads to a huge confusing mess.

That code should only fire when you link libraries using `kind=static`, which you should avoid if you don't need it. As long as you use either `kind=dylib` or the still unimplemented `kind=static-nobundle` it will just pass the name you specify along to the linker and not try to find the library itself.

**Comment by steveklabnik** [comment]
I don't know enough about this, so it's a question: isn't this more of a cargo issue than a rustc issue?

**Comment by Timmmm** [comment]
@retep998: Ah yes I should have said I have this in my code. It seemed to work fine with gcc, and in fact stopped working if I removed it:


```
#[link(name = "libsoundio")]
#[link(name = "ole32")]
extern {
	pub fn soundio_version_string() -> *const c_char;
        ....
```

I don't think I am using `kind=static` anywhere.

**Comment by retep998** [comment]
@Timmmm You're using build script overrides (in `.cargo/config`) to override what is being linked to, but they only override what is specified in the build scrip itself! If you specify what to link via `#[kind]` then that cannot be overridden by a build script override. Instead you end up with the library specified twice, once from the `#[link]` and again from the build script override. With this knowledge I can now answer some of your questions.

>Ok first wtf. I definitely didn't specify libsoundio.lib anywhere.

Oh yes you did. You specified `#[link(name = "libsoundio")]`.

>I don't think I am using kind=static anywhere.

It doesn't look like you are based on your repo, so that rustc code you linked shouldn't apply.

As for what is passed to the linker when you specify different names, here is a table.

specified|passed to linker
---------|----------------
soundio|soundio.lib
libsoundio|libsoundio.lib
soundio.lib|soundio.lib.lib
libsoundio.lib|libsoundio.lib.lib

As you can see, it does append a `.lib` extension unconditionally, but it never prepends anything, for msvc anyway. The reason you thought it was prepending `lib` was because of that `#[link(name = "libsoundio")]`.

I recommend removing your `#[link]` attributes and replacing them with commands in the build script itself, so that they can be overridden properly.

**Comment by phanimahesh** [comment]
@Timmmm Is the issue resolved?
If it still exists, can you provide any additional information? If not, can you please close this issue?

(Trying to triage and close resolved issues, h/t https://www.codetriage.com)

**Comment by Timmmm** [comment]
Well the behaviour hasn't changed, and I still think it is very unclear and *way* too 'magical'. But I don't expect it to ever change so in the interests of cleanliness I'll close this.
