### ISSUE TITLE
./configure fails for Minix

### ISSUE THREAD

**Issue by paulohrpinheiro** [rust-lang/rust#38290]
Minix is not supported:

```
$ ./configure
configure: looking for configure programs
configure: found program 'cmp'
configure: found program 'mkdir'
configure: found program 'printf'
configure: found program 'cut'
configure: found program 'head'
configure: found program 'grep'
configure: found program 'xargs'
configure: found program 'cp'
configure: found program 'find'
configure: found program 'uname'
configure: found program 'date'
configure: found program 'tr'
configure: found program 'sed'
configure: found program 'file'
configure: found program 'make'
configure: inspecting environment
configure: error: unknown OS type: Minix
```

Are there any plans to include this support? Is there a standard procedure that I can run to try to include this support? Thank you!

**Comment by steveklabnik** [comment]
> Are there any plans to include this support?

I'm not aware of any specific plans to support Minix.

> Is there a standard procedure that I can run to try to include this support?

Yes! For background, here's the details on support https://forge.rust-lang.org/platform-support.html

That is, we have a "tier" system. You start at the bottom and work your way up. The first step is to send in a PR that makes the build work. What that specifically means depends entirely on the platform itself. If you're interested in getting Minix support, writing that patch is priority number one.

Since we don't keep issues open to track platforms, I'm going to give this a close. But if you or anyone else wants to make progress, please send in that PR! Thanks.

**Comment by sanxiyn** [comment]
Just in case: there is now a functional port of Rust to Minix. https://github.com/ids1024/rust-minix
