### ISSUE TITLE
rustdoc: support external search engine

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#38360]
A server-based full text search engine handles large database better and normally have typo tolerance, advanced filters and works fast.

Doxygen has an option for it (`SERVER_BASED_SEARCH`).

**Comment by ishitatsuyuki** [comment]
To allow flexible search engine backends we need some kind of plugin system (which typically allows injecting/replacing a JS file), and I think we have a few ways to abstract search related code:

1. Let the search plugin handle all the UI, just pass a DOM node to it. A few CSS rules are exposed to uniform the look.

Pros: Allows backend specific options (like filters). Complies with Algolia's logo display policy.
Cons: Complexity handling the DOM.

2. Pass the query, let the search plugin return the results.

Pros: Easy and straightforward to code.
Cons: Less flexibility, no custom filter options.

3. Make an API call with a predefined schema.

Rationale: This is what Doxygen uses.
Cons: Requires more code, requires a dedicated API forwarding server (more latency).

@rust-lang/rustdoc Do you have any opinions on this?

**Comment by GuillaumeGomez** [comment]
It'd introduce a lot of issues but the main one: it'd force to have another server to make the docs work. Also, each crate has its own search-index, which would mean to have a server handling all of them (for each version of course).

Honestly, I don't think this is worth it, or at least it not for now. And the fact that you can have docs working locally without internet is a just plus.

**Comment by ishitatsuyuki** [comment]
@GuillaumeGomez

> it'd force to have another server to make the docs work. ... 
which would mean to have a server handling all of them

Can you elaborate why this is bad? A search server should be able to handle multiple indexes without issues. Also, most large scale search implementations will scale, if that's your question.

> Honestly, I don't think this is worth it, or at least it not for now.

IMO rustdoc search is pretty weak for now. Mainly it's lack of typo tolerance and it doesn't seem to search descriptions as well.

Another motivation for this is that sometimes index can get pretty large, at a few megabytes. This is painful to download on a throttled data plan, while a server side search can serve results fast.

**Comment by GuillaumeGomez** [comment]
> Can you elaborate why this is bad? A search server should be able to handle multiple indexes without issues. Also, most large scale search implementations will scale, if that's your question.

Just more requests and servers to maintain. It's already quite painful with `docs.rs`, `crates.io` and all the others so adding one would just add load over this. But my main point is the following: the server would have to deal with a lot of requests (which isn't an issue in itself), if anything happens to this server, no more search would be possible. Also, we're talking about doc search here, not something incredibly elaborate (even though improvements in docs search would be welcome).

> IMO rustdoc search is pretty weak for now. Mainly it's lack of typo tolerance and it doesn't seem to search descriptions as well.

It has some tolerance, just not a huge one. Again, improvements would be very welcome.

> Another motivation for this is that sometimes index can get pretty large, at a few megabytes. This is painful to download on a throttled data plan, while a server side search can serve results fast.

I agree with you on this one but I can use the following counter-argument: it's not much compared to multimedia content you have everywhere around the internet and it's certainly faster than sending a request to a server and get its answer (even more if it's a huge one!). The problem not being the server computation time but the answer's size.

Again, I'm not against it but I don't think right now is a good time. If you have issues with search, open issues and/or PR and I'll try to move forward on them when I have time to deal with them.

**Comment by QuietMisdreavus** [comment]
I'm personally against introducing a server component or an external API to the generated docs because it will catastrophically break offline docs. A key value of rustdoc's output is that you can take the bundle of files, cut off your network connection, and have the exact same experience. This is the key behind `cargo doc --open`, or `rustup doc --std`. I'm worried that if we introduce this to rustdoc, and *don't* have a way to keep offline search, we will face a similar backlash to when we turned off downloading the `rust-docs` rustup component on new installations by default.

Another key component of rustdoc's search is that it can work for totally private/internal/experimental crates that haven't, won't, or can't be published to a public index. Can Algolia (or whatever other search index service) support keeping a server behind a corporate firewall? Can it support generating a temporary index and spinning up a short-lived server to look through a quick version of the docs while the library is still being worked on?

-----

Reading over a couple of the early posts, it seems like this is already a thing in other systems, as an optional feature. I think i would be okay with an *option* to create a different search index and search integration code. However, i haven't interacted with that corner of rustdoc's codebase much at all, so i have no idea how difficult it would be to "just swap out the search provider".

I'd also be concerned about lock-in, or licensing issues with plugging into an external service. Are there required terms that need to be followed for Algolia to keep the search index? Can we be sure that integrating into their auto-complete will work as long as our local search index can? There are still plenty of old docs sitting around that aren't updated with each rust compiler release.

**Comment by GuillaumeGomez** [comment]
> Some downsides could be it being closed source, and the volume of docs.rs may be too huge for them to provide the OSS plan for free.

So to be clear: it's not opensource and it's not free. That's two **huge** cons.

> I've also seen increasing adoption of Algolia in the JS community.

On my side, that's clearly not a pro. JS community isn't a model to follow, not because it's bad but because it has nothing to do with Rust.

> Or do you have any concerns on implementing this right now?

rustdoc is changing *a lot* currently and search is clearly not an expected big change right now. We have issues being fixed, features being implemented and improvements being done, but a full switch is **not** expected.

**Comment by ishitatsuyuki** [comment]
Your comments seems to be exaggerating.

> it's not opensource and it's not free. That's two **huge** cons.

While Algolia is not open source, it doesn't mean that we're locked in to proprietary software. This proposal is just requesting to add search backends, and does not mean the removal of client-side search. If you hate SaaS, ElasticSearch is also an option, but its tuning is hard and likely cost more on infra.

And Algolia is free to a degree, especially with their [OSS offer](https://www.algolia.com/for-open-source). For hosting https://doc.rust-lang.org, the 100k OSS offer is enough. Also Rust already relies on some paid infrastructure like Travis. The case in question is docs.rs which hosts over 10k crates which doesn't fit in their default offer, but I can't tell more without contacting them.

> but a full switch is not expected.

I'm not saying that we should throw away the client-side search backend; I'm just adding server-side options with this proposal.

**Comment by steveklabnik** [comment]
Triage: no changes

**Comment by GuillaumeGomez** [comment]
Closing on the meantime since we don't intend to add it for the moment. Maybe it'll be done when we'll have another JS front-end based on the rustdoc multiple output formats.
