### ISSUE TITLE
links on first line of trait description are gone

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#38386]
See for example doc for the method scan: https://docs.rs/rawslice/0.1.0/rawslice/struct.SliceIter.html#method.scan

The link at `fold()` is removed because only the first line is shown in the trait impl documentation.

**Comment by QuietMisdreavus** [comment]
Hmm, from what I could tell by looking at [the same method in std](https://doc.rust-lang.org/std/str/struct.Chars.html#method.scan) in various versions of the std docs, this probably hasn't worked for the trait function summaries since they were printed in the first place. The summary lines in modules can format links just fine, so I'll take a look and see if that code can be adapted to trait impl rendering.

**Comment by QuietMisdreavus** [comment]
I could see "just render it so the link exists" backfiring because links are typically specified as relative links. This specific example would likely work because the link to `fold()` is specified as just the anchor ID, but I could easily see a summary line linking to a separate struct, or anywhere else within the crate. In that case, the relative link would be relative to the *implementer*, and it would create a broken link. It might be possible to strip the link out entirely, though. The code is trying to do that already, but it seems like the way it's passing the test to the Markdown renderer doesn't let it see that there's a link there.
