### ISSUE TITLE
rust 1.15 regression in cargo CARGO_OUT handling

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38391]
Linking this here for the regression tag.

https://github.com/rust-lang/cargo/issues/3368

https://internals.rust-lang.org/t/regression-report-stable-2016-11-08-vs-nightly-2016-12-06/4462/3

**Comment by alexcrichton** [comment]
Checking back in on this, there haven't been any more comments in https://github.com/rust-lang/cargo/issues/3368. For the breakage we've seen:

* pinyin has a PR - https://github.com/mozillazg/rust-pinyin/pull/5
* rasen is already fixed by removing the build script - leops/rasen@fa6ee9223d10e37c2e85b4f9c9739013b0f0c11b
* zip_codes has a PR - https://github.com/SkylerLipthay/zip_codes/pull/2

Still unsure what to do about this regression, but wanted to give a status report.

**Comment by brson** [comment]
I think we're pretty committed to leaving this as is.
