### ISSUE TITLE
`for` borrowing lasts after the end of the for loop

### ISSUE THREAD

**Issue by ProgVal** [rust-lang/rust#38614]
Hi,

The following code:

```rust
fn method(vector: &mut Vec<u64>) -> &u64 {
    {
        for item in vector.iter() {
            return item
        }
    }

    vector.last_mut().unwrap()
}
```

Raises an error about `vector.iter()`'s borrow conflicting with `vector.last_mut()`:

```
error[E0502]: cannot borrow `*vector` as mutable because it is also borrowed as immutable
 --> <anon>:8:5
  |
3 |         for item in vector.iter() {
  |                     ------ immutable borrow occurs here
...
8 |     vector.last_mut().unwrap()
  |     ^^^^^^ mutable borrow occurs here
9 | }
  | - immutable borrow ends here
```

 However, I would have expected the first borrow to end with the first closing bracket.

Playground URL: https://play.rust-lang.org/?gist=36c206ebc1f8c96b96978a628b5c09a9&version=stable&backtrace=0

**Comment by steveklabnik** [comment]
I _believe_ this is a duplicate, but I'm not sure.

**Comment by rkruppe** [comment]
This is because of lexical lifetimes and is thus covered by https://github.com/rust-lang/rfcs/issues/811. `item` is returned, so it must be valid for longer than the loop (longer than the function, actually) and consequently the vector is also borrowed for as long. This isn't a real problem because this only applies to the return path, but because lifetimes are lexical, the compiler only has one choice for the lifetime of that borrow (namely, the lifetime encompassing the whole function).

**Comment by steveklabnik** [comment]
I was not 100% sure, but this was also a suspicion I had. Thanks for the report, @ProgVal , but yes, it's covered by that linked issue.

**Comment by nox** [comment]
But the whole loop is in a block by itself, why would the borrow need to survive longer than the enclosing block?

**Comment by steveklabnik** [comment]
You're reading "not a real problem" backwards; @rkruppe is saying that your code is fine, that it doesn't have an actual problem. Borrowck can't understand that, though.

**Comment by nox** [comment]
Oh I see, thanks for the explanation!
