### ISSUE TITLE
The compiler gets confused if an additional "/*" is included in the comments

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/rust#38646]
e.g:
```
/*
 let foo = "/**";
 ...
*/
```
Leads to

```
error: unterminated block comment
  --> <anon>:1:1
   |
1  | /*
   | ^

error: aborting due to previous error
```

**Comment by xen0n** [comment]
This is working as intended, because

* Rust supports nested comments, and
* Text inside a comment block is not lexed like code (no parsing is done for the text!).

The compiler has no way to figure out whether the `/*` should be treated as start of a nested comment block or not, so it's just treated as such.

That said, maybe the diagnostics could be more helpful? However I seriously doubt we could do anything here, as we'd then have to do parsing from the lexer, not mentioning the difficulty telling code snippets apart from text.

**Comment by lu-zero** [comment]
It is quite anti-ergonomic, if that's intended please at least make `//` have priority over `/*` since:

```
/*
// let foo = "/*";
*/
```

won't make the thing behave.

**Comment by brson** [comment]
I doubt there is anything we can do to change this as it's a fundamental tradeoff on whether comments nest or not. The typical solution when this happens is to insert a unicode zero-width space in the comments so that it looks correct and parses correct.

**Comment by lu-zero** [comment]
Unicode zero-width is usually a cut-and-paste trap. 

What would be the problem in giving `//` the higher priority, thus making the parser stop reading once it is met at the start of the line?

**Comment by DemiMarie** [comment]
@lu-zero Another option is to use `//` comments everywhere, which do not have this problem.

**Comment by rkruppe** [comment]
> What would be the problem in giving // the higher priority, thus making the parser stop reading once it is met at the start of the line?

It would break backwards compatibility. This program compiles today and wouldn't with such a change: https://play.rust-lang.org/?gist=ce5f23f3c5d115c92507c94221481c1d&version=stable&mode=debug&edition=2015

**Comment by oli-obk** [comment]
This is a complex topic that at minimum requires an RFC and would probably need an edition to be possible without a breaing change.

I think it would be best to open an internals forum thread to hash out a general plan and then open an RFC
