### ISSUE TITLE
Emscripten target specs are conditional on the host platform

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38724]
In [this PR](https://github.com/rust-lang/rust/pull/38601), to make emscripten work on windows, the target specs are conditionalized to use `emcc.bat` as the linker, only on windows hosts.

In practice this should be perfectly fine, but I don't think it's correct for the target spec to vary like that and there should be some way to express the spec statically that works on both platforms.`

cc @schulzch

**Comment by schulzch** [comment]
Emscripten provides three files per command, e.g.:

- `emcc` python 2.x and 3.x wrapper which invokes `emcc.py` using python 2.x
- `emcc.bat` invokes `emcc.py` using `python`
- `emcc.py`contains the actual code

I think having a host platform dependent switch is not wrong, because that is how script commands are usually wrapped on windows - the Node.js package manager `npm` creates wrapper `*.cmd` files transparently on windows. 

The only other solution I can think of would be to enable shell expansion, i.e., to have windows append `*.exe`, `*.cmd`, `*.bat`, etc., which could imply a performance penalty (?).

**Comment by alexcrichton** [comment]
Nowadays we even have more special treatment of `emcc.bat`, so I think this may just be a necessary evil for now :(
