### ISSUE TITLE
Allow linking with macOS frameworks on non macOS when documentating

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#38755]
https://docs.rs/crate/fsevent/0.2.15 is broken due to use of a macOS framework while docs.rs uses linux.

**Comment by Mark-Simulacrum** [comment]
I feel like this should be using `cfg()`, possibly `cfg_attr(doc, cfg())` or something like this.

**Comment by jyn514** [comment]
I don't see what rustdoc can do about this. If the crate tries to use native dependencies that aren't available, then it will fail to build whether you run rustdoc or rustc.

Normally I'd transfer this to docs.rs, but since the latest version builds fine, I think it makes sense to just close this. Feel free to re-open if you're still having trouble.
