### ISSUE TITLE
Command-line option to list supported feature-gate names

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#38768]
I'd like to have a command-line option to list all the supported feature-gate names in rustc. This would simplify the job of tools that want to detect the features supported by the installed version of rustc.

I don't know if introducing an option like this would require an RFC, or just a patch. Posting this as an issue to find that out before working on a patch.

**Comment by rkruppe** [comment]
Is this about language features, library features, or both?

**Comment by est31** [comment]
I'm not sure whether this is what you want, but do you know of the output of `x.py src/tools/tidy`?

**Comment by joshtriplett** [comment]
@rkruppe Both, for as long as std and rustc remain coupled.  Anything supported in a `feature(...)` declaration.

**Comment by joshtriplett** [comment]
@est31 I didn't. That would work, if available as a runtime option rather than a build-time command.

**Comment by rkruppe** [comment]
Language features are listed in `librustc/middle/lang_items.rs`. Library features are a bit more difficult to enumerate because they're spread in annotations all over multiple crates (e.g., for the compiler to even know about the `test` feature, it must look at the `test` crate). Still, it ought to be feasible to load all relevant crates for `--print features` because the set is fixed and quite small. After all, third party crates can't (at least really really shouldn't) have stability annotations.

One wrinkle with the `tidy` tool is that it crawls the source code. So one would have to include its output into the binary as a static string, gross! Besides, it lists feature flags that aren't relevant to the current target. For example, on linux it lists various `windows_*` library features which are only applied to stuff behind a `cfg(unix)`. This is the right choice for development but probably not for "what feature flags can I set?".

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/45223 was supposed to close this, but github didn’t for some reason. Closing!
