### ISSUE TITLE
Tool support for testing wasm targets

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38803]
In order to make the wasm targets production ready we'll need a testing solution. Right now I'm inclined to teach [cross](https://github.com/japaric/cross) how to do it and call that the solution, but that excludes macOS hosts, and for now at least, Windows as well, since it relies on docker.

cc @japaric

**Comment by japaric** [comment]
> Right now I'm inclined to teach cross 

See rust-lang/cross#36. If `rustc` emitted *executable* `.js` files with a `#!/usr/bin/env node` shebang in them then `cross test` would work for the asmjs target. I'm not sure what else would need to be done for the wasm target though because `node hello-wasm.js` errors with node v7.3.0 as stated in that PR.

**Comment by alexcrichton** [comment]
I believe we've since implemented the "runner" configuration in Cargo, which I believe solves this.
