### ISSUE TITLE
Run all crates.io tests against wasm target to uncover fresh bugs

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38802]
To quickly get an idea for the ecosystem support for wasm we can pretty quickly run all the tests in the world with [cargobomb](https://github.com/brson/cargobomb). I think it makes a lot of sense, once some of the other low-hanging fruit is fixed, to run all crates' test suites under wasm before making the final push for production.

**Comment by steveklabnik** [comment]
Triage; this would be very cool! This isn't assigned to a team; I'm gonna ping @rust-lang/infra to see if they think this is feasible/worth spending resources on.

**Comment by Mark-Simulacrum** [comment]
I think at this point we've stabilized WASM to the extent that this wouldn't really be helpful -- it's also true that many crates would panic or otherwise not work just because some features on WASM aren't implemented today. I could see us perhaps trying to test WASI with this, but I don't personally think keeping this open just for that is worth while. I'm going to assign @alexcrichton as the person with the most WASM knowledge on the infra team though, I think they probably can make the call whether something like this is worth it.

**Comment by steveklabnik** [comment]
> it's also true that many crates would panic or otherwise not work just because some features on WASM aren't implemented today. 

Yeah, I mean, I think the original intention was to make sure that stuff worked properly, but I still think it would be cool to have some sort of "ecosystem report", like we could know how much of the ecosystem at least compiles on wasm, and let crate maintainers know if it doesn't, that kind of thing.

**Comment by rafaelcaricio** [comment]
We would need to filter out *-sys dependent crates and any crate that uses threads.

1. Creates that use native extensions will need to adapt their `build.rs` to support WASI.
2. Trying to run today crates that spawn threads will result in something like:
```
thread 'main' panicked at 'failed to spawn thread: Custom { kind: Other, error: "operation not supported on wasm yet" }', src/libcore/result.rs:1165:5
```

**Comment by Enselic** [comment]
Triage: Closing since this was proposed for closing without objections, and WASM is since long "pushed for production".
