### ISSUE TITLE
Can't compare FFI function pointers

### ISSUE THREAD

**Issue by YaLTeR** [rust-lang/rust#38848]
`extern "fastcall"`, `"system"`, `"cdecl"` and some others function pointers cannot be compared.

I tried this code:

https://is.gd/5JBZee
```rust
extern "fastcall" fn test() {}

fn main() {
    let fastcall_ptr: extern "fastcall" fn() = test;
    
    let check = fastcall_ptr == test;
}
```

I expected to see this happen: the code compiles fine.

Instead, this happened:

```
error[E0369]: binary operation `==` cannot be applied to type `extern "fastcall" fn()`
note: an implementation of `std::cmp::PartialEq` might be missing for `extern "fastcall" fn()`
error[E0308]: mismatched types
    expected fn pointer, found fn item
```

Replacing `fastcall` with `C` in this example, or getting rid of `extern "fastcall"` entirely results in code that compiles fine:

https://is.gd/JI89Zs
```rust
fn test() {}
extern "C" fn c_test() {}

fn main() {
    let ptr: fn() = test;
    let c_ptr: extern "C" fn() = c_test;
    
    let check = ptr == test;
    let c_check = c_ptr == c_test;
}
```

rustc 1.16.0-nightly (468227129 2017-01-03)

**Comment by petrochenkov** [comment]
A bit of history: several traits were [originally implemented](https://github.com/rust-lang/rust/pull/28268) for fn pointers for all ABIs, but that caused serious metadata bloat, so implementations for "rare" ABIs were dropped.
Unfortunately, the only way to generalize over ABIs is macros, so this bloat is unavoidable currently.
However, metadata format changed few times since https://github.com/rust-lang/rust/pull/28268 so it may make sense to try to add these impls and re-measure the size of libcore.

Workaround:
```
// Cast to `usize` and compare
fn main() {
    let a: extern "fastcall" fn() = panic!();
    let b: extern "fastcall" fn() = panic!();
    a as usize == b as usize;
}
```

**Comment by petrochenkov** [comment]
I'll close this in favor of more general https://github.com/rust-lang/rust/issues/40710.
