### ISSUE TITLE
Rename 'Makefile.in' to something less offensive

### ISSUE THREAD

**Issue by Meai1** [rust-lang/rust#38869]
According to the code of conduct: https://www.rust-lang.org/en-US/conduct.html
making less of or fun of disabled persons is not okay. 
As a disabled man, I wonder if we could change the name to something less offensive. I cannot 'make' many things in life anymore with my disability and I feel unsafe looking at 'Makefiles' in the repository, which implies that clearly I'm not welcome to contribute as somebody who can't make things quite as well as others.

**Comment by KalitaAlexey** [comment]
@Meai1,
I can't understand whether it is a joke or not.

**Comment by gabibbo97** [comment]
I do hope this is a very funny joke.

**Comment by retep998** [comment]
I think the real problem here is that you've given in to hopelessness. Even a disabled person can create, they're just limited somewhat by their disability. You clearly are able to use a computer as evidenced by your ability to create this issue, therefore you are perfectly capable of creating all sorts of things digitally. @camlorn is an excellent example of someone who is able to make a lot of things despite their disability.

**Comment by arielb1** [comment]
> One of Rust's major contributors is in fact blind

Who, if you can tell?

**Comment by retep998** [comment]
@arielb1 I'd prefer not to say publicly until they confirm that they are okay with having their name put here.

**Comment by Manishearth** [comment]
This is concern trolling.

Also, you don't need makefiles to build Rust anymore. `./x.py build` works fine.

**Comment by camlorn** [comment]
Hi. I would be the blind contributor to the Rust compiler.  No, I don't care if we tell people that.  Also, blindness is my least significant disability, honestly: the others are the kind of thing that I don't go into because most people would consider it too much information.  Suffice it to say that I will probably always have to work remotely, or at least have the option to work remotely on some days.  On the off chance this is intended seriously, let this give the following weight: I have no problem with `makefile.in`.  That said, I join the people who are on the fence in their uncertainty.

And I actually know someone who is both blind and almost completely deaf who can code, and the other day there was something going around in my circles about another deaf and blind coder who is doing Cobol for a major bank.  You can type this issue through some method.  Therefore you can code in all likelihood.  You may not be able to code as fast as your equivalent non-disabled self, but that's no reason not to do it anyway.  Besides, most of coding is actually a thought exercise, not typing.  My understanding is that there are workable solutions available even for people who are missing both hands, but fortunately missing both hands isn't one of my problems so I don't know much about it.

**Comment by ticki** [comment]
OP is just jet another poor troll who thinks it's funny to mock disabled people. A lot of people have disabilities, but are able to be perfectly productive.
