### ISSUE TITLE
std::path::Path::Display allocates internally

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#38879]
It should be possible to display a `Path` without doing any additional allocations, by having the lossy conversion use `Formatter` directly.

**Comment by martinhath** [comment]
I would like to try this out 😄

**Comment by martinhath** [comment]
So I've done some digging. The allocation comes from `path::Display::fmt`s `self.path.to_string_lossy()`, which eventually gets down to `os_str::Slice::to_string_lossy`, which calls `String::from_utf8_lossy`, yes?

However, I am a little confused by what you mean about "having the lossy conversion use `Formatter` directly" means. Do you suggest giving the `Formatter` the `Path` directly, and do the non-Unicode sequence conversion in the `Formatter`?

**Comment by jethrogb** [comment]
I think so. You'll need to loop through the bytes and get valid `char`s. You can then write those `char`s using [`fmt::Write::write_char`](https://doc.rust-lang.org/std/fmt/trait.Write.html#method.write_char)

**Comment by martinhath** [comment]
Some more questions:
 - I found #33906 (with PRs #33907 and #35947), which seems very relevant here. However, the issue is about UTF-8, while the docs for [`path::to_string_lossy()`](https://doc.rust-lang.org/std/path/struct.Path.html#method.to_string_lossy)(which is what `path::Display` uses internally) only mentions "any non-Unicode sequences". Is this a significant difference?
 - If `char::decode_utf8` fits this issue it makes sense to wait for it to be stable, right? (I imagine using unstable features isn't something we'd _like_ to do, unless we really need to) 

Or is there some hidden thing I haven't seen yet?

**Comment by jethrogb** [comment]
I think it's fine to use this in `std` internally.
