### ISSUE TITLE
Tracking issue for Child::try_wait

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#38903]
Introduced in https://github.com/rust-lang/rust/pull/38866 this is a tracking issue for the `Child::try_wait` method.

This method attempts to wait for a child and collect its status but does not block. Questions for stabilization include:

* Is the method name suitable?
* Is the return type suitable? (`io::Result<T>` vs `io::Result<Option<T>>`)

**Comment by SimonSapin** [comment]
If this does not block, there’s not waiting involved?

**Comment by oconnor663** [comment]
One problem I'm grappling with right now is how to wait on a child (in one thread) while leaving open the option of killing it later (from another thread) if it hasn't exited yet. Right now the `wait` method takes `&mut self`, so there's no wait to call `kill` (which also takes `&mut self`) if someone's waiting on `wait`. The Unix way seems to be listening to SIGCHILD, but that assumes I own the whole process's signal handlers, and I don't want to assume that in library code.

`try_wait` will help. I can call that in a loop with sleeps in-between. That's doesn't feel great, but it's what [Python does](https://github.com/python/cpython/blob/dac0ab425862e2f9cc1903d20bd325aca1bafc16/Lib/subprocess.py#L1393-L1420). A _perfect_ solution might be to call the [newer `waitid` function](https://lwn.net/Articles/98243/) with `WNOWAIT`, which waits without reaping the child, to avoid racing against `kill`. But that one might not be defined on all platforms? I'm not sure yet. It does seem like it'll be easier to use `waitid` out of tree where available, since it's still safe (actually necessary to avoid leaks?) to call the child's `wait` afterwards.

If it's true that `waitid` "subsumes the rest of the wait* family" (according to that link above), it might be nice to expose it at some point? I wouldn't want to derail this issue with that question, but I'm interested in thinking about what it would look like. If a hypothetical future `wait_without_waiting` method/koan took `&self`, it would still be impossible to call `kill` while another thread was waiting. What API would make that possible? Maybe returning some sort of `KillHandle` that borrows the `Child`? I think it's [unspecified what happens](http://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_13) if multiple threads are waiting at once on the same child, so preventing that might be a good thing.

**Comment by alexcrichton** [comment]
@oconnor663 what you're trying to do is inherently race-prone on Unix and `&mut` is simply expressing that. A pid is consumed in the ownership sense once `wait` succeeds, so a call to `kill` could be a use-after-free if it's not synchronized with `wait`. 

It does indeed sound like `waitid` would be quite nice! If it's implemented across platforms then I think we could definitely start using it and consider relaxing `&mut self` and such.

**Comment by oconnor663** [comment]
Golang added support for `waitid` [six months ago](https://go-review.googlesource.com/#/c/23967/), and it looks like they only did it on Linux. Ah well.

**Comment by oconnor663** [comment]
Hmm, https://github.com/rust-lang/libc/pull/489 seems to have included Mac support though. I'll play with it. (Interesting timing!)

**Comment by oconnor663** [comment]
Thinking more about how I'm going to expose a similar API in [duct](https://docs.rs/duct). I think I'm going to opt for `io::Result<Option<ExitStatus>>`. My reasoning is that most callers are going to want to short-circuit on "real errors", and I want them to look like this

```rust
if let Some(status) = foo.try_wait()? {
    ...
} else {
    ...
}
```

instead of like this

```rust
match foo.try_wait() {
    Ok(status) => {
        ...
    }
    Err(err) if err.kind() == io::ErrorKind::WouldBlock => {
        ...
    }
    Err(err) => return Err(err),
}
```

The non-blocking `Read` and `Write` APIs don't work this way, because they have to support both blocking and non-blocking callers in the same function signature, and it's nasty to force the common blocking case to `unwrap`. But the `try_wait` API here is never blocking, and probably none of its callers are going to want to treat the `WouldBlock` condition as a real error.

Name-wise, I agree with @SimonSapin that the term "try_wait" is kind of confusing, though I guess it's consistent with what libc calls everything, and with the `Mutex` API. (The gold medal winner for confusing names in this part of the standard has got to be `waitid(...WNOWAIT)`.) I could see `check` or `poll`? But those don't really convey the "and also clean up the child if it's finished" part of the function, which is pretty important.

**Comment by alexcrichton** [comment]
@oconnor663 good point about using `Option` instead of just `io::Result`! 

Also yeah the name is mostly inspired by mutexes and other nonblocking/opportunistic operations which are prefixed with `try_` (e.g. `try_recv`, `try_borrow`, etc)

**Comment by oconnor663** [comment]
@alexcrichton would you be interested in a PR that tried out the `Option` approach?

**Comment by alexcrichton** [comment]
Oh oops I thought that it already did that actually. Sure if you want to send a PR sounds good to me!

**Comment by oconnor663** [comment]
We merged #39512, but @nagisa mentioned in there that they were worried about adding more inconsistency to our async APIs, and I worry about that too. Here's some of the existing work that we'll want to think about:

- `std::io::Read` and friends, which use `std::io::Result` with `ErrorKind::WouldBlock`
- `try_lock`, which uses a custom `TryLockError` enum with a `WouldBlock` case of its own
- the `futures` crate, which defines the [`Poll`](https://docs.rs/futures/0.1.10/futures/type.Poll.html) type to be `Result<Async<T>, E>`, very similar to `Result<Option<T>, E>`

**Comment by Timidger** [comment]
Any updates on this issue? Right now this function leaves a hole in the lockscreen for Way Cooler where the lock screen program could have failed but we can't clean the input locks / stored PID properly because there's no way to check the status of the program without blocking.

**Comment by oconnor663** [comment]
@Timidger is there any chance you could use the `shared_child` crate, which exposes a `try_wait` function now? There might be some missing features (particularly if you're collecting stdout), but I'd be happy to add them.

**Comment by Timidger** [comment]
@oconnor663 Thanks, it looks like that crate will work. Would be nice for this to be in the stable standard library thought :-/. Until this stabilizes I'll try to use that then.

**Comment by alexcrichton** [comment]
Aha and that reminds me!

@rfcbot fcp merge

**Comment by sfackler** [comment]
@oconnor663 the method is stabilized and will land in the next release or the one after that depending on the timing.
