### ISSUE TITLE
Confusing error message: "can't qualify macro invocation with `pub`" when a inherent method lacks "fn"

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/rust#38911]
Both stable 1.14 and nightly 2017-01-06.
[playpen](https://is.gd/Zwvabj)
```rust
struct A {}

impl A {
    pub get(self) {}
}
```
(**Edit:** Above example is fixed as of 1.20.0, but [free functions are affected](https://github.com/rust-lang/rust/issues/38911#issuecomment-331317518).)
```text
rustc 1.14.0 (e8a012324 2016-12-16)
error: can't qualify macro invocation with `pub`
 --> <anon>:4:5
  |
4 |     pub get(self) {}
  |     ^^^
  |
  = help: try adjusting the macro to put `pub` inside the invocation

error: expected one of `!` or `::`, found `(`
 --> <anon>:4:12
  |
4 |     pub get(self) {}
  |            ^

error: aborting due to previous error
```
while the actual issue is that the definition of `get` is missing the `fn` keyword.

**Comment by estebank** [comment]
If [`parse_impl_method`] doesn't see `fn` it tries to parse as macro, always and it uses  [`complain_if_pub_macro`] to output the "can't qualify macro invocation with 'pub'" error. We can use the same approach as #42578 if we fail to find the `!`, rewind the parser and try to parse the rest as a method. If it succeeds in doing so, expand the diagnostic with a suggestion to write `pub fn get`, otherwise rewind the parser to the previous error and emit the original diagnostic without modification.

[`parse_impl_method`]: https://github.com/rust-lang/rust/blob/17f56c549c35bb2cb316e5abff116e65277c7bb1/src/libsyntax/parse/parser.rs#L4921-L4922
[`complain_if_pub_macro`]: https://github.com/rust-lang/rust/blob/17f56c549c35bb2cb316e5abff116e65277c7bb1/src/libsyntax/parse/parser.rs#L4870

**Comment by ExpHP** [comment]
On the contrary, it seems to me this has been fixed:

```
error: missing `fn`, `type`, or `const` for impl-item declaration
 --> src/main.rs:4:8
  |
4 |     pub get(self) {}
  |        ^ missing `fn`, `type`, or `const`

error: aborting due to previous error
```

**Comment by ExpHP** [comment]
Ahah, it still occurs for functions that are not part of an impl.

```rust
pub get(x: u8) {}

fn main() {}
```

**Comment by fschutt** [comment]
Just wanted to say, this happens when you create a struct but forget the `struct` keyword:

```
pub MyStruct { }; // keyword struct missing

fn main() { }
```

```
   Compiling playground v0.0.1 (file:///playground)
error: can't qualify macro invocation with `pub`
 --> src/main.rs:1:1
  |
1 | pub MyStruct { }; // keyword struct missing
  | ^^^
  |
  = help: try adjusting the macro to put `pub` inside the invocation

error: expected one of `!` or `::`, found `{`
 --> src/main.rs:1:14
  |
1 | pub MyStruct { }; // keyword struct missing
  |             -^ unexpected token
  |             |
  |             expected one of `!` or `::` here

error: aborting due to 2 previous errors
```

A better error message would be helpful.
