### ISSUE TITLE
Book: forward references in 'lifetimes' chapter

### ISSUE THREAD

**Issue by jmdyck** [rust-lang/rust#39038]
In https://doc.rust-lang.org/book/lifetimes.html, there are sections that talk about lifetimes with respect to structs and impl blocks, but these constructs haven't been introduced yet.

If it's important/unavoidable that these things appear in this order, then the book should at least acknowledge that the first appearance is a forward reference.

**Comment by steveklabnik** [comment]
We are currently working on the second edition of the book, over at https://github.com/rust-lang/book. As such, we're not really editing the old book. If you or anyone else wants to send in a PR to fix this, please do! I'd be happy to merge it. But since we aren't putting time in, we aren't tracking things like this, so I'm going to give it a close. Thanks!

**Comment by jmdyck** [comment]
Ah, I see. Not really worth it then.

**Comment by jmdyck** [comment]
... but maybe worth a PR on the meta-issue...
