### ISSUE TITLE
#![macro_export] cannot use unexported macros inside of its implementation

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#39032]
Test:

```
macro_rules! id {
    ($($ts: tt)*) => {
        $($ts)*
    }
}

#[macro_export]
macro_rules! do_stuff {
     (...) => { id!(...} }
}
```

result:

```
error: macro undefined: 'id!'
   --> path
... (code pointing to use of do_stuff!)
    = note: this error originates in a macro outside of the current crate
```

**Comment by abonander** [comment]
I didn't realize this was supposed to work. It made sense, to me at least, that any macros an exported macro used had to be exported themselves.

**Comment by nagisa** [comment]
That forces exposing implementation details and therefore is not as flexible as it could be.

My particular use-case was a macro like this:


```
#[cfg(stage0)]
macro_rules! attribute {
    ($($ts: tt)*) => {
        $($ts)*
    }
}
#[cfg(not(stage0))]
#[allow_internal_unstable]
#[other_stuff]
macro_rules! attribute {
    ($($ts: tt)*) => {
        #[attribute1] #[attribute2] $($ts)*
    }
}
```

which I was hoping to then use in a macro that’s exported from the libcore – where such helper macros are inappropriate.

**Comment by durka** [comment]
This is one of those things that's always been a "feature" of a macros so I never imagined it could be "fixed". It would also be a breaking change to fix, until we have real macro scoping -- imagine crate A defines `println!` (shadowing the real one), and defines + exports `foo!` which invokes `println!`, if we fix this then in crate B `foo!` will invoke A's `println!` instead of `std`'s.

**Comment by Dylan-DPC** [comment]
This issue seems resolved now as the code works as intended
