### ISSUE TITLE
Error message for missing linker on MSVC is not actionable

### ISSUE THREAD

**Issue by K900** [rust-lang/rust#39044]
Inspired by [this Reddit comment](https://www.reddit.com/r/rust/comments/5nmjq3/can_someone_please_help_me_get_rust_going_in/dccod19/).

Right now, when rustc can't find the linker, it produces a pretty generic error message that explains what went wrong, but doesn't explain how to fix it. A solution might be to extend the error message with something like "Do you have Visual C++ Build Tools installed? Check http://doc.rust-lang.org/some/place for more info." and provide a page explaining what exactly is missing and how to get it somewhere in the docs.

**Comment by brson** [comment]
Rust can be better about this generally, not just with MSVC, but yes, somewhere in the stack, some tool should be giving a better hint about what to do here. This is one of the most common failure modes for new installs.

Same situation applies for all targets and plattforms. In the MSVC case it's pretty easy to imagine what sort of direction to give, but if we start thinking about other configs it gets more difficult since it's not clear which part of the toolchain is responsible for these external deps, and the exact procedure for getting the deps depends on the platform and cross scenario.

As a starting point I would suggest that rustc, before it executes any external tools, should check that it exists, and if not, punt to some more helpful error routine, which can be expanded over time for more scenarios. We can start with the common MSVC link.exe failure.

**Comment by ChrisDenton** [comment]
Is this still an issue? I note that Rust now has some helpful messages for when the MSVC linker isn't found or returns unexpected output. E.g. [here](https://github.com/rust-lang/rust/blob/3cb1c1134050c059a15d9ca7a00d4dd89111a373/compiler/rustc_codegen_ssa/src/back/link.rs#L954-L977) and [here](https://github.com/rust-lang/rust/blob/3cb1c1134050c059a15d9ca7a00d4dd89111a373/compiler/rustc_codegen_ssa/src/back/link.rs#L1008-L1017).

**Comment by K900** [comment]
Looks like we can close this then.
