### ISSUE TITLE
Rust beta/nightly has a false positive #[warn(unused_imports)] that's not in stable

### ISSUE THREAD

**Issue by pedrocr** [rust-lang/rust#39225]
When compiling https://github.com/pedrocr/rawloader with rust beta or nightly I get an unused_import warning that's a false positive (the compile fails without that import). The import in question is the following:

https://github.com/pedrocr/rawloader/blob/rawloader-0.29.0/src/decoders/ljpeg/decompressors.rs#L3

With stable everything works fine. The import is a little too broad (need to break up that code) and changing  it to just the two structs that are needed fixes the warning. Still seems like a bug.

**Comment by alexcrichton** [comment]
cc @jseyfried

**Comment by Thinkofname** [comment]
Compiles for me on nightly/beta with that line removed. 

It seems the `use decoders::ljpeg::*;` line is also pulling in basics which is a bit surprising to me because that file just `use`'s it not `pub use`

Example here https://play.rust-lang.org/?gist=c6b422dfbdfa63519ce0e72f597c5a87&version=nightly&backtrace=0

**Comment by pedrocr** [comment]
Interesting. Removing that line in beta compiles but not in stable where it fails with the BitPump stuff.

**Comment by pedrocr** [comment]
Could it be something to do with the two modules requiring each other?

**Comment by pedrocr** [comment]
I've been able to generate a minimal test case for this and it seems you need this specific situation of a submodule and module including each other. Two modules at the same level including each other doesn't work.

[test_nightly_unused_imports.tar.gz](https://github.com/rust-lang/rust/files/721528/test_nightly_unused_imports.tar.gz)

**Comment by jseyfried** [comment]
This was caused by [stabilizing](https://github.com/rust-lang/rust/pull/37127) RFC 1560 (now in beta), specifically [this change](https://github.com/rust-lang/rfcs/blob/master/text/1560-name-resolution.md#non-public-imports) and [this change](https://github.com/rust-lang/rfcs/blob/master/text/1560-name-resolution.md#glob-imports-of-accessible-but-not-public-names). Due to these changes, `use decoders::ljpeg::*;` imports everything in `basics` (as @Thinkofname [pointed out](https://github.com/rust-lang/rust/issues/39225#issuecomment-274288793)).
