### ISSUE TITLE
Tracking issue for RFC 1651: Extend Cell to non-Copy types 

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#39264]
[RFC](https://github.com/rust-lang/rfcs/pull/1651)

**Comment by SimonSapin** [comment]
#39287 broke a library of mine where I had code like this:

```rust
trait Take<T> {
    fn take(&self) -> Option<T>;
}

impl<T: Copy> Take<T> for Cell<Option<T>> {
    fn take(&self) -> Option<T> {
        let value = self.get();
        self.set(None);
        value
    }
}
```

`foo.take()` calls that used to call this trait method now call the new inherent method, but since that’s unstable the crate didn’t build until I added `#![feature(move_cell)]`. After that I could remove the trait since the new method has the same behavior.

Anyway, this is just FYI. If we don’t want this kind of breakage we can’t add any new method to existing `std` types ever, so that doesn’t sound viable. If the new method had had different behavior or if I wanted to keep supporting older compilers, it wouldn’t be too hard to rename my trait’s method or use UFCS.

**Comment by alexcrichton** [comment]
Yeah in general we reserve the right to break downstream code with differences in method resolution because the downstream code can always be written in an "elaborated" form which works on all compilers (e.g. using ufcs).

If a change to the standard library breaks an excessive amount of code in the ecosystem, though, then we'd need to take the steps much more purposefully.

**Comment by SimonSapin** [comment]
> If a change to the standard library breaks an excessive amount of code in the ecosystem

Sounds good.

Again, I don’t expect anything to change here and only made the previous comment to let people know this happened. I made this particular crate as an experiment, I don’t know of anyone actually using it.

**Comment by aturon** [comment]
Given that the core changes to the bounds on existing methods were instantly stable, it doesn't make a lot of sense to keep `take` and `replace` as unstable. I propose we immediately stabilize these APIs.

@rfcbot fcp merge

**Comment by alexcrichton** [comment]
ping @BurntSushi (checkbox)

**Comment by SimonSapin** [comment]
What’s the next step here? Batch stabilization PR near the end of the release cycle?

**Comment by aturon** [comment]
@SimonSapin Yep, I'm preparing one right now.
