### ISSUE TITLE
Tracking issue for removing temporary lifetime extension by borrow hint

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#39283]
UPDATE: [Mentoring instructions for removing the various bits of dead code found below.](https://github.com/rust-lang/rust/issues/39283#issuecomment-304305780)

------

This is the **summary issue** for the removal of temporary lifetime extension by borrow hint.

### What is this issue about

One issue that languages with deterministic destruction have to face is the lifetime of expression temporaries. To avoid confusion, temporaries have to be destroyed in some definite time, and temporaries living for too short or too long a time can cause subtle errors. The Rust rules for that - nikomatsakis/rust-memory-model#17 - are somewhat complicated.

The implementation used to follow the rules, but it also contained a leftover from the old days of Rust - issue #36082:

Normally, temporaries in Rust live until the containing arena, which in simple cases is the containing statement. For example, in this code the `RefCell` borrows only live to the end of their containing statements, so this code does not panic:
```Rust
use std::cell::RefCell;

fn main() {
    let r = 0;
    let s = 0;
    let x = RefCell::new((&r,s));

    let val = x.borrow().0;
    println!("{}", val);

    x.borrow_mut().1 += 1;
}
```

However, due to said leftover, adding an `&_` or `&mut _` type hint would make the borrow live until the end of the containing *block*, which means this code would keep a long borrow and panic due to a double borrow:
```Rust
use std::cell::RefCell;

fn main() {
    let r = 0;
    let s = 0;
    let x = RefCell::new((&r,s));

    let val: &_ = x.borrow().0; //~ WARN this temporary used to live longer
    println!("{}", val);

    x.borrow_mut().1 += 1;
}
```

This "feature" is an oversight from the old days of Rust, and therefore it is removed starting from Rust 1.16.

However, some code might be relying on the changed temporary lifetimes, and in some cases might not even compile without it:
```Rust
use std::cell::RefCell;

fn main() {
    let mut r = 0;
    let s = 0;
    let x = RefCell::new((&mut r,s)); //~ WARN this temporary used to live longer

    let val: &_ = x.borrow().0;
    println!("{}", val);
}
```

### How to fix this warning/error

Use an explicit variable with an explicit lifetime instead of the temporary:
```Rust
use std::cell::RefCell;

fn main() {
    let r = 0;
    let s = 0;
    let x = RefCell::new((&r,s));

    {
        let b = x.borrow();
        let val: &_ = b.0;
        println!("{}", val);
    }

    x.borrow_mut().1 += 1;
}
```

and
```Rust
use std::cell::RefCell;

fn main() {
    let mut r = 0;
    let s = 0;
    let x = RefCell::new((&mut r,s));

    let b = x.borrow();
    let val: &_ = b.0;
    println!("{}", val);
}
```

**Comment by nikomatsakis** [comment]
Given that this behavior has been changed, and is unlikely to be changed back, I am going to close this issue -- there is (at this moment) no further work to be done here. However, if you encounter this error and have questions or concerns, please feel free to comment. If we find there *is* further work to be done, we will re-open the issue. Thanks!

**Comment by nikomatsakis** [comment]
*Actually*, I take that back. The further work to be done is probably removing the error message that sends users to this issue after a suitable period of time. In particular, I think it would be a good thing to remove after the current nightly reaches beta.

**Comment by Mark-Simulacrum** [comment]
I think that it's perhaps time to consider removing this message. cc @rust-lang/compiler (and nominating).

**Comment by nikomatsakis** [comment]
I agree. Thank you @Mark-Simulacrum for bringing it up, I've been meaning to do the same. The main thing that's been holding me from making an "rfcbot" motion is that the typical procedure is to do a crater run to estimate the impact and I've not gotten around to it yet.

**Comment by Mark-Simulacrum** [comment]
@nikomatsakis That looks like a potential easy or at least mentorable issue to make this a hard error so we can do the crater run; does that sound correct? Could you write up some quick steps?

**Comment by nikomatsakis** [comment]
I was wrong, we don't need a crater run. We already made it a hard error. We just have to kill code related to this. I'll provide a few pointers, this is indeed a good mentoring issue.

**Comment by nikomatsakis** [comment]
Tracking this change introduced a small amount of cruft in the compiler. In particular, some data structures track the 'temporary region', and since that changed, those structures are updated to have both the old and new values. In particular, [the `Categorization<'tcx>` structure](https://github.com/rust-lang/rust/blob/2f278c57ff4a805941f1497f34b3ad20b6f8e13b/src/librustc/middle/mem_categorization.rs#L90-L102) contains a variant with an extra field:

```rust
#[derive(Clone, PartialEq)]
pub enum Categorization<'tcx> {
    // temporary val, argument is its scope
    Rvalue(ty::Region<'tcx>, ty::Region<'tcx>),
    //     ^^^^^^^^^^^^^^^^ this data is the new temporary lifetime, after the change
    //                       ^^^^^^^^^^^^^^^^ this data is the *old* lifetime, before the change
    ...
}
```

If you ripgrep around, you will see that this field is mostly unused, except in borrowck [where it is used to report this warning](https://github.com/rust-lang/rust/blob/2f278c57ff4a805941f1497f34b3ad20b6f8e13b/src/librustc_borrowck/borrowck/mod.rs#L1134-L1138).

If we remove that variant, you'll be able to follow a trail of breadcrumbs of code that can be removed. For example, `MemCategorizationCx::cat_rvalue` no longer needs [this argument](https://github.com/rust-lang/rust/blob/2f278c57ff4a805941f1497f34b3ad20b6f8e13b/src/librustc/middle/mem_categorization.rs#L885). Eventually, following this trail should let us delete [cruft like `temporary_scope2()` in `region.rs`](https://github.com/rust-lang/rust/blob/2f278c57ff4a805941f1497f34b3ad20b6f8e13b/src/librustc/middle/region.rs#L398-L411).

**Comment by venkatagiri** [comment]
@nikomatsakis I would like to work on this.
From going over the code and removing the extra field in Categorization structure, feels like all the changes done by #39066 needs to be removed.
Everything from [`shrunk_rvalue_scopes`](https://github.com/rust-lang/rust/pull/39066/files#diff-eaec58cd2e0c9e0564f2f3f7e417340cR280) to [`temp_lifetime_was_shrunk`](https://github.com/rust-lang/rust/pull/39066/files#diff-1fb2a5c748d7e41d90ffa6fe7fef7a0fR101).
I wasn't able to figure out where exactly the lifetime was shrunk that needs to be retained so that they continue to show errors.
Am I in the right direction?

**Comment by nikomatsakis** [comment]
@venkatagiri 

> From going over the code and removing the extra field in Categorization structure, feels like all the changes done by #39066 needs to be removed.

Yes, that is basically correct. This is the PR that introduced this infrastructure, because we were changing some values from one thing to another and we wanted to give warnings to the affected code. 

But, that said, we don't want to *revert* that PR. In other words, we want to keep the *new* values that the PR introduced, we just want to stop tracking the *old* values that got replaced (and stop warning about it).

> I wasn't able to figure out where exactly the lifetime was shrunk that needs to be retained so that they continue to show errors.

I'm not sure I understand your question here. 

>  Am I in the right direction?

Sounds like it!

**Comment by nikomatsakis** [comment]
@venkatagiri (ps, feel free to ping me on IRC or gitter sometime -- gitter is maybe better if you don't have a persistent IRC connection)
