### ISSUE TITLE
External crates in documentation comments examples not working

### ISSUE THREAD

**Issue by torkleyy** [rust-lang/rust#39341]
There are two things related to documentation examples that I think are weird and not intended.

#### `lib.rs` in crate `foo`
```rust
/// # Examples
/// 
/// This is working:
///
/// ```
/// use foo::Foo;
/// ```
///
/// However, this is not:
///
/// ```
/// extern crate foo;
///
/// use foo::Foo;
/// ```
/// 
pub struct Foo;
```

The latter one gives me

```
error[E0432]: unresolved import `foo::Foo`
 --> <anon>:4:5
  |
3 | use foo::Foo;
  |     ^^^^^^^^^^ Maybe a missing `extern crate foo;`?
```

when running `cargo test`.

Probably that's some technical thing, however the error message should still tell that you should not use `extern crate` for your own library.

More general, using `extern crate` in documentation code does not work at all for me. If I want to `use` a symbol from an external library, I'll also get `Maybe a missing 'extern crate external_library'` with and without the `extern crate` line.

### Version

The provided error messages are from version `rustc 1.16.0-nightly (4ecc85beb 2016-12-28)`.
`rustc 1.14.0 (e8a012324 2016-12-16)`(stable) suggests using `self::external_library::foo` instead.

**Comment by torkleyy** [comment]
Is there anybody with the same problem or is this just me?

**Comment by Kimundi** [comment]
The issue is that doc comments are placed in a compilable rust code template, with some heuristics as to what to generate/omit.

If you do
```rust
/// ```
/// use foo::Foo;
/// ```
```

It generates something like
```rust
extern crate test;
extern crate <name of this lib>;
fn main() {
    use foo::Foo;
}
```

By using `extern crate`, you place the new names inside the function body of `main`, where `use` can not see them.

You can avoid those issues by writing your own main function:

```rust
/// ```
/// extern crate foo;
/// use foo::Foo;
/// fn main() {
///    // ...
/// }
/// ```
```
The heuristics sees that you'll have defined a `main`, and thus will not emit one itself.

To recover the same kinds of code snippets as possible per default, you can hide parts of the code with a leading `#`:

```rust
/// ```
/// extern crate foo;
/// use foo::Foo;
/// # fn main() {
/// // ...
/// # }
/// ```
```

should show up rendered as

```rust
extern crate foo;
use foo::Foo;
// ...
```

**Comment by torkleyy** [comment]
@Kimundi Thank you so much! With `external crate` these integration tests are definitely more useful now.

But it shouldn't be to hard for someone who knows the internals to fix this so that the `extern crate` is placed before `fn main`, is it? I'd love to contribute to this repository more, however it's hard for me to understand the structure of the compiler / related crates.

**Comment by malbarbo** [comment]
The error message is misleading, `extern crate foo;` is not missing.

**Comment by Mark-Simulacrum** [comment]
The top-level comment example compiles today, so I think this is fixed, possibly due to 2018 edition.
