### ISSUE TITLE
`assert_eq!` has a terrible error message when given a trailing comma

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#39369]
Trailing commas are an easy mistake to make, especially in a language like Rust where they are often accepted. Erroneously adding a trailing comma to `assert_eq!` triggers the error message "requires at least a format string argument", which is confusing and leads the user to think (incorrectly) that they need to add some kind of format string. [Example.](https://is.gd/8pJ1w6)

**Comment by KalitaAlexey** [comment]
I think we should add a hint to remove the last comma.

**Comment by abhijeetbhagat** [comment]
er... aren't you supposed to provide one then? :)
`assert_eq!(1, 2, "Nah, some other day maybe... {} {}", 1, 2,)`

**Comment by cramertj** [comment]
@abhijeetbhagat You certainly can do that, yes, but you don't have to.

**Comment by zackmdavis** [comment]
This looks tricky. What's happening is that the comma puts us into the "match a 'token tree' of zero or more additional tokens after the `$left` and `$right` args" [branch](https://github.com/rust-lang/rust/blob/24055d0f2/src/libcore/macros.rs#L116) of `assert_eq!`, those tokens being passed to `format_args!`, which is what emits the "requires at least a format string argument" message.

What we would _want_ is to only match _one_ or more additional tokens (or emulate this by conditioning on the length of the token tree or something), but I don't immediately see how or whether this can be done with the macro system (my naïve hopes that `+` instead of `*` would work as in regular expressions seems to be unfounded).

**Comment by zackmdavis** [comment]
> my naïve hopes that + instead of * would work as in regular expressions seems to be unfounded

Wait, it [looks like](https://github.com/rust-lang/rust/blob/d7777ae6/src/libcore/macros.rs#L79) I was wrong about this!
