### ISSUE TITLE
Incorrect destruction of temporary borrow from `Rc`

### ISSUE THREAD

**Issue by botev** [rust-lang/rust#39435]
One problem arising from this issue have been described with code [here](https://users.rust-lang.org/t/double-borrows-drops-temporary-too-early/8991) where temporary variables are dropped too early.

Another example, of what I think is the same issue, appears at runtime in the following code:
```
self.to_expr(self.get_mut().parameter(data_type, shape, name)?)
```
With error:
```
thread 'main' panicked at 'already mutably borrowed: BorrowError', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:870
```
While the following code works:
```
let x = self.get_mut().parameter(data_type, shape, name)?;
self.to_expr(x)
```
In this example `get_mut` and `to_expr` both borrow the same `Rc`. However, it is unclear why at runtime of the first example does the borrow occur simultaneously?

**Comment by arielb1** [comment]
First, FYI: `get_mut` is `RefCell::get_mut`, which does not have anything to do with `Rc`.

Second, temporaries are not destroyed "the moment they are not needed" - that would create much confusion because there is no good way to define that. The rules are admittedly baroque (https://github.com/nikomatsakis/rust-memory-model/issues/17), but if there are no control flow statements nearby temporaries are destroyed at the end of the current *statement*.

**Comment by arielb1** [comment]
a
