### ISSUE TITLE
Extract libcore benchmarks to a separate crate

### ISSUE THREAD

**Issue by phungleson** [rust-lang/rust#39484]
When looking though `libcore` I saw this

![image](https://cloud.githubusercontent.com/assets/93457/22589231/59b0f0ac-ea5d-11e6-8676-a62701285707.png)

https://github.com/rust-lang/rust/blob/master/src/libcore/Cargo.toml#L16-L19

So just want to check if the task is about:

1. Create `libcorebench` in `src`
1. Move all `#[bench]` from `libcoretest` to `libcorebench` like this one

https://github.com/rust-lang/rust/blob/master/src/libcoretest/any.rs#L128

If it is I can give it a try, thanks

**Comment by alexcrichton** [comment]
@phungleson yeah that should do the trick! I think that you can avoid a whole new directory even, but could have something like `src/libcore/bench/*.rs` and then that could get pulled in the `Cargo.toml`

**Comment by stjepang** [comment]
The same thing applies to libcollections, too: benchmarks should be moved into libcollectionsbench.

**Comment by est31** [comment]
I've recently been wondering what the reason behind that was. Any ideas? Any links to previous discussion?

**Comment by alexcrichton** [comment]
@est31 in general compiling libcore with --test literally is a huge PITA because there's so many intermixed types. The "foreign" libcore (one linked by libtest) duplicates the local libcore (the one being compiled with --test) and it's very difficult to keep the types straight, especially for standard traits.

It ended up being easier to do everything out of the library

**Comment by est31** [comment]
@alexcrichton thanks!
