### ISSUE TITLE
rustc and cargo use different precision for commit sha in --short

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#39635]
```
brian@ip-10-145-43-250:~/dev/rust⟫ rustc -V
rustc 1.16.0-nightly (7821a9b99 2017-01-23)
brian@ip-10-145-43-250:~/dev/rust⟫ cargo -V
cargo 0.17.0-nightly (2324c2b 2017-01-21)
brian@ip-10-145-43-250:~/dev/rust⟫ rustup -V
rustup 1.0.0 (17b6d21 2016-12-15)
```

rustc uses `git rev-parse --short=9` but cargo and rustup just use `git rev-parse --short`.

**Comment by est31** [comment]
running `git rev-list --all --abbrev=0 --abbrev-commit |
  awk '{ a[length] += 1 } END { for (len in a) print len, a[len] }'` ([source](https://blog.cuviper.com/2013/11/10/how-short-can-git-abbreviate/)) gives me: 

```
4 7
5 33956
6 25711
7 2159
8 124
9 14
10 1
```

So over 100 commits that need more than 7 characters in order to be unique.

You can get some examples with the command `git rev-list --all --abbrev=0 --abbrev-commit |  awk '{ print length, $0 }' | sort -n -s | cut -d" " -f2- | tail`:

```
fd029209e
8d05f6c74
4b34f3c3a
15ba87f03
c588e407b
4d6dde7f4
faa280cee
c2baaa8d8
299657550
0b2e6f8087
```

So I think if consistency is a goal, then rustup and cargo should adapt, not the other way round :)

**Comment by tommyip** [comment]
I would like to take this issue. So should we have the SHA length set to 9 for both rustup and cargo?

**Comment by Mark-Simulacrum** [comment]
@tommyip Go ahead! That seems fine.

**Comment by tommyip** [comment]
Opened a PR in both repo.

**Comment by alexcrichton** [comment]
This is now fixed everywhere!
