### ISSUE TITLE
configure adb check seems faulty

### ISSUE THREAD

**Issue by binarycrusader** [rust-lang/rust#39763]
While admittedly most people may never encounter this oddity, adb was not originally known as the android debugger.  Instead, adb historically refered to [adb(1)](https://en.wikipedia.org/wiki/Advanced_Debugger), a venerable tool (general-purpose debugger) in the UNIX tool chest -- which the 7th Edition of UNIX (from 1979) had a version of.

So on Solaris, ./configure amusingly produces this output when it finds /usr/bin/adb:

```
configure: looking for target specific programs
configure: 
configure: CFG_ADB              := /usr/bin/adb 
```

The `adb --version` check that ./configure runs should be failing since that causes adb to exit with a return code of 2:

```
$ adb --version; echo $?
adb: illegal option -- version
Usage: adb [-fkmuwyAFKMSUW] [+/-o option] [-p pid] [-s dist] [-I path] [-L path]
        [-P prompt] [-R root] [-V dis-version] [object [core] | core | suffix]
...
2
```

This doesn't appear to cause any real harm, but since the configure check should be failing, this seems like it should be investigated and fixed.

**Comment by alexcrichton** [comment]
Oh dear, sounds bad! Now that we've got rustbuild though we should just remove this logic entirely as I believe it's all unused

**Comment by Mark-Simulacrum** [comment]
Today we don't have any verification logic or otherwise in regards to `adb`, just pulling it from the path [here](https://github.com/rust-lang/rust/blob/81734e0e06d24cf580dd5352c64d10110e4d3b7b/src/bootstrap/check.rs#L271). As such, I guess this isn't a problem in that there is no check anymore, though we will still have problems if a wrong adb is used (which may be cryptic, I don't know). I'm going to close this since the issue it's tracking (configure detection of adb) is gone now.
