### ISSUE TITLE
rust/src/doc/book/nightly-rust.md is kind of messed up?

### ISSUE THREAD

**Issue by Rufflewind** [rust-lang/rust#39783]
Inside the section *Nightly Rust*, there's a section for *Uninstalling*, followed by stuff related to `curl | sh`, supported platforms, version, installation, and getting help.  I don't think any of these belong to the *Nightly Rust* section.

**Comment by steveklabnik** [comment]
It's intended to be a mirror of https://doc.rust-lang.org/stable/book/getting-started.html, but for nightly instead of stable. 

We are going to be killing this entire section of the book once https://github.com/rust-lang/rust/pull/39633 lands, in favor of an entire separate book on nightly Rust, so that will fix this. As such, I'm going to give this a close, thanks!
