### ISSUE TITLE
Multiple rlib candidates found on beta/nightly, but not stable

### ISSUE THREAD

**Issue by djc** [rust-lang/rust#39879]
[Askama](https://github.com/djc/askama) has a Cargo workspace with multiple crates in it. Previously, all of the crates just referenced each other by path. However, last night I published them to crates.io, so now I need conventional dependency specifications. As I did this, my testing with `cargo test --all` (specifically, the doctests, apparently) started to fail with this error:

See here: https://travis-ci.org/djc/askama/builds/202002221

(As reported in #cargo, @brson asked me to file a bug about it.)

**Comment by alexcrichton** [comment]
Taking a look now, but note that even if you've published crates it's still best to use `path` dependencies to pick up local changes. You'll just need to annotate the dependency with an extra `version = "..."` that you'd otherwise write in for crates.io ([example](https://github.com/alexcrichton/git2-rs/blob/0d745cf0efad95a9e407beecd7b508ca9a37df80/Cargo.toml#L27))

**Comment by alexcrichton** [comment]
This looks like a regression in Cargo, it's passing two `--extern askama=...` flags to `rustdoc --test`

**Comment by alexcrichton** [comment]
Correction, Cargo's always done that, apparently rustdoc is just now reading it...

**Comment by alexcrichton** [comment]
I've sent a PR to Cargo to fix this: https://github.com/rust-lang/cargo/pull/3721

I'm not really sure what the regression was here between stable/beta, but we may as well backport it to beta on Cargo to get that fix in.
