### ISSUE TITLE
#[repr(X)] should inhibit enum layout optimization

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#40029]
This is a regression stable to nightly (breaking nodrop and arrayvec at the moment; not their compilation but their tests, which indicate their implementation is not sound for element types like `&T` or `Vec<T>`).

Found by [cargobomb report](https://brson.github.io/cargobomb-reports/stable-v-nightly-2017-02-17/index.html)

Note that the regression applies to enums with `#[repr(u8)]` (and similar) but not `#[repr(C)]`.

PR #25651 was never merged, but it would document this aspect of `#[repr(u8)]`

Evaluating https://github.com/rust-lang/rust/pull/39595 for its impact. Thanks @eddyb for the pointers!

**Comment by bluss** [comment]
As usual filing an issue for every regression; it doesn't mean that the change in behaviour must be fixed. In this case it probably should, though.

**Comment by bluss** [comment]
First nightly with change is `rustc 1.17.0-nightly (24a70eb59 2017-02-09)`  (rustup's `nightly-2017-02-10`)

**Comment by bluss** [comment]
All crates affected by the nodrop breakage are fixed by just released nodrop 0.1.9.

It changed from this:

```rust
    #[repr(u8)]
    enum Flag<T> {
        Alive(T),
        Dropped,
    }

```

to this:

```rust
    #[repr(u8)]
    enum Flag<T> {
        Alive(T),
        Dropped(u8),
    }
```

I didn't find a reason to not use this workaround.

**Comment by nikomatsakis** [comment]
I believe we should restore the old behavior. I feel like if you request a representation with a `u8` discriminant, we should give you a `u8` discriminant, not no discriminant at all. =) More specifically, I've always thought of the `u8` repr as being `struct { u8, X }` where X is the union of all arguments. (Same for `u16` etc.) 

I could see other choices, but given that this is what we've done till now (right?) I'd say we ought to stick with it. If you want the option for us to apply further optimizations (use "u8" if you need a discriminant, but otherwise who cares...) we should have people opt in to that.

**Comment by brson** [comment]
I agree this is a regression that should be fixed.

**Comment by nikomatsakis** [comment]
on it.

**Comment by nikomatsakis** [comment]
See https://github.com/rust-lang/rust/pull/40188
