### ISSUE TITLE
rustdoc creates test in tmpdir, which is noexec on some systems

### ISSUE THREAD

**Issue by chifflier** [rust-lang/rust#40065]
When running `cargo test` to run unit tests, the documentation tests are executed from `/tmp`, which is mounted as noexec on many distros (for security reasons).
This does not happen for other unit tests (using the `test` attribute), because they are build in `target/<build type>`.

Suggested solution: build documentation tests in the same directory ?

Example code:
```
/// ```
///
/// # fn main() { test1 () }
pub fn test1() {
}
```

And mount `/tmp` as noexec:
```
mount -o remount,noexec /tmp
```

(reopening here as requested in  https://github.com/rust-lang/cargo/issues/3756)

**Comment by Mark-Simulacrum** [comment]
I'm not entirely sure this is possible without some work, since rustdoc to my knowledge doesn't have access to the target directory. Just as a note, the code that needs to be changed in rustdoc: https://github.com/rust-lang/rust/blob/5b13bff5203c1bdc6ac6dc87f69b5359a9503078/src/librustdoc/test.rs#L241

**Comment by eun-ice** [comment]
Workaround:
 
`TMPDIR=/some/where/with/exec cargo test --doc`

**Comment by jyn514** [comment]
I'm going to close this since it's a rare issue with an easy workaround.

**Comment by SBeausoleil** [comment]
The workaround does not work on Windows however.

**Comment by jyn514** [comment]
@SBeausoleil PowerShell has a slightly different syntax for setting env variables, but the workaround should still work fine if you fix the syntax.

**Comment by SBeausoleil** [comment]
It also doesn't work with CMD. I tried setting it under ./cargo/config.toml as 
```
[env]
TMPDIR="./tmp"
```
And with the [correct syntax](https://stackoverflow.com/questions/1420719/powershell-setting-an-environment-variable-for-a-single-command-only) in PS:
![image](https://user-images.githubusercontent.com/10907577/200202376-dc37ddc6-58c4-44c6-8573-f5ffa66e29da.png)
The issue is that in the back, doc tests use the result of [std::env::temp_dif()](https://doc.rust-lang.org/std/env/fn.temp_dir.html), which on Windows does not interrogate environment variables, but instead calls the OS.

**Comment by markmmm** [comment]
I think you can use `TMP` or `TEMP` environment variables instead of `TMPDIR`...
from [std::env::temp_dir()](https://doc.rust-lang.org/std/env/fn.temp_dir.html):
> On Windows, the behavior is equivalent to that of [GetTempPath2](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppath2a) / [GetTempPath](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppatha), which this function uses internally.

Then from the docs for [GetTempPath2A](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppath2a) or [GetTempPath](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppatha):
> The GetTempPath function checks for the existence of environment variables in the following order and uses the first path found:
>
> 1. The path specified by the TMP environment variable.
> 2. The path specified by the TEMP environment variable.
> 3. The path specified by the USERPROFILE environment variable.
> 4. The Windows directory.

**Comment by mikelync** [comment]
I can confirm that using:
```
$env:TMP = './target/tempdoc'; cargo test --doc
```
on a corporate blocked Windows machine with PowerShell does indeed allow this workaround.
