### ISSUE TITLE
cannot infer an appropriate lifetime error is vague and unhelpful

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#40209]
```rust
struct One<'a> {
    refs: &'a u8
}

struct Two<'a,'b> where 'a:'b {
    one: &'b One<'a>,
}

impl<'a,'b> Two<'a,'b> {
    pub fn new(one: &'b One) -> Self {
        Two {
            one: one,
        }
    }
}
```

> error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements

This is the only information provided ([playpen](https://is.gd/qdfsoZ)). It doesn't say which lifetimes, and doesn't say what are the  requirements.

It was impossible for me to figure out what was going on without rewriting the whole code bit by bit in a reduced case and adding and removing annotations almost by brute force.

For the record, Rust wanted: `pub fn new(one: &'b One<'a>) -> Self`, as it inferred wrong lifetime for `One<_>`.

**Comment by nikomatsakis** [comment]
This has been "fixed'' on nightly, in the sense that we provide full information, and I believe the fix was backported to beta, so it should be showing up on stable very soon. That said, I still consider these errors subpar. I expect we'll be improving them shortly (I've been working on a write-up of a plan to do so; in any case there exist various issues, and this example isn't particularly interesting, so I'm going to close this particular issue.) Thanks for the report!
