### ISSUE TITLE
OsStr: compare prefix

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#40300]
`OsStr` could implement a way to compare against prefix `&str` (as it does not implement iterators over its data), similarly to how it implements comparison against `&str`.

Currently you need to go out of your way to convert to bytes. `as_str` is not suitable, as following case shows:

```
let x = /* OsStr with invalid utf8 */;
x.as_str().map(|x| x.starts_with("-")).unwrap_or(false); // false even if only the first byte really matters
```

**Comment by jmesmon** [comment]
Older related issue: #26499 (there are quite a few about expanding the OsStr api, seems to be a continuous pain point).

I've put together a crate ([os-str-generic](https://crates.io/crates/os-str-generic)), to fill some of these holes, but due to not having access to the underlying representation it will always have certain in-efficiencies (can't generally create references to "slices" of an `OsStr` due to the limited windows `OsStrExt`).

**Comment by djzin** [comment]
I came across a whole bunch of these seeing what it would take to have rustc handle non-utf8 paths (It is a deep, deep pit of madness. Demons lie there. Do not enter). Basically a lot of argument-handling code relies on comparing substrings and suchlike, and there is no way to do it for OsStr because of the barmy way Windows handles strings.

Unfortunately, this leaves us in the position where, in trying to do everything "correctly" in handling OsStr, PathBuf & co, it is just far more ergonomic for users to use `to_str().unwrap()` (or one of the methods that calls it implicitly), making basically every rust program crash on non-utf8 paths, environment variables etc. - a worse situation in my mind than not handling utf-8 at all.

**Comment by dtolnay** [comment]
I believe this is going to require an RFC. Let's track this in https://github.com/rust-lang/rfcs/issues/900. There is a promising start to an `OsStr` RFC in https://github.com/rust-lang/rfcs/pull/1309 if anyone is interested in taking that over.
