### ISSUE TITLE
Suggest to move/copy use statement from parent into inline module declaration

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#40341]
Given the below Rust code, we can probably produce a more user friendly error message than today's "failed to resolve. Use of undeclared type or module `File`".

```rust
use std::fs::File;

mod foo {
    fn some_function(f: File) {}
}
```

It'd be nice to suggest something like "Possibly move `use std::fs::File` from outer scope into module `foo`". This will help beginners understand how to deal with the `File` use in the parent module not being in scope within the child module.

**Comment by arielb1** [comment]
There is *supposed* to be a hint.

**Comment by jseyfried** [comment]
@Mark-Simulacrum I think like you're using an old `rustc` -- that hasn't been the error since `1.14` or earlier. The error on beta and nightly is:
```
error[E0412]: cannot find type `File` in this scope
 --> example.rs:4:25
  |
4 |     fn some_function(f: File) {}
  |                         ^^^^ not found in this scope
  |
  = help: possible candidate is found in another module, you can import it into scope:
            `use std::fs::File;`
```

If the user adds `use std::fs::File;` as suggested, the the top-level import will be an unused import warning.

cc @petrochenkov

**Comment by petrochenkov** [comment]
I think @Mark-Simulacrum means that the "you can import it into scope" may be useless if beginner assumes that the parent module scope extends to children modules. "Why does it tell me `File` is not in scope? I've just written `use std::fs::File;` and imported it!"

I'm not sure it's important enough to implement, but in principle we can detect the situation when some name isn't present in this scope, but presents in some parent module scope, and enlighten the user on the basics of the module system.

(It looks like the wording "failed to resolve. Use of undeclared type or module X" was never used in this context (at least since 1.0), so I suspect @Mark-Simulacrum copy-pasted it from somewhere else and is not necessarily using an old compiler)

**Comment by Mark-Simulacrum** [comment]
Yes; I copy-pasted the message from IRC; I assumed that it was a direct quote.

I agree with the sentiment that beginners may not understand why it isn't imported, so providing an error message for that case would probably be a good idea.

**Comment by durka** [comment]
I always forget to do this when writing inline test modules as well.
