### ISSUE TITLE
Tracking issue for ManuallyDrop

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#40673]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1860

I believe initially implemented at https://github.com/rust-lang/rust/pull/40559

**Comment by Ericson2314** [comment]
I left a comment https://github.com/rust-lang/rfcs/pull/1860#issuecomment-280208052 which slipped by FCP. The tl;dr is: this is fine for now in my book, but we should consider `&move` and improved `Drop` again prior to stabilization. I'd hope the popularity of this feature would be considered a +1 `&move`---a wholly nicer, if harder-to-implement, solution---rather than a `-1` (with the reasoning that this trick is good enough so who needs `&move`).

**Comment by SimonSapin** [comment]
I’d like this to be stabilized. What’s the next step?

The only alternative that I know of is https://crates.io/crates/nodrop, which on stable Rust requires a combination of hacks that look fragile to me.

**Comment by crumblingstatue** [comment]
I am personally using this in a project, so I'm in favor of stabilizing a solution for specifying drop order, but I also don't want @Ericson2314's comment ignored before stabilizing this.

**Comment by sfackler** [comment]
I don't believe `&move` or a new `Drop` are anywhere near the horizon. It seems unreasonable to hold this API up indefinitely.

@rfcbot fcp merge

**Comment by dtolnay** [comment]
I filed https://github.com/brson/rust-api-guidelines/issues/93 to follow up with a justification of why we prefer `into_inner(ManuallyDrop<T>)` over `into_inner(self)`.

<img src="https://camo.githubusercontent.com/41b3ec3419116e3b3f84507ad965646ce4ce1f0c/68747470733a2f2f72657669657761626c652e696f2f6c67746d2e706e67" width="100"></img>

@rfcbot reviewed

**Comment by Ericson2314** [comment]
Fair enough, this can always be deprecated.

**Comment by SimonSapin** [comment]
@brson I think this is waiting on you :)

**Comment by Gankro** [comment]
Hey nice I was about to propose stabilizing this. 🎉

**Comment by bluss** [comment]
Sorry if I have missed this somewhere — do we have a decision for how layout optimization handles things like `Option<ManuallyDrop<&i32>>`? I can see that right now, the inner value is not used for the discriminant.

**Comment by SimonSapin** [comment]
In the case of `struct ArrayVec<A: Array> { length: usize, data: ManuallyDrop<A> } impl<T, N: usize> Array for [T; N] {…}` (assuming integer generics, or with a macro to generate impls for a number of specific N values), it is important that e.g. `Option<ArrayVec<[&i32; 16]>>` does *not* use the nonzeroness of `&i32` to represent the discriminant of `Option` because the `&i32` items might be uninitialized.

Or, in other words, `ArrayVec` needs *some* way to inhibit propagation of enum layout optimizations, and `ManuallyDrop` could be it.

**Comment by ldr709** [comment]
This is probably neither the right time nor place for this, but any plans to `impl Copy`? It may seem odd to do so, since `Copy` types can be dropped trivially, but this would be useful in situations where you don't know whether or not a type `impl`s Copy.

**Comment by Gankro** [comment]
You can submit a PR to derive(Copy) and it will likely be accepted.

**Comment by kjetilkjeka** [comment]
When testing it seems like `impl<T: Clone> for ManuallyDrop<T>` works on nightly/beta, but not on stable. I can't seem to find the PR/issue tracking this, does anyone have a link? Do anyone know if this will this land for 1.21? 

[this](https://travis-ci.org/UAVCAN/uavcan.rs/builds/299864203?utm_source=github_status&utm_medium=notification) is the test I'm referring to.

**Comment by ldr709** [comment]
@kjetilkjeka [Here](https://github.com/rust-lang/rust/pull/44310) is the PR. Rust 1.21 has already been released and it doesn't have it. According to [this](https://forge.rust-lang.org/release-process.html) if it is in beta now it should be in 1.22 (maybe a few weeks?), but I don't know much about it.
