### ISSUE TITLE
Wrong message from object safety checker

### ISSUE THREAD

**Issue by qnighy** [rust-lang/rust#40670]
**UPDATE:** There are mentoring instructions to be found [in a comment below](https://github.com/rust-lang/rust/issues/40670#issuecomment-288337422).

---

Object safety checker produces messages with "supertrait something" even when the cause is in where-clause.

```rust
trait Bar<X:?Sized> {}
trait Foo where Box<Self>: Bar<Self> {}
fn f(x: Box<Foo>) {}
fn main () {
}
```

```
rustc 1.17.0-nightly (b1e31766d 2017-03-03)
error[E0038]: the trait `Foo` cannot be made into an object
 --> <anon>:3:1
  |
3 | fn f(x: Box<Foo>) {}
  | ^^^^^^^^^^^^^^^^^^^^ the trait `Foo` cannot be made into an object
  |
  = note: the trait cannot use `Self` as a type parameter in the supertrait listing

error: aborting due to previous error
```

Rust Playground: https://is.gd/mAvVNW

Indeed this seems object-unsafe, but the message should be something about "where-clause", not "supertrait listing".

**Comment by nikomatsakis** [comment]
I tend to agree. This message is generated in `src/librustc/traits/object_safety.rs`, which houses the object safety analysis. The simplest fix would just be to adjust the wording to say "in the supertraits or where-clauses". It would be difficult -- but not impossible -- for us to distinguish the two, since at this phase in the compiler they are effectively unified. Doesn't seem worth the effort.

**Comment by gaurikholkar** [comment]
Will take this up.

**Comment by mandeep** [comment]
Currently, working on this. Hope to submit a pull request tonight.

**Comment by qnighy** [comment]
May I (or should I) close this issue?

**Comment by nikomatsakis** [comment]
Yep! Thanks. =)
