### ISSUE TITLE
Converting &str to String

### ISSUE THREAD

**Issue by DirtGrubDylan** [rust-lang/rust#40762]
As of now, there are several ways to convert a `&str` to a `String`. Without going into too much detail, a good resource to see the different ways can be found [here](https://mgattozzi.github.io/2016/05/26/how-do-i-str-string.html). Now, some of these methods, like `push_str`, `format!`, and `into` make sense, as they extend far beyond the scope of just converting a `&str` to a `String`. However, `to_string()`, `to_owned()`, and `String::from` do not. This is, what I consider to be, code bloat, which is a massive problem in languages like **C++**. Since **Rust** is such a young language, there is a big opportunity for this to be avoided.

I suggest, since those later three functions do they same thing, that two of them be eliminated. As for which ones should be removed, that is for someone much smarter than me to decided. I will say, though, that both `to_string()` and `String::from` are both more descriptive than `to_owned()`. If removing functions is not possible, or considered bad practice, maybe consider declaring which method is idiomatic.

Sorry if this sounds aggressive! I just love this language, and I would hate to see it fall into the same pits as older, non-modern, languages.

**Comment by steveklabnik** [comment]
> I suggest, since those later three functions do they same thing, that two of them be eliminated. 

There is no way to eliminate things in stable Rust. That is, we cannot make backwards incompatible changes.

>  maybe consider declaring which method is idiomatic.

`to_string` is considered idiomatic, generally. But each of the others are useful in their own situations. That is, the reason there are many ways to do this is that strings are very fundamental.

I'm going to file this as a docs bug to make sure the differences are made more clear.

**Comment by bluss** [comment]
@DirtGrubDylan Specifically `to_owned` and `to_string`, those methods come from the ToOwned and ToString traits respectively and the traits have different meanings associated with them. It just happens that for the `str` type in particular, the ToOwned and ToString traits do the same operation.

**Comment by DirtGrubDylan** [comment]
@steveklabnik Awesome. Yeah, strings are pretty important.

@bluss Right! I wasn't saying that these methods are intrinsically bad or anything. I just wanted to toss out my thoughts on keeping Rust from turning into the turgid monster that C and C++ have morphed into.
By no means do I claim to know, well, anything. I am still pretty new to programming, no less **Rust**. Just trying to be helpful.

**Comment by SilverWingedSeraph** [comment]
Potentially we could add an example to the String docs in the book, a section like this perhaps:women race response 

### &str and String Conversions

`&str` is very efficient to pass around, since it's just a reference to heap memory; but in order to do any manipulation, it's often necessary to have a `String`. There are a whole slew of ways to get from an `&str` to a `String`. In general, an `&str`'s `to_string` method is the best way. However, there are a few other cases. For instance, if you need to interpolate the string, you can use `format!`, which takes a string literal and interpolates it, returning a String. For instance:

```
fn describe_x(x: i64) -> String {
    format!("x is: {}", x);
}   
```

If you already have a `String`, you can use `.push_str()`.

```
// Given s is a String
s.push_str(", and some other stuff!");
```

`&str`s also has the usual `into_owned()` method implemented by many references which satisfy the trait `IntoOwned`, which in this case does the same thing as `to_string()`.

**Comment by steveklabnik** [comment]
@SilverWingedSeraph in the second edition of the book, we use String/str to motivate ownership and borrowing https://doc.rust-lang.org/nightly/book/second-edition/ch04-00-understanding-ownership.html

so there's already a lot more stuff there.

**Comment by steveklabnik** [comment]
I'm going to give this one a close; if there are specific changes to that chapter of the book, please open issues on its repo. Thanks!
