### ISSUE TITLE
Concrete vs. bound lifetime with fn-ptr from &Struct to &Trait

### ISSUE THREAD

**Issue by hban** [rust-lang/rust#40834]
The following code [[playpen](https://is.gd/b3tjuJ)]...

```rust
struct Foo {}

trait Bar {}

impl Bar for Foo {}

fn foo_to_foo(foo: &Foo) -> &Foo {
    foo
}

fn foo_to_bar(foo: &Foo) -> &Bar {
    foo
}

fn fn_converter<X, Y: ?Sized>(_: fn(&X) -> &Y) {}

fn main() {
    // Works.
    fn_converter::<Foo, Foo>(foo_to_foo);

    // Doesn't work.
    fn_converter::<Foo, Bar>(foo_to_bar);
}
```

...fails to compile with:

```
error[E0308]: mismatched types
  --> <anon>:22:30
   |
22 |     fn_converter::<Foo, Bar>(foo_to_bar);
   |                              ^^^^^^^^^^ expected concrete lifetime, found bound lifetime parameter 
   |
   = note: expected type `fn(&Foo) -> &Bar`
              found type `fn(&Foo) -> &Bar {foo_to_bar}`
```

Trying to use closures instead of fn pointers also fails, in two different ways [[playpen](https://is.gd/s3xWlm)].

**Comment by stephaneyfx** [comment]
Somebody correct me if I'm wrong.

I think this behavior can be explained by the rules for default object bounds ([RFC 599](https://github.com/nox/rust-rfcs/blob/master/text/0599-default-object-bound.md) and adjusted rules in [RFC 1156](https://github.com/rust-lang/rfcs/blob/master/text/1156-adjust-default-object-bounds.md)).

I think desugaring `foo_to_bar` according to the lifetime elision and the default object bound rules gives:
```rust
fn foo_to_bar<'a>(foo: &'a Foo) -> &'a (Bar + 'a) {foo}
```

And desugaring `fn_converter` gives:
```rust
fn closure_converter<X, Y: ?Sized, F: for<'a> Fn(&'a X) -> &'a Y>(_: F) {}
```

Applying the default object bounds to the call gives:
```rust
closure_converter::<Foo, Bar + 'static, _>(foo_to_bar);
```

Meaning `closure_converter` expects:
```rust
F: for<'a> Fn(&'a Foo) -> &'a (Bar + 'static)
```

This does not match the signature of `foo_to_bar`.

This can be fixed by changing the signature of `foo_to_bar` ([playground](https://play.rust-lang.org/?gist=d6146e834b3d30efbf366deb4ac4c82c&version=stable&backtrace=0)).
```rust
struct Foo {}

trait Bar {}

impl Bar for Foo {}

fn foo_to_foo(foo: &Foo) -> &Foo {
    foo
}

fn foo_to_bar(foo: &Foo) -> &(Bar + 'static) {
    foo
}

fn closure_converter<X, Y: ?Sized, F: Fn(&X) -> &Y>(_: F) {}

fn main() {
    closure_converter::<Foo, Foo, _>(foo_to_foo);
    closure_converter::<Foo, Bar, _>(foo_to_bar);
    closure_converter::<Foo, Bar, _>(|x| foo_to_bar(x));
}
```

**Comment by hban** [comment]
That does the trick, and also matches was I actually intended for that code to do. Too bad the error messages are completely unhelpful. I see that there are other similar open issues, so I'll go ahead and close this one.

Thanks for the help, @stephaneyfx!
