### ISSUE TITLE
Tracking issue for the cmp::Reverse type

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/rust#40893]
Added in #40720 under the `reverse_cmp_key` feature flag.

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

Seems like a nifty feature to stabilize!

**Comment by dtolnay** [comment]
I think a wrapper type makes sense by analogy with [`std::num::Wrapping`](https://doc.rust-lang.org/std/num/struct.Wrapping.html). :+1:

Elsewhere in std we call this "rev" instead of "reverse". :-1:

- [`Iterator::rev`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.rev)
- [`std::iter::Rev`](https://doc.rust-lang.org/std/iter/struct.Rev.html)

I see the `iter` module mentioned in the PR but not the `Rev` type so it doesn't seem like this was discussed. Does it make more sense to call this `std::cmp::Rev`?

@rfcbot concern rev

**Comment by BurntSushi** [comment]
@dtolnay Slices have a [`reverse`](https://doc.rust-lang.org/std/primitive.slice.html#method.reverse) method. :-)

**Comment by dtolnay** [comment]
Well shucks.

Comparing by conceptual similarity, I think this feature has more in common with `std::iter::Rev` than with slice `reverse`. They mean "don't do anything, but the next thing I ask you to do, do it backwards."

FWIW I think `Reverse` is a better name.

**Comment by BurntSushi** [comment]
> FWIW I think Reverse is a better name.

Me too. Given we already have the inconsistency, I think that pushes me toward `Reverse`.

**Comment by dtolnay** [comment]
With a clean slate, would we call them `Iterator::reverse` and `std::iter::Reverse`?

- If so, is there somewhere we should be tracking this so that when the AI overlords invent a way to version std, they can follow up?
- If not, is there any way to rationalize the difference?

**Comment by alexcrichton** [comment]
I feel like we discussed `Iterator::rev` vs `Iterator::reverse` a long time ago, but that was like pre-1.0 days. I always find it hard to drag up these rationales after-the-fact. (e.g. why `std::iter` and not `std::iterator`?)

**Comment by mitsuhiko** [comment]
FWIW the Python model has traditionally been "short names for modules" and "long descriptive names for methods" which is also what seems to be followed generally in Rust now. It does feel like `rev()` is one of the few exceptions to that rule.

**Comment by dtolnay** [comment]
Reverse is a better name.

@rfcbot resolved rev

**Comment by dtolnay** [comment]
@rfcbot reviewed

**Comment by scottmcm** [comment]
There's also the [`Ordering::reverse`](https://doc.rust-lang.org/std/cmp/enum.Ordering.html#method.reverse) method, so the struct version of that being `Reverse` seems logical :+1:
