### ISSUE TITLE
Apparent bad interaction between panic! and Ruby's rb_raise

### ISSUE THREAD

**Issue by wagenet** [rust-lang/rust#40973]
I can only get this issue to happen on AppVeyor with 32-bit Rust and Ruby. Every other environment I've tried (including a local Windows VM) does not exhibit this problem.

On this one environment however, using `panic!` with `catch_unwind` and then Ruby's `rb_raise` twice successively causes a hard abort. It's a bit hard to explain, but you can see the code in action here: https://github.com/wagenet/rust_panic_test.

If I remove either the `panic!` or the `rb_raise` then the code runs cleanly. If I only call them each once, the code also exits cleanly.

It's not easy for me to tell if this is specifically a Rust or a Ruby issue.

**Comment by wagenet** [comment]
I'm happy to dig into this more, but I don't really know where to go next.

**Comment by alexcrichton** [comment]
cc @vadimcn

**Comment by alexcrichton** [comment]
Note that this may be related to the specific versions of ruby, mingw, and/or MSVC that appveyor is using, but that's just a guess

**Comment by wagenet** [comment]
@alexcrichton yes, that's possible. I'm pretty sure that I'm using the same Ruby and mingw locally, though MSVC and base OS are not identical. @steveklabnik mentioned that he might look into it some too. The first step is probably trying to reproduce the issue outside of AppVeyor. It might also make sense to try to limit the PATH on AppVeyor so that we know exactly what is being introduced.

**Comment by vadimcn** [comment]
Any idea what stack unwinding strategy does `rb_raise` use?
Also, what happens if you `rb_raise` first and *then* `panic!`?  I wonder if `rb_raise` somehow messes up the current thread state.

**Comment by steveklabnik** [comment]
I did not have time to try to reproduce this this weekend.

https://github.com/ruby/ruby/blob/trunk/include/ruby/ruby.h#L1790 is the declaration of rb_raise, 

https://github.com/ruby/ruby/blob/47563655037ed453607de33b86fcc094878769ac/error.c#L2192-L2202 is its implementation; it's a wrapper around https://github.com/ruby/ruby/blob/2aaca105058950af2fc1a39c7e5c7cb032c85fff/eval.c#L619-L626

which I believe longjumps to something like https://github.com/ruby/ruby/blob/5318154fe1ac6f8dff014988488b9e063988a105/eval_error.c#L267-L318 ?

Maybe @tenderlove has some free cycles to help here, though he's a busy guy so maybe not!

**Comment by sfackler** [comment]
Can you have a debugger hooked up when the abort triggers? It'd be interesting to see where it is when that happens.

**Comment by tenderlove** [comment]
AFAIK Ruby will do a long jump.  I don't know that you can catch a long jump (I could be wrong though). What are you trying to accomplish?  Seems like if you're calling out to arbitrary Ruby code but you need to do cleanups, you should use `rb_ensure`.  I'm totally making a guess about what you're doing though.

**Comment by steveklabnik** [comment]
@tenderlove https://github.com/wagenet/rust_panic_test/blob/master/src/lib.rs#L9-L16

basically, @wagenet is trying to 

1. write a native extension in ruby using rust
2. catch a rust panic, aka totally not an exception
3. then raise a ruby exception instead

This is because unwinding across an FFI boundary is asking for trouble; Ruby isn't gonna be able to understand Rust's unwinding.

It _appears_ that on some Windows environments, this doesn't work for some reason.

**Comment by wagenet** [comment]
@tenderlove the test case is a reduced one to the point of looking a bit odd. The main point of surprise around this test case is that it works everywhere except for 32-bit builds on Windows on AppVeyor. This points to it being some sort of problem specific to Rust or Ruby in this specific environment.

As far as what I'm ultimately trying to accomplish, the idea is to have Ruby code that calls Rust code. Under some circumstances we may want to raise a Ruby exception from within this code. Since Rust has an unwinding process which does things like clean up allocators, we want to call `rb_raise` as late as possible to avoid skipping any important unwinding. The idea is then to use Rust's `panic!` to raise an exception and then catch that and `rb_raise` just before we would have returned control back to Ruby. Doing this once actually works fine, even in the failing environment. However, we could easily repeat this multiple times in a given process and the second repetition causes a hard exit on the 32-bit Windows AppVeyor environment.

**Comment by vadimcn** [comment]
@wagenet, To narrow this down, can you please modify your test such that it rb_raise's/catches first, then does Rust panic!/catch_unwind?
Also, please do try to get a callstack at the point of failure.  We are still unsure whether it aborts on Rust or on Ruby side, right?

**Comment by wagenet** [comment]
@vadimcn that won't work. The `rb_raise` will jump over any following Rust code.

**Comment by wagenet** [comment]
@vadimcn the output of the failure can be seen on the AppVeyor build of https://github.com/wagenet/rust_panic_test at https://ci.appveyor.com/project/wagenet/rust-panic-test/build/1.0.24/job/mf31hta2y9qw5bva

**Comment by wagenet** [comment]
Also, feel free to make a PR for my test app. Any PRs will get their own AppVeyor builds.

**Comment by vadimcn** [comment]
@wagenet I mean make it two separate FFI calls:
- the first one rb_raise's, this gets caught in Ruby code.
- the second one does the Rust part.

**Comment by wycats** [comment]
@tenderlove @steveklabnik to give a bit more detail:

The scenario in question is:

1. Ruby code calls into a Ruby method that is implemented in Rust
2. As part of the implementation, Rust calls back into some other Ruby code (after a few Rust frames which might need to be unwound)
3. The Ruby code raises a Ruby exception

In this case, we would like to rescue the Ruby exception at (3), unwind the Rust frames up to the FFI boundary at (1), and then re-raise the Ruby exception to the Ruby caller of (1).

As a result, Helix uses `rb_protect`, which effectively wraps a `begin`/`rescue` around the Ruby call at (3), to rescue any Ruby exception caused by the call into Ruby. We then `panic!` to unwind back to the FFI boundary, and use `rb_jump_tag` to re-raise the exception at the FFI boundary. Under-the-hood, `rb_jump_tag` uses a `longjmp` plus a custom unwinding strategy to clean up any intermediate Ruby frames.

This should ensures that any Rust frames are cleaned up by Rust, and Ruby handles Ruby exceptions as expected.

This strategy appears to work in general, but something about 32-bit Windows doesn't work (in some cases, the second time an exception is re-raised in this way, the program segfaults).

**Comment by wagenet** [comment]
@wycats that is also something we're doing, but this specific problem is actually not that one.

**Comment by wycats** [comment]
@wagenet Aha. We're investigating and will report back soon 😄 

Thanks @vadimcn for the suggestion.

**Comment by vadimcn** [comment]
Btw, I am not sure we expect people longjmp'ing out of Rust functions, even `extern "C"` ones.  
I think that cross-FFI error handling is supposed to work like this:
* In extern "C" function you catch any panics coming from Rust code.
* You return an error code to the caller.
* Caller (re-)raises the exception using whatever means are appropriate in the calling language.

**Comment by wycats** [comment]
@vadimcn Yeah, I can see how "Rust code that triggers a longjmp" is off the beaten path. Unfortunately, one of the goals of the project is to avoid needing custom C glue code, and it seems like there should be *some* way to implement an FFI boundary that might trigger a longjmp, even if it's highly constrained and requires care (or unsafe).

**Comment by wagenet** [comment]
@vadimcn I just split it into two calls. It looks like the issue is indeed calling `panic!` after `rb_raise`. You can see my change here: https://github.com/wagenet/rust_panic_test/commit/6d9f80b6eefbfdec0b215c5c3c83cfa8b9d73889 and the test results at: https://ci.appveyor.com/project/wagenet/rust-panic-test/build/1.0.30

**Comment by alexcrichton** [comment]
@wagenet would it be possible to keep minimizing? It'd be great if we could entirely rule helix out and get this down to basically just a Rust file compiled as a cdylib loaded into the ruby interpreter. Right now there's a lot of moving parts (most of which I don't understand) and it seems like the bug could be with any of them :(

**Comment by wagenet** [comment]
@alexcrichton the helix code in this is just a pass-through. `rb_raise` is just re-exported from Ruby.

**Comment by alexcrichton** [comment]
Sure yeah, but historically whenever I think something is "just a pass-through" there's typically a bug in that pass-through, so it'd just be helpful to work to reduce this further.

**Comment by wagenet** [comment]
@alexcrichton I understand, but given the nature of this specific case it seems highly unlikely. I can try to simplify it more but it won't be until next week at the earliest as I'm out of town the rest of the week.

**Comment by wycats** [comment]
@alexcrichton I can try to minimize it further with @chancancode. Next steps would be to try reducing down the `rb_raise` to a `longjmp`.

**Comment by nikomatsakis** [comment]
So [this test](https://github.com/wagenet/rust_panic_test/pull/1) suggests that the problem is that the call to `rb_raise` passes a `CString::new` (which means that there is a pending dtor at the time of the longjmp). Converting that argument to a byte string seems to solve it.

Is it possible that invoking a fn (in this case, `rb_raise`) with a pending dtor winds up storing a pointer to the stack into some thread-local variable? (I believe win32 SEH is not zero-cost, right?)

**Comment by vadimcn** [comment]
Good catch!
MSVC longjmp uses SEH to [unwind the stack](https://msdn.microsoft.com/en-us/library/yz2ez4as.aspx), so yes, you can expect all destructors to be invoked.

**Comment by alexcrichton** [comment]
Hm the intention at least is that we only run Rust destructors for Rust exceptions, if we're cleaning up on other exceptions I'd consider that a bug.

**Comment by wagenet** [comment]
And again, it's worth remembering that this issues doesn't occur on all Win32 environments.

**Comment by vadimcn** [comment]
If I am reading [this code](https://github.com/rust-lang/rust/blob/master/src/librustc_trans/intrinsic.rs#L720) correctly, it does not distinguish between Rust and foreign exceptions, right?

**Comment by vadimcn** [comment]
Er, I guess the code that generates cleanups would be more relevant here actually.  @alexcrichton, do you remember where's that?

**Comment by alexcrichton** [comment]
@vadimcn I think quite a bit has change since I last looked at this (like all of MIR), but [I think it's around here](https://github.com/rust-lang/rust/blob/3b5754e5ce73d24c6684b3ed0c68a557dfdd2f52/src/librustc_trans/mir/block.rs#L57-L59)?

AFAIK there's not a lot of MSVC-specific cleanups here. IIRC we used to use raw SEH intrinsics and functions, but that ended up cleaning up everything, like segfaults. We then switched to C++ exceptions whose personalities handled this correctly.

I wonder, is it possible to drill into precisely what form of exception is being thrown by longjmp? Does it also look like a C++ exception?

**Comment by nikomatsakis** [comment]
@wagenet are you able to at least workaround the problem? it seems like the ingredients you need are there. It'd be nice to fully understand the cause, though it seems like we are *somewhat* close.

@vadimcn I'm a bit confused by your comments. You're saying that `longjmp` on MSVC correctly 'pops' frames? In that case, is the potential problem that we are not settings things up correctly? I feel like I'm lacking a bit of background, because I don't know the full ... taxonomy of exceptions on windows (i.e., I'm not clear on the difference between "SEH" and C++-exceptions etc in terms of how they get translated in various Windows environments).

**Comment by wagenet** [comment]
@nikomatsakis current theory is that this only happens when we're leaking. We don't want to leak anyway, so the "workaround" is to structure our code such that we won't leak :)

**Comment by wagenet** [comment]
@alexcrichton `rb_raise` [(defn)](https://github.com/ruby/ruby/blob/ruby_2_4/error.c#L2207) calls `rb_exc_raise` [(defn)](https://github.com/ruby/ruby/blob/ruby_2_4/eval.c#L620) which then calls `rb_longjmp` [(defn)](https://github.com/ruby/ruby/blob/ruby_2_4/eval.c#L609).
`rb_longjmp` calls `TH_JUMP_TAG` which is an alias for `rb_threadptr_tag_jump` [(defn)](https://github.com/ruby/ruby/blob/ruby_2_4/eval_intern.h#L170) which calls `ruby_longjmp` an alias for `RUBY_LONGJMP` which on Win32 is an [alias](https://github.com/ruby/ruby/blob/ruby_2_4/win32/Makefile.sub#L762) for `longjmp`, which looks to be a C method.

**Comment by vadimcn** [comment]
@nikomatsakis: on WIndows, both setjmp/longjmp and C++ exceptions are kinds of SEH exceptions and use the same mechanism to unwind the stack.  It is up to the personality routine to decide whether or not to execute cleanups.
In principle, C++ is equipped to catch foreign SEH exceptions (via `catch (...)`), and since on win32 we are re-using C++'s personality routine, it's possible that we've set up exceptions table such that it catches everything.  I am not familiar with this code, so it'll take time to figure out what happens there.

**Comment by nikomatsakis** [comment]
@wagenet 

> We don't want to leak anyway, so the "workaround" is to structure our code such that we won't leak :)

Yes, this is sort of my latest understanding. I'm not 100% sure why things leak, given that @vadimcn says that `longjmp` runs cleanups, nor why the crash occurs when things leak, but I'm not sure how important it is to have the precise answer just now.

**Comment by alexcrichton** [comment]
@vadimcn FWIW this is what we tell LLVM:

https://gist.github.com/alexcrichton/130900d4440ab674f50ddd10c9babb3d

Namely we:

* Use the standard `__CxxFrameHandler3` personality routine
* Use a `cleanuppad` with no filters

Presumably this means "clean up for all C++ exceptions", and if longjmp is implemented on i686 MSVC by throwing a C++ exception then we'd run cleanups. I'm under the impression that the personality here doesn't run cleanups for non-C++ exceptions. For example if the function segfaults it will not run cleanups (but the personality routine is still run I believe).

Judging from the [documentation you pointed out](https://msdn.microsoft.com/en-us/library/yz2ez4as.aspx) though, it looks like longjmp is a C++-like exception because it claims object destructors are run.

To me the possible fixes here are:

* Use our own personality. I found this really didn't play nicely with LLVM and never got it to work, I would not recommend this. LLVM has lots of "if this is `__CxxFrameHandler3` do this else that" sort of clauses, and our lives tend to be easier using that personality. I may have just not understood personalities, though, so there may be a possible fix here.
* Use a catch clause to only catch some exceptions. I unfortunately don't know and/or understand how this works. I believe it's how `catch(SpecificException e)` works in C++, and we'd probably just want to inspect the output of `clang-cl` (IR form) and copy that if we take this route.

**Comment by nikomatsakis** [comment]
> To me the possible fixes here are:

It seems to me that we still don't **really** know what the problem is.

**Comment by alexcrichton** [comment]
@nikomatsakis oh really? [Your findings](https://github.com/rust-lang/rust/issues/40973#issuecomment-292571945) compared with [the docs](https://msdn.microsoft.com/en-us/library/yz2ez4as.aspx) @vadimcn [found](https://github.com/rust-lang/rust/issues/40973#issuecomment-292598025) implies to me that `longjmp` is running destructors, which is definitely unexpected from our and and I could totally see how that leads to a segfault (calling a `nounwind` function and then it unwinds)

**Comment by nikomatsakis** [comment]
@alexcrichton Ah, I see, because we label `rb_raise` as "nounwind"? That sort of makes sense, yeah. Is there any way today to declare an external function that **can** unwind?

**Comment by chancancode** [comment]
@alexcrichton The reason we suspect that we don't yet fully understand the problem is: after @nikomatsakis successfully fixed the issue in the reduced test case, we attempted to reduce our usage down to something similar.

Here's the current code: https://github.com/tildeio/helix/blob/4d5342326026439459e976d7c6c3df9ffa7ba1de/src/macros.rs#L127-L141

Now, the `rb_raise` is coming from inside of `__ruby_method__`, which only handles `VALUE`s (which are type aliases for `*mut c_void`). At this point, it's hard to see where the pending destructor could be coming from. (we tried without `#[inline]` too).

**Comment by nikomatsakis** [comment]
In principle, it's probably still UB if Rust marks the call as "nounwind" when it does, in fact, unwind, but I'm not sure of that, and I'm also not sure if it's an *actual* problem or merely a theoretical one.

**Comment by nikomatsakis** [comment]
@chancancode @wagenet how is `rb_raise` declared? Try adding the `#[unwind]` attribute (not sure if it's stable) -- that tells rustc that the C function may indeed unwind, I'd be curious to know if it has any effect. I guess we could run a similar experiment on the minimized version.

**Comment by alexcrichton** [comment]
@nikomatsakis hm so as I wrote that comment sorry I should have expanded more. I'm now also weirded out how running destructors could cause a segfault, because it looks like Ruby at least isn't storing a reference to the `CString`, it's copying it into a local string it appears.

So with that in mind I do think that calling a `nounwind` function which then unwinds is indeed UB, but precisely how it segfaults can be kinda weird. Note that we [do have a method](https://github.com/rust-lang/rust/blob/43ef63d5b4279ef97ed921338a69b0d62101ca83/src/libpanic_unwind/windows.rs#L94) of saying that a foreign function can unwind, it's just not stable.

@chancancode ah ok cool. So there's no destructors on the stack, and you're still getting a fault/failure? That seems.. interesting! Would maybe mean that the destructor related pieces are indeed a red herring.

**Comment by alexcrichton** [comment]
@chancancode also if you can describe the state of the stack when the call to `rb_raise` is called, that'd also be great. Basically just a stack trace. Is `__ruby_method__` the only Rust-defined frame on the stack? If so that'd be... weird!

**Comment by alexcrichton** [comment]
And also just due to how unwind tables work on Windows (maybe?) it could mean that `#[unwind]` fixes everything.

**Comment by wycats** [comment]
> @chancancode also if you can describe the state of the stack when the call to rb_raise is called, that'd also be great. Basically just a stack trace. Is __ruby_method__ the only Rust-defined frame on the stack? If so that'd be... weird!

The intent of the current code is to make that true. `__ruby_method__` is passed as a function pointer to `rb_define_method`, which is C code that calls the extern "C" function directly. So there should be nothing else on the stack.

**Comment by chancancode** [comment]
Adding `#[unwind]` to `rb_raise` didn't fix the issue, see https://ci.appveyor.com/project/wagenet/helix/build/1.0.414/job/fml3ri114iost24t for https://github.com/tildeio/helix/commit/e9c333f6fdfd71cfdd9debd99e853f8b675d33d4

**Comment by nikomatsakis** [comment]
@chancancode can we test it in the more limited setup?

**Comment by alexcrichton** [comment]
I have [minimized the failure](https://ci.appveyor.com/project/alexcrichton/helix/build/1.0.78) to a [few small files](https://github.com/alexcrichton/helix/tree/493755b5bc61cd7910653102a80ce7ea9f7a8578).

Unfortunately I must now at this moment get on a flight, so it will take me awhile to come back and keep investigating.

(note that this is what I meant by minimized)

**Comment by alexcrichton** [comment]
I cannot reproduce locally unfortunately using the installers from rubyinstaller.org. I can reproduce on AppVeyor (clearly) though. Unfortunately stepping through in a debugger on AppVeyor is not illuminating, there's not debug symbols and the program exhibits different behavior in the debugger than on the console.

I determined that the fault was happening in `catch_panic`, not in `rb_raise`. That is, the second time the Rust code executes `catch_panic` it somehow segfaults (or some other faults) somewhere inside there. In the debugger it said "failed to initiate unwind" which sounds like something got corrupted, although I do not know what.

**Comment by wagenet** [comment]
@alexcrichton does that mean that rb_raise is a red herring? or just that it's not where the actual fault happens?

**Comment by alexcrichton** [comment]
Nah I think it's definitely related to `rb_raise`, specifically the longjmp/setjmp aspect. It's just also related I think to panics in Rust. If I had to guess that something is implemented incorrectly, I'd guess it's us!

The next steps here are probably reducing this further to eliminate ruby entirely as a dependency. Stick to just plain C. If that still fails then stick to just plain-old LLVM IR. And if that fails maybe ask on the LLVM mailing list what's wrong.

**Comment by alexcrichton** [comment]
[Such a minimization](https://github.com/alexcrichton/helix/commit/e8b8e59fd527ef5d588cb87385a844f6cfa86bb8) does not segfault.

I [accidentally tested](https://ci.appveyor.com/project/alexcrichton/helix/build/1.0.113) with Ruby 1.9.3 and it work. Ruby 2.3.0 [does not work](https://ci.appveyor.com/project/alexcrichton/helix/build/1.0.117)

**Comment by alexcrichton** [comment]
This broke [between Ruby 2.0.0-p648](https://ci.appveyor.com/project/alexcrichton/helix/build/1.0.122) and [Ruby 2.1.9](https://ci.appveyor.com/project/alexcrichton/helix/build/1.0.121)

**Comment by alexcrichton** [comment]
This is as far as I got today: https://github.com/alexcrichton/helix/tree/ec26e1b2c30be1c3890d52357e77a00066e6f1dc

* An attempt to reproduce with just C + Rust doesn't segfault, it works as expected.
* An attempt to reproduce with Ruby + C++ doesn't segfault, it works as expected.
* The minimum Ruby version which fails is 2.1.9 (installed on appveyor at least)
* I've stripped the Rust library to `no_std` plus `panic_unwind` 
* I've attempted to minimize what's in play so far.

This is getting very far into the weeds at this point. The fact that C++ works and Rust doesn't is disturbing.

**Comment by wagenet** [comment]
@alexcrichton thanks for all of your hard work on this! If there's any way I can help, let me know, though I suspect it's pretty far beyond me at this point.

**Comment by alexcrichton** [comment]
I've unfortunately only been able to debug this on/off, and progress is super slow. So far I've managed to get a little farther (I think) each time but I still have no idea where the bug is, I'm just trying to narrow the gap between "working" and "not working".

@wagenet do you know how Ruby on Windows typically works? It'd be useful if I knew how to build Ruby itself and I could perhaps try to kick off a bisection in my spare time as I know it was introduced at some point in Ruby (although it's likely still a Rust bug). I just don't know off hand where the "standard" location is to get ruby on Windows, nor how that is itself compiled.

**Comment by steveklabnik** [comment]
@alexcrichton http://rubyinstaller.org/ is what people use to get Ruby on
Windows, but is ... "abandonware" is far too strong, but the main
maintainer dropped out a while back, and some people are keeping new
releases going, but not much else.

**Comment by wagenet** [comment]
It may also be possible to just look at the C diffs in the Ruby source to get some insight, though I'm not sure how big the delta is. As for RubyInstaller, that is for the initial install, but after that you can use RVM to install new Rubies. Should be possible to get down to patch releases this way.

**Comment by wagenet** [comment]
Actually, I take that back about RVM. I thought I had tried it, but now remember that I never did.

**Comment by thomthom** [comment]
Not sure if this applies to this issue, but it sounded similar. I stumbled across this issue while trying to figure out why we would suddenly start o crash in our C++ application that embedded the Ruby interpreter.

Turns out that we needed to have `/EHs` set - telling the compiler to assume that functions declared as `extern "C"` may throw. With this the compiler unwinds the stack correctly when Ruby longjumps. We found that a compiler update included more aggressive optimizations  that caused Release builds to crash at random places. We had been simply lucky we hadn't run into this in earlier versions of the MSVC compilers. 

Haven't found any similar flags in other compilers, nor have we observed the need for it.

**Comment by workingjubilee** [comment]
I believe this should be addressed by the changes to `extern "C"` and introduction of `extern "C-unwind"`.

**Comment by chancancode** [comment]
Not opposed to closing at all, it's been so long we probably all kind of lost the context on a lot of this.

That being said, I'm not sure `extern "C-unwind"` fully solved the problem here – I'm only casually observing at a distance at this point, so I am definitely fuzzy around the details, but from what I can tell the `extern "C-unwind"` RFC specifically did not address the `setjmp`/`longjump` use cases, which are relevant here. The RFC said those are TODOs for the future, and I dug around a bit for that and it doesn't seem like there have been follow-ups to those efforts yet.

Just thought I'd mention that for people who came across this in the future (and feel free to correct me if that's not the case, I'd be delighted).

**Comment by workingjubilee** [comment]
Hm. It does not solve it generally, no, though I think using `extern "C-unwind"` is still the compatible option on Windows due to the implementation details of Windows.
