### ISSUE TITLE
Rust 1.18 regression rustc-serialize doc tests have regressed

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#40994]
https://ci.appveyor.com/project/alexcrichton/rustc-serialize/build/1.0.563/job/s4vnewjo4l4448j2

```
failures:
---- src\base64.rs - base64::DECODE_TABLE (line 333) stdout ----
	error: unexpected close delimiter: `}`
  --> <anon>:21:1
   |
21 | }
   | ^
thread 'rustc' panicked at 'Box<Any>', src\libsyntax\parse\mod.rs:216
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'rustc' panicked at 'couldn't compile the test', src\librustdoc\test.rs:270
failures:
    src\base64.rs - base64::DECODE_TABLE (line 333)
test result: FAILED. 20 passed; 1 failed; 1 ignored; 0 measured
```

Likely related to https://github.com/rust-lang/rust/issues/40912

**Comment by steveklabnik** [comment]
This is basically the same as https://github.com/rust-lang/rust/issues/40979

https://github.com/rust-lang-nursery/rustc-serialize/blob/master/src/base64.rs#L332-L333

hoedown treated this all as a `p` tag, `pulldown-cmark` treats this as a `<p><code>`

In this case, the code block is invalid. The fix is to either fix that by removing line 352 (and then outdenting all the code), add a function header that accepts `ch` to make it a different kind of example, or change to `rust,ignore` so that it's not run as a test.

**Comment by alexcrichton** [comment]
@steveklabnik sure yeah, but to put this in perspective: [this](https://github.com/servo/rust-url/blob/v0.5.7/Cargo.toml#L14-L18) is invalid TOML that Cargo [still accepts with a warning](https://github.com/rust-lang/cargo/blob/4729175045b41b688ab903120860866ce7a22ba9/src/cargo/util/toml.rs#L168-L185) and we even [fix bugs in parsing](https://github.com/alexcrichton/toml-rs/commit/827a7c960cdfc6285afa5d780a6c0e273019ea09) as they arise to ensure we can keep parsing this.

I think we should totally fix the markdown, but I don't think we should immediately start failing so many builds without warning.

**Comment by steveklabnik** [comment]
>  so many builds without warning.

I've seen five builds so far, and they've all already been fixed. If there's a huge impact, I agree, but I haven't actually seen any evidence of that.

**Comment by bluss** [comment]
It's a CI failure for rustc-serialize that does not affect anything that depends on rustc-serialize, so impact is very limited in that way

**Comment by steveklabnik** [comment]
Fix sent: https://github.com/rust-lang-nursery/rustc-serialize/pull/182
