### ISSUE TITLE
mod and its inner struct have same name will cause a redefinition

### ISSUE THREAD

**Issue by wind2412** [rust-lang/rust#41099]
I have a `NFA.rs` in my workspace and there has a `RE.rs` in the same directory. They both have `#![allow(non_snake_case)]`.
```
.
|____NFA.rs
|____RE.rs
```
In `NFA.rs`, there has a struct which also names `pub struct NFA`.
When I want to reference the `pub struct NFA` in `RE.rs`, I use
```
mod NFA;
use NFA::NFA;

struct RE{
	re: &'static str,
	nfa: NFA,
}

```
Then I get an error:
```
error[E0255]: a module named `NFA` has already been defined in this module
 --> RE.rs:5:5
  |
3 | mod NFA;
  | -------- previous definition of `NFA` here
4 | //use NFA::NFA;
5 | use NFA::NFA;
  |     ^^^^^^^^ `NFA` already defined

error[E0573]: expected type, found module `NFA`
 --> RE.rs:9:7
  |
9 | 	nfa: NFA,
  | 	     ^^^ not a type
  |
  = help: possible better candidate is found in another module, you can import it into scope:
            `use NFA::NFA;`

error: aborting due to 2 previous errors
```
Of course Rust recognizes `NFA` first as a mod but not a struct.

But when I `use NFA::NFANode` and avoid the same-name problem, it will run perfectly.

Besides, when I change it as:

```
mod NFA;

struct RE{
	re: &'static str,
	nfa: NFA::NFA,
}
```

It will work, too...

I didn't find an issue like this in `Issues` before. If this one is duplicated or it is not a bug, that's my fault.

Besides,
    
    >rustc --version 
    rustc 1.18.0-nightly (2564711e8 2017-04-04)
;)

**Comment by TimNN** [comment]
This is expected behaviour as far as I know -- modules and structs share the same namespace. 

One possible fix would be to just use lowercase names\[0] for your modules (eg. `nfa.rs` and `re.rs`) then you'll have no problems doing `mod nfa; use nfa::NFA;`.

[0]: Which, by the way, is also the general convention in Rust, although it is of course your choice whether you follow that for your projects or not.

**Comment by arielb1** [comment]
This is as expected.
