### ISSUE TITLE
FnOnce closures cannot set uninitialized variables.

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#41124]
```rust
struct Foo(usize);

fn main() {
    let foo;
    map(|| foo = Foo(0));
    println!("{}", foo.0);
}

fn map<F>(f: F)
    where F: FnOnce()
{
    f();
}
```
gives
```text
error: closure cannot assign to immutable local variable `foo`
 --> x3.rs:5:9
  |
4 |     let foo;
  |         --- use `mut foo` here to make mutable
5 |     map(|| foo = Foo(0));
  |         ^^ cannot borrow mutably

error[E0381]: capture of possibly uninitialized variable: `foo`
 --> x3.rs:5:9
  |
5 |     map(|| foo = Foo(0));
  |         ^^ use of possibly uninitialized `foo`

error[E0381]: use of possibly uninitialized variable: `foo.0`
 --> x3.rs:6:20
  |
6 |     println!("{}", foo.0);
  |                    ^^^^^ use of possibly uninitialized `foo.0`

error: aborting due to 3 previous errors
```
Unless I'm mistaken, this should be perfectly legal?

Making `foo` mutable does also *not* fix the issue. The compiler continues to complain that the closure captures the possibly uninitialized value `foo`, even though the closure never reads `foo`. Furthermore, the `println!` below should see the value written by the closure, and so is not actually using a possibly uninitialized value.

**Comment by aidanhs** [comment]
The compiler doesn't do cross-function analysis, so it doesn't know if you actually *call* the `FnOnce` that you pass into map. As a result, the `println` is definitely unsafe. But there's an additional problem - if you don't know whether the closure has been called, you don't know whether the variable is initialised or uninitialised, so you can neither read it (`println`) *or* write to it (via assignment) without some drop flags magic to handle drop types.

Here's a simpler example that also fails to compile:
```
fn main() {
    let foo;
    let f = || foo = 5;
}
```

I'll be a bit more handwavey here since I'm less sure, but if you consider the closure to be a function boundary then maybe it makes sense - you can't pass uninitialised variables around, so you're also not allowed to stash away the uninitialised variable and make it available to the closure when it's called. That said, there's no reason why this specific case couldn't be special cased to work. But I'm not sure what you could do with it (since the special casing would fail in many more complex cases) without an RFC about uninitialised variables and what you can do with them.

**Comment by jonhoo** [comment]
Ah, that's a good point. I hadn't considered the case where the function is passed but not called. You're right, this is probably a non-bug then -- closing.
