### ISSUE TITLE
Incremental compilation - internalize symbols using up more than 1GB (double the RAM usage before)

### ISSUE THREAD

**Issue by neon64** [rust-lang/rust#41466]
It's my first time testing out incremental compilation and I encountered some issues building `alacritty` after making a negligible change... After speaking with @eddyb on IRC he suggested I open an issue here...

here is `-Z time-passes` with incremental compilation enabled:
https://gist.github.com/neon64/bb8ca569575b5e07b98da8805fd7c223
and without:
https://gist.github.com/neon64/50d005c24bb9da767615f5a5ba2cfc97

cc @nikomatsakis

**Comment by michaelwoerister** [comment]
cc me

**Comment by michaelwoerister** [comment]
I suspect this is due to the higher number of codegen units/object files that incremental compilation produces. "internalize symbols" is the first thing where we measure memory consumption after all LLVM modules have been created. In non-incremental mode that's just one LLVM module, in incremental mode it's somewhere around 30 for this crate.

If you recompile with only a small change, memory consumption should be a lot lower (given that the change does not affect too many of the object files).

The issue of keeping all LLVM modules in memory at the same time is already recorded as #39280.

**Comment by eddyb** [comment]
@michaelwoerister The way passes nest *always* throws me off! This makes a lot more sense.

**Comment by neon64** [comment]
Thanks for the explanation. Should I close this issue in favour of #39280 then?

**Comment by neon64** [comment]
Although I tried what you said an just made a small change (added a `println!()` statement in one file), and yet the memory usage was basically the same and it appeared as if all the LLVM modules were still being built.

**Comment by michaelwoerister** [comment]
> Although I tried what you said an just made a small change (added a println!() statement in one file), and yet the memory usage was basically the same and it appeared as if all the LLVM modules were still being built.

Can you tell me where exactly you made the change and which version of the crate that was?

**Comment by neon64** [comment]
Okay I am using the latest version (`a99a69c`) and the change I made was inside `src/input.rs`, line after 323 (inside the `on_mouse_wheel` function) I added the following:

```
println!("Delta: {:?} Phase: {:?}", delta, phase);
```

**Comment by alexcrichton** [comment]
Since https://github.com/rust-lang/rust/issues/39280 is now closed I'm going to close this as well
