### ISSUE TITLE
Setting slice values to scalar

### ISSUE THREAD

**Issue by beamspease** [rust-lang/rust#41532]
I wanted to do something like this:
```
x[a..b] = 0;
```

where a and b are variables, not constants.

There doesn't seem to be a well-known, easy way to do so (rust-beginners didn't know anything close).

IMO this is a fairly ergonomic way to initialize a range equal to some constant.

**Comment by steveklabnik** [comment]
In general, we don't track small feature requests with issues; we accept PRs to implement them. It'd be similar with something like this. As such, I'm going to close this; discussion about what this might look like in order to work up a PR might be a good thing for a thread on http://internals.rust-lang.org/ though! Thanks 😄
