### ISSUE TITLE
Spurious unused import warning when import used by #[test] code

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust#41737]
If `thread::sleep()` is used in `#[test]` code, but not by the rest of a lib, then the Rust compiler complains that the import is unused.

:/

Rust 1.16.0 / macOS 10.12.4

**Comment by Mark-Simulacrum** [comment]
As I understand it, this is because `#[test]` has the same effect as `#[cfg(test)]`, so this code simply isn't compiled; I'm not sure how much we can do about this case, though I agree if we could do better that would be great. `#[cfg(test)]` on the import should work though, at least as a temporary workaround.

**Comment by mcandre** [comment]
Cool,

```rust
#[cfg(test)]
use std::thread;
```

works for me!
