### ISSUE TITLE
Replace miniz.c with a pure-Rust implementation

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#41770]
As of today, it looks like the only two in-tree C dependencies are libbacktrace and miniz. Unlike libbacktrace, the existence of pure-Rust (de)compression libs sounds broadly useful and feasible to implement. Determine which functions in miniz we actually need and explore whether or not any crates in our library ecosystem can serve as a suitable replacement.

**Comment by kennytm** [comment]
miniz is only used in the `flate` crate, which probably could be replaced by an external crate (`flate2`? `deflate`?) as a whole. Compression speed seems to be a primary concern.

```rust
/// Compress a buffer without writing any sort of header on the output. Fast
/// compression is used because it is almost twice as fast as default
/// compression and the compression ratio is only marginally worse.
pub fn deflate_bytes(bytes: &[u8]) -> Bytes;

/// Decompress a buffer without parsing any sort of header on the input.
pub fn inflate_bytes(bytes: &[u8]) -> Result<Bytes, Error>;
```

**Comment by est31** [comment]
There is also compiler-rt, but its being replaced by a [pure rust implementation](https://github.com/rust-lang-nursery/compiler-builtins).

**Comment by BurntSushi** [comment]
Do you need flate specifically? The snap crate is a pure Rust snappy implementation.

**Comment by kennytm** [comment]
@est31 compiler-rt is imported as a submodule, so it is out-of-tree and off-topic for this issue I guess? Otherwise we would need to consider hoedown, jemalloc, graphviz and LLVM as well 😉.

**Comment by rkruppe** [comment]
For how compression is used in the compiler, see https://github.com/rust-lang/rust/issues/37086 for prior discussion and some experiments.

@kennytm @est31 Submodule or not, all these things are still used by and potentially merit discussion &mdash; just not *in this issue* since it's specifically about miniz.c. Separate issues might be worthwhile for some of them, and also for native libraries that get pulled in via crates.io dependencies (if any). But of those you named, hoedown is temporary, LLVM is 200% impractical to get rid of, graphviz AFAIK isn't a dependency (we have "libgraphviz" but AFAIK that's a pure-Rust implementation of writing out dot files). jemalloc might be interesting, once https://github.com/rust-lang/rfcs/pull/1974 merges and `alloc_jemalloc` moves to crates.io, it will only be used internally by the compiler.

**Comment by Mark-Simulacrum** [comment]
`miniz.c` is no longer in the compiler. We've removed the in-compiler libflate, replacing with https://crates.io/crates/flate2, which itself does bind to it, but IMO that's outside the scope of tracking here, see https://github.com/alexcrichton/flate2-rs/issues/67.
