### ISSUE TITLE
rustc --pretty=expanded outputs invalid syntax for #[derive(RustcDecodable)]

### ISSUE THREAD

**Issue by eqrion** [rust-lang/rust#42213]
### Run
1. `cargo rustc -- -Z unstable-options --pretty=expanded > lib-expanded.rs`
2. `rustc -Z parse-only lib-expanded.rs`

### With
```rust
// src/lib.rs
extern crate rustc_serialize;

#[derive(RustcDecodable, RustcEncodable)]
struct Foo;
```
```
$ rustc --version
rustc 1.19.0-nightly (5b13bff52 2017-05-23)
```

### Results
```
error: expected `{`, found `::`
  --> src/lib-expanded.rs:16:39
   |
16 |                             |_d| -> _ ::std::result::Result::Ok(Foo))
   |                                       ^^

error: expected one of `.`, `;`, `?`, `}`, or an operator, found `::`
  --> src/lib-expanded.rs:16:39
   |
16 |                             |_d| -> _ ::std::result::Result::Ok(Foo))
   |                                      -^^ unexpected token
   |                                      |
   |                                      expected one of `.`, `;`, `?`, `}`, or an operator here

error: aborting due to 2 previous errors
```

lib-expanded.rs:
```rust
#![feature(prelude_import)]
#![no_std]
#[prelude_import]
use std::prelude::v1::*;
#[macro_use]
extern crate std as std;
extern crate rustc_serialize;

struct Foo;
#[automatically_derived]
#[allow(unused_qualifications)]
impl ::rustc_serialize::Decodable for Foo {
    fn decode<__D: ::rustc_serialize::Decoder>(__arg_0: &mut __D)
     -> ::std::result::Result<Foo, __D::Error> {
        __arg_0.read_struct("Foo", 0usize,
                            |_d| -> _ ::std::result::Result::Ok(Foo))
    }
}
#[automatically_derived]
#[allow(unused_qualifications)]
impl ::rustc_serialize::Encodable for Foo {
    fn encode<__S: ::rustc_serialize::Encoder>(&self, __arg_0: &mut __S)
     -> ::std::result::Result<(), __S::Error> {
        match *self {
            Foo =>
            __arg_0.emit_struct("Foo", 0usize,
                                |_e| -> _
                                    { return ::std::result::Result::Ok(()) }),
        }
    }
}
```

### Expected

`rustc lib-expanded.rs` to succeed. Pretty printing should output valid rust syntax.

Not sure if this is specific to `rustc_serialize`, I haven't tried to create a simpler testcase.

**Comment by varkor** [comment]
The problem here, as far as I can tell, is a result of a combination of factors:
- The generated implementation of `decode()` generates an expression for the body of the lambda (rather than a block, unlike `encode()`:
https://github.com/rust-lang/rust/blob/b176285ba775f86301040fc624acb96b4499f562/src/libsyntax_ext/deriving/decodable.rs#L158-L160
- The closure-building method, `lambda`, generates the correct signature for the closure, but any closures that are printed will have full return type annotations regardless of whether they are `_` or not.
https://github.com/rust-lang/rust/blob/b176285ba775f86301040fc624acb96b4499f562/src/libsyntax/ext/build.rs#L925-L927
- pprust prints the closure signature, including return type, then the closure body immediately after. This is because it expects valid Rust syntax as input (in which this construction is impossible), but the syntax tree generated by `decodable` is not necessarily _syntactically_ valid:
https://github.com/rust-lang/rust/blob/b176285ba775f86301040fc624acb96b4499f562/src/libsyntax/print/pprust.rs#L2171-L2174

So the solutions are:
1. Modify `decodable_substructure` (or optionally `lambda`) to always wrap the expression in a block.
2. Modify the lambda printing that always prints the closure return type regardless, to special case `_`.
3. Make pprust handle invalid inputs better.

I'm not sure which is best here: fixing just 1 or 2 means other issues could slip by; fixing 3 seems like covering up the issue. 1 might be best for now, and if this issue re-emerges, then we can re-evaluate.

**Comment by varkor** [comment]
On second thoughts, it seems reasonable for pprust to assume correct input. In that case, the correct fix would be: modify the closure printing code to omit return types of `TyInfer` (which the functions generated by `lambda` always return). I could imagine this having other side effects, but I can't immediately think if that would cause any other problems.
