### ISSUE TITLE
Consider allowing non-object safe traits as types

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/rust#42235]
Today, we only allow you to use a trait as a type if that trait is object safe, because you cannot sanely instantiate the object unless the trait is object safe.

This is a bit odd, though! We let you implement traits for `HashMap<f32, _>`, even though you cannot instantiate a HashMap with f32 keys.

We could limit the object safety check to two cases:

*  *Instantiations* of these types
* Attempts to access items of these types.

```rust
trait NotObjectSafe: Sized { }

trait SomeTrait {
    fn static_method();
    fn non_static_method(&self);
}

impl SomeTrait for NotObjectSafe {
    fn static_method() {
        println!("There's no object, why isn't this allowed?");
        println!("You could totally call this function just fine.");
    }
    
    fn non_static_method(&self) {
        println!("You could just never instantiate the object.");
        println!("So you could never call this method.");
    }
}

fn main() {
     NotObjectSafe::static_method() // Never instantiated, should be fine.
}
```

Similarly, we could allow you to omit associated types from the receiver of such impls (e.g. `impl for Iterator`, without specifying an item).

I actually have a motivating use case for this: I have types which are parameterized by a trait, which is used solely for static dispatch. The trait is never actually instantiated as an object, and making it object safe is very limiting.

**Comment by nikomatsakis** [comment]
The problem is this:

```rust
fn foo<T: ?Sized + SomeTrait>() {
    T::static_method();
}

fn main() {
    foo::<SomeTrait>();
}
```

So, what we could do -- and we discussed in ad infinitum back in the day  -- is to keep the current notion of "object-safe", but report an error when:

- Accessing a "non-object-safe" member of a trait object (e.g., a generic method)
- Non-object-safe traits (like `SomeTrait`) do not "implement themselves" (i.e., `SomeTrait: SomeTrait` would not be true, hence the call to `foo()` would be illegal)

This was the case at some point. It complicates the "base language" in various ways. For example, right now, MIR has no *built-in* notion of a "virtual method dispatch". Instead, if you have a variable `foo: &SomeTrait` and you do `foo.non_static_method()`, that is encoded in MIR as `SomeTrait::non_static_method(foo)`. This corresponds to (in the user's mental model) the idea that `SomeTrait: SomeTrait` always holds (if objects are allowed at all). I am reluctant to lose this property, I must admit.

If you really want `static_method` to behave like a traditional static-method, you might consider this setup:

```rust
trait SomeTrait {
    fn non_static_method(&self);
}

impl SomeTrait {
    fn static_method();
}
```

Now you can do `SomeTrait::static_method()` but there is only one implementation of it (it is an inherent method).

**Comment by nikomatsakis** [comment]
> I actually have a motivating use case for this: I have types which are parameterized by a trait, which is used solely for static dispatch. The trait is never actually instantiated as an object, and making it object safe is very limiting.

Can you say more about this use case? I don't quite understand.

**Comment by nikomatsakis** [comment]
(To be clear, though, I am not in particular satisfied with the current setup. I'm just *also* not very enamored with a setup where `SomeTrait: SomeTrait` may not hold, but trait objects are possible.)

**Comment by withoutboats** [comment]
> The problem is this:

Wouldn't it be enough to say that the Foo trait object doesn't implement Foo unless it is object safe?

> Can you say more about this use case? I don't quite understand.

cargonauts has a macro that looks like this:

```rust
resource MyResource {
     method Get in JsonApi;
}
```

`Get` is a trait (implemented by `MyResource`). `Get` also needs to (as a type) implement a trait called `Method`, that has only static functions. Its compiled to a representation like `EndpointService<MyResource, Get, JsonApi>`, which invokes a static function from `Method`.

**Comment by withoutboats** [comment]
Your example demonstrates the problem fine: https://is.gd/LUymxo

In order to provide an inherent impl, the trait must be object safe. But I don't think that's necessary.

**Comment by nikomatsakis** [comment]
@withoutboats argh, I thought I had responded to this, but I see that I didn't. So, would you be satisfied with some solution that permitted methods on non-object-safe trait types, but didn't permit such types to be used more generally? (For example, we might say that you can always have type `Trait` for any trait, but unless the trait is object safe, then `Trait: Trait` does not hold and you cannot create instances of the type `Trait`.)

**Comment by withoutboats** [comment]
> (For example, we might say that you can always have type Trait for any trait, but unless the trait is object safe, then Trait: Trait does not hold and you cannot create instances of the type Trait.)

Yes, that seems like exactly what I'm trying for.

**Comment by withoutboats** [comment]
Closing in favor of this RFC rust-lang/rfcs#2027
