### ISSUE TITLE
Syntax: Return value

### ISSUE THREAD

**Issue by bumblebritches57** [rust-lang/rust#42274]
Why is it even possible to have an implicit return value?

What does that feature offer, except confusion, and making the learning curve even bigger?

I think you should remove this "feature", the only real purpose it serves is being *different* from C/C++.

**Comment by Mark-Simulacrum** [comment]
This feature is entirely optional, of course. I have found that it makes code look cleaner in many cases. While the purpose itself isn't too important, at this point I don't think removing this syntax is something that would be actively considered -- it is too widely distributed throughout the ecosystem.

To the learning curve point, I don't think it really increases it significantly, especially since the user can choose to never use implicit return until they want to.

**Comment by apasel422** [comment]
There's some discussion of this here: https://www.reddit.com/r/rust/comments/2v82ag/why_isnt_the_syntax_of_return_statements_explicit/

If you're passionate about changing this, consider [filing an RFC](https://github.com/rust-lang/rfcs), but note that what you're suggesting would be a massive breaking change and is unlikely for even a hypothetical Rust 2.0.

**Comment by bumblebritches57** [comment]
K, but users still need to make sure to double check that in other peoples code.

as I was trying to say, it just increases the user's mental load for absolutely no benefit.

**Comment by est31** [comment]
@bumblebritches57 There is [rust-clippy](https://github.com/manishearth/rust-clippy) which contains a bunch of lints for rust code, maybe they would welcome a new lint for implicit returns.
