### ISSUE TITLE
Infra - any interest in setting up a status.rust-lang.org page?

### ISSUE THREAD

**Issue by caspark** [rust-lang/rust#42308]
I [just saw on Reddit](https://www.reddit.com/r/rust/comments/6dopbn/from_the_new_infrastructure_team_an_official/) we've got [a Twitter account](https://twitter.com/RustStatus) for tracking outages and downtime now, and it got me thinking - would the infra team be interested in using [StatusPage.io](https://www.statuspage.io/) to set up a status page at e.g. status.rust-lang.org, similar to [metastatuspage.com](https://metastatuspage.com/) or [status.twilio.com](https://status.twilio.com)?

It can cross post incident updates to Twitter so we could keep the Twitter account, but it does email/sms/webhook notifications too (also RSS, which I saw someone asked for in the Reddit thread). Could potentially display some performance metrics there too.

I mention StatusPage.io specifically because I'm on the dev team and can probably organize a free account: Atlassian has been giving away free non-profit and open source software licenses for a long time and I think this should extend to status pages too, but I haven't looked into this officially.

cc @aidanhs who I gather may have set up the current Twitter account.

**Comment by aidanhs** [comment]
Hi @caspark, thanks for getting in touch! The Twitter was set up just to have *somewhere* to update people, but I'll definitely bring this up at the next infra team meeting on Friday to see if this is something we might be interested in (either now or in the future).

As an aside, internals.rust-lang.org might be a better location for discussions like this (since it's not an actual issue about Rust) - how would you feel about starting a thread there?

**Comment by aidanhs** [comment]
In fact, I've created a 'feedback' thread on internals (https://internals.rust-lang.org/t/feedback-on-ruststatus-twitter-and-anything-else-status-related/5331) and linked to here. I'll close this issue for now, but thanks again for getting in touch - I'll get back to you after our meeting.
