### ISSUE TITLE
Item names displayed by RLS can be from indirect dependencies

### ISSUE THREAD

**Issue by jntrnr** [rust-lang/rust#42393]
Playing around with Piston this morning, I noticed that there are sometimes cases where the compiler reports a type, but if you actually try to type this type it will error.

![image](https://cloud.githubusercontent.com/assets/547158/26744536/804eb9f2-483a-11e7-8843-ab8ddcdc7bed.png)

You can see the type on hover here as `piston_window::Texture<gfx_device_gl::Resources>`.  Great!  Let's type that in...

![image](https://cloud.githubusercontent.com/assets/547158/26744636/dd599cac-483a-11e7-8eb6-d48cb4fad0e1.png)

Wait what?  You just told me that was the type.  Don't tease me.

I'm guessing this type just isn't visible to me?  I'm honestly not 100% sure what is happening.

(apologies if this is a dupe)

**Comment by arielb1** [comment]
Sure enough. `gfx_device_gl` is an external crate, that your code is not using (otherwise it would work), but is used indirectly from places like https://github.com/gfx-rs/gfx/blob/7014ffd9fc5f549eaa67393de1f2421ea195d39b/src/lib.rs.

Because it's a crate, it's not really private - you could add `extern crate gfx_device_gl;` to your code and the respective dependency to Cargo, and then it would work.

This is sort-of related to #19792.

**Comment by arielb1** [comment]
I'm not sure what is the best thing to output in this situation, but it's possible we could do better.

**Comment by arielb1** [comment]
Actually, I think we already solved this and you just need to use absolute paths there (`piston_window::Texture<::gfx_device_gl::Resources>`).

**Comment by jonathandturner** [comment]
@arielb1 - that fix gives a different error.

![image](https://cloud.githubusercontent.com/assets/547158/26756535/ed8fb278-48f8-11e7-97dd-28ab5f492889.png)

It's possible this new error is correct, but would require yet more steps, since the type is coming from a crate I haven't added as dependency directly on my project.

After poking around, I found there is a type provided that can match called `G2dTexture` that comes from the same piston crate.  No idea if we can suggest things like this, but it would have saved an hour if we could.

**Comment by arielb1** [comment]
> After poking around, I found there is a type provided that can match called `G2dTexture` that comes from the same piston crate. No idea if we can suggest things like this, but it would have saved an hour if we could.

Automatic type alias completion. That's not something we are likely to introduce, I think.

**Comment by jyn514** [comment]
Save-analysis has been [removed from the compiler](https://github.com/rust-lang/rust/pull/101841).
