### ISSUE TITLE
[rustbuild] LLVM seems to not be rebuilt when submodule changes

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#42405]
I

* Changed the submodule, commited the changes;
* Commited the submodule commit change in the rust repo;
* Built.

Rustbuild did not seem to pick up on the submodule being changed.

**Comment by petrochenkov** [comment]
LLVM rebuild is currently triggered only when contents of `llvm-rebuild-trigger` and `llvm-finished-building` stamps disagree (including `llvm-finished-building` being non-existent), so it's *always* manual.
Full checking of something in LLVM being outdated is not performed because it's expensive thing to do on every build, but the submodule state check can be performed I guess.
