### ISSUE TITLE
Add wildcard support for UI tests

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#42434]
Some diagnostics have different output in different architectures, which [makes it harder to write arch agnostic UI tests](https://github.com/rust-lang/rust/pull/42304#issuecomment-305862331). This has cropped up multiple times. Personally I've either reworked the test or changed it to a compile-fail test, but given that [we'd like to consolidate on UI tests exclusively](https://github.com/rust-lang/rust/issues/40882), UI tests should have a way to avoid this problem.

**Comment by nikomatsakis** [comment]
cc @petrochenkov @cengizIO @kennytm -- all of whom have shown an interest in our testing infrastructure

**Comment by nikomatsakis** [comment]
I agree, we need to fix this, but I'm not sure the best way.

I'm a bit reluctant to just add random wildcards into the output, since then you can't run the "regenerate reference" script and have it work.

One thought I had was to permit multiple references, one per architecture, but that does seem to have the same problem.

Another thought I had was to permit you to add a custom file that indicates other search-and-replace pairs specific to a particular test. 

I guess it really depends on how often it comes up -- maybe it's ok to have to regenerate *some* reference files by hand, but it seems like a drag.

**Comment by Mark-Simulacrum** [comment]
I think maybe the right way to fix this is to have an easy way to not run UI tests on more than one platform; most UI tests don't really need this I think. That is, we're primarily testing spans, not so much the error itself. Perhaps that's not the right way to think about them, though.

**Comment by kennytm** [comment]
Instead of a custom file, I think the `*.rs` could specify headers for `TestCx::normalize_output` to teach it further normalization rules, e.g. for #42304 

```rust
// normalize-stderr-x86: s/fn\(\)(>?) \(32 bits\)/fn()$1 (64 bits)/g
// normalize-stderr-arm: s/fn\(\)(>?) \(32 bits\)/fn()$1 (64 bits)/g
// normalize-stderr-emscripten: s/fn\(\)(>?) \(32 bits\)/fn()$1 (64 bits)/g
```

If regex is too heavy, we could use simple literals instead:

```rust
// normalize-stderr-x86: "fn() (32 bits)" -> "fn() (64 bits)"
// normalize-stderr-x86: "fn()> (32 bits)" -> "fn()> (64 bits)"
// normalize-stderr-arm: "fn() (32 bits)" -> "fn() (64 bits)"
// normalize-stderr-arm: "fn()> (32 bits)" -> "fn()> (64 bits)"
// normalize-stderr-emscripten: "fn() (32 bits)" -> "fn() (64 bits)"
// normalize-stderr-emscripten: "fn()> (32 bits)" -> "fn()> (64 bits)"
```

BTW there should be `ignore-32bit` / `ignore-64bit` / `normalize-std???-32bit` / `normalize-std???-64bit` so you don't need to write everything three times.

**Comment by nikomatsakis** [comment]
@kennytm yes, that sounds fine too. We'd have to make the "update references" script rather smarter (so it can parse those things out).

**Comment by nikomatsakis** [comment]
Maybe rewrite it in Rust :)

**Comment by nikomatsakis** [comment]
@kennytm oh right, good point :)
