### ISSUE TITLE
With impl trait, some variables are not recognised as `'static` when used with `AsRef`.

### ISSUE THREAD

**Issue by P-E-Meunier** [rust-lang/rust#42451]
An example is the following code:

``` rust
fn f() -> impl Future<Item = (), Error = Error> {
    my_future.and_then(move |_| {
        foo("blah")
    })
}
fn foo<T: AsRef<str>>(t: T) {
     unimplemented!()
}
```

The current nightly rustc complains about unnamed lifetimes in impl trait. It accepts the same code with `"blah"` replaced by `"blah".to_owned()`.

I believe `"blah"` should be recognised of lifetime `'static`, and this code should be accepted by the compiler.

**Comment by eddyb** [comment]
cc @aturon @nikomatsakis I believe this is hard to accomplish without forcing *all* lifetimes in the concrete type, that were not inferred to be `'a` from `impl Trait + 'a`, to be `'static`. Because they *would* be inferred if there is an `+ 'a` (AFAIK)`, so that means `impl Trait` without lifetimes allows no lifetimes (*outside* of type parameters of the function) to be anything other than `'static`.

On second thought, that sounds close to the new RFC - if it's compatible with it, we're done!

**Comment by jyn514** [comment]
Triage: I'm not sure how to reproduce the original error, since neither `futures::Future` nor `core::future::Future` has `Item` or `Error` associated items. I would expect this to probably be fixed though since impl-trait is no longer experimental.

**Comment by P-E-Meunier** [comment]
Yes, definitely fixed.
