### ISSUE TITLE
refactor lint handling to be more "eager"

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#42511]
Lint handling at present works like this:

- During most of compilation, when we see something we might want to lint about, we insert this potential lint into a [mutable table in the session](https://github.com/rust-lang/rust/blob/f062832b208e94f2f0f26ed7fb5c48c172069fbe/src/librustc/session/mod.rs#L79). This comes along with a `NodeId` that identifies the AST/HIR node that the lint is attached to, along with the lint name, message, etc.
- We then have a dedicated pass that walks over the HIR. At each point, it tracks which lints are "allowed", "denied", etc. At the same time, it extracts entries from this table and reports them. It also invokes "lint visitors" that may generate additional lints.
    - In particular, some lints are just a custom pass, but others are generated as a side-effect of other things (like type-checking). It just depends on when the information that is needed is most readily available.

This is not a very good setup. Among other things:

- It requires us to generate a big table of "pending" lints, even in the case where a lint is `#[allow]`. Wasteful.
- It means that lints all get displayed fairly late in compilation -- this limits their value, since often a lint is detected early which might be useful in solving a compilation error, but we can't report the lint.
- It's not very incremental friendly because of the Big Mutable Table.

@eddyb proposed an alternative architecture that I think is better.

- In HIR lowering, we would compute which lints are in scope at each point. We would store this information in the HIR in some way (some thoughts on this below). 
- When we detect (in some phase) a lintable scenario, we would check *immediately* whether the lint is "allow", "warn", etc, and -- if needed -- issue the appropriate diagnostic right then.
- We can still run the custom lint code, it would simply query the HIR settings in the same way.

The best way to store this lint table is not 100% clear. Something sparse seems obviously like a good idea, since most nodes in the HIR do not have lint-related attributes on them (and hence just inherit the settings from their parent). I think maybe having each item store a link to the "current" settings for each lint makes sense; this can be easily shared between items. Then, *within* an item, if we need to compute the settings for some particular node, we would walk up the parents in the HIR map, looking for lint-related attributes and -- when we reach the item -- just using the settings stored on the item itself. 

Alternatively, we could just cache nothing and compute *everything* this way, at least to start. If more caching is desired, maybe have passes keep a local cache that would then be populated within the things within a particular item.

I'm available to mentor this. It is a bit of a "design needed" sort of job, so I'm not sure what the immediate instructions would be. The first step is obviously familiarizing yourself with the current setup. After that, I would probably try to make a commit that adds a method to the HIR map that will compute the innermost applicable lint setting for a particular node (just by walking up the parents). We could then use this and remove all the existing lint code for tracking. That should work, but be slow (O(n^2) lookups). Presumably we can then adopt some sort of caching strategy.

@eddyb also mentioned that for bonus points, we should probably "decode" attributes during HIR lowering more generally, so that we are not walking the general attribute data structures, but rather something specific to the stuff the compiler cares about.

**Comment by eddyb** [comment]
Another problem with the existing deferred lints is I don't think there is a way to make the messages rich (complex diagnostics) while emitting the diagnostics on the spot would make that trivial.

**Comment by nikomatsakis** [comment]
@eddyb I actually added support for rich lints, but yes, it was a pain, and it shouldn't be.

**Comment by oli-obk** [comment]
Cc @Manishearth , @llogiq , @mcarton 

We have a few lints which use a custom visitor because they need additional info. With these lints we've had problems with the attributes not working on the actual item which is linted. The way I understood this new system, such a check could become way simpler.

**Comment by mjkillough** [comment]
@nikomatsakis - I'd like to have a go at this if you're still willing to mentor it. I've started familiarising myself with the existing code and I am preparing to have a go at the "step one" you suggest.

**Comment by mjkillough** [comment]
I've added a function to the HIR map that naively calculates a `LintLevels` at a particular node by walking up its parents. I'm now trying to figure out how best to re-write some of the lints to use it.

If I understand the code correctly, there are four phases where we try to lint about things:

 1. Calls to `Session::add_lint()` before HIR lowering and before `lint::context::EarlyContext` runs. These get added to the table of pending lints and are emitted by `EarlyContext` as it walks the AST. ([[1]](https://github.com/rust-lang/rust/blob/bc9822af2eb8f59300354fd7c9336aa1f78304a1/src/librustc_driver/driver.rs#L712) [[2]](https://github.com/rust-lang/rust/blob/bc9822af2eb8f59300354fd7c9336aa1f78304a1/src/librustc_driver/driver.rs#L1226) [[3]](https://github.com/rust-lang/rust/blob/bc9822af2eb8f59300354fd7c9336aa1f78304a1/src/librustc_passes/ast_validation.rs#L221) [[4]](https://github.com/rust-lang/rust/blob/bc9822af2eb8f59300354fd7c9336aa1f78304a1/src/librustc_passes/ast_validation.rs#L236))
 2. The `EarlyContext` pass which walks the AST just before HIR lowering. It emits any pending lints from the table and also runs these checks and immediately emits any appropriate lints: `UnusedParens`, `UnusedImportBraces`, `AnonymousParameters`, `IllegalFloatLiteralPattern`, `DeprecatedAttr`.
 - (The AST is then lowered to HIR).
 3. Calls to `Session::add_lint()` after HIR lowering. (I think there are ~32 such calls). These get added to the table of pending lints and are emitted by `lint::context::LateContext` as it walks the HIR.
 4. The `LateContext` pass which walks the HIR. It emits any pending lints from the table and runs the rest of the lint passes, immediately emitting any appropriate lints.
 - (The doc-string of `lint::context::raw_emit_lint()` says that it is made public so that lints may be emitted during `trans`, after `LateContext` has already run. I can't see anywhere that's actually done though).

Which would mean the plan in the issue description expands to:

 - Leave (1) and (2) alone. Continue to build-up a small table of pending lints with calls to `Session::add_lint()`. These continue to get emitted by `lint::context::EarlyContext`. Continue to determine the level of each lint by parsing the attrs as we walk the AST in `EarlyContext`. (As both of these happen during `librustc_driver::driver::phase_2_configure_and_expand`, will it affect incremental compilation?)
- During HIR lowering, calculate the level of each lint at each node.
- For (3), calls to `Session::add_lint()` after HIR lowering use the calculated lint levels to emit lints immediately.
- For (4), `LateContext` stops trying to keep track of the lint levels as it walks the HIR and just uses the information on the HIR nodes that we calculated during lowering.

Is that still what you had in mind @nikomatsakis?

**Comment by eddyb** [comment]
@mjkillough That seems fine, expect that walking up the HIR every time can be expensive - or did you mean that HIR lowering records the information for some nodes (items?) and the HIR maps walks up for anything in between that and the node it was queried about?

**Comment by mjkillough** [comment]
@eddyb - Yeah, once we calculate the levels at each node during HIR lowering, we'd just walk up from the current node to whichever node had the calculated lint levels. As I haven't touched the HIR lowering part yet, I'm currently doing the easier thing and walking all the way up to the crate each time.

I don't think it'll just be items that we store the calculated lint levels on. Based on what the visitors in `lint::context` do, I think we'd need to store it on:`Item`, `ForeignItem`, `TraitItem`, `ImplItem`, `StructField`, `Variant`, `Local` and `Expr`. (We'd therefore need to walk up from whichever node we want to lint about to the enclosing one of these, which we can do quite easily).

I also haven't put much thought into how we'd store the calculated lint levels on the HIR nodes yet - I'd planned to do that once I had something working.

**Comment by eddyb** [comment]
@mjkillough I'd do only `Item` for now and have a hybrid solution for retrieving lint nodes for a specific node - mostly because lint annotations are somewhat rare.

**Comment by mjkillough** [comment]
@eddyb - OK, that makes sense. I'll have a go at doing that. Thanks!

**Comment by Mark-Simulacrum** [comment]
Related to this, I believe: https://github.com/rust-lang/rust/issues/14407 and https://github.com/rust-lang/rust/issues/14408.

**Comment by mjkillough** [comment]
@alexcrichton is keen to pick this up, so I've pushed what I had here and wrote my planned next-steps in the commit message: https://github.com/rust-lang/rust/compare/master...mjkillough:eager_linting_prototype

It may not make sense to base changes off that branch, as it is quite rough around the edges. It'll at least give you an indication of the direction I was heading in. :)

**Comment by alexcrichton** [comment]
I've opened a PR for this at https://github.com/rust-lang/rust/pull/43522
