### ISSUE TITLE
Tracking issue for `-Z profile` 

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#42524]
This is intended to be a tracking issue for the profiling feature, built on the gcov-style support in LLVM first added in https://github.com/rust-lang/rust/pull/38608 and later rebased in https://github.com/rust-lang/rust/issues/42433.

**Comment by steveklabnik** [comment]
Triage: not aware of any major move to stabilize this.

**Comment by glandium** [comment]
Is it expected that this doesn't work with --release?

**Comment by tylerhawkes** [comment]
Is there a way to change the path that the tests output to? I want to use this on some code that is cross compiled and needs to run on a device that only has a few writable paths. I'm currently getting this to work by replacing `/target/aarch64...` with `./arget/aarch64...` in the binary since we can't change the length of the string. 

I've never worked on the compiler before, but an option for this would be very useful.

**Comment by workingjubilee** [comment]
Removed: https://github.com/rust-lang/rust/pull/131829

**Comment by whitequark** [comment]
Aw, that's unfortunate.

**Comment by tshepang** [comment]
@whitequark why so

**Comment by whitequark** [comment]
As far as I understand there's no replacement?

**Comment by tshepang** [comment]
was thinking this was for branch coverage, which has since been implemented

**Comment by whitequark** [comment]
Oh. I missed that then!

**Comment by workingjubilee** [comment]
@whitequark Yes, `-Cinstrument-coverage` should work and supports the llvm-cov style of handling coverage: https://doc.rust-lang.org/nightly/rustc/instrument-coverage.html

**Comment by whitequark** [comment]
Oh that's fantastic work =^_^=
