### ISSUE TITLE
1.17.0 armv7 fails in debuginfo-gdb test macro-stepping.rs

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#42673]
See https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=armhf&ver=1.17.0%2Bdfsg2-4&stamp=1497504124&raw=0 - similar to #37225 but for armv7.

~~~~
error: line not found in debugger output: [...]#inc-loc3[...]
status: exit code: 0
command: /usr/bin/gdb -quiet -batch -nx -command=/«BUILDDIR»/rustc-1.17.0+dfsg2/build/armv7-unknown-linux-gnueabihf/test/debuginfo/macro-stepping.debugger.script
stdout:
[..]
~~~~

For the time being, I'll disable this test for armv7 in Debian, like how it already is disabled for aarch64.

**Comment by Enselic** [comment]
Triage: Does this test still fail? If yes, I'm still not sure this is worth keeping an issue open for? After all, this is a Tier 2 target, so tests are not guaranteed to pass. I agree it made sense to report this 6 years ago because someone might have showed up and said "oh it fails? I'll fix it then". But since that hasn't happened for 6 years, it seems unlikely to ever happen.

**Comment by Enselic** [comment]
Triage: No objections to close, so let's close.
