### ISSUE TITLE
Compilation time blows up with huge, numerous and nested enums

### ISSUE THREAD

**Issue by phaazon** [rust-lang/rust#42747]
I’m building a GLSL parser and hence have a very specific need for numerous, deeply nested enums. I added all the grammar symbols / tokens, and now the compilation takes more 20 minutes on my rustc 1.19.0-nightly \(78d8416ca 2017-06-17\), Mac OSX. The [compilation passes](https://gist.github.com/phaazon/96e674cf171204fefe75af66ec3ac0ac) point at the `item-types checking` pass – it takes roughly 5 minutes here – as being the bottleneck. The code can be found [here](https://github.com/phaazon/glsl/blob/master/src/syntax.rs).

Important note: I *think* that the problem is linked to all the numerous recursive enums. I guess rustc struggles to identify the size or whatever about the enums because it tries to see whether recursions are terminal? Thing is: I tried to box almost all variants, and the result is there: I reduced the compilation time from 20 minutes to a few seconds.

> Extra note: you can take the module linked above and compile it directly with `rustc`, no need to depend on the whole `phaazon/glsl` project ;)

**Comment by arielb1** [comment]
@phaazon 

First, if you have a big nested series of `enum`s, you probably want to insert a few `box`es inside. Otherwise you can waste a ton of memory in "dead" variants (I just had to add a few `Box`es to `rustc` to shave off a 100MB of RAM). The `-Z print-type-sizes` option on a nightly compiler can help you make sure that variant sizes are sane.

However, that should not cause any blowups in item-types checking! item-types checking should not be aware of the layout of your types, so that certainly looks like a bug

I was not able to reproduce the bug - the code you linked to seems to have the boxes in place already, and I was not able to cause slowness by removing boxes myself. Could you post a version of the code that exhibits the bug?

**Comment by lqd** [comment]
@arielb1 it happens to me with this version https://github.com/phaazon/glsl/blob/77686623da59895e82083955957dfdc0ae11f130/src/syntax.rs

**Comment by TimNN** [comment]
I had a quick look with Instruments on macOS and it seems that most of the time is spend in a somewhat deeply nested call to [`is_representable`](https://github.com/rust-lang/rust/blob/master/src/librustc/ty/util.rs#L820).

**Comment by arielb1** [comment]
I've seen that function hot on the rustc profiles too. Now that I have an excuse, let's go around fixing it.

**Comment by phaazon** [comment]
Yep, the version linked by @lqd is the one to blame (I fixed my code with boxes and forgot I didn’t provide a link via the commit hash – sorry!).
