### ISSUE TITLE
Add suggestion to unused_parens lint

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust#42892]
I just ran rustfix on <https://github.com/space-wizards/bsdiff-rs> and noticed that the built-in unused_parens lint has no suggestions.

Suggesting the underlined span without the surrounding parentheses should be enough.

```
warning: unnecessary parentheses around assigned value
   --> src/diff.rs:552:21
    |
552 |             lenf += (lens - overlap);
    |                     ^^^^^^^^^^^^^^^^
    |
    = note: #[warn(unused_parens)] on by default
```

**Comment by est31** [comment]
While the rustfix use case is legitimate, I think that such a suggestion would pretty well qualify as noise in the "normal" usage of rustc, as the suggested change is so obvious. Maybe rustfix could special case the lint?

**Comment by nixpulvis** [comment]
I'm too lazy to go hunting right now, but isn't there an RFC or Issue or something somewhere about a machine formatted output for rustc's lints and stuff? Could that possibly have the suggestion?

**Comment by est31** [comment]
> I'm too lazy to go hunting right now, but isn't there an RFC or Issue or something somewhere about a machine formatted output for rustc's lints and stuff?

There is (already since some time) the option to have json formatted error output for rustc. I'm not sure whether it also supports suggestions, but at least it supports spans and everything that's connected to those. However, the use cases this json format gets used for are various, they might be shown inline in some IDE or something. There is no guarantee whether the json gets churned by some external tool like in rustfix's case. You could of course add an additional mode, json_suggest_all_you_can or something, which also outputs obvious suggestions like how to remove unused parens or unused functions, etc. This is IMO the best way to tackle this from the compiler side.

**Comment by sanxiyn** [comment]
`--error-format json` does support suggestions.
