### ISSUE TITLE
Error NotExecutable

### ISSUE THREAD

**Issue by Verideth** [rust-lang/rust#42914]
Hey guys, I've been attempting to create a dll game function hooker, in rust. And I've ran into a problem. I'm using the library minhook-rs to hook my functions, and I keep getting this error in my match statement, "Error NotExecutable"

```rust
    let test = match test {
        Ok(test) => {
            println!("OKAY! {:?}", test);
        },

        Err(test) => println!("Error {:?}", test)
    };
```
where test is:
```rust
let test = unsafe { minhook::Hook::<createmove_fn>::create::<createmove_fn>(hook_createmove, fn_ptrs.addy) };
```

```rust
::create::
``` 
returns a std::result::Result

Its building the DLL fine, I'm building the target as `cargo build --target=i686-pc-windows-msvc`

createmove_fn is my type for my function pointer: 
```rust
type createmove_fn = fn(f32, *mut UserCmd) -> bool;
``` 
and fn_ptrs.addy is:

```rust
lazy_static! {
    static ref fn_ptrs: FunctionPtrAddress = FunctionPtrAddress {
        addy: unsafe {
            std::mem::transmute::<usize, createmove_fn>(0x104E1D68)
        }
    };
}
```
Thanks guys, all helps appreciated. I'd like to know why, and how to fix this error 2 ❤️

**Comment by TimNN** [comment]
I don't this issue is related to the rust compiler or standard library, so you may have better luck asking on https://users.rust-lang.org, https://stackoverflow.com or https://reddit.com/r/rust, however:

The `transmute::<usize, createmove_fn>(0x104E1D68)` looks bogus, where do you get the `0x104E1D68` from? Extrapolating from the error message, I would assume the `0x104E1D68` is incorrect and points to a section of non-executable memory.

**Comment by Verideth** [comment]
Yup @TimNN you're a life savior.

It was indeed that problem. I juts need to get the right address now :)

Thanks!! :D
