### ISSUE TITLE
Conversion to trait object seems to unreasonably require `Self: Sized`

### ISSUE THREAD

**Issue by marcianx** [rust-lang/rust#42923]
Here's the thread with the discussion:
https://users.rust-lang.org/t/specifying-that-trait-should-be-object-safe-for-purpose-of-casting-to-object/11564

Specifically, the following error happens

```rust
trait Trait {
    fn method(&self) {
        // ERROR: the trait `std::marker::Sized` is not implemented for `Self`
        let _ = self as &Trait;
    }
}
```
[Playground](https://play.rust-lang.org/?gist=07b7d16bb344262c589e714ffb184281&version=stable&backtrace=0)

It claims that `Self: Sized` is needed, but really, we are converting the *reference* `&Self` to `&Trait` which should work for both sized and unsized `Self`.

To prove this, one can create an intermediary `AsObj` trait that successfully does precisely this conversion.

```rust
trait Trait {
    fn method<'a>(&'a self) where &'a Self: AsObj {
        let _: &Trait = self.as_obj();
    }
}

trait AsObj {
    fn as_obj(&self) -> &Trait;
}

impl<'a, Type: Trait> AsObj for &'a Type {
    fn as_obj(&self) -> &Trait { *self }
}
```

[Playground](https://play.rust-lang.org/?gist=ac0b3c331673a96f232f4ec23195d845&version=stable&backtrace=0)

As far as I can see, `AsObj` has *no additional information* over the original `self as &Trait` at compile time and is identically constrained. The only difference I can see is that `as_obj()` takes, effectively, a reference to a reference, but that should make no difference. In particular, `*&self as &Trait` in the original doesn't succeed either.

So what gives? Is this a bug in the compiler?

**Comment by marcianx** [comment]
Crud, I just noticed that I can reproduce the original error if I use `Type: Trait + ?Sized` instead.

```rust
impl<'a, Type: Trait + ?Sized> AsObj for &'a Type {
    fn as_obj(&self) -> &Trait { *self }
}
```

Is the original behavior working as intended? I still don't see why `Sized` is necessary to create a trait object since, for example, `&[T]` knows its own size even though `[T]` is unsized.

**Comment by TimNN** [comment]
I'm not entirely sure, however I think the problem is as follows:

A reference to a sized concrete struct `&Struct` is just the pointer to the struct.

A reference to an unsized concrete struct `&UnsizedStruct` is a pointer to the struct + a `usize` with the actual size of the struct (or something similar).

A reference to a trait object `&Trait` is a pointer to a struct implementing that trait + a pointer to the vtable for that struct / trait combination.

If you wanted to support trait objects for unsized structs you would need some place to store the length. This means either a) carrying it alongside the other two pointers (this is bad since *all* users of the trait object would have to account for that) or b) add an additional layer of indirection (this should be possible today: add an `impl<T: Trait + ?Sized> Trait for Box<T>` or something similar and then cast an `&Box<T> as &Trait`).

**Comment by marcianx** [comment]
Yes, thanks! I just woke up in the morning and remembered this fact and just came here to post this. Rust doesn't support ...uh... superfat pointers. This issue should be closed.

**Comment by RReverser** [comment]
Stumbled upon this and I'm not convinced the explanation above is right... vtables already contain sizes for anything they reference, this is how `Box<Trait>` knows how much to deallocate for sized structs, and I don't see any good reason why it couldn't use the same information for unsized ones.
