### ISSUE TITLE
Errormessage regarding curly braces in for statement

### ISSUE THREAD

**Issue by Bendrien** [rust-lang/rust#42982]
I got the following [code](https://is.gd/W4021P):

```rust
struct StructWithCurlyBraces {
    _foo: usize
}

impl Iterator for StructWithCurlyBraces {
    type Item = ();
    
    fn next(&mut self) -> Option<Self::Item> {
        None
    }
}

pub fn main() {
    // with surrounding parentheses it works
    for _ in (StructWithCurlyBraces { _foo: 42 }) { }
    
    // without it doesn't
    for _ in StructWithCurlyBraces { _foo: 42 } { }
}
```

I don't know if the case without surrounding parentheses is intended to work but apart from that the error message is somewhat missleading.

```rust
error: expected type, found `42`
  --> <anon>:18:44
   |
18 |     for _ in StructWithCurlyBraces { _foo: 42 } { }
   |                                            ^^

error[E0423]: expected value, found struct `StructWithCurlyBraces`
  --> <anon>:18:14
   |
18 |     for _ in StructWithCurlyBraces { _foo: 42 } { }
   |              ^^^^^^^^^^^^^^^^^^^^^ did you mean `StructWithCurlyBraces { /* fields */ }`?

error: aborting due to 2 previous errors
```
It seems that the tokenizer doesn't get this right?

Edit: Include error message

**Comment by fintelia** [comment]
The same thing happens with an if statement:

```rust
struct X {}
if let X {} = X {} {}
```

```
error[E0423]: expected value, found struct `X`
  |
4 |     if let X {} = X {} {}
  |                   ^ did you mean `X { /* fields */ }`?
```

**Comment by estebank** [comment]
The parser cannot differentiate between a struct literal and a "path" (a variable) followed by a block in these places. There's no way to do so at parse time, as you don't yet know wether the found path is a struct so it could be parsed as such, so the parser just flat out [doesn't allow that construct](https://github.com/rust-lang/rust/blob/442b7bd10ab1955832fac39e47671327747033c6/src/libsyntax/parse/parser.rs#L3079).

What _could_ be improved is

1) not [suggesting the struct literal](https://github.com/rust-lang/rust/blob/442b7bd10ab1955832fac39e47671327747033c6/src/librustc_resolve/lib.rs#L2663-L2676) (remove the "did you mean..." if `tcx.sess.get_parent_node(id)` is an if/while/for statement)

2) suggesting this instead:
```
error[E0423]: expected value, found struct `X`
  |
4 |     if let X {} = X {} {}
  |                   ^
help: if you wanted to use a literal struct constructor here, try surrounding it with parenthesis
4 |     if let X {} = (X {}) {}
  |                   ^^^^^^
```

The second would be harder as at this point the compiler already decided that we meant `X` as the struct itself, not as the struct constructor, so we do not know where the span for its block ends, if it would parse correctly as such and even if _does_ end. Instead of the suggestion a `help` could be displayed instead of the current suggestion stating something along the lines of "struct literals are forbidden here due to ambiguous parsing, surround with parenthesis to avoid this".

**Comment by estebank** [comment]
Fixed by https://github.com/rust-lang/rust/pull/51360, https://github.com/rust-lang/rust/pull/59981 and https://github.com/rust-lang/rust/pull/60118
