### ISSUE TITLE
Bencher: Add method to run once?

### ISSUE THREAD

**Issue by joliss** [rust-lang/rust#42983]
*I hope it's OK to post a feature request here—feel free to just close if you want to declutter the issue tracker.*

I've found myself wishing I had a function to benchmark something just once (or a fixed number of times), e.g. `b.once`, in addition to the `b.iter` method:

```rust
#[bench]
fn foo_bench(b: &mut Bencher) {
    b.once(|| {
        // Do something slow and expensive
    });
}
```

Alternatively, perhaps libtest could allow for printing timings for the entire function. It could do that either by detecting that we're not calling `b.iter`, or by inspecting the function signature to check if there is no `Bencher` parameter.

```rust
#[bench]
fn foo_bench(_b: &mut Bencher) {
    // Do something slow and expensive
}
```

Right now if we do this, it just prints `bench: 0 ns/iter (+/- 0)`, even if the function is actually quite slow.

**Comment by Mark-Simulacrum** [comment]
I'm actually going to close this in favor of https://github.com/rust-lang/rust/issues/11010 since I think that's the underlying problem here. Could you add a comment there with your suggestion? It sounds interesting, though I think possibly not quite ideal -- I'd worry that one run may not give us enough information to say how long it takes per iteration....

**Comment by joliss** [comment]
Sounds good. I've added my use case there and provided some motivation.
