### ISSUE TITLE
unix::fs::OpenOptions get_access_mode EINVAL

### ISSUE THREAD

**Issue by raggi** [rust-lang/rust#43094]
I am doing some integration work trying to use Rust in Fuchsia and one of the tasks I am doing requires performing an ioctl on a directory in order to mount. The system requires that the directory is opened with and O_ADMIN flag, which can be applied using `std::os::unix::fs::OpenOptionsExt`.

I was receiving a spurious EINVAL result for the following code:

```
OpenOptions::new()
        .custom_flags(O_ADMIN | O_DIRECTORY)
        .open("/mydir")
```

After some time, I tracked this down to the `get_access_mode` method here: https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/fs.rs#L394

I believe the behavior of this case in this method is incorrect. It is not necessarily invalid for all use cases of open(2) to not have an access mode set. For the purposes of certain fcntl and ioctl calls on many different unix platforms, no access mode is strictly required. I propose removing this case.

**Comment by aidanhs** [comment]
According to posix (http://pubs.opengroup.org/onlinepubs/009695399/functions/open.html, which the LSB refers to):

> Values for oflag are constructed by a bitwise-inclusive OR of flags from the following list, defined in <fcntl.h>. Applications shall specify exactly one of the first three values (file access modes) below in the value of oflag:
>
> O_RDONLY
Open for reading only.
O_WRONLY
Open for writing only.
O_RDWR
Open for reading and writing. The result is undefined if this flag is applied to a FIFO.

So it's apparently not valid to not specify one of those.

Libc only happens to work because `O_RDONLY` is defined as 0 (at least, it is on my Linux), so it's effectively always enabled. This is hinted at in that posix page:

> In historical implementations the value of O_RDONLY is zero. Because of that, it is not possible to detect the presence of O_RDONLY and another option. Future implementations should encode O_RDONLY and O_WRONLY as bit flags so that:
>
> O_RDONLY | O_WRONLY == O_RDWR

It is arguable that we should enable read by default, but that could be a breaking change where `O_RDONLY` is nonzero. What does Fuchsia define it as?

**Comment by cramertj** [comment]
[Looks like it's also defined as 0 on Fuchsia.](https://github.com/fuchsia-mirror/magenta/blob/bc917d4ab9a58fdaca2ec3ff2953d3bfb5624c2e/third_party/ulib/musl/include/fcntl.h#L41)
