### ISSUE TITLE
`!` does not implement `Clone`

### ISSUE THREAD

**Issue by Twey** [rust-lang/rust#43296]
There is a trivial `impl Clone for ! { fn clone(&self) -> Self { *self } }`, but `!` as it stands does not implement `Clone`.  Maybe we should have that available?  It does implement `Copy`.

Playground:
https://play.rust-lang.org/?gist=3a2e62b2ed08be07de7d84d8620c4b34&version=nightly

**Comment by retep998** [comment]
Another type that is `Copy` but not `Clone` despite `Copy: Clone`?! How are we able to keep repeating this mistake?

**Comment by durka** [comment]
This seems to be a known issue: https://github.com/rust-lang/rust/issues/35121#issuecomment-314978341

**Comment by abonander** [comment]
Why not have  `!` implement every trait automatically? It makes sense.

**Comment by cuviper** [comment]
> Why not have `!` implement every trait automatically?

It shouldn't implement `Drop`, at least, and I think associated types are a challenge too.

**Comment by jmesmon** [comment]
If `!` can't be created, we can't ever drop it, right? Why would implementing `Drop` be an issue?

> It shouldn't implement Drop, at least

**Comment by cuviper** [comment]
AIUI there are many assumptions that `Copy` and `Drop` are exclusive, and if you try to do this explicitly you get [E0184](https://doc.rust-lang.org/error-index.html#E0184).  Maybe `!` could be special in this regard.

It may also make things like `needs_drop::<Result<(), !>>()` return `true`, which seems weird.

**Comment by abonander** [comment]
>It shouldn't implement Drop, at least, and I think associated types are a challenge too.

`Drop`, no. Associated types could be all set to `!` themselves; any trait requirements on them would be satisfied transitively. Actually, what might be the problem are static methods that don't return `Self`, e.g.:

```rust
pub trait MyTrait {
    fn static_method() -> &'static str;
}
```

Of course, they could just be generated with `unimplemented!()` but that could get a little surprising in generic code.

**Comment by cuviper** [comment]
For the problem of associated types, I was thinking something like this:

```rust
trait Foo: Iterator<Item = i32> {}
trait Bar: Iterator<Item = &static str> {}
```

So would `!` magically implement `Foo` _and_ `Bar`?  Or only `Iterator<Item = !>` set to itself, then fail to meet `Item` bounds that say otherwise?  It will also need to _not_ auto-implement `IntoIterator`, since the blanket implementation for `T: Iterator` already applies.

**Comment by abonander** [comment]
What I meant was that all associated types would be transitively set to `!`:

```rust
impl Iterator for ! {
    type Item = !;
    fn next(&mut self) -> Option<!> { ::core::intrinsics::unreachable() }
}
```

> It will also need to not auto-implement `IntoIterator`, since the blanket implementation for `T: Iterator` already applies.

My thought was that the part of the compiler that answers the question, "Does [this type] implement [this trait]?" would just always say "Yes" for `!`. This does bring up the interesting question of user-defined impls for `!`, if they should override or what. I feel like this can be handled by specialization.

**Comment by cuviper** [comment]
If it weren't `Sized`, then `!` couldn't be used in `Option`, `Result`, etc., let alone `Copy` or `Clone`.

How about associated consts?  That's similar to your `static_method()`, but we can't write `unreachable()`.

**Comment by abonander** [comment]
Good question. The answer that comes to mind is "just have it be an error to access them" but that doesn't help much in a generic context because then you could have generic code that compiles just fine but if you introduce `!` as a type parameter you're suddenly getting errors from inside that generic boundary.

I think associated consts should just disqualify traits from this auto-impl since there's no sane value to give them. It wouldn't diminish the utility of the feature all that much.

**Comment by soltanmm** [comment]
How would `!` implementing all traits interact with negative traits? Would it be the sole type simultaneously implementing `Trait` and `!Trait` for all traits? I can imagine this leading the compiler to automatically propagate `!` during type inference and allowing problematic code to compile, leaving problems undiscoverable until runtime when everything panics on empty implementations (though I haven't taken the time to think of any specific problematic weaponizations of the feature if they're possible).

**Comment by jmesmon** [comment]
@soltanmm the compiler is the one emitting that code (dummy `!` impls). All it has to do is not emit it and give an error instead. Ideally, we'd have a mechanism other than actual dummy impls for `!`).

**Comment by durka** [comment]
Stepping back, what is the advantage of having ! pretend to implement every
trait? Seems like it comes with a host of tricky complications.

**Comment by canndrew** [comment]
I don't think `!` should implement *all* traits, but there are a lot of traits for which it has only one possible (and trivial) implementation. Auto-implementing it for these doesn't come with the tricky implications and would make `!` available for use where it otherwise wouldn't be. For example, take `Hasher`:

```rust
pub trait Hasher {
    fn finish(&self) -> u64;
    fn write(&mut self, bytes: &[u8]);
    ...
}
```

Since every method takes a `self` parameter, every method is uncallable and so every possible method implementation is equivalent to just `{ *self }`.  In other words, there's only one possible implementation for `!: Hasher`, so it might make sense to not have to implement it manually.

But why would you *want* `!` to implement `Hasher`? Well, it's plausible that someone could be implementing a trait that looks like this:

```rust
trait SomeTrait {
    type H: Hasher;
    fn do_the_thing(&self) -> Result<Self::H, DoTheThingError>;

    // more items omitted
}
```

And it's plausible that they want to disable the hashing functionality of their impl and make `do_the_thing` always error. In which case setting `H = !` would make sense. This may be contrived but the point is that there are *so* many other traits like `Hasher` - traits that `!` has a sane, canonical, but maybe unexpected implementation for - that people are bound to end up in situations like this occasionally. And unless we make it very easy to impl these traits for `!` those impls likely just won't exist.
