### ISSUE TITLE
Suboptimal debug codegen in `rand`

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#43299]
I found in one of my crates that when compiling in debug mode (`cargo build`) the *largest* function in the whole executable looked like it was [this one](https://github.com/rust-lang-nursery/rand/blob/6ba6aabd580c0be3a34a9b5f8ab5e8591a1d5d7a/src/isaac.rs#L309-L368). That looked pretty innocuous so I dug a little deeper. It turns out that function creates 1000 `alloc` instructions using [this program](https://gist.github.com/alexcrichton/b16c54c93f5135abf4bbf23c4ab98184) as `find.rs` compiling [this source](https://gist.github.com/885e6d0bd72cde4756bb8da4bd0cc0be):

```
$ rustc +nightly -V
rustc 1.20.0-nightly (b2c070787 2017-07-13)
$ rustc +nightly foo.rs --emit llvm-ir --crate-type lib -Z time-passes && ./find < ./foo.ll
1137 allocas
```

Trying to winnow it down further [this source](https://gist.github.com/ba7626121c0454da2f576f392b7281b4) contains 337 allocas:

```
$ rustc +nightly foo.rs --emit llvm-ir --crate-type lib -Z time-passes && ./find < ./foo.ll
337 allocas
```

For comparison, [the equivalent C++ program](https://gist.github.com/dc9cf806c197ac82e85e8b6cbbb5432c) (I think? my C++ isn't very good) has only 86 allocas:

```
$ clang++ -emit-llvm -S foo.cpp -std=c++11 && ./find < ./foo.ll
86 allocas
```

Interestingly enough the C++ program compiles in ~0.035s whereas the Rust program compiles in ~0.2s, over 4x slower. The major passes in Rust 0.07s in translation, 0.03s in expansion, and 0.01s in item-bodies checking and LLVM passes. As to where the other 0.08s went in `-Z time-passes` I'm not sure!

**Comment by alexcrichton** [comment]
Also it looks like if the [inner block](https://gist.github.com/alexcrichton/ba7626121c0454da2f576f392b7281b4#file-foo-rs-L15-L22) is repeated in place Clang doesn't compile any more allocas (it's always 86) whereas Rust's number of alloca instances will grow linearly.

**Comment by kennytm** [comment]
Changing `a = a - e` to `a -= e` (and all 24 operations) increases that to 433 allocas 😕

**Comment by oyvindln** [comment]
From a glance at the assmbly, I suspect [`Range::next()`](https://github.com/rust-lang/rust/blob/master/src/libcore/iter/range.rs#L215) might be one of the issues here. (Though there are probably several things.) The function uses `mem::swap` to save the incremented counter value back to the iterator and return the previous value of the counter. 

Now,  `mem::swap` which is simply a shim that calls [`ptr::swap_nonoverlapping`](https://github.com/rust-lang/rust/blob/master/src/libcore/ptr.rs#L148) which ultimately calls [This monstrosity (`ptr::swap_nonoverlapping_bytes`)](https://github.com/rust-lang/rust/blob/master/src/libcore/ptr.rs#L156). All this to swap two numbers. Now this will get optimised out in release mode, but in debug mode it results in a lot of redundant cruft. I presume swap is used since the range trait could theoretically be used on something that is not primitive integers, though maybe the next function (and anything else currently using swap) should be specialised to avoid using swap for types where it's not needed. Even in release mode this seems like something that will create a lot of redundant work for the llvm optimiser.

**Comment by oyvindln** [comment]
So there are some differences between the cpp version you posted and the rust version. 

Firstly there is the loop. In the C++ version, the loop is a loop over an array of 4 elements, rather than a range iterator as in Rust.  See [this](http://en.cppreference.com/w/cpp/language/range-for). It looks as though it avoids using iterators entirely in this case (I don't see any calls to `begin()` `end()` in the output) which makes it a bit cleaner than the rust version which has to iterate by calling `next()`. 

Secondly, there are some differences in the functions on the wrapping type. In Rust the methods on `Wrapping` are marked `#[inline(always)]`, so they get inlined even when not doing optimizations. In the rust version this results redundant extra temporary copies being created (e.g more alloc statements) for every invocation of these methods. (This also explains the massive increase when manually unrolling) In the cpp version, the temporaries are created inside the method call instead, which results in the IR having less alloc statements.

I made an altered cpp version that gives results that are a bit closer to the rust version, by force-inlining the method calls and calling wrapping add/sub through a function as in rust: (I didn't bother altering the loop iteration as that would be a bit more complex.)

https://gist.github.com/oyvindln/cc65fc6c479d3347708be972798d49f7

(There other value in Wrapping::shr/shl is anded by [this](https://github.com/rust-lang/rust/blob/master/src/libcore/num/wrapping.rs#L343) in the rust version also, but I'm not sure what value `pub const u64: u32 = i64;` results in). 

This gives me 286 allocas which is a bit closer to the rust version. Interestingly, the wrapping_{add/sub} functions have two allocas in c++, and only one in rust. Maybe there is some basic processing that could be done during this inlining to avoid all the redundant copies here.

Another interesting observation is that both the rust and c++ versions treat the wrapping type as though it is an aggregate, and thus accesses the inner value by a pointer into the struct. Maybe [`#[repr(transparent)]`](https://github.com/rust-lang/rust/issues/43036) could help here to let llvm know the inner value could be manipulated directly once it's added.

**Comment by alexcrichton** [comment]
Oh nice find on the `#[inline(always)]`!

I removed the annotations and the example dropped from 337 allocas to 129 allocas (yay!). Unfortunately though Rust still shows linear growth in terms of repetition while C++ still doesn't :(

**Comment by alexcrichton** [comment]
I've opened https://github.com/rust-lang/rust/pull/43367 to remove `inline(always)` annotations.

**Comment by oyvindln** [comment]
Removing the redundant masking operation in [`Wrapping:shl/shr`] (which calls [`wrapping_shl/shr`] which already masks anyhow) would probably also help avoid one alloca for each of those functions, at least it did when tested with a local copy of them (didn't try with the standard library itself).

**Comment by Mark-Simulacrum** [comment]
We appear to generate a constant 46 allocas today in debug on stable for [this program](https://gist.github.com/ba7626121c0454da2f576f392b7281b4), including when repeating the body of the loop many times. I think this is fixed. The original program (random generator) produces a total of 103 allocas without filtering as well, so I think we're doing much better in this space.
