### ISSUE TITLE
Could we smartly elide some info from types in error messages?

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#43354]
If there is a type error where the outer types don't match (e.g., `Foo<T> != Bar<U>`) we could elide the un-important type info (e.g., report `Foo<...> != Bar<...>`. This would be effective where there are very long, complex types such as iterators or closures.

**Comment by estebank** [comment]
@nrc we already [elide matching type arguments](https://github.com/rust-lang/rust/pull/41205) when the outer types match (`Foo<A, B> != Foo<A, A>` -> `Foo<_, B> != Foo<_, A>`).

The heuristic to elide the presentation of all type arguments should be a bit more involved than "outer types don't match" to avoid hiding cases like:

 - `Some(X) != X` and vice bersa
 - `Foo<A, B> != Bar<A, B>`
 - `Option<A> != Result<A, B>`

I think we should only do what is proposed here if under the current output both lines would be "fully highlighted", and even then, I'd only do it if the line is over a certain length.

`</2¢>`

**Comment by jackh726** [comment]
I'm going to go ahead and close this. I think for this to be actionable, we need specific examples of code that gives bad diagnostics today; otherwise, we just end up with an issue without some concrete way to know when it should be closed. As @estebank mentions, we do (for a long time) elide matching type arguments. There's also been #57413 that has been merged since.
