### ISSUE TITLE
No EndRegion emitted for DestructionScope

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#43457]
The following code
```rust
fn rc_refcell_test(r: RefCell<i32>) {
    r.borrow_mut();
}
```
compiles to MIR without any `EndRegion` (this is right before the `EraseRegions` pass):
```
// MIR for `rc_refcell_test`
// source = Fn(NodeId(54))
// pass_name = EraseRegions
// disambiguator = before

fn rc_refcell_test(_1: std::cell::RefCell<i32>) -> () {
    let mut _0: ();                      // return pointer
    scope 1 {
        let _2: std::cell::RefCell<i32>; // "r" in scope 1 at ../tests/run-pass/std.rs:19:20: 19:21
    }
    let mut _3: std::cell::RefMut<ReScope(DestructionScope(NodeId(259))), i32>;
    let mut _4: &ReScope(DestructionScope(NodeId(259))) std::cell::RefCell<i32>;

    bb0: {
        StorageLive(_2);                 // scope 0 at ../tests/run-pass/std.rs:19:20: 19:21
        _2 = _1;                         // scope 0 at ../tests/run-pass/std.rs:19:20: 19:21
        StorageLive(_4);                 // scope 1 at ../tests/run-pass/std.rs:20:5: 20:6
        _4 = &ReScope(DestructionScope(NodeId(259))) _2; // scope 1 at ../tests/run-pass/std.rs:20:5: 20:6
        _3 = const <std::cell::RefCell<T>>::borrow_mut(_4) -> bb1; // scope 1 at ../tests/run-pass/std.rs:20:5: 20:19
    }

    bb1: {
        drop(_3) -> bb2;                 // scope 1 at ../tests/run-pass/std.rs:20:5: 20:19
    }

    bb2: {
        StorageDead(_4);                 // scope 1 at ../tests/run-pass/std.rs:20:19: 20:19
        _0 = ();                         // scope 1 at ../tests/run-pass/std.rs:19:37: 21:2
        StorageDead(_2);                 // scope 0 at ../tests/run-pass/std.rs:21:2: 21:2
        return;                          // scope 1 at ../tests/run-pass/std.rs:21:2: 21:2
    }
}
```

Cc @pnkfelix

**Comment by RalfJung** [comment]
Cc @nikomatsakis

**Comment by pnkfelix** [comment]
Indeed, even the CleanEndRegions.before.mir shows no `EndRegion(_)` for that borrow. Looking further now.

**Comment by pnkfelix** [comment]
Very weird: It seems like at the time that control reaches this statement in `rustc_mir::build::Builder::ast_block_stmts`, there is no destruction scope attached to it...? still looking... (I'm not aware of a place where a destruction scope would be added later...)

**Comment by pnkfelix** [comment]
A ha!

The destruction scope exists, but during the HIR -> HAIR translation, we fail to find it, because the way we look up the destruction scope is with some code that looks like this:

```rust
    let opt_def_id = cx.tcx.hir.opt_local_def_id(block_id);
        ...
        let opt_dxn_ext = opt_def_id.and_then(|def_id| {
            cx.tcx.region_maps(def_id).opt_destruction_extent(stmt.node.id())
        });
```

but the `opt_def_id` that we got for that `block_id` is `None`, so the lookup doesn't have a chance of working.

Now to figure out what `opt_local_def_id` is returning `None` here (or if we perhaps should be using a different key for the `region_maps` lookup?)

**Comment by pnkfelix** [comment]
@eddyb [points out](https://botbot.me/mozilla/rustc/2017-08-25/?msg=90283838&page=1) that I should not be attempting to do `cx.tcx.region_maps(def_id)` in the first place here (which then goes south when I fail to find the appropriate `def_id` to use), because the `cx` itself now *carries* the appropriate `region_maps` directly, thanks to #41662 

Will fix!
