### ISSUE TITLE
`mem::uninitialized`'s documentation has an incomplete list of safe ways to write to uninit

### ISSUE THREAD

**Issue by Vurich** [rust-lang/rust#43473]
All the writing functions in `std::ptr` (even `ptr::swap`, I believe, although I can't think of a meaningful usecase for that and you'd have to `mem::forget` the returned value) are valid ways to write to uninitialized memory. `mem::uninitialized`'s documentation mentions only `ptr::write`, `ptr::copy` and `ptr::copy_nonoverlapping`.

**Comment by steveklabnik** [comment]
@rust-lang/libs , is this true? If so, we should fix it, so p-medium.

(And generally enhance all their docs with this info)

**Comment by Mark-Simulacrum** [comment]
`std::ptr::replace` can't work; it returns the previous value at the src pointer as a `T` (which is UB, at least for some T).

`std::ptr::swap` and the non-overlapping could plausibly work, but is a bit odd IMO -- seems like we could support it on `MaybeUninit`, but there's not much benefit as far as I can tell, because given MaybeUninit, you can use `std::mem::swap(&mut MaybeUninit<T>, &mut MaybeUninit<T>)` without the unsafety, too...

As such, I'm going to close this since it seems like there's not much left to do here.
