### ISSUE TITLE
We suggest both adding a semicolon and a return type

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#43516]
This isn't necessarily bad, but perhaps not anticipated. It looks a little bit odd. I'm not sure if we should do anything, but opening to discuss.

```rust
fn read_u32() {
    100i32.to_le()
}
```

```
error[E0308]: mismatched types
 --> src/main.rs:2:5
  |
2 |     100i32.to_le()
  |     ^^^^^^^^^^^^^^ expected (), found i32
  |
  = note: expected type `()`
             found type `i32`
help: try adding a semicolon
  |
2 |     100i32.to_le();
  |                   ^
help: try adding a return type
  |
1 | fn read_u32() -> i32 {
  |               ^^^^^^

```

cc @estebank

**Comment by estebank** [comment]
What would you expect the compiler to suggest? The only problems I see is that the suggestions are mutually exclusive and are not inline.

**Comment by oli-obk** [comment]
I deliberately chose to not put multiple suggestions inline when I added inline suggestions. The second one can't be inline anyway, since its span is not connected to or part of the error span.

Clippy has had multiple suggestions for the same diagnostic for a while.

We could add a heading above multiple suggestions noting there are "multiple possible suggestions". They are rare, so being a little more verbose wouldn't hurt imo.

**Comment by Mark-Simulacrum** [comment]
Hm, yeah, I'm going to say that there's nothing I actually think should change here. Closing, let me know if you want to keep the bug open.
