### ISSUE TITLE
print! and panic! don't work on std platforms without pthreads

### ISSUE THREAD

**Issue by Others** [rust-lang/rust#43633]
Currently, using  `print!` or `panic!` with `std` requires thread local (and I think maybe mutex) support. This is a pain point for running Rust on systems without `pthread`/`TLS` support.

I work on an OS that works on embedded devices. We have a libc (a MUSL fork), and much of the Rust standard library runs out of the box on our system. However, since we roll our own threads, we don't have `pthread` support.

I've been working to get Rust running on our system, and this is an annoying issue. It isn't a big deal for `print!`, since it's trivial to roll our own, but it really matters for `panic!`. While it seems like we could just use a custom hook, we can't in practice since it involves taking a lock. When a library thread calls `panic!` we'd prefer to get an actual message, rather than a crash in our `pthread` stubs.

I think a solution for this would be to add an option to `std`, similar to `force_alloc_system `? This would disable all the complex infrastructure around prints and panics, and just do the absolute simplest thing. These functions can be implemented (with very similar functionality) on systems without `pthreads`, it's just a case of exposing them in some way.

**Comment by Others** [comment]
C-feature-request / T-libs ?

**Comment by aidanhs** [comment]
Does `has_elf_tls` not work? I can see you're using it in https://github.com/Others/lib_composite/blob/master/i686-unknown-composite-musl.json#L11.

Note that libstd itself needs to be compiled with that target specification, but it looks like you're using xargo already, so you should in theory just use a target spec that disables elf tls and be done with it (alternatively, since you have to recompile Rust anyway to get your musl in liblibc, you can carry a patch to rust adding your own built-in target).

----

As an aside, please don't use `force_alloc_system`! I added it as a hack for one purpose only, to allow 'local rebuilds' of a Rust without jemalloc, from one that does - *any* other use-case to do with allocators should be served by the target spec allocator options. I've noticed a few people try to use it, so clearly it needs renaming to discourage use.

**Comment by Others** [comment]
@aidanhas It's my understanding that without ELF TLS thread_local falls back to using pthreads thread local support. And even if that wasn't true, 'panic!' still takes a lock (I believe).

Point totally taken about 'force_alloc_system' though, I'll get rid of that :)

**Comment by Others** [comment]
(Whoops sorry, misspelled your name @aidanhs)

**Comment by aidanhs** [comment]
Oh, doesn't pthread thread local and mutex support effectively just consist of the gs register on i386 and assorted atomics? I assumed that would be acceptable, given you're targeting i686 (atomics and therefore mutexes are no problem), and you'd just stub out the bits of pthreads you explicitly don't want (or not, and just let them crash as it sounds like they do today).

I'm say this because I'm familiar with using a no-thread musl fork and the battle only begins with libstd - there are a bunch of libraries out there, tokio being an obvious one, that just assume thread local support (even if you don't use threads). In addition, using this hypothetical 'no-threads' flag without correctly modifying libc would make it easy to do bad things in safe Rust. I could see there being a 'no threads' target for Rust at some point that makes sure to do everything correctly in Rust, but you may find it easier to look elsewhere.

**Comment by Others** [comment]
@aidanhs Our OS actually does have threads, it just doesn't have the infrastructure to tell pthreads about them / actual pthread methods. (Accessing the `gs` register faults with our current setup.) That's not really relevant though.

Here is what I think: you should be able to use `std` on systems without pthread support. You should not expect anything related to threads in std to work. You should not expect all libraries to work (especially those with anything to do with threads). But you should be able to use basic `std` functionality, even if you have to enable some option to do so. You literally cannot use `print!` unless your system supports some quite complicated threading primitives. And while the story for `panic!` is more complicated, it's a shame that it can't be made to work.

**Comment by nagisa** [comment]
If your OS differs from the usual supported systems enough (which lack of pthreads seems to signify), you should make a custom target and port the libstd to your own system.

The whole point of libstd and libcore split is that libstd could be platform specific -- printing to stdout is implemented in a plenty platform specific manner for a reason. This is a conscious design decision. I doubt you will see anything done about this.

**Comment by dtolnay** [comment]
I tend to agree with @nagisa -- if anything, I would prefer to solve this by making it easier to port std to odd platforms. See [Refactoring std for ultimate portability](https://internals.rust-lang.org/t/refactoring-std-for-ultimate-portability/4301) for some ideas on that. Nevertheless if there is anything we can change about the current implementation of print and panic to improve your situation, I would welcome a PR or RFC (whichever is easier).
