### ISSUE TITLE
rose_tree-0.1.2 beta regression due to petgraph

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43677]
[rose_tree](https://crates.io/crates/rose_tree) version 0.1.2 regressed from stable to beta due to a compilation failure of [petgraph](https://crates.io/crates/petgraph) version 0.1.18 ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/rose_tree-0.1.2/log.txt)):

```
Aug 03 17:57:33.026 INFO kablam! error[E0034]: multiple applicable items in scope
Aug 03 17:57:33.026 INFO kablam!    --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/petgraph-0.1.18/src/graph.rs:404:17
Aug 03 17:57:33.026 INFO kablam!     |
Aug 03 17:57:33.026 INFO kablam! 404 |         assert!(Ix::max().index() == !0 || NodeIndex::end() != node_idx);
Aug 03 17:57:33.026 INFO kablam!     |                 ^^^^^^^ multiple `max` found
Aug 03 17:57:33.026 INFO kablam!     |
```

cc @mitchmindtree @bluss

**Comment by bluss** [comment]
petgraph 0.1.18 is broken since a breaking change in **Rust 1.6**.

Relevant error that breaks it since Rust 1.6, if we ignore the new error about max:

```
error: defaults for type parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions.
  --> src/graph.rs:77:6
   |
77 | impl<Ix: IndexType = DefIndex> NodeIndex<Ix>
   |      ^^
```

User crates should upgrade to petgraph 0.2 or 0.4, which have received recent updates. Preferably, 0.4.x, or whatever is the latest version at the time of upgrade.

When Rust has left a crate for broken, it should not be awoken again. petgraph 0.1 was broken.

**Comment by alexcrichton** [comment]
Thanks for the clarification @bluss! Sounds like this is expected, so closing.
