### ISSUE TITLE
The `Default` trait is not implemented for the `*mut T` type.

### ISSUE THREAD

**Issue by gtors** [rust-lang/rust#43722]
In my opinion, the default value should be `ptr::null_mut()`. Are there any reasons not implement this trait?

**Comment by Others** [comment]
I disagree with this. There is no reason to encourage the bad practice of using null pointers. It's better to leave this as-is.

**Comment by dtolnay** [comment]
Generally I prefer for code manipulating pointers to be explicit rather than implicit, so I think implementing `Default` would require some more motivation and discussion of the tradeoffs and alternatives. This would be a better fit for the [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md) process if anyone feels strongly enough to lead that.
