### ISSUE TITLE
Mis-calculated spans

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/rust#43796]
```
[00:33:43] ERROR:rustc_save_analysis::dump_visitor: Mis-calculated spans for path 'AsRef<U>::as_ref'. Found 1 spans, expected 2. Found spans:
[00:33:43] ERROR:rustc_save_analysis::dump_visitor:     'as_ref' in /checkout/src/libcore/convert.rs, line 355
```
This has been seen in a few different places, e.g.
 - https://travis-ci.org/rust-lang/rust/jobs/263196246 from https://github.com/rust-lang/rust/pull/43348
 - https://github.com/rust-lang/rust/pull/40939#issuecomment-311256737
 - https://github.com/rust-lang/rust/pull/40113#issuecomment-318702624

I don't think it actually causes build failures, but it seems suspicious and something that should be fixed. I'll use logobble to dig up some more tomorrowish.

**Comment by Mark-Simulacrum** [comment]
cc @nrc -- any ideas on what could be causing this?

**Comment by kennytm** [comment]
The problem is that `SpanUtils::spans_with_brackets` (called from `spans_for_path_segments`) does not handle UFCS path at all. It will ignore everything between angle brackets, so input like `<T as AsRef<U>>::as_ref` will only produce the span for `as_ref` (one segment).

However, the `ast::Path` of this will be `AsRef<U>::as_ref` (two segments), thus the mismatch error.

Thanks to #40369, each PathSegment already contain the span, so we shouldn't need to use `spans_for_path_segments` anymore.
