### ISSUE TITLE
E0621 not working for below example

### ISSUE THREAD

**Issue by gaurikholkar** [rust-lang/rust#43865]
```
fn foo<'a>(x: &i32) -> &'a i32 {
    x
}

fn main() { }
```
cc @nikomatsakis

**Comment by nikomatsakis** [comment]
The problem is that `'a` will be early bound because it does not appear in the arguments. This used to be represented as `ReFree`, but that has changed, and now `'a` would be represented as `ReEarlyBound`. Therefore, the helper `is_named_region()` ([the only callers are here](https://github.com/rust-lang/rust/blob/faf477a8c232d0442d16a4025f49d3ae1519131e/src/librustc/infer/error_reporting/named_anon_conflict.rs#L34)) will have to be changed to accommodate the `ReEarlyBound` case as well as `ReFree`. This will probably require changing various other helpers too.

**Comment by nikomatsakis** [comment]
Maybe we should move `is_named_region()` into `util.rs` just because it is very specific to this code. It's kind of dubious if others wind up using it.

**Comment by nikomatsakis** [comment]
One complication is that `is_suitable_region` extracts the scope in which a free region is bound from the `ReFree` variant. Doing that for `ReEarlyBound` is a bit different. There is this helper `early_free_extent()` that will *sort of* do what we want, but actually we don't want to use it because it does some other work afterwards too. I think we want `is_suitable_region` to do something like this (untested):

```rust

    // This method returns the DefId and the BoundRegion corresponding to the given region.
    pub fn is_suitable_region(&self, region: Region<'tcx>) -> Option<FreeRegionInfo> {
        // Find the def-id where this free region is bound. So, for
        // example, if we have something like `fn foo<'a>(x: &'a i32)`
        // where `'a` is early bound, then the binding def-id would be the
        // def-id of `foo`.
        let binding_scope_def_id = match *region {
            ty::ReFree(ref free_region) => free_region.scope,
            ty::ReEarlyBound(ref ebr) => self.tcx.parent_def_id(ebr.def_id),
            _ => return None, // not a free region
        };
        let node_id = self.tcx
                          .hir
                          .as_local_node_id(suitable_region_binding_scope)
                          .unwrap();
        let mut is_impl_item = false;
        match self.tcx.hir.find(node_id) {
            Some(hir_map::NodeItem(..)) |
            Some(hir_map::NodeTraitItem(..)) => {
                // Success -- proceed to return Some below
            }
            Some(hir_map::NodeImplItem(..)) => {
                is_impl_item = self.is_bound_region_in_impl_item(suitable_region_binding_scope);
            }
            _ => return None,
        }
        return Some(FreeRegionInfo {
            def_id: suitable_region_binding_scope,
            boundregion: free_region.bound_region,
            is_impl_item: is_impl_item,
        });
}
```

**Comment by nikomatsakis** [comment]
Note that in that code I kind of "normalized" early-bound-regions by synthesizing a `BoundRegion` for them (even though the actual data structure doesn't have one). I'd have to work through the rest of the code but it seems likely that doing such a normalization will make the rest somewhat simpler.

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?gist=4f2aa3b85171befb28264a69488ffeef&version=stable):

```
error[E0621]: explicit lifetime required in the type of `x`
 --> src/main.rs:2:5
  |
1 | fn foo<'a>(x: &i32) -> &'a i32 {
  |            - consider changing the type of `x` to `&'a i32`
2 |     x
  |     ^ lifetime `'a` required
```
