### ISSUE TITLE
Rustdoc should emit [src] link for "Implementors" section also for traits.

### ISSUE THREAD

**Issue by vi** [rust-lang/rust#43893]
It should work a bit like IDE's feature that finds everything that implements a given interface.

@QuietMisdreavus

**Comment by QuietMisdreavus** [comment]
This should be a fairly small change (the most annoying part has already been done) so i'll open this up as a mentored issue.

The bit that writes out the "Implementors" section is [at the bottom of the `item_trait` function](https://github.com/rust-lang/rust/blob/3c96d40d326b64f6a50f4a902051fe71c4acdc92/src/librustdoc/html/render.rs#L2485-L2506) in `src/librustdoc/html/render.rs`. This is where the known implementors for a given trait are pulled out of the global context and listed out onto the rendered page.

The bit that's responsible for creating `[src]` links is [the `src_href` method](https://github.com/rust-lang/rust/blob/3c96d40d326b64f6a50f4a902051fe71c4acdc92/src/librustdoc/html/render.rs#L1603), implemented on a local `Item` type. This kind of Item is easily made from the kind of Item that's otherwise worked on in `render.rs`, but there's a catch: The entries in the Implementors list aren't `clean::Item`s. They're `clean::Impl`s, which are only a subset of the things you get on an Item. This is the "most annoying part" i mentioned earlier.

Fortunately, i ran into this when creating the "Implementations on Foreign Types" section, so if you scroll up a little in `item_trait`, you can see [where i pulled out an Item for "foreign" impls](https://github.com/rust-lang/rust/blob/3c96d40d326b64f6a50f4a902051fe71c4acdc92/src/librustdoc/html/render.rs#L2466-L2479) so i could render the full impl block for them. The task for anyone who wants to take this on is to pull that up a little so that it's used for all the implementors, not just the foreign ones.

With a `clean::Item` in hand, combine it with the Context to create a `render::Item` and call `src_href` to generate the link. ([Here's an example doing that for associated methods.](https://github.com/rust-lang/rust/blob/3c96d40d326b64f6a50f4a902051fe71c4acdc92/src/librustdoc/html/render.rs#L3241-L3246) This also helpfully includes the extra HTML bits that will flush the `[src]` link to the right edge, which is really the final step.)

And... that's it! The link should *probably* go between the `fmt_impl_for_trait_page` and the where clause underneath it, so that it's aligned with the impl line and not the where clause. You may need to also close/open the `<code>` that's wrapping the whole line to make sure the `[src]` link itself isn't monospace.

If you have any questions, let me know! Either comment here, or hop onto IRC in `#rust-dev-tools`, or  the impl period Gitter under `WG-docs-rustdoc`.
