### ISSUE TITLE
reconsider magic `-A unused` for UI tests?

### ISSUE THREAD

**Issue by zackmdavis** [rust-lang/rust#43896]
I agree with [this reasoning](https://github.com/rust-lang/rust/blob/0374e6aab7ef60/src/tools/compiletest/src/runtest.rs#L1163-L1167) for compile-fail tests (for which composing and revising test-expectation comments can be laborious), but for UI tests (for which the expectation files are automatically generated, anyway), test authors have a reasonable expectation that the test output will be the same as when manually invoking `rustc` on the test file; discovering that this is not the case may be something of a rude surprise.

cc @alexcrichton

**Comment by petrochenkov** [comment]
>but for UI tests (for which the expectation files are automatically generated, anyway), test authors have a reasonable expectation that the test output will be the same as when manually invoking rustc on the test file

On the other hand, `unused` warnings in the UI test expectation file are still noise obscuring the actually tested expectations.
(Note, that all compile-fail tests are going to be UI-tested in hopefully near future.)

>discovering that this is not the case may be something of a rude surprise.

Documentation can solve this?

**Comment by Mark-Simulacrum** [comment]
I think there are significant downsides to this, and few gains; typically you check all UI test outputs when adding new tests or modifying old ones, so it seems rare that this comes up in practice.

I'm going to close this issue since it seems like we're unlikely to actually implement this; if we'd be interested then exploring avenues I listed above (compiler team meetings, or rfcbot poll) would be good.

**Comment by petrochenkov** [comment]
We need to disable `-A unused` for `// run-pass` tests though, which are also a part of UI tests now, but should not have dead code in general.

**Comment by Mark-Simulacrum** [comment]
I'll open a PR shortly doing that.
