### ISSUE TITLE
Implement std::borrow::Borrow<&str> for String

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#43940]
I strongly believe that rust should provide more interoperability between the `String` and the `&str` types, given the prevalence of the two types and interaction between them.

In particular, I think anywhere that you need to dereference a `&str` to do some `String` operation that can be avoided is not correct.

As one concrete such example, `String` should implement `std::borrow::Borrow<&str>` to make something like this work:

```rust
let hashmap = HashMap::<String, _>::new();
for key in ["foo", "bar"] {
    if hashmap.contains_key(key) {
        ...
    }
}
```

Currently this throws an error about `String` not implementing `borrow<&str>`:
```rust
error[E0277]: the trait bound `std::string::String: std::borrow::Borrow<&str>` is not satisfied
  --> src/main.rs:76:21
   |
76 |         if !hashmap.contains_key(key) {
   |                     ^^^^^^^^^^^^ the trait `std::borrow::Borrow<&str>` is not implemented for `std::string::String`
   |
   = help: the following implementations were found:
             <std::string::String as std::borrow::Borrow<str>>
```

Aside from the fact that compiler doesn't (directly) suggest dereferencing the &str, I don't believe it should be necessary to do so in the first place.

(obviously changing the test to `if !hashmap.contains_key(*key)` takes care of the error.)

Alternatively, could we automatically dereference `&foo` when a trait matching the dereferenced `foo` type is found and there is none for `foo`? That would automatically take care of an entire class of problems.

(Apologies if either the original suggestion or the alternative suggestion of auto-dereferencing to match `impl`'d traits are already in the system; I could not find them, but with the overwhelming number of issues in the this project makes it hard to be certain.)

**Comment by dtolnay** [comment]
I don't think `impl Borrow<&str> for String` would be a simple fix. That signature would need to take a `&String` and return a `&&str`. Those are both thin pointers that look like this:

```
                      String
+-------+        +--------------+
| input | -----> | data pointer |
+-------+        +--------------+
                 | capacity     |
                 +--------------+
                 | length       |
                 +--------------+

                       &str
+--------+       +--------------+
| output | ----> | data pointer |
+--------+       +--------------+
                 | length       |
                 +--------------+
```

The problem is there is no data pointer and length next to each other in the input for the output to borrow. We may be able to do a more invasive redesign of how String works to make this possible, but it isn't clear to me that we would be comfortable committing to a String layout just to make this cast possible. Failing that, the `contains_key` use case would need to be handled by auto-dereference behavior at the language level.

Either way I would prefer for this to go through the RFC process because there is design work to be done and tradeoffs to be discussed.
