### ISSUE TITLE
rustdoc: Does not list impls on type aliases

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#44182]
Happens with https://github.com/sdroege/gstreamer-rs/tree/52c013b8348ab3a98bb8475916aa306a3fc664de

If you check gstreamer/src/caps.rs, it has `impl Caps`, where `type Caps = GstRc<CapsRef>`. That one shows up in the rustdoc index (when searching), but neither on the `Caps` type alias docs, nor on the `GstRc` docs.

In gstreamer/src/buffer.rs there is `impl GstRc<BufferRef>`. That one shows up in the `GstRc` docs.

@GuillaumeGomez

**Comment by QuietMisdreavus** [comment]
That commit (nor the current `master`) does not contain an `impl Caps` block for rustdoc to pick up. It does have an `impl GstRc<CapsRef>`, which, when changed to `impl Caps` will properly show up on the Caps page, thanks to https://github.com/rust-lang/rust/pull/42027. It does, however remove it from the `GstRc` page. If this is desired, this has been fixed. Otherwise it can be folded into https://github.com/rust-lang/rust/issues/32077 since it would require more active work of substituting the full type when searching for impls.

**Comment by sdroege** [comment]
Having it only the the Caps page would be good enough for my taste. If it's on the GstRc page, there will be a lot of noise and it will be hard to find anything :)

**Comment by QuietMisdreavus** [comment]
Then I'll call this "fixed by https://github.com/rust-lang/rust/pull/42027". :grinning: If you change the impl blocks to point to the type alias instead of the expanded type, then render docs with a nightly compiler, the docs will show up the way you want them.

**Comment by sdroege** [comment]
Perfect, thanks :)
