### ISSUE TITLE
Tracking issue for HashMap `OccupiedEntry::{replace_key, replace_entry}`

### ISSUE THREAD

**Issue by Binero** [rust-lang/rust#44286]
At the moment the only way to replace a map entry with a new one, swallows the old key. In cases the user wants to keep the old key, the only way to do so is to first `remove_entry` and to then `insert` a new one. This requires two map look-ups. 

As the Entry API aims to make operations that would otherwise require two look-ups into operations that require only one, the replacing of an entry is an obvious hole in the API.

- [x] Implemented in #44278
- [x] Tweaked in #45152

**Comment by stepancheg** [comment]
While it is indeed a missing API, there are several issues with this new API implemented in PR #44278:

* it seems to panics if `take_key` was called before
* it replaces both key and value, so
* * is not possible to replace only key or only value
* * it does do completely independent things in one operation
* it is not possible to replace key in `VacantEntry`
* it takes `self`, while it could take `&mut self`, so replace could be called again if it is needed for some reason
* key replacement it is against least surprise principle

I think `HashMap::replace` should be different:

```
impl OccupiedEntry<...> {
    fn replace_value(&mut self, new_value: V) -> V {
        replace value with new value, do not touch the key.
    }
}
```

And probably that's it.

If we need to replace key for some reason, `replace_key` operation needs to be added to **both** `OccupiedEntry` and `VacantEntry`.

**Comment by Binero** [comment]
- `take_key` cannot be called before, all functions that call it consume the entry.
- The point is to be able to swap out the key without multiple lookups. `replace_value` beats the point.
- A `VacantEntry` does not have a key, so it's unclear how the function would work.

**Comment by stepancheg** [comment]
> take_key cannot be called before, all functions that call it consume the entry.

Oh, it is not public API, thanks.

> The point is to be able to swap out the key without multiple lookups. replace_value beats the point.

But this function does not allow to replace key without replacing value.

BTW, there's already a function to replace value, it's called insert.

So if we had `replace_key` instead of current `replace`, then current `replace` could be emulated as:

```
occupied_entry.insert(new_value);
occupied_entry.replace_key()
```

`replace_key` is not possible now, and `replace` is redundant if we had `replace_key`.

> A VacantEntry does not have a key, so it's unclear how the function would work.

Please ignore that.

**Comment by Binero** [comment]
I will take a look at `replace_key` when I have time, probably next week.

**Comment by Binero** [comment]
@stepancheg I think it's probably better to have `replace_key` consume the entry, because the semantics of the function would otherwise change after the first call.

**Comment by SimonSapin** [comment]
This has been in Nightly for long enough that I’m inclined to stabilize, but I don’t quite understand the use case. @Binero, can you explain some more why it can be important to recover the old key rather than the new one (passed to `HashMap::entry()` which hashes and compares equal?

**Comment by Binero** [comment]
@SimonSapin 

It is quite a niche function, so it's certainly not instantly obvious where this would be useful. 

That said, it has some uses when you want to for example lower the memory footprint of a HashMap by swapping out an identical `Rc<T>` with another, equivalent, `Rc<T>` that you are already using elsewhere. 

If either `T` or the `HashMap` is large enough, this could reduce the memory footprint of the application by quite a lot.

**Comment by joshlf** [comment]
Not sure if this was the original intent, but I have a use case for `replace_key` where I need the key back (by value) in certain failure conditions. I have code like:

```rust
match map.entry(key) {
    Entry::Occupied(entry) => 
        entry.into_mut().do_thing_which_can_fail.map_err(|_| entry.replace_key()),
    Entry::Vacant(entry) => ...,
}
```

Without `replace_key`, I'd need to do `map.entry(key.clone())` instead so that I could still have `key` around by value.

**Comment by jonhoo** [comment]
I may be off-base here, but I feel like there is a requirement for these methods that the key continue to have the same hash? If so, that should almost certainly be stated in the documentation.

**Comment by Amanieu** [comment]
That is correct.

**Comment by jonhoo** [comment]
Ah, reading it again, I guess the reason this is okay is because you can only get an `OccupiedEntry` in the first place if the provided key already hashes to the appropriate value. Not mentioning it in the docs seems fine then!

**Comment by KodrAus** [comment]
It's not super easy to spot from this issue alone, but the `replace_key` method is incompatible with another unstable `Entry::insert` method. See: https://github.com/rust-lang/rust/issues/65225#issuecomment-571584668

**Comment by glaebhoerl** [comment]
I just happened upon a use case for this feature while generalizing the code linked [here](https://twitter.com/glaebhoerl/status/1287731327857557505) to arbitrary key types. Basically, it's a hash table with support for scoping and shadowing, and if a newly inserted key shadows an existing one, the old key and value are put into a separate `Vec`, and when the shadowing scope is popped, they are inserted back into the map. But `insert()` only gets one copy of the key as input, and that key can't simultaneously exist in two places: in the `HashMap` with the newly inserted value, and in the `Vec` alongside the previous/shadowed one. So in the case where the key already exists in the map, I need to be able to get the old value *and* the old key back out so I can put both of them into the `Vec`.

**Comment by joshlf** [comment]
Would somebody mind providing a short status update on what's left before stabilization?

**Comment by qm3ster** [comment]
Maybe it should at least return `(K, &mut V)`, since it will consume the entry? (Which it has to, in order to return the key.)

My ideal API would be:
```rust
impl OccupiedEntry {
    fn swap_keys(&mut self)
    // +
    fn into_key(self) -> K
}
```
It allows the most flexibility and I don't see an immediate drawback.
The latter can also be substituted for 
```rust
fn into_inner(self) -> (K, &mut V)
```
Which is a little less ergonomic since we could already get that `&mut` with the `HashMap`'s lifetime.

Basically, I really want *my* `K` back :)

**Comment by cuviper** [comment]
These methods will currently `unwrap`-panic if the `OccupiedEntry` was created by `VacantEntry::insert_entry` or a vacant `Entry::insert_entry`, both of which will be stable in Rust 1.59. In this case we no longer have a key because it was used for the new insertion.

**Comment by qm3ster** [comment]
This is actually really wild.
It looks like `OccupiedEntry.key` has always been an `Option<K>`, but it was always constructed as a `Some(key)` and `unwrap`ed everywhere.
Was `entry_insert` planned from the initial commit of `hashbrown`?

**Comment by Amanieu** [comment]
I think we should remove this feature because it requires `OccupiedEntry` to hold the key that was used when searching for the entry. This conflicts with other was that `OccupiedEntry` can be used, such as the `insert_entry` API which allows converting a `VacantEntry` to an `OccupiedEntry` by inserting a value.

While there are valid use cases for modifying the key of an existing entry in a `HashMap`, these use cases usually involve the key type holding additional data in addition to the key itself and are better addressed by using the [`HashTable`](https://docs.rs/hashbrown/latest/hashbrown/struct.HashTable.html) API in hashbrown instead.

@rfcbot fcp close

**Comment by 71** [comment]
Note for anyone hit by the removal of these functions: the same result can be achieved with [`raw_entry_mut()`](https://doc.rust-lang.org/stable/std/collections/hash_map/struct.HashMap.html#method.raw_entry_mut) and [`insert_key()`](https://doc.rust-lang.org/stable/std/collections/hash_map/struct.RawOccupiedEntryMut.html#method.insert_key):

```rust
match map.raw_entry_mut().from_key(&key) {
    hash_map::RawEntryMut::Occupied(mut occupied) => occupied.insert_key(key),
    hash_map::RawEntryMut::Vacant(_) => {}
}
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4dbc14658bb4a3958792d697f37f5b9b).

**Comment by Amanieu** [comment]
The raw entry API is also slated for removal. Can you have a look at hashbrown's `entry_ref` API instead to see if it solves your use cases? That is important information as to whether it's worth upstreaming to the standard library.

**Comment by 71** [comment]
@Amanieu Oh, I wasn't aware. In my particular case I also make use of other more "exotic" features of raw entries (supplying hashes, custom comparison functions), so I will likely need to go for `hashbrown` anyway. I don't think `entry_ref` would have helped me either because `Borrow<Q>` doesn't seem to apply to my case (I don't have `&Q`, I have `impl Deref<Target = Q>`), although I could see `entry_ref` being useful to others who have less "exotic" keys.

**Comment by constituent** [comment]
@Amanieu hashbrown's `entry_ref` API is itself very useful. Usually with a `HashMap<String, T>`, I'd like to entry it with `&str`, only `to_owned()` while necessary.
However, `replace_key` is another unrelated ergonomic tool IMHO. If it has to be removed due to implementation reasons, a similar API of maybe `HashMap` would be much appreciated.

**Comment by Amanieu** [comment]
@constituent If you need to mess with keys in ways where "equivalent" keys actually carry additional data then the correct tool to use is hashbrown's `HashTable` type which gives you all the low-level control you need. However this is not planned for inclusion in the standard library at this time: if you need it then you should use it from the hashbrown crate.
