### ISSUE TITLE
missing_debug_implementations misses structs exported from other crates

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#44304]
For example, `std::str::SplitWhitespace` does not have a debug implementation (see: PR #44303), but the lint didn't trigger. I'd consider this a bug; if there isn't a debug implementation for an exported struct, the user should have to put `allow(missing_debug_implementations)` to suppress it if they can't fix it themself.

This probably applies to `missing_docs` too.

**Comment by Enselic** [comment]
Triage: As far as I know, it is a widely accepted policy to not lint on code that does not belong to the compiled crate, since the code in dependencies can't be changed (without significant effort like forking or contributing a fix). So I'll go ahead and close this as won't fix. If you still want to try to change this I would recommend going the RFC route.
