### ISSUE TITLE
Path & PathBuf missing FromStr trait

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#44431]
Both `std::path::Path` and `std::path::PathBuf` implement `std::convert::From<String>` but neither one implements the `std::str::FromStr` trait. Since both `Path` and `PathBuf` have infallible conversions from string types, they should implement `std::str::FromStr` (esp. so that they can be used as generic "convertible from str" types).

Note that if something is done about rust-lang/rfcs#2143, this would be a moot discussion.

**Comment by kennytm** [comment]
Note that, as discovered from #48292, it is impossible to implement `FromStr` for `Path` (requires unsized return value) nor `&'a Path` (requires GATs).

**Comment by SimonSapin** [comment]
@rust-lang/libs, do we want to revert this addition https://github.com/rust-lang/rust/pull/48292 until we can add it back again with `!` for the error type? https://github.com/rust-lang/rust/pull/49039, https://github.com/rust-lang/rust/pull/50121

**Comment by alexcrichton** [comment]
I'd be ok landing with a custom error type personally, still.

**Comment by scottmcm** [comment]
If this lands with a different custom type from `string::ParseError`, I suspect it wouldn't be able to be changed to `!` later because of coherence.  Would it be crazy to have it use `string::ParseError` as the we-don't-have-`!`-yet uninhabited error type, so that could potentially become `!` later?

**Comment by mqudsi** [comment]
I would be for anything that lets us commit to switching it over to `!` when that becomes available. Perhaps we should have a global `this_will_be_bang` error type...

**Comment by mitsuhiko** [comment]
Is there a specific reason this could not use `string::ParseError`? This would be really nice to have and it seems like `!` stabilization is quite far off.

**Comment by SimonSapin** [comment]
Sounds ok to me. `std::string::ParseError` is already stable (used in another `FromStr` impl) and we’ll need to deal with it somehow anyway, when we figure out the never type situation. @rust-lang/libs, any thoughts?

**Comment by alexcrichton** [comment]
Seems reasonable to me!

**Comment by SimonSapin** [comment]
Implemented in https://github.com/rust-lang/rust/pull/55148 with FCP for insta-stable impl.

**Comment by SimonSapin** [comment]
Yeah I forgot to update the `since` attribute when unreverting in https://github.com/rust-lang/rust/pull/55148. Based on the merge date it should be 1.32. Do you want to send a PR to fix it?

`Path` cannot implement `From` or `FromStr` directly since their methods return an owned value, but `Path` is dynamically-sized and so can only be used behind a pointer indirection.

Closing since I think there is nothing else to do here, but feel free to reopen or comment if this is not the case.
