### ISSUE TITLE
Tracking issue for existential types (RFC 2071)

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/rust#44685]
This is the tracking issue for existential types, a part of rust-lang/rfcs#2071

Blocking stabilization:

- [ ] Implement
- [ ] Document
- [ ] Decide final syntax

**Comment by nikomatsakis** [comment]
I am closing this as a duplicate of https://github.com/rust-lang/rust/issues/34511

**Comment by Tyler-Hardin** [comment]
I don't see a mention of anything like this in the referenced duplicate. It might be good to add it to the todo list there if this is going to be closed as a dup. (I would do it myself, but I barely grasp the RFC, and even then only in the specific context in which it would be useful to me.)

**Comment by Ekleog** [comment]
@aturon This tracking issue having been closed in favor of https://github.com/rust-lang/rust/issues/34511, would it be possible to update the checklist up there with tracking information for this feature, so that it's easy to figure out whether this part of https://github.com/rust-lang/rfcs/issues/2071 has been implemented, is still under debate, is pending stabilisation, etc.? :)

**Comment by jethrogb** [comment]
I think the relevant issue is https://github.com/rust-lang/rust/issues/63063
