### ISSUE TITLE
PartialEq for str and CStr

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#44738]
>  the trait `std::cmp::PartialEq<str>` is not implemented for `std::ffi::CStr`

I'm surprised that there is no implementation. I'd like to check `CStr::from_ptr(p) == "foo"`. It seems that this comparison could be done. If `CStr` is non-UTF-8, then it simply won't match.

I'm happy to make a PR if that's a sensible impl to add.

**Comment by retep998** [comment]
What if the C string is in some non-UTF8 encoding but the bytes happen to be identical to a UTF-8 string?

**Comment by pornel** [comment]
Good point.

**Comment by axos88** [comment]
@retep998 @kornelski, in that case CStr::to_str() would return a UTF-8 string as well, which would compare. 
There isn't really a way to "know" the semantic data that a binary blob is describing that comes from C, so they should be treated as equal - same way that .to_str() will convert the binary blob to a utf-8 string. It is up to the programmer to "annotate" and correctly use the incoming data since the type system cannot lend a hand in this case.
