### ISSUE TITLE
Tracking issue for `entry_and_modify`

### ISSUE THREAD

**Issue by mchlrhw** [rust-lang/rust#44733]
Tracking issue for the `and_modify` method on hash map `Entry`s (added in https://github.com/rust-lang/rust/pull/44734).

**Comment by mchlrhw** [comment]
The scope of this has change to include the `BTreeMap` as well as `HashMap` on the advice of @kennytm.

**Comment by hedgehog1024** [comment]
Just wonder, is there any particular reason to keep this feature unstable? I personally find it pretty usable and convenient and it doesn't look like something that can break an invariant

**Comment by kennytm** [comment]
@hedgehog1024 The only reason these are kept unstable is because no one pushed for stabilization. Everyone is welcome to submit a PR to stabilize a library feature 😊.

1. Ensure the documentations, examples and implementations are correct. Ensure no missing edge cases. Ensure necessary tests are present.
2. Change all `#[unstable]` attributes related to that feature to `#[stable]`.
3. Submit the PR.
4. Wait for team consensus.
5. Profit!

**Comment by hedgehog1024** [comment]
@kennytm Does such a PR need to remove the information about this feature from Unstable Book?

**Comment by kennytm** [comment]
@hedgehog1024 Yes. Those information should be moved into the documentation of the functions.

**Comment by mchlrhw** [comment]
@hedgehog1024 Thanks for your support of this feature, much appreciated :smile:

**Comment by Jarngreipr** [comment]
I see this feature has been stabilised.
Should it now be available for use on stable?

I get the following error on rustc 1.25:
```
error[E0658]: use of unstable library feature 'entry_and_modify' (see issue #44733)
   --> src/models/mod.rs:155:34
    |
155 |                                 .and_modify(|&mut tup| {tup.1 = idx}) ;
    |                                  ^^^^^^^^^^

```

**Comment by mchlrhw** [comment]
I think it's due in 1.27

**Comment by mchlrhw** [comment]
Scratch that. I just looked on the stabilisation PR and it's slated for 1.26. Even better! 😁
