### ISSUE TITLE
Better error message for "[E0601]: main function not found"

### ISSUE THREAD

**Issue by djc** [rust-lang/rust#44798]
I'm seeing this in a crate with multiple binaries defined, so one important improvement would be to name the binary that is causing the problem. Once I've figured why this error is happening incorrectly in the particular crate that I'm struggling with now, I'll probably have more suggestions.

**Comment by estebank** [comment]
Proposed outputs:

- Regular
```
error[E0601]: main function not found
 --> file.rs
```
- Oneline
```
file.rs - error[E0601]: main function not found
```

**Comment by ehuss** [comment]
This has come up before, see rust-lang/cargo#4948

**Comment by djc** [comment]
@ehuss thanks for working on this! The changes in your PR already look this, but I don't think they fully cover the particular case I'm talking about here ("crate with multiple binaries defined") too well (that is, a crate that has a `bin` directory containing multiple `.rs` files). Am I missing something?

**Comment by ehuss** [comment]
@djc it should work, unless I am misunderstanding your situation.  From the terminology I've seen, each bin is considered a separate "crate", and a *package* can have multiple binary crates (rust-lang/cargo#3380).  So for a package layout like this:

```
foo/Cargo.toml
foo/src/lib.rs
foo/main.rs
foo/bin/bin1.rs
foo/examples/ex1.rs
```

The corresponding errors for the three binaries would be:
* `main function not found in crate foo`
* `main function not found in crate bin1`
* `main function not found in crate ex1`

There might be confusion (such as if you have examples with the same name as a binary, or binaries with the same name in separate packages within a workspace).  That's why I proposed in the PR to add the exact path to the recommended source file where you should add a main function, but I have not heard back.

**Comment by djc** [comment]
@ehuss, ah, awesome! In this case, I find the wording of "not found in crate" maybe a little confusion, because as far as I understand it, the intention of "crate" is usually to cover the whole thing rather than a single binary included in it.
