### ISSUE TITLE
Off-by-one in println! diagnostic

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#44954]
This program:

```rust
fn main() {
    let name = "foo";
    
    println!("{} {}", name);
}
```

Gives this error:

```text
error: invalid reference to argument `1` (there is 1 argument)
```

Both things having 1 here is confusing, it'd be nicer if we didn't compare a zero-indexed and a one-indexed number.

Additionally, a note could make this easier to understand overall too.

**Comment by estebank** [comment]
### Mentoring instructions

Modify [`verify_arg_type`](https://github.com/rust-lang/rust/blob/185cc5f26d2c8a794189b028b43f6a3b8fc586db/src/libsyntax_ext/format.rs#L266-L268) to instead of outputting positional argument errors, to keep track of them (bubbling them up to the callee of `verify_piece`) so that the following cases are handled:

 - `println!("{} {} {}", name);`: All arguments are positional, estate the difference clearly:
`error: 3 positional arguments in format string, while only 1 was supplied`
 - `println!("{} {value} {}", name, value=2);`  There're named arguments in the string, keep current output:
`error: invalid reference to positional argument `3` (there are 3 arguments)`
- `println!("{name} {value} {} {} {} {} {}", 0, name=1, value=2);` There are multiple missing arguments, make a list and present only one diagnostic:
`error: invalid reference to positional arguments `4` and `5` (there are 3 arguments)`

The following case are already handled in other parts of the code:
 - `println!("{}", name, surname);`

**Comment by BrunoWilkinson** [comment]
Hi,

I was wondering if this PR is still ongoing? I've started learning Rust and I was wondering if you think I can tackle this, I'm very curious and driven to learn more about the language and also how programming languages are built. 

Thank you for your feedback.

**Comment by estebank** [comment]
@BrunoWilkinson go ahead! People are available at https://gitter.im/rust-impl-period/WG-compiler-errors and on IRC for quick questions as well as on this issue for longer questions. Once you create a PR we can continue the conversation there. There are [instructions to build the compiler](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#building), and if you want to use debug statements, you can use `RUST_LOG=debug ./path/to/rustc file.rs` and `debug!()` statements in the code will be printed out to `stderr`.

**Comment by BrunoWilkinson** [comment]
@estebank thank you, I'm gonna check all this out and give it a shot!

**Comment by bagedevimo** [comment]
Hey @BrunoWilkinson - are you still looking at this? If not, I'd like to have a go.

**Comment by BrunoWilkinson** [comment]
Hey @bagedevimo, currently no I couldn't find the time to tackle the issue, In parallel, I'm still learning Rust. But I would love to see the solution to this issue like I did spend some time on it.

**Comment by tommyip** [comment]
Hey @bagedevimo are you working on this?

**Comment by bagedevimo** [comment]
Yeah, but not having much luck. If you're super keen and beat me to it, I
won't be upset. :)

**Comment by tommyip** [comment]
Currently
```rust
let name = "foo";
println!("{} {value} {}", name, value=2);
```
produces the output `foo 2 2`, is this the intended behavior and do we want to change it?

**Comment by estebank** [comment]
@tommyip I believe that is expected behavior, let's keep it and handle the other cases laid down in the mentoring instructions.
