### ISSUE TITLE
The “use of unstable library feature 'rustc_private'” error is very repetitive

### ISSUE THREAD

**Issue by JakubAdamWieczorek** [rust-lang/rust#44953]
`rustc 1.22.0-nightly (0e6f4cf51 2017-09-27)`

Compiling this:
```rust
#[macro_use] extern crate log;

pub fn main() {
    info!("This is a log message.");
}
```

while not including `log` as a dependency in `Cargo.toml`, produces the following output:
```
error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:1:14
  |
1 | #[macro_use] extern crate log;
  |              ^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: aborting due to 10 previous errors
```

**Comment by estebank** [comment]
### Mentoring instructions

Modify [`leveled_feature_err`](https://github.com/rust-lang/rust/blob/185cc5f26d2c8a794189b028b43f6a3b8fc586db/src/libsyntax/feature_gate.rs#L1073) to accept an extra flag stating wether the `help` should be outputted or not (it's already checking wether the current compiler is nightly) so that [`TyCtxt::stability`](https://github.com/rust-lang/rust/blob/185cc5f26d2c8a794189b028b43f6a3b8fc586db/src/librustc/middle/stability.rs#L511) can keep track of wether a diagnostic of this type has already been emitted, and if it has, the help isn't shown.

**Comment by zackmdavis** [comment]
> so that TyCtxt::stability can keep track of wether a diagnostic of this type has already been emitted

But `TyCxt` has access to the `Session`, which means we should be able to use the [existing `one_time_diagnostics` field](https://github.com/rust-lang/rust/blob/354eb160e07/src/librustc/session/mod.rs#L78-L81) (if we slightly generalize it to take an `Option<LintId>` rather than a `LintId` to accomodate non-lint errors like the matter at hand).

However, the reported code isn't reproducing the issue for me with a stage 1 compiler, perhaps hinting at something more subtle going on with this report.

**Comment by virgil-palanciuc** [comment]
That actually works and is a pretty elegant/quick fix. The only caveat is that you shouldn't pass the span in the tuple... i'm guessing, it messes up the hashcode, and the error ends up being different each time. I can't yet figure out why (complete newbie to the codebase) - so if you want to take up this issue & fix it, please feel free to do so, it'll take me a little while (I'm slow/don't have much time available to work on it :) ).

**Comment by virgil-palanciuc** [comment]
Update - i had some time to inspect it. Basically, the error is reported in two places. Here:
```
1 | #[macro_use] extern crate log
  |              ^^^^^^^^^^^^^^^^^
```
and here:
```
 4 |     info!("This is a log message.");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 ```

The second one is the one that is reported many times - and the primary span seems to be different each time (which is why if you include the span in the "key", it sees the messages as different and emits them all). I'm planning to go from the primary span to file/line/column string, and include that in the message - basically, the key for `one_time_diagnostics` would be `(None, None, modified_message)` instead of `(None, Some(span), message)`; this way, we would preserve the first two error messages, but remove the subsequent ones. Still feels a bit hackish, but I don't have a better idea.

**Comment by zackmdavis** [comment]
> the primary span seems to be different each time

But they _look_ like they're all pointing to the same code-snippet; what could be making them different? It looks like [`Span`s have a mysterious `ctxt` field](https://github.com/rust-lang/rust/blob/fbc3642ef/src/libsyntax_pos/lib.rs#L70-L76); if that's it, I'd rather manipulate that before setting/getting the `one_time_diagnostics` entry than pollute the error message string itself with file-position data.

**Comment by virgil-palanciuc** [comment]
So, I printed the location from the span - most of the "repeated" ones are within the macros, e.g.
```
    Loc {
        file: FileMap(<log macros>),
        line: 5,
        col: CharPos(
            36
        )
    }
)
```

I'm _pretty sure_ I need to invoke EmitterWritter::fix_multispan_in_std_macros() on the primary span, in order to retrieve the true location (main.rs, line 4) - only problem is, that method is private. And now it's late :)

I have another idea, I'll try it tomorrow  - anyway, this looks to be genuinely trickier than it first appeared to be

**Comment by virgil-palanciuc** [comment]
Ok guys, I've created PR https://github.com/rust-lang/rust/pull/45540 - let me know if you think it's a reasonable solution.

**Comment by kennytm** [comment]
#45540 did not contain the UI test to verify correctness. @virgil-palanciuc could you (or anybody interested) submit another PR to add the test? Sorry for the inconvenience.

**Comment by virgil-palanciuc** [comment]
Just to clarify: the request is that I add a test in `src/test/ui` that validates this issue is fixed (so that we can't have regressions in the future)?

If yes - sure, I'll add it, sorry for not adding it from the start, I'm new to this project :).

**Comment by estebank** [comment]
@virgil-palanciuc that is exactly right :)

**Comment by virgil-palanciuc** [comment]
I added the test with PR https://github.com/rust-lang/rust/pull/45635 ... but, at least on my local build, it seems that the compilation error changed in the meanwhile? (I get a much-more reduced version of it). Not sure why/ if I changed something in the build environment, or the code changed due to other PRs, in `main`. If the build fails in the PR, I'll need to re-evaluate how to produce a different testcase that still exposes the issue (if it's possible, at at all - I'll may need help on that).

(FWIW, that's  why I thought that a test won't be needed for this fix -  error output tends to change in time, making such tests a bit fragile)

**Comment by virgil-palanciuc** [comment]
So it wasn't just a thing on my build environment - the error is now simply `E0463 can't find crate for log`. need to figure out a different test, but it'll probably take me a few days.

**Comment by JakubAdamWieczorek** [comment]
@virgil-palanciuc, in my opinion the way to go would be to write a [complete full-deps test](https://github.com/rust-lang/rust/tree/master/src/test/ui-fulldeps), so as not to rely on the `log` crate's `rustc_private` attribute. Essentially, have an auxiliary crate with the `rustc_private` configuration attribute (see [here](https://github.com/rust-lang-nursery/log/blob/b8d931bf887e25a1bfc7c484de61ad14dbd10b56/src/lib.rs#L266)) and a test that tries to use it without a `#[feature(rustc_private)]` attribute. But someone else should also comment if that sounds sensible.
