### ISSUE TITLE
dylib for target -musl

### ISSUE THREAD

**Issue by pashinin** [rust-lang/rust#44991]
As it was said here https://github.com/rust-lang/rust/issues/34987, we should have support for targets that use a dynamic musl (like alpine linux) in nightly rust.

I want to build .so file to use on Alpine (musl).
```
[lib]
crate-type = ["dylib"]   # with staticlib it compiles OK
```
```
cargo build --target=x86_64-unknown-linux-musl --release --manifest-path ./Cargo.toml
error: cannot produce dylib for ... as the target `x86_64-unknown-linux-musl` does not support these crate types
```

```
rustc -V
rustc 1.22.0-nightly (f1b5225e8 2017-10-01)
```

**Comment by aidanhs** [comment]
Can you try passing `-C target-feature=-crt-static`? See second subpoint of point 5 of https://github.com/rust-lang/rust/pull/40113#issuecomment-323193341

**Comment by pashinin** [comment]
Magic, thank you. But I thought `rustc` or `cargo` will set what it needs to be able to compile.

**Comment by aidanhs** [comment]
There are still some rough edges with dynamic musl - it's essentially a tier 3 platform and there are possible issues with backwards compatibility (since it's historically unconditionally meant static linking).

That said, I'd (cautiously) say that I see no reason why a dylib can't default to dynamic linking given it just errors out at the moment - we'd welcome a PR to start a discussion about it!

**Comment by brucify** [comment]
For me, adding this to `.cargo/config` made `dylib` work for `x86_64-unknown-linux-musl`

```toml
# Cargo.toml

[lib]
crate-type = ["dylib"]
```

```toml
# .cargo/config

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "target-feature=-crt-static",
]
```
Then this worked
```bash
cargo build --target=x86_64-unknown-linux-musl
```
