### ISSUE TITLE
Emit `nounwind` LLVM attribute with `-C panic=abort`

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#44992]
Currently whenever you compile with `-C panic=abort` we will omit `invoke` instructions and the `uwtable` LLVM function attribute, but we should *also* set the `nounwind` attribute. It looks like on ARM this forces the object file to *not* reference functions that otherwise a function missing the `nounwind` attribute will not have.

This should help out remove some weird hacks for embedded work!

cc @japaric

**Comment by rkruppe** [comment]
Just for the record: in #45029 @sunfishcode brought up the possibility of other languages unwinding through Rust code. IIUC this could theoretically work if the Rust code contains no landing pads, though I believe that it is and should be UB instead. Still, I find it interesting that *if* we wanted to support that, the change proposed here would break that (b/c any unwinding would now be UB, rather than passing through the landing-pad-free code harmlessly).

**Comment by alexcrichton** [comment]
@rkruppe that seems like support for that would be opt-in, if ever?

**Comment by rkruppe** [comment]
Mayyyyybe? I don't think this is likely to happen regardless of the details. I mostly wanted to record the thought somewhere.

**Comment by retep998** [comment]
There are currently platforms where Rust and C++ can unwind through each other and landing pads will function correctly (such as windows msvc). I don't understand why anyone would want to support unwinding between Rust and other languages when `-C panic=abort` is specified, considering the whole point of `-C panic=abort` is that no unwinding occurs.
