### ISSUE TITLE
compiletest: Test execution time-stamping should take into account debugger pretty printers.

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#45022]
Modifying one of the pretty-printer python files in [src/etc](https://github.com/rust-lang/rust/tree/master/src/etc) does "un-ignore" debuginfo tests. The relevant files should be added to the list of inputs in `compiletest::up_to_date()`:

https://github.com/rust-lang/rust/blob/fd8099f0ecc2fd3980469ec45cf834ae9a941ca3/src/tools/compiletest/src/main.rs#L491-L507

Bonus points for exiting from that function immediately when finding something out-of-date.

**Comment by k0pernicus** [comment]
Maybe I can help here as a first contribution to the programming language.
I will try to propose a solution for tomorrow evening.

**Comment by k0pernicus** [comment]
So, I have read the code and I tried to understand where is the problem, and what kind of solution I can propose.

This is my thought:
1. The problem is pretty-printer Python files in `src/etc` are not considered in `up_to_date`; so, if you modified one of those files, you will not ignoring them (am I right?).
2. You propose to add the relevant files (`debugger_pretty_printers_common.py`, `gdb_load_rust_pretty_printers.py`, and `gdb_rust_pretty_printers.py` I think) as inputs of `up_to_date`, in order to consider them as "important files to not ignore" (am I right?).
3. In order to include the pretty printer files, I have to include them in `TestPaths`, right?

Thanks for those responses.

**Comment by michaelwoerister** [comment]
@k0pernicus You're on the right track:
1. Almost right. When the `compiletest` tool executes a test and that test passes, it will not re-execute it until something relevant has changed. "Not re-executing" in practice means that the test will show up as `ignored` in the commandline output. The problem here is that modifications to the pretty printer files are not picked up as "relevant changes". As a consequence the tests stay "ignored" even though they should actually be re-run because the changes to the pretty printer scripts can influence their result.
2. Correct. `inputs` is a list of all things that must not have changed since the last test execution if that test is to stay `ignored`. If any file from `inputs` has a modification time that is newer than the last test execution, the test has to be re-executed.
3. Not quite. `TestPaths` contains the location of the test that is being executed. What we want here is to just directly add the pretty-printer script paths to the `inputs` list. Something like
```rust
let rust_src_dir = ...; 
inputs.push(rust_src_dir.join("src/etc/debugger_pretty_printers_common.py"));
inputs.push(rust_src_dir.join("src/etc/gdb_load_rust_pretty_printers.py"));
...
```
Unfortunately the `rust_src_dir` is not readily available. But you could move the `runtest::TestCx::find_rust_src_root()` to `common::Config` and then use that for finding it.

**Comment by k0pernicus** [comment]
Ok, I understand.
Thanks a lot for these explanations.

I will work on that issue after work, in order to submit a PR + code review for tomorrow morning.

**Comment by k0pernicus** [comment]
@michaelwoerister I just created the PR to share the code.
I compiled the project and I ran the test (using `./x.py test`), and the compilation is OK.
Unfortunately, I don't know how to test my changes (which is why I put a "WiP")...

Is it possible to obtain a simple example of "procedure" to test my changes please?
Thanks a lot.

**Comment by michaelwoerister** [comment]
Implemented in https://github.com/rust-lang/rust/pull/45051.
