### ISSUE TITLE
Error span is in incorrect place due to Unicode fullwidth characters

### ISSUE THREAD

**Issue by hcpl** [rust-lang/rust#45211]
```sh
$ rustc +nightly --version
rustc 1.22.0-nightly (d6d711dd8 2017-10-10)
$ uname -sri
Linux 4.2.0-42-generic x86_64
```
Code:
```rust
fn main() {
    let _ = ("こんにちは", 100i40);
}
```
rustc output:
```
error: invalid width `40` for integer literal
 --> main.rs:2:23
  |
2 |     let _ = ("こんにちは", 100i40);
  |                       ^^^^^^
  |
  = help: valid widths are 8, 16, 32, 64 and 128

error: aborting due to previous error
```

**Comment by hcpl** [comment]
GitHub renders fullwidth characters with width less than 2 monospace cells - the span actually starts under the last string char and ends under the 1 digit.

**Comment by zackmdavis** [comment]
possibly related to #44080?

**Comment by hcpl** [comment]
@zackmdavis yeah, totally. Also it's revealed in #8706 that this is likely the same issue which dates back to August 2013.

Should I close it to decrease the noise/signal ratio or keep it to tell maintainers that this issue is persistent?

**Comment by estebank** [comment]
Just want to point out that the RLS, which is being distributed with the compiler, transitively depends on `unicode-width` due to a dependency on `clap`. I don't remember now if there was decision on avoiding depending on the external `unicode-*` crates that would allow the compiler to properly account for this. I _think_ part of the discussions predates building `rustc` with cargo. @alexcrichton, if we don't mind adding that dependency, we can use the existing PRs previously fixing this to solve this once and for all. Thoughts?

**Comment by alexcrichton** [comment]
Oh certainly, adding a dependency on `unicode-width` would be totally ok!
