### ISSUE TITLE
binaries built in debug mode want to import __CxxFrameHandler3 

### ISSUE THREAD

**Issue by Trolldemorted** [rust-lang/rust#45492]
I am building windows kernel drivers with rust (`no_std` and no libc), and debug builds fail because the linker can't find `__CxxFrameHandler3` in the kernel libraries (which makes sense).

However, when building with --release the function apparently is optimized out, and linking is successfull.

My target.json:
```
{
  "_": "Inspired by https://github.com/ryanbreen/breenix/blob/master/x86_64-unknown-none-gnu.json",
  "_note": "`is_like_mcvc` works since #32823, nightly 2016-04-12",
  "_note": "`data-layout` became mandatory since rust-lang/rust#32939, nightly 2016-04-20",

  "llvm-target": "x86_64-pc-windows-msvc",
  "target-endian": "little",
  "target-pointer-width": "64",
  "target-c-int-width": "32",
  "linker-flavor": "msvc",
  "data-layout": "e-m:w-i64:64-f80:128-n8:16:32:64-S128",

  "cpu": "x86-64",
  "features": "-mmx,-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2,-3dnow,-3dnowa,-avx,-avx2,+soft-float",

  "arch": "x86_64",
  "vendor": "pc",
  "os": "windows",
  "env": "msvc",

  "executables": true,
  "dynamic-linking": true,

  "is-like-windows": true,
  "is-like-msvc": true,

  "dll-prefix": "",
  "dll-suffix": ".sys",
  "exe-prefix": "",
  "exe-suffix": ".exe",
  "staticlib-prefix": "lib",
  "staticlib-suffix": ".lib",

  "no-default-libraries":     true,
  "no-compiler-rt":           true,
  "has-rpath":                false,

  "function-sections": true,
  "has-elf-tls":              false,
  "disable-redzone":          true,
  "custom-unwind-resume":     false,
  "eliminate-frame-pointer":  false,
  "position-independent-executables": false,

  "code-model":              "kernel",
  "relocation-model":        "dynamic-no-pic",

  "pre-link-args": ["/NOLOGO", "/NODEFAULTLIB", "/SUBSYSTEM:NATIVE", "/DRIVER", "/RELEASE", "/NXCOMPAT", "/DYNAMICBASE",
    "/INCREMENTAL:NO", "/MANIFEST:NO"],

  "post-link-args": ["/OPT:REF,ICF", "ntoskrnl.lib", "hal.lib",
    "/noimplib", "/ENTRY:DriverEntry", "/DEF:exports.def", "/MERGE:.edata=.rdata", "/MERGE:.rustc=.data"],

  "_end" : false
}
```

Maybe related: #38641

**Comment by alexcrichton** [comment]
Fascinating! Out of curiosity, are you compiling with panic=abort or panic=unwind?

**Comment by Trolldemorted** [comment]
Neither nor, i just added

```
#[lang = "eh_personality"] extern fn eh_personality() {}
#[lang = "panic_fmt"] extern fn panic_fmt() -> ! { loop {} }
```

for now.

**Comment by alexcrichton** [comment]
Ah thanks for testing!

Yeah this is being referenced because of `panic = "unwind"` referencing panicking machinery (which references this function on MSVC). If it works now I think that's intended behavior so let's close, but we could certainly of course document this better :)

**Comment by Trolldemorted** [comment]
Imho this is not a documentation issue, but a rustc one: If we build a `no_std` crate without `panic = "abort"`, the compiler should print a meaningful error message stating that this is impossible.

**Comment by alexcrichton** [comment]
Perhaps yeah! It's technically not *impossible* but certainly quite hard to get working

**Comment by Trolldemorted** [comment]
It would indeed be nice to get it working, but until it does I really recommend a decisive error message.

Should I create a seperate issue for that?

**Comment by alexcrichton** [comment]
Sure!

**Comment by mauricekayser** [comment]
I have the same error, but can't solve it by adding `abort` to the configuration for `[profile.dev]` and `[profile.release]`.

I also have a `#![no_std]` crate which uses `extern crate rlibc;` because `link.exe` asks for `memcpy`.
`cargo build --release` -> Success
`cargo build` -> error LNK2001 for symbol __CxxFrameHandler3
`cargo test` -> error[E0152]: duplicate lang item found: `panic_impl`. note: first defined in crate `std`.

I don't want to say that I'm not the problem, but this seems very inconsistent.

**Comment by mauricekayser** [comment]
This issue is not resolved by adding `panic = "abort"` to the crate, because the precompiled libcore is compiled with `panic = "unwind"`. Would it be possible to provide a precompiled libcore with `panic = "abort"`? That would be really useful for `no_std` on Windows.

References:
[No-std Windows DLL linker error](https://users.rust-lang.org/t/no-std-windows-dll-linker-error/15008)
[Missing symbol in no_std application on panic (windows-msvc) #54137](https://github.com/rust-lang/rust/issues/54137)
[Other modules `extern` functions can currently be redefined #47449](https://github.com/rust-lang/rust/issues/47449)
[rustc: assertion failiure in llvm when defining __CxxFrameHandler3 #38641](https://github.com/rust-lang/rust/issues/38641)
