### ISSUE TITLE
std::str::pattern::Pattern documentation

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#45507]
Correct me if I'm wrong, but I don't think it's possible to find out from the currently available online documentation if the following code returns true or false:
```rust
"ab".contains(&['b', 'a'][..])
```
Is searching for a slice of chars the same as searching for the string of the contatenation? Or is this a set match?

There is no information on this in the following places:
* https://doc.rust-lang.org/std/primitive.str.html#method.contains
* https://doc.rust-lang.org/std/str/pattern/trait.Pattern.html
* https://doc.rust-lang.org/std/str/pattern/struct.CharSliceSearcher.html

**Comment by Freyskeyd** [comment]
If no one is working on it I would be happy to update this.

**Comment by frewsxcv** [comment]
@Freyskeyd did you make any progress on this or is it alright for others to work on it?

**Comment by Emerentius** [comment]
I think it'd be best if the explanation is put on the page of `std::str::pattern::Pattern` (and not on the respective impls) so that it is easy to lookup in a central position.
A small table and some examples should do such as the ones I've written [over here](https://github.com/Emerentius/rust/blob/c516d8cf2437c158ccdfd5139f9641c6b6232f35/src/libcore/str/pattern.rs#L39).

I don't know how to do a sanity check compile. Apparently I need to compile all of rustc(?!) to get the docs, which is not feasible for me. If anybody would like to send the PR, they can use my branch as a base. Maybe improve the wording as well.
