### ISSUE TITLE
It's not clear when try_clone calls can fail

### ISSUE THREAD

**Issue by achanda** [rust-lang/rust#45536]
Some types have a `try_clone` methods that returns `Result<T>`. From the documentation, it is not clear under what conditions can this call fail. Types that implement it are

https://doc.rust-lang.org/std/?search=try_clone

**Comment by cuviper** [comment]
The error conditions are OS-dependent, e.g. from Windows [`DuplicateHandle`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724251(v=vs.85).aspx) or Posix [`dup`](http://man7.org/linux/man-pages/man3/dup.3p.html) (or really [`fcntl`](http://man7.org/linux/man-pages/man3/fcntl.3p.html) `F_DUPFD_CLOEXEC`).

**Comment by retep998** [comment]
Because `try_clone` creates a new handle or file descriptor, any sort of resource exhaustion which prevents another handle or file descriptor from being created can cause `try_clone` to fail.

**Comment by pocesar** [comment]
for windows specifically for TcpStream:

Sockets. No error is returned, but the duplicate handle may not be recognized by Winsock at the target process. Also, using DuplicateHandle interferes with internal reference counting on the underlying object. To duplicate a socket handle, use the WSADuplicateSocket function.

**Comment by DevQps** [comment]
@steveklabnik What do you think we should do with this? Personally I find it quite clear from the context that these methods can fail (since they deal with OS primitives like sockets and files). But adding extra information in what kind of contexts they could fail would mean adding platform-specific cases. Do you think that we can close this? Or do you believe we should append something to the currently existing docs?

**Comment by steveklabnik** [comment]
Given [this comment](https://github.com/rust-lang/rust/issues/40322#issuecomment-490508562), I believe we should close this issue.
