### ISSUE TITLE
Platform-incompatibility with hard-coded "make" in FFI wrappers

### ISSUE THREAD

**Issue by mneumann** [rust-lang/rust#45717]
There are lots of crates that use `Command::new("make")`. This breaks most BSDs, which instead use "gmake". For that reason, some years ago I wrote [make-cmd crate](https://github.com/mneumann/make-cmd-rs), but I think this should be somehow part of Rust itself, or at least part of rust-lang-nursery, for wider adoption (and security issues). It is pretty time-consuming and daunting to fix these kinds of things and not to forget one of the BSDs. Having `cfg!(target_os = ...)` orgies all over the place is no solution!

Some example crates where this occurs are `curl-sys` and `sass-sys`. There are much more. Please let us find a good solution for this "trivial" problem.

**Comment by est31** [comment]
lol this is the same kind of situation that debian has in the nodejs vs node debate...

**Comment by pietroalbini** [comment]
cc @rust-lang/libs

**Comment by niacat** [comment]
`gmake` is not a special name for `make` but rather the GNU implementation of make with GNU extensions. The default `make` is BSD make with BSD-specific extensions. The NetBSD implementation of make is also available for Linux as `bmake`.

It would be preferable for make usage to be portable rather than assuming that make is always the GNU version.

**Comment by Mark-Simulacrum** [comment]
I would expect that the path forward does not lie within the standard library (at least, not yet). Similar to the `cmake` and `cc` crates, I presume a `make` crate could exist. In any case, I don't think we can do anything about this until we have a community implementation that gains consensus -- based on @niacat's comment and my own thoughts, I don't think just falling back to gmake/bmake/etc depending on the system is the right approach in all cases.

Either way something like this being added to the standard library would need an RFC, I think, since it represents definite new territory and I would not expect us to do so. I don't think this is something that can be forced upon downstream crates.

It might be reasonable to file an issue or PR against the [API guidelines](https://github.com/rust-lang/api-guidelines), recommending that usage of make in build scripts be aware of this platform-specific detail and try to be compatible, though I don't think it's really an API guideline I guess, so that would probably also not be the best place.

(Generally speaking we don't have a good place, nor am I sure we should make one, for these sorts of issues -- they need community members to do things, and aren't something we can force on anyone or really encourage).

I guess it's also possible a clippy lint that warns on literal `Command::new("make")` could exist but that seems... non-ideal as well.
