### ISSUE TITLE
rustdoc nightly: search deduplication can cause missing items

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#45968]
This example is outdated, but in it, `thread::spawn` is missing in nightly.

stable:
![](https://i.imgur.com/JhfAz96.png)

nightly:
![](https://i.imgur.com/1CYVDpZ.png)

Probably caused by https://github.com/rust-lang/rust/commit/ee7e372bbf2d6ce184e50aaf2679873eb961dc49.

**Comment by crumblingstatue** [comment]
This seems fixed on `(ff0f5de3b 2017-11-14)`, but I don't know if a regression test should be added or something, so I'll leave this open for now.

**Comment by ollie27** [comment]
This isn't fixed. Now `std::thread::Builder::spawn` is missing. I believe this was originally caused by ee7e372bbf2d6ce184e50aaf2679873eb961dc49 (cc @GuillaumeGomez). It seems to be de-duplicating search results based on `path + name` ignoring `parent` and `ty` so it's treating `std::thread::spawn` and `std::thread::Builder::spawn` as the same.

**Comment by GuillaumeGomez** [comment]
I have to wait for both of my rustdoc PRs [here](https://github.com/rust-lang/rust/pull/46081) and [here](https://github.com/rust-lang/rust/pull/46175)) to be merged before looking for this.

**Comment by durka** [comment]
Searching for `read_to_end` in the nightly docs doesn't come up with `std::io::Read::read_to_end`. Is this the same issue?

**Comment by GuillaumeGomez** [comment]
Maybe? I'll take a look as well.

**Comment by GuillaumeGomez** [comment]
Can you confirm once again? When I just tested on nightly, it worked as expected?

**Comment by GuillaumeGomez** [comment]
@durka: However, your issue is still there. Taking a look.
