### ISSUE TITLE
Wrong null ptr check in release

### ISSUE THREAD

**Issue by msiglreith** [rust-lang/rust#46182]
We are currently facing an issue that the following [code part](https://github.com/tomaka/glutin/blob/master/src/api/wgl/mod.rs#L167-L176) from glutin (slightly modified with the panic calls) will panic with "0x0" in the if-clause, which looks like a regression to me:
```rust
pub fn get_proc_address(&self, addr: &str) -> *const () {
        let addr = CString::new(addr.as_bytes()).unwrap();
        let addr_ptr = addr.as_ptr();
        let p = unsafe { gl::wgl::GetProcAddress(addr_ptr) as *const _ };
        if !p.is_null() {
            panic!("{:?}", p);
            return p;
        }
        panic!("How?");
        unsafe { kernel32::GetProcAddress(self.gl_library, addr_ptr) as *const _ }
    }
```
This only appears in release mode, debug runs correctly.

Windows 10, MSVC 15.3.3 2017
`rustc 1.23.0-nightly (63739ab7b 2017-11-21)`

Reproduction is a bit trickier:
Run `cargo run --example triangle --release` in our `gfx-rs/pre-ll` [branch](https://github.com/gfx-rs/gfx/tree/pre-ll) should crash on loading the function pointers, boiling down to the issue noted above.

**Comment by arielb1** [comment]
@msiglreith 

The problem is that (I think, don't have an actual Windows to check) `GetProcAddress` returns a `PROC`, which (I think) is defined here:

https://github.com/brendanzab/gl-rs/blob/89d77d7c7f8497096fdf2e3fb7bed5ed1a28f63a/gl_generator/generators/templates/types/wgl.rs#L29

So it is a function pointer, which are not allowed to be null, so `GetProcAddress` returning null is UB.

**Comment by arielb1** [comment]
```Rust
pub type PROC = extern "system" fn(); // Not sure about this one :/
```

**Comment by msiglreith** [comment]
Thanks again! Changing the noted typedef to `*const ()` fixes the issue.
