### ISSUE TITLE
Confusing error about Fn trait bound

### ISSUE THREAD

**Issue by davll** [rust-lang/rust#46200]
[Playground Link](https://play.rust-lang.org/?gist=b01c046cb2ac63f7d75918d83952218b&version=stable)

I defined the trait bound `Fn(X) -> Y` in a trait definition, but the compiler complains that `Fn(X)` is not satisfied when implementing that trait. Is it an expected syntax error?

**Comment by ExpHP** [comment]
The error mentioned is:

```
the trait bound
    `for<'r> std::boxed::Box<
        for<'r> std::ops::Fn(&'r ShaderName) ->
            std::boxed::Box<futures::Future<Error=std::io::Error, Item=ShaderDef> + 'static>
        + 'static
     >: std::ops::Fn<(&'r ShaderName,)>` is not satisfied
```

The error is not wrong; a Boxed `Fn()` does not implement `Fn()`.  (why? I don't know)

**Comment by sinkuu** [comment]
Implementing `Fn` for `Box<Fn>` requires that `impl FnOnce for Box<FnOnce>` exists (since `FnOnce` is a supertrait of `Fn` and `FnMut`) which is currently impossible (https://github.com/rust-lang/rust/issues/28796#issuecomment-144892484).

As a workaround, it can be `type Loader: Deref<Target = Fn(&Self::Name) -> Self::DefinitionFuture>;` if you are ok with boxing all `Loader`s.

Or you can create a trait which is basically your own `Fn` trait but doesn't require `FnOnce`, and then bound `type Loader` by it.
Function-ish trait like `Future` or tokio's `Service` is an example of this way of creating boxable functions.

**Comment by davll** [comment]
OK, Thanks. I just boxed all `Loader`s for workaround.
