### ISSUE TITLE
Documentation in `std::net` lacks description of possible error values

### ISSUE THREAD

**Issue by torkleyy** [rust-lang/rust#46274]
For many methods it's unclear for which reason a method could fail, e.g. `TcpStream::try_clone`. An `Errors` section would be very helpful for these methods.

**Comment by fhartwig** [comment]
Related:  #45536

**Comment by DevQps** [comment]
@steveklabnik I am not sure, but I think we can close this one for the following reasons:

1. #45536 more or less already covers try_clone method specifically.
2. If this issue intended to cover Errors of the entire std, it's probably a bit too broad for an issue.

There are already some other issues around for adding potential errors for specific std submodules. Let me know if you agree! Otherwise we can maybe try to think towards a managable solution!

**Comment by steveklabnik** [comment]
Yep, I agree completely. Thanks!
