### ISSUE TITLE
rustdoc: how does `#[doc(hidden)]` interact with `--document-private-items`?

### ISSUE THREAD

**Issue by hdevalence** [rust-lang/rust#46380]
I have types `Public` (which is exported) and `Private` (which isn't) and an `impl Add<Private> for Public`.  I would like the `impl Add<Private> for Public` to appear in the Rustdoc output only when using `--document-private-items`.

As far as I can tell, the `impl Add<Private> for Public` appears in the normal rustdoc output unless it has a `#[doc(hidden)]` attribute. But this prevents the impl from appearing with `--document-private-items`.

Is `--document-private-items` supposed to override `#[doc(hidden)]`? Is there another way to hide `impl Add<Private> for Public` from the public rustdoc output?

**Comment by QuietMisdreavus** [comment]
So it seems like there's two things going on here:

* [`--document-private-items` runs the `strip-hidden` pass](https://github.com/rust-lang/rust/blob/0a2e9ade83ff253bb489c63a95b1f499c5e0916f/src/librustdoc/lib.rs#L469-L477), which i would consider a bug. `#[doc(hidden)]` items are private implementation details and fall under the same camp, conceptually, as regular items that aren't public. (Removing the `String::from("strip-hidden"),` line from that block will fix that.)
* Trait impls whose trait's type parameters include private items still appear in the docs, because the type it's impl'd *for* is public. Again, i would consider this a bug, but a separate one. The fix for that is more involved, though. `>_>`

**Comment by QuietMisdreavus** [comment]
To fix the second note in my previous comment, you'd need to unpack `imp.trait_` [in here](https://github.com/rust-lang/rust/blob/0a2e9ade83ff253bb489c63a95b1f499c5e0916f/src/librustdoc/passes/mod.rs#L182-L186), iterate through the contained `Type`'s `.generics()` and check each of those (via `.def_id()`) against `self.retained` the same way that `imp.for_` is. Something like this:

```rust
if let Some(generics) = imp.trait_.and_then(|t| t.generics()) {
    for typaram in generics {
        if let Some(did) = typaram.def_id() {
            if did.is_local() && !self.retained.contains(did) {
                return None;
            }
        }
    }
}
```

Right after that linked block.

This is technically not part of the issue (at least it sounds like the issue was more about `--document-private-items`) but would also be a nice thing to add, probably separately from the other proposed change.

**Comment by QuietMisdreavus** [comment]
Fixed in https://github.com/rust-lang/rust/pull/46412
