### ISSUE TITLE
Path.is_dir returns false for folders in OneDrive using "Files On Demand"

### ISSUE THREAD

**Issue by roblourens** [rust-lang/rust#46484]
Files On Demand is a new OneDrive feature that only downloads files to the local disk when needed. 

- Install the latest Windows and OneDrive updates
- Open OneDrive settings, enable Files On Demand
- Run this code with the path to your OneDrive folder:

```rust
    let metadata = Path::new("C:\\Users\\roblourens\\OneDrive").metadata().expect("failed");

    println!("{:?}", metadata.file_type());
    println!("{:?}", metadata.is_dir());
    println!("{:?}", metadata.is_file());
    println!("{:?}", metadata.len());
```

Output:

```
FileType(ReparsePoint)
false
false
4096
```

Here's a PR in libuv that fixed an issue with Files On Demand, in case there's a similar issue in Rust: https://github.com/libuv/libuv/pull/1522/files

Ref: https://github.com/BurntSushi/ripgrep/issues/705 and Microsoft/vscode#35433

**Comment by jonas-schievink** [comment]
Are you sure this is a bug? Seems like those folders are indeed reparse points and only look like folders to the user.

**Comment by roblourens** [comment]
I guess I'm not sure what the expected result is. Node says it's a directory:

`require('fs').lstatSync('C:\\Users\\roblourens\\OneDrive').isDirectory(); // => true`

**Comment by retep998** [comment]
When given a reparse point `metadata` is supposed to return information on the target of the reparse point, not the reparse point itself. To quote the documentation "This function will traverse symbolic links to query information about the destination file." Therefore the fact that this doesn't follow the reparse point and simply says that it is a reparse point is a bug.

**Comment by roblourens** [comment]
Is there anything I can help with on this bug? It's the root cause of a nasty bug that prevents vscode from searching inside some OneDrive folders. I could attempt a PR, if someone can give me some pointers.

**Comment by retep998** [comment]
@roblourens You could poke around with calling `GetFileInformationByHandle` directly on that directory and figure out how to determine that it is indeed a directory.

**Comment by roblourens** [comment]
Don't know if this helps:

```
let metadata = Path::new(onedrive_file).metadata().expect("failed");
println!("{:?}", metadata.file_attributes()); // 1056

let metadata2 = Path::new(onedrive_dir).metadata().expect("failed");
println!("{:?}", metadata2.file_attributes()); // 1040
```

The file attributes for a file and a directory in onedrive - both have `FILE_ATTRIBUTE_REPARSE_POINT`. The file has `FILE_ATTRIBUTE_ARCHIVE` (?). The directory has `FILE_ATTRIBUTE_DIRECTORY` which seems to make sense.

**Comment by parkovski** [comment]
The implementation of `FileType` actually has a lot of problems. Compare [the Unix implementation](https://github.com/rust-lang/rust/blob/3bee2b44cfd5610ad0346f0179602d91a8dedfd0/src/libstd/sys/unix/fs.rs#L192) to [the Windows implementation](https://github.com/rust-lang/rust/blob/3bee2b44cfd5610ad0346f0179602d91a8dedfd0/src/libstd/sys/windows/fs.rs#L517). Let's ignore the fact that there are a lot more factors on the Windows side for now. The particular issue in this thread is caused by line 523, where to be considered a directory, we expect the reparse point flag to be false and the dir flag to be true. That's, um, bad. But pretty much every function in that impl is wrong - it should work the same way the Unix version does, where it stores the native mode and each `is_*` checks for the existence of the appropriate flag. Maybe someone more familiar with Unix can say whether a symlink to a file should be treated as `SYMLINK | FILE` or just `SYMLINK`?

Now, `is_symlink_dir` is a little harder to solve. Actually, if you say that mount points are symlinks which this does, you're kind of in messy territory here because reparse points are totally up to the FS driver. So one way or another, symlink detection is broken here because you are basically saying a symlink is a reparse point that resolves to another FS location, but you can't make that judgment just from the `IO_REPARSE_TAG_*` flags. All those tell you is that it's a particular thing that Microsoft implemented, but there's no reason you can't have other implementations that act like symlinks. To actually figure this stuff out correctly you need to do what libuv is doing and try to get the FS driver to treat the reparse point as what you're looking for.

For the purpose of getting ripgrep to work, I would just refactor the methods to check for native flags like I described in the first paragraph. There should not be a `SYMLINK_DIR` mode - you should check for the existence of a symlink flag and a dir flag, but I'd make a doc comment above that function noting that it's broken and actually only tells you if the thing is a Win32 symlink or a mount point. How it should work may need some discussion, I'm not sure.

**Comment by roblourens** [comment]
Thanks for the notes. I may try to work around this downstream just for fixing search in VS Code, but I think that coming up with the right fix for Rust is outside my area of expertise. But I'm hoping that someone is able to look at this because I think it's quite a bad bug.

**Comment by BurntSushi** [comment]
@pitdicker Do you happen to have any context on what led to [this change](https://github.com/rust-lang/rust/commit/7f6f4581946f9ae8e2c23cd7e09eb4f03d6c3cb1#diff-2079e3221e2faa3ae91c9338767d2637R446) with respect to this bug?

**Comment by pitdicker** [comment]
I sort-of remember writing that code, but forgot the details. It was an effort to get symlinks on Windows in a mostly working state. Would have to dive into the details again to be of much use to be honest.

As @retep998 [commented](https://github.com/rust-lang/rust/pull/47956#issuecomment-362481996) file types on Windows behave pretty different from Unix. I would not call the logic 'wrong' as @parkovski does, but more a best effort to a cross-platform interface. I think the easiest solution is to change [`(_, true, _) => FileType::ReparsePoint,`](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/fs.rs) to something like (not tested):
```
(false, true, _) => FileType::File,
(true, true, _) => FileType::Dir,
```

So just act as if it really is a file or directory if we don't recognize the reparse point as a symlink, directory junction or mount point.

**Comment by ssokolow** [comment]
@roblourens For the record, `FILE_ATTRIBUTE_ARCHIVE` is an old [DOS-era piece of metadata](https://blogs.msdn.microsoft.com/oldnewthing/20090219-00/?p=19093/) meant for backup tools.

The FAT driver sets the Archive flag whenever you modify a file and a DOS-era backup tool operating in incremental backup mode can then go through, save copies of any files marked "Archive", and then clear the bit to indicate to its future self that they haven't changed since the previous incremental backup.
