### ISSUE TITLE
Clarify semantics of `File::try_clone()`

### ISSUE THREAD

**Issue by abonander** [rust-lang/rust#46578]
`File::try_clone()` could be clearer about how the duplicated file cursors behave. It currently says:

> The returned File is a reference to the same state that this object references. Both handles will read and write with the same cursor position.

I think it could be much clearer about how reads, writes, and seeks will affect **both handles**.

**Comment by bstrie** [comment]
Tagging P-medium at @Havvy 's request.

**Comment by Havvy** [comment]
Having an example where it shows this behaviour would also be helpful. E.g. try_clone the File, mutate the internal state in the clone, and then show that the original has also been mutated. Such as a file with contents "123456". Read to "3" in the clone, and then show that the next read of a character gets you "4".

The semantics that a separate File can change the first one should also probably be mentioned in the struct level documentation, since that's quite important to know even if you never call the method yourself.

**Comment by frewsxcv** [comment]
This is very similar to https://github.com/rust-lang/rust/issues/45536, if not a duplicate

**Comment by Havvy** [comment]
Not a dupe. #45536 is about what the error case is. This is about being more explicit about the shared cursor position in the success case. Very related though.

**Comment by frewsxcv** [comment]
I opened a PR for this: https://github.com/rust-lang/rust/pull/47958
