### ISSUE TITLE
rustc: add support for nontemporal_load intrinsic

### ISSUE THREAD

**Issue by gwenn** [rust-lang/rust#46618]
For [stdarch](https://github.com/rust-lang/stdarch), some intrinsics need this.
It should be similar to the `nontemporal_store` introduced by #45367.

**Comment by workingjubilee** [comment]
I have been informed that the required memory fencing to implement these is not supported by LLVM in a cross-platform way yet, so this is likely blocked on further codegen backend support in order to implement them safely, at least for now. https://lists.llvm.org/pipermail/llvm-dev/2020-April/141279.html

**Comment by Mark-Simulacrum** [comment]
I'm going to close this - we have some intrinsics exposing this (e.g., _mm_stream_ps), and while there are some issues with this currently (https://github.com/rust-lang/rust/issues/114582) I don't know that we expect to do more here. I doubt we'd want a stable cross-platform API for something this niche.
