### ISSUE TITLE
"remove this" suggestions should take spacing into account

### ISSUE THREAD

**Issue by zackmdavis** [rust-lang/rust#46614]
![rls_remove_this](https://user-images.githubusercontent.com/1076988/33801099-a9e378ac-dd04-11e7-9a81-7b376b05bb4e.png)

**Comment by sfackler** [comment]
I think this might make more sense over on https://github.com/rust-lang-nursery/rls-vscode or https://github.com/rust-lang-nursery/rls

**Comment by zackmdavis** [comment]
RLS is just plumbing through the suggestions [we (the compiler) give it](https://github.com/rust-lang/rust/blob/8db163e5/src/librustc_borrowck/borrowck/unused.rs#L80-L88); any improvements would need to happen here.

**Comment by sfackler** [comment]
But it seems right at the diagnostic level that the `mut` span only covers that token, and not whitespace - it's the job of the library performing automated source transforms to do any stylistic cleanup.

**Comment by zackmdavis** [comment]
That's a good point; I guess the deeper issue is that the compiler's "replace this span with this text" concept of a "suggestion" is limited? (On the other hand, I'm not eager to try to teach external tools about the AST ...)

**Comment by oli-obk** [comment]
We do suggest inserting spaces, I don't see why we can't suggest removing them either.

Especially in the mut case, we always know that it's preceded and followed by a space

**Comment by estebank** [comment]
As a stop-gap measure we can use `span_through_char` instead of `span_until_char` in any suggestion that we know ends with a space separator to do the right thing on correctly formatted code, but the suggestion engine will need a revamp to be able to account for this kind of things on a more consistent and less ad-hoc manner so that it can handle, for example, multiple spaces between `mut` and the identifier.
