### ISSUE TITLE
wasm32-unknown-unknown: function returns undefined

### ISSUE THREAD

**Issue by gitawego** [rust-lang/rust#46699]
with follow code 

```rust
#[no_mangle]
pub fn rust_function() -> String {
    let mut a = vec![];
    for x in 0..10000 {
        println!("{}", x); // x: i32
        a.push(x);
    }
    return a.iter()
        .map(|x| format!("{}", x))
        .collect::<Vec<_>>()
        .join("-");
}
```

in the built wasm file, this function returns undefined called by WebAssembly in nodejs. but it works well in a non-wasm build.

**Comment by killercup** [comment]
Right now, in wasm, Rust can't/doesn't return values that are not primitives. String for example, is 3 words in size: It contains a pointer to data on the heap, a length, and a capacity.

If you look at the wasm output rustc generates, you can see that your function actually has one parameter, which is used as an out pointer. You need to allocate a piece of memory that is 3 words in size, and pass a pointer to that when you call your rust function.

You should probably have this function return a CString, which is just a pointer to some zero-terminated data. Otherwise, have a look at https://github.com/killercup/wasm-experiments

**Comment by gitawego** [comment]
thanks a lot for your clarification!
