### ISSUE TITLE
for initial release, limit two phase borrows to method-call autorefs

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#46747]
@nikomatsakis is concerned that two-phased borrows are a hazard. In particular, they are coupled to MIR code-generation, which means if we are too aggressive in how much code we accept today, it could mean that a later change to MIR construction will inject a regression.

Niko has suggested a simple strategy for fixing this that we should deploy before we stabilize two-phase borrows: We should thread through information about whether a borrow was introduced via method-call autoref, and then *only* do the two-phase borrow system for those autorefs.

That way we will be somewhat conservative in what code is deemed acceptable by two-phase borrows today, and therefore give us more breathing room in the future as we refine the system.

**Comment by pnkfelix** [comment]
cc #46037

**Comment by pnkfelix** [comment]
To be clear, we do not think that this aspect of two-phase borrows needs to block the initial release of `#[feature(nll)]`; that is why this issue is *not* on the NLL prototype milestone.

**Comment by pnkfelix** [comment]
In my work on #46908, it seems like we have a choice:

Either:
 1. we modify a (relatively small...) number of our tests in slightly inscrutable ways in order to force a two-phase borrow to activate ... or
 2. we implement this *before* trying to land `-Z borrowck=migrate` (and thus this does belong on a NLL milestone.

at this point we have a series of NLL milestones on the path to stabilization, so we should decide where this falls in that sequence anyway.

**Comment by nikomatsakis** [comment]
Given the large number of tests affected, it seems pretty clear to me that we ought to make this change if we are going to make it. That is, unless we plan to make two-phase borrowing part of the model we expect to teach users -- which *might* be ok but seemed like something we wanted to be cautious about -- then I feel confident we need to impose restrictions, or else people will be stumbling across it all the time. In other words, I kind of think we should do this first so that we don't have to edit a bunch of tests.
