### ISSUE TITLE
Wrong suggestion for struct's type-param that is not iter::Iterator but should

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/rust#46806]
In the following example, Rust 1.22.1 and nightly complain about `T` of `Foobar` not being `iter::Iterator`, which `IterWrapper` demands.
```rust
use std::iter;

struct IterWrapper<T:iter::Iterator> {
    iter: T
}

struct Foobar<T> {
    w: IterWrapper<T>
}
```
The suggestion `consider adding a "where T: std::iter::Iterator" bound` is correct, the main suggestion `maybe try calling ".iter()" or a similar method` is not applicable to this situation, though. 

```
error[E0277]: the trait bound `T: std::iter::Iterator` is not satisfied
 --> src/main.rs:8:5
  |
8 |     w: IterWrapper<T>
  |     ^^^^^^^^^^^^^^^^^ `T` is not an iterator; maybe try calling `.iter()` or a similar method
  |
  = help: the trait `std::iter::Iterator` is not implemented for `T`
  = help: consider adding a `where T: std::iter::Iterator` bound
  = note: required by `IterWrapper`

error: aborting due to previous error
```
Same problem for an `impl<T> Foobar<T>`: Rustc suggest to call `.iter()` on the type-parameter, which is nonsense.

**Comment by zackmdavis** [comment]
#44755 could help with this. (Currently, the "maybe try calling .iter()" language is hardcoded rather than depending on what we know about `T`.)

**Comment by estebank** [comment]
To accomplish this correctly, we need to modify [`on_unimplemented_note`](https://github.com/rust-lang/rust/blob/3bcda48a30b21e46b81a7989deb30a3ba85fb918/src/librustc/traits/error_reporting.rs#L330-L396) to be able to query wether `Self` is a type argument, so that we can suggest a trait bound, instead of using `iter`. We would still be unable to tell the compiler to point `Self`s span (that might be another worthwhile improvement to `rustc_on_unimplemented`).
