### ISSUE TITLE
serde compilation is not deterministic

### ISSUE THREAD

**Issue by johnklai1** [rust-lang/rust#46846]
I was looking into why sccache was missing more than expected, and it looks like serde_derive compiles are not deterministic.

I tried this code on OSX 10.12 (Xcode 7.3.1)
```git clone https://github.com/serde-rs/serde.git
> cd serde
> git checkout 0b89bc920e6052c05483c8b56661e859caae9d25
> cargo build
> md5 target/debug/deps/libserde_derive-*.dylib
(output: MD5 (target/debug/deps/libserde_derive-c403614b534b4e94.dylib) = be85fd8981e5bb5aa789a56d6f9ae4da)
> rm target/debug/deps/libserde_derive-*.dylib
> cargo build
> md5 target/debug/deps/libserde_derive-*.dylib
(output: MD5 (target/debug/deps/libserde_derive-c403614b534b4e94.dylib) = 5fc806ed2f22bdf7e9c3b0b018ca2671)
```

I expected that the MD5s would be identical after deleting and re-running cargo build.  I ran with just the underlying `rustc` command, and that also generated different files each time.  Here is the underlying rustc command:

```rustc --crate-name serde_derive serde_derive/src/lib.rs --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="deserialize_from"' -C metadata=c403614b534b4e94 -C extra-filename=-c403614b534b4e94 --out-dir /Users/jklai/serde/target/debug/deps -L dependency=/Users/jklai/serde/target/debug/deps --extern syn=/Users/jklai/serde/target/debug/deps/libsyn-b667971f1cdadd98.rlib --extern quote=/Users/jklai/serde/target/debug/deps/libquote-34dfebedcb580111.rlib --extern serde_derive_internals=/Users/jklai/serde/target/debug/deps/libserde_derive_internals-3788ef8c57ed9e45.rlib```

I have also tried this on Windows and Linux, and it also generates different serde_derive libraries when rebuilding.

## Meta

`rustc --version --verbose`: rustc 1.24.0-nightly (dc39c3169 2017-12-17)

**Comment by alexcrichton** [comment]
Looking into this a bit. I had to run the build a few times but eventually was able to reproduce as well (on stable, but nightly also seems affected)

I found that the `synom` dependency was the one changing (that rlib was the only thing changing in the input to the linker). So I checked out dtolnay/syn@5e42499da986c81e5ab74d163acb5b3c68c3d404 and built just the `synom` crate. Turns out two objects files were changing:

* `synom-3d068837ed89ca46.synom15.rust-cgu.o`
* `synom-3d068837ed89ca46.synom9.rust-cgu.o`

Emitting the LLVM IR for all the stages yields two diffs:

* [synom15 diff](https://gist.github.com/alexcrichton/32018153e53802969b47ea04f17c23d9)
* [synom9 diff](https://gist.github.com/alexcrichton/ecfbbb5f8987c74ea229e7e9350ab12c)

Looks like those objects files may have been swapped!

cc @michaelwoerister, is this perhaps related to the partitioning code? Can you think of anything that may cause two codegen units to be swapped between two compilations?

I also have a sinking feeling this may have been introduced with the thinlto work...

**Comment by michaelwoerister** [comment]
Maybe this code can introduce instabilities if there are codegen units with the same number of trans items in them?:
https://github.com/rust-lang/rust/blob/de38f49528b537414385d42a66dda711c8c8a309/src/librustc_mir/monomorphize/partitioning.rs#L374-L397

**Comment by alexcrichton** [comment]
A minimal reproduction of this locally for me is:

```rust
pub fn foo(bar: &str) {
    bar.find('\n');
}
```

When compiled with `rustc foo.rs --crate-type lib` it'll oscillate a bit. There's definitely two codegen units getting swapped. Gonna dig more to see what codegen units are oscillating.
