### ISSUE TITLE
module resolution regression on rustc 1.24.0-nightly (2017-12-21)

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/rust#46936]
Beginning with `rustc 1.24.0-nightly (250b49205 2017-12-21)`, `rustc` fails to find the appropriate file for a module when the module root is not `mod_name/mod.rs` or `mod_name.rs` (i.e, when using `#[path]`). This has broken `ring`, which has the following `mod` declarations:

In `lib.rs`:
```rust
#[path = "arithmetic/arithmetic.rs"]
mod arithmetic;
```

In `arithmetic/arithmetic.rs`:
```rust
pub mod montgomery;
```

And `arithmetic/montgomery.rs` contains the `montgomery` module code. This results in the following error:

```rust
error[E0583]: file not found for module `montgomery`
  --> $home/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.12.1/src/arithmetic/arithmetic.rs:15:9
   |
15 | pub mod montgomery;
   |         ^^^^^^^^^^
   |
   = help: name the file either arithmetic/montgomery.rs or arithmetic/montgomery/mod.rs inside the directory "$home/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.12.1/src/arithmetic"
```

Related issues: https://github.com/briansmith/ring/issues/598, https://github.com/rust-lang/rust/pull/46531

**Comment by SergioBenitez** [comment]
cc @cramertj @nikomatsakis

**Comment by est31** [comment]
Ring has `#![allow(legacy_directory_ownership)]` inside its lib.rs, cc #37872. Seems that #46531 has turned this into a hard error. Not sure if this was intended, but it didn't refer to the tracking issue #37872 at all. Small reproduction:

`src/lib.rs`:
```rust
#[path="foo/foo.rs"] pub mod foo;
```
`src/foo/foo.rs`:
```rust
pub mod bar;
```
`src/foo/bar.rs`:
```rust
// Empty
```

#34596 strikes again... You shouldn't be able to disable forward compatibility lints.

**Comment by cramertj** [comment]
Oh, interesting. This is a bit of a weird case-- what's happening here is that, when using `#[path="foo/foo.rs"] pub mod foo;`, the `non_modrs_mods` feature will look for an inner `pub mod bar;` in `foo/foo/bar.rs` or `foo/foo/bar/mod.rs`, whereas this legacy feature looks for it in `foo/bar.rs` or `foo/bar/mod.rs`.

The new behavior is motivated because `foo.rs` is not a `mod.rs` file, so it's child modules are nested inside `foo/*` relative to `foo.rs`'s directory.

I'm not quite sure the best way to solve this. AFAIK there's no way to check the value of feature gates before parsing the files, and it isn't always valid to pull in both because `foo.rs` might have a legitimate sibling named `bar.rs` which is unrelated to `foo/bar.rs`.

Looking at https://github.com/rust-lang/rust/issues/37872, it seems like this lint has been around for quite some time and was made deny-by-default in https://github.com/rust-lang/rust/pull/42894. While it wasn't originally my intention, I personally think the best solution here is to move forward with the breakage.

**Comment by SergioBenitez** [comment]
It sounds like this is intended breakage with a fair warning period that was intentionally ignored by ring. As such, this is a non-issue. Thanks for the input @cramertj, @est31!

**Comment by cramertj** [comment]
I feel we ought to do some kind of crater run on this change at least, so this might be worth reopening. `ring` has quite a few transitive dependencies, and I'm worried about breaking all of the ones not using the latest version.

cc @jseyfried, with whom I was discussing this in another thread.

**Comment by nikomatsakis** [comment]
I'm going to re-open the ticket for discussion. I think I agree that this was intended breakage that ring ignored, but I also agree that we want to minimize the disruption if at all possible -- it *ought* to be possible to check if the feature-gate is enabled, I suppose, though it's gonna be annoying (and, later, just opt-in with the new epoch).

**Comment by nikomatsakis** [comment]
OK, chatting on IRC, @eddyb and I came up with a concrete plan of action:

We could add `-Zepoch=2018` (which implicitly requires nightly) and enable the new feature only when in that epoch.

Until then, the old behavior would be preserved.

**Comment by cramertj** [comment]
@nikomatsakis Sure, we can just switch on the `-Zepoch` flag when finding children of a non-`mod.rs` `#[path]` file and not report a feature gate error in that case, and we can report an error when we hit a the feature gate in combination with the `-Zepoch` flag. The bigger question I have is whether we want to wait for the next epoch in order to start supporting mod statements in non-`mod.rs` files. I think that's probably reasonable, but I don't know what the goal timeline was.

**Comment by nikomatsakis** [comment]
I guess I think it's *ok* to wait for the new epoch -- I would really prefer not to break ring. I think this is a grey line case, where we can justify making the change, but I am not happy with the real-world effects, so it may not be *worth* doing it.

**Comment by cramertj** [comment]
Agreed. I will make the change.

**Comment by daboross** [comment]
Sorry if this has already been elaborated on, but could someone with more knowledge clarify this for me?

Why does the mod resolution in the new system depend on _where the file actually is_, rather than _what the mod name is_?

I thought `foo::bar` would always be located at `src/foo/bar.rs`, regardless of where the `foo` mod file is located? Like, in the new system, `foo` could be at `src/foo.rs` or `src/foo/mod.rs`. Why does `mod.rs` have special treatment - why not just ignore the filename of the module entirely, and only depend on the absolute path of the module for where the file should be located?

**Comment by aidanhs** [comment]
I've just stumbled across this because rustoto_core hasn't released a new version since removing a dependency on ring. Where is this issue up to? Is it worth backing out the previous PR until a new one with the epoch suggestion is in place?

**Comment by cramertj** [comment]
@daboross 
> I thought foo::bar would always be located at src/foo/bar.rs, regardless of where the foo mod file is located?

Your impression is that a `src/whoodliewhatsit/foo.rs` containing a `mod baz;`, introduced by `#[path="whoodliewhatsit/foo.rs"]` in `lib.rs`, would cause `baz` to be included from `src/foo/baz.rs` rather than `src/whoodliewhatsit/foo/baz.rs`? This seems strange to me personally because I would expect submodules to be paired with their parent modules, but the RFC does not clarify the behavior, and your interpretation would allow the existing code to continue working-ish.

@aidanhs 
> Where is this issue up to?

I'm currently working on a branch that moves this change into `-Zepoch 2018`. That change should be backported to beta, which will fix the affected crates.

**Comment by daboross** [comment]
@cramertj 


> Your impression is that a file src/whoodliewhatsit/foo.rs containing a mod baz;, introduced by #[path="whoodliewhatsit/foo.rs"] mod foo; in lib.rs, would cause baz to be included from src/foo/baz.rs rather than src/whoodliewhatsit/foo/baz.rs? This seems strange to me personally because I would expect submodules to be paired with their parent modules, but the RFC does not clarify the behavior, and your interpretation would allow the existing code to continue working-ish.

Yes, that would be my interpretation of the behavior, given that the crate root is at `src/lib.rs`. It seems just like a different interpretation of the "path" attribute: I would interpret `#[path="whoodliewhatsit/foo.rs"] mod foo;` as "the file for foo itself is here rather than src/foo.rs" not "the foo module and all of its submodules are in `whoodliewhatsit/`".

You're right that this is pretty ambiguous, which is why I would prefer this interpretation over the other one. Once https://github.com/rust-lang/rust/issues/37872 happens, all submodules of `#[path]` marked modules will need `#[path]` as well for clarification anyways, so the behavior wouldn't last longer than that.
