### ISSUE TITLE
Universal impl trait shows camel case name warning

### ISSUE THREAD

**Issue by vi** [rust-lang/rust#46959]
```rust
#![feature(universal_impl_trait)]
#![feature(conservative_impl_trait)]
 
fn qqq(lol: impl Iterator<Item=u32>) -> impl Iterator<Item=u64> {
    lol.map(|x|x as u64)
}
```

```
warning: type parameter `impl Iterator<Item = u32>` should have a camel case name such as `Impl iterator<item = u32>`
```

**Comment by cramertj** [comment]
`impl Trait` in argument position now desugars to explicit type parameters at the HIR level. There are two possible fixes for this: specifically ignore `impl xxx` params, or move the `NonCamelCaseTypes` lint to run on the AST (an `EarlyLintPass` instead of a `LateLintPass`). I'm working on this.

**Comment by nikomatsakis** [comment]
Kind of amusing. Ignoring parameters tagged as synthetic seems to make sense. On Dec 22, 2017 9:10 PM, Taylor Cramer <notifications@github.com> wrote:impl Trait in argument position now desugars to explicit type parameters at the HIR level. There are two possible fixes for this: specifically ignore impl xxx params, or move the NonCamelCaseTypes lint to run on the AST (an EarlyLintPass instead of a LateLintPass).
I'm working on this.
cc @nikomatsakis
