### ISSUE TITLE
Bad example in `FnOnce` documentation

### ISSUE THREAD

**Issue by alercah** [rust-lang/rust#47091]
In the documentation for `FnOnce`, there are two examples. The first is 

```rust
let x = 5;
let square_x = move || x * x;
assert_eq!(square_x(), 25);
```

This is not a `FnOnce` closure, as it never moves out of a variable in a way that would prevent it from calling again.

**Comment by durka** [comment]
As a technical point, all closures are `FnOnce` closures, because they may be called at least once. `Fn` implies `FnMut` which implies `FnOnce`. However, closures that modify their environment are *only* `FnMut` and `FnOnce` (not `Fn`) and closures that move out of their environment are *only* `FnOnce`.

**Comment by alercah** [comment]
Fair point. But as someone new to the documentation, I feel there's an implication in a few places (including the book, but unfortunately that section is frozen) that any `move` closure is only `FnOnce` and neither `FnMut` or `Fn`, which isn't true.

**Comment by durka** [comment]
Yes, it needs to be made more clear that those are totally orthogonal
issues.

**Comment by DevQps** [comment]
I personally think that the first example is better to be removed from the [FnOnce](https://doc.rust-lang.org/std/ops/trait.FnOnce.html) page, since (in my opinion) it causes more confusion then that it actually helps. I guess that most people looking up FnOnce already know a bit about closures and might already know about the `move || x * x;` syntax. The page also references the book on closures, so I don't think its necessary to provide an example for calling by-value. The second example also includes the calling by value part.

I can imagine that users think the first example can only be called once (because of the FnOnce name), but this code also works:
```
fn main() {
    let x = 5;
    let square_x = move || x * x;
    println!("{}", square_x());
    println!("{}", square_x());
}
```
@steveklabnik What do you think about this?

**Comment by steveklabnik** [comment]
Sounds good to me!
