### ISSUE TITLE
DIFlags overlap?

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rust#47109]
https://github.com/rust-lang/rust/blob/5deba220d4c42b5313d7e71731ce5e8698866684/src/librustc_llvm/ffi.rs#L479-L489

https://github.com/rust-lang/rust/blob/5deba220d4c42b5313d7e71731ce5e8698866684/src/rustllvm/RustWrapper.cpp#L439-L447

Is it intentional that `FlagPrivate | FlagProtected == FlagPublic`? It doesn't look like these constants are actually used anywhere, but I think this is a bug.

Shall I submit a PR?

**Comment by mark-i-m** [comment]
ping @shepmaster @michaelwoerister?

**Comment by shepmaster** [comment]
> Is it intentional

Yes, it was intentional to start out [matching LLVM's values](https://github.com/llvm-mirror/llvm/blob/4604874612fa292ab4c49f96aedefdf8be1ff27e/include/llvm/IR/DebugInfoFlags.def#L19-L24 ):

```c
HANDLE_DI_FLAG(0, Zero) // Use it as zero value.
                        // For example: void foo(DIFlags Flags = FlagZero).
HANDLE_DI_FLAG(1, Private)
HANDLE_DI_FLAG(2, Protected)
HANDLE_DI_FLAG(3, Public)
HANDLE_DI_FLAG((1 << 2), FwdDecl)
```

As the comment mentions, it *shouldn't* matter what actual values these have so long as they get correctly translated to LLVM's values, but keeping them the same allows easier comparisons and allows the same potential combinations.

**Comment by shepmaster** [comment]
> `FlagPrivate | FlagProtected == FlagPublic`

Think of these bits as making up a 2-bit enum; the other values are bit flags.

**Comment by mark-i-m** [comment]
Got it! Thanks 😄
