### ISSUE TITLE
Wrong optimization code calling a C function.

### ISSUE THREAD

**Issue by kubo** [rust-lang/rust#47123]
I made a program which checks the result of an external C function.
It works fine for non-optimized code. However it doesn't check the result
and executes code as if the C function returns non-zero when it is optimized.

I made a small program to reproduce it.
It prints "Failure" when it is optimized and the rust version is 1.20 or later.
It works fine with rust 1.18 and 1.19.

**foo.c:**
```c
typedef struct {
    const char *val;
    int val_len;
} param;

int foo_func(param *param)
{
    return 0;
}
```

**foo.rs:**
```rust
use std::os::raw::c_char;
use std::os::raw::c_int;
use std::ptr;
use std::slice;

#[repr(C)]
#[derive(Debug, Copy)]
pub struct Param {
    pub val: *const c_char,
    pub val_len: c_int,
}

impl Clone for Param {
    fn clone(&self) -> Self {
        *self
    }
}

impl Default for Param {
    fn default() -> Param {
        Param {
            val: ptr::null(),
            val_len: 0,
        }
    }
}

#[link(name = "foo")]
extern "C" {
    pub fn foo_func(param: *mut Param) -> c_int;
}

fn main() {
    // This issue disappears when wasteful code is removed... 
    let param1: Param = Default::default();
    let mut param2 = param1;
    if unsafe { foo_func(&mut param2) } == 0 {
        let vec = unsafe { slice::from_raw_parts(param1.val as *const u8, param1.val_len as usize) };
        println!("Success {}", String::from_utf8_lossy(vec).into_owned());
    } else {
        // "Failure" should not be printed because foo_func() always returns zero.
        println!("Failure");
    }
}
```

Compile `foo.c` as a shared library as follows on Linux or macOS.
```shell
$ cc -shared -fPIC -o libfoo.so foo.c
```

When `foo.rs` is compiled without optimization, it prints "Success" as expected.
```shell
$ rustc -o foo-non-optimized foo.rs -L.
$ ./foo-non-optimized
Success 
```

When `foo.rs` is compiled with optimization with rust 1.20 or upper, it prints "Failure" even though `foo_func()` always returns zero.
```shell
$ rustc -o foo-optimized -O foo.rs -L.
$ ./foo-optimized
Failure
```

## rust versions I used

```shell
$ rustc --version --verbose
rustc 1.20.0 (f3d6973f4 2017-08-27)
binary: rustc
commit-hash: f3d6973f41a7d1fb83029c9c0ceaf0f5d4fd7208
commit-date: 2017-08-27
host: x86_64-apple-darwin
release: 1.20.0
LLVM version: 4.0
```

```shell
$ rustc --version --verbose
rustc 1.21.0 (3b72af97e 2017-10-09)
binary: rustc
commit-hash: 3b72af97e42989b2fe104d8edbaee123cdf7c58f
commit-date: 2017-10-09
host: x86_64-apple-darwin
release: 1.21.0
LLVM version: 4.0
```

```shell
$ rustc --version --verbose
rustc 1.22.1 (05e2e1c41 2017-11-22)
binary: rustc
commit-hash: 05e2e1c41414e8fc73d0f267ea8dab1a3eeeaa99
commit-date: 2017-11-22
host: x86_64-apple-darwin
release: 1.22.1
LLVM version: 4.0
```

```shell
$ rustc --version --verbose
rustc 1.23.0-beta.2 (c9107ee93 2017-12-08)
binary: rustc
commit-hash: c9107ee9309636ea1abc97db166c96cc5d721c1b
commit-date: 2017-12-08
host: x86_64-apple-darwin
release: 1.23.0-beta.2
LLVM version: 4.0
```

```shell
$ rustc --version --verbose
rustc 1.24.0-nightly (3f916bd30 2017-12-30)
binary: rustc
commit-hash: 3f916bd3029262e2270dfbafb9ab045927499abd
commit-date: 2017-12-30
host: x86_64-apple-darwin
release: 1.24.0-nightly
LLVM version: 4.0
```

**Comment by retep998** [comment]
`let param1: Param = Default::default();`
`let vec = unsafe { slice::from_raw_parts(param1.val as *const u8, param1.val_len as usize) };`
Because you never assign a non-null value to `param1.val`, this means that you are effectively dereferencing a null pointer. LLVM correctly interprets this as impossible and assumes that the branch can never be hit and therefore it always hits the failure branch when optimizations enabled.

Not a bug in Rust, just you hitting undefined behavior and paying the price.

**Comment by kubo** [comment]
@retep998 Thank you!
I understand what you wrote. I think that rustc should print a warning instead of slightly ignoring the true branch.

I have a question.
Some C functions set a pair of null and zero to an output value when the value is empty.
In this case, if I change the code as follows and a null value is set to `param2.val` in C, is the behavior of `slice::from_raw_parts()` undefined?
```rust
let vec = unsafe { slice::from_raw_parts(param2.val as *const u8, param2.val_len as usize) };
```

**Comment by retep998** [comment]
If C ends up assigning a null value to `param2.val` then it is *still* undefined behavior, however LLVM likely won't notice and your code may end up failing in a different way. Undefined behavior is undefined in how it fails, or whether it even causes your code to fail at all. Sometimes it leads to silent data corruption or massive security breaches.

In general it's a really hard problem to print warnings based on LLVM optimizations due to undefined behavior. Partially because it's really hard to ask LLVM when this happens in the first place, and partially because this happens in a lot of cases where the behavior is expected for performance reasons.

**Comment by kubo** [comment]
Thank you!
I should checked [API document about std::slice::from_raw_parts](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html) before I opened this issue.
It is documented as `p must be non-null, even for zero-length slices`.
I had thought that a null pointer could be accepted when the length is zero.
