### ISSUE TITLE
struct derefrences and prints fn pointer

### ISSUE THREAD

**Issue by mandober** [rust-lang/rust#47137]
I'm not sure about the title, but here's what happens on https://play.rust-lang.org

```
struct P();
fn main() {
    let b = P;
    println!("{:?}", b);
}
// error[E0277]: the trait bound `fn() -> P {P::{{constructor}}}: std::fmt::Debug` is not satisfied ...

// but when the type is annotated:
struct P();
fn main() {
    let b: fn()->P = P;
    println!("{:?}", b);
}
// it prints (e.g.):  0x55ccacc68f70
```

**Comment by durka** [comment]
This is because annotating the type causes a coercion from the concrete function reference type (not sure of the right term but it's zero-size because the type is tied to the specific function) to the function pointer type (which is a memory address).

This has nothing to do with structs, by the way. You're using the struct constructor as a function, which works for tuple structs. The same thing would happen with a normal function.

**Comment by vitalyd** [comment]
I believe it’s called an "fn item".

**Comment by mandober** [comment]
I see... thank you! The type of `b`is a function item, but it can't be annotated as such; when `b` is annotated as a function pointer it coerces to one. (now off to see the actual functional difference between the two)

**Comment by durka** [comment]
Start here: [function item types](https://doc.rust-lang.org/stable/reference/types.html#function-item-types), [function pointer types](https://doc.rust-lang.org/stable/reference/types.html#function-pointer-types).

This issue can be closed.
