### ISSUE TITLE
2.pow(n) does not optimize well

### ISSUE THREAD

**Issue by hanna-kruppe** [rust-lang/rust#47234]
A mibbit user noted in `#rust-beginners` that the integer `pow` method with a base of two generates far worse code than a shift: https://godbolt.org/g/mE1wjH (the shift is not equivalent for n >= 64, but you can see that it would still be better code if you accounted for that)

Perhaps we can special case the base 2 and use a shift in that case? One complication is that `pow` is subject to overflow checks: Whether it panics or returns 0 for excessive exponents depends on whether overflow checks are enabled, and I don't know of a way to branch depending on whether they are enabled (which is required for this optimization to not change behavior).

Alternatively, better LLVM optimizations could help, but this might be a bit too much to ask.

**Comment by nagisa** [comment]
LLVM doesn’t optimise even a 

```
pub fn dopow(mut exp: u32) -> u64 {
            let mut acc = 1;
            while exp > 0 {
                acc = acc * 2;
                exp -= 1;
            }
            acc
}
```

so I don’t see it being able to optimise the more complicated algorithm used currently.

**Comment by est31** [comment]
Sooo... that means that there should be a MIR optimisation that checks whether the function is `libcore::num::<sth>::pow` and then checks whether the base is a constant expression and a power of two and if is, it should replace the expression by a shift instead?

Or is this rather solved on the llvm side by having a pow intrinsic that works on integers?

**Comment by rkruppe** [comment]
A MIR pass would be a pretty big hammer. We'd have to make this random library function specially recognized by the compiler. Also the implementation effort wouldn't be justified for a one-off optimization.

I think the closest thing to a practical solution would be changing the library code that implements `pow`. The problem with that is that it can't match the current algorithm wrt overflow checks. But that doesn't seem like it's unique to this function, surely other code runs into the same problem? Might be worth adding a way to query the status of overflow checks. Historically `cfg!(debug_assertion)` was that way (if you ignored `-Z` flags), but now we also have `-C overflow-checks`.

**Comment by e00E** [comment]
As of 1.53.0 and today's nightly the bug still occurs: https://godbolt.org/z/Kjn4odTdh

**Comment by NCGThompson** [comment]
As of 1.74.0, Rust still isn't able to optimize `2u32.wrapping_pow(u)`. However, since 1.60.0, it is able to optimize `1u32.wrapping_pow(u)`.

If the leading zeroes of the base are removed before exponentiation with a right shift and then added back with a left shift after exponentiation, then the `2u32.wrapping_pow(u)` becomes a `1u32.wrapping_pow(u)` and therefor can be optimized. In fact, it gives equivalent assembly to `1u32.checked_shl(u).unwrap_or_(0)` However, removing the zeroes only significantly helps in with special cases like a constant power of two, so it isn't worth implementing.

Here is an example. This wasn't thoroughly checked for logic errors: [Compiler Explorer link](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywYSA7KUcAZPAZMADl3ACNMYhAfAAdUBUI7Bhc3D29SOITbAQCg0JYIqJ8rTBskoQImYgIU908uYsxrbIYKqoJckPDI6MtK6tq0hr72zvzC6IBKS1QTYmR2DgBSACYAZiWAVgAhQNpAzAgggDdIya2AESWNAEEAejuAagAVBDwFR4jgQ0fgTAJbEZHqgYrYWHgAF6YdCPQKPUzmZCPLgAOi8kmuNxiJjCjyoDF%2BGggJhAjxMaxWk0eAFolmtsGSKY8ll5tpjHhzkeSViiAO7EJgxGKBYAAfTivOJ51uLKuMpl6y2uwY%2ByCR0wp2I502cvuTwAkgQwBwPmJeUwAJ4fEFgyHQ2FUT6oAgIYExSKGdCm4iYR5oBjmQwETHY3H434rCBU2n0xkrZms9mclbcvkCoUi8WoSWbaU3WWYwuKnZ7A7qzXa3WhvEEqhEklx6N0hnchNs26cx4pilpwXCoxZyUmPMF%2BX54vK1WHE5nS4hnE1vFcYmk7lN2Otlntm6drip5AIUoAa2hooUCFoUpRJgY/MFopIoqwVCYJloBCjha8uqLGxLKrLGctTnW5q3DKhIwbNcaWbOM2yTDk7wzAcMHQUUwiYJRBwgbsVlIMkR2/QsFT/SdAI1WcdXnMMCWAZcmFXCl1xbJktwQx4kP7MVUPQzDMGwphHgAKi7fCmK/H9QIXcNOMzHiMKwiUIAU9g43wqCmJgjdWMTDtOTwR0TGZNYrhMx4NHgvTOw5H0CDmAkuDpbdO1HHd9MdFTjNMi5zMstzrPhf57PMpz2Nczt6AIR4CAhLzPj4lECAFOhMyhYh4k/NZnM5SLgXQNDPLpHzCvpWCYtCqy8oKhLZIHJThxRA9j1Pc9LxilEFCYOyBUBMUWDfKVJmvW90wfYgn0wF83w/QjJKxaSCSa5ATzQ%2BS%2BOwlTGLwsktuYx4AHlQSSOknG5WC2MqgyyS8orfIu/zrNs4KhFQNgIC4c4srCojLo8vibrMiz7oCmyguIAkXrejRPuyjlwpy/5ouS1UxTS%2BI4pUxLkdSyIMph9jcrWpQMf%2B5syuxgc0YUCqHtymJ0vQEwbFFJKmBSyncY%2BW7WfZ1HOcaw9ltPfrL2HOkADEaYixGePpjAmai26icwAXmrQ%2BrPslr6x2lqLiDi2WGYVlFUE1KhaGzTNz2IYkKRAEBtn1Z4hBpR45cZ5meZR0UqfxyqHheN5rTNi3eT9QWj0edBUEwBQGGNKLeRISPeUIV0EmAIIYUCAgFDAMB2Ku/PiBRLhmRWAA2VYK/hFELPz26gd0h7Oye8HHmCARMClzlXPYw35ZsVWhbQ1qIHdhWWYpvn0oUWaOGmWhOE2XhPA4LRSFQTgACUzCihRZnmX1VjWHhSAITQF%2BmI8QE2DR9E4SRV8vzfOF4BQQHvi/14X0g4FgJAaAWDCnoGQCgEAgEgJ6MQBokh740HfJED%2BykX5hECFUC0nAz5oOYMQC0%2B0wjaFKN/M%2BQC2CCH2iqTBP9SBYDCCYYATgxC0A/twXgWAWCGGAOIGh%2BAfRlFOKwjemBVClBMAQRYZ8c5NBfvsMIAo8EuCwC/JKeAWBYN/ubJgwAFAADU8CYF5IdRgGiZCCBEGIdgUgzHyCUGoF%2BuguD6C4SABEFg5Ef0gNMG0SRWHUn2rwU2kRiB4CwJ4qMlgmjEKSA4BgzhXB1D0P4A44wehOMyIkAQgx6gZHiJkhgYxuhRCcSUMoAg2gDASUMSJzRyj9A6CkopehAyVNSDklpDS8hNI%2BjMOYCwJCL2Xs/GhW8ODwj3kiVE6I66PAgLgQgJBy6n0mLwb%2BWhJjX1vvfJeHAn6kDXhvUZ79P7n0vhsh%2BHAVjDMOW/U5P9zmagSPYSQQA%3D%3D)

**Comment by nikic** [comment]
https://github.com/rust-lang/rust/pull/114390 is the fix for this issue, but it doesn't have recent activity.

**Comment by NCGThompson** [comment]
> #114390 is the fix for this issue, but it doesn't have recent activity.

@nikic Should I take it over or should I give the pull requester more time?

**Comment by NCGThompson** [comment]
> One complication is that pow is subject to overflow checks: Whether it panics or returns 0 for excessive exponents depends on whether overflow checks are enabled,

We can fix that now that we have `#[track_caller]`. We will be further able to improve this further once we have `#[cfg(overflow_checks)]`.

**Comment by yugr** [comment]
PR has been reverted due to #120537 . Perhaps this issue could be reopened ?
