### ISSUE TITLE
Generic trait implementation over other traits doesn't work ... 

### ISSUE THREAD

**Issue by przygienda** [rust-lang/rust#47260]
`
trait X {
    fn a(&self) {}
}

trait Y {
    fn b(&self) {}
}

impl Y for X {}

#[derive(Default)]
struct V {}

impl X for V {}

fn r<T: ?Sized>(e: &T) -> &Y
where
    T: Y,
{
    e
}

fn main() {
    let v = V::default();

    r(&v as &X);
}

`

should compile but it does not. struct V derives implementation of Y over provided impolementation of X but the ultimate casting doesn't work with or without ?Sized  

However, instead of returning e doing e.b() works fine which indicates that the derivation works but compiler gets confused about Sizing ...

**Comment by qnighy** [comment]
`V` is irrelevant to the problem. The minimal reproduction code is here:

```rust
trait Y {}

fn r<T: ?Sized>(e: &T) -> &Y
where
    T: Y,
{
    e
}
```

Then it seems to be a duplicate of e.g. #42923. I think it's a fundamental restriction because if `e: &T` is already a fat pointer (i.e. `T` is a DST value), then there's no room for the vtable.

If you really want to cast a DST value into another trait object, the typical workaround here is to put another level of `&` or `Box` indirection.

**Comment by przygienda** [comment]
yupp, closing ...
