### ISSUE TITLE
docs: Have panic!() and compile_error!() point to each other in docs

### ISSUE THREAD

**Issue by xftroxgpx** [rust-lang/rust#47275]
While viewing the docs for each:
https://doc.rust-lang.org/beta/std/macro.panic.html
https://doc.rust-lang.org/beta/std/macro.compile_error.html
would be real nice to have them link to each other, like an "See also" thing, but probably not as simple as only two words.

(I don't know how to do that or even how to word it, hopefully someone will take this task)

For your consideration.
Thank you.

**Comment by AndrewBrinker** [comment]
I'd love to work on this.

**Comment by AndrewBrinker** [comment]
So, the relationship between "panic" and "compile_error" is that panic is meant to signal a run time error from which the thread cannot recover, while compile_error is meant to signal an error in compilation. Generally, compile_error is used in a few select contexts:

1. For better error messages in writing your own macros.
2. For better errors with conditional compilation.

Thinking about it more, it may make sense to have the compile_error docs reference panic, but not the other way around. Because confusion in the other direction seems unlikely.

**Comment by xftroxgpx** [comment]
> Thinking about it more, it may make sense to have the compile_error docs reference panic, but not the other way around. Because confusion in the other direction seems unlikely.

I usually only remember the existence of `panic!` but I do know there's an equivalent for erroring during compile time, so I would just go ahead look up `panic!` and "expect" to find a link to `compile_error!` :)


I personally don't think they'd be any confusion between the two, mainly because I assume the wording would be slightly more verbose than simply "See also: panic!" or "See also: compile_error!", it'd be more like: "For throwing an error at compile-time, see `compile_error!`", or "For throwing an error at runtime, see `panic!`".

Hey, thanks for considering it ;)

**Comment by ogham** [comment]
I had a go at this today!

> Thinking about it more, it may make sense to have the compile_error docs reference panic, but not the other way around.

I agree with the sentiment that `panic!()` is the “main” macro, and `compile_error!()` is the “secondary” macro. So I’ve tried to word it to say that the latter is the compiler version of the former, rather than giving them equal documentation footing.
