### ISSUE TITLE
Speed up SVH computation by using Fingerprint::combine().

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#47297]
Existing fingerprint values can be merged into one fingerprint via the rather efficient `Fingerprint::combine()` method. We should make use of that during SVH computation instead of re-hashing all those fingerprints.

See here: https://github.com/rust-lang/rust/blob/2e33c89ff1518359c4bd5fbed1571ea00cb3b146/src/librustc/hir/map/collector.rs#L123-L163

**Comment by srinivasreddy** [comment]
I am taking it.

**Comment by michaelwoerister** [comment]
Thank you, @srinivasreddy! Let me know if you need any further directions.

**Comment by Pulkit07** [comment]
@srinivasreddy are you still working on it or can I take this one?

**Comment by michaelwoerister** [comment]
Feel free to give it a shot if you are still interested, @Pulkit07!

**Comment by retep007** [comment]
Hello @michaelwoerister I would like to take this one, but first I will need a bit more explanation since I'm new to this project.

You are suggestings using Fingerprint::combine() method I suppose you meant 
``` rust
pub fn combine(self, other: Fingerprint) -> Fingerprint
```
`from ich/fingerprint.rs`
which however requires a fingerprint to be combined with.

From what I see method `finalize_and_compute_crate_hash` always creates new Svh and calculates all hashes and you probably want to reuse some fingerprints from previous computation?

**Comment by retep007** [comment]
@michaelwoerister did you have time to check my commit?

**Comment by michaelwoerister** [comment]
Oh, sorry for the delay, @retep007! I remember taking a look and then completely forgot replying to you.

The code combining the fingerprints looks good. However, we have to keep the sorting step in order to make the hash more stable. Otherwise exchanging to functions in the source code would lead to a different hash, even though such a change makes no semantic difference.
