### ISSUE TITLE
File writing error

### ISSUE THREAD

**Issue by DoctorVWA** [rust-lang/rust#47335]
When I try to overwrite a file with a string parsed to bytes, for some reason it duplicate the last character.

I tried this code: https://github.com/DoctorVWA/NoteIt/tree/working/ 

I expected to see this happen: first of all, I build that using `cargo build`, go to `target/debug`, create a note(`note_it create test`) it stores that string in the database: `1;test;false;`, finish it(`note_it finish 1`) and store it in the database: `1;test;true;`

Instead, this happened: in the database I have `1;test;true;;` instead of `1;test;true;`

**Comment by estebank** [comment]
I'm sorry but this is the issue tracker for the compiler itself. Questions like this are more appropriate for places like https://www.reddit.com/r/rust, https://users.rust-lang.org and https://stackoverflow.com. It is also better to provide a reduced set of code that replicates the issue you're seeing, so that people are better able to help you.

Having said that, it does seem that it looks to me that on these two strings

```
1;test;false;
1;test;true;
```

the last one is shorter by one character than the previous one. This makes me think that you're probably reusing a buffer and not properly truncating it after "deleting" it, instead overwriting, which would result in what you're seeing: ` 1;test;true;;`
