### ISSUE TITLE
change to `-Zunpretty=X` instead of `--unpretty=X -Zunstable-options`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#47395]
Currently, the `--unpretty` switch, which dumps internal compiler IRs etc, requires `-Zunstable-options`. It should just be `-Zunpretty`.

Honestly I can't recall precisely how all this option code works, but here are a few pointers to what might need to be changed:

`unpretty` opt group:

https://github.com/rust-lang/rust/blob/0b90e4e8cd068910f604f3e1fb5d03cc01f1658f/src/librustc/session/config.rs#L1512-L1519

debugging options (`-Z` flags) are defined by this crazy macro:

https://github.com/rust-lang/rust/blob/0b90e4e8cd068910f604f3e1fb5d03cc01f1658f/src/librustc/session/config.rs#L1045-L1239

When editing this code, I usually try to find some comparable option and copy-and-paste the relevant code. 👅

**Comment by nikomatsakis** [comment]
Ok, calling those mentoring instructions is a bit of a stretch, but there are at least a few tips =) feel free to ping me

**Comment by mark-i-m** [comment]
@nikomatsakis I could try my hand at this :)

**Comment by nikomatsakis** [comment]
@mark-i-m cool =) do you need any more tips to get started?

**Comment by mark-i-m** [comment]
Just confirming one thing: the unpretty flag doesn't affect dependency
tracking; it should be UNTRACKED, right?


On Jan 14, 2018 7:01 AM, "Niko Matsakis" <notifications@github.com> wrote:

@mark-i-m <https://github.com/mark-i-m> cool =) do you need any more tips
to get started?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rust-lang/rust/issues/47395#issuecomment-357510337>,
or mute
the thread

**Comment by nikomatsakis** [comment]
Untracked should be fine.

**Comment by mark-i-m** [comment]
IIUC, no other `-Z` flag can take the form `-Z flag k=v` (e.g. `-Z unpretty hir=foo`)... Would it be better to make the format `-Z unpretty=hir=foo` or to add such a format possibility to `-Z` generally?

**Comment by mark-i-m** [comment]
If I use the `-Z unpretty=hir=foo` format, I believe I have a PR that works :)

**Comment by nikomatsakis** [comment]
I think `-Zunpretty=hir=foo` is fine.

**Comment by mark-i-m** [comment]
Made a PR :)
