### ISSUE TITLE
Looks like the unstable book on doc.rust-lang.org isn't being rebuilt?

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust#47394]
The unstable book on master has [documentation for match_default_bindings](https://github.com/rust-lang/rust/blob/master/src/doc/unstable-book/src/language-features/match_default_bindings.md) that [got merged Oct 6, 2017](https://github.com/rust-lang/rust/pull/44614). However, at all 3 of these URLs, the documentation for match_default_bindings is blank:

* Stable: https://doc.rust-lang.org/stable/unstable-book/language-features/match-default-bindings.html
* Beta: https://doc.rust-lang.org/beta/unstable-book/language-features/match-default-bindings.html
* Nightly: https://doc.rust-lang.org/nightly/unstable-book/language-features/match-default-bindings.html

Which leads me to believe the unstable book isn't getting rebuilt/redeployed/recached at all/correctly?

cc @alexcrichton, @steveklabnik

**Comment by alexcrichton** [comment]
Probably an artifact of https://github.com/rust-lang/rust/blob/master/src/tools/unstable-book-gen/src/main.rs, I think the filename needs dashes not underscores.

**Comment by est31** [comment]
Okay, so putting it all together:

* unstable-book-gen puts `match_default_bindings.md` into the destination dir perfectly and with content.
* unstable-book-gen generates a `SUMMARY.md` that contains a link to `match-default-bindings.md`. So it expects dashes.
* mdbook, instead of giving an error or something just outputs an empty file: https://github.com/rust-lang-nursery/mdBook/issues/540

Tidy has a lint that checks all source files of the unstable book whether they correspond to a valid feature. If you put hello.md there, tidy will complain. However, this check does not account for the fact that the generation tool needs dashes instead of underscores.

I think the best solution for this on the Rust side is to change the affected files from underscores to dashes and to enhance the tidy lint to treat underscores as invalid. Expect a PR any moment.
