### ISSUE TITLE
It should be an error to have #[inline] on trait methods

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#47475]
It should be an error to have [#[inline] on trait methods](https://play.rust-lang.org/?gist=8fda62c29771a76803a6cbe5bbac7138&version=nightly) because #[inline] should be on the impl.
Otherwise it has no effect and leads people to think they are inlining when they aren't.

**Comment by petrochenkov** [comment]
*on trait methods *without body*

**Comment by dtolnay** [comment]
To clarify: this is asking for an enabled-by-default warning and not a breaking change right?

**Comment by Boscop** [comment]
Yes, that makes the most sense for now :)

(But it could be a hard error later..)

**Comment by etaoins** [comment]
This should be fixed by rust-lang-nursery/rust-clippy#2367

**Comment by Manishearth** [comment]
Closing the issue since there's a clippy lint -- the general preference is that aside from deprecation/stability/epoch lints, rustc isn't going to get new lints. If you feel strongly that this should be in rustc, open a new issue for uplifting the clippy lint and make a case specifically for why it belongs in rustc.
