### ISSUE TITLE
Anonymous bound region BrAnon(0) in return but not args

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#47511]
Looks just like #43567. Mentioning @petrochenkov and @eddyb who were involved in that issue. The following code compiles with 1.21.0 but ICE as of 1.22.0.

```rust
fn f(_: X) -> X {
    unimplemented!()
}

type X<'a> = <&'a () as Trait>::Value;

trait Trait {
    type Value;
}

impl<'a> Trait for &'a () {
    type Value = ();
}

fn main() {}
```

```
error: internal compiler error: librustc_typeck/astconv.rs:1212: anonymous bound region BrAnon(0) in return but not args
 --> src/main.rs:1:15
  |
1 | fn f(_: X) -> X {
  |               ^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-nightly (da569fa9d 2018-01-16) running on x86_64-unknown-linux-gnu
```

**Comment by eddyb** [comment]
cc @nikomatsakis Looks like `astconv` is eagerly normalizing, but not when checking the return.
`fn f<'a>(x: X<'a>) -> X<'a> { x }` produces a non-ICE error which is also wrong (IMO).

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by topecongiro** [comment]
https://github.com/rust-lang/rust/blob/ab7abfcf3457ebc67ac7fef5c3028a6ae4402156/src/librustc_typeck/astconv.rs#L1207

Is changing `collect_referenced_late_bound_regions` to `collect_constrained_late_bound_regions` ok?

My understanding is that `fn f<'a>(x: X<'a>) -> X<'a>` is ok, whereas `fn g<'a>(x: X<'a>) -> &'a X<'a>` is not and rustc should produce an error.

**Comment by nikomatsakis** [comment]
OK, looked a bit closer. I think the code is correct, but the `span_bug` was just there to catch an edge-case in the error message formation that I didn't feel like handling (and thought was impossible) -- in particular, the case where a region is anonymous and yet somehow appears only in the return type.

I *thought* this was impossible because the elision code (which kicks in in such a case) ought to have detected that and repored an error. For example, `fn foo() -> &u32` will error out in a different way.

But I overlooked the fact that there could be a lifetime which **appeared** in the parameters but was not **constrained** by the parameters. In particular, type and lifetime inputs to an associated type are not constrained (which is of course what we have here, though the use of a type-alias kind of hides it).

So I think we basically just want to tweak the error message code in this case.

**Comment by nikomatsakis** [comment]
Hmm, actually, while we can simply fix the error message, I'm now second guessing if this is the right place to detect an error, or if this should be an error at all. We could certainly handle it (alternatively) by treating the anonymous lifetime as an early-bound region.

**Comment by nikomatsakis** [comment]
Well, I opened a PR to fix the ICE, anyway.

**Comment by nikomatsakis** [comment]
Regarding the regression, it was caused by this bug fix https://github.com/rust-lang/rust/issues/33685, for which we already underwent the warning cycle etc. I'm not sure why however things were working until 1.21. Seems like a bug.

**Comment by nikomatsakis** [comment]
The bug was fixed by @petrochenkov in 80cf3f99f4a3377fd9b544d18017ef29b8713dfd, if I'm not mistaken.  This moved a check that previously appears to only have been in place for `fn()` types to be applied more generally. I'm not inclined to do much more on this issue besides fix the ICE -- @dtolnay is this causing a problem for anyone, or just something you noticed?

**Comment by dtolnay** [comment]
> @dtolnay is this causing a problem for anyone, or just something you noticed?

This bug prevented me from implementing [SCARY assignments](http://www.stroustrup.com/SCARY.pdf) for [`Punctuated`](https://docs.rs/syn/0.12/syn/punctuated/struct.Punctuated.html) iterators in Syn.

`Punctuated<T, P>` is a punctuated sequence with elements of type `T` separated by punctuation of type `P`. I have an IntoIterator implementation for Punctuated, &Punctuated, and &mut Punctuated which iterate over just the sequence elements of type `T`, `&T`, `&mut T` (there are other ways to iterate over both elements and punctuation). In Syn 0.12 the iterator types are parameterized over both `T` and `P` so you have `IntoIter<T, P>`, `Iter<T, P>`, `IterMut<T, P>`. This is inconvenient because the second type parameter is useless, there is no way to access a value of type `P` from these iterators, and is a candidate for SCARY assignments.

In the next breaking release of Syn I plan to expose simply `IntoIter<T>`, `Iter<T>`, `IterMut<T>` with a single type parameter. However in the near term I wanted to do this cleanup without a breaking change. Idea: provide a type parameter default for `P` and use type system tricks to make `*Iter<T, P1>` an identical type to `*Iter<T, P2>`. This is technically a breaking change if someone had implemented a trait for iterators with different `P` type parameters that used to be different types but would now be the same type, but I felt comfortable making this change in a minor version because of the way people use these iterators in practice.

A proof of concept works great for `IntoIter` and allows SCARY assignments and referring to iterators with a single type parameter.

```rust
use std::marker::PhantomData;

pub struct Punctuated<T, P> {
    t: PhantomData<T>,
    p: PhantomData<P>,
}

impl<T, P> IntoIterator for Punctuated<T, P> {
    type Item = T;
    type IntoIter = IntoIter<T, P>;

    fn into_iter(self) -> Self::IntoIter {
        unimplemented!()
    }
}

pub type IntoIter<T, P = ()> = <Punctuated<T, P> as private::IntoIterator>::IntoIter;

mod private {
    use super::Punctuated;
    use std::marker::PhantomData;

    pub trait IntoIterator {
        type IntoIter;
    }

    impl<T, P> IntoIterator for Punctuated<T, P> {
        type IntoIter = IntoIter<T>;
    }

    pub struct IntoIter<T> {
        t: PhantomData<T>,
    }

    impl<T> Iterator for IntoIter<T> {
        type Item = T;

        fn next(&mut self) -> Option<Self::Item> {
            unimplemented!()
        }
    }
}

struct A;
struct B;
struct C;
fn f(arg: IntoIter<A, B>) -> IntoIter<A, C> {
    // SCARY assignment
    arg
}
```

But it falls apart if we attempt exactly the same thing for `Iter` and `IterMut`. I believe the following is valid Rust code and should compile successfully.

```rust
use std::marker::PhantomData;

pub struct Punctuated<T, P> {
    t: PhantomData<T>,
    p: PhantomData<P>,
}

impl<'a, T, P> IntoIterator for &'a Punctuated<T, P> {
    type Item = T;
    type IntoIter = Iter<'a, T, P>;

    fn into_iter(self) -> Self::IntoIter {
        unimplemented!()
    }
}

pub type Iter<'a, T, P = ()> = <&'a Punctuated<T, P> as private::IntoIterator>::IntoIter;

mod private {
    use super::Punctuated;
    use std::marker::PhantomData;

    pub trait IntoIterator {
        type IntoIter;
    }

    impl<'a, T, P> IntoIterator for &'a Punctuated<T, P> {
        type IntoIter = Iter<'a, T>;
    }

    pub struct Iter<'a, T: 'a> {
        t: PhantomData<&'a T>,
    }

    impl<'a, T> Iterator for Iter<'a, T> {
        type Item = &'a T;

        fn next(&mut self) -> Option<Self::Item> {
            unimplemented!()
        }
    }
}

struct A;
struct B;
struct C;
fn f(arg: Iter<A, B>) -> Iter<A, C> {
    // SCARY assignment
    arg
}
```

```
error: internal compiler error: librustc_typeck/astconv.rs:1212: anonymous bound region BrAnon(0) in return but not args
  --> src/main.rs:47:26
   |
47 | fn f(arg: Iter<A, B>) -> Iter<A, C> {
   |                          ^^^^^^^^^^

note: the compiler unexpectedly panicked. this is a bug.
```

**Comment by nikomatsakis** [comment]
> This bug prevented me from implementing SCARY assignments for Punctuated iterators in Syn.

Hmm, so, I had in mind issuing a future compatibility warning, which means this code would break *eventually*.

However, an alternative, with perhaps a bit more effort, might be to promote `'a` here to be early-bound, in which case the function could be compiled.

**Comment by dtolnay** [comment]
I guess I am unclear where this is going wrong. The second code sample does not immediately look like #33685 to me because every lifetime in the code also appears in the trait input type.

> Note that it is perfectly fine for a higher-ranked lifetime to appear in an associated type or function return type if it also appears in the trait inputs or function arguments.

Is there an easy way to sum up the rules for whether a type alias with generic parameters is valid and behaves in a sensible way? Does every lifetime parameter and type parameter need to be mentioned in the Associated type?

```rust
type Iter<'a, T, P> = <&'a Punctuated<T, P> as Trait>::Associated;
```

If it is possible to relax the restrictions by promoting `'a` to early-bound, that seems like the way to go.

**Comment by nikomatsakis** [comment]
@dtolnay 

> because every lifetime in the code also appears in the trait input type.

The point is that the **type** of the argument is not the trait inputs, it's the projection. i.e., the type is `<&'a Punctuated<T, P> as private::IntoIterator>::IntoIter` -- and that might very well be some type like `u32` once normalizes, so in that case `'a` would not be constrained in any way.

Still, as I said, the ordinary thing for us to do is to make lifetimes that meet this criteria early-bound. For example, if you do `fn foo<'a>(x: u32) -> u32` (which, as I said, could very well be the signature of `f` post normalization), **that** is legal, and it's because we make `'a` early-bound. What's going wrong here is that `'a` appears in the input types, just in an uncontrained position, and so our early-bound checks get confused.

**Comment by nikomatsakis** [comment]
I'll try to prep a full fix, I think, @dtolnay's example convinces me that this is a bug.

**Comment by nikomatsakis** [comment]
Huh. It appears that the code is *trying* to do the right thing here, actually. The problem is that the `resolve_lifetime` code runs before type-aliases are expanded, and so it (incorrectly) considers the `'a` in `X<'a>` to be constrained by `X<'a>`. Pain in the neck. I suppose we could expand type aliases in the `resolve_lifetime` code as well.

**Comment by nikomatsakis** [comment]
(Or, better, make some kind of query that we can use for a def-id to tell which of its substs are constrained; for a type definition, this would be all of them, but for a type alias it would check the definition.)

**Comment by eddyb** [comment]
Wait, why would `resolve_lifetime` care about type aliases? Since we want to eventually use projections for them anyway, riiight? Is this about early vs late? Can't we somehow defer that?

**Comment by nikomatsakis** [comment]
Ugh. Solving this properly is a horrible pain in the ass.

> Is this about early vs late? 

Yes it is.

> Can't we somehow defer that?

Maybe, I'm going to investigate that tomorrow I suppose, because unfolding the type aliases basically amounts to a specialized re-implementation of lifetime resolution (perhaps factoring out into the "map lifetime name to def-id" part that we've talked about would help here, not sure, but that's its own job).

**Comment by nikomatsakis** [comment]
However, deferring that would be also quite annoying. It's very nice the way it is now =)

**Comment by nikomatsakis** [comment]
Specifically, the problem is this code:

https://github.com/rust-lang/rust/blob/def3269a71be2e737cad27418a3dad9f5bd6cd32/src/librustc/middle/resolve_lifetime.rs#L2284-L2291

which treats all type parameters to something like `X<'a>` as constrained.

**Comment by nikomatsakis** [comment]
triage: P-medium

This is not a **burning problem** right now, but it's a definite bug. I'm thinking about trying to mentor out (or do) some refactorings that would make a proper fix more feasible.

**Comment by estebank** [comment]
Current output no longer ICEs but is still rejected:

```
error[E0581]: return type references an anonymous lifetime which is not constrained by the fn input types
 --> src/main.rs:1:15
  |
1 | fn f(_: X) -> X {
  |               ^
  |
  = note: lifetimes appearing in an associated type are not considered constrained
```

**Comment by Xiphoseer** [comment]
Is this issue the reason why in [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1fa87fdb26b14d27a7f502de20350284), line 45 compiles but line 52 produces an error?

**Comment by marmeladema** [comment]
Hi!
In a discussion around lifetime-only GAT not really requiring GAT, @steffahn ended up sharing this code: https://gist.github.com/rust-play/a050229041bd8924c1891ab4756827d7#file-playground-rs-L72

```Rust
impl ValueOperationWithGat for Box<dyn for<'e> Fn(&'e ExecutionContext<'e>) -> Value<'e>> {
    #[inline]
    // the 'e: 'e works around a compiler bug
    fn execute<'e: 'e>(&self, ctx: ExecutionContextOf<'e, Self>) -> Value<'e> {
        (self)(ctx)
    }
}
```

We believe it's another instance of this bug! If you just introduce the `<'e>` lifetime, you get this error:
```
error[[E0581]](https://doc.rust-lang.org/stable/error-index.html#E0581): return type references lifetime `'e`, which is not constrained by the fn input types
  [--> src/main.rs:73:65
](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a050229041bd8924c1891ab4756827d7#)   |
73 |     fn execute<'e>(&self, ctx: ExecutionContextOf<'e, Self>) -> Value<'e> {
   |                                                                 ^^^^^^^^^

For more information about this error, try `rustc --explain E0581`.
```
Is there a path forward to fix it?
