### ISSUE TITLE
Size of structs changed in the latest beta

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#47621]
Apparenty, there was a change somewhere in the latest beta that resulted in a change of size of some structs with `#[repr(packed)]`, because (for example) the [eep](https://crates.io/crates/eep) crate now fails to compile on the latest beta with a bunch of errors like this one (while being fine on stable):

```
error[E0512]: transmute called with types of different sizes
   --> src/ring_buffer.rs:101:40
    |
101 |         let entry: [u8; 65] = unsafe { mem::transmute(entry) };
    |                                        ^^^^^^^^^^^^^^
    |
    = note: source type: ring_buffer::Entry<T> (456 bits)
    = note: target type: [u8; 65] (520 bits)
```

[Implementation of the struct in question](https://github.com/fitzgen/eep/blob/065eafbc35afcd513427248d0eeee12e456175e5/src/ring_buffer.rs#L229-L239).

* [eep](https://crates.io/crates/eep) regressed from stable to beta ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/eep-0.1.0/log.txt))

cc @fitzgen

**Comment by bstrie** [comment]
It looks like the type in question is marked as `repr(packed)`. Don't we only guarantee the size of a type when it's marked with `repr(C)`?

**Comment by rkruppe** [comment]
I think it's a very reasonable assumption that a packed struct's size is the sum of the fields' sizes (since a packed struct has no padding, and fields can't be combined due to the ability to take pointers to fields), though I don't know if we actually guarantee that right now. However, this struct contains some types that definitely don't have a guaranteed size. Most strikingly, the `why` field is `Option<(Option<ThreadId>, u32)>` (where `ThreadId` is a newtype around `usize`) which is subject to layout optimizations.

**Comment by dtolnay** [comment]
Whether or not we guarantee that the size of a `repr(packed)` struct is the sum of the field sizes, we definitely don't guarantee the size of `Option<(Option<ThreadId>, u32)>` so this is going to need to be fixed in the eep crate.

A more correct implementation could be:

```diff
- let entry: [u8; 65] = unsafe { mem::transmute(entry) };
- self.write(&entry);
+ let ptr = &entry as *const Entry<T> as *const u8;
+ let size = std::mem::size_of::<Entry<T>>();
+ let bytes = unsafe { std::slice::from_raw_parts(ptr, size) };
+ self.write(bytes);
```
