### ISSUE TITLE
possible compile-time regression

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#47742]
According to perf.rust-lang.org, rollup commit 51b0b3734cbd0ca58c8be3512d53fce2d95f40dd seems to have caused a big jump in the "Summary" numbers. However, scrolling down through the individual tests, we don't see that same jump mirrored anywhere else. Moreover, clicking on the commit in question [doesn't give the usual test-by-test breakdown, just an empty page](http://perf.rust-lang.org/compare.html?start=0b90e4e8cd068910f604f3e1fb5d03cc01f1658f&end=51b0b3734cbd0ca58c8be3512d53fce2d95f40dd&stat=wall-time). I'm guessing this is some sort of fluke, but it'd be great to have that confirmed.

(Also, what exactly do the summary numbers represent, anyway?)

cc @Mark-Simulacrum @rust-lang/compiler @rust-lang/infra

**Comment by nikomatsakis** [comment]
triage: P-high

We need to know what happened.

**Comment by kennytm** [comment]
This is likely just rust-lang-nursery/rustc-perf#178. Nothing to see here, move along.

**Comment by nikomatsakis** [comment]
Should we close? How "likely" :)

**Comment by kennytm** [comment]
Very likely given the commit hash, but I'll let @Mark-Simulacrum confirm ☺️

**Comment by Mark-Simulacrum** [comment]
I'll investigate. Assigned myself.

**Comment by Mark-Simulacrum** [comment]
We weren't compiling crates.io in either release or debug mode because `ring` failed to compile, after https://github.com/rust-lang/rust/pull/47298 was merged in the rollup PR crates.io began compiling, and so the summary numbers jumped up. I'm going to close this issue as nothing to be worried about. I'm working on a patch that'll allow this to be more visible in the compare view (instead of just breaking).
