### ISSUE TITLE
Building from rustc-beta-src.tar.xz fails on git commands

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#47754]
I'm trying to test Fedora builds of the current beta:

```
$ cat rustc-beta-src/version
1.24.0-beta.8 (ed9751a90 2018-01-23)
```

Rustbuild fails in `Build::beta_prerelease_version()`:

```
failed to execute command: "git" "ls-remote" "origin" "beta"
error: No such file or directory (os error 2)
```

With network access, `git ls-remote` *could* work with a URL instead of the missing `origin` remote.  However, the configuration we use for rpm builds is completely offline.  (Actually, I probably don't even have git in the build root at the moment, but I could add that.)

A few options:
- Just don't support `--release-channel=beta` with non-git sources. (status quo)
- If git fails, call the release `X.Y.Z-beta` without a prerelease version at all.
- Try to extract the prerelease version from the same `version` file I quoted above.
- Allow an environment variable or config option to set a prerelease version manually.

**Comment by kennytm** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
Oops, sorry about that! I think even if we had a url it'd fail later because it wants to find the diff between the origin's branches and the local revision, but with the tarballs there's no local revision!

I'd say we should just drop the prerelease number entirely from betas-build-from-tarballs perhaps? Having an optional env var override seems fine by me though!
