### ISSUE TITLE
"Unreachable pattern" warning could be an error

### ISSUE THREAD

**Issue by Badel2** [rust-lang/rust#47811]
Why is "unreachable pattern" a warning and not an error? I found some discussion in the PR: https://github.com/rust-lang/rust/pull/19115 but that was in 2014.

I'm specially concerned about the following use case: [Playground](https://play.rust-lang.org/?gist=47d0b46906b29e12c4499d053c73cd5a&version=stable)

```rust
pub enum Bit {
    L,
    H,
}

fn from(x: Bit) -> u8 {
    match x {
        L => 0,
        H => 1,
    }
}
```

That code throws 8 warnings at me, but I would prefer it to not compile. [I also found a similar problem in stackoverflow.](https://stackoverflow.com/questions/44889689/why-does-match-not-work-while-partialeq-eq-works-fine) I think it's important to make this a clear error so beginners don't get confused.

**Comment by scottmcm** [comment]
Hmm, it looks like ``` warning[E0170]: pattern binding `L` is named the same as one of the variants of the type `Bit` ``` isn't a lint so one can't even choose to `deny` it?

Generally, as I understand it, Rust doesn't make things like unreachable code an error by default because sometimes they happen intentionally while in the middle of writing something, and the error is sufficient as a brain nudge.  I'd personally be good with making the "binding is the same as a variant" lint deny-by-default, though, since that's almost certainly a brain fart.

**Comment by Badel2** [comment]
I'm closing this since you can just `#![deny(unreachable_patterns)]`, however making the "binding is the same as a variant" lint deny-by-default looks like a good idea, maybe we can do it on the next edition?
