### ISSUE TITLE
Add auto-fixable suggestion to remove unused imports

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust#47888]
Warnings like the following should contain information in their diagnostics output that allows rustfix to remove the unused import.

```
warning: unused import: `std::io::prelude::*`
  --> src/tiso/tiso_msg.rs:10:5
   |
10 | use std::io::prelude::*;
   |     ^^^^^^^^^^^^^^^^^^^

warning: unused import: `std::fmt`
  --> src/tiso/tiso_msg.rs:13:5
   |
13 | use std::fmt;
   |     ^^^^^^^^
```

The strategy is to suggest replacing the unused import with an empty string. There are two cases:

- Are all items in the `use` statement unused (e.g., `std::fs` in `use std::fs;` is unused)? Then remove the whole `use` statement.
- Are only some of the items imported by the `use` statement unused (e.g., `File` in `use std::fs::{File, copy};` is unused)? Remove only these items but keep the `use` statement.

A quick search found this relevant file in typeck:

https://github.com/rust-lang/rust/blob/70517540dad71801a2ab903fb91d3e0c7406f115/src/librustc_typeck/check_unused.rs#L27-L46

Originally opened as <https://github.com/killercup/rustfix/issues/56>.

**Comment by JJJollyjim** [comment]
I'm taking a shot at writing this - it's my first attempt at touching rustc so there's a 50/50 chance that anything will come of it :)

**Comment by JJJollyjim** [comment]
My thinking on various edge cases:

When we encounter multiple unused items, like so:

```rust
warning: unused imports: `io`, `net`
 --> src/main.rs:1:22
  |
1 | use std::os::{unix::{io, net}, linux};
  |                      ^^  ^^^
  |
  = note: #[warn(unused_imports)] on by default
```
I'm assuming we want just a single suggestion with every unused item in this `use` tree removed.

In this case, should it be `use std::os::{linux};` or `use std::os::linux;`?

How about if we would end up with `unix::{self}`/`unix::self`?

```rust
warning: unused imports: `io`, `net`
 --> src/main.rs:1:22
  |
1 | use std::os::unix::{io, self};
  |                     ^^  
```

Should the `self` component be removed from the path?

**Comment by JJJollyjim** [comment]
One roadblock encountered, for these squiggly bracket situations:

**[skippable backgound]** There are two stages of unused import checking (documented [here](https://github.com/rust-lang/rust/blob/master/src/librustc_resolve/check_unused.rs#L12)). The first and main stage (in resolve) doesn't always have the knowledge to determine conclusively that an imported trait is actually unused. These candidates are saved for the later stage in typeck (the one killercup linked above).

---

A problem arises when an uncertain Trait import is alongside a concrete import in a single `use`: 

https://play.rust-lang.org/?gist=a08ec0cd799f258f2a1c371cc3ca2f4c&version=nightly

```rust
warning: unused imports: `Bar`, `Foo`
 --> src/main.rs:3:12
  |
3 | use test::{Bar, Foo, Trait1, Trait2, C};
  |            ^^^  ^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `Trait2`
 --> src/main.rs:3:30
  |
3 | use test::{Bar, Foo, Trait1, Trait2, C};
  |                              ^^^^^^
```

These problems are found at different times, thus they produce two different diagnostics. This means that we can't emit a single suggestion to resolve all these issues.

---

(The reason I am proposing emitting a single suggestion, aside from user-convenience, is so that we don't get conflicts applying two suggestions which both, say, remove a comma).

---

For now I will attempt to write a version which does not touch the uncertain traits, leaving them as is in the use.

**Comment by JJJollyjim** [comment]
Okay, I have a tested implementation [here](https://github.com/JJJollyjim/rust/commit/8f88a48222f9dcc279e6654ef00114e7020c4168), which does not touch late-decided trait imports. I will have a look tomorrow at would will be necessary to cover those cases as well.

**Comment by euclio** [comment]
@JJJollyjim Any interest in reviving this?

**Comment by vors** [comment]
Oh please revive it, unused imports are killing me

**Comment by JJJollyjim** [comment]
@vors apparently someone else finished it

**Comment by JJJollyjim** [comment]
I had been working on it still, I will have a look at @pietroalbini's code later to see if there's anything I can contribute from my verison

**Comment by pietroalbini** [comment]
Yeah, the problem at the moment is that cargo and rustfix won't accept more suggestions from the same error messages due to a corner case in diagnostics emitting, so it's not possible at all to fix most of the unused_import warnings. I'll try to get things moving at the All Hands this week.

**Comment by pietroalbini** [comment]
The issue about the corner case is https://github.com/rust-lang/rust/issues/53934.

**Comment by steveklabnik** [comment]
Hit this today.

**Comment by xue8** [comment]
Is there any progress on this issue?

**Comment by xue8** [comment]
Is there any progress on this issue?

**Comment by estebank** [comment]
This is fixed by now, as evidenced by the test added at https://github.com/rust-lang/rust/pull/120305/files#diff-cc1a791dd6a817de22fa7682b0d02a9247d789ae615c849893375af8f3a1c805
