### ISSUE TITLE
overflowing_literals should be strict error

### ISSUE THREAD

**Issue by g0ddest** [rust-lang/rust#47979]
Tried this code:
```
fn main() {
    let a = 1234567890123;
    println!("{}", a);
}
```
I've got result on a: `1912276171`
I see `#[warn(overflowing_literals)]` but I think it should be error because I have unuseable garbage in my variable.

**Comment by sgrif** [comment]
I believe this would require an RFC at minimum. That said, making this lint deny by default would make code in the wild break for very little gain. I agree with you that it should be an error, but I don't personally think it is worth the cost to change it at this point.

**Comment by scottmcm** [comment]
@sgrif Can you give an example of a place where the truncation is desirable?

Making code that's almost certainly not what you want be a deny-by-default lint seems perfectly reasonable to me.  One can always `#[allow]` it if for some reason you can't just put the right value...

**Comment by kpp** [comment]
Also it is possible for compiler to resize integer from 32 to 64 bits. Why does rustc try to fit literal in 32?

**Comment by scottmcm** [comment]
@kpp Because unconstrained-integral-literal fallback is always to `i32`.  Consistency (+lint) is probably better than some sort of "best fit" here, as a bigger literal meaning a bigger type would probably also need to mean that a smaller literal means a smaller type, which might then lead to `3*100` overflowing because they were considered to be `u8`, or `3*1000` failing with mixed (8- and 16-bit) types.

**Comment by kpp** [comment]
OK. Let literal integral always be i32, but instead of truncating I want to see compilation error.

**Comment by steveklabnik** [comment]
Yes, changes around lints need to be an RFC, including going from warn by default to error by default. Thank you!
