### ISSUE TITLE
Bug in rust automatic deref for methods of generic traits

### ISSUE THREAD

**Issue by porky11** [rust-lang/rust#48145]
Normally generics should just work like specialized versions, just substituted with the correct type.
For example `trait MyTrait<T> {…}` is intended to work for a type MyType as if I defined `trait MyTrait_MyType {…}`.
This doesn't apply, when one specialized version of a generic trait is implemented for a type T, which derefs to U, which implements a different specialization of the same trait.
Then the specialized version for T also shadows the specialized version for U, even if they could both be called on this type.

I made an example to show, what this means [here](https://play.rust-lang.org/?gist=63632a82df2ad0012d35adb92585a3bc&version=stable).

**Comment by estebank** [comment]
You can use the [fully qualified syntax](https://doc.rust-lang.org/book/second-edition/ch19-03-advanced-traits.html#fully-qualified-syntax-for-disambiguation), and [it will work](https://play.rust-lang.org/?gist=5479a93a0e362d33ca5724492aba4c54&version=nightly):

```
<IntegerList as AddElement<i16>>::add(&mut list, 1i16);
```

Agree that it is not completely ergonomic.

**Comment by ExpHP** [comment]
Sounds like an unavoidable consequence of rust's in-order type checker.  I don't think isn't any place in rust which handles this sort of polymorphism this well.

Basically, you've created a situation where it is not possible to express all of the possible signatures of `list.add` as a single generic function with `where` bounds. In a manner similar to function overloading, `list.add` has multiple signatures that can differ arbitrarily. This thwarts the type checker, which is otherwise normally able to do it's job without any direct help from type inference. (at least, this is my understanding)

I suspect that the actual [specialization feature](https://github.com/rust-lang/rust/issues/31844) faces problems like this as well.

**Comment by Enselic** [comment]
Triage: Since there is a way to make the code compile, I don't really see what other specific action to take here. Let's close.
