### ISSUE TITLE
Compiling for Cortex-M MCUs broken

### ISSUE THREAD

**Issue by therealprof** [rust-lang/rust#48182]
With the latest nightlies there's a severe regression in building firmwares for embedded MCUs:

> xargo build --release --example gpio_direct_blinky
>    Compiling microbit v0.3.3 (file:///Users/egger/OSS/microbit)
> DICompileUnit not listed in llvm.dbg.cu
> !2303 = distinct !DICompileUnit(language: DW_LANG_Rust, file: !3, producer: "clang LLVM (rustc version 1.25.0-nightly (16362c737 2018-02-12))", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !170, globals: !2304)
> LLVM ERROR: Broken module found, compilation aborted!
> error: Could not compile `microbit`.

The problem can be reproduced with my microbit crate at https://github.com:therealprof/microbit.git using the `xargo` commandline posted above.

**Comment by pietroalbini** [comment]
cc @alexcrichton, this seems to be related to llvm, maybe some fallout from the llvm 6 upgrade?

**Comment by alexcrichton** [comment]
Thanks for the report @therealprof! (and the cc @pietroalbini)

This came up during the LLVM 6 upgrade specifically for the wasm target actually. It came from [this area](https://github.com/rust-lang/rust/blob/4d2d3fc5dadf894a8ad709a5860a549f2c0b1032/src/librustc_trans/back/write.rs#L739-L758) where we called `llvm::LLVMCloneModule` which apparently caused *something* buggy to happen internally. I found that, for wasm, not calling `LLVMCloneModule` fixed the issue.

I believe the reason that `LLVMCloneModule` is called here is because either `--emit asm` is passed or an external assembler is being used rather than LLVM's. I'm not sure how to actually fix the problem though...

**Comment by therealprof** [comment]
@alexcrichton Nice catch! Indeed the culprit here seems the use of `--emit asm`. I can confirm that the problem is gone by removing that option.

**Comment by jonas-schievink** [comment]
Cannot reproduce on rustc 1.49.0-nightly (1773f60ea 2020-11-08) and https://github.com/therealprof/microbit/commit/afd51b5347256047d8d451b370c9417a2e0facf8 with

`xargo build --release --example gpio_direct_blinky`

Presumably the bug has been fixed by a newer LLVM version? Or do I need to pass other flags?

**Comment by therealprof** [comment]
Wow, this is still open? Yeah, I haven't seen that issue for years now, let's close it.
