### ISSUE TITLE
rustc panics given malformed attribute

### ISSUE THREAD

**Issue by darakshan** [rust-lang/rust#48387]
A typo in an attribute causes a compiler panic.  It is probably connected with the presence of 
#![plugin(rocket_codegen)]

I've reduced the offender to a tiny single .rs file and its Cargo.toml.
[Rust_bug.zip](https://github.com/rust-lang/rust/files/1742047/Rust_bug.zip)

**Comment by ExpHP** [comment]
## Further details

### The code snippet

It is short enough that it might as well be posted here:

```
#![feature(plugin, custom_derive, decl_macro)]
#![plugin(rocket_codegen)]

#[get"x"]
fn main() {
	print!("hello world")
}
```

**Note:** Commenting out the `#![plugin(rocket_codegen)]` line resolves the error.

### The error:

```
error: internal compiler error: Error constructed but not emitted
```

A DiagnosticBuilder is being dropped somewhere.  The question is, who created it?  Rustc or Rocket?  *(well, okay, it's _obviously_ gotta be Rocket, I just haven't been able to prove it yet)*

<details>
<summary>Backtrace (nightly channel)</summary>

```
error: internal compiler error: Error constructed but not emitted

thread 'rustc' panicked at 'explicit panic', librustc_errors/diagnostic_builder.rs:242:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
   6: <rustc_errors::diagnostic_builder::DiagnosticBuilder<'a> as core::ops::drop::Drop>::drop
   7: syntax::ext::expand::MacroExpander::expand_invoc
   8: syntax::ext::expand::MacroExpander::expand
   9: syntax::ext::expand::MacroExpander::expand_crate
  10: rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}
  11: rustc::util::common::time
  12: rustc_driver::driver::phase_2_configure_and_expand
  13: rustc_driver::driver::compile_input
  14: rustc_driver::run_compiler
```
</details>

(No sign of Rocket in the backtrace, though I'm not sure how much this helps as I don't know if a plugin would normally show up in the stack trace or not; also, there is lots of inlining)

I looked through the Rocket codegen plugin's source trying to brainstorm all sorts of ways that a drop of a DiagnosticBuilder might get hidden in the source code.  I did learn something, which is that *`PResult` is very scary!*...but I didn't find anything. :V

---

*(I can picture it now; the compiler blows up just moments before printing the actual error message it was supposed to print, because somebody wrote `result.unwrap_or_else(|_| cx.span_fatal(span, "something else"))`...)*
