### ISSUE TITLE
[Rustdoc] Show #[must_use] on functions

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#48485]
As it's important information about the function, Rustdoc should show that the result of the function must be used.

**Comment by GuillaumeGomez** [comment]
Adding it.

**Comment by GuillaumeGomez** [comment]
Hum actually, how would the function show that the returned type should be used?

cc @rust-lang/docs

**Comment by frewsxcv** [comment]
Some history: https://github.com/rust-lang/rust/issues/37012

**Comment by QuietMisdreavus** [comment]
I imagine, for bare functions, the `#[must_use]` attribute would be shown the same way as attributes are shown on structs. The problem comes in on associated methods on structs and traits. They don't have the same visual language as bare functions do, but they can get `#[must_use]` attributes the same way.
