### ISSUE TITLE
Cannot use function impl'd under enum

### ISSUE THREAD

**Issue by rickyhan** [rust-lang/rust#48530]
```rust
enum Bug {}

impl Bug {
  fn bar() {}
}

fn main() {
  use Bug::bar; // error
  bar();
}
```

Is it expected behavior?

**Comment by petrochenkov** [comment]
This is expected, items from `impl`s cannot be imported with `use`.

The reason is implementation complexity, compiler has to process `use` items before type information is available and `Bug::bar` needs type information to be resolved.
There's a chance this will be supported (with limitations), but now it doesn't work.
