### ISSUE TITLE
Most of UI tests are now compiled twice, once with `--error-format json` and once with `--error-format human`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#48550]
The change was made in https://github.com/rust-lang/rust/pull/48337
cc @GuillaumeGomez 

This is not helpful for our testing times, especially given that number of UI tests will grow due to other test categories being converted to UI.

**Comment by GuillaumeGomez** [comment]
Yep, sorry about that. However, if I didn't do this, the output was broken (because we'd have multiple useless "rustc --explain" sentences). If anyone has a better idea, it'd be very appreciated!

**Comment by GuillaumeGomez** [comment]
Actually, for the moment we only rely on the json error output. Add a new check over the "normal" error output would allow us to greatly reduce the ui tests duration.

**Comment by zackmdavis** [comment]
@GuillaumeGomez 

> if I didn't do this, the output was broken (because we'd have multiple useless "rustc --explain" sentences).

Can you be more specific about what the problem was exactly? Intuitively, I wouldn't expect printing one or two extra lines after the errors to require _any_ changes to the UI test framework itself.

**Comment by zackmdavis** [comment]
I have a branch which reverts a4dd670. And indeed, when outputting for humans, we see the message about `--explain` just once, but in JSON mode, it appears once _per error_. It _looks like_ this is because the message is being printed inside of `EmitterWriter`'s `.drop()` method (!), and the JSON emitter [itself instantiates an `EmitterWriter`](https://github.com/rust-lang/rust/blob/89e5a0796e0c5de52cd1d6c7541e5c2c7c47f2cd/src/libsyntax/json.rs#L209-L210) when creating a `Diagnostic` from a `DiagnosticBuilder`.

**Comment by zackmdavis** [comment]
I need to sleep now, but I'd like to put together a PR tomorrow

**Comment by zackmdavis** [comment]
I'm pretty confident that we want to revert #48337: printing the `--explain` usage message inside of `EmitterWriter.drop` was not an adequate solution (because it's counterintuitive to be doing non-cleanup work in `.drop`, the unintended additional messages for every diagnostic in the JSON output were undesirable, and changing the test framework in response to that unintended undesirable thing is also undesirable).

I was _hoping_ that, in order to avoid another enormous UI test output diff (which could potentially slow down the rest of the queue), it would be easy to reimplement the `--explain` usage message near where we issue the "aborting after _n_ errors" message, without changing the output: then we would only have one more enormous UI test output diff when we edit the wording (#48559). But outputting the `--explain` usage message along with the "aborting after _n_ errors" message in the `Handler` is looking somewhat less trivial that it sounds, because `Handler` doesn't seem to have direct access to an output stream where we can write some arbitrarily lines; it just has an [`Emitter` trait object](https://github.com/rust-lang/rust/blob/0ff9872b2280009f094af0df3dcdc542cc46a5fd/src/librustc_errors/lib.rs#L263) whose sole method (`emit`) can only take a `DiagnosticBuilder`. No doubt we could formulate the `--explain` message that we want in the form of a diagnostic (or come up with some alternative solution), but I wouldn't want to block on that.

**Comment by petrochenkov** [comment]
Fixed in #48684
