### ISSUE TITLE
Tracking issue for hexadecimal integers with fmt::Debug output

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#48584]
This is a tracking issue for https://github.com/rust-lang/rfcs/pull/2226, @SimonSapin mind filling in some details here?

**Comment by SimonSapin** [comment]
Implementation PR: https://github.com/rust-lang/rust/pull/48978

In formatting strings (in `format!` and related macros), this adds two "formatting types" `x?` and `X?` (in addition to the existing `x`, `?`, `p`, etc) that make integers be formatted in (lower- or upper-case) hexadecimal with the `fmt::Debug` trait. This is useful when a composite type implements `fmt::Debug` (for example a `struct` with `#[derive(Debug)]`) but not `fmt::LowerHex` or `fmt::UpperHex`, and contains integers or a slice of integers or a byte string.

For example:

```rust
assert!(format!("{:02x?}", b"Foo\0") == "[46, 6f, 6f, 00]");
assert!(format!("{:02X?}", b"Foo\0") == "[46, 6F, 6F, 00]");
```

**Comment by shepmaster** [comment]
I assume this should be closed now that it's shipped in 1.26.0 stable?

**Comment by TyPR124** [comment]
Is there still intent to make the debug_upper_hex and debug_lower_hex flags public? See: https://github.com/rust-lang/rust/blob/ef92009c1dbe2750f1d24a6619b827721fb49749/src/libcore/fmt/mod.rs#L1743-L1751

I would find these useful.

**Comment by Kimundi** [comment]
I just "rediscovered" these `{:x?}` formatting options. A short summary of the history here:

- https://github.com/rust-lang/rfcs/pull/2226 proposed this feature, including:
  - grammar changes to the formatting syntax to account for the new `radix` position where the `x` gets inserted in `{:x?}`
  - new fmt::Formatter APIs for querying that value
  - extension of the Debug impl for integers to conditionally delegate to fmt::LowerHex or fmt::UpperHex if this is set.
- Discussion on the original RFC thread lead to open questions about how to design the Formatter API in a way that is future-proof with possible other extensions like this.
- As reaction to that, it got implemented in https://github.com/rust-lang/rust/pull/48978 without public Formatter API changes.

However, as a result of this the discoverability of this feature is kinda bad, as the only way to know about it is to read the two lines in std::fmt's docs that talk about it. Otherwise it's completely internal magic hidden between the Formatter type and Debug impls for integers, that can not be externally used for something else, and is thus completley invisible in the API.

This is also confusing because the syntax section in std::fmt's docs never got updated with the new grammar.
