### ISSUE TITLE
Re-exporting items using a glob breaks if the module imports another module

### ISSUE THREAD

**Issue by z0w0** [rust-lang/rust#4865]
```rust
priv mod say {
	pub fn hello() { io::println(~"hello"); }
}

pub mod hello {
	use say;

	pub fn hello() {
		say::hello();
	}
}

pub use hello::*; // doesn't work - `pub use hello::hello;` does

fn main() {
	hello();
}
```

Results in this error when compiling:
```
error: failed to resolve imports
a.rs:13:8: 13:17 error: unresolved import
a.rs:13 pub use hello::*; // doesn't work - `pub use hello::hello;` does
                ^~~~~~~~~
a.rs:6:5: 6:9 error: unresolved import
a.rs:6 	use say;
            ^~~~
```

As mentioned in the code, explicitly re-exporting items works but is not a good alternative for when you have hundreds of items (including variants) in a module. Changing the say module to public doesn't fix it.

**Comment by steveklabnik** [comment]
Triage: globs are un-feature gated, but this issue still persists.

**Comment by steveklabnik** [comment]
Re-nominating because of that

**Comment by pnkfelix** [comment]
polish issue, 1.0 P-high.  (Note that we believe this and other glob bugs we know of are "only" rejecting valid programs, and thus the associated bug can be fixed backwards compatibly.)

If someone knows of a case where an invalid program is accepted due to glob bugs, that would be much more severe.

**Comment by pnkfelix** [comment]
P-high 1.1

**Comment by kali** [comment]
I reached this point while reducing an issue, I think it is the same problem, and the testcase is somewhat simpler.

```
pub mod a {
  use b::*;
}

pub mod b {
  use a::*;
}

use a::*;

fn main() {
}
```

**Comment by gbersac** [comment]
Still apply. [Spend two days getting mad because of this bug](http://stackoverflow.com/questions/30004569/circular-depency-between-modules-error/30007409?noredirect=1#comment48149420_30007409).  Note that there is no need for the modules to reference each others directly :

```rust
pub mod a {
    use b::fn_b;
    use c::*;

    pub fn fn_a(){
    }
}

pub mod b {
    use a::fn_a;
    use c::*;

    pub fn fn_b(){
    }
}

pub mod c{
    pub fn fn_c(){
    }
}

use a::fn_a;
use b::fn_b;

fn main() {
}
```

Here the star imports (mod::*) are not the modules themself, but another module, the module c.

**Comment by pnkfelix** [comment]
@gbersac 's test case seems especially frustrating; as he noted, the reported error is for imports that are not glob imports, and yet for some reason the presence of the unrelated glob imports is causing the resolution of the circular non-glob imports to fail.

**Comment by brson** [comment]
The final case here is solved by https://github.com/rust-lang/rust/pull/26242
