### ISSUE TITLE
[NLL] ICE: unexpected region for local data with reference to closure

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/rust#48697]
The following code gives an internal compiler error. It is a normal compiler error without NLL.

```rust
#![feature(nll)]

fn foo(x: &i32) -> &i32 {
    let z = 4;
    let f = &|y| { y };
    let k = f(&z);
    f(x)
}

fn main() {}
```

```text
error: internal compiler error: unexpected region for local data ReFree(DefId(0/0:3 ~ example[8787]::foo[0]), BrAnon(0))
 --> <source>:9:17
  |
6 |     let k = f(&z);
  |                ^
error: aborting due to previous error
Compiler returned: 101
```

**Comment by nikomatsakis** [comment]
This is a side-effect, I believe, of the hacky-ish way that we are enabling NLL while still running the old borrow check. In particular, this ICE originates from the **old** borrow check, I believe caused because we suppressed an error from the **old** region check (in favor of the new NLL check). We ought to be skipping the old borrow checker as well when NLL is enabled; but we can't do that until the `unused_mut` work that @KiChjang is working on is complete, I believe, since the borrow checker is still used to track which mut declarations are used. Maybe I can make it swallow the ICE though.

**Comment by KiChjang** [comment]
Work is tracked on this PR: https://github.com/rust-lang/rust/pull/48605.

**Comment by nikomatsakis** [comment]
I have a simple fix for the ICE in the meantime.

**Comment by nikomatsakis** [comment]
Looks like #53349 was merged, closing
