### ISSUE TITLE
[Documentation] Expand collapsed implementation when clicking on indexed methods

### ISSUE THREAD

**Issue by pravic** [rust-lang/rust#48726]
Stable documentation (e.g. https://doc.rust-lang.org/stable/std/collections/hash_map/struct.HashMap.html): 

* Click on `[-]` to collapse everything
* Click on `iter` in [Methods section](https://doc.rust-lang.org/std/collections/hash_map/struct.HashMap.html#methods)

Page will be scrolled to the [pub fn iter](https://doc.rust-lang.org/stable/std/collections/hash_map/struct.HashMap.html#method.iter).

Nightly documentation (e.g. https://doc.rust-lang.org/nightly/std/collections/hash_map/struct.HashMap.html):

* Click on `[-]` to collapse everything
* Click on `iter` in [Methods section](https://doc.rust-lang.org/nightly/std/collections/hash_map/struct.HashMap.html#methods)

Nothing will happen, because the `iter` is inside a collapsed `impl<K, V, S> HashMap<K, V, S>` outer section.

**Comment by ehuss** [comment]
Another example:  Click the word `flush` in the description on the page https://doc.rust-lang.org/nightly/std/io/struct.BufWriter.html.  Nothing happens, making it appear that the link is broken.  Since trait impls are collapsed by default, AFAIK there is no way to properly link to them.

I'm guessing this would need to be implemented in `hashchange` and `autoCollapse`, and check if the block is hidden?
