### ISSUE TITLE
Tracking issue for reversing the bit pattern in an integer

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/rust#48763]
Tracking issue for the `reverse_bits` method implemented in #48573.

```rust
impl {integer} {
    pub fn reverse_bits(self) -> Self;
}
```

**Comment by SimonSapin** [comment]
Motivation from https://github.com/rust-lang/rust/pull/32798#issuecomment-207086053
> On ARM, there are dedicated instructions for reversing bits. The intrinsic would lower to a single `RBIT` instruction.

**Comment by zbentley** [comment]
I'm a user that would benefit from this being stabilized. No worries if I have to wait until an LLVM requirement version bump, though. We would benefit from it, but aren't in a position to contribute support, so we are happy to wait/offer testing or documentation help.

**Comment by raphaelcohn** [comment]
Just to add to this, these intrinsics are useful for formatting data that is represented bit reversed, such as the IEEE standard for bit-reversed MACs, token ring addresses, etc.

**Comment by nvzqz** [comment]
I'd really like to make use of this in my chess engine. What's the status on this?

**Comment by SimonSapin** [comment]
This thread or https://github.com/rust-lang/rust/pull/48573 do not show a serious issue as far as I can tell.

@rfcbot fcp merge

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/pull/48573#issuecomment-372971821 says
> keep in mind that the performance of LLVM's generic bitreverse solution can vary greatly depending on the types involved, your target architecture, and what the rest of your code does around it: https://bugs.llvm.org/show_bug.cgi?id=31810
>
> If your target has a bit reverse instruction (only ARMv8 as far as I know) then everything should be fine.

The linked bug has some discussion about changing the code emitted when there is not a dedicated instruction. That has not yet lead to an LLVM change, but it doesn’t seem serious enough to me that we shouldn’t expose this at all.

-----

Since we also have a `[T]::reserve(&mut self)` that works in place, it’s possible that someone assumes `reverse_bits ` does the same. So it could be good to add `#[must_use]` to these methods. @nvzqz, do you want to send a PR to do that?
