### ISSUE TITLE
Bundled LLD is not found when sysroot is changed

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#48772]
Since https://github.com/rust-lang/rust/pull/48125, a LLD binary is shipped with Rust. According to [this comment](https://github.com/rust-lang/rust/pull/48125#issuecomment-364689472), it can be used by specifying `"linker-flavor": "ld.lld"` in target specs. However, this fails when the sysroot is changed, for example when compiling for a custom target using `xargo`. The following error occurs:

```
error: linker `lld` not found
  |
  = note: No such file or directory (os error 2)
```
The problem is that the `lld` binary is part of the host sysroot (e.g. in `.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin` on linux), so Rust does not find it when the sysroot is changed.

**Comment by phil-opp** [comment]
Update: We now get the same error for Windows and Linux too (but it still works on travis/appveyor).

**Comment by phil-opp** [comment]
Ok, it only works on CI because `lld` is in the default PATH on travis and appveyor.

**Comment by alexcrichton** [comment]
After some debugging with @steveklabnik I think this may be due to the use of xargo where the sysroot is changing so rustc's unable to find its original sysroot which contains lld

**Comment by phil-opp** [comment]
@alexcrichton Makes sense, thanks! I updated the issue title and description.

I wonder why `lld` is part of the sysroot in the first place. Is it target dependent somehow? Otherwise we could put it alongside the `rustc` and `cargo` executables, maybe as `rust-lld` (or alternatively in some subfolder not in `PATH`).

**Comment by alexcrichton** [comment]
Ah yeah currently it is in the sysroot to mirror the placement of other items like codegen backends and `gcc.exe` on Windows. We don't want to place it alongside rustc/cargo as it would otherwise pollute `PATH`. Additionally we want to still maintain it as a bit of an internal dependency for now which may change (but placing it in `PATH` may make it much harder to change later).

One of two changes need to happen here I think:

* Either xargo should be updated to symlink in the host target's directory into the custom sysroot it creates
* Or rustc's own logic for adding items to `PATH` should always add the original sysroot, even if a custom one is specified.

**Comment by japaric** [comment]
> Either xargo should be updated to symlink in the host target's directory into the custom sysroot it creates

We already do this in Xargo but we copy / hardlink / symlink only the lib directory, not the bin directory which is where lld is. I'd be happy to accept a PR that adds the bin directory to Xargo's copy of the host / original sysroot.

> Or rustc's own logic for adding items to PATH should always add the original sysroot, even if a custom one is specified.

We'll probably have to do this if / when Xargo functionality gets added to Cargo since the last invocation will be `rustc --target $T --sysroot $S` and the plan I sketched in rust-lang/cargo#4959 is to *not* have a copy of the original sysroot in the target directory (we don't need the original sysroot when compiling build scripts, proc macros, compiler plugins, etc. for the host because we never pass `--sysroot` to rustc when compiling those).

**Comment by FenrirWolf** [comment]
I made a PR to xargo that seems to do the trick

**Comment by steveklabnik** [comment]
So, now that new xargo is released, should we close this?

**Comment by phil-opp** [comment]
The issue is resolved by the new `xargo` version, so I'm going to close this.
