### ISSUE TITLE
Vulnerability to attacks because there is no size limit

### ISSUE THREAD

**Issue by BijanVan** [rust-lang/rust#48788]
https://github.com/rust-lang/rust/blob/2789b067da2ac921b86199bde21dd231ace1da39/src/libstd/io/stdio.rs#L274

read_line function seems vulnerable to attack. If an attacker sends data continually without "\r\n" the size of buffer (String) would keep growing without a limit.
[tokio](https://github.com/tokio-rs/tokio/issues/186)

**Comment by nagisa** [comment]
This is a function on the standard input though? What is the threat model? That you DoS your own computer?

**Comment by BijanVan** [comment]
That is not limited to Tokio. TcpStream from standard library could be wrapped by BufReader.
Here is an example:

`use std::io::{BufRead, BufReader};
use std::net::TcpListener;

fn main() {
    let listener = TcpListener::bind("localhost:8080").unwrap();

    for stream in listener.incoming() {
        let mut stream = stream.unwrap();
        let mut string_buf = String::new();
        let mut reader = BufReader::new(stream);
        let line = reader.read_line(&mut string_buf);
    }
}
`

**Comment by Mark-Simulacrum** [comment]
This somewhat feels like something the user should be aware of. It's also not clear to me that there's much we can/should do about this -- an arbitrary limit on our side would be decidedly odd (and potentially break some use cases). Users using and of the `read` methods should be aware that they are both blocking and may not return (ever, potentially). This seems semi-obvious to me... but perhaps we could clarify it in documentation.

**Comment by BijanVan** [comment]
I guess adding
`fn read_line(&mut self, buf: &mut String, max_length: usize) -> Result`
in addition to:
`fn read_line(&mut self, buf: &mut String) -> Result`
would not break anything.

**Comment by Mark-Simulacrum** [comment]
That should be done via [`Read::take`](https://doc.rust-lang.org/nightly/std/io/trait.Read.html#method.take), so I'm not sure that it's entirely useful. Anyway, it almost seems like this is a *too* specific thing to add - in most cases, I'd imagine that if you want to limit the potential line length, you'd want a different return type, among maybe other things. Since I'd imagine they'd be fairly specific to each use case it seems easier for users to implement that on their own via `read` or a similar call.

**Comment by alexcrichton** [comment]
We discussed this during libs triage today and the conclusion was that we didn't consider this a bug to fix in libstd but would of course be more than willing to update the documentation. As a result I'm reclassifying as a documentation issue.

**Comment by frewsxcv** [comment]
Note to future selves: if we put a note about this on `BufRead::read_line`, we should consider adding a note on [`BufRead::read_until`](https://doc.rust-lang.org/nightly/std/io/trait.BufRead.html#method.read_until) too since it's susceptible to the same issue

**Comment by poliorcetics** [comment]
If the added doc is deemed sufficient, this should be close, though I do not know who to ping for that.

**Comment by roolebo** [comment]
While many languages expose unbounded “read a line/token into a growable string” APIs, Go is notable in that its default, idiomatic API is bounded and fails fast instead of consuming unbounded memory. Consider this `readline.go` program:
```go
package main

import (
        "bufio"
        "fmt"
        "os"
)

func main() {
        scanner := bufio.NewScanner(os.Stdin)
        if scanner.Scan() {
                line := scanner.Text()
                fmt.Printf("%s\n", line)
        }

        if err := scanner.Err(); err != nil {
                fmt.Fprintln(os.Stderr, "reading standard input:", err)
        }
}
```
When fed unbounded input, it fails early with a clear error:
```
$ go build readline.go
$ ./readline < /dev/zero
reading standard input: bufio.Scanner: token too long
```

In contrast, the equivalent `readline.rs`  program:
```rust
use std::io;

fn main() {
    let mut line = String::new();

    io::stdin()
        .read_line(&mut line)
        .expect("Failed to read line");

    println!("{line}");
}
```

will continue allocating memory until the process is killed by the kernel OOM killer. On a large host, this can result in hundreds of gigabytes of memory being consumed:
```
$ rustc readline.rs
$ ./readline < /dev/zero
[1]    833676 killed     ./readline < /dev/zero
$ sudo dmesg | grep readline
[791613.936258] [ 833676]  1000 833676 67109673 53380366 53379312     1054         0 446369792  2299024             0 readline
[791613.936270] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=docker.service,mems_allowed=0-1,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/tmux-spawn-726fd620-49c7-49f1-8052-e1c0b4c7fbfe.scope,task=readline,pid=833676,uid=1000
[791613.936292] Out of memory: Killed process 833676 (readline) total-vm:268438692kB, anon-rss:213517248kB, file-rss:4216kB, shmem-rss:0kB, UID:1000 pgtables:435908kB oom_score_adj:0
[791625.889867] oom_reaper: reaped process 833676 (readline), now anon-rss:10548kB, file-rss:3256kB, shmem-rss:0kB
```

The current API makes it easy to accidentally write programs with unbounded memory consumption when processing malformed or adversarial input, which is a robustness and denial-of-service concern. I believe it would be beneficial if read_line had an upper bound on the amount of data it is willing to consume.

One possible migration path could be:
* introduce tooling support (e.g. a Clippy lint) warning about unbounded read_line usage and suggest an alternative;
* later, consider changes to the standard library API or defaults once the ecosystem has had time to adapt.

It should require more explicit effort to write unbounded programs.
