### ISSUE TITLE
Procedural Macros expanding macros by example vs. __rust_unstable_column()

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust#48781]
In [flamer](https://github.com/llogiq/flamer) and [overflower](https://github.com/llogiq/overflower), I expand `ExprMac`s when I find them so I can fold their expansion. However, this clashes with current libstd implementation of `assert!(..)` etc., because they use the __rust_unstable_column() macro, which, it appears, may not be called from outside libstd. This causes an error when trying to apply the procedural macro.

In general: Is there a way to get the macro expanded version of the code within a procedural macro? Do I need to register differently?

(Note: Since this only occurs with procedural macros, this is nightly-only).

**Comment by est31** [comment]
On the origins of why `__rust_unstable_column!()` exists: Once I've added column info to panic output and for this I was calling the `column!()` macro. But due to a gap in macros 1.0 hygiene this caused a regression (#43057). So we ended up adding and using the `__rust_unstable_column!()` macro instead.

I'm not very familiar with the capabilities of the procedural macro API but maybe you can just invoke the `column!()` macro instead of the `__rust_unstable_column!()` macro? It doesn't call the unstable column macro itself, but is rather built in, so it should work.

**Comment by est31** [comment]
Alternatively, you can try shadowing the `__rust_unstable_column` macro. As you are on nightly this should be no problem.

**Comment by llogiq** [comment]
Honestly, I'd just like to use the expansion of the macro. Ideally the expander would deal with it, leaving me to care about my procedural macro.

**Comment by est31** [comment]
IDK, I just want to avoid any kind of stabilisation of that macro which is a kludge and a hack but needed. Make sure it stays nightly only even if proc macros get stable.

**Comment by llogiq** [comment]
Agreed, and that should be possible without requiring proc macro authors to resort to kludges of their own. We just need to figure out how to let them expand macros like rustc.

**Comment by llogiq** [comment]
It appears [RFC #2320](https://github.com/rust-lang/rfcs/pull/2320) shows a way to resolve this.

**Comment by matklad** [comment]
Just a wild thought, but can we now use `$crate::column!` inside of libstd instead of `__rust_unstable_column` ?

**Comment by est31** [comment]
@matklad nice idea. It should work actually. You should try to make a PR and check whether the `issue-43057.rs ` unit test breaks or not.

**Comment by petrochenkov** [comment]
`__rust_unstable_column` is removed in https://github.com/rust-lang/rust/pull/63613.
