### ISSUE TITLE
Tracking issue for RFC 2169: Euclidean Modulo

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#49048]
Tracking issue for rust-lang/rfcs#2169, euclidean modulo methods on numbers

**Steps**:

- [x] Implementation (https://github.com/rust-lang/rust/pull/49389)
- [ ] Stabilization PR

**Comment by varkor** [comment]
@fanzier had expressed interest in implementing this RFC as a good starter issue ([most of the details are included in the RFC](https://github.com/rust-lang/rfcs/blob/master/text/2169-euclidean-modulo.md)), so I'd be happy to mentor this issue if they want to tackle it!

**Comment by KodrAus** [comment]
[A question came up in the initial implementation PR](https://github.com/rust-lang/rust/pull/49389#issuecomment-377067213) about shifting the euclidean modulo methods for `f32`/`f64` into `libcore` rather than `libstd`.

**Comment by sdroege** [comment]
`euc` as the function name seems a bit short. I didn't see that one before elsewhere, is it used in any other language? A longer, more descriptive name would seem useful.

**Comment by lfairy** [comment]
@huonw [made this argument](https://www.reddit.com/r/rust/comments/8d0ji1/this_week_in_rust_230/dxjif3t/) for a longer name, which I find convincing:

>Using just `euc` as a suffix seems a bit like Rust's abbreviation gone too far. For a common word like `Vec`, it makes sense in a huffman-encoding sense (length should be inversely proportional to frequency) and "vector" is common enough that it's relatively self-explanatory. But, performing Euclidean division is much less common, and "Euclidean" isn't that common as a word to begin with. At least for `mod`, it could be `mod_positive`, but something like `div_euclidean`/`mod_euclidean` does pair nicer.

**Comment by varkor** [comment]
@sdroege, @lfairy: I think the plan was to take another look at the method names during the FCP for these methods (which won't be for a while at least) — because there was some disagreement about what to prioritise for the naming here. With some actual usage statistics, it might be easier to form arguments one way or the other.

**Comment by xen0n** [comment]
Just my 2c: the suffix `euc` is woefully confusing for Asian users where "EUC" usually refers instead to a family of legacy charsets like EUC-JP or EUC-CN. Considering the expected frequency of usage a longer name *might* be more appropriate -- we'll have to see.

**Comment by pietroalbini** [comment]
There is an issue about the future compatibility lint of this: https://github.com/rust-lang/rust/issues/50232

**Comment by varkor** [comment]
@pietroalbini: I think that was an issue about the lint in general, rather than specifically about `mod_euc`; I've made a comment on the issue to clarify. Thanks!

**Comment by Boscop** [comment]
I really like the short name. Even knowing that "EUC" also refers to charsets, in this case it's disambiguated by the `mod_` part of the function name :) 
And anyone who stumbles across this function in 3rdparty code will see that it is called with numbers as args, so they can easily infer that it is "probably some kind of modulo" even if they don't know about euclidean modulo, but then they will look it up and find out! 
So IMO there's not really a high chance for confusion with the "EUC" charsets..

**Comment by clarcharr** [comment]
I didn't follow the original RFC, but I think that the methods should be `div_euc` and `rem_euc` for consistency with the `Rem` trait.

**Comment by clarcharr** [comment]
Another thing to note: while it has been mentioned before that having a `div_rem` method wouldn't make too much sense considering how LLVM automatically optimises nearby `x / y` and `x % y` calls to one operation, but I think it would be worthwhile to have a `div_rem_euc` method which is more efficient.

Although I don't know how far down the rabbit hole we'd want to go with that, considering how adding every combination of `checked`, `wraping`, and `overflowing` for `div_rem_euc` and `div_rem` would be around 8 new methods.

**Comment by demurgos** [comment]
Regarding terminology, I believe that `mod` (for modulo) was specifically chosen to refer the mathematical modulo and avoid confusion with the `rem` (remainder) operation available currently.

**Comment by clarcharr** [comment]
@demurgos Haskell uses the distinction quot/rem for the Euclidean versions and div/mod for the non-euclidean versions. I personally don't like this distinction and find it hard to remember, which is why I accept Rust's decision to simply append `_euc` to indicate Euclidean versions.

But if we're going to change rem to mod and not div to quot, that seems too odd to me. And besides, the ship has sailed and Rust is stuck with `rem` instead of `mod`. So, I'd say that `rem_euc` is a better name.

**Comment by clarcharr** [comment]
Also, I messed around with the code and `div_rem_euc` would be:

```
let (q, r) = (self / rhs, self % rhs);
if r < 0 {
    if rhs > 0 {
        (q - 1, r - rhs)
    } else {
        (q + 1, r + rhs)
    }
} else {
    (q, r)
}
```

versus the existing:

```
let q = if self % rhs < 0 {
    if rhs > 0 { self / rhs - 1 } else { self / rhs + 1 }
} else {
    q
};
let r = self % rhs;
let r = if r < 0 {
    if rhs < 0 {
        r - rhs
    } else {
        r + rhs
    }
} else {
    r
};
```

And I haven't run any benchmarks, but it seems pretty clear that even if LLVM can combine the existing division and remainder into one operation, it probably won't be smart enough to combine the branches. But, if we can write the latter in a way that optimises to the former, I think it'd be reasonable to say that a divrem method isn't necessary.

**Comment by tspiteri** [comment]
I don't think it should be hard for LLVM to find the common subexpressions. In fact, I get the same assembly for `div_mod_euc` and `separate_div_mod_euc` below; the only difference I found was in the labels.
```rust
pub fn div_mod_euc(lhs: i32, rhs: i32) -> (i32, i32) {
    let (q, r) = (lhs / rhs, lhs % rhs);
    if r < 0 {
        if rhs > 0 {
            (q - 1, r - rhs)
        } else {
            (q + 1, r + rhs)
        }
    } else {
        (q, r)
    }
}
```
```rust
pub fn separate_div_mod_euc(lhs: i32, rhs: i32) -> (i32, i32) {
    (div_euc(lhs, rhs), mod_euc(lhs, rhs))
}
pub fn div_euc(lhs: i32, rhs: i32) -> i32 {
    let (q, r) = (lhs / rhs, lhs % rhs);
    if r < 0 {
        if rhs > 0 {
            q - 1
        } else {
            q + 1
        }
    } else {
        q
    }
}
pub fn mod_euc(lhs: i32, rhs: i32) -> i32 {
    let r = lhs % rhs;
    if r < 0 {
        if rhs > 0 {
            r - rhs
        } else {
            r + rhs
        }
    } else {
        r
    }
}
```

**Comment by varkor** [comment]
> Haskell uses the distinction quot/rem for the Euclidean versions and div/mod for the non-euclidean versions. I personally don't like this distinction and find it hard to remember

Even though it can be annoying to have to remember the distinction, it's more helpful to follow convention and at least be unambiguous than mix terminology confusingly. Rust [originally used `Quot` and `Rem` too](https://github.com/rust-lang/rust/pull/5990), but `Quot` was later renamed to `Div` because it was more familiar. Unfortunately, this leaves us in an awkward state where one of the operators is named inconsistently. It's too late to change that now, though, so I think the best we can do is try to be correct going forward — hopefully the suffix makes it clear something different is going on.

> Another thing to note: while it has been mentioned before that having a div_rem method wouldn't make too much sense considering how LLVM automatically optimises nearby x / y and x % y calls to one operation, but I think it would be worthwhile to have a div_rem_euc method which is more efficient.

I was under the impression LLVM _doesn't_ optimise this as much as it could, but I haven't checked in a while, so that may be outdated. I think it could be worth having a dedicated method for this, and it's worth proposing (it wasn't part of the original RFC just to avoid too much bloat).

> Although I don't know how far down the rabbit hole we'd want to go with that, considering how adding every combination of checked, wraping, and overflowing for div_rem_euc and div_rem would be around 8 new methods.

Yeah, this method propagation is unfortunate, and it's unclear how to completely avoid it. Maybe just by adding the simplest methods first and then adding the others if/when people request them?

**Comment by anirudhb** [comment]
I would like to work on stabilizing this. One question: would it be stable since 1.27.1 or the next version?

**Comment by pietroalbini** [comment]
You should use the current nightly version when stabilizing (at the moment 1.29.0).

**Comment by anirudhb** [comment]
OK, thanks! I'll open a PR soon.

**Comment by daboross** [comment]
@clarcharr do you think you could elaborate on your concerns in https://github.com/rust-lang/rust/pull/52547#issuecomment-406647231?

It seems to me that the consensus is generally that `-5 remainder x` is negative and `-5 modulo y` is positive. As other's have said in this thread, the distinction was purposeful.

----

There's was already quite a bit of discussion in https://github.com/rust-lang/rfcs/pull/2169 that came up with the current names, `mod_euc` and `div_euc`, though. If the arguments there don't provide enough rationale for the current names, we could discuss more here.

But if there aren't further concerns, might I move to stabilize this again?

**Comment by ubsan** [comment]
@demurgos This is not a "mod operation", mathematically, this is a remainder operation. "mod operation" doesn't make sense - modular arithmetic is about equivalences, not operators.

**Comment by ubsan** [comment]
Also, the names are too short - `div_euclidean` is a much better name.

**Comment by varkor** [comment]
> This is not a "mod operation", mathematically, this is a remainder operation. "mod operation" doesn't make sense - modular arithmetic is about equivalences, not operators.

There [_is_ such a thing as a mod(ulo) operation](https://en.wikipedia.org/wiki/Modulo_operation). It's analogous to modular arithmetic, but it's a distinct concept.

> Also, the names are too short

This is exactly the point under discussion. Personally, I find the full `_euclidean` suffix to be too verbose, considering it's the most common choice for negative operands in many contexts (the RFC thread contains many examples).

**Comment by varkor** [comment]
I'm not sure why the mathematics versus programming distinction should be made, but even then, the definition for programming languages seems like the most appropriate anyway.

As you say, the precise definition is language-specific anyway, but:

> Remainder is what the rest of the ecosystem calls it, we should continue calling it remainder.

Rust chose the name "remainder" specifically because it produced negative results for negative dividends. This is either described in the commit history or the mailing list, but I don't have time to dig it up right now. (If I recall correctly, it used to be called "modulo" until it was changed for this reason.)

**Comment by ubsan** [comment]
@varkor that doesn't change the fact that even in CS, "mod" does not imply positive. It's only used that way, afaict, in Haskell - other languages use `mod` to just mean remainder.

**Comment by clarcharr** [comment]
I personally think that `_euclid` is a good suffix; it's not as verbose as `_euclidean` while still feeling natural and unambiguous. Additionally, even as a mathematically inclined person, I don't immediately read "euc" as "Euclidean," whereas I feel that even non-mathematically-inclined people would read "euclid" as "Euclidean."

As far as the distinction between "modulo" and "remainder," I feel like the most important distinction is that Rust currently uses "rem" to refer to the remainder of truncated division, rather than "mod." Because `div_euc` does not use any weird terminology compared to the regular `div`, it feels inconsistent to use `mod` instead of `rem` for `mod_euc`.

So to clarify, I think we should name the methods to `div_euclid` and `rem_euclid`.

That way, we have truncated division + remainder and Euclidean divison + remainder, rather than truncated division + remainder and Euclidean division + modulo.

**Comment by clarcharr** [comment]
Side note-- I really think that Rust should have somewhere in the documentation for `Div` that division is truncated, rather than floored. I don't know all of the places where this would be relevant, but I feel like having that officially clarified is important, considering how C used to have floored division and then changed.

**Comment by ubsan** [comment]
Can I fix the names of these functions? Will that be accepted?

**Comment by aaronfranke** [comment]
What about a modulus operator, perhaps `%%`, such that:

`5 %% 3` returns `2`  
`-5 %% 3` returns `1`  
`5 %% -3` returns `-1`  
`-5 %% -3` returns `-2`

The rule is that the output wraps around the second argument on a range `[0, b)`. If the first argument is already on said range it will be output with no change, such that `-2 %% -3` returns `-2`.

**Comment by varkor** [comment]
> I just noticed that the naming discussion is not closed

I think as of https://github.com/rust-lang/rust/pull/56936, consensus was reached.

> I would much prefer the suffix _floor over _euclid

As mentioned in the RFC, flooring division/modulo is different from Euclidean division/modulo (as described in [this paper](https://dl.acm.org/citation.cfm?doid=128861.128862)), which is why the name was chosen.

I'd rather avoid any more bikeshedding and put the functions forward for stabilisation.

**Comment by starblue** [comment]
Ah, I see, I missed that it behaves differently for negative divisors.

**Comment by clarcharr** [comment]
Irritatingly, rounding to negative infinity, positive infinity, zero, and absolute infinity are all different division methods, and so is

**Comment by crlf0710** [comment]
I think this is a good candidate for stabilization? Could any one propose a fcp for it?  @SimonSapin @alexcrichton

**Comment by est31** [comment]
@crlf0710 you can just file a PR for stabilization, should speed up the process.

**Comment by cmcqueen** [comment]
Is there a trait for `mod_euclid()`, for use with generics constraints?

**Comment by lambda-fairy** [comment]
I don't think so. The general policy for `std` is to do the minimum needed for operator overloading, and leave anything else to external crates (like `num`).
