### ISSUE TITLE
[rustdoc] Respect .editorconfig files for source view

### ISSUE THREAD

**Issue by fbruetting** [rust-lang/rust#49155]
`cargo doc` files currently show 8-spaces-wide tabs in source view. A general and portable approach for specifying editor settings of whole projects are `.editorconfig` files. Please respect that, for making sure that alignment doesn’t get destroyed and is the same as in the editor.

**Comment by QuietMisdreavus** [comment]
If rustdoc encounters files with tab characters in them, it should just pass them along to the final source page. It's the web browser which is displaying the tabs with 8-space width. Should rustdoc replace tab characters with a number of spaces based on an `.editorconfig` file? That seems like quite a bit of overhead.

**Comment by fbruetting** [comment]
Replacing tabs with spaces is not a good solution, in my opinion. It would be better to forward the `.editorconfig` tab setting to the browser. Can this be realized?

**Comment by QuietMisdreavus** [comment]
It looks like [it's possible to set the tab width](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size) in CSS, though it's currently "experimental" and isn't supported in IE/Edge. A small PR to set this to 4 (to match the [style guide](https://github.com/rust-lang/rfcs/pull/2436)) could be a quick first step, but i'm less certain on full `.editorconfig` support. It seems like overkill for a documentation tool to go and look at your text editor's configuration just because it displays source code. I wouldn't reject such a PR outright, but my personal opinion is that i won't prioritize it either.

@rust-lang/rustdoc (and possibly @rust-lang/dev-tools more generally) What do y'all think?

**Comment by steveklabnik** [comment]
I personally think this is far too much complexity for too little advantage.

**Comment by QuietMisdreavus** [comment]
I opened https://github.com/rust-lang/rust/pull/50947 to hardcode 4 for tab width.

**Comment by QuietMisdreavus** [comment]
With https://github.com/rust-lang/rust/pull/50947 merged, where does that leave this issue? Is `.editorconfig` support still that pressing for you, or can we go ahead and close this?

**Comment by fbruetting** [comment]
Fine, thanks!
