### ISSUE TITLE
Compile errors are no longer colorized

### ISSUE THREAD

**Issue by aloucks** [rust-lang/rust#49322]
Previously, the line numbers were in cyan and error codes and error underlines were in red.

Possibly related: https://github.com/rust-lang/rust/pull/48588

![image](https://user-images.githubusercontent.com/221559/37860135-c5777f12-2ef5-11e8-8b45-7f8607123b99.png)

**Comment by retep998** [comment]
cc @alexcrichton who wrote the likely offending PR.

**Comment by alexcrichton** [comment]
Thanks for the report @aloucks! This is almost for sure due to https://github.com/rust-lang/rust/pull/48588

The interesting part here is that it looks like rustc is detecting that it should use colors because somet of the messages look bold. It looks, though, like there may be a bug in how rustc is colorizing things as the wrong colors are coming out!

To confirm, @aloucks are you using `cmd.exe` as a shell here?

**Comment by aloucks** [comment]
@alexcrichton - Yes, the screen shot is using `cmd.exe`. I first noticed it from VSCode with the embedded powershell terminal. I noticed it was showing bold too. It is strange that it detects that it *should* use color, but doesn't apply it correctly.

**Comment by ehuss** [comment]
I did some investigation on this.  It looks like when you use both `bold` and `intense` that the color doesn't work.  It appears to be due to the fact that `termcolor` sets the color *before* issuing the bold VT100 command.  The Windows console currently does not support true "bold" fonts, and instead just shows a "bright" color.  It seems like setting "bold" is overriding the "intense" color.  I've noted a few other people having various issues with bold text at [Microsoft/console](https://github.com/Microsoft/console/issues).

@BurntSushi do you have any particular insight on this?  I did a quick fix by just moving the code to set bold to before the `write_color` in this function:  

https://github.com/BurntSushi/ripgrep/blob/d7c9323a689239ac8b29baba63b1c3a26e12afda/termcolor/src/lib.rs#L972-L987

I didn't do significant testing, but it seems to avoid the bold setting from overriding the color setting.

**Comment by BurntSushi** [comment]
@ehuss I don't have any special insight, no, but I do recall running into those sorts of problems when adding VT100 support for Windows. I can't remember the details. If re-arranging the ordering fixes things, then that seems like a fine thing to me. I'd be happy to take your patch!

**Comment by alexcrichton** [comment]
Oh awesome thanks so much for the fix here @ehuss! @BurntSushi mind publishing a new version of `termcolor` so we can test out the fix?

**Comment by BurntSushi** [comment]
Oh, errm, yeah I didn't mean to close this. I always forget that github does cross repo closes. In any case, `termcolor 0.3.6` is on crates.io!

**Comment by alexcrichton** [comment]
Awesome, thanks!

@ehuss want to send a PR I can r+? No worries if you're busy though!

**Comment by ehuss** [comment]
@alexcrichton sure!  I'd like to do a build first, but I'll post it soon!
