### ISSUE TITLE
Tracking issue for {HashMap, BTreeMap}::get_key_value stabilization

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#49347]
Implemented in #49346

**Comment by joshlf** [comment]
Any update on this? I'd like to use this on stable.

**Comment by CAD97** [comment]
Is anything keeping this from stabilization?

**Comment by ErichDonGubler** [comment]
Following up with what @Diggsey said, my summarized understanding is this: the `get_key_value` API for immutable access (which seems to be the entirety of what's being tracked here) seems to have borne no objections, but it was less clear if simply exposing an similar API that merely returns a tuple of mutable references and calling it `get_key_value_mut` would be preferred over reusing the `OccupiedEntry` API (i.e., returning `Option<OccupiedEntry<_, _>>`.

I don't see how the above influences this particular issue, so AFAICT there's nothing keeping this from stabilization at this point. @Diggsey, I don't know who else we could ping to get this pushed through...

**Comment by Diggsey** [comment]
I believe this needs someone from the @rust-lang/libs team to propose an "fcp merge", or is there something else I need to do here?

On a meta-note, this does seem to be a bit of a gap in the process, with almost 500 open tracking issues, some of which have been sitting around since 2013 and no indication of who is responsible for next steps... Compare to eg. https://github.com/rust-lang/rust/issues/60602 where the author is on the libs team and able to take a feature from implementation to stabilisation in a single release cycle.

If the stabilisation of this feature is simply not a priority, it would be nice to make that decision publicly.

**Comment by sfackler** [comment]
The general process is that people who care about a feature ask for it to be stabilized. If no one cares enough to ask about it, it's probably not going to be stabilized.

@rfcbot fcp merge

**Comment by SimonSapin** [comment]
@Diggsey I do sometimes look through https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AC-tracking-issue+label%3AT-libs and try to find tracking issues where there is nothing else left to do other than start FCP. If you do find some like that, feel free to ping someone in the team so that can do it. However in a lot of cases there are ongoing design discussions without a clear resolution. In some cases a tracking issue has many comments, and its not obvious whether or not all the issues that have been brought up are in fact resolved even though discussion has stalled. For those, it can be helpful to have someone read through the history of that feature (including potential other threads, like in an RFC or on internals.rlo), write up a summary comment, and propose a way forward.

**Comment by SimonSapin** [comment]
Oh and then there’s https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AC-tracking-issue+label%3Afinished-final-comment-period+label%3Adisposition-merge where the only thing left to do might be a stabilization PR (which anyone can submit). There are some false positives there, though.
