### ISSUE TITLE
The Rust Programming Language book doesn't clarify OS dependencies

### ISSUE THREAD

**Issue by pjhanzlik** [rust-lang/rust#49343]
Just tried to compile the Hello World example using ArchLinuxARM and got an "OS error 2" message basically saying Rust couldn't find g++ or clang++.  Turns out, of course, I didn't have either installed which is easy enough to fix, but I think the install section of The Rust Programming Language could be improved if the book listed OS dependencies not installed with "$ curl https://sh.rustup.rs -sSf | sh".  [Or maybe the script could check for essential dependencies and send out warnings?]

**Comment by steveklabnik** [comment]
Hi there! thanks for caring about the book.

The correct repo to file issues against is https://github.com/rust-lang/book, rather than this one. So, normally I'd ask to you re-file over there. However, in this case, we've recently changed the introduction to add some text about this:

> Finally, you’ll need a linker of some kind. It’s likely you already have one installed, but if you try to compile a Rust program and get errors telling you that a linker could not be executed, you’ll need to install one. You can install a C compiler, as that will usually come with the correct linker. Check your platform’s documentation for how to install a C compiler. Some common Rust packages depend on C code and will need a C compiler too, so it may be worth installing one now regardless.

https://doc.rust-lang.org/nightly/book/second-edition/ch01-01-installation.html

Thanks!

**Comment by pjhanzlik** [comment]
That's awesome, thanks Steve!
