### ISSUE TITLE
rustc has a stack overflow when using `impl Trait` of a trait with a generic parameter with a default type of Self

### ISSUE THREAD

**Issue by quininer** [rust-lang/rust#49376]
https://play.rust-lang.org/?gist=a827cb4bc9dd29324227e3ac676dd47a&version=nightly

```rust
#![crate_type = "rlib"] 
#![feature(conservative_impl_trait)]

struct Bar {}
trait Foo<T = Self> {}
impl Foo for Bar {}

fn foo() -> impl Foo {
    Bar {}
}
```

**Comment by matthewjasper** [comment]
I guess this should be erroring with [E0393](https://doc.rust-lang.org/error-index.html#E0393) or E0666 (nested impl trait is not allowed).

**Comment by shepmaster** [comment]
Continues crashing in 1.26 stable.

**Comment by shepmaster** [comment]
This does not crash:

```rust
struct Bar {}
trait Foo<T = i32> {}
impl Foo for Bar {}

fn foo() -> impl Foo {
    Bar {}
}

fn main() {}
```

**Comment by leodasvacas** [comment]
Particularly unfortunate because of `PartialEq` and `PartialOrd`.

What is going on here: There is a syntactical check to forbid `Self` in `impl Trait<Self>` because that is equivalent to a nested impl Trait which is forbidden. The default sneaks past the syntax check, so we probably have to check for that substitution after HIR lowering in type collection.

The overflow itself is caused [here](https://github.com/rust-lang/rust/blob/master/src/librustc_privacy/lib.rs#L946) but that won't matter once we fix the underlining issue.

I can take this myself unless someone wants mentorship or is just faster.
