### ISSUE TITLE
rustdoc doesn't link correctly to methods in trait implementations

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#49455]
https://doc.rust-lang.org/nightly/std/?search=until

-------

<img width="429" alt="screen shot 2018-03-28 at 3 14 37 pm" src="https://user-images.githubusercontent.com/416575/38031107-c35cda58-329a-11e8-848e-dc1f8dfc09f2.png">

**Comment by QuietMisdreavus** [comment]
The link anchors exist in the HTML, but they don't exist by default because the anchor is hidden by the automatic folding of trait implementations.

@GuillaumeGomez Should the search index links for trait implementations link to the trait impl itself now? Otherwise the link anchor goes nowhere and the user doesn't see where the method comes from.

**Comment by GuillaumeGomez** [comment]
I'll need to think about it.
