### ISSUE TITLE
rustdoc: Bad handling of proc_macro's re-exported via use_extern_macros

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#49553]
If you [define a proc-macro in one crate, then re-export it from another crate](https://github.com/nemo157/rustlang-rust-issue-49553/) via the `use_extern_macros` feature the [resulting documentation](https://nemo157.com/rustlang-rust-issue-49553/target/doc/proc_macro_re_export/index.html) does not link to the macro correctly, and the tooltip has some weird details displayed in it:

link: `../proc_macro_re_export_proc_macro/macro.%7B%7BGlobalMetaData::Krate%7D%7D.html`

![screen shot 2018-04-01 at 11 27 56 am](https://user-images.githubusercontent.com/81079/38171732-ca5e041e-359f-11e8-94f6-27207d7f8c05.png)

**Comment by QuietMisdreavus** [comment]
Still broken, looks like. Seems we'll need to properly document proc-macros, and handle their re-export, now.

Something that strikes me as odd is that the *original* crate shows the proc-macro as a function, and it's only when it's re-exported is it seen as a macro:

![image](https://user-images.githubusercontent.com/5217170/44549370-79be3e80-a6e6-11e8-83fc-b7513c146e44.png)

I think we'll need to handle the `#[proc_macro_attribute]` (and other proc-macro declaration attributes) when displaying these items. Then we'll need to see what happens when we get these as re-exports. I'm not too surprised that it still appears as a re-export, but i am curious what is causing it to mess up the link like that.

**Comment by QuietMisdreavus** [comment]
Update: It looks like the odd curly-brace segment of the link is gone, but the links are still broken because rustdoc is still treating proc-macros as functions in their source crate. Not sure what fixed that, but it means one less thing to figure out when fixing this for real.

**Comment by QuietMisdreavus** [comment]
I've opened https://github.com/rust-lang/rust/pull/54577 to make rustdoc properly document proc-macros, but there's a wrinkle that means their re-export is still a little awkward (though it's better than before).
