### ISSUE TITLE
Does it can have Rc or Refcell derive on some struct？Get full feafure of Rc or Refcell by default.

### ISSUE THREAD

**Issue by mokeyish** [rust-lang/rust#49578]
I want to make a strcuct have feafure of ```Rc``` or ```Refcell``` by default.
for example:
```rust
#[derive(Copy, Clone, Rc, RefCell)]
struct SampleA {
    ...
}
```
and we can use SampleA  with full feature of ```Rc ``` and ```Refcell ```after ```SampleA ::new() ```.

**Comment by warlord500** [comment]
I think if i understand your question right. your asking how to make a struct be reference counted and ref-cell by default?
  within current rust you can not enforce that a struct be always inside of reference counted pointer structure. 
there are  no direct limitations of what can be put inside of Reference counted pointer.
however some of the methods  can not be used if the type doesn't implement specific traits.
 
for your specific example to have sample A be reference counted and inside of a ref cell.  use the below code 
```rust
use  std::rc::Rc;
use  std::cell::RefCell;  //use imports the Rc and refCell structs for the module
rc::new(refcell::new(sampleA::new())
``` 
this question looks as to be written by a rust beginner, I would recommend for you redirect your questions to [#rust-beginners](https://client00.chat.mibbit.com/?server=irc.mozilla.org&channel=%23rust-beginners). if you have issues that are specific to the rust tool-chain then use GitHub issues.  otherwise redirect your questions to above link 

In addition, I would recommend you revise your questions before publishing them. you spelled struct wrong!
