### ISSUE TITLE
Remove str::is_whitespace and str::is_alphanumeric

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#49657]
These methods were added as stable in #49381 (currently in beta for 1.27.0) but we would prefer not to add them as discussed in https://github.com/rust-lang/rust/pull/49381#issuecomment-378519840.

**Comment by withoutboats** [comment]
Strongly prefer to have this method (unsurprisngly). I assumed it was an oversight that it was missing; I've probably tried `s.is_whitespace()` a half dozen times and then been surprised it was nightly only. I do not think it is at all surprising that this method has the same semantics of `.chars().all(|c| c.is_whitespace())`.

**Comment by oli-obk** [comment]
We could add a system to be able to add suggestions to missing method errors. Thus the use of `is_whitespace` would suggest `.chars().all(char::is_whitespace)`

**Comment by LukasKalbertodt** [comment]
@oli-obk I like this idea a lot! (independently from this discussion)

---

About `is_alphanumeric`: I think I prefer to remove `str::is_alphanumeric` as it might lead to subtle Unicode bugs. Example:

```rust
println!("{}", "böb".chars().all(char::is_alphanumeric));    // true
println!("{}", "böb".chars().all(char::is_alphanumeric));    // false
```

The second string uses a [Combining Diaeresis](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks) with an `o` instead of an `ö`. Sure, the explicit variant `chars().all(...)` also has this problem, but being explicit makes the bug a bit less subtle. Having `is_alphanumeric` on a string might suggest that the method "does the right thing" (whatever that is) instead of looking at characters individually. 

---

I think `str::is_whitespace` doesn't have a problem with subtle Unicode bugs, but I don't quite like the name: `is_whitespace` sounds singular to me and thus doesn't translate perfectly to a string. 

If you are interested, I did a bit of research how `.chars().all(char::is_whitespace)` is called in other languages (sometimes with libraries):

- Ruby on Rails: [`blank?`](http://api.rubyonrails.org/v4.2.6/classes/Object.html#method-i-blank-3F)
- Java (Apache Commons Lang): [`StringUtils.isBlank`](https://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/StringUtils.html#isBlank-java.lang.CharSequence-)
- Python: [`isspace`](https://docs.python.org/3.1/library/stdtypes.html#str.isspace)
- C# with .NET: [`IsNullOrWhiteSpace`](https://msdn.microsoft.com/en-us/library/system.string.isnullorwhitespace.aspx)
- I didn't find such a method for C++, JavaScript, Haskell, Swift and Go

Maybe **`str::is_blank`** is a better name for Rust?
