### ISSUE TITLE
Conflicting nonexistent implementation

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/rust#49754]
Types `Owned<Trait>` and `Owned<E>` are differ, but this error appears.
I try create convertion for my own small pointer.
```
error[E0119]: conflicting implementations of trait `core::convert::From<Owned<_>>` for type `Owned<_>`:
   --> mem\lib.rs:117:1
    |
117 | impl<Trait,E:core::marker::Unsize<Trait>> core::convert::From<Owned<E>> for Owned<Trait>{
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: conflicting implementation in crate `core`:
            - impl<T> core::convert::From<T> for T;
```

**Comment by jonas-schievink** [comment]
An impl conflicts as soon as it's possible to replace its type parameters in a way that creates a duplicate impl.

In this case, you'd need to set the type parameters `E` and `Trait` to the same type (let's call it `Ty`) to get `impl From<Owned<Ty>> for Owned<Ty>`, which conflicts with the blanket impl in `core` because you can set its type parameter `T` to `Owned<Ty>`, which also results in `impl From<Owned<Ty>> for Owned<Ty>`.

**Comment by aristarh2704** [comment]
How can I properly implement this trait?

**Comment by aristarh2704** [comment]
But type T does not implement Unsize<T>? True&

**Comment by jonas-schievink** [comment]
I don't know what you're trying to do, so I can't really help you. The [user forum](https://users.rust-lang.org/) might be a good place to ask.
