### ISSUE TITLE
-C panic=abort doesn't generate EHABI information on arm

### ISSUE THREAD

**Issue by makotokato** [rust-lang/rust#49867]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1453220

Gecko profiler uses EHABI information to walk stack.  But since rustc doesn't generate EHABI, it cannot walk stack on generated code by rust.

@glandium says, "-C panic=abort" causes that EHABI isn't emitted", so we need a option not to remove it (or don't remove EHABI even if -C panic=abort).

**Comment by glandium** [comment]
Note the same actually applies to EH_FRAME info on x86-64, which iirc the Firefox profiler also uses on x86-64. More generally, it can be desirable to have unwind info even when panic doesn't unwind.

**Comment by luser** [comment]
For C/C++ code in Firefox we use [`-funwind-tables`](https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html#index-funwind-tables) to ensure that the compiler generates these when `--enable-profiling` is on:
https://dxr.mozilla.org/mozilla-central/rev/0a2dae2d8cf9f628c55668514c54a23da446d5de/build/autoconf/frameptr.m4#12

The equivalent for x86-64 is [`-fasynchronous-unwind-tables`](https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html#index-fasynchronous-unwind-tables) which is apparently on by default.

It seems like having a compiler option to enable this would be good enough, since the behavior here mirrors what gcc does: only emit unwind info if needed for exceptions/unwinding.

**Comment by makotokato** [comment]
LLVM seems to turn on EHABI as default by https://reviews.llvm.org/D2627 (EnableARMEHABI is removed by this landing, but src/rustllvm/PassWrapper.cpp still has it)
https://github.com/rust-lang/rust/pull/40549 is similar issue for Win64 ABI.

**Comment by alexcrichton** [comment]
This may or may not be related to https://github.com/rust-lang/rust/pull/45031, but I can prepare a patch like https://github.com/rust-lang/rust/pull/40549 for the targets here. @makotokato do you know what targets are in use by Firefox and would need this treatment?
