### ISSUE TITLE
compiletest is misled by comments talking about src/test/run-pass/ dir

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#49860]
Discovered while working on #48879

Due to #49855 I am  forcing a number of tests without a `// run-pass` directive to explicitly always fall in any compilation mode.

I was surprised to discover one of the tests was emitting no errors but it wasn't one of the ones I had to force a failure on, and yet it was not tagged as `// run-pass`.

This was this test: https://github.com/rust-lang/rust/blob/master/src/test/ui/span/issue-23338-locals-die-before-temps-of-body.rs

The problem is that this occurs on line 14 of the test:

```
// Compare to run-pass/issue-23338-params-outlive-temps-of-body.rs
```

which AFAICT is probably matching some regexp in `compiletest` e.g. like `^//.*run-pass.*$`

**Comment by varkor** [comment]
Seems slightly odd, because the tests for `run-pass` seem to check this correctly:
https://github.com/rust-lang/rust/blob/0b72d48f8e5f3c7cabcf6fcd31474209bff0ab59/src/tools/compiletest/src/header.rs#L523-L525
https://github.com/rust-lang/rust/blob/0b72d48f8e5f3c7cabcf6fcd31474209bff0ab59/src/tools/compiletest/src/header.rs#L602-L609
And the check for the start of the line:
https://github.com/rust-lang/rust/blob/0b72d48f8e5f3c7cabcf6fcd31474209bff0ab59/src/tools/compiletest/src/header.rs#L439-L441

**Comment by pnkfelix** [comment]
Its possible that I misdiagnosed the reason that issue-23338-locals-die-before-temps-of-body.rs "worked" without adding `#[rustc_error]` in rust-lang/rust#49861

I'll try to dobule check.

**Comment by pnkfelix** [comment]
Ah, I see: I think I misinterpreted what's happening in issue-23338-locals-die-before-temps-of-body.rs 

Namely, the test isn't succeeding.

The compiler is ICE'ing!
