### ISSUE TITLE
Improve output of type mismatch due to lack of return value

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#50009]
When you have

```rust
fn foo() -> usize {
    ""
}
```

the diagnostic correctly points at the return value

```
error[E0308]: mismatched types
 --> src/main.rs:2:5
  |
1 | fn foo() -> usize {
  |             ----- expected `usize` because of return type
2 |     ""
  |     ^^ expected usize, found reference
  |
  = note: expected type `usize`
             found type `&'static str`
```

while if the error is due to not having a return value

```rust
fn bar() -> usize {
    3;
}
```
[the output is](https://play.rust-lang.org/?gist=75e45261f367f7fa576cab9a05aa846b&version=nightly)
```
error[E0308]: mismatched types
 --> src/main.rs:5:19
  |
5 |   fn bar() -> usize {
  |  ___________________^
6 | |     3;
  | |      - help: consider removing this semicolon
7 | | }
  | |_^ expected usize, found ()
  |
  = note: expected type `usize`
             found type `()`
```

It probably should be
```
error[E0308]: mismatched types
 --> src/main.rs:5:19
  |
5 |   fn bar() -> usize {
  |               ----- expected due to this return type
6 |     3;
  |     ^- help: consider removing this semicolon
  |     |
  |     expected usize, found ()
  |
  = note: expected type `usize`
             found type `()`
```

**Comment by estebank** [comment]
Alternative output

```
error[E0308]: mismatched types
 --> src/main.rs:5:19
  |
5 |   fn bar() -> usize {
  |   ----------------- this function doesn't return anything
6 |     3;
  |      - help: consider removing this semicolon
  |
  = note: expected type `usize`
             found type `()`
```

**Comment by ashtneoi** [comment]
I'm not sure if it has the same root cause, but there's a similar issue with `break` expressions. The code

```rust
fn foo() -> usize {
    loop {
        break;
    }
}
```

[gives this error](https://play.rust-lang.org/?gist=8ccd1eef94ee8ad98b8e4dc4ed849d54&version=stable):

```none
error[E0308]: mismatched types
 --> src/main.rs:3:9
  |
3 |         break;
  |         ^^^^^ expected (), found usize
  |
  = note: expected type `()`
             found type `usize`
```

I assume the error message points at the `break` expression because it could be changed to `break 7;` or something, but I don't think that's the first place the average user would consider putting a return value.

**Comment by kballard** [comment]
This issue is the biggest annoyance I have when using RLS to write Rust code in VSCode, as it causes the entire function to get highlighted as an error, which is very unhelpful. I've started having to adopt a style where I put a dummy statement at the end of the function before writing anything else just to suppress the error while I write the rest of the function, but it's rather annoying to deal with.
