### ISSUE TITLE
Borrow checker determines borrows by examining lifetime parameters on unexpanded associated types instead of inspecting their lifetime bounds

### ISSUE THREAD

**Issue by dylanede** [rust-lang/rust#50029]
Consider the following ([playpen](https://play.rust-lang.org/?gist=ec1b2f437ec978dd477a76046828699e&version=nightly)):

```rust
trait Foo<'a> {
    type Out: 'a;
}

fn foo<'a, T>(_: &'a mut T) -> <T as Foo<'a>>::Out where T : Foo<'a> {
    unimplemented!()
}

fn baz<T>(mut x: T) where for<'a> T : Foo<'a>, for<'a> <T as Foo<'a>>::Out : 'static {
    let y = foo(&mut x);
    let z = foo(&mut x);
}

fn main() {
    struct Bar;
    impl<'a> Foo<'a> for Bar {
        type Out = i32;
    }
    let mut b = Bar;
    let y = foo(&mut b);
    let z = foo(&mut b);
}
```

`main` compiles fine, as expected, since the associated type expands to `i32`, which does not use the lifetime `'a` that the mutable reference input argument is bound by.

`baz` however fails to compile (error message below), despite the additional constraint on `Out` to be `'static`, implying that the return value of `foo` does not borrow the argument.

```text
error[E0499]: cannot borrow `x` as mutable more than once at a time
  --> src/main.rs:11:22
   |
10 |     let y = foo(&mut x);
   |                      - first mutable borrow occurs here
11 |     let z = foo(&mut x);
   |                      ^ second mutable borrow occurs here
12 | }
   | - first borrow ends here
```

This problem appears to be unique to unexpanded associated types, as they are the only case where the lifetime parameters do not directly determine the lifetime bounds on the type.

**Comment by oskgo** [comment]
No longer reproduces. Fixed by #116733.

searched nightlies: from nightly-2023-05-23 to nightly-2024-01-23
regressed nightly: nightly-2023-10-30
searched commit range: https://github.com/rust-lang/rust/compare/e5cfc55477eceed1317a02189fdf77a4a98f2124...608e9682f0a6482903de8d3332770104a0ad943c
regressed commit: https://github.com/rust-lang/rust/commit/ec2b311914a4880235862f3cd65fe24e92e6d3a5

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.7</summary>


Host triple: x86_64-pc-windows-msvc
Reproduce with:
```bash
cargo bisect-rustc success --start=2023-05-23 --end=2024-01-23
```
</details>
