### ISSUE TITLE
Could not compile cssparser with features-await

### ISSUE THREAD

**Issue by Brooooooklyn** [rust-lang/rust#50099]
### Project to reproduce
https://github.com/Brooooooklyn/rust-err

### Reproduce Steps:
- run `cargo build`

- Error messages:

```
error: failed to run custom build command for `cssparser v0.23.5`
process didn't exit successfully: `/Users/longyinan/workspace/test/rusts/rust-err/target/debug/build/cssparser-d0b7ad1d7984b6be/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-cfg=rustc_has_pr45225

--- stderr
thread 'main' panicked at 'proc_macro::__internal::with_sess() called before set_parse_sess()!', libproc_macro/lib.rs:1319:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### OS Version
```
macOS 10.13.4 (17E199)
```

### Homebrew Version
```
Homebrew 1.6.0
Homebrew/homebrew-core (git revision 89315; last commit 2018-04-18)
```
### Rust Version
```
rustc 1.27.0-nightly (ac3c2288f 2018-04-18)
```

### Cargo Version
```
cargo 1.26.0-nightly (008c36908 2018-04-13)
```

### Clang Version
```
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by Brooooooklyn** [comment]
disappear in `rustc 1.27.0-nightly (79252ff4e 2018-04-29)`

**Comment by rubyFeedback** [comment]
I just ran into this problem.

   Compiling approx v0.3.2
   Compiling float-cmp v0.6.0
   Compiling rand_pcg v0.2.1
   Compiling rand_chacha v0.2.2
   Compiling crossbeam-deque v0.7.3
   Compiling gdk-pixbuf v0.8.0
   Compiling rsvg_internals v0.0.1 (/Depot/jj/librsvg-2.49.3/rsvg_internals)
   Compiling pangocairo v0.9.0
   Compiling locale_config v0.3.0
   Compiling simba v0.1.5
   Compiling rand v0.7.3
   Compiling rayon-core v1.7.1
   Compiling phf_generator v0.8.0
   Compiling rand_distr v0.2.2
   Compiling phf_codegen v0.8.0
   Compiling string_cache_codegen v0.5.1
   Compiling nalgebra v0.21.1
   Compiling selectors v0.22.0
   Compiling pin-project-internal v0.4.22
   Compiling futures-macro v0.3.5
   Compiling phf_macros v0.8.0
   Compiling serde_derive v1.0.114
   Compiling cssparser v0.27.2
   Compiling cssparser-macros v0.6.0
   Compiling derive_more v0.99.9
   Compiling phf v0.8.0
error: failed to run custom build command for `cssparser v0.27.2`

Caused by:
  process didn't exit successfully: `/Depot/jj/librsvg-2.49.3/target/release/build/cssparser-0ce507e8d710c4ef/build-script-build` (signal: 6, SIGABRT: process abort signal)
--- stdout
cargo:rustc-cfg=rustc_has_pr45225
cargo:rerun-if-changed=/Depot/jj/librsvg-2.49.3/vendor/cssparser/src/tokenizer.rs

warning: build failed, waiting for other jobs to finish...
error: build failed
make[2]: *** [Makefile:1774: librsvg_c_api.la] Error 101
make[2]: Leaving directory '/Depot/jj/librsvg-2.49.3'
make[1]: *** [Makefile:1278: all-recursive] Error 1
make[1]: Leaving directory '/Depot/jj/librsvg-2.49.3'
make: *** [Makefile:827: all] Error 2
make install
make  install-recursive
make[1]: Entering directory '/Depot/jj/librsvg-2.49.3'
Making install in .
make[2]: Entering directory '/Depot/jj/librsvg-2.49.3'
cd ./librsvg &&                                         \
PKG_CONFIG_ALLOW_CROSS=1                                                \
PKG_CONFIG='/usr/bin//pkg-config'                                               \
CARGO_TARGET_DIR=/Depot/jj/librsvg-2.49.3/target                                        \
cargo --locked build   --release \
&& cd /Depot/jj/librsvg-2.49.3 && /bin/sh ./libtool --silent --tag=CC   --mode=link gcc  -O2 -fPIC -fno-strict-overflow -Wno-error   -o librsvg_c_api.la _rsvg_dummy.lo && mv /Depot/jj/librsvg-2.49.3/target/release/librsvg_c_api.a .libs/librsvg_c_api.a
   Compiling pin-project v0.4.22
   Compiling cssparser v0.27.2
   Compiling markup5ever v0.10.0
error: failed to run custom build command for `cssparser v0.27.2`

Caused by:
  process didn't exit successfully: `/Depot/jj/librsvg-2.49.3/target/release/build/cssparser-0ce507e8d710c4ef/build-script-build` (signal: 6, SIGABRT: process abort signal)
--- stdout
cargo:rustc-cfg=rustc_has_pr45225
cargo:rerun-if-changed=/Depot/jj/librsvg-2.49.3/vendor/cssparser/src/tokenizer.rs

warning: build failed, waiting for other jobs to finish...
error: build failed
make[2]: *** [Makefile:1774: librsvg_c_api.la] Error 101
make[2]: Leaving directory '/Depot/jj/librsvg-2.49.3'
make[1]: *** [Makefile:1278: install-recursive] Error 1
make[1]: Leaving directory '/Depot/jj/librsvg-2.49.3'
make: *** [Makefile:1585: install] Error 2


This may be a problem on my host system; I recompiled gcc and
glibc but that had errors, so perhaps this is related to it - I am not
sure.

But I believe, it may be helpful to be more specific about the
error too. After looking at the commandline, I still have
absolutely no idea what went wrong and why. So it is hard to
paste information here. :)

Just mentioning it.
