### ISSUE TITLE
Stabilize the "approximate suggestion" flag, use for the epoch

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#50168]
We're going to be using rustfix for epoch upgrades, and we need a way to signal to the tool that a suggestion may not apply (and instead to prompt with it).

We have an unstable "approximate suggestion" flag. I propose stabilizing this. We should also start using it everywhere.

cc @rust-lang/dev-tools

**Comment by nrc** [comment]
I'm mostly in favour. I wonder if the flag is future proof enough - should we upgrade it to an enum?

**Comment by oli-obk** [comment]
Like a suggestion kind field that currently only allows "approximate" and "automatic"?

**Comment by Manishearth** [comment]
There's also a difference between those which _may_ work and those which
_definitrly won't work_. Macros fall within the former, but placeholders
fall within the latter.

**Comment by killercup** [comment]
Dev tools meeting: Let's use an enum with these variants at first (represented as string in JSON output):

1. unspecified (all lints will use this by default)
2. machine-applicable
3. approximate (we might want to subdivide this further in the future, e.g. "appox because macros", "placeholder used", …)

Will implement, then do a FCP on this issue

**Comment by killercup** [comment]
impl in #50486

**Comment by killercup** [comment]
This landed.
