### ISSUE TITLE
Allow custom derives for unions

### ISSUE THREAD

**Issue by h2so5** [rust-lang/rust#50223]
Derived from this question: 
https://users.rust-lang.org/t/why-are-proc-macro-derives-prohibited-for-unions/17065

Currently, we cannot apply custom derives to unions:
```rust
#[repr(C)]
#[derive(CustomDerive)]
union Value {
    a: u64,
    b: f64,
}
```

```
error: proc-macro derives may only be applied to struct/enum items
  --> src/value.rs:48:10
   |
48 | #[derive(CustomDerive)]
   |          ^^^^^^^^^^^^
```

This restriction should be removed if there is no technical issue.

**Comment by abonander** [comment]
Most derives are not expecting a union. Moreover, how useful would any derive be in isolation if you need an external value to tell which field is valid data?

The only derived traits I can see being useful are `Clone` and `Copy` but only for unions of exclusively `Copy` types since we can just bit-copy the union. 

Maybe `Default` as well but then how do you define the default value of the union? Write the first field with the default value for its type? How will the user know which value is valid?

**Comment by ExpHP** [comment]
After a brief investigation, it is tempting to say that this might be a [one-line change](https://github.com/rust-lang/rust/blob/6eb4f1d03601d262f4a10fd350d9d31fb27a2d94/src/libsyntax_ext/deriving/custom.rs#L66-L74).  The linked snippet is a last-minute check on the item kind just moments before expanding the macro. (It is, of course, the check that produces this error message.)

Since custom derives are allowed to expand to arbitrary items, I can't imagine that there are any other diagnostics hiding around the corner anywhere that might be attempting to match this against a struct or enum.  (But I'm still paranoid about it because if there is one, it'll probably give an ugly ICE)

**Comment by abonander** [comment]
If builtin derives are already allowed on unions then it's a discrepancy not to allow custom derives. I do agree that it likely just requires lifting that check in the line you linked.

**Comment by est31** [comment]
The use case seems to be

> I want to create a derive to guarantee that all union fields implement a specific trait.
Such derives are safe for any unions because their fields are not accessed at run-time.

So why not use a proc macro here? They'll get stable soon if we are lucky.

**Comment by durka** [comment]
@est31 why not use a proc macro in place of every custom derive? Same answer -- derive attributes look better and don't prevent code parsing tools like rustfmt from seeing the item.

As for custom derives not expecting a union, it seems that at least syn is [already equipped](https://github.com/dtolnay/syn/blob/6e4a9c2d118fa665a8e22e6abf974707636cd2b7/examples/heapsize/heapsize_derive/src/lib.rs#L86) for this.

**Comment by durka** [comment]
Attribute proc macro makes more sense than bang proc macro here, yeah. I
think there are legitimate uses for derive on unions though, even this
isn't one of them.

**Comment by ExpHP** [comment]
> The only use case of this feature that I'm aware of is what @h2so5 mentioned in the thread linked: they wanted to make sure that every variant of the union implemented a trait. This is a solid use case, but it still is abusing the derive feature.

There are legitimate use cases.

* Marker traits
* Type-level programming

**Comment by h2so5** [comment]
@est31 
In my use case, the custom derive is used for applying a marker trait to struct/union recursively: `#[derive(A)]` adds `trait A` for struct/union if every field implements `trait A`. So it's not a workaround for unstable proc macro.

Custom marker traits for union make sense when we want to ensure the characteristics of its memory block independent of the type of variant.

For example:
- Struct/Union only contains abi-safe types or not
- Struct/Union may contain a pointer or not (for conservative GC)
- Struct/Union is relocatable or not

**Comment by abonander** [comment]
This appears to be an E-Easy change and I'm willing to mentor. If everyone concurs I'll post mentoring instructions.

**Comment by dtolnay** [comment]
All of the arguments against derive on unions so far also work as arguments against letting users handwrite trait implementations for their unions.

Given that we already permit builtin derives on unions, and given that we allow users to handwrite trait implementations for a union type, I believe custom derive needs to be supported.

**Comment by est31** [comment]
Sure, go with it. I don't feel too strongly about it.

**Comment by stevepentland** [comment]
@abonander I'd like to take care of this one as my first contribution to Rust once the mentoring instructions go up.

**Comment by abonander** [comment]
@stevepentland It should be as simple as adding `ItemKind::Union(..)` to [this match](https://github.com/rust-lang/rust/blob/master/src/libsyntax_ext/deriving/custom.rs#L68), which does exactly what it looks like it does.

Of course you'll need to implement a test derive, which would involve adding two files to `src/test/run-pass-fulldeps/proc-macro`; one implementing the derive and one to use it. The file implementing the derive goes in the `auxiliary/` subfolder, I recommend using `derive-a.rs` as a template for that. Then in your test file you signal it to build your derive file by adding these comments (the second is because of an unrelated issue):

```rust
// aux-build:derive-filename.rs
// ignore-stage1
```

The derive itself can be as simple as asserting the contents of the input and outputting nothing (`"".parse().unwrap()`).

Don't forget the license headers, of course. You can copy them from one of the other files in the directory.
