### ISSUE TITLE
Rustdoc should allow copying `use` statements into clipboard with 1 click

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#50239]
The intention of many (if not most) visits to any crate doc (e.g. on docs.rs but also std) is to find out the import paths, so that one can write the right `use` statement for the symbol.

So Rustdoc should allow copying `use` statements into the clipboard with 1 click.
There should be a copy icon next to the name of each type/trait/module, which will cause a `use` statement for this symbol to be copied to the user's clipboard (`"use {};\n"`).
For easy pasting into the editor after lookup up the path of the symbol.
I always find myself manually selecting the path (carefully avoiding clicking its link but also not selecting any chars before and after, which is annoying*), then copying, pasting and writing `use ` before and `;\n` after it, for many symbols, which wouldn't be necessary with this feature.

The icon could be something from FontAwesome or similar (that's instantly recognizable as a "copy-to-clipboard" icon.)

*Also, why is the symbol even a link, always to its page which is the same page, when the user is already on that page? (We could just change (re-purpose) this link to copy the `use`-statement to the clipboard, but it won't be as obvious as with a copy icon.)

**Comment by hellow554** [comment]
While I think this could be a very useful feature, I tried three different pages in the std doc ([time::instant](https://doc.rust-lang.org/std/time/struct.Instant.html),  [mpsc::Sender](https://doc.rust-lang.org/std/sync/mpsc/struct.Sender.html) and [process::Command](https://doc.rust-lang.org/std/process/struct.Command.html))
They all have an examples section and they all have an use declaration in it. I guess if there is something missing in the std crate, just file an PR and fix that.
For other crates, I do not have a strong opinion on that. Imho the crate should be documented well, so that people can use it and if I write documentation I try to look at the std and mimic it.
But let's see what other people think. As I said, I would find it very neat, but not very necessary.

**Comment by Boscop** [comment]
Yes, std is better documented than probably any other crates, but even there, the use statements in the examples are not at a consistently placed location, requiring manual visual searching and manual selecting+copying. And most of the time when I'm looking stuff up in the docs it's **just** to find the import path, I don't want to have to read through the example code to find a possible use statement (which may not even be there).. 
And many other crates don't have example code for each type (esp with use statements), and I also wouldn't expect them to, it shouldn't be required / necessary.

**Comment by steveklabnik** [comment]
Triage: no changes here that I'm aware of.

**Comment by GuillaumeGomez** [comment]
A few extra info on copying things in clipboard on IE:
 * https://stackoverflow.com/a/15958810
 * https://gist.github.com/ddallala/343872
