### ISSUE TITLE
Duration::as_msecs(), as_microsecs(), as_nanosecs()

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#50243]
I often find myself needing this extension to `std`'s `Duration`, why isn't something like this part of `std`? :)

```rust
pub trait DurationExt {
	fn as_msecs(&self) -> u64;
	fn as_microsecs(&self) -> u64;
	fn as_nanosecs(&self) -> u64;
}

impl DurationExt for Duration {
	fn as_msecs(&self) -> u64 {
		self.as_secs() * 1_000 + (self.subsec_nanos() as f64 / 1_000_000.0).round() as u64
	}
	fn as_microsecs(&self) -> u64 {
		self.as_secs() * 1_000_000 + (self.subsec_nanos() as f64 / 1_000.0).round() as u64
	}
	fn as_nanosecs(&self) -> u64 {
		self.as_secs() * 1_000_000_000 + self.subsec_nanos() as u64
	}
}
```

**Comment by hellow554** [comment]
You may get a problem with this. 
Because you can use a `u64` for seconds you can overflow `as_msecs` by using `u64::max` and then you would cause an overflow/panic/destroy of the universe. 
I guess, that's why there is [`subsec_millis`][0] to avoid this problem (which was btw. merged 8 days ago :) )


[0]: https://doc.rust-lang.org/std/time/struct.Duration.html#method.subsec_millis

**Comment by est31** [comment]
#50202 #50167

**Comment by rossmacarthur** [comment]
It appears this can be closed?

https://doc.rust-lang.org/std/time/struct.Duration.html#method.as_millis
https://doc.rust-lang.org/std/time/struct.Duration.html#method.as_micros
https://doc.rust-lang.org/std/time/struct.Duration.html#method.as_nanos
