### ISSUE TITLE
Bad debug info on windows for unwrap crashes

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/rust#50256]
For this crash: https://crash-stats.mozilla.com/report/index/c4d1d1c5-331a-4ea7-bb71-bc00b0180421
we get debug info that claims the crash is happening here:
https://hg.mozilla.org/mozilla-central/annotate/cc0d7de218cb0c260c8ba0cf6637845ad2222f49/gfx/webrender_bindings/src/moz2d_renderer.rs#l460

That's not really a helpful place.

Similarly, https://crash-stats.mozilla.com/report/index/d1d968eb-220b-435b-b0c2-6054a0180421 suggests https://hg.mozilla.org/mozilla-central/annotate/cc0d7de218cb0c260c8ba0cf6637845ad2222f49/gfx/webrender/src/platform/windows/font.rs#l137

when it should say:
https://hg.mozilla.org/mozilla-central/annotate/cc0d7de218cb0c260c8ba0cf6637845ad2222f49/gfx/webrender/src/platform/windows/font.rs#l134

**Comment by wesleywiser** [comment]
Visited during wg-debugging. We decided to close this because the crash data is no longer available and there have been many improvements to our line number generation since this was opened, including reporting useful line numbers in the panic message itself via `#[track_caller]`. If this is still occurring, we can re-open.
