### ISSUE TITLE
Nightly docker image out of date

### ISSUE THREAD

**Issue by chucksmash** [rust-lang/rust#50287]
Hello Fellow Rustaceans!

It looks like the docker image for rustlang/rust:nightly currently has  rustc version `1.27.0-nightly (2018-04-18)` but version `1.27.0-nightly (2018-04-26)` is available. This causes the compilation of a Rocket web app to fail and a naive `rustup update` on the container also fails.

**Comment by kennytm** [comment]
Hi, thanks for the report. However, this repository does not host the Docker image. Please consider filing to https://github.com/rust-lang-nursery/docker-rust-nightly instead. 

You may also want to wait for 4 to 5 more hours since the [last build](https://hub.docker.com/r/rustlang/rust/builds/) was 20 hours ago.

**Comment by chucksmash** [comment]
Cool, wasn't sure where to report. Thanks.
