### ISSUE TITLE
Files all over the place

### ISSUE THREAD

**Issue by Nocxy** [rust-lang/rust#50382]
Hi everyone,

As mentioned in #50361, I have files all over the place and would like to know how to avoid it, e.g. by changing the installation path..
I could provide a screenshot to show you what I mean but I'm currently on macOS with a lot of personal files in there.

Could you help me?

Thanks in advance,
Nocxy

PS: Thank you for not closing this one.

**Comment by kennytm** [comment]
As mentioned in https://github.com/rust-lang/rust/issues/50361#issuecomment-385798668, this is still something which is more suited for our support forum https://users.rust-lang.org/. Try to ask there first. If it turns out to be a bug of [rustup](https://github.com/rust-lang-nursery/rustup.rs/), you may file an issue there then.

**Comment by retep998** [comment]
The environment variables `RUSTUP_HOME` and `CARGO_HOME` determine where rustup and cargo dump all their files.
