### ISSUE TITLE
ci: Documentation outdated

### ISSUE THREAD

**Issue by hberntsen** [rust-lang/rust#50396]
The `README.md` in `src/ci/docker`, section Cross toolchains, specifies how to generate a `.config` file. 

* It refers to `build_toolchain_root.sh` which does not exist
* `linux-cross` exists as a folder in the old repository: https://github.com/rust-lang-deprecated/rust-buildbot/tree/master/slaves/linux-cross but not in this one
* Looks like `ubuntu:15.10` has been replaced by `ubuntu:16.04`

**Comment by alexcrichton** [comment]
Oh dear everything in rust-buildbot is *ancient* at this point. The reference to `build_toolchain_root.sh` is basically just a few bundled ct-ng commands (I think?) as well as `linux-cross` being long since gone and obsoleted. 

In general it's just supposed to be helpful docs for anyone trying to mentally recreate the image from scratch and understand why it is the way it is, these kinds of docs get out of date pretty quickly...

**Comment by Mark-Simulacrum** [comment]
I'm going to close this since I think fixing this is pretty much out of scope (we can't effectively maintain these docs).
