### ISSUE TITLE
run-make wasm tests cannot be run

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#50711]
I am unable to run the wasm tests in `src/test/run-make`.  It looks like the `wasm32-unknown` Travis image is no longer running them, either.  Reverting some of the changes in #50000 brings them back (but causes the `cross-lang-lto` test to fail).

I'm not very familiar with the bootstrap code, so I'm uncertain how this should be fixed.

cc @alexcrichton @michaelwoerister

**Comment by alexcrichton** [comment]
Oh oops, sorry I should have caught this in review!

I think the fix is:

* Move `cross-lang-lto` from `run-make` to `run-make-fulldeps`
* Change the `RunMake` test suite back to `default_test!` from its current `host_test!`

@ehuss or @michaelwoerister, would y'all be able to submit a PR with that?

**Comment by ehuss** [comment]
I can give it a shot.
