### ISSUE TITLE
Make str::ends_with a const fn

### ISSUE THREAD

**Issue by alex** [rust-lang/rust#50899]
Currently it can't be called from a `const fn`, which is sad :-(

Ordinarily I'd take a pass at implementing this myself, but `str::ends_with` is slightly more complex than meets the eye because of the `Pattern` abstraction, and I'm not particularly sure how that's best handled.

**Comment by oli-obk** [comment]
This is very hard! We need `if` at the least (which has a merged RFC). But we also need https://github.com/rust-lang/rfcs/pull/2345 to abort in the case of bad indices.

I don't think this can be done any time soon and keeping an extra issue open for it is not really much use.

There's also a chance we need a new RFC entirely to be able to do this (due to the internal indexing traits being involved)

Once all the prerequisites are fulfilled we'll definitely do this though.

**Comment by alex** [comment]
👍  thanks for the quick response!

**Comment by oli-obk** [comment]
The groundwork for this is happening right now under the `const_traits` feature gate: https://github.com/rust-lang/rust/issues/67792
