### ISSUE TITLE
1.26.0 - stdsimd/coresimd/x86/mod.rs test failures on non-x86 architectures

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#50988]
Same failures on [Debian](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=ppc64el&ver=1.26.0%2Bdfsg1-1%7Eexp1&stamp=1527026474&raw=0) and [Fedora](https://kojipkgs.fedoraproject.org/packages/rust/1.26.0/1.fc29/data/logs/ppc64le/build.log)
````
test ../stdsimd/coresimd/x86/mod.rs - coresimd::x86::__m256d (line 32) ... FAILED
test ../stdsimd/coresimd/x86/mod.rs - coresimd::x86::__m128 (line 32) ... FAILED
test ../stdsimd/coresimd/x86/mod.rs - coresimd::x86::__m64 (line 39) ... FAILED
test ../stdsimd/coresimd/x86/mod.rs - coresimd::x86::__m256i (line 36) ... FAILED
test ../stdsimd/coresimd/x86/mod.rs - coresimd::x86::__m128i (line 39) ... FAILED
test ../stdsimd/coresimd/x86/mod.rs - coresimd::x86::__m128d (line 32) ... FAILED
test ../stdsimd/coresimd/x86/mod.rs - coresimd::x86::__m256 (line 32) ... FAILED
````
Current master has diffs on top of 1.26.0 looking like this:
```diff
     /// ```
-    /// # #![feature(cfg_target_feature, target_feature, stdsimd)]
+    /// # #![cfg_attr(not(dox), feature(stdsimd))]
     /// # #![cfg_attr(not(dox), no_std)]
```
but on a first glance this doesn't look like it would fix the failures.

cc @cuviper

**Comment by cuviper** [comment]
I guess these need a `target_arch` config filter too?

**Comment by infinity0** [comment]
Is there a way to do that for the whole file, like the opposite of ``// ignore`` ?

**Comment by infinity0** [comment]
The error message says: 

~~~~
---- ../stdsimd/coresimd/x86/mod.rs - coresimd::x86::__m256d (line 32) stdout ----
	error: 
is_x86_feature_detected can only be used on x86 and x86_64 targets.
You can prevent it from being used in other architectures by
guarding it behind a cfg(target_arch) as follows:

    #[cfg(any(target_arch = "x86", target_arch = "x86_64"))] {
        if is_x86_feature_detected(...) { ... }
    }

~~~~

So I'm going to try that and report back. Ironically this overly-strict macro is defined in the very same crate whose tests fail its strictness, in `stdsimd/arch/detect/mod.rs`.

What's curious is that we don't get the same errors for very similar tests defined in `coresimd/avx2/mod.rs`, which also use `is_x86_feature_detected` that are ungarded by a `cfg()`. There are other similarities and differences about these tests but none of them seem like they should be causing such a failure vs non-failure that we're seeing.

**Comment by gnzlbg** [comment]
> I guess these need a target_arch config filter too?

The whole `coresimd/x86` module has a `cfg` on the `target_arch` for `x86` and `x86_64` (https://github.com/rust-lang-nursery/stdsimd/blob/master/coresimd/mod.rs#L149).

Why is that module being compiled for your `ppc` builds? I don't know, our build bots for `ppc`, `ppc64` (be), and `ppc64le` are not failing.

Maybe it has something to do with `dox`? cc @QuietMisdreavus

**Comment by QuietMisdreavus** [comment]
It's possible that we can make the `doc(cfg)` handling a little more clever by reducing the condition if it gets something like `all(a, any(a, b))` to just make it use `a` in that situation, and leave the `doc(cfg)` tags on the exports, which should leave the docs as-is, and also properly tag all the doctests! That sounds like it starts to lean into "CS research" territory tho. `>_>`

**Comment by QuietMisdreavus** [comment]
I've opened https://github.com/rust-lang-nursery/stdsimd/pull/466 to tag the private modules. We'll need to run doctests for libcore in a powerpc64 environment (or in Debian/Fedora's environment, if that doesn't work) to be sure it fixes the issue.

**Comment by infinity0** [comment]
Thanks, I've [added this](https://salsa.debian.org/rust-team/rust/commit/ceac151a86572818c339928847061e877fa6ed1a) to Debian and uploaded, results will appear [here](https://buildd.debian.org/status/package.php?p=rustc&suite=experimental) in about 4-10 hours.

**Comment by gnzlbg** [comment]
Why is debian running ppc64le tests at all? It is a tier2 target which means "test are not guaranteed to pass" and in general they won't because we don't run them at the rustc level (even though some components might run them).

If you want ppc64le tests to pass the first step should be to make it a tier1 rustc target. Otherwise, whatever you fix today we might break tomorrow accidentally.

**Comment by gnzlbg** [comment]
@infinity0 I did not know it was working _that_ good. I think @lu-zero might be interested / able of pushing ppc64le to tier1 since it has been doing a lot of work on altivec and vsx intrinsics. 

Maybe you should open an issue about it.

**Comment by lu-zero** [comment]
I would be glad to help, what tier1 would involve?

**Comment by gnzlbg** [comment]
running all rustc tests on ppc64le instead of just compiling the binaries. I don't know if qemu would be enough (like in stdsimd) or if we need to do so on the real hardware, but there are real powerpc's available for CI, so, worst case we'll need to do that. Note that rustc test set up is "similar" to the stdsimd one, which you are already a bit familiar with.

**Comment by lu-zero** [comment]
I'm sure @edelsohn would be glad to help regarding hardware for CI :)

**Comment by edelsohn** [comment]
The Rust CI community can request a Power8 PPC64LE VM at OSUOSL 

http://osuosl.org/services/powerdev/

List David Edelsohn as the sponsor.

**Comment by lu-zero** [comment]
I can probably do all the paperwork, but I'll need some help to deal with the CI setup.

**Comment by QuietMisdreavus** [comment]
cc @rust-lang/infra for the note about setting up CI with a ppc64le machine ^

-----

I've tested running the docs with the change to stdsimd, and it turns out my fears about the "platform warning" becoming too verbose were completely unfounded. It turns out the piece that propagates `doc(cfg)` attributes to contained items (the `propagate-doc-cfg` pass) runs after non-public items are stripped and re-exports are inlined, so the docs for libcore don't change from where they are right now. It's still alarming that that environment tries to run doctests from private modules, but at least for now these specific doctests won't run any more.

**Comment by QuietMisdreavus** [comment]
Update: Turns out, "rustdoc runs doctests on private items despite not being asked to document them" is an old issue: https://github.com/rust-lang/rust/issues/30094

**Comment by gnzlbg** [comment]
Is this still happening?
