### ISSUE TITLE
1.26 Release notes document unstable nightly cargo feature

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#51091]
The release notes for 1.26 mention `Cargo.lock files are now included in published crates.` but that is a nightly-only unstable feature.  Was that intentional?

**Comment by Aaronepower** [comment]
Yes, this seems unintentional, which is odd since it was marked relnotes and unstable features tend not to get that tag. cc @rust-lang/cargo would anyone be able to clarify [cargo/5093](https://github.com/rust-lang/cargo/pull/5093)?

**Comment by alexcrichton** [comment]
https://github.com/rust-lang/cargo/pull/5093 was initially intended for stable but through testing we ended up realizing it would be a breaking change and is not always desirable. Instead of stabilizing it https://github.com/rust-lang/cargo/pull/5093 was landed as a nightly feature, guarded by `cargo-features = ["publish-lockfile"]` in the manifest
