### ISSUE TITLE
Using type parameters instead of concrete types changes borrowing behaviour

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#51150]
The problem basically boils down to the following. The original problem can be seen in https://github.com/sdroege/byte-slice-cast/issues/1#issuecomment-392331136

```rust
fn foo<T: AsRef<[u8]>>(slice: &T) -> &[u8] {
    slice.as_ref()
}

fn bar(slice: &[u8]) -> &[u8] {
    slice
}
```

When passed a `&[u8]`, both functions should be exactly the same but in practice they behave different with regards to borrowing behaviour:

This works with and without the additional & (which will become important later)
```rust
    let b = bar(&bar(&slice));
    let b = bar(bar(&slice));
```

This fails and the & before the inner foo is necessary
```rust
    let slice = [1, 2, 3, 4];

    // 13 |     let s = foo(&foo(&slice));
    //    |                  ^^^^^^^^^^^ - temporary value dropped here while still borrowed
    //    |                  |
    //    |                  temporary value does not live long enough

    let s = foo(&foo(&slice));
```

Without the & it fails differently and I'm not sure why. There is no `[u8]` anywhere, only references to `[u8]` and those are `Sized`
```rust
    // &[u8] is Sized and that's what it operates on, not [u8]. The return value is &[u8]
    // 13 |     let s = foo(foo(&slice));
    //    |             ^^^ `[u8]` does not have a constant size known at compile-time
    //    |
    //    = help: the trait `std::marker::Sized` is not implemented for `[u8]`

    let s = foo(foo(&slice));
```

CC @Manishearth

**Comment by sdroege** [comment]
Interestingly, the `let s = foo(&foo(&slice));` variant (with &) builds fine with current nightly and NLL enabled. The second variant (without &) does not and fails with the same error still.

However, from my understanding, both should work exactly the same as the variant without generics.

**Comment by stephaneyfx** [comment]
Regarding the `Sized` error, this is due to the missing `?Sized` bound for `T` in the definition of `foo`. The inner call to `foo` has type `&[u8]` which means the outer `foo` sees `T` as being `[u8]` which is a DST, thus the error. Adding `?Sized` works: [playground](https://play.rust-lang.org/?gist=18dd0aa45abbe3545f7f7a7ecc5d5ce7&version=stable&mode=debug)

```rust
fn foo<T: AsRef<[u8]> + ?Sized>(slice: &T) -> &[u8] {
    slice.as_ref()
}

fn main() {
    let v = [1, 2, 3, 4];
    let _ = foo(foo(&v));
}
```

As to why `let b = foo(&foo(&v));` is rejected but not `let b = bar(&bar(&v));`, the latter makes use of autoderef to turn `&'a &'b [u8]` into `&'b [u8]` in the outer call to `bar`, because `bar` takes _exactly_ `&[u8]` -- it is not generic over a type. The outer call to `bar` receives a `&[u8]`, not a `&&[u8]`.

The desugared version of `foo` is:

```rust
fn foo<'a, T: AsRef<[u8]> + ?Sized>(slice: &'a T) -> &'a [u8] {
    slice.as_ref()
}
```

With these explicit lifetimes, the outer call to `foo` receives a `&'a &'b [u8]` (`T` is `&'b [u8]`) and returns a `&'a [u8]`, not a `&'b [u8]`. `'a` is the lifetime of the borrow of a temporary that is a reference to a slice (`&'b [u8]`) returned by the inner `foo`. Thus the error about the borrowed temporary not living long enough.

Note that NLL makes the code compile, but _only_ if the reference is not used. This fails to compile too ([playground](https://play.rust-lang.org/?gist=d72015faf72c395c773f92a055467c47&version=nightly&mode=debug):

```rust
#![feature(nll)]

fn foo<T: AsRef<[u8]> + ?Sized>(slice: &T) -> &[u8] {
    slice.as_ref()
}

fn main() {
    let v = [1, 2, 3, 4];
    let x = foo(&foo(&v));
    println!("{:?}", x);
}
```

**Comment by sdroege** [comment]
Thanks, the `?Sized` bound is fixing it for all my use-cases. Thanks for the explanation!
