### ISSUE TITLE
NLL fails to remind users that locals in same scope are dropped in reverse declaration order

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#51195]
Looking at a case like [E0597.rs](https://github.com/rust-lang/rust/blob/2e104a77cfb6b83f725512210c88dc970426a354/src/test/ui/error-codes/E0597.rs), we can see that the AST-borrowck includes the note:

https://github.com/rust-lang/rust/blob/2e104a77cfb6b83f725512210c88dc970426a354/src/test/ui/error-codes/E0597.stderr#L10

while [NLL](https://github.com/rust-lang/rust/blob/2e104a77cfb6b83f725512210c88dc970426a354/src/test/ui/error-codes/E0597.nll.stderr) has no reminder about the drop order for a pair of locals declared in the same lexical scope. 

 * (I personally am not a fan of the use of the word "created" in the error message there, since I attach that word to the dynamic semantics, while drop order is entirely defined by the  *declaration order*, which is part of the static semantics (or really, part of the source syntax itself). The only thing that's potentially dynamic is whether or not a local variable actually holds  a value at the moment that we go out of that local variable's scope.)

But anyway, the point is that NLL is failing to say anything at all on the matter, which is probably not ideal for Rust's target audience.

**Comment by pnkfelix** [comment]
The importance of doing this (and doing it well) may grow in the face of the potential change to the static semantics described in #51036

**Comment by estebank** [comment]
> I personally am not a fan of the use of the word "created" in the error message there

@pnkfelix `%s/created/declared/g`?

**Comment by pnkfelix** [comment]
@estebank yes, `s/created/declared/` would be better here, I think.

**Comment by nikomatsakis** [comment]
So, @spastorino and I have been talking a bit about this [in Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/topic/issue-51195-warning-about-variable-declaration-order). The actual NLL error message is in some ways better than the AST one. Notably, it includes the crucial bit of info that the final use of the variable is in the destructor for `x`:

```
error[E0597]: `y` does not live long enough
  --> src/test/ui/error-codes/E0597.rs:18:16
   |
18 |     x.x = Some(&y);
   |                ^^ borrowed value does not live long enough
19 |     //~^ `y` does not live long enough [E0597]
20 | }
   | -
   | |
   | borrowed value only lives until here
   | borrow later used here, when `x` is dropped
```

that said, it would be that much better if it also included the note about the relative order of variables being significant. The question is *when* to print such a thing. As I wrote on Zulip, I think we want to trigger the message under two conditions:

(1) the last use is when another local variable is dropped
(2) a local variable is borrowed

We find about Condition (1) in the function `explain_why_borrow_contains_point`:

https://github.com/rust-lang/rust/blob/2a0062974a5225847fc43d5522c4dc3718173fe5/src/librustc_mir/borrow_check/nll/explain_borrow/mod.rs#L56-L89

In that same function, we have access to some information about the borrow in the `borrow_data` variable:

https://github.com/rust-lang/rust/blob/2a0062974a5225847fc43d5522c4dc3718173fe5/src/librustc_mir/borrow_check/nll/explain_borrow/mod.rs#L29

[The `borrow_data` struct][bds] includes in particular the place that was borrowed:

https://github.com/rust-lang/rust/blob/2a0062974a5225847fc43d5522c4dc3718173fe5/src/librustc_mir/borrow_check/borrow_set.rs#L80

[bds]: https://github.com/rust-lang/rust/blob/2a0062974a5225847fc43d5522c4dc3718173fe5/src/librustc_mir/borrow_check/borrow_set.rs#L67-L83

so we can check that this `Place` is a local variable (or a field of a local variable). I would probably *not* issue the warning if the `Place` includes a `Deref`, I don't think, although we should maybe try to craft some examples where that is the case and make sure I'm right that the message doesn't seem relevant then.

**Comment by nikomatsakis** [comment]
That means detecting when we are reporting an error due to this call (or the one for `Drop`):

https://github.com/rust-lang/rust/blob/2a0062974a5225847fc43d5522c4dc3718173fe5/src/librustc_mir/borrow_check/mod.rs#L501-L509

So specifically looking for `WriteKind::StorageDeadOrDrop`:

https://github.com/rust-lang/rust/blob/2a0062974a5225847fc43d5522c4dc3718173fe5/src/librustc_mir/borrow_check/mod.rs#L505

**Comment by nikomatsakis** [comment]
Comment from Zulip, recording for posterity:

Recall that the basic structure of the "error reporting" phase of the borrow check is like this:

- Walk over the MIR
- For each "action" of various kinds, check if there is a conflicting loan:
  - In this particular case, if there is a `StorageDead(y)` or `Drop(y)`, that means that the stack space for a local variable is being freed
  - Therefore, if there is a loan of that variable `y`, that's a problem and we should report an error

Currently, if there is a loan of that variable `y`, we report an error, and then we invoke [`explain_why_borrow_contains_point`](https://github.com/rust-lang/rust/blob/2a0062974a5225847fc43d5522c4dc3718173fe5/src/librustc_mir/borrow_check/nll/explain_borrow/mod.rs#L26-L31). This tries to report *why* the variable `y` is still considered borrowed. In the case of our example, we find that the reason is because [that reference is going to be used in the `Drop(x)` for some other variable `x`](https://github.com/rust-lang/rust/blob/2a0062974a5225847fc43d5522c4dc3718173fe5/src/librustc_mir/borrow_check/nll/explain_borrow/mod.rs#L56-L89).

What I am saying is that *in precisely these conditions*, where the current statement is a `Drop`/`StorageDead` *and* the final use is *another* `Drop`, we should report the note about the relative ordering of variables. This is because that means that

- we are dropping one variable (`y`)
- but a reference to that variable  is going to be used in the destructor of another variable (`x`)

It seems like precisely here is where the relative order of variables is relevant.
