### ISSUE TITLE
NLL diagnostics span RHS of assignment when LHS was prior (and better?) choice

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#51217]
Consider the output diagnostics from 

https://github.com/rust-lang/rust/blob/746d63a203174f6c91396230b86f6b4fbda507c4/src/test/ui/command-line-diagnostics.nll.stderr#L4-L5

and compare them to

https://github.com/rust-lang/rust/blob/746d63a203174f6c91396230b86f6b4fbda507c4/src/test/ui/command-line-diagnostics.stderr#L4-L5

I don't know why NLL deviates.

(Maybe its fine to switch to the right-hand side, but I want to make sure we do so as a deliberate choice, not an accident.)

**Comment by matthewjasper** [comment]
So `let x = 6 * 9;` is a single statement in MIR, so there is only currently the option to place one span on it. Most of the time either the current span is the correct choice here, so it's certainly easier to keep the current span. I guess the two main possibilities here are:

* Check if the variable starts initialized, and use the span from the variable's declaration instead of from the assignment.
* Always evaluate the RHS into a temporary so that there can be two separate spans: this would break some other stuff I'm working on, and I don't really want MIR to have even more temporaries.

**Comment by pnkfelix** [comment]
I personally like the option of "Check if the variable starts initialized, and use the span from the variable's declaration instead of from the assignment."

In particular, I'm already extending `mir:LocalDecl` in a number of ways, threading state down from the AST into each `mir::LocalDecl` in order to increase the amount of information available for the MIR borrowck to use when constructing diagnostic output.

So it seems natural to me to include information like: Is there an explicit type attached? (if so, what is its span?), and is there an initialization expression (and if so, what is its span)?

**Comment by pnkfelix** [comment]
(Adding such info as mentioned in my previous comment to `mir::LocalDecl` may be a natural addition to PR https://github.com/rust-lang/rust/pull/51275 ; I'm noting that here mostly as a reminder that I should double check that theory as part of my work on that PR.)

**Comment by nikomatsakis** [comment]
I'm marking this as RC -- it seems not *that* criticial.

**Comment by nikomatsakis** [comment]
Well, it is somewhat wrong. I'm going to put it as EP.

**Comment by nikomatsakis** [comment]
But if we can't find a nice fix, oh well.
