### ISSUE TITLE
Use of unimplemented!() causing ICE with NLL

### ISSUE THREAD

**Issue by dylanede** [rust-lang/rust#51345]
Here is a fairly small test case ([playground](http://play.rust-lang.org/?gist=cd668d431e2aab78ac92f1061979f524&version=nightly&mode=debug)):

```rust
#![feature(nll)]
fn main() {
    use std::collections::HashMap;
    let mut m: HashMap<(), ()> = HashMap::new();
    m.insert((), unimplemented!());
}
```

The error message is

```text
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some((_4, bw0))`,
 right: `None`: never found an activation for this borrow!', librustc_mir/borrow_check/borrow_set.rs:121:9
```

**Comment by nikomatsakis** [comment]
The assertion failure is here:

https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc_mir/borrow_check/borrow_set.rs#L119-L130

I think that this assertion is just wrong. We add the assertion because -- for 2-phase borrows -- we always generate an activation. But I did not consider the case where the activation is in dead code (as in this case). 

Unfortunately, we probably can't *just* delete the assertion. The challenge is that the `activation_location` would then remain `None`, which means that later on when we read the borrow, we will interpret it as "not 2-phase":

https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc_mir/borrow_check/path_utils.rs#L84-L91

What we probably want to do is to change that field from an `Option` to some kind of 3-valued enum. Something like:

```rust
enum TwoPhaseActivation {
    NotTwoPhase, // what is now `None`
    NotActivated,
    ActivatedAt(Location), // roughly what is now `Some`
}
```

We could then use the `NotActivated` setting instead of the existing `TwoPhaseUse::SharedUse` enum (the `TwoPhaseUse` enum can probably just go away), so that we basically just return false and say it is never annotated:

https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc_mir/borrow_check/path_utils.rs#L87-L88
