### ISSUE TITLE
rustbuild: `x.py doc -i --stage 1 src/libstd` builds the compiler twice

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#51424]
This seems to be new? I think in the past it worked without building the stage1 compiler. (At least, without the `--incremental` flag.) My current branch is based on master at 4122885e0f99b3f28e65c122cde48de5bfc8231a.

Full build log with `--verbose`: https://gist.github.com/QuietMisdreavus/5d000903b7cc4f1aae655f7c9b3073b8

cc @Mark-Simulacrum

**Comment by kennytm** [comment]
(Hint: You could use <code>./x.py doc --stage 1 src/lib <strong>--dry-run</strong> -v</code> to dump the build tree without actually building anything.)

I think this is old, because until #51302 we require a stage2 sysroot for anything rustdoc related. Perhaps need to update these lines:

https://github.com/rust-lang/rust/blob/c131bdcaff68d35f96e954baac4340206779335f/src/bootstrap/builder.rs#L802-L807

**Comment by Mark-Simulacrum** [comment]
Yes, those lines look like the problem. We probably just need to change the compiler argument to the compiler passed to the cargo function
