### ISSUE TITLE
Rename CodeMap/FileMap to SourceMap/SourceFile.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#51574]
The name `FileMap` always seemed a bit jarring, and I think this would be an improvement.
cc @nikomatsakis @nrc

**Comment by abhijeetbhagat** [comment]
I can take this up.

**Comment by abhijeetbhagat** [comment]
What about structs like `FileMapAndLine` ?

**Comment by eddyb** [comment]
@abhijeetbhagat `SourceFileAndLine` looks fine to me.

**Comment by eddyb** [comment]
Yeah, any combination of the words "code" and "map" should.

**Comment by abhijeetbhagat** [comment]
Right. Changing that too.

**Comment by jolson88** [comment]
With the merge, it's unclear to me whether this is an older issue that needs closing, or if there is more work to do. A quick search seems to show the following occurences still:
- `MalformedForCodemap` and `MalformedCodemapPositions` in `src/libsyntax_pos/lib.rs` and `src/libsyntax/source_map.rs`
- `pub use self::caching_codemap_view::CachingSourceMapView` in `src/librustc/ich/mod.rs`
- `StableFilemapId` in `src/libsyntax/source_map.rs`

If this issue is still considered open, does that reflect that that these should be renamed as well?
- `MalformedForCodemap` -> `MalformedForSourceMap`
- `MalformedCodemapPositions` -> `MalformedSourceMapPositions`
- `self::caching_codemap_view` -> `self::caching_source_map_view`
- `StableFilemapId` -> `StableSourceFileId`

**Comment by eddyb** [comment]
I assume this is done after #55190?

**Comment by eddyb** [comment]
I came across over this instance of `cm` today:
https://github.com/rust-lang/rust/blob/e6ec0d125eba4074122b187032474b4174fb9d31/src/librustc_errors/lib.rs#L149

So we might need to do another pass just for easier to miss things like `cm`.

**Comment by Alexendoo** [comment]
Looks done after #69375
