### ISSUE TITLE
Unexpected undefined behavior when assigning a function pointer to std::mem::zeroed()

### ISSUE THREAD

**Issue by archshift** [rust-lang/rust#51615]
Note: the following behavior only exists when compiling ***with optimizations*** (a.k.a. release mode).

### Example 1:
```rust
pub fn bar() -> usize {
    let foo: fn() = unsafe { ::std::mem::zeroed() };
    foo as usize
}
```

This emits (as of 1.26.0):
```asm
  push rbp
  mov rbp, rsp
  ud2
```

Whereas it used to have expected behavior up until 1.19.0:
```asm
  push rbp
  mov rbp, rsp
  xor eax, eax
  pop rbp
  ret
```

### Example 2:

A bit of an odd case I discovered, which results in what seems to be some stack corruption:
```rust
pub struct Foo<T: Copy> {
    map_keys: [u64; 64],
    map_vals: T,
}

impl<T: Copy> Foo<T> {
    pub fn new() -> Self {
        Foo {
            map_keys: [!0; 64],
            map_vals: unsafe { ::std::mem::zeroed() }
        }
    }
}

fn main() {
    Foo::<fn()>::new();
}
```
[Playground link](https://play.rust-lang.org/?gist=16467ab7ba367b172472f6270d4efb9f&version=stable&mode=release)

---

What I think is striking here is that this behavior occurs while *never even dereferencing the pointer!*. This allows one to shoot oneself in the foot when trying to, for example, set a default value for a function pointer member.

**Comment by petrochenkov** [comment]
"Function pointers" are actually "function references", so they can't be null, so `Option<fn()>` needs to be used for nullable function pointers (as explained in the [documentation](https://doc.rust-lang.org/nightly/std/primitive.fn.html)).

**Comment by rkruppe** [comment]
Yeah, this might surprise people, but it's working as intended: creating a bit pattern that is invalid for a type and unsafely claiming it to be of that type is instant UB, and has to be to enable a variety of optimizations. One more reason to be extremely careful with `mem::zeroed` (e.g., the `Foo` type in example 2 is unsound for many Copy types T, not just fn types).

We might want to explicitly call this out in more places (e.g., [in the reference](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) and [in the nomicon](https://doc.rust-lang.org/nomicon/what-unsafe-does.html)) since quite a few people trip over this, but it's not going to change.

**Comment by steveklabnik** [comment]
Let's put this stuff in `mem::zeroed`'s docs.
