### ISSUE TITLE
Cargo doc regression in crates that include #![deny(unused_imports)]

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#51661]
```rust
#![deny(unused_imports)]

use std::fs::File;

pub fn f() {
    let _: File;
}
```

`cargo doc` of the above lib.rs works up through `cargo +nightly-2018-06-17 doc`. As of `cargo +nightly-2018-06-18 doc` it fails with:

```console
$ cargo +nightly-2018-06-18 doc
 Documenting unused-imports v0.0.0
error: unused import: `std::fs::File`
 --> src/lib.rs:3:5
  |
3 | use std::fs::File;
  |     ^^^^^^^^^^^^^
  |
note: lint level defined here
 --> src/lib.rs:1:9
  |
1 | #![deny(unused_imports)]
  |         ^^^^^^^^^^^^^^

error: Compilation failed, aborting rustdoc

error: Could not document `unused-imports`.
```

**Comment by dtolnay** [comment]
That commit range: https://github.com/rust-lang/rust/compare/ae46aefd5...86a8f1a63. Mentioning @QuietMisdreavus and @GuillaumeGomez who were touching librustdoc in that range.

**Comment by GuillaumeGomez** [comment]
The problem is a bit complex (to say the least)...

**Comment by QuietMisdreavus** [comment]
The problem was the introduction of the `intra_doc_links_resolution_failure` lint, which caused rustdoc to stop capping lints:

https://github.com/rust-lang/rust/blob/f790780451a724dce9be0ba03ff217955036ff88/src/librustdoc/core.rs#L216

The sample in this issue (and the regression in winapi in https://github.com/rust-lang/rust/issues/51689) both explicitly deny the lint, despite us allowing it in rustdoc ahead of time. We need a way to disable this lint (and potentially any others that are affected by `everybody-loops`?) when rustdoc is running. Alternately, some kind of "porous lint cap" that still lets us fire the intra-doc-links lint? Is that possible with the current system?

**Comment by GuillaumeGomez** [comment]
It requires investigation but I think we can.

**Comment by GuillaumeGomez** [comment]
No, it's the same source. I know what the problem is, just need to fix it when I have time.
