### ISSUE TITLE
[Feature Request] Polymorphism

### ISSUE THREAD

**Issue by ameykshirsagar** [rust-lang/rust#51673]
Hi,
I am really excited to see Rust getting polymorphism because we have to write multiple functions for different outputs using partially same methods but morphing the result. If we can get that, Rust can take head on with Java. 
Cheers!!

**Comment by ishitatsuyuki** [comment]
Please prefer composition instead of inheritance. See https://stackoverflow.com/q/32736170/2484972 for some resources.

The issue tracker is for bug reports and small feature requests only. Big feature proposals should be filed as a RFC, and questions should be directed to Stack Overflow, https://users.rust-lang.org or a community of your choice.

**Comment by Ixrec** [comment]
Also, Rust already has compile-time polymorphism in the form of generics, and runtime polymorphism in the form of trait objects, so it's not clear what sort of "polymorphism" you're asking for. Based on the "using partially same methods" phrase in your comment, I'm guessing you'd be interested in [the current RFC for delegation](https://github.com/rust-lang/rfcs/pull/2393).

If none of those are what you were looking for, then please post a more detailed version of your question on https://users.rust-lang.org.
