### ISSUE TITLE
[feature] Support for char::from_utf8 & friends

### ISSUE THREAD

**Issue by anirudhb** [rust-lang/rust#51700]
This is exactly in the same domain as `str::from_utf8` except that it uses one character only. Also, this should exist since `char::encode_utf8` does.
The other functions (`from_utf8_mut`, `from_boxed_utf8`, etc.) should (if appropriate)
be implemented.

An implementation of this is provided below:
```rust
fn from_utf8(a: &[u8]) -> Result<char, Utf8Error> {
    let s = ::std::str::from_utf8(a)?;
    s.chars().next().unwrap()
}

unsafe fn from_utf8_unchecked(a: &[u8]) -> char {
    let s = ::std::str::from_utf8_unchecked(a);
    s.chars().next().unwrap()
}
```

I don't believe an RFC is needed; if so, please tell me.
edit: make `from_utf8_unchecked` unsafe

**Comment by bjorn3** [comment]
Should this check if there is only one char in the input?

**Comment by anirudhb** [comment]
@bjorn3 I think it should be up to the libs team to decide its behavior with multiple characters.

**Comment by SimonSapin** [comment]
What are some use cases for this? Given that we already have `str::from_utf8` I’m not sure why this should be in the standard library (as opposed to crates.io).

**Comment by anirudhb** [comment]
@SimonSapin I thought it would make sense, given we have `char::encode_utf8`.

**Comment by SimonSapin** [comment]
When you have a single `char`, or a iterator of them or whatever, there is no question what `char::encode_utf8` means. When starting with `&[u8]`, there is no question what `str::from_utf8` means either.

But when starting with `&[u8]`, what does it mean to decode a single `char`? If the byte string starts with a valid code point but then continues, do you want to return it decoded together with the rest of the bytes, so that the caller can keep decoding more? Is that considered an error same as invalid UTF-8?

These two possibilities would answer to completely different use cases. And some use cases might have a better solution, possibly one already available. The fact that you don’t care about the behavior suggests that you don’t actually want to use this function. Until someone actually wants it, I think that we should not add it just because. And even then we’d discuss what actual problem they’re solving and whether this is the best solution.

**Comment by anirudhb** [comment]
OK, thanks for your insight @SimonSapin. I'll be closing this issue since I use it the way described in the OP.
