### ISSUE TITLE
What is the easiest way to tell the parser to use 2018 edition?

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rust#51888]
Background: in tools like rustfmt, we need a way to tell the parser to use different edition. I was expecting that libsyntax provides an API like `parser_with_edition`, but could not find any.

What is the easiest way to tell the parser to use 2018 edition? If such thing does not exist, is it possible to add APIs to libsyntax for tools?

**Comment by Mark-Simulacrum** [comment]
I believe the parser does or will work on the basis of the `Span` it's parsing to determine which edition it is in. We can't have something like `parser_with_edition` since the edition is specific to macros etc across crates. However, there is `syntax_pos::hygiene::set_default_edition` which may be interesting for tools (it's what is used if `--edition 2018` is passed).

**Comment by topecongiro** [comment]
`syntax_pos::hygiene::set_default_edition` seems to solve the issue. Thank you for the reply!
