### ISSUE TITLE
PathBuf::as_mut_vec() makes assumption on the shape of OsString type.

### ISSUE THREAD

**Issue by prataprc** [rust-lang/rust#51897]
PathBuf is a wrapper around OsString. Would it be a good idea to avoid unsafe{} logic within PathBuf::as_mut_vec(), and call inner.as_mut_vec() ?

Drilling down the code path, it looks like we may need as_mut_vec() implementation for OsString and Buf types as well.

**Comment by Mark-Simulacrum** [comment]
Since these are std-internal details I think this is fine and adding those methods would mostly not be helpful (since it's not giving that many benefits). So I'm going to close this, but if someone wants to do this then I think we'd probably accept such a PR (so long as all the methods are kept private to std).
