### ISSUE TITLE
edition lint: prefer `crate` to `pub(crate)`

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#52048]

**Comment by zackmdavis** [comment]
Mentoring hints: study [the `unreachable_pub` lint](https://github.com/rust-lang/rust/blob/a22bcd8aab2905f6f5496c1ae66a45ba60ca4c90/src/librustc_lint/builtin.rs#L1387-L1432) for an example of a lint that operates on visibility modifiers, except in this case, we probably want an `EarlyLintPass` (which operates on the AST rather than the [HIR](https://rust-lang-nursery.github.io/rustc-guide/hir.html)). The `Item`, `ForeignItem`, `StructField`, and `ImplItem` AST nodes all have a `vis` field of type [`Visibility`](https://github.com/rust-lang/rust/blob/a22bcd8aab2905f6f5496c1ae66a45ba60ca4c90/src/libsyntax/ast.rs#L1965-L1973). `Visibility` has two fields: `span` (a `Span`, representing the place in the source code that the visibility modifier takes up) and `node` (which is a `VisibilityKind`). We want the lint to fire if `node` is the variant `VisibilityKind::Crate(CrateSugar)` _and_ the value it wraps is a `CrateSugar::PubCrate`. We should suggest (using [`span_suggestion_with_applicability`](https://github.com/rust-lang/rust/blob/a22bcd8aab2905f6f5496c1ae66a45ba60ca4c90/src/librustc_errors/diagnostic.rs#L299)) replacing the visibility span with the text `crate`.

**Comment by seanmonstar** [comment]
What does this mean exactly? Will the lint warn if I use `pub(crate)`? Or this is more for rustfix?

I personally find `pub(crate)` **much** clearer as a visibility modifier than just `crate`. I'd probably even want a lint in the opposite direction (warn contributors to not change things to `crate` over `pub(crate)` in libraries I maintain.

**Comment by Manishearth** [comment]
This is an edition lint; post edition upgrade this will ask you to replace `pub(crate)` with `crate`, via rustfix.

**Comment by seanmonstar** [comment]
Is there a reason to push people from `pub(crate)` to `crate`? Why not allow (as in, leave alone) `pub(crate)` to stay?

**Comment by carllerche** [comment]
👍 I agree, I find `pub(crate)` much clearer and will most likely stick with that.

**Comment by seanmonstar** [comment]
I get that, though the path changes tracking issue is so noisy, it'd get easily lost. Besides, the path changes doesn't seem to suggest that `pub(crate)` is *deprecated*, just that people who *want to* can change to `crate`. If that's the case, then this implementation issue might be slightly over-zealous.

**Comment by nikomatsakis** [comment]
I believe we are not going to stabilize `crate` in Rust 2018, correct? If so, I nominate for removal from the milestone.

**Comment by joshtriplett** [comment]
Discussion in the @rust-lang/lang meeting came to the same conclusion: this is fundamentally tied to whether we add `crate` as a visibility modifier. If we do, we want this lint; if we don't, we don't.

**Comment by jplatte** [comment]
`crate` was [removed](https://github.com/rust-lang/rust/pull/97254), pretty sure this can be closed.
