### ISSUE TITLE
Double colons (::) do dyn keyword act as undeclared

### ISSUE THREAD

**Issue by kirch7** [rust-lang/rust#52071]
When I try to compile
```rust
fn main() -> Result<(), Box<dyn ::std::error::Error>> {
    Ok(())
}
```
the compiler gives me back
```
  |
1 | fn main() -> Result<(), Box<dyn ::std::error::Error>> {
  |                             ^^^ Use of undeclared type or module `dyn`
```

It seams that is because `::` allows spaces characters, por exemple: `std :: error`.

I am not sure if this is expected, since`dyn` could be a module name, por example.

## Meta
```
> rustc --version --verbose
rustc 1.27.0 (3eda71b00 2018-06-19)
binary: rustc
commit-hash: 3eda71b00ad48d7bf4eef4c443e7f611fd061418
commit-date: 2018-06-19
host: x86_64-unknown-linux-gnu
release: 1.27.0
LLVM version: 6.0
```

**Comment by petrochenkov** [comment]
`dyn` is not a keyword, but a context-sensitive identifier due to backward compatibility.
This means it's not interpreted as a part of `dyn Trait` if other interpretations are possible, like in the case of following `::`.
The workaround is to use parentheses
```rust
fn main() -> Result<(), Box<dyn (::std::error::Error)>> {
    Ok(())
}
```
or to use `crate::` for absolute paths (it's not stable yet though)
```rust
fn main() -> Result<(), Box<dyn crate::std::error::Error>> {
    Ok(())
}
```
