### ISSUE TITLE
Consider renaming Option::and_then to flat_map, to be consistent with Iterator::flat_map

### ISSUE THREAD

**Issue by nstoddard** [rust-lang/rust#52094]
`Option` and `Result` have a method `and_then`, which has the same purpose as `Iterator::flat_map`. For consistency, we could add `Option::flat_map` and `Result::flat_map`, and possibly deprecate `and_then`.

**Comment by kennytm** [comment]
This has been suggested before and declined https://github.com/rust-lang/rust/issues/7294#issuecomment-27992095.

**Comment by nstoddard** [comment]
Why was this declined before? That comment doesn't provide any reasons for the decision.

This change would be harder to do now, since we're more concerned with backwards compatibility now, but it might still be worth doing.

**Comment by ExpHP** [comment]
> This change would be harder to do now, since we're more concerned with backwards compatibility now, but it might still be worth doing.

Such changes should not be taken so lightly!

[Look at the changelog](https://github.com/rust-lang/rust/blob/master/RELEASES.md).  The only instances I can find of anything being renamed are:

* **(1.13.0)** `SipHasher` was renamed to `DefaultHasher` (and the documentation no longer specifies the algorithm)
* **(1.3.0)** `SliceConcatExt::connect` was renamed to `SliceConcatExt::join`.
  The old name, bizarre as it was, appeared to have been because `join` was formerly a keyword. [This went through the RFC process.](https://github.com/nox/rust-rfcs/blob/master/text/1102-rename-connect-to-join.md)
* **(1.2.0)** `std::mem::min_align_of` was renamed to `std::mem::align_of` (replacing a less-useful function that no longer exists)

As far as I can tell, `flat_map` is *just another name*.  Sure, it has symmetry with iterators; but `and_then` is nice because it has symmetry with `or_else`, and because the name works just as well on types like `Result` and `Future`.

**Comment by nstoddard** [comment]
Oh, I hadn't realized methods were renamed so rarely, or that `Future` also uses the name `and_then`. Given that, I agree that this isn't worth it.
