### ISSUE TITLE
"use possibly unitialized variable" that is actually always initialized

### ISSUE THREAD

**Issue by vberger** [rust-lang/rust#52192]
This code:

```rust
fn some_test(_: i32) -> io::Result<()> {
    unimplemented!()
}

fn try_all() -> io::Result<i32> {
    let mut last_error;
    for i in 0..32 {
        match some_test(i) {
            Ok(()) => return Ok(i),
            Err(e) => last_error = e,
        }
    }
    Err(last_error)
}
```

results on this error (both stable & nightly):

```
error[E0381]: use of possibly uninitialized variable: `last_error`
  --> src/main.rs:15:9
   |
15 |     Err(last_error)
   |         ^^^^^^^^^^ use of possibly uninitialized `last_error`
```

even though it'll clearly always be initialized.

It looks like rustc fails to understand this loop is guaranteed to run at least once?

**Comment by scottmcm** [comment]
Yes.  `for` loops are over iterators, which can in general be empty, and there's nothing at type-checking time that could say "I will definitely produce at least one" -- `for i in 0..0` has exactly the same type as the example above and doesn't run the loop body.

Note that there are much simpler examples of this, like
```rust
fn foo() -> i32 {
    let x;
    while true {
        x = 4;
        break;
    }
    x // error: use of possibly uninitialized variable
}
```

So I'm going to close this as expected behaviour.

(`loop` is known to run at least once, but `while` and `for` are always considered to be zero-or-more.)
