### ISSUE TITLE
liballoc doc tests are "silently" failing

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#52243]
I noticed this in the output running `python x.py test` locally:

```
   Doc-tests alloc
error: no global memory allocator found but one is required; link to std or add #[global_allocator] to a static item that implements the GlobalAlloc trait.
```

and that didn't make tests fail.

Cc: @SimonSapin

**Comment by glandium** [comment]
Same with panic_unwind:
```
   Doc-tests panic_unwind
error: no global memory allocator found but one is required; link to std or add #[global_allocator] to a static item that implements the GlobalAlloc trait.
```

**Comment by SimonSapin** [comment]
This error message is printed when running `rustdoc --test src/liballoc/lib.rs […]`, but before running any test. The code printing it is in `src/librustc_metadata/creader.rs`. It looks like rustdoc is using that code in order to load the crate and find doctests in it. But since it’s not actually compiling this crate, not having an allocator is not a problem.

So I think there are two issues:

* rustdoc keeps doing its thing even though there are errors. It probably should call something like `abort_if_errors` on its `rustc::session::Session` instance at some point.
* This error should not occur in the first place. One way to inhibit it would be to tell `creader` that we’re "compiling" an rlib (`CrateTypeRlib`) rather than some other crate type. rlibs do not need (yet) to have an allocator defined. This is possibly this line:

https://github.com/rust-lang/rust/blob/4700e1188f66fdb4086b7593416b678b8fe935f4/src/librustdoc/test.rs#L76

The first issue could in some other situation hide a real problem, but in this case it makes the second one mostly harmless. The only bad consequence is some noise in the output of a test run.

**Comment by RalfJung** [comment]
Related: https://github.com/rust-lang/rust/issues/54010
