### ISSUE TITLE
Nonsense suggestion for `concat!(x)`

### ISSUE THREAD

**Issue by ollie27** [rust-lang/rust#52347]
The error for `concat!(x)` is:

```
error: expected a literal
 --> src/main.rs:2:13
  |
2 |     concat!(x);
  |             ^
help: you might be missing a string literal to format with
  |
2 |     concat!("{}", x);
  |             ^^^^^^^
```

That suggestion will clearly not work and gets worse when there are more arguments:

```
error: expected a literal
 --> src/main.rs:2:13
  |
2 |     concat!(x, y, z);
  |             ^
help: you might be missing a string literal to format with
  |
2 |     concat!("{}", x, y, z);
  |             ^^^^^^^

error: expected a literal
 --> src/main.rs:2:16
  |
2 |     concat!(x, y, z);
  |                ^
help: you might be missing a string literal to format with
  |
2 |     concat!(x, "{}", y, z);
  |                ^^^^^^^

error: expected a literal
 --> src/main.rs:2:19
  |
2 |     concat!(x, y, z);
  |                   ^
help: you might be missing a string literal to format with
  |
2 |     concat!(x, y, "{}", z);
  |                   ^^^^^^^
```

This suggestion was added by #51614. cc. @csmoe, @estebank

**Comment by estebank** [comment]
@csmoe, we might get away with `println` calling a specialized `concat` where the builtin is just one method with different diagnostics depending on the callee. Just a thought though, you'll likely find a better solution :)

**Comment by estebank** [comment]
It'd be ideal if we could also keep the `expected a literal` messages to a minimum, by emitting only one diagnostic with a `MultiSpan` primary span. (In the last example, instead of three errors, only one pointing at all three arguments.)

**Comment by csmoe** [comment]
@estebank I suspect this issue is more complex than I used thought, here is a testcase:
```rust
fn main() {
    concat!(a);     // ERROR: ("{}", a)
    println!(a);    // FINE: ("{}", a)
}
```
[playgroud](http://play.rust-lang.org/?version=nightly&mode=debug&edition=2015)
Since we are working with `concat.rs` here, when only ONE arg is passed into them, the emitted `"{}", foo` message ONLY helps `println!`, not `concat!`. And we cannot distinguish between `println!` and `concat!` here(only-one-arg-passed-in method fails), so I think such kind of help-message is blocked by the [mixed literal and format string issue](https://github.com/rust-lang/rust/issues/30143), and https://github.com/rust-lang/rust/pull/51614 should be retrieved.

**Comment by ollie27** [comment]
What I think should be done is for the suggestion to be moved to `format_args!` where it should always make sense. It would then work for macros like `write!`, `print!`, `format!` and `format_args!` itself. Then to get it working for the `*ln!` macros fixing #30143 would be enough. Maybe the prospect of better diagnostics would persuade people that it's worth fixing.
