### ISSUE TITLE
unused_extern_crates lint should handle aliasing

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#52451]
e.g., `extern crate rls_span as span;`. I'm not sure what the suggestion should be though = `pub use ... as ...;` to replace the `extern crate`?

**Comment by CryZe** [comment]
Last time I checked pub use doesn't actually reexport crates as reported here: https://github.com/rust-lang/rust/issues/52140

**Comment by alexcrichton** [comment]
Some data points:

* As of today's nightly this construct [emits a warning](https://play.rust-lang.org/?gist=8437c9326a474dc1bdef0207dc335f60&version=nightly&mode=debug&edition=2018) that indicates that a `use` statement should be used instead, but no rustfixable suggestion is emitted.
* However, [precisely the same warning](https://play.rust-lang.org/?gist=2952137838adfe3c2fa38ca1d8db4e68&version=nightly&mode=debug&edition=2018) happens for a non-renamed crate as well (this was reported as https://github.com/rust-lang/rust/issues/52832)
* If the crate isn't actually used you [get a warning to remove it](https://play.rust-lang.org/?gist=18e1709ed1d3df40598d3eda4d5e295e&version=nightly&mode=debug&edition=2018)
* When migrating 2015 code relying on `extern crate` renaming you [get a suggestion to use `crate::`](https://play.rust-lang.org/?gist=6a44e65516a9da004a663e0f87295902&version=nightly&mode=debug&edition=2015) which [does indeed work](https://play.rust-lang.org/?gist=da225da787108bead33bc0e8aa732322&version=nightly&mode=debug&edition=2015)

This all makes sense with [today's implementation](https://github.com/rust-lang/rust/blob/61b00727076ce251b54bdefa18779a13819d2209/src/librustc_typeck/check_unused.rs#L84-L182) which [only emits suggestions for 2018 code](https://github.com/rust-lang/rust/blob/61b00727076ce251b54bdefa18779a13819d2209/src/librustc_typeck/check_unused.rs#L151-L155) and [doesn't emit machine-applicable suggestions](https://github.com/rust-lang/rust/blob/61b00727076ce251b54bdefa18779a13819d2209/src/librustc_typeck/check_unused.rs#L168-L180).

Given all that I'm going to close this issue in favor of https://github.com/rust-lang/rust/issues/52829. I think it's basically just a bug in the compiler today that we're not emitting rustfixable suggestions for removing `extern crate` annotations. Fixing https://github.com/rust-lang/rust/issues/52829 will involve taking this issue into account, but otherwise I think that this is an issue currently about a hypothetical buggy implementation that doesn't implement handling renames, but an implementation doesn't even exist today!
