### ISSUE TITLE
[Rust 2018] rustdoc doesn't link "pub use whatever_crate;"

### ISSUE THREAD

**Issue by crepererum** [rust-lang/rust#52509]
## Rust 2015 (`1.27.1`)
![screenshot from 2018-07-18 22-36-24](https://user-images.githubusercontent.com/1529400/42906316-1e6addf8-8adb-11e8-9ef9-a1a4558d9f13.png)

## Rust 2018 (preview at `1ecf6929d 2018-07-16`)
![screenshot from 2018-07-18 22-36-49](https://user-images.githubusercontent.com/1529400/42906323-23dd4276-8adb-11e8-88d6-6da55f2a54b7.png)

**Comment by crepererum** [comment]
Please can someone give this a `A-rust-2018-preview` label?

**Comment by nikomatsakis** [comment]
Nominating for prioritization. cc @rust-lang/docs -- this is a rustdoc bug, is there someone who wants to tackle it?

I added T-compiler so that we take a look at the next compiler meeting otherwise.

**Comment by nikomatsakis** [comment]
cc @GuillaumeGomez -- any news?

**Comment by GuillaumeGomez** [comment]
Busy then sick so nothing, sorry about that.

**Comment by pnkfelix** [comment]
discussed at compiler team meeting. Taking off RC2.

**Comment by nikomatsakis** [comment]
@GuillaumeGomez ok — if you still have time to tackle, great! Otherwise, let us know and we can find someone to take a peek.

**Comment by GuillaumeGomez** [comment]
If I haven't finish this week-end, then please please ask someone else.

**Comment by GuillaumeGomez** [comment]
So, here what we got: in here, `pub use` imported crates are defined as `ImportItem(Glob(ImportSource))`. Inside it, I found absolutely no track of any possible way to determine if it's how an extern crate is imported or not. Also, here's the current rustdoc output:

<img width="1440" alt="screen shot 2018-10-20 at 17 32 06" src="https://user-images.githubusercontent.com/3050060/47259885-19166c80-d4b1-11e8-8883-687d016c2c38.png">

(Yes, in "Modules".)

**Comment by pnkfelix** [comment]
I'll see what I can do to help here.

**Comment by QuietMisdreavus** [comment]
I think we can modify [`impl Clean for doctree::Import`](https://github.com/rust-lang/rust/blob/694cf752988728ba5da85c36c2deaeefeb49c05e/src/librustdoc/clean/mod.rs#L3488) to check if a "single" import that is importing a module is actually the root of a different crate, then refuse to inline it? That at least makes it appear like an import:

![image](https://user-images.githubusercontent.com/5217170/47578420-f6e87880-d90e-11e8-9ad4-3a1c97a62c0f.png)

(This sample was made by applying `#[doc(no_inline)]` to the `pub use qwop;` statement, which provides the same effect.)

Alternately, after that check, we could generate a `pub extern crate` item instead of an import, which would unify it with the 2015 output. On that note, do we even want to try unifying these outputs? Do we always want docs to look like the latest edition (which would require that we start changing how we render existing `pub extern crate` statements), or do we render based on the edition passed to rustdoc (which makes docs look different based on the crate being documented)? I'm leaning toward "modify docs to look like newest edition", but i'm going to punt to @rust-lang/docs for that one.

In the immediate term, i guess this issue is now about the eager inlining of external crates as if they were modules inside the current crate, which drives me back to my earlier suggestion.

**Comment by pnkfelix** [comment]
T-compiler triage. Tagging P-high. Leaving assigned to self.

**Comment by QuietMisdreavus** [comment]
I've opened https://github.com/rust-lang/rust/pull/55804 to make `pub use some_crate` turn into a plain re-export in the docs, which should at least help this out.

**Comment by nikomatsakis** [comment]
@QuietMisdreavus would you call this a "blocker" for the final release? Do you think we should backport our fixes?

**Comment by QuietMisdreavus** [comment]
@nikomatsakis The bug, as it stands today, is benign and has a small workaround, namely adding `#[doc(no_inline)]` to the re-export. I'm okay if https://github.com/rust-lang/rust/pull/55804 is not backported, if we're okay with advertising that fix for one version.

The broader question of "do we want to adapt docs to look like a different edition from what it was compiled for" is something i wanted to get input from @rust-lang/docs on. If we leave this as-is, we default to "no", but i think we can leave the question open for future work, especially with the edition code freeze just next week.

**Comment by steveklabnik** [comment]
> Do we always want docs to look like the latest edition (which would require that we start changing how we render existing pub extern crate statements), or do we render based on the edition passed to rustdoc (which makes docs look different based on the crate being documented)? I'm leaning toward "modify docs to look like newest edition", but i'm going to punt to @rust-lang/docs for that one.

I feel like the *right* thing is "based on the edition passed to rustdoc", but I'd be fine with either, to be honest.

**Comment by Havvy** [comment]
I said prior on Discord that it'd be nice to have a toggle on the page itself without giving it too much thought. A little more thought, and I realized that since we can `cargo doc` and get docs of all dependencies as well, we can just render based on the edition of the crate we are ultimately working on. Though how that works for online docs is a bit iffy. It'd be nice to see the stdlib docs in each edition and perhaps likewise with docs.rs?

**Comment by nagisa** [comment]
Removing T-compiler, as it seems that this issue is not critical for Rust2018 and involvement of T-compiler to help getting this fixed ASAP is not necessary.

**Comment by alexcrichton** [comment]
@QuietMisdreavus has mentioned on discord that https://github.com/rust-lang/rust/pull/55804 has fixed this issue enough for the edition, so I'm going to remove it from the milestone and also remove the P-high tag

**Comment by jyn514** [comment]
This is working on master: 
![image](https://user-images.githubusercontent.com/23638587/114075310-6bab9500-9873-11eb-9e81-8602d0f85037.png)
