### ISSUE TITLE
src/liballoc/alloc.rs:169: undefined reference to `<core::ptr::Unique<T>>::as_ptr'

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#52528]
Tests with `panic=abort` cause

```
In function `alloc::alloc::box_free':
          /home/oliver/Projects/rust/rust3/src/liballoc/alloc.rs:169: undefined reference to `<core::ptr::Unique<T>>::as_ptr'
          /home/oliver/Projects/rust/rust3/src/liballoc/alloc.rs:169: undefined reference to `<core::ptr::Unique<T>>::as_ptr'
          /home/oliver/Projects/rust/rust3/src/liballoc/alloc.rs:169: undefined reference to `<core::ptr::Unique<T>>::as_ptr'
          collect2: error: ld returned 1 exit status
```

For me locally.

This isn't happening on Travis.

Maybe it's

* debuginfo,
* fullmir
* incremental

related? Because I have all of these set in my config.toml. Has been happening since I rebased yesterday.

I'll investigate locally.

**Comment by pnkfelix** [comment]
One thing I just realized: some of our bugs seem very sensitive to whether you are running under optimize or not (i.e. are you compiling the tests with `-O`).

See for example #54153

I often have `optimize-tests` set to false in my config.toml without even thinking about it, but the default is true.

(I also don't know what setting I am using that is exposing the problems that I see that are similar to that listed by @varkor above, but I currently hypothesize that I am seeing it in the context of a build with `optimize-tests` set to false.)

What about you two, @oli-obk and @varkor ? Do you override that setting typically/often? Or do you usually leave it at its default of false?

(I ask mainly because I am continuously wondering why other people, and our continuous-integration server, do not run into these issues...)

**Comment by varkor** [comment]
I think I've only ever tried testing these with the default optimisation mode.

**Comment by oli-obk** [comment]
I don't think I have set tests to run without optimizations

**Comment by steveklabnik** [comment]
@oli-obk are you still seeing this?

**Comment by oli-obk** [comment]
I haven't seen this in a long time. Not sure what changed.
