### ISSUE TITLE
Parse IPv4 addr 127.1

### ISSUE THREAD

**Issue by kpp** [rust-lang/rust#52550]
127.1 is a valid IPv4 addr equals to 127.0.0.1 according to https://www.quora.com/Is-127-1-a-valid-IP-address. 

I tried this code:
```rust
assert_eq!("127.1".parse::<Ipv4Addr>().unwrap(), Ipv4Addr::new(127, 0, 0, 1));
```

I expected to see this happen: test passes.

Instead, this happened:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AddrParseError(())', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

MRE: https://play.rust-lang.org/?gist=e8591b1f1f5710b2438c45ab42928bb0&version=stable&mode=debug&edition=2015

**Comment by nodakai** [comment]
A legacy API called `inet_addr()` had such a "feature", but its younger cousin `inet_pton()` was defined not to.

* http://pubs.opengroup.org/onlinepubs/9699919799/functions/inet_ntop.html

> The `inet_pton()` function does not accept other formats (such as the octal numbers, hexadecimal numbers, and fewer than four numbers that `inet_addr()` accepts).

So that's basically a legacy specification that the industry has agreed to abandon a while ago.

But it's also true that the more "user-friendly" `getaddrinfo()` is still supposed to accept whatever acceptable for `inet_addr()`:

* http://pubs.opengroup.org/onlinepubs/9699919799/functions/getaddrinfo.html

> If the `nodename` argument is not null, it can be a descriptive name or can be an address string. ...snip... If the specified address family is `AF_INET` or `AF_UNSPEC`, address strings using Internet standard dot notation as specified in `inet_addr` are valid.

This is probably not to surprise legacy configs assuming the existence of `inet_addr()`.

To me, such shorter-than-quadruple addresses seem to be associated too tightly with the idea of classful addressing which nobody cares about nowadays (everyone uses more flexible CIDRs) and I personally wouldn't love them.

Are you actually in need of a parser function supporting such legacy address notations, or just seeking for feature-completeness?

**Comment by kpp** [comment]
> Are you actually in need of a parser function supporting such legacy address notations, or just seeking for feature-completeness?

Actually I don't need it. Just asking the reason why I was not implemented.

**Comment by Mark-Simulacrum** [comment]
Given that this is a legacy specification, and no one has actually volunteered a need for this, I'm going to close this issue. If someone actually wants this, please let us know and we can reopen to consider whether we want to include it in std.
