### ISSUE TITLE
Possible Rust Compiler Bug/Error --- Probably Benign

### ISSUE THREAD

**Issue by jbendor-dsc** [rust-lang/rust#52600]
BY: Jonny Bendor --- email: "rodneab@retet.net" --- GitBub account: "jbendor-dsc"

$ rustc --version
rustc 1.27.1 (5f2b325f6 2018-07-07)

The attached Rust code is trivial, and seems to be valid, but the Rust compiler complains.

Specifically, all is fine when line 45 is commented and line 49 is "Un-Commented" --- The program reads 10 bytes from a named file.

Yet, the compiler issues a bizarre error when line 49 is commented and line 45 is "Un-Commented", as shown in the attached PNG and LOG files.

[RUST.compiler.log](https://github.com/rust-lang/rust/files/2216616/RUST.compiler.log)

[main.rs.txt](https://github.com/rust-lang/rust/files/2216617/main.rs.txt)

![rust compiler problem](https://user-images.githubusercontent.com/2029869/43041045-c8ad5b26-8d09-11e8-84ab-6bc311e05a4a.png)

IMHO, the "lifetimes" of the (relevant) variables are wrongly "estimated/analyzed" by the compiler.

Jonny

**Comment by scottmcm** [comment]
This already compiles with the upcoming NLL feature: https://play.rust-lang.org/?gist=d38d99a3e6c4f00c3b8141d4a8520550&version=nightly&mode=debug&edition=2015

The error in stable is correct by the current rules because if `read_txt` is declared on line 45, it outlives `bytes_vec`, so cannot have a reference to `bytes_vec`, as the code is trying to do.  This is made more clear by the addition of a block and trying to use `read_txt` outside it: https://play.rust-lang.org/?gist=f2979e101f51c3fbc73b3fbf4500837b&version=nightly&mode=debug&edition=2015

**Comment by jbendor-dsc** [comment]
ThanksScott,

I actually understood the problem shortly after submitting it --- Didn't expect a reply so quickly.

The "actual" cause of MY error was considering "text-constants" as Strings --- This is not so in Rust.

Also, the compiler's report did NOT mention that "read_txt" COULD have a reference to "bytes-vec".

Jonny
