### ISSUE TITLE
Remove `extern crate` when migrating to Rust 2018

### ISSUE THREAD

**Issue by johnthagen** [rust-lang/rust#52829]
Migrated from https://github.com/rust-lang/cargo/issues/5829

It's been mentioned/requested multiple times on the [internals thread](https://internals.rust-lang.org/t/help-test-out-the-2018-module-system-changes/8047/21?u=johnthagen) that `cargo fix` should remove the `extern crate` statements when moving to Rust 2018.

# Motivation

One of the big draws of Rust 2018's module system is that all of the "redundant" `extern crate` lines can finally be removed. It took some of the excitement away when I went through all of the `cargo fix` steps and still saw them there. I think it will just be a better experience for users to see one of the tangible benefits of this change. As it is right now, they just see the `crate::` in front of all of their local imports and they might not realize what a nice change the module system updates really are.

After I manually removed the `extern crate`'s I did get my satisfying result 😄, but let's give this to users on the first go around.

# Implementation

If I understand correctly this should be implemented in the compiler under the `#![warn(rust_2018_idioms)]` lints, rather than `cargo fix` itself.

cc @alexcrichton

**Comment by alexcrichton** [comment]
I'm moving this forward up on the milestone list due to just having closed https://github.com/rust-lang/rust/issues/52451 in favor of this issue, which was itself on the RC milestone.

**Comment by alexcrichton** [comment]
Ok so I've some triaging of `extern crate` related lint issues, and I believe the current work items are:

* A rustfix-fixable suggestion for removing `extern crate` needs to be implemented. The implementation would [go here](https://github.com/rust-lang/rust/blob/61b00727076ce251b54bdefa18779a13819d2209/src/librustc_typeck/check_unused.rs#L164-L180).
* Currently the lint suggests switching to simply `use`. While technically correct and handles lots of corner cases, this doesn't achieve the desired goal of actually removing annotations.
* We can't blanket remove all `extern crate` statements, for example [this test case](https://play.rust-lang.org/?gist=c6bbdc82f47896528b34bbe3f03473b5&version=nightly&mode=debug&edition=2018) is correctly warned to use a `use` rather than deleting the statement outright.

I'm testing out some ideas locally as well.

**Comment by alexcrichton** [comment]
I believe this should be fixed by https://github.com/rust-lang/rust/pull/53684, I think the naive solution actually works well!
