### ISSUE TITLE
Update to LLVM 7.0

### ISSUE THREAD

**Issue by dylanmckay** [rust-lang/rust#52970]
LLVM 7.0 has been branched as of 2018-08-01, with the final tag probably a couple weeks away.

The first release candidate will be tagged in a couple of days.

[Here](https://lists.llvm.org/pipermail/llvm-dev/2018-August/125004.html) is the llvm-dev announcement, and [here](https://github.com/llvm-mirror/llvm/commits/release_70) is a view of the commits on the branch.

Once the final release has been tagged, Rust should be updated to LLVM 7.0.

**Comment by alexcrichton** [comment]
Great! 

I've started our branches:

* [rust-lang/llvm](https://github.com/rust-lang/llvm/tree/rust-llvm-release-7-0-0-v2)
* [rust-lang/lld](https://github.com/rust-lang/lld/tree/rust-llvm-release-7-0-0-v2)
* [rust-lang/compiler-rt](https://github.com/rust-lang/compiler-rt/tree/rust-llvm-release-7-0-0-v2)
* [rust-lang-nursery/compiler-builtins](https://github.com/rust-lang-nursery/compiler-builtins/tree/rust-llvm-release-7-0-0-v2)

I'm hoping that this'll be pretty smooth since we upgraded most of the way through the cycle! I'm testing locally now and will send a PR once green.
