### ISSUE TITLE
Performance cliff when parsing f64 above 1e305

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#53015]
I noticed the following performance cliff of 3 orders of magnitude:

```rust
#![feature(test)]

#[cfg(test)]
extern crate test;

#[bench]
fn bench_parse_1e304(b: &mut test::Bencher) {
    // Anything under 1e305 is reasonably fast: ~120 ns/iter
    b.iter(|| "1.234e304".parse::<f64>());
}

#[bench]
fn bench_parse_1e305(b: &mut test::Bencher) {
    // Anything 1e305 or above is slower by 3 orders of magnitude: ~220,000 ns/iter 
    b.iter(|| "1.234e305".parse::<f64>());
}
```

[Playground that reproduces the same behavior.](https://play.rust-lang.org/?gist=8a9e7f5cb9f7861f80bd5999c9433c18&version=nightly&mode=release&edition=2015)

I tried Go and it parses both inputs in 60 ns. The resulting bits are the same in both implementations.

```go
package test

import (
	"strconv"
	"testing"
)

func BenchmarkFast(b *testing.B) {
	for n := 0; n < b.N; n++ {
		strconv.ParseFloat("1.234e304", 64)
	}
}

func BenchmarkAlsoFast(b *testing.B) {
	for n := 0; n < b.N; n++ {
		strconv.ParseFloat("1.234e305", 64)
	}
}
```

**Comment by kennytm** [comment]
Parsing `0.99e305` is also fast 🤔

**Comment by kennytm** [comment]
https://golang.org/src/strconv/atof.go:

```go
// decimal to binary floating point conversion.
// Algorithm:
//   1) Store input in multiprecision decimal.
//   2) Multiply/divide decimal by powers of two until in range [0.5, 1)
//   3) Multiply by 2^precision and round to get mantissa.
```

**Comment by rkruppe** [comment]
The general shape of the algorithm as quoted by @kennytm is also what we're doing in the slow path. I haven't read the Go code in detail yet, but it also seems to have fast paths that don't construct any bignums. So my assumption is that this fast path is taken more often than the one in the Rust implementation (i.e., the check whether it's safe is more accurate) and that's why 1e305 is faster. Presumably there will be a similar performance cliff if you find an input that does force Go to actually go the bignum route.
