### ISSUE TITLE
When lint attributes in the same scope overlap, all but the last declared one are dropped

### ISSUE THREAD

**Issue by FaultyRAM** [rust-lang/rust#53079]
```rust
#![forbid(warnings)]
#![allow(dead_code)]

struct Foo;

fn main() {}

```

[Playground link](http://play.rust-lang.org/?gist=94ac02e3892180958a95d956fddc38c5)

The above code should fail to compile with an error about trying to `allow` a `forbid`den lint, but successfully builds without any warnings. Tested on latest stable/beta/nightly.

**Comment by zackmdavis** [comment]
At least one thing that's going on here is that `warnings` isn't (as one might intuitively think) an ordinary lint group that happens to contain all lints. Rather, it's a special magic setting that [makes lints deny when they otherwise would have warned](https://github.com/rust-lang/rust/blob/6e63b0dbedd5d4617d95aee1a42b9345b180d27b/src/librustc/lint/levels.rs#L103-L117). This is pretty confusing and should at least be better documented.

It looks like it might _also_ be the case that directives at the same scope can clobber each other? So

```rust
#![forbid(dead_code)]
#![allow(dead_code)]

struct Foo;

fn main() {}
```

surprisingly works, but

```rust
#![forbid(dead_code)]

#[allow(dead_code)]
struct Foo;

fn main() {}
```

fails as expected.

**Comment by Enselic** [comment]
This issue can be closed because this was fixed by https://github.com/rust-lang/rust/pull/81556

```console
$ rustc +1.71 main.rs
warning: allow(dead_code) incompatible with previous forbid
 --> /home/martin/src/bin/src/main.rs:2:10
  |
1 | #![forbid(warnings)]
  |           -------- `forbid` level set here
2 | #![allow(dead_code)]
  |          ^^^^^^^^^ overruled by previous forbid
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #81670 <https://github.com/rust-lang/rust/issues/81670>
  = note: `#[warn(forbidden_lint_groups)]` on by default

warning: 1 warning emitted
```
