### ISSUE TITLE
Implicit relationship between FromStr and TryFrom

### ISSUE THREAD

**Issue by npmccallum** [rust-lang/rust#53167]
When `TryFrom` is stabilized, it would be really nice if there were an implicit relationship between `TryFrom` and `FromStr`. For example:

```rust
impl<'a, T: TryFrom<&'a str>> FromStr for T {
    type Err = T::Error;

    fn from_str(value: &'a str) -> Result<T, Self::Err> {
        T::try_from(value)
    }
}
```

I think, for stability reasons, that this can only be done before `TryFrom` is stabilized.

**Comment by sfackler** [comment]
That implementation can't be added without specialization.

**Comment by czipperz** [comment]
What's the status of this?

**Comment by sfackler** [comment]
> That implementation can't be added without specialization.

**Comment by Mark-Simulacrum** [comment]
Since it's true that we can't add this without specialization, and we've stabilized TryFrom already, I believe that we can basically conclude that this is not something that we can add today. I also believe that this is a sort of unnecessary blanket impl to add so would not want to see it personally too. Closing.
