### ISSUE TITLE
error message found by NLL in `librustc_codegen_llvm`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#53221]
Trying to port `librustc_codegen_llvm` to use NLL (cc #53172) yields these errors:

https://gist.github.com/memoryruins/14a2aad7fc85d0429ae9e4240ec0dacb

The error seem legitimate. I reduced the pattern in question to this test case:

https://play.rust-lang.org/?gist=6e22b15051f9a108d09f28a0b657f717&version=nightly&mode=debug&edition=2015

As far as I can tell, the `Some(child.raw)` is interpreted as a `Some(&mut *child.raw)`, which borrows from `Child` -- but that borrow outlists the variable `child`. And `child` has a dtor that frees memory. So something may be legitimately wrong here?

You can solve this by adding a `take` method that clears the `raw` field afterwards:

https://play.rust-lang.org/?gist=64c20d529ad49d5871417c391a8dbcde&version=nightly&mode=debug&edition=2015

But I'm not sure what is the intention.

cc @eddyb @irinagpopa

**Comment by nikomatsakis** [comment]
Putting on the 2018 RC since this blocks #53172.

**Comment by nikomatsakis** [comment]
Here is the code that is failing to compile:

https://github.com/rust-lang/rust/blob/fbb6275f4fd6cf774e1789fabfacae7248c45021/src/librustc_codegen_llvm/back/archive.rs#L239-L254

**Comment by eddyb** [comment]
What happens if this line is changed from `&'a ArchiveChild` to `&ArchiveChild<'a>`?
https://github.com/rust-lang/rust/blob/b73535f1e9c46a698527fab51b1cc9fad3f53412/src/librustc_codegen_llvm/llvm/ffi.rs#L1567

An `&ArchiveChild` doesn't *point into* the archive itself, it points to an owned object *that itself* points to the archive, and `LLVMRustArchiveMemberNew` copies the `ArchiveChild` (whereas the current signature suggests it keeps the `&ArchiveChild`).

**Comment by memoryruins** [comment]
@eddyb your suggestion was on point :)
fixed in commit: https://github.com/rust-lang/rust/pull/53297/commits/085535bbe1da2350fb1c58907bf63df446e03dff
merged in rollup: https://github.com/rust-lang/rust/pull/53297

**Comment by nikomatsakis** [comment]
I'll close this then.
