### ISSUE TITLE
Do you allow or disallow distribution of rust programming language due to trademark issue?

### ISSUE THREAD

**Issue by 717g301github** [rust-lang/rust#53285]
Please read the issue at Hyperbola GNU/Linux-libre system distribution:
https://issues.hyperbola.info/index.php?do=details&task_id=736

and give us clear answer if there is permission, without problems with trademark "Rust" to distribute the package according to GNU public license as it is on this website.

**Comment by steveklabnik** [comment]
I am not a lawyer; this is a legal question, for real legal advice, please consult a lawyer.

> to distribute the package according to GNU public license as it is on this website.

We distribute Rust under the MIT and Apache2 licenses; in order to change the license the the GPL, you would have to get all the contributors to agree to change the license.

The MIT license is GPL compatible, though.

I have never heard of the "hyperbola" distribution, and so don't know what your distro's rules are, so I don't know if that's good enough for you. Debian currently packages both, as do many other distros.

That thread seems to have some confusion about the trademark on the name; it is true that both "Rust" and "Cargo", as well as their respective logos, are trademarked. Without knowing how your distro plans to make modifications, I can't say if those modifications would be acceptable under

>  We will usually allow these uses as long as the modifications are (1) relatively small and (2) very clearly communicated to end-users.

Additionally, as https://www.rust-lang.org/en-US/legal.html says

> . If you want to use these names or brands, especially in a commercial way, please read this page or feel free to reach out and ask us about it!

where "reach out" is a link to `trademark@rust-lang.org`. This conversation should be pursued through that email address, rather than on the bug tracker. We try to keep the bug tracker for bugs only. As such, I'm going to close this, but please follow up via that email address. Thanks!
