### ISSUE TITLE
The "future_atomic_orderings" feature is broken.

### ISSUE THREAD

**Issue by lachlansneff** [rust-lang/rust#53391]
Compiling code that matches against `core::sync::atomic::Ordering` requires the `future_atomic_orderings` feature to be enabled. But, when I enable that feature, I get 
```
error[E0635]: unknown feature `future_atomic_orderings`
  --> src/main.rs:33:5
   |
33 |     future_atomic_orderings,
   |     ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by varkor** [comment]
This is a bug with the feature collector; thanks for pointing it out!

Not that in this case specifically, it shouldn't be a problem anyway. You can match over all variants of `core::sync::atomic::Ordering` _except_ for `Ordering::__Nonexhaustive`. This is specifically hidden so that you _don't_ try to exhaustively match the enum. You should be using a catch-all `_` arm instead.

Really, `Ordering` should be using `#[non_exhaustive]` instead.

**Comment by lachlansneff** [comment]
Yeah, that's how I'm sidestepping this bug for now, but actually, the code in libcore does match against the `__Nonexhaustive` case, which I was largely copying.
