### ISSUE TITLE
async/await: “the requirement `for<'r> 'r : 'static` is not satisfied” with `'static` across await point

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#53548]
(continuation of https://github.com/rust-lang-nursery/futures-rs/issues/1199 as it looks like a compiler bug after all, important points repeated here)

### Problem

There appear to be an issue in handling traits that have a parent `'static` bound boxed through an await point: the following example fails to compile with `the requirement `for<'r> 'r : 'static` is not satisfied` (note: I'm using generators for simplicity of reproduction, see below for a futures-only example)
```rust
trait Trait: 'static {}
async fn foo(b: Box<Trait + 'static>) -> () {
    let bar = move || { b; () };
    yield
}
```
[(playground link)](https://play.rust-lang.org/?gist=7ec91101db1560175685897700a47aaa&version=nightly&mode=debug&edition=2015)

However, when removing the `'static` bound on `Trait`, it appears to compile correctly, even though the `Box` itself still has the `+ 'static` bound.
```rust
trait Trait {}
async fn foo(b: Box<Trait + 'static>) -> () {
    let bar = move || { b; () };
    yield
}
```
[(playground link)](https://play.rust-lang.org/?gist=05492dee18f45fa969d7d3469f04add4&version=nightly&mode=debug&edition=2015)

### Futures-only version

The error originated in code that looked like:
```rust
use futures::future;                                  
use std::any::Any;                                    
async fn foo(b: Box<Any + Send + 'static>) -> () { 
    await!(future::lazy(move |_| {                    
        b;                                          
        ()                                            
    }))                                               
}    
```
The `Any` being here the trait that has the `'static` bound. This was tested with `futures-rs` at commit https://github.com/rust-lang-nursery/futures-rs/commit/c02ec75a155485ff4b50f21205b6a462851b08e1 and nightly 2018-08-14.

### No generator-only version

I couldn't manage to get a generator-only version to fail: this compiles.
```rust
use std::any::Any;
use std::ops::Generator;
fn send(msg: Box<Any + 'static>) -> impl Generator + 'static {
    || {
        let mut pinned = move || { msg; () };
        yield
    }
}
```
[(playground link)](https://play.rust-lang.org/?gist=7f9438aec5f66c39a3e5dcd5aeeea57e&version=nightly&mode=debug&edition=2015)

### Potentially related issue

This is potentially related to https://github.com/rust-lang/rust/issues/53259, as the same `for<'r>` appears there?

**Comment by Ekleog** [comment]
Some work has started on https://github.com/rust-lang/rust/pull/53736 ; the information there will likely be helpful to someone trying to fix this.

**Comment by nikomatsakis** [comment]
I'm marking this issue as **blocking** the async-await stabilization -- if nothing else, we need to investigate it and figure out what is going on.

**Comment by nikomatsakis** [comment]
I did some more digging into this problem. This code will actually ICE if using a version of rustc built with debug assertions. Moreover, the follow example code -- which doesn't use generators at all -- will ICE in the same way:

```rust
use std::cell::RefCell;
use std::rc::Rc;

trait Trait: 'static {}

struct Store<C> {
    inner: Rc<RefCell<Option<C>>>,
}

fn main() {
    let store = Store::<Box<for<'a> fn(&(dyn Trait + 'a))>> {
        inner: Default::default(),
    };
}
```

the problem here ultimately has to do with the way that the WF code works. I left some [obscure notes on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/187312-t-compiler.2Fwg-async-await/topic/.60for.3C'r.3E.20'r.20.3A.20'static.60.20is.20not.20satisfied.20.2353548/near/160517487), but the bottom line is something like this:

- The WF code presently descends through binders but (generally speaking) opts not to prove WF conditions that involve higher-ranked regions.
- The strategy was described as "lazy" in the relevant RFC, but with the new universes code we can generally try to pursue something better, so I hope to get rid of it sooner or later.
- Anyway the idea is that whenever a higher-region is "expanded" with a particular value, we'll prove the WF at that point. 

So in this particular case we wind up with a type `for<'a> (dyn Trait + 'a)` -- for this type to be WF, the region bound `'a: 'static` must hold. We are producing this constraint. If debug assertions are enabled, we ICE out because the constraint isn't supposed to include higher-ranked regions (here, `'a`). But without debug assertions, we fail to detect that, and then we just wind up failing to prove it. 

It's kind of hard to stumble across this ICE normally, because `dyn Trait` defaults to `dyn Trait + 'static` since we see the `'static` bound declared on `Trait`. However, with **generators**, it occurs more readily because when constructing the generator witness, we replace the `'static` with a bound region (we replace *all* the internal regions in this way).

Pursuant with the existing lazy strategy, I think the right fix is just for the wf code to ignore the `'a: 'static` constraint -- and that is a small patch to do. I will probably open a PR around this shortly.

**Comment by Ekleog** [comment]
Great, thank you! I can confirm that on latest nightly the issue is no longer there :D
