### ISSUE TITLE
Transition graph of some of the most common stdlib types

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#53556]
In the Rust documentation I'd like an image similar to the graph of page 71 in "How to think in Rust" by Nick Cameron, RustConf 2018:

https://github.com/nrc/talks/blob/master/rustconf-2018-pub.pdf

The slide: https://imgur.com/a/Y5E8qn3

**Comment by Havvy** [comment]
We discussed this in a docs team meeting. It doesn't seem like there's a place for this in the API docs. Especially since it doesn't really live on a single module or type. It might be useful in TRPL or Rust by Example, but the meeting was missing people who had enough context to make that decision. Vacations and whatnot. So we're waiting on people to get back from their vacations to make a decision on where this kind of material should live.

**Comment by leonardo-m** [comment]
More generally I think it's a good idea to start adding few images and diagrams to the Rust docs. Sometimes images give a quick help or help understanding.

**Comment by Dylan-DPC** [comment]
Closing this as there was no motivation for adding this to the api docs, and it may be better suited elsewhere, but i don't think anyone followed up on that.
