### ISSUE TITLE
Tracking Issue for using std::mem::transmute() in const fn (const_fn_transmute)

### ISSUE THREAD

**Issue by TheDarkula** [rust-lang/rust#53605]
Using `std::mem::transmute()` in constant functions is behind the `const_transmute`/`const_fn_transmute` feature gate.
(In constants, it is stable.)

Blocked on https://github.com/rust-lang/const-eval/issues/14.

**Comment by mjbshaw** [comment]
@TheDarkula I know. I'm just trying to show support for eventually stabilizing this feature (rather than being removed because people are opposed to it).

**Comment by jamesmunns** [comment]
Even with the flag, is this possible? I am getting an error stating that the use of unsafe functions are not allowed in `const fn`:

```rust
pub const unsafe fn rx_buffer_init() -> [BufferDescriptor; BUFFER_CT] {
    transmute::<
        [u8; size_of::<BufferDescriptor>() * BUFFER_CT],
        [BufferDescriptor; BUFFER_CT]
    >([0u8; size_of::<BufferDescriptor>() * BUFFER_CT])
}
```

gives me

```
error: call to unsafe function is unsafe and unsafe operations are not allowed in const fn
  --> foo/src/test.rs:18:5
   |
18 | /     transmute::<
19 | |         [u8; size_of::<BufferDescriptor>() * BUFFER_CT],
20 | |         [BufferDescriptor; BUFFER_CT]
21 | |     >([0u8; size_of::<BufferDescriptor>() * BUFFER_CT])
   | |____________________________________________________________^ call to unsafe function
   |
   = note: consult the function's documentation for information on how to avoid undefined behavior
```

**Comment by mgostIH** [comment]
Is there some blocker on this or could this be starting to get stabilized? I'm mostly looking out for a way to define a function from a `u8` array without any indirection but I have no idea whether this is supposed to be supported or not in the design of const fn.

**Comment by MSxDOS** [comment]
`unsafe` in `const fn` has been [stabilized in 1.33](https://github.com/rust-lang/rust/pull/57067/). Is there anything else left preventing this from being stabilized as well?

**Comment by RalfJung** [comment]
Given that `union` field access is already possible inside `const` (but not inside `const fn`), it seems somewhat silly to block `transmute`. All that does is make code less readable by pushing people to use unions instead of transmutes.

So I propose we stabilize `transmute` in `const`, but not `const fn`. However, currently our handling of intrinsics in const-qualif is [somewhat broken](https://github.com/rust-lang/rust/issues/61495), so that should be fixed first.

**Comment by RalfJung** [comment]
See https://github.com/rust-lang/rust/pull/64011 for stabilizing `transmute` inside `const` but not `const fn`.

**Comment by WaffleLapkin** [comment]
Is there any news about the stabilization?

**Comment by jplatte** [comment]
@WaffleLapkin: @oli-obk reopened #64011 today because it got unblocked, then closed it again because apparently stabilizing `transmute` inside `const` but not `const fn` is no longer feasible.

So I think this is now blocked on union accesses in `const fn` being stabilized (#51909). I don't really understand the path forward for that one based on its comments.

**Comment by RalfJung** [comment]
Should we give this another try? Not much progress has been made on the unconst side of things (also [see here](https://github.com/rust-lang/rust/issues/51909#issuecomment-636751681)), but allowing `transmute` where we already allow union could help get rid of a lot of nasty union-type-punning code (probably half of which is wrong because it forgets to add `repr(C)` to the union).

**Comment by oli-obk** [comment]
I'm creating a new stabilization PR to show the workarounds needed to allow such a split. We can then decide whether we'll take on that technical debt.

**Comment by RalfJung** [comment]
In the const lang-team meeting with @rust-lang/wg-const-eval we did make some plans towards unconst operations, but nothing has happened since then I think. See [the meeting notes](https://hackmd.io/7BPJmbPuTRKLzNZ5cEQ5MQ#what-are-open-questions-about-unsafe-const-fn). The first step would be an RFC specifying what "UB during CTFE" means.

**Comment by Ekleog** [comment]
Is there any summary of what the current status is here to actually get `transmute` to be `const` in `const fn`?

(Coming here because I'd have liked to make `Path::new()` `const`, but AFAIU this requires either pointer deref or transmute to be `const`, and transmute sounds easier to stabilize than pointer deref)

**Comment by RalfJung** [comment]
Raw pointers and transmute are pretty much equal in terms of "what it takes to make them const-stable".

The next step is to figure out what we want to to with UB during CTFE, for which I recently proposed an RFC: https://github.com/rust-lang/rfcs/pull/3016. The key PR needed to implement that RFC is up at https://github.com/rust-lang/rust/pull/78407.

**Comment by programmerjake** [comment]
I think it would be a good idea to split out into a separate feature that can be stabilized transmute of references to types that are `repr(transparent)` wrappers:
```rust
#[repr(transparent)]
pub struct MySlice(pub [u8]);

impl MySlice {
    pub const fn new(v: &[u8]) -> &MySlice {
        unsafe { std::mem::transmute(v) }
    }
}
```

**Comment by RalfJung** [comment]
I think once we find some kind of consensus on https://github.com/rust-lang/rfcs/pull/3016 (which turned out to be much harder than I anticipated), there's not much blocking stabilization here.

**Comment by benesch** [comment]
So, rust-lang/rfcs#3016 was merged. @RalfJung, does that mean we can proceed with stabilization here?

**Comment by benesch** [comment]
It seems to me that the answer is probably yes, since #75196 has a stabilization PR out and was previously blocked on  rust-lang/const-eval#14.

**Comment by RalfJung** [comment]
The stabilization PR is already up. :)
https://github.com/rust-lang/rust/pull/85769
