### ISSUE TITLE
Undefined Symbol Linking ThinLTO on Fuchsia

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#53794]
After https://github.com/rust-lang/rust/pull/53356, all Rust binaries fail to link when using ThinLTO on Fuchsia (at least, all the admittedly non-minimal examples I have tried do). The full error is [here](https://gist.github.com/cramertj/1d77970a88feb5871efce61bb88747fa). TL;DR: `ld.lld: error: undefined symbol: _$LT$$u5b$A$u5d$$u20$as$u20$core..slice..SlicePartialEq$LT$A$GT$$GT$::equal::hcbd9a5cdc751fed8`.

Most binaries mentioned `PartialEq`-related things as the symbol that was failing to link, which is maybe coincidental (due to the order in which function references occur or something) but I figured it was worth mentioning.

The error does not occur before https://github.com/rust-lang/rust/pull/53356, and does not occur even post-https://github.com/rust-lang/rust/pull/53356 when disabling LTO or using fat LTO.

cc @michaelwoerister

**Comment by alexcrichton** [comment]
@cramertj are you able to reduce the test case down to one that we can reproduce? That would make it much easier to track down and confirm a fix.

**Comment by cramertj** [comment]
Scratch that-- I asked around and there's a way to pull down a recent sysroot using some scripts. I'll post here when I've gotten a small repro.

**Comment by cramertj** [comment]
```
curl -L -o cipd "https://chrome-infra-packages.appspot.com/client?platform=linux-amd64&version=latest" && chmod +x cipd && ./cipd install fuchsia/sdk/linux-amd64 latest -root sdk && ./cipd install fuchsia/clang/linux-amd64 --root clang
```
will get you a sysroot, libs dir, and our version of clang, which you can use to compile w/
```
rustc foo.rs --target=x86_64-fuchsia -Clinker=clang/bin/clang -Clink-arg=--target=x86_64-fuchsia -Clink-arg=--sysroot=./sdk/arch/x64/sysroot -Lnative=./sdk/arch/x64/lib
```

I'll work on tracking down a minimal repro using this approach.

**Comment by cramertj** [comment]
Okay, it's not exactly minimal, but I've put together [this repo](https://github.com/cramertj/link-error-repro) containing some scripts and an example project that will reproduce the error. To download the fuchsia SDK, run `.,/clone_sdk.sh`, and to build (and get the error) run `./build.sh`. Let me know if there's anything else I can do help debug this!

**Comment by cramertj** [comment]
Ping @michaelwoerister have you had any luck trying to track this down? If not, is there any possibility we could roll back the original change? This is blocking a number of different issues in Fuchsia. If there's any more information or support I can provide, let me know.

**Comment by cramertj** [comment]
@michaelwoerister Ugh... I've spent several hours trying to track this down. It seems that something has changed now since I originally tested, and I get the same error unless I change `CARGO_TARGET_RUSTFLAGS` to `CARGO_TARGET_x86_64_FUCHSIA_RUSTFLAGS`. I've pushed this change as long as a change to fix the specific versions of clang and the sdk that are being downloaded so as to prevent further breakages. However, once I do that, I not longer get any link errors at all :cry:, so I'm no longer able to reproduce outside of the fuchsia tree (which still reproduces perfectly consistently). I'm still digging for a new reproducer and trying to figure out what changed between the time I originally submitted the example and now.

**Comment by cramertj** [comment]
Encountered https://github.com/rust-lang/rust/issues/54042 when working towards a repro. It may be related.

**Comment by alexcrichton** [comment]
Ok I've done some digging with @cramertj and here's some things we've discovered. I was never able to reproduce the link error seen here exactly but I was able to get pretty close:

https://gist.github.com/alexcrichton/c79ba388aeb2d94e1ac22592e1bd9562

The bug appears to be because [this comment is violated](https://github.com/rust-lang/rust/blob/551244f05b92f90fe327f8f0a6d9a6e674eaab1b/src/librustc_codegen_llvm/lib.rs#L269-L274), namely the same CGU name is used in two different crates for different data. This later causes issues with ThinLTO which is where that requirement stems from.

The reproduction above shows that if you have two crates then the "volatile" CGUs which contain instantiations from upstream crates will end up having the same CGU name as the CGU name for a local crate doesn't consider the local crate's crate name and crate disambiguator, only the upstream one (which is now duplicated between two CGUs).

That brings up a whole bunch of questions of "why don't we see this everywhere?!" which I believe is all answered by: 

* In non-incremental mode we [rename numbered CGUs](https://github.com/rust-lang/rust/blob/551244f05b92f90fe327f8f0a6d9a6e674eaab1b/src/librustc_mir/monomorphize/partitioning.rs#L596-L598) based on the current crate, so non-incremental CGUs never collide in names.
* Within one crate CGU names are always unique, meaning that ThinLTO's required guarantees are still upheld.

So this bug only shows up when we're doing whole-crate-graph ThinLTO (a rarity) *and* some dependencies were compiled incrementally. You can't even express this in Cargo because this invocation is invalid:

```rust
rustc foo.rs -C incremental=out -C lto=thin
```

as rustc prints "error: can't perform LTO when compiling incrementally" (as we haven't implemented it!). All that to say that this all makes sense that it's only Fuchsia's own build system, no one else can even encounter this with Cargo!

@michaelwoerister does that make sense? I think the fix here is to factor in the local crate name and crate disambiguator into "volatile" codegen units, but I'd want to confirm with your before sending a PR.

**Comment by michaelwoerister** [comment]
Oh yes, that makes sense! Always adding the instantiating crate ID to the CGU would indeed be a valid fix for the problem.

**Comment by michaelwoerister** [comment]
@alexcrichton, it sounds like you already have a PR ready? Otherwise, let me know and I'll create one.

**Comment by alexcrichton** [comment]
Oh I don't have a patch yet myself, was gonna confirm first. if you'd like to make the patch though feel free!

**Comment by michaelwoerister** [comment]
Sure, I'll do a PR tomorrow. It's me who introduced the regression after all `:)`

**Comment by cramertj** [comment]
I've confirmed that https://github.com/rust-lang/rust/pull/54152 fixed this. Thanks so much @alexcrichton and @michaelwoerister!

**Comment by michaelwoerister** [comment]
Great to hear! Credit goes to @alexcrichton for identifying the underlying problem. The fix was pretty simple after that `:)`
