### ISSUE TITLE
Add test which attempts to modify static memory at compile-time

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#53818]
No matter what kind of const eval features we add, we should never allow this. Even if we managed to allow this, I think the current impl would ICE. Even if it does not ICE, it could never actually modify the memory. We should ensure that the following code always errors.

```rust
#![feature(const_raw_ptr_deref)]
#![feature(const_let)]

use std::cell::UnsafeCell;

struct Foo(UnsafeCell<u32>);

unsafe impl Send for Foo {}
unsafe impl Sync for Foo {}

static FOO: Foo = Foo(UnsafeCell::new(42));

static BAR: () = unsafe {
    *FOO.0.get() = 5;
};

fn main() {
    println!("{}", unsafe { *FOO.0.get() });
}
```

**Comment by agnxy** [comment]
Hi @oli-obk , I would like to work on this if that's ok. I'm a new Rustacean and I'm learning rustc development and testing. It's time to get my feet wet 😃

**Comment by agnxy** [comment]
Hi @oli-obk ,
When I was running the test in step 3, or compiled the new test with nightly rustc (rust-lang/rust@fc81e3624), I got errors like this.

error[E0015]: calls in statics are limited to constant functions, tuple structs and tuple variants
  --> mod-static-with-const-fn.rs:24:6
   |
24 |     *FOO.0.get() = 5;
   |      ^^^^^^^^^^^

error[E0658]: statements in statics are unstable (see issue #48821)
  --> mod-static-with-const-fn.rs:24:5
   |
24 |     *FOO.0.get() = 5;
   |     ^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(const_let)] to the crate attributes to enable

error: aborting due to 2 previous errors

I think E0015 is the expected error. But I'm not sure about E0658. It seems that the const_let feature is not stabilized yet. (But compiling const_let.rs doesn't return this error.) Could you please help with this problem. Thanks a lot.

**Comment by oli-obk** [comment]
These errors are fine. the idea of this issue is to just make sure the code always fails to compile. More errors are fine, too. the const let feature has a bug where even enabling it will still report it. that's not problematic for this issue. Can you add a comment to the test mentioning that this test should never ever succeed?

If you want you can additionally try to minimize the test to something still emitting the feature  gate error even though the feature gate is active (and maybe to something that should be perfectly fine at compile time). then open a new issue about that.

**Comment by oli-obk** [comment]
you can just make them match ;) Add all the annotations you need to make the test pass. Whenever someone changes your test, because they fixed other bugs or implemented new features, they'll hopefully look at the comment about the fact that the test should never succeed to compile.
