### ISSUE TITLE
Linter suggestion breaks compilation

### ISSUE THREAD

**Issue by omni-viral** [rust-lang/rust#53925]
I define `#![deny(rust_2018_idioms)]` which implies `#![deny(unreachable_pub)]` and I got linter complaining about the `pub use` inside private module while I reexport the symbol at crate level.

[Here is a small example of what I'm talking about](https://play.rust-lang.org/?gist=e23c1eed9bb2a4136c14363061bb9c36&version=nightly&mode=debug&edition=2015)

Looks ok. Let's  do what linter suggests - change `pub` to `pub(crate)` and...
Get compilation error with '`Bar` is private'

[Here is how it looks like](https://play.rust-lang.org/?gist=7d27b544695d34912ea08ca14ec5f0be&version=nightly&mode=debug&edition=2015)

What is the correct way to export `Bar` in example? My guess is that second variant is correct, hence linter is correct as well, and the bug is in visibility system somewhere in `rustc`. But I'm not an expert here.

**Comment by zackmdavis** [comment]
The unreachable-pub lint was removed from the 2018-idioms lint group in #52926 because it suffers from the bugs #47816 (which is the cause of the problem in your first example) and #52665, but this change won't be in stable until 1.29 (13 September). Until we have a release candidate, the nightly toolchain might be a better choice for testing out edition-2018 features.
