### ISSUE TITLE
`cargo build` panics with include_bytes!() of the file itself

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#53956]
This code looks meaningless, but it's still valid code. However it can cause `cargo` to panic.

```rust
// This file is: main.rs
fn main() {
    let mut bytes = vec![];
    bytes.append(&mut include_bytes!("main.rs").to_vec());
    println!("Byte count: {}", bytes.len());
}
```

First build is ok. Then call shell `touch main.rs` and build again, `cargo` will crash with:

```shell
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 1',
/checkout/src/libcore/slice/mod.rs:2079:10
```

Version: `cargo 1.28.0 (96a2c7d16 2018-07-13)`

**Comment by Havvy** [comment]
```
[havvy@rust-nightly:~/scratchspace]$ cargo new --bin include_self
     Created binary (application) `include_self` project

[havvy@rust-nightly:~/scratchspace]$ cd include_self/

[havvy@rust-nightly:~/scratchspace/include_self]$ ls
Cargo.toml  src

[havvy@rust-nightly:~/scratchspace/include_self]$ sublime .

// Replace main.rs with the file in the opening comment.

[havvy@rust-nightly:~/scratchspace/include_self]$ cargo run
   Compiling include_self v0.1.0 (file:///home/havvy/scratchspace/include_self)                                                                                                                                      
    Finished dev [unoptimized + debuginfo] target(s) in 1.50s
     Running `target/debug/include_self`
Byte count: 170

[havvy@rust-nightly:~/scratchspace/include_self]$ cd src

[havvy@rust-nightly:~/scratchspace/include_self/src]$ touch main.rs

[havvy@rust-nightly:~/scratchspace/include_self/src]$ cargo run
   Compiling include_self v0.1.0 (file:///home/havvy/scratchspace/include_self)                                                                                                                                      
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 2', /checkout/src/libcore/slice/mod.rs:2046:10
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (9395f0af7 2018-09-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `include_self`.

To learn more, run the command again with --verbose.
```

**Comment by mcr431** [comment]
So I've been debugging this quite a bit and have boiled it down to the (semi) root cause but don't really know how continue with it and I'd love some guidance or at least to follow closely with whoever takes the reigns. 

This actually has has to do generally with checking contents of any source file being used and how files are cached. It is also reproducible as follows:

file `src/main.rs`
```
mod external;

fn main() {
    external::hello();
    let mut bytes = vec![];
    bytes.append(&mut include_bytes!("external.rs").to_vec());
    println!("Byte count: {}", bytes.len());
}
```

file `src/external.rs`
```
pub fn hello() {
    println!("hello");
}
```

`cargo build` once and its all good,  `touch src/main.rs` and `cargo build` again and error happens.

Basically whats happening is that the source code for the files is getting put into the SourceMap then the `include_bytes!` macro expansion also makes an entry for the given file but with NO source content:

src/libsyntax/ext/source_util.rs, line 187  -- `pub fn expand_include_bytes`
```
// Add this input file to the code map to make it available as
// dependency information, but don't enter it's contents
cx.source_map().new_source_file(file.into(), String::new());
```

Then when it finds the file in the source map on subsequent compilations, expecting to find source code in it, it finds an empty file with no source, no lines, etc and panics.

I'm pretty new to working on the compiler and don't have a strong grasp on the query system or where a fix would fit into this. Not sure if its something where the `expand_include_bytes` function should check if the file is already in the source map and if so, use the contents of whatever is already there, or if it should be a change made elsewhere in the code. Any guidance, suggestions would be greatly appreciated.

**Comment by eddyb** [comment]
cc @michaelwoerister @nikomatsakis
