### ISSUE TITLE
static-pie for musl target (remove crt1.o)

### ISSUE THREAD

**Issue by aep** [rust-lang/rust#53968]
rustc explicitly adds crt1 before passing to the linker, which breaks musl-cross.
for static-pie we need to use rcrt1 instead.

Also i think crt1.o is actually wrong, since that target is supposed to support both dyn and static.

https://github.com/rust-lang/rust/blob/b7c6e8f1805cd8a4b0a1c1f22f17a89e9e2cea23/src/librustc_target/spec/linux_musl_base.rs#L59

any chance we can at least have a rustc arg that removes the crt? (like -nostartfiles essentially)

or a blank target that lets the user configure the rest of the target via commandline.

**Comment by mixi** [comment]
In case anyone wants to work at this: Something like this (introducing a flag to make rustc trust the linker to includes the right start files) was discussed and a (at the time working) patch for it proposed at #50105, but was scrapped (the version that eventually landed didn't include that flag anymore) because there was an easier way to fix my issue and there were concerns over adding another target feature for this.
