### ISSUE TITLE
Weird Behaviour (Leak in Unclosed Thread)

### ISSUE THREAD

**Issue by omrerdn** [rust-lang/rust#53974]
Hello i am new in Rust and i have the following code : 

```
use std::sync::mpsc::channel;
use std::thread;
use std::time::Duration;

fn main() {
    let (sender, receiver) = channel::<i32>();

    //let _ = sender.clone();

    let _ = thread::spawn(move || loop {
        for i in 1..1_000_000 {
            sender.send(i).unwrap();
        }

        thread::sleep(Duration::new(5, 0));
    });

    let t2 = thread::spawn(move || loop {
        match receiver.recv() {
            Ok(i) => println!("{}", i),
            Err(e) => println!("{:?}", e),
        }
    });

    if t2.join().is_err() {
        println!("Closed ...");
    }
`}`
```
Simple program, as you can see we have 2 different threads , first one sends i32 values to receiver which lives in second thread. So far everything works as expected first one sends then second one writes received values to the console. I executed this program in mac os(10.12.2) and windows 10 with checking the used memory by processes. I'll add results only from mac(almost work same with windows)

**Here is the result from with code (47mb):** 
![image](https://user-images.githubusercontent.com/19870706/45115084-88313f00-b157-11e8-9734-62395cc801c7.png)

And the weird behaviour happens when you uncomment this line 
`    //let _ = sender.clone();`

**Here is the new results (~1.4mb):** 
![image](https://user-images.githubusercontent.com/19870706/45115193-d3e3e880-b157-11e8-8ad8-d86acc7be6a6.png)

Actually i want to know if i did something wrong because sender and receiver are both live until the program ends. On the other hand the received values should get dropped in "t2" but it doesn't.(note : memory gets freed if i terminate "t2" but currently i don't want to do that)
And the interesting part is whether if i use it or not, just cloning sender helped freeing the received values from memory.

And one more weird behaviour that i want to note , if you try to execute the leaked program you'll see that it will stick on **47mb**(values can be different), it will not get decreased or increased(in mac os). if i change the for loop's upper limit to **10_000_000**, used memory size will always get increased, it never stops.

used **stable toolchain, rustc 1.28.0**

**Comment by abonander** [comment]
There's no leak here, you're just changing whether or not the receiver thread can keep up with the sender. The asymptotic memory growth you see in some cases arises purely from the receiver being significantly slower, and thus the sender filling up the queue.

The receiver is going to be the significantly slower half because of those `println!()`s, which involves both formatting and repeatedly locking/unlocking the stdout handle. If you comment those out, then on my machine the memory usage for the process never even breaks 1 MB regardless of whether or not you clone the handle or stop the loop at 1 million vs 10 million.

Cloning the sender handle changes the behavior of the queue. It goes from being a single-producer/single-consumer (SPSC) queue with a relatively simple synchronization scheme to a multi-producer/single-consumer (MPSC) queue which not only has to synchronize between the producer and the consumer but between multiple producers as well (even if there is only one actual producer, there are multiple handles on different threads so it can't safely use the SPSC implementation). 

The synchronization on the sender end slows down the sender and allows the receiver to keep up easier, preventing the queue from growing too large. Conversely, extending the sender's loop to 10 million allows it to push 10 times more values before it sleeps; this gives it much more time to outpace the receiver.

**Comment by omrerdn** [comment]
@abonander thanks for your response, but i still have few questions. 

> The receiver is going to be the significantly slower half because of those println!()s, which involves both formatting and repeatedly locking/unlocking the stdout handle. If you comment those out, then on my machine the memory usage for the process never even breaks 1 MB regardless of whether or not you clone the handle or stop the loop at 1 million vs 10 million.

Check this code please, due to asymptotic memory growth(for 10million) i increased backpressure by increasing sleep time to 20 seconds and also i didn't use  println!. ( btw with println scenario, it prints 10 million line in 9 seconds on my mac), so i expect that receiver has sufficient time for handling whole queue(freeing the memory), here is the code i tried :
```
let _ = thread::spawn(move || loop {
        for i in 1..10_000_000 {
            sender.send(i).unwrap();
        }

        thread::sleep(Duration::new(20, 0));
    });

    let t2 = thread::spawn(move || loop {
        let _ =  receiver.recv();
    });

    if t2.join().is_err() {
        println!("finished !");
    }
```
After executing this code it started with 16mb and it increased over the time , 16 -> 25 -> 27 -> 31 -> 36 ...  and this is behaviour is not changing if i increase sleeping to 30 seconds or more, so can we still tell this one is an asymptotic memory growth ? 

> Cloning the sender handle changes the behaviour of the queue. It goes from being a single-producer/single-consumer (SPSC) queue with a relatively simple synchronisation scheme to a multi-producer/single-consumer (MPSC) queue which not only has to synchronise between the producer and the consumer but between multiple producers as well 

If i use the simple synchronisation scheme(SPSC)  i use much more memory and it gets increased over the time ? On the other hand if i clone sender (converting scheme to MPSC) i use significantly less memory comparing to SPSC and it's memory doesn't get increased over the time ?
The weird thing about this if i use less complex material it needs to use lesser resource why would i use SPSC then ? I could just clone sender and let it live in some scope and not use it. 

_Note : I am hoping my words are not looking offensive , If it's looking like that i am sorry, its probably because of my english, i am just trying to understand that is this a different concept or some bug, thanks._

**Comment by abonander** [comment]
Because this is concurrent code it's highly dependent on the machine. Starting the receiver thread second could give the sender enough of a head start to still outpace it. One thread or another can be preempted randomly by the operating system. They may not be even running simultaneously. I just don't think it's a leak.

The important part with switching to MPSC is that it slows down the sender (producer) by making it do more work to push values. This makes it harder for it to outpace the receiver.

**Comment by jonas-schievink** [comment]
Closing as there doesn't seem to be a bug here. For further questions about this, consider using https://users.rust-lang.org/ as you're more likely to get responses there.
