### ISSUE TITLE
unstable `alloc` crate can be used without feature gates on the 2018 edition

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#54006]
### STR

This compiles when `edition = "2018"`

``` rust
// crate-type: lib
#![no_std]

use alloc::vec;

fn foo() {
    let mut xs = vec![];
    xs.push(0);
}
```

This doesn't compile when `edition = "2015"` because it needs a feature gate.

``` rust
// crate-type: lib
#![no_std]

extern crate alloc; //~ ERROR use of unstable library feature `alloc`

use alloc::vec;

fn foo() {
    let mut xs = vec![];
    xs.push(0);
}
```

### Meta

```console
$ rustc -V
rustc 1.30.0-nightly (6e0f1cc15 2018-09-05)
```

**Comment by Centril** [comment]
Marking as P-high due to edition urgency.

**Comment by alexcrichton** [comment]
This sounds the same as https://github.com/rust-lang/rust/issues/52489, curious! cc @eddyb

**Comment by eddyb** [comment]
@alexcrichton Uhhhh this is because we can't stability-check intermediary path components.
`alloc::vec` *is stable*, it's just `alloc` that's not - this is the same as `std::intrinsics::transmute`.

cc @petrochenkov This seems much worse than usual.

OTOH, I do have a branch where you *have to* use `extern crate alloc;` or pass `--extern alloc` to the compiler, that I'm working on right now. Would that alleviate the issue for now?

**Comment by alexcrichton** [comment]
Ah yes, indeed!

The "intermediary path components stability doesn't work" has never been high priority *because* the root crate always had to be listed as `extern crate foo`. I would agree that if you don't have to write `extern crate foo` this is definitely much higher priority now

**Comment by nikomatsakis** [comment]
Can't we check the stability when we do the lazy path resolution?

**Comment by nikomatsakis** [comment]
Sorry, that's not very clear. What I meant is:

Can we do the stability checking when we first load the crate?

**Comment by pnkfelix** [comment]
Visited for triage. Assigning to @eddyb, who sounds like they are on the case.

**Comment by nikomatsakis** [comment]
Another question:

Can you specify `--extern` to access `alloc` without a feature gate?

**Comment by nikomatsakis** [comment]
(If you invoke rustc manually, or maybe by cajoling cargo sufficiently)

**Comment by eddyb** [comment]
@nikomatsakis The only way you can access the sysroot crate *without* knowing its path is the new `--extern alloc` (without a path), that's being added in #54116, which is unstable.

We can't check stability when we load the crate, because that happens before the query engine is set up, and it's a pretty messy right now to get any useful information across.

What we could do is try to get a stability check into #54145.
