### ISSUE TITLE
#![deny(warnings)] affects doc warnings

### ISSUE THREAD

**Issue by kpp** [rust-lang/rust#54316]
On `rustc 1.30.0-nightly (e4ba1d41e 2018-09-15)` `#![deny(warnings)]` affects doc warnings, which makes it impossible to build docs. It may take huge time for a crate to fix these warnings. See https://github.com/tokio-rs/tokio/issues/437

Possible solution: distinguish warnings in code and warnings in docs by providing `#![deny(doc_warnings)]`

**Comment by matthewjasper** [comment]
Does this help?
https://doc.rust-lang.org/rustdoc/the-doc-attribute.html#testattr

**Comment by kpp** [comment]
None of these helped:

```
#![deny(missing_docs, missing_debug_implementations, warnings)]
#![doc(allow(warnings))]
```

```
#![deny(missing_docs, missing_debug_implementations, warnings)]
#![doc(test(attr(allow(warnings))))]
```

```
#![deny(missing_docs, missing_debug_implementations, warnings)]
#![doc(attr(allow(warnings)))]
```

I want to make warnings be warnings again when I call `cargo doc`.

**Comment by QuietMisdreavus** [comment]
`#![doc(test(attr(...)))]` only affects doctests, not the crate. There is no real mechanism for the issue as requested right now.

If you're using `#[doc(cfg(...))]` then `#[cfg(rustdoc)]` will be available, and you can use `#![cfg_attr(rustdoc, deny(warnings))]`. However, that requires a nightly feature right now, and may not be applicable to everyone.

My suggestion for affected crates is to set `#![warn(intra_doc_link_resolution_failure)]`, which is always the lint at fault in situations like this. This lint is only emitted by rustdoc, so it won't affect regular compilation.

The other thing i noticed in your linked issue is that it's affecting *dependencies* when running `cargo doc`. Cargo is supposed to set `--cap-lints allow` when documenting dependencies now; is this issue still happening when you're documenting downstream crates?

I would be open to creating a new lint group for rustdoc-specific lints; since we're planning on adding more over time, that would be a good way to handle them in a blanket fashion. cc @GuillaumeGomez

**Comment by kpp** [comment]
`#![allow(intra_doc_link_resolution_failure)]` worked for me!

**Comment by GuillaumeGomez** [comment]
@QuietMisdreavus there is one, kind of. Nothing official yet though. :)

**Comment by QuietMisdreavus** [comment]
I've opened https://github.com/rust-lang/rust/pull/56689 to add a new lint group for lints emitted by rustdoc.

**Comment by jyn514** [comment]
This was fixed by https://github.com/rust-lang/rust/pull/56689; you can now use `#[allow(rustdoc)]` or `#[allow(rustdoc::all)]` to ignore rustdoc warnings (the attributes do the same thing, but the second only works on 1.52 and later).
