### ISSUE TITLE
`alloc` not added to extern prelude

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/rust#54392]
After https://github.com/rust-lang/rust/issues/50605, `core` and/or `std` are added to the extern prelude when the feature `extern_prelude` is enabled.

It seems to me that if, additionally, the feature `alloc` is enabled, `alloc` should be added to the prelude too.

# Meta
`rustc 1.30.0-nightly (20dc0c507 2018-09-19)`

**Comment by cramertj** [comment]
This was discussed on another thread (trying to track it down, but a quick look didn't turn it up) and the plan was to allow adding `alloc` to the extern list by providing a flag in Cargo.toml that made cargo pass a `--extern alloc` (with no value for `x` in `--extern alloc=<x>`). This would cause the named crates to be included in the extern prelude (if found in the link path).

**Comment by Nemo157** [comment]
I believe the change @cramertj mentions is slated to be a post-2018 feature (since there are still design considerations for the cargo side of it). Until then use of `extern crate {alloc,test,proc_macro};` are all still needed (only the last is possible on stable, the first two are unstable crates).

**Comment by petrochenkov** [comment]
`alloc` still requires using `extern crate alloc` as now documented in https://rust-lang-nursery.github.io/edition-guide/rust-2018/module-system/path-clarity.html
