### ISSUE TITLE
[1.30 beta] test attribute on methods cause errors

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#54465]
**This regression will probably be marked as "won't fix". This issue notifies crate authors.**

The following snippet causes an error in 1.30 beta, while compiling on 1.29 stable.

```
#[allow(unused_attributes)]
#[test]
pub fn get_vertices_test(&self) -> &Vec<Option<Vertex<TInformation>>> {
    &self.vertices
}
```

* [graphify](https://crates.io/crates/graphify) `0.1.0` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/graphify-0.1.0/log.txt)) cc @tyleo

cc @djrenren

**Comment by djrenren** [comment]
Ah yeah that's a result of these lines: https://github.com/rust-lang/rust/blob/4591a245c7eec9f70d668982b1383cd2a6854af5/src/libsyntax_ext/test.rs#L54-L57

Personally, I think this should have always been an error. Most of the time it's just people using `#[test]` instead of `#[cfg(test)]`. But in the interest of compatibility we could remove the error message there and instead act as a noop if `unused_attributes` are allowed.

**Comment by pnkfelix** [comment]
visited at T-compiler meeting. Team believes this was an expected outcome, and are closing this as WONTFIX.
