### ISSUE TITLE
mcount support??

### ISSUE THREAD

**Issue by taeguk** [rust-lang/rust#54500]
Is there mcount support in `rustc`??
Many profiling tools such as `gprof` and `uftrace` require mcount function. An user can use `-pg` option to add a mcount function call at the entry of each function in `gcc` or `clang` compiler.
Is there similar way to get same effect of using `-pg` option?

If there is no way to add the mcount function call, I want to suggest adding mcount support for utilizing existing profiling tools.

**Comment by steveklabnik** [comment]
Please ask questions on https://users.rust-lang.org/, we try to keep the issue tracker for bugs only. Thanks!

**Comment by sanxiyn** [comment]
This was a legitimate issue that shouldn't have been closed. mcount support got added in #57220.

@taeguk For better reception in the future, instead of "mcount support??", confidently write, "Support mcount". This was a feature that should be supported which rustc lacked. No need to be shy about that.

**Comment by taeguk** [comment]
@sanxiyn Okay, I got it. thanks :)
