### ISSUE TITLE
1.30 beta.7 const-related tests fails on multiple architectures

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#54546]
| arch | const-eval/double_check{,2} | const-size_of-cycle | invalid_const_promotion |
|---|---|---|---|
| [armv7-hf](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=armhf&ver=1.30.0%7Ebeta.7%2Bdfsg1-1%7Eexp1&stamp=1537795400&raw=0) | ok |  failed | ok
| [aarch64](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=arm64&ver=1.30.0%7Ebeta.7%2Bdfsg1-1%7Eexp1&stamp=1537799004&raw=0) | ok | failed | failed |
| [ppc64](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=ppc64&ver=1.30.0%7Ebeta.7%2Bdfsg1-1%7Eexp1&stamp=1537793616&raw=0) | failed | failed | failed |
| [s390x](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=s390x&ver=1.30.0%7Ebeta.7%2Bdfsg1-1%7Eexp1&stamp=1537797168&raw=0) | failed | failed | ok |

**Comment by karcherm** [comment]
`const-eval/double_check` (and its sibling) fail on all Big-Endian architectures, because the Enums are not represented in `usize`, so casting a pointer to the usize-constant 5 or 42 does not yield a pointer to a (probably u8-sized) Enum with the value 5 or 42, but the value 0 instead, as Big-Endian architectures have the more significant bytes containing `0x00` *before* the interesting byte containing 5 or 42.

**Comment by karcherm** [comment]
This has already been fixed in HEAD by 283f2be1421eca11b1a3abbaac40ca946e806037.

**Comment by oli-obk** [comment]
ah, this only fixes the enum test. So `const-size_of-cyle` and `invalid_const_promotion` still need fixing
