### ISSUE TITLE
NLL doesn't check user type annotations are well-formed

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/rust#54620]
For example, this code is accepted with NLL enabled:

https://github.com/rust-lang/rust/blob/f1694eac74216da22b395a5589b8d080ccd5a2ec/src/test/ui/regions/regions-free-region-ordering-caller.rs#L19-L30

cc #47184

**Comment by nikomatsakis** [comment]
(Related: https://github.com/rust-lang/rust/issues/54105)

I imagine that the way to fix this is that we have to prove a `WellFormed` predicate with-respect-to the user-given type annotations:

https://github.com/rust-lang/rust/blob/1c5e9c68ea6c76fe400528de17ebe03e338bac68/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L1284-L1288

Probably the place to do this is on the `relate_type_and_user_type` function:

https://github.com/rust-lang/rust/blob/1c5e9c68ea6c76fe400528de17ebe03e338bac68/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L946-L953

One complication, though, is that the user-given type is a "canonical type":

https://github.com/rust-lang/rust/blob/1c5e9c68ea6c76fe400528de17ebe03e338bac68/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L950

which means that it might have `_` and things encoded in it. However, the [`relate_type_and_user_type` fn](https://github.com/rust-lang/rust/blob/1c5e9c68ea6c76fe400528de17ebe03e338bac68/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L954) already creates type variables representing each of those `_` and things. Right now it just stores them into a vector:

https://github.com/rust-lang/rust/blob/1c5e9c68ea6c76fe400528de17ebe03e338bac68/src/librustc_mir/borrow_check/nll/type_check/relate_tys.rs#L128-L139

I guess what we would need to do is -- after equating, relating, whatever -- to instantiate the canonical type with these final values (presumably using [the `substitute` function](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/infer/canonical/struct.Canonical.html#method.substitute)), and then create the `WellFormed` predicate.

**Comment by blitzerr** [comment]
The issue is that this code compiles and executes file with NLL enabled as you can see [here](https://play.rust-lang.org/?gist=5e26dbc233aa7797a5bd9edee28bcb37&version=nightly&mode=debug&edition=2015). But with NLL turned off, it errors out as [here](https://play.rust-lang.org/?gist=97d0126b499e10b95ff166bda027393d&version=nightly&mode=debug&edition=2015).
[This](https://rust-lang.github.io/rfcs/1214-projections-lifetimes-and-wf.html#well-formed-types) RFC (unrelated) but helps defined what wellFormed types are.
