### ISSUE TITLE
SliceIndex not implemented for usize for string slices

### ISSUE THREAD

**Issue by StevenDoesStuffs** [rust-lang/rust#54629]
It looks like SliceIndex is implemented for usize for [T] but not &str. Is there a reason why this is? If not, should I submit a PR?

**Comment by Thiez** [comment]
This is intentional. What return type would you expect? You can get bytes with `s.as_bytes()[n]`, but `s[n]` could not (reasonably) return a `char`, because strings are UTF-8 encoded and as such characters have different lengths, to find the 1000th character the implementation would essentially have to do `s.chars().skip(n - 1).next().unwrap()`, so indexing a string would be linear in the length of the string.

**Comment by nagisa** [comment]
Yes, this is intentional. Closing.

**Comment by StevenDoesStuffs** [comment]
Since SliceIndex is implemented for ranges for str, I expected it to return the same thing as .get(n..n+1). Would that be wrong (cause unexpected behavior or something)?
