### ISSUE TITLE
NLL doesn't respect user types in closure signatures

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/rust#54692]
For example, the following code compiles

```rust
#![feature(nll)]
fn foo<'a>() {
    |x: &'a i32| -> &'static i32 {
        return &x;
    };
}
```
cc #47184

**Comment by nikomatsakis** [comment]
Tagging as RC2

**Comment by nikomatsakis** [comment]
So, the closure region requirements are as follows:

```bash
> rustc ~/tmp/issue-54692.rs   -Zverbose
note: External requirements
 --> /home/nmatsakis/tmp/issue-54692.rs:6:5
  |
6 | /     |x: &'a i32| -> &'static i32 {
7 | |         return &x;
8 | |     };
  | |_____^
  |
  = note: defining type: DefId(0/1:10 ~ issue_54692[317d]::foo[0]::{{closure}}[0]) with closure substs [
              i8,
              extern "rust-call" fn((&'_#1r i32,)) -> &'_#2r i32
          ]
  = note: late-bound region is '_#3r
  = note: number of external vids: 4
  = note: where '_#1r: '_#2r
```

**Comment by nikomatsakis** [comment]
You can see the `'_#1r: '_#2r` indicating that — indeed — the argument must outlive the return type. But we have lost the connection to `'a` and `'static`, indeed.

**Comment by nikomatsakis** [comment]
The user-given signature of the closure is computed here, during the HIR typeck:

https://github.com/rust-lang/rust/blob/1c5e9c68ea6c76fe400528de17ebe03e338bac68/src/librustc_typeck/check/closure.rs#L529-L533

(In general, reconciling the expected signature and the user-given signature is a royal pain, as is described in detail in that file.)

I imagine what we have to do is probably to record the "supplied closure signature" somewhere, [probably in a new table similar to `user_substs`](https://github.com/rust-lang/rust/blob/1c5e9c68ea6c76fe400528de17ebe03e338bac68/src/librustc_typeck/check/closure.rs#L529-L533). 

The question is where it should be accessed from. I think it should probably be the closure's job to enforce these relations (if you read that code above, you might see why: in general, the user's signatures are written from the "POV" of the closure body, rather than its creator).

This implies that MIR may want to grow a `user_fn_sig` field, set to `None` for everything but closures. The type-checker can then unify those signatures with the types of the arguments.

**Comment by nikomatsakis** [comment]
Hmm this may be blocking me in other areas.

**Comment by pnkfelix** [comment]
adding self to the assignee list to try to ensure this gets addressed soon

**Comment by pnkfelix** [comment]
Got a report from @mikhail-m1 that they are actively working on this

Unassigning @spastorino (since @mikhail-m1 is taking lead here)
