### ISSUE TITLE
rustdoc: put contenthash in output filenames

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#54786]
We should use some kind of unique identifier for the script/style assets we use in rustdoc. This is commonly known in webpack as "chunkhash" or "contenthash".

Reference link: https://developers.google.com/web/fundamentals/performance/webpack/use-long-term-caching

**Comment by jyn514** [comment]
Is this still necessary? If the styles are served from a website (like docs.rs), it can add its own caching. If you're looking at local documentation, caching doesn't really matter because everything is loaded from disk.

FWIW, rustdoc does allow distinguishing these with `--resource-suffix` as long as you pass it explicitly, that's how docs.rs does it: https://github.com/rust-lang/docs.rs/blob/bcc1a2c9f63a62907abbe68dcbe3f73632a9a4de/src/docbuilder/rustwide_builder.rs#L527-L530

**Comment by ishitatsuyuki** [comment]
You're right, `--resource-suffix` can solve the issue most of the time. I'm closing the issue since it's getting old.
