### ISSUE TITLE
Tracking issue for std::sync::Once::is_completed

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#54890]
Implemented in #53027

> I propose to expose a way to check if a `Once` instance is initialized. 
>
> I need it in `once_cell`. `OnceCell` is effetively a pair of `(Once, UnsafeCell<Option<T>>)`, which can set the `T` only once. Because I can't check if `Once` is initialized, I am forced to add an indirection and check the value of ptr instead:
> 
> https://github.com/matklad/once_cell/blob/8127a81976c3f2f4c0860562c3f14647ebc025c0/src/lib.rs#L423-L429
> 
> https://github.com/matklad/once_cell/blob/8127a81976c3f2f4c0860562c3f14647ebc025c0/src/lib.rs#L457-L461
> 
> The `parking_lot`'s version of `Once` exposes the state as an enum: https://docs.rs/parking_lot/0.6.3/parking_lot/struct.Once.html#method.state.
> 
> I suggest, for now, just to add a simple `bool` function: this fits my use-case perfectly, exposes less implementation details, and is forward-compatible with more fine-grained state checking.

**Comment by nagisa** [comment]
The documentation needs to be made slightly more strict.

For example:

>  It is also possible that immediately after `is_completed` returns false, some other thread finishes executing `call_once`. 

Should be replaced with

>  This function returning `false` does not mean that `Once` has not been executed.

The distinction is important, because at the exact moment this function returns `Once` might already be executed/resolved, without it necessarily happening “immediately after”.

---

To avoid people shotgunning their feet off, I would suggest to add some guidance on how this should be used. For example, doing something *useful* based on this function returning a `false` is somewhat likely to be a bug. And yet, examples do not really result in such an impression.

**Comment by SimonSapin** [comment]
CC @matklad for nagisa’s comment above.

**Comment by mjbshaw** [comment]
It's been 9 months since this was implemented. Can this be stabilized now?

**Comment by pyrrho** [comment]
Is there anything preventing this method from being stabilized? It looks like there was some bikesheding in #53027 but it's now been just past a year since initial adoption.

**Comment by matklad** [comment]
Note that I am personally no longer directly interested in having this method: in `once_cell`, I ended-up copy-pasting the whole of `Once` anyway. That said, this does look like straightforward addition, which allows to do more with the thing, without actually expanding it's surface area greatly.
