### ISSUE TITLE
[E0668] Malformed inline assembly when building rustc

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#54918]
When running `./x.py build --stage 1`, I now get the error:
```
error[E0668]: malformed inline assembly=======>                        ] 16/27: compiler_builtins                                                                                                           
  --> rustc/compiler_builtins_shim/../../libcompiler_builtins/src/probestack.rs:55:5
   |
55 | /     asm!("
56 | |         mov    %rax,%r11        // duplicate %rax as we're clobbering %r11
57 | |
58 | |         // Main loop, taken in one page increments. We're decrementing rsp by
...  |
92 | |         ret
93 | |     " ::: "memory" : "volatile");
   | |_________________________________^

error: aborting due to previous error
```
I'm on macOS 10.12.6. This error was added recently (https://github.com/rust-lang/rust/pull/54568), but it suggests there's been a problem for longer.

**Comment by varkor** [comment]
And here:
```
error[E0668]: malformed inline assembly============================>   ] 26/27: std                                                                                                                         
  --> ~/GitHub/rust/src/libcore/../stdsimd/coresimd/x86/cpuid.rs:64:9
   |
64 | /         asm!("cpuid\n"
65 | |              : "={eax}"(r.eax), "={ebx}"(r.ebx), "={ecx}"(r.ecx), "={edx}"(r.edx)
66 | |              : "{eax}"(leaf), "{ecx}"(sub_leaf)
67 | |              : "rbx" :);
   | |________________________^

error[E0668]: malformed inline assembly
  --> ~/GitHub/rust/src/libcore/../stdsimd/coresimd/x86/xsave.rs:91:5
   |
91 |     asm!("xgetbv" : "={eax}"(eax), "={edx}"(edx) : "{ecx}"(xcr_no));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors
```

**Comment by dsciarra** [comment]
OK on macOS 10.14

**Comment by levex** [comment]
Hmm, I added that error code, and I find that pretty odd. Sadly, I am unable to reproduce this on Linux and I don’t have access to a macOS machine right now.

The error code is emitted if we pass the inline assembly (with its constraints) to LLVM and for some reason it rejects it. (that is, the function `InlineAsm::Verify` returns `false` in `src/llvm/lib/IR/InlineAsm.cpp`. If you have access to the rust source code (which you do since you are trying to get it to compile :p ), it would be appreciated if added a few printfs around the `return false;` statements in the above mentioned file. That way, we could pinpoint why LLVM rejected these seemingly valid inline assembly statements.

Thanks!

**Comment by varkor** [comment]
Okay, this is strange. `InlineAsm::Verify` is returning *`true`* and yet the malformed assembly message is still being output.
