### ISSUE TITLE
Better error message using byte string where only regular strings are allowed in attributes

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#54926]
The error message shows the code that matters.

```
error: literal in `cfg` predicate value must be a string
 --> src/lib.rs:L:11
  |
L | #[cfg(X = b"a")]
  |    
```

It should probably suggest removing the `b`. Likewise if using single quotes, it should suggest using double quotes. Both should also be machine applicable. Raw strings are allowed, so nothing needs to be done with them.

**Comment by Havvy** [comment]
It might also be valid to give this an error code and explain it all there.

**Comment by zackmdavis** [comment]
Petrochenkov's technical-debt concern (which I agree with) [also came up in #54683](https://github.com/rust-lang/rust/pull/54683#pullrequestreview-160662636). ~~I think the _non_-filling-the-compiler-with-garbage place to do this would have to be during parsing: perhaps [`parse_unsuffixed_lit`](https://github.com/rust-lang/rust/blob/e1643a8968753226dab7ab3c9fee826f097550f2/src/libsyntax/parse/attr.rs#L216) could be generalized to take arguments specifying which literals are allowed (keeping `parse_unsuffixed_lit` as a less-general version that calls the generalized method)?~~ (Struckthrough thought doesn't actually work because different attributes want to allow different kinds of literals and the parser doesn't and shouldn't know about the semantics of different attributes.)

**Comment by estebank** [comment]
Self quoting from #54929:

> I feel that we can move a lot of these ad-hoc diagnostics further up in the parser by having a more complex version of `Parser::eat(&mut self, TokenKind)` that also takes some textual info for diagnostics, and also checks for "confusables"—not only single tokens that look alike, like ; and :, but also cases like this one (b""/"").
