### ISSUE TITLE
Panicking in const context results in peculiar compiler error message

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#54947]
Take this program:
```rust
const fn foo() -> i32 {
    [1,2,3][42]  // error here
}

static BAR: i32 = foo();

fn main() {
    println!("{}", BAR)
}
```

On nightly it produces this error output:
```
error: index out of bounds: the len is 3 but the index is 42
 --> src/main.rs:2:5
  |
2 |     [1,2,3][42]
  |     ^^^^^^^^^^^
  |
  = note: #[deny(const_err)] on by default

error[E0080]: could not evaluate static initializer
 --> src/main.rs:2:5
  |
2 |     [1,2,3][42]
  |     ^^^^^^^^^^^ index out of bounds: the len is 3 but the index is 42
...
5 | static BAR: i32 = foo();
  |                   ----- inside call to `foo`

error: aborting due to 2 previous errors
```

To some degree the redundancy is understandable, since the first error is in the const fn definition itself while the second is at the use site (and has the additional useful context); perhaps this could be improved somehow. But more noteworthy is the line in the first error message: `note: #[deny(const_err)] on by default`. Sure enough, `#![allow(const_err)]` silences this error. I suspect this is some sort of oversight, because why would we ever want to allow such an error to be silenced? Is this intentional?

**Comment by oli-obk** [comment]
>  I suspect this is some sort of oversight, because why would we ever want to allow such an error to be silenced? Is this intentional?

We allow this because the user might write this code in runtime code, and we had an [RFC about this](https://github.com/rust-lang/rfcs/blob/master/text/1229-compile-time-asserts.md) that resulted in stating that any code statically known to panic at runtime should just emit a lint and not an error

**Comment by oli-obk** [comment]
> To some degree the redundancy is understandable, since the first error is in the const fn definition itself while the second is at the use site (and has the additional useful context); perhaps this could be improved somehow.

I don't see how we could improve this. The const function and the static are checked independently. Even a non-const fn would emit that error (but it won't twice, because it can't be used in a static)

**Comment by oli-obk** [comment]
@bstrie do you see any way to keep this issue actionable? Otherwise I'm going to close it

**Comment by bstrie** [comment]
@oli-obk I hadn't seen that RFC before, but it seems like this would fall under one of the unresolved questions of the RFC: "In the future the body of const fn might also be interpreted as a constant evaluation context [(places where an expression needs to be constant)]." I can't find any discussion as to why we wouldn't want to treat the body of a const fn in such a way. I appreciate the backwards-compatibility rationale of the RFC and agree with it, but I don't see how it applies here; this issue is predicated on the assumption that the body of a const fn must be const, and that there would be no value in having it be otherwise. Does there exist an example of code that can be written in the body of a const fn that would present the sort of backcompat hazard the RFC intends to guard against? Doesn't the fact that non-const features are necessarily forbidden in const fn bodies naturally prevent any such breakage?

**Comment by oli-obk** [comment]
Interesting point. It's still not easy since just being const doesn't mean we detect that. we might accidentally assume that something depends on function arguments, and later improve the analysis  

@Centril we need to act fast for const fn if we want to make this a hard error in const fn

**Comment by Centril** [comment]
cc @rust-lang/lang @RalfJung 

@oli-obk @bstrie what would "acting fast" entail here?

**Comment by oli-obk** [comment]
Making a decision. The implementation is trivial, it's just adding a condition in the form of `if is_const_fn { error } else { lint }` where currently there's just `lint`

this change needs to be done in the following places:

* https://github.com/rust-lang/rust/blob/c40e2ac2b61e7302de37f54574df987053c15cb2/src/librustc_mir/transform/const_prop.rs#L660
* https://github.com/rust-lang/rust/blob/master/src/librustc_mir/transform/const_prop.rs#L242
* https://github.com/rust-lang/rust/blob/master/src/librustc_mir/transform/const_prop.rs#L449

The big issue is that the const propagator is much weaker than the const evaluator. So there might be things that can theoretically be statically detected in const fn bodies but we can't detect them right now, but during evaluation we'll hit them. We might be able to statically detect these situations in the future, thus causing const fn bodies to break. This was the reasoning behind https://github.com/rust-lang/rfcs/blob/master/text/1229-compile-time-asserts.md making all such diagnostics deny-by-default lints, so we don't break anybody's code but still can improve the analyses to detect more cases.

I don't think the situation is different for const fn.

One example would be 

```rust
const fn foo(i: usize) -> i32 {
    [0, 1, 2][(i % 10) + 3]
}
```

which is obviously out of bounds for any `i` (the modulo is so that there's no question about release mode overflowing the usize into a legal index)

We might (some day in the future), detect that this will always panic. I don't see how the decision made in rfc 1229 does not apply to const fn as well. I have not thought about this too deeply though.

**Comment by RalfJung** [comment]
> I don't think the situation is different for const fn.

Agreed. There's a static check here, on the `const fn`, which has false negatives -- so we don't want to make it a hard error or else we can never reduce the number  of false negatives in the future. `fn` and `const fn` are just the same here. And then there's a dynamic check, when executing the `const fn` to compute the static initializer, where we have no choice but hard error. This is dynamic (it's executing arbitrary code in a turing-complete language), but at compile-time.

As @oli-obk mentioned, we do get two errors even in the following situation:
```rust
fn foo() -> i32 {
    [1,2,3][42]  // error here
}

fn main() {
    println!("{}", foo())
}
```
And again the second error is a dynamic check. It's just, now the dynamic check happens later.

**Comment by Centril** [comment]
Per https://forge.rust-lang.org/, Rust 1.31 goes beta on 2018-10-26 whereas the meeting is on the 18th so 1 week to go.

Nominated for triage for next Thursdays meeting.

My inclination is to not take any action per @oli-obk's and @RalfJung's notes.

**Comment by scottmcm** [comment]
:+1: the "we don't want to make it a hard error or else we can never reduce the number of false negatives in the future" argument is persuasive to me.

**Comment by oli-obk** [comment]
@Centril mused on discord whether

> the current set of analyses could be made into errors and then subsequent additional analyses become deny/warn once they are more powerful?

While that is certainly possible, I believe the maintenance const of it is not worth it considering the small diagnostics purity benefit we gain. We'd need to carefully opt out of reporting the result of "new" analyses as errors and instead report a lint. It is not always clear where a new analysis ends and an old one begins. Taking the above example as a strawman:

```rust
const fn foo(i: usize) -> i32 {
    [0, 1, 2][(i % 10) + 3]
}
```

currently does not report a diagnostic, because we are not tracing range information on integers along during the existing analyses. If we added such an analysis, we would also "taint" all preexisting analyses to be unable to report an error iff they got input from the new analysis. This would probably cause large parts of the const propagator to be about taint tracing instead of const propagating.

There is one alternative: duplicate the analyses as one that is not allowed to improve (the error one) and one that is allowed to improve (reports only lints). Now we'd have two copies of very similar code to keep in sync, but without causing one of them to get smarter.

**Comment by Centril** [comment]
We discussed this briefly at today's and decided to not take any action here.
In other words, the linting behavior shall remain.
