### ISSUE TITLE
Search box on nested 404 page `abc/123` goes to 404 `abc/std/index.html?...`

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#54952]
For instance, on https://doc.rust-lang.org/nightly/abc/123, the search box offers to search the standard library for 123. Clicking the search button goes to https://doc.rust-lang.org/nightly/abc/std/index.html?search=123 (note the `abc/std`) which is invalid. Probably related to 
https://github.com/rust-lang/rust/pull/54609 (cc @GuillaumeGomez).

**Comment by kzys** [comment]
Ah, my bad. I was assuming that the 404 page wouldn't contain `/`...

**Comment by GuillaumeGomez** [comment]
Problem is a bit more complicated than that: we need to keep the version we're looking at (stable, beta or nightly). Not a very complicated fix but still need to be careful. I'll open the PR soon.

**Comment by QuietMisdreavus** [comment]
This got brought up again in https://github.com/rust-lang/www.rust-lang.org/issues/864, so it's worth bringing @rust-lang/rustdoc and @rust-lang/docs into this thread as well.

The primary concern is *which* libstd search to send the user to. `doc.rust-lang.org` hosts documentation for every version of Rust, so it's possible someone hit a 404 while trying to browse docs for version 1.30.0` or the like. Should we redirect them to stable anyway? (Or nightly, since the standard library itself makes other crates link to nightly thanks to its `html_root_url`?) Should we try to detect which version of Rust they're browsing, and introduce a JavaScript semver parser into our 404 page? (Or have some other means of injecting the version number into the page?) There's not really a clean way to approach this, at least that i can see.

**Comment by huonw** [comment]
I think the version thing can be maintained from the current page as a "black box" slug without having to parse it? The difficulty would seem to then be deciding whether a URL is versioned (like `/nightly/std/...` or `/1.30.0/std/...`) or not (like `/std/...`), which can potentially be done via checking a list of the known fixed slugs or whether the first slug starts with a number. That might look something like the following (which is untested, and doesn't have appropriate error handling):

```javascript
const path = new URL(window.location.href).pathname
const firstComponent = path.split('/')[0]
const fixedVersions = ["stable", "beta", "nightly"]
const includeFirst = fixedVersions.includes(firstComponent) || /^[0-9]/.test(firstComponent)

// inside the search submit:

document.location.href = (includeFirst ? "/" + firstComponent : "") + "/std/index.html?search=" ...
```

**Comment by Dylan-DPC** [comment]
This now redirects to [this link](https://doc.rust-lang.org/std/index.html?search=123) which works as it's supposed to so closing this

**Comment by huonw** [comment]
That link https://doc.rust-lang.org/std/index.html?search=123 has lost the version (`/nightly/` in the original), which is probably okay, but isn't exactly 'correct'.
