### ISSUE TITLE
compiler_fence SeqCst docs are incorrect

### ISSUE THREAD

**Issue by parched** [rust-lang/rust#54962]
The documentation for `compiler_fence` with `SeqCst` say "no re-ordering of reads and writes across this point is allowed". As I understand it, `SeqCst` for a single thread doesn't give anything more than `AcqRel`. E.g., a store before the fence could be moved past a load after then fence. Is that correct?

cc @jonhoo @RalfJung

**Comment by jonhoo** [comment]
@RalfJung I'm actually not entirely sure about that. Another store to the same memory location shouldn't be ordered before, but I don't see from the reference text why an unrelated store with `SeqCst` couldn't be.

I'd be happy for this to be rephrased this in terms of the memory model, but I'm not entirely sure how we'd even do that. Proposals welcome. I think talking about what can and cannot happen, with examples, is probably the most understandable way to present what the different orderings do.

I left off the total order part because it didn't seem directly related to the original question. But you're right that it's a vital part of `SeqCst` that shouldn't get lost in the docs!

**Comment by parched** [comment]
> It actually depends on the other operation, does it not? 

Yes, good point. So how about we move the `SeqCst` bullet point to bottom and change it to say
> with `SeqCst`, all of the above rules are enforced and no re-ordering of any `SeqCst` reads or writes across this point are allowed.
