### ISSUE TITLE
Unnecessary macro expansion in unused_parens lint

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#55109]
This code snippet ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=390c4ae44b04058930f6899b095320c1))

```rust
fn main() {
    let _ = (format!("Test"));
}
```

results in the following lint output:

```
warning: unnecessary parentheses around assigned value
 --> src/main.rs:2:13
  |
2 |     let _ = (format!("Test"));
  |             ^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_parens)] on by default
help: remove these parentheses
  |
2 |     let _ = ::fmt::format(::std::fmt::Arguments::new_v1(&["Test"],
3 |                                              &match () { () => [], }));
  |

    Finished dev [unoptimized + debuginfo] target(s) in 0.56s
     Running `target/debug/playground`
```

The `help: remove these parentheses` should contain the literal string `format!`, not the expanded macro that it repreesnts.

**Comment by zackmdavis** [comment]
Ah, I think this is because we should be using `CodeMap::span_to_snippet` (to get the code the user actually wrote) [rather than `pprust::expr_to_string`](https://github.com/rust-lang/rust/blob/5ea8eb55cd9f4547b332f43c9f723de30187c223/src/librustc_lint/unused.rs#L284) (to render the AST); I could PR this tonight.
