### ISSUE TITLE
impl-everywhere.rs has a weird test

### ISSUE THREAD

**Issue by Munksgaard** [rust-lang/rust#55201]
From https://github.com/rust-lang/rust/pull/54824#issuecomment-428706766:

> > [ ] impl-everywhere.rs:// @!has foo/fn.foo.html '//section[@id="main"]//pre' "x: &\'x impl Foo"
>
> This test looks strange. The generated documentation looks like this (wrapped in pre):
> 
> ```
> pub fn foo<'x>(
>     x: &'x impl Foo
> ) -> &'x impl Foo
> ```
>
> so it seems like the backslash in the test is taken literally which means that it doesn't match. Is that on purpose? @GuillaumeGomez it seems like you created the test, so perhaps you can enlighten me?
>
> Edit: To be clear, removing the backslash from the test causes the test to fail.

My understanding is that test is trying to assert that `fn.foo.html` doesn't contain the phrase `x: &' impl Foo`, but because it is erroneously escaping a quote it fails to make that assertion. Furthermore, the generated `fn.foo.html` file actually _does_ contain the text being checked for, so there is a bug in rustdoc as well.

**Comment by Munksgaard** [comment]
This issue should be assigned to @GuillaumeGomez, as per his request in https://github.com/rust-lang/rust/pull/54824#issuecomment-431297782

**Comment by liketechnik** [comment]
I've made the following observations:

- The current output of `rustdoc` for the test is the same as the output with the initial implementation used with the test (e67bba8ebe14c815c4f756aa267249e5c35d5ec5) and also seems to match with the initial goal of the implementation in #53541. (I don't think the actual output of `rustdoc` is necessary here, but can provide that if needed). 
- The check has not been modified since its creation, I haven't been able to compare the implementations of the relevant parts in `rustdoc` though, due to my unfamiliarity with `rustdoc`s code.

My interpretation is that there is no bug in `rustdoc` (since the output stayed the same), but the test simply never validated the output correctly, because

- all checks validate the *absence* (all checks start with `@!has`) of an `impl Type` in parameters or return values, while the original goal of the implementation (see #53541) was to add support for `impl Type` in parameters and return values. Example: https://github.com/rust-lang/rust/blob/430feb24a46993e5073c1bb1b39da190d83fa2bf/src/test/rustdoc/impl-everywhere.rs#L11-L13 which would generate `pub fn foo<'x>(x: &'x impl Foo) -> &'x impl Foo` as documentation
- all checks expect an opening brace `{` after the return type, which is not generated by `rustdoc`. This makes the checks work, because now the 'expected' (see point 1) mismatch occurs.
- all checks with a lifetime were erroneously escaping a quote. Again, this makes the checks work, because now the 'expected' mismatch occurs.

If my observations are correct, I would go forward by opening a pr fixing the issues listed above for the test (e. g. making the test fail for possibly incorrect output by `rustdoc` in the future).

**Comment by jyn514** [comment]
@GuillaumeGomez can you confirm whether the summary above is correct?

**Comment by GuillaumeGomez** [comment]
Yes, it seems to be correct. Thanks for the summary @liketechnik ! Please feel free to open the PR. :)
