### ISSUE TITLE
Add `into_keys` and `into_values` to associative maps

### ISSUE THREAD

**Issue by orlp** [rust-lang/rust#55214]
Associative maps (`HashMap` and `BTreeMap`) in Rust are currently missing two methods to get owning iterators to their keys or values.

We have `iter` to get key-value reference pairs, `iter_mut` to get key-value mutable reference pairs and `into_iter` to get owned key-value pairs.

I'd expect `keys` and `values` to offer a similar trio of methods (with an exception for `keys_mut` of course). `values_mut` is there, but the `into` variants are missing for seemingly no good reason.

As an example implementation (but perhaps we can do better):

```rust
pub fn into_keys(self) -> impl Iterator<Item = K> {
    self.into_iter().map(|(k, v)| k)
}

pub fn into_values(self) -> impl Iterator<Item = V> {
    self.into_iter().map(|(k, v)| v)
}
```

**Comment by dtolnay** [comment]
I would accept a PR to introduce unstable into_keys() and into_values().

**Comment by canova** [comment]
@dtolnay Hi, I’m interested in working on this but I have a question regarding the implementation. I guess we can implement this in two ways. First one is implementing like the example in the first comment, like returning `Map<IntoIter<K, V>>`. And the second option is to return a struct of its own (like a mixture of [IntoIter](https://github.com/rust-lang/rust/blob/4fb54ed484e2239a3e9eff3be17df00d2a162be3/src/libstd/collections/hash/map.rs#L1094-L1096) and [Keys](https://github.com/rust-lang/rust/blob/4fb54ed484e2239a3e9eff3be17df00d2a162be3/src/libstd/collections/hash/map.rs#L1114-L1116)/[Values](https://github.com/rust-lang/rust/blob/4fb54ed484e2239a3e9eff3be17df00d2a162be3/src/libstd/collections/hash/map.rs#L1142-L1144) structs) instead of returning `Map<IntoIter<T>>`. We can name them IntoKeys and IntoValues and they can be responsible of implementing the `Iterator` trait.
I feel like performance wise they are same, since map and custom struct both will be evaluated lazily when we iterate over. But there might be a rule to always return a proper type in the rust std code that I don't know. So I think I’m okay implementing either way but wanted to ask just in case. What do you think?

**Comment by dtolnay** [comment]
For the public API I would prefer this implemented using dedicated IntoKeys and IntoValues iterator types. They can be implemented internally as wrappers around Map\<IntoIter\<K, V\>\> if that simplifies things.

**Comment by canova** [comment]
Thanks for the answer @dtolnay! Created a PR for this and added you as a reviewer. Would you mind taking a look at it when you have time?
