### ISSUE TITLE
Cannot link to Apple universal (fat) libraries

### ISSUE THREAD

**Issue by awakecoding** [rust-lang/rust#55235]
I have started modifying a few Rust "-sys" crates to point to some prebuilt C libraries that I currently share between my C and Rust code. For macOS and iOS, my prebuilt libraries are merged into universal libraries, with multiple architectures contained in the same .a static libraries.

For instance, when trying to link against a universal libcurl.a library for iOS, I get the following error:
failed to add native library /opt/wayk/sdk/iOS/curl/lib/libcurl.a: File too small to be an archive

The only other mention of such an issue is https://github.com/rust-lang/rust/issues/50220 but it was meant to fix an issue with compiling Rust, not adding proper support for linking to universal binaries from Rust crates.

For macOS, I could "fix" the issue because we have recently deprecated support for i386 in our prebuilt libraries, and managed to make single-arch x86_64 libraries. Only non-universal binaries work, a universal binary with a single architecture won't work. I had to modify my scripts to avoid calling lipo to merge multiple libraries if there was only one architecture to "merge" and end up with non-universal binaries.

One possible workaround would be to process libraries to be linked such that "lipo -thin" is called to extract single-arch non-universal libraries to a temporary location and then pass those libraries to the linker. It may not be the cleanest patch, but it could work well without much changes.

The exact line throwing the error can be found here:
https://github.com/rust-lang/llvm/blob/caddcd9b9dc9479a20908d93c3e47c49b021379e/lib/Object/Archive.cpp#L554

For reference, I took a screenshot of the first few bytes of a thin library and a fat library. The macOS thin library can be seen on the left with the magic number "CAFEBABE". The iOS fat library can be seen on the right the with magic string "`!<arch>`". The code throwing the error checks for the "`!<arch>`" magic string, so the first step to try to add code specific to universal binaries would be to handle files with the "CAFEBABE" magic number differently.

![libcurl_fat_thin](https://user-images.githubusercontent.com/295841/47260602-70561600-d48c-11e8-81a9-5037d1f8445e.png)

The relevant documentation for the universal binary format can be found here:
http://math-atlas.sourceforge.net/devel/assembly/MachORuntime.pdf#//apple_ref/doc/uid/20001298/TPXREF130

**Comment by rossmacarthur** [comment]
For those looking for some sort of a workaround for this I used the following in my `build.rs` when building a vendored library with CMake.

```rust
let mut config = cmake::Config::new(&vendor);

if env_var("CARGO_CFG_TARGET_OS") == "macos" {
    config.define("CMAKE_OSX_ARCHITECTURES", env_var("CARGO_CFG_TARGET_ARCH"))
}
```

**Comment by alex** [comment]
I spent some time digging into this:

An important note is that the error only reproduces if you are linking a fat `.a` into a Rust _library_. If you like it into a Rust _binary_ it'll actually work fine. I assume (without evidence) this is because the former need to get embedded into an `rlib` while the latter are passed directly to the system linker.

The full relevant places in the code are:

- https://github.com/rust-lang/rust/blob/0e1a6fb463e7075572cee841525bf44a864da807/compiler/rustc_codegen_llvm/src/back/archive.rs#L239
- https://github.com/rust-lang/rust/blob/0e1a6fb463e7075572cee841525bf44a864da807/compiler/rustc_codegen_llvm/src/back/archive.rs#L68
- https://github.com/rust-lang/rust/blob/0e1a6fb463e7075572cee841525bf44a864da807/compiler/rustc_codegen_llvm/src/llvm/archive_ro.rs#L32
- https://github.com/rust-lang/rust/blob/0e1a6fb463e7075572cee841525bf44a864da807/compiler/rustc_llvm/llvm-wrapper/ArchiveWrapper.cpp#L74
- https://github.com/rust-lang/llvm-project/blob/c9e2e89ed3aa5a3be77143aa0c86906b4138374a/llvm/lib/Object/Archive.cpp#L655-L658
- https://github.com/rust-lang/llvm-project/blob/c9e2e89ed3aa5a3be77143aa0c86906b4138374a/llvm/lib/Object/Archive.cpp#L695-L707
