### ISSUE TITLE
rust 2018: local_inner_macros and stringify

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/rust#55268]
I am trying to update `yew` to work with the 2018 edition. I need to use the `local_inner_macros` feature, but it seems to clobber built-in macros like `stringify` and `compile_error`. Is is possible to just spot these particular macros and not add `$crate::` to them?

**Comment by petrochenkov** [comment]
>Is is possible to just spot these particular macros and not add `$crate::` to them?

Not without effort that would be disproportionally high for a transitional/deprecated-on-arrival feature like `local_inner_macros`.
(Built-in macros can be shadowed, so we can't detect them correctly just looking at their name in isolation, we'd basically need some insta-stable form of def-site hygiene.)

If you don't need compatibility with pre-1.30 versions of Rust, `$crate` is recommended for use instead of `local_inner_macros`.
If you need compatibility, then built-in macros can be used with `local_inner_macros` through [one more level of indirection](https://github.com/rust-lang-nursery/log/pull/288).

**Comment by derekdreery** [comment]
I see, so you can just create a macro that delegates. Hopefully this issue
will serve as documentation if anyone else has this issue.

**Comment by derekdreery** [comment]
Made a doc PR for this: https://github.com/rust-lang-nursery/edition-guide/pull/117

**Comment by petrochenkov** [comment]
The doc PR has landed, so I'm closing this.
