### ISSUE TITLE
rustdoc intra links: doc of exported private items don't have the namespace of their doc-visible location

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#55365]
```Rust
mod window {
    /// See [Event]
    pub struct Window;
}
mod event {
    /// See [Window]
    pub struct Event;
}

pub use event::Event;
pub use window::Window;

```

```
6 |     /// See [Window]
  |              ^^^^^^ cannot be resolved, ignoring

```
I don't know if this is an accidental regression or intentional, but this used to resolve.

It has been used extensively by rust-sfml. See the [example of Event referring to Window](https://docs.rs/sfml/0.14.0/sfml/window/enum.Event.html). From the viewpoint of the user, `Event` and `Window` exist in the same module. It's only a private implementation detail that they are implemented in their own submodules, and re-exported into a common module.

Ref #43466

**Comment by Nemo157** [comment]
IMO this seems like spooky action at a distance, I would expect doc links to always resolve from the place where they are written. Otherwise you have issues if the same documentation is expected to be shown at multiple places with different locally visible paths (presumably this changed to fix this exact case, it is an issue that has been hit many times in the `futures(0.3)` ecosystem).

**Comment by Manishearth** [comment]
reexports are expected to be broken with intra doc links

see https://github.com/rust-lang/rust/issues/43466 , this is why we haven't been able to stabilize it
