### ISSUE TITLE
ICE in macro: doc meta with expr on an item, string concat, stringify!(...)

### ISSUE THREAD

**Issue by u32i64** [rust-lang/rust#55414]
## code

```rust
macro_rules! bug {
    () => {
        bug!("bug" + stringify!(found));
    };
    ($test:expr) => {
        #[doc = $test]
        struct Test {} // looks like any item works
    };
}

bug!();
```

## description

Any of the following actions stop the panic:
- Removing or commenting the `doc` attribute:
  ```rust
  // #[doc = $test]
  ```
- Replacing macro call with:
  ```rust
  bug!("");
  ```
- Removing concatenation:
  ```rust
  () => {
      bug!(stringify!(anything));
  };
  ```
- Replacing `stringify!(...)`:
  ```rust
  () => {
      bug!("bug" + "test");
  };
  ```

## stderr
<details><summary>Show output</summary>

```console
thread 'main' panicked at 'no entry found for key', libcore/option.rs:1000:5
stack backtrace:
   0:     0x7f381365575e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hf5316c67202e23c8
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f381362e946 - std::sys_common::backtrace::print::h3068ed2a6dc7ac86
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x7f381362c54d - std::panicking::default_hook::{{closure}}::h1b9d29cc09d41897
                               at libstd/panicking.rs:211
   3:     0x7f381362c2c0 - std::panicking::default_hook::h3a27b204a313406b
                               at libstd/panicking.rs:227
   4:     0x7f380fe769f1 - rustc::util::common::panic_hook::hf9d72254884e6e21
   5:     0x7f381362cc53 - std::panicking::rust_panic_with_hook::h0e12cb2fc86d00fa
                               at libstd/panicking.rs:481
   6:     0x7f381362c7b9 - std::panicking::continue_panic_fmt::h141671b29fe0e27d
                               at libstd/panicking.rs:391
   7:     0x7f381362c6b5 - rust_begin_unwind
                               at libstd/panicking.rs:326
   8:     0x7f38136a55db - core::panicking::panic_fmt::h429a06507aba9228
                               at libcore/panicking.rs:77
   9:     0x7f38136a5671 - core::option::expect_failed::h4c79c3aae6612643
                               at libcore/option.rs:1000
  10:     0x7f38128de274 - rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a, 'crateloader>>::resolve_macro_invocation::hcacc2b568dda6de5
  11:     0x7f380eecdf28 - syntax::ext::expand::MacroExpander::expand_fragment::h26fd612375b32814
  12:     0x7f380eecd6b1 - syntax::ext::expand::MacroExpander::expand_crate::h3497aacb05bd8e53
  13:     0x7f38139c0303 - rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}::h3d4d02fec2b68db2
  14:     0x7f38139bedda - rustc::util::common::time::ha1804c2290179406
  15:     0x7f38139d7b54 - rustc_driver::driver::phase_2_configure_and_expand::h2c60f5950dd2995f
  16:     0x7f38139d356b - rustc_driver::driver::compile_input::h6a302c45b9b8d410
  17:     0x7f3813a7b20c - rustc_driver::run_compiler_with_pool::h2a396394cdff52b0
  18:     0x7f38139d2f34 - rustc_driver::driver::spawn_thread_pool::h5dec0f6efcb9456b
  19:     0x7f3813a7a221 - rustc_driver::run_compiler::he4a6ce0f80da709f
  20:     0x7f38139c169c - <scoped_tls::ScopedKey<T>>::set::h0d2c211708f72196
  21:     0x7f38139fd651 - syntax::with_globals::hcc4912b6b554b6a2
  22:     0x7f381366c469 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:103
  23:     0x7f3813a7847c - rustc_driver::run::h9e76da7d522d5bdd
  24:     0x7f3813a864ba - rustc_driver::main::h979d81f5800d15a6
  25:     0x55b562390992 - std::rt::lang_start::{{closure}}::h5cee4df267a41ddd
  26:     0x7f381362c652 - std::panicking::try::do_call::h572dc6f90deb1a4d
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  27:     0x7f381366c469 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:103
  28:     0x7f3813642b45 - std::rt::lang_start_internal::hce01021c3c1cf20d
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/rt.rs:58
  29:     0x55b562390983 - main
  30:     0x7f3813400222 - __libc_start_main
  31:     0x55b562390838 - <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0 (da5f414c2 2018-10-24) running on x86_64-unknown-linux-gnu
```

</details>

## rustc

```console
$ rustc --version --verbose
rustc 1.30.0 (da5f414c2 2018-10-24)
binary: rustc
commit-hash: da5f414c2c0bfe5198934493f04c676e2b23ff2e
commit-date: 2018-10-24
host: x86_64-unknown-linux-gnu
release: 1.30.0
LLVM version: 8.0
```

**Comment by jonas-schievink** [comment]
Still reproduces on current stable and nightly

**Comment by nagisa** [comment]
@petrochenkov this sounds like something you might want to look at.

**Comment by petrochenkov** [comment]
Minimized further:
```rust
macro_rules! bug {
    ($expr:expr) => {
        #[rustc_dummy = $expr] // Any key-value attribute, not necessarily `doc`
        struct S;
    };
}

// Any expressions containing eager expansion `X` that's more complex than `X` itself.
// Parentheses will work.
bug!((stringify!(a)));
```

**Comment by petrochenkov** [comment]
The ICE happens due to a mismatch in nonterminal token visiting between `Visitor` and `MutVisitor` (`token::NtExpr` in this case).

`Visitor` (`BuildReducedGraphVisitor`) doesn't visit them so macros in them don't get properly registered, `MutVisitor` (`InvocationCollector`) however visits them and attempts to expand macros in them even if they are not registered, so ICEs happen.

**Comment by pnkfelix** [comment]
@petrochenkov is the presumed fix here to add `fn visit_interpolated` and `fn walk_interpolated` to the `syntax::visit::Visitor` trait?

**Comment by petrochenkov** [comment]
That would fix the ICE, but
- Visiting interpolated tokens as AST (mutably or not) was never a good idea. In the token-based macro expansion model (which is currently in effect in proc macros, but we'd like to migrate to it everywhere else) interpolated tokens contain tokens and not AST.
- Make more code compile successfully despite us not wanting it to compile from the token-based model's point of view.

**Comment by petrochenkov** [comment]
I have a plan on running some crater experiments to find out which kinds of expansions inside interpolated tokens are used in practice, but I need someone else's help to implement it due to lack of time.

**Comment by petrochenkov** [comment]
The experiment is to attempt restricting macro expansion inside attributes to `#[attr = $expr]`.

Some relevant links are
https://github.com/rust-lang/rust/issues/55414
https://github.com/rust-lang/rust/issues/47358
https://github.com/rust-lang/rust/issues/44732#issuecomment-526560063

If the experiment goes well, then we'll proceed further in this direction and the end result should be an RFC about supporting macro expansions in key-value attributes like `#[doc = include_str!("doc.md")]`.

Another link: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Nt.20tokens.20in.20the.20parser

---
So, the problem is that `InvocationCollector` collects and attempts to expand macro invocations inside tokens in attributes.

How does that happen?
Tokens in attributes can be nonterminal tokens (like `NtExpr`, aka `$expr: expr` in `macro_rules` in source code).
`InvocationCollector` is a `MutVisitor` and `MutVisitor` by default visit nonterminals as actual AST fragments (expressions, types, etc).
So, `InvocationCollector` visits all those fragments too, in any tokens, and attempts to expand them as macros.
The zulip link above shows how this can be used for building the value of a `#[doc = ...]` attribute with a macro.

We need to restrict `InvocationCollector` to only doing this when the attribute looks like this - `#[attr = $expr]` (not `#[attr(1 2 $expr 3 4)]` or anything else).
This can be done by overriding `fn visit_attribute`, detecting key-value attributes in it, visiting only them, and not recursing further into tokens.

**Comment by petrochenkov** [comment]
It's simpler to implement this on top of https://github.com/rust-lang/rust/pull/66935.

**Comment by CAD97** [comment]
I just ran into this with a [`doc_comment!` macro](https://github.com/rust-lang/rust/blob/adc65725004c8aac16392fe4052c3e347181157d/src/libcore/num/mod.rs#L28-L33):

```rust
doc_comment! {
    concat("Create a new ", stringify!($RcBox), "."),
    pub fn new(data: T) -> Self
    where
        T: Sized,
    {
        unsafe { $RcBox::from_unchecked($Rc::new(data)) }
    }
}
```

The typo of `concat(` instead of `concat!(` lead to this ICE.

This does show the common "abuse" of `#[doc = $expr]` and how easily it can go wrong, however.

**Comment by spastorino** [comment]
[As per Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/pre-meeting.20triage.202020-04-02.20.2354818/near/192571535) changing priority to `P-medium`

**Comment by petrochenkov** [comment]
I started working on this in https://github.com/rust-lang/rust/pull/77271.
