### ISSUE TITLE
diagnostics: span_note/span_help/etc should work with dummy spans

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#55669]
`span_note` and friends require this non-obvious pattern to work correctly:
```rust
if span.is_dummy() {
    err.note(msg);
} else {
    err.span_note(span, msg);
}
```
If dummy span is passed to `span_note` then the message simply won't be displayed, but with `note` it will be attached to the primary `err` message.
The difference is that `note` turns into an empty multi-span, but `span_note` turns into multi-span containing a single dummy span.

I think `span_note` should "just work" with dummy spans and display the message equivalently to `note`.

**Comment by petrochenkov** [comment]
cc @estebank

**Comment by eddyb** [comment]
cc @nikomatsakis @nrc

**Comment by estebank** [comment]
Now multispans also have an `is_dummy()` method, so that won't be a source of problems. The only thing that I can think of that _could_ present a challenge is for suggestions (which I guess are out of scope for this thicket) they usually have a fallback with tweaked wording to work as `note`/`help`.

I can write out mentoring notes for this.
