### ISSUE TITLE
rustdoc: missing const values

### ISSUE THREAD

**Issue by jnqnfe** [rust-lang/rust#55680]
Just noticed with 1.30 that generated documentation no longer shows values of constants, only their type. Was this a deliberate change or a regression?

Aplogies if already reported, I took a quick look and did not find, nor do I recall reading in blog post.

**Comment by frewsxcv** [comment]
At least for associated constants, here's a relevant thread: https://github.com/rust-lang/rust/pull/53409

**Comment by QuietMisdreavus** [comment]
The change was deliberate. Rustdoc got the rendering of the value directly from the compiler, and didn't try to hide things like private or `#[doc(hidden)]` fields, because it had no control over its rendering. The PR that @frewsxcv linked, (and its linked issue, https://github.com/rust-lang/rust/issues/44348) contains farther discussion.

**Comment by jnqnfe** [comment]
Oh, okay, thanks :+1:
