### ISSUE TITLE
gdb BTreeMap pretty printer is incorrect

### ISSUE THREAD

**Issue by tromey** [rust-lang/rust#55771]
As noted [here](https://github.com/rust-lang/rust/pull/53357#issuecomment-436333097), the `BTreeMap` pretty-printer for gdb only works for a small number of elements.

For example, this works:
```
use std::collections::BTreeMap;

pub fn main() {
    let mut btree_map = BTreeMap::new();
    for i in 0..10 {
        btree_map.insert(i, i * 2);
    }
    let x = 72;
}
```

However, if you change the 10 to 15, it will stop working:

```
(gdb) p btree_map 
$1 = BTreeMap<i32, i32>(len: 15) = {
  [6] = 12,
  [0] = 32767,
  [1431906992] = 0,
  [21845] = 11,
  [1431907048] = 22,
  [21845] = 21845,
  [4] = -12448,
  [0] = 32767,
  [1431907004] = -11872,
  [21845] = 32767,
  [4] = 1431680491,
  [12] = 0,
  [32767] = 1431906880,
  [0] = 21845,
  [11] = 1431906992
}
```

**Comment by ortem** [comment]
The problem is this pretty-printer gets the data only from the root node and doesn't take into account the structure of B-tree. It is necessary to implement the iteration over all tree, so the bug is not so easy to fix. I will try to do it in the near of future, together with the [HashMap](https://github.com/rust-lang/rust/issues/41082), but not sure if I can handle it.
