### ISSUE TITLE
Rustdoc's generated IDs overlap with manually written HTML

### ISSUE THREAD

**Issue by jnqnfe** [rust-lang/rust#55791]
I noticed a bug in generated documentation in 1.29, still affecting 1.30, where the second heading is incorrectly given the wrong CSS attributes, causing overlapping content.

Specifically it seems to only occur if the second heading is "Results" or "results", and only for the second heading. These are the only combinations I've seen it happen for.

The heading is given an `absolute: relative` attribute...

... Ah, I see the issue, the heading gets the ID "results", which matches an existing CSS rule... Perhaps the IDs assigned to headings should have a prefix to prevent clashes?

![screenshot from 2018-11-08 18-49-59](https://user-images.githubusercontent.com/33935229/48220972-ac441300-e388-11e8-904a-d4e290988fae.png)

**Comment by euclio** [comment]
I don't think we can add a prefix to the heading links, because that would break any external links that are pointing to the docs.

We could add tags to the CSS selectors, which would increase the specificity, but has the downside that then the CSS must be updated if the tag associated with the ID changes. Also, we still have an issue that IDs used on the page could conflict with the heading IDs.

We could use the `name` attribute on the headings instead of id, but then links with that ID could still potentially conflict with other elements on the page.

Another solution would be to not use IDs in the CSS or page at all, meaning that there is no chance for a conflict, but this would involve quite a bit of change to the HTML, CSS, and JavaScript.

**Comment by GuillaumeGomez** [comment]
We already solved this issue a while ago so closing. Some more information: we keep track of the IDs used by rustdoc and then "derive" the ones generated by users' docs to prevent conflicts.
