### ISSUE TITLE
Factor out rustc_apfloat into a standalone crate

### ISSUE THREAD

**Issue by sunfishcode** [rust-lang/rust#55993]
[librustc_apfloat](https://github.com/rust-lang/rust/tree/master/src/librustc_apfloat) is a Rust translation of [LLVM's APFloat library](https://github.com/llvm-mirror/llvm/blob/master/lib/Support/APFloat.cpp), written in C++, and provides software implementations of `f32`, `f64`, and other floating-point types, which are useful for performing host-independent floating-point computation. We made a standalone crate of this for use in Cranelift, however other compiler projects could make use of such a library as well, and in general it'd be good to have only one copy of this code.

Where's the best place for the code live?
 - Create a new repository under [the rust-lang organization](https://github.com/rust-lang/).
 - Use the repository that Cranelift is currently using [here](https://github.com/CraneStation/rustc_apfloat).

What should the crate be called?
 - `rustc_apfloat` -- the current name. "apfloat" isn't very descriptive, except that it's the name of the upstream code this crate is based on. And the crate isn't specific to rustc :-).
 - `software_float` -- a more descriptive name, and not yet claimed on crates.io
 - other ideas?

cc @eddyb @lachlansneff

**Comment by eddyb** [comment]
`software_float` is a bit long, I'd rather expect something like `softfloat`.

cc @rust-lang/compiler

**Comment by eddyb** [comment]
Also, I *think* we need to figure out copyright. I remember talking to a few people about it and our licensing setup deals with LLVM, but I'm not sure about a crate in isolation.
cc @alexcrichton

**Comment by bstrie** [comment]
What's there about copyright to figure out? The copyright header of that LLVM file implies it's licensed under the Illinois Open Source License, which is an FSF- and OSI-approved permissive license.

**Comment by eddyb** [comment]
@bstrie `rustc_apfloat` is not currently explicitly licensed in any way different from any of the other Rust code in the repo, but apparently this is okay because of the `COPYRIGHT` file or something.
IANAL so no clue what we'd need to do here, I just remember being told things are okay.

**Comment by bstrie** [comment]
Ah, I see. I'm also not a lawyer, but I'm fairly confident that it isn't compliant with the license for us to create a derivative work of apfloat that doesn't use the Illinois license, at least not without explicit permission of the copyright holder. Those license headers claiming that rustc_apfloat is MIT/Apache seem somewhat dubious.

On the one hand I want to say that we should just change the license headers to be compliant (under this interpretation this doesn't count as relicensing, since we didn't have permission to use a different license in the first place); shipping more Illinois-licensed code when we already ship all of LLVM isn't a problem.

However--and here's the thing you might really need a lawyer for--if there's anyone who's contributed to rustc_apfloat while it's been erroneously licensed, I have absolutely no idea what license their contributions are actually licensed under. The conservative response would be to reach out to anyone who's ever contributed to it and ask them if they're okay with their contributions being licensed as Illinois.

**Comment by eddyb** [comment]
> if there's anyone who's contributed to rustc_apfloat while it's been erroneously licensed, I have absolutely no idea what license their contributions are actually licensed under

Looking at https://github.com/rust-lang/rust/commits/master/src/librustc_apfloat, it's mostly sweeping changes across the the codebase, with only a few `apfloat`-specific changes.

Some of the more specific ones, like fixing comments, need to be upstreamed to LLVM as well, IMO.
I should've enforced a stricter policy of keeping the two in sync (modulo language/library minutiae).

**Comment by eddyb** [comment]
Note to self: write an email to Mozilla legal about this situation.
(please ping me on IRC/Discord next week until this comment gets removed)

**Comment by eddyb** [comment]
Oops, this *really* slipped through the cracks. I remembered about it at the All-Hands in Berlin (back in February IIRC), but forgot about it again.

Also, this is now completed: https://llvm.org/foundation/relicensing/ - LLVM moved to the Apache2 license.
So that might change the legal calculus a bit. But it seems likely we can just use Apache2 now.

**Comment by eddyb** [comment]
Once we move this out of tree we might want to have (as per https://github.com/rust-lang/rust/pull/63416#issuecomment-524545946):
> * one branch for the port (where LLVM->Rust backports would go into)
> * one branch for the crates.io version, *based* on the other branch, with some other patches on top

This would even allow upstreaming some of the changes to LLVM, but at our own pace.

**Comment by RalfJung** [comment]
@eddyb [wrote](https://github.com/rust-lang/rust/pull/83185#issuecomment-800275389)
> But I haven't been able to do as much as I want with it because it's been stuck in licensing limbo for years.
>
> I don't dare to touch it at all, really, while the licensing situation is up in the air, in the fear that it will prolong the limbo (originally I was assured there were no licensing issues and whoever told me that was wrong, so I don't want that to happen again) and I'd strongly advise anyone else against messing with it.

However, in this thread here [it sounds like](https://github.com/rust-lang/rust/issues/55993#issuecomment-502466788) things are fine as LLVM moved to Apache2 licensing. Are there further licensing issues not yet mentioned in this thread?

**Comment by est31** [comment]
Not a lawyer but these are a few open problems/questions I would have:

* LLVM moved not to Apache2 itself but to "Apache-2.0 WITH LLVM-exception" to use its SPDX identifier. I would guess that it's downward compatible to Apache-2.0, but ideally that exception is kept as it has definite GPL 2.0 compatibility, while the compatibility of Apache-2.0 with GPL 2.0 is an open question.
* From my understanding, rustc_apfloat bases on an older version of llvm's apfloat code that existed before the relicensing. From what I understand, the relicensing did *not* extend to historic versions of llvm arbitrarily far back into the past. Is the historic version sufficiently different from the oldest relicensed version for it to be a problem?
* Since its merger, rustc_apfloat has had modifications here and there (although few I guess?). I'm not sure under which license those modifications were, and where that'd put the combined work.

**Comment by eddyb** [comment]
> Since its merger, rustc_apfloat has had modifications here and there (although few I guess?). I'm not sure under which license those modifications were, and where that'd put the combined work.

At least we can split out the modifications somewhat, I'm more interested in the original port.
I could resync the port to a newer version of LLVM if it helps, and treat any changes on top as if they never happened (and anything that's not just aesthetic changes, can be redone as-needed).

> Are there further licensing issues not yet mentioned in this thread?

All I know is people more qualified than me are going to look into it (or are already doing that). I haven't heard anything to suggest it's solved, though.

**Comment by bstrie** [comment]
The current situation where people seem too afraid to approve changes to rustc-apfloat seems untenable. Instead of not approving any changes, get approval from the people submitting changes that they consent to having their changes optionally released under some set of licenses that you come up (say, Illinois, MIT, Apache 2).

**Comment by cbeuw** [comment]
Similar to @bstrie's suggestion. Can we change the rustbot comment to something like "You agree that the license of your contributions to `rustc_apfloat` may be changed to Apache 2.0 with LLVM exceptions at the core team's pleasure without notification"

**Comment by RalfJung** [comment]
Cc https://github.com/rust-lang/rust/pull/96784 which also mentions apfloat licensing

**Comment by eddyb** [comment]
It's been a while <sub><sup>(my bad)</sup></sub> since potential solutions were discussed, but I come bearing good news.

With @pnkfelix and @wesleywiser coordinating things and also e.g. painstakingly verifying the licensing side  (unsurprisingly, LLVM's colossal relicensing effort didn't go perfectly smooth - I'm very grateful they're handling those aspects, so that we'll never end up again, hopefully), I finally managed to find some time to execute on the plan we discussed late last year: start fresh *all the way back from the original port*.

---

My main focus this time was **correctness**: we kept stumbling onto bugs, and, *personally*, I don't think `rustc` devs should be in the business of randomly fixing softfloat bugs (or Rust users randomly running into them).

This is a library of 100% pure integer math, *there are better ways*.

---

### Here's a rundown of the notable [commits from the WIP `rustc_apfloat` repo](https://github.com/LykenSol/rustc_apfloat/network):
* **[fuzz: `cargo-afl`-based fuzzer comparing Rust vs C++ (vs hardware floats).](https://github.com/LykenSol/rustc_apfloat/commit/4aca99d02eb619e35983e100ebabc63bb90d8aa2)**
  * while it doesn't have complete coverage of all possible operations (and we can of course always add more), for the ones it *does*, it's incredibly effective at finding mismatches (sometimes within less than a second, if seeded right)
  * I originally wanted to include e.g. IBM IEEE floating-point test data as seeds, but didn't get to it, and it found plenty of bugs *anyway*
  * the current version of this tool has `decode` subcommand for reports like this:
    <sub>*(click to enlarge)*</sub>
    <img src="https://github.com/rust-lang/rust/assets/77424/b0c0c7aa-a042-4ced-8d40-474d467435a5" height="100">
    <sup>(and yes that FMA NaN behavior mismatch in APFloat vs hardware does get very annoying)</sup>
* **[Fix porting mistake found by fuzzing: `mul_add(finite, finite, ±inf_or_nan)` needs to ignore the finite multiplication.](https://github.com/LykenSol/rustc_apfloat/commit/8270711aa52c6568392c7f50c3ad6af6c6c9c3c8)**
  * this fixes https://github.com/rust-lang/rust/issues/100233
  * *crucially*, the fuzzer found testcases we hadn't considered, and *forced* me to find the correct solution
* at this point (after some other commits I'm eliding here) I'd ran out of things I could fix without updating the `rustc_apfloat` port to include newer `llvm::APFloat` changes (as most bugs we've ran into were upstream ones), so that's what I started doing
* **[Advance the port to](https://github.com/LykenSol/rustc_apfloat/commit/9590e584afa43f1593096a4a96b661bc475f6ac2) https://github.com/llvm/llvm-project/commit/768d6dd08783440606da83dac490889329619898** (Dec 2017)
  * this fixes https://github.com/rust-lang/rust/issues/102403
    (thanks to upstream fix https://github.com/llvm/llvm-project/commit/f2c2851efe0505328d1f4074b313a2922bcd8f2c)
* **[Advance the port to](https://github.com/LykenSol/rustc_apfloat/commit/423500440433720f44cacc321a2be5c5f9eba5e4) https://github.com/llvm/llvm-project/commit/69f6098e89312b934ed87e4cd3603401a9b436b4** (Dec 2018)
  * not notable because of any Rust issues, but this is the last stretch of `APFloat` changes before the massive LLVM relicensing (https://github.com/llvm/llvm-project/commit/2946cd701067404b99c39fb29dc9c74bd7193eb3) in early 2019
* **[Advance the port to](https://github.com/LykenSol/rustc_apfloat/commit/e7308e483bc1b8f85ecd6a5d0fda3a2fd4242d84) https://github.com/llvm/llvm-project/commit/2b6b8cb10c870d64f7cc29d21fc27cef3c7e0056** (Dec 2019)
  * this fixes https://github.com/rust-lang/rust/issues/93224
    (thanks to upstream fix https://github.com/llvm/llvm-project/commit/e62555c129d535d524354351791c5474c9929582)
* **[Advance the port to](https://github.com/LykenSol/rustc_apfloat/commit/8eb769d5034ee983ad344e6d01dbacc54ed86c96) https://github.com/llvm/llvm-project/commit/6dabc38cce73549ed747c537f81f6f4dd79eba39** (Nov 2020)
  * this obsoletes https://github.com/rust-lang/rust/pull/77368
    (as the port now includes https://github.com/llvm/llvm-project/commit/e34bd1e0b03d20a506ada156d87e1b3a96d82fa2 and https://github.com/llvm/llvm-project/commit/149f5b573c79eac0c519ada4d2f7c50e17796cdf without selective backporting)
  * because `rustc_apfloat` doesn't take certain questionable shortcuts, this exposed a testing mistake
    *all the way back from 2013*: https://github.com/llvm/llvm-project/issues/63842

At this point I think it's safe to say this version of `rustc_apfloat` is strictly superior to what's in `compiler/rustc_apfloat` right now <sub>(okay, sure, maybe it has more typos, and we still need to bring in @wesleywiser's detailed documentation of all the licensing history, before it can actually be used by anyone)</sub>.

Pushing the port forward another year or two (or even all the way up to the present) should be quite doable (I've previously overestimated the complexity added by new float formats - `bfloat16` was just *one line* in `src/ieee.rs`, NaN-related tests seem to the be bulk of the changes), but I need to stop <sub><sup><sub>~~after 30h awake~~</sub></sup></sub> for now.

---

As a teaser, this is what seems to be the only remaining issue:
* https://github.com/rust-lang/rust/issues/113407
  * fixed upstream last year (https://github.com/llvm/llvm-project/commit/ed6c309d4bf60b8a6abcf37a4e9d5b4bef96191b)
  * fuzzer found it pretty quickly once the relevant operation was added:
    
    ![image](https://github.com/rust-lang/rust/assets/77424/54bad053-c973-49db-9082-6d80b84b2ea9)

**Comment by eddyb** [comment]
Small update regarding the port advancing PR:
* https://github.com/rust-lang/rustc_apfloat/pull/1

Specifically, these new commits are significant:
* **[Advance the port to](https://github.com/rust-lang/rustc_apfloat/commit/b4f1e92e1a1446924eb36862d7124c50b1ebb8d0) https://github.com/llvm/llvm-project/commit/462a31f5a5abb905869ea93cc49b096079b11aa4** (Dec 2022)
  * this fixes https://github.com/rust-lang/rust/issues/113407
    (thanks to upstream fix https://github.com/llvm/llvm-project/commit/ed6c309d4bf60b8a6abcf37a4e9d5b4bef96191b)
* [**fuzz: add `bruteforce-tiny` subcommand for exhaustively checking 8-bit formats.**](https://github.com/rust-lang/rustc_apfloat/commit/d7c5328a447afa863adda6b44f07281003bd91e1)
  * the introduction of 8-bit floating-point formats allowed exhaustive testing which revealed:
    https://github.com/llvm/llvm-project/issues/63895
    * even if this FMA+subnormals bug was found via 8-bit floats, it applies to `f32::mul_add`/`f64::mul_add` (including LLVM constant-folding: a `rustc` build w/ LLVM assertions enabled *will* crash)
    * at least `rustc_apfloat` will always trip the `assert!` but [LLVM can just give wrong results](https://github.com/llvm/llvm-project/issues/63895#issuecomment-1639050715)

### At this point, all previously-known `rustc_apfloat` bugs have been fixed<br><sub>(shame about the new one though)</sub>

**Comment by eddyb** [comment]
Both `rust-lang/rustc_apfloat` PRs have now landed:
* https://github.com/rust-lang/rustc_apfloat/pull/2
* https://github.com/rust-lang/rustc_apfloat/pull/1

I've also tried [to describe as much I could in the README](https://github.com/rust-lang/rustc_apfloat#readme).
<sup>(it may be a bit too verbose though, feel free to file issues/PRs or bring it up on Zulip)</sup>

Next steps are probably to perf+crater switching to the new version, and releasing on crates.io if everything goes well (ideally fully replacing the old `CraneStation/rustc_apfloat` crate published by @lachlansneff - IMO the existing versions should be yanked because [they're labeled as `MIT` and `MIT/Apache2`](https://crates.io/crates/rustc_apfloat/versions), and I doubt either of those choices is legitimate).
