### ISSUE TITLE
Integral type mismatch error messages should use "expression" instead of "variable"

### ISSUE THREAD

**Issue by dooblad** [rust-lang/rust#56115]
Type mismatch error messages involving integral expressions use the word "variable", when the problematic term is an expression.

I tried this code:
```rust
fn main() {
    let f = if true {
        ()
    } else {
        1
    };
}
```

I expected to see this happen:
```
<code sample that causes the bug>
error[E0308]: if and else have incompatible types
 --> src/main.rs:2:13
  |
2 |       let f = if true {
  |  _____________^
3 | |         ()
4 | |     } else {
5 | |         1
6 | |     };
  | |_____^ expected (), found integral expression
  |
  = note: expected type `()`
             found type `{integer}`
```

Instead, this happened:
```
<code sample that causes the bug>
error[E0308]: if and else have incompatible types
 --> src/main.rs:2:13
  |
2 |       let f = if true {
  |  _____________^
3 | |         ()
4 | |     } else {
5 | |         1
6 | |     };
  | |_____^ expected (), found integral variable
  |
  = note: expected type `()`
             found type `{integer}`
```

## Meta

`rustc --version --verbose`:
```
rustc 1.31.0-nightly (3e6f30ec3 2018-10-26)
binary: rustc
commit-hash: 3e6f30ec3e6bda159063fcd126dcb14725fef92d
commit-date: 2018-10-26
host: x86_64-apple-darwin
release: 1.31.0-nightly
LLVM version: 8.0
```

Backtrace: N/A

**Comment by varkor** [comment]
It's probably sufficient just to change:
https://github.com/rust-lang/rust/blob/e7b4bc35e99ee3c5b2b42a1b8b3f9cd6eca1f0b2/src/librustc/ty/error.rs#L213-L214
to:
```rust
            ty::Infer(ty::IntVar(_)) => "integer variable".into(),
            ty::Infer(ty::FloatVar(_)) => "floating-point number".into(),
```

**Comment by hdhoang** [comment]
Do you think the `FreshIntTy` and `FreshFloatTy`  below those should be changed similarly? I haven't seen those in messages before.

**Comment by varkor** [comment]
I don't think those should appear in user error messages, so I think they can be ignored.

**Comment by codeworm96** [comment]
Is there anyone working on this issue? If not, I would like to have a try.

**Comment by codeworm96** [comment]
I almost finished [the change](https://github.com/codeworm96/rust/commit/710dcbd3818deca8f193a45e321b58af3c24feae), but I start to worry about whether we really want to change it.
1. The old terminology is already used widely (I have to change many tests)
2. The "variable" does have some meaning. It means type variable in the type inference. (However, it has nothing to do with the "variable" in the user's code, which caused the confusion.)

**Comment by hdhoang** [comment]
Well done! I'm certain this is an improvement for users, since we also emit this message for integer literals. In my head, "integer -> oh, my integer-typed variable" flows very nicely, compared to the original report above where I have to make the inference "integral variable -> uuuhh, the literal integer I put there". Reading the updated `stderr` files gave me similar feeling.

I have seen this message used in the submodules for `src/doc/book/` and `src/tools/clippy`, so you will need to change those too. Then making PRs following this procedure:  https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#breaking-tools-built-with-the-compiler will update the repos in concert.
