### ISSUE TITLE
Get rid of global `AllocId` tables

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#56383]
Right now we have a big global table of all allocations that the current rustc execution has need of. This doesn't fit the query system, has loads of complicated code for loading from metadata and generally complicates const eval.

I believe it is a goal to ensure that the `const_eval` query result needs no further queries to inspect the `Allocation`s returned. For this, we'd need to return the entire set of `Allocation`s from the query and have some sort of local allocation ids for relocations, or just have relocations refer to `Allocation`s directly.

The direct refering to `Allocation`s is problematic if we ever allow heap allocations and thus graphs or other cyclic datastructures in constants, because then we'd have cyclic references.

Local ids are problematic, because we either have to duplicate all `Allocation`s we get from other constants, or we have to figure out a scheme to use the same `Allocation` 

![grafik](https://user-images.githubusercontent.com/332036/49300168-cc677d80-f4c1-11e8-9ab2-68d75d90cae3.png)
<details>
<summary>Click here for graphviz code of this graph</summary>

```dot
digraph G {
    constA -> AllocationA -> AllocationB
    AllocationA -> AllocationC
    AllocationA -> AllocationY
    constX -> AllocationX -> AllocationY
    
    constA [label="const A: &[&u32] = &[&5, &6, X];
allocations: [A, B, C, Y]"]
    constX [label="const X: &u32 = &99;
allocations: [X, Y]"]
    
    AllocationX [label = "X
[1]"]
    AllocationY [label = "Y
[]"]
    AllocationA [label = "A
[1, 2, 3]"]
    AllocationB [label = "B
[]"]
    AllocationC [label = "C
[]"]
}
```

</details>

We can probably find a solution for the above graph, but the one below is problematic. We'd need to duplicate the entire allocation. The allocation might be a huge constant though.

![grafik](https://user-images.githubusercontent.com/332036/49301490-01c19a80-f4c5-11e8-8ee9-13272f6693aa.png)
<details>
<summary>Click here for graphviz code of this graph</summary>

```dot
digraph G {
    node [shape=box, nojustify=true]
    constA -> AllocationA -> AllocationB
    AllocationA -> AllocationC
    AllocationA -> AllocationY
    AllocationC -> AllocationD
    AllocationB -> AllocationE
    AllocationY -> AllocationZ
    constX -> AllocationX -> AllocationY
    
    constA [label="const A: &[&&u32] = &[&&5, &&6, X];
allocations: [A, B, C, D, E, Y, Z]"]
    constX [label="const X: &u32 = &99;
allocations: [X, Y, Z]"]
    
    AllocationX [label = "X\n[1]"]
    AllocationY [label = "Y\n[?? 6 or 2 ??]"]
    AllocationA [label = "A\n[1, 2, 5]"]
    AllocationB [label = "B\n[4]"]
    AllocationC [label = "C\n[3]"]
    AllocationZ [label = "Z\n[]"]
    AllocationE [label = "E\n[]"]
    AllocationD [label = "D\n[]"]
}
```

</details>

Of course we can move to fully refering to the other constant in order to get a its memory. I initially thought that such a scheme would require all our const eval pointers to contain a `DefId`, `Substs`, `ParamEnv` and an optional promoted index (which are the four components in a `GlobalId` required for fully identifying a constant, statics just need a `DefId` as long as they stay nongeneric). That's a serious increase in size (from `u64` currently).

![grafik](https://user-images.githubusercontent.com/332036/49305184-d93e9e00-f4ce-11e8-81e1-b6a919e72dd2.png)
<details>
<summary>Click here for graphviz code of this graph</summary>

```dot
digraph G {
    node [shape=box, nojustify=true]
    constA -> AllocationA -> AllocationB
    AllocationA -> AllocationC
    AllocationA -> AllocationY
    AllocationC -> AllocationD
    AllocationB -> AllocationE
    AllocationY -> AllocationZ
    constX -> AllocationX -> AllocationY
    
    constA [label="const A: &[&&u32] = &[&&5, &&6, X];
allocations: [A, B, C, D, E]"]
    constX [label="const X: &u32 = &99;
allocations: [X, Y, Z]"]
    
    AllocationX [label = "X\n[1]"]
    AllocationY [label = "Y\n[2]"]
    AllocationA [label = "A\n[1, 2, X[1]]"]
    AllocationB [label = "B\n[4]"]
    AllocationC [label = "C\n[3]"]
    AllocationZ [label = "Z\n[]"]
    AllocationE [label = "E\n[]"]
    AllocationD [label = "D\n[]"]
}
```

</details>

But we can store these `GlobalId`s in the `ty::Const` value and just refer to them via an index:

![grafik](https://user-images.githubusercontent.com/332036/49305680-325b0180-f4d0-11e8-95d9-9c6613fc3a2a.png)
<details>
<summary>Click here for graphviz code of this graph</summary>

```dot
digraph G {
    node [shape=box, nojustify=true]
    constA -> AllocationA -> AllocationB
    AllocationA -> AllocationC
    AllocationA -> AllocationY
    AllocationC -> AllocationD
    AllocationB -> AllocationE
    AllocationY -> AllocationZ
    constX -> AllocationX -> AllocationY
    
    constA [label="const A: &[&&u32] = &[&&5, &&6, X];
allocations: [A, B, C, D, E, X[1]]"]
    constX [label="const X: &u32 = &99;
allocations: [X, Y, Z]"]
    
    AllocationX [label = "X\n[1]"]
    AllocationY [label = "Y\n[2]"]
    AllocationA [label = "A\n[1, 2, 5]"]
    AllocationB [label = "B\n[4]"]
    AllocationC [label = "C\n[3]"]
    AllocationZ [label = "Z\n[]"]
    AllocationE [label = "E\n[]"]
    AllocationD [label = "D\n[]"]
}
```

</details>

So... Anyone wants to poke holes into the last scheme? @Zoxc @eddyb @RalfJung

**Comment by eddyb** [comment]
I'm guessing interning `Allocation`s just before `const_eval` returns isn't an option?

As for encoding things using indices, it sounds a lot like some sort of "de Bruijn" scheme and/or substitution, cc @nikomatsakis

**Comment by oli-obk** [comment]
We could of course move to some sort of `Arc`/`Weak`-scheme instead of doing all these interning dances. That could actually work out nicely.

**Comment by eddyb** [comment]
> I'm assuming you ask whether we could just place `&'tcx Allocation`s inside AllocIds?

No, interning would mean you turn a `Allocation` into an `AllocId` you can later get a `&'tcx Allocation` from.

To handle cycles I'm guessing you'd need to handle an "allocation group" and allocate all of the `AllocId`s and `&'tcx Allocation`s at once? I guess maybe similar to what we do today, but without explicit mutation outside of the implementation.

**Comment by oli-obk** [comment]
> No, interning would mean you turn a Allocation into an AllocId you can later get a &'tcx Allocation from.

That's what we are doing right now. But that means we do have this global `FxHashMap<AllocId, &'tcx Allocation>` in `TyCtxt` that we need to update and query for allocations. It's independent of the query system, even though the `AllocId`s are not.

**Comment by RalfJung** [comment]
> But we can store these GlobalIds in the ty::Const value and just refer to them via an index:

How is that index different from the `AllocId` we are using currently? From what I can see, you have gone full-circle here. ;)

The issue is that we have to represent a cyclic graph.  We can either try to do this with references -- with shared references and an arena (which is our case here), that is hard but not impossible.  We'd have to *first* intern everything without relocations, and *then* add all the relocations.

Or, if we think that is too complicated (or if we are worried a cyclic reference graph will cause too much "fun" elsewhere, like during hashing), we need an indirection through an ID.  Currently, we use `AllocId` for that purpose.  Why do you think it is beneficial to introduce another kind of ID for this, given that we will still *also* need a per-execution `AllocId`? Having two kinds of IDs here sounds just awfully confusing for no benefit.

**Comment by oli-obk** [comment]
So... the root motivation was `AllocId` encoding/decoding to/from metadata. Right now it's a rather complicated process, because we try to do it right from the first run. This means cyclic `Allocation`s require knowing the id of the allocation being deserialized before deserializing the `Allocation`.

Const eval has a similar problem, and also obtains global ids for every allocation, even ones that won't make it into the final constant.

In order to achieve this, we don't just need global state, we need global mutable state. While it's hard to mess up (loads of assertions that would trigger), it's worrysome.

> How is that index different from the AllocId we are using currently?

The index is different in it being allocation-local unique, not globally unique. We can just deserialize it with the default generated deserializer instead of the handcrafted one we have now.

We can still get there by using crate-unique `AllocId`s and evaluation-context-unique `AllocId`s and doing a transformation of the datastructures before interning them into the global id-space.

**Comment by RalfJung** [comment]
We inherently *have* global mutable state: The graph of allocations that make up all the constants. It's monotonic state though, in the sense that the graph only grows, so it's not too bad -- in some sense it isn't really mutable, because all references always remain valid and nothing you ever saw changes.

> The index is different in it being allocation-local unique

How does it refer to other allocations then?

Okay so I think you are saying that these indices are just a local optimization and can be ignored for the high-level picture. The high-level picture, then, is to use an already existing "kind of ID" to represent the edges in this cyclic graph, namely `GlobalId`.  You are saying `GlobalId` is sufficient to identify any *constant*/*static*, but we are talking here about identifying *allocations*. Is there a `GlobalId` for the inner allocation in `const FOO: &'static usize = &13`? Imagine CTFE can do `Box::new`, which `GlobalId` refers to the allocation that backs that `Box`?

> We can still get there by using crate-unique AllocIds and evaluation-context-unique AllocIds and doing a transformation of the datastructures before interning them into the global id-space.

Come again? I agree that all of these are English words, but I have no idea what you are saying. :D Why are crate boundaries suddenly relevant? If anything I'd have expected a partition by miri engine instance.

**Comment by oli-obk** [comment]
> Is there a GlobalId for the inner allocation in const FOO: &'static usize = &13? Imagine CTFE can do Box::new, which GlobalId refers to the allocation that backs that Box?

You'd use the GlobalId to get a `ty::Const`, which contains an array of the allocations that make up said constant. Then you'd use the index to index into that array.

> Come again? I agree that all of these are English words, but I have no idea what you are saying. :D Why are crate boundaries suddenly relevant? If anything I'd have expected a partition by miri engine instance.

It's still named [`EvalContext`](https://github.com/rust-lang/rust/blob/9cd3bef4cfaaac2a608682d4b0834cda344249e0/src/librustc_mir/interpret/eval_context.rs#L38).

Yes I do mean every miri engine instance to have its own set of ids, and every crate's serialized metadata also its own set of ids.

When interning the result of a constant evaluation, we'd replace all ids with global ids while interning the allocations.

When decoding an `AllocId` from metadata, we'd decode the allocation graph necessary for it and then intern the allocations.

Interning of allocations would be an "atomic" operation inside the `TyCtxt`, which updates all the `AllocId`s to point to an interned version.

We just need to ensure that we don't end up with `FOO` and `BAR` pointing to the same allocation after codegen:

```rust
static mut FOO: &'static mut u32 = &mut 42;
static mut BAR: &'static mut u32 = &mut 42;
```

**Comment by RalfJung** [comment]
> You'd use the GlobalId to get a ty::Const, which contains an array of the allocations that make up said constant. Then you'd use the index to index into that array.

I thought that array is just an optimization to avoid repeating long identifiers (`GlobalId`) everywhere. So let's ignore that, because I'm not even getting the high-level picture yet.

What is the `GlobalId` for the inner allocation in `const FOO: Box<i32> = Box::new(0)`?

**Comment by oli-obk** [comment]
It's just the `GlobalId` of `FOO`. You really do need the extra index to choose the "constant-local" allocation.

**Comment by RalfJung** [comment]
> I think this entire conversation has become moot. I'm explaining a scheme that I came up with but have since been convinced is not beneficial to global interning.

Okay.^^

> So we should just clean up global interning (which I haven't done so far because I thought it was just an intermediate situation to be replaced).

I think using references would be nice, but I guess reference cycles could cause trouble in too many places.

> What we still can do is have miri-engine-local ids and metadata-local ids that get converted to global ids after evaluation/decoding.

So we have three ID namespaces? What is the point of that?

I briefly thought two namespaces would be nice, so that we can tell from an `AllocId` whether it is global-tcx-memory or miri-engine-memory, but that doesn't work if you consider mutable statics (that need to be copied into the miri engine when mutated).  The way I see it, global-tcx-memory is an optimization so that we don't have to recompute the same stuff over and over again.  Instead we just compute the allocation's content once and then reuse it.  Some `AllocId` get cached, so to speak, but that is transparent to most of miri.  To make that work, we need coherent `AllocId` across executions.  However, which `AllocId` are cached can change over time (re: mutable statics), and hence we cannot encode this information in the ID itself.

**Comment by oli-obk** [comment]
> I think using references would be nice, but I guess reference cycles could cause trouble in too many places.

I don't mean using references. I just mean cleaning up things in the existing scheme without changing it.

>  but that doesn't work if you consider mutable statics (that need to be copied into the miri engine when mutated)

We can just overwrite the `const_eval` query in miri and do some trickery to not even have to do that. The miri-engine doesn't need to know about mutable static uplifting.

Or we immediately copy mutable statics on access instead of at first mutation.

We would need a local-id -> global id mapping scheme anyway, which we already support (The `Id` generic parameter is almost everywhere, it would be possible to extend it to the entire engine). Then the engine can encode such things in the `AllocId` directly. If an `AllocId` is in the local table we never even look at the global table, so the mutable static trick would still work by simply copying all relevant allocations into the local `Memory`.

> The way I see it, global-tcx-memory is an optimization so that we don't have to recompute the same stuff over and over again. Instead we just compute the allocation's content once and then reuse it

We'd never recompute the content. We'd only do a single interning of the final `Allocation`-graph of a constant which replaces all `AllocId`s with global ones.

**Comment by RalfJung** [comment]
> I don't mean using references. 

Sorry for not being clear. I understand you want to keep IDs, I just said I'd consider using references quite neat :D

> Or we immediately copy mutable statics on access instead of at first mutation.

It would have to be copied the first time a *reference* is created. Basically, for stand-alone miri, we should only ever have local IDs (we anyway cannot directly use `tcx` allocations because they have a different pointer tag).  For CTFE, we can have an enum so it's either local or global.

I am not convinced that would actually simplify anything, though.  It means a more complicated type for `AllocId`, another type parameter to push through everything, and having to rewrite IDs during interning.  That's quite some cost.  What is the benefit?

> We'd never recompute the content.

I was talking about a hypothetical scenario without any shared global state, where a constant referencing another constant just recomputes that constant. Just ignore what I said.^^
