### ISSUE TITLE
Libraries required for Firefox

### ISSUE THREAD

**Issue by DibyaTheXPFan** [rust-lang/rust#56400]
Which are the rust libraries required for Firefox?

**Comment by Centril** [comment]
cc @SimonSapin

**Comment by SimonSapin** [comment]
Closing, since this is not an issue for the Rust project.

For running a Firefox build that you downloaded, you should not need to care about Rust at all.

For building Firefox yourself from source code, see documentation at https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions. You’re going to need rustc and Cargo (I recommend installing them through rustup: https://rustup.rs/). The Rust libraries used in Firefox are vendored in the repository, so you don’t need to obtain them separately. You can see them here: https://searchfox.org/mozilla-central/source/third_party/rust
