### ISSUE TITLE
Investigate impact of removing shell32 dependency of libstd on Windows

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#56510]
An [excellent blog post recently](https://randomascii.wordpress.com/2018/12/03/a-not-called-function-can-cause-a-5x-slowdown/) showed that removing the gdi32.dll dependency from LLVM speed up its test suite by a huge amount. For us libstd doesn't depend on gdi32.dll directly but it does depend on shell32.dll which depends on gdi32.dll (according to the blog post). Specificaly it looks like `CommandLineToArgvW`, the same function as LLVM, is used by us! 

It'd be great to investigate removing the shell32 dependency from libstd (may be a few other functions here and there). We should run some tests on Windows to see if this improves rustc cycle times!

**Comment by retep998** [comment]
Based on my limited investigation, it's likely that replacing `CommandLineToArgvW` with a pure Rust equivalent should be good enough to get rid of the gdi32 dependency in things that only use libstd. So really someone just needs to write that pure Rust implementation which should be easy to do.

**Comment by retep998** [comment]
So now that the change has been implemented, have we actually investigated how much of an impact the change made?

**Comment by Eh2406** [comment]
Perf, an lolbench are both linux only. So nether help with this question. So don't waste your time like I did.

**Comment by Zoxc** [comment]
Here are just number for `run-pass` on 8 cores / 16 threads on Windows 10 v1809:

Without the `shell32` dependency:
333.012 325.587 320.650

With `shell32`:
310.852 319.165 323.645

**Comment by Mark-Simulacrum** [comment]
For what it's worth, though there's no good way to differentiate PR-to-PR due to very high variance, it does look like there was a recent regression in PR build times:

﻿﻿﻿
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/5047365/50262391-52465c80-03ce-11e9-8b17-b8ec14f589b5.png">

**Comment by Zoxc** [comment]
I see that the CPU usage averages about 40% when running `run-pass`, so maybe we'd see some real improvements if we got rid of `shell32.dll` in the compiler too. Something is certainly holding things back.

**Comment by Zoxc** [comment]
Yeah, I saw that the compiler doesn't load `gdi32.dll`. So there's probably some other reason why `compiletest` doesn't load all the cores.

**Comment by briansmith** [comment]
According to https://news.ycombinator.com/item?id=18604194 the performance issue is fixed in Windows itself in the latest (or upcoming) Windows release. However, there is at least one other non-performance reason to prefer this change: https://github.com/rust-lang/rust/pull/56568#issuecomment-466247750.
