### ISSUE TITLE
search-index.js slows down documentation browsing

### ISSUE THREAD

**Issue by yacoob** [rust-lang/rust#56545]
I'm just starting with Rust, so I'm using its documentation quite often. Primarily along the lines of "hmm, no idea if a thing like foo exists in stdlib... let's search the docs.". This means, I'm changing pages of documentation a lot. I've noticed that when I'm jumping to a specific method's docs, I get the following experience:

* page loads entirely (judging by the side scrollbar)
* load indicator keeps spinning
* after couple of seconds, browser jumps down to method description

I've looked at Chrome's console, and I've noticed that `search-index.js` is the culprit.

<img width="1704" alt="screen shot 2018-12-05 at 19 34 08" src="https://user-images.githubusercontent.com/190463/49539422-877a8700-f8c5-11e8-845a-d489b9bb9b05.PNG">

Note that the above is loading from a `file://` URI, after launching `rustup doc`. That index is 2MB, and it looks like it contains all keywords for the search. Not sure why it's equally slow on both online and local docs.

Any chance of improvement here, to speed up the initial load? Loading the index asynchronously, to have it ready for user search once user decides to use it?

**Comment by GuillaumeGomez** [comment]
Funny enough: chrome is very slow to render Rust documentation (give a try to firefox if you want it to be faster). However, some PRs should greatly improve this situation (like #56005). Before then, we can't help you much on this...

**Comment by yacoob** [comment]
No worries, I'm happy to wait. Let's see how much better will it get once the improvements are in. I'll leave this one open for the time being so other people who wonder about this have a reference point.

Thanks!

**Comment by tyehle** [comment]
This is a pretty serious issue for me. I've been trying to browse the documentation for the [atsamd-rs crate](https://atsamd-rs.github.io/atsamd/atsamd21g18a/feather_m0/index.html) and the `search-index.js` file is so large it has been crashing chrome and firefox. The only way to get the page to load reliably is by disabling js. Even when the page works "properly" it takes around 6 seconds to load, and when I checked the performance logs most of that time is spent compiling and executing `search-index.js` which makes some sense because it is ~2MB. Is there some way to reduce the size of this file? It seems like it is super large because its including information about all the dependent crates.

**Comment by GuillaumeGomez** [comment]
I had the same issue when opening the page... Any idea to reduce the size of this file is very welcome. I opened #71144 recently but not sure we'll go forward with it considering it'd reduce the search usefulness. An idea I had was to rely on wasm. I need to investigate it too.

**Comment by ollie27** [comment]
It might help to convert `search-index.js` into a plain JSON file. I'm pretty sure that `JSON.parse` is significantly faster than trying to compile and execute JavaScript code.

**Comment by GuillaumeGomez** [comment]
I think it's worth a try. I'll test it tomorrow.

**Comment by euclio** [comment]
@GuillaumeGomez Sounds like this can be closed with the switch to JSON?

**Comment by GuillaumeGomez** [comment]
Absolutely!
