### ISSUE TITLE
Ipv4Addr::is_broadcast() doesn't cover all broadcast methods

### ISSUE THREAD

**Issue by povilasb** [rust-lang/rust#56646]
`Ipv4Addr::is_broadcast()`  returns true only for `255.255.255.255` address. But, if we take a look at https://tools.ietf.org/html/rfc919 page 6:
```

   The address 255.255.255.255 denotes a broadcast on a local hardware
   network, which must not be forwarded.  This address may be used, for
   example, by hosts that do not know their network number and are
   asking some server for it.

   Thus, a host on net 36, for example, may:

      - broadcast to all of its immediate neighbors by using
        255.255.255.255

      - broadcast to all of net 36 by using 36.255.255.255
```
It's obvious that network specific broadcast addresses are possible as well, e.g., `36.255.255.255`.
Say on my Debian system, `ip address` prints:
```
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether e0:94:67:0a:aa:f0 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.210/24 brd 192.168.1.255 scope global dynamic wlan0
       valid_lft 26538sec preferred_lft 26538sec
    inet6 fe80::bc49:2dc4:5827:fd86/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:41:bb:92:62 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```
Where it shows at least 2 other broadcast address examples: `192.168.1.255` and `172.17.255.255`.

Would you guys be interested in a PR for this? Given I'm not misinterpreting the data :)

**Comment by the8472** [comment]
The `Ipv4Addr::is_*` functions only check for fixed addresses, this is fairly cheap.

Checking based on the current interface configuration would be slow since it has to do several syscalls to enumerate network interfaces which can by very slow on systems with hundreds of addresses. And the results could change over time.
An additional complication which would make this ambiguous is the possibility of having overlapping subnets. What is a broadcast address on one network interface may be normal host address on another.

I think it would be better to update the documentation instead to mention that it only checks for the *limited broadcast address* as it's called in [rfc8190](https://tools.ietf.org/html/rfc8190#section-2.2).

**Comment by povilasb** [comment]
Thank you, that totally makes sense. I got confused that I'm able to extract the subnet from IP address itself, which is not true. So I'm closing this issue.
