### ISSUE TITLE
Potential stable point release tools issues

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#56726]
* [Fix for common infinte loop regression](https://github.com/rust-lang/rls/pull/1170)
* [Can't jump to std defs](https://github.com/rust-lang/rls/issues/1171)

The first is probably not worth making a point release just for that. The second is probably worth a point release, but doesn't have a fix yet. @Xanewok is investigating.

The other major tools issues are with rustup which won't need a point release.

cc @rust-lang/release

**Comment by Xanewok** [comment]
Just the go-to def fix is at https://github.com/Xanewok/rust/commits/1.31-stable-gotodef (one commit ahead of current rust/stable branch), confirmed locally that it works. (RLS is checked out with a branch that points to patched rls-analysis: https://github.com/rust-dev-tools/rls-analysis/tree/1.31-stable-src-prefix-fix)

**Comment by Xanewok** [comment]
This pulls a specific commit from [rust-dev-tools/rls-analysis](https://github.com/rust-dev-tools/rls-analysis) as opposed to the one from crates.io (https://github.com/Xanewok/rust/commit/c3277aff22bb03c35ec500076310c1efdb8f0664#diff-5d9bf57935c52008319cccc88d4d737dR1813). Will that be a problem?

**Comment by pietroalbini** [comment]
cc @rust-lang/dev-tools, should this be `stable-accepted`?

Also, I'm not too familiar with RLS, what would be the steps to backport the changes to stable?

**Comment by Xanewok** [comment]
For the 2nd point (go to definition) we'd have to merge https://github.com/Xanewok/rust/commit/c3277aff22bb03c35ec500076310c1efdb8f0664 (updates `rls-analysis` to branched version in Rust lockfile and checks out *branched* RLS using the patched `rls-analysis`).
The other approach would be to `[patch]` Cargo.toml to use the patched rls-analysis version and update it in Cargo.toml, although iirc @nrc was against that.

I think I'm confused as to what exactly version is on stable due to edition (do stable and beta point to the same release with nightly being only couple of days younger now?), so I'm not exactly sure what and how we should backport changes also including the fix for hover infinite loop regression.

**Comment by nrc** [comment]
I've published the rls-analysis branch as `0.16.10-stable`. I created the RLS branch stable-update-1.31.7. I have a PR for Rust in progress, but didn't quite finish it up tonight.

Thanks @Xanewok for doing all the real work!

**Comment by pietroalbini** [comment]
Also cherry-picked https://github.com/rust-lang/rls/pull/1170 inside the `stable-update-1.31.7` branch.

**Comment by pietroalbini** [comment]
Uh, are those issues fixed on beta?

**Comment by Xanewok** [comment]
It doesn't seem like it;

https://github.com/rust-lang/rls/commit/77ff073fe83985aecd997db66e46007ee228cd2d is the last commit on beta, while the infinite hover fix (https://github.com/rust-lang/rls/commit/bfa1371f5cceacebe307d9ee70760296eb0ec489) is just one PR further. In this case, could we just bump RLS a few commits ahead on beta channel?

However I *think* goto-def should work, since I believe the `src/` path change actually got into beta in time. I'll check the `beta` channel if this problem persists.

**Comment by nrc** [comment]
> Uh, are those issues fixed on beta?

Ah, curses I was planning on updating beta to most recent RLS at some point before the uplift, but just uplifting that fix is fine too. Thanks for doing it @Xanewok !
