### ISSUE TITLE
Commit ed6c7b751dd4 causes test failures in debuginfo suite on Debian Stable

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rust#56730]
Hi,

I have been trying to get the rust compiler tests running on my Debian/stable (Stretch) computer and was hitting continuous failure running the debuginfo suite, specifically the pretty-std-collections test.  I kept hitting gdb complaining with `Python Exception <class 'gdb.error'> No type named alloc::collections::btree::node::InternalNode<i32, ()>.` and similar.

Looking at the gdb pretty printer python integration, I decided to try reverting the commit mentioned in the title and now the tests pass just fine.

I'm sadly not well enough versed in gdb/python bindings to begin to debug this, but would be pleased to be remote-hands to help someone else work it out.

**Comment by nikic** [comment]
The corresponding PR is #56144, cc @tromey.

**Comment by tromey** [comment]
Reverting the commit isn't really an option as the previous code was incorrect.  Rewriting it in a different way is hard because `BTreeSet` and `BTreeMap` hide the real types of nodes.

What version of gdb are you using?  `gdb --version` will say.  I can build that locally and try it out.  Perhaps some workaround can be found.

Failing a workaround, I think the only recourse will be to disable the test, and probably that pretty-printer, on whatever gdb releases show the problem.

**Comment by kinnison** [comment]
I guessed that a revert wasn't the *right* answer, sure :-)  It just got me to a point of being able to run the rest of the test suite so I could play with another issue.

GDB is version `GNU gdb (Debian 7.12-6) 7.12.0.20161007-git`

It is the version packaged in Debian's Stretch (Stable) distribution.

**Comment by tromey** [comment]
> I guessed that a revert wasn't the right answer, sure :-)

Sorry about that, I didn't mean to imply anything.

I've built 7.12 and I can reproduce the problem.

**Comment by tromey** [comment]
I think this was this gdb bug: https://sourceware.org/bugzilla/show_bug.cgi?id=21763.  I fixed it in 8.1.  There isn't a workaround so I'll be disabling the test.

**Comment by kinnison** [comment]
Fair enough :-) Thanks for looking into this.
