### ISSUE TITLE
x86_64 simd fmadd (and other) bug (release only)

### ISSUE THREAD

**Issue by kali** [rust-lang/rust#56950]
This bit of code falls in the assert in Release, while working in Debug.

Both stable and nightly.

https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=6f280db2aaf8241e46a080f4189e0328

```rust
use std::arch::x86_64::*;

fn main() {
        unsafe {
            let a = [2.0f32, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];
            let b = -1.0f32;

            let ar = _mm256_loadu_ps(a.as_ptr());
            println!("ar: {:?}", ar);
            let br = _mm256_set1_ps(b);
            println!("br: {:?}", br);
            let mut abr = _mm256_setzero_ps();
            println!("ab: {:?}", abr);
            abr = _mm256_fmadd_ps(ar, br, abr);
            println!("ab: {:?}", abr);
            
            let mut ab = [0.0; 8];
            _mm256_storeu_ps(ab.as_mut_ptr(), abr);
            assert_eq!(ab[0], -2.0f32);
    }
}
```

**Comment by kali** [comment]
might be related to https://github.com/rust-lang/rust/issues/50154

**Comment by kali** [comment]
Problem was discovered on a skylake mac, if it helps.

**Comment by peterjoel** [comment]
Perhaps not discovered sooner because the function isn't being used much. I found it in two Github repositories:

 * [https://github.com/jackmott/simdeez](https://github.com/jackmott/simdeez/blob/6b3d00212af00eeab90b9cb1bc2494245efdcf71/src/avx2.rs#L267)
 * [https://github.com/bluss/matrixmultiply](https://github.com/bluss/matrixmultiply/blob/174971909dbe7e28931daaeaed54f100d8a3067b/src/x86/mod.rs#L30)

**Comment by kali** [comment]
Problem also occurs with simple multiplication.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=affc00bf05919f648a5c4b3e1e053070

**Comment by lqd** [comment]
Yeah, it doesn't look like the problem lies with the functions themselves, like this [simple 2.0 * 1.0 multiplication](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=772bfe8d1d72f0da25696dfcdfa9211a) shows. 

So it could indeed be an instance of the linked LLVM by-ref args promotion issue ?

**Comment by BurntSushi** [comment]
What is the expected behavior here? From what I can tell, the given code isn't correct because you aren't using `#[target_feature(enable = "avx2")]`. (Alternatively, compile with `RUSTFLAGS="-C target-feature=+avx2"`.)

I think you'll want to have a careful review of https://doc.rust-lang.org/std/arch/index.html#overview and https://doc.rust-lang.org/std/arch/index.html#dynamic-cpu-feature-detection

**Comment by hellow554** [comment]
@BurntPizza  why avx2? According to the [doc](https://doc.rust-lang.org/core/arch/x86_64/fn._mm256_setzero_ps.html) it only requires "avx"

**Comment by BurntSushi** [comment]
@hellow554 I didn't check the precise requirements of each individual vendor intrinsic, and I don't have them memorized. :-) Feel free to `s/avx2/avx`, but I don't think my general point changes.

**Comment by lqd** [comment]
`#[target_feature(enable = "avx")]` works indeed.

**Comment by kali** [comment]
all right... going back to hiding, thanks folks :)
