### ISSUE TITLE
Add support for MIPS64 (Big and Little endians) for musl

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#57134]
So mips and mipsel are exist for musl. Why we don't have support for 64 bit mips?

**Comment by workingjubilee** [comment]
Hello.

We have codified our approach to [platform support](https://doc.rust-lang.org/nightly/rustc/platform-support.html), and adding new targets should probably be pursued as a [T-compiler Major Change Proposal](https://forge.rust-lang.org/compiler/mcp.html). As this issue was opened by a user who is now gone, and the most appropriate venue is now codified as another one, not opening an issue against rust-lang/rust, I am closing this issue. This is in no way a decision against adding these targets if the relevant community expresses interest and the appropriate MCP is opened.
