### ISSUE TITLE
AAPCS ABI is accepted for x86 target

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#57182]
Currently the following code compiles fine when targetting x86_64.

```rust
pub extern "aapcs" fn  foo() {}
```

This code is non-sensical because AAPCS calling convention is only defined for ARM. An example of non-sensical ABI being disallowed is

```rust
pub extern "fastcall" fn  foo() {}
```

when compiling with `--target=armv7-unknown-linux-gnueabihf` which fails with:

```
error[E0570]: The ABI `"fastcall"` is not supported for the current target
 --> <source>:6:1
  |
6 | / extern "fastcall" fn foo() { 
7 | | }
  | |_^
```

Targets should be reviewed for such nonsensical ABIs and their blacklists updated. I feel that to avoid this issue in the future we should rather prefer a *whitelist* of ABIs, rather than a blacklist, and by default put no ABIs, so that the compilation fails until the ABI list is properly populated for the target.

**Comment by nagisa** [comment]
Compiling `extern "aapcs"` on aarch64 will explode in LLVM with `LLVM ERROR: Unsupported calling convention.`.

**Comment by gnzlbg** [comment]
I ran into these same issues in https://github.com/rust-lang/rust/issues/65443 . 

One thing that I mentioned there, that is not mentioned here, is that because these errors can happen on stable safe Rust code, this is actually a soundness bug (safe Rust code has UB). 

>  I feel that to avoid this issue in the future we should rather prefer a whitelist of ABIs, rather than a blacklist, and by default put no ABIs, so that the compilation fails until the ABI list is properly populated for the target.

I agree. There are some ABIs that the reference says are available on all targets (e.g. `"C"`, `"system"`, `"Rust"`, etc.) but except for those, each target should have a white-list that explicitly allows using an ABI on the target.
