### ISSUE TITLE
CI doesn't catch total tools breakage

### ISSUE THREAD

**Issue by o01eg** [rust-lang/rust#57398]
PR https://github.com/rust-lang/rust/pull/57101 introduced changes cause all tools to fail tests.

Should CI have test for common tools usages such as searching and loading codegen dynamic libraries and searching std rust libraries?

**Comment by ehuss** [comment]
I'm going to close this as I don't think there is anything particularly actionable here.

When #57101 landed, the other tools were already in the "broken" state.  There would be no way to check for the failure when they were already failing.  Also, it did detect that `miri` failed.

Nowadays, clippy is in-tree and its tests are now required to pass, so that should detect this particular problem.  RLS will eventually go away, so that just leaves miri as a potentially breakable tool, and that is handled differently (nightly only, has a cron job, etc.)
