### ISSUE TITLE
some const_int_foo features were entirely removed

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#57562]
As part of the `const` project moving things into stable, some of the associated sub-features were recently removed entirely rather than being left in with a warning about them being old, which causes previously working code to now error out ([example build log](https://ci.appveyor.com/project/Lokathor/randomize-rs/builds/21578845/job/i990fo22oc1js862)). Of course it's nightly and all, but it'd be better if they could be warnings instead of errors.

**Comment by Centril** [comment]
I would personally prefer to simply warn on unknown features rather than introduce `#[rustc_const_stable(...)]` since that will need to be used a lot and thus will substantial add technical debt to the standard library.

While retaining `#[stable(..)]` is useful for the purposes of rustdoc documentation the same cannot be said for `#[rustc_const_stable(...)]` since it isn't shown... that is, unless we actually show it in rustdoc (which might be too much information to fit and show visually).

cc @QuietMisdreavus

**Comment by QuietMisdreavus** [comment]
It's possible to add a "const stability" banner like the regular stability banner and make rustdoc look it up based on that attribute. @rust-lang/rustdoc

**Comment by doctorn** [comment]
Hello! I'd be interested in working on this if nobody else already is

**Comment by Centril** [comment]
@doctorn Don't think anyone is working on this... The main issue seems to be that we haven't settled how we want to approach this since me and @varkor have a disagreement... and the rustdoc team hasn't weighed in except for @QuietMisdreavus ;)

**Comment by sjakobi** [comment]
> The main issue seems to be that we haven't settled how we want to approach this since me and @varkor have a disagreement... and the rustdoc team hasn't weighed in except for @QuietMisdreavus ;)

May I suggest that the `E-mentor` and `E-medium` labels be removed until the approach has been settled?

**Comment by Mark-Simulacrum** [comment]
I suspect it likely doesn't matter too much at this point -- this is a pretty old issue, and I think we should const stability these days. So I'm going to go ahead and just close.
