### ISSUE TITLE
Build failed due to Python27\lib\subprocess.py

### ISSUE THREAD

**Issue by shangchihh** [rust-lang/rust#57594]
I am trying to build Rust from source on Windows, but meet an error:

![image](https://user-images.githubusercontent.com/43683886/51110498-db1cb080-1833-11e9-935d-b28687f56dd0.png)

Who could help me to solve this? Thanks.

**Comment by shangchihh** [comment]
> what happens if you set env. var `RUST_LOG=info` and rerun?

@xftroxgpx Same error messages output.

**Comment by xftroxgpx** [comment]
try `./x.py build -vv` ?

**Comment by shangchihh** [comment]
> try `./x.py build -vv` ?

@xftroxgpx 
![image](https://user-images.githubusercontent.com/43683886/51113273-6ef27a80-183c-11e9-81af-007c61e08cff.png)

**Comment by xftroxgpx** [comment]
WindowsError 5 is access denied, just not sure exactly what it refers to... especially since you seem to be running with full admin privileges(I guess?).

Try editing file `F:\dev\rust\src\bootstrap\bootstrap.py` at line 136, change it from:
`ret = subprocess.Popen(args, **kwargs)`
to:
`ret = subprocess.Popen(args, **kwargs, shell=True)`
Then rerun the `./x.py build -vv` command.

Credit for this workaround: https://github.com/NVIDIA/DIGITS/issues/1095#issuecomment-249810772
Hopefully it works.

**Comment by retep998** [comment]
Do you get the same error if you try to build Rust in powershell instead of git bash/msys2?

**Comment by shangchihh** [comment]
@xftroxgpx `ret = subprocess.Popen(args, **kwargs, shell=True)` has a syntax error.

**Comment by shangchihh** [comment]
@retep998 Yes, the same error in PowerShell.

**Comment by mati865** [comment]
@shangchihh it's probably AV software not permitting to create another process.
What is your python version BTW?
