### ISSUE TITLE
Nested `?` matchers can cause the compiler to infinite loop/crash

### ISSUE THREAD

**Issue by alercah** [rust-lang/rust#57597]
The following code will cause the compiler to fail:

```rust
macro_rules! ex {
    ($($(i:ident)?)+) => { };
}

fn main() {
    ex!();
}
```

Playground link: https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=acce7614d74028b67c92a79b50b93522

It should error that the inner matcher can match an empty string and reject it, just as it does if `*` is used in place of `?`.

**Comment by jonas-schievink** [comment]
The fix should be very easy, since this was already fixed for `*` repetitions in https://github.com/rust-lang/rust/pull/36721 (original bug: https://github.com/rust-lang/rust/issues/5067):

https://github.com/rust-lang/rust/blob/1a3a3dfcdd7faf0b8ab266a79a4a35ab30e5136a/src/libsyntax/ext/tt/macro_rules.rs#L435-L440

Looks like `sub_seq.op` just needs to be checked against `?`, too.

**Comment by Centril** [comment]
cc @mark-i-m

**Comment by alercah** [comment]
Note that with `?` on the outside, this errors properly, although with inconsistent error messages: if the inner repetition uses `*` only, the error is "repetition matches empty token tree", but it seems that if any of the repetitions are `?`, then the error is "multiple successful parses".

**Comment by mark-i-m** [comment]
I've opened  #57610
