### ISSUE TITLE
Handle missing closing brackets in turbofish

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#57819]
Like https://github.com/rust-lang/rust/pull/57817 handles [too many closing brackets](https://github.com/rust-lang/rust/issues/54521) in type arguments when using turbofish, we should also handle too _few_ closing brackets correctly with an appropriate suggestion (and proper item generation):

```
fn main() {
    println!("{:?}", vec![1, 2, 3].into_iter().collect::<Vec<usize>());
}
```

**Comment by abonander** [comment]
@estebank looks like you got your link syntax turned around

**Comment by davidtwco** [comment]
I've submitted #57852 for this. It takes the opposite approach to that suggested here, instead of suggesting that extra `>` characters are added at the end (and making redundant pairs of angle brackets legal), it suggests that unmatched leading `<` characters are removed. 

I think if suggestions are applied with this approach that it ends up with a cleaner result (at the expense of implementation complexity). Happy to scrap that and take the approach suggested here instead if preferred.
