### ISSUE TITLE
Crater runs for Rust 1.33

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#57877]
cc @rust-lang/release

**Comment by pietroalbini** [comment]
@craterbot run name=beta-1.33-1 start=1.32.0 end=beta-2019-01-22 cap-lints=warn p=10
@craterbot run name=beta-1.33-2 start=1.32.0 end=beta-2019-01-22 mode=rustdoc p=5

**Comment by pietroalbini** [comment]
@craterbot run name=beta-1.33-2 start=1.32.0 end=beta-2019-01-22 mode=rustdoc p=5

**Comment by Mark-Simulacrum** [comment]
Triage for normal and rustdoc crater completed. Filed https://github.com/rust-lang/rust/issues/57940, https://github.com/rust-lang/rust/issues/57941, https://github.com/rust-lang/rust/issues/57943, https://github.com/rust-lang/rust/issues/57942 and https://github.com/alexcrichton/backtrace-rs/issues/155.

Numerous crates also errored on lack of documentation for macros, but because this is due to a `deny(missing_docs)` lint those errors have not been reported.

**Comment by Mark-Simulacrum** [comment]
No new regressions.
