### ISSUE TITLE
unrecognized platform-specific intrinsic function

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#57940]
A set of intrinsics are no longer present it seems (perhaps in LLVM?); see log in https://crater-reports.s3.amazonaws.com/beta-1.33-1/beta-2019-01-22/reg/basic_dsp-0.6.0/log.txt.

cc @rust-lang/libs @liebharc

**Comment by rkruppe** [comment]
This is an unstable feature removed in #57416. It appears [the `simd` crate](https://crates.io/crates/simd) (which basic_dsp uses) sets RUSTC_BOOTSTRAP to use unstable features on stable ☹️

**Comment by liebharc** [comment]
For `basic_dsp` users: `simd` is an optional dependency of `basic_dsp`. So as a workaround people should still be able to compile it with[ `--no-default-features --std`](https://github.com/liebharc/basic_dsp/blob/master/building.md). 

At the time `basic_dsp` was created the `simd` crate was the only explicit SIMD support in Rust. I haven't followed SIMD development in Rust that closely in the last year, but it seems that there are [alternatives to `simd`](https://github.com/liebharc/basic_dsp/issues/38). So that would be a possibility for me to address this.

Please let me know how you would like to proceed with this issue.

**Comment by alexcrichton** [comment]
Looks like @rkruppe is right and I believe the bug here is not in @liebharc's `basic_dsp` crater but rather the dependency on `simd`. Setting `RUSTC_BOOTSTRAP` is definitely not covered by our stability policy, which I believe is already known, so I'm going to close this.

**Comment by alexcrichton** [comment]
@liebharc in the meantime if you'd like to remove the dependency on `simd` the recommendations are:

* Ideally use `std::arch` if functionality is already implemented there
* If you're willing and it's not there, add such functionality to `std::arch` via the `stdsimd` repository
* Falling back to inline assembly
* If none of that is appropriate, using `simd` but understanding that it's nightly only for now
