### ISSUE TITLE
Cloneable generators

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#57972]
There was [some discussion on Discord](https://discordapp.com/channels/442252698964721669/443150878111694848/539561017722535937) about whether generators can be cloned. It seems to me that non-self-referential generators can be trivially cloneable if everything in their environment implements clone (including both upvars and saved state, the implementation would be non-trivial as it would have to check the current state to know which fields need cloning, but that's basically like the generated `Drop` implementation).

I don't see any way that self-referential generators could be cloneable, if there were some sort of `fn clone_into(&self, place: Pin<*mut Self>)` operation they could potentially support that via re-writing the self-references, but that doesn't exist yet as far as I know. You can clone them before starting by using something like `impl (FnOnce() -> impl Generator) + Clone` instead of taking the generator directly.

**Comment by tema3210** [comment]
The `Clone` trait, like `Move`, uses `memcpy()` function to copy it's data to another location. The simplest way i can propose is to have a `OnMove` trait to use in object lifecycle. Since the arichmetic isn't so demandful to hardware resources, this solution sounds better to me. Moving from one pin to another sounds good, especially for the gurantee that generator won't be moved too frequently.  The most impotant question is syntax: how can we shortly mark self-refs?. The implementation i can propose is:

**Comment by jonas-schievink** [comment]
I think I can say fairly confidently that `OnMove` is not going to happen. It has been discussed and rejected many times in the past already.

It looks like supporting this for self-referential generators would run into https://github.com/rust-lang/rust/issues/63818 too, so limiting it to movable generators seems like the only option. A simplification would be to first limit it to `Copy`able generators, which would keep things fairly simple since no decisions based on the generator state have to be made.

**Comment by bouk** [comment]
Related: https://github.com/rust-lang/rust/issues/95360

**Comment by Nemo157** [comment]
Looks like #95360 fully covers this.
