### ISSUE TITLE
Use statement not migrated

### ISSUE THREAD

**Issue by Swoorup** [rust-lang/rust#58004]
Use statements doesn't migrate to 2018 when using 
`cargo fix --edition`

I later realized this was on a project which had all warnings turned off. Should rustfix, somehow understand warnings regardless of the warnings suppress by the user?

https://github.com/rustlang-cn/Rust-webapp-starter

**Comment by Enselic** [comment]
Triage: I think this issue should be moved to https://github.com/rust-lang/rustfix/issues?

**Comment by ehuss** [comment]
I believe this was fixed in 2021 via https://github.com/rust-lang/rust/pull/85788 and https://github.com/rust-lang/cargo/pull/9588. From what I can gather (the linked repo is no longer available), it sounds like they were allowing warnings. The force-warn system now forces warnings to be applied.

@Enselic, just FYI, the rustfix repo will be closing soon. Most suggested diagnostic issues should remain in this repo. Also, before transferring an issue, it is helpful to have a reproduction or enough information to assess where the issue lies.
