### ISSUE TITLE
unnecessary path disambiguator slips past deny(warnings)

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#58055]
```rust
#[deny(warnings)]
pub fn foo() {
    type _V = Vec::<u32>;
}
```
Although there is a `deny(warnings)` attribute, this code compiles with a warning only.
```
   Compiling warn v0.1.0 (/tmp/warn)
warning: unnecessary path disambiguator
 --> src/lib.rs:3:18
  |
3 |     type _V = Vec::<u32>;
  |                  ^^ try removing `::`

    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
```
This behavior is present in all versions I tested including the latest nightly 2019-01-31 and 1.21.0 when relaxed path syntax was introduced.

**Comment by zackmdavis** [comment]
This happens because the warning is issued unconditionally, rather than under the purview of a lint:

https://github.com/rust-lang/rust/blob/c9a86879515ed1677196f4d3585ec7a5935d2712/src/libsyntax/parse/parser.rs#L2266-L2267

Reservations [were expressed](https://github.com/rust-lang/rust/pull/43540#issuecomment-322886356) at the time. (@estebank do we have a _policy_ anywhere on unsilenceable warnings? It seems kind of bad for it to be a thing the compiler _mostly_ doesn't do, except _sometimes very rarely_ when it didn't feel "worthy" of a top-level lint.)

**Comment by petrochenkov** [comment]
All hard-coded warnings should generally be subsumed by lints or eliminated.
For this specific warning https://github.com/rust-lang/rust/pull/57565 does the job.
