### ISSUE TITLE
bat

### ISSUE THREAD

**Issue by drvegass** [rust-lang/rust#58076]
```rust
fn main() {
    println!("Hello, world!");
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=53bb1c585d49ec40853aeaccb17faa81))

Output:

```
Hello, world!

```

Errors:

```
   Compiling playground v0.0.1 (/playground)
    Finished release [optimized] target(s) in 0.46s
     Running `target/release/playground`

```

**Comment by killercup** [comment]
I'm sorry, I don't understand what you are trying to say with this. What is the meaning of the headline "bat"? Can you explain what the issue is, what you expected to happen, what didn't work as expected?

**Comment by totorigolo** [comment]
Is the problem that, on the Playground, on the right-hand side of the screen, it's written "Standard Error"?

```
--- Standard Error ---                                  <-- here?
   Compiling playground v0.0.1 (/playground)
    Finished release [optimized] target(s) in 0.46s
     Running `target/release/playground`

--- Standard Output ---
Hello, world!
```

This doesn't mean that the execution ran into an error. [According to Wikipedia](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)):

> **Standard error** is another output stream typically used by programs to output error messages or diagnostics. It is a stream independent of standard output and can be redirected separately.

Basically, we usually use `stderr` (STandarD ERRor) to log some messages, such as errors, diagnostics or general information, which are not directly related to the program you're writing. Here, the output tells you that the compiler successfully optimized and compiled your program (in 0.46s), and then that the program is running (hence the text on `stdout` (STandarD OUTput)).

We're lucky, the "Hello, World!" isn't broken :wink: 

---

If I'm correct, then I suggest you to read the [Rust Book](https://doc.rust-lang.org/book/) ([https://doc.rust-lang.org/book/](https://doc.rust-lang.org/book/)). It explains how to use Rust, and If I remember correctly introduces `stdout` and `stderr`. For the time being, just remember that `println!()` prints on `stdout`.

Moreover, if you need help, go to the [Discord](https://discordapp.com/invite/rust-lang) ([https://discordapp.com/invite/rust-lang](https://discordapp.com/invite/rust-lang) or the [forum](https://users.rust-lang.org/) ([https://users.rust-lang.org/](https://users.rust-lang.org/)) instead of this GitHub repository (frankly, you won't need to come here until you don't know how to use Rust).

PS: Please rename your Issue with a title like "What does "Standard Error" mean?" or "Why does Cargo output on stderr". "bat" doesn't help us understand your problem :slightly_smiling_face:
