### ISSUE TITLE
Large slices cause different errors

### ISSUE THREAD

**Issue by matthias-t** [rust-lang/rust#58084]
So I tried creating very large slices.

```rust
fn main() {
    let _ = [false; /* power of two */];
}
```

Up to 2^22 = 4194304 this compiles and runs. Starting with 2^23 = 8388608, it compiles but running gives the error:

```
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
terminated by signal SIGABRT (Abort)
```

The error changes starting with 2^32 = 4294967296

```
terminated by signal SIGSEGV (Address boundary error)
```

From 2^47 = 140737488355328 however the compiler complains:

```
error: the type `[bool; 140737488355328]` is too big for the current architecture

error: aborting due to previous error
```

***

#### Questions

- why do those different errors happen?
- what is the biggest slice I can create?
- why is `usize` used for indexing slices?

**Comment by ExoticMatter** [comment]
The stack overflow is likely due to your system's stack size limit. 2^22 = 4 MiB. The maximum stack size varies from platform to platform, as does the largest block of memory you can allocate. On nightly, you can probably circumvent this by allocating the array using the `box` keyword. (Note: `[_; _]` is an array, not a slice.)

I don't understand why you'd get SIGSEGV from initializing something that can't fit in physical memory rather than a panic.

The last error:

    error: the type `[bool; 140737488355328]` is too big for the current architecture

is due to the address being larger than 48 bits. The top 16 bits of 64-bit addresses are currently unused and reserved for future use.

It should be noted that slices are simply references to a range of an array-like object. Therefore, the largest *valid* slice you can create depends on the largest contiguous block of memory you can allocate on that platform.

`usize` is used for indexing to allow full access of any slice. For example, on a 32-bit platform, if a slice was larger than 2GiB you would only be able to access the first 2GiB, since `2147483647 + 1 = -2147483648`, which is always out of bounds.

**Comment by jonas-schievink** [comment]
Please direct questions about Rust to the forum (https://users.rust-lang.org/) or [Discord](https://discord.gg/rust-lang), this issue tracker is meant for bug reports only.

**Comment by matthias-t** [comment]
@ExoticMatter thanks, that was very helpful.

> `usize` is used for indexing to allow full access of any slice. For example, on a 32-bit platform, if a slice was larger than 2GiB you would only be able to access the first 2GiB, since `2147483647 + 1 = -2147483648`, which is always out of bounds.

I don't understand this part. Could you please elaborate a bit?

@jonas-schievink I'm sorry. I'll post to the forum next time.

**Comment by ExoticMatter** [comment]
@matthias-t With signed integers, the highest bit represents the sign.

- `2147483647 = 0x7FFFFFFF`; all bits are set except the sign bit.
- `-2147483648 = 0x80000000`; only the sign bit is set.

Attempting to access past the 2147483647th position in a slice on a 32-bit platform would be impossible if `isize` was used.

Slices can only validate indexes within its own range, as they do not "know" the full range of the array they're borrowed from. Negative indexes would go outside of this range, therefore they are rejected, and the most sensible way to reject negative values is with the type checker.

```rust
let a = [1, 2, 3, 4, 5];
let b = &a[1..4];
assert_eq!(b.len(), 3);
// No way to derive a.len() from b!
```

**Comment by matthias-t** [comment]
Oh, I get it. But why is there no `u48` for 64 bit targets?

**Comment by ExoticMatter** [comment]
x86-64 doesn't do 48-bit arithmetic; it's still a 64-bit architecture that does 64-bit (as well as 32-bit) arithmetic. `u48` would be a strange type of integer, as it can't be aligned with 64-bit or 32-bit words without wasting space.
