### ISSUE TITLE
Rewire MMX intrinsics to SSE2 instructions

### ISSUE THREAD

**Issue by the8472** [rust-lang/rust#58168]
GCC just implemented [rewiring the MMX intrinsics to 8byte SSE2 equivalents](https://gcc.gnu.org/ml/gcc-patches/2019-02/msg00061.html). Rust could do the same to avoid emitting MMX instructions and the associated pitfalls such as #57831 while still offering `__m64` vector types.

**Comment by workingjubilee** [comment]
This is an understandable request but it seems sanest to simply Not, as core::arch has [recently completely removed MMX support](https://github.com/rust-lang/stdarch/pull/890). While it is technically possible to completely replace it with SSE2 capabilities, it seems like adding unnecessary confusion as we would then have emulated SSE2-dependent MMX but not real MMX.

**Comment by mati865** [comment]
This issue was opened when removal was not yet considered viable option.
GCC and Clang reimplemented MMX with SSE because they did not want to break old code.

In our case MMX was never stabilised (and never would have been) so the removal is pretty straightforward.
As bonus with CPUs available today MMX is hardly ever the best option.

**Comment by the8472** [comment]
Good points. The only remaining use-cases I see is if someone tried to mechanically translate existing code using intrinsics. But that'sprobably niche enough that we don't need it in std.

Closing.
