### ISSUE TITLE
Cannot link to --crate-type staticlib as -whole-archive

### ISSUE THREAD

**Issue by krdln** [rust-lang/rust#58277]
Background: I was trying to integrate `libfoo.a` (compiled as `crate-type = "staticlib"`) as a static depencency of `libbar.so` library (written in C++). Turned out that `bazel` was passing `-whole-archive libfoo.a` to the linker, which caused problems:

#### Steps to reproduce

This is a slightly different scenario, but produces the same error:

```sh
touch foo.rs
rustc --crate-type staticlib foo.rs
ld -r -whole-archive libfoo.a -o foo.o
```

Fails with (both with `ld` and `ld.gold`):

```
libfoo.a(clzsi2.o): In function `__clzsi2':
clzsi2.c:(.text.__clzsi2+0x0): multiple definition of `__clzsi2'
libfoo.a(compiler_builtins-05f9079cfd1746c1.compiler_builtins.5xigqg70-cgu.0.rcgu.o):/cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.5/src/int/mod.rs:332: first defined here
```

#### Failing version

```
rustc 1.34.0-nightly (4b1e39b7b 2019-02-05)
GNU ld (GNU Binutils for Ubuntu) 2.30
GNU gold (GNU Binutils for Ubuntu 2.30) 1.15
Ubuntu 18.04
```

#### Last working versions

This scenario works without errors on stable (1.32) and beta (1.33.0-beta.6).

---

I don't actually understand linkers enough to even say if that's a bug or expected behaviour, but at least for me it's a regression, because a scenario that was working on stable has stopped to work on nightly.

**Comment by cdetrio** [comment]
I ran into the same issue when using nightly (downgrading to stable fixed it).

**Comment by MackieLoeffel** [comment]
I am running into the same problem and my current workaround is to remove `clzsi2.o` from the static library before linking it into a shared library:
```
touch foo.rs
rustc +nightly --crate-type staticlib foo.rs
ar d libfoo.a clzsi2.o # without this line I get the linker error from above
ld -r -whole-archive libfoo.a -o foo.o
```
@nagisa I don't understand what you mean with two different compilers. What other compiler than rustc do you mean? The problem seems to me that rustc puts two versions of `__clzsi2` into libfoo.a.

**Comment by kleisauke** [comment]
It look like this is fixed with https://github.com/rust-lang-nursery/compiler-builtins/commit/752e35a11f2e7eb29df84668bef0945e75cf3eb5 which is available within Rust 1.36.0 (https://github.com/rust-lang/rust/pull/60841).

Note that the above mentioned workaround only needs to be applied to Rust 1.35.0 and 1.34.0, otherwise it will cause linker errors. See for example:
https://gitlab.gnome.org/GNOME/librsvg/issues/485#note_549519

**Comment by petrochenkov** [comment]
I have submitted an RFC about supporting whole archive - https://github.com/rust-lang/rfcs/pull/2951.

**Comment by petrochenkov** [comment]
Closing this issue, the `whole-archive` modifier was implemented about 9 months ago, and https://github.com/rust-lang/rust/pull/93901 now intends to make it available on stable.
