### ISSUE TITLE
Tracking issue for #[ffi_returns_twice]

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#58314]
~~I'll update with the PR and RFC links when those are ready.~~

PR: https://github.com/rust-lang/rust/pull/58315
RFC: https://github.com/rust-lang/rfcs/pull/2633

**Comment by jonas-schievink** [comment]
Implemented in https://github.com/rust-lang/rust/pull/58315

**Comment by JohnTitor** [comment]
Could we stabilize this feature now? I'm not sure if this is unstable because it's _newly_ added or there's a blocker but it'd be great if we could de-deprecate `vfork` on the libc :) cc @Amanieu

**Comment by Amanieu** [comment]
I am very hesitant to do so since it would stabilize a horrible hack that C uses for two functions: `vfork` and `setjmp`. In particular:
- This basically works by disabling a bunch of optimizations in LLVM, but it would likely require additional work in rustc for MIR optimizations.
- Functions that return twice are a hack, you can't even implement such functions in C: they must be written in assembly.
- If you *really* want to use `vfork` then you should use a C or asm wrapper that hides the "returns twice" hack and provides a safe callback interface that allows you to run a function in the child process.

**Comment by JohnTitor** [comment]
Ah, fair enough! I just thought this was missed from stabilizing eyes since rust-lang/libc#1574's OP says "I propose deprecating it until `#[returns_twice]` is stable". With the above comment, I'm fine to leave this feature as-is, thanks for clarifying!

**Comment by joshtriplett** [comment]
Closing because https://github.com/rust-lang/rfcs/pull/2633 was closed. (The ffi-unwind project is looking at this.)

**Comment by VorpalBlade** [comment]
Whatever became of this? Since FFI-unwind was mentioned, C-unwind now exists and is stable, so is it time to revisit this?

**Comment by Amanieu** [comment]
This is completely unrelated to unwinding. It's about the weird ABI used by functions like `vfork` and `setjmp` which do not want to support in Rust.
