### ISSUE TITLE
Box hides value from borrow checker inside closure

### ISSUE THREAD

**Issue by anderspapitto** [rust-lang/rust#58443]
in this code snippet, whether it's ok to assign to an Option which has been captured by a closure depends on whether the type inside the Option is wrapped in Box or not. The borrow checker also seems to turn off when the exact type is indirected through a generic function.

This is a simplification derived from https://github.com/rust-lang/rust/issues/58441

```
type A = ();
type B = Box<()>;

fn foo<T>() {
    let mut x: Option<T> = None;
    let f = || {
        x.unwrap();
    };
    x = None;
    f();
}

fn main() {
    let mut a: Option<A> = None;
    let mut b: Option<B> = None;
    let f = || {
        a.unwrap();
        b.unwrap();
    };
    a = None; // illegal
    b = None; // legal!!
    f();
    
    foo::<A>(); // legal when indirected through generic function!!!!!
    foo::<B>(); // also still legal
}
```

**Comment by jonas-schievink** [comment]
It is legal to assign a value to a variable that has been moved from. This happens for `b = None;` and `x = None;` because `Option<Box<()>>` and `Option<T>` aren't `Copy`.

For `a = None;`, the reassignment is forbidden because the compiler doesn't move `a` into the closure, it makes the closure borrow it. This works because the `a.unwrap()` inside the closure will copy the option. You can force the closure to move/copy all outside variables by using `move ||`, which makes it compile.

So at first glance, this just seems like a maybe not very intuitive consequence of how borrowing/moving in closure environments is inferred. The borrow checker is never turned off though.

**Comment by jonas-schievink** [comment]
(Closing - If you still think this is a bug, please leave a comment and I can reopen)
