### ISSUE TITLE
Expose `libstd::sys_common::remutex`

### ISSUE THREAD

**Issue by ckaran** [rust-lang/rust#58612]
I just discovered that `libstd::sys_common::remutex` has the `ReentrantMutex` type, which is not exposed in `std::sync`.  Can you please expose it in `std::sync`?

**Comment by eggyal** [comment]
See also #27738

**Comment by ckaran** [comment]
@eggyal Thank you for link!

**Comment by SimonSapin** [comment]
The fact that an implementation already exists inside `std` may help a little but it’s not the most important point. This would add non-trivial new API surface to the standard library, so it should likely go through the RFC process to consider questions like: what are the details of new APIs? What are their semantics? Why is making these choices preferable over alternatives? Is this a commonly-used enough primitive that is should be in the standard library rather than on crates.io? etc.

**Comment by eggyal** [comment]
> Is this a commonly-used enough primitive that is should be in the standard library rather than on crates.io?

Worth noting that @Amanieu's [parking_lot](https://crates.io/crates/parking_lot) crate provides a [`ReentrantMutex`](https://docs.rs/parking_lot/0.11.1/parking_lot/type.ReentrantMutex.html).

**Comment by ckaran** [comment]
@SimonSapin I agree that it should go through the RFC process, if for no other reason than the fully refine the API and ensure it is *exactly* what we want to expose.  Unfortunately, I don't have the time to push for it (too many deadlines at work right now).

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/libs-team/issues/193, which is tracking this API (and has an open PR).
