### ISSUE TITLE
"Not greater" and "not less" (`!>` and `!<`) operators 

### ISSUE THREAD

**Issue by mankinskin** [rust-lang/rust#58650]
I have been wondering why these two operators are not supported by most languages. Of course you can achieve the same behavior by using `<=` or `!(x > y)` but I usually think more in terms of **not greater** instead of **less than or equal**. The `!(x > y)` syntax requires more keystrokes and reads: **not: x is greater than y** which is very unlike natural speech and requires the programmer to bend according to the language, while the language should be as ergonomic as possible.

I am curious why these operators are not widespread, if there is a reason for that, because I can't see how they would make code harder to reason about or how they would be inconsistent or anything (there is the `!=` operator already, and I suppose we are all glad that we don't have to read or write `!(x == y)` every time).

I am curious what your opinions about this feature proposal are.

**Comment by varkor** [comment]
> I am curious why these operators are not widespread, if there is a reason for that

Because, as you say, they're synonymous with `>=` and `<=` (and take the same number of keystrokes, besides). Redundant operators is something to be avoided.

> I usually think more in terms of **not greater** instead of **less than or equal**.

I think the simplest solution is to try to think of `!>` as being the same as `<=` instead.

> there is the `!=` operator already

Conversely, this is not synonymous with any existing operator.

---

Proposals such as this should take place at the [RFC repository](https://github.com/rust-lang/rfcs), but I think you'd be better off getting used to the existing operators.
