### ISSUE TITLE
E0310 gives invalid suggestion for explicit static lifetime bound

### ISSUE THREAD

**Issue by czipperz** [rust-lang/rust#58804]
The error message given here makes it seem like the correct thing to do is change `cast_triggers: impl CastTriggers` to `cast_triggers: impl CastTriggers: 'static`.  The correct thing to do is `cast_triggers: impl CastTriggers + 'static`.

```
error[E0310]: the parameter type `impl CastTriggers` may not live long enough
  --> src/triggers.rs:76:35
   |
75 |     pub fn with_cast_triggers(mut self, cast_triggers: impl CastTriggers) -> Self {
   |                                                        ------------------ help: consider adding an explicit lifetime bound `impl CastTriggers: 'static`...
76 |         self.cast_triggers = Some(Arc::new(cast_triggers));
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^
   |
note: ...so that the type `impl CastTriggers` will meet its required lifetime bounds
  --> src/triggers.rs:76:35
   |
76 |         self.cast_triggers = Some(Arc::new(cast_triggers));
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^
```

[Context](https://github.com/czipperz/magic/blob/043a83cd26ee77ad331cd935b5fe6d01b235be9d/src/triggers.rs#L75)

**Comment by czipperz** [comment]
[Context](https://github.com/czipperz/magic/blob/043a83cd26ee77ad331cd935b5fe6d01b235be9d/src/triggers.rs#L75)

**Comment by fmease** [comment]
Smaller:

``` ` ` rs
use std::sync::Arc;

pub struct Triggers {
    pub cast_triggers: Option<Arc<dyn CastTriggers>>,
}

pub trait CastTriggers {}

impl Triggers {
    pub fn with_cast_triggers(mut self, cast_triggers: impl CastTriggers) -> Self {
        self.cast_triggers = Some(Arc::new(cast_triggers));
        self
    }
}
` ` ` 

Now yields the correct suggestion:

``` ` ` 
error[E0310]: the parameter type `impl CastTriggers` may not live long enough
  --> src/lib.rs:13:35
   |
13 |         self.cast_triggers = Some(Arc::new(cast_triggers));
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^
   |                                   |
   |                                   the parameter type `impl CastTriggers` must be valid for the static lifetime...
   |                                   ...so that the type `impl CastTriggers` will meet its required lifetime bounds
   |
help: consider adding an explicit lifetime bound
   |
12 |     pub fn with_cast_triggers(mut self, cast_triggers: impl CastTriggers + 'static) -> Self {
   |                                                                          +++++++++
` ` `
