### ISSUE TITLE
rustdoc seems to ignore `edition2018` attribute

### ISSUE THREAD

**Issue by Alexander-N** [rust-lang/rust#58875]
Running
```sh
rustdoc -L target/debug/deps --test test.md
```
with the following content of test.md
````rust
```edition2018
// extern crate clap;
use clap::Arg;
```
````
gives me
```
running 1 test
test test.md -  (line 1) ... FAILED

failures:

---- test.md -  (line 1) stdout ----
error[E0432]: unresolved import `clap`
 --> test.md:3:5
  |
4 | use clap::Arg;
  |     ^^^^ use of undeclared type or module `clap`

thread 'test.md -  (line 1)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:351:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
The test passes when I uncomment `extern crate clap`.

This is a problem when code blocks in the documentation should get tested, see https://github.com/amethyst/amethyst/pull/1364#issuecomment-455472322 for an example.

## Meta

`rustdoc --version --verbose`:
rustdoc 1.34.0-nightly (aadbc459b 2019-02-23)
binary: rustdoc
commit-hash: aadbc459bd97a0325897e2ff94999efbec6a499c
commit-date: 2019-02-23
host: x86_64-unknown-linux-gnu
release: 1.34.0-nightly
LLVM version: 8.0

**Comment by ehuss** [comment]
I think that is expected.  Crates are only added to the extern prelude if the `--extern` flag is used. Since mdbook doesn't really know about extern crates (https://github.com/rust-lang-nursery/mdBook/issues/706), you'll probably need to keep the `extern crate` lines (or figure out how to pass the correct `--extern` flags to rustdoc).

**Comment by Alexander-N** [comment]
Ok, thanks.
