### ISSUE TITLE
Identity macro 'launders' hygiene information

### ISSUE THREAD

**Issue by pierzchalski** [rust-lang/rust#59011]
Consider this hygiene demonstration ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2c5d69037bf893b013e9cf07280055e8)):
```rust
#![feature(decl_macro)]

macro x() {
    println!("x");
}

macro y() {
    x!(); // This `x` identifier is in a fresh hygiene scope within `y`,
    macro x() { println!("y"); } // so it resolves to this definition.
}

fn main() {
    y!();
}
```
This prints `"y"`, as expected.

However, if we 'launder' the definition `macro x()` using an identity macro ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a974b31b219f9ed0bd40f93e2f1ffee6)):
```rust
#![feature(decl_macro)]

macro id($($tt:tt)*) {
    $($tt)*
}

macro x() {
    println!("x");
}

macro y() {
    x!();
    id!(macro x() { println!("y"); }); // What is the scope of this `x`?
}

fn main() {
    y!();
}
```
We get an error that the invocation of `x` is ambiguous.

Is this the expected behaviour?

**Comment by pierzchalski** [comment]
Pinging the usual crowd: @alexreg @nrc @petrochenkov @dtolnay

**Comment by alexreg** [comment]
I agree, this is strange. I'd expect the hygiene for the inner definition of the macro `x` to be almost the same in both cases (just an extra expansion mark in the second case?).

**Comment by petrochenkov** [comment]
This works as expected.

*Both* `macro x`s are in scope when we are resolving `x!()`.
The first one is in scope because macros 2.0 provide *definition site* hygiene (so stuff like [this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a6102ea66b540b34af80a749347c25c8) works) and it's in scope at definition point of `macro y`.

In the first example the inner `macro x` shadows the outer `macro x` and everything compiles successfully.

In the second case both `macro x`s are still in scope, but they hit a [restricted shadowing](https://github.com/rust-lang/rust/pull/53778#issuecomment-419224049) rule, that's unrelated to hygiene, but related to expansion algorithm and ensures that it gives predictable results.
Names materializing *later* during expansion (like the second `macro x`) cannot shadow names materializing *earlier* during expansion (like the first `macro x`), so we get the "cannot shadow" error aka ambiguity error.
