### ISSUE TITLE
Use a different DefId for the Def::Variant and Def::VariantCtor

### ISSUE THREAD

**Issue by dlrobertson** [rust-lang/rust#59131]
The enum variant (`Dev::Variant`) and the enum variants constructor (`Def::VariantCtor`) share the same `DefId` making it impossible for `tcx.describe_def` to resolve a `DefId` to a `VariantCtor`.

This issue originates from the discussion [here](https://github.com/rust-lang/rust/pull/59036#discussion_r263991093).

Note: `tcx.describe_def` has not moved away from `NodeId`. It may be best for the fix to wait until it is.
CC: #59036

**Comment by davidtwco** [comment]
I think this can be closed. #59382 resolved this by separating the `DefId` used for a variant and its constructor. `describe_def` (now `def_kind`) can [now return a `Def::VariantCtor`](https://github.com/rust-lang/rust/blob/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/librustc/hir/map/mod.rs#L354-L365) (now `DefKind::Ctor`) and the code from the original PR that raised this now uses `DefKind::Ctor` instead of `DefKind::Variant` as the review suggested.

**Comment by dlrobertson** [comment]
That is awesome! Thanks!
