### ISSUE TITLE
#[cfg(not(test))] doesn't work in dependencies

### ISSUE THREAD

**Issue by nhynes** [rust-lang/rust#59168]
I have something that looks like

```rust
// crateA/lib.rs

#[cfg(not(test))]
extern "C" {
	fn ext_fn();
}

#[cfg(test)]
fn ext_fn() {
	unimplemented!();
}

pub fn do_ext() {
	unsafe { ext_fn() };
}
```

```rust
// crateB/lib.rs
crateA::do_ext()
```

but despite using `cargo test`, I still get a link error saying that `ext_fn` isn't found. Is `#[cfg(not(test))]` a valid attribute?

**Comment by jonas-schievink** [comment]
AFAIK `cargo test` only applies `cfg(test)` to the crate you run it in, not to any dependencies.

**Comment by nhynes** [comment]
That's unfortunate. It seems that a workaround is to use `[features] test = []`, but it'd be nice if conditional compilation flags were propagated through the entire graph.

**Comment by sfackler** [comment]
This would be best filed on cargo, not rustc itself, but I don't think we want to rebuild the entire dependency tree for tests necessarily.

**Comment by mleduque** [comment]
Was there a follow-up issue somewhere else for this bug?

**Comment by mimoo** [comment]
IIRC, the way we fixed that in diem was to have a `[features] testing = []` in every crate, and import dependencies with this feature in `[dev-dependencies]` (see https://github.com/diem/diem/blob/0cdde0d258a3706d7d84d05225899df8518f319a/testsuite/smoke-test/Cargo.toml#L52 for an example)

but then in every other crate you had to do stuff like

```rust
if cfg!(any(test, feature = "testing")) {
  // ...
}
```

and

```rust
#[cfg(any(test, feature = "testing"))]
// ...
```

instead of just having "test"

it's a pain
