### ISSUE TITLE
Make dbg macro work in WASM -> map to browser console

### ISSUE THREAD

**Issue by najamelan** [rust-lang/rust#59248]
Currently, `dbg!` seems to do nothing on wasm, at least as far as the browser console is concerned. `web_sys::console::log_1( &obj.into() );` Allows to get an interactive (eg. not a string) entry in the browser console where we can inspect all the objects javascript properties.

It would be nice if this was supported by `dbg!` out of the box (without consuming the object if possible).

**Comment by Centril** [comment]
(What `dbg!` does is simply print to STDERR)

**Comment by najamelan** [comment]
Yeah, wondering if we can not make it do something more interesting on platform `wasm-....`. Haven't actually check whether something ends up on STDERR of the browser, but I doubt it.

**Comment by CryZe** [comment]
wasm32-unknown-unknown isn't actually targeting the "web". It targets an unknown platform that happens to use WebAssembly. Therefore it is impossible for the standard library to access any web apis such as the browser's console. Eventually there might be a "wasm32-unknown-bindgen" target though that could implement the standard library in a more meaningful way.

**Comment by najamelan** [comment]
@CryZe Thanks, I didn't realize that. How does such an unknown platform guarantee to have an stderr? Docs for eprintln (used by dbg) say:

`Panics if writing to io::stderr fails.`

dbg does not panic on wasm, so something must implement std::io::stderr. 

Don't know if I should close this? Maybe document on which platforms this works?

**Comment by CryZe** [comment]
The wasm32-unknown-unknown target shouldn't really actually provide std, as many things simply are stubbed out that a normal platform with std would have. In this case stdout and stderr simply act as if they printed out something, but never actually do anything. It was chosen that the wasm32-unknown-unknown target implements std regardless of it not really properly supporting std, as many crates depend on std (instead of core or core + alloc). The long term goal for Rust is to eventually have a std with platform lints such that no one needs to use core or alloc directly anymore, just different subsets of std. And the wasm32-unknown-unknown target is kind of an experimentation in a way towards that eventual goal. On platforms where stderr exists and properly errors, dbg panics.

I agree that stuff like this should probably be documented in some way, but I think long term the different platform lints are probably going to help people figure out what's available where.

**Comment by alexcrichton** [comment]
I'm going to close this because the standard library is pretty unlikely to implement this. There's various crates in the ecosystem to do this as well as the wasm32-wasi target, but the bare wasm32-unknown-unknown target is largely defined nowadays as "prints don't work, which isn't that great"

**Comment by MakotoE** [comment]
I just created crate [debug-macro](https://crates.io/crates/debug-macro). It does the same thing as `dbg!()` but uses `log::debug!()` so that you can control where it prints to.
