### ISSUE TITLE
Incorrectly documented core::arch modules in the offical and nursery docs

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#59294]
Compare the documentation of, e.g., `core::arch::arm`, from the 

* official docs: https://doc.rust-lang.org/nightly/core/arch/arm/index.html
* nursery: https://rust-lang-nursery.github.io/stdsimd/arm/core_arch/arm/index.html

The official documentation should contain the items available under all arm features, yet there are some items that the nursery documentation contains, that are not available in the official docs.

At the same time, the documentation on the nursery is missing some items that should unconditionally be there.

**Comment by DevQps** [comment]
To be really honest I am not too familiar with the Rust nursery but I read [here](https://internals.rust-lang.org/t/end-of-days-for-the-rust-lang-nursery/8750) that the core team more or less deprecated the nursery (if I understand correctly?).

I am also wondering why the nursery and official docs are out of sync in the first place. Is it not because the nightly version is being maintained and the nursery version is not? If that would be the case, then I guess it would be best to just get rid of the whole nursery repo (or keep it for compatibility purposes)

**Comment by gnzlbg** [comment]
> Is it not because the nightly version is being maintained and the nursery version is not?

Both are the same, libstd and libcore have direct dependencies to the nursery repo, yet for some reason the docs of libstd and libcore are incorrect.

**Comment by DevQps** [comment]
@gnzlbg Ahh my bad then, thanks for your clarification! Mmm so if the source is exactly the same, then there must be some kind of problem with generating the docs right? Maybe one of the two uses an old version?

**Comment by gnzlbg** [comment]
The stdsimd docs are generated on every commit to master (https://github.com/rust-lang-nursery/stdsimd/tree/gh-pages) while libstd and libcore follow stdsimd master very closely: https://github.com/rust-lang-nursery/stdsimd/tree/4bf456c35e85fcca5cf95008401af8ab25abf850

So the code being used to generate the docs is pretty much identical, so AFAICT the issue has to be in how the docs are generated.

**Comment by DevQps** [comment]
@gnzlbg I asked around in the rustdoc channel in Discord. If I get a reply I will let you know (Y)

**Comment by jyn514** [comment]
@gnzlbg the nursery page is currently a 404 unfortunately. Do you have some examples of intrinsics that aren't being documented?

**Comment by workingjubilee** [comment]
The Wayback Machine is of no help either. This issue functionally seems to be non-actionable. Closing, feel free to reopen if we have a followup.
