### ISSUE TITLE
rustdoc: doc(hidden) also hides re-exports

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#59368]
Code:

```rust
#[macro_use]
pub mod my_module {
    /// This is a simple macro.
    #[macro_export]
    #[doc(hidden)]
    macro_rules! foo {
        () => ();
    }

    /// This doc comment doesn't show up in rustdoc (there's just an ugly re-export).
    pub use crate::foo as bar;

    // And this re-export doesn't show up in rustdoc at all!
    #[doc(inline)]
    pub use crate::foo as baz;
}
```

Generated docs:

![screenshot](https://screenshotscdn.firefoxusercontent.com/images/a5d96304-392c-4fa9-9d72-e40da31f380a.png)

So what I want to do is create a macro inside `my_module`. I don't want it to show up in crate root - I want it only in this module.

Both of the re-exports above work just fine. However, in the generated docs, one of them has no docs and the other doesn't show up at all.

I'm surprised that `#[doc(hidden)]` is "recursive" - shouldn't it only hide `foo` and not hide `baz`? Is this a bug?

Versions:

```console
$ rustc --version
rustc 1.35.0-nightly (94fd04589 2019-03-21)
$ cargo --version
cargo 1.35.0-nightly (0e35bd8af 2019-03-13)
$ rustdoc --version
rustdoc 1.35.0-nightly (94fd04589 2019-03-21)
```

**Comment by weiznich** [comment]
Is there any news on this?
We would like to use something like that for diesel to.

**Comment by jonhoo** [comment]
This doesn't appear to be just an issue with macros either:
```rust
/// Hello world
#[doc(hidden)]
pub struct Foo;

#[doc(inline)]
pub use Foo as Bar;
```
Produces entirely empty rustdoc output!

**Comment by nazar-pc** [comment]
I have a similar issue with modules:
```rust
pub mod foo {
    #[doc(hidden)]
    mod bar {
        pub struct Baz;
    }
}

#[doc(inline)]
pub use foo::bar;
```
Essentially I want to present nested module structure (that is used to limit visibility within crate) as non-nested in docs by leveraging re-exports.

I'm thinking of `#[doc(visible)]` that would override `#[doc(hidden)]` of the definition if applied to `pub use`:
```rust
pub mod foo {
    #[doc(hidden)]
    mod bar {
        pub struct Baz;
    }
}

#[doc(inline, visible)]
pub use foo::bar;
```

Without this when inlining is used it creates confusion since the same module is both visible at the root of the crate and nested within submodule. This also confuses IntelliJ Rust, it shows 2 suggestions for imports all the time and could use this to hide one of them.

**Comment by SergioBenitez** [comment]
This is causing quite a big issue for Rocket's docs. We'd _really_ like to export `macro_rules!` macros only from specific modules, but this bug makes it impossible without also exporting them at the root.

Specifically, this:

```rust
pub mod foo {
    /// `macro_rules!`
    #[macro_export]
    macro_rules! m { () => () }

    /// `pub use m;`
    #[doc(inline)]
    pub use m;
}
```

Results in:

index:
```
modules:
foo

macros:
m `macro_rules!`
```

foo:
```
macros:
m `macro_rules!`
```

Which is expected. Now, by adding `#[doc(hidden)]` to `m`'s declaration/definition...

```diff
    #[macro_export]
+   #[doc(hidden)]
    macro_rules! m { () => () }
```

..._all_ instances of `m` in the docs disappear, even though `foo:m` is still reachable and not hidden!

**Comment by SergioBenitez** [comment]
Here's a macro that (sort of) patches around this issue:

```rust
#[macro_use]
macro_rules! export {
    (
        $(#[$m:meta])*
        macro_rules! $name:ident {
            $(($($matcher:tt)*) => ($($expansion:tt)*));* $(;)?
        }
    ) => (
        mod $name {
            #[macro_export]
            #[doc(hidden)]
            $(#[$m])*
            macro_rules! __impl {
                $(
                    ($($matcher)*) => ($($expansion)*)
                );*
            }

            #[doc(inline)]
            pub use __impl;
        }

        $(#[$m])*
        #[cfg(nightly)]
        pub macro $name {
            $(
                ($($matcher)*) => ($($expansion)*)
            ),*
        }

        #[doc(inline)]
        #[cfg(not(nightly))]
        pub use $name::__impl as $name;
    )
}
```

It assumes the existence of a `nightly` `cfg` set when compiled with nightly, and also assumes that there's a `#![cfg_attr(nightly, feature(decl_macro))]` in the crate root.

Here's a use in Rocket:

```rust
export! {
    /// A helper macro for custom validation error messages.
    ///
    /// The macro works identically to [`std::format!`] except it does not allocate
    /// when the expression is a string literal. It returns a function (a closure)
    /// that takes one parameter and evaluates to an `Err` of validation [`Error`]
    /// with the formatted message. While useful in other contexts, it is designed
    /// to be chained to validation results via `.or_else()` and `.and_then()`.
    ///
    /// Note that the macro never needs to be imported when used with a `FromForm`
    /// derive; all items in [`form::validate`](crate::form::validate) are already
    /// in scope.
    ///
    /// # Example
    ///
    /// ```rust
    /// use rocket::form::FromForm;
    ///
    /// #[derive(FromForm)]
    /// struct Person<'r> {
    ///     #[field(validate = len(3..).or_else(msg!("that's a short name...")))]
    ///     name: &'r str,
    ///     #[field(validate = contains('f').and_then(msg!("please, no `f`!")))]
    ///     non_f_name: &'r str,
    /// }
    /// ```
    ///
    /// See the [top-level docs](crate::form::validate) for more examples.
    macro_rules! msg {
        ($e:expr) => (
            |_| {
                Err($crate::form::Errors::from($crate::form::Error::validation($e)))
                    as $crate::form::Result<()>
            }
        );
        ($($arg:tt)*) => (
            |_| {
                Err($crate::form::Errors::from($crate::form::Error::validation(format!($($arg)*))))
                    as $crate::form::Result<()>
            }
        );
    }
}
```

**Comment by SpriteOvO** [comment]
It looks like this issue has been inactive for a while, but the problem is still there.

I would like to know if there are more comments from members about https://github.com/rust-lang/rust/issues/59368#issuecomment-826034070?

@danielhenrymantilla said [in this reply](https://users.rust-lang.org/t/how-to-namespace-a-macro-rules-macro-within-a-module-or-macro-export-it-without-polluting-the-top-level-namespace/63779/5) he had a discussion with @jyn514 and @GuillaumeGomez about this, but I didn't find it. @jyn514 [replied later](https://users.rust-lang.org/t/how-to-namespace-a-macro-rules-macro-within-a-module-or-macro-export-it-without-polluting-the-top-level-namespace/63779/7) that it looked fine to him.

**Comment by jyn514** [comment]
I'm no longer a member of the rustdoc team, please don't ping me.

**Comment by GuillaumeGomez** [comment]
Technical information for everyone following this issue: I'm working on it (well, you can infer that from my PRs I suppose). One of the last blockers is actually `#[doc(hidden)]`: currently we merge both the `pub use`'s and the item's attributes. Meaning that the `#[doc(hidden)]` is inherited. The problem is that it's currently not possible to filter the sub-attributes of an `ast::Attribute` (for example, in `#[doc(hidden, inline)]`, we want to keep `inline`).

So hopefully, once I figure out this part, I should be able to fix all the remaining issues at once.

**Comment by GuillaumeGomez** [comment]
So now only one issue remains:

```rust
#[macro_export]
#[doc(hidden)]
macro_rules! foo {
    () => {};
}

pub use crate::foo as Macro; // this one isn't displayed, as expected
#[doc(inline)]
pub use crate::foo as Macro2; // this one isn't displayed but should be!
```

**Comment by danielhenrymantilla** [comment]
FWIW, I had a branch with an implementation tackling your `Macro2` situation, @GuillaumeGomez, if you are interested

**Comment by GuillaumeGomez** [comment]
I have a vague idea on how to fix it but I'm definitely interested into seeing how you did it. You sure you don't want to send a PR btw?
