### ISSUE TITLE
Better diagnostics for binary operators

### ISSUE THREAD

**Issue by tumdum** [rust-lang/rust#59458]
```rust
use std::ops::Mul;

struct BoxedValue<T: Mul> {
    value: T
}

impl<T: Mul<Output=T>> Mul for BoxedValue<T> {
    type Output = Self;

    fn mul(self, rhs: Self) -> Self {
        BoxedValue{value: self.value*rhs.value}
    }
}

fn width<T: Mul>(value: T) -> BoxedValue<T> {
    BoxedValue{value}
}

fn height<T: Mul>(value: T) -> BoxedValue<T> {
    BoxedValue{value}
}

fn foo(s1: f64, s2: f64) -> BoxedValue<f64> {
    (width(s1) * height(s1)) + (width(s2) * height(s2))
}

fn main() {
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e7da30e9f717954343ca8858bba74d0f))

When compiled produces error which only highlights whole expression - offending operator is not marked in any way.
Newest gcc is capable of much nicer diagnostics in similar situation: https://developers.redhat.com/blog/2019/03/08/usability-improvements-in-gcc-9/ - similar diagnostics should be added to rustc.

**Comment by oli-obk** [comment]
I think the following steps should be able to address this

1. Change https://github.com/rust-lang/rust/blob/ea43c3c688980edd6f09a4cb632c9eb996c4f2af/src/librustc_typeck/check/op.rs#L330 to use `op.span` instead of `expr.span`
2. add a call to `err.span_label(lhs_expr.span, lhs_ty.to_string())`
3. do 2. for `rhs_*`, too
4. run `./x.py test --stage 1 src/test/ui --bless`

**Comment by hgallagher1993** [comment]
Ya I'll take this on :+1:
