### ISSUE TITLE
Re-introduce load-bearing assert, or fix niche debuginfo generation properly.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#59509]
See https://github.com/rust-lang/rust/pull/55701#discussion_r270227197, this is just one-line addition for the assert.

Currently, this example:
```rust
#![feature(repr128)]

#[repr(u128)]
pub enum Foo {
    Lo,
    Hi = 1 << 64,
    Bar = 18_446_745_000_000_000_123,
}

pub fn foo() -> Option<Foo> {
    None
}
```
has this in its LLVM IR (in debug mode):
```llvm
!22 = !DIDerivedType(tag: DW_TAG_member, name: "None", scope: !20, file: !6, baseType: !23, size: 128, align: 64, extraData: i64 926290448508)
```
Note the `extraData`, which indicates the discriminant (niche, in this case), it should be the same value as `Foo::Bar`, plus `1`, but is instead the truncated value (see below).

The debuginfo for `Foo` is also wrong, but that is caused elsewhere in the codebase (in a spot where no assertion was ever added AFAIK. also see https://github.com/rust-lang/rust/issues/59509#issuecomment-478128182):
```llvm
!10 = !DIEnumerator(name: "Lo", value: 0)
!11 = !DIEnumerator(name: "Hi", value: 0)
!12 = !DIEnumerator(name: "Bar", value: 926290448507)
```

The compiler should ICE, instead, to avoid generating the wrong debuginfo.

<hr/>

Alternatively, if LLVM and DWARF support it, we should encode the 128-bit discriminant, by employing `const_uint_big` instead of `const_u64` here:
https://github.com/rust-lang/rust/blob/237bf3244fffef501cf37d4bda00e1fce3fcfb46/src/librustc_codegen_llvm/debuginfo/metadata.rs#L1817 
Also, this field would need to become `Option<u128>`:
https://github.com/rust-lang/rust/blob/237bf3244fffef501cf37d4bda00e1fce3fcfb46/src/librustc_codegen_llvm/debuginfo/metadata.rs#L924

**Comment by cuviper** [comment]
> Alternatively, if LLVM and DWARF support it

I think DWARF LEB128 isn't technically bounded, but I'll bet a lot of tools will only decode 64-bit values. There's also `DW_FORM_data16` though.

But it looks like LLVM is limited:

https://github.com/rust-lang/rust/blob/2002b4b39a16760f37107cf02d7a91ff316d3073/src/librustc_codegen_llvm/debuginfo/metadata.rs#L1541-L1545
https://github.com/rust-lang/rust/blob/2002b4b39a16760f37107cf02d7a91ff316d3073/src/rustllvm/RustWrapper.cpp#L866-L870
https://github.com/rust-lang/llvm-project/blob/1f484cbe0e863e9e215f1b3d7198063444d60873/llvm/include/llvm/IR/DIBuilder.h#L180-L181

We probably should at least be setting that `isUnsigned` parameter where possible. It was added in llvm-project [commit 08dc66e](https://github.com/rust-lang/llvm-project/commit/08dc66eff0c7ad594584a8a6925ef830cd6873a1), [D42734](https://reviews.llvm.org/D42734), since LLVM 7.

**Comment by eddyb** [comment]
Okay I was a bit confused, turns out there are two separate parts to this:
* `Foo`'s enumeraror debuginfo, which has nothing to do with the assert that was removed, and is missing its own assert, until the problem described by @cuviper is resolved
* `Option<Foo>`'s variant member type debuginfo for `None`, is the one affected by the removed assert
  * the function creating that debuginfo metadata (`LLVMRustDIBuilderCreateVariantMemberType`) takes an arbitrary LLVM value, so `i128` might work here
  * this is the part which https://github.com/rust-lang/rust/pull/59520 fixes, which we can try to merge now

**Comment by cuviper** [comment]
> The compiler should ICE, instead, to avoid generating the wrong debuginfo.

Wouldn't it be better to just omit debuginfo when it can't be represented?

**Comment by eddyb** [comment]
Maybe, with a warning.

**Comment by wesleywiser** [comment]
Visited during wg-debugging triage. This assert exists today:

https://github.com/rust-lang/rust/blob/8006510ab0f69ee75e9c3f7e8bff3776886dae51/compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/native.rs#L416-L419

so I'm going to close this issue as completed and open a new issue specifically for tracking the removal of the assert.
