### ISSUE TITLE
std::iter::Cycle has many methods that cannot be used without an infinite loop

### ISSUE THREAD

**Issue by dralley** [rust-lang/rust#59501]
A cycle object is an iterator that repeats itself endlessly - therefore, performing a ```.sum()```, ```.count()```, ```.product()``` or other similar methods on a cycle object will create an instant self-contained infinite loop.  

While not "unsafe", I cannot imagine how this could possibly be useful.

I'm unfamiliar with any tools you might have at your disposal to disable these methods specifically on the Cycle struct, since they are provided "for free" by a blanket impl.  If there's no way to do so, then the "cure" of fixing this might be worse than the disease.  Maybe document it?

**Comment by jonas-schievink** [comment]
This might also be useful as a clippy lint

**Comment by memoryruins** [comment]
clippy catches cases with the `infinite_iter` lint.

Since it's in the `correctness` category, It is enabled by default when clippy runs.
https://rust-lang.github.io/rust-clippy/master/index.html#infinite_iter

There is a `maybe_infinite_iter` lint, but it is disabled by default since it's in the `pedantic` category.
https://rust-lang.github.io/rust-clippy/master/index.html#maybe_infinite_iter

**Comment by jonas-schievink** [comment]
Closing in favor of that lint. If there's any improvements to it that should be made, an issue should be filed at https://github.com/rust-lang/rust-clippy
