### ISSUE TITLE
Macros ignore formatting

### ISSUE THREAD

**Issue by Fihtangolz** [rust-lang/rust#59709]
TokenStream or TokenTree after converting to string lose formatting (for example tabs, newline characters, number of spaces). This may be a problem in the following cases:
* if you are using python or another language for which formatting is important
* you write a piece of text
* you want to transfer some data to another program for which formatting is important
* your sense of beauty does not allow you to use auto-formatting

**Comment by ExpHP** [comment]
Even if whitespace was preserved, macros would be inappropriate for arbitrary text.  For instance, consider the following snippet of python:

```python
# Get the sum of elements in the range [begin, end)
def sum_range(xs, begin, end):
    return sum(xs[begin:end])
```
which the rust lexer would consider to have unbalanced brackets.

If formatting is important, you should put it in a string literal.  

```rust
the_macro!{r##"
def foo(x):
    pass
"}
```

**Comment by Fihtangolz** [comment]
Raw literals look terrible. I hint that why can't we have something like proc_macro::RawText?

**Comment by ExpHP** [comment]
They can't be that bad; raw literals look exactly like the text you want, except with a little header and footer.  (and maybe it'd be nice to strip a leading indent; there's the [indoc](https://crates.io/crates/indoc) crate for that)

`proc_macro::RawText` couldn't work because rust must tokenize the macro input merely to find out where the macro invocation ends:

* Rust macros support comments in their input.  Closing braces in these comments should not end the macro call.
* Rust macros support string literals in their input.  Closing braces in these strings should not end the macro call
* Rust macros support nested `[] () {}`.  If you have a macro call like `mac!{{{}}}`, the first `}` should not end the macro.

The only way a macro taking "raw text" could work is if it was delimited by some magic string, like bash heredocs or something:

```
let PYTHON: &'static str = mac!<BANANAS
# Get the sum of elements in the range [begin, end)
def sum_range(xs, begin, end):
    return sum(xs[begin:end])
BANANAS
;

fn main() {
    ...
}
```

...which, if you think about it, is more or less exactly how a raw string literal works.
