### ISSUE TITLE
Memory leak when sending/receiving mpsc or crossbeam channel

### ISSUE THREAD

**Issue by pusateri** [rust-lang/rust#59944]
I may be doing something wrong but I was seeing a memory leak using both crossbeam and mpsc channels and so I created a simple loop program that replicates the leak. I would expect the message over the channel to be freed once it is received but the program memory grows without bound.

% rustc --version
rustc 1.34.0 (91856ed52 2019-04-10)
% rustup toolchain list
stable-x86_64-apple-darwin (default)
```
use std::sync::mpsc::channel;
use std::thread;

fn main() {

    let (send, recv) = channel();

    thread::spawn(move || {
        for x in recv.iter() {
            println!("Got: {}", x);
        }
    });

    let mut i = 0;
    loop {
        send.send(i).unwrap();
        i += 1;
    }
}
```

Here's the crossbeam version too:
```
use crossbeam_channel::unbounded;
use std::thread;

fn main() {

    let (send, recv) = unbounded();

    thread::spawn(move || {
        for x in recv.iter() {
            println!("Got: {}", x);
        }
    });

    let mut i = 0;
    loop {
        send.send(i).unwrap();
        i += 1;
    }
}
```

**Comment by jonas-schievink** [comment]
Your senders are sending data faster than it can be processed. Use a bounded channel if you want to limit the queue size.

**Comment by pusateri** [comment]
Ok, that's not the case with my original program. I will try to replicate this without the tight loop because I think there is still a problem here.

**Comment by erictapen** [comment]
@pusateri Did you find a solution for this? I think the observed memory growth is intentional here (at least in the `mpsc` case), as when the `recv` half is cloned in a later part of the program it will still `recv()` all the messages ever sent, regardless of how long the sending dates back.

I just stumbled over this in a case, where I create a channel at startup and then handle websocket connections by feeding them the content of the channel. This would not be sustainable regarding memory usage. Maybe the documentation for `std::sync::mpsc::channel` could be improved here, in the regard that what once is sent into the channel will stay in memory as long as any of the two halves are in scope?

**Comment by pusateri** [comment]
I rewrote my code so as not to hit this so I can't say if it persists.

**Comment by MitchellRhysHall** [comment]
I fixed this issue by creating a manual buffer on the main thread using mpsc::sync_channel. As noted by [jonas-schievink](https://github.com/jonas-schievink) this is caused by a tight loop in the worker thread sending more messages than can be handled properly by the main thread.
