### ISSUE TITLE
Proc macro errors can lead to rustc panics at stage1 or on non-Linux

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#59998]
**Update (by @eddyb)**: this also occurs with `x.py test --stage 1 src/test/ui` on Linux (and is responsible for several `// ignore-stage1` in `src/test/ui`), so I'm updating the title to reflect it.
See also https://github.com/rust-lang/rust/issues/59998#issuecomment-483580082 for more details.

<hr/>

Discovered at https://github.com/rust-lang/rust/pull/59769#issuecomment-483017515: running the `ui\proc-macro\invalid-punct-ident-*.rs` tests on some platforms (observed on Windows and macOS but not on Linux) leads to things like
```
thread 'rustc' panicked at 'unsupported character `'`'`', src\libsyntax_ext\proc_macro_server.rs:315:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
being printed on stderr.

Cc @eddyb

**Comment by RalfJung** [comment]
This seems to also happen on macOS. Just not on Linux. @eddyb speculated that this is about whether libstd is shared between the proc macro client and server. I do not know what that means.

**Comment by eddyb** [comment]
Statically linked Rust libraries (such as libcore or libstd) can be duplicated between non-Rust "final" artifacts (e.g. binaries, or `cdylib`s, and the latter is what proc macros are).

That is, you can end up with several copies of libstd's functions *and globals* in one process, if you dynamically load a Rust `cdylib` / proc macro crate.
The functions aren't really an issue, but globals control panicking, and this means that a proc macro is not guaranteed to use the same panicking "global state machine" as the rustc that loaded it.

We account for this in terms of catching panics and transporting them over RPC, but we've forgotten to do the "stderr printing bypass" for panics happening on the server-side (i.e. caused by rustc handling a request from a proc macro client), we're only bypassing the printing for panics that happened client-side.

Also, to be clear, sharing libstd's *is not* the solution, but rather Linux is *hiding* an issue because it *happens to* do so (and this is not the case at e.g. stage1, because the server and client libstd's are incompatible).
https://github.com/rust-lang/rust/pull/59769#issuecomment-483037771 has more info on what we might do to fix this.

**Comment by pnkfelix** [comment]
triage: P-medium. Leaving nomination tag in hopes we can discuss at meeting.

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting. self-assigning. unnominating.

**Comment by eddyb** [comment]
Not sure yet if relevant, but: turns out my expectation of proc macros being "most `cdylib`" is wrong because (more details here: https://github.com/rust-lang/rust/issues/99909#issuecomment-1199945273) of this bail-out: https://github.com/rust-lang/rust/blob/9067d5277d10f0f32a49ec9c125a33828e26a32b/compiler/rustc_codegen_ssa/src/back/linker.rs#L651-L661

AFAICT that's what's causing proc macro dylibs to have so many dynamic exports (instead of exactly one, the `proc_macro_decls` or w/e it's called) - and if all it takes for the panic runtimes to conflict is dynamic linking to unify one of those symbols, that might be what's been causing all of these issues for years and we just didn't look in the right place...
