### ISSUE TITLE
Stabilize the core::array module and reexport in std (for TryFromSliceError)

### ISSUE THREAD

**Issue by ollie27** [rust-lang/rust#60014]
[`TryFromSliceError`](https://doc.rust-lang.org/nightly/core/array/struct.TryFromSliceError.html) has been stabilized in [`core::array`](https://doc.rust-lang.org/nightly/core/array/index.html) but `core::array` is an unstable module. Additionally `TryFromSliceError` isn't re-exported anywhere in `std`. There isn't even a `std::array` module to re-export it into.

cc @rust-lang/libs

**Comment by jonas-schievink** [comment]
cc @rust-lang/release another missed libstd reexport

**Comment by Centril** [comment]
Can @rust-lang/libs confirm that you wish to stabilize `TryFromSliceError` in `core::array`?

**Comment by alexcrichton** [comment]
I suspect that we want this type stable but probably not in `core::array` but rather in `{core,std,alloc}::slice`.

**Comment by SimonSapin** [comment]
The libs team discussed this in today’s triage meeting. `std::slice` was suggested as an alternative location for this type, but David pointed out that `array::TryFromSliceError` reads better than `slice::TryFromSliceError`. Additionally, we expect to have more array-related APIs (e.g. iterator types) in the future. So consensus was to **stabilize the array module** and reexport it in `std`.

We feel comfortable backporting this to beta, but backporting to stable and mentioning this in a point release blog post seems excessive. This error type is part of another of a return type in another API and typically does not need to be named.

Since `std::array` hasn’t been proposed before, let’s do the process dance:

@rfcbot fcp merge
