### ISSUE TITLE
Rustdoc shows a _DERIVE_..._FOR_... const when HashStable is derived

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#60150]
Eg https://doc.rust-lang.org/nightly/nightly-rustc/rustc/mir/constant._DERIVE_rustc_data_structures_stable_hasher_HashStable_rustc_ich_StableHashingContext_ctx_FOR_CastKind.html

List of all of these items in `rustc::mir`:

![Screenshot_2019-04-21 rustc mir - Rust](https://user-images.githubusercontent.com/17426603/56470064-2a313d80-6442-11e9-964e-193147c93622.png)

**Comment by euclio** [comment]
I'm working on this.

**Comment by euclio** [comment]
So, this is trickier than I thought. The `_DERIVE_` constants are an [implementation detail of synstructure](https://docs.rs/synstructure/0.10.1/synstructure/struct.Structure.html#hygiene), which are used to ensure hygiene for the generated impls. They appear because we pass `--document-private-items` while generating the compiler docs.

I thought that I would be able to add `#[doc(hidden)]` to synstructure, but unfortunately the `--document-private-items` flag also removes the `strip-hidden` pass.

I suppose we have two options:

1. Modify synstructure to add `#[doc(hidden)]` to the generated constants, and modify rustbuild to keep the `strip-hidden` pass when generating compiler docs.
2. Wait until synstructure can achieve the same hygiene effect through a feature like [underscore constants](https://github.com/rust-lang/rust/issues/54912).
