### ISSUE TITLE
Confusing error message: "expected 2 lifetime parameters"

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rust#60216]
This code:

```rust
pub fn cli_args() -> clap::App<'_, '_> {
    clap_app! {foo =>
        (about: "foo the bar.")
    }
}
```

Gives me the following error:

```
error[E0106]: missing lifetime specifiers
  --> src/analysis.rs:10:32
   |
10 | pub fn cli_args() -> clap::App<'_, '_> {
   |                                ^^ expected 2 lifetime parameters
```

But I do have 2 lifetime parameters?

**Comment by estebank** [comment]
CC https://github.com/rust-lang/rust/issues/60199 which shows how you can easily end with this code thanks to compiler suggestions.

I believe the parser is unifying the two lifetimes as one because they have the same name. @nikomatsakis was this intended? I was under the impression that multiple uses `'_` would always introduce a new lifetime. The fix is either for changing the current behavior to accept this code, or fix the diagnostics and suggestions to explain the need for named lifetimes in this case.

**Comment by estebank** [comment]
It does seem like accepting only one `'_` lifetime was intentional:

https://github.com/rust-lang/rust/blob/e938c2b9aae7e0c37c382e4e22bdc360e9a4f0b6/src/librustc/middle/resolve_lifetime.rs#L2204-L2208

**Comment by mark-i-m** [comment]
In that case, the error just needs to be updated to say "only one elided lifetime is allowed" or something. But I'm very curious why that is the case.

**Comment by mark-i-m** [comment]
Hmm... also what are the odds that the same error was reported less than a day ago? Is this a regression or has it always done this?

**Comment by estebank** [comment]
Changing the code I linked above to be `Elide::FreshLateAnon(Cell::new(lifetime_count as u32))` with the following code

```
struct S<'a, 'b> {
    a: &'a usize,
    b: &'b usize,
}

fn foo() -> S<'_, '_> {
    unimplemented!();
}
fn main() {
}
```

emits the following output (and changes some existing tests' output the same way)

```
error[E0581]: return type references an anonymous lifetime which is not constrained by the fn input types
 --> file.rs:6:13
  |
6 | fn foo() -> S<'_, '_> {
  |             ^^^^^^^^^
  |
  = note: lifetimes appearing in an associated type are not considered constrained
```

---

> Is this a regression or has it always done this?

It's always been the case since stabilization in 1.26, and probably since Jan 2017 when the code was originally written. My guess would be the "hidden lifetime parameters in types are deprecated" landing recently causing this type of code more likely to appear due to suggestions.

---

I believe that this can be solved as a simple diagnostics fix, but am intrigued at how to communicate why `S<'_, '_>` isn't valid (sure, we can say that it is hard to decide what lifetime goes with what, but it sounds like a cop-out).

**Comment by mark-i-m** [comment]
There is always that compiler buzzword: _ambiguous_ :stuck_out_tongue:

**Comment by estebank** [comment]
> There is always that compiler buzzword: _ambiguous_

> me: _writes code_
> `rustc`: 🤷ZWJ🦀

**Comment by estebank** [comment]
@joelparkerhenderson we do so when possible, but it is considered acceptable (at the very least tolerated) if a suggestion gives you wrong code that a subsequent compilation will receive a new suggestion that _does_ get you to working code.

**Comment by kadiwa4** [comment]
The error message is helpful now (nightly 2023-01-15, clap 2.34.0):
```
error[E0106]: missing lifetime specifiers
 --> lib.rs:3:32
  |
3 | pub fn cli_args() -> clap::App<'_, '_> {
  |                                ^^  ^^ expected named lifetime parameter
  |                                |
  |                                expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime
  |
3 | pub fn cli_args() -> clap::App<'static, 'static> {
  |                                ~~~~~~~  ~~~~~~~
```
