### ISSUE TITLE
Use of uninitialized variable after pattern error

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/rust#60350]
The following code reports a warning that `x` is uninitialized as well as the expected pattern error.

```rust
fn destructure_slice(s: &[i32]) {
    let [x] = *s;
    drop(x);
}
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a728ed9d4b08603379abc7d7a70c966e)

**Comment by Pulkit07** [comment]
I will like to work on this bug.

On initial findings, the initial pattern error is coming from https://github.com/rust-lang/rust/blob/master/src/librustc_mir/hair/pattern/check_match.rs#L261.

My hypothesis is that because of the pattern error, we don't add x to a list of initialized variables and hence we get the uninitialized error.

Does that sounds like a good start?

**Comment by matthewjasper** [comment]
The place to start looking would be here: https://github.com/rust-lang/rust/blob/472211ab0ae2beec0fbec23c7f90f5d15c51317d/src/librustc_mir/build/matches/mod.rs#L417

You'll need to use the functions in `rustc_mir::build::matches::test` to extract any bindings from the `match_places`.

**Comment by Centril** [comment]
@matthewjasper We now have two errors instead... is there anything more to do here, e.g. improving diagnostics?
