### ISSUE TITLE
How does one build cargo from scratch?

### ISSUE THREAD

**Issue by filmil** [rust-lang/rust#60490]
The default installation script does not install cargo.  The [cargo install-from-source instructions][1] say that a preexisting installation of cargo is required to install cargo.

So, how does one build and install cargo purely from source?

[1]: https://github.com/rust-lang/cargo

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

I'm not sure what you're trying to accomplish, but since the Rust toolchain is bootstrapped, you need to build off of the prebuilt bootstrap toolchain. For new architectures, you generally start with a cross-compiler that works on a supported architecture and then build the toolchain for the new target.

**Comment by filmil** [comment]
The concrete small feature request here would be to describe how one can build rustc and cargo from source, starting from checked out source.  Or at least a pointer to where such an approach is described.

**Comment by jonas-schievink** [comment]
I think what you want is to set `extended = true` in [config.toml](https://github.com/rust-lang/rust/blob/08bfe16129b0621bc90184f8704523d4929695ef/config.toml.example#L186) before building.
