### ISSUE TITLE
Add `get` and `get_unchecked` to `*const [T]` and `*mut [T]`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#60639]
If one has a `*const [T]` and wants a pointer to a specific element of that slice, one needs to go through a reference and index, or cast the pointer to `*const T` and offset that by the number of elements (which doesn't do a length check, so you need that, too). I propose that we add two new methods to `*const [T]` and `*mut [T]`:

```rust
impl<T> *const [T] {
    fn get(self, idx: usize) -> Option<*const T>;
    unsafe fn get_unchecked(self, idx: usize) -> *const T;
} 
```

`get_unchecked` is unsafe, because if a large index is used, one may overflow the pointer, which is UB

To make the implementation of `get` simpler, I propose to additionally add a `len` method:

```rust
impl<T> *const [T] {
    fn len(self) -> usize;
}
```

cc @RalfJung @shepmaster

**Comment by shepmaster** [comment]
My specific case would have been for `*mut T` — is that deliberately omitted?

**Comment by oli-obk** [comment]
no, I'm just lazy and didn't want to type everything twice. There should be an equivalent of all the above for `*mut [T]`

**Comment by Stargateur** [comment]
Pardon me if It's stupid but why not just let the user go from `*const [T]` to `&[T]` ?

```rust
fn main() {
    let x_ptr = &[1, 2, 4] as *const [_];
    
    unsafe {
        let x = &*x_ptr;
        println!("{:?}", x.get(1).map(|x| x as *const _));
        println!("{:?}", x.get_unchecked(1) as *const _);
    }
}
```

Is that really to long to write ? Also, worse to ask, when do you need a `*const [T]` ?

**Comment by shepmaster** [comment]
The original context was this code:

```rust
use std::collections::BTreeSet;

fn uniq_refs<'i, 'd: 'i, T>(
    data: &'d mut [T],
    indices: &'i BTreeSet<usize>,
) -> impl Iterator<Item = &'d mut T> + 'i {
    let in_bounds_indices = indices.range(0..data.len());

    in_bounds_indices.map(move |&i| {
        // I copied this from a Stack Overflow answer 
        // without reading the text that explains why this is safe
        unsafe {
            let r = data.get_unchecked_mut(i);
            let p: *mut T = r;
            &mut *p
        }
    })
}
```

Miri detects that this usage triggers undefined behavior:

```rust
use std::iter::FromIterator;

fn main() {
    let mut scores = vec![1, 2, 3];
    let indices = BTreeSet::from_iter(vec![0, 2]);

    let selected_scores: Vec<_> = uniq_refs(&mut scores, &indices).collect();
    for score in selected_scores {
        *score += 1;
    }
}
```

I wanted to make use of `get_unchecked_mut`, but that function requires unique access to `data`. That's invalid here because there's an outstanding mutable reference to a `T` from inside the slice. The non-UB form of this involves getting a raw pointer to the data and performing offsets:

```rust
fn uniq_refs<'i, 'd: 'i, T>(
    data: &'d mut [T],
    indices: &'i BTreeSet<usize>,
) -> impl Iterator<Item = &'d mut T> + 'i {
    let start = data.as_mut_ptr();
    let in_bounds_indices = indices.range(0..data.len());
    in_bounds_indices.map(move |&i| unsafe { &mut *start.add(i) })
}
```

With the proposed functions, that code could look like

```rust
fn uniq_refs<'i, 'd: 'i, T>(
    data: &'d mut [T],
    indices: &'i BTreeSet<usize>,
) -> impl Iterator<Item = &'d mut T> + 'i {
    let start = data as *mut [T];
    let in_bounds_indices = indices.range(0..data.len());
    in_bounds_indices.map(move |&i| unsafe { &mut *data.get_unchecked(i) })
}
```

**Comment by RalfJung** [comment]
Yeah, this seems reasonable. However, I think it should be seen in the context of our general need for [a better story for raw pointers](https://internals.rust-lang.org/t/need-for-operator-for-unsafe-code-guidelines/10022/48?u=ralfjung).

**Comment by scottmcm** [comment]
```rust
impl<T> *const [T] {
    fn get(self, idx: usize) -> Option<*const T>;
}
```
Wouldn't that need to be `unsafe` for the same reason as `offset`?

**Comment by oli-obk** [comment]
Since it would be bounds-checked, you can't overflow, so `get` should be safe

**Comment by oli-obk** [comment]
Ah no, you're right. One can create a wrong slice that would overflow for some indices...

**Comment by RalfJung** [comment]
It could use `wrapping_offset`, though. Then it could be safe.

**Comment by Stargateur** [comment]
just to note that in C, it's UB to create a out of bound pointer of more than len, for exemple:

```c
char *ptr = malloc(42); // assert no null
char *ub = ptr + 43;
```

Look like Rust allow this, but use raw pointer is often use with C binding, I just through this could be useful to know.

**Comment by rkruppe** [comment]
But then people would have a performance incentive to not use the clearer and more convenient method. And what for? If one uses this method they'll almost always go on to access memory through the resulting pointer, and then they'd almost certainly have UB anyway if the index is too large or goes otherwise out of bounds. While wrapping_offset does allow "allocation crossing" with a suitably crafted offset, this is extremely rare and so I don't see why we should prioritize it in a convenience method.

**Comment by RalfJung** [comment]
> But then people would have a performance incentive to not use the clearer and more convenient method. 

If they want the performance, wouldn't they use `get_unchecked` anyway? Seems like if you care about whatever LLVM gets from knowing there is no overflow, you'll also want to bounds check.

**Comment by rkruppe** [comment]
> Put differently, what is even the point of _having_ `get` if it is not safe?

This is a good question. I feel like the answer might well be "there is no point to having `get`". Is there anything useful one can do with `get` that doesn't already require knowing the preconditions of `get_unchecked` are met? If the resulting pointer is not good to dereference (e.g., because the `*[T]` was dangling) one could still compare the resulting pointer safely, but is that ever useful by itself? (The aforementioned jumping between allocations in ways that still result in dereferenceable pointer is too niche to justify the existence of the method.)

I can see some potential value in how an unsafe `get` could *simplify* proof obligations, though. Assume `get` does bounds checking against the claimed length of the slice, but uses `offset` if the bounds check passes and hence has UB if the ptr/length pair is "wrong" (e.g., dangling pointer, excessive length). Using this method soundly only requires only knowing that the raw slice pointer you have is "correct", you don't have to worry at all about the values you use as indices because all your accesses are bounds-checked against the length of the slice. A complete characterization of when the slice is "correct" for this purpose could get complicated, but many simple common cases are obviously fine, e.g.:

- if you got the pointer from a safe slice reference (that's not been invalidated since)
- if you called `alloc(Layout::array<T>(n))` and turned the resulting pointer into a slice of length `n` (and haven't deallocated the memory since then)

I believe this distinction between trusting the slice and trusting the indices also answers this question:

> If they want the performance, wouldn't they use get_unchecked anyway?

They might need the bounds-check anyway (because the indices are untrusted) and then they might as well leave that to the standard library rather than open-coding it.

**Comment by gnzlbg** [comment]
> To make the implementation of get simpler, I propose to additionally add a len method:

For that `len` method to be safe, it would need to panic if `*mut [T]` is null, and it would either need to panic if the pointer is not properly aligned, or do an unaligned ptr read of the len.

**Comment by RalfJung** [comment]
@gnzlbg why that? A `*mut [T]` is a `(*mut T, usize)`, and to read the `usize` we don't care if the pointer is NULL or unaligned.

**Comment by gnzlbg** [comment]
> And we can assume that this pair itself is well-aligned

I was missing this, makes sense. 

> to read the usize we don't care if the pointer is NULL

So does this mean that if the pointer is NULL, the len must be zero, or else the pointer is invalid ?

**Comment by RalfJung** [comment]
It's a raw pointer, I don't think we are making any such requirements. Both pointer and integer can be just about anything that a `*mut T` or `usize` can be.

**Comment by RalfJung** [comment]
So, in terms of implementing this as an unstable feature... the main problem is that we want these to be inherent methods on `*const [T]`, right? AFAIK this needs some rustc magic and lang items as those types are not defined in any crate, and thus cannot usually get inherent methods?

**Comment by oli-obk** [comment]
Yea, we need to add the same kind of magic that the integer types have in https://github.com/rust-lang/rust/blob/1572c433eed495d0ade41511ae106b180e02851d/src/libcore/num/mod.rs#L2380-L2381

Though in this case it may be more difficult due to the involved generics, so you should look at the implementation of the magic for slices for inspiration:

https://github.com/rust-lang/rust/blob/1572c433eed495d0ade41511ae106b180e02851d/src/libcore/slice/mod.rs#L56-L58

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/71082 does all the hard parts here -- now adding more raw slice methods (like indexing) is a libcore-only patch, rustc does not need any further changes.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/73986 should resolve this.

**Comment by WaffleLapkin** [comment]
The checked version,
```rust
impl<T> *const [T] {
    fn get(self, idx: usize) -> Option<*const T>;
}
```
wasn't implemented. Why?

**Comment by RalfJung** [comment]
As far as I am concerned, mostly due to lack of imagination -- I figured if you'd want checks you'd use references, not raw pointers. The return type `Option<*const T>` is also strange, note that this one cannot be enum-niche-optimized.
