### ISSUE TITLE
Weird generated documentation with const generics

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#60737]
When playing around with const generics, I found some weird generated docs:

http://prntscr.com/nn8fgg

How to reproduce:
```
git clone https://github.com/DutchGhost/vecset.git
cd vecset
cargo doc --open
```
and go to the documentation on the VecSet struct (inside the vecset module), and find the auto impls.

**Comment by jonas-schievink** [comment]
My guess is that rustdoc just doesn't yet handle const generics properly

**Comment by varkor** [comment]
Support for const generics in rustdoc has not been tested very thoroughly at all (I don't think there are any tests in the test suite for it at all yet). We also have a number of issues with pretty-printing consts (https://github.com/rust-lang/rust/issues/60738). That said, I imagine this would not be too difficult to fix: we're getting the right parameter — we're just debug printing it instead of pretty-printing it.
