### ISSUE TITLE
Test overflows stack as a doctest, but runs fine as a regular test

### ISSUE THREAD

**Issue by LPGhatguy** [rust-lang/rust#60753]
I recently added this doc test to the `lib.rs` of my crate:

https://github.com/LPGhatguy/rbx-dom/blob/493ce5a4f5c3da6932c51e003987e2cbd69eecf7/rbx_xml/src/lib.rs#L13-L39

When I try to run it through `cargo test`, I get a stack overflow that contains none of my own code, and not very many stack entries:

![dpX8vyi](https://user-images.githubusercontent.com/654598/57576788-13688000-741d-11e9-8515-3a60371319a2.png)

When I run this same test as a regular test, it passes just fine.

I tried running the test on today's nightly, as well as with a larger stack (`RUSTFLAGS="-C link-args=/STACK:8194304" cargo t`) and it still occurs. After talking with Arnavion on IRC, I verified the stack size using dumpbin.

Wrapping the entire doctest in `std::thread::spawn(|| { ... })` causes the test to no longer overflow the stack.

This issue **does not** happen on Linux on Travis-CI; here are the test results for Rust 1.31.0 and 1.34.1 (stable) for the same commit: https://travis-ci.org/LPGhatguy/rbx-dom/builds/531288814

Config:
- Windows 10 v1809
- VS Build Tools 2017
- rustc 1.34.1 (fc50f328b 2019-04-24)

**Comment by Arnavion** [comment]
The `generate_classes` function is called from the main thread of the doctest binary, and about 0x4460 bytes of stack is used before the function is called. It then attempts to allocate another 0x147100 bytes. The `__chkstk` in the prolog attempts to validate that `0x4460 + 0x147100` is valid, hits the guard page (default stack for main thread on Windows is 1 MiB == 0x100000) and reports the overflow.

As for *why* the function uses > 1 MiB stack space, it happens to be a 33,000-line beast of generated code, that creates 6,622 instances of `Cow::Borrowed(&'static str)` temporaries to populate a bunch of `HashMap`s. From inspecting the disassembly, almost all the `+0x100000` and higher offsets on the stack are used to store the `1` corresponding to the `Cow::Borrowed` discriminant. So it's likely to be expected behavior from an unoptimized debug build.

We validated on IRC that:

- `cargo test --release` works fine, since it probably does not waste space allocating each temporary in unique locations.

- Compiling with `RUSTDOCFLAGS='-C link-arg=/STACK:8194304'` works fine. It didn't work in the OP case because it used `RUSTFLAGS` which is not used for compiling doc tests.

- Moving the doctest function body into a `std::thread::spawn()`ed thread works fine, since non-main threads have larger stacks.

**Comment by jyn514** [comment]
Is this actually a bug? It sounds like this was very close to the memory limit already and running in rustdoc just happened to push it over the edge.

FWIW I can't replicate this on Linux.

**Comment by Arnavion** [comment]
As I wrote in my comment, no it's not a bug but just expected behavior for such a function, and yes the default limit of 1MiB for the main thread stack is for programs linked with the Windows (MSVC) linker.

**Comment by jyn514** [comment]
I'm going to close this, I don't think rustdoc can do much about taking up slightly more stack space than rustc.
