### ISSUE TITLE
error for too many trailing #s in raw string literals could be improved

### ISSUE THREAD

**Issue by fbstj** [rust-lang/rust#60762]
for example ([play](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=30cb101c03c070947da815e108333c93))
```rust
let foo = r##"bar"###;
```
results in
```
error: expected one of `.`, `;`, `?`, or an operator, found `#`
 --> src/main.rs:2:25
  |
2 |     let foo = r##"bar"###;
  |                         ^ expected one of `.`, `;`, `?`, or an operator here
```

while too few has a much nicer error:

```
error: unterminated raw string
 --> src/main.rs:3:15
  |
3 |     let baz = r##"quxx"#;
  |               ^ unterminated raw string
  |
  = note: this raw string should be terminated with `"##`
```

This issue has been assigned to @rcoh via [this comment](https://github.com/rust-lang/rust/issues/60762#issuecomment-605386317).

**Comment by hellow554** [comment]
Gonna work on it (first working on the compiler internals, so please bear with me :) )

**Comment by estebank** [comment]
Feel free to ask for help!

**Comment by hellow554** [comment]
I indeed have a question @estebank. The fatal error itself is emitted at https://github.com/rust-lang/rust/blob/80e7cde2238e837a9d6a240af9a3253f469bb2cf/src/libsyntax/parse/parser.rs#L729 but my logic is currently somewhere around https://github.com/rust-lang/rust/blob/80e7cde2238e837a9d6a240af9a3253f469bb2cf/src/libsyntax/parse/lexer/mod.rs#L1163-L1240

I don't see how I can add labels to that error message without actually creating my own fatal which would most likely will end up in code duplication.

Solutions I see:
  1. Emit my own fatal which is very similar to the one already emitted
    * downside would be code duplication and increased complexity
    * plus would be, same error message as before
  2. Emit a warning with the suggested solution
    * downside, more text, 
    * plus, very little additional code needed
  3. Emit a different error than we do now
    * downside, another error, which might ne not suitable, because the current one is already very good
    * plus, very little additional code needed

This is what my solution currently looks like. I find it way too verbose (maybe because I use `help` instead of `label`s.

```
op@VBOX ~/m/rust2> build/x86_64-unknown-linux-gnu/stage1/bin/rustc src/test/ui/parser/raw/raw-literal-too-many.rs
warning: The raw string needs 2 trailing `#`, but found 3
 --> src/test/ui/parser/raw/raw-literal-too-many.rs:2:26
  |
2 |     let _foo = r##"bar"###;
  |                          ^
  |
help: remove this `#`
 --> src/test/ui/parser/raw/raw-literal-too-many.rs:2:26
  |
2 |     let _foo = r##"bar"###;
  |                          ^

error: expected one of `.`, `;`, `?`, or an operator, found `#`
 --> src/test/ui/parser/raw/raw-literal-too-many.rs:2:26
  |
2 |     let _foo = r##"bar"###;
  |                          ^ expected one of `.`, `;`, `?`, or an operator here

error: aborting due to previous error
```

**Comment by hellow554** [comment]
In addition to too many `#`, I was looking at the case where there are less `#` than expected, but not in the same line, but over a lot of lines (in my newly added testcase there are 18 lines now).
I would like to improve that error message as well, something like:

```
error: unterminated raw string
  --> $DIR/raw-string-long.rs:2:13
   |
LL |     let a = r##"This
   |             ^
   |             started here with 2 `#`
...
   |
LL |        ends"#;
   |             ^ ended here with only 1 `#`
   |             help: close the raw string with `"##`

error: aborting due to previous error
```

I'm not sure about how to do that, if I just can use a span from the very beginning to the end and it will leave out the intermediate lines automatically or do I have to do something about that?

**Comment by hellow554** [comment]
I looked at the first implementation of this cc #48546 @GuillaumeGomez . What do you think about this?

**Comment by GuillaumeGomez** [comment]
That might make things more clear, indeed. :+1:

**Comment by estebank** [comment]
> I'm not sure about how to do that, if I just can use a span from the very beginning to the end and it will leave out the intermediate lines automatically or do I have to do something about that?

@hellow554, you should be able to synthesize a span that covers the entire closing sigil (`"####`) [where we look for it and break if we don't find it](https://github.com/rust-lang/rust/blob/80e7cde2238e837a9d6a240af9a3253f469bb2cf/src/libsyntax/parse/lexer/mod.rs#L1207-L1213). We should hold a vec of spans that we add to every time we find them, because it is possible that we indeed have a raw string that contains `"#` multiple times and we can't assume that the first we find is correct. We could have some extra smarts in case we were writing something like `r###"r##"r#""#"##"###` or `r#"r##"r#""#"##"###` to avoid suggesting all three closing spans, but for now the naïve way should be fine.

For the too many `#` at the end, you could [proactively look for them before the `break`](https://github.com/rust-lang/rust/blob/80e7cde2238e837a9d6a240af9a3253f469bb2cf/src/libsyntax/parse/lexer/mod.rs#L1213), by following case 1 and using something like
```
let lo = self.span;
let mut too_many = false;
while self.ch_is('#') {
    too_many = true;
    self.bump();
}
if too_many {
    let sp = lo.to(self.span);
    let mut err = self.sess.span_diagnostic.struct_span_err(sp, "too many `#` when terminating raw string");
    err.span_label(sp, "too many `#` for raw string");
    err.hidden_span_suggestion(
        sp,
        "remove the unneeded `#`"
        String::new(),
        Applicability::MachineApplicable,
    );
    err.emit();
}
```

By doing this, the parser (the lexer, rather) will continue on its merry way and parse the rest of the file as if nothing had happened.

**Comment by hellow554** [comment]
Thanks estebank. That was very helpful indeed. I haven't thought of consuming the bad characters so that the lexer can do the rest for me. Very nice.
I'm a bit undecided where the journey goes. Currently I have this:

```
error: too many `#` when terminating raw string
 --> src/test/ui/parser/raw/raw-literal-too-many.rs:2:15
  |
2 |     let foo = r##"bar"####;
  |               ^^^^^^^^^^--
  |               |         |
  |               |         help: remove the unneeded `#`
  |               The raw string needs 2 trailing `#`, but found X
```

This is nice and looks very neat :) This is not a hidden suggestion as you see, is that okay for you as well? I mean, yes, it's kind of obvious which ones to remove, but I also like the expressiveness here.

**Comment by hellow554** [comment]
I also tried to add the text *"The raw string has {} leading `#`"*, but it looks very crowded to me, when the raw string only is one line.

```
op@VBOX ~/m/rust2> build/x86_64-unknown-linux-gnu/stage1/bin/rustc src/test/ui/parser/raw/raw-literal-too-many-long.rs
error: too many `#` when terminating raw string
  --> src/test/ui/parser/raw/raw-literal-too-many-long.rs:2:13
   |
2  |       let a = r##"This
   |               ^-- The raw string has 2 leading `#`
   |  _____________|
   | |
3  | |     is
4  | |     a
5  | |     very
...  |
19 | |     lines
20 | |     "###;
   | |        ^
   | |        |
   | |________help: remove the unneeded `#`
   |          The raw string needs 2 trailing `#`, but found 3

op@VBOX ~/m/rust2> build/x86_64-unknown-linux-gnu/stage1/bin/rustc src/test/ui/parser/raw/raw-literal-too-many.rs
error: too many `#` when terminating raw string
 --> src/test/ui/parser/raw/raw-literal-too-many.rs:2:15
  |
2 |     let foo = r##"bar"####;
  |               ^--^^^^^^^--
  |               ||        |
  |               ||        help: remove the unneeded `#`
  |               |The raw string has 2 leading `#`
  |               The raw string needs 2 trailing `#`, but found 4
```

Should I add an check if the raw string only spans over one line? If yes, how to do that? ^^

**Comment by estebank** [comment]
There are two options, either we don't use the full string's span (showing only the start and the end), or [use `is_multiline` to provide different output depending on the visual result](https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/_match.rs#L820-L844).

**Comment by hellow554** [comment]
That looks very promising! 

```
op@VBOX ~/m/rust2> build/x86_64-unknown-linux-gnu/stage1/bin/rustc src/test/ui/parser/raw/raw-literal-too-many-long.rs
error: too many `#` when terminating raw string
  --> src/test/ui/parser/raw/raw-literal-too-many-long.rs:2:13
   |
2  |       let a = r##"This
   |               ^-- The raw string has 2 leading `#`...
   |  _____________|
   | |
3  | |     is
4  | |     a
5  | |     very
...  |
19 | |     lines
20 | |     "###;
   | |______--^
   |        |
   |        ...but is closed with 3.
   = help: remove the unneeded `#`

op@VBOX ~/m/rust2> build/x86_64-unknown-linux-gnu/stage1/bin/rustc src/test/ui/parser/raw/raw-literal-too-many.rs
error: too many `#` when terminating raw string
 --> src/test/ui/parser/raw/raw-literal-too-many.rs:2:15
  |
2 |     let foo = r##"bar"####;
  |               ^--^^^^^----
  |                |      |
  |                |      ...but is closed with 4.
  |                The raw string has 2 leading `#`...
  = help: remove the unneeded `#`
```

The only thing is (that bugs me a little bit) are the `^^^` between the `----`. 

![grafik](https://user-images.githubusercontent.com/921462/57834672-19fc4c00-77bd-11e9-8854-d4408feb1c93.png)
 but I haven't found a way to get rid of them. I think it's okay, but they are not needed IMHO. Time to work on the other suggestion!

**Comment by hellow554** [comment]
Wow.. TIL the code for a raw string, aka `r#"foo"#` and a raw byte string aka `br#foo"#` are actually two different code paths... Let me try to merge them :/ (https://github.com/rust-lang/rust/blob/1962adea6ad9b992516ae56ad7f8c5bc33b951cb/src/libsyntax/parse/lexer/mod.rs#L1369-L1427 vs https://github.com/rust-lang/rust/blob/1962adea6ad9b992516ae56ad7f8c5bc33b951cb/src/libsyntax/parse/lexer/mod.rs#L1139-L1216)
I'm really going forward in this issue and I really like the architecture of the compiler (although it's confusing sometimes, because sometimes you need to pass a `&str` but sometimes a `String` which is kind of weird and has no reason, but meh... 🙄)

If you could me assist further with the error messages I would be happy.

**Comment by estebank** [comment]
> If you could me assist further with the error messages I would be happy.

@hellow554 Of course! Feel free to reach out with whatever problem you might face.

As for the output, I think the following should be ok for all cases (even though it hides a big of content in between that isn't strictly relevant):

```
error: too many `#` when terminating raw string
  --> src/test/ui/parser/raw/raw-literal-too-many-long.rs:2:13
   |
2  |       let a = r##"This
   |                -- this raw string has 2 leading `#`
...
20 |      "###;
   |       ^^^ this raw string is closed with 3 trailing `#`, but should be 2
   = help: remove the unneeded `#`

**Comment by hellow554** [comment]
Ummm.... not what I expected...... @pietroalbini this is not what I expected ^^

**Comment by pietroalbini** [comment]
@hellow554 that's the correct behavior: you can't be assigned to the issue directly because GitHub only allows organization members to be assigned to issues. The only way we have to get around that is to assign the bot itself and add a note in the top message that you're actually the one assigned.

**Comment by hellow554** [comment]
> @hellow554 that's the correct behavior: you can't be assigned to the issue directly because GitHub only allows organization members to be assigned to issues. The only way we have to get around that is to assign the bot itself and add a note in the top message that you're actually the one assigned.

Thanks for the clarification. I haven't seen the *"This issue has been assigned to @hellow554 via this comment."* in the top post. Thanks for that.

**Comment by rcoh** [comment]
@rustbot claim

Working on this now, should have a diff in a few days
