### ISSUE TITLE
Rustdoc doesn't allow to navigate to lines after 50000

### ISSUE THREAD

**Issue by Riateche** [rust-lang/rust#60948]
When I click on the `[src]` link of a function in the rendered documentation, if the function's line number is greater than 50000, the browser navigates to line 50000 instead of the proper location. I found the relevant code here:

https://github.com/rust-lang/rust/blob/3418d2f50867b2c179be4239aedfffef9a650d5f/src/librustdoc/html/static/main.js#L165

What's the rationale behind this limitation? Can it be lifted?

**Comment by Torrencem** [comment]
Interestingly, it looks like if this limit were removed, the for loop [here](https://github.com/rust-lang/rust/blob/3418d2f50867b2c179be4239aedfffef9a650d5f/src/librustdoc/html/static/main.js#L182) might be a problem. Then, maybe, someone could link to a url such as https://doc.rust-lang.org/src/.../something.rs.html#1-9007199254740992 which would make the page freeze up, since the loop won't exit early if the line doesn't exist. I don't know if this would be considered harmful, however

**Comment by Riateche** [comment]
The freeze in that `for` loop can be avoided with something like this:
```js
for (i = from; i <= to; ++i) {
    let element = document.getElementById(i);
    if (!element) { break; }
    addClass(element, "line-highlighted");
}
```

**Comment by GuillaumeGomez** [comment]
Wo, super strange old code as it seems. Good catch!
