### ISSUE TITLE
offline documentation isn't available on raspberry pi 3b+ running raspbian 

### ISSUE THREAD

**Issue by catastrop** [rust-lang/rust#61045]

**Comment by jonas-schievink** [comment]
What did you try to view the docs, and how did you install Rust?

If you installed Rust through apt-get, you should look for an extra documentation package to install (or, if the docs aren't packaged, talk to the Debian maintainers). If you used rustup, you should be able to read the docs by running `rustup doc --std`. What happens if you run that?

**Comment by mati865** [comment]
`rust-docs` component is unavailable on most of (all?) tier 2 platforms: https://rust-lang.github.io/rustup-components-history/aarch64-unknown-linux-gnu.html
I don't know the details here but it's probably related to lack of CI time.

**Comment by Mark-Simulacrum** [comment]
Yes, we don't currently provide this component, primarily due to CI time reasons. Closing in favor of https://github.com/rust-lang/rust/issues/52133 (though I'm about to close that as well).
