### ISSUE TITLE
azure: Merge most prepare steps into a single one on Azure

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#61167]
There are tons of steps in our Azure builds that install a thing or configure the environment, increasing clutter in the build page. We should try to merge them, with just a "Prepare `<platform>`" step for each platform.

**Comment by alexcrichton** [comment]
I definitely agree tha tthe UI seems a bit cluttered with all the skipped steps, but I personally find it much easier to follow if it's chunked up the way it is. For example there's a chunk of config to install Clang on OSX/Windows, but it's skipped on Linux. By seeing them together we can easily verify that they're downloading roughly the same thing from the same location, and we know what to update when one is updated.

I think it'd be great to consolidate where possible, though. For example all of `install-windows-build-deps.yml` could probably be one script or one step, but otherwise if there's shared work between platforms I think there's value gained from not worrying too much about the UI and making it easier to read/modify in-tree.

**Comment by pietroalbini** [comment]
> By seeing them together we can easily verify that they're downloading roughly the same thing from the same location, and we know what to update when one is updated.

Would you be ok with something like this?

```yaml
- bash: |
    set -e
    src/ci/prepare/install-clang.sh
    src/ci/prepare/install-sccache.sh
  displayName: Prepare macOS
  condition: ...

- bash: |
    set -e
    src/ci/prepare/install-clang.sh
    src/ci/prepare/install-sccache.sh
    src/ci/prepare/install-mingw.sh
  displayName: Prepare Windows
  condition: ...
```

We would still be able to update each step across all OSes by changing each file while having a clean UI.

**Comment by mati865** [comment]
@pietroalbini could you update this and other `azure-evaluation` issues?

**Comment by pietroalbini** [comment]
I don't think this is needed anymore.
