### ISSUE TITLE
fast path to detect tool breakage?

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#61256]
sometimes the following happens:

rust pr A breaks clippy
rust pr B gets tested
   clippy gets fixed
a rust pr C to fix clippy is opened
rust pr B gets merged and breaks clippy AGAIN
rust pr C gets tested
rust pr C fails and wastes ~3 hours of CI time 

I wonder if we could have a fast path that does not involve compiler bootstrap in order to determine if a tool will be fixed or not.

Would it to:
If ONLY the submodule is changed in the PR (because otherwise it may affect the compiler as well)
use the previous rustc master to build and run the tools tests.
If that works, start bootstrapping the compiler and test again.
If that fails, cancel the build immediately (after ~10-15 minutes instead of ~2 hours)

**Comment by Mark-Simulacrum** [comment]
I don't think this is really viable at this point (we don't have a way to install previous master commit); there is some background work in this area which will likely make something along these lines more viable in the future though; for now I'm going to close this since I don't think an issue will help it get implemented faster unfortunately.
