### ISSUE TITLE
Missed space optimization in enums with `rustc_layout_scalar_valid_range_X` attributes

### ISSUE THREAD

**Issue by jfrimmel** [rust-lang/rust#61352]
Since the introduction of the `NonZero`-types, it is possible to store information about the used enum variant without requiring extra space, e.g.:
```rust
use core::{mem::size_of, num::NonZeroUsize};

size_of::<Option<NonZeroUsize>>() == size_of::<usize>()
```
As far as i understand it, this is achieved by telling the compiler, that the lowest bit is always unused. This bit then can be used to differentiate between the Some() and None case. This works great today.

The point of this particular issue is the following: if you have a (custom) enum with two variants and both of them store such a type, the optimization described above has no effect.
This means, that the following code ([godbolt link](https://godbolt.org/z/IH23tp)) has a size of 8:
```rust
use core::{mem::size_of, num::NonZeroU32};
enum S {
    A(NonZeroU32),
    B(NonZeroU32),
}
size_of::<S>() == 8 // could be 4
```

I think it should be possible, especially since the "payloads" inside the enum variants are of the same type, that _rustc_ uses the lowest bit to select between `A` and `B`, whereas the rest of the bits are used to store the `NonZeroU32`. This would save 4 bytes.

Is that something, that can be achieved in some way? Of course, you can build such a type yourself, but you loose the ability to pattern-match, etc. which would come handy.

**Comment by jonas-schievink** [comment]
The compiler cannot use the lowest bit, only the value `0x00000000` is forbidden for `NonZeroU32`, so `0x00000001` would be valid.

**Comment by jfrimmel** [comment]
> The compiler cannot use the lowest bit, only the value `0x00000000` is forbidden for `NonZeroU32`, so `0x00000001` would be valid.

Oh, I see, that was an error on my side. Nevertheless there is some optimization space, though:

After a look at the source code of `NonZeroUsize` I have created this test code ([godbolt link](https://godbolt.org/z/gO7bY1)):
```rust
#![feature(rustc_attrs)]

#[repr(transparent)]
#[rustc_layout_scalar_valid_range_start(0x2)]
struct LowestBitUnused(u32);

enum S {
    A(LowestBitUnused),
    B(LowestBitUnused),
}
```
The size is still 8, although 4 would be enough, and there is enough space for the variant information (try to increase the `rustc_layout_scalar_valid_range_start` argument, it does not change the code).

But maybe this optimization is to much of a niche/edge case, even when rustc internals are used....

**Comment by scottmcm** [comment]
I suspect that the optimization wouldn't be legal.  Because for the size to be 4, that means that `S::B(LowestBitUnused(2))` would be a `3` in memory, but then if I get a `&mut LowestBitUnused` to the internals and write a `LowestBitUnused(4)` to it, it would overwrite the discriminant.

Also, `#[rustc_layout_scalar_valid_range_start(0x2)]` doesn't make the lowest bit unused, it means it can't be zero or one -- it can still be `3` or `4`, which have different values for the bottom bit.  But that's not the important example, because you just change the situation to `#[rustc_layout_scalar_valid_range_end(0x7FFF_FFFF)]` and then end up with the first problem again.

(The `Option` optimization is easier because there's nothing in a `None` to which to get a reference.)

**Comment by jonas-schievink** [comment]
Yeah, this could not be optimized like that.
