### ISSUE TITLE
regression: conflicting implementations of trait for Into<Box>

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#61471]
https://github.com/rust-lang/rust/issues/46328 is a very old similar issue

root: bow - 5 detected crates which regressed due to this; cc @clarcharr
<details>

```
 * hostman-0.4.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/hostman-0.4.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/hostman-0.4.0/log.txt); cc @lucascaro
 * multistr-0.5.4: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/multistr-0.5.4/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/multistr-0.5.4/log.txt); cc @clarcharr
 * parse-hosts-0.5.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/parse-hosts-0.5.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/parse-hosts-0.5.0/log.txt); cc @clarcharr
 * swc-hosts-0.2.1: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/swc-hosts-0.2.1/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/swc-hosts-0.2.1/log.txt); cc @clarcharr
 * lucascaro/hostman: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/gh/lucascaro.hostman/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/gh/lucascaro.hostman/log.txt); cc @lucascaro
```

</details>

root: pin-api - 1 detected crates which regressed due to this; cc @withoutboats
<details>

```
 * pin-api-0.2.1: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/pin-api-0.2.1/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/pin-api-0.2.1/log.txt); cc @withoutboats
```

</details>

**Comment by Centril** [comment]
I'm guessing this is due to https://github.com/rust-lang/rust/pull/49799.

**Comment by Centril** [comment]
cc @clarfon

**Comment by clarfon** [comment]
I had deprecated the crate and mentioned that exact issue in its description. The latest release simply includes nothing and the readme has a link to that issue. It should be blacklisted by crater.

**Comment by pnkfelix** [comment]
I discussed with @pietroalbini whether `crater` should blacklist the `bow` crate.

If I understand correctly, blacklisting `bow` would not actually address the issue, since the problem building `bow` would still arise when we attempt to build the downstream crates that (directly or indirectly) depend on `bow`.

Here is a ascii-art graph showing the reverse dependencies here

```
bow --> multistr --> parse-hosts --> swc-hosts
                         |
                         '---------> hostman
```

The top four crates are all authored by @clarfon. I couldn't find any active repositories for those crates (all the links in the crates.io metadata are dead), so i couldn't file any issues against them.

I filed lucascaro/hostman#4 about the crate on the bottom of the graph.

I don't think there's anything further that we should do on our end about this. So I'm closing this as expected fallout from #49799.
