### ISSUE TITLE
there is no way to deal with csv, json ,hex data in standard library

### ISSUE THREAD

**Issue by catastrop** [rust-lang/rust#61690]

**Comment by nagisa** [comment]
That much API surface definitely needs an [RFC](https://github.com/rust-lang/rfcs), so closing in favor of that.

Note that this is extremely unlikely to happen since we have several high-quality csv and serialization crates on crates.io already and there is no pressing reason to pull that sort of functionality into libstd.

(cc @jonas-schievink I took liberty of re-using your wording here)

**Comment by catastrop** [comment]
If i working in a place where i don't have internet connection, what should i do?

**Comment by jfrimmel** [comment]
> If i working in a place where i don't have internet connection, what should i do?

Use [cargo vendor](https://github.com/alexcrichton/cargo-vendor) or set up a crates.io-mirror.
