### ISSUE TITLE
rustup doc permission problems (Ubuntu/Firefox)

### ISSUE THREAD

**Issue by kfrncs** [rust-lang/rust#61796]
This appears in Firefox when I run `rustup docs`:

```
Access to the file was denied

The file at /home/ken/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/doc/rust/html/index.html is not readable.

It may have been removed, moved, or file permissions may be preventing access.
```

I had tried a bunch of stuff to give myself permission, but running `cat /home/ken/blahblah/index.html` works. There is a record of some troubleshooting [here](https://stackoverflow.com/questions/55961953/access-denied-when-i-run-rustup-doc?noredirect=1#comment98647187_55961953), but to no avail. 

Hope we can find a solution, thanks in advance for your time.

version info:
```
rustc 1.37.0-nightly (2887008e0 2019-06-12)
binary: rustc
commit-hash: 2887008e0ce0824be4e0e9562c22ea397b165c97
commit-date: 2019-06-12
host: x86_64-unknown-linux-gnu
release: 1.37.0-nightly
LLVM version: 8.0
```

**Comment by Mark-Simulacrum** [comment]
I suspect this is not a bug with Rust/rustup, but can't be sure -- without more information though I don't think we can do anything to help here. I would try to continue asking on stack overflow or perhaps try to reach out on Discord (#wg-rustup may be helpful).

If there's some actionable bug we can fix here please let us know and we'd be happy to reopen!

**Comment by genIterator** [comment]
Hello everyone,

the issue is directly related to firefox being provided as snap package now in Ubuntu. You can check that the snap package provides access to the home folder using the "snap connections firefox" command. However, as described [here](https://askubuntu.com/questions/1238211/how-to-make-snaps-access-hidden-files-and-folders-in-home#) access to the home folder does not include access to hidden files like ".rust". Therefore the docs cannot be opened, no matter the file permissions. 
I see three possible solutions:
1. rust needs to change the path to the documentation, so snap packages are able to open it again
2. Firefox Snap developers need to add the personal-files interface, as described [here](https://forum.snapcraft.io/t/the-personal-files-interface/9357)
3. (maybe) users could get around the issue using hardlinks, as described [here](https://askubuntu.com/a/1308552)

**Comment by glts** [comment]
This issue is likely to get more exposure now with the .1 release of Ubuntu LTS 22.04.

Anybody who installs Rust on plain Ubuntu now will not be able to view local documentation with `rustup doc --book` or `rustup doc --std`.

**Comment by makoConstruct** [comment]
Huh. Honestly,

4. Most users shouldn't install a web browser into a sandboxed environment, web browsers are themselves a very good sandbox. (And personally I think snap is actively making things worse here, it's introducing yet an obstacle to progress in the web by preventing what's (eventually) supposed to be a very broad-reaching safe system interface for cross-platform applications from having full access to the system.)

**Comment by KevinKelley** [comment]
> A temporary solution for people who just wanna get the docs up and running locally:
> 
> 1. `cd` into `$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust`
> 2. execute `python -m http.server`
> 
> And now you can view the docs locally. It works on Firefox as well

thanks for this; it's the only method working so far for me.  New install on ZorinOS (ubuntu 22.04 based), according to instructions from rust.org, and I'm getting that same error in the browser (chromium) with `rustup doc --book` 
...docs generate fine, way down in `.rustup/`, but somehow not accessible in browser.  python server works fine tho

**Comment by seralekseenko** [comment]
Another easy way to open documentation locally is to change the default browser. For example, on Chrome or Edge. But they must be installed outside of snap.

**Comment by jano-petras** [comment]
For whomever it might benefit, here is the workaround that I am using on Ubuntu 24.04.1 LTS

1. Before installing rust, set env variable by modifying ~/.bashrc file `export RUSTUP_HOME=/home/<your-username>/rustup`
2. Use a new terminal to pick up the env variable
3. Run `curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh` to install rust as per installation instructions
4. After rust is installed and added to `PATH`, running `rustup doc`  Firefox shows the documentation without permission issues
5. As pointed out in previous comments, the issue is due to snap packages being blocked from accessing hidden folders. With this env variable, the rustup folder is not hidden any more
