### ISSUE TITLE
Simplify `#[derive(BuiltinTrait)]` expansion wrt. lifetimes

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#61876]
For example, given:

```rust
#[derive(Clone)]
struct A<'a>(&'a u8);
```

we generate:

```rust
impl<'a> Clone for A<'a> { ... }
```

but we should be able to generate:

```rust
impl Clone for A<'_> { ... }
```

This *might* lead to perf improvements by generating less tokens.

cc @zackmdavis @scottmcm @eddyb @petrochenkov 
cc https://github.com/rust-lang/rust/pull/61824

**Comment by eddyb** [comment]
If we need to generate *any* bounds, *at all*, this will be tricky as we'd have to check which lifetime names would show up in the bounds. Other than that, it seems straight-forward.
One thing we should make sure first is that we don't use `A<'a>` *anywhere* today other than the `impl` header (and that we're using `Self` everywhere else).

**Comment by jyn514** [comment]
Is this useful? It seems awfully complicated, and I don't think the lexer is the slow part of the compiler ...

**Comment by petrochenkov** [comment]
This kind of leads to a philosophical question - what is the purpose of an issue tracker? Should it track potentially nice ideas that nobody is going to implement, not even the author?

I'd personally close this, if someone is ready to invest work into proving usefulness of this idea and measure performance, then a PR is welcome, but otherwise we should not track this as an open issue.
