### ISSUE TITLE
Leak when returning out of box syntax

### ISSUE THREAD

**Issue by agashlin** [rust-lang/rust#62289]
@nils-ohlmeier mentioned a leak coming from `vec![f()?]` but not `vec![f()?; 1]` [here](https://github.com/mozilla/webrtc-sdp/blob/master/src/attribute_type.rs#L2158-L2160), I think I tracked this down to the use of `box` in `vec!` when given a comma-separated list.

I've made [a smallish test](https://gist.github.com/agashlin/cd5e2227f13d48e3c701b68df4f89e6c) that demonstrates it with `stats_alloc`, if it gets much simpler than this then the leak doesn't occur when built with --release.

I'm testing on rustc 1.37.0-nightly (0af8e872e 2019-06-30) nightly-x86_64-pc-windows-msvc, targeting x86_64-pc-windows-msvc.

**Comment by agashlin** [comment]
Valgrind Memcheck also reports heap in use at exit on a Linux VM with the test linked above.

**Comment by nils-ohlmeier** [comment]
Thanks a lot @agashlin for creating a reduced test case and creating this issue here.

I stumbled over the original issue when carg-fuzz reported a memory leak in this code https://github.com/mozilla/webrtc-sdp/blob/3a46c37c6d11e2e856b946f4a2e11d90adde3af6/src/attribute_type.rs#L2060-L2062

This PR appears to fix the issue https://github.com/mozilla/webrtc-sdp/pull/151/files

This was also with rustc 1.37.0-nightly on Linux. I can check if I can repro with the fuzz test case on other platforms.

**Comment by Manishearth** [comment]
Looks like the early return doesn't interact well with box syntax's preallocation.

MIR generation issue? cc @oli-obk

**Comment by matthewjasper** [comment]
`value.ty` should be `expr.ty` here:

https://github.com/rust-lang/rust/blob/848e0a23f34aaab3e4a974b031c86ef2a4e4fcc1/src/librustc_mir/build/expr/as_rvalue.rs#L127-L132

Now that `schedule_drop` can only schedule drops for locals, we should get the type from `self.local_decls` to avoid this sort of problem in the future.

**Comment by nils-ohlmeier** [comment]
Confirmed with my fuzzing test case that the problem is fixed in the latest rust nightly.
Thanks for fixing it so quickly.
