### ISSUE TITLE
Size of `fn` can be either 8 or 0

### ISSUE THREAD

**Issue by peterjoel** [rust-lang/rust#62440]
There is a discrepancy on the size of a `fn`, depending on if you treat it generically or not:

```
fn foo() { }

fn main() {
    generic(foo);
    function(foo);
}

fn generic<F>(f: F) {
    println!("value: {}", std::mem::size_of_val(&f));  // 0
    println!("type:  {}", std::mem::size_of::<F>());  // 0
}

fn function(f: fn()) {
    println!("value: {}", std::mem::size_of_val(&f));  // 8
    println!("type:  {}", std::mem::size_of::<fn()>());  // 8
}
```

I would expect all of these to have the same size.

-----

Tested in Rust 1.36.0

**Comment by Centril** [comment]
This is expected behavior.

Note that the function `fn foo() {}` is *not* of a function pointer type, indeed when you type check:
```rust
fn foo() {}
const TEST: () = foo;
```
this will error with:
```
error[E0308]: mismatched types
 --> src/lib.rs:3:18
  |
3 | const TEST: () = foo;
  |                  ^^^ expected (), found fn item
  |
  = note: expected type `()`
             found type `fn() {foo}`
```

Notice in particular that the compiler says the found type is `fn() {foo}` and not `fn()`.
This is the compiler's way of representing the *unique* *zero sized type* that corresponds to the function.
This is akin to how closures also create a unique type (but in that case, the size may be >= 0 depending on the captured environment).

What happens when you write something like:
```rust
let my_fun: fn() = foo;
```
is that *the compiler coerces `foo` to a function pointer*.

For more on this, [read the relevant section on function *item* types in the reference](https://doc.rust-lang.org/nightly/reference/types/function-item.html).

**Comment by peterjoel** [comment]
Thanks for the explanation!
