### ISSUE TITLE
The total Rust archive size has intensified recently

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#62486]
**Edit**: 
> I forgot that with nightly, I also installed clippy, rustfmt, musl target.
> The new edit will not contains those.

The total Rust archive size has intensified recently.

```console
% rustc +nightly-2019-07-07-x86_64-unknown-linux-gnu -V
rustc 1.38.0-nightly (dfd52ba6a 2019-07-06)
% du -sch ~/.rustup/toolchains/nightly-2019-07-07-x86_64-unknown-linux-gnu
868M    /home/lzutao/.rustup/toolchains/nightly-2019-07-07-x86_64-unknown-linux-gnu
868M    total
```

```console
% rustc +nightly-2019-07-08-x86_64-unknown-linux-gnu -V
rustc 1.38.0-nightly (6e310f2ab 2019-07-07)
% du -sch ~/.rustup/toolchains/nightly-2019-07-08-x86_64-unknown-linux-gnu
1.1G    /home/lzutao/.rustup/toolchains/nightly-2019-07-08-x86_64-unknown-linux-gnu
1.1G    total
```

Is this a regression caused by #59800 ?
cc @Zoxc (for the PR), @Centril (infra team)

**Comment by Zoxc** [comment]
Yes, this is an expected regression by https://github.com/rust-lang/rust/pull/59800.

**Comment by mati865** [comment]
See also https://github.com/rust-lang/rust/issues/61978

**Comment by est31** [comment]
This contains justification of the change: https://github.com/rust-lang/rust/pull/56987#issuecomment-448786853

This contains suggestions on decreasing the size: https://github.com/rust-lang/rust/pull/56987#issuecomment-448985578

**Comment by eddyb** [comment]
My own suggestion: https://github.com/rust-lang/rust/pull/59800#issuecomment-503990460 - reproduced below:
> Has shipping .rmeta instead of .rlib been considered?
We would have to either include MIR for everything and codegen at the end (potentially subopyimal) or just throw away the .rlib and somehow require the final .so crate to be linked in order to use anything from the component crates.
For the latter, it could be as simple as a check like "at least one of the dependency crates must claim to contain each symbol referenced and be linkable".
