### ISSUE TITLE
Is Rc’s and Arc’s data_offset correct?

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#62522]
In the implementation of `Arc`, we find:

https://github.com/rust-lang/rust/blob/09ab31bc64f4ede9f9498440cb4225c173767c1e/src/liballoc/sync.rs#L258-L269

https://github.com/rust-lang/rust/blob/09ab31bc64f4ede9f9498440cb4225c173767c1e/src/liballoc/sync.rs#L2288-L2304

(And similarly in `rc.rs` with `struct RcBox`.)

Note the comment: `Because it is ?Sized, it will always be the last field in memory.`

Is this actually true, even for instantiations where `T` happens to be `Sized`? Does the language guarantee that there exist no type `Foo` such that the fields of `ArcInner<Foo>` would be re-ordered?

Or do we need to add `#[repr(C)]` to `ArcInner` and `RcBox`?

CC @rust-lang/wg-unsafe-code-guidelines

**Comment by rkruppe** [comment]
If this were user-facing code it would be a clear case of "no that's not specified, don't assume that". However, I believe rustc does currently honor this assumption and libstd can of course rely on rustc implementation details. @eddyb would know best.

> Is this actually true, even for instantiations where T happens to be Sized?

Note that because unsizing happens with "reorganizing" the struct, the struct with a sized T has to be laid out "as if unsized" from the start. For example, `Rc<u8>` and `Rc<u128>` and many other `Rc<T: Sized>` can all be casted to `Rc<dyn Debug>` without touching the `RcInner`, the differences in layout between those are quite constrained (limited to different amounts of paddding to respect alignment, I think?).

This reasoning wouldn't apply if there was a type that couldn't ever be involved in unsizing, but I don't think the compiler can ever realistically rule that out locally, and I'm rather certain that it doesn't today.

**Comment by SimonSapin** [comment]
Ah that’s a good point. The constraint that layout cannot change while unsizing is probably enough indeed.

**Comment by Centril** [comment]
> If this were user-facing code it would be a clear case of "no that's not specified, don't assume that". However, I believe rustc does currently honor this assumption and libstd can of course rely on rustc implementation details.

We should probably add a comment to that effect so "don't assume that" is clearer to everyone.

**Comment by RalfJung** [comment]
> We should probably add a comment to that effect so "don't assume that" is clearer to everyone.

We should! See https://github.com/rust-lang/unsafe-code-guidelines/issues/90.

**Comment by RalfJung** [comment]
FWIW these are `repr(C)` nowadays so this got properly fixed at some point.
