### ISSUE TITLE
Send trait bound failure error message doesn't refer to Send at all

### ISSUE THREAD

**Issue by marmistrz** [rust-lang/rust#62718]
If a trait method expects a `Future` to be `Send` but we try to use it for a `Future` that doesn't implement `Send`, the compiler error message doesn't mention the missing `Send` trait at all, which makes it very hard to debug the issue.

Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=53cdebbab43fa37326e73fe554de7db4

The error message:
```
   = note: the method `decorate` exists but the following trait bounds were not satisfied:
           `&dyn futures::future::Future<Error = (), Item = ()> : Decorate<_>`
           `&mut (dyn futures::future::Future<Error = (), Item = ()> + 'static) : Decorate<_>`
           `&mut std::boxed::Box<(dyn futures::future::Future<Error = (), Item = ()> + 'static)> : Decorate<_>`
           `&std::boxed::Box<dyn futures::future::Future<Error = (), Item = ()>> : Decorate<_>`
           `dyn futures::future::Future<Error = (), Item = ()> : Decorate<_>`
           `std::boxed::Box<dyn futures::future::Future<Error = (), Item = ()>> : Decorate<_>`
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `decorate`, perhaps you need to implement it:
           candidate #1: `Decorate`
```

**Comment by rylev** [comment]
The issue as described [no longer seems to be the case](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=67f95f991822943f30b63e51cce2e063). I needed to update some of the type signatures since `Future` has changed since this issue was created. The error message still seems to be pretty hard to read because the trait bounds are pretty complex.

I'm going to close this for now, and we can think about opening a new issue with the new (and still confusing but for different reasons) diagnostic.
