### ISSUE TITLE
Confusing Debug of chars

### ISSUE THREAD

**Issue by max-sixty** [rust-lang/rust#62947]
Currently, the Debug of `Chars` prints the underlying bytes, rather than the chars:

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7b09ceeb511d2859dbf492b5f4c046f4)

```rust
#![allow(unused)]
fn main() {
    let s = String::from(" é 😀 ");
    let c = s.chars();
    dbg!("Debug of Chars: ", &c);
    dbg!("Debug of each char: ");
    for x in c {
        dbg!(x);
    }
}
```

Returns:

```
[src/main.rs:5] "Debug of Chars: " = "Debug of Chars: "
[src/main.rs:5] &c = Chars {
    iter: Iter(
        [
            32,
            195,
            169,
            32,
            240,
            159,
            152,
            128,
            32,
        ],
    ),
}
[src/main.rs:6] "Debug of each char: " = "Debug of each char: "
[src/main.rs:8] x = ' '
[src/main.rs:8] x = 'é'
[src/main.rs:8] x = ' '
[src/main.rs:8] x = '😀'
[src/main.rs:8] x = ' '
```

As I was trying to work out what `chars` was (whether it was unicode points or bytes or something else), the first output was v confusing - is there a reason we don't print something like the second case?

Would you take a PR to change this?

I couldn't find any previous discussion on this - https://github.com/rust-lang/rust/pull/49283 was the closest I could find.

**Comment by ExpHP** [comment]
The first one is UTF-8 bytes.  You see this because the `Debug` impl for `Chars` is auto-generated:

```rust
#[derive(Clone, Debug)]
pub struct Chars<'a> {
    iter: slice::Iter<'a, u8>
}
```

Strictly speaking, since the bytes inside of `Chars` should always be valid UTF-8, this could have a custom `Debug` impl that makes it pretend to contain a string by formatting the member as `str::from_utf8(self.iter.as_slice()).unwrap()`.

**Comment by max-sixty** [comment]
> I guess that, questionable concerns of efficiency aside, my main concern is simply that showing a list of individual chars would be... dishonest, I guess.

Do `str` & `String` contain more data than `Chars`? I had thought they both contained the underlying bytes and then these were decoded as needed - including as part of the `Display` & `Debug` implementations

**Comment by ExpHP** [comment]
No, they contain the same data.  They're all just UTF-8 bytes.  And the `Display` implementation of `str` simply writes the bytes contained in the `str` directly to the `io::Write` instance.

---

Suppose we are writing to STDOUT.  On UNIX, these bytes are written directly to the underlying file descriptor with no processing.

https://github.com/rust-lang/rust/blob/eedf6ce4ef54bb03818ab21d714f1b9f13a6b31c/src/libstd/sys/unix/stdio.rs#L27-L30

https://github.com/rust-lang/rust/blob/eedf6ce4ef54bb03818ab21d714f1b9f13a6b31c/src/libstd/sys/unix/fd.rs#L109-L116

I would imagine this is because the console on any UNIX platform almost certainly uses UTF-8.[^1]  It is your terminal application that is then responsible for decoding these bytes and producing glyphs.  Considering that UTF-8 dominates much of the web space as well, it's quite possible that even on the playground, these bytes are ultimately sent over the wire to your PC with minimal processing, where your browser is responsible for decoding and displaying them.

On Windows, `Stdout` transcodes the UTF-8 into the UTF-16 format expected by the windows APIs:

https://github.com/rust-lang/rust/blob/eedf6ce4ef54bb03818ab21d714f1b9f13a6b31c/src/libstd/sys/windows/stdio.rs#L76-L84

and then Windows does whatever it does with those UTF-16 bytes.  (Quite likely, it hands them directly to the console, which is then responsible for decoding and displaying them)

---

[^1]: (I think in actuality UNIX accepts arbitrary strings of bytes, and then the portions of these strings which are valid UTF-8 are rendered appropriately by the console.  I don't know; doesn't really matter)

**Comment by max-sixty** [comment]
OK, so given that - is there still an objection to displaying the unicode characters for `Chars` but not `String`?
