### ISSUE TITLE
Ungreat diagnostic error borrowed data escapes outside of function

### ISSUE THREAD

**Issue by spastorino** [rust-lang/rust#62953]
On an change I was implementing in the compiler I got the following error ...

```
error[E0521]: borrowed data escapes outside of function
   --> src/librustc_codegen_ssa/mir/analyze.rs:228:9
    |
218 |     fn visit_place(&mut self,
    |                    --------- `self` is declared here, outside of the function body
219 |                    place: &mir::Place<'tcx>,
    |                    ----- `place` is a reference that is only valid in the function body
...
228 |         self.process_place(place_ref, context, location);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `place` escapes the function body here

error: aborting due to previous error
```

I don't remember how the code looked like exactly but we can probably rebuild an example that shows this behavior.

More info https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/borrowed.20data.20escapes.20outside.20of.20function

**Comment by ssomers** [comment]
This is effectively google's landing page for an explanation of this mysterious Rust error E0521, given that the [official error spokeswomen](https://doc.rust-lang.org/nightly/error-index.html#E0521) and `rustc --explain` deny its existence. Most of the links here badmouth the error, but I couldn't figure out what the actual problem in the code is about. #67007 goes into a lot of detail, but if I understood all that, I bet I wouldn't have landed here.

Luckily, just a few links further, google also lists a [link to a stackoverflow question](https://stackoverflow.com/questions/51118023/what-does-borrowed-data-cannot-be-stored-outside-of-its-closure-mean) (even though it does not mention E0521 nor the same error message). It doesn't actually offer a complete example, but it allowed me to strip mine down and spot the solution.

```rust
fn main() {
    let mut stash: Option<&i32> = None;
    let mut thief = |r: &i32| { stash = Some(r) };
    thief(&42);
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5ba4ac28fc564a48c53d4d0685f3d5c1))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0521]: borrowed data escapes outside of closure
 --> src/main.rs:3:33
  |
2 |     let mut stash: Option<&i32> = None;
  |         --------- `stash` declared here, outside of the closure body
3 |     let mut thief = |r: &i32| { stash = Some(r) };
  |                      -          ^^^^^^^^^^^^^^^ `r` escapes the closure body here
  |                      |
  |                      `r` is a reference that is only valid in the closure body
```

The problem here is that we need to remove the type from the closure:
```rust
    let mut thief = |r| { stash = Some(r) };
```

**Comment by jesusprubio** [comment]
Long explanation added. Thanks for the explanation @ssomers, it helped me a lot :).

https://github.com/rust-lang/rust/pull/81634

Do you consider it enough to close the issue?

**Comment by ssomers** [comment]
For my example, that is definitely very helpful and more than enough.

**Comment by jesusprubio** [comment]
@GuillaumeGomez , could you close this issue please? :)

**Comment by GuillaumeGomez** [comment]
@ssomers seems satisfied so let's close it. Thanks @jesusprubio !
