### ISSUE TITLE
Async fn does not compile if lifetime does not appear in bounds (sometimes)

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#63033]
```rust
#![feature(async_await)]

use std::marker::PhantomData;

trait Trait {}

async fn f<'a>(reference: &(), marker: PhantomData<dyn Trait>) {}
```

This fails with:

```console
error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
 --> src/main.rs:7:64
  |
7 | async fn f<'a>(reference: &(), marker: PhantomData<dyn Trait>) {}
  |                                                                ^
  |
note: hidden type `impl std::future::Future` captures the scope of call-site for function at 7:64
 --> src/main.rs:7:64
  |
7 | async fn f<'a>(reference: &(), marker: PhantomData<dyn Trait>) {}
  |                                                                ^^
```

I believe this should compile because:

1. The non-async function with the same signature does compile;

    ```rust
    fn f<'a>(reference: &(), marker: PhantomData<dyn Trait>) {}
    ```

2. Seemingly insignificant tweaks, like adding a wrapper struct, make it compile.

    ```rust
    struct Wrapper(PhantomData<dyn Trait>);
    async fn f<'a>(reference: &(), marker: Wrapper) {}
    ```

Mentioning @cramertj who fixed a similar error message in #59001.
Mentioning @nikomatsakis who touched this error message in #49041 and #61775.

*rustc 1.38.0-nightly (c43753f91 2019-07-26)*

**Comment by nikomatsakis** [comment]
I agree this is a bug -- it doesn't necessarily block stabilization (no fwd compat risk) but would definitely be a good one to fix. Marking as blocking + unclear for the moment and will return to it.

**Comment by nikomatsakis** [comment]
I did a bit of investigation. The error results because we have an inference variable (`'_#3r`) that seems to have no constraints, but must be equal to one of the captured regions (e.g., `'a`). I haven't 100% figured out where this variable comes from, I imagine it's related to `'a` though? In any case, the resolver basically winds up in a situation where it could pick any of the lifetimes but has no reason to prefer one over the other, and hence it reports an error.

**Comment by nikomatsakis** [comment]
OK, I think I see what's going on. It doesn't actually have much to do with the unused lifetime per se. What happens is this:

- The type of the generated result is something like `Foo<&'2 (), PhantomData<dyn Trait + '3>>` -- i.e., it includes the types of the parameters, though with region variables in place of the known regions. Those types must be supertypes of the actual parameter types.
- We capture the argument `marker` of type `dyn Trait + 'static` -- per the subtyping rules, we create the type `dyn Trait + '3` for the type of this captured value, with the requirement that `'static: '3` -- as it happens, this is always true, so there is effectively no constraint on `'3`.
- We do impose the constraint that `'2` and `'3` must both be equal to one of the free regions -- in this case, `'a` or the anonymous lifetime of `reference` (which I'll call `'b`). 

So thus the region solvers get in a state where `'3` must be equal to `'a`, `'b`, or `'static` -- but any one of them would be a reasonable choice. 

Removing the unused lifetime (`'a`) makes this an easy choice -- it can pick `'b`, which is smaller than `'static`. (Per the "least choice" rules we usually use.)

Removing the type and putting it into a struct (`Wrapper`) removes the lifetime variable altogether, as then we have `Foo<&'2 (), Wrapper>`, and there are no lifetime parameters involved.

I'm not sure what I think is the best fix. It would be nice for the solver to pick `'static`, though it complicates the algorithm. You could certainly imagine a tweak that picks `'static` if the value is legal and otherwise looks for a least choice. That might indeed be superior to the current approach, though I'd want to think about the full implications -- in particular, when `impl Trait` is used in places outside of the fn return type (e.g., in a `let` statement), picking `'static` might lead to unnecessary borrow check errors. (The alternative would be to only look for `'static` when there is no least choice; that seems safer.)

(Interestingly, at some point at least I thought that a polonius-like approach sidesteps a lot of the challenges here-- if we had confidence that we would transition that might ease some of my concerns.)

**Comment by nikomatsakis** [comment]
Now that I understand better what is happening, I don't feel this has to block stabilization -- in particular, I don't think that there is a forward compatibility risk from us improving the region inference algorithm. I don't think we would choose an algorithm that makes existing code illegal. =)

**Comment by sfackler** [comment]
Here's another example of the same problem that *doesn't* have an unused lifetime (AFAIKT):

```rust
struct Foo;

impl Foo {
    async fn wat(&self, _: &'static str, _: Bar<'_>) {}
}

struct Bar<'a>(Box<dyn std::fmt::Debug + 'a>);
```

```
error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
 --> src/lib.rs:4:54
  |
4 |     async fn wat(&self, _: &'static str, _: Bar<'_>) {}
  |                                                      ^
  |
note: hidden type `impl std::future::Future` captures the scope of call-site for function at 4:54
 --> src/lib.rs:4:54
  |
4 |     async fn wat(&self, _: &'static str, _: Bar<'_>) {}
  |                                                      ^^

error: aborting due to previous error
```

**Comment by lovasoa** [comment]
I am also affected by this bug, where having both a reference and a box as parameters to a function causes the cryptic "hidden type for `impl Trait` captures lifetime that does not appear in bounds" : 

```rust
trait Trait {}
async fn f<'a>(_a: &(), _b: Box<dyn Trait>) {}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0ab3d470158a6d130dff15db8c9771dc))

Is there a resolution in sight ?

**Comment by sfackler** [comment]
`'a` is unused in that function - if you remove the `<'a>` it compiles.

**Comment by lovasoa** [comment]
Ok, let me change it to something closer than I had in my original code:

```rust
trait T {}
struct S;
impl S {
    async fn f(_a: &S, _b:&S, _c: Box<dyn T>) {}
}
```

([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1338486a2f50292b7cb9dd4bff90399f))

**Comment by netvl** [comment]
I think I found another example of this:
```rust
trait T {}

struct L<A = Box<dyn T>> {
    value: A,
}

async fn test1(l: L, s1: &str, s2: &str) {
}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b5b670e22e655bb49793fcc82d66c30a))

This example more or less represents what I met in my code (when I tried to pass a structure with a type parameter to an async function with the default value for this type parameter being a trait object), but it can be simplified by removing the default parameter assignment and passing the `Box<dyn T>` argument to `L` explicitly:

```rust
trait T {}

struct L<A> {
    value: A,
}

async fn test1(l: L<Box<dyn T>>, s1: &str, s2: &str) {
}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3b23d524ea48e7c1f1f07a6e0e6d13d4))

Curiously, if you replace `async fn ... { ... }` with `fn ... -> impl Future { async { ... } }`, the error goes away:

```rust
use std::future::Future;

trait T {}

struct L<A> {
    value: A,
}

fn test1(l: L<Box<dyn T>>, s1: &str, s2: &str) -> impl Future<Output=()> {
    async {
    }
}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=66d28dc7d0cd61299f80bd6d902c97d6))

It is important to note that the `test1` method has *two* additional arguments. If you remove one or both of them, it starts compiling again:

```rust
trait T {}

struct L<A> {
    value: A,
}

async fn test2(l: L<Box<dyn T>>, s1: &str) {
}

async fn test3(l: L<Box<dyn T>>) {
}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d46b2e4989578e9f9473c4bce2c04772))

**Comment by skeet70** [comment]
@netvl 's comment is a minimal reproduction of what I ran into. I had a function `async f(a: &CacheA, b: &CacheB, c: &CacheC, d: Arc<dyn Client>)`. If I remove two of the cache arguments it compiles. As soon as I add one back in it gives me the title error.

**Comment by nikomatsakis** [comment]
Hmm, it is probably worth revisiting this problem now that stabilization has happened.

**Comment by swilcox3** [comment]
Any word on this?  I'm getting this error as well.
```
pub async fn publish(
    conn: &mut StateConnection,
    file: &FileID,
    user: &UserID,
    latest: ChangeID,
    mut subscribers: Vec<Box<dyn ChangeSubscriber>>,
) -> Result<(), ObjError> {
    let to_publish = gather_changes(conn, file, latest).await?;
    for sub in subscribers {
        sub.get_changes(file, user, latest, &to_publish).await?;
    }
    Ok(())
}
```
Changing `mut subscribers: Vec<Box<dyn ChangeSubscriber>>` to `subscribers: &mut Vec<Box<dyn ChangeSubscriber>>` fixes the issue.  Only problem is that I actually want to move that vector in because I want to `tokio::spawn` each call to `get_changes`.

**Comment by nikomatsakis** [comment]
No progress or major updates. The [description here](https://github.com/rust-lang/rust/issues/63033#issuecomment-521234696) is still accurate as to the root cause, but I think we don't yet know the best fix.

**Comment by danieleades** [comment]
this is going to become a problem now that #72459 is merged.

It makes it impossible to implement `IntoFuture` for types with lifetimes, when the future that's returned is unnameable.

consider

```rust
pub struct Request<'a> {
    ...
}

impl<'a> Request<'a> {
    async fn send(self) -> Result<(), Error> {
        ...
    }
}

// does not compile
// "cannot infer an appropriate lifetime for lifetime parameter `'a` due to conflicting requirements"
impl<'a> IntoFuture for Request<'a> {
    type Output = Result<(), Error>;
    type Future = impl Future<Output = Self::Output>;

    fn into_future(self) -> Self::Future {
        self.send()
    }
}

// does not compile
// "hidden type for `impl Trait` captures lifetime that does not appear in bounds"
impl<'a> IntoFuture for Request<'a> {
    type Output = Result<(), Error>;
    type Future = impl Future<Output = Self::Output> + 'a;

    fn into_future(self) -> Self::Future {
        self.send()
    }
}
```

**Comment by AndiDog** [comment]
Here's another very simple example:

```
#[allow(dead_code)]
struct SomeStruct<'a> {
    s: &'a str,
}

async fn something_asynchronous(_a: &'static str, _b: &str, _c: &SomeStruct<'_>) {}
```

```
error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
 --> src/main.rs:6:82
  |
6 | async fn something_asynchronous(_a: &'static str, _b: &str, _c: &SomeStruct<'_>) {}
  |                                                                                  ^
  |
note: hidden type `impl std::future::Future` captures lifetime smaller than the function body
 --> src/main.rs:6:82
  |
6 | async fn something_asynchronous(_a: &'static str, _b: &str, _c: &SomeStruct<'_>) {}
  |                                                                                  ^
```

Removing **any** of the 3 parameters makes the code compile. Alternatively, removing the static lifetime of `_a` (→ `_a: &str`) makes it compile as well.

**Comment by redragonx** [comment]
Hi.

I get the following error that matches what everyone is also getting:

```
error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
  --> src/profile.rs:91:10
   |
91 |     ) -> Result<(), BoxError> {
   |          ^^^^^^^^^^^^^^^^^^^^
   |
note: hidden type `impl futures::Future` captures lifetime smaller than the function body
  --> src/profile.rs:91:10
   |
91 |     ) -> Result<(), BoxError> {
   |       
```

```
pub type BoxError = Box<dyn Error + Send + Sync + 'static>;

    pub async fn run_profile(
        &self,
        app_config: &AppiConfig,
        app_args: ArgMatches<'static>,
    ) -> Result<(), BoxError> {
```

**Comment by pthariensflame** [comment]
[Another case showed up yesterday:](https://www.reddit.com/r/rust/comments/jt1s5q/unexpected_borrow_checker_behavior/)

```rust
rust async fn test(test: &String, test2: &String, test3: &'static String) {}
```

**Comment by autodidaddict** [comment]
I have the following case triggering this error message:

```rust
async fn reinvoke_bindings(
    key: &KeyPair,
    target: Recipient<Invocation>,
    provider_id: &str,
    contract_id: &str,
    binding: &str,
    existing_bindings: Vec<(String, HashMap<String, String>)>,
    claims_cache: HashMap<String, Claims<wascap::jwt::Actor>>,
    authorizer: Box<dyn Authorizer>,
) {
...
}
```

**Comment by krojew** [comment]
Got the error in the following:

```
    async fn foo(
        &self,
        user_id: &Uuid,
        character_id: &Uuid,
        item_id: &Uuid,
        topic: &'static str,
    ) -> Result<(), String>
```

Removing ` topic: &'static str,` helps.

**Comment by wigy-opensource-developer** [comment]
> Ok, let me change it to something closer to what I had in my original code:
> 
> ```rust
> trait T {}
> struct S;
> impl S {
>     async fn f(_a: &S, _b:&S, _c: Box<dyn T>) {}
> }
> ```
> 
> ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1338486a2f50292b7cb9dd4bff90399f))

I know I am late to the game, but this issue still hunted us down with a Rust 1.48 compiler. The workaround is simple, but it pollutes all the callers with extra lifetime parameters. Basically, wherever `'static` saved us from introducing a lifetime parameter, we have to introduce it in `struct`s, `fn`s, everywhere.

```rust
trait T {}
struct S;
impl S {
    async fn f<'a>(_a: &S, _b:&S, _c: Box<dyn T + 'a>) {}
    async fn g<'a>(&self, _b:&S, _c: Box<dyn T + 'a>) {}
}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cc1de4c85577a0ea60d400f69699920f))

@nikomatsakis Maybe if you treat `'static` special in the implementation, like in other parts of the language, that would cover most of the cases this issue is hit.

**Comment by Kimundi** [comment]
Another short example based on reducing code from a discordquestion:
```rust
async fn foo(x: &'static str, y: &str, z: &str) {
}
```

**Comment by wigy-opensource-developer** [comment]
> Another short example based on reducing code from a discord question:
> 
> ```rust
> async fn foo(x: &'static str, y: &str, z: &str) {
> }
> ```

And 2 workarounds for the issue:
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8e9d97061ce90b8f449c45626dd72448)

**Comment by AVee** [comment]
Found this after pulling my hair out for a few hours. At least I've got a workaround now, but I'd have to say this behavior is really unexpected.

Of those two workarounds @wigy-opensource-developer mentions only the first seems to be actually usable if you actually want to do something with those parameters:
    
    // Compiles
    async fn foo<'a>(x: &'static str, y: &'a str, z: &'a str) {
        println!("{} {}", y, z);
    }

    // Doesn't compile: 
    // error[E0759]: `y` has an anonymous lifetime `'_` but it needs to satisfy a `'static` lifetime requirement
    fn bar(x: &'static str, y: &str, z: &str) -> impl Future<Output=()> {
        async {
            println!("{} {}", y, z);
        }
    }

**Comment by nikomatsakis** [comment]
I'm going to remove the "async await triaged" label so that we take a second look at this. Maybe worth reprioritizing. I'll see if I can post some mentoring instructions.

**Comment by wigy-opensource-developer** [comment]
> ```rust
> // Doesn't compile: 
> // error[E0759]: `y` has an anonymous lifetime `'_` but it needs to satisfy a `'static` lifetime requirement
> fn bar(x: &'static str, y: &str, z: &str) -> impl Future<Output=()> {
>     async {
>         println!("{} {}", y, z);
>     }
> }
> ```

@AVee Oh, my fault. And indeed. after "fixing" the async block it definitely looks worse than the async fn one.

```rust
fn bar<'a>(x: &'static str, y: &'a str, z: &'a str) -> impl Future<Output=()> + 'a {
  async move {
    println!("{} {}", y, z);
  }
}
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a219da926d3ec71c8cf1b1466e70917c)

**Comment by DanielJoyce** [comment]
Just hit this as well.

**Comment by nikomatsakis** [comment]
@rustbot claim

I'm claiming this to write some mentoring instructions

**Comment by danielhenrymantilla** [comment]
FWIW, in the meantime, and also to help solve the issue with manual `-> impl Trait` capturing a potentially bigger invariant lifetime, I have published a helper proc-macro-attribute crate that automatically appends the necessary `Captures<'_>` hacks: https://docs.rs/fix_hidden_lifetime_bug

**Comment by tubzby** [comment]
Coming to this too, a little google drives me here.

```rust
async fn read_loop(
    &self,
    st: &mut State,
    stream: Box<dyn std::io::Read>
 ) -> Result<(), Error> {
.....
}
```
Remove any of the parameters will fix this, but I can't.

This thread is almost 2 years old, is there any solution or plan to fix this?

**Comment by nazar-pc** [comment]
@tubzby explicit lifetimes on references should fix the issue for you until compiler is smart enough to figure that out on its own

**Comment by nikomatsakis** [comment]
@rustbot release-assignment

I haven't had time to write up any mentoring instructions here, I'm afraid. :(

**Comment by wigy-opensource-developer** [comment]
Big sad. I wish I was more into the compiler details. I love what async-await did to learnability for newbies and this issue hunts down them after getting their first successes.

**Comment by tubzby** [comment]
@nazar-pc I want to ensure that, is it because the read_loop function might execute after the scope of self reference? 
If so, how can I explicitly set the lifetime of read_loop  is greater than the reference?

**Comment by danielhenrymantilla** [comment]
@tubzby note that your code can be automatically fixed by the tool I mentioned in [my previous comment](https://github.com/rust-lang/rust/issues/63033#issuecomment-843566481):

<img width="838" alt="Screen Shot 2021-07-05 at 14 33 31" src="https://user-images.githubusercontent.com/9920355/124472093-fed66700-dd9d-11eb-84b2-1b39e947f84d.png">

A reliable fix that doesn't change the semantics of the function 🙂 

### How to manually fix this without changing the semantics of the function

You can even query that attribute with the extra `showme` parameter fed to the attribute, and the eponymous Cargo feature, to get:

<img width="681" alt="Screen Shot 2021-07-05 at 14 36 38" src="https://user-images.githubusercontent.com/9920355/124472437-6a203900-dd9e-11eb-9b76-22abf30120ae.png">

### Fixing the `Box<dyn Trait…>` case in practice

For the specific case of `Box<dyn Trait…>` usage, you can almost always _change_ the signature of the function to one using `Box<dyn Trait… + 'static>`. Granted, this is technically a more constraining signature, so we don't really fix the issue and rather circumvent / avoid it, but in practice, this other function signature is as usable as the original one 🙂 :

```diff
  async fn read_loop(
      &self,
      st: &mut State,
-     stream: Box<dyn std::io::Read>,
+     stream: Box<dyn std::io::Read + 'static>,
  ) -> Result<(), Error> {
      todo!("FUNCTION BODY")
  }
```

___

@nikomatsakis I'd like to experiment with `-> impl …` unsugared's TAIT being automatically generic over _all_ the lifetime parameters in scope of the return type. This is what `#[fix_hidden_lifetime_bug]` achieves by using the `+ Capture<'lt>` hack for each and every such lifetime, and I've never encountered cases where this would be an error.

If that approach seems fine to you, I can try to implement this new unsugaring on the compiler myself, although I may not be very fast since I'll need to experiment a bit to get acquainted with the related compiler internals 😅

**Comment by tubzby** [comment]
@danielhenrymantilla thanks, I will try that.

**Comment by abc-mikey** [comment]
I just got bitten by this and I'm a beginner. @danielhenrymantilla 's workarround worked but a proper fix would be desirable.

**Comment by nikomatsakis** [comment]
@danielhenrymantilla are you saying you want to change how `-> impl Trait` works for all cases? That would certainly be a breaking change, so I don't think we can do that. However, it would be good to talk about a better fix than the `Captures<'tcx>` hack. One thing we talked about in the very beginning was having a syntax like `impl<'a, T>` to be very explicit about what things are captured and what are not. But that would, I think, require a lang-team proposal.

**Comment by ttappr** [comment]
I followed the dup link to this issue from this one, https://github.com/rust-lang/rust/issues/87632.  In that case the 'static lifetime applied to the parameter is not meaningfully used within the body of the method. I prefer the compiler not allow this because it unnecessarily constrains code that calls the method. This should not be considered a bug, but the compiler error message could be more precise.

**Comment by danielhenrymantilla** [comment]
> That would certainly be a breaking change

When I thought about this I struggled to come up with an instance of this, so I'm genuinely curious about it. In other words: could annotating a function with `#[fix_hidden_lifetime_bug]` lead to breakage somewhere along the way? If so, such an example could help us evaluate the different options at our disposal 🙂

**Comment by nikomatsakis** [comment]
OK, I've read up on this issue again. The basic diagnosis I had is correct. The fact that some of the lifetimes are unused isn't really especially relevant.

For example, in the [example from this comment](https://github.com/rust-lang/rust/issues/63033#issuecomment-565745749), the problem is simply that there are *two* lifetimes (from `_a` and `_b`) along with the `Box<dyn T>`. This still gets us into the situation where the inferencer must pick between `_a`, `_b`, or `'static`. 

Let me run this through the compiler and take a look at the constraints. I also want to think about how polonius affects this.

**Comment by nikomatsakis** [comment]
I just read over @danielhenrymantilla's [comment](https://github.com/rust-lang/rust/issues/63033#issuecomment-874085626). The reason that this "desugared" version works is because it introduces a new lifetime, `'_async_fut`, and this lifetime has a relationship to every other lifetime. So when we have to pick between `'a`, `'b`, and `'static`, we now also haev the choice of `'_async_fut`, which is strictly less than all of those choices. So we pick that.

Now I realize that the reason that this whole situation is a non-issue in polonius is basically that the polonius representation permits lifetimes that are the intersection of a set of lifetimes. So you could infer the result to be `'a ^ 'b`, which is effectively the same as `'_async_fut`. But in the current implementation, we don't have anything like that.

**Comment by nikomatsakis** [comment]
> I'd like to experiment with -> impl … unsugared's TAIT being automatically generic over all the lifetime parameters in scope of the return type.

I'm not sure if I understand exactly what you were proposing here, @danielhenrymantilla. I thought at first that it meant:

```rust
fn foo(&self) -> impl Debug
```

would be able to capture `self` (because it would capture that lifetime). That would be a breaking change, but is that what you meant?

**Comment by nikomatsakis** [comment]
Fix in https://github.com/rust-lang/rust/pull/89056

**Comment by danielhenrymantilla** [comment]
> The reason that this "desugared" version works is because it introduces a new lifetime, `'_async_fut`, and this lifetime has a relationship to every other lifetime

, effectively defining it, for all intents and purposes, as the intersection lifetime! (which indeed meets the bounds) Ah yes, I see now how there are definitely two distinct issues at hand, here, and that my fix for one just happened to fix the other as a byproduct 😅

___

So, while your PR will fix the `async fn` one, I'm personally still concerned about the case of the existential capturing both `'long_invariant : 'short`, and it's to tackle that one that I was suggesting that `-> impl …` existentials were, internally, allowed to be _generic_ over all the lifetime parameters in scope.

That is, what I meant, or what I'm basically qualifying as a bug, is the fact that `impl …` and `dyn …` don't have the same semantics, lifetime-wise (so, to clarify, I am definitely not talking about changing the rules for lifetime elision in function signatures):

 1. In the same fashion that `fn foo(&self) -> Box<dyn Debug>` stands for `Box<dyn Debug + 'static>`, and can thus not capture `self` since it is `'_`-bound,

 1. then `fn foo(&self) -> Box<impl Debug>` stands for `-> Box<impl Debug + 'static>` and can thus not capture `self` yadda yadda. And in the `impl` case, the `Box` is not needed, so it can be skipped if the implementation doesn't need it.
      - But the key change I am suggesting is the definition of that `impl Debug + 'static` existential. Currently, it would be defined as something like `type Ret = impl Debug + 'static;`, and then unified. What I'm suggesting is that it be defined as `type Ret<'self_> = impl Debug + 'static;`, much like what adding a `+ Captures<'self_>` would achieve.

 1. This would be meaningful, for instance, in all the cases with a captured invariant lifetime which is not equal to the lower bound.
    Take `Self = &'long ()`, and `fn bar<'s>(&'s mut self) -> Box<impl Debug + 's> { Box::new(self) }`.
    In that case, if instead of `impl` we had `dyn`, the signature would work. But in the `impl` case, we have a `type Ret<'s> = impl Debug + 's;`, and such a type definition cannot be unified with the actual type of the implementor, `&'s mut (&'long ())`, **since there is no `'long` in scope of that definition**. My observation is that I believe it cannot hurt to have too many lifetime parameters "in scope" / reachable for an existential's type definition.

      - In that regard, the `+ Captures<'lt>` hack, be it manual or automated through the `#[fix…]` attribute, is just a way to test my theory: the attribute currently adds `+ Captures<'lt>` bounds for _every_ lifetime it meets, without asking further questions, and that suffices to make the existential type definition be generic over all of them, and this whole thing has, empirically, solved the compilation problems without any problems on its own, thus allowing for `impl` and `dyn` to remain quite interchangeable (lifetime-wise, barring obvious `dyn` safety caveats).

      - <sub><sup>(Slight aside: I've noticed that this `type Ret` [seems to currently be always generic over all the _type_ parameters in scope](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9df19adbaf66c1a0c998758c5905814e), so it's really just the lifetime parameters that it's being (overly) picky around, it seems)</sup></sub>

**Comment by mingmwang** [comment]
Just hit this as well.

**Comment by qiujiangkun** [comment]
Encountered this today.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7171c029eb79ccf2068ee469dbce73a1

Though the original error was this, which I couldn't reproduce it in playground.
```
error[E0700]: hidden type for impl std::future::Future<Output = std::result::Result<TransactionReturnData, ErrReport>> captures lifetime that does not appear in bounds
std::result::Result<TransactionReturnData, ErrReport>> captures lifetime '_#22r
```
