### ISSUE TITLE
Tracking issue for Result::cloned, Result::cloned_err, Result::copied, Result::copied_err

### ISSUE THREAD

**Issue by ksqsf** [rust-lang/rust#63168]
[PR](https://github.com/rust-lang/rust/pull/63166)

**Comment by alexcrichton** [comment]
Some unresolved questions for us to resolve while this is unstable:

* Do `*_err` method carry their weight?
* Is it right for `cloned` to work on `Result<&T, E>` or should it work on` Result<&T, &E>`?

**Comment by Fishrock123** [comment]
My 2c:

cloned and copied for `Result` should do the respective operation to either branch, it seems to me that in most cases where you'd need it fro one you'd need it to handle both branches.

I realize this does make the copied one kinda marginal since most errors are unlikely to be `Copy`, but perhaps there is a workaround in the odd case you'd want to copy and yet be able exclude `Err`?

**Comment by spinda** [comment]
I'm in favor of `cloned` only cloning the `Ok` side, i.e., going from `Result<&T, E>` to `Result<T, E>`. This API mirrors `Option::cloned`, and I think it's more likely that a function of the form `fn do_fallible_thing() -> Option<&T>` eventually evolves into `fn do_fallible_thing() -> Result<&T, SomeError>` than `fn do_fallible_thing() -> Result<&T, SomeError>`. It's still the possibly-present success value that you want to clone; the fact that the failure path now carries an error (versus just `None`) is an incidental detail.

**Comment by matklad** [comment]
Given that we already have precedent of `Result::map`, which applies only to `Ok`, and is named `map` rather then `map_ok`, I feel moderately confident that:

* cloned should only clone `&T`, not `E` 
* it should be named `cloned`, rather than `cloned_ok`

Not sure about `_err` variants, but they are stabilizable separately. So, it seems that we potentially can write a stabilization report here and FCP?

**Comment by ksqsf** [comment]
Thanks @matklad for bringing the attention. I believe we generally agree on `cloned` and `copied` so the `_err` variants are left out here.

# Stabilization Report

## Brief summary

- Add `Result::cloned()` for converting `Result<&T, E>` and `Result<&mut T, E>` into `Result<T, E>` by cloning the contents of the `Ok` part.
- Add `Result::copied()` for converting `Result<&T, E>` and `Result<&mut T, E>` into `Result<T, E>` by copying the contents of the `Ok` part.

## Test cases

- Doc tests included in the original PR (#63166).

## Documentation

- Doc comments included in the original PR(#63166).

## Things not covered

- The `_err` variants are not proposed to be stabilized.

**Comment by joshtriplett** [comment]
Shall we stabilize the `cloned` and `copied` methods on `Result`, per the above stabilization report?

@rfcbot merge
