### ISSUE TITLE
How to parse rmeta file

### ISSUE THREAD

**Issue by zhjq8688** [rust-lang/rust#63224]
Hello, I'm currently working on the compiler process of rust and I want to know some details about the metadata included in the rlib file. I have extracted the rmeta file from the rlib file, however, I found out it is also a binary file. I wonder if there are any approaches or tools to parse rmeta file so that I can have a clear picture of the metadata. Thank you

**Comment by nagisa** [comment]
The metadata format is implementation-specific and is not otherwise specified. It is not guaranteed to be the compatible between versions, commits or builds of the compiler.

As thus, the only approach to learn about specifics of the metadata file is to read the compiler source code, mostly for [librustc_metadata crate](https://github.com/rust-lang/rust/tree/452087b4bf18cece2d52d7cd8c9147195e5404bf/src/librustc_metadata).

**Comment by Mark-Simulacrum** [comment]
Closing as this isn't a bug; if you'd like to ask further questions or discuss this internals.rust-lang.org is the best place.
