### ISSUE TITLE
f32/64::asinh() should return -0.0 for -0.0

### ISSUE THREAD

**Issue by TimothyGu** [rust-lang/rust#63271]
Currently, both of the following return false:

```rust
(-0.0 as f64).asinh().is_sign_negative()
(-0.0 as f32).asinh().is_sign_negative()
```

However, in other languages like [C](https://en.cppreference.com/w/c/numeric/math/asinh), `asinh(-0.0)` would always return `-0.0`. We might need another fast case for 0.0 and -0.0 here: https://github.com/rust-lang/rust/blob/f01b9f803b59f170f5dabaaa8aedc96abe45bfea/src/libstd/f64.rs#L833-L839

**Comment by nagisa** [comment]
IEEE-754 (2008), section 9.2.1:

> For the functions expm1, exp2m1, exp10m1, logp1, log2p1, log10p1, sin, tan, sinPi, atanPi, asin, atan, sinh, tanh, asinh, and atanh, f(+0) is +0 and f(−0) is −0 with no exception.

and

> sinh(±∞) and asinh(±∞) are ±∞ with no exception.

**Comment by Phosphorus15** [comment]
I don't think adding a fast case for -0.0 is enough, codes like
```rust
println!("{}", (-1e-20f64).asinh().is_sign_negative());
```
also reports to be `false`, considering that `asinh` is a monotone function.
`(-0.0 as f64).asinh().is_sign_negative()` and `(-1e-20f64).asinh().is_sign_negative()` should have the same result considering that `-0.0` is strictly larger than `-1e-20f`.
Maybe it is more sound to add a case for any given floating number that is smaller than `0.0`, and negate the result if it turns out not to be negative.
