### ISSUE TITLE
std::iter::Rev breaks order or operation with std::iter::Map

### ISSUE THREAD

**Issue by p-avital** [rust-lang/rust#63301]
Hello,

I've just found out that when you use `it.rev().map(...).rev()`, the two `.rev()` seem to cancel each other. While in most cases, this isn't much of an issue, it does cause problems with stuff such as this:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6427a92ae18c8d79e4bf422041453ba9

Is this behaviour intended ? It doesn't seem quite logical to me, but I can see how this kind of pattern could be difficult to implement efficiently without a middle collection step like in the `good()` function.

Best regards :)

**Comment by jonas-schievink** [comment]
I think that this is expected. If you call `rev()` on an iterator chain, all that happens is that a lazy adapter gets created that calls `next_back()` instead of `next()`. This means that your `map` closure will also be called "in reverse" (ie. with the last element of the preceding iterator first).

**Comment by scottmcm** [comment]
This is documented in <https://doc.rust-lang.org/nightly/std/iter/struct.Map.html#notes-about-side-effects>, so I'm going to assume it's intentional and close this.  (Arguably `map` should have only taken `Fn`, not `FnMut`, [because the order isn't guaranteed](https://github.com/rust-lang-nursery/api-guidelines/issues/197).  But that can't change now.)
