### ISSUE TITLE
Warn on using intra-doc links on stable

### ISSUE THREAD

**Issue by abonander** [rust-lang/rust#63305]
It would be a significant effort to implement feature-gates in Rustdoc just for intra-doc links so I understand why that hasn't been done.

However, because there is no warning I've been unintentionally creating docs with broken links on stable for a while now. I haven't observed this myself because I prefer nightly compilers and assume it works on stable if there's no feature flags, and docs.rs uses a nightly compiler as well so published docs work fine. It should be relatively easy to produce this warning on stable as most of the same logic already exists to tell the difference between a real URL and an item path: https://github.com/rust-lang/rust/blob/master/src/librustdoc/passes/collect_intra_doc_links.rs#L277

This has caught at least one other user by surprise as well: https://www.reddit.com/r/rust/comments/cm7rhv/hey_rustaceans_got_an_easy_question_ask_here/ew0nvo2/?context=1000

**Comment by abonander** [comment]
cc #43466, @steveklabnik

**Comment by jyn514** [comment]
I'm sympathetic to the issue, but because intra-doc links are so close to stabilizing, I think it makes sense to let this be solved 'naturally' by having them work on stable too :) Especially since any fix would be part of rustdoc, so you'd only see it after the fix itself rode the release train for 12 weeks.

I'll leave this open until intra-doc links are finally stable, though.

**Comment by jyn514** [comment]
Closing this since intra-doc links will be stable in 1.48 and will be a moot point: https://github.com/rust-lang/rust/pull/74430
