### ISSUE TITLE
Lots of "cannot find in scope" errors can make name resolution extraordinarily slow

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#63478]
I missed a `use` and found a `check` that takes _over 4 minutes_ to fail.

Repro: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=aaac7e403ced051c0e4165df25a455a5

time-passes blames this on "name resolution"

**Comment by petrochenkov** [comment]
Suggestion search does a lot of heavy stuff like loading all the known crates and searching names in them (https://github.com/rust-lang/rust/pull/54391) and maybe something else.

This was never profiled or optimized, AFAIK, due to the general stance that "the error case can be slow".
So it's quite possible there are low-hanging fruits there, someone needs to run a profiler on that.

**Comment by Mark-Simulacrum** [comment]
The reproduction in this issue fails to compile in a total of 1.3 seconds with 1.24 seconds spent in name resolution -- and duplicating the set a couple times only gets me up to around ~7 seconds so I feel like this can probably be closed now? It seems sort of "expected" that tons of errors will be slow...
