### ISSUE TITLE
document that target features are unsafe

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#63597]
When discussing https://github.com/rust-lang/rust/issues/63466 in the compiler team triage meeting, it became clear that target-features ought to be considered generally unsafe. We should document this fact in the `-Chelp` and in the [rustc book](https://doc.rust-lang.org/rustc/index.html). Ideally, we'd also start listing out known gotchas. 

For example, in #63466 @nikic noted that:

> https://github.com/rust-lang/rust/issues/63466#issuecomment-521641479

and @rkruppe had a [much more detailed comment](https://github.com/rust-lang/rust/issues/63466#issuecomment-521645648).

This issue has been assigned to @togiberlin via [this comment](https://github.com/rust-lang/rust/issues/63597#issuecomment-526267979).

**Comment by nikomatsakis** [comment]
Compiler triage meeting:

Marking as P-medium

**Comment by gnzlbg** [comment]
The reference section about [Behavior considered undefined](https://github.com/rust-lang-nursery/reference/blob/master/src/behavior-considered-undefined.md#behavior-considered-undefined) mentions this.

**Comment by rkruppe** [comment]
That is one way in which target_feature is unsafe, but it's not the one which was the subject of #63466 so just pointing at the reference as it is is insufficient. Plus, it's also more about `-C target-feature` than `#[target_feature]` (where the compiler will hit you in the face with `unsafe`). So the rustc book is a better place for it than the reference IMO.

**Comment by gnzlbg** [comment]
I think that for users to better properly understand the UB involved, it might be more educational to say that `-C target-feature=+X` stamps `#[target_feature(enable = "X")]` on all functions, but with the subtle difference that it doesn't make them `unsafe fn`. 

The reference does not document all current perils of using `#[target_feature(enable = "X")]`. In particular, it does not document that these can change the function call ABI, and that rustc neither checks that nor handles it correctly - we just currently assume people don't do that. 

Independently of whether we document that in the rustc book as well or not, that bit should also probably be documented in the reference, because it is easy to trigger this. On stable Rust, _I think_ one can indeed only trigger this via `-C target-feature` and the reference should say so, but on nightly one can definitely trigger this with bare `#[target_feature(enable = "...")]` within a single Rust crate.
