### ISSUE TITLE
hygiene: cannot find macro `foo!` in this scope

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#63685]
This code ([playpen]) compiles on stable but not on nightly and beta:
```rust
macro_rules! foo {
    () => {
        "foo"
    };
}

macro_rules! bar {
    () => {
        foo!()
    };
}

fn main() {
    println!(bar!());
}
```

[playpen]: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8b3bc98ae358e6ff16fb7dc4003c6233

Standard Error

```rust
   Compiling playground v0.0.1 (/playground)
error: cannot find macro `foo!` in this scope
 --> src/main.rs:9:9
  |
9 |         foo!()
  |         ^^^

warning: unused macro definition
 --> src/main.rs:1:1
  |
1 | / macro_rules! foo {
2 | |     () => {
3 | |         "foo"
4 | |     };
5 | | }
  | |_^
  |
  = note: `#[warn(unused_macros)]` on by default

error: aborting due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

**Edit**: Removed `concat!` macro

_Originally posted by @lzutao in https://github.com/rust-lang/rust/issues/63460#issuecomment-522294181_

**Comment by lzutao** [comment]
I updated the snippet that had outer module.

**Comment by petrochenkov** [comment]
This is a regression from https://github.com/rust-lang/rust/pull/63114 (cc @matthewjasper).
Slightly more minimized reproduction will look like this:
```rust
macro_rules! foo {
    () => {
        "foo"
    };
}

macro_rules! bar {
    () => {
        foo!()
    };
}

fn main() {
    format_args!(bar!()); // ERROR, `foo` is not found, happens because `format_args` is opaque now
}
```

`format_args` performs eager expansion on its arguments and hygienic context of `foo` produced by such expansion looks like it was produced by the opaque `format_args` for some reason, so it's resolved at `format_args`' definition site.

It maybe either some issue with hygiene infra interacting with eager expansion, but it also may be caused by incorrect spans produced by `format_args`.

**Comment by petrochenkov** [comment]
(I'm currently looking into the details.)

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/63717.
