### ISSUE TITLE
Impl HasDataLayout and HasTargetSpec for T where T: HasTyCtxt

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#63857]

**Comment by varkor** [comment]
What's the context for this issue?

**Comment by bjorn3** [comment]
It makes life easier for people who have to implement `HasDataLayout` and `HasTargetSpec` on a type themself. For example codegen backends.

**Comment by oli-obk** [comment]
do you have some pointers to codegen_cranelift or codegen_llvm where we could simplify things after doing this change? Then we could mark the issue as E-mentored or sth to attract ppl to address it.

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rust/blob/1e13a9bb33debb931d603278b7f1a706b0d11660/compiler/rustc_codegen_llvm/src/context.rs#L767-L779 and https://github.com/rust-lang/rust/blob/df3d86b535182cd52927405a4316ad688d2240f8/compiler/rustc_codegen_cranelift/src/common.rs#L275-L279 / https://github.com/rust-lang/rust/blob/df3d86b535182cd52927405a4316ad688d2240f8/compiler/rustc_codegen_cranelift/src/common.rs#L287-L291

could be removed if `HasDataLayout` and `HasTargetSpec` are implemented for all types implementing `HasTyCtxt` automatically.

**Comment by ebobrow** [comment]
Hey! I wanted to try working on this, but I'm a little stuck. I can't write the implementations in the `rustc_target` crate, where `HasDataLayout` and `HasTargetSpec` are defined, because the `rustc_middle` crate already depends on that crate and it would create a dependency cycle if I tried to import `HasTyCtxt`. However, if I try to write the implementation in the `rustc_middle` crate, where `HasTyCtxt` is defined, I get
```
error[E0210]: type parameter `T` must be used as the type parameter for some local type (e.g., `MyStruct<T>`)
    --> compiler/rustc_middle/src/ty/layout.rs:2003:12
     |
2003 | impl<'tcx, T> HasTargetSpec for T
     |            ^ type parameter `T` must be used as the type parameter for some local type
     |
     = note: implementing a foreign trait is only possible if at least one of the types for which it is implemented is local
     = note: only traits defined in the current crate can be implemented for a type parameter
```
Is there a way around this issue? This is my first contribution to Rust, so apologies if I'm missing something obvious. Thanks!

**Comment by bjorn3** [comment]
Hm, looks like the coherency check is throwing a wrench into this. I don't think there is a way around this issue. Thanks for trying anyways @ebobrow. If you want you can try to fix another E-easy issue.
