### ISSUE TITLE
[1.38] Regression: failed to resolve: use of undeclared type or module `SliceConcatExt`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#63892]
https://github.com/rust-lang/rust/issues/63628#issuecomment-524634090

>failed to resolve: use of undeclared type or module `SliceConcatExt`

```
./gh/echupriyanov/tls-ws/beta-2019-08-13.txt:[INFO] [stderr] error[E0433]: failed to resolve: use of undeclared type or module `SliceConcatExt`
```

`SliceConcatExt` was an unstable standard library trait removed in https://github.com/rust-lang/rust/pull/62403.

**Comment by Mark-Simulacrum** [comment]
Closing as expected breakage (cc @rust-lang/libs, but this is so minimally breaking and was an unstable use).

**Comment by SimonSapin** [comment]
Ouch, it turns out an unstable trait in the prelude can be *named* without any `#![feature(…)]` opt-in.

https://github.com/echupriyanov/tls-ws/blob/d458e2edfabc7e28494482987afbb5eebba1de7f/src/bin/server.rs#L117 reduced:

```rust
fn main() {
    dbg!(SliceConcatExt::join(&["foo", "bar"][..], "-"));
}
```

Not to say that we should revert or do anything else here, but to keep in mind next time we consider adding an unstable trait in the prelude. Or should we consider that a compiler bug?

**Comment by Mark-Simulacrum** [comment]
Yeah, looks like a compiler bug (probably similar to the other stability problems with 'absolute' paths -- if we're importing it for you it probably bypasses stability by looking like a root path?
