### ISSUE TITLE
Wasm code failing regression probably related to update to LLVM 9 trunk 

### ISSUE THREAD

**Issue by thiolliere** [rust-lang/rust#63918]
# Summary:

The following piece of code fail when compiled to wasm32-unknown-unknown since nightly-2019-07-18. This nightly introduces https://github.com/rust-lang/rust/pull/62592/files so probably related.

# Regression test:

```rust
pub fn get() -> u128 {
	let d = [0, 0, 32, 59, 157, 181, 5, 111, 0, 0, 0, 0, 0, 0, 0, 0];
	decode_impl(&mut &d[..]).unwrap()
}

#[no_mangle]
fn main() {
	let c: u128 = get();
	assert_eq!(c, 8000000000000000000u128);
}

#[inline(never)]
fn decode_impl(input: &mut &[u8]) -> Result<u128, ()> {
	let mut buf = [0u8; 16];
	read(input, &mut buf)?;
	Ok(<u128>::from_le_bytes(buf))
}

#[inline(never)]
fn read(input: &mut &[u8], into: &mut [u8]) -> Result<(), ()> {
	if into.len() != input.len() {
		return Err(());
	}
	into.copy_from_slice(&input[..]);
	Ok(())
}
```

with configuration:
```toml
[lib]
name = "code"
crate-type = [
	"cdylib",
	"rlib",
]

[profile.release]
opt-level = "z"
```

# Reproduce:

see the repo: https://github.com/thiolliere/wasm-llvm9-issue it contains:
* javascript file `t.js` used to execute test with node.
* `make.sh` file to execute the test on rust version 2019-07-17 and 2019-07-18.

# Notes:

* probably introduced by https://github.com/rust-lang/rust/pull/62592/files
* if you remove either `"rlib"` or `opt-level = "z"` it works (it is not failing anymore)

cc @pepyakin

**Comment by pepyakin** [comment]
I changed an example a bit, minimized it from the size of wasm binary prespective and used some c-reduce (which hasn't yield much improvements).

```rust
#![no_std]
use core::arch::wasm32::unreachable;
#[panic_handler]
fn panic_handler(_: &core::panic::PanicInfo) -> ! {
    unsafe { unreachable() }
}
#[no_mangle]
fn main() {
    let b = c();
    if b != 8000000000000000000u128 {
        unsafe { unreachable() }
    }
}
pub fn c() -> u128 {
    let d = [0, 0, 32, 59, 157, 181, 5, 111, 0, 0, 0, 0, 0, 0, 0, 0];
    match e(&mut &d[..]) {
        Ok(f) => f,
        _ => unsafe { unreachable() },
    }
}
#[inline(never)]
fn e(g: &&[u8]) -> Result<u128, ()> {
    let mut buf = [0; 16];
    h(g, &mut buf).ok_or_else(|| ())?;
    Ok(u128::from_le_bytes(buf))
}
fn h(g: &&[u8], i: &mut [u8]) -> Option<()> {
    if i.len() != g.len() {
        return None;
    }
    i.copy_from_slice(g);
    Some(())
}
```

compiling with

```
rustc --crate-name code lib.rs --crate-type cdylib --crate-type rlib -C opt-level=z -C codegen-units=1 --target=wasm32-unknown-unknown
```

there is no notable difference in [LLVM IR](https://gist.github.com/pepyakin/cc56ab8ab9ef967ebbc4090714ef7c2d), only some identifiers and added imm arg in e.g. `declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #4` which I believe is not related.

The miscompilation seems to happen around `c` function, specifically when copying low and high parts of the u128 by the out RVO ptr ([gist](https://gist.github.com/pepyakin/7659c7a88e64cd56791c06b4b437c99a#file-ok-wat-L67-L78)):

```webassembly
;; local 1 = SP
;; local.2 = i64.load(sp + 16)
      get_local 1
      i32.const 16
      i32.add
      i64.load
      set_local 2
;; *out.0 = i64.load(sp + 8)
      get_local 0
      get_local 1
      i64.load offset=8
      i64.store
*(out.0+8) = local.2
      get_local 0
      get_local 2
      i64.store offset=8
```

in miscompiled version we just do this ([gist](https://gist.github.com/pepyakin/7659c7a88e64cd56791c06b4b437c99a#file-err-wat-L71-L73)):

```webassembly
;; *out.0 = local.2
    get_local 0
    get_local 2
    i64.store
```

which doesn't make a lot of sense since `local.2` should hold i64 of descriminator of `Option`.

All this makes me think (although I am of course not sure) that this is a LLVM IR to wasm32 lowering bug, so cc @sunfishcode

**Comment by pepyakin** [comment]
What I meant is that the descriminator of the `Result` returned by `e` (which is `u64`, AFAIR) is stored in first half of the out ptr `*u128` (which is the return value of `c` as you noted)

**Comment by nikomatsakis** [comment]
Visiting for compiler triage meeting. I'm marking this as a "P-medium" bug since it is specific to WASM and also due to an LLVM bug. I'm not sure if we plan to fix this on our side in any way?

**Comment by sunfishcode** [comment]
The reduced testcase is now fixed in [r370430](https://github.com/llvm/llvm-project/commit/8cfeeaf9de0b24248be1074c7593107c748cc16c).
