### ISSUE TITLE
Call pinned method from Trait on generic parameter

### ISSUE THREAD

**Issue by Jonathas-Conceicao** [rust-lang/rust#63966]
I've found a problem regarding [Pin](https://doc.rust-lang.org/nightly/std/pin/struct.Pin.html) that I just can't solve and the current Nightly compiler gives a misleading suggestion.

[This playground example serves well as a minimalist example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=12f320922559410ace38822a309b94a4). I can't manege to call `quack` on the `Animal` inside the `Transporter` even with the restriction to `Animal: Quack`.

And the Nightly compiler suggests:
```
   = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `quack`, perhaps you need to restrict type parameter `Animal` with it:
   |
17 | impl<Animal: Quack + Quack> Quack for Transporter<Animal> {
   |      ^^^^^^^^^^^^^^^
```
Which clearly doesn't really solve anything.

If a take off the `Pin` from the Traits and it's impl and just use a `&self` I can get the expected `Quack!` from inside the transporter.

The compiler suggestion surely doesn't seams right to me, but what about the `Pin`? Am I missing something or is there a bug too?

**Comment by Aaron1011** [comment]
@Jonathas-Conceicao: as @memoryruins mentioned, the diagnostic suggestions are wrong in this case.

You're trying to go from a `Pin<&MyType>` to a `Pin<&MyField>`, where `&MyField` is a reference to a field of `MyType`. This is known as a [pinned projection](https://doc.rust-lang.org/std/pin/index.html#projections-and-structural-pinning), and comes with some additional requirements in order to be sound.

\<shameless-plug\>You might want to take a look at the [pin-project](https://github.com/taiki-e/pin-project) crate (disclaiminer: I'm a contributor), which makes it easy to write safe pin projections.

**Comment by taiki-e** [comment]
The diagnostic issue seems to dup of #57994.

**Comment by Jonathas-Conceicao** [comment]
@Aaron1011, thank you for the explanation and the suggestion, that does indeed solve the error.

Regarding the suggestion, it really does seams to be a duplicate, will be closing this in favor of #57994.
