### ISSUE TITLE
Self::fn_name returns non-static fn item

### ISSUE THREAD

**Issue by CodeSandwich** [rust-lang/rust#63981]
It's hard to describe, but this fails to compile [playground](https://play.rust-lang.org/?gist=b8ea20af2f92d025b0fa2176346a971e):
```rust
trait Foo {
    fn bar() {
        Self::bar.type_id(); // Any::type_id, Any requires 'static
    }
}
```
Error:
```
error[E0310]: the parameter type `Self` may not live long enough
 --> src/main.rs:7:19
  |
7 |         Self::bar.type_id();
  |                   ^^^^^^^
  |
  = help: consider adding an explicit lifetime bound `Self: 'static`...
note: ...so that the type `fn() {<Self as Foo>::bar}` will meet its required lifetime bounds
 --> src/main.rs:7:19
  |
7 |         Self::bar.type_id();
  |                   ^^^^^^^
```
I think that it's wrong, because both `Self` and trait function are always static, they're created at compilation and are always available.

**Comment by CodeSandwich** [comment]
@jonas-schievink This bug is a big problem for me and I want to fix it. Unfortunately I couldn't find the spot to fix and I don't even know where to start. I have zero experience with the codebase. Who could help me and guide me?

**Comment by jonas-schievink** [comment]
@CodeSandwich You might want to ask around in the language/compiler discord channels or on Zulip

**Comment by HyeonuPark** [comment]
I think this is correct. If we have `impl<'a> Foo for Baz<'a>` where Baz is `struct Baz<'a>(&'a u8)`, `<Baz as Foo>::bar` is not `'static` and for every possible occurrence of `'a` `Baz::<'a>::bar` has different types, thus it should have different type id if we allow it.

**Comment by CodeSandwich** [comment]
This shouldn't affect associated functions. No matter how many monomorphized versions are generated, they all are static. It doesn't even matter if their parameters have lifetimes or structs generating them are generic over lifetime.

**Comment by HyeonuPark** [comment]
Actually, "how many monomorphized versions are generated" is the reason why we don't allow to generate type id for non-`'static` ones. Note that every possible pairs of lines in MIR can generate different lifetimes. Should compiler generate typeid for all of them during compilation?

**Comment by CodeSandwich** [comment]
That's s valid reason to make `TypeId` require static. But this isn't a good reason to make generic-generated functions non-static. It's perfectly fine to store such function in a static container, it's not going anywhere. It will also be forever valid to use as long as its argument lifetime constraints are fulfilled. I start suspecting a problem around assumption that every static data must have precise type ID.

**Comment by rkruppe** [comment]
Although none of the parameters of `bar` mention `Self` (and thus, any lifetimes that may be contained in `Self`), the `Self` type still has to be "part of" the function item type. For example, `<i32 as Foo>::bar` and `<i8 as Foo>::bar` (assuming such impls exists) are different functions, and each distinct function has its own unique type.

I'm not familiar with how this is represented internally, but on a type system level I don't really see how `typeof(<T as Foo>::bar)` could "forget" or otherwise not contain `T` without contradicting that `<T as Foo>::bar` has a different type from `<U as Foo>::bar` whenever `T` and `U` are different. And likewise it seems difficult to say that `<T as Foo>::bar` contains `T` but outlives lifetimes that `T` doesn't outlive.

**Comment by Mark-Simulacrum** [comment]
Yes, this seems like correct and expected behavior; I suspect that you may be trying to get the TypeId of the default impl; that can likely be done with a dummy struct implementing the trait and doing Foo::bar.type_id() or so.
