### ISSUE TITLE
Suggest borrowing when doing `if let Some(_)` from non-Copy ADT

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#63988]
Just got this error:

```
error[E0382]: borrow of moved value: `x`
    --> src/librustc_mir/hair/pattern/_match.rs:1614:53
     |
1611 |                         if let Some(range) = x {
     |                                     ----- value moved here
...
1614 |                         debug!("intersection {:?}", x);
     |                                                     ^ value borrowed here after partial move
     |
     = note: move occurs because value has type `hair::pattern::_match::IntRange<'_>`, which does not implement the `Copy` trait

error: aborting due to previous error
```

It should suggest to borrow `x`.

**Comment by sam09** [comment]
Looks like this is unclaimed? I would like to pick it up in that case

**Comment by ayazhafiz** [comment]
@estebank can you elaborate on the message you expect to see here? Something like

```
error[E0382]: borrow of moved value: `x`
    --> src/librustc_mir/hair/pattern/_match.rs:1614:53
     |
1611 |                         if let Some(range) = x {
     |                                     ----- value moved here
...
1614 |                         debug!("intersection {:?}", x);
     |                                                     ^ value borrowed here after partial move
     |
     = note: move occurs because value has type `hair::pattern::_match::IntRange<'_>`, which does not implement the `Copy` trait
       Consider borrowing `x` rather than moving it.
```

perhaps?

**Comment by estebank** [comment]
@ayazhafiz I believe we should aim at:

```
error[E0382]: borrow of moved value: `x`
    --> src/librustc_mir/hair/pattern/_match.rs:1614:53
     |
1611 |                         if let Some(range) = x {
     |                                     -----    - help: consider borrowing here: `&x`
     |                                     |
     |                                     value moved here
...
1614 |                         debug!("intersection {:?}", x);
     |                                                     ^ value borrowed here after partial move
     |
     = note: move occurs because value has type `hair::pattern::_match::IntRange<'_>`, which does not implement the `Copy` trait
```

**Comment by ayazhafiz** [comment]
I took a look at this today. I am a first-time contributor to this project and would like to contribute this enhancement, but I'm not sure how much work this will end up requiring. Here are some notes/leads I've noticed; I'm hoping someone may be able to provide suggestions, and at the very least I hope this is helpful for anyone else wishing to tackle this.

Consider the example provided in the first comment of this issue (abbreviated for example):

```
error[E0382]: borrow of moved value: `x`
    --> src/librustc_mir/hair/pattern/_match.rs:1614:53
     |
1611 |                         if let Some(range) = x {
     |                                     ----- value moved here
...
1614 |                         debug!("intersection {:?}", x);
     |                                                     ^ value borrowed here after partial move
```

This error message is generated by `MirBorrowckCtxt#report_use_of_moved_or_uninitialized`:

https://github.com/rust-lang/rust/blob/a6624ed9806fe4caa10de5b94e590f71a4a1eab9/src/librustc_mir/borrow_check/conflict_errors.rs#L47-L53

This function knows about the erroring span (where the value is borrowed after a move; `x` in ` debug!("intersection {:?}", x)` in the example above) and the location of where the value was moved (`range` in the example above).

It's not immediately clear to me that it's easy to recover the span of the RHS of `Some(range) = x` from here, which is the span we want to give a suggestion for. However, `MirBorrowckCtxt` seems to know about move sites, and about where values are moved out of:

https://github.com/rust-lang/rust/blob/7eb65dfe66e56618f87531cdc378865135c47efb/src/librustc_mir/dataflow/move_paths/mod.rs#L100-L102

https://github.com/rust-lang/rust/blob/7eb65dfe66e56618f87531cdc378865135c47efb/src/librustc_mir/dataflow/move_paths/mod.rs#L156-L168

I have a feeling that a `MoveOut.source` is what we're looking for (I assume it would describe the moving out of `x` in `Some(range) = x`), but am not entirely certain of that. It's also not yet clear to me how to convert a `MoveOut` source into a `Span` that can be used to give a suggestion.

Looking from the top-down is interesting but doesn't seem too useful. One of the lower-stack callers that generates this error is `MirBorrowckCtxt#consume_rvalue`:

https://github.com/rust-lang/rust/blob/7eb65dfe66e56618f87531cdc378865135c47efb/src/librustc_mir/borrow_check/mod.rs#L1218-L1261

Which does exactly what it sounds like, consuming an rvalue (seemingly `x` in ` debug!("intersection {:?}", x)` in the example above) and checking for any errors. This doesn't seem too helpful for this problem because the actual checking of move sites isn't done until higher up the call stack, particularly in `MirBorrowckCtxt#report_use_of_moved_or_uninitialized`.

Right now, I think looking at `MirBorrowckCtxt#report_use_of_moved_or_uninitialized` and the `MoveOut` struct are the most likely paths to get closer to solving this. I definitely have many knowledge gaps, and am likely misunderstanding a lot, so any suggestions would be appreciated. Otherwise, I hope it can provide some baseline information for anyone else interested in this.
