### ISSUE TITLE
Dependencies with build script fail on FreeBSD + 1.39 nightly

### ISSUE THREAD

**Issue by johalun** [rust-lang/rust#64006]
Tested on various crates like bindgen, backtrace, async-std, etc, that has one or more -sys dependencies that include a build.rs file. All such deps fail with errors like:
```
error: failed to run custom build command for `openssl-sys v0.9.49`

Caused by:
  process didn't exit successfully: `/usr/home/johannes/dev/curl-test/target/debug/build/openssl-sys-7d3ff8c9464a6e09/build-script-main` (signal: 11, SIGSEGV: invalid memory reference)
```

```
error: failed to run custom build command for `backtrace-sys v0.1.31`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installOYpgIo/release/build/backtrace-sys-8309d2ffb8202182/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)
--- stdout
cargo:rustc-cfg=rbt

warning: build failed, waiting for other jobs to finish...
```

stable and beta works fine, this only happens for nightly 1.39
```
johannes@jm:~/dev/curl-test % rustc -V
rustc 1.39.0-nightly (17e73e801 2019-08-28)
johannes@jm:~/dev/curl-test % cargo -V
cargo 1.39.0-nightly (22f7dd049 2019-08-27)
```

**Comment by cuviper** [comment]
It could be this: https://github.com/rust-lang/libc/issues/1489

**Comment by nikomatsakis** [comment]
check-in from compiler triage:

Although this is a regression, it's also affecting freebsd only (right?) which is a lower tier platform, and therefore I'm marking as P-medium. There is a pending fix in #64019, although it sounds like that fix will need to be verified once it lands (not a guarantee). If @johalun you are able to do a custom build of rustc and give that fix a try, that'd be good too, but otherwise you can wait for it to land.

Feel free to re-nominate if you feel the priority is misassigned.

**Comment by mati865** [comment]
@johalun could you check if this works in latest nightly?

**Comment by johalun** [comment]
Test with async-std and backtrace-rs and it is working as expected now.
Thanks!

**Comment by jonas-schievink** [comment]
Closing as fixed
