### ISSUE TITLE
`-(-0.0)` raises const_err "attempt to negate with overflow"

### ISSUE THREAD

**Issue by sinkuu** [rust-lang/rust#64059]
```rust
fn main() {
    let _ = -(-0.0);
}
```

```
error: this expression will panic at runtime
 --> test.rs:2:13
  |
2 |     let _ = -(-0.0);
  |             ^^^^^^^ attempt to negate with overflow
  |
  = note: `#[deny(const_err)]` on by default

error: aborting due to previous error
```

<details><summary>Meta</summary>

```
rustc 1.39.0-nightly (fba38ac27 2019-08-31)
binary: rustc
commit-hash: fba38ac27e2ade309f4c2504a6d6cd3556972a28
commit-date: 2019-08-31
host: x86_64-unknown-linux-gnu
release: 1.39.0-nightly
LLVM version: 9.0
```

</details>

**Comment by Centril** [comment]
cc @oli-obk

**Comment by oli-obk** [comment]
Huh...

```rust
const X: f32 = -(-0.0);
const Y: f64 = -(-0.0);
```

compiles fine.

https://github.com/rust-lang/rust/blob/d0677b9abc143d64d6b0cd6720e36eb73674632f/src/librustc_mir/transform/const_prop.rs#L414

is the cause, I believe we don't need this anymore. We are now emitting the warning on the `TerminatorKind::Assert` that precedes it.

So in order to fix this (and deduplicate a bunch of warnings in our test suite), remove https://github.com/rust-lang/rust/blob/d0677b9abc143d64d6b0cd6720e36eb73674632f/src/librustc_mir/transform/const_prop.rs#L410-L421 and rerun all ui tests with `--bless`
