### ISSUE TITLE
manifest path to bootstrap/Cargo.toml does not exist, when it does

### ISSUE THREAD

**Issue by whitequill** [rust-lang/rust#64336]
I do not know what is going on when I am building rust from source. 
what is going on is that I run `python x.py build` and it caches `rust-std-beta-i686-pc-windows-gnu` for whatever reason even though I've set my target in config.toml to be `x86_64-pc-cygwin`
so I'd think it should be caching the `x86_64` version.

Then after its gotten to the part where is tries to run bootstrap/Cargo.toml it errors with 
```
error: manifest path `/home/brazg/source/rust/src/bootstrap/Cargo.toml` does not exist
failed to run: /home/brazg/source/rust/build/i686-pc-windows-gnu/stage0/bin/cargo build --manifest-path /home/brazg/source/rust/src/bootstrap/Cargo.toml
 ```
I don't know why because if I go to the directory in question `/home/brazg/source/rust/src/bootstrap/`, `Cargo.toml` is there.

Any ideas as to what is going on?

**Comment by Mark-Simulacrum** [comment]
I'm afraid not. Can you provide a full log, along with steps to reproduce, ideally starting with `git clone` of rust-lang/rust?

**Comment by whitequill** [comment]
college happened. 
yes I can.

1) I did was a pulled the git sources into a folder called, _rust-lang_ in my home directory.
 because I've learned its good practice not to build in the source directory.
2) I made a directory in my home directory called, `build-rust`.
3) I then ran `../path/to/git/source/configure`
4) it then prompted me to `run 'python /home/brazg/gitrepos/rust-lang/x.py --help'`
my build directory now contained the files `config.toml` and `Makefile`
5)  I then changed line 442 to my desired target system.
6) I lastly ran the python command given by running configure.
[output from python command](https://pastebin.com/fy00v8Yu)

at the very end of the output it gives the error I posted.

**Comment by Mark-Simulacrum** [comment]
I am not sure that Rust currently supports out of tree builds, though the directory can be a subdirectory of the source directory (e.g. rust/obj). This isn't generally necessary though, it is common practice to use x.py normally inside the Rust checkout, without a separate build directory. 

I'm going to close as won't fix in that regard because I don't think we should support this, but I may accept a PR to do so if it's minimally invasive.

Feel free to let me know if I've incorrectly diagnosed the problem and things don't start working intree and we can reopen.
