### ISSUE TITLE
Spurious "found two different crates with name `alloc`" errors in PR builder

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#64389]
- https://github.com/rust-lang/rust/pull/64378#issuecomment-530412814
- https://github.com/rust-lang/rust/pull/64429#issuecomment-531692042

**Comment by Mark-Simulacrum** [comment]
Some relatively unscientific digging for where we create SVHs dug up this [bit of code](https://github.com/rust-lang/rust/blob/74d5c70b174f06843049af2d764ff57ddc81c81c/src/librustc/hir/map/collector.rs#L188-L195) -- that sort_unstable looks rather suspicious, as it's presumably possible for two crates with different hashes to end up in a different order, and then when we go on to hash it it'll lead to problems down the line if the sort resulted in a different ordering then we'd expect.

To be clear, thinking some more about this, I think it's presumably fine for this to be an unstable sort since an unstable sort should still have stable output, it just might be different than input order, AIUI -- what's _not_ fine is that we're introducing non-determinism by not sorting by hash.

cc @michaelwoerister who I believe is the original author of this bit of code in 8129c539582942e67bb581b2e88d40242ba6fc0f

cc @Zoxc @aturon -- this is a potentially interesting case for wg-parallel-rustc to examine, as it's a case where we need to be careful about ordering in a subtle way -- the output of a query is assumed to be ordering-stable across compilations, otherwise this svh computation won't work well I believe, though not certain

**Comment by Mark-Simulacrum** [comment]
Another note is that this is likely to prove rather hard to track down as to what caused this as we've seen relatively few of these errors - the PR description lists one case, and anecdotal data suggests maybe around 6 or so errors that we've noted like this. Interestingly, all were specifically in these liballoc doctests which explicitly have an `extern crate alloc;`; maybe that points to the bug (Cc @petrochenkov, in case this is somehow resolver related). I suspect that means we have something like two extern crate allocs in these tests due to rustdoc auto-insertion, but haven't verified.

I personally suspect this is sort of due to https://github.com/rust-lang/rust/pull/63470 which likely causes us to keep around more artifacts than previously and perhaps one of those is contaminating the path whereas it didn't before; to be clear, this exposed the bug perhaps but almost certainly didn't cause it.

**Comment by ehuss** [comment]
Has this happened before #63827?

**Comment by Mark-Simulacrum** [comment]
I believe so, but not completely confident. It occurs really rarely, so it's hard to be certain unfortunately.

**Comment by Centril** [comment]
I haven't seen this reproduced for a long time so I'll close it for now.

**Comment by mati865** [comment]
There was similar error recently but with `bitflags` when building rustdoc: https://github.com/rust-lang/rust/pull/66108

**Comment by Enselic** [comment]
Triage: Has anyone here seen this error in recent years?

**Comment by ehuss** [comment]
GitHub search shows the most recent this particular message was in #67281, 4 years ago.

The error message has since changed. I'm going to close, since I don't think this is a direct issue anymore. Here are my notes:

The error appeared when compiling `alloc` doctests, while loading the `alloc` library via `extern crate alloc;`.
```
error[E0523]: found two different crates with name `alloc` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
```

There was a verification step in `creader.rs` which would check if two crates have the same stable crate ID, but different SVH, and it would raise that error.

https://github.com/rust-lang/rust/pull/100928 migrated to use the new diagnostics.

https://github.com/rust-lang/rust/pull/100599 removed the particular message and replaced it with a bug!:
```
bug!(
    "Previously returned E0523 here. \
     See https://github.com/rust-lang/rust/pull/100599 for additional discussion.\
     root.name() = {}.",
    root.name()
);
```

Looks like the authors couldn't find a way to create a test for it, and thought that maybe it was an unreachable section.
However, jyn happened to run into it after bug! was added.

Shortly afterwards, the bug! and SVH check was simply removed in https://github.com/rust-lang/rust/pull/109213 which refactored things to eagerly verify collisions (updated in https://github.com/rust-lang/rust/pull/111461). Now, if there are two crates with the same stable crate ID, the errors are now:
- If collision with local crate:
    SymbolConflictsCurrent
    E0519 the current crate is indistinguishable from one of its dependencies: it has the same crate-name `{$crate_name}` and was compiled with the same `-C metadata` arguments. This will result in symbol conflicts between the two.
- If it knows the name of the other:
    StableCrateIdCollision
    found crates (`{$crate_name0}` and `{$crate_name1}`) with colliding StableCrateId values.
- If it doesn't know the name of the other:
    NotFound
        CannotFindCrate
        can't find crate

Searching for those error messages doesn't pull up anything recent.
