### ISSUE TITLE
mips-linux-musleab is broken again because it uses the wrong crt for static pie

### ISSUE THREAD

**Issue by aep** [rust-lang/rust#64547]
somewhen between nightly-2019-08-30 and nightly-2019-09-15 the link call was changed to "-static" "-pie" but the crt in mips-linux-musleabi has't changed. it should be rcrt, but instead links the one intended for call via libc via .interpr

result is segv in dlstart

the correct solution is to not ship crt, but since that seems to have no agreement, the intermediate fix would be to either remove -static or use the correct crt

**Comment by mati865** [comment]
It'd be really helpful if you could bisect this issue to the single nightly.

**Comment by petrochenkov** [comment]
`-static -pie` is (counter-intuitively) equivalent to `-static`, i.e. `-pie` in this case is suppressed, so using rcrt shouldn't be necessary and I'm not sure what causes the issue exactly.

https://github.com/rust-lang/rust/pull/70740 adds proper support for `-static-pie` including rcrt, so this issue was likely fixed somewhere on the way.

I'll close this issue in a ~week if an up-to-date reproduction doesn't appear.

**Comment by aep** [comment]
Sorry we no longer use rust. Close sounds good.
