### ISSUE TITLE
The behaviour of `librustc_errors::Handler::reset_err_count` seems to contradict its documentation

### ISSUE THREAD

**Issue by AnthonyMikh** [rust-lang/rust#64976]
The function: https://github.com/rust-lang/rust/blob/702b45e409495a41afcccbe87a251a692b0cefab/src/librustc_errors/lib.rs#L473

Citing the doc comment for this function: 

```rust
    /// NOTE: *do not* call this function from rustc. It is only meant to be called from external
    /// tools that want to reuse a `Parser` cleaning the previously emitted diagnostics as well as
    /// the overall count of emitted error diagnostics.
```

However, in the body of this function the field `emitted_diagnostics` (which is `FxHashSet<u128>`) is rewritten by `Default::default()`, so it effectively frees the allocated memory instead of reusing it. Although the comment above that line underlines that this is intended, it seems to contradict the claimed behaviour.

cc @Centril, @estebank. Also tagging @oli-obk as the one who introduced this behaviour [in this commit](https://github.com/rust-lang/rust/commit/ab3f37ec43b0ca842baf5d79416eb0f86195cda6)

**Comment by Mark-Simulacrum** [comment]
Note that it says reuse a _Parser_; clearing out the memory is just a performance hit not really all that important. I don't personally think it's worth tracking this since if anything it's a minor performance optimization (less allocations) -- in particular since this is intentional based on that commit.
