### ISSUE TITLE
an empty `:vis` doesn't work in trait declaration

### ISSUE THREAD

**Issue by limira** [rust-lang/rust#65041]
I want to create a macro that generate `fn`s that use in both `impl Item...` and `trait TraitName`. In `trait`, `pub` must be omitted, but in `impl SomeStruct` I need `pub`, so the macro need a `$vis:vis` like this:

```rust
macro_rules! create_method {
    ($vis:vis $name:ident) => {
        $vis fn $name(&self) {
            println!("{}", stringify!($name));
        }
    }
}

trait T1 {
    // This not works
    create_method!(method_of_t1);
}

trait T2 {
    fn method_of_t2(&self);
}

struct Struct;

impl T2 for Struct {
    // This works
    create_method!(method_of_t2);
}

impl Struct {
    // I want this method to be `pub`, so the macro need a `:vis`
    // for receiving the visibility keyword like this:
    create_method!(pub another_method);
}
```
Expected result: `create_method!(method_of_t1);` in `trait T1` should works.

(**Edit**: a better comment about the `:vis` in `impl Struct`)

**Comment by petrochenkov** [comment]
@Centril 
This looks relevant to https://github.com/rust-lang/rust/pull/64910#issuecomment-536552629 and the parser work you've been doing recently.

**Comment by Centril** [comment]
> ```rust
>     // The macro need a `:vis` to generate `fn` for a normal `impl`
> ```

This bit doesn't seem right; when I remove the `pub` it works (which is expected because the `impl T2 for Struct {` works).

Looking at `fn parse_trait_item_` there seems to be something odd going on. In particular we have:

- `self.eat_bad_pub();`

- `} else if let Some(mac) = self.parse_assoc_macro_invoc("trait", None, &mut false)? {`

   (note the `None` here -- for `fn parse_impl_method` we instead have:

   `if let Some(mac) = self.parse_assoc_macro_invoc("impl", Some(vis), at_end)? {`

  This suggests this is somehow by design? Odd...!

**Comment by Centril** [comment]
...actually it's not that odd. This code was likely written before we had the `vis` matcher.

I think what we want to do is to use `let vis = self.parse_visibility(false)?;` in`parse_trait_item_` as well and then do a check right after to see if the visibility is not "empty" -- that would probably fix the issue here and allow us to discuss semantic vs. syntactic errors for `pub fn foo` in trait defs later.

**Comment by limira** [comment]
> This bit doesn't seem right;

Sorry for the confusion by the comment. I edit the post, hope it is better now!

**Comment by Centril** [comment]
Finally got around to this. I have a fix in https://github.com/rust-lang/rust/pull/66183.
