### ISSUE TITLE
`incremental = true` as the default in config.toml?

### ISSUE THREAD

**Issue by anp** [rust-lang/rust#65060]
I'm curious whether it would make sense for `incremental = true` to be the default for rustbuild in the absence of another setting.

Per @eddyb on IRC:

```
07:53 <eddyb> it used to be bad for a bit until a few months ago (that is, it would produce a very slow compiler) but nowadays we should just turn it on by default lol
07:53 <eddyb> (feel free to open an issue about it)
07:53 <eddyb> it would need to not be turned on for {stable,beta,nightly} builds (as opposed to regular dev builds), but idk how that's handled (I assume it's still possible to make that distinction)
```

Searching around for incremental-related compiler perf issues it does seem to me that most of them are closed.

**Comment by eddyb** [comment]
cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
We can definitely make incremental the default and just switch it off on any build configured with a non-dev channel. I think that's all CI, not sure, can confirm.

**Comment by jyn514** [comment]
I tried adding this in #76417 and it was closed for various reasons:

- It sometimes breaks.
- It takes about 5GB of extra disk space, which might be too much for some people.
- It often causes 32-bit builds on Windows to fail because rustc needs more memory with incemental objects.

With those in mind does this still make sense to change? If not, I think this should be closed.

**Comment by jyn514** [comment]
Since https://github.com/rust-lang/rust/pull/77004, this is enabled by default for the compiler and library profiles.
