### ISSUE TITLE
`fetch_add` in atomic integers won't check for overflow

### ISSUE THREAD

**Issue by AmatanHead** [rust-lang/rust#65183]
Since the default Rust semantics is to check for overflows in debug, maybe `fetch_add` and `fetch_sub` should check for overflows (in debug), and we should provide `fetch_wrapping_add` and `fetch_wrapping_sub`? Or, if we don't want to introduce breaking changes, we should at least clearly state in documentation that we don't check for overflows (and for signed integers, we might still check for overflows because signed overflow should be UB)?

**Comment by jonas-schievink** [comment]
Signed overflow in not UB in Rust

**Comment by Mark-Simulacrum** [comment]
I think most of the time when working with atomics you usually either don't care or already are aware that you need to handle overflow -- somewhat more so then when normally adding two integers, I think.

We already state "This operation wraps around on overflow." in the docs I believe so that should satisfy the documentation concern.
