### ISSUE TITLE
Provide a way to disable rustdoc keyboard shortcuts

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#65211]
Some people have custom OS or browser-level shortcuts, providing a way to disable these makes it easier for them

**Comment by GuillaumeGomez** [comment]
I can add a setting for it if you want. But do we want to disable all keyboard shortcuts or only a few of them? For example, I doubt that 'S' is conflicting in any layout (but I might be wrong!).

**Comment by GuillaumeGomez** [comment]
But then some features won't be accessible anymore (well, I doubt that the '?' menu would interest people who don't care about provided shortcuts). Also, should we keep the text of the search bar as is even though the shortcuts are disabled?

**Comment by Mark-Simulacrum** [comment]
I think not referring to the shortcuts when they are disabled makes sense; a single button is sufficient IMO as Manish said. If features aren't available without the shortcut, that seems a bit weird, but I'd need a list of such features since I can't think of any other than ? which is obviously useless if shortcuts are off.

Gmail, for example, provides a single button (https://support.google.com/mail/answer/6594?hl=en).

**Comment by GuillaumeGomez** [comment]
Well then, I'll add the option and not change anything else then.
