### ISSUE TITLE
Confusing error message when trying to implement From<GenericLocalType<T>> for Option<T>

### ISSUE THREAD

**Issue by rep-nop** [rust-lang/rust#65247]
I have a local type:
```rust
#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum BadOption<T> {
    Some(T),
    None(Value),
}
```
and I want to `impl<T> From<BadOption<T>> for Option<T>` but the error message suggests that `T` isn't being used as the type parameter for a local type
> type parameter `T` must be used as the type parameter for some local type

Reproduction: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9abd2ab4860140be2859d4767fc027f8

Full error:
```
error[E0210]: type parameter `T` must be used as the type parameter for some local type (e.g., `MyStruct<T>`)
  --> src/main.rs:11:1
   |
11 | impl<T> From<BadOption<T>> for Option<T> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type parameter `T` must be used as the type parameter for some local type
   |
   = note: only traits defined in the current crate can be implemented for a type parameter
```

**Comment by estebank** [comment]
Current output:

```
error[E0210]: type parameter `T` must be used as the type parameter for some local type (e.g., `MyStruct<T>`)
  --> src/main.rs:11:6
   |
11 | impl<T> From<BadOption<T>> for Option<T> {
   |      ^ type parameter `T` must be used as the type parameter for some local type
   |
   = note: only traits defined in the current crate can be implemented for a type parameter
```

**Comment by Aaron1011** [comment]
This is fixed by `#![feature(re_rebalance_coherence)]`, which is [getting stabilized](https://github.com/rust-lang/rust/pull/65879)

**Comment by spunit262** [comment]
[Minimal example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a6c631485a54674714c48ba56ce89eb8) that still error with `#![feature(re_rebalance_coherence)]`

The error message needs to tell the user that the order the types are listed in is important. Maybe some thing like "A local type must appear before type parameters". And change it to "uncovered type parameters" if `re_rebalance_coherence` is on (`Option` covers `T` in OP's example which is why it works under `re_rebalance_coherence`)
