### ISSUE TITLE
Use 'mut' as alias for 'let mut'

### ISSUE THREAD

**Issue by pbbob** [rust-lang/rust#65257]
The idea of shortening `let mut` to `var` has been discussed many times before, and the general consensus always ends up being that it is not a good idea. I would like to propose something a bit different, so please hear me out.

I propose that instead of aliasing `var` to `let mut`, we instead just make `mut` expand into `let mut` when in the context of a variable declaration. For example:
```Rust
let mut foo = 12;
// is identical to
mut foo = 12;
```
This solves the problems (readability, more concise) that people have with `let mut`, whilst not causing the issues that people have (pattern matching and consistancy).

The most common issue people have with aliasing `var` to `let mut` is that it doesn't fit well with patterns, like `let (x, mut y) = ...`. However, `mut` gets rid of this problem, because you wouldn't write `let mut (x, mut y)` if you were trying to pattern match, so why would someone want to write `mut (x, mut y)`? You wouldn't do that, and it wouldn't compile.

This would be optional, of course. `let mut x = 1` would still work fine, and people would just have to option of removing the `let` to let it be implied.

There are a lot of other abbreviations used in rust (`fn`, `mod`, `pub`) that all serve the purpose of writing less. It just doesn't feel right that one of the most commonly used keywords is so long.

:heart::crab:

**Comment by Centril** [comment]
It seems unlikely to me that we would support `mut $ident = $expr;` as a short-hand. I'm personally opposed to it both because it adds unnecessary compiler complexity, stylistic schisms, and for the reasons outlined by @KrishnaSannasi.

However, I've taken the liberty of reusing this issue towards improved diagnostics:

1.

```
mut x = 0;
--- help: missing `let`
```

The idea here is to check `self.token.is_keyword(kw::Mut) && self.look_ahead(1, |t| t.is_ident())`.

2.

```
var x = 0;
--- help: to introduce a variable, write `let` instead of `var`

auto x = 0;
---- help: to introduce a variable, write `let` instead of `auto`
```

The idea here is to check:
```rust
is_ident_var_or_auto && !self.look_ahead(1, |t| is_brace(t))`
```

cc @estebank

**Comment by SimonSapin** [comment]
@Centril Although I would also guess that the initial idea is very unlikely to end up accepted, it feels premature to unilaterally hijack the thread in your very first comment and make it have a different (and in a way opposite) purpose. Teams of the Rust project are designed to make decisions collectively. Improving diagnostics sounds good, but issue numbers are cheap.

**Comment by Centril** [comment]
> @Centril Although I would also guess that the initial idea is very unlikely to end up accepted, it feels premature to unilaterally hijack the thread in your very first comment and make it have a different (and in a way opposite) purpose.

Implementing something as a diagnostic actually brings you closer to a working implementation -- I think more proposals should start out as

> Teams of the Rust project are designed to make decisions collectively. [...]

I will not bother the other language team members with not-fully-formed proposals that we will not accept in either case. I converted the issue into the most actionable and productive thing it could be.
The place for ephemeral discussions is either on Discord or on internals.

If you want to discuss this further, I'm available at Discord (but will not respond to it further here).

> [...], but issue numbers are cheap.

...but wasting everyone's time with things that will go nowhere (because it won't be accepted and because it is not important enough to be raised at the team) is not.

**Comment by nox** [comment]
This issue was literally in the RFCs repo initially, @Centril transferred it from there.

**Comment by carols10cents** [comment]
> Incorrect. Extreme brevity harms readability. See Perl. lol

@burdges Language bashing is not welcome here

**Comment by chocol4te** [comment]
@steveklabnik Wait, so should I unassign here, and assign to the new issue?

**Comment by Centril** [comment]
@chocol4te Nah, just use this one.

**Comment by chocol4te** [comment]
I'm sorry, I've been pretty busy with coursework, and I'm still fighting my Python installation to even build the compiler, let alone make progress on this. Sorry :(

**Comment by Centril** [comment]
I'll assign this to myself to work on when I have time. If you want to work on it however, feel free to work-steal it from me!

**Comment by JesterOrNot** [comment]
I would like to help with this

**Comment by Centril** [comment]
@JesterOrNot Sorry; should have updated this issue...! There's a PR https://github.com/rust-lang/rust/pull/65811 at the moment. Feel free to leave suggestions on it if you like. :)
