### ISSUE TITLE
aarch64 windows backend forces panic=abort

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#65313]
The [aarch64-pc-windows-msvc](https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/aarch64_pc_windows_msvc.rs#L8) and [aarch64-uwp-windows-msvc](https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/aarch64_pc_windows_msvc.rs#L8) targets force panic=abort. @alexcrichton said [this](https://github.com/rust-lang/rust/pull/63155#discussion_r312162970):
```
The AArch64 Windows backend didn't implement SEH unwinding when the aarch64-pc-windows-msvc target was first added, so I suspect this is the same as that. I haven't checked the LLVM backend recently to see if this works.
```
This looks related to https://github.com/rust-lang/rust/issues/54291, which points at these now-merged LLVM changes:
* https://reviews.llvm.org/D50166
* https://reviews.llvm.org/D50288
* https://reviews.llvm.org/D51524

It's possible that we do not need to force panic=abort anymore for arm64 Windows as a result. What's the best way to determine if this is still required?

**Comment by alexcrichton** [comment]
Theoretically the way to fix this issue is:

* First [remove these lines](https://github.com/rust-lang/rust/blob/e369d87b015a84653343032833d65d0545fd3f26/src/librustc_target/spec/aarch64_pc_windows_msvc.rs#L8-L9)
* Next, run the build
* Finally, run the tests

If that all passes, then the change can land! The tests may be able to be skipped, and some tests may fail, so it may be possible to switch the defaults and we can fixup bugs later. I don't personally have hardware to test these changes on myself, though.

**Comment by jdm** [comment]
I occasionally have access to a Windows arm64 laptop, so I'll try and get a rustc build going on it at some point.
