### ISSUE TITLE
could not evaluate static initializer

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#65526]
https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/reg/vptr-0.2.0/log.txt
looks like this is inside a proc macro so would be good to figure out what the raw expression is

cc https://github.com/rust-lang/rust/issues/64962

**Comment by Centril** [comment]
cc @oli-obk @RalfJung  -- my guess is the crate is doing something UB in the static.

**Comment by ecstatic-morse** [comment]
This proc macro creates [reference to address `0` here](https://github.com/ogoffart/vptr/blob/ca32aa416b97311afc569564eb08b2e18f1a4e15/macros/macros.rs#L125). They should switch to `memoffset`, whose behavior is not *as* undefined :smile:.

**Comment by Centril** [comment]
cc @ogoffart 

Closing as wontfix because of UB.

**Comment by RalfJung** [comment]
Well, there's no way to do `offsetof` in CTFE right now. Previously, there were some approaches that seemed to work but actually were UB, like this one. But now our const-time UB checker got a bit better, hence the crater regression.

https://github.com/rust-lang/rust/pull/63810 is the key ingredient to enable a less insane version of `offsetof` in CTFE. (Basically, the CTFE variant is then just as unsound as `memoffset`. In other words, it is UB but works in practice because right now we do not exploit that UB in the compiler.)

**Comment by RalfJung** [comment]
I opened an issue in the crate to give the author a heads-up: https://github.com/ogoffart/vptr/issues/1.

@Mark-Simulacrum were there other regressions that look similar? `offsetof` is one of these notorious operations that Rust doesn't support but people want it, and they want it so badly that instead of making the language support `offsetof` they write programs with UB that happen to work at the time of implementation... so I'd not be surprised to see that kind of snippet come up a few times.

**Comment by Mark-Simulacrum** [comment]
I didn't see any other cases of this.

**Comment by ecstatic-morse** [comment]
Ugh, I missed the `static` declaration.
