### ISSUE TITLE
Cannot index and immediately call FnMut

### ISSUE THREAD

**Issue by timotree3** [rust-lang/rust#65682]
Running this code on the latest stable (1.38.0) as well as nightly (2019-10-20)
```rust
fn foo<F, I>(i: &mut I)
where
    F: FnMut(),
    I: std::ops::IndexMut<(), Output = F>,
{
    i[()](); // fails
    (&mut i[()])(); // works
}
```
gives the error
```
error[E0596]: cannot borrow data in an index of `I` as mutable
 --> src/lib.rs:6:5
  |
6 |     i[()](); // fails
  |     ^^^^^ cannot borrow as mutable
  |
  = help: trait `IndexMut` is required to modify indexed content, but it is not implemented for `I`
```
which is clearly wrong.

Notably, the same error does not occur if we switch everything to `Fn`:
```rust
fn foo<F, I>(i: &I)
where
    F: Fn(),
    I: std::ops::Index<(), Output = F>,
{
    i[()](); // works
}
```

**Comment by timotree3** [comment]
I can still reproduce this on latest nightly (`nightly-2019-12-21`)

**Comment by timotree3** [comment]
I can still reproduce this on the playground with nightly-2020-05-08 and stable 1.43.1

**Comment by estebank** [comment]
There seems to be something unaccounted for in mir's `check_access_permissions`.

CC @oli-obk in case they have context around this already

**Comment by estebank** [comment]
Looking further I think that the problem is that the `place` for `i[()]` is a `Deref` instead of `DerefMut` before we get to the MIR borrow checker, which is why it rejects it as not mutable. This makes me think that somewhere in `typeck` we _don't_ flow the mutable obligation from the `i[()]()` call back to the `i[()]`. This also explains why `(&mut i[()])()` works, because the mutable obligation is explicitly stated and flowed forward, making the call work incidentally.

**Comment by estebank** [comment]
I'm not sure what the correct thing will be, but I suspect that changing the following so that it modifies the adjustments for `callee_expr` to be mutable `Deref`/`Borrow` will do the trick, but I am not overly familiar with this part of the codebase:

https://github.com/rust-lang/rust/blob/1ccb0b4a020cac07a9772d0da722869096a46cef/src/librustc_typeck/check/callee.rs#L149-L164

**Comment by compiler-errors** [comment]
This code works now.
