### ISSUE TITLE
STATUS_HEAP_CORRUPTION crashes are hidden by the test harness

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#65692]
Consider the following code:
```rust
fn main() {
    use std::alloc::{alloc, dealloc, Layout};
    unsafe {
        let ptr = alloc(Layout::from_size_align(4096, 4096).unwrap());
        dealloc(ptr, Layout::from_size_align(4096, 1).unwrap());
    }
}
```

Yes, it breaks the invariants for dealloc, and yes, it crashes on Windows, with:
```
error: process didn't exit successfully: `target/debug/foo.exe` (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)
```

The problem is that when that happens in a test, the test just fails in a completely non-useful manner. (just switch to a lib crate, rename the function and add `#[test]`).

The test fails with:
```
running 1 test
error: test failed, to rerun pass '--lib'
```
And nothing else.
When the crate happens to have other tests, some other tests, but not all, will show `test foo... ok`, then the same error.

**Comment by ehuss** [comment]
I don't think this is something libtest can do anything about, since once the process has crashed, it is no longer running.  I think this is a Cargo issue where it is not displaying the exit message properly.

I have opened rust-lang/cargo#7535 with a fix.

You still won't see which individual test caused the error, but presumably you can attach a debugger or something in this scenario (or whittle it down manually).  There is experimental support in libtest to run each test in a separate process (for panic=abort tests), which could maybe be extended in the future to be something you could opt in to in order to narrow down which test failed.
