### ISSUE TITLE
Why does rust use stupid uft8 strings?

### ISSUE THREAD

**Issue by lovelife2020** [rust-lang/rust#65725]
I found rust two days ago and I really loved the language. 
But  but but  but but   ,why does rust use stupid uft8 strings?  Why not use unicode strings?
Even the simplest substring  and replace method does not exist.
Still playing a hammer?
Waste my feelings！

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

**Comment by Ixrec** [comment]
Also, UTF-8 *is* Unicode, and [`String::replace` exists](https://doc.rust-lang.org/std/string/struct.String.html#method.replace). Substring would typically be done with iterator methods like `.chars().skip(2).take(5)` that correctly deal with UTF-8's variable-sized code points.

If you're asking about constant-time substring and replace methods whose arguments are byte indices, those aren't provided simply because they're impossible to implement on a variable-length encoding like UTF-8. That's only possible with fixed-length encodings like UTF-32, which are a colossally inefficient use of space for most real world text and text-processing applications, which is why UTF-8 is the default.
