### ISSUE TITLE
Under what conditions can you implement Copy for a union?

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#65748]
From https://github.com/rust-lang/rust/issues/32836#issue-147034658:

> Under what conditions can you implement `Copy` for a `union`? For example, what if some variants are of non-`Copy` type? All variants?

@RalfJung notes in https://github.com/rust-lang/rust/issues/55149#issuecomment-430667174 that:

> The RFC doesn't say anything about that, but I think indeed the answer should be "all variants".

cc https://github.com/rust-lang/rust/issues/55149

**Comment by petrochenkov** [comment]
>the answer should be "all variants".

+1
If `Copy` is implemented for a union with non-copy fields, it undermines all the remaining move/initialization checking for unions.

**Comment by Centril** [comment]
The current behavior does fortunately seems to enforce the "all variants" behavior:
```rust
#![feature(untagged_unions)]

struct NoCopy;

#[derive(Clone, Copy)]
struct IsCopy;

#[derive(Clone, Copy)]
union U {
    a: NoCopy,
    b: IsCopy,
}
```
results in an error:
```rust
error[E0204]: the trait `Copy` may not be implemented for this type
  --> src/lib.rs:8:17
   |
8  | #[derive(Clone, Copy)]
   |                 ^^^^
9  | union U {
10 |     a: NoCopy,
   |     --------- this field does not implement `Copy`
```

I agree that it is a sensible conservative default.

**Comment by varkor** [comment]
There don't seem to be any sensible alternatives to the current behaviour. What else could the condition possibly be?

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

We discussed this in today's @rust-lang/lang meeting and we all felt that this behavior seemed like the obvious and correct one. It is also the one that is presently implemented. Moreover, it's a *conservative* choice -- if we wanted to permit `Copy` impls under more conditions, we could do so at some later point. Therefore, I move that we "merge". (Since the behavior is already implemented, no changes are needed -- though one good question is whether we have suitable tests.)

**Comment by petrochenkov** [comment]
The current behavior is [not accidental](https://github.com/rust-lang/rust/pull/36016#issuecomment-242948929) and it has a test (`union-copy.rs`).

**Comment by Centril** [comment]
Moving all remaining work to the reference in https://github.com/rust-lang/reference/issues/709 now that FCP is complete.
