### ISSUE TITLE
Remove msys2 hacks and vendor the whole thing

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#65767]
On 2019-10-24 we had a CI outage due to the ca-certificates msys2 package being broken. The hack @mati865 implemented (:heart:) is to download an older, known good package beforehand and install it after msys2 updated its packages.

Once https://github.com/msys2/MINGW-packages/issues/5887 is fixed we should revert the hack, but I think at this point it's worth investing in vendoring msys2 as a whole.

**Comment by crlf0710** [comment]
msys2 is using `pacman` and other tools from archlinux distro. Arch Linux provides per-day official repositories snapshots. User can "pin" to a specific date. I think it is possible to reuse that  mechanism to vendoring msys2 as a whole, by providing a mirror of a specific date's version.

See here for more descriptions [about it](https://wiki.archlinux.org/index.php/Arch_Linux_Archive).

**Comment by mati865** [comment]
@crlf0710 that would be nice but msys doesn't remove old packages from their repo so the mirror would be enormous.
Search for `mingw-w64-x86_64-qt5` in http://repo.msys2.org/mingw/x86_64, only those packages take dozens of GiB.

Also extracting it from archive would make CI a bit faster because you won't be modifying thousands of small files over and over. On Linux that is not a problem but `pacman` working through cygwin emulation a bit struggles on this part.

**Comment by pietroalbini** [comment]
No update on this, planning to discuss what to vendor at the all hands.

**Comment by aidanhs** [comment]
At the last infra meeting we decided a good step is to move towards using the pre-installed msys2 packages. In theory this is as simple as removing the msys2 installation step and pointing things at the right location on the images in CI.
