### ISSUE TITLE
Bound UnixDatagram & UnixListener leak socket file on Drop

### ISSUE THREAD

**Issue by jean-airoldie** [rust-lang/rust#65895]
Currently binding a path with `UnixDatagram` or `UnixListener` will leak the socket file on drop.

Its quite a pain in terms of usability because it makes binding a non-idempotent operation. For instance, you need to call `libc::unlink` on the path you are about to bind just in case it was previously leaked. Moreover, from what I understand, since `AF_UNIX` sockets don't implement `SO_REUSEADDR`, there not viable use for this leaked file.

I suggest that `libc::unlink` is called when one of these sockets are dropped (if the socket was bound to a path) just after `libc::close` so that the socket file is removed when there are no open sockets referencing it left.

For reference: https://github.com/tokio-rs/mio/pull/1111

## Meta
```
rustc 1.38.0 (625451e37 2019-09-23)
binary: rustc
commit-hash: 625451e376bb2e5283fc4741caa0a3e8a2ca4d54
commit-date: 2019-09-23
host: x86_64-unknown-linux-gnu
release: 1.38.0
LLVM version: 9.0
```

**Comment by sfackler** [comment]
The standard library should not make this choice for users. If the system does not automatically delete the file when a Unix socket is closed, we aren't going to do that.

**Comment by jean-airoldie** [comment]
I'm not sure I understand the reasoning. Whats the difference between this and closing the file descriptor of the socket on drop in the first place? This is effectively "making a decision" for the user, albeit its a sensible decision.

I'm not sure that leaking a socket file just in case somebody has a weird use for it is the most user friendly approach.

**Comment by sfackler** [comment]
> I'm not sure that leaking a socket file just in case somebody has a weird use for it is the most user friendly approach.

That sounds like a concern to bring up with the POSIX standards committee. This behavior was presumably specified for a reason!

We generally want to adhere to the underlying system primitives as closely as possible so that things behave as expected to people who know how the underlying system primitives behave. There are a very small number of exceptions (e.g. we set CLOEXEC on file descriptors). We do not, however, automatically set SO_REUSEADDR, or SO_REUSEPORT, or whatever on TCP sockets, and we do not automaticallhy delete Unix socket files.

**Comment by jean-airoldie** [comment]
Fair enough.
