### ISSUE TITLE
Tracking issue for fallback of diverging expressions to the `never_type` (`!`)

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#65992]
This issue is tracking the proposed change in fallback for "abrupt" expressions (part of the `!` type RFC, tracking issue https://github.com/rust-lang/rust/issues/35121). 

## Substeps

* [ ] create a fallback lint (https://github.com/rust-lang/rust/issues/66173)
* [ ] ...

**Comment by bill-myers** [comment]
It seems to me this change is wrong as-is, since it causes a bare call to mem::zeroed() with unused result to panic, which is obviously absurd.

Based on https://hackmd.io/3VA7vpBFQZCZFjhVSh4O-A it seems to me that the problem is that the type of panic! and unimplemented! is an unbound inference variable, where in fact it should just be the "!" type.

With such a change, those expressions will have the "!" type even when fallback is to (), and that's the only argument in favor listed.

If fallback to "!" is still desired, then it DEFINITELY must not happen in places where it would cause code to panic that would not panic if the fallback was to "()" like simply calling mem::zeroed(): the thing that comes to mind is to add a "NotNever" or "Inhabited" trait bound to everything that uses unsafe code to generate arbitrary types like mem::zeroed, mem::uninitialized and mem::transmute, but not quite sure about this.
