### ISSUE TITLE
Were all the run-make tests meant to to be moved to run-make-fulldeps?

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#66085]
#48883 moved the `run-make` tests to `run-make-fulldeps`

But a lot of the `run-make` tests can be run against the stage1 compiler.

From the description on PR #48883, I am not clear on whether the `run-make` move to `run-make-fulldeps` was meant to be permanent, or just a temporary way to test a change that accidentally got committed.

**Comment by Centril** [comment]
cc @alexcrichton @Mark-Simulacrum

**Comment by alexcrichton** [comment]
I didn't want that PR to bounce and I didn't want to start testing more than we were already testing, so yes it was intentional that everything moved. It's true that some items could be moved back, I just didn't want to do the work to do that personally.

**Comment by pnkfelix** [comment]
That's fine; I just wanted to make sure there wasn't some reason I wasn't seeing for trying to move tests back to `run-make` if possible.

**Comment by ehuss** [comment]
Also beware that run-make-fulldeps is now treated differently in CI for various reasons. For example, the macOS tests are split into separate runners because they take too long to run and run-make-fulldeps is one of the suites that is split up.  Also, the "debug" runner *only* runs the run-make-fulldeps tests.
