### ISSUE TITLE
Tracking issue for `#![register_attr]`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#66080]
This is a direct replacement for now removed `#![feature(custom_attribute)]` (https://github.com/rust-lang/rust/issues/29642), except it doesn't rely on implicit fallback from unresolved attributes to custom attributes (which was always hacky and is the primary reason for the removal of `custom_attribute`) and requires registering the attribute explicitly.

```rust
#![register_attr(my_attr)]

#[my_attr] // OK
fn main() {}
```

It's not yet clear whether this should go through stabilization or not.
It's quite possible that all the uses should migrate to `#![register_tool]` (https://github.com/rust-lang/rust/issues/66079) instead.

**Comment by joshtriplett** [comment]
> It's quite possible that all the uses should migrate to #![register_tool] (https://github.com/rust-lang/rust/issues/66079) instead.

We discussed this in today's @rust-lang/lang meeting, and we agreed: anything new should be scoped, and anything existing we need to support for backwards compatibility shouldn't require calling `register_tool` first, so we can just keep the hardcoding of the handful of exceptions in the compiler.

@rfcbot close

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by scottmcm** [comment]
Hello folks!  This can't be closed yet, despite the FCP, because the feature still exists in the compiler under the `register_attr` feature gate.

If anyone would like to make a PR to remove the associated code (and tests) under the gate, it'd be appreciated!  `rg` should help find anything relevant
![image](https://user-images.githubusercontent.com/18526288/183982492-1c3b78b2-efdc-4868-a9e5-c9323395511b.png)
