### ISSUE TITLE
Types equal to/wrapping () result in "not FFI-safe" warning

### ISSUE THREAD

**Issue by Rantanen** [rust-lang/rust#66202]
```rust
// OK
pub extern "system" fn raw() -> () {}

// warning: `extern` fn uses type `()`, which is not FFI-safe
pub extern "system" fn assoc() -> <() as ToOwned>::Owned {}
//                                ^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe

#[repr(transparent)]
pub struct W<T>(T);

// warning: `extern` fn uses type `()`, which is not FFI-safe
pub extern "system" fn wrap() -> W<()> { W(()) }
//                              ^^^^^^ not FFI-safe
// note: composed only of `PhantomData`
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=62da3bf343e1358e16a6692a72ca7f33

All of these cases work in Beta. At least the associated type warning is recent regression in Nightly. I suspect https://github.com/rust-lang/rust/pull/65134

CC @davidtwco

**Comment by davidtwco** [comment]
@Rantanen This is related to #65134 in so far as that PR made the improper-ctypes lint apply to extern functions that are outside `extern {}` blocks. As you can see [from this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1e26a7d9f14ff6ae28afa912b0e27a49), when on stable (which doesn't have #65134 yet) and inside an `extern {}` block, the lint fires on those functions - so this is a pre-existing issue with the lint.

@rkruppe @eddyb do you know if this is a bug or is expected?

**Comment by rkruppe** [comment]
My knee-jerk reaction is that both are bugs that can and should be fixed.

- `<() as ToOwned>::Owned` should have been normalized to `()`, why wasn't it?
- The error message for `W<()>` is clearly bogus, and if plain `()` doesn't warn then clearly a transparent newtype around it shouldn't either. But note that `#[repr(C)] struct Foo(());` also gets flagged for containing `()` because "tuple layout is unspecified", so unless we want to open that whole can of worms too, the fix can't be just making `()` FFI-safe.

**Comment by Rantanen** [comment]
> This is related to #65134 in so far as that PR made the improper-ctypes lint apply to extern functions that are outside extern {} blocks.

Good to know! I was worried this was a change in functionality that wasn't expected.

I've since worked around this issue by normalizing the `<() as Trait>::Foo` case into `()` manually in my proc macro code. There are still some corner cases where this might be an issue for me, but I'm not sure if those will ever occur in practice.

**Comment by rodrimati1992** [comment]
How can `()` not be ffi-safe,given that it's a zero sized type with an alignment of 1?

**Comment by rkruppe** [comment]
Passing ZSTs by value is on thin ice since zero-sized types don't exist in standard C and ABIs aren't always consistent about how they handle types that use GNU extensions to be zero-sized. The lint also fires on `repr(C)` structs without fields or with only PhantomData fields, accepting `#[repr(C)] struct Foo(());` would deviate from that. While I don't want to say it's the wrong call, we should be consistent and that turns it into a larger question that's better handled independent from the bug originally reported here.

I guess this also ties into the "linting likely mistakes in FFI code" versus "linting use of types with unspecified layout" that has come up in https://github.com/rust-lang/rust/issues/66220 at the same time.

**Comment by rodrimati1992** [comment]
That won't be a problem for me so long as Rust itself stays consistent in how it passes zero-sized types through `extern "C"` functions across compiler versions.

**Comment by rkruppe** [comment]
That isn't really the case, though. For example, https://github.com/rust-lang/rust/pull/64259 changes how ZSTs are passed in the C ABI on (some target triples of) PowerPC. That is arguably a bugfix, but it's happening *because* ZSTs in C are such a non-standard mess.

**Comment by eddyb** [comment]
I thought we fixed the normalization problem for this years ago, ugh.
It's very weird that the message prints the normalized form, since there's nothing in the printing logic that would do that normalization for you.

**Comment by rkruppe** [comment]
@eddyb FWIW the title change is not fully accurate, only one of the two warnings in the OP involve associated types, the other is about transparent newtypes. Arguably these are two separate issues but at present both are discussed here so both should be covered by the title.

**Comment by eddyb** [comment]
I had to check this but apparently we always treat *returning* a ZST like `void` in C:
https://github.com/rust-lang/rust/blob/76ade3e8ac42cd7a7b7c3c5ef54818ab68e3ebdc/src/librustc/ty/layout.rs#L2711-L2719

(even if on some architectures *passing in* a ZST to C code can have strange requirements)

I wonder if this logic is wrong, compared to returning `struct {}` in GCC.

If it's not, we should allow any ZSTs, or at least transparent ones (note that the code snippet above doesn't look at anything other than the size being `0`, not `repr(transparent)` etc.).
