### ISSUE TITLE
VxWorks needs a newer version of cc-rs

### ISSUE THREAD

**Issue by BaoshanPang** [rust-lang/rust#66232]
Do we have plan to get rid of this restriction recently? A newer version of cc-rs is needed for VxWorks 

https://github.com/rust-lang/rust/blob/9e346646e93cc243567e27bb0f4e8716d56ad1f1/src/librustc/Cargo.toml#L15

**Comment by ehuss** [comment]
`cc` can't currently be updated due to a build problem with riscv.  More info at https://github.com/rust-lang/rust/pull/65445#issuecomment-542710813.  I think the issue is that rustbuild uses cc to discover cc toolchains, and `cc-rs` gained riscv support, and so now it thinks it should use a gcc toolchain that doesn't exist.  The detection is in https://github.com/rust-lang/rust/blob/master/src/bootstrap/cc_detect.rs and Alex mentioned just setting a `CC_*` env var in the riscv container might be enough.  It's been on my todo list for a while, but I haven't had a chance to look at it.  I can maybe try to look at it this weekend.

**Comment by BaoshanPang** [comment]
@ehuss 
Thanks for working on this issue. Enjoy your weekend, it is not that urgent.
