### ISSUE TITLE
Path::starts_with and ends_with should be case-insensitive on Windows

### ISSUE THREAD

**Issue by zuobaoquan** [rust-lang/rust#66260]
```rust
#[test]
fn test_path_starts_with() {
    let path = PathBuf::from(r"C:\A\b");
    assert!(path.starts_with(r"C:\a"));
}

#[test]
fn test_path_ends_with() {
    let path = PathBuf::from(r"C:\a\b");
    assert!(path.ends_with("B"));
}

```

**Comment by nagisa** [comment]
Case sensitivity is a property of the filesystem, not operating system.

As thus, this issue is not actionable. Closing. If you feel differently please complain and I’ll reopen.

**Comment by Arnavion** [comment]
It's fine if the functions want to be case-sensitive, but their docs need to be changed to point this out explicitly and noticeably. Every Windows user is going to assume that the functions are case-insensitive just like they are in other languages on the platform. (I imagine OSX users will have the same expectation?)

It's made slightly worse because `PrefixComponent` is handled in a special way that makes `Path::new("C:\\Windows").starts_with(Path::new("c:"))` evaluate to `true` despite the mismatched case. So someone using that as a quick test of their assumption would end up with the wrong idea.

@nagisa Would you mind reopening for this reason?

**Comment by retep998** [comment]
I think it would also be good to have a crate like `same-file` provide a `starts_with` that *does* hit the filesystem. Such an API would also be able to detect when the same folder is specified but using alternate prefixes or mount points or through symbolic links.

**Comment by ChrisDenton** [comment]
The driver letter is located in the Object Manager and lookup is always case-insensitive. Folders are located on the filesystem and may or may not be case sensitive.

I do think platform specific behaviour should be documented if it can be a source of confusion.

**Comment by bigdogs** [comment]
Path::starts_with is case sensitive and not aware of operation system,  then why this api can be useful in practice if the target platforms contain windows
