### ISSUE TITLE
Rename `rustc_data_structures::Sync` to something else to avoid some problem

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#66609]
See https://doc.rust-lang.org/nightly/nightly-rustc/rustc_data_structures/sync/trait.Sync.html

Context: https://github.com/rust-lang/rust/pull/60900#discussion_r345025636

cc @alexreg @nikomatsakis

**Comment by Mark-Simulacrum** [comment]
It would be super helpful to document the reasons for this here rather than just a link -- I wasn't able to quickly parse out the reasons for this and without knowing them it's hard to know whether a rename makes sense :)

(In particular, we'd presumably also want to do the same for `Send`?)

**Comment by Centril** [comment]
So the problem to solve was:

> The second is because otherwise encounter ambiguity errors during bootstrap, owing to the rustc_datastructures::sync::Send trait (which is not the same as the standard Send trait).

Maybe @alexreg & @nikomatsakis can elaborate re. that?

> (In particular, we'd presumably also want to do the same for `Send`?)

Seems right, yeah.

**Comment by Mark-Simulacrum** [comment]
I am going to close this as if it solves a concrete problem and is useful it can be posted as a PR, and it seems like we should *not* do this unless that materializes; I think any breakage to the existing feature seems like it'd presumably be a breaking change too?

**Comment by Centril** [comment]
@Mark-Simulacrum What breakage? This is a compiler-internal trait...

**Comment by Mark-Simulacrum** [comment]
I don't believe that compiler changes that lead us to have to rename traits (internally or otherwise) are likely to not cause breakage in the wild as well. I also don't like having issues that are predicated on "this PR needs this" -- i.e., we haven't actually concluded for sure that something needs this. It seems also clear to me that this issue is not actively helping us, i.e., no one is going to implement it just because. If it becomes clear that we need to rename the traits, then it seems plausible that we could "just" do so...
