### ISSUE TITLE
Atomic tests in libcore/tests don't test atomicity

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#66692]
https://github.com/rust-lang/rust/blob/e41ced3f8d8e2f3f377ef931458e612d5f3d1f3f/src/libcore/tests/atomic.rs

They are all single threaded.

**Comment by Mark-Simulacrum** [comment]
I feel like testing our atomics is both likely to be pretty hard (i.e., you can't actually test for sure, just heuristics AFAIK) and also not really worthwhile -- we're pretty unlikely to actually encounter bugs in the multithreaded case but not the singlethreaded case, I suspect, since we're lowering to pretty raw LLVM primitives.

With that in mind, I would propose that we close this issue as not actually desirable.
