### ISSUE TITLE
`const fn`: reported test for a simple `match` with a wildcard-only arm

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#66758]
This works; let's consider adding a test for it since it's a bit of a special case. Reported to be working in https://github.com/rust-lang/rust/issues/49146#issuecomment-558333127 by @jyn514.

```rust
// check-pass

#![feature(const_if_match)]

enum E {
    A,
    B,
    C
}

const fn f(e: E) {
    match e {
        _ => {}
    }
}
```

**Comment by jyn514** [comment]
@ecstatic-morse do you mind if I add this? My laptop is no longer broken ^^ so I can actually get some work done without disappearing for a week at a time.

I put this in a file called `src/test/ui/consts/control-flow/empty-match.rs` and ran `./x.py test --stage 1`, is that about the right approach?

**Comment by Centril** [comment]
@jyn514 It is, but I'd recommend using `--pass check` to make it go faster. Also use `--test-args empty-match` to just test that file. Also, I'd rename the test to not suggest `match x {}`... something like `single-arm-match-wild.rs`.

**Comment by jyn514** [comment]
I ran `./x.py test src/test/ui/consts --stage 1` about an hour ago and that worked fine (although it took a while ^^). However, since then I updated nightly and I'm now getting compile errors when building stage 1:

```
cargo:warning=In file included from ../rustllvm/PassWrapper.cpp:6:0:
cargo:warning=../rustllvm/rustllvm.h:1:10: fatal error: llvm-c/BitReader.h: No such file or directory
cargo:warning= #include "llvm-c/BitReader.h"
cargo:warning=          ^~~~~~~~~~~~~~~~~~~~
```

What am I doing wrong?

Full error: https://pastebin.com/pbnpgmK9

(cross posted from https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp)
