### ISSUE TITLE
Better interface for static assert

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#6676]
In #6670 I add a basic form of static assertions (as suggested by graydon in #6568), but it's not nice to use. The biggest problem with it is you need a static variable with a name, that goes through trans and ends up in the object file.

@kud1ing suggested `static_assert!()`, which I think is a nice API but would need some invasive changed to the compiler (I think, uncertain).

**Comment by steveklabnik** [comment]
triage: nothing to add. We don't currently use `static_assert` anywhere in the codebase, which leads me to wonder if @thestinger isn't right here.

**Comment by nodakai** [comment]
An implementation in standard Rust based on the array size trick:

```rust
macro_rules! static_assert {
    (type $t:ty; ) => (
        type __StaticAssert = $t;
    );

    (type $t:ty; $e:expr $(, $ee:expr)*) => (
        static_assert!(type ($t, [i8; 0 - ((false == ($e)) as usize)]); $($ee),*);
    );

    ($e:expr $(, $ee:expr)*) => (
        static_assert!(type [i8; 0 - ((false == ($e)) as usize)]; $($ee),*);
    );
}

// static_assert!(1 > 0);
static_assert!(1 > 0, 2 > 1, 3 > 2);

fn main() {
//    static_assert!(1 > 0);
    static_assert!(1 > 0);
}
```
- https://play.rust-lang.org/?gist=cb2d54bc13da8cddcf27&version=stable

In short, an invocation `static_assert!(1 > 0, 2 > 1, 3 > 2, 3 > 1);` expands to 

```rust
type __StaticAssert =
    (((
       [i8; 0 - ((false == (1 > 0)) as usize)],
       [i8; 0 - ((false == (2 > 1)) as usize)]),
      [i8; 0 - ((false == (3 > 2)) as usize)]),
     [i8; 0 - ((false == (3 > 1)) as usize)]);
```

It is variadic because there will be a name collision between two invocations... Yes the usability is horrible.

**Comment by lilianmoraru** [comment]
I wish Rust would support more static features(I use them extensively in C++ in order to enforce correct API usage)...
I need to assert the simplest case: making sure the user doesn't pass an empty array/slice - and I cannot do it with the language...
It's awful that I have to "assert" at run-time for such a simple case...
