### ISSUE TITLE
Can't use different Error type in one async block with only ? operator

### ISSUE THREAD

**Issue by CGQAQ** [rust-lang/rust#66864]
@Nemo157
```rust
async fn a() -> Result<(), reqwest::Error> {Ok(())}
async fn b() -> Result<(), std::io::Error> {Ok(())}

fn c() {
    async {
        a().await?;
        b().await?;
        Ok(())
    };
}
```
```
error[E0282]: type annotations needed
 --> src/x.rs:6:9
  |
6 |         a().await?;
  |         ^^^^^^^^^^ cannot infer type

error: aborting due to previous error
```
```rust
async fn a() -> Result<(), reqwest::Error> {Ok(())}
async fn b() -> Result<(), std::io::Error> {Ok(())}

fn c() {
    async {
        a().await?;
        b().await?;
        Ok::<(), impl std::error::Error>(())
    };
}
```
```
error[E0562]: `impl Trait` not allowed outside of function and inherent method return types
 --> src/x.rs:8:18
  |
8 |         Ok::<(), impl std::error::Error>(())
  |                  ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

_Originally posted by @CGQAQ in https://github.com/rust-lang/rust/issues/62290#issuecomment-559711471_

### Currently my solution is unwrap() other Result, use ? only one type of Result, like this: 
```rust
async fn a() -> Result<(), reqwest::Error> {Ok(())}
async fn b() -> Result<(), std::io::Error> {Ok(())}
async fn c() -> Result<(), std::io::Error> {Ok(())}

fn d() {
    async {
        a().await.unwrap();
        b().await?;
        c().await?;
        Ok::<(), std::io::Error>(())
    };
}

**Comment by Nemo157** [comment]
@CGQAQ the former _is_ unconstrained, there's no way rustc can know what the error type should be, changing it to be used in a closure returning an async block passed to a function which constrains it [works fine](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6f18274ebfcf720b5ec9da45aff65f5d) (and the equivalent blocking code [also fails](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5a517860b9922f238d852f6ba98d3c20)). The latter already [works](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f6c962ab0c758c76327a2201b3c10734) after replacing `impl Error` with a concrete error type (as far as I'm aware `impl Trait` in that position is not supported and has not been RFCed). (I also switched both to use `serde_json::Error` instead of `reqwest::Error` as it provides the necessary conversion into `io::Error`).

**Comment by CGQAQ** [comment]
> a().await.unwrap();
        b().await?;
        c().await?;

This just makes error handling so inconsistent

**Comment by jonas-schievink** [comment]
Closing since this seems to be working as expected.

**Comment by CGQAQ** [comment]
> Closing since this seems to be working as expected.

What?

**Comment by jonas-schievink** [comment]
The comment above explains it: https://github.com/rust-lang/rust/issues/66864#issuecomment-559718929

There's no way to make the first example work, and the second example just misused `impl Trait` and can be made to work by simply not doing that.

**Comment by CGQAQ** [comment]
> The comment above explains it: [#66864 (comment)](https://github.com/rust-lang/rust/issues/66864#issuecomment-559718929)
> 
> There's no way to make the first example work, and the second example just misused `impl Trait` and can be made to work by simply not doing that.

I opened this issue is hoping first one will work **eventually**, is there any rfc could make it work?

**Comment by jonas-schievink** [comment]
Not as far as I know. If you know how to make it work, feel free to open one, but we generally don't track wishlist-type stuff in this repo.

**Comment by CGQAQ** [comment]
> Not as far as I know. If you know how to make it work, feel free to open one, but we generally don't track wishlist-type stuff in this repo.

Ok, thank you
