### ISSUE TITLE
Implement Trait for `dyn Trait` possibly breaking orphan rules

### ISSUE THREAD

**Issue by paulocsanz** [rust-lang/rust#66939]
I saw this discussion on [reddit](https://www.reddit.com/r/rust/comments/e3fzip/unsoundness_in_pint/f936fit/) and tried to break some stuff.

Is this a breakage of orphan rules? Using f32 keys in `BTreeMap`s by casting it to a `dyn Trait` that implements `Ord`, it's not UB but it breaks basic assurances that most code depends on. Since `dyn Traits` don't implicitly cast this will only happen if the user wants to, but it still allows you to bypass the orphan rules without a NewType. I don't know if it's bad nor if something can be done (since a breaking change may not be possible), but maybe someone can extend this to break some bigger assumptions.

```
fn main() {
    let mut btree = BTreeMap::new();
    btree.insert(&0.0f32 as &dyn MyOrd, true);
}
```

The full code is here, it doesn't do anything that works, it was just a quick experiment.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=289f9f181c238aabd731ea16befcc1e6

**Comment by jonas-schievink** [comment]
The orphan rules ensure that you cannot write an impl that could also be written by a dependency, since that would cause overlap and thus break your code. By defining your own trait, you get the right to define whatever impls on it that you want (as long as they don't overlap), so this looks working as expected.

There is currently one unsoundness related to trait objects and impls, and that is https://github.com/rust-lang/rust/issues/57893. It requires somewhat more elaborate setup.
