### ISSUE TITLE
Incorrect outer `#![derive(Debug)]` emits too many errors

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#67107]
The following incorrect code:

```rust
#![derive(Debug)]
struct Coordinate(i32, i32);

fn main() {
    println!("{:?}", Coordinate(4, 2));
}
```
[generates the following output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ef81d3cc909f2125bdf11680bd134f42):
```
error: `derive` may only be applied to structs, enums and unions
 --> src/main.rs:1:1
  |
1 | #![derive(Debug)]
  | ^^^^^^^^^^^^^^^^^ help: try an outer attribute: `#[derive(Debug)]`

error: cannot determine resolution for the derive macro `Debug`
 --> src/main.rs:1:11
  |
1 | #![derive(Debug)]
  |           ^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports

error[E0277]: `Coordinate` doesn't implement `std::fmt::Debug`
 --> src/main.rs:5:22
  |
5 |     println!("{:?}", Coordinate(4, 2));
  |                      ^^^^^^^^^^^^^^^^ `Coordinate` cannot be formatted using `{:?}`
  |
  = help: the trait `std::fmt::Debug` is not implemented for `Coordinate`
  = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
  = note: required by `std::fmt::Debug::fmt`
```

We should not emit the second value, given it could detect that the following element is an ADT it could internally treat it as `#[derive(Debug)]` so that no knock-down errors will happen.

**Comment by jDomantas** [comment]
A slightly bigger problem with this issue is that compiler emits an error for *every* custom attribute in the crate if the bad attribute ends up being on the root of the crate:

```rust
#![forbif(unused)]
// ^^^^^^ note the typo

use serde::Serialize;

#[derive(Serialize)]
pub struct Foo {
    #[serde(rename = "bar")]
    foo: i32,
    #[serde(rename = "quux")]
    baz: i32,
}
```

For this example compiler emits a total of 4 errors - first the one about the typo, and then one of each of `derive` and `serde` attributes. Only the first error is meaningful, with the other 3 seeming completely unrelated to the first one.
