### ISSUE TITLE
codegen-units=1 builds e.g. style and webrender faster

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#67213]
This is the cargo-timing output for gkrust when running `CARGOFLAGS="-Z timings" MOZ_RUST_TIER=1 ./mach build pre-export export rust` on mozilla-central with a patch to remove a dependency that cranelift has on packed-struct: https://glandium.org/files/gkrust-cargo-timing-no-packed-struct-one-codegen-real-clobber.html (the command allows to build rust without C/C++ happening in parallel to interfere)
mozilla-central is setup such that the release profile uses codegen-units=1 (in its top-level Cargo.toml).

Lifting that restriction makes the build time for gkrust surprisingly identical. And the reason is that while plenty of crates build faster, some others, like style (60 vs. 74) and webrender (18 vs. 26), don't. https://glandium.org/files/gkrust-cargo-timing-no-packed-struct-multi-codegens-real-clobber.html

**Comment by Mark-Simulacrum** [comment]
I'm not sure there's much to be done here. It's definitely true that in some cases codegen units are a loss, but tweaks to that algorithm are typically very difficult (see, e.g., recent analysis work: https://nnethercote.github.io/2023/08/01/how-to-speed-up-the-rust-compiler-data-analysis-update.html). I'm going to go ahead and close this since I don't think it's an actionable issue.
