### ISSUE TITLE
tracking issue for strip_prefix, strip_suffix for str 

### ISSUE THREAD

**Issue by Dylan-DPC** [rust-lang/rust#67302]
Cc @KodrAus 

Will fill the content later. Creating this so that #66735 can be merged and tracked.

**Comment by lzutao** [comment]
The code generated by `str::strip_prefix` is really complicated and inefficient.
Godbolt link: https://rust.godbolt.org/z/AnEoHH
Should we add `strip_prefix` / `strip_suffix` method directly to [Pattern](https://doc.rust-lang.org/nightly/std/str/pattern/trait.Pattern.html) or [Searcher](https://doc.rust-lang.org/nightly/std/str/pattern/trait.Searcher.html) trait?

**Comment by CryZe** [comment]
Oof that does indeed look pretty bad.

**Comment by benesch** [comment]
I whipped up that fix here: https://github.com/rust-lang/rust/pull/69784

Not sure if it's actually the ideal fix, but figured it would be a good point to launch the discussion from.

**Comment by benesch** [comment]
Ok, the code should be far more optimized now. What remains to be done? The main issue description has yet to be filled in. 😄

**Comment by lights0123** [comment]
On [some criterion benchmarks that I did](https://gitlab.com/lights0123/code-review-gorillas/-/blob/master/benches/str_trim.rs), I'm seeing that
```rust
fn strip_suffix(input: &str) -> &str {
	input.strip_suffix(char::is_whitespace).unwrap_or(input)
}
```
is much faster than `trim_end`, at least for newlines only. Is this only because I'm stripping off a very small amount of text, or is this function more optimized than `trim_end` (assuming that I didn't screw something up)? See "Standard strip suffix" versus "Standard trim end", with "unix" having the input of `"50\n"` and "win" being `"50\r\n"`:
![benches](https://lights0123.gitlab.io/code-review-gorillas/String%20trim/report/violin.svg)

**Comment by benesch** [comment]
Ah, yeah, looks the optimizations I made to strip_prefix/strip_suffix in #69784 are optimizations that don't exist for `trim_end`: https://github.com/rust-lang/rust/blob/20fc02f836f3035b86b56a7cedb97c5cd4ed9612/src/libcore/str/mod.rs#L4137-L4148

I wonder if `trim_end_matches` could be reimplemented as a loop over `strip_suffix_of`...

By the way, since I'm here, @Dylan-DPC (or anyone else on the Rust team), what remains to be done here?

**Comment by Dylan-DPC** [comment]
> By the way, since I'm here, @Dylan-DPC (or anyone else on the Rust team), what remains to be done for this issue?

If you want to change the implementation this is a good time. Else, the thing left is stabilisation with the libs team approving it (if needed) but i'd wait for some time to check if there are any other issues.

**Comment by benesch** [comment]
The implementation is now _faster_ than the existing similar stable functions `trim_start` and `trim_end`, so I think we're in a good spot implementation wise. Would you be able to add a note about the progress and when we expect to start the stabilization discussion in the issue description? (Or whatever normally goes in there?)

**Comment by Dylan-DPC** [comment]
@benesch you can submit a stabilisation PR by following the instructions here: https://forge.rust-lang.org/libs/maintaining-std.html?highlight=stabi#when-a-feature-is-being-stabilized.
