### ISSUE TITLE
use tbaa.struct to inform LLVM about struct/enum padding

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#6736]
This will allow LLVM to be lazier when copying the contents.

**Comment by Aatch** [comment]
Investigation in to how LLVM uses `tbaa.struct` suggests that it doesn't actually help with padding, it just informs LLVM of the types inside what would otherwise be an opaque pointer to help with alias analysis.

If/When we get actual TBAA, outputing `tbaa.struct` metadata may be useful, but my investigations have shown that LLVM doesn't use it for avoiding padding, etc.

Maybe somebody with more knowledge on LLVM could confirm? @dotdash?

**Comment by dotdash** [comment]
I came to the same conclusion when I looked at the LLVM code.
Am 20.01.2015 21:15 schrieb "James Miller" <notifications@github.com>:

**Comment by thestinger** [comment]
It used to use it but it was lost after various rewrites of the relevant passes. It could be taught to make use of it again, of course.

**Comment by nox** [comment]
Hey, psst. @rust-lang/wg-codegen

**Comment by nox** [comment]
Also cc @rust-lang/compiler.

**Comment by nox** [comment]
Given @cmr's blog post and @Aatch and @dotdash comments which seem to indicate that it doesn't actually help with padding, I suggest we just close this issue.

**Comment by oli-obk** [comment]
I agree, without a concrete case of something that we want to improve, this issue is not really actionable
