### ISSUE TITLE
fs::copy on Windows has a 260 character filename limit

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#67403]
It relies on the CopyFileExW Windows API, which has [path limits](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-copyfileexw#parameters) that yield surprising runtime behaviour. We could opt in to longer path limits (32k instead of 260) by prepending `\?` to the string, according to that same documentation.

**Comment by retep998** [comment]
`CopyFileExW` isn't special in this regard. *All* Rust filesystem code on Windows currently bumps into this limitation, and it's not just as simple as prepending `\\?\`.

**Comment by jdm** [comment]
One option might be to document this so it's a little bit less inexplicable to people who don't know the platform details.

**Comment by andrewbanchich** [comment]
@retep998 The [official Microsoft docs](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation) suggest doing what @jdm mentioned. The only exception I'm aware of is if it's a UNC then you need to use `\\?\UNC\`.

What kind of issues would this not address?

**Comment by ChrisDenton** [comment]
Win32 has four types of absolute path:

|Type|Win32 Example|
|--|--|
|DOS|`C:\Windows`|
|UNC|`\\server\share\`|
|Device|`\\.\PIPE\name`|
|Verbatim|`\\?\C:\Windows`<br>`\\?\UNC\server\share\`<br>`\\?\PIPE\name`|

It also has three types of relative path:

|Type|Win32 Example|
|---|---|
|Path Relative|`file.ext`<br>`.\file.ext`<br>`..\file.ext`|
|Drive Relative|`\file.ext`|
|Root Relative|`D:file.ext`|

Rust's file system APIs would at least need to be internally consistent with how they handle all these paths.

A smarter `std::path::Path` could resolve this issue by having a function to make the path both absolute and verbatim. Or another option is to have an internal API function that automatically gets called before almost* every use of a Windows filesystem API which would do the same thing when necessary.

###### \* I say "almost" because setting the Current Directory does not support verbatim paths. Only DOS and UNC paths are supported.
