### ISSUE TITLE
rustc-ap-rustc_session version 633.0.0 build failed

### ISSUE THREAD

**Issue by rchaser53** [rust-lang/rust#67477]
reproducible repository: https://github.com/rchaser53/failed-build-rustc-ap-rustc_session-633
build result in CI: https://travis-ci.org/rchaser53/failed-build-rustc-ap-rustc_session-633/builds/628023861?utm_medium=notification&utm_source=github_status

I checked rustc-ap-rustc session version 633.0.0 on my local PC. There is no rustc_private attribute in lib.rs of rustc-ap-rustc_session. I think it's the reason why the build failed.

I want to use this module for updating rustfmt. Thank you.

**Comment by rchaser53** [comment]
All error messages are like below.
```
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead?
    --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_session-633.0.0/config.rs:2845:25
     |
2845 |             if !matches.opt_present(opt.name) {
     |                         ^^^^^^^^^^^
     |
     = note: for more information, see https://github.com/rust-lang/rust/issues/27812
     = help: add `#![feature(rustc_private)]` to the crate attributes to enable
```

**Comment by Centril** [comment]
cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
I expect this to be fixed in the next publish. The auto publish script looks for `\n#![feature(` to inject the rustc_private feature; the first version of the crate had only one feature (so no such string was present) but as of 83fc600a28044f8384bbce437c3251620f869254 there are now two, so it should fix itself. Since this is "fixed" on master I'm going to close.
