### ISSUE TITLE
"pattern binding is named the same as one of the variants of the type `<type>`" warning is not generated when matching against a borrow

### ISSUE THREAD

**Issue by yshui** [rust-lang/rust#67776]
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6b951a2fc1cc70455730b35d42fcf483

This issue has been assigned to @LeSeulArtichaut via [this comment](https://github.com/rust-lang/rust/issues/67776#issuecomment-570070940).

**Comment by csmoe** [comment]
This lint was generated by `check_for_bindings_named_same_as_variants`:
https://github.com/rust-lang/rust/blob/9e6fb538f9254884ca9f958fdce413d6c3f2016c/src/librustc_mir/hair/pattern/check_match.rs#L287-L289
as we can see `ty::Ref` is just ignored, so the fix is pretty easy, just [peel off ](https://github.com/rust-lang/rust/blob/9e6fb538f9254884ca9f958fdce413d6c3f2016c/src/librustc/ty/util.rs#L990-L1000)all the refs in the `pat_ty`.
