### ISSUE TITLE
Resolving the diamond problem

### ISSUE THREAD

**Issue by hameerabbasi** [rust-lang/rust#67805]
Related to #31844.

As noted by Discord user `pie_flavor#7868`, we see an error about the diamond problem: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f7b45b0efa1007a421a93aa386c6afd4

The issue is that we can't pick if we want the implementation from `A` or `B` (or our own) if this happens by doing `default impl<T> C for T where T: A + B {}`.

**Comment by pie-flavor** [comment]
note: I had meant it without the `default`, as in that the `A+B` bounded impl would be the concrete one, but really it should be valid either way

**Comment by jonas-schievink** [comment]
This is working as specified. As a fix, the "lattice rule" has been proposed, where any two overlapping impls must be disambiguated by adding a third impl that applies to exactly the types in the overlap.

In this case, such an impl would be `default impl<T> C for T where T: A + B {}`.

This design has not been RFC approved though, and I'm unsure if that's because there's something fundamental wrong with it.

In any case, this is working as expected, so closing.
