### ISSUE TITLE
rustdoc: Emoji for deprecated items

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#67872]
Nightly only items have emoji:
![image](https://user-images.githubusercontent.com/15225902/71769421-ab3e4f80-2f53-11ea-8444-7e37de323ca2.png)

I think deprecated items should have emoji too. 
For example this item: https://doc.rust-lang.org/nightly/std/primitive.str.html#method.trim_right
@pickfire suggests using coffin emoji ⚰️ in https://github.com/rust-lang/rust/pull/67868#issue-359222211
I suggest using fire emoji: :fire:

**Comment by lzutao** [comment]
cc #67871

**Comment by DataTriny** [comment]
Hello,
I personally think that the coffin emoji convey better the idea that the item should not be used anymore (it's dead). Fire can have multiple significations in my opinion.

**Comment by kennytm** [comment]
For reference, MDN uses

* 🗑 (trash can) for Obsoleted and won't work
* ⚠️ (warning sign) for Non-standard
* 👎 (thumbs down) for Deprecated but still works
* ⚗️ (*actually, a beaker) for Experimental

(that said, I think it's fine to use no emoji)

**Comment by euclio** [comment]
I commented on the open PR already, but I'll add my sentiments here, too.

Other options to consider:

- 👎
- 🕸
- 🚨
- 🚧
- 🛑
- ⛔
- 🚫
- ❗
- ❌
- 🟡
- 🟨
- 🚩
- ⚠️

I'm personally partial to 🚩. I think it conveys the message of "hey, pay attention, this will go away at some point" without being too strong or prescriptive. I like 👎 too given the definition of "deprecate" and that MDN already uses it.

I also like 🚧 but it may have too much of a "under construction, stabilizing" connotation than we would like, though.

I dislike the coffin because it is difficult to tell what it is from a glance (also, it's too grim for my tastes).

**Comment by ExpHP** [comment]
🚩 and ⚠️ looks more like they mean "unsafe" to me.

I kinda like 🕸.

**Comment by pickfire** [comment]
I like :coffin: (conveys dead) and :-1: (conveys not recommended) symbol. I cannot understand why :fire: and :spider_web: means deprecated.

**Comment by lzutao** [comment]
It just come to my mind after your suggestion of :coffin: .I think :fire: means think
to be burnt to ashes.

**Comment by kennytm** [comment]
#37250 already used ⚠️ to mean "unsafe".

**Comment by pickfire** [comment]
@kennytm Yes, I noticed :warning: already being used. We also use that here.

**Comment by Ixrec** [comment]
I agree that 👎 conveys "not recommended", but I don't see that as a problem. "Deprecated" is often synonymous with "not recommended" (especially when compatibility forbids ever removing the item), and that's certainly the most important part of what "deprecated" means for the end user.

Without any other context, 🕸 looks to me more like a snowflake than a cobweb (at least the ways github/gmail render it in Chrome), which obviously doesn't quite work.

⚰️ does look like a coffin to me, but in a way I suspect is fragile. I could easily imagine a slightly different size or image choice making it look more like a cigar or a chocolate bar or something else that obviously doesn't work.

A lot of the other suggestions like 🗑 and ❌ and 🛑 feel closer to "deleted" or "disabled" than the "deprecated" we're after here.

I think ⚠️ is one of the better choices for unsafe because it expresses danger without implying that there's any construction or destruction or other temporary work in progress; just a general "be aware" without any other baggage. It also doesn't express disapproval (after all, there's nothing _wrong_ with using unsafe when appropriate). So even if it wasn't already being used for that, I'd keep it there.

In the end 👎 seems like the strongest candidate for "deprecated" in my extremely subjective opinion.

**Comment by GuillaumeGomez** [comment]
Ok, then I'll add the :-1: emoji for deprecated items!
