### ISSUE TITLE
difficulty adding a dependency

### ISSUE THREAD

**Issue by Eddie-254** [rust-lang/rust#67998]
I have added the below dependency but does not seem to work
[package]
name = "Rust_Code"
version = "0.1.0"
authors = ["Joy Safie"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"

**Comment by matklad** [comment]
@Eddie-254 asking this as a question at https://users.rust-lang.org/ might be more appropriate, as it doesn't seem to be a bug with the language per se. Alternatively, there's a [Discord](https://discordapp.com/channels/442252698964721669/448238009733742612) channel where one can get help.

It would also help to know what exactly does not work for you (ie, what kind of error do you see). 

So, I am closing this, as it seems to be more like a support question rather than a bug/feature request.
