### ISSUE TITLE
Tracking issue for iterator_fold_self

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/rust#68125]
Tracking issue for [`Iterator::fold_first`](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.fold_first), like `fold1` in Haskell.

# Steps

- [x] Initial implementation: #65222 
- [x] Stabilisation PR: #79805

# Open questions

- [x] Naming.
 - `fold_first`
 - `fold_with_first`
 - `fold1`
 - `reduce`
 - ...
- [x] ~~Should we reconsider `try_fold_first`?~~

**Comment by turion** [comment]
For me as a Haskeller who relatively new to Rust, `try_fold_first` sounds right, because it returns an `Option`.

**Comment by pcpenpal** [comment]
Following Scala's approach, what about `reduce`?

**Comment by Danue1** [comment]
Kotlin is doing the same naming.

https://kotlinlang.org/docs/reference/collection-aggregate.html#fold-and-reduce

**Comment by Riey** [comment]
I prefer `reduce` because it quite different from `fold`

`fold` compute acc with all elements then return acc type

but `reduce` compute all elements into one then return element type

**Comment by Kroisse** [comment]
`reduce` might be conflict with [ParallelIterator::reduce][1] in Rayon, which has the `identity` parameter act as fold's `init` parameter.

[1]: https://docs.rs/rayon/1.3.1/rayon/iter/trait.ParallelIterator.html#method.reduce

**Comment by WaffleLapkin** [comment]
Why only `Iterator::fold_first` was implemented and not `DoubleEndedIterator::rfold_first`? Is it appropriate to make a PR that adds the later method?

**Comment by rossmacarthur** [comment]
I think `reduce` is an appropriate name for this function. `try_fold_first` would also be better than `fold_first`.

**Comment by jagill** [comment]
This functionality is very useful for situations where there's no reasonable default value.  For example, I'm using it for a parser, and would be very interested in it being stabilized.

I don't have a strong opinion on the name.

**Comment by amrhassan** [comment]
I concur, this would be very useful regardless of the name.

**Comment by jagill** [comment]
I'd like to officially push for stabilization.  This feature is useful and available in many other languages, and the implementation is simple and non-controversial.  The only debate so far is the name.  I'll list the primary contenders for the name and the pros/cons I've read for each:

## `fold_first`
The current name.

### Pros:
1. It is the existing name that won't break anything.
2. It is similar to `fold`, so it is easy to remember, and the name gives a strong clue to what it does.

### Cons:
1. It is, AFAICT, unique to Rust.

## `reduce`

### Pros:
1. This would use `fold` and `reduce` the same way that Scala and Kotlin do, which may start an effective standardization.
2. The different names emphasize an important difference: while `fold` may have a different accumulator state, `reduce` returns the iterator `Item` type.

### Cons:
1. For new people (not from Kotlin/Scala), it may seem arbitrary which functionality is `fold` and which is `reduce`.
2. It is not as obvious if you are looking at either `fold` or `reduce` that the other function exists.

## `try_fold_first`

### Pros:
1. Emphasizes that it may return `None`, which is error-like.

### Cons:
1. The current functions `try_fold` and `try_for_each` use `try_` to indicate that the _supplied_ function may fail.  This function would use `try_` to indicate that the `fold` may "fail" because the iterator is empty, not because the supplied function is fallible.

I'm happy to add additional pros/cons if people feel I've missed something important.

As stated before, I don't have strong feelings about the name.  I weakly dislike `try_fold_first`, because it is using `try_` differently than other functions within the group.  In particular, the `None` case is not an error, but an expected result on an empty iterator.

**Comment by WaffleLapkin** [comment]
Personally, I'm against `try_fold_first`:
- `try_` commonly corresponds to `Result` or `T: Try`, seeing it with `Option` is weird and confusing
- It's not an error actually, it's just an absence of value
- Similar function don't have `try_` prefix, e.g.: [`find`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.find), [`position`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.position), [`max`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.max), etc
- too long :D

I'm also slightly in favour of `reduce`, partially because I've used Kotlin in the past, but also because it's nicer (?) and `1`/`first` postfix didn't help me understanding semantics of the function...

**Comment by rossmacarthur** [comment]
Something like `fold_with_first` is clearer as to the semantics of the function.

**Comment by kinnison** [comment]
I found myself wanting this last night.  Based on the context in which I was using it, any of `fold_first()` `reduce()` or `fold_with_first()` would be good.  I think `try_fold_first()` would have confused matters given it was in a function returning `Result<>`.  My personal preference lies with `fold_first()` since my brain was hunting for `fold1` already thanks to Haskell :D

**Comment by jagill** [comment]
Edited the summary post based on the comments above.  I've removed `try_fold_first`, since all who have expressed an opinion (since the post) have disliked it for the same reason, which suggests that reason is strong.  I've added `fold_with_first` as an option (heh), since it's more explicit than `fold_first` but has similar pros and cons.

To move things towards completion, I am now disprefering `reduce`, since `fold`/`fold_{with_,}first` are more explicit.  It is not apparent from the names alone which version `reduce` is vs `fold`, while `fold_{with_,}first` is clearly the version that uses the first element.  I weakly prefer `fold_with_first`, because it reads more nicely and is more obvious to someone just reading the name -- `fold_first` might be interpretable as just folding the first element.  At least, when I first saw the name `fold_first` I had to read the description to know what it did.

**Comment by jagill** [comment]
Another argument against `try_fold_first`: I was folding an iterator that needed both the properties of `try_fold` (gracefully handling a fallible `map`) and `fold_first` (using the first item as the initial state, returning `None` if empty).  This prospective `fold` function should have the name `try_X`, where `X` is the name of this stabilized feature.

**Comment by m-ou-se** [comment]
I personally prefer the name `reduce`, for the same reason as stated in https://github.com/rust-lang/rust/issues/68125#issuecomment-650571847: Although related, `fold` and this function are fundamentally different. `fold` folds all the elements into a variable that could be of any type (e.g. it could be collecting integers into to a String), which doesn't have to be a reduction. `reduce` reduces the iterator to a single element (of the same type).

I don't think discoverability is a problem, as the documentation for `fold` can simply link to `reduce` and back, and the signature makes the difference very clear.

And as already mentioned above, we already have `scan` and `fold` with the same name as in Scala and Kotlin, and those languages also call this function `reduce`.

**Comment by WaffleLapkin** [comment]
I agree that the `reduce` is the best name so far, but there was a number of opinions, how do we decide?

**Comment by m-ou-se** [comment]
@WaffleLapkin I've already nominated this issue for the next libs meeting to make a decision on this. But looking at the 15 :+1: and 0 :-1: (currently at least) on the `reduce` suggestion, we could also just directly kick off an FCP on a stabilization PR that changes the name to `reduce` and see if everyone agrees. :)

**Comment by imjasonmiller** [comment]
> I don't think discoverability is a problem

I have no experience with Kotlin or Scala, but coming from JavaScript, the name [`reduce`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce) is clear to me and I assume to many others as well. One of my [first questions](https://discord.com/channels/442252698964721669/448238009733742612/687016813875560522) in the Rust Discord was about this method's functionality and how I'd achieve the same in Rust.

I've just used `.fold_first()` today and it's fantastic. Thank you. :-)

**Comment by felixc** [comment]
Ditto for Python, where it's called [`functools.reduce`](https://docs.python.org/3.9/library/functools.html#functools.reduce). So, to add another point of anecdata, that's the name I went looking for in the docs :)

**Comment by jagill** [comment]
`reduce` is the clear frontrunner.  I support starting the FCP with `reduce` as the proposed name, and if there are strong objections they can be raised then (the C in FCP!).  It'd be great to get the PRs merged before the next release cut.

**Comment by felixc** [comment]
Would this also be the place to leave comments/questions on the API and usage?

I'm wondering if I'm missing something obvious (I'm a beginner!), but since the closure takes `Self::Item` (_not_ a reference!), but `.iter()` seems to produce _references_, does that mean every `fold_first` invocation currently needs to be preceded by `.cloned()` (and incur that cost) if the iterated type can't be copied?

For example, take this manually-implemented version that does the same thing as `fold_first`:

```rust
fn count_repeated_chars_in_list_of_groups(list_of_groups: &[HashSet<char>]) -> usize {
    let mut iter = list_of_groups.iter();
    let first = iter.next().unwrap().clone();
    iter.fold(first, |accumulator, next| {
        accumulator.intersection(&next).copied().collect()
    })
    .len()
}
```

I tried to translate it to `fold_first`:
```rust
fn count_repeated_chars_in_list_of_groups__fold_first(list_of_groups: &[HashSet<char>]) -> usize {
    list_of_groups
        .iter()
        .fold_first(|accumulator, next| accumulator.intersection(&next).copied().collect())
        .unwrap()
        .len()
}
```

...but this doesn't work, because `fold_first` needs `accumulator` and `next` to be `HashSet`s, not `&HashSet`, like `iter()` gives us:

```
error[E0277]: a value of type `&std::collections::HashSet<char>` cannot be built from an iterator over elements of type `char`
   --> src/bin/day6.rs:153:82
    |
153 |         .fold_first(|accumulator, next| accumulator.intersection(&next).copied().collect())
    |                                                                                  ^^^^^^^ value of type `&std::collections::HashSet<char>` cannot be built from `std::iter::Iterator<Item=char>`
    |
    = help: the trait `FromIterator<char>` is not implemented for `&std::collections::HashSet<char>`
```

So instead we have to insert a `cloned()` into the iterator, which seems expensive:

```rust
fn count_repeated_chars_in_list_of_groups__fold_first(list_of_groups: &[HashSet<char>]) -> usize {
    list_of_groups
        .iter()
        .cloned()
        .fold_first(|accumulator, next| accumulator.intersection(&next).copied().collect())
        .unwrap()
        .len()
}
```

I'm assuming I'm missing something (since, I'll reiterate, I'm very new to Rust!), but this would seem to somewhat limit the usefulness of `fold_first`?

**Comment by tech6hutch** [comment]
@felixc while this doesn't solve your situation, I'd just like to point out that your function already creates a new HashSet on every iteration, when you take the intersection, so a more efficient solution wouldn't use fold_first anyway.

**Comment by BartMassey** [comment]
@tech6hutch, @felixc I think the fundamental problem here is with `HashSet::intersection()`, not with `fold_first()` (which will now be called `reduce()`, apparently). It would be really nice if sets provided `Set::union_with(&set)` and `intersect_with(&set)` and `difference_with(&set)` that took owned `self` and returned a modified `Set`.  In my experience, that is a pretty common thing to want to do with sets. It would solve this problem nicely while likely being more efficient than re-collecting the set: I am somewhat skeptical that the compiler can sort this out.

I would love to see this stabilized, under any name. Right now my Advent of Code 2020 Day 6 [solution](https://github.com/BartMassey/advent-of-code-2020/blob/main/day06/soln.rs) essentially synthesizes it via something vaguely like ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f70ec67948e1c008ebc93233e39db3ef))

```rust
fn fold_first_vec<T>(mut v: Vec<T>, combine: fn(T, T) -> T) -> Option<T> {
    let last = v.pop()?;
    Some(v.into_iter().fold(last, combine))
}
```

which works but is Vec-specific and only works when `combine` is symmetric and is somewhat awkward to use with `union()` and `intersection()`.

**Comment by jacobchrismarsh** [comment]
> So instead we have to insert a `cloned()` into the iterator, which seems expensive:

Another solution to this would be to use `into_iter` as opposed to just `iter` to take ownership of the values.

 I also stumbled onto this issue due to Advent of Code, and I'm a firm proponent of `reduce`. As mentioned above, that's the common terminology across several languages (scala, python, javascript, kotlin). This feature also matches the functionality in the aptly named ["reduce" crate](https://crates.io/crates/reduce).

**Comment by WaffleLapkin** [comment]
> I'm wondering if I'm missing something obvious (I'm a beginner!), but since the closure takes `Self::Item` (_not_ a reference!), but `.iter()` seems to produce _references_, does that mean every `fold_first` invocation currently needs to be preceded by `.cloned()` (and incur that cost) if the iterated type can't be copied?

@felixc it doesn't need to be produced by `.cloned()`. For `.iter()` iterator, `Self::Item = &'a T`, so `reduce` will work with references just as with any other type.

> ...but this doesn't work, because fold_first needs accumulator and next to be `HashSets`, not `&HashSet`, like iter() gives us:

Compiler is telling you the opposite. `reduce` assumes that the accumulator is equal to the item of the iterator. In this case the `Self::Item = &HashSet<usize>`. So the closure is expected to return a reference too,  but it's impossible to create a reference in your case, since you are trying to create a new `HashSet`.

**Comment by vchekan** [comment]
> ## `fold_first`
> 
> The current name.
> ### Pros:
> 
>     1. It is the existing name that won't break anything.

While it is an iportant factor to break as little as possible, it is one-time cost, whereas good name is recurring cost. So if there is a possibility to choose good name, then breaking non-stable API should have lower wight.
 
>     2. It is similar to `fold`, so it is easy to remember, and the name gives a strong clue to what it does.

I would say it is not. It has important semantic difference in case of empty iterator, so calling it the same will make it only more difficult to find.

Another argument would be that `reduce` is used in other CS areas and is associated with operation which takes 2 items, consumes it and produce 1 item. For example, in parsers expression evaluation, and many other. 


> ## `fold_with_first`
> 
> **[Edit: Added after suggestion]**
> ### Pros:
> 
>     1. It is similar to `fold`, so it is easy to remember, and the name gives a strong clue to what it does.
> 
>     2. It is more explicit than `fold_first`, so easier for first-time users.

I would not associate one more word in function name with better explicitness. It is not how first-timers seek for a function. Nobody reads function name as plain English. What people do, is use operation name they know from their primary language or CS course. Then scan function list of Iterator for this name. So the word "with" is just noise in process of locating the function. Backup plan is to find similar function, for example `fold` and scroll source code up and down, similar functions usually are nearby. Or 3rd option is to use stackoverflow and search for "<reduce in my primary language> in Rust".

> 
> ### Cons:
> 
>     1. It is, AFAICT, unique to Rust.
> 
>     2. It is longer than `fold_first`, and of similar utility to users who have used it a few times before.
> 
> 
> ## `reduce`
> ### Pros:
> 
>     1. This would use `fold` and `reduce` the same way that Scala and Kotlin do, which may start an effective standardization.
> 

Again, I think it is not just those 2 languages but much closer to meaning of `reduce` operation concept.

>     2. The different names emphasize an important difference: while `fold` may have a different accumulator state, `reduce` returns the iterator `Item` type.
> 
>

Yes!

> ### Cons:
> 
>     1. For new people (not from Kotlin/Scala), it may seem arbitrary which functionality is `fold` and which is `reduce`.

They have different API and different capabilities and different results for empty sets. Can not see how this could be qualified as "arbitrary". 

>     2. It is not as obvious if you are looking at either `fold` or `reduce` that the other function exists.

Naming things similarly does not achive this goal. It can be achieved much more efficiently by documentation. List logical and functional limitations in both functions: `reduce` can not produce type different than the set and `fold` can produce meaningless result for empty sets and cross-reccommend functions in the documentation.
Rust is already doing great job by "Use X when:" https://doc.rust-lang.org/std/collections/index.html


>     3. It might conflict with `ParallelIterator::reduce` in Rayon.
> 
> 
> ## ~`try_fold_first`~
> 
> **[Edit: Removed since most people disprefer this.]**
> ### ~Pros:~
> 
>     1. ~Emphasizes that it may return `None`, which is error-like.~

Rust have already made it hard to ignore :)

> 
> ### Cons:
> 
>     1. ~The current functions `try_fold` and `try_for_each` use `try_` to indicate that the _supplied_ function may fail.  This function would use `try_` to indicate that the `fold` may "fail" because the iterator is empty, not because the supplied function is fallible.~
> 
> 
> I'm happy to add additional pros/cons if people feel I've missed something important.
> 
> As stated before, I don't have strong feelings about the name. I weakly dislike `try_fold_first`, because it is using `try_` differently than other functions within the group. In particular, the `None` case is not an error, but an expected result on an empty iterator.

**Comment by m-ou-se** [comment]
> Would this also be the place to leave comments/questions on the API and usage?

It'd be better to ask quesitons like that on [Discord](https://discord.gg/rust-lang) or the [users forum](https://users.rust-lang.org/), to keep these (tracking) issues focussed on the design of the API.

**Comment by rossmacarthur** [comment]
@imjasonmiller  https://github.com/rust-lang/rust/pull/79805#issuecomment-740469963 brings up another concern for `reduce()` which I think hasn't been mentioned yet.

> With Rust seemingly already having `.rfold()`, I think it might be hard on the eyes to possibly have `.rreduce()` — if that functionality might be added and the naming convention will be adhered to? In that regard, I think `.rfold_first` might be easier to read.

**Comment by jacobchrismarsh** [comment]
@rossmacarthur there's some more great discussion in that issue as well. It definitely flipped my opinion. While `reduce` is what my heart wants, it looks like `fold` and `reduce` are used pretty interchangeably, and as such Rust should stick with `fold` and `fold_first`. Especially if `rfold_first` gets added to the API.

**Comment by rossmacarthur** [comment]
Yeah, it's also my concern that `reduce` seems to be quite an overloaded term. As for `rfold_first` / `rfold_with_first`, would it make more sense for it to be `fold_last` / `fold_with_last` 🤔? I

**Comment by rossmacarthur** [comment]
Also I think discoverability is not really a concern. I think it would be very easy to make it so that `reduce` links to these functions in the documentation. This already works actually:

![image](https://user-images.githubusercontent.com/17109887/101732013-3198d500-3ac5-11eb-8794-95bc518c34c1.png)

**Comment by leebenson** [comment]
FWIW, and this may be a minor point, but I like the fact that `fold_first` is right next to `fold` in the docs, alphabetically

If this were `reduce` to fit other languages, it would have probably taken me a little longer to hunt down. I found the naming to be quite descriptive/instinctive, having it grouped with the explicit first value variant.

**Comment by mibmo** [comment]
Regardless of the name, this would be extremely useful.

I myself am partial to `fold_first` and `fold_with_first`, since they'd be right next to `fold` in the docs, like @leebenson mentioned.
`fold1` would still be next to `fold`, but I'd be confused if I hadn't seen it before and encountered it in code.

**Comment by arnabanimesh** [comment]
I prefer `fold_first` because of the `docs` thing and also it shows that it is related to the `fold` function in some way. `fold_with_first` is unnecessarily verbose; `reduce` isn't descriptive, doesn't associate itself with `fold` and also it becomes confusing to memorize in the long run.

**Comment by m-ou-se** [comment]
@arnabanimesh See [the stabilization PR](https://github.com/rust-lang/rust/pull/79805) for that discussion.

**Comment by jplatte** [comment]
Stabilized in #79805, this issue can be closed 🙂
