### ISSUE TITLE
`unused_parens` doesn't fire for trailing return expression

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#68386]
```rust
fn foo() -> u32 {
    let _ = (5); //~ LINT unnecessary parentheses around assigned value
    (5) // no lint
}
```

**Comment by Tyg13** [comment]
I'd be interested in handling this.

Looking at `librucst_lint/unused.rs`, it looks fairly straightforward -- however it does look like there could be some ambiguity with return values in blocks (e.g. `let _ = { (5) };`) Would we want to disambiguate lints, or would it be fine to use the same lint diagnostic for both cases?

**Comment by varkor** [comment]
@Tyg13: what sort of ambiguity do you mean? I'd expect a single lint on `(5)` in your example (note that we [don't yet lint](https://github.com/rust-lang/rust/issues/68387) about unused `{}`).

**Comment by Tyg13** [comment]
@varkor: To use your original example,

```rust
fn foo() -> u32 {
    let a = {
        let b = 5;
        (b)
    };
    (a)
}
```

Both `(a)` and `(b)` are `StmtKind::Expr`, since they represent the implicit return at the end of a block. I was wondering if we'd care about the `(b)` case, and if we did, if it made sense to treat it the same as `(a)`. If you naively add a match arm to the `Stmt` visitor, you get the same diagnostic for both.

**Comment by varkor** [comment]
Yes, both `(a) and `(b)` should be linted here.
