### ISSUE TITLE
rustc doesn't complain if extern rlib is missing

### ISSUE THREAD

**Issue by andir** [rust-lang/rust#68417]
I just came across a weird case where rustc would not warn that a given extern dependency could not be found. I believe it should just warn the user or throw an error in that case instead of silently ignoring the error. It seems like the dependencies are only checked on a per-use basis whereas I believe being more strict here would probably not harm and help users find issues earlier.

# Reproducer

```
$ echo 'fn main() {}' > foo.rs
$ rustc foo.rs --extern something=asdlflaksdjfljsaljfdlaskjdf
```

# What happened

It did compile my trivial program without any issues.

# Expected output

The compiler should have warned or thrown an error about the missing `something` dependency. Alternatively warned about an unused dependency that was provided.

**Comment by nagisa** [comment]
Likely an oversight in implementation of Rust 2018 implicit `extern crate` mechanism.

```
echo 'extern crate banana; fn main(){}' | rustc --extern banana=fooooooo -
```

behaves just as you'd expect.

**Comment by petrochenkov** [comment]
This is by design.
Crates from `--extern` are looked up on the filesystem and loaded lazily, so if they are never used from source code, then they are never loaded and not put into dependency info.

[Sometimes](https://play.rust-lang.org) the number of crates on the command line is much larger than the number of actually used crates, so we don't want to load, or even search and touch them.

**Comment by petrochenkov** [comment]
>Alternatively warned about an unused dependency that was provided.

This, on the other hand, would be a nice lint.
(And not requiring going to filesystem.)

**Comment by nagisa** [comment]
A lint for unused crates is being tracked https://github.com/rust-lang/rust/issues/57274 AFAIK
