### ISSUE TITLE
Need a solution for select / async events

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#6842]
Pipes supports 'select', which allows one to receive on multiple ports at the same time. The new scheduler doesn't have a solution for this, but it needs to be more general than the old one.

Some types of events we might want to wait on:

* Port receives, both one-shot, stream and other receives
* I/O reads of all kinds
* Timers
* Socket accepts

Miscellaneous notes:

The biggest requirement is that we need one abstraction that allows for waiting on both I/O events (single-threaded) and comm events (multithreaded). uv handles and comm types have very different implementations.

`select` may not be the right abstraction. Maybe there are more expressive ways to do this. We could for instance have an event loop with callbacks. Also look an .NET's async I/O which I know nothing about. Needs more research.

Asynchronous I/O events should hopefully allow for all the various extension methods and decorator types that synchronous I/O allows.

The solution should additionally be workable for tasks that are not coroutines scheduled by an I/O event loop. We would like to have tasks that are backed simply by threads and don't use the I/O event loop and that makes the design of various runtime components more difficult. It's potentially ok not to solve this yet.

Some types of events need to be cancellable as well, e.g. if you wait on both a timer and an accept, if the timer goes off first you may want to cancel the accept.

**Comment by SirVer** [comment]
+1. I was playing around trying to implement a simple chat server and was confused that I could not `select!` over socket types or streams. Having channels is only half good if you cannot have `poll` on your sockets.

**Comment by nathanaeljones** [comment]
One of the earliest comments asked about .NET's async system. It's a callback system, like most, but there is a lot of syntactic sugar, and the 3 different systems that are exposed have different levels of overhead. 

The most popular is C# async/await, which generates a closure and state machine to provide a continuation callback. Stack and thread context restoration is expensive, but you can opt out per-task.

 F# has a simpler implementation, due to its functional nature and the ease of continuation passing.

The original used begin_[task] end_[task], i.e, https://msdn.microsoft.com/en-us/library/system.io.stream.beginread(v=vs.80).aspx and https://msdn.microsoft.com/en-us/library/system.io.stream.endread(v=vs.80).aspx

I am very interested in interop between Rust and other languages, particularly F#, C#, Ruby, and Lua.

Are there any traits in the standard library which will describe a (callback+token/state object)-driven stream interface?

**Comment by steveklabnik** [comment]
Moving to the RFCs repo, like other wishlist items: https://github.com/rust-lang/rfcs/issues/1081
