### ISSUE TITLE
`nth_back()` for `Zip` returns wrong values

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#68536]
Assertions are successful in this code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ecd909fd9a7fb53290298f2045a07bfd)):

```rust
let mut a = Vec::new();
let mut b = Vec::new();
let value = [1, 2, 3, 4, 5, 6]
    .iter()
    .cloned()
    .map(|n| {
        a.push(n);
        n * 10
    })
    .zip([2, 3, 4, 5, 6, 7, 8].iter().cloned().map(|n| {
        b.push(n * 100);
        n * 1000
    }))
    .nth_back(3);
assert_eq!(value, Some((30, 4000)));
assert_eq!(a, vec![6, 6, 5, 5, 4, 4, 3]);
assert_eq!(b, vec![800, 700, 700, 600, 600, 500, 500, 400]);
```

But later assertions are actually wrong (the second and third ones shouldn't double-count).
@matthewjasper pointed out it's a bug that exists in the current `next_back` implementation.

**Comment by timvermeulen** [comment]
`a` and `b` are obviously wrong, but `value` seems correct to me? The `zip` produces
```rust
[(10, 2000), (20, 3000), (30, 4000), (40, 5000), (50, 6000), (60, 7000)]
```
so `nth_back(3)` correctly produces `(30, 4000)`.

**Comment by JohnTitor** [comment]
@timvermeulen Ah, my bad. Thanks for pointing out!

**Comment by timvermeulen** [comment]
The problem seems to be that the specialized version of `Zip::next_back` calls `TrustedRandomAccess::get_unchecked(i)` on both inner iterators [here](https://github.com/rust-lang/rust/blob/master/src/libcore/iter/adapters/zip.rs#L246), which doesn't affect the `len()` of the inner iterators in any way. As a result, the next time `next_back` is called, `next_back` is called on both inner iterators [here](https://github.com/rust-lang/rust/blob/master/src/libcore/iter/adapters/zip.rs#L226-L242) because their length now exceeds `self.len` by 1. So I think we probably need to call `next_back` on the inner iterators instead of `get_unchecked`. I'll check if this negatively affects benchmarks in any way.

To be honest, it's not really clear to me why `Zip` needs `get_unchecked` anyway (or why `Zip` has the `index` and `len` fields for that matter). From quickly reading the code, it seems like its main purpose is to make `Zip::nth` O(1) in case both inner iterators are known to not have side-effects, but in that case I think we could just call `nth` on the inner iterators instead? Maybe I'm missing something.

**Comment by spastorino** [comment]
This is really a `libs-impl` thing, fixing labels accordingly.

**Comment by nikomatsakis** [comment]
@timvermeulen did you ever experiment with the fix that it sounds like you had in mind here:

>  I'll check if this negatively affects benchmarks in any way.

**Comment by spastorino** [comment]
Removing nomination as [it was discussed during today's weekly meeting](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.20meeting.5D.202020-06-11.20.2354818/near/200555757).

**Comment by Dylan-DPC** [comment]
Marking this as p-high as per the [prioritization discussion](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/I-prioritize.20.2368536.20.60nth_back().60.20for.20.60Zip.60.20returns.20wrong.20val)

**Comment by timvermeulen** [comment]
@nikomatsakis Thanks for pinging me, I had completely forgotten about this. I remember going down a rabbit hole that eventually spawned #69187 — in a world where that compiled better, we might very well not need the `index` and `len` fields on `Zip` anymore (or, for that matter, a `get_unchecked` method that doesn't advance the iterator). But for now it looks like this issue is being taken care of.
