### ISSUE TITLE
Cross-platform conflict while linking

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/rust#68599]
Now I try use nightly rustc on cygwin. While compiling libbacktrase-sys, mingw-gcc uses cygwin headers, for example, it take errno value as "__errno()", and after compiling, symbol dumping shows that library has undefined reference to "___errno" (with 3 underscores). While libmsvcrt adds this function named __errno (with 2 underscores). This makes it impossible to compile on the cygwin platform. I think the mingw compiler shipped with rustc must have its own headers.
```
$ rustc -vV
rustc 1.42.0-nightly (8a79d08fa 2020-01-27)
binary: rustc
commit-hash: 8a79d08fa57e1c257d647c9848e35defcb379c07
commit-date: 2020-01-27
host: i686-pc-windows-gnu
release: 1.42.0-nightly
LLVM version: 9.0
```
I can use the hack with editing errno.h, but it's not good solution.

**Comment by retep998** [comment]
Rust does not support Cygwin.

**Comment by aristarh2704** [comment]
Why does mingw come with the compiler? Indeed, in theory, the system should have its own mingw compiler, if in some situations headers are used

**Comment by retep998** [comment]
The `pc-windows-gnu` targets come with a minimal subset of MinGW sufficient to link pure Rust binaries. That currently causes some issues such as https://github.com/rust-lang/rust/issues/47048 when you also have a full external MinGW toolchain, but https://github.com/rust-lang/rust/pull/67429 is supposed to fix that so it'll favor your external MinGW toolchain over the bundled MinGW. That said, Rust still does not support Cygwin.

**Comment by aristarh2704** [comment]
Ok, it's possible define i686-pc-cygwin-gnu?

**Comment by mati865** [comment]
`pc-windows-gnu` nightly builds now use system MinGW if available with bundled one as a fallback.

@aristarh2704 do you want to crate binaries for Cygwin or native Windows?

**Comment by workingjubilee** [comment]
Any hypothetical new target would follow the [target tier policy](https://doc.rust-lang.org/rustc/target-tier-policy.html) for how to add it, and you are welcome to do so if you also want to do the work of maintaining it. Judging by how often the existing pc-windows-gnu target gets flakey, it would be a **LOT** of work if you ever wanted it above tier 3. Not for the fainthearted. But if sufficient maintenance comes for it, I suppose we might.

Otherwise, I do not think the windows-gnu target includes cygwin, so closing this.
