### ISSUE TITLE
rustbuild: LLVM is not partially rebuilt anymore

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#68715]
Even tiny changes like https://github.com/rust-lang/rust/pull/68570 cause a full rebuild.

This is a regression from the few recent months (?).
Before that partial rebuilds worked, I remember it because I implemented them back in 2017 (https://github.com/rust-lang/rust/pull/40329).

I didn't yet investigate what happens exactly.

**Comment by cuviper** [comment]
I think it's because the git hash is set in `LLVM_VERSION_SUFFIX` here:
https://github.com/rust-lang/rust/blob/cd1ef390e731ed77b90b11b1f77e2c5ca641b261/src/bootstrap/native.rs#L240-L253

This propagates to `PACKAGE_VERSION` in `llvm/Config/config.h`, which affects the entire build.

**Comment by cuviper** [comment]
There's a cmake variable `LLVM_APPEND_VC_REV` that would probably behave better for this.

**Comment by tmiasko** [comment]
The `LLVM_VERSION_SUFFIX` is indeed responsible for complete rebuilds.
The intent behind PR that introduced it was to disambiguate between versions of
LLVM library that are incompatible yet previously could share the same name.

Unfortunately `LLVM_APPEND_VC_REV` doesn't help, since it is about stashing
version control revision information somewhere inside the library, rather than
changing the library name itself.

Removing commit SHA from default version suffix should be enough to address 
the original issue while resolving this one.
