### ISSUE TITLE
Specialization of associated types do not compile, while it should.

### ISSUE THREAD

**Issue by wdanilo** [rust-lang/rust#68776]
Hi, consider the following code:

```rust
#![feature(specialization)]

use core::ops::Deref;
use std::rc::Rc;

pub trait HasContent {
    type Content : ?Sized;
}

pub type Content<T> = <T as HasContent>::Content;

pub trait Unwrap : HasContent {
    fn unwrap(&self) -> &Self::Content;
}

default impl<T:Deref> HasContent for T {
    type Content = <Self as Deref>::Target;
}

default impl<T> Unwrap for T
where T:Deref<Target=Content<T>> {
    fn unwrap (&self) -> &Self::Content {
        self.deref()
    }
}

impl<T:?Sized> Unwrap     for Rc<T> {}
impl<T:?Sized> HasContent for Rc<T> { type Content = T; }
```

It compiles fine. However, if we change the last line to:

```rust
impl<T:?Sized> HasContent for Rc<T> {}
```

It does not anymore:
```
conflicting implementations of trait `Unwrap` for type `std::rc::Rc<_>`
```

Playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=588c3a6580482515580e65e977f5b778

I believe it should compile as the default impl should resolve to the same thing as the original code.

**Comment by jonas-schievink** [comment]
According to the rules specified in RFC 1210, it is expected that this fails to compile.

In particular, if you instantiate the bottom impl, you *can* always instantiate the `default` impl so that the input types match, but then assuming the where-clauses on the bottom impl will *not* let you prove the where-clauses on the `default impl`, so this is rejected.

Closing as expected behavior.
