### ISSUE TITLE
dep-info rmeta path is wrong

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#68839]
The path to the rmeta file in the dep-info file is wrong.  It is missing the `lib` prefix.

`rustc --emit=dep-info,metadata --crate-type lib foo.rs`

`foo.d` will contain `foo.rmeta: foo.rs`, but I think it should be `libfoo.rmeta: foo.rs` because the filename is `libfoo.rmeta`.

The crate type doesn't matter.  A "bin" type will also emit `foo.rmeta`, but bin types (confusingly) also use `libfoo.rmeta`.

(This doesn't really affect Cargo, as it ignores these filenames.)

**Comment by contrun** [comment]
Can you please elaborate on why this does not affect cargo and how cargo set the output file name? 

It seems the crate type is parsed from https://github.com/rust-lang/rust/blob/15812785344d913d779d9738fe3cca8de56f71d5/src/librustc_session/config.rs#L1844-L1865. It is a vector. I am not sure if I need to add the prefix `lib`.

**Comment by ehuss** [comment]
I'm not sure I understand the relevance of the note about parsing crate types.

[This](https://github.com/rust-lang/cargo/blob/94c7bc7bdbdb76f36686640117edbe20ce0e1707/src/cargo/core/compiler/fingerprint.rs#L1614-L1618) is where Cargo parses the dep-info file. It only looks at the first line, and ignores the value before the `:`.

You can look at #49289 to start to investigate why binaries emit a filename with the `lib` prefix. That PR is what added `rmeta` output for binaries (the rmeta file is empty, it only exists to signal to Cargo that the compilation finished).  I believe [this](https://github.com/rust-lang/rust/blob/303d8aff6092709edd4dbd35b1c88e9aa40bf6d8/src/librustc_interface/passes.rs#L920-L935) is where the rmeta filename is determined.  The dep-info filenames are computed around [here](https://github.com/rust-lang/rust/blob/303d8aff6092709edd4dbd35b1c88e9aa40bf6d8/src/librustc_interface/passes.rs#L461-L493).  Somehow the two are out of sync.

**Comment by TheDreadedAndy** [comment]
According to the [documentation for --emit](https://doc.rust-lang.org/rustc/command-line-arguments.html#--emit-specifies-the-types-of-output-files-to-generate), the default filename for an rmeta file should be CRATE_NAME.rmeta. That would suggest that the actual problem is the file name itself, which I believe is set [here](https://doc.rust-lang.org/stable/nightly-rustc/src/rustc_session/output.rs.html#140). Changing that would likely be breaking for anyone who doesn't use Cargo, though.

A workaround for this problem is to specify the output path for the metadata file. e.g. --emit=metadata=path/to/libfoo.rmeta. The dep-info is generated correctly when that is done.

**Comment by ehuss** [comment]
Oh, looks like the `--emit` docs are wrong.  The rmeta file needs to start with `lib` to work with crate discovery, and to match the `.rlib` naming convention.  I posted #95131 with a fix for the docs.

**Comment by Enselic** [comment]
PR with fix: https://github.com/rust-lang/rust/pull/114750
