### ISSUE TITLE
Strange borrowing issue in inherent async method.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#68950]
Not sure whether it's a bug, but it is indeed strange...
```rust
struct A;
// this compiles
fn test(s: &mut A, arg: &str, handler: Box<dyn Fn() + 'static>) {
        
}
// this doesn't
impl A {
    async fn test2(&mut self, arg: &str, handler: Box<dyn Fn() + 'static>) {
        
    }
}
```
`test2` errors with:
```
error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
  --> src/lib.rs:8:76
   |
8  |     async fn test2(&mut self, arg: &str, handler: Box<dyn Fn() + 'static>) {
   |                                                                            ^
   |
```

**Comment by crlf0710** [comment]
Seems similar to #68759 ....

**Comment by Aaron1011** [comment]
This appears to have the same underlying cause as https://github.com/rust-lang/rust/issues/64552 (which @csmoe is working on in https://github.com/rust-lang/rust/pull/68362).

When you write `handler: Box<dyn FnOnce() + 'static>` (or `handler: Box<dyn FnOnce()>`, which desugars to the same thing), the AST lowering doesn't create a lifetime parameter in the created opaque type, since you don't need a lifetime parameter for `'static`. However, 

However, when we create the generator type, we forget that the region is `'static`: https://github.com/rust-lang/rust/blob/9b9d2aff8de4d499b4ba7ca406e000f8d3754ea7/src/librustc_typeck/check/generator_interior.rs#L124-L144

Thus, we end up trying to process a member constraint for some newly created region `_#0r`. Since by construction we have no constraints for it, we cannot prove that it is equal to any of the regions in the member constraint (even though it's "really" `'static`).

As a workaround, we could special-case `'static` during the creation of the generator type, and leave it as-is instead of creating a fresh late-bound region.

As in https://github.com/rust-lang/rust/issues/64552, I believe the full solution is for generator types to carry 'extra' region constraints with them in some form, so that we don't lose the lexical region information that we had prior to the lowering.

**Comment by tmandry** [comment]
Thanks @Aaron1011. I'm going to close this as a duplicate of #64552, but note on the issue that we should add a test with the code from this issue.
