### ISSUE TITLE
Intermediate operations on collected Vec prevent type inference

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#68991]
I tried this code:

```rust
use std::ffi::OsString;
use std::os::windows::ffi::OsStrExt;

pub fn foo(s: OsString) -> Vec<u16> {
    let mut s = s.encode_wide().collect();
    s.push(0);
    s
}
```

I expected it to compile, considering the only thing `s` can be, here, is a `Vec<u16>`. Without the intermediate `push`, the code compiles.

Instead, this happened:

```
error[E0282]: type annotations needed
 --> <source>:6:5
  |
5 |     let mut s = s.encode_wide().collect();
  |         ----- consider giving `s` a type
6 |     s.push(0);
  |     ^ cannot infer type
  |
  = note: type must be known at this point

error: aborting due to previous error
```
### Meta

`rustc --version --verbose`:
```
rustc 1.43.0-nightly (58b834344 2020-02-05)
binary: rustc
commit-hash: 58b834344fc7b9185e7a50db1ff24e5eb07dae5e
commit-date: 2020-02-05
host: aarch64-unknown-linux-gnu
release: 1.43.0-nightly
LLVM version: 9.0
```

**Comment by jonas-schievink** [comment]
I believe this is a known issue with how inherent impls are treated. Not sure if there's already an issue for that.

**Comment by ExpHP** [comment]
This is a well-known limitation of the type-checker.  Basically, the code is type-checked in order.  Normally, thanks to type inference, this is not a big deal, but for method calls it must be possible to resolve the method at the time a method call is seen (to know whether it's inherent or from a trait), otherwise the compiler cannot determine the return type.

See #42333.

**Comment by jonas-schievink** [comment]
Closing in favor of that, then
