### ISSUE TITLE
make format! accept const vars as format-strings

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#69133]
I wonder if we could make rustc accept code like this:
````rust
    const y: &str = "hello {}";
    let x = format!(y, "world");
````

Currently this errors with:

````
error: format argument must be a string literal
 --> src/main.rs:3:21
  |
3 |     let x = format!(y, "world");
  |                     ^
  |
help: you might be missing a string literal to format with
  |
3 |     let x = format!("{} {}", y, "world");
  |                     ^^^^^^^^
````

`rustc 1.43.0-nightly (58b834344 2020-02-05)`

**Comment by sfackler** [comment]
Macros run before name resolution, so there's no way for `format!` to find the contents of the string `y`.

**Comment by Centril** [comment]
Closing with @sfackler's explanation.

**Comment by vgsantoniazzi** [comment]
If you want to interpolate like that, you can use `stringify!`

https://doc.rust-lang.org/std/macro.stringify.html

**Comment by EricHe56** [comment]
maybe a inline function can help on it.

**Comment by dtolnay** [comment]
I wonder whether this can be reconsidered now after https://github.com/rust-lang/rust/pull/106745, as processing the format string no longer occurs during macro expansion, so it could do name resolution.

**Comment by m-ou-se** [comment]
Processing the string still happens during macro expansion actually. (The format string syntax is directly parsed, implicit arguments are directly resolved to their indexes, etc. etc.) It's just that instead of expanding to a `fmt::Arguments::new(…)` expression directly, it will expand to a special [FormatArgs AST node](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/format/struct.FormatArgs.html) first, which will be expanded to the call expression when lowering the AST to HIR.

(And if we want to be able to resolve names/constants, I think we'd need to postpone the parsing not only until the AST lowering, but even later in the HIR.)
