### ISSUE TITLE
unused_unsafe: stop interpreting `unsafe fn`s as unsafe contexts

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#69173]
In other words, the following will result in a lint being emitted today:
```rust
unsafe fn _bar() {}

unsafe fn _foo() {
    unsafe {
        _bar();
    }
}
```

==>

```rust
warning: unnecessary `unsafe` block
 --> src/lib.rs:4:5
  |
3 | unsafe fn _foo() {
  | ---------------- because it's nested under this `unsafe` fn
4 |     unsafe {
  |     ^^^^^^ unnecessary `unsafe` block
  |
  = note: `#[warn(unused_unsafe)]` on by default
```

Based on the discussion in a recent language team meeting (see summary as outlined by @nikomatsakis in https://github.com/rust-lang/rfcs/pull/2585#issuecomment-586325462), we would like to stop emitting the lint in this case where we have unsafe operations inside an `unsafe { ... }` inside an `unsafe fn` (it's probably easiest to not emit the lint at all as opposed to emitting a different lint name, but this can be determined as part of the implementation).

cc @RalfJung @rust-lang/lang 

This issue has been assigned to @LeSeulArtichaut via [this comment](https://github.com/rust-lang/rust/issues/69173#issuecomment-587110831).

**Comment by Centril** [comment]
cc @oli-obk @eddyb for mentoring instructions?

**Comment by eddyb** [comment]
So looking at the code, it seems that the *outermost* active `unsafe` block (or `unsafe fn`) is used:
https://github.com/rust-lang/rust/blob/dbef35309d10bed2f09cd55b3e9ea980a58c62aa/src/librustc_mir_build/build/block.rs#L212-L216

(NB: very confusing terminology around `unpushed_unsafe`, AFAICT it means "`unsafe` unrelated to `{Push,Pop}Unsafe`", and the latter is a hacky way to do `allow_internal_unsafe`, so we should rip it out sooner or later - but it shouldn't impact this issue, it's just confusing)

This are the possible values for `Safety`: https://github.com/rust-lang/rust/blob/dbef35309d10bed2f09cd55b3e9ea980a58c62aa/src/librustc/mir/mod.rs#L380-L388

So when the "current safety" is `Safety::FnUnsafe`, it early-`return`s, instead of replacing it with the inner `Safety::ExplicitUnsafe`.

By making this change, I think we can get the desired lint effect (while `unsafe fn` still allowing unsafe operations outside of `unsafe` blocks):
```diff
- Safety::Safe => {}
+ Safety::Safe | Safety::FnUnsafe => {}
```

**Comment by LeSeulArtichaut** [comment]
I’m currently trying to tackle this.
@rustbot claim

**Comment by RalfJung** [comment]
I updated the RFC to discuss the new proposed lint and the interaction with the "unnecessary unsafe" lint. See https://github.com/rust-lang/rfcs/pull/2585#issuecomment-605663111.

**Comment by kevinmehall** [comment]
This can probably be closed in favor of the RFC tracking issue https://github.com/rust-lang/rust/issues/71668. Merging the change proposed here alone was rejected in https://github.com/rust-lang/rust/pull/69245, but an allow-by-default lint was merged in https://github.com/rust-lang/rust/pull/71862.

**Comment by RalfJung** [comment]
@kevinmehall agreed, thanks.
