### ISSUE TITLE
`Mut` in a pattern matched against a reference changes the binding's type

### ISSUE THREAD

**Issue by arucil** [rust-lang/rust#69461]
I tried this code:

```rust
let (a, mut b) = &(1, 2);
b = *a;
```

With nightly rustc, this code compiles. The hover information of VSCode shows that `a` is a `&i32`, while `b` is an `i32`.

I expected both `a` and `b` to be `&i32`.

**Comment by LeSeulArtichaut** [comment]
I don't think this is a bug, but I might be wrong.
If you change the variable to a non-`Copy` type, you'll get this:
```
error[E0507]: cannot move out of a shared reference
 --> src/main.rs:2:22
  |
2 |     let (a, mut b) = &("a".to_string(), "b".to_string());
  |             -----    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |             |
  |             data moved here
  |             move occurs because `b` has type `std::string::String`, which does not implement the `Copy` trait
```

What you are probably searching for is the `ref mut` syntax:

```rust
let (a, ref mut b) = &mut (1, 2);
*b = *a;
```

**Comment by Centril** [comment]
This is expected behavior.

What happens is pattern type checking is given the *expected* type `&(i32, i32)` and a tuple pattern at the root. A tuple pattern uses the "peeling" adjustment mode, resulting in removing `&` (as many as possible, in this case a single) from the expected type and then making the binding mode to pass down into the recursive steps by-ref. However, default binding modes only affect *unannotated* bindings, whereas annotated bindings (`ref | ref mut | mut`) get the binding mode from the annotation. Since the annotation is `mut`, the binding mode becomes by-value and thus the expected type passed down is used.
