### ISSUE TITLE
New Ternary Operator for Rust

### ISSUE THREAD

**Issue by mrjpaxton** [rust-lang/rust#69545]
Hi,

I have a suggestion for a new and readable ternary operator. I know there's already an issue thread that discusses this, and it is a hot-button topic, but hear me out. Those of you who like this C/C++ feature a lot might like this idea.

The reason why the ternary operator `?:` exists in C++ is to save keystrokes/typing, and improve code layout. It can help improve readability in certain circumstances, while also being a double-edged sword by decreasing readability and keyword searching in other situations. In other words, even professional programmers would agree, its invention can be perceived as its own folly.

I also am aware that the question mark `?` is now used as its own operator for the use of try statements in Rust, so I do not want to conflict with this.

However, what about something more intuitive? This just literally popped into my mind a few minutes ago:

```
let my_value = conditional +: {true} -: {false};
```

Now I don't know if the brackets need to be required, but let's just assume that they do. But you can see how obvious this is, right? If the statement is true (positive) it will evaluate to true. If negative (false) it will just go to false.

It should support newlines as well:

```
let my_value = conditional
+: {true statement}
-: {false statement};
```

Perhaps order can be reversed:

```
let my_value = conditional
-: {false statement}
+: {true statement};
```

And perhaps either the true/false stanza can be ignored:

```
let my_value = conditional
+: {true statement};
```

Now, if anyone mentions the `match` operator (similar to `switch` in C++) then yes, you could use that, but this would have the exact same overhead as an `if-else`, which is what you would want, versus the overhead of a `match`, which can be negligible, but still significant for large code bases.

Feel free to close if anyone is still firm on using `if-else`, because I can deal with it. I just don't know if everyone else is....

**Comment by LeSeulArtichaut** [comment]
I think it has already been decided that Rust would not feature the ternary operator. Please see rust-lang/rfcs#1362

**Comment by Mark-Simulacrum** [comment]
Closing. As a major feature request, this will need to follow the RFC process here https://github.com/rust-lang/rfcs#before-creating-an-rfc.

However, as noted, I believe it's unlikely that Rust would currently accept this feature.

**Comment by Ixrec** [comment]
Since the OP appears unaware of the actual main reason we have no ternary operator:

In C and C++, `if { ... }` is a statement only, but the `?:` ternary operator **is an expression**. For example, `int foo = bar ? 0 : 1;` is legal C/C++, but there's no way to write that with `if`. That's the  biggest practical advantage of `?;` in those languages.

In Rust, `if { ... }` is an expression, so `let foo = if bar { 0 } else { 1 };` is already legal Rust. Thus, a ternary operator would be mostly redundant / only syntactic sugar. And like every other language, sugars need a much stronger argument than "saving a few keystrokes" to justify being added.
