### ISSUE TITLE
Display in test fails with SIGILL (illegal instruction)

### ISSUE THREAD

**Issue by SnowyCoder** [rust-lang/rust#69558]
I tried this code (using `cargo test`):

```rust
use std::fmt::{Display, Formatter};
use std::fmt;
 
pub struct A(Vec<u32>);
 
impl Display for A {
    fn fmt(&self, _f: &mut Formatter<'_>) -> fmt::Result {
       self.0[0];
       Ok(())
   }
}
 
#[test]
fn main() {
   let a = A(vec![]);
   eprintln!("{}", a);
}
```

I expected to see this happen:
The thread should've panicked with 'Index out of bounds: the len is 0 but the index is 0'

Instead, this happened:
Thread crashes with SIGILL (illegal instruction)

### Meta
This bug works in stable, beta and nightly.
It also does the same in [rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5d2cd0b4c6fbbae1455b5cd534693092).
Here is my [cpu info](https://pastebin.com/2VDnmMPR) (I figured that it might be useful given the nature of the bug).
The bug doesn't appear if run from main, nor if run directly (without passing from the Display impl).

`rustc --version --verbose`:
```
rustc 1.41.1 (f3e1a954d 2020-02-24)
binary: rustc
commit-hash: f3e1a954d2ead4e2fc197c7da7d71e6c61bad196
commit-date: 2020-02-24
host: x86_64-unknown-linux-gnu
release: 1.41.1
LLVM version: 9.0
```

<details><summary>Backtrace</summary>
<p>

running 1 test
thread panicked while processing panic. aborting.
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/path/to/proj/target/debug/deps/proj-296b7cb53c6210d6` (signal: 4, SIGILL: illegal instruction)

</p>
</details>

**Comment by jonas-schievink** [comment]
This seems to be due to the `eprintln!`. Using `format!` instead works fine.

**Comment by Mark-Simulacrum** [comment]
I can reproduce. This seems to happen if LOCAL_STDERR is initialized (e.g., with set_panic) which leads us to this [code](https://github.com/rust-lang/rust/blob/eaa02f599f651246d5d1b99e7a4c6fa8d04bc9dc/src/libstd/io/stdio.rs#L795-L799). Note that the RefCell there is borrowed so that we can write to it, but then when we go to panic we try to temporarily [take the value out](https://github.com/rust-lang/rust/blob/eaa02f599f651246d5d1b99e7a4c6fa8d04bc9dc/src/libstd/panicking.rs#L218). This borrows the RefCell mutably, again, leading to a panic. Since this happens within an existing panic, we abort the process.

Smaller example:

```
#![feature(set_stdio, print_internals)]

use std::fmt::{Display, Formatter};
use std::fmt;
use std::io::set_panic;

pub struct A;

impl Display for A {
    fn fmt(&self, _f: &mut Formatter<'_>) -> fmt::Result {
        panic!();
   }
}

fn main() {
    set_panic(Some(Box::new(Vec::new())));
    std::io::_eprint(format_args!("{}", A));
}
```
