### ISSUE TITLE
rustc_const_unstable should check constness

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#69630]
The `rustc_const_unstable` attribute currently does not check whether the function it is applied upon is indeed a `const fn`. I feel like it should check that.

I recently made the mistake of forgetting to mark the function const: https://github.com/rust-lang/rust/pull/69617#discussion_r386157010

ping @oli-obk

**Comment by oli-obk** [comment]
Oh yea, that's a good idea. Note that this can't be done for intrinsics at this point, so you need to make sure to only check `extern "Rust"` functions

**Comment by DutchGhost** [comment]
I'd be happy and try to implement this. However Im not verry familiar with the compiler structure.
As far as I understood, `rust_const_unstable` isn't realy a macro, but more an attribute used by the compiler. With some help on where to start, I'd like to give this a try!

**Comment by oli-obk** [comment]
I didn't find a good entry point. I guess you could pass `i` into https://github.com/rust-lang/rust/blob/beac68a88711a90346ec8b68e3baefbec62b3b0d/src/librustc_passes/stability.rs#L289 instead of the various `i` fields and then  check `i.kind` in https://github.com/rust-lang/rust/blob/beac68a88711a90346ec8b68e3baefbec62b3b0d/src/librustc_passes/stability.rs#L83 for https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/enum.ItemKind.html#variant.Fn and check whether it's `const` (and doesn't have intrinsic Abi). Not sure how messy that gets, but if it's fairly contained, that seems ok to me.

**Comment by lambinoo** [comment]
I am interested in working on this! Could I get assigned to this? I already have a PR for this I think

**Comment by LeSeulArtichaut** [comment]
@lambinoo You can use the `@rustbot claim` command

**Comment by lambinoo** [comment]
Oooh, thanks! :D
