### ISSUE TITLE
Rustdoc doesn't show src button for many functions in the rustc docs

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#70025]
https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/hir/map/struct.Map.html

![image](https://user-images.githubusercontent.com/17426603/76705195-77637100-66de-11ea-93cd-6d28b229d89f.png)

**Comment by ehuss** [comment]
I have narrowed this down to #66364.  There some interaction between remap-path-prefix and macros in a dependency.

**Repro:**
```
cargo new --lib foo
cd foo
cargo new --lib dep
rm dep/src/lib.rs
cat << EOF > dep/src/lib.rs
#[macro_export]
macro_rules! make_item {
    () => {
        pub fn f() {}
    }
}
EOF

echo 'dep = {path="dep"}' >> Cargo.toml
echo 'dep::make_item!{}' >> src/lib.rs
RUSTFLAGS="--remap-path-prefix=`pwd`=/" cargo doc -v  --no-deps
```

This emits a warning:

```warning: source code was requested to be rendered, but processing `/dep/src/lib.rs` had an error: "/dep/src/lib.rs": No such file or directory (os error 2)```

and the `[src]` links don't exist.

If you want to repro with the rustc sources, set `remap-debuginfo = true` and `compiler-docs = true` in `config.toml` and build the rustc docs.

@Centril can you maybe take a look at why this is now broken?

**Comment by Centril** [comment]
For now, I'll cc @GuillaumeGomez @eddyb @petrochenkov who probably know more about this than I.

**Comment by Centril** [comment]
I did a bit of investigation. In https://github.com/rust-lang/rust/pull/66364/files#diff-2b18e583c8286c5f266dcc0aea004e91, we have:
```diff
-        let def = data.get_macro(id.index);
-        let macro_full_name = data.def_path(id.index).to_string_friendly(|_| data.root.name);
-        let source_name = FileName::Macros(macro_full_name);
-
-        let source_file = sess.parse_sess.source_map().new_source_file(source_name, def.body);
-        let local_span = Span::with_root_ctxt(source_file.start_pos, source_file.end_pos);
-        let dspan = DelimSpan::from_single(local_span);
-        let (body, mut errors) = source_file_to_stream(&sess.parse_sess, source_file, None);
-        emit_unclosed_delims(&mut errors, &sess.parse_sess);
+        let span = data.get_span(id.index, sess);
+        let dspan = DelimSpan::from_single(span);
+        let rmeta::MacroDef { body, legacy } = data.get_macro(id.index, sess);
```

Note in particular the `.new_source_file(source_name, def.body)` call, which results in a call to https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/source_map/struct.SourceMap.html#method.try_new_source_file, which has:

```rust
        let (filename, was_remapped) = match filename {
            FileName::Real(filename) => {
                let (filename, was_remapped) = self.path_mapping.map_prefix(filename);
                (FileName::Real(filename), was_remapped)
            }
            other => (other, false),
        };
```
In particular:
```rust
                let (filename, was_remapped) = self.path_mapping.map_prefix(filename);
```

This seems like it could be the significant change here, but I'm not sure.

**Comment by Centril** [comment]
Also relevant:
https://github.com/rust-lang/rust/blob/2113659479a82ea69633b23ef710b58ab127755e/src/librustdoc/html/sources.rs#L35-L55

**Comment by eddyb** [comment]
Hang on, but there should be no macros involved in the `impl` @bjorn3 posted, how is #66364 relevant?

**Comment by bjorn3** [comment]
That code sets `self.scx.include_sources` to false when **any** file could not be read.

**Comment by eddyb** [comment]
Oh, that's just bad UX and should be fixed independently on not being able to load some file.

**Comment by eddyb** [comment]
@Mark-Simulacrum Is there any way to use the `try` build on #70642 to check if it fixes this issue?
i.e. does it include any docs?

**Comment by Mark-Simulacrum** [comment]
I think it should, but not sure. We have a try build going and once that's done IIRC a command like `rustup-toolchain-install-master 5da172dc1b9c7a124a51904b96c20a79b5587292 -c rust-docs` should work, I believe.

**Comment by eddyb** [comment]
@Mark-Simulacrum Uh oh I can't get anything like https://doc.rust-lang.org/nightly/nightly-rustc even for regular `nightly` in `rustup`, and none of `alloc`/`core`/`proc_macro`/`std`/`test` are affected.

Also, since this seems to affect the whole crate, it's easier to spot at that level:
* Affected crates that use the `newtype_index!` macro to define types:
  * [`rustc_ast`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/)
  * [`rustc_hir`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/)
  * [`rustc_middle`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/)
  * [`rustc_mir`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir/)
  * [`rustc_mir_build`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir_build/)
  * [`rustc_query_system`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_query_system/)
  * [`rustc_span`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/)
  * [`rustc_target`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_target/)

* Other affected crates, that use `declare_lint_pass!` to define types:
  * [`rustc_lint`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/)

* Other affected crates, that use `declare_box_region_type!` to define types:
  * [`rustc_interface`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_interface/)

* Other affected crates, that use `impl_stable_hash_via_hash!` to define `impl`s:
  * [`rustc_errors`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/)
  * [`rustc_session`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_session/)

Other affected crates, that use `implement_ty_decoder!` to define `impl`s:
  * [`rustc_metadata`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_metadata/  )

* Other affected crates, that use `thread_local!` to define `static`s:
  * [`rustc_data_structures`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_data_structures/)
  * [`rustdoc`](https://doc.rust-lang.org/nightly/nightly-rustc/rustdoc/)

And that's all the affected crates! Each uses macros from other crates, which define something.

<hr/>

`thread_local!` stands out as being from the standard library. Sure enough:
```rust
thread_local!(pub static FOO: bool = false);
```
```
$ cargo doc
 Documenting test-70025 v0.1.0 (/home/eddy/Projects/test-70025)
warning: source code was requested to be rendered, but processing `/rustc/76b11980ad416c3ad6143504c2277757ecacf9b5/src/libstd/thread/local.rs` had an error: "/rustc/76b11980ad416c3ad6143504c2277757ecacf9b5/src/libstd/thread/local.rs": No such file or directory (os error 2)
         skipping rendering of source code
    Finished dev [unoptimized + debuginfo] target(s) in 3.53s
```
But with #70642, it works:
```
$ rustup-toolchain-install-master 40f2b445cd1c6c4e72d663d23c6d1bef2c674ad4 -c rust-src
$ cargo +40f2b445cd1c6c4e72d663d23c6d1bef2c674ad4 doc
 Documenting test-70025 v0.1.0 (/home/eddy/Projects/test-70025)
    Finished dev [unoptimized + debuginfo] target(s) in 2.21s
$ find target/doc/src/ | rg html
target/doc/src/test_70025/lib.rs.html
target/doc/src/test_70025/home/eddy/.rustup/toolchains/40f2b445cd1c6c4e72d663d23c6d1bef2c674ad4/lib/rustlib/src/rust/src/libstd/thread/local.rs.html
```

However, I have no way to check the CI environment itself, so we'll have to wait for #70642 to land.

**Comment by eddyb** [comment]
Something `rustdoc` could be doing, though, is checking *which `CrateNum`* a file is imported from, and try to use that crate's doc URLs, or at the very least use a separate `doc/src` dir, e.g. instead of:
```
target/doc/src/test_70025/home/eddy/.rustup/toolchains/40f2b445cd1c6c4e72d663d23c6d1bef2c674ad4/lib/rustlib/src/rust/src/libstd/thread/local.rs.html
```
it should probably have created:
```
target/doc/src/std/thread/local.rs.html
```

**Comment by eddyb** [comment]
#70642 landed, let's see what happens in 14-15h from now.

**Comment by eddyb** [comment]
And the source is back! So I'm closing this issue, and I've opened #70757 for the remaining items.
