### ISSUE TITLE
ICE with lifetime-generic type alias impl trait

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#70121]
```rust
#![feature(type_alias_impl_trait)]

pub type Successors<'a> = impl Iterator<Item = &'a ()>;

pub fn f<'a>() -> Successors<'a> {
    None.into_iter()
}

trait Tr {
    type Item;
}

impl<'a> Tr for &'a () {
    type Item = Successors<'a>;
}

fn ohno<'a>() -> <&'a () as Tr>::Item {
    None.into_iter()
}
```

gives:

```
error: internal compiler error: free_scope: DefId(0:3 ~ playground[ad24]::Successors[0]) not recognized by the region scope tree for None / Some(DefId(0:13 ~ playground[ad24]::ohno[0]))
```

My guess is that this has the same underlying cause as https://github.com/rust-lang/rust/issues/56445, but this one doesn't involve associated consts or arrays at all, so it might be different still.

**Comment by Aaron1011** [comment]
This appears to be due to a bad interaction between https://github.com/rust-lang/rust/pull/66178 and associated type projections involving lifetimes.

When we normalize the function signature during type-checking, we project `<&'a () as Tr>::Item` to `Successors<'_#0r>`. We then convert `'_#0r` back to the 'generic' region for `Successors`, which is `'a`.

However, this `'a` is a distinct early bound region, different from the `'a` in `fn ohno<'a>()` (changing the regions to not all be called `'a` in the example makes this clearer). This causes issues during `lexical_region_resolve`, since we've essentially pulled a region out of thin air.

This issue doesn't seem to come up for type parameters ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=fc247fec7228a8ab25c14250ab82949f) with lifetimes replaced with types). I'm not sure if this is because our handling of type parameters is correct for this kind of projection, or if we need a more complicated example to break things.

**Comment by JohnTitor** [comment]
The ICE no longer happens with the latest nightly (note that the playground's nightly isn't the latest). That `delay_span_bug` was removed by #72362. Marked as E-needs-test.
