### ISSUE TITLE
diagnostic could be better whe using "..." instead of ".." when destructuring enum

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#70388]
````rust
enum MyEnum {
    A(i32),
    B(u32),
}

fn use_enum(e: MyEnum) {
    if let MyEnum::A(...) = e {
        println!("got enum")
    };
}
````
The problem here is that we have `if let MyEnum::A(...) = e` instead of `if let MyEnum::A(..) = e`

The compiler however points towards `)` in the error message instead of the superfluous `.`:
```
 error: unexpected token: `)`
 --> src/main.rs:7:25
  |
7 |     if let MyEnum::A(...) = e {
  |                         ^

error: aborting due to previous error
```

Fun fact: when using four dots ` MyEnum::A(....)`, it correctly points at the last dot :)
```
error: unexpected token: `.`
 --> src/main.rs:7:25
  |
7 |     if let MyEnum::A(....) = e {
  |                         ^

error: aborting due to previous error
```

This issue has been assigned to @rakshith-ravi via [this comment](https://github.com/rust-lang/rust/issues/70388#issuecomment-603783627).

**Comment by rakshith-ravi** [comment]
@matthiaskrgr seems like a simple issue to fix. If I were to take a shot at fixing this, where would I start?

**Comment by Centril** [comment]
Mentoring instructions:

Add a branch after this one...
https://github.com/rust-lang/rust/blob/cdb50c6f2507319f29104a25765bfb79ad53395c/src/librustc_parse/parser/pat.rs#L294-L297

...but instead of `self.check(&token::DotDot)`, check that `self.token.kind == token::DotDotDot`.

This should be interpreted as a `::Rest` as in the previous branch, but an error should also be emitted. (Add the code for error emission in a separate method, with an appropriate `.span_suggestion(...)`, where the span of the `...` is replaced with `..`. See `fn recover_intersection_pat` for an example on emitting an error with a suggestion.)

**Comment by rakshith-ravi** [comment]
Sure thing! Will get to it right after work. Thanks for the guidance.
