### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by scalar438** [rust-lang/rust#70433]
I tried this code:

```rust
enum Flag {
    A,
    B,
}

fn move_value(_: Flag) {}

pub fn get_activity_list() {
    loop {
        let activity;

        match 42 {
            42 => {
                if true {
                    activity = Flag::A;
                }
            }
            _ => continue,
        }

        move_value(activity);
    }
}

fn main() {}
```

I expected to see error like "error[E0381]: use of possibly-uninitialized variable". But instead I got error "use of moved value: `activity`". [Playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=5c0758aacb9c18d2f2c3a070124f7253). It happens on nightly and stable and seems very confusing.

**Comment by steffahn** [comment]
Smaller example:

```rust
struct S;

pub fn f() {
    loop {
        let x;
        if true {
            x = S;
        }
        drop(x);
    }
}

fn main() {}
```

([Playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=0afaec45010e35e090dcab41201b0ba8))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0382]: use of moved value: `x`
 --> src/main.rs:9:14
  |
5 |         let x;
  |             - move occurs because `x` has type `S`, which does not implement the `Copy` trait
...
9 |         drop(x);
  |              ^ value moved here, in previous iteration of loop

error: aborting due to previous error

For more information about this error, try `rustc --explain E0382`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by steffahn** [comment]
Gives correct error in 1.35.0. First appears (in stable) in 1.36.0.

**Comment by max-heller** [comment]
> ```rust
> struct S;
> 
> pub fn f() {
>     loop {
>         let x;
>         if true {
>             x = S;
>         }
>         drop(x);
>     }
> }
> 
> fn main() {}
> ```

Without the loop, the appropriate error (use of possibly-initialized `x`) is emitted. I've traced the difference down to the `report_use_of_moved_or_uninitialized` function in `borrow_check::diagnostics::conflict_errors`, where the possibly-initialized error can only be emitted if the vector of move sites produced by `MirBorrowckCtxt::get_moved_indices` is empty. In the version without the loop, it produces no move sites, but when the loop is added it produces a single move site. This seems wrong, since the `x` in the first iteration of the loop is different from the one in the second, but I don't know enough about the borrowck code to know how to address it.

> Gives correct error in 1.35.0. Regression first appears (in stable) in 1.36.0.
> Edit: regression in nightly-2019-04-23

I'm seeing this happen in the 2015 edition, but in 2018 even 1.35 seems to exhibit the incorrect behavior.

**Comment by scalar438** [comment]
It is not reproduces on actual version of rust. On rust 1.56 I got:

   Compiling playground v0.0.1 (/playground)
error[E0381]: use of possibly-uninitialized variable: `x`
 --> src/main.rs:9:14
  |
9 |         drop(x);
  |              ^ use of possibly-uninitialized `x`

For more information about this error, try `rustc --explain E0381`.
error: could not compile `playground` due to previous error

as expected.
