### ISSUE TITLE
Rustdoc shouldn't document a struct's associated constants as methods

### ISSUE THREAD

**Issue by calime** [rust-lang/rust#70475]
When writing associated constants in a struct's implementation, those constants appear under the `Methods` section. Here's a minimal example:
```rust
struct Struc;

impl Struc {
    const S: u64 = 0;
}
```
`$ cargo doc`

For traits though, they appear under `Associated Constants`:
```rust
trait Tr {
    const S: u64 = 0;
}
```
There should also be an `Associated Constants` section for struct documentation.

**Comment by MattX** [comment]
I've looked into this a little bit. It looks like for structs, rustdoc is grouping methods / associated types / associated constants / etc. *per `impl` block*. I agree this makes the "Methods" heading name a bit misleading. For instance,

```rust
struct Struc;

impl Struc {
    const MY_CONST: u64 = 0;
}

impl Struc {
    const MY_OTHER_CONST: u64 = 0;
}
```

Will produce two subheadings under "Methods", both called "`impl Struc`", and each with its own constant documented.

So if we want to keep doing it this way, we can't just add a toplevel "Associated constants headers". (As you mention, it does work for traits, since they don't have several sub-blocks in this way). We could do one of several things:

- Add smaller headings under `impl` headings to separate methods from other associated things. This might get a little crufty.
- Just rename the "Methods" header to "Implementation blocks" or something like that.
- Merge all the `impl` blocks that don't implement a trait (is there a name for these?) together in the doc, and place their combined elements under correct toplevel headings.

Thoughts or other solutions?

**Comment by calime** [comment]
I think renaming Methods to something else will be fine because it is a bit misleading. If I need to, I could put constants and methods in separate `impl`blocks or group relevant items together or something, and get to document each `impl` block separately
