### ISSUE TITLE
TryEnterCriticalSection prototype does not match Windows docs

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#70504]
According to [this documentation](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-tryentercriticalsection), the return type of `TryEnterCriticalSection` is `BOOL` (an alias for `i32`), but in Rust we use `BOOLEAN` (an alias for `u8`):
https://github.com/rust-lang/rust/blob/b9d5ee567652cd342d9348c215009049551747b0/src/libstd/sys/windows/c.rs#L781
Which one is right?

**Comment by Mark-Simulacrum** [comment]
winapi [uses](https://docs.rs/winapi/0.3.8/winapi/um/synchapi/fn.TryEnterCriticalSection.html) BOOL (c_int/i32) -- I suspect that this has been wrong since forever. Presumably we haven't noticed because in practice the values are always just `!= 0` and usually not 0 modulo 256, either, so we aren't spuriously wrong, and the value is passed in a register -- which on ~all platforms is 32-64bits anyway.

Presumably though we should just fix this; cc @alexcrichton who originally added these in 10b103af48368c5df644fa61dc417a36083922c8 and cc @rust-lang/libs more broadly.

(Also, can I just say that having both BOOLEAN and BOOL as aliases and they mean different things is pretty confusing?)

**Comment by alexcrichton** [comment]
This is practically guaranteed to just be a typo on my end, so BOOL is most likely right.

**Comment by RalfJung** [comment]
> (Also, can I just say that having both BOOLEAN and BOOL as aliases and they mean different things is pretty confusing?)

Yeah, that one is on Microsoft... [other functions do return `BOOLEAN`](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-tryacquiresrwlockexclusive).
