### ISSUE TITLE
Odd "error[E0658]: is unstable" diagnostic

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#70538]
```rust
#[link(name = "c", cfg(yes))]
extern {}
```

```
error[E0658]: is unstable
 --> src/lib.rs:1:1
  |
1 | #[link(name = "c", cfg(yes))]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/37406
```

:thinking: 

In addition to the malformed diagnostic, the tracking issue has been closed already. According to https://rust-lang.github.io/rfcs/1721-crt-static.html#lazy-link-attributes, this is supposed to be a permanently-unstable implementation detail. In that case, should the link be updated to point somewhere else?

This issue has been assigned to @Rustin-Liu via [this comment](https://github.com/rust-lang/rust/issues/70538#issuecomment-606399105).

**Comment by estebank** [comment]
The wording can be easily fixed at https://github.com/rust-lang/rust/blob/699f83f525c985000c1f70bf85117ba383adde87/src/librustc_metadata/native_libs.rs#L165.

The link can't be changed to a non-issue because of how the machinery is currently set up, but we can update the description of the ticket to point at RFC 1721.
