### ISSUE TITLE
Make thread local accesses an `Rvalue` in MIR

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#70685]
https://github.com/rust-lang/rust/pull/70598#discussion_r401941499

Thread local accesses are a runtime operation, even if LLVM shims them to appear like normal static accesses. We should encode this runtime-ness in MIR and translate them back to the llvm static accesses in the llvm backend. The other backends (miri, cranelift) then have an easier life at doing the right thing ^TM.

cc @bjorn3 @eddyb @vakaras

**Comment by eddyb** [comment]
Copying my https://github.com/rust-lang/rust/issues/70684#issuecomment-607660169 here
(note "the address of a `#[thread_local]` `static`", *not* "access", the *address itself* is runtime):
<hr/>

As I suggested elsewhere, I believe `#[thread_local]` `static`s should have their own separate access mechanism, probably their own `Rvalue` (or we could start extending what `Rvalue::{Ref,RawPtr}` can borrow).

That's because getting the address of a `#[thread_local]` `static` is a *fundamentally runtime* operation, and LLVM reusing the same syntax as for regular `static`s, is in the wrong here.

**Comment by vakaras** [comment]
@eddyb @oli-obk 
Do you have an estimate how much effort this would require? If it is doable in a day or two and you could give me the mentoring instructions, I could try implementing this.

**Comment by eddyb** [comment]
No idea, cc @matthewjasper @wesleywiser (I forget who did the move to constant pointers for statics)

**Comment by bjorn3** [comment]
> I forget who did the move to constant pointers for statics

That was done in #67000.
