### ISSUE TITLE
`.try_into().unwrap()` is suggested even when `.into()` would work

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#70851]
```rust
fn returns_usize() -> usize {
    let x = 0u8;
    x
}
```

```
error[E0308]: mismatched types
 --> src/lib.rs:3:5
  |
1 | fn returns_usize() -> usize {
  |                       ----- expected `usize` because of return type
2 |     let x = 0u8;
3 |     x
  |     ^ expected `usize`, found `u8`
  |
help: you can convert an `u8` to `usize` and panic if the converted value wouldn't fit
  |
3 |     x.try_into().unwrap()
  |
```

It would be better to suggest `x.into()` instead, which is shorter, cannot fail, and doesn't require importing a trait.

This issue has been assigned to @ryr3 via [this comment](https://github.com/rust-lang/rust/issues/70851#issuecomment-610643984).

**Comment by estebank** [comment]
You need to change the following
https://github.com/rust-lang/rust/blob/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/librustc_typeck/check/demand.rs#L755-L770

so that when one of the `bit_with` is `None` and the other is 8 or 16 bits `is_fallible` is set to `true`.

**Comment by ryr3** [comment]
Hi, this seems like a good first issue. Can I take this up as my first contribution?

**Comment by estebank** [comment]
@ryr3 sure! Go ahead. Visit the rustc guide if this is your first time compiling rustc.

**Comment by tsandstr** [comment]
The docs don't specify that a `usize` can fit a `u16`. In fact, if rust gains support for 8 bit microcontrollers, then wouldn't `usize` be smaller than a `u16`? It seems like the recommendation should be dependent upon the build target. Is this possible?

Note: I have almost zero experience contributing to rust, so if I am wrong (there's probably a good chance I am), I would love to learn why.

**Comment by LeSeulArtichaut** [comment]
> so that when one of the bit_with is `None` and the other is 8 or 16 bits is_fallible is set to `true`

@estebank Isn't it the opposite? If we try to convert a `u8` to a `usize`, we want `is_faillible` to be `false` so we suggest `.into()` instead of `.try_into().unwrap()`.

**Comment by tsandstr** [comment]
Yeah. It's the other way around.

**Comment by ryr3** [comment]
Sorry about those notifications, all. I was experimenting a bit.
Would that fix be good for a PR here, @estebank ?

https://github.com/ryr3/rust/commit/39d2b4a985d17db32e18dcfaf19f8269a7f0adf8

**Comment by LeSeulArtichaut** [comment]
@ryr3 If it works you should open a PR I think. Have you fixed the [tests](https://github.com/rust-lang/rust/tree/master/src/test/ui) that will be affected by this change? You can do so by running `x.py` with the `--bless` flag, like: `x.py test -i --stage 1 --bless src/test/ui`.

**Comment by estebank** [comment]
There might not be tests exercising this code path, but you can add some cases to `src/test/ui/integer-literal-suffix-inference.rs`.

The code change looks good. You will want to also run `./x.py fmt` just to make sure it doesn't get rejected due to formatting style (although the diff I saw looks good to my eyes). Feel free to create a PR with these changes, I'll be more than happy to review/approve.

**Comment by LeSeulArtichaut** [comment]
> There might not be tests exercising this code path, but you can add some cases to src/test/ui/integer-literal-suffix-inference.rs

There still are some. For example:
https://github.com/rust-lang/rust/blob/53712f8637dbe326df569a90814aae1cc5429710/src/test/ui/numeric/numeric-cast.stderr#L23-L32
needs to be changed

**Comment by estebank** [comment]
@LeSeulArtichaut that one seems almost incidental. Given that the test matrix in this case is small enough, it's a good idea to exhaust it in a central place. It's my fault that the `*size` cases weren't in that test already 😬.

**Comment by ryr3** [comment]
With the changes I've made now, it's such that the compiler will suggest usize be .into() when the function requires a u8. Is that fine, because usize will greater than u8 on most targets?
And From(usize) is not implemented for u8/u16 anyway so that would be a bad suggestion.

Also, when I'm writing tests for the *size cases, should I use the `usize::max_value()` and min value functions or just their result on the largest target?

**Comment by LeSeulArtichaut** [comment]
If I understand the code correctly, in your changes, the pattern `(None, Some(8 | 16))` represents the case where we expect a `usize` value, but we have a `u8` or `u16` value instead. In this case, we want `is_fallible` to be `false`.
The pattern `(Some(8 | 16), None)` however, represents the case where we expect a `u8` or a `u16` but we have a `usize`. Then, we want `is_fallible` to be `true` for the reasons you explained.
So if you delete the second pattern, the case where we want to cast `usize` to `u8`/`u16` will get picked up by the next arm and `is_fallible` will be `true` as expected.

As for the testing, I think the value doesn't really matter because those checks are about types, not values themselves. Rust doesn't make implicit conversions. You can just use random values like `5` or `2`, or `usize::max_value()` if you want.

**Comment by ryr3** [comment]
Thanks! I just realized that it would be the other way around here, because in 
https://github.com/rust-lang/rust/blob/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/librustc_typeck/check/demand.rs#L756 and https://github.com/rust-lang/rust/blob/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/librustc_typeck/check/demand.rs#L765 the match parameters are found, exp whereas they are in the order of exp, found everywhere else, including the compiler messages.
Should I rearrange that too (in the match statements only) or leave it as it is?

**Comment by estebank** [comment]
It'll be great if you can bring some consistency in the order.
