### ISSUE TITLE
Refactor CTFE and const-prop machines to share common code

### ISSUE THREAD

**Issue by vakaras** [rust-lang/rust#71129]
[Miri](https://github.com/rust-lang/miri), [CTFE](https://github.com/rust-lang/rust/blob/8e18e26f12b1e8b3e913b15278bf6185f0f61add/src/librustc_mir/const_eval/machine.rs#L169), and [const-prop](https://github.com/rust-lang/rust/blob/8e18e26f12b1e8b3e913b15278bf6185f0f61add/src/librustc_mir/transform/const_prop.rs#L163) are implemented by using a MIR interpreter that can be customized by implementing the [`Machine`](https://github.com/rust-lang/rust/blob/8e18e26f12b1e8b3e913b15278bf6185f0f61add/src/librustc_mir/interpret/machine.rs#L80) trait. Currently, the CTFE and const-prop machines have quite a bit of common code that is duplicated. It would be nice to reduce the code duplication.

One idea that could be used to reduce the code duplication would be to add a new trait `CommonMachine` and put all the common implementation into it:
```rust
pub trait CommonMachine<'mir, 'tcx>: Sized {

    /// Borrow the current thread's stack.
    fn stack(
        ecx: &'a InterpCx<'mir, 'tcx, Self>,
    ) -> &'a [Frame<'mir, 'tcx, (), ()>];

    /// Mutably borrow the current thread's stack.
    fn stack_mut(
        ecx: &'a mut InterpCx<'mir, 'tcx, Self>,
    ) -> &'a mut Vec<Frame<'mir, 'tcx, (), ()>>;

    // Other methods that require custom implementations for the CTFE and const-prop machines.
}

impl<'mir, 'tcx, T: CommonMachine<'mir, 'tcx>> super::machine::Machine<'mir, 'tcx> for T {

    type MemoryKind = !;
    type PointerTag = ();
    type ExtraFnVal = !;

    type FrameExtra = ();
    type MemoryExtra = ();
    type AllocExtra = ();

    #[inline(always)]
    fn enforce_alignment(_memory_extra: &Self::MemoryExtra) -> bool {
        false
    }

    /// Borrow the current thread's stack.
    fn stack(
        ecx: &'a InterpCx<'mir, 'tcx, Self>,
    ) -> &'a [Frame<'mir, 'tcx, (), ()>] {
        CommonMachine::stack(ecx)
    }

    /// Mutably borrow the current thread's stack.
    fn stack_mut(
        ecx: &'a mut InterpCx<'mir, 'tcx, Self>,
    ) -> &'a mut Vec<Frame<'mir, 'tcx, (), ()>> {
        CommonMachine::stack_mut(ecx)
    }

    // TODO: other methods
}
```

**Comment by RalfJung** [comment]
I propose `ConstMachine` or so as trait name.

I wonder if there is a way to also share the `stack` field between the two? Though given how simple these two getters are it's probably not worth it...

**Comment by samrat** [comment]
Hi, I am interested in working on this issue.

**Comment by vakaras** [comment]
> Hi, I am interested in working on this issue.

@samrat Perfect! If you have any questions, just post them here.

**Comment by samrat** [comment]
@vakaras Since the methods you reference in the issue description are added in #70598, I'm curious-- is there a specific reason to do this refactoring on top of that PR? I was planning on working off of `master` otherwise.

**Comment by vakaras** [comment]
@samrat I would suggest for you to work on top of `master` because it is not clear if that PR will land before you finish your changes.

**Comment by samrat** [comment]
Hi, I don't have things working quite yet. But wanted to ask a few questions and get some feedback on what I have so far. (I have called the common trait ConstMachine as @RalfJung suggested)

This is my understanding of what needs to be done as part of the refactoring: 
- const_prop and const_eval machines will implement ConstMachine. There will be an impl so anything that implements the ConstMachine trait also implements the `interpret::Machine` trait.
- ConstMachine will have default implementation fn's for common code. Otherwise just the signatures. 
- For fn's that has to differ between const_prop and const_eval, the ConstMachine impl's will differ between the two.

Questions:
- Introducing ConstMachine brings in quite a bit of duplication in the form of fn signatures that exist in both interpret::Machine and ConstMachine: https://github.com/samrat/rust/commit/1f1820c1c0d1f22e715cc37679e215e6c51ae68d#diff-86bbb578ec97cf2c4fb01cd5d62c44ccR14 The common code that I can hoist up to default ConstMachine fn's seem to be just one- or two-liners. Is there anyway I can avoid this, or is this something we'll have to live with?

**Comment by vakaras** [comment]
> ConstMachine will have default implementation fn's for common code.

Also, `ConstMachine` can have more concrete types because most of the associated types are instantiated in the same way in both machines.

> Introducing ConstMachine brings in quite a bit of duplication in the form of fn signatures that exist in both interpret::Machine and ConstMachine: samrat@1f1820c#diff-86bbb578ec97cf2c4fb01cd5d62c44ccR14 The common code that I can hoist up to default ConstMachine fn's seem to be just one- or two-liners. Is there anyway I can avoid this, or is this something we'll have to live with?

I have not anticipated that we can achieve only so little reuse here; sorry, I should have checked this before opening the issue. One alternative maybe would be to put all shared code into the `Machine` trait so that we can avoid the duplication caused by adding the additional `ConstMachine` trait. However, I am not sure whether there are any serious drawbacks of this approach. @RalfJung: What is your opinion about this?

> It seems with my change, the interpreter now thinks the `PAGE_SIZE` const is zero. Do you have any advice on how I can go about debugging this?

This looks really weird. I do not see how your changes could have led to this. However, you could use the approaches described [here](https://rustc-dev-guide.rust-lang.org/compiler-debugging.html) for figuring out what is being done to the `PAGE_SIZE` macro. For example, you could try getting a backtrace for the error or look at the logs produced by the compiler (note that to get the logs you need to add `debug-assertions=yes` to your `config.toml`).

**Comment by RalfJung** [comment]
Thanks a lot @samrat for giving this a shot!

> One alternative maybe would be to put all shared code into the Machine trait so that we can avoid the duplication caused by adding the additional ConstMachine trait. 

I don't think we can do that -- that code only works for particular values of these associated consts. IIRC we already have all assoc-type-independent code that can be shared in the `Machine` trait. (Well, except for the `enforce_*` methods. I guess we could move those.)

But I also did not expect this much duplication, this is helping much less than I expected. :/

I wonder if there is a way to use specialization to have less duplication here?

**Comment by RalfJung** [comment]
I think your current patch [can be improved](https://github.com/samrat/rust/commit/1f1820c#r38580078), but even with that, there is a lot of extra duplication of signatures, when avoiding signature duplication was the entire point of this exercise. Maybe it's just not worth it, at least with the techniques Rust currently offers.

**Comment by samrat** [comment]
Thanks @RalfJung and @vakaras. I'll table my efforts on this issue for now then-- do let me know if there are any other ideas to move forward with the issue.

**Comment by RalfJung** [comment]
That's okay, thanks for trying!

**Comment by vakaras** [comment]
@samrat Thank you for trying! And sorry for not checking properly how much benefit we can get here.

@RalfJung Shall we close this issue as undoable or would you like to keep it open?

**Comment by RalfJung** [comment]
I [asked on Zulip if someone has an idea](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Sharing.20code.20across.20trait.20implementations).

**Comment by RalfJung** [comment]
One rather crude but definitely working approach (suggested by @hanna-kruppe) would be to use a macro to share this code... not sure if @oli-obk would like that though.^^

**Comment by hanna-kruppe** [comment]
Let the record show that I am also skeptical whether this is a good idea, despite pointing out the possibility. I'm not very confident since I'm not familiar with any of the code in question, but this seems like one of those cases where LOC reduction is "penny-wise, pound-foolish" -- it does not seem to help prevent future bugs (only trivial logic and compiler-checked signatures are duplicated), while maintenance becomes harder if some previously-common code has to change in one impl but not in the other.

**Comment by RalfJung** [comment]
This issue is actually motivated by the maintenance burden that we currently have when changing the signatures of methods that are shared by both instances of the trait. Specifically, anything to do with pointers typically has a trivial implementation we want to use everywhere in the compiler, but because pointers *might* be tagged, we cannot just share that code. So specifically for this I feel like the macro would help reduce maintenance burden.

But I might be underestimating how annoying it would be to maintain that macro.
