### ISSUE TITLE
libfmt_macros should be renamed to have a rustc_ prefix or moved into librustc_builtin_macros.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#71177]
For historical reasons we have a crate that looks like it would be part of the standard library, but it's really just a parser for the implementation of `format_args!`.

cc @petrochenkov

**Comment by Mark-Simulacrum** [comment]
❤️ I would also deeply appreciate the removal/merge of this crate. It's what I always hit when trying to find the "real" formatting piece of the compiler, and it's essentially never what I want.

**Comment by petrochenkov** [comment]
>or moved into librustc_builtin_macros

Unfortunately, `fmt_macros` is also used from `rustc_trait_selection` due to implementation of the `#[on_unimplemented]` attribute, and it's undesirable to introduce the dependency `rustc_builtin_macros` -> `rustc_trait_selection`.

Possible solutions:
- Keep it as a separate crate, rename to `rustc_parse_format`.
- Merge it into `rustc_parse` if it doesn't add extra dependencies (need to check).
- Turn `#[rustc_on_unimplemented]` into an built-in attribute macro so it does formatting during expansion and trait selection works with some lowered form of it, `#[rustc_on_unimplemented_impl]` or whatever. Then the crate can be merged into `rustc_builtin_macros`.

**Comment by eddyb** [comment]
> * Keep it as a separate crate, rename to `rustc_parse_format`.
> * Merge it into `rustc_parse` if it doesn't add extra dependencies (need to check).

Either of these seem fine with me, anything else would be overkill, IMO.
