### ISSUE TITLE
Convert `search-index.js` into a plain JSON file.

### ISSUE THREAD

**Issue by Dylan-DPC** [rust-lang/rust#71216]
> It might help to convert `search-index.js` into a plain JSON file. I'm pretty sure that `JSON.parse` is significantly faster than trying to compile and execute JavaScript code.
_Originally posted by @ollie27 in https://github.com/rust-lang/rust/issues/56545#issuecomment-614619940_

Opening this issue to gain traction so that someone can work on it (Ready to mentor if possible) 

cc @GuillaumeGomez 

This issue has been assigned to @euclio via [this comment](https://github.com/rust-lang/rust/issues/71216#issuecomment-614900675).

**Comment by euclio** [comment]
I am willing to work on this.

**Comment by Dylan-DPC** [comment]
@euclio go ahead and run `@rustbot claim`. 

if you have any issues feel free to ping me here or anywhere else

**Comment by euclio** [comment]
It's easy enough to generate a JSON file instead of a JavaScript file, but how do we want to load the JSON file? I'm not familiar with how the search works: can we request the JSON via XMLHttpRequest and then call `addSearchOptions` and `initSearch` asynchronously? We could also [embed the JSON in the HTML via a data block](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-type), but that would add the cost of the search index to the initial page load.

**Comment by Dylan-DPC** [comment]
turns out @GuillaumeGomez has some progress on this :/ so maybe you can work on a different issue

**Comment by GuillaumeGomez** [comment]
Arf sorry @euclio, didn't see this issue so I commented on the other one... Even though I did it, it'd be awesome if you took a look at the PR: #71250 :)

**Comment by Alexendoo** [comment]
Closed by #71250
