### ISSUE TITLE
Only use ByVal values in the proc-macro bridge call ABI

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#71379]
The current bridge call ABI uses structs that are too big to be passed in registers. This means that they have to be passed at a fixed stack offset according to the SystemV abi for x86_64. This is harder to implement in a codegen backend that normal values passed either in a register, or passing a pointer to the value in a register. While I have a [WIP PR](https://github.com/bytecodealliance/wasmtime/pull/1559) to implement the correct behavior for passing structs on the stack for Cranelift, it will likely take a while before it is merged given the amount of changes.

For example

https://github.com/rust-lang/rust/blob/25f070d1edf3d54d8933e00eeac95ce55ca8eabb/src/libproc_macro/bridge/client.rs#L390-L393

could become:

```rust
extern "C" fn run( 
     bridge: *mut Bridge<'_>, 
     f: fn(crate::TokenStream) -> crate::TokenStream, 
 ) -> *mut Buffer<u8> { 
```

`*mut Bridge<'_>` and `*mut Buffer<u8>` could be wrapped in a `#[repr(transparent)]` struct.

cc @eddyb (author of the proc-macro bridge)

@rustbot modify labels: +A-cranelift

**Comment by eddyb** [comment]
Ah, I see, this is only a problem because it has to go through the C ABi, when our Rust ABI would just pass them by pointer-in-register.

I'm not too happy with making the bridge even more unsafe than it already is, though :disappointed:.

I think what you want is actually to pass `&mut` instead of `*mut` and use `mem::take` (which, actually, a bunch of the code could switch to `mem::take`, but that's a completely unrelated tangent).

If you want to make a wrapper, it should be like this, for safety reasons:
```rust
#[repr(transparent)]
struct MoveRef<'a, T>(&'a mut T);

impl<'a, T> MoveRef<'a, T> {
    pub fn give(r: &'a mut T) -> Self {
        MoveRef(r)
    }

    pub fn take(self) -> T {
        mem::take(self.r)
    }
}
```

**Comment by est31** [comment]
With the PR mentioned by @bjorn3 merged, can this be closed?

**Comment by bjorn3** [comment]
While this isn't important for cg_clif at the moment, the new style Cranelift backends don't have support for passing structs yet. Avoiding them can also be useful for other backends.

@rustbot modify labels: -A-cranelift

**Comment by bjorn3** [comment]
Not much value in keeping this open.
