### ISSUE TITLE
Dynamically select alignment of a `dyn Trait` local value

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#71695]
Spawned off of #71416

Specifically this comment: https://github.com/rust-lang/rust/issues/71416#issuecomment-618429879

quoted here:

> > Unlike the other unsound features, this is one where we don't even have a plan for how to soundly implement it. Not sure how much I like keeping that around.
> 
> Can't we do something dynamic where we allocate `size + (align - 1)` and align it ourselves?
Also, this has been discussed before, hasn't it?

**Comment by RalfJung** [comment]
@pnkfelix (in https://github.com/rust-lang/rust/issues/71694)
> which actually I guess would have to be done via alloca if we cannot put an upper-bound on align

`size` is also statically unknown here, so yes this needs `alloca`, that is indeed the entire point. ;)

**Comment by spastorino** [comment]
Assigning `P-medium` as [discussed as part of the Prioritization Working Group process](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/I-prioritize.20.2371695.20Dynamically.20select.20alignment.20of.20a.20.60dyn.20T) and removing `I-prioritize`.

Assigning to myself as followup of the rest of the stuff that I've done.

**Comment by ldr709** [comment]
> Can't we do something dynamic where we allocate `size + (align - 1)` and align it ourselves?

Here's a small optimization: pick some default alignment, maybe 16, then allocate `size + max(align - default_align, 0)` bytes. If `align >= default_align` then `align % default_align == 0` because they are both powers of two, so the offset required to align to `align` bytes is `i * default_align` for `i < align / default_align`, which is at most `(align / default_align - 1) * default_align = align - default_align`. If `align < default_align` then the allocation will already be properly aligned, no offset required.
