### ISSUE TITLE
`#[forbid(unused_qualifications)]` is incompatible with all builtin derives

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#71898]
```rust
#![forbid(unused_qualifications)]

#[derive(Clone)]
pub struct S;
```
```
error[E0453]: allow(unused_qualifications) overruled by outer forbid(unused_qualifications)
 --> src/main.rs:3:10
  |
1 | #![forbid(unused_qualifications)]
  |           --------------------- `forbid` level set here
2 | 
3 | #[derive(Clone)]
  |          ^^^^^ overruled by previous forbid
```

All built-in custom derives put `#[allow(unused_qualifications)]` on the generated impl, but the `forbid` level can not be overridden by that.

Custom derives are not able to trigger the `deprecated` lint, despite not attaching `#[allow(deprecated)]`, so maybe the same mechanism should be used for `unused_qualifications`?

**Comment by jonas-schievink** [comment]
Ah, the deprecation lint has this check:

https://github.com/rust-lang/rust/blob/2454a68cfbb63aa7b8e09fe05114d5f98b2f9740/src/librustc_middle/middle/stability.rs#L220-L222

**Comment by samrat** [comment]
If my understanding is correct, `Derive`s(custom and builtin) will always be defined in a crate that will be external to the one using them. And it seems we turn off suggestions for lints originating from external crates: https://github.com/rust-lang/rust/blob/2454a68cfbb63aa7b8e09fe05114d5f98b2f9740/src/librustc_middle/lint.rs#L224

My original approach to this issue was to avoid adding the `#[allow(unused_qualifications)]` to the impl and add a `in_derive_expansion` check in https://github.com/rust-lang/rust/blob/2454a68cfbb63aa7b8e09fe05114d5f98b2f9740/src/librustc_resolve/late.rs#L1844 but I couldn't figure out a case where the `in_derive_expansion` check makes a difference in the suggestion displayed(I did verify that the lint is captured in the lint_buffer in the case the unnecessary qualification is in an external crate, just not displayed).

Any thoughts on this approach, and suggestions on how I can go about testing this change?

**Comment by Alexendoo** [comment]
Triage: Hi, are you still working on this issue @samrat?

**Comment by samrat** [comment]
Hi @Alexendoo, I don't think I'll be able to devote sufficient time to work on this issue anytime soon.

**Comment by Alexendoo** [comment]
No problem

@rustbot release-assignment

**Comment by mdholloway** [comment]
I think @samrat had the right solution to this one.  I'd be happy to pick it up and drag it over the finish line.

@rustbot claim
