### ISSUE TITLE
Are we calling macOS "open" with a wrong argument type?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#71915]
In this line, we are calling `open64` (which on macOS is `open` renamed):
https://github.com/rust-lang/rust/blob/de27cd7649e4182c63c770d18a561bda0d88cfc6/src/libstd/sys/unix/fs.rs#L706
As third argument, we are passing something of type `c_int`. However, according to [this document](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/open.2.html), the type should be `mode_t` instead, and on macOS these types do not seem identical -- the libc crate has
```
src/unix/bsd/apple/mod.rs
10:pub type mode_t = u16;
```
Seems like we are using the wrong argument type here?
(`open` is variadic so the compiler cannot check this. But Miri complained when I started to check argument sizes.)

**Comment by tmiasko** [comment]
The types are correct. In C, the default argument promotions are performed on trailing arguments.

**Comment by RalfJung** [comment]
>  In C, the default argument promotions are performed on trailing arguments.

I don't know what that means, but the man page explicitly says `mode_t` -- so is the man page wrong then?

**Comment by hanna-kruppe** [comment]
The third argument is passed as variadic argument, so the man page is *not* saying the function has signature `open(const char*, int, mode_t)`, just that C programmers should use `mode_t` for representing the mode if one is needed -- presumably not just w.r.t. `open` but more generally in all APIs. But at ABI level, the third argument is passed as `int` because of the C rule that @tmiasko alludes to.

**Comment by RalfJung** [comment]
So would a comment like this be appropriate? https://github.com/rust-lang/rust/pull/71921
