### ISSUE TITLE
Type mismatch mentioning trait as type

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#72217]
```rust
trait DynEq {}

impl<'a> PartialEq for &'a (dyn DynEq + 'static) {
    fn eq(&self, _other: &Self) -> bool {
        true
    }
}

impl Eq for &dyn DynEq {}
```
Causes the following error:
```
error[E0308]: mismatched types
 --> src/lib.rs:9:6
  |
9 | impl Eq for &dyn DynEq {}
  |      ^^ lifetime mismatch
  |
  = note: expected type `std::cmp::PartialEq`
             found type `std::cmp::PartialEq`
note: the lifetime `'_` as defined on the impl at 9:13...
 --> src/lib.rs:9:13
  |
9 | impl Eq for &dyn DynEq {}
  |             ^
  = note: ...does not necessarily outlive the static lifetime
```
This is somewhat confusing, especially since `std::cmp::PartialEq` is not a type.

This issue has been assigned to @ayrtonm via [this comment](https://github.com/rust-lang/rust/issues/72217#issuecomment-663166876).

**Comment by rodrimati1992** [comment]
This looks similar to what I reported in https://github.com/rust-lang/rust/issues/59865

**Comment by estebank** [comment]
Here we don't account for anything other than type mismatches

https://github.com/rust-lang/rust/blob/2002ebacfbca288830a3c308ddc8189705c608fe/src/librustc_infer/infer/error_reporting/mod.rs#L1404-L1433

which means that later we use the generic `"type"` prefix

https://github.com/rust-lang/rust/blob/2002ebacfbca288830a3c308ddc8189705c608fe/src/librustc_infer/infer/error_reporting/mod.rs#L1447-L1448

We need to account for `ValuePairs::TraitRefs` in the first snippet and ferry the prefix strings from there to the later (instead of what we do now).

**Comment by ayrtonm** [comment]
I'd like to work on this
@rustbot claim

**Comment by estebank** [comment]
@ayrtonm do not hesitate to reach out if you need help!

**Comment by ayrtonm** [comment]
Do we need to get the correct prefix strings from the contents of `ValuePairs::TraitRefs` or are they just `"trait"`?

**Comment by estebank** [comment]
I believe they can be just "trait".

**Comment by ayrtonm** [comment]
#74698
