### ISSUE TITLE
Remove `Session::crate_types_opt`?

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#72427]
See https://github.com/rust-lang/rust/pull/72256#discussion_r428775106 for context.

There's only one place in the compiler that can't call `Session::crate_types` because that field is sometimes uninitialized.

https://github.com/rust-lang/rust/blob/31add7e60709445617ab54a69f6f21cfcb2e3122/src/librustc_codegen_llvm/context.rs#L100-L103

Perhaps this indicates that we want to force initialization of `crate_types` somewhere?

**Comment by petrochenkov** [comment]
`all_outputs_are_pic_executables` is used during creation of LLVM `TargetMachine`.
Sometimes we create an "informational" target machine to query supported LLVM target features, for example.
We don't need to force initialize `crate_types` in this case because the queried information doesn't depend on them, but we also can't do it in some cases because initialization of `crate_types` requires running parsing and expansion, which would create cycles because the LLVM target feature list is an input for expansion.

**Comment by Mark-Simulacrum** [comment]
Hm, it sounds like maybe we should not attempt a read of the crate types of we're creating it for that informational use case?

I presume the crate type can influence LLVM in some way, right?

**Comment by petrochenkov** [comment]
Ha, the `PositionIndependentExecutable` parameter in `LLVMRustCreateTargetMachine` is not even used.
We need to enable more warnings in C++ code.

So it should be possible to remove `crate_types_opt` from `all_outputs_are_pic_executables`, I'll prepare a PR now.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/72435.
