### ISSUE TITLE
Tracking issue for `#![feature(const_float_bits_conv)]`

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#72447]
Tracking issue for the `#![feature(const_float_bits_conv)]` feature gate, which makes the following methods on `f32` and `f64` `const fn`:
- formerly `#![feature(float_bits_conv)]`
  - `to_bits`
  - `from_bits`
- formerly `#![feature(float_to_from_bytes)]`
  - `to_bytes_be`
  - `to_bytes_le`
  - `to_bytes_ne`
  - `from_bytes_be`
  - `from_bytes_le`
  - `from_bytes_ne`

These require `transmute` within a `const fn` to stabilize, and–unlike the recently stabilized `#![feature(const_int_conversion)]`–do not have a const-stable alternate implementation. Nevertheless, these may be useful for nightly users.

Stabilization is blocked on https://github.com/rust-lang/rust/issues/57241.

**Comment by lebensterben** [comment]
Is there anyway to hard-code this without nightly?
I've a real world use case, I need to define
`pub const NA_REAL: f64 = f64::from_le_bytes([0xa2, 0x07, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x7f]);`
which is the `NA` (not `NaN`) value used in R.

**Comment by ecstatic-morse** [comment]
`transmute` is stable in constants and statics (but not in `const fn`) as of 1.46.

**Comment by lebensterben** [comment]
```rust
pub const NA_REAL: f64 = unsafe {
    std::mem::transmute(u64::from_le_bytes([
        0xa2, 0x07, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x7f,
    ]))
};
```
This works for me now.

**Comment by bstrie** [comment]
> Stabilization is blocked on #57241.

Does that issue need to be a blocker for this? The functions in question aren't doing arithmetic on floats, they're just casting bit representations. AIUI while float arithmetic might be nonportable, bit representations are well-specified, yes?

**Comment by bstrie** [comment]
Actually, I take that back after looking at https://github.com/rust-lang/rust/issues/73288 . `from_bits(foo).to_bits()` isn't even guaranteed to round-trip properly...

**Comment by thomcc** [comment]
Is there any reason `from_bits` couldn't be stabilized on its own (without `to_bits`)? I think `to_bits` is the problematic one (or at least, it's the one with open questions).

It might not seem useful to provide *just* `from_bits` (and not `to_bits`) to const fn, but here are two use cases:

1. Parsing floats at compile time, either from `env!`/`option_env!` or user provided string literals (e.g. you could imagine a version of that hex float crate that use const fn instead of proc macros).
2. A software floating point implementation that works in `const fn` (admittedly, as a way to hack around the current lack of support).

The 2nd is what I was poking around with, when I realized that I can't actually turn the result into a user-friendly `f32`/`f64` (instead I have to give them a `u32`/`u64`, which needs to be `from_bits`ed outside of const).

**Comment by tspiteri** [comment]
Now that transmute is const since 1.56.0, not stabilizing these methods is only an invitation to use unsafe code instead of these safe methods.

**Comment by workingjubilee** [comment]
per @burrbull in https://github.com/rust-lang/rust/issues/57241#issuecomment-909858133
"`const fn transmute` is already stabilized"

This allows routing around these using `unsafe` const code. I think that the question now is whether we want to stabilize the safe methods or to instead fix the bugs that can cause unconst behavior (and thus, continue to make people `unsafe`ly assert that they believe the result will be const or, in effect, that it will not cause problems) and then stabilize them.

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/rfcs/pull/3514 having been accepted, I think this is unblocked. I am working on stabilizing `const_fn_floating_point_arithmetic`; anyone reading this should feel free to pick up stabilizing `const_float_bits_conv`. :)  It'd be nice if they ended up both being part of the same release, though it's also not a big deal if they end up stretched out over multiple releases.
