### ISSUE TITLE
"automatic va_arg instruction only works on Darwin" when running AArch64 tests

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#72579]
When running the rustc test suite on AArch64, the `ui/abi/variadic-ffi.rs` test fails due to the following LLVM assertion:

```
rustc: /checkout/src/llvm-project/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:5726: llvm::SDValue llvm::AArch64TargetLowering::LowerVAARG(llvm::SDValue, llvm::SelectionDAG&) const: Assertion `Subtarget->isTargetDarwin() && "automatic va_arg instruction only works on Darwin"' failed.
```

**Comment by jhass** [comment]
Here's how Clang implements `va_arg` on AArch64: https://github.com/llvm/llvm-project/blob/a574edbba2b24fcfb733aa2d82308131f5b7d2d6/clang/lib/CodeGen/TargetInfo.cpp#L5677-L5921

I think it's best to just disable `va_arg` on AArch64 (and quite possibly more targets)  until LLVM decides to properly implement it. Don't get your hopes  up on that though, when asked I asked in IRC  why clang would do this  rather than fixing `va_arg` on AArch64, I got comments in the vein of:

> \<jhass> it almost feels like va_arg is just broken on aarch64 and rather than fixing that somebody went through the effort of reimplemnting it like this for clang
 \<nbjoerg> no
 \<nbjoerg> the IR stuff is really only appropiate and meant for the easy cases
 \<jhass> a bunch of i32's is an easy case, no? I can't get that to work
 \<nbjoerg> I don't know the aarch64 ABI from memory
 \<nbjoerg> in general, the IR is only really applicable if you have a nice stack based calling convention
\<jhass> well, the call instruction seems to be implemented fine for the aarch64 variadic calling convention?
\<jhass> why is it inappropriate for the va_arg instruction to handle it as well?
\<jhass> why does it exist then?
\<nbjoerg> jhass: legacy
\<nbjoerg> jhass: noone bothered enough to remove it

**Comment by pietroalbini** [comment]
cc @Stammark @JamieCunliffe @vigoux @joaopaulocarreiro @raw-bin, this is one of the tests that are failing on AArch64.

**Comment by pietroalbini** [comment]
This was fixed!
