### ISSUE TITLE
Do not suggest importing hash_map::HashMap or btree_map::BTreeMap

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#72642]
```rust
struct S {
    m: HashMap<String, ()>,
}
```

```console
error[E0412]: cannot find type `HashMap` in this scope
 --> src/main.rs:2:8
  |
2 |     m: HashMap<String, ()>,
  |        ^^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
1 | use std::collections::HashMap;
  |
1 | use std::collections::hash_map::HashMap;
  |
```

The `std::collections::hash_map::HashMap` suggestion here is just noise, it's (almost?) never what we actually want the person to import.

This issue has been assigned to @ayushmishra2005 via [this comment](https://github.com/rust-lang/rust/issues/72642#issuecomment-634702867).

**Comment by davidtwco** [comment]
@ayushmishra2005 responding to [your comment](https://github.com/rust-lang/rust/pull/72656#issuecomment-636906348) here rather than on the PR - here are some rough pointers of what I'd look into (not having dug much into this myself, I can't say exactly what will be the solution):

So, let's start at the beginning - the suggestion that we see comes from this line:

https://github.com/rust-lang/rust/blob/0aa6751c19d3ba80df5b0b02c00bf44e13c97e80/src/librustc_resolve/diagnostics.rs#L1498

You can find that yourself using grep or just search on GitHub for the wording used in the suggestion (or some subset of it - as you can see, a bunch of this particular message is format strings). It looks like it gets the suggestions to print from a `path_strings` variable, which itself comes from the `candidates` argument.

That's in a function called `show_candidates`, searching for that - it's used once, here:

https://github.com/rust-lang/rust/blob/f6072cab136beea206b7cfe79f8d10fccf5af591/src/librustc_resolve/lib.rs#L2579-L2591

We can see that the candidates come from deconstructing a `UseError` struct. Fortunately, searching for `UseError` turns up only one location where it is constructed:

https://github.com/rust-lang/rust/blob/91fb72a8a9f53de2bcc5638c1358fcb552dba8ce/src/librustc_resolve/late.rs#L1621-L1629

Going even further back, we see that `candidates` is the result of calling `smart_resolve_report_errors` ([defined here](https://github.com/rust-lang/rust/blob/f93bb2a50b37bc8bafe4d960e2afd839eaa854ed/src/librustc_resolve/late/diagnostics.rs#L93)) - looking through that function, we can see that `candidates` is produced by calling `lookup_import_candidates` and then filtering the results (making sure that the suggestion isn't what we think the name already is and know to be incorrect):

https://github.com/rust-lang/rust/blob/f93bb2a50b37bc8bafe4d960e2afd839eaa854ed/src/librustc_resolve/late/diagnostics.rs#L213-L223

`lookup_import_candidates` ([defined here](https://github.com/rust-lang/rust/blob/0aa6751c19d3ba80df5b0b02c00bf44e13c97e80/src/librustc_resolve/diagnostics.rs#L721)) basically just calls `lookup_import_candidates_from_module` ([defined here](https://github.com/rust-lang/rust/blob/0aa6751c19d3ba80df5b0b02c00bf44e13c97e80/src/librustc_resolve/diagnostics.rs#L628)).

A rough read of this function suggests that [it starts at some arbitrary starting module](https://github.com/rust-lang/rust/blob/0aa6751c19d3ba80df5b0b02c00bf44e13c97e80/src/librustc_resolve/diagnostics.rs#L642), looks over every name defined in that module [for names that match what the user wrote](https://github.com/rust-lang/rust/blob/0aa6751c19d3ba80df5b0b02c00bf44e13c97e80/src/librustc_resolve/diagnostics.rs#L658), and if the current name is itself a module, it [adds that to the list of modules to search](https://github.com/rust-lang/rust/blob/0aa6751c19d3ba80df5b0b02c00bf44e13c97e80/src/librustc_resolve/diagnostics.rs#L704).

I hope that you can see how this could start with something like `std`; and then look at `std::collections`, and `std::fmt`; and then `std::collections::HashMap` - and that matches the name that the user wrote, so it adds it as as candidate - and `std::collections::HashSet`, and so on; and then eventually `std::collections::hash_map`; before finding `std::collections::hash_map::HashMap` - which also matches the name that the user wrote! So we've ended up with two suggestions - it just also happens that they are suggesting the same thing - `std::collections::HashMap` is a re-export of `std::collections::hash_map::HashMap`.

I suspect that we could determine that both of these items are actually the same by comparing their `DefId`s - which this code finds just before adding the candidate:

https://github.com/rust-lang/rust/blob/0aa6751c19d3ba80df5b0b02c00bf44e13c97e80/src/librustc_resolve/diagnostics.rs#L679-L683

So what I'd probably end up doing is experimenting with how expensive it would be to iterate over each of the candidates before adding a new candidate (we know an error occurs at this point, so we've got some room to impact perf), and checking for duplicate suggestions; or maybe accumulating suggestions into a `HashMap` before converting to a `Vec` (using the `DefId` as a key, only replacing the value if the path would be shorter?).

**Comment by ayushmishra2005** [comment]
@davidtwco Great Thanks. Let me work on it
