### ISSUE TITLE
Rust-docs missing, can’t install on FreeBSD12.1 in Rust 1.43.1

### ISSUE THREAD

**Issue by kaifoon** [rust-lang/rust#72792]
Rust-docs missing, can’t install on FreeBSD12.1 in Rust `1.43.1.
The error is as follows：

`  ✘ ⚡ root@saraunix  ~  rustup update stable
info: syncing channel updates for 'stable-x86_64-unknown-freebsd'

  stable-x86_64-unknown-freebsd unchanged - rustc 1.43.1 (8d69840ab 2020-05-04)

info: checking for self-updates
 ⚡ root@saraunix  ~  rustup component add rust-docs
error: toolchain 'stable-x86_64-unknown-freebsd' does not contain component 'rust-docs' for target 'x86_64-unknown-freebsd'`

Excuse me, can someone help me explain why this is happening？

**Comment by Mark-Simulacrum** [comment]
Yep, this is essentially because we don't have CI time to build docs for all of the platforms. See https://github.com/rust-lang/rust/issues/69525 which I'm closing this in favor of -- I think that's the "canonical" issue even if that's not super clear based on it's content, and I think there was another one that I can't find right now...
