### ISSUE TITLE
AddressSanitizer and LeakSanitizer should be enabled together like C/C++ projects

### ISSUE THREAD

**Issue by inferno-chromium** [rust-lang/rust#73294]
Currently ASan and LSan in Rust are mutually exclusive [https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/sanitizer.html], this is not how it works in other places. In C/C++ projects, we always enable them in the same build and actually address enables both ASan and LSan. Rust compiler should match this, this will make it easy to enable LSan in several Rust OSS projects in OSS-Fuzz (e.g. Servo, Wasmtime, etc).

**Comment by inferno-chromium** [comment]
@kcc fyi!

**Comment by mati865** [comment]
Cc @tmiasko

**Comment by tmiasko** [comment]
-Zsanitizer=address has the same behaviour with respect to memory leak
detection as -fsanitize=address in clang. Enabled by default on Linux, and
through detect_leaks=1 on macOS.

The use of multiple -Zsanitizer flags at the same is currently impossible and
this is what docs were referring to (they have been since changed, since indeed
the meaning of "only a single sanitizer at a time" was ambiguous given that
AddressSanitizer incorporates LeakSanitizer).

**Comment by inferno-chromium** [comment]
Thanks for clarifying that and fixing docs, closing it then.
