### ISSUE TITLE
thread '<unnamed>' panicked at 'index out of bounds: the len is 3 but the index is 3'

### ISSUE THREAD

**Issue by kematy** [rust-lang/rust#73397]
thread '<unnamed>' panicked at 'index out of bounds: the len is 3 but the index is 3', dll_qin.rs:14:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5

when I call r_span function with FFI in ruby,it shows up these messages.

here is the code:
#![crate_type="cdylib"]
//use std::any::Any;

#[no_mangle]
extern "C" fn r_span(ary:&[u32],n:usize)->f64
{

	let mut sum3:f64=0.0;
	let mut sum:f64=0.0;
	let mut i:usize=0;
	while i<n
    {

    	  sum3+=(ary[i] as f64).powf(3.0);
          sum+=ary[i] as f64;
          i+=1;
    }    
    let tmp:f64=sum3/sum;
   tmp.sqrt().round()
}	

#[no_mangle]
extern "C" fn root_cubic_simple(b:f64,c:f64,d:f64)->f64
{

	
	let px:f64=-(b.powf(3.0))/27.0-d/2.0+b*c/6.0;
	let deta:f64=px.powf(2.0)+((3.0*c-b.powf(2.0))/9.0).powf(3.0);
	if deta < 0.0 && px < 0.0
	{
	 	let alpha:f64=(-(-deta).sqrt()/px).atan();
		let x1:f64=2.0*(b.powf(2.0)-3.0*c).sqrt()/3.0*((5.0*std::f64::consts::PI+alpha)/3.0).cos()-b/3.0;
		
		return x1;
	 }   
	else if deta < 0.0 && px > 0.0
	{
		let alpha:f64=((-deta).sqrt()/px).atan();
		let x1:f64=2.0*(b.powf(2.0)-3.0*c).sqrt()/3.0*((6.0*std::f64::consts::PI+alpha)/3.0).cos()-b/3.0;
		return x1;
	}
	else
	{
		let p1:f64=px+deta.sqrt();
		let p2:f64=px-deta.sqrt();
		let x1:f64=p1.powf(1.0/3.0)+p2.powf(1.0/3.0)-b/3.0;
		
		return x1;
	}	
	
}

**Comment by ratijas** [comment]
Please, fix your code formatting, it is hard to read as it is. Also, `root_cubic_simple` has nothing to do with it, it seems.

> the len is 3 but the index is 3

That is pretty much expected, since array indices are zero-based. Double-check how do you pass `n:usize` parameter in you call.

Also it is suspicious that you receive _slice_ in FFI. slices are fat pointers of (pointer to a data, length). What you probably means to write is `ary: * constu32, n:usize`, and then construct a slice via [`slice::from_raw_parts`](https://doc.rust-lang.org/stable/std/slice/fn.from_raw_parts.html).

Hope that helps!

**Comment by jonas-schievink** [comment]
This is not a bug in Rust. Please ask troubleshooting questions about your own code on https://users.rust-lang.org/, not in this issue tracker.
