### ISSUE TITLE
"died due to signal 9" in collectionsbenches on arm-android

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#73535]
Recently enabled benchmarks (#73142) frequently fail on arm-android builder on GitHub Actions:

```console
test slice::rotate_medium_half_plus_one ... ok
test slice::rotate_tiny_half ... ok
test slice::rotate_tiny_half_plus_one ... ok
died due to signal 9
error: test failed, to rerun pass '-p alloc --bench collectionsbenches'
```

The issue looks similar to previously reported #55861.

**Comment by ehuss** [comment]
I'm sorry, I noticed this during my local testing, but figured it was due to my hardware which had a very high parallel count, and it seemed to go away when I lowered the parallel test threads. 

I also had great difficulty running these tests at -j32 on android as well:

```
ui/iterators/iter-count-overflow-debug.rs
ui/iterators/iter-count-overflow-ndebug.rs
ui/iterators/iter-position-overflow-debug.rs
ui/iterators/iter-position-overflow-ndebug.rs
ui/iterators/skip-count-overflow.rs
ui/mpsc_stress.rs
```

They either seemed to hang, or took a very long time to finish.
 
Would people prefer to just disable the bench tests on android, or should we do more investigation?

**Comment by pietroalbini** [comment]
*Again?* cc @badboy

**Comment by jonas-schievink** [comment]
Looks like https://github.com/rust-lang/rust/pull/71123 didn't fix the "died due to signal 11" errors either :(

**Comment by badboy** [comment]
hm, yeah if these keep coming back I guess that's reason enough for me to allocate time for it again.

**Comment by pietroalbini** [comment]
@nellshamrell will open a PR disabling collectionsbench on Android for the time being.
