### ISSUE TITLE
Build error: Missing documentation for `owning_ref` module

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#73798]
I tried this build command: `./x.py test --stage 1 src/librustdoc`

I expect to see the build complete happily.

Instead, there are a warnings degraded to errors:

```rust
error: missing documentation for a module
  --> src/librustc_data_structures/lib.rs:71:1
   |
71 | pub mod owning_ref;
   | ^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D missing-docs` implied by `-D warnings`

error: aborting due to previous error
```

I added this option `--warnings warn` to the build command above and run it again:

```rust
warning: missing documentation for a module
  --> src/librustc_data_structures/lib.rs:71:1
   |
71 | pub mod owning_ref;
   | ^^^^^^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> src/librustc_data_structures/owning_ref/mod.rs:1:9
   |
1  | #![warn(missing_docs)]
   |         ^^^^^^^^^^^^
```

The commit I used to build is: 394e1b40d264aa6928811919c1124fa248e7d802

**Comment by ehuss** [comment]
This is quite strange, I can't seem to reproduce it. 

The error itself seems very unusual, since the `owning_ref` module definitely has a [module doc](https://github.com/rust-lang/rust/blob/9bdd2db3a60176012f4dc240eea02d615cc60061/src/librustc_data_structures/owning_ref/mod.rs#L3-L245).

Does it continue to happen after `x.py clean`?

**Comment by lzutao** [comment]
It might be some of my changes in rustdoc changed its behavior.
Kinda surprised because the librustdoc test suite doesn't catch this.

I leave this open until I can confirm my hypothesis.

**Comment by lzutao** [comment]
That's totally my fault.
