### ISSUE TITLE
Failed to clone the index on CI

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#73992]
We started seeing a lot of failures cloning the crates.io index across the rustc CI.

* https://github.com/rust-lang/rust/pull/73650
  * [Failure 1 (Azure)](https://dev.azure.com/rust-lang/rust/_build/results?buildId=33572&view=logs&jobId=aac1e68a-9baa-54d2-b80b-75ce793a8506&j=aac1e68a-9baa-54d2-b80b-75ce793a8506&t=c6894453-ba55-5ebb-334b-3b9eaf7d0823)
  * [Failure 2 (GHA)](https://github.com/rust-lang-ci/rust/runs/834179855#step:22:176)
* https://github.com/rust-lang/rust/pull/73845
  * [Failure 1 (GHA)](https://github.com/rust-lang-ci/rust/runs/834191075#step:22:170)

**Comment by RalfJung** [comment]
More failures:
* https://github.com/rust-lang/rust/pull/73693#issuecomment-653506007
* https://github.com/rust-lang/rust/pull/73925#issuecomment-653510408

**Comment by oliviacrain** [comment]
Looks like this is still happening as of Oct 19 - #76688 has the same failure to clone the crates.io index on an 1686 platform.

[Logs link for that run](https://github.com/rust-lang-ci/rust/runs/1272423728#step:24:63)

This is a bit of a weird one- it seems like this issue is happening despite bootstrapping using the cargo beta from 2020-10-16, which includes the fix for this issue (rust-lang/cargo#8517).

**Comment by Enselic** [comment]
Triage: If this was still a problem I think this issue would not have gone silent? Closing as obsolete.
