### ISSUE TITLE
Hygiene Example Typo

### ISSUE THREAD

**Issue by BeniReydman** [rust-lang/rust#74118]
### What needs to be fixed?
In the Rust book under Hygiene section for the following code:
```
macro_rules! foo {
    ($v:ident) => (let $v = 3);
}

fn main() {
    foo!(x);
    println!("{}", x);
}
```
There is missing a semi-colon at the line `let $v = 3` which doesn't compile in Rust Playground

### Page(s) Affected
https://doc.rust-lang.org/1.7.0/book/macros.html#hygiene

**Comment by ehuss** [comment]
That link is from the 1.7 docs, which is more than 4 years old.  I believe that code was valid at the time, but was changed in #34660.  

The corrected, old documentation can be found at: https://doc.rust-lang.org/1.30.0/book/first-edition/macros.html#hygiene
Hygiene was removed from the new edition (https://doc.rust-lang.org/book/ch19-06-macros.html).  I would guess that is because it is an advanced topic, which is covered in [the reference](https://doc.rust-lang.org/reference/macros-by-example.html#hygiene).

cc #44687, where there really should be a version selector, and https://internals.rust-lang.org/t/adding-outdated-notices-to-archived-versions-of-documentation/12281 for the request for a bold disclaimer to indicate you are looking at outdated documentation.
