### ISSUE TITLE
On linux, __rust_probestack shouldn't be called on smallish stack allocations

### ISSUE THREAD

**Issue by KyleSiefring** [rust-lang/rust#74405]
On linux (x86_64), had a stack allocation that was "only" 8*4096 bytes causing __rust_probestack to be called. From what I understand from this, https://github.com/rust-lang/rust/pull/43072, linux only needs to have the stack probed for much larger sizes.

Compiler version: Tested on 1.44.0, but a cursory glance in perf still shows __rust_probestack.

**Comment by nagisa** [comment]
`__rust_probestack` being called for anything more than 1 typical page on the platform (4k on Linux) is expected. That's because when the guard page _is_ 1 page large (true at least for non-main threads), then not probing could allow functions to jump over the guard.

All the linked PR does is not manually allocating said guard page on the main thread. I’m not sure what the relation between it and probing functionality is, other than the fact that both involve stacks and their guard pages.

**Comment by cuviper** [comment]
With LLVM 11, I hope to switch to `"probe-stack"="inline-asm"`, which avoids any call and supports more targets. That code uses a loop for large stack allocations, but also does unroll to a series of probes for small cases.

**Comment by vtjnash** [comment]
Fixed?

**Comment by nagisa** [comment]
We still probe at 4k increments, but I don't think this issue is otherwise actionable given the reasoning outlined above.

Thank you, Kyle, for the report and Jameson for a reminder.
