### ISSUE TITLE
Rust 1.45.0 aarch64-apple-ios generates multiple messages: "'+cyclone' is not a recognized feature for this target (ignoring feature)"

### ISSUE THREAD

**Issue by trsoluti** [rust-lang/rust#74427]
I tried this code:

```
cargo new cyclone_test
cd cyclone_test
cargo build --target=aarch64-apple-ios
```

I expected to see this happen: *explanation*
no errors or warnings
Instead, this happened: *explanation*
multiple copies of
```
'+cyclone' is not a recognized feature for this target (ignoring feature)
```
### Meta

`rustc --version --verbose`:
```
rustc 1.45.0 (5c1f21c3b 2020-07-13)
binary: rustc
commit-hash: 5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2
commit-date: 2020-07-13
host: x86_64-apple-darwin
release: 1.45.0
LLVM version: 10.0
```

<details><summary>Backtrace</summary>
<p>

```
(not applicable)
```

</p>
</details>

**Comment by lzutao** [comment]
"cyclone" has been renamed to "apple-a7" in #73086 .

**Comment by lzutao** [comment]
ping @Mark-Simulacrum

**Comment by trevyn** [comment]
This is fixed in beta and nightly via #73086. Should probably be nominated for backport to a point release, if there is one.

**Comment by francesca64** [comment]
Is this fixed in 1.45.1?

**Comment by Mark-Simulacrum** [comment]
I am confused how it was fixed in beta and nightly by #73086, as it seems that was not backported to beta.

@lzutao -- please ping the whole release team, not just me, so that hopefully someone sees things like this. It would also be helpful to include some mention about *why* you're pinging rather than just doing so.

This was not fixed in 1.45.1. I am not sure that I am inclined to backport it into stable at all, though, presuming that it is merely an annoyance rather than an error?

**Comment by francesca64** [comment]
@Mark-Simulacrum 

> presuming that it is merely an annoyance rather than an error?

https://github.com/rust-lang/rust/pull/73086#issue-429824619 suggests that it "probably also created incorrectly optimized artifacts", though things indeed still build fine. That said, this does result in *a lot* of messages, i.e. in a largish project I'm seeing it 719 times, which makes it difficult to read any other build output. So at the very least, it's a substantial user experience regression.
<img width="746" alt="Screen Shot 2020-07-30 at 15 32 43" src="https://user-images.githubusercontent.com/2096580/88981502-f4047f80-d27a-11ea-8d64-a8446e8b613c.png">

**Comment by JohnTitor** [comment]
Removing `I-prioritize` as this is waiting on backport (but it seems we missed it on 1.45.2?) and already fixed in beta and nightly ([related discussion on the wg-prioritization](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2374427.20Rust.201.2E45.2E0.20aarch64-apple-ios.20generates.E2.80.A6)).

**Comment by spastorino** [comment]
@Mark-Simulacrum I think we should close this issue given that we decided to not backport to stable, right?.

**Comment by Mark-Simulacrum** [comment]
Given that it's fixed on beta/nightly that does indeed seem reasonable.
