### ISSUE TITLE
q: why doc on local machine isn't served by an HTTP server?

### ISSUE THREAD

**Issue by qlcom** [rust-lang/rust#74473]
we are viewing it on a web browser. but it isn't served by an HTTP server. I don't understand this.

**Comment by VictorKoenders** [comment]
Running `cargo doc` actually creates a completely static HTML file structure. If you look at the URL of your browser, you'll see something like `file:///<project path>/target/doc/<project name>/index.html`.
If you were to browse to `target/doc/` in your file explorer, you'll see a dozen or so HTML files generated.
Your browser simply serves these files from the filesystem, instead of from a HTTP server

**Comment by qlcom** [comment]
> Running `cargo doc` actually creates a completely static HTML file structure. If you look at the URL of your browser, you'll see something like `file:///<project path>/target/doc/<project name>/index.html`.
> If you were to browse to `target/doc/` in your file explorer, you'll see a dozen or so HTML files generated.
> Your browser simply serves these files from the filesystem, instead of from a HTTP server

thanks, i know this.

Why it doesn't use an HTTP server. features like theme aren't persistent in file://

**Comment by qlcom** [comment]
Also what about Rust's own doc?

**Comment by VictorKoenders** [comment]
There seems to be a (stalled) discussion on being able to run rustdoc in a server: https://github.com/rust-lang/cargo/issues/4966

**Comment by qlcom** [comment]
> There seems to be a (stalled) discussion on being able to run rustdoc in a server: [rust-lang/cargo#4966](https://github.com/rust-lang/cargo/issues/4966)

this doesn't make any sense.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this in favor of https://github.com/rust-lang/cargo/issues/4966, as this support is super unlikely to land in rustdoc IMO because including a full HTTP server in rustdoc seems like a significant expansion of scope, one that we're not prepared for at this time. Inclusion of an HTTP server in Cargo is similarly a big feature, but there at least it's more in scope as Cargo already talks to network and such.

If you're interested in discussing *why* this is the case, starting a thread on internals.rust-lang.org is the way to go.
