### ISSUE TITLE
Confusing error message for `Foo{ bar @ .. }` pattern

### ISSUE THREAD

**Issue by rodrimati1992** [rust-lang/rust#74701]
This erroneous code:
```rust
let std::ops::Range{ bar @ .. } = 0..0;
```

Produces this error message
```
error: expected `,`
 --> src/main.rs:2:26
  |
2 |     let std::ops::Range{ bar @ .. } = 0..0;
  |                          ^^^
```

It would be better if instead it produced an error message like this:
```
error: `bar @` is not allowed in a struct
 --> src/main.rs:2:26
  |
2 |     let std::ops::Range{ bar @ .. } = 0..0;
  |                          ^^^
  = help: remove this and bind each struct field independently
help: if you don't need to use the contents of bar, discard the struct's remaining fields
   |
11 |     let std::ops::Range{ .. } = 0..0;
   |                          ^^
```

### Meta

Tried the code in these Rust versions and they all produced the same error message:

- 1.37.0 stable

- 1.45.0 stable

- 1.46.0-beta.1 (2020-07-15 e51b714db8ff82ac38ea)

- 1.47.0-nightly (2020-07-22 bbebe7351fcd29af1eb9)

**Comment by Nadrieril** [comment]
This shouldn't be too hard. This comes from the parser, specifically the code that parses a pattern, which is one of [these](https://github.com/rust-lang/rust/blob/1d726a2be0b9a762c5a15154e65f925994a58445/compiler/rustc_parse/src/parser/pat.rs#L113) `parse_pat_*` functions. Somewhere there is the code to parse a struct pattern. I assume the error above happens when it successfully parses a struct field and then expects a comma or closing brace. To fix it you'd have to check for `@ ..` and report a better error message.
