### ISSUE TITLE
Creating a raw reference/pointer to an extern never value claims following code is unreachable

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#74840]
I tried this code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3a284533ec584206e289695de0f08df1)):

```rust
#![feature(never_type)]
#![feature(raw_ref_macros)]
#![feature(raw_ref_op)]

extern {
    static FOO: !;
}

fn main() {
    dbg!(unsafe { core::ptr::raw_const!(FOO) });
    dbg!(unsafe { &raw const FOO });
}
```

I expected to see this happen: just a linker failure because `FOO` doesn't exist.

Instead, this happened: before the linker failure, `rustc` complained that code was unreachable.

```
warning: unreachable expression
  --> src/main.rs:10:19
   |
10 |     dbg!(unsafe { core::ptr::raw_const!(FOO) });
   |                   ^^^^^^^^^^^^^^^^^^^^^^---^
   |                   |                     |
   |                   |                     any code following this expression is unreachable
   |                   unreachable expression

warning: unreachable expression
  --> src/main.rs:11:19
   |
11 |     dbg!(unsafe { &raw const FOO });
   |                   ^^^^^^^^^^^---
   |                   |          |
   |                   |          any code following this expression is unreachable
   |                   unreachable expression
```

(The code should also build without the `unsafe`; that is caused by the same problem.)

### Meta
```
1.47.0-nightly
(2020-07-26 6c8927b0cf80ceee1938)
```

cc @rust-lang/wg-unsafe-code-guidelines

**Comment by Nemo157** [comment]
To step it up a notch, I then tried giving `FOO` an address pointing to data at least as valid as `!` ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4b021808aa061dd1f9642388b8ef875d)):

```rust
#![feature(never_type)]
#![feature(raw_ref_macros)]
#![feature(raw_ref_op)]

extern {
    static FOO: !;
}

mod foo {
    #[no_mangle]
    static FOO: u32 = 5;
}

fn main() {
    dbg!(unsafe { core::ptr::raw_const!(FOO) });
    dbg!(unsafe { &raw const FOO });
}
```

I expected this to run and exit fine, since it is just printing the address of a symbol that definitely has an address.

Instead, it ran and then SIGILLd:

```
     Running `target/debug/foo`
[src/main.rs:15] unsafe { core::ptr::raw_const!(FOO) } = 0x000055b8aacb1604
[src/main.rs:16] unsafe { &raw const FOO } = 0x000055b8aacb1604
[1]    662959 illegal hardware instruction (core dumped)  cargo run
```

**Comment by RalfJung** [comment]
The [relevant MIR looks like this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3dce3c1e74b6f806b7d1ac06f3373fa8):
```rust
        _2 = const {alloc0: &!};
        _1 = &raw const (*_2);
 ```
@oli-obk looks like creating a raw ptr to a static goes through a reference, with the new scheme? Also Cc @matthewjasper 

FWIW I am not sure if this is really a bug; an explicitly uninhabited static seems at the very least highly suspicious to me. This is currently certainly not a blessed pattern. But the generated MIR is still odd.

**Comment by Nemo157** [comment]
The context in which I noticed it was an attempt by @repnop at using them to pass the heap start/end addresses from the linker to a Rust program ([discord convo](https://discord.com/channels/273534239310479360/273539705595756544/737403902932025354)). It seemed like a somewhat correct way to encode a symbol that has a known address, but should not be readable.

**Comment by RalfJung** [comment]
I think an inhabited ZST like `()` is a more appropriate way to encode that pattern.

**Comment by RalfJung** [comment]
Btw I think this should be merged with https://github.com/rust-lang/rust/issues/74843; both are caused by the same odd MIR generation.

**Comment by oli-obk** [comment]
We're computing the type of the "address of" constant of statics in https://github.com/rust-lang/rust/blob/06e7b93f6a2a3eeaf80fd6a9a3ef7b180bb5d778/src/librustc_mir_build/hair/cx/expr.rs#L839 and that doesn't account for extern statics: https://github.com/rust-lang/rust/blob/39d5a61f2e4e237123837f5162cc275c2fd7e625/src/librustc_middle/ty/util.rs#L543-L552

I thought we had some more logic there a while back... oh well. We need an `else if self.is_foreign_item(def_id) { self.mk_imm_ptr(static_ty) }`... before the `else`, which should then give us exactly what we want

**Comment by oli-obk** [comment]
You can check this out by changing all your extern statics to be mutable, then you get the codegen you'd get with my suggested change above. Though the never type example still dies horribly, so there seems to be a bit more to the never type, even if there's never a reference to it.

**Comment by RalfJung** [comment]
Yeah, the problem is here already:
```
_2 = const {alloc0: &!};
```
We are embedding the const at *reference* type (note that `&!`), which is wrong.

Maybe @matthewjasper knows more about how/why this happens.

**Comment by oli-obk** [comment]
The fix is described in https://github.com/rust-lang/rust/issues/74840#issuecomment-665667945

**Comment by RalfJung** [comment]
@oli-obk I am not sure if that is the right fix, or at least not a complete one. For this code:
```rust
static FOO: T = ...;

let ptr = ptr::raw_const!(FOO);
```
I'd expect no reference to be created. This makes a difference when there's invalid data in `FOO`.

**Comment by oli-obk** [comment]
there can't be invalid data for `FOO`, unless `FOO` is extern, and my fix suggests to make using an extern static create a raw pointer just like we do with mutable statics.

**Comment by RalfJung** [comment]
There can be invalid data. `FOO` could be interior mutable and somebody could cast a pointer to it to a different type, and write data that is invalid at `FOO`'s type.

**Comment by oli-obk** [comment]
I was under the impression that it's UB to have a (non extern) static that has invalid data. I thought static items and local variables had the same rules with that. Is there any discussion about this? Because it's definitely news to me.

**Comment by RalfJung** [comment]
It's the same for statics and locals. There is nothing [in the UB list](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) that says that locals or statics always have valid data. It only says you may not create invalid data. Through pointer type casts, it is possible to havie invalid data in a local without ever creating invalid data. Whether we want to do something about this and if it has any negative consequences, is tracked at https://github.com/rust-lang/unsafe-code-guidelines/issues/84.

**Comment by oli-obk** [comment]
oh wow... ok. We'll need to rewrite the entire system around `StaticRef` in that case. I guess what we need to do is to translate `ExprKind::Ref(ExprKind::Path(name_of_static))` directly instead of recursing when encountering `ExprKind::Ref` and translating `ExprKind::Path` to `*&STATIC`. The good thing if we do this is that we can get rid of some hacks in promotion and const checking.

**Comment by Dylan-DPC** [comment]
I'm not sure if this issue classifies as "E-Easy" any more :D

**Comment by RalfJung** [comment]
Not sure if we need to rewrite the entire system... an alternative might be to always use raw pointers, but make unsafety checking recognize these derefs of const raw ptrs that point to a `DefId` of the right type... or maybe they are marked somehow in the MIR.

**Comment by oli-obk** [comment]
> an alternative might be to always use raw pointers, but make unsafety checking recognize these derefs of const raw ptrs that point to a `DefId` of the right type... or maybe they are marked somehow in the MIR.

Stop reading my mind :stuck_out_tongue_closed_eyes:. I considered this, but the complexity for that would imo warrant rewriting the system and simplifying everything. Right now we need to look at a deref, check whether its local is a `StaticRef` local as per debug info, if it is, we need to find the last (and only) assignment to that local and look at the rhs to read the constant and process it. Adding more layers to that scheme doesn't seem too great to me. The entire reason I wrote the scheme was so we can use references and pointers to signal what can be safely accessed and what not, because I thought there was a canonical lowering to all accesses to statics.

**Comment by RalfJung** [comment]
I don't think I follow. My proposed scheme should make the insertion of these pointers simpler -- just always use raw pointers. This is in exchange for a bit more complexity in the unsafety checks (as otherwise all static accesses would be considered unsafe). I am not sure if that's a good tradeoff considering how critical the safety checks are, but it doesn't match what you are saying about this being more complex during MIR construction.

**Comment by RalfJung** [comment]
I like the sound of "simplify everything", but I am not sure what alternative you are thinking of.

**Comment by oli-obk** [comment]
So... we have the folliwing cases:

* `ExprKind::Ref(ExprKind::Path(path_to_static))` (this is taking a reference to a static)
* `ExprKind::AddrOf(ExprKind::Path(path_to_static))` (this is taking a raw pointer to a static)
* `ExprKind::Path(path_to_static)` (this is reading from or writing to a static directly)

And right now we're translating all of them to a constant of `&STATIC` value (sometimes at pointer type, sometimes at reference type). We then immediately insert a deref so what we actually get is `*&STATIC` or `*&raw STATIC`. In the case of `Ref` or `AddrOf` we then proceed to take a reference again, so we get `&*&STATIC` or `&raw *&STATIC` (or either of these with a `&raw STATIC`). In all other cases, we read from the static in a copying manner since we can't move out of a reference or raw pointer via deref.

What we could do instead is to lower `Ref` directly to a `&STATIC` constant, `AddrOf` directly to a `&raw STATIC` constant and all other uses to a new `Rvalue` kind (`Rvalue::Static(DefId)`?) that just reads from the static.

**Comment by RalfJung** [comment]
> If we want we can also put everything into the Rvalue::Static by having another enum that decides whether this Rvalue is reading from the static, taking a reference to it or taking a pointer to it.

IMO then it would make more sense to just bring back static places.

If we can rely on such larger patterns, my proposal would be:
* `ExprKind::Ref(ExprKind::Path(path_to_static))` -> static address at reference type
* `ExprKind::AddrOf(ExprKind::Path(path_to_static))` -> static address at raw pointer type
* `ExprKind::Path(path_to_static)` -> copy deref of static address at reference type

However, I am not sure if the first case is correct -- does unsafety checking still detect `static mut` and `extern static` uses as unsafe this way?

**Comment by oli-obk** [comment]
> However, I am not sure if the first case is correct -- does unsafety checking still detect `static mut` and `extern static` uses as unsafe this way?

right, we'll need to keep generating raw pointers there

> IMO then it would make more sense to just bring back static places.

While my first knee-jerk reaction was nonono, you gave me an idea:

We add a fifth kind of local (we have return place, argument, local, temporary) for statics! Then we have a map from local indices to `DefId`s.

**Comment by RalfJung** [comment]
> right, we'll need to keep generating raw pointers there

OTOH, the unsafety check says "use of mutable static is unsafe and requires unsafe function or block", so clearly this is not just treated the same as a raw pointer access.

> We add a fifth kind of local (we have return place, argument, local, temporary) for statics! Then we have a map from local indices to DefIds.

Uh... more indirections don't seem great if we can avoid them. I like the "const ptr" scheme because it reuses an existing mechanism that we have to support anyway.

What about the other scheme I suggested? It doesn't need static places or rvalues.

**Comment by oli-obk** [comment]
> Uh... more indirections don't seem great if we can avoid them.

we keep one level of indirection, there's no new indirection (right now we need to check debug info, except in miri, which just evaluates the operand). Though I do realize that miri will now have an additional step.

This will make some static analyses actually have less indirection, as when reading from a local we don't have to walk to the local's last assignment in case its debug info says it's a local that gets a reference to a static assigned.

> clearly this is not just treated the same as a raw pointer access.

it is, we just tune the diagnostic message after we're sure we're emitting an error. If borrowck didn't know about the debug info for statics it would just emit an error about raw pointer derefs needing unsafe. In contrast to your scheme, where the "debug" info would become critical to safety.

> What about the other scheme I suggested? It doesn't need static places or rvalues.

I'm thinking about these cases where the current scheme requires some roundabout analyses. These would not get simpler with your scheme.

**Comment by RalfJung** [comment]
> we keep one level of indirection, there's no new indirection (right now we need to check debug info, except in miri, which just evaluates the operand). Though I do realize that miri will now have an additional step.

I'd expect codegen can also just evaluate the operand? Then it gets a `DefId` pointer but that is something it has to be able to handle anyway.

> This will make some static analyses actually have less indirection, as when reading from a local we don't have to walk to the local's last assignment in case its debug info says it's a local that gets a reference to a static assigned.

I don't follow, why would that be an interesting special case?

> In contrast to your scheme, where the "debug" info would become critical to safety.

(I assume you are referring to my "always use raw ptrs" scheme; I don't this this is true for my [later scheme](https://github.com/rust-lang/rust/issues/74840#issuecomment-676066359) which uses the raw ptr vs reference distinction like current master.)

I'd not rely on the debug info, I'd follow the `DefId`. A raw pointer to a static of the same type is definitely dereferencable, so that is something we could exploit: when we see `*RAW_PTR`, but the `RAW_PTR` is a constant that is a pointer literal pointing to a `DefId`, we check the type of the static and if it matches and this is a non-extern immutable static we declare the deref safe.

This is subtle, but OTOH right now it turns out that [this code](https://github.com/rust-lang/rust/blob/39d5a61f2e4e237123837f5162cc275c2fd7e625/src/librustc_middle/ty/util.rs#L543-L552) is crucial for unsafety checking and there's not even a comment there explaining that. So right now a similar subtlety is spread across several files, my proposal would centralize them all in the unsafety checking file.

I actually think I now prefer "always raw ptrs" over my [later scheme](https://github.com/rust-lang/rust/issues/74840#issuecomment-676066359).

> I'm thinking about these cases where the current scheme requires some roundabout analyses. These would not get simpler with your scheme.

I am trying to understand what those cases are. As Miri shows, in terms of semantics, no special case should be needed. I think the same should be true for codegen. I don't know what borrowck has to do.

**Comment by oli-obk** [comment]
> (I assume you are referring to my "always use raw ptrs" scheme; I don't this this is true for my [later scheme](https://github.com/rust-lang/rust/issues/74840#issuecomment-676066359) which uses the raw ptr vs reference distinction like current master.)

Oh, apologies. Yes, the lastest scheme would be essentially what we have today from all but mir building, that seems the best way to go about this imo.

> when we see *RAW_PTR, but the RAW_PTR is a constant that is a pointer literal pointing

The problem with `*RAW_PTR` is that there's no rvalue for that. We need to

```rust
let tmp = RAW_PTR;
let whatever = *tmp;
```

Now this could be resolved by moving the deref projection into a custom `Rvalue::Deref(Operand)`, then we'd have everything in one statement, but currently I have to find the assignment to `tmp` before being able to figure out that it's a constant being assigned to it and that this constant is actually a reference/pointer to a static item.

**Comment by oli-obk** [comment]
One example of such a roundabout analysis is https://github.com/rust-lang/rust/blob/5b04bbfcbb79ed7325ea2b580458a80d95da6bbb/src/librustc_mir/transform/promote_consts.rs#L509-L539

**Comment by RalfJung** [comment]
> The problem with *RAW_PTR is that there's no rvalue for that.

Oh, because you can only deref places which have to start at a local... yeah that's annoying. This makes me more sympathetic with an option that lets us put a static into a place more directly.

> One example of such a roundabout analysis is 

Oh wow okay now I start to see what happens here. We are following the def-use chain backwards to the def. Yeah that's quite awful that we have to do that.

**Comment by oli-obk** [comment]
Ok, so I've reread the previous plans for virtual locals (https://github.com/rust-lang/compiler-team/issues/291) that we are not performing since there are other things we can try first. Right now a `LocalId` only refers to things that don't alias with anything else, so changing that should not be done lightly here.

*but* we can still implement the part where all `mir::Place` get replaced with `mir::PlaceId` (this is a new type), which is then used to index an `IndexVec<PlaceId, Place>`.

After we do that, we can reserve some more indices in `PlaceId` for constants. I think e.g. 2^30 different constants should suffice for every mir::Body (likely rustc will die elsewhere if you manage to produce that many *different* constatns in a mir body). These constants then keep the current scheme of encoding statics as references/pointers. The difference is that we can now use them in places and perform projections on them (yes I know this will conceptually allow `5 = x` as a `mir::StatementKind::Assign` because now constants can appear in places, but it does also mean that accessing fields of statics doesn't require two statements anymore in mir building. We can use mir validation to prevent the accidental creation of constants other than pointers to statics in write places

Another `2^30` will go to locals with projections. Another `2^30` can be used for places without projections (this is purely an optimization, we can do this later), so we just map them 1:1 to `LocalId`s, and finally the rest of the `2^30` can be used for niches.

This means we're basically reintroducing static places, but without increasing the size of places everywhere. In fact, we're now reducing the sice of places!

**Comment by RalfJung** [comment]
> Ok, so I've reread the previous plans for virtual locals (rust-lang/compiler-team#291) that we are not performing since there are other things we can try first. 

That MCP doesn't say anything about what virtual locals are, does it? It talks about refactoring projections but I don't see the connection.

> but we can still implement the part where all mir::Place get replaced with mir::PlaceId (this is a new type), which is then used to index an IndexVec<PlaceId, Place>.

Woah what does that have to do with statics?^^

This seems way overkill for the problem we have here, I even prefer the "have `LocalId` -> `DefId` mapping" over this.^^ Though this indirection will increase the MIR size for functions that reference many statics.

---

So far [this](https://github.com/rust-lang/rust/issues/74840#issuecomment-676066359) still seems to be the simplest proposal to fix the regressions here (modified to also use raw pointers for unsafe-to-access statics). My proposal would be to implement that, and then think about how to avoid [cases like this](https://github.com/rust-lang/rust/blob/5b04bbfcbb79ed7325ea2b580458a80d95da6bbb/src/librustc_mir/transform/promote_consts.rs#L509-L539) without the pressure of a regression.

**Comment by RalfJung** [comment]
> Ok, so I've reread the previous plans for virtual locals (rust-lang/compiler-team#291) that we are not performing since there are other things we can try first. 

That MCP doesn't say anything about what virtual locals are, does it? It talks about refactoring projections but I don't see the connection.

> but we can still implement the part where all mir::Place get replaced with mir::PlaceId (this is a new type), which is then used to index an IndexVec<PlaceId, Place>.

Woah what does that have to do with statics?^^

This seems way overkill for the problem we have here, I even prefer the "have `LocalId` -> `DefId` mapping" over this.^^ Though this indirection will increase the MIR size for functions that reference many statics.

---

So far [this](https://github.com/rust-lang/rust/issues/74840#issuecomment-676066359) still seems to be the simplest proposal to fix the regressions here (modified to also use raw pointers for unsafe-to-access statics). My proposal would be to implement that, and then think about how to avoid [cases like this](https://github.com/rust-lang/rust/blob/5b04bbfcbb79ed7325ea2b580458a80d95da6bbb/src/librustc_mir/transform/promote_consts.rs#L509-L539) without the pressure of a regression.

**Comment by oli-obk** [comment]
There's no regression that we're fixing, none of this is stable, right?

**Comment by RalfJung** [comment]
> One example of such a roundabout analysis is
> 
> https://github.com/rust-lang/rust/blob/5b04bbfcbb79ed7325ea2b580458a80d95da6bbb/src/librustc_mir/transform/promote_consts.rs#L509-L539

If this issue gets closed by your https://github.com/rust-lang/rust/pull/76982, then we should make sure to track the above problem (and considered solutions) somewhere else.

**Comment by oli-obk** [comment]
So... I looked a bit deeper and realized that it's not related to anything in the MIR or MIR building at all, but it's typeck which treats all diverging expression (path expression to an extern static in this case) as causing all following expressions to be unreachable, even if in the raw pointer case this is not technically true. More details can be found in https://github.com/rust-lang/rust/pull/76982#issuecomment-696043491

TLDR: I don't see a good reason to allow uninhabited extern statics, since their only use case is getting their address taken. So I'm proposing to instead add a future incompat lint that tells you to not use extern statics of uninhabited type and instead use a dummy type that you can safely take the address of.

**Comment by RalfJung** [comment]
> TLDR: I don't see a good reason to allow uninhabited extern statics, since their only use case is getting their address taken. So I'm proposing to instead add a future incompat lint that tells you to not use extern statics of uninhabited type and instead use a dummy type that you can safely take the address of.

Agreed. It could directly recommend `()` as said dummy type.

That said, isn't something like this still needed to make `&raw const STATIC` not create an intermediate reference? The only remaining reason why that is bad is that references technically are UB when they point to invalid data, raw pointers are not... so in principle we could just add a FIXME and rely on the compiler not exploiting this.

(Also `static_ptr_ty` still needs better comments to explain how critical that function is. I was going to add those comments once we figured what we want to do.)

**Comment by oli-obk** [comment]
Yea, I am currently rewriting that PR, but I wanted to separate it from the UB situation here.

**Comment by RalfJung** [comment]
The reason uninhabited extern statics are so problematic is that they are the only *uninhabited places* that one can actually access in Rust -- normal statics cannot be uninhabited as then computing their initial value would error, and uninhabited locals cannot be accessed before being initialized which can never happen.

So, with that lense on, it makes perfect sense to just make these a hard error after some transition period. @oli-obk are you taking care of that PR or should I put it on my list?

**Comment by RalfJung** [comment]
I opened #77096 for the problems the current static handling is causing, and the refactoring we might want to do.

**Comment by oli-obk** [comment]
I am not working on that

**Comment by RalfJung** [comment]
I have written the code for rejecting uninhabited statics... but I realized I have no idea where to put it.^^ I first put it to the other static checks such as `Sync`, but realize that those are never run for `extern` statics...

**Comment by RalfJung** [comment]
In fact this means that `extern static` can be `!Sync`, which seems... strange?

**Comment by RalfJung** [comment]
I think I found a reasonable place: https://github.com/rust-lang/rust/pull/78324

**Comment by simonbuchan** [comment]
So I just hit this warning testing some code doing interop with Objective-C (ugh). The relevant code here is approximately:

```rust
// roughly the content of the objc headers
pub enum objc_class {}
pub type Class = *const objc_class;

...

// presumably this could change to ptr::raw_const!()? 
impl NSObject {
    pub fn class() -> Class {
        extern "C" {
            #[link_name = "OBJC_CLASS_$_NSObject"]
            static CLASS: objc_class;
        }
        &NS_OBJECT_CLASS
    }
}
```

Essentially, using the dynamic linker to generate runtime identifiers. This is emulating what Objective-C and Swift emit to avoid (or rather optimize, since the dynamic linker is doing it) the runtime cost of looking up classes.

As far as I can tell from this thread, the issue is approximately that it's illegal to take the address of a value that can't exist (in Rust) as it's uninhabited, and the replacement is to use a valid (ie. inhabited) type? Here the issue is that `objc_class` should not be constructible, movable, or really have any size (zero or not) by users of the crate, and should be a distinct type from, e.g.  `objc_object`. The constructible constraint is easy enough, but the others are a lot harder to emulate without an uninhabited type.

Would the suggestion be to change this simply to:

```rust
        extern "C" {
            #[link_name = "OBJC_CLASS_$_NSObject"]
            static CLASS: ();
        }
        (&NS_OBJECT_CLASS).cast()
```

Or is there a better `!Size` type that `objc_class` and friends could wrap that wouldn't cause this issue?

**Comment by qwerty19106** [comment]
Possible you should use [extern type](https://github.com/rust-lang/rfcs/blob/master/text/1861-extern-types.md) syntax.

> Add a new kind of type declaration, an extern type:
> 
> extern {
>     type Foo;
> }
> 
> These types are FFI-safe. They are also DSTs, meaning that they do not implement Sized. Being DSTs, they cannot be kept on the stack, can only be accessed through pointers and references and cannot be moved from.

It requires Nightly now.

**Comment by oli-obk** [comment]
The lack of a Size is indeed problematic without `extern type`, but you can satisfy immovability quite easily: you just don't implement `Copy` for your type: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=809cdd29dbe7449c682c2020b9e89b13

If you want to make sure ppl realize the size is problematic, put a `[u8; 1000*1000*1000*1000]` into it. Since there's never an instance of this value, this won't blow you stack or anything unless someone tries to create a value via `MaybeUninit` or other unions

**Comment by RalfJung** [comment]
@simonbuchan using an uninhabited type to model an opaque type is a very bad idea, because Rust assumes that uninhabited type *cannot be constructed by anyone ever*. That is not what you want to express -- you want to express that *the (Rust) client of your library cannot construct this type*, but other parts of the code (across an FFI boundary, but that makes no difference) *can* construct it.

The "proper" but nightly-only solution is indeed `extern { type Foo }`. There's a less elegant version taht works on stable [described in the nomicon](https://doc.rust-lang.org/nightly/nomicon/ffi.html#representing-opaque-structs).

**Comment by simonbuchan** [comment]
Thanks everyone! `extern type` looks great, but for now, I'll go with the zero-sized struct. Unfortunately, pointer to uninhabited enum is a bad idea with tenure: it's seems to be used everywhere as the current implementation of extern types. It seems it works fine unless you are doing exactly this though, so it's probably not too bad.

**Comment by RalfJung** [comment]
> It seems it works fine unless you are doing exactly this though

It works if you only ever use it as the pointee of a raw pointer, like `*mut Uninhabited`. But if you ever use it with a reference type, or dereference the raw pointer (`*ptr`), then you have UB.
