### ISSUE TITLE
Tracking Issue for Vec::spare_capacity_mut

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/rust#75017]
The feature gate for the issue is `#![feature(vec_spare_capacity)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history

- Initial implementation (#75015)

**Comment by danielhenrymantilla** [comment]
FWIW, here is a full-featured API provided by an external crate: https://docs.rs/uninit/0.3.0/uninit/extension_traits/trait.VecCapacity.html#foreign-impls

**Comment by djc** [comment]
I wonder how this API relates to `ReadBuf`. It would be great if there was some safe API that wrapped around the use of `ReadBuf` to access a `Vec`'s spare capacity, then updated `len` based on the `ReadBuf`s `filled`.

**Comment by the8472** [comment]
> FWIW, here is a full-featured API provided by an external crate: https://docs.rs/uninit/0.3.0/uninit/extension_traits/trait.VecCapacity.html#foreign-impls

Maybe we should follow that example and generalize `spare_capacity_mut()` to return  `(&mut [T], &mut [MaybeUninit<T>])`?

**Comment by Shnatsel** [comment]
> Maybe we should follow that example and generalize `spare_capacity_mut()` to return `(&mut [T], &mut [MaybeUninit<T>])`?

#79015 has implemented that, albeit as a private function. Sounds like a good idea to me.

**Comment by the8472** [comment]
Since #81944 exists now I think `vec_spare_capacity` is redundant.

**Comment by WaffleLapkin** [comment]
@the8472 
> Since #81944 exists now I think `vec_spare_capacity` is redundant.

That's not actually true due to pointer invalidation, see https://github.com/rust-lang/rust/issues/81944#issuecomment-782849785 and https://github.com/rust-lang/rust/pull/82564

**Comment by saethlin** [comment]
I think it would be better to have this feature sooner rather than later. I'm starting to notice instances where people are doing things that are probably or definitely UB because they want this functionality. So I think this API falls squarely into the standard library's mission to provide pre-built and correct implementations of things that are subtle or difficult to get right.

[`rayon`](https://github.com/rayon-rs/rayon/blob/f45eee8fa49c1646a00f084ca78d362f381f1b65/src/iter/collect/mod.rs#L130-L142)
```rust
    /// Reserve space for `len` more elements in the vector,
    /// and return a slice to the uninitialized tail of the vector
    fn reserve_get_tail_slice(vec: &mut Vec<T>, len: usize) -> &mut [MaybeUninit<T>] {
        // Reserve the new space.
        vec.reserve(len);

        // TODO: use `Vec::spare_capacity_mut` instead
        // SAFETY: `MaybeUninit<T>` is guaranteed to have the same layout
        // as `T`, and we already made sure to have the additional space.
        let start = vec.len();
        let tail_ptr = vec[start..].as_mut_ptr() as *mut MaybeUninit<T>;
        unsafe { slice::from_raw_parts_mut(tail_ptr, len) }
    }
```

[`protobuf`](https://github.com/stepancheg/rust-protobuf/blob/aa516f28f26f964c0b5580bf74928d97489418f7/protobuf/src/misc.rs#L5-L9)
```rust
/// Slice from `vec[vec.len()..vec.capacity()]`
pub unsafe fn remaining_capacity_as_slice_mut<A>(vec: &mut Vec<A>) -> &mut [A] {
    let range = vec.len()..vec.capacity();
    vec.get_unchecked_mut(range)
}
```

(originally posted on #81944 but per Ralf's comments there, it is probably better to have _this_ method for the above use cases)

**Comment by Amanieu** [comment]
I agree. I've been using this in my code and found it to be very useful. Even though `split_at_spare_mut` is more general, I've never had a need for it and I feel that `spare_capacity_mut` is useful on its own.

The API being stabilized is:

```rust
impl Vec<T> {
    pub fn spare_capacity_mut(&mut self) -> &mut [MaybeUninit<T>];
}
```

@rfcbot merge

**Comment by danielhenrymantilla** [comment]
@saethlin while waiting for this feature to be _stabilized_, you should suggest that `rayon` and `protobuf` use one of the convenience methods in: https://docs.rs/uninit/0.4.0/uninit/extension_traits/trait.VecCapacity.html#method.split_at_extra_cap

**Comment by saethlin** [comment]
@danielhenrymantilla Ralf mentioned this on #81944, mostly rewording with my own opinion: I would prefer not to recommend that function, because even if you just want access to the spare region, under SB, these interfaces invalidate all pointers to the initialized region. I think that's too much of a footgun for codebases where people are already writing code that is rejected by Miri.

**Comment by danielhenrymantilla** [comment]
I wonder how many people do keep outstanding pointers to the initialized part while toying with the extra part 🤔 `::uninit`'s implementation is already way better than their 0-elems slices that get `unsafe`-ly converted into non-empty slices 😱 

Anyhow, I've just released a new version with a dedicated `.spare_cap()` adapter: https://docs.rs/uninit/0.5.0-rc1/uninit/extension_traits/trait.VecCapacity.html#method.spare_cap, for extra good measure.

**Comment by saethlin** [comment]
> I wonder how many people do keep outstanding pointers to the initialized part while toying with the extra part

To be clear, my concern is that the splitting interfaces are adding a landmine for the future. If I'm sending someone a PR I'll make sure it passes Miri at the time, but that's a hard condition to maintain. Especially because the two aforementioned codebases have dependencies that do int-ptr casts, an operation that Miri just doesn't understand at the moment, so it would be hard to advocate Miri in CI.
