### ISSUE TITLE
Assertion `MFI.isCalleeSavedInfoValid() && "CalleeSavedInfo not calculated"' failed on AArch64

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#75096]
The `debuginfo/function-arguments-naked.rs` test is failing on AArch64's CI:

```
---- [debuginfo-gdb] debuginfo/function-arguments-naked.rs stdout ----
NOTE: compiletest thinks it is using GDB with native rust support

error: compilation failed!
status: signal: 6
command: "/checkout/obj/build/aarch64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/debuginfo/function-arguments-naked.rs" "-Zthreads=1" "--target=aarch64-unknown-linux-gnu" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/aarch64-unknown-linux-gnu/test/debuginfo/function-arguments-naked.gdb/a" "-Crpath" "-Zunstable-options" "-Lnative=/checkout/obj/build/aarch64-unknown-linux-gnu/native/rust-test-helpers" "-g" "-L" "/checkout/obj/build/aarch64-unknown-linux-gnu/test/debuginfo/function-arguments-naked.gdb/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
warning: unused variable: `x`
  --> /checkout/src/test/debuginfo/function-arguments-naked.rs:36:10
   |
36 | fn naked(x: usize, y: usize) {
   |          ^ help: if this is intentional, prefix it with an underscore: `_x`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `y`
  --> /checkout/src/test/debuginfo/function-arguments-naked.rs:36:20
   |
36 | fn naked(x: usize, y: usize) {
   |                    ^ help: if this is intentional, prefix it with an underscore: `_y`

rustc: /checkout/src/llvm-project/llvm/lib/Target/AArch64/AArch64MachineFunctionInfo.h:197: unsigned int llvm::AArch64FunctionInfo::getCalleeSavedStackSize(const llvm::MachineFrameInfo&) const: Assertion `MFI.isCalleeSavedInfoValid() && "CalleeSavedInfo not calculated"' failed.

------------------------------------------
```

**Comment by mati865** [comment]
Just like with every LLVM update it might fix itself or get worse after https://github.com/rust-lang/rust/pull/73526

**Comment by JamieCunliffe** [comment]
The test is causing an infinite loop due to the link register being updated during the call to zzz, that call is causing the link register to be the ret instruction after that call, the ret instruction then returns to the link register causing an infinite loop. Normally before the call the link register would be saved and then restored after the call, however due to this being a naked function that isn't happening. 

The emitted LLVM IR is just calling the function and that call isn't preserving anything so this could change in a future version of LLVM I suppose.
Although with c++ and clang that code would fail to compile as you can only use asm inside a naked function. https://internals.rust-lang.org/t/idea-naked-functions-2-0/11637/25 suggests it's a bug in rustc for allowing the code to compile, @Amanieu is that still your understanding?

I also suspect it's why this https://github.com/rust-lang/rust/issues/74847 was raised.

I can get the test to pass, but I'm wondering if the test is actually correct in it's current state.

**Comment by Amanieu** [comment]
The test is definitely incorrect. Using anything other than inline asm in a naked function is UB.
