### ISSUE TITLE
Optimize `if` conditions with integer equality to matches on the integer

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#75144]
If we generate the MIR for

```rust
fn black_box<T>(t: T) -> T { t }

fn main() {
    let x = black_box(42);
    
    let y = if x == 43 {
        "foo"
    } else {
        "bar"
    };
}
```

we get something like

```rust
        _3 = Eq(move _4, const 43i32);
        StorageDead(_4);
        switchInt(_3) -> [false: bb2, otherwise: bb3];
```

which we could also write as

```rust
        switchInt(_4) -> [43i32: bb3, otherwise: bb2];
```

(plus move the `StorageDead` to the beginning of `bb2` and `bb3`). The same goes for `!=` (`Ne`).

cc @rust-lang/wg-mir-opt

**Comment by simonvandel** [comment]
I would like to work on this
@rustbot claim

**Comment by simonvandel** [comment]
Hi @oli-obk 
While working on this I see that SwitchInt values are of type u128. This would mean that this optimization could only be done if the integer value is unsigned. 

Is it an oversight that SwitchInt does not allow to switch on signed values?

**Comment by bjorn3** [comment]
The u128 is just a zero-extended version of the value to switch on. For example `if i == -1i8` would be something like `Switch(i) -> [0xff: bb1, otherwise: bb2]`.

**Comment by tmiasko** [comment]
FYI: Codegen does the this transformation in other direction:

https://github.com/rust-lang/rust/blob/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d/src/librustc_codegen_ssa/mir/block.rs#L220-L224

**Comment by oli-obk** [comment]
Hmm... that's good to know. Maybe we should additionally have the opposite optimization as a cleanup before we go into codegen, then this codegen arm can just become an assert.

**Comment by bjorn3** [comment]
For cg_clif `Eq + SwitchInt` results in suboptimal codegen over `SwitchInt`. The former has to materialize the flag into a register before comparing it again, while the later can just perform the comparison and directly jump on the flag. This is because bools have to be represented as integers at the abi boundary and when loading and storing memory. Keeping them as bools until these points results in much more complexity than turning them into integers and compare them in the `SwitchInt` impl like any other integer. Also it is likely quicker for cg_llvm to switch to `icmp` + `br_if` during codegen than it is to rewrite the mir with the associated possibility of a reallocation of the statements vec.

**Comment by oli-obk** [comment]
so... should we remove that transformation from codegen_ssa and let the backend handle it?

**Comment by bjorn3** [comment]
I think so. It can wait though, as I don't yet use codegen_ssa anyway.

**Comment by simonvandel** [comment]
So we still want to do the MIR optimization? I understood from @bjorn3 that switching directly on the integer would be beneficial for cranelift but not necessarily for llvm. Did I get that right?

**Comment by bjorn3** [comment]
I think that is correct.

**Comment by oli-obk** [comment]
Yes, we still want this optimization. The llvm backend already handles this change correctly, so I think we should just keep the optimization unconditionally since it simplifies the MIR.
