### ISSUE TITLE
x.py says "patch for the non root package will be ignored"

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#75442]
`x.py` recently started saying something like this several times on almost every invocation:
```
warning: patch for the non root package will be ignored, specify patch at the workspace root:
package:   /home/r/src/rust/rustc/src/tools/rls/Cargo.toml
workspace: /home/r/src/rust/rustc/Cargo.toml
```

**Comment by RalfJung** [comment]
Probably caused by https://github.com/rust-lang/rust/pull/75427
Cc @Xanewok  @calebcartwright

**Comment by Mark-Simulacrum** [comment]
@rust-lang/cargo, is there any way for us to make that warning an error? Ideally this wouldn't pass CI...

**Comment by mati865** [comment]
It was done to fix CI in RLS repo and has no effect on Rust. Why should it be hard error?

**Comment by Xanewok** [comment]
It's worth noting that functionally it doesn't change anything - the `patch` section in the RLS manifest should always point to the version checked in the submodule.

I'll update the RLS.

I understood that this use case might be useful to support in some ways - my intent was to patch the dependency from the crate PoV to emphasize that pulling Rustfmt from git is a temporary measure and a regular crates.io dependency should be used eventually t]ere, rather than trying to globally patch the rustfmt (which is already done by the final Rust virtual manifest).

**Comment by Mark-Simulacrum** [comment]
It should be a hard error or silenceable -- we shouldn't have warnings on master.

**Comment by est31** [comment]
>  is there any way for us to make that warning an error? 

AFAIK it's hardcoded. I've suggested introduction of `cargo::` lints in https://github.com/rust-lang/cargo/pull/8437#issuecomment-663098291 , to build upon https://github.com/rust-lang/cargo/issues/5034 .

The largest implementation complexity I see with the cargo feature is in fact non-cargo lints because rustc prints the source of the lint level, and if cargo sets arguments, rustc would only see those and thus complain about arguments to the users.

Maybe initially the feature could only allow `cargo::` lints, with rustc lints coming once it's figured out how to get rustc print the source of the lint level.

It would be great to have this feature for https://github.com/rust-lang/cargo/pull/8437 as well so that one doesn't need to support `#![deny(unused_crate_dependencies)]` in random compilation units.

**Comment by est31** [comment]
Yeah it's hardcoded to warn: https://github.com/rust-lang/cargo/blob/7bce509826e29bd79566f7a33621fea7e7a657f9/src/cargo/core/workspace.rs#L828

**Comment by Mark-Simulacrum** [comment]
@Xanewok, any news on updating RLS? I can take care of removing the patch and bumping the submodule to a separate branch on rust-lang/rls if you'd like (the patch shouldn't be needed for rust-lang/rust, but I guess is needed upstream).

**Comment by est31** [comment]
You don't need a separate branch. You only have to create a different Cargo.toml file and then change ci to do sth like `--manifest-path Cargo.toml.ci`.

**Comment by Mark-Simulacrum** [comment]
I guess that would work too, but personally that seems somewhat more complicated and more likely to lead to problems of only updating one of them.
