### ISSUE TITLE
Typoing dot instead of comma in `println!` gives a warning at the wrong place

### ISSUE THREAD

**Issue by vivia** [rust-lang/rust#75492]
```rust
use std::time::SystemTime;

fn main() {
    println!("Hello, {:?}!". SystemTime::now());
}
```
says:
```
error: expected token: `,`
 --> src/main.rs:4:40
  |
4 |     println!("Hello, {:?}!". SystemTime::now());
  |                                        ^^ expected `,`

```

... which isn't exactly where the `,` was expected.

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e2837f62f524065616b120f71269b78c))

Another variation is this code:

```rust
fn random_xkcd_number () -> i32 {
    4
}

fn main() {
    println!("Hello, {}!". random_xkcd_number());
}
```
which gives this result:
```
error: format argument must be a string literal
 --> src/main.rs:6:14
  |
6 |     println!("Hello, {}!". random_xkcd_number());
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
help: you might be missing a string literal to format with
  |
6 |     println!("{}", "Hello, {}!". random_xkcd_number());
  |              ^^^^^
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0c6aef1d9e5224185984d2af854da750))

**Comment by scileo** [comment]
Hello,
I am a quite new contributor, and I'd like to tackle this issue. Do you think that is possible?

I have looked a bit at the code, and I think this mostly comes from the [`parse_args`] function, more precisely, [this condition][cond] can be tweaked. Is that correct?

[`parse_args`]: https://github.com/rust-lang/rust/blob/668ef72f4429059240ee361a2f0f748558a5326f/src/librustc_builtin_macros/format.rs#L124
[cond]: https://github.com/rust-lang/rust/blob/668ef72f4429059240ee361a2f0f748558a5326f/src/librustc_builtin_macros/format.rs#L143

**Comment by scileo** [comment]
> I have looked a bit at the code, and I think this mostly comes from the [`parse_args`](https://github.com/rust-lang/rust/blob/668ef72f4429059240ee361a2f0f748558a5326f/src/librustc_builtin_macros/format.rs#L124) function, more precisely, [this condition](https://github.com/rust-lang/rust/blob/668ef72f4429059240ee361a2f0f748558a5326f/src/librustc_builtin_macros/format.rs#L143) can be tweaked. Is that correct?

Turns out I was terribly wrong. The problem is that the following snippet:

```rust
println!("A number: {}". std::iter::once(42).next().unwrap());
``` 

Can be rewritten as:

```rust
println!("A number: {}".std ::iter::once(42).next().unwrap());
```

And that the [`parse_args`] function looks for an expression as the first argument ([corresponding code][expression], [code example][snippet]). Consequently, `"A number: {}".std` is the said expression, which explain why the error is raised on the first `::`.

Now that I know where the error comes from. I think the best way to fix this issue is to check if this expression can be a format string, perhaps with the [`expr_to_spanned_string`] function. I am still unsure about the quality of the emitted error, but at least it would have the correct span.

[`parse_args`]: https://github.com/rust-lang/rust/blob/668ef72f4429059240ee361a2f0f748558a5326f/src/librustc_builtin_macros/format.rs#L124
[expression]: https://github.com/rust-lang/rust/blob/668ef72f4429059240ee361a2f0f748558a5326f/src/librustc_builtin_macros/format.rs#L138
[snippet]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=81feaf8547821901720e4421e889d0e8
[`expr_to_spanned_string`]: https://github.com/rust-lang/rust/blob/a45dedf3d07dd2c088d89b5e5b7f4c7912b0812f/src/librustc_expand/base.rs#L1120
