### ISSUE TITLE
Track time to build compiler on CI

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#75570]
On CI, we print out the time to build individual crates with the prefix `[RUSTC-TIMING]`. However, we don't seem to do anything with this data (as far as I can tell). I think it would be useful to integrate this with `perf.rust-lang.org` - this would give us a (fairly coarse-grained) idea of how the time to bootstrap the compiler is changing.

I'm not sure if the wall-clock times on CI are too nosiy to make this useful.

**Comment by ehuss** [comment]
The data used to be displayed at https://alexcrichton.github.io/rust-ci-timing-tracker/ but it is no longer collecting new data.  That can probably be adapted to work with GHA (the code is at https://github.com/alexcrichton/rust-ci-timing-tracker). I too think it would be useful, since there have been PRs which accidentally add something very expensive, or remove something that should be running.  Unfortunately the data tends to be almost too noisy to work with.  CI has a variety of different hardware that jobs get assigned to that can vary dramatically, and is also probably heavily influenced by neighboring VMs.  It also requires someone to look at it, which historically didn't happen too much.

**Comment by Aaron1011** [comment]
This appears to have been implemented in rustc-perf at se point,  so I'm closing this issue.
