### ISSUE TITLE
platform-support: x86_64-linux-kernel should be *

### ISSUE THREAD

**Issue by geofft** [rust-lang/rust#75581]
The tier 3 platform x86_64-linux-kernel has support for core + alloc, and we test it in CI at https://github.com/fishinabarrel/linux-kernel-module-rust, so I think it should be marked **.

**Comment by scileo** [comment]
Hi,
I'm Sasha, I've never contributed to Rust before, and I'd like to know if I can work on this issue.

If I understand correctly, this issue is just about fixing the Tier 3 table in [the platform support file][platfom-support.md]. Is that correct? Are there some other details that should be discussed before?

[platform-support.md]: https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/platform-support.md

**Comment by geofft** [comment]
That sounds right to me, @scileo. Welcome!

Thanks for moving, @XAMPPRocky, apparently I checked right before it was moved :)
