### ISSUE TITLE
name mangling cannot be reversed

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#7610]
We're using hacks like identity numbers instead of paths to traits and types.

**Comment by steveklabnik** [comment]
Triage: no changes here.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by bstrie** [comment]
I'm not sure what the complete extent of the scope of this issue was intended to be, but our mangled symbols are indeed reversible (see @alexcrichton 's repo at https://github.com/alexcrichton/rustc-demangle/blob/master/src/lib.rs ). I highly suspect that the exact symbol mangling scheme isn't considered *stable* though, but I'd consider that to be a distinct issue that we'd need to tackle if we ever wanted to stabilize our ABI.
