### ISSUE TITLE
Tracking issue for const `Ordering` methods

### ISSUE THREAD

**Issue by CDirkx** [rust-lang/rust#76113]
Constify methods of `core::cmp::Ordering` under feature `const_ordering`.

Current methods made const:
 - `reverse`
 - `then`

Tracking issue for `const fn`: #57563.

**Comment by pnkfelix** [comment]
Visiting for T-compiler steering backlog bonanza

Its not totally clear what this issue is meant to be tracking.

The description lists a pair of methods that *were already* made const in #75463. 

We suspect the intent is to track the constification of the *remainder* of the `Ordering` methods that can be made `const`, but there's no clear specification of what the work items there are.

@rustbot label: S-tracking-need-summary

**Comment by CDirkx** [comment]
This issue was created originally created as a tracking issue for constifying `reverse` and `then` under the feature `const_ordering`. However, because these methods were insta-const-stabilized, skipping `rustc_const_unstable(feature = "const_ordering", issue = "76113")`. This issue has thus never actually been used.

I agree that constifying the remainder of `Ordering` is a good idea, but not something I myself can work on right now. I could therefore close this issue for now, and if someone else starts working on further constification a new tracking issue could be opened.
