### ISSUE TITLE
Tracking Issue for const_caller_location

### ISSUE THREAD

**Issue by ArekPiekarz** [rust-lang/rust#76156]
This is a tracking issue for the const part of RFC 2091: track_caller (rust-lang/rfcs#2091).
The feature gate for the issue is `#![feature(const_caller_location)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps
- [x] Implement the RFC
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history

https://github.com/rust-lang/rust/pull/72445

**Comment by ArekPiekarz** [comment]
I wasn't sure if there was anything else needed to fully implement the RFC for const, but I preferred to stay on the safe side and left it unchecked when creating this issue.

**Comment by davidbarsky** [comment]
Out of curiosity, are there any blockers to this being stabilized, other than getting meaningful feedback on its current state? I ask because a stable, const `Location::caller` would be _incredibly_ valuable for [tokio-rs/tracing](https://github.com/tokio-rs/tracing/), as it'd allow tracing to get rid of some pretty gnarly macros.

**Comment by pnkfelix** [comment]
Visiting for T-compiler steering backlog bonanza.

We believe this feature will be most useful in concert with PR #101030. But the latter has not been merged yet.

So we're going to treat this as "needs to bake", and after PR #101030 has gotten some exercise in the wild, then we can talk about stabilizing them as a set.

@rustbot label: S-tracking-needs-to-bake

**Comment by wesleywiser** [comment]
@davidbarsky out of curiosity, does tracing need #101030 to be stabilized as well or just this feature?

**Comment by pnkfelix** [comment]
(there is also the question of whether #102911 should be merged in with this tracking issue. That's basically a question of whether this functionality is sufficiently useful on its own, *without* the ability to observe Location fields, that it would be worth stabilizing #76156 **without** stabilizing #102911.)

**Comment by davidbarsky** [comment]
@wesleywiser @pnkfelix sorry for the delay in responding! This post was sitting unpublished in my tabs 😓. Anyways: tracing will need https://github.com/rust-lang/rust/issues/102911 _in addition to_ https://github.com/rust-lang/rust/issues/76156  because [Metadata](https://docs.rs/tracing/latest/tracing/struct.Metadata.html) has a de-facto requirement to be `'static` [from Subscribers](https://docs.rs/tracing/latest/tracing/trait.Subscriber.html). tracing 0.2 might loosen this requirement to use `Cow` under the hood, but I'm not sure when that will happen.

**Comment by robertbastian** [comment]
This has baked for a while now and hasn't lit any fires. Can we get this on track for stabilisation?

**Comment by robertbastian** [comment]
Bump

**Comment by Amanieu** [comment]
Libs-api is happy to to stabilize this, but we would like to check with @rust-lang/wg-const-eval first.

**Comment by oli-obk** [comment]
I don't see any issues with this. The impl has been tried and tested on the miri side extensively.

**Comment by Amanieu** [comment]
@rfcbot fcp merge

**Comment by Amanieu** [comment]
To be clear, this FCP is intended to also cover #102911 which const-stabilizes the other methods on `Location`.

**Comment by Ciel-MC** [comment]
Yipee, when is this getting stabilized? :D
