### ISSUE TITLE
Give a better error message for `async pub fn` and `const pub fn`

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rust#76437]
It may be possible that developers get mixed up where pub visibility needs to be shown.

```
error: expected item, found keyword `async`
 --> src/lib.rs:1:1
  |
1 | async pub fn t() {}
  | ^^^^^ expected item

error: aborting due to previous error
```

```
error: expected identifier, found keyword `pub`
 --> src/lib.rs:1:7
  |
1 | const pub fn t() {}
  |       ^^^ expected identifier, found keyword

error: expected one of `:`, `;`, or `=`, found keyword `fn`
 --> src/lib.rs:1:11
  |
1 | const pub fn t() {}
  |           ^^ expected one of `:`, `;`, or `=`

error: missing type for `const` item
 --> src/lib.rs:1:7
  |
1 | const pub fn t() {}
  |       ^^^ help: provide a type for the item: `r#pub: <type>`

error: aborting due to 3 previous errors
```

I am working on the first one, the second one looks harder to solve so I am not solving it.

It would be good to suggest the developer that `pub` needs to come before `async` or `const`. And I don't even know if `async` should come before `const` or the other way around.

**Comment by troublescooter** [comment]
Another place where the messages are confusing:

```
///
async pub fn foo() {}
```

```
error: expected item after doc comment
 --> /home/playground/src/main.rs:1:1
  |
1 | ///
  | ^^^ this doc comment doesn't document anything

```

**Comment by pickfire** [comment]
@troublescooter That is a different issue, please open a new issue if there is no existing issue on that.

**Comment by troublescooter** [comment]
I'm confused what you mean by you see no issue with that. Do you mean no Github issue or no problem whatsoever?
I should have formulated the example more clearly, the issue here isn't that the docstring is missing. Swapping `pub` with `async` compiles without errors. So this seems at least related to the issue at hand where `async` was expected to be an item. In this case `async pub fn` doesn't seem to be recognised at all.

If I misunderstood your disagreement I'll happily file another issue.

**Comment by pickfire** [comment]
I don't think the pull request I sent fix the issue you mentioned, need to check.
