### ISSUE TITLE
rustbuild: is llvm always built with AVR backend?

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#76470]
I have this in my `config.toml`

`targets = "X86"`
but while `x.py` runs cmake, I saw

````
-- Constructing LLVMBuild project information
-- Linker detection: LLD
-- Found Git: /usr/bin/git (found version "2.28.0")
-- Targeting X86
-- Targeting AVR
Traceback (most recent call last):
  File "<string>", line 22, in <module>
IndexError: list index out of range
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_EXECUTABLE
    WITH_POLLY

````

Making me wonder if there is something that always causes AVR to be activated (by mistake?)

repo @ e82584a77d019bd5ee4254b5870270b1493763a6

**Comment by mati865** [comment]
Seems like error in https://github.com/rust-lang/rust/pull/69478

https://github.com/rust-lang/rust/pull/69478/files#diff-9a46b13a265be2ded97369dddf5037f5R147 probably should have been left empty, otherwise [this comment](https://github.com/rust-lang/rust/pull/69478/files#diff-c18ae2d8b23f1968bca15e8e349dbbf3R68) is not valid:
```
# LLVM experimental targets to build support for. These targets are specified in
# the same format as above, but since these targets are experimental, they are
# not built by default
```

cc @dylanmckay

**Comment by matthiaskrgr** [comment]
Yeah, I was looking into `native.rs` and it seems that when no experimental targets are activated, AVR is enabled. I'll push a patch in a few minutes.

**Comment by petrochenkov** [comment]
This is not an issue with AVR specifically, all experimental targets were always built by default, similarly to how all regular targets are built by default.
So you always had to use
```toml
targets = "X86"
experimental-targets = ""
```
rather than just
```toml
targets = "X86"
```
to disable targets except for x86.

**Comment by matthiaskrgr** [comment]
That seems counterintuitive to me.
The default according to `config.toml.example` is indeed ` #experimental-targets = "AVR"` but since it is commented out it makes it look like it's not building that.

**Comment by petrochenkov** [comment]
I agree that it's counterintuitive, but not building AVR by default will silently disable `// needs-llvm-components: avr` tests, for example.

Perhaps the better default would be to drop experimental targets only if the `targets` field was specified explicitly.

**Comment by mati865** [comment]
What about disabling experimental-targets by default but explicitly enabling AVR on the fastest CI test job?

**Comment by Mark-Simulacrum** [comment]
Hm, I think the comment is probably misleading, but I don't personally see why this is counterintuitive - everything in config.toml.example is commented out, since it's intended to just provide defaults at a point in time. Since many people copy it in its entirety, if they weren't mostly commented we would find it harder to update defaults (and have them actually take effect).

On this case, maybe we can merge AVR into the targets list? Rustbuild could manually separate it out into experimental targets for LLVM, but I feel like from a rustc perspective there's no significant difference between experimental and regular targets.

I am personally a bit hesitant to modify local configurations in a way that diverges from CI to prevent painful debugging as much as possible - do we have some idea how much time cutting LLVM targets saves?

**Comment by jyn514** [comment]
See also https://github.com/rust-lang/rust/issues/76408

**Comment by nikic** [comment]
AVR is no longer an experimental target since LLVM 11.

**Comment by jyn514** [comment]
I'm going to close this since it seems like it's no longer causing issues.
