### ISSUE TITLE
Regression: some macro invocations no longer work in Nightly.

### ISSUE THREAD

**Issue by emilio** [rust-lang/rust#76482]
This is a regression which also affects Firefox, though it can be worked around by updating the syn crate.

I'll post a repro in a bit. The repro builds with stable rust (`rustc 1.46.0 (04488afe3 2020-08-24)`) and fails to build with nightly rust (`rustc 1.48.0-nightly (0e2c1281e 2020-09-07)`).

**Comment by emilio** [comment]
Repro lives here: https://github.com/emilio/rustc-issue-76482

**Comment by Aaron1011** [comment]
This is caused by an outdated version of `syn`, which does not handle `None`-delimited groups properly. Running `cargo update -p syn` in your repro repository fixed the issue.

**Comment by emilio** [comment]
Yes, I mentioned that above: 

> it can be worked around by updating the syn crate

Still seems weird for it to regress like that...

**Comment by emilio** [comment]
To be clear, I'm a bit disappointed at breaking changes without even a warning cycle, but so it is I guess.

**Comment by Aaron1011** [comment]
@emilio: Unfortunately, the nature of this change makes emitting a warning impossible. The error is emitted by a proc macro, which is a black box as far as rustc is concerned. The only way to know if a proc-macro will produce an error is to run it, and the only way to 'recovery' or 'downgrade' such an error would be to run the proc-macro again with a different `TokenStream`. Since proc-macros are currently unsandboxed, this could cause all sorts of issues (duplicate network requests, overwriting files, etc).
