### ISSUE TITLE
Remove `qualify_min_const_fn` and `#![feature(const_fn)]`

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#76618]
We currently have two separate MIR passes that are responsible for const-checking. One lives in the `check_consts` directory, and is responsible for the checks that run in all const contexts. The other is `qualify_min_const_fn`, which performs additional checks within `const fn` when `#![feature(const_fn)]` is not enabled. The split was necessary to push `const fn` feature over the finish line due to technical debt in the const-qualification code, but it resulted in some checks being duplicated between the two modules. Const-qualification has since been rewritten entirely, and it should be possible to unify the two to reduce the maintenance burden and improve diagnostics.

I half-heartedly attempted this in #68940, but eventually abandoned it due to the volume of error message changes and reticence from a former lang-team member. However, I think we should give this another try, since the split has caused some confusion about `#![feature(const_fn)]` (see #76602) and there was a request from the libs-team to change how stability attributes affect whether the `qualify_min_const_fn` runs (see #75794).

I did not fully understand when writing #68940 that `qualify_min_const_fn` is responsible for ensuring that publicly exported, stable `const fn` in `staged_api` crates do not rely on unstable features as part of their implementation. `check_consts` makes no such effort. So far, we've relied on the review process to enforce this, but I think one of the first steps will be to add this functionality to `check_consts`, enabling it only within `const fn` at first. After that, we can define new structured errors for each of the checks in `qualify_min_const_fn` in the `check_consts` framework and disable the former entirely. At first, all of these checks will be controlled by the `#![feature(const_fn)]` feature gate, but I think we should assign a new gate to each (floating point arithmetic within `const fn`, `impl Trait`, etc.).

@oli-obk, would you be willing to review this work? Is there anything I missed?

TODO:
* [x] Fully [remove `qualify_min_const_fn`](https://github.com/rust-lang/rust/issues/76618#issuecomment-699201921)
* [ ] ... (list needs completing)

cc @rust-lang/wg-const-eval

**Comment by RalfJung** [comment]
> So far, we've relied on the review process to enforce this

I am confused, haven't we relied on `qualify_min_const_fn` to enforce this?

**Comment by ecstatic-morse** [comment]
For checks that exist in both `qualify_min_const_fn` and `check_consts`, yes. However, not everything in `check_consts` has an analogue in `qualify_min_const_fn`. `const_precise_live_drops` for sure does not, and I believe there are others (`MutDeref`?).

**Comment by RalfJung** [comment]
Ah, so basically when `check_consts` was extended to accept more things, we sometimes forgot to extend `qualify_min_const_fn` to make sure it rejects them? That is surprising as I thought `qualify_min_const_fn` was a tight whitelist and thus wouldn't accept any of these new features.

**Comment by josephlr** [comment]
> I believe there are others (`MutDeref`?).

So it looks like stable library functions can't use `MutDeref`, as `qualify_min_const_fn` has [a specific type-level check that bans any mutable references](https://github.com/rust-lang/rust/blob/b6c84553c4fa47174d2510541a90243000fb44d8/compiler/rustc_mir/src/transform/qualify_min_const_fn.rs#L111-L113). However, this only applies in functions not constants, leading to a strange outcome where:
```rust
const FOO: Option<&mut i32> = None;
```
is allowed on stable, but
```rust
const fn bar() {
    let x: Option<&mut i32> = None;
}
```
is not, [playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8514fd0173e8af6e6d11459b2e0e7cc4).

This corresponding check in `check_consts` bans [the _operation_ of taking mutable references, rather than the type itself](https://github.com/rust-lang/rust/blob/b6c84553c4fa47174d2510541a90243000fb44d8/compiler/rustc_mir/src/transform/check_consts/ops.rs#L183-L227). These checks not being exactly the same mostly just seem to cause weird compiler errors (with incorrect recommendations).

> That is surprising as I thought `qualify_min_const_fn` was a tight whitelist and thus wouldn't accept any of these new features.

This seems _mostly_ true, an example of where it's not is the type-level check, which checks for some banned types, and then [lets all other types pass through](https://github.com/rust-lang/rust/blob/b6c84553c4fa47174d2510541a90243000fb44d8/compiler/rustc_mir/src/transform/qualify_min_const_fn.rs#L146).

**Comment by RalfJung** [comment]
> leading to a strange outcome 

Note that we have a few cases where things are allowed in constants but not `const fn`. Union field access and `mem:.transmute` are further examples.

**Comment by oli-obk** [comment]
> would you be willing to review this work? 

yes definively!

**Comment by ecstatic-morse** [comment]
I tried to remove `qualify_min_const_fn` in #76850, but ended up merely disabling it in `rustc` because it would have broken `clippy`, which would have caused CI to fail. I tried to remove it for real in #77128, but `clippy` can only run lints on `optimized_mir`, which is a) wrong and b) causes some assertions in const-checking to fail.

To fully resolve the first half of this issue, one of a few things needs to happen:

* `qualify_min_const_fn` can be moved into `clippy`. The `missing_const_for_fn` will be wrong in some cases but no worse than before. I'm not going to continue to maintain it, however.
* `missing_const_for_fn` can be disabled entirely. This lint is only in the ["nursery"](https://github.com/rust-lang/rust/pull/77128#discussion_r494766574), so this should be fine.
* `clippy` can add support for linting on the stolen MIR queries (e.g. `mir_const`). This is the correct solution long-term, and it means we can reopen #77128.

**Comment by RalfJung** [comment]
> missing_const_for_fn can be disabled entirely. This lint is only in the "nursery", so this should be fine.

That would be my preferred solution for now, TBH -- but I am not a Clippy maintainer so obviously I am picking what would be easiest for rustc itself.

I added resolving this as a checkbox to the OP. I am not sure if there are still parts of `const_fn` left to be moved out so I couldn't add those to the list.

**Comment by RalfJung** [comment]
Cc @rust-lang/clippy for the clippy problem

**Comment by ebroto** [comment]
I would like to make the necessary changes in Clippy to unblock this.

I would start by disabling `missing_const_for_fn` for now, and then tackle the changes needed to make Clippy use `mir_const` instead of `optimized_mir`, given that we have other places where `optimized_mir` is being used for linting (notably `redundant_clone`, but also `implicit_return`). For this step I would need some mentoring instructions though, here or in Zulip. IIUC, after that moving `qualify_min_const_fn.rs` would not be needed?

If the Clippy team agrees with the steps I can start with this tonight.

**Comment by RalfJung** [comment]
> IIUC, after that moving qualify_min_const_fn.rs would not be needed?

Clippy is the only client of `qualify_min_const_fn` right now. So it should be either moved to Clippy or removed, as the rest of rustc does not use it.

The new const analysis that rustc is using does not have a "speculative mode" -- if it detects a const-error, it raises a hard error. That is how such analysis usually work in rustc AFAIK, min_const_fn was the odd one out. Clippy exploited this special status to be able to detect if a function *could* be const without raising hard errors when it is not. A new mechanism to achieve this will have to be introduced, ideally with minimal maintenance overhead on the rustc side.

**Comment by oli-obk** [comment]
Clippy frequently has custom algorithms to detect whether to lint on something. It's totally fine not to reuse the compiler logic and keep the compiler logic simple and just have a bunch of false negatives in the lint. False negatives in a non-bug-detecting lint are absolutely no problem. So yes, I think we should just move the function to clippy and call it a day. We can then look into improving things on the clippy side without requiring any maintaining on the compiler side

**Comment by RalfJung** [comment]
@oli-obk sounds like a good plan to me.

**Comment by oli-obk** [comment]
I'll do that now

**Comment by RalfJung** [comment]
@oli-obk @ecstatic-morse what is left to be done here? The checklist in the original issue only has one unchecked item, which says "list needs completing"... ;)
