### ISSUE TITLE
rustdoc: Enable smart punctuation

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#76690]
Split off from #76687.

---

@rustbot modify labels: T-rustdoc C-enhancement

**Comment by camelid** [comment]
Uh, it looks like rustbot is editing my message and adding weird comments:

```markdown
Split off from #76687.

---

@rustbot modify labels: T-rustdoc C-enhancement

<!-- TRIAGEBOT_START -->

<!-- TRIAGEBOT_ASSIGN_START -->

<!-- TRIAGEBOT_ASSIGN_DATA_START$${"user":"camelid"}$$TRIAGEBOT_ASSIGN_DATA_END -->

<!-- TRIAGEBOT_ASSIGN_END -->
<!-- TRIAGEBOT_END -->
```

**Comment by camelid** [comment]
Cc @Mark-Simulacrum

**Comment by camelid** [comment]
It looks like smart punctuation doesn't work in headers:

![image](https://user-images.githubusercontent.com/37223377/93031561-b10b2b00-f5e0-11ea-97c4-d4e3f1a4ce29.png)

@marcusklaas wasn't able to reproduce this in pulldown itself; I'm guessing rustdoc is doing something special with headers. Cc @GuillaumeGomez

**Comment by Mark-Simulacrum** [comment]
Triagebot does that as a way of easily storing data per-issue (we could do it in the database now, we didn't have one back then). But it's expected and shouldn't really be a problem.

**Comment by pickfire** [comment]
Is this a good thing? Wouldn't keeping things as it is is better?

**Comment by Mark-Simulacrum** [comment]
@pickfire I think if you want to argue against doing this, giving reasons would be helpful.

I personally think given that we already use emoji and otherwise non-ASCII characters readily, it should be reasonable for us to generate smart quotes as well.

**Comment by pickfire** [comment]
I do think emoji and other non-ASCII characters if specified would be good. It's like saying to use greek question mark which is the same as semi-colon when a semi-colon was seen in documentation.

One thing is copying, when others are copying the text, it will copy the utf-8 version of smart quotes which when displayed in terminals is not that good of an option.

Auto changing text to emoji I am okay with that. But not automatically changing single quotes, double quotes and semi-colons. Personally I don't see much benefit to that, usually if users want it they would specifically type it out but otherwise it would be similar. In my humble opinion, looks wise the smart quotes are more ugly, but easier to distinguish opening and closing quotes, but still when copied and such it may not look so good.
