### ISSUE TITLE
Intra-doc links to items in `std::primitive` are broken

### ISSUE THREAD

**Issue by ollie27** [rust-lang/rust#76692]
For example ``[`std::primitive::i32`]`` generates a link to https://doc.rust-lang.org/nightly/std/primitive.std::primitive::i32.html.

**Comment by jyn514** [comment]
I didn't realize you _could_ re-export primitives, good catch!

This will need a redesign of how rustdoc links primitives: right now it does pure text comparison, which will have to be changed to go through `rustc_resolve`. I _think_ just looking at `Res` instead of `is_primitive` will work for almost everything, since you can't define a primitive and module in the same scope:

```rust
mod inner {
    pub use u64;
    //^~ ERROR ambiguous
    
    pub mod u64 {}
    //^~ ERROR defined multiple times
}
```

The only thing rustdoc needs to second-guess resolve on is for primitives and modules with the same name:

```rust
/// [prim@char]
/// [mod@char]
mod char {}
```
So this usage needs to stay: https://github.com/rust-lang/rust/blob/5ea3eaf237793c978cad9d48f7850619c7f49d69/src/librustdoc/passes/collect_intra_doc_links.rs#L1138
but everything else should be removed.

**Comment by jyn514** [comment]
I expect fixing this to also fix https://github.com/rust-lang/rust/issues/76693 at the same time.

**Comment by jyn514** [comment]
A related issue: when this is fixed, the link text displayed for primitives will be wrong: https://github.com/rust-lang/rust/blob/8a13fc494d4365e57d8f343219f0201458b68591/src/librustdoc/passes/collect_intra_doc_links.rs#L1058

That should just say `link_text` instead.
