### ISSUE TITLE
350MB-long type name regression in 1.46

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#76785]
Build fails with:

> reached the type-length limit while instantiating `std::future::from_generator::<[s...0, ()>}]>, ()}]>>, ()}]>>, ()}]>`

To reproduce:

```sh
git clone --recursive https://gitlab.com/crates.rs/crates.rs.git/ # f3f0c87e70d57e
cd crates.rs
cargo build
```

It compiles in 1.45 with the default type length limit.

In 1.46 it won't compile unless I add `#![type_length_limit="347827478"]` to a couple of libraries in the workspace.

### Meta

It affects 1.46 stable, and nightlies since 2020-08-14.

`cargo bisect-rustc` blames 0a49057dd35d9bd2fcc9760a054809c30eee2a58 for the regression.

**Comment by jyn514** [comment]
It sounds like there are two different issues:
1. The diagnostic problem, which is not a regression. This is the issue you're fixing in https://github.com/rust-lang/rust/pull/76777.
2. The type length limit issues, which is a regression (and has several related issues: https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+type+length+limit).

Is that accurate? If so, do you mind if I change this only to track 1, since there are other issues tracking 2?

**Comment by kornelski** [comment]
Ok, it looks like a dupe of #75992
