### ISSUE TITLE
Attribute for types that should always be passed by value

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#76935]
Inspired by #76914. Currently, we have a lint in `rustc` for types that should *always* be passed by value. Usually, these types are thin wrappers around references, so there is no benefit to an extra layer of indirection. However, this lint uses a hard-coded list of (diagnostic) names (currently `Ty` and `TyCtxt`). We should use an attribute (e.g. `#[rustc_pass_by_value]`) to control this. Note that `Ty` is a type alias, not a `struct`.

This is worthwhile because there are more widely used types that are merely a wrapper around a reference (e.g. `ty::Predicate`). One could also imagine crates in the ecosystem that also do a lot of interning might take advantage of this.

cc @lcnr

**Comment by ecstatic-morse** [comment]
Clippy has a more expansive, [allow-by-default version](https://rust-lang.github.io/rust-clippy/master/#trivially_copy_pass_by_ref) of this BTW.

**Comment by mdibaiee** [comment]
@ecstatic-morse I just tinkered around with this today a little bit.

I wasn't clear on one part: Do we want this lint to be internal to rustc, or just a builtin for everyone? I was confused because at some point you say:

> One could also imagine crates in the ecosystem that also do a lot of interning might take advantage of this.

My PR is not fully functional yet: For some reason when I try to compile code with `#[pass_by_value]`, I get the error below, even though I have registered it as a builtin:

```
error: cannot find attribute `pass_by_value` in this scope
   --> compiler/rustc_middle/src/ty/mod.rs:469:3
    |
469 | #[pass_by_value]
    |   ^^^^^^^^^^^^^
```

I will try to take another look a bit later, but any help is appreciated. Thank you!

**Comment by ecstatic-morse** [comment]
@mdibaiee Internal to rustc for now. For the broader ecosystem, a clippy lint is probably more appropriate.
