### ISSUE TITLE
Tracking issue for array::from_ref and array::from_mut

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#77101]
Tracking issue for `feature(array_from_ref)` which adds the following methods
```rust
// std::array
pub fn from_ref<T>(s: &T) -> &[T; 1];
pub fn from_mut<T>(s: &mut T) -> &mut [T; 1];
```

### Steps / History

- [x] Implementation: #77074
- [ ] FCP
- [ ] Stabilization PR

**Comment by WaffleLapkin** [comment]
Why is the mut version name differs from the slice variant? (`from_ref_mut` vs `from_mut`)

And what is blocking stabilization, it seems like there aren't any open questions/controversies. Shall I make a stabilization PR?

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by oconnor663** [comment]
Has anyone proposed to stabilize these? Could I just open a PR to start that? :)

**Comment by WaffleLapkin** [comment]
@oconnor663 I've proposed, it was already stabilized even :)

https://github.com/rust-lang/rust/pull/84105

**Comment by mzji** [comment]
Since `core::array::from_ref()` and `core::array::from_mut()` has been stablized, could we now add `impl<T> From<T> for [T; 1]`, `impl<'a, T> From<&'a T> for &'a [T; 1]` and `impl<'a, T> From<&'a mut T> for &'a mut [T; 1]` to libcore? These impls should be easy to implement (just one-liners) and ergonomic to use.

**Comment by jhpratt** [comment]
@mzji Feel free to create a pull request! I would imagine it would be accepted.

**Comment by zachs18** [comment]
> [...] could we now add `impl<T> From<T> for [T; 1]`, `impl<'a, T> From<&'a T> for &'a [T; 1]` and `impl<'a, T> From<&'a mut T> for &'a mut [T; 1]` to libcore? [...]

Adding `From<T> for [T; 1]` could conflict with downstream [`From<Local> for [Local; 1]`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b03b12a141f8d284fce04b7218f748ad).
Similarly, since `&` and `&mut` are "fundamental" and behave like their pointee for coherence purposes, downstream impls of `From<&'a Local> for &'a [Local; 1]` etc are also currently allowed, such that adding `impl<'a, T: 'a> From<&'a T> for &'a [T; 1]` would also conflict.
Adding another `x.into()` candidate for `x: &T` also was pointed out as possibly being [an issue for type inference](https://github.com/rust-lang/rust/issues/45703#issuecomment-408403441)
.
