### ISSUE TITLE
Regression for #![feature(const_in_array_repeat_expressions)]

### ISSUE THREAD

**Issue by josephlr** [rust-lang/rust#77138]
The following code used to compile on nightly, but now does not:
```rust
#![feature(const_in_array_repeat_expressions)]

struct T;

impl T {
    const fn new() -> Self {
        Self
    }
}

const fn bar() -> [T; 2] {
    [T::new(); 2]
}
```

Note that
```rust
static FOO: [T; 2] = [T::new(); 2];
```
still compiles. Adding `#![feature(const_fn)]` doesn't affect this issue.

I think this regression was introduced in either #76807 or #76850 

CC: @ecstatic-morse @oli-obk

**Comment by josephlr** [comment]
Actually @RalfJung this might be caused by #76411, as this seems to be a promotion issue.

**Comment by RalfJung** [comment]
No, this is https://github.com/rust-lang/rust/pull/75502. We used to incorrectly apply `const`-promotion rules inside `const fn`, but since `const fn` are also `fn`, that has all the same problems as applying those rules in `fn`.

So, this was never intended to work, and worked by accident. To make this work we'd have to change array initializers to explicit promotion rules, which IIRC we already have an issue for?

**Comment by RalfJung** [comment]
Hm, looks like we do not have an issue open for this, but the tracking issue probably makes sense as a place for this discussion: https://github.com/rust-lang/rust/issues/49147.

**Comment by josephlr** [comment]
> Hm, looks like we do not have an issue open for this, but the tracking issue probably makes sense as a place for this discussion: #49147.

Makes sense, we can continue discussion in the tracking issue.
