### ISSUE TITLE
Field accesses in debuginfo are treated as real uses of the base local

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#77454]
MIR may contain debuginfo like this after inlining:

```
    scope 1 {
        debug x => _3;                   // in scope 1 at $DIR/inline-closure-captures.rs:11:9: 11:10
        scope 2 {
            debug _q => _10;             // in scope 2 at $DIR/inline-closure-captures.rs:11:14: 11:16
            debug q => (*((*_6).0: &i32)); // in scope 2 at $DIR/inline-closure-captures.rs:10:23: 10:24
            debug t => (*((*_6).1: &T)); // in scope 2 at $DIR/inline-closure-captures.rs:10:17: 10:18
            let mut _9: T;               // in scope 2 at $DIR/inline-closure-captures.rs:12:5: 12:9
        }
    }
```

Here, the field access `(*_6).0` is treated like a use of the `_6` local in MIR visitors (using `PlaceContext::NonMutatingUse`), even though it is not an actual use of `_6`.

Instead, it should be using `PlaceContext::NonUse(NonUseContext::VarDebugInfo)`.

**Comment by camelid** [comment]
@jonas-schievink Can you describe where the change needs to be made? The visit method for debuginfo seems to be correct:

https://github.com/rust-lang/rust/blob/603ab5bd6e0ffefafa7411cd8bd23a6ca82bcff0/compiler/rustc_middle/src/mir/visit.rs#L827-L842

It shells out to `visit_place` with `PlaceContext::NonUse(NonUseContext::VarDebugInfo)`, and `visit_place` then shells out through some other methods to `visit_projection_elem`. `visit_projection_elem` isn't getting the PlaceContext that `visit_place` was called with (I guess because the context of a projection is potentially different than that of the local it's projecting), but it seems to do nothing for field accesses:

https://github.com/rust-lang/rust/blob/603ab5bd6e0ffefafa7411cd8bd23a6ca82bcff0/compiler/rustc_middle/src/mir/visit.rs#L974-L990

So what part should I change? Thanks!

**Comment by jonas-schievink** [comment]
Looks like the problem is here:

https://github.com/rust-lang/rust/blob/603ab5bd6e0ffefafa7411cd8bd23a6ca82bcff0/compiler/rustc_middle/src/mir/visit.rs#L1020-L1024

**Comment by camelid** [comment]
Okay, thank you!
