### ISSUE TITLE
Type system accepts wrong expression type on a statement that is unreachable

### ISSUE THREAD

**Issue by orium** [rust-lang/rust#77655]
Hi everyone.  There seems to be bug where an expression with type `!` that is made into a "statement" by adding a `;` will behave like it has type `!` instead of `()`:

The following code typechecks correctly, even though the function body has type `()` and the return type is `u32`:

```rust
fn foo() -> u32 {
    panic!();
}
```

If you replace the body with `panic!(); ()` you correctly get a type error.

Note that this is still sound, since the expression will never finish evaluation.

This happens in stable (1.46.0) as well as nightly 1.49.0-nightly (2020-10-05 a1dfd24).

**Comment by jyn514** [comment]
I'm pretty sure this intentional.

**Comment by ehuss** [comment]
This is the expected behavior. It is similar to how `fn foo() -> u32 { return 1; }` doesn't have a type error either, even though there is no tail expression after the `;`.  When determining the return type of a function body, if rustc determines that the block *diverges*, then the block has the never type which can coerce to any type.  There are several things that can cause divergence (return, panic, break, infinite loops, etc.).  This unfortunately isn't documented terribly well.
