### ISSUE TITLE
rustc_target: The differences between `target_os = "none"` and `target_os = "unknown"`, and `target_vendor = "unknown"` and `target_vendor = ""` are unclear

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#77730]
The majority of targets use `target_os = "none"` / `target_vendor = "unknown"` respectively, but some targets deviate and use `target_os = "unknown"` / `target_vendor = ""`.

Possible solutions:
- There's no difference between "", "none" and "unknown", normalize to the more common variants.
- There are deep reasons for the status quo, keep and document it.
- 50 / 50 of the above.

**Comment by ehuss** [comment]
For OS, `none` has a specific meaning of being bare-metal (no OS).  `unknown` would mean there is an OS, but it is not specified.  One way rustc cares about this is that `none` targets are built as no_std by default.

Generally a missing component of the triple is supposed to be interpreted as "unknown".  I think it might be reasonable to use "unknown" instead of an empty string in the Target definition, though I'm not sure if it matters too much in practice.  Generally people only care about the canonical target string (like `x86_64-linux-kernel` or `aarch64-fuchsia`), and the vendor string is never used (like one probably wouldn't bother doing `cfg(target_vendor="unknown")` or printing it anywhere).

This is sorta documented at https://doc.rust-lang.org/cargo/appendix/glossary.html#target (which is derived from https://clang.llvm.org/docs/CrossCompilation.html#target-triple, which is in turn derived from GNU AIUI). https://doc.rust-lang.org/rustc/targets/index.html should probably discuss this in more detail.
