### ISSUE TITLE
Missing short summaries for reexported items in rustdoc

### ISSUE THREAD

**Issue by ollie27** [rust-lang/rust#77783]
For example the current [nightly docs](https://doc.rust-lang.org/nightly/std/#modules) show: 
![image](https://user-images.githubusercontent.com/7189418/95651659-701d0e00-0adb-11eb-9d74-8543d23cd927.png)

The summary lines for the reexported modules is missing. They're also missing from the search index and sidebar.

This is a regression from #77519. cc @jyn514 @GuillaumeGomez

**Comment by ollie27** [comment]
Testing locally, this is fixed by simply removing the newly added `DocFragmentKind::Divider` but I don't know what that was added for so I don't know if that's the correct fix.

**Comment by jyn514** [comment]
> this is fixed by simply removing the newly added DocFragmentKind::Divider but I don't know what that was added 

This was added to distinguish between the attributes on the original item and attributes on the re-export: https://github.com/rust-lang/rust/pull/77519/commits/8fbfdc548aa8f0f7b9e7bbd54d6916eb5ed53e23. Previously, `collapse_docs` would collapse all attributes into one giant attribute:

```
// crate1
/// Docs in original
pub struct S;

// crate2
/// Docs on re-export
pub use crate1::S;

// how rustdoc sees it: as if _both_ docs were in crate1
/// Docs in original
/// Docs on re-export
pub struct S;
```

After my change, it distinguishes between the same two in `collapse_docs`, so they're now separate attributes the way `#[doc = "x"]` and `/// x` are not combined: https://github.com/rust-lang/rust/blob/8fbfdc548aa8f0f7b9e7bbd54d6916eb5ed53e23/src/librustdoc/passes/collapse_docs.rs#L39

I think the issue is that `doc_value` is now returning the `Divider` even if there were no additional docs: https://github.com/rust-lang/rust/blob/8fbfdc548aa8f0f7b9e7bbd54d6916eb5ed53e23/src/librustdoc/clean/types.rs#L653-L657

There are two possible fixes:
1. Don't add a divider if there were no new docs. I like this one because it's simple.
2. Change `doc_value` to ignore the first attribute if it's a `Divider` and look for the first attribute which isn't. This has the drawback there might be other places using `attrs`, although off the top of my head I don't know where.

I'll try to get a fix in with 1. today.

**Comment by jyn514** [comment]
And good catch, thanks!

**Comment by camelid** [comment]
Assigning `P-high` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2377783.20Missing.20short.20summaries.20for.20reexported.20.E2.80.A6) in the prioritization working group.

**Comment by ollie27** [comment]
> This was added to distinguish between the attributes on the original item and attributes on the re-export: [8fbfdc5](https://github.com/rust-lang/rust/commit/8fbfdc548aa8f0f7b9e7bbd54d6916eb5ed53e23).

Right, I figured that's what it was trying to do but the `Divider` is being placed at the beginning of the list of `DocFragment`s: https://github.com/rust-lang/rust/blob/c71248b70870960af9993de4f31d3cba9bbce7e8/src/librustdoc/clean/types.rs#L614 so it's not actually dividing anything. The result is that `collapse_docs` is still collapsing the docs as it did before so if a reexport has extra docs, all links are resolved relative to the local crate.

Rather than adding `Divider` couldn't `collapse_docs` check for differing `parent_module`s to decide whether to merge `DocFragment`s? That seems like the simpler solution.

**Comment by jyn514** [comment]
Oops, you're right on both counts. I guess it didn't show up because of https://github.com/rust-lang/rust/issues/77200.

> couldn't collapse_docs check for differing parent_modules to decide whether to merge DocFragments

That sounds better, yeah, then we could get rid of `Divider`. Let me try that.
