### ISSUE TITLE
`./x.py test --host=''` does nothing and succeeds

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#77906]
Running `./x.py test --host=''` builds bootstrap, but then exits successfully without building Rust and running any test. This should probably cause an error instead.

cc @Mark-Simulacrum

**Comment by jyn514** [comment]
Here's the relevant code: https://github.com/rust-lang/rust/blob/e9e09083674a58d361cd805877be55b5856d2806/src/bootstrap/builder.rs#L292-L298

We should probably have an `assert!(!targets.is_empty())` there or something (not an assert because of https://github.com/rust-lang/rust/issues/107019, but something like it).

**Comment by AleksaBajat** [comment]
Hey @Mark-Simulacrum,
Is this issue still something that needs to be worked on? I noticed in the previous PR discussion that this might not require a change. However, if we still want to address this issue, I can review flags.rs and other mentioned code and attempt to make a more appropriate fix.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this. I don't think it's critical that every invocation that is mostly a no-op errors. If you request an empty set, getting an empty set seems fine.
