### ISSUE TITLE
Inline const blocks default integers to i32

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#78132]
Inline const blocks default to the `i32` type on integer literals, see the following:

```Rust
#![feature(inline_const)]

fn main() {
    let _: usize = const { 0 };
}
```

fails compilation with: 
```
error[E0308]: mismatched types
 --> src/main.rs:4:20
  |
4 |     let _: usize = const { 0 };
  |            -----   ^^^^^ expected `usize`, found `i32`
  |            |
  |            expected due to this
  |
help: you can convert an `i32` to `usize` and panic if the converted value wouldn't fit
  |
4 |     let _: usize = const.try_into().unwrap() { 0 };
```

Regular integer literals, and in unsafe blocks just get the type right: `let _: usize = 0` and  `let _: usize = unsafe { 0 };`

Another minor thing is the error message, `const.try_into().unwrap() { 0 };` is an invalid suggestion ^^.

**Comment by camelid** [comment]
_Originally posted by @lcnr in https://github.com/rust-lang/rust/issues/78330#issuecomment-716196908:_

we probably have to treat inline consts similar to closures during typeck. That might be somewhat complicated and I don't have the time to look into this myself.

If someone wants to work on this feel free to open a topic on zulip and ping me there though

**Comment by nbdd0121** [comment]
I'll take a lot at this.

@rustbot claim

**Comment by lcnr** [comment]
@nbdd0121 the reason this happens is because of https://github.com/rust-lang/rust/issues/78132#issuecomment-719744393.

@spastorino already intends to work on this, so it might make sense to talk about this with them to prevent any duplicate work.
The relevant zulip thread is https://rust-lang.zulipchat.com/#narrow/stream/260443-project-const-generics/topic/inline.20consts.20typeck
