### ISSUE TITLE
#[must_use] on async fns works on returned `Future` instead of the awaited value

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#78149]
I tried this code:

```rust
#[must_use]
async fn foo() -> i32 {
    std::future::pending().await
}

pub fn with_warnings() {
    foo();
}

pub async fn without_warning() {
    foo().await;
}
```

I expected the compiler to warn about the unused return value in `without_warning()`, but the compiler emitted two warnings in `with_warnings()`:
```
warning: unused implementer of `Future` that must be used
 --> src/lib.rs:7:5
  |
7 |     foo();
  |     ^^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default
  = note: futures do nothing unless you `.await` or poll them

warning: unused return value of `foo` that must be used
 --> src/lib.rs:7:5
  |
7 |     foo();
  |     ^^^^^^
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&code=%23%5Bmust_use%5D%0Aasync%20fn%20foo()%20-%3E%20i32%20%7B%0A%20%20%20%20std%3A%3Afuture%3A%3Apending().await%0A%7D%0A%0Apub%20fn%20with_warnings()%20%7B%0A%20%20%20%20foo()%3B%0A%7D%0A%0Apub%20async%20fn%20without_warning()%20%7B%0A%20%20%20%20foo().await%3B%0A%7D%0A) (tried using nightly 2020-10-18 b1496c6e606dd908dd651ac2cce89815e10d7fc5)

As the *real* return values of `async fn`s are actually `impl Future`s, you may consider this as the expected behavior (I don't agree, and `impl Future`s are [already `#[must_use]`](https://github.com/rust-lang/rust/blob/9832374f6e378971e1a933362cf9781b121bb845/library/core/src/future/future.rs#L28)). If that is the case, there should be a way to make the compiler warn on unused `.await`ed values (when type of the `.await`ed value is not `#[must_use]`).

@rustbot modify labels: A-async-await A-lint -A-diagnostics

**Comment by tmandry** [comment]
I think this is indeed a bug, or at the very least unexpected behavior. It might be challenging to fix, since I don't know of a way to express the desired desugaring.

**Comment by nikomatsakis** [comment]
I agree that this will be challenging. The first problem as you said is that, in the desugaring, the `#[must_use]` is being applied to the function that returns the `impl Future`, and we don't have a clear place where it would be applied to mean "the value awaited by this future". So that's something we'd have to teach the lint *somehow*.

Second problem then would be that the lint would have to have the idea of a "must use future" (let's call it), and it would have to track when that future is awaited and figure out that the resulting value is itself `#[must_use]`.

I'm pondering if there is a generalization that might make this easier and less special case, not clear.

**Comment by tmandry** [comment]
In the short term we could make a lint to warn people who use the attribute on async fns that it won't do anything.

**Comment by camelid** [comment]
Assigning `P-medium` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2378149.20.23.5Bmust_use.5D.20on.20async.20fns.20works.20on.20retur.E2.80.A6) in the prioritization working group.

**Comment by jinpan** [comment]
A hacky workaround for this is to wrap the return type inside a `Result`:
```
async fn bar() -> Result<(), i32> {
    std::future::pending().await
}

pub async fn async_with_warnings() {
    bar().await;
}
```
and the compiler will emit warnings for the unused result.

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&code=async%20fn%20bar()%20-%3E%20Result%3C()%2C%20i32%3E%20%7B%0A%20%20%20%20std%3A%3Afuture%3A%3Apending().await%0A%7D%0A%0Apub%20async%20fn%20async_with_warnings()%20%7B%0A%20%20%20%20bar().await%3B%0A%7D%0A%0A%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0A%0A%23%5Bmust_use%5D%0Aasync%20fn%20foo()%20-%3E%20i32%20%7B%0A%20%20%20%20std%3A%3Afuture%3A%3Apending().await%0A%7D%0A%0Apub%20fn%20with_warnings()%20%7B%0A%20%20%20%20foo()%3B%0A%7D%0A%0Apub%20async%20fn%20without_warning()%20%7B%0A%20%20%20%20foo().await%3B%0A%7D%0A%0A%0A)

**Comment by guswynn** [comment]
@rustbot claim

At least "In the short term we could make a lint to warn people who use the attribute on async fns that it won't do anything." part

**Comment by ijackson** [comment]
A similar issue arises with `fehler`, https://github.com/withoutboats/fehler/issues/45.  In fact, it would be nice in general to be able to say, for a function which returns `Result<Wombat,SomeError>`, that the `Wombat` must be used.  `#[must_use]` doesn't work there either, because it just demands use of the `Result`.

Another way to look at this is that both `Result` and `Future` have syntactic sugar for unpacking and implementing control flow effects, which makes them both special in that their contained type is somehow the "underlying" "real" return type of the function.
