### ISSUE TITLE
regression: target_feature no longer permitted in some places

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#78143]
* https://crater-reports.s3.amazonaws.com/beta-1.48-1/beta-2020-10-09/gh/atkurtul.xvmath/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.48-1/beta-2020-10-09/reg/xvmath-0.1.4/log.txt

Likely caused by https://github.com/rust-lang/rust/pull/71205

**Comment by Mark-Simulacrum** [comment]
I suspect we'll call this won't fix but I have nominated it for T-lang to get it on the agenda for next triage meeting.

**Comment by nikomatsakis** [comment]
Summary:

* unused `#[target_feature]` attributes appearing in surprising places because of https://github.com/rust-lang/rust/pull/71205, places that have no effect
* another case where we have to think about our regression policy
* seems clear that the "detect if attributes are used" part of the compiler winds up incorrectly thinking that things are used fairly regularly
* given limited impact and the fact that it's clearly a bug, we're inclined to let this change go forward as a bug fix (we can revisit if/when we receive more complaints)

**Comment by pnkfelix** [comment]
assigning to mark to ensure that release notes include the note about this being a bug fix with limited impact.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/78364/files#diff-4a00447b47c36ebd3ded77321deff288e424f4605496ee1199fc9953a20f4473R80 (though that link may go stale). Closing.
