### ISSUE TITLE
Tracking Issue for feature: "option_insert"

### ISSUE THREAD

**Issue by Canop** [rust-lang/rust#78271]
This is a tracking issue for the feature "option_insert".
The feature gate for the issue is `#[unstable(feature = "option_insert")]`.

This feature adds a `insert` method to any `Option`, setting its value and returning a mutable reference to this value.
This method removes a cause of `unwrap` and code complexity.
It allows replacing

```
option_value = Some(build());
option_value.as_mut().unwrap()
```

with

```
option_value.insert(build())
```

### Steps / History

- [x] Implementation: #77392
- [x] Decide on a name. Suggestions:
  - `insert` (As in the original PR.)
  - `insert_and_get`
  - `replace`
  - `replace_and_get`
  - `set`
  - ...
- [x] FCP
- [x] Stabilization PR: https://github.com/rust-lang/rust/pull/84088

**Comment by ThePuzzlemaker** [comment]
I'd like to work on stabilizing this. @rustbot claim

As for a name, I think that either `insert_and_get_mut` or `replace_and_get_mut` would be better than `insert_and_get` and `replace_and_get` as it implies that you are getting a mutable reference just from the name, without having to look at any signatures or documentation.

**Comment by kupiakos** [comment]
`insert` seems like the best name for this to me, as that matches the existing naming of `get_or_insert` and `get_or_insert_with`. `insert` is just the unconditional version of `get_or_insert`.

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by et342** [comment]
Should this be called `get_replace`?

Say, if we have a box and if we put a `thing` into it, then what we get is a box filled with the `thing`, and not the `thing` itself. But, we do get the thing here, so prefix `get_` seems appropriate. But, `get_insert` does not seems appropriate, because if box is filled − then we cannot insert, we can only replace and replacement is what is what's happening here, so `get_replace`.

**Comment by Amanieu** [comment]
I feel that `insert` is the least confusing way to describe the operation that is happening here. We're inserting a value and replacing the old one (just like `HashMap::insert`). Returning a reference to the inserted element makes sense: that's the only reason you'd use this method instead of just doing `foo = Some(bar)`.

**Comment by et342** [comment]
I'm not really against it. `insert` is stretchable enough and kind of makes sense − but also not exactly?

> Returning a reference to the inserted element makes sense: that's the only reason you'd use this method instead of just doing `foo = Some(bar)`.

Yes, that's exactly the point. The reference you get is the primary reason to call this method, not the fact that the value gets replaced − that's secondary, because if it's a replacement action that you want, then just perform an assignment. So maybe this should be reflected in the name, like with the other `get_` methods of `Option`.

> `HashMap::insert`

I don't think `HashMap::insert` is particularly an example in favor of `insert` here, because in case of `HashMap`, new value is *pushed* into the slot, and the old one is *pushed out*. And it makes sense if we imagine it like we're inserting something somewhere and what was in there already − falls out from the other side. But in case of `insert` here − we're not getting the old thing back, it just disappears into nowhere.

Perhaps, `get_inserted`? We get a reference to an unconditionally inserted value.

**Comment by m-ou-se** [comment]
We discussed this yesterday in the library team meeting, and we agreed to continue with our original decision: `insert`.

**Comment by tmandry** [comment]
Semantics aside, I find it confusing that `Option::insert` returns a reference to the *new* value, while `HashMap::insert` returns the *old* value. That inconsistency makes it harder to remember what both methods do.

**Comment by m-ou-se** [comment]
There's already `Option::replace` that returns the old value. I'd argue that `HashMap::insert` should've been called `HashMap::replace` (and `HashMap::try_insert` just `HashMap::insert`), but that ship has sailed. :(

**Comment by WaffleLapkin** [comment]
I wonder if it would be useful to have a method on `Option` which would **both** return the old value and a reference to the new one. I.e. 
```rust
fn insert_replace(self, new: T) -> (Option<T>, &mut T) {...}
```

🤔

**Comment by Amanieu** [comment]
This seems overly complicated when you can just do:
```rust
let old = option.take();
let new_ref = option.insert(new);
```
