### ISSUE TITLE
rustdoc: Referencing methods on extern_types does not resolve

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#78777]
I tried this code:

```rust
#![feature(extern_types)]

extern {
    /// The extern type Foo.
    pub type Foo;
}

/// The struct Bar.
pub struct Bar;

impl Foo {
    /// Does stuff
    pub fn do_it(&self) {

    }
}

impl Bar {
    /// This does stuff too
    pub fn do_it(&self) {

    }
}

/// See also [Foo::do_it]
pub fn foo() {

}

/// See also [Bar::do_it]
pub fn bar() {

}
```

I expected to see this happen: Both `Foo::do_it` and `Bar::do_it` resolve.

Instead, this happened: Only `Bar::do_it` resolves.

```
warning: unresolved link to `Foo::do_it`
  --> src/lib.rs:25:15
   |
25 | /// See also [Foo::do_it]
   |               ^^^^^^^^^^ the foreign type `Foo` has no associated item named `do_it`
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24)
binary: rustc
commit-hash: ffa2e7ae8fbf9badc035740db949b9dae271c29f
commit-date: 2020-10-24
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
LLVM version: 11.0
```

**Comment by jyn514** [comment]
Mentoring instructions: in https://github.com/rust-lang/rust/blob/b385598c9658fef4a143a770c21db38b7872c134/src/librustdoc/passes/collect_intra_doc_links.rs#L436
instead of checking specific [`DefKind`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/def/enum.DefKind.html)s one at a time, look to see if they're in the [`TypeNS`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/def/enum.Namespace.html). You can check with `kind.ns() == Some(TypeNS)`.

**Comment by lochsh** [comment]
I'll have a crack at this if no one is working on it -- I'm a first-time contributor but the mentoring instructions look like enough to be getting on with :+1:

**Comment by jyn514** [comment]
@lochsh awesome! There's instructions for getting started on https://rustc-dev-guide.rust-lang.org/, and you can ask in the [Rustdoc Discord](https://discord.gg/4yEYPuT) channel if you need help.
