### ISSUE TITLE
Rustdoc should show the name of an item on a separate line before its description on small screens

### ISSUE THREAD

**Issue by RDambrosio016** [rust-lang/rust#78799]
Sometimes, on small screens, reading rustdoc documentation feels like solving a crossword puzzle:

![oh no word wrap please](https://imgur.com/waZuaR9.png)

It would be great if instead of doing this, rustdoc would just place the name on the line before and then the description as such:

<code>function_name</code>
Description here

**Comment by arj101** [comment]
This can be reproduced in Chrome dev tools too.
![Uploading 20201106_09h57m55s_grim.png…]()

**Comment by arj101** [comment]
This can be reproduces in Chrome dev tools too.
![Uploading 20201106_09h57m55s_grim.png…]()

**Comment by arj101** [comment]
This can be reproduced in Chrome dev tools too.

https://imgur.com/CEorIrc.png

**Comment by jsha** [comment]
This was effectively fixed in #79936. The solution is not exactly as proposed here. It doesn't put the name on a separate line, but instead sets a minimum width. Still, I think it solves the main problem.

The issue here is that the list shown (on a crate summary page, e.g. https://docs.rs/ureq/2.1.0/ureq/#functions or https://doc.rust-lang.org/nightly/std/#keywords, is rendered using `<table>`, `<tr>`, and `<td>`. Rendering the item name on a separate line would require getting rid of the table layout, which I think would be rather complicated.

I think we should close this. @RDambrosio016 is the issue sufficiently resolved for you?

**Comment by RDambrosio016** [comment]
Yeah that works for me
