### ISSUE TITLE
./x.py clippy errors in library/core

### ISSUE THREAD

**Issue by Nicholas-Baron** [rust-lang/rust#78813]
Running `./x.py clippy` produces [2,000 lines](https://github.com/rust-lang/rust/files/5502582/clippy.txt), where the first 500 are simple warnings. 

The error come in around line 600 and are all 
error: cannot find attribute `rustc_allow_const_fn_unstable` in this scope
out of the files
* `library/core/src/num/int_macros.rs` at lines 2048 and 2197
* `library/core/src/num/uint_macros.rs` at line 1806 and 1995
* `library/core/src/slice/mod.rs` at line 91
* `library/core/src/str/converts.rs` at line 160
* `library/core/src/str/mod.rs` at line 222
* `library/core/src/task/wake.rs` at line 133

I apologize for not adding links to the relevant code.

**Comment by jyn514** [comment]
@Nicholas-Baron you're running an old version of nightly, the errors in the current version are tracked at https://github.com/rust-lang/rust-clippy/issues/6302. Beta works fine.

In general, nightly clippy on rustc is probably not a great idea because it rapidly desyncs with the master branch. beta has special handling with `cfg(bootstrap)`.

**Comment by Nicholas-Baron** [comment]
@jyn514 `rustup override beta` did fix the issue. Thank you.
