### ISSUE TITLE
&mut coerced into & still precludes subsequent immutable borrows

### ISSUE THREAD

**Issue by fghzxm** [rust-lang/rust#78973]
I tried this code:

```rust
fn f() {
    let mut x = ();
    let r = &mut x as &();
    let _ = &x;
    drop(r);
}
```

I expected to see this happen:
- The code compiles.  Since the `&mut x` is not bound to any variable, no mutable references to `x` should be outstanding at `let _ = &x`.

Instead, this happened:
```
error[E0502]: cannot borrow `x` as immutable because it is also borrowed as mutable
 --> <source>:4:13
  |
3 |     let r = &mut x as &();
  |             ------ mutable borrow occurs here
4 |     let _ = &x;
  |             ^^ immutable borrow occurs here
5 |     drop(r);
  |          - mutable borrow later used here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0502`.
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (25f6938da 2020-11-09)
binary: rustc
commit-hash: 25f6938da459a57b43bdf16ed6bdad3225b2a3ce
commit-date: 2020-11-09
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
```

**Comment by SkiFire13** [comment]
This is not sound in the general case.

The following code coerces a mutable reference to a shared one without binding it to any variable, so following your reasoning the mutable borrow shouldn't be alive anymore. Except this allows to later grab a mutable reference to the inner value, which is UB because there's also a shared borrow alive!

```rust
fn f() {
    let mut x = core::cell::RefCell::new(());
    let r = x.get_mut() as &();
    let _ = x.borrow_mut();
    drop(r);
}
```

You could probably add a special case for `&mut x as &()`, but this is something you shouldn't even write in the first place so what is really being fixed here?
