### ISSUE TITLE
Inconsistent default display of doc(cfg(...)) on impls of empty traits

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#79279]
```rust
#![feature(doc_cfg)]

pub struct S;

#[doc(cfg(feature = "traits"))]
impl Eq for S {}

#[doc(cfg(feature = "traits"))]
impl PartialEq for S {
    fn eq(&self, _rhs: &Self) -> bool {
        true
    }
}
```

`cargo doc` renders this as follows. Notice that the blue banner appears for Eq (I guess because the trait is empty) but not for PartialEq. I believe that it should consistently appear for **neither** Eq nor PartialEq, *or* **both** Eq and PartialEq.

<img src="https://user-images.githubusercontent.com/1940490/99888226-f7dc5900-2bff-11eb-9596-2b9d14cab80d.png" width="300">

<br>

Expanding the \[+\] next to impl PartialEq shows the other blue banner but this issue is about the default appearance on page load.

<img src="https://user-images.githubusercontent.com/1940490/99888231-09256580-2c00-11eb-8aca-28349d14a578.png" width="300">

<br>

Mentioning `doc(cfg(...))` tracking issue #43781.
Mentioning @GuillaumeGomez @Nemo157

**Comment by Nemo157** [comment]
Ohh, the collapse settings are fun; I never noticed this in #78678 because I have `rustdoc-collapse: true` which seems to imply _not_ collapsing the trait implementations. Clearing that setting from local storage, or if it's set to `false` does this; I think it should be possible to make it so that having this block there either ignores collapsing so it shows always, (though this may be inconsistent with how it works with functions), or make it default to uncollapsing the trait.

**Comment by Nemo157** [comment]
(Something else to check at the same time: what happens with JS disabled)

**Comment by GuillaumeGomez** [comment]
Nothing is collapsed when JS is disabled. :)

I'll take a look tomorrow.

**Comment by Nemo157** [comment]
> Nothing is collapsed when JS is disabled. :)

The `[+] Show hidden undocumented items` toggle, and the items it toggles, are hidden when JS is disabled.

**Comment by GuillaumeGomez** [comment]
Hum... I suppose it's a new issue then. Something to add in `noscript.css`.
