### ISSUE TITLE
`x.py check` doesn't check `compiler/rustc_query_system` or `library/core/tests`

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#79305]
I had compilation errors in these two modules, but `x.py check` succeeded (discovered when creating https://github.com/rust-lang/rust/pull/79299).

**Comment by Mark-Simulacrum** [comment]
Hm, the tests are not checked because that's what happens in... any cargo check. You need to pass `--all-targets` for tests (including cfg(test) in the crate itself) to get checked, the same is true of x.py check.

The error in rustc_query_system came from cfg(parallel_compiler) code, which was not checked because you don't enable that locally.

I believe both of these are won't fix (or at least not x.py check problems, really).

**Comment by varkor** [comment]
Okay, thanks for clarifying. That does seem reasonable.
