### ISSUE TITLE
BufReader reads limited by the size of the internal buffer

### ISSUE THREAD

**Issue by K0bin** [rust-lang/rust#79480]
When using a BufReader it is not possible to read more data in one call than what can fit into the internal buffer unless that buffer is empty.

I tried this code:

```rust
let file = File::open("PATH TO BIG FILE").unwrap();
let mut reader = BufReader::new(file);
let mut ignore = vec![0u8; 2];
reader.read(&mut ignore);
let mut buffer = vec![0u8; 12525];
let read = reader.read(&mut buffer).unwrap();
println!("expected: {}, got {}", buffer.len(), read);
```

I expected to see this happen: I would expect the BufReader to read 12525 bytes as both my buffer is big enough and the reader is more than that number of bytes away from the end of the file.

Instead, this happened: The BufReader only reads 8190 bytes.
Interestingly, the bug doesn't occur if I don't do that initial read. Making the BufReader discard its internal buffer (with #68559) also works around the issue.

I think [this line](https://github.com/rust-lang/rust/blob/master/library/std/src/io/buffered/bufreader.rs#L262) is incorrect
and should discard the buffer whenever it's trying to read more data than can be fit in remainder of the current buffer.

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0 (04488afe3 2020-08-24)
binary: rustc
commit-hash: 04488afe34512aa4c33566eb16d8c912a3ae04f9
commit-date: 2020-08-24
host: x86_64-pc-windows-msvc
release: 1.46.0
LLVM version: 10.0
```

I can also reproduce it with nightly.
```
rustc 1.49.0-nightly (98edd1fbf 2020-10-06)
binary: rustc
commit-hash: 98edd1fbf8a68977a2a7c1312eb1ebff80515a92
commit-date: 2020-10-06
host: x86_64-pc-windows-msvc
release: 1.49.0-nightly
LLVM version: 11.0
```

**Comment by K0bin** [comment]
Is this not considered a bug?

**Comment by jyn514** [comment]
@K0bin `read()` can always read any number of bytes; if you want to read a set amount, use `read_all` instead, or call `read` in a loop.

**Comment by K0bin** [comment]
Yes but I'd never expect a buffered reader to do this unless the underlying Read reached the end.

**Comment by the8472** [comment]
BufReader's primary goal is is to speed up _small_ reads by performing a large read to prefill the buffer from which small reads are then served. If you're already performing large reads then there's no need for a `BufReader`.
That said, there might be room for improvement for mixed workloads.

> Yes but I'd never expect a buffered reader to do this unless the underlying Read reached the end.

You will get short reads from sockets or pipes too, this isn't unique to BufReader.

**Comment by the8472** [comment]
After digging through the current implementation I think `BufReader` can't be improved further due to existing constraints. If it has data in its buffer it must return that and not attempt to read further data from its inner reader since a read could block and thus hang the program even though data is available. For that reason and because reads could error it also cannot perform additional reads if there already is data in the buffer.

So the only option is to return a short read if a large buffer is passed for the first time. But then the buffer is drained and additional reads will be passed through to the underlying reader. So it's already as good as it can get.
