### ISSUE TITLE
Whether floating point value Display should adhere to IEEE standard?

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#79490]
It was raised in https://github.com/rust-lang/rust/pull/78618 that there needs conscious on whether f32/f64 `Display` should adhere to IEEE standard, for example outputting `+0` instead of more conventional `0`.

This issue is created to track this.

**Comment by programmerjake** [comment]
From what I can tell, the controversial part was having `format!("{}", -0.0)` produce `"-0"` instead of `"0"` as required by IEEE 754 to preserve the sign of zeros when round-tripping `f32`/`f64` -> `String` -> `f32`/`f64`. Producing `"+0"` when formatting `+0.0` is unnecessary for compliance with IEEE 754 because the sign for `"0"` is already parsed as positive.

**Comment by joshtriplett** [comment]
Personally, I think printing `-0.0` as `-0` seems reasonable. If you end up with a negative zero, it seems reasonable to support round-tripping that.

**Comment by bstrie** [comment]
Related to https://github.com/rust-lang/rust/issues/72676 .

**Comment by joshtriplett** [comment]
We discussed this in the @rust-lang/libs meeting today. We had consensus that changing floating-point printing to print the negative sign on -0 seems reasonable. We don't expect that to cause a problem in practice.

Please go ahead with the PR. We would like to see that PR go through a libs FCP for confirmation when it's ready.
