### ISSUE TITLE
CTFE: remove memoization leftovers

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#79667]
Since https://github.com/rust-lang/rust/pull/79594, memoization of argumentless functions is restricted to intrinsics, because other functions could perform heap allocations and thus memoization would be incorrect.

I doubt we have any argumentless intrinsic that is expensive enough that memoization is worth it, so I propose we remove the leftovers of that infrastructure.

Cc @rust-lang/wg-const-eval

**Comment by dvtkrlbs** [comment]
I want to work on this but i never contributed to rust-lang before so i need some guidance.

**Comment by oli-obk** [comment]
Great! So... step 0 is to write `@rustbot claim` as a comment here, this will make sure the issue is assigned to you and noone else tries to tackle it at the same time.

The main change is to remove this function: https://github.com/rust-lang/rust/blob/e5721a5283b52afbf074d3bf13c3e37822278601/compiler/rustc_mir/src/const_eval/machine.rs#L31 entirely without a replacement. You'll then have to adjust the call site to act as if the function returned `Ok(false)`. This may allow some small cleanups at the call site; I expect nothing major to happen there.

I do not think there will be further test changes due to this, so, `./x.py test src/test/ui` should run through without any failures. If it doesn't, still open a PR and let us know of your findings.
