### ISSUE TITLE
Modules in doc-tests can not access types in super/crate module

### ISSUE THREAD

**Issue by MauriceKayser** [rust-lang/rust#79769]
I probably am just using doc-tests wrongly, but I have come across a "type not found" problem using modules in doc-tests that seems rather odd to me, because it compiles in normal code without complaining:

```rust
type MyType = u8;

// Without extra module.
fn my_func(_: MyType) {}

fn main() {
    my_func(0);
}
```

```rust
type MyType = u8;

// With extra module.
mod my_mod { pub(super) fn my_func(_: super::MyType) {} }

fn main() {
    my_mod::my_func(0);
}
```

When using the same code (without `main`) in doc-tests with `cargo test`, only the first snippet passes the test:

```rust
//! ```rust
//! type MyType = u8;
//!
//! fn my_func(_: MyType) {}
//!
//! my_func(0);
//! ```
```

```rust
//! ```rust
//! type MyType = u8;
//!
//! mod my_mod { pub(super) fn my_func(_: super::MyType) {} }
//!
//! my_mod::my_func(0);
//! ```
```

The second snippet fails with the following message:

```rust
error[E0412]: cannot find type `MyType` in module `super`
 --> src\lib.rs:4:46
  |
5 | mod my_mod { pub(super) fn my_func(_: super::MyType) {} }
  |                                              ^^^^^^ not found in `super`
```

I also tried to use `crate::MyType` instead of `super::MyType` but that did not work either.

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (e792288df 2020-12-05)
binary: rustc
commit-hash: e792288df31636ca28108516c63a00ce4267063a
commit-date: 2020-12-05
host: x86_64-pc-windows-msvc
release: 1.50.0-nightly
```

**Comment by ehuss** [comment]
It doesn't work because doctests wrap the entire example in `fn main() { ... }`.  Functions themselves don't introduce a new namespace in the module hierarchy, so the `super` is referring to the module scope *outside* of the main function.  #79260 is a similar issue.

The solution is to add a main function:

```rust
//! ```rust
//! type MyType = u8;
//!
//! mod my_mod { pub(super) fn my_func(_: super::MyType) {} }
//!
//!
//! fn main() {
//!   my_mod::my_func(0);
//! }
//! ```
```
