### ISSUE TITLE
Rename json::ItemEnum to ItemKind

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#80142]
This was renamed in `clean` in https://github.com/rust-lang/rust/pull/79041, but I missed `json`.

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/pull/80119#discussion_r545222779_

**Comment by pierwill** [comment]
Doing a simple LSP renaming command, got this error:

```
error[E0428]: the name `ItemKind` is defined multiple times
   --> src/librustdoc/json/types.rs:188:1
    |
158 | pub enum ItemKind {
    | ----------------- previous definition of the type `ItemKind` here
...
188 | pub enum ItemKind {
    | ^^^^^^^^^^^^^^^^^ `ItemKind` redefined here
    |
    = note: `ItemKind` must be defined only once in the type namespace of this module
```

There is already a `json::ItemKind` type. Shall we use another name?

**Comment by pierwill** [comment]
(See https://github.com/pierwill/rust/blob/85c43c1afd0b0014418329b42bb03bc8f38f6567/src/librustdoc/json/types.rs#L156-L232)

**Comment by jyn514** [comment]
It's not clear to me why `Item` has both a `kind` and `inner` field. @P1n3appl3 do you remember the reason for that?

**Comment by P1n3appl3** [comment]
In the output we had items be "adjacently tagged" where they store the kind in a separate field instead of having the inner field be like an object with 1 key (the kind) and the inner ItemEnum as the value. Serde has an option to do that adjacent tagging automatically but it didn't work for ItemEnum for some reason iirc so instead we explicitly provide the kind alongside inner.

It's not strictly necessary if you're using serde on both ends (it figures out which kind of ItemEnum it is based its contents when deserializing) but we wanted it to be easy to use other tools/languages to process the json where it'd be simpler to switch on a single field's value.

Also looking at it now I remember that there's a couple of kinds of items (union, foreign function, and TyMethod) which reuse the ItemEnum representations from other kinds because they're identical but have separate ItemKinds to distinguish which one they were. It's doesn't have to be that way (you could just duplicate the types and give them different names like I think Clean does) buy it's something to watch out for if you're changing it.

Oh and also ItemSummary needs the kind of the item but not the contents of it's ItemEnum so it may be best to keep ItemKind around actually now that I think about it.

**Comment by jyn514** [comment]
Hmm, ok. That makes sense, this sounds tricky to fix without changing the stable format. Thanks!
