### ISSUE TITLE
Promote Certain Lints to Errors in Rust 2021 Edition

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#80165]
Tracking issue for turning lints into errors in Rust 2021.

- [ ] `BARE_TRAIT_OBJECTS`
- [ ] `ELLIPSIS_INCLUSIVE_RANGE_PATTERNS`

`ELIDED_LIFETIMES_IN_PATHS` is still under active discussion. 

cc @rylev

**Comment by camelid** [comment]
>     * MACRO_USE_EXTERN_CRATE

I'm not sure if this one should be deny-by-default; this is what the lint's page says:

> This lint is "allow" by default because this is a stylistic choice that has not been settled, see issue #52043 for more information.

**Comment by camelid** [comment]
Also, `MACRO_USE_EXTERN_CRATE` is not warn-by-default – it's actually allow-by-default.

**Comment by m-ou-se** [comment]
@rylev GitHub won't let me assign you to this issue; you wanted to work on this, right? I think you can `@​rustbot claim` to claim the issue.

**Comment by camelid** [comment]
Hmm, I wonder why GitHub won't let us assign rylev directly – they *are* an org member...

**Comment by taiki-e** [comment]
> * UNUSED_EXTERN_CRATES

> * EXPLICIT_OUTLIVES_REQUIREMENTS
> * UNREACHABLE_PUB
> * MACRO_USE_EXTERN_CRATE

I think these lints belong to a similar category as `unused` lint. I think it probably makes sense to warn by default, but I don't think we need to deny it by default.

> * ELLIPSIS_INCLUSIVE_RANGE_PATTERNS
> * ELIDED_LIFETIMES_IN_PATHS

The other two (ELLIPSIS_INCLUSIVE_RANGE_PATTERNS and  ELIDED_LIFETIMES_IN_PATHS) are related to compatibility or deprecation, and it seems reasonable to deny them in the next edition. (ELIDED_LIFETIMES_IN_PATHS is actually already rejected on async functions.)

**Comment by jyn514** [comment]
unreachable_pub still has bugs after three years: https://github.com/rust-lang/rust/issues/64762. I don't think it should be even warn-by-default until the false positives are fixed.

**Comment by oli-obk** [comment]
`CONST_ERR` has also been `deny` for a few years now (cc @RalfJung )

**Comment by RalfJung** [comment]
CONST_ERR is not an edition lint though, not even a future-incompat lint... not sure how it relates to the discussion here?

**Comment by oli-obk** [comment]
it was always intended to become a hard error, before we had the concept of edition lints or anything. I would like to make it a hard error in the next edition

**Comment by RalfJung** [comment]
I thought the plan was to make it a future incompat lint first (we can't really say it's "intended to become a hard error" without that having happened), and then eventually make it a hard error *on all editions*? That's the only way we can actually do the cleanup we want to do.

**Comment by rylev** [comment]
Where we are now:

**Promote to deny**:
* ELLIPSIS_INCLUSIVE_RANGE_PATTERNS
* ELIDED_LIFETIMES_IN_PATHS

Do the above need discussion, or are the uncontroversial? 

**Needs more discussion**:
* MACRO_USE_EXTERN_CRATE: this is currently allow by default. More discussion needs to happen (likely in #52043) on whether this should be promoted to warn. This is likely to fall in the same category as other "unused" lints and thus might not be subject to an edition change.
* BARE_TRAIT_OBJECTS: this is currently warn-by-default but it has not been settled whether this will be deny-by-default. There is currently discussion happening in [rust-lang/lang-team#65](https://github.com/rust-lang/lang-team/issues/65)
* EXPLICIT_OUTLIVES_REQUIREMENTS and UNUSED_EXTERN_CRATES: Should this be promoted to warn, and do we need to do this on an edition boundary? 

**Needs implementation work**:
* UNREACHABLE_PUB: this lint gives false positives and so is not currently ready to be promoted.

**Comment by camelid** [comment]
There's also the `mutable_borrow_reservation_conflict` lint. There's a PR to turn it from warn-by-default to deny-by-default: #76104.

**Comment by nikomatsakis** [comment]
I'm nominated this for @rust-lang/lang discussion. I'd like us to review these lints and make sure we are happy with them.

**Comment by m-ou-se** [comment]
As discussed in the lang meeting: Let's have separate PRs to turn each of these lints into deny-by-default on 2021 (which should be trivial changes), such that each lint can have its down discussion on its own PR. Then we can use this issue as the tracking issue for tracking those PRs. (cc @rylev)

**Comment by joshtriplett** [comment]
:+1:

We should also discuss (on an appropriate issue once filed) whether `bare_trait_objects` should be a deny-by-default lint, or a hard error. The argument for the latter is in https://github.com/rust-lang/lang-team/issues/65 : making `bare_trait_objects` a hard error in an edition will make it easier to give better error messages for const-generics in that edition and newer.

**Comment by rylev** [comment]
I will submit PRs for each of these lints. 👍

**Comment by nikomatsakis** [comment]
In our [2021-02-02](https://github.com/rust-lang/lang-team/blob/master/minutes/2021-02-02.md) meeting, the @rust-lang/lang team discussed this issue. We want to make decisions on the individual lints, but there is another interesting policy question: how to manage idiom lints in discussions going forward. I agree to write-up some of the pros/cons here. This may not be the right place for this comment (seems clearly not), but it'll do for now.

The question is: if you have an idiom lint for edition N, what does that mean? Of course any particular lint may follow whatever pattern we want, but what would be the *default* path?

# Options

## Version 1: Allow for earlier editions, warn starting in N, deny/error in N+1

One option is that the lint is allow and starts to warn in edition N. This is fairly weak, but it doesn't disturb older users. For folks in Edition N, they start getting warnings, and those warnings will become a stronger error in N+1.

For folks who have no wish to upgrade, and they will not see any warnings.

## Version 2: Allow for earlier editions, deny starting in N

We could also move straight to a deny in edition N. This semi-violates the rules of editions, which say that the code must warn in earlier editions if it is going to error in edition N. But it's not clear to me if those rules are meant to be that code must warn with the default settings -- e.g., perhaps the migration can issue warnings.

## Version 3: Warn for earlier editions, deny starting in N

Another option is that the lint is warning in older editions and becomes a *deny* in edition N. Effectively, the pattern is *deprecated* in earlier editions, and that deprecation becomes stronger in edition N.

If there are folks who do not wish to upgrade, they will start to see warnings, unless they use an `allow`.

## Version 4: Warn for earlier editions, hard error starting in N

Another option is that the lint is warning in older editions and becomes a hard error in edition N. Effectively, the pattern is *deprecated* in earlier editions, and that deprecation becomes a hard error (which cannot be allowed).

If there are folks who do not wish to upgrade, they will start to see warnings, unless they use an `allow`.

# Advantages and disadvantages

The important question really is what happens with older editions. Do they see warnings or not? 

Advantages of older crates seeing warnings: We encourage people to migrate. The patterns must be harmful for us to have deprecated them, so we also see improvements in all Rust code, not just Rust code in the newer editions.

Disadvantages of older crates seeing warnings: People stuck on older editions will now get warnings even if they haven't migrated. They might feel like "hey, I thought editions were opt-in!" Also, it may be that the recommended pattern they need to use to silence the warning is only available on newer releases or even in the new edition. In this case, they will have to use an `allow` to silence the lint, and we generally try to avoid that requirement.

I think those are the main advantages and disadvantages.

**Comment by nikomatsakis** [comment]
Having written the above comment, let me say how I see it -- I think a core question is **why do we keep supporting older editions?** Is it because we **want to** or because we **have to**?

To me, the reason is because we **have to**. If I had my druthers, everyone would move to the newer edition. But I know that there is extant code that won't be updated, so we keep support for the older editions. But it's ok if that code gets warnings. Good even, as it will help encourage code that is actively maintained to migrate.

Another relevant question is **why do we deprecate things**? I think the answer there is -- because they are bad. There is some problem with that pattern. I am not sure why we would want code that is using an older edition to keep using a bad pattern! As a concrete example, it seems like we want to encourage `dyn Trait` in 2015 code just as much as 2018, because we believe it is easier for people to understand code that uses `dyn Trait`. 

Similarly, I want to do whatever we can to make all editions feel similar. I want to minimize the need to answer "what edition am I in?" This is why we make features available on all editions. It's also why I am opposed to lots of fine-grained editions, since it makes it harder to remember the differences between them.

**Comment by jhpratt** [comment]
Imo (2) and (4) are no-go's. (1) is what I've assumed what would happen for the 2018 lints — that is what this issue is for, of course. (3) also seems reasonable to me for the reasons that Niko stated. A warning is functionally a deprecation, and something like `dyn Trait` is objectively clearer on _any_ edition, so warning to avoid potential confusion seems reasonable. The same reasoning would apply for any edition lint (not sure if any are planned for 2021).

**Comment by rylev** [comment]
I've gone through all the "warn-by-default" lints and seen which ones might make sense to promote to deny (usually the ones labeled as future incompatible). 

Note: a few lints that had been previously discussed have been removed from the list as they were "allow-by-default" and in my opinion we should promote them first to "warn-by-default before then possibly moving to "deny-by-default" (see @nikomatsakis's discussion of this above). First promoting these to "warn" would not require an edition and so are out of scope here.

Here's the list: 
* WHERE_CLAUSE_OBJECT_SAFETY
* ELLIPSIS_INCLUSIVE_RANGE_PATTERNS
* BARE_TRAIT_OBJECTS
* SAFE_PACKED_BORROWS
* CENUM_IMPL_DROP_CAST
* COHERENCE_LEAK_CHECK
* CLASHING_EXTERN_DECLARATIONS
* CONST_EVALUATABLE_UNCHECKED
* CONST_ITEM_MUTATION
* ILLEGAL_FLOATING_POINT_LITERAL_PATTERN
* INDIRECT_STRUCTURAL_MATCH
* LATE_BOUND_LIFETIME_ARGUMENTS
* MUTABLE_BORROW_RESERVATION_CONFLICT
* NONTRIVIAL_STRUCTURAL_MATCH
* PRIVATE_IN_PUBLIC
* PROC_MACRO_DERIVE_RESOLUTION_FALLBACK
* TYPE_ALIAS_BOUNDS
* UNINHABITED_STATIC
* UNSUPPORTED_NAKED_FUNCTIONS 

@m-ou-se can you update this issues description with this updated list?

**Comment by rylev** [comment]
@nikomatsakis A few aspects that are missing from your analysis:
* Warnings can be introduced at any time. How much *time* must pass before the pattern in question is denied by default in the latest edition. (i.e., is it acceptable to introduce a lint that is warn-by-default in older editions and a deny-by-default in a new edition at the exact same time? Or should users in older editions be made aware that "change is on the horizon"). 
* There is the future incompatible warning that explicitly states that a warning *will* become a hard error in a future edition. Is this a requirement before upgrading a warn-by-default lint to deny-by-default? Or is it acceptable for a lint to be promoted when it was not explicitly stated that promotion would happen? 

I personally think the *default* case should be:
* Introduce warnings in all all editions where the recommended new pattern is legal (to avoid warnings with no possible upgrade path in some editions). Warnings that will be upgraded in the next edition should be explicitly marked as such with a future incompatibility note. This should happen ideally at least 1 release before the next edition happens.
* Lints can only move up the "chain of lint levels" one step at a time. Lints should start life as allow-by-default and then go to warn-by-default, deny-by-default, and finally hard error. The last two steps must happen at the edition boundary.

**Comment by nikomatsakis** [comment]
@rylev 

My opinion:

>  is it acceptable to introduce a lint that is warn-by-default in older editions and a deny-by-default in a new edition at the exact same time

Yes, this was explicitly the goal as described in the RFC.

> There is the future incompatible warning that explicitly states that a warning will become a hard error in a future edition. Is this a requirement before upgrading a warn-by-default lint to deny-by-default?

First, future compatibility warnings are never *mandatory*. They are advisable to help give people a heads up. However, I don't think they apply to Edition migrations. They cover the case where something used to be accepted in Edition N and then later becomes an error in Edition N. I would probably include deny-by-default as "error" -- it's hard to imagine why we would go *straight* to deny by default if we already have a lint. The main reason to skip a FCW is if it is impractical to implement or so few crates are affected.

**Comment by nikomatsakis** [comment]
One additional point: in case this was unclear -- whatever we choose, I believe we should "repurpose" the 2018 idiom lints as 2021 idiom lints. In other words, if we opt for "deny by default in edition N" (what I called Variant 3), then the lints would be deny by default only in Edition 2021.

**Comment by nikomatsakis** [comment]
@rylev I see there is an underlying principle in what I am saying:

* The thing we want to avoid is that you upgrade rustc, rebuild, and you get errors (deny-by-default or hard error) that you weren't getting before, with no warning. It's ok to get warnings you weren't getting before, that's normal.
* Editions are the kindest way to avoid that, because you have to opt-in to the new edition to get the error.
* Future Compatibility Warnings are another way, but they are only appropriate when we consider it ok to break semver (e.g., soundness).

**Comment by rylev** [comment]
> Future Compatibility Warnings are another way, but they are only appropriate when we consider it ok to break semver 

[Future compatibility warnings](https://github.com/rust-lang/rust/blob/2918062d1d94b65dfd53d265e957d86fcb8bfdbd/compiler/rustc_lint_defs/src/lib.rs#L141-L143) can explicitly mention editions in their warnings, so I'm not sure it should only be used for semver breaking changes. It's good to know if something in edition N will go from being "just a warning" to being  a hard error in the next edition. This is extra incentive for a codebase to update.

**Comment by scottmcm** [comment]
> Lints can only move up the "chain of lint levels" one step at a time. Lints should start life as allow-by-default and then go to warn-by-default, deny-by-default, and finally hard error. The last two steps must happen at the edition boundary.

I'll push back a bit on the last part of this.  I wouldn't want a lint to have to spend a whole edition as deny-by-default before it could be a hard error.

I would say that warn-by-default to hard-error on an edition boundary is totally fine, assuming of course it's a low-effort (probably automated) fix in the migration.  And that warn-by-default to deny-by-default is fine *without* an edition boundary, so long as it's well-justified -- see `overflowing_literals`, for example, where we did this.  (I think that's also a case where even though it's deny-by-default already, it's not something that needs promoting to hard error in an edition.)

**Comment by zackmdavis** [comment]
>  * ELIDED_LIFETIMES_IN_PATHS
> Do the above need discussion, or are the uncontroversial?

#60199 and #71957 should be fixed before promoting `elided_lifetimes_in_paths`.

**Comment by RalfJung** [comment]
> SAFE_PACKED_BORROWS

That lint always always a bit weird since it allowed packed borrows in `unsafe` blocks even though that is still UB. So with https://github.com/rust-lang/rust/pull/82525, SAFE_PACKED_BORROWS disappears, and instead UNALIGNED_REFERENCES becomes a future-incompat lint. It probably makes more sense to put that on the list here.

**Comment by rylev** [comment]
This was discussed in a lang team meeting. You can find more detail [here](https://hackmd.io/7YycPi5ORhiXbualfhaQRw). Essentially only two warnings are slated to be promoted to errors in Rust 2021: `BARE_TRAIT_OBJECTS` and `ELLIPSIS_INCLUSIVE_RANGE_PATTERNS`. 

All other lints are either not ready for promotion or are future compatibility warnings (i.e., bugs in the language that we first warn about before making errors in *all* editions). 

Beside implementation work to make these warnings error in 2021, the next steps for lang team is to create better guidance on the lint policy so decisions like this are easier in the future.

**Comment by petrochenkov** [comment]
How were the lint candidates selected?
There are some notorious deprecation lints like `PUB_USE_OF_PRIVATE_EXTERN_CRATE` that should be turned into errors with high priority, but I can't find them in the list.

**Comment by rylev** [comment]
@petrochenkov We went through every lint documented [here](https://doc.rust-lang.org/rustc/lints/listing/) and decided whether it was edition bearing or not. The document I linked above has more information on the lints we explicitly discussed.

We did not explicitly discuss `PUB_USE_OF_PRIVATE_EXTERN_CRATE `, but it is a future-compatibility lint which are used for bug fixes. It was determined that bug fixes do not fall under Rust's backwards compatibility guarantees and as such they can be turned from warnings into hard errors at any time (not only at edition boundaries). That means this is not an edition concern. We can and should open a separate issue discussing when we want to turn future compatibility warnings into errors. 

@nikomatsakis has been leading an effort to more thoroughly document our linting policy to capture the answers to subtle questions like this. I believe he will be opening an RFC or an issue about this in the nearish future.

**Comment by petrochenkov** [comment]
I see.

>It was determined that bug fixes do not fall under Rust's backwards compatibility guarantees and as such they can be turned from warnings into hard errors at any time (not only at edition boundaries). That means this is not an edition concern.

Some bugfix lints like `PUB_USE_OF_PRIVATE_EXTERN_CRATE` or `PROC_MACRO_DERIVE_RESOLUTION_FALLBACK` cause hundreds of failures on crates.io when turned into hard errors, e.g. due to old versions of popular crates relying on them.

This makes them practically ineligible for promotion to errors, but it can still be reasonable to promote them at edition boundary.

**Comment by RalfJung** [comment]
> This makes them practically ineligible for promotion to errors, but it can still be reasonable to promote them at edition boundary.

I agree. There are lints for which the question isn't "make them a hard error in all code or in new code"; the question is "make them a hard error in new code or not at all".

**Comment by Nemo157** [comment]
I also just had this idea of making future-incompat lints into hard errors at the edition boundary in https://github.com/rust-lang/rust/pull/82702. It seems like this is something that should be applied to _all_ future-incompat lints at every edition boundary, independent of whether the warning may be promoted into a hard error in previous editions as well in the future.

No maintained code should ever have a future-incompat warning triggering since that code may stop compiling at any point in time, if users are going through the effort of migrating the code to the new edition while keeping code with a future-incompat warning around it seems like there is something going very wrong somewhere.

**Comment by Manishearth** [comment]
> I also just had this idea of making future-incompat lints into hard errors at the edition boundary in #82702. It seems like this is something that should be applied to _all_ future-incompat lints at every edition boundary, independent of whether the warning may be promoted into a hard error in previous editions as well in the future.

Yes, with the caveat that not all future incompat lints can be automatically fixed with `cargo fix`

**Comment by rylev** [comment]
> There are bugfix lints for which the question isn't "make them a hard error in all code or in new code"; the question is "make them a hard error in new code or not at all". 

This is definitely something we should discuss. I don't think we had a frank discussion about future incompatibility lints that are so pervasive that changing them in older code would be too damaging to be practical. 

> Yes, with the caveat that not all future incompat lints can be automatically fixed with cargo fix

I'm not sure if you're implying that we can only make future imcompat lints errors on edition boundaries if they can be automatically fixed with `rustfix`, but if so, that's not the case. We don't guarantee that edition changes have to be 100% migratable with `rustfix`.

**Comment by Manishearth** [comment]
> I'm not sure if you're implying that we can only make future imcompat lints errors on edition boundaries if they can be automatically fixed with `rustfix`, but if so, that's not the case. We don't guarantee that edition changes have to be 100% migratable with `rustfix`.

I am not implying this. However, I _am_ implying that edition breakages need to have a proper analysis of what they break, whether those breakages need to be autofixed, and if so, how they will be autofixed. This is something we're working on clarifying in the 2021 edition RFC.

Which means that we cannot have a blanket policy of upgrading future incompat lints to edition breakages since this manual analysis must be done as well.

**Comment by Aloso** [comment]
>  I wouldn't want a lint to have to spend a whole edition as deny-by-default before it could be a hard error.

The problem is that deny-by-default lints can be `#[allow]`ed. If someone has allowed bare trait objects and then upgrades to an edition that makes them deny-by-default, their code doesn't break. However, if a new release or edition turns it into a hard error, it's a breaking change (with no prior warning, since the warning was silenced).

One possible remedy is to issue a warning when someone allows a deny-by-default lint that is supposed to become a hard error in a future release.

For the person that has allowed bare_trait_objects, this means:

* If they migrate to edition_2021, they get a new warning: "bare trait objects will become a hard error in a future release in the 2021 edition. Please update your code to use the `dyn Trait` syntax and remove the `#[allow(bare_trait_objects)]` attribute"
* If they stay on edition_2018, their code will continue to work
* If they migrate to edition_2021 _after_ bare_trait_objects has been made a hard error in the 2021 edition, they get errors, even though their code built without warnings before. But this seems acceptable to me.

**Comment by Manishearth** [comment]
Okay so after going through this discussion I feel like we are retreading a lot of the work done for migration/idiom lints in the last edition, and facing the same dillemmas. We already decided on a lot of this in 2018.

If I recall correctly:


 - Idiom lints are "allow in edition X, warn in edition X + 1"
    - It is acceptable for idiom lints to be "allow in edition X, warn in X+1, deny in X+1 after a period of time" (we never implemented this)
 - Migration lints are "allow/warn in edition X, warn when migrating to X+1, hard error after migrating to X+1" 
 - Future incompat lints can and often should be turned into migration lints (i.e. they become hard errors in that edition). Note that the edition allows for _entirely new lints_ to be immediately made into a hard error, so this is, if anything, a weaker change.
 - Idiom lints from previous editions probably _should_ be made into migration lints in the next edition (i.e. they become a hard error). bare_trait_objects is one of these
 - It is not a big deal to turn _any_ lint, allow or warn, into an edition migration lint.
 - The edition upgrade mechanism should itself include a lint for `allow()` on any lints that have been turned into migration lints.

For turning something into a migration lint I really do not see a need to go "one step at a time". The edition involves _entirely new_  things -- never before linted -- being made into hard errors, it should be even less of a problem for things which have been linted for ages.

I'll point out, `bare_trait_objects` is an idiom lint from 2018, and there was a general feeling that it would probably be a migration lint (warn -> hard error) in 2021.

------

> There is the future incompatible warning that explicitly states that a warning will become a hard error in a future edition. Is this a requirement before upgrading a warn-by-default lint to deny-by-default? Or is it acceptable for a lint to be promoted when it was not explicitly stated that promotion would happen?

There is already a stability policy for lints. It is acceptable for lints to randomly change default lint levels without it ever being considered breaking, due to `cap-lint-level`. It is unacceptable for lints to turn into hard, nonsilenceable errors.

There is a strong distinction between deny-by-default and hard error that is being missed here. deny-by-default is silenceable, and does not break dependencies. On the other hand hard errors are not silenceable and always break dependencies. New hard errors for things which previously compiled or linted are always breaking changes, new deny lints for things which previously compiled or warn-linted are never breaking changes.

Turning a warn into a deny never need be tied to an edition, it _can_ be for making people want to do it more. Turning a warn into a hard error almost always _must_ be tied to an edition (or an argument should be made about why the breakage is acceptable and the blast radius should be surveyed -- this happens with future incompat stuff)

**Comment by camelid** [comment]
I'm not sure if we're including rustdoc lints in this list, but I wonder if it might be good to promote `broken_intra_doc_links` and maybe `private_intra_doc_links` to deny-by-default lints.

**Comment by jyn514** [comment]
I don't think those should be denied by default. The documentation still works fine even if the links are broken, and if people care they can always deny the lint themselves.

**Comment by Manishearth** [comment]
> I'm not sure if we're including rustdoc lints in this list, but I wonder if it might be a good idea to promote `rustdoc::broken_intra_doc_links` and maybe `rustdoc::private_intra_doc_links` to deny-by-default lints.

Please no, these are not particularly bad, and are sometimes possible to trigger by accident.

**Comment by nikomatsakis** [comment]
Closing this as done! Thanks @rylev for pushing on this.

**Comment by higker** [comment]
this was previously accepted by the compiler but is being phased out; it will become a hard error in the 2021 edition!
