### ISSUE TITLE
Type of `Option::as_ref()` is not correctly inferred when returned from `Error::source()`

### ISSUE THREAD

**Issue by teppah** [rust-lang/rust#80605]
I have a custom Error enum:

```rust
#[derive(Debug)]
pub enum ProcessError {
    ParseFieldError { source: Option<ParseIntError>, /* fields omitted*/ },
    /* ... */
}

// Assume Display is implemented
impl Error for ProcessError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            ProcessError::ParseFieldError { source, .. } => source.as_ref(),
            /* ... */
        }
    }
}
```
`source.as_ref()`'s return type, `Option<&ParseIntError>`, should be equivalent to the one required for `Error::source()` (`Option<&(dyn Error + 'static)>`). However, when I run it, I get the following error:
```
  --> src/err.rs:26:57
   |
26 |             ProcessError::ParseFieldError { source, .. } => source.as_ref(),
   |                                                             ^^^^^^^^^^^^^^^ expected trait object `dyn std::error::Error`, found struct `ParseIntError`
   |
   = note: expected enum `Option<&(dyn std::error::Error + 'static)>`
              found enum `Option<&ParseIntError>`
```
But when I take out the method call and replace it directly with `Option::as_ref()`'s source code,  

```rust
impl Error for ProcessError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            ProcessError::ParseFieldError { source, .. } => match *source {
                Some(ref x) => Some(x),
                None => None
            },
            /* ... */
        }
    }
}
```
I don't get any compiler errors and everything works as expected.

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0
```
Same issue on the latest nightly.
```
rustc 1.51.0-nightly (17eec1433 2021-01-01)
binary: rustc
commit-hash: 17eec1433c69972844dd228b5fe801f218e118c3
commit-date: 2021-01-01
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
```

<details><summary>Backtrace</summary>
<p>

```
  --> src/err.rs:26:57
   |
26 |             ProcessError::ParseFieldError { source, .. } => source.as_ref(),
   |                                                             ^^^^^^^^^^^^^^^ expected trait object `dyn std::error::Error`, found struct `ParseIntError`
   |
   = note: expected enum `Option<&(dyn std::error::Error + 'static)>`
              found enum `Option<&ParseIntError>`
```

</p>
</details>

**Comment by quixotrykd** [comment]
I believe this may be intended behavior, according to Rust's coercion rules. Taking a look over at https://doc.rust-lang.org/reference/type-coercions.html, we see that valid coercions include:

* `[T; n]` to `[T]`.

* **`T` to `dyn U`, when `T` implements `U + Sized`, and `U` is object safe.**
* `Foo<..., T, ...>` to `Foo<..., U, ...>`, when:

  * `Foo` is a struct.
  * `T` implements `Unsize<U>`.
  * The last field of `Foo` has a type involving `T`.
  * If that field has type `Bar<T>`, then `Bar<T>` implements `Unsized<Bar<U>>`.
  * `T` is not part of the type of any other fields.
* Additionally, a type `Foo<T>` can implement `CoerceUnsized<Foo<U>>` when `T ` implements `Unsize<U>` or `CoerceUnsized<Foo<U>>`. This allows it to provide a unsized coercion to `Foo<U>`.

According to these rules, it seems that we shouldn't be allowed to coerce directly from `Option<&ProcessError>` -> `Option<&(dyn Error + 'static)>`, as you're attempting to do here.

My understanding here is that your internal match expression, however, provides a coercion site (also discussed in the provided link) for `&ProcessError` -> `&(dyn Error + 'static)`, which is why your second example works. Keep in mind that Rust allows coercion even when behind various "pointer types" (of which references qualify, but `Option`s don't).

If you're looking to avoid a nested match expression here, you can do something like the following. This provides a coercion site without needed a full match expression:

```rust
impl Error for ProcessError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            ProcessError::ParseFieldError { source, .. } => source.as_ref().map(|e| e as _),
            /* ... */
        }
    }
}
```

which compiles just fine for me, on:

```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0
```
and
```
rustc 1.51.0-nightly (e22670468 2020-12-30)
binary: rustc
commit-hash: e2267046859c9ceb932abc983561d53a117089f6
commit-date: 2020-12-30
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
```

**Comment by jonas-schievink** [comment]
Yes, this is working as intended
