### ISSUE TITLE
Do a Crater run with all public `*Ext` traits in `std` sealed

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#80634]
I’d be in favor of trying out in Crater a PR that "seals" all public `*Ext` traits in the standard library.

_Originally posted by @SimonSapin in https://github.com/rust-lang/rust/issues/77728#issuecomment-753552477_

**Comment by SimonSapin** [comment]
With a bit more context: the "sealed trait" pattern is https://rust-lang.github.io/api-guidelines/future-proofing.html#sealed-traits-protect-against-downstream-implementations-c-sealed and aims to prevent crates other than the one defining a trait from implementing it. This in turns allows adding new method to that trait after it is stable. (Which would otherwise break those external implementations.)

`*Ext` are "extension traits" that add methods to one or a few types. They are typically not intended to for external crates to add more implementations and it’s not clear that doing could be useful to anyone, but without the sealed pattern there’s nothing to prevent it.

**Comment by lygstate** [comment]
> With a bit more context: the "sealed trait" pattern is https://rust-lang.github.io/api-guidelines/future-proofing.html#sealed-traits-protect-against-downstream-implementations-c-sealed and aims to prevent crates other than the one defining a trait from implementing it. This in turns allows adding new method to that trait after it is stable. (Which would otherwise break those external implementations.)
> 
> `*Ext` are "extension traits" that add methods to one or a few types. They are typically not intended to for external crates to add more implementations and it’s not clear that doing could be useful to anyone, but without the sealed pattern there’s nothing to prevent it.

Do I need to wait this to be finished?

**Comment by Enselic** [comment]
Triage: crater run performed in https://github.com/rust-lang/rust/pull/81213
