### ISSUE TITLE
ctxts on macro invocations won't work in some places

### ISSUE THREAD

**Issue by jbclements** [rust-lang/rust#8063]
The current scheme of attaching contexts to macro invocations won't work correctly when that macro invocation is inside of another macro definition, because that definition will be represented only as token trees, and the macro invocation won't accumulate context correctly.

There are a couple of possible fixes for this. One would be to back out the existing scheme and just use the context associated with the macro invocation identifier--that is, the 'foo' in an invocation foo!(3,4,5). A better way of doing it--if it's not too expensive--would be to add a context to every tt_delim, and then transfer it correctly to a tt_delim that parses into a macro invocation.

**Comment by steveklabnik** [comment]
This bug has long been open, and there hasn't been a lot of recent discussion. Macros aren't @jbclements , a reproduction would be nice if you still think this is a relevant issue. Thanks!

**Comment by jbclements** [comment]
@steveklabnik , is there a macros czar? What's the state of macros in Rust these days?

**Comment by steveklabnik** [comment]
Whoah, first of all, sorry for the half-sentence in the previous mention. What I was going to say is relevant to your question:

> What's the state of macros in Rust these days?

Basically, we reserved a `macro` keyword for 'macros 2.0'. We know that the current macro design has flaws, and because of backwards compatibility, we won't be removing `macro_rules`. But because a 2.0 will someday come, nobody is really the czar at the moment. 

https://github.com/rust-lang/rfcs/issues/440 is the tracking issue for macros++.

That said, if people are interested in fixing macro issues, we're accepting improvements. I'm fine with re-opening this issue, it was just a year since the last bit of discussion and no direct reproduction, so I figured it was closeable.

**Comment by jbclements** [comment]
> On Sep 3, 2015, at 10:57 AM, Steve Klabnik <notifications@github.com> wrote:
> 
> Whoah, first of all, sorry for the half-sentence in the previous mention. What I was going to say is relevant to your question:
> 
> What's the state of macros in Rust these days?
> 
> Basically, we reserved a macro keyword for 'macros 2.0'. We know that the current macro design has flaws, and because of backwards compatibility, we won't be removing macro_rules. But because a 2.0 will someday come, nobody is really the czar at the moment.
> 
> rust-lang/rfcs#440 is the tracking issue for macros++.
> 
> That said, if people are interested in fixing macro issues, we're accepting improvements. I'm fine with re-opening this issue, it was just a year since the last bit of discussion and no direct reproduction, so I figured it was closeable.

Okay, sounds good. Thanks!

John
