### ISSUE TITLE
Detect static narrowing of integer fields for exhaustibility purposes

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#80669]
Quite apart from tagging variables with their temporarily narrowed range until the next assignment, it would be nice if the compiler had at least basic support for detecting constant/static narrowing of a field at the site of a match/comparison, allowing this code to compile:

```rust
pub fn foo(x: u32) -> u32 {
    match x & 0x01 {
        0 => 0,
        1 => 1,
    }
}
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&code=%23!%5Bcrate_type%20%3D%20%22rlib%22%5D%0Apub%20fn%20foo(x%3A%20u32)%20-%3E%20u32%20%7B%0A%20%20%20%20match%20x%20%26%200x01%20%7B%0A%20%20%20%20%20%20%20%200%20%3D%3E%200%2C%0A%20%20%20%20%20%20%20%201%20%3D%3E%201%2C%0A%20%20%20%20%7D%0A%7D%0A)

**Comment by leonardo-m** [comment]
This is a beautiful can of pretty worms.

**Comment by oli-obk** [comment]
I think this is what is meant when ppl talk about refinement types, even in such a "simple" case. I don't think this issue is really actionable at this point. We have a large design space to explore here, and I don't think we'll be able to hash this out in this issue. There have been many discussions around it, and while I personally think it would be great to support just the simple cases for now as long as they are forward compatible to any other design, I don't know how much effort an RFC for it would be.

**Comment by jonas-schievink** [comment]
This is certainly RFC / Project Group territory, so closing in favor of that
