### ISSUE TITLE
Accessing DST field of packed struct calculates the wrong field address

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#80925]
Execute with Miri:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7e7d31feebbea4c3caceaccff1fa6bac

The problem is that https://github.com/rust-lang/rust/blob/6526e5c772f2da07db745c94ca6bb0a591a39ba4/compiler/rustc_codegen_ssa/src/mir/place.rs#L181-L182 and https://github.com/rust-lang/rust/blob/6526e5c772f2da07db745c94ca6bb0a591a39ba4/compiler/rustc_mir/src/interpret/place.rs#L413 do not take the reduced field alignment into account and calculate the offset as-if the standard alignment was in place.

**Comment by mahkoh** [comment]
The labels are incorrect. Neither does this require nightly, nor is it related to const-eval. This is I-unsound on stable.

**Comment by apiraino** [comment]
Assigning `P-medium` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2380925.20Accessing.20DST.20field.20of.20packed.20struct.20calculates.20the.20.E2.80.A6) and removing `I-prioritize`.

**Comment by nikomatsakis** [comment]
@rustbot labels -T-types

Discussed in types team on-site -- we think this is a MIR building bug, in any case, not part of T-types.

Throwing hot 🥔 back to compiler team.

**Comment by RalfJung** [comment]
> we think this is a MIR building bug

It was actually a bug in the codegen backend, introduced when support for `packed(N)` was added -- the existing code has logic that assumed "if it is packed then alignment is 1", and that was never re-visited.

**Comment by RalfJung** [comment]
Ah, scratch that -- there was a different related bug (the size_of_val / align_of_val computation for packed structs with `dyn Trait` tail was wrong), caused by what I said above.

This here was caused by the codegen backend just never considering packed types when computing the offset of the unsized field. Almost always this happened to work since the unsized field is a slice/str and so its alignment (and therefore its offset) is dynamically known, but when dyn trait tails are involved this starts to go wrong.
