### ISSUE TITLE
rustdoc documents `mut self` as `mut self: Self`

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#81289]
Rustdoc on [nightly documents][1] methods have signature of `fn(mut self)` as `fn(mut self: Self)` while it only has to document it as `fn(self)`.
![image](https://user-images.githubusercontent.com/15225902/105565172-0823c800-5d58-11eb-9347-c2d7a5743021.png)

On [rustdoc stable][2], things are normal: 
![image](https://user-images.githubusercontent.com/15225902/105565195-2b4e7780-5d58-11eb-9eb0-a11be199549e.png)

### Meta

`rustc --version --verbose`: Version 1.49.0 (e1884a8e3 2020-12-29)

[1]: https://doc.rust-lang.org/nightly/std/io/struct.BufWriter.html#method.into_inner
[2]: https://doc.rust-lang.org/1.49.0/std/io/struct.BufWriter.html#method.into_inner

**Comment by LeSeulArtichaut** [comment]
I'd like to investigate this :)

**Comment by LeSeulArtichaut** [comment]
searched nightlies: from nightly-2020-12-29 to nightly-2021-01-22
regressed nightly: nightly-2021-01-09
searched commits: from https://github.com/rust-lang/rust/commit/c8915eebeaaef9f7cc1cff6ffd97f578b03c2ac9 to https://github.com/rust-lang/rust/commit/26438b473883ea607b30288e461187f0fb2fe589
regressed commit: https://github.com/rust-lang/rust/commit/9155a9dae522bbedd42b4a11366d8157da0614ec

This regressed in #80806, so this is probably caused by #80799

**Comment by LeSeulArtichaut** [comment]
This also affects
```rust
fn bar(mut foo) {}
```

Where `rustdoc` will generate:

```text
fn bar(mut foo: Foo)
```

**Comment by LeSeulArtichaut** [comment]
So a few observations:
- [`rustc_hir_pretty::param_to_string`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_pretty/fn.param_to_string.html) uses [`print_pat`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_pretty/struct.State.html#method.print_pat) which displays mutability in patterns, causing `mut` to be displayed
- the mechanism for detecting and eliding `: Self` works by [litterally checking if the pattern is `self`](https://github.com/rust-lang/rust/blob/4d0dd02ee07bddad9136f95c9f7846ebf3eb3fc5/src/librustdoc/clean/types.rs#L1152-L1154), but as `param_to_string` returns `mut self` instead of `self`, the comparison fails and `rustdoc` displays the `Self` type.

**Comment by LeSeulArtichaut** [comment]
I see two path to solving this bug:

1. Add an option for `rustc_hir_pretty::param_to_string` to not display the mutability in patterns
2. Just revert #80799

cc @jyn514 what do you think?

**Comment by jyn514** [comment]
I would prefer to go for 1, there's no reason to have two completely different functions for pretty-printing.

**Comment by camelid** [comment]
Assigning `P-medium` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2381289.20rustdoc.20documents.20.60mut.20self.60.20as.20.60mut.20self.3A.20Self.60) in the prioritization working group.

**Comment by camelid** [comment]
(now a beta regression)
