### ISSUE TITLE
Use grailsort for sort_unstable

### ISSUE THREAD

**Issue by MusicTheorist** [rust-lang/rust#81842]
Hello, Rust contributors!

I've been managing a bit of a passion project centered around Grailsort, a stable, in-place, O(n log n) worst-case sorting algorithm, for a while now. It was partially inspired by previous issues brought up in this repo, including https://github.com/rust-lang/rust/issues/19221 and
https://github.com/rust-lang/rfcs/pull/956#issuecomment-78504506.

Our project is currently focusing on rewriting and documenting Grailsort, with the hopes of making the algorithm much more readable and intuitive.

I was curious if there's still interest in implementing an in-place sort like this for Rust, especially because one of our contributors is maintaining a WIP Rust version of said rewrite in our repo.

https://github.com/MusicTheorist/Rewritten-Grailsort

Feel free to let us know what your thoughts are. Thanks for reading!

**Comment by jyn514** [comment]
Can you explain the difference between Grailsort and the current `sort_unstable` algorithm?

**Comment by 666666t** [comment]
The current [`slice::sort_unstable`](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.sort_unstable) is based off a variant of Pattern-Defeating Quicksort (PDQsort), which generally achieves a high performance in O(n log n) time, and is in-place (non-allocating), however is unstable as the name implies, meaning values which respond as equal within the bounds of the Eq trait may be re-ordered, which is generally undesirable and the reason why (slice::sort)(https://doc.rust-lang.org/std/primitive.slice.html#method.sort) exists.

(slice::sort)(https://doc.rust-lang.org/std/primitive.slice.html#method.sort) is based in Timsort, a particularly adaptive version of quicksort which is fairly quick, maintains O(n log n) time, and is stable, ensuring elements that are equal by whatever comparison metric is provided are not rearranged. However, it does use allocations, requiring O(n) extra space in the form of temporary storage half the size of the given slice, meaning it is out-of-place.

Block merge sorts, such as Grailsort (and certain WIP derivative projects), in contrast, Balance the conditions of the prior 2 sorts, producing a sort that maintains fair performance in O(n log n) time, maintains stability between values, *and* can be executed in-place, with zero additional allocations for buffers or extra space.

**Comment by gaming32** [comment]
By “certain WIP derivative projects,” you mean Holy Grailsort? (there’s also Kota, Ecta, and Helium)

**Comment by 666666t** [comment]
> By “certain WIP derivative projects,” you mean Holy Grailsort? (there’s also Kota, Ecta, and Helium)

Correct, though given the original focus of this issue cites Grailsort in particular, It seemed preferable to keep the focus on that, while Holy Grailsort and similar WIP projects seek to improve adaptability and certain other aspects but generally don't appear as complete as the current Grailsort rewrites.

**Comment by 666666t** [comment]
Regardless, as for a generic run-down of the algorithm itself;

Grailsort works by maintaining an in-place buffer of unique values which are collected from the slice at the beginning, generally of some power of 2 size which scales with sqrt(n). It uses this in-place buffer (which is guaranteed to be stable by only collecting unique values) to traverse the array, performing in-place merges with the provided space. For fragments which are small enough to be merged, it does this outright, in one piece. For fragments which are larger than the available in-place buffer, the fragments are merged in "blocks", using a method of dividing the merge operation which involves "tagging" of blocks and fragments to ensure stability. After all fragments are merged, the in-place buffer is re-inserted to the slice, using a method of block rotations for quick insertion.

I'm certainly not the most versed in explaining the algorithm as a whole, but that should give a short idea of how the parts of the algorithm function in theory.

**Comment by 666666t** [comment]
Ah, sorry, I should make it clear for noting;

Grailsort is a stable sort, in-line with [`slice::sort`](https://doc.rust-lang.org/std/primitive.slice.html#method.sort), but is in-place, requiring no extra allocations, unlike the existing implementation. [`slice::sort_unstable`](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.sort_unstable) is in-place, but it lacks the stability guarantee of  [`slice::sort`](https://doc.rust-lang.org/std/primitive.slice.html#method.sort) or Grailsort, which puts block merge sorts "in between" the two, more akin to something like a `slice::sort_inplace` type method, with the stability guarantees of [`slice::sort`](https://doc.rust-lang.org/std/primitive.slice.html#method.sort) and in-place nature of [`slice::sort_unstable`](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.sort_unstable), at the cost of some speed (while still remaining in O(n log n) time, however).

**Comment by MusicTheorist** [comment]
Right, definitely want to make clear Grailsort is a stable sort. It's not unstable.

**Comment by scottmcm** [comment]
How does its speed compare to `slice::sort`?

**Comment by MusicTheorist** [comment]
@scottmcm While Grailsort has a solid design to it, there are many flaws and opportunities to micro-optimize which generally make a "vanilla" implementation slower than Timsort.

Generally speaking, I would characterize Grailsort as decently cache-friendly due to relatively simple linear memory accesses while also scaling pretty favorably. According to the original author, comparisons are about 1.6 * n log n and writes are 2.1 * n log n in the worst-case.

Grailsort is nowhere near as adaptive as Timsort, and we're pretty sure its best case is O(n log n).

For what it is, I think it's pretty clever and impressive but definitely has some kinks that need to be worked out.

**Comment by the8472** [comment]
Is the issue title correct? Would you intend to replace the stable or the unstable sort implementation?

**Comment by nagisa** [comment]
> is generally undesirable and the reason why `slice::sort` exists.

Its the other way around. The `slice::sort_unstable` has been added because people felt the potential performance increase with an unstable sort is worth the extra API surface over `slice::sort`. The desirable properties for the `sort_unstable` are in-place first and speed second. If the `unstable_sort` is replaced with a slower algorithm that's stable, then the API loses half of its intended purpose.

That said I'd welcome improvements to the stable `slice::sort` if there are any to be had.

**Comment by MusicTheorist** [comment]
@the8472 To be clear, I wasn't aiming to necessarily replace any functions in Rust. I was asking if people still were interested in a *non-allocating* sort.

**Comment by 666666t** [comment]
(Or at least, a non-allocating stable sort, in this case.)

**Comment by ecstatic-morse** [comment]
I wrote an [in-depth explanation](https://ecstaticmorse.net/posts/grailsort) of the Huang and Langston-style block sort (grailsort) as well as a [Rust implementation](https://github.com/ecstatic-morse/MrrlSort). Perhaps this will help potential reviewers to understand the block sort paradigm. I looked at some of the implementations in the Rewritten Grailsort project, but it didn't seem to close the [documentation gap](https://github.com/rust-lang/rust/issues/19221#issuecomment-70445816) between grailsort and "wikisort". In the process, I was able to implement the block tagging scheme described by Huang and Langston, although I'm not sure if halving the size of the internal buffer is actually worth the extra bookkeeping.

Personally, I would not recommend we switch `sort` to a block sort given the complexity and overhead compared to merge sort. The addition of a version of `std` that propagated allocation errors or a compelling use for a stable sort in `no_std` environments might change my mind though.

**Comment by tstj** [comment]
> Personally, I would not recommend we switch sort to a block sort given the complexity and overhead compared to merge sort.

I agree, currently there is PR for changing the stable sort, which looks complex, too.
Also, GrailSort is always slower than the current stable sort, mostly 1.5 to 2 times slower and in the best case of the current stable sort GrailSort is more than 10 times slower. The current stable sort can be easily optimized to use stable in place Symmerge for cases where the arrays to merge have very different lengths (symmerge is 2 or 3 times faster here). Also, Symmerge outperforms all other linear merging routines when there are not many unique elements, but that's hard to find out with TimSort, so it's not helpful here.
The GrailSort implementation linked above is also maybe a bit buggy (I showed an example input that panics in the issues).

An additional optimization that would make the current TimSort-based stable sort 1-3% faster for all inputs would be to replace the outer loop (which does hard to understand "invariant checks") by an iteration over a log2(n) runs stack, where the index of the array is used as a merge counter (the current runs stack reallocates, is not fixed size and probably has a higher max size than log2(n)).

**Comment by Enselic** [comment]
Triage: Thank you for reporting. Always interesting to learn about new sorting algorithms.

> While Grailsort has a solid design to it, there are many flaws and opportunities to micro-optimize which generally make a "vanilla" implementation slower than Timsort.

Then let's close this issue for now, but feel free to reopen when the Grailsort implementation outperforms what Rust currently has!

**Comment by TS60** [comment]
I want to add that it is possible to stay with the current algorithm and just replace the merge routine that currently requires `N/2` external memory by an external variant of Chen's unstable inplace algorithm (see [A simple algorithm for in-place merging](https://www.sciencedirect.com/science/article/abs/pii/S002001900500339X)). Such a merge routine would require $2\cdot\sqrt{N}$ external memory of size `T` and additionally $1\cdot\sqrt{N}$ external memory of size `usize`. So, in total it requires $O(\sqrt{N})$ external memory. The nice thing here is that we have the exact same number of comparisons ($m+n-1$) for merging two sequences of lengths $m$ and $n$) and also in the exact same order like the current merge routine that requires $N/2$ external memory.

The total number of moves (writes to memory) would nonetheless grow from $1.5\cdot N$ to $2\cdot N$.
Note that Chen's inplace algorithm is unstable by default but will become stable with external memory of the size mentioned above and also will get the optimal number of comparisons because the block search is not required anymore and also fixing the last two blocks of size $\sqrt{N}$ each can now get finished very easily because the elements don't get out of order here. Because of this, also the high number of cache misses will go away.

I assume this will be a better alternative because the algorithm will still use the highly adaptive PowerSort run scanning and still requires the same number of comparisons.

Though, I have not implemented this and just assume that a good implementation (branchless calculation of next buffer positions etc.) will have nearly the same performance like the current merge routine or even better because nearly all of the blocks operate on inplace memory here.

Note that GrailSort never can outperform the current stable sort because it first has to collect the first $O(\sqrt{N})$ unique elements to use as an internal buffer. After this it will use the normal merging routine. Thus, it requires at least $3\cdot N\cdot\log_2{N} + O(N)$ writes because it merges using swaps and also a slightly higher number of comparisons that comes from the collection of unique elements first.

I assume, the method I proposed above is the best possible way to reduce the external memory without losing too much.
