### ISSUE TITLE
GlobalAlloc docs example crashes

### ISSUE THREAD

**Issue by ijackson** [rust-lang/rust#81847]
I cut and pasted [the example for `GlobalAlloc`](https://doc.rust-lang.org/std/alloc/trait.GlobalAlloc.html) from the stdlib docs into the playground.  Contrary to the implications in the documentation, the program does not run to completion.  Instead, it prints

```
memory allocation of 4 bytes failed
timeout: the monitored command dumped core
/playground/tools/entrypoint.sh: line 11:     8 Aborted                 timeout --signal=KILL ${timeout} "$@"
```

I think this is fine behaviour.  The example is wrong and should be fixed somehow.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=54f5b4b24c19b64962d35ec4031ee4a5

<strike>I was doing this because I am trying to write a test case for the stdlib which involves a stunt allocator.  So far my `#[global_alloc]` annotation in a file in `library/std/tests/` does not seem to be effective.  I suspect that whatever is getting in my way might also get in the way of adding a test case specifically for `#[global_alloc]`.</strike>  Looks like `src/test/ui/` is the right place and I should read the dev docs...

The [example from `std::alloc::System`](https://doc.rust-lang.org/std/alloc/struct.System.html) works correctly.

**Comment by vitalyd** [comment]
My $.02 is that #81864 is a bit too involved for an example.

The existing example can be fixed by delegating to the `System` allocator up until `main()` runs, at which point the sample allocator can take effect.  Something like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0ad3836e3af007ddfa6328405dcd4e72).
