### ISSUE TITLE
Exclusive range patterns in function arguments are broken

### ISSUE THREAD

**Issue by LeSeulArtichaut** [rust-lang/rust#81903]
I tried this code:

```rust
#![feature(exclusive_range_pattern)]

fn foo(0..256: u8) {}
```

I expected to see this happen: code compiler successfully

Instead, this happened: `rustc` violates mathematics and claims that `0 >= 256`:
```text
error[E0579]: lower range bound must be less than upper
 --> src/main.rs:9:8
  |
9 | fn foo(0..256: u8) {}
  |        ^

error: aborting due to previous error
```

The error text being wrong probably has the same cause as #68972.
However, the code should compile (?) since `0..256` is an irrefutable pattern for an `u8`

### Meta

`rustc` version: 1.52.0-nightly (2021-02-07 9778068cbc1e06cc3685), from playground

cc #37854

**Comment by estebank** [comment]
The pattern themselves aren't broken, it's just that the diagnostic is confusing as this code should have been written as:

```rust
#![feature(exclusive_range_pattern)]

fn foo(0..=255: u8) {}
```

We should have suggested that instead. The reason is because `256u8` isn't valid and overflows to `0u8`, which is the same as the start of the range, [which gives you that error](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b058d33eb8917835caee34c6adacd106).

**Comment by sladyn98** [comment]
@estebank Hey, I am a bit new to contributing to rust, is this something easy that can be fixed? If yes I would like to give it a shot.

**Comment by LeSeulArtichaut** [comment]
Hmm, I thought I tested that `0..256` worked in other contexts, but I think I forgot to force the type to be `u8`, my bad.

**Comment by LeSeulArtichaut** [comment]
I'll close this in favor of #68972.

@sladyn98 feel free to claim that issue if you want to try to fix it

**Comment by estebank** [comment]
@sladyn98 the error is being emitted here

https://github.com/rust-lang/rust/blob/50e1ae15e9f3035b06bae00e1b1dc7a358546d3e/compiler/rustc_mir_build/src/thir/pattern/mod.rs#L455-L464

You would also need access to the AST to figure out that the issue is an overflow, unless the const value of variant `Scalar` actually has the right value (255 instead of 0). If it does, it just requires you to see that the start is 0 and the end is the maximally representable integer in the type being used and add a `note` to the error explaining what is happening. In the former case, you will need to pass along the expressions available here into the `fn` emitting the error:

https://github.com/rust-lang/rust/blob/50e1ae15e9f3035b06bae00e1b1dc7a358546d3e/compiler/rustc_mir_build/src/thir/pattern/mod.rs#L521-L529
