### ISSUE TITLE
How about renaming `Arc::{increment,decrement}_strong_count` to `Arc::strong_count_{increment,decrement}`?

### ISSUE THREAD

**Issue by arniu** [rust-lang/rust#81962]
According to Cambridge Dictionary, [increment](https://dictionary.cambridge.org/dictionary/english/increment) and [decrement](https://dictionary.cambridge.org/dictionary/english/decrement) both are nouns.

The naming of `Arc::{increment,decrement}_strong_count` is weird.
How about renaming `Arc::{increment,decrement}_strong_count` to `Arc::strong_count_{increment,decrement}`?

**Comment by slerpyyy** [comment]
I don't think this is a problem with the std crate, but rather with the Cambridge dictionary. 

The Cambridge dictionary might not be the best source if it comes to CS-specific vocabulary, because that's not what it's made for. It will also tell you that neither "[lock](https://dictionary.cambridge.org/dictionary/english/lock)" nor "[atomic](https://dictionary.cambridge.org/dictionary/english/atomic)" have anything to do with concurrency. 

As a side note, the Oxford dictionary lists a verb definition for both "[increment](https://www.lexico.com/definition/increment)" and "[decrement](https://www.lexico.com/definition/decrement)".

**Comment by Enselic** [comment]
Triage: Closing as won't fix.
