### ISSUE TITLE
Any should be marked unsafe

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/rust#82466]
Any should be marked unsafe as it currently relies on Rust not having specialization. While it is extremely unlikely Rust will ever have specialization, marking Any unsafe should be fully backwards-compatible, so there's no good reason not to do it, and there are some good reasons for doing it today rather than when we do get specialization. In particular, we feel it would serve good documentation purpose that Any makes some assumptions.

Anyway, it's mostly just a strong feeling we have about it. We were thinking about [generic generics](https://internals.rust-lang.org/t/generic-generics/14080/7) when we noticed Any isn't marked unsafe, while a hypothetical `AnyA<'a>` would probably have to be marked as unsafe.

(Hey, at least marking a trait like Any as unsafe, unlike most other cases of marking things as unsafe, should be backwards-compatible, yeah?)

**Comment by moxian** [comment]
Can you elaborate on how would `Any` exhibit memory unsafety in presence of specialization?

**Comment by SkiFire13** [comment]
I can't see how you could specialize/override any `Any`'s method, even with full specialization feature:

* All the `downcast` methods use `<dyn Any>::is` which can't be specialized because it isn't a trait method.

* `<dyn Any>::is` internally uses `Any::type_id`, however you can't specialize it because it's not declared as `default` in the blanklet `impl`. 

* You can't even declare other non-overlapping `impl`s because the blanklet impl already covers all the possible `impl`s (notice that `Any` has a bound on `'static`).

**Comment by jonas-schievink** [comment]
This was rejected in https://github.com/rust-lang/rust/pull/67562, so closing.

Even with specialization, `Any` would not be unsafe though, since its only impl is not specializable.

**Comment by SoniEx2** [comment]
What's wrong with showing it as an unsafe trait? Send and Sync are unsafe traits, and nobody complains about making use of them.
