### ISSUE TITLE
span_to_snippet is broken

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#8256]
Passing it a span that I get _from rustc_ fails with:

rust: task failed at 'assertion failed: `(left == right) && (right == left)` (left: `{__field__: 9860}`, right: `{__field__: 57921}`)', /home/cmr/hacking/rust-benching/src/libsyntax/codemap.rs:376

To reproduce: build dd598e1 from cmr/rustdoc_ng, run it on libstd.

@jbclements maybe?

**Comment by pnkfelix** [comment]
I think I'm going to change this code to return `Result` instead `Option`, so that we have a prayer of tracking down on the caller's side what the cause of the problem is.

**Comment by pnkfelix** [comment]
(i encountered this when adding a revision to the syntax extension that implements `for`)

**Comment by steveklabnik** [comment]
Triage: it looks like @pnkfelix did some work, but I'm unaware of any further things. Is there a way we can get a reproduction of this issue?

**Comment by Mark-Simulacrum** [comment]
I feel like this should be closed since reproducing is hard, and I see that there have been some efforts (e.g., #21980, and a few more) to fix this. As such, I'm closing, but please reopen if we want to continue tracking this--preferably with some steps that could be taken to at least reproduce this.
