### ISSUE TITLE
Upgrading to 2018 edition with nameless trait arguments gives opaque error message.

### ISSUE THREAD

**Issue by edre** [rust-lang/rust#82729]
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2d5990f9266a843f299cffb49ea24f36

The current output is:
```
error: expected one of `(`, `...`, `..=`, `..`, `::`, `:`, `{`, or `|`, found `)`
 --> src/main.rs:3:46
  |
3 |     fn apply(&self, &mut <Self::G as Game>::S);
  |                                              ^ expected one of 8 possible tokens
```

Ideally the output should look like:
```
error: traits require argument names
```

This was very painful to debug, because there's some type shenanigans going on, and it wasn't clear if some of those didn't work in the 2018 edition now.

**Comment by ehuss** [comment]
Just FYI, it is usually recommended to use `cargo fix --edition` to transition from 2015 to 2018.  That will automatically fix the syntax so it works on both editions.

If `cargo fix` isn't an option, or if you want to do it manually, you can use the `#![warn(rust_2018_compatibility)]` attribute in the crate root while still on the 2015 edition. This will cause it to show warnings for each thing that needs to be fixed. If your editor supports "quick fixes", it can automatically fix each one.

I agree that the error could be better. It was supposed to be fixed by #53990, but it seems to be confused by reference patterns.

```rust
// Gives bad error on 2018.
trait Foo {
    fn f(&mut i32);
}
```
