### ISSUE TITLE
Tracking Issue for const_replace

### ISSUE THREAD

**Issue by usbalbin** [rust-lang/rust#83164]
Feature gate: `#![feature(const_replace)]`

This is a tracking issue for making the functions `mem::replace` and `ptr::replace` `const fn`.

### Public API

```rust
mod mem {
    pub const fn replace<T>(dest: &mut T, src: T) -> T;
}

mod ptr {
    pub const unsafe fn replace<T>(dst: *mut T, mut src: T) -> T;
}
```

### Steps / History

- [x] Implementation: #83091
- [x] Final commenting period (FCP)
- [ ] Stabilization PR - #130954

### Unresolved Questions

- None yet.

**Comment by RalfJung** [comment]
This got reverted again by #86003, but hopefully we can re-land it soon.

**Comment by Zizico2** [comment]
status on this? is any help needed?

**Comment by RalfJung** [comment]
@rust-lang/libs-api I think this is ready to be stabilized, given that const_mut_refs is in FCP. :)

This is about const-stabilizing two already-stable functions:
```rust
mod mem {
    pub const fn replace<T>(dest: &mut T, src: T) -> T;
}

mod ptr {
    pub const unsafe fn replace<T>(dst: *mut T, mut src: T) -> T;
}
```

**Comment by RalfJung** [comment]
@Amanieu @BurntSushi @joshtriplett @m-ou-se would be nice to get this (and some of the other `&mut`/`*mut` APIs) into the next release so that const_mut_refs is not quite so bare-bones when it lands. :D  Also, this particular feature fate blocks `replace`/`take` on `Option` so there's a bit of a dependency chain here.
