### ISSUE TITLE
Doc comments causing build errors

### ISSUE THREAD

**Issue by hquil** [rust-lang/rust#83492]
`rustc 1.51.0 (2fd73fabe 2021-03-23)`
`rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)`

Docstrings placed at a few selected positions that cause either a warning (`good`), an unrelated error (`bad`) or both (`ugly`).

```rust
fn good(num: u8) -> bool {	
   match num {
      3 => true,
      /// warning: unused doc comment
      _ => false,
   }
}

fn bad(num: u8) -> bool {
   if num == 3 {
      true
   }
   /// error[E0308]: mismatched types
   /// error: expected expression, found keyword `else`
   else {
      false
   }
}

fn ugly(num: u8) -> bool {
   /// error[E0658]: attributes on expressions are experimental
   /// warning: unused doc comment
   num == 3
}
```

On the third example we at least get an additional warning to point us in the right direction.
The second example can become nightmare to catch :3

**Comment by JohnTitor** [comment]
Note that the doc comment is equal to `#[doc("")]` so all the errors/warnings are _valid_. On `ugly`, it should be reasonable to emit an error and a warning both since it isn't straightforward to have the user add a feature flag and remove the error, to tell that rustdoc doesn't do anything there. On the second, we could improve the diagnostics by recovering at some point, I imagine.

**Comment by scottmcm** [comment]
I concur that errors for these things are absolutely by design.  One can always use normal `//` comments in these places.

So at most this is a "would be nice if the error hinted removing a `/`" issue, I think.
