### ISSUE TITLE
compiletest should check for possible typos in annotated test directives

### ISSUE THREAD

**Issue by klensy** [rust-lang/rust#83551]
This should help with things like https://github.com/rust-lang/rust/pull/83348#discussion_r602685312
Levenshtein distance with list of known directives will be enough?

**Comment by osa1** [comment]
> Levenshtein distance with list of known directives will be enough?

Is this to distinguish an ordinary comment from a directive?

**Comment by klensy** [comment]
@osa1 
Yes, this is the first idea that came into my mind.

**Comment by jieyouxu** [comment]
This is easier if/when we port over all current `//` directives in all test suites and modes over to use `ui_test`-style `//@` directives, so that it is easier to detect between regular comments and directives.

Other bootstrap tools like tidy should also probably use something else to distinguish them from regular comments. Otherwise, trying to check between a valid directive vs comment is really cursed, and comments like

```
// testing testing one two three
// ignore-test is a very useful
// directive to have in compiletest
```

gets treated as `// ignore-test`, making it quite surprising.
