### ISSUE TITLE
Tracking issue for `explicit_generic_args_with_impl_trait`

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/rust#83701]
This is a tracking issue for the `explicit_generic_args_with_impl_trait` feature gate.
There has not been an RFC for this.

### Steps
- [x] Implement (#86176)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions
- ~~We should add a bit extra info when there are extra generic args and `impl Trait` (see https://github.com/rust-lang/rust/pull/86176#discussion_r680613890)~~

### Implementation history

- Initital implementation in #86176

---

# Background

Currently you cannot specify explicit generic arguments if a function uses `impl Trait` anywhere its arguments. This is pretty annoying because it heavily restricts what kind of code you can write with functions that use `impl Trait` compared to what is possible with explicit generics.

This difference between `impl Trait` and explicit is in my opinion very unintuitive, it feels like you should be able to use them together. It is even mentioned as something in the original tracking issue for `impl Trait` (https://github.com/rust-lang/rust/issues/44721) that this would be desirable behaviour, but that there was a decision to hold off for the time being. That issue has been closed for long time, and there hasn't been any follow up as far as I can tell. So I'm opening up a new issue to discuss the feature and hopefully track adding it to the rust compiler.

### Examples

```rust
#![feature(explicit_generic_args_with_impl_trait)]

fn find_from<I>(iter: impl IntoIterator<Item=impl Into<I>>, is_match: impl Fn(&I) -> bool) -> Option<I> {
    for i in iter {
        let i = i.into();
        if (is_match)(&i) {
            return Some(i)
        }
    }
    
    None
}

fn main () {
    matches!(find_from::<u32>(vec![2u8, 3, 4, 5,], |&x| x == 5), Some(5u32));
}
```

### Related Issues
- https://github.com/rust-lang/rust/issues/71869

**Comment by alexxbb** [comment]
It's unfortunate that it's not possible, I just hit this issue and it stopes me from having a nice API. Here's my use case:

```rust
impl Parameter {
    pub fn set<T: ParmType>(&self, value: impl AsRef<[<T as ParmType>::Type]>) -> Result<()> {
        T::set(self.node, &self.info, value)
    }
}

// 
let parm: Parameter;
parm.set::<i32>([1,2,3]);
```

**Comment by jhpratt** [comment]
With the only unresolved question listed being diagnostics, is there anything holding up stabilization? Other than a stabilization report of course.

**Comment by nbdd0121** [comment]
Probably it's still too recent. I only implemented this in June, and I doubt it has been widely used or tested in the ecosystem. This also needs a lang team FCP or RFC.

**Comment by jhpratt** [comment]
FCP was a given. Time-wise makes sense, though.

**Comment by XAMPPRocky** [comment]
@nbdd0121 Thanks for implementing this! I've updated the example to use the new feature so there's now at least one use in the wild. 🙂

**Comment by WaffleLapkin** [comment]
@nbdd0121 What is the path towards stabilization of this feature? Is it old enough yet? 👀

**Comment by Wopple** [comment]
For anyone afflicted by this, the workaround I found was to specify the type parameters in the value you're binding to. For example:
```rust
// instead of this:
let v = f::<u64>();

// do this:
let v: F<u64> = f();
```

**Comment by c410-f3r** [comment]
Is there anything left holding up stabilization? I guess enough public testing is not a concern anymore

**Comment by nbdd0121** [comment]
There is a discussion on Zulip about this: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Stabilization.20of.20.60explicit_generic_args_with_impl_trait.60

**Comment by Lipen** [comment]
Another "workaround" is to use "normal" generic type instead of the `impl` sugar and use `_` (inside turbofish) when calling in order to auto-derive the "unnecessary" type.
(example somewhat similar to @alexxbb's):
```rust
// "Original" function
// `T` is the type you want to obtain after calling `get`.
// `arg` is some additional value for which you initially use `impl`-type,
//   and you want it to be automatically derived by the compiler.
// Here, the type of `value` is `Into<...>`, but it might be `IntoIterator`, `AsRef`, etc
fn get<T>(arg: impl Into<...>) -> T {...}

// The call side might look like this:
let result = get(...); // this doesn't compile since the compiler cannot derive `T`
let result = get::<i32>(...); // intuitively OK, but for now, we can't do this
                              // (the current issue is exactly about this)
let result: i32 = get(...); // OK, but sometimes it is not possible to specify `T` on the lhs,
                            // because sometimes there is no lhs (e.g. inside another expression)
```
```rust
// "Fixed" function
// We can change the original definition to the following:
fn get<T, X>(arg: X) -> T where X: Into<...> {...}

// And use it like that:
let result = get::<i32, _>(...); // note the `_` as the second type parameter
                                 // it is being auto-derived, and everyone is happy!
```

**Comment by nrc** [comment]
> There is a discussion on Zulip about this: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Stabilization.20of.20.60explicit_generic_args_with_impl_trait.60

Summarising the Zulip discussion, there was mostly discussion on whether and how to support `impl Trait` in explicit generic arguments, rather than about the feature itself. In particular a path for converting an `impl Trait` type to a generic type. There was nobody against stabilising this feature and implied or explicit support for it from everyone involved.

To paraphrase, I think the only risk with stabilisation is that it might prevent some syntaxes for explicit specification of `impl Trait` implicit generics. However, given that the desire to not require explicit generics for `impl Trait` even when other generics are explicitly specified, and the desire for back compat when changing `impl Trait` types, it seems to me that nearly any proposal must allow specifying the generics without the `impl Trait` or any indication that they might (e.g., a `..` syntax).

(My personal view on explicit types for APIT is that it only makes sense to specify them in the argument list rather than in the turbofish, similar to type ascription, since there is no way to map the implicit type variables to an explicit one either using position (due to nesting and back compat) or via naming).

I would like to propose we stabilise this feature (`explicit_generic_args_with_impl_trait`) as is.

From the OP, there is an unresolved question ("We should add a bit extra info when there are extra generic args and impl Trait (see https://github.com/rust-lang/rust/pull/86176#discussion_r680613890)"), but this seems to be more of a TODO item than a question which needs answering (we just need to improve the error message). So I think that should just be changed to a check box.

Assuming there are no objections in the next few days, I'm happy to do the outstanding work items and then make a stabilisation PR. I'd also be happy if somebody else wants to do this.

**Comment by petrochenkov** [comment]
>I think the only risk with stabilisation is that it might prevent some syntaxes for explicit specification of `impl Trait` implicit generics.

Until today I thought that `explicit_generic_args_with_impl_trait` is exactly for explicitly specifying `impl Trait` implicit generics.
```rust
fn foo(foo: impl Foo) {}

foo::<u8>();
```
But looks like it's not the case, so it further cements the approach that implicit generic parameters introduced by `impl Trait` are special magic, and not just sugar for regular generic parameters.
So the main goal of explicit `T` and `impl Trait` being interconvertible (that enables using `impl Trait` in older public interfaces in particular) is not achieved.
So this is not acceptable.

**Comment by petrochenkov** [comment]
>there is no way to map the implicit type variables to an explicit one either using position (due to nesting and back compat)

I'm not sure why this is an issue.
Type parameters for `impl Trait`s are created in "left to right" aka DFS order.
Complex nesting is rare in practice so this works fine.
C++ does this too.

**Comment by oli-obk** [comment]
As long as we keep the door open to allowing argument position impl trait to be specified later (via the mentioned `foo<u32, ...>()` syntax, which could be useful in general), I think it would be fine to punt on the exact way to specify them to later

**Comment by scottmcm** [comment]
While I'm a fan of offering `foo::<u32, ..>()` to avoid `foo::<u32, _, _, _, _>()` (analogously to tuple struct patterns), it not obvious to me that we ever *need* to allow turbofishing an APIT.

Given that it appears in an argument, there's always a way to specify it other than by turbofishing, right?

**Comment by oli-obk** [comment]
Not right now. You can cast your type, but that may break inference. You could use a generic identity helper and specify the generic param of that.

The problem stays that you can't make your APIs prettier without a breaking change, because users may already be turbofishing your functions.

**Comment by nrc** [comment]
> > there is no way to map the implicit type variables to an explicit one either using position (due to nesting and back compat)
> 
> I'm not sure why this is an issue. Type parameters for `impl Trait`s are created in "left to right" aka DFS order.

This seems really nasty to explain, having to specify a search order seems the opposite of intuitive.

> C++ does this too.

I don't think this makes it OK for Rust, given how painful C++ generics are in general, this is probably a reason not to do it

> Not right now. You can cast your type, but that may break inference. You could use a generic identity helper and specify the generic param of that.

Type ascription?

> But looks like it's not the case, so it further cements the approach that implicit generic parameters introduced by impl Trait are special magic, and not just sugar for regular generic parameters.

Sugar or magic is an implementation issue. We should strive to do what is best for the user.

> So the main goal of explicit T and impl Trait being interconvertible (that enables using impl Trait in older public interfaces in particular) is not achieved.

Main goal for whom? This seems like a nice to have rather than a main goal

> So this is not acceptable.

Not acceptable *to you*. Everything is a trade-off and getting a good design here will mean compromising on some values/goals.

It seems to me that the goals of making `impl Trait` and explicit generics interconvertable, and making `impl Trait` as ergonomic as possible as a feature in its own right are in conflict when it comes to using turbofish.

To make things interconvertable, I think there is only one solution which is that implicit generics must always be specified when using turbofish,  and must be specified in order and furthermore that the explicit generics must be declared in the same order in which they are first used (which is already a backwards incompatible change). But this loses some of the advantages of impl Trait: it is nice from the perspective of writing an API to be able to say: these are the parameters that the user might specify and these are the ones they shouldn't have to. It makes using turbofish with `impl Trait` awkward in some situations. It makes converting between `dyn Trait` and `impl Trait` or from a concrete type to `impl Trait` a breaking change. 

Some examples:

```rust
fn foo<T>(a: impl Bar, b: T) {}

// Awkward, comparing actual to formal generic args is weird
foo::<_, String>(some_bar, some_string);

fn baz<T>(a: T, b: impl Bar, c: T) {}

// Confusing, since T appears before and after impl Bar
baz::<String, _>(some_string, some_bar, some_string);

// Confusing, which comes first?
fn qux<T>(a: impl Bar<T>)
// More confusing
fn qux2<T>(a: impl Bar<T, impl Bar>)

// Confusing, does the return type come before or after argument usage.
// Non-ergonomic, will be common to specify `T`, very uncommon to specify the type for impl Context.
// Back compat hazard to change `impl Context` to `dyn Context` or to a concrete context type.
fn return_t<T>(c: &impl Context) -> T
```

**Comment by petrochenkov** [comment]
@nrc 
>Main goal for whom? This seems like a nice to have rather than a main goal

For anyone who wants to use APIT without thinking whether it's a public enough interface or not.

APIT is a great convenience feature, it's unfortunate to limit it in such a way and accompany any documentation for it with a big CAVEAT clause.
It's as if you couldn't change
```rust
pub fn foo<'a>(&'a u8) {}
```
to
```rust
pub fn foo(&'_ u8) {}
pub fn foo(&u8) {}
```
for "otherwise unused" lifetime parameters in public interfaces (*).
`impl Trait` is a very close analogue of this, but for "otherwise unused" type parameters.

In rustc I converted numerous `T: Trait`s to `impl Trait`s just for convenient syntax, without any *semantic* changes in the meaning, they were regular generic type parameters before and they are still regular generic type parameters after the change, and they can be changed back to the old syntax for any reason.
But I could do that only because all uses of rustc interfaces are controlled and we can deal with the breakage if necessary, I want the same thing to be available to all code using `T: Trait`.

From this experience I can say that the  `T: Trait` <-> `impl Trait` conversion is 1-2 orders of magnitude more common than `impl Trait` <-> `dyn Trait`.

>Sugar or magic is an implementation issue. We should strive to do what is best for the user.

Ok, let's use different wording, not sugar vs magic, but "different syntax for the same feature" vs "different feature", this difference is user-observable, it's not an implementation issue, see above for the user experience.

I'm on board with any other features allowing skipping generic arguments, like `foo<u8, ..>` or whatever.
They just need to be orthogonal to the `impl Trait` issue and apply equally to both explicitly and implicitly introduced type parameters.

(*) Thankfully it's not an issue for majority of lifetimes because they are late bound, but early bound lifetimes are affected by the same issue as `impl Trait` - https://github.com/rust-lang/rust/issues/42868.

**Comment by nrc** [comment]
So, I agree that everything else being equal I would like to make converting between T: Trait and impl Trait as easy as possible. However, I think that wanting to be able specify T: Trait parameters without specifying the impl Trait parameters is also desirable.

> Ok, let's use different wording, not sugar vs magic, but "different syntax for the same feature" vs "different feature", this difference is user-observable, it's not an implementation issue, see above for the user experience.

OK. They have different syntax, so they are different features. You are making a case that these different features should behave in the same way. Currently they do not. If you change T: Trait to impl Trait, then the turbofish rules mean that is backwards incompatible.

Not listing explicit types for impl Trait means that migrating from a concrete type to impl Trait is not a breaking change. It makes it possible for an API author to indicate which are the important type parameters for the caller to specify and which are a detail.

Also, as I pointed out previously, relying on the order of impl Trait usage is confusing and awkward. It also means that changing from T: Trait to impl Trait is only backwards compatible if the order of use matches the order of declaration, which is a detailed rule which is surprising and awkward to explain to users.

**Comment by petrochenkov** [comment]
>I think that wanting to be able specify T: Trait parameters without specifying the impl Trait parameters is also desirable

I agree with this, and suggest using `_` for such parameters as for any other parameters.
```rust
fn foo<T>(arg: impl Trait) {}

foo::<u8, _>(); // the argument for `arg` is inferred, not specified
```

*Then* we can add any sugar for omitting trailing `_`s, but that's an orthogonal issue.

>Also, as I pointed out previously, relying on the order of impl Trait usage is confusing and awkward. 

As I said above, I don't think it's an issue in practice because complex nesting is rare.
Also, I still don't understand why left-to-right order is confusing, if a person likes metaprogramming enough to use complex nesting of `impl Traits`, then understanding the ordering also won't be a problem for them.

>It also means that changing from T: Trait to impl Trait is only backwards compatible if the order of use matches the order of declaration

This is true, but it's still an improvement on the current situation.
It would be interesting to see some statistics on how common these cases are.

**Comment by oli-obk** [comment]
> `fn foo<T>(arg: impl Trait) -> T {}` which is exactly the kind of example where I'd like to specify just the `T`.

Hold up. I think you're talking past each other. I'm very confident that @petrochenkov is not proposing to interleave impl trait with explicit generics, but only to list all the impl traits after the explicit generics.

I also don't think there's a "flatten the tree" complexity here unless you are a compiler dev. For everyone else they just look at the function signature and count impl traits in source order ignoring nesting or such

**Comment by nrc** [comment]
> Hold up. I think you're talking past each other. I'm very confident that @petrochenkov is not proposing to interleave impl trait with explicit generics, but only to list all the impl traits after the explicit generics.

I don't think so. @petrochenkov's goal is that T: Trait and impl Trait are interconvertable without a breaking change. If all impl Trait generics are listed after explicit generics then the change would be breaking (unless you change only a postfix subset of generics).

> I also don't think there's a "flatten the tree" complexity here unless you are a compiler dev. For everyone else they just look at the function signature and count impl traits in source order ignoring nesting or such

My point is that, we never rely on source order ignoring nesting for anything semantic. Literal source order is really unintuitive when programming. Asking the reader to ignore nesting is what I think of as the mental tree flattening. Like if you read `Vec<T>` you read that as `Vec` *of* `T`, you don't read it as `Vec` then `T`.

**Comment by nrc** [comment]
> Sure, but where would that order differ here? If both intuitions result in the same thing, does it matter which one you're using?

I don't think there is a good intuition here. There is usually no link between type parameter order and value parameter order, and there is a proposal for linking the two, but only in the impl Trait case.

> I don't claim to speak for petrochenkov, but my impression was that it's not being proposed to be possible to convert every last example out there but only most of them

I'll wait for petrochenkov to clarify on whether impl Trait arguments should be grouped or not, but neither option looks good to me.

> If you don't have more than one per argument, it's again trivial

This is not quite right, there could be multiple generics in the single type, there could also be a return type.

Even with a single argument and a single generic type, if macros are involved, there could be all kinds of weirdness caused.

> If we close the door on specifying impl trait generic params, then that means we can't ever use it in all those libstd APIs like and_then and friends which are imo trivial, as the argument order is in the right order

I don't think we block this case. We could in the future allow the user to optionally specify actual type parameters in turbofish, grouped at the end of the parameters and in lexical order as long as we don't require syntax to opt out. That would allow back compat conversion from explicit types to impl Trait if the ordering is right, but not vice versa

E.g., for `fn foo<T>(a: T, b: impl U)` we allow `foo::<X>(instance_of_x, instance_of_u)` and `foo::<X, Y>(instance_of_x, instance_of_y)`. For `fn foo<T, U>(a: T, b: U)`, we allow `foo::<X, Y>(instance_of_x, instance_of_y)`.

**Comment by oli-obk** [comment]
> grouped at the end of the parameters and in lexical order as long as we don't require syntax to opt out

Now I'm confused. This is pretty much what's being proposed, only with a different syntax (no "...", just fewer or more args specified). All I was asking for at the start was to plan this now so by stabilizing this feature we also decide on how to proceed with specifying the implicit generics of impl trait in argument position. Either we have to add trailig dots now, or we don't ever for trailing underscores, but it's not something we should just force without consideration at this point

**Comment by nrc** [comment]
> Now I'm confused. ...

Heh, sorry!

Agree we need to consider the trailing dots now. I am in favour of not requiring them. I think that for full interconvertability, they are required. The difference between the informal proposal at the end of my last comment and petrochenkov's proposal is the dots and possible whether impl Trait arguments are grouped or ordered amidst the explicit generics. The difference in effect is that my proposal only permits changing from T: Trait to impl Trait backwards compatibly, whereas petrochenkov's permits impl Trait to T: Trait (in both cases, ordering permitting).

> All I was asking for at the start was to plan this now so by stabilizing this feature we also decide on how to proceed with specifying the implicit generics of impl trait in argument position.

I agree it is necessary to pick a direction now, I would like to avoid blocking stabilisation on a full design.

**Comment by petrochenkov** [comment]
>I'll wait for petrochenkov to clarify on whether impl Trait arguments should be grouped or not

I assumed that explicit parameters would go first, then synthetic parameters from `impl Trait`.
(That's what the implementation has been doing all this time, IIRC.)

**Comment by nrc** [comment]
OK, so I will spell out two alternative proposals and the consequences of those (@petrochenkov please let me know if I misrepresent anything, etc):

(I will follow the convention of calling the type arguments supplied by the caller 'actuals' and the type arguments declared by the callee 'formals'; I will use arguments/parameters interchangeably and will always mean *type* parameters unless explicitly calling them value parameters)

## Option 1 (@petrochenkov's proposal):

Now:

* If any actuals are specified, then all `impl Trait` actuals must be specified (though we can always use `_` as expected)
* `impl Trait` actuals are grouped together after all `T: Trait` actuals and are supplied in order of use of the types of formal value parameters
* CONSEQUENCE: if all `impl Trait` formals occur after uses of `T: Trait` formals in the value parameter types and return types, then:
  - it is backwards compatible to change `T: Trait` to `impl Trait` or `impl Trait` to `T: Trait`
  - it is backwards *incompatible* to change a concrete type (or `dyn Trait`) to `impl Trait`
* CONSEQUENCE: `fn foo<T>(ctxt: &impl Context) -> T` is called like `foo::<String, _>()`

Later:

Allow some postfix sublist of actual parameters to be elided either explicitly (e.g., using `, ...`) or implicitly.

## Option 2 (@nrc's proposal):

Now:

(i.e., stabilise `explicit_generic_args_with_impl_trait` as is)

* Cannot specify actual parameters for `impl Trait` formals in turbofish
* Presence of `impl Trait` formals does not prevent the use of turbofish for `T: Trait` parameters
* No extra syntax (e.g., `, ...`) is required

Later:

* Due to back compat, the 'now' constraints are kept
* We could discuss and design any system within those constraints. For the sake of comparison I will describe a system which is as close to option 1 as possible (other alternatives include not allowing actual parameters for `impl Trait` formals at all, but I don't think we need to discuss this as part of the stabilization of `explicit_generic_args_with_impl_trait`):
  - `impl Trait` actuals are always optional and their presence or absence is not indicated by special syntax
  - `impl Trait` actuals are grouped together after all `T: Trait` actuals and are supplied in order of use of the types of formal value parameters
  - CONSEQUENCE: if all `impl Trait` formals occur after uses of `T: Trait` formals in the value parameter types and return types, then:
    - it is backwards compatible to change `T: Trait` to `impl Trait`, but *not* `impl Trait` to `T: Trait`
    - it is backwards compatible to change a concrete type (or `dyn Trait`) to `impl Trait`
  - CONSEQUENCE: `fn foo<T>(ctxt: &impl Context) -> T` is called like `foo::<String>()`

Note the `foo` example I've used is a motivating case for me preferring option 2, the idea is that the concrete `Context` type should very rarely be specified, but the return type should often be specified.

**Comment by E-gy** [comment]
How about a double Turbofish? `foo::<Explicit><Implicit>(args)`

1. For a function without implicit/explicit traits, the other turbofish is ommitted.
2. If the implicit `impl Trait` need not be specified, only explicit turbofish is used.
3. We keep backwards compat since the explicit turbofish is the default one if there's only one.
4. We can potentially add any new operators (such as `...`) for the implicit turbofish without breaking backwards compat.

**Comment by nrc** [comment]
> From the OP, there is an unresolved question ("We should add a bit extra info when there are extra generic args and impl Trait (see https://github.com/rust-lang/rust/pull/86176#discussion_r680613890)"), but this seems to be more of a TODO item than a question which needs answering (we just need to improve the error message). So I think that should just be changed to a check box.

This had actually been done. I've edited the OP to strikethrough this point

**Comment by nrc** [comment]
I would like to stabilise this feature.

This comment is meant to be a stabilisation report. It is perhaps a little earlier in the stabilisation process (there is no PR yet) because I want to get lang team input on an important question, and that basically answers the 'should we stabilise' question. Details below. 

## What is being stabilised?

The ability to specify types at the call site (using the normal turbofish notation) for explicit type parameters (`T: Trait`) even when `impl Trait` is used in the argument types. This does not allow the specifying of types at the callsite to correspond to the `impl Trait` types, that is left for future work, but stabilising this feature would affect the design space there (see below).

E.g., 

* `fn <T>foo(a: T, b: impl Display)` could be called as either `foo(42, "hello")` or `foo::<u8>(42, "hello")`
* `fn <T>bar(a: impl Error) -> T` could be called as `let _: String = bar(my_err);` or `let _ = bar::<String>(my_err);`

This feature was implemented in https://github.com/rust-lang/rust/pull/86176

## TODO

* Documentation PR (there is some documentation in the [unstable book](https://doc.rust-lang.org/beta/unstable-book/language-features/explicit-generic-args-with-impl-trait.html), that needs editing and moving to the book and reference).
* Stabilisation PR

## Tests

Tests are in [src/test/ui/impl-trait/explicit-generic-args-with-impl-trait](https://github.com/rust-lang/rust/tree/master/src/test/ui/impl-trait/explicit-generic-args-with-impl-trait). There are tests of the basic functionality, error messages, that `impl Trait` parameters cannot be specified, and of an edge case where an explicit parameter is used within an `impl Trait` type.

## Future work and an unresolved question

In the future we may want to allow users to supply explicit type parameters corresponding to `impl Trait` types, either using turbofish or some other syntax. Stabilising this feature constrains the design space there. Specifically, it prevents a design where `impl Trait` types are treated exactly like type parameters and can be specified using the turbofish syntax and where doing so is not optional, either at all or without some explicit syntax. For a discussion of the details and implications of this see https://github.com/rust-lang/rust/issues/83701#issuecomment-1104871405. With this stabilisation request, I am pursuing option 2 from that comment.

**Comment by joshtriplett** [comment]
It seems reasonable to me to allow omitting the impl Trait parameters in a turbofish; we could always make their specification optional in the future.

T-lang, shall we allow turbofish for standard generic type parameters in a function that also has impl Trait parameters?

@rfcbot merge

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

I think it makes sense to stabilize this as-is -- I'm not sure how I think that APIT should be modeled in the future (e.g., as early- or late-bound type parameters, for example) but this seems like it leaves space for all options.

**Comment by scottmcm** [comment]
@rfcbot reviewed

I think having a way to write "*can't* turbofish this" generic parameters is really handy for API design (https://github.com/rust-lang/rust/pull/91970#discussion_r866446507, https://github.com/rust-lang/rust/pull/94119#discussion_r815334382), so let's do this!  And I haven't seen anyone come up with a good way to do the "move to APIT without breakage" idea, so I'm ok sacrificing that. 

cc @rust-lang/libs-api that this will make any standard library APIs using APIT callable this way -- if there are any -- so if any of those have suboptimal generic parameters (since it hasn't mattered before) now would be a good time to fix those.

**Comment by joshtriplett** [comment]
This will stabilize in 1.63, closing.

**Comment by Xiretza** [comment]
Can someone link #96868 in the issue description?
