### ISSUE TITLE
Function is optimized to a ZST leading to invalid pointer from `Box::from_raw()`.

### ISSUE THREAD

**Issue by danobi** [rust-lang/rust#83766]
I tried this code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8c5696502cedfae159ceeee9356b1749

I expected to see this happen: `p` to be a valid address (not `0x1`)

Instead, this happened: `p == 0x1`

### Meta
Just running this on the playground. Looks like it reproduces for nightly as well as stable.

I understand this may be the compiler optimizing `foo()` to be a ZST b/c there's only 1 reference to it. It feels wrong to me despite the code "working" that `p` takes on an indeterminate value. This may cause issues if someone decided to pass the pointer value to C code for whatever reason.

Feel free to close this issue if you disagree -- this is just my opinion.

**Comment by Mark-Simulacrum** [comment]
This is not an optimization; the Box is created with the ZST (unique) type of the function, rather than a function pointer. I'm not sure why you'd want to box a pointer, but regardless, if you want the 'real' pointer you can do `foo as fn()` (with the right signature).

**Comment by SNCPlay42** [comment]
Function item types are documented [here](https://doc.rust-lang.org/reference/types/function-item.html) for reference.

Also, `0x1` is in fact a [valid](https://doc.rust-lang.org/stable/std/ptr/index.html#safety) pointer to any ZST type (because "the memory range of the given size starting at the pointer" is empty; perhaps the docs should be more explicit about this?)
