### ISSUE TITLE
Too-wide spans for function arguments with unsatisfied trait bounds

### ISSUE THREAD

**Issue by giovanniberti** [rust-lang/rust#83782]
Currently rustc outputs very wide spans for missing trait impls in function signatures (the spans cover the whole function instead of the offending arguments only).

Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=910ee19aff7219ada0a39c619137aafc

```rust
struct A;

trait T {
    type Item;
}

fn foo(a: <A as T>::Item) {
    let _ = 1;
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the trait bound `A: T` is not satisfied
 --> src/lib.rs:7:1
  |
7 | / fn foo(a: <A as T>::Item) {
8 | |     let _ = 1;
9 | | }
  | |_^ the trait `T` is not implemented for `A`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

Ideally the output should look like:

```
error[E0277]: the trait bound `A: Signature` is not satisfied
  --> robusta-example/src/lib.rs:70:13
   |
7  |             a: <A as T>::Item
   |                ^^^^^^^^^^^^^^ the trait `T` is not implemented for `A`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

For example, compare rustc output to something like:
```rust
struct A;

trait T {
    type Item;
}

fn bar(a: A) {
    let _: <A as T>::Item;
}
```

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the trait bound `A: T` is not satisfied
  --> src/lib.rs:12:12
   |
7  |     let _: <A as T>::Item;
   |            ^^^^^^^^^^^^^^ the trait `T` is not implemented for `A`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

Currently the output is the same in stable, beta and nightly.

**Comment by jyn514** [comment]
The error comes from here: https://github.com/rust-lang/rust/blob/0978a9eb99eca9f99889014b232f67ece898aadb/compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs#L303-L309
But I'm not sure where the span comes from, it's passed in as an argument to `report_selection_error`. I think it comes from somewhere in `FnCtxt::select_all_obligations_or_error`?

**Comment by SkiFire13** [comment]
I think the problem is that `wfcheck::check_item_fn` calls `normalize_associated_types_in` with the span of the whole function:

https://github.com/rust-lang/rust/blob/97717a561844eccbb6d6cc114adb94a8fa4e0172/compiler/rustc_typeck/src/check/wfcheck.rs#L613

Then that span ends up in `<InferCtxt as InferCtxtExt>::partially_normalize_associated_types_in` where it is used to create an `ObligationCause`, which is the one that then provides the span to `FnCtxt::select_all_obligations_or_error`:

https://github.com/rust-lang/rust/blob/0978a9eb99eca9f99889014b232f67ece898aadb/compiler/rustc_trait_selection/src/infer.rs#L73

I [tried](https://github.com/rust-lang/rust/compare/master...SkiFire13:fix-83782?expand=1) to reduce the span used, but it's still far from perfect. For example if we change the parameter's type to be `(<A as T>::Item, SomeOtherType)` the span will point to the whole tuple. I guess it's better than nothing, but it doesn't solve the underlying problem. 

Looks like the second parameter of `normalize_associated_types_in` is folded with a `AssocTypeNormalizer`, and that's where the actual cause for the `Obligation` is known, so it would be nice if the `ObligationClause` could be created there. Unfortunately a `TypeFolder` is only provided with a `ty::Ty`, which doesn't know its span, so we can't create anything and must rely on a `cause` passed when creating the `AssocTypeNormalizer`. I

A similar thing happens in `wfcheck::check_associated_item`, which is the cause of #83794.

**Comment by Aaron1011** [comment]
On the latest nightly, this now produces:

```
error[E0277]: the trait bound `A: T` is not satisfied
 --> src/lib.rs:7:11
  |
3 | trait T {
  | ------- required by this bound in `T`
...
7 | fn foo(a: <A as T>::Item) {
  |           ^^^^^^^^^^^^^^ the trait `T` is not implemented for `A`
```
