### ISSUE TITLE
Conflicting compiler type inference result

### ISSUE THREAD

**Issue by Jaimeloeuf** [rust-lang/rust#83812]
Hello, thanks for taking your time to read this issue. I believe I am facing a compiler bug issue, but if it is not, please do let me know and would be great if you can point me to some resource regarding this! Thanks 🙏🏻

---

I am trying to convert methods on a Compiler struct of type ParseFnBase into functions of type ParseFn using a macro. The way I want to do this, is to create a wrapper function of type ParseFn and call the original function of type ParseFnBase inside.
```rust
type ParseFnBase = fn(compiler: &mut Compiler) -> Result<(), CompileError>;
type ParseFn = fn(compiler: &mut Compiler, can_assign: bool) -> Result<(), CompileError>;
```

The problem however starts when I try to return the original function's return value. As one would expect, since both of the above function types share the same exact return type, I should be able to just do something like ```return ParseFnBase(compiler);``` directly.
But this is not the case, rust states that it found type ```()``` instead of ```Result<(), CompileError>``` to be the return value of a method that is of type ParseFnBase.
![original](https://user-images.githubusercontent.com/44993072/113483812-e5402d80-94d7-11eb-9378-58c993387e50.PNG)

Since I thought this is weird and should not be the case, I decide to test calling the inner function, and returning ```Ok(())``` directly. This time however, it did compile, BUT it also correctly detected and warned that the inner function returns a value of type ```Result<(), CompileError>``` and that it should be handled instead of ignoring it.
![1](https://user-images.githubusercontent.com/44993072/113483963-9050e700-94d8-11eb-88cf-23c41dde34ff.PNG)

Now I am abit confused, so I decide to just try a bunch of things to test it out. First I tried following rust-c's advice as shown on the first image, to wrap the return value in a Result variant. So I wrap it in the Ok variant. Interestingly now it detects that the return value of the inner function is indeed a Result variant, and that I should not wrap it in the Ok variant again. Rust-c thinks that I should return ```Ok(())``` instead of returning a ```Ok(Result<(), CompileError>)```
![4](https://user-images.githubusercontent.com/44993072/113484095-28e76700-94d9-11eb-94fe-12b55909e461.PNG)

Wrapping the return value in Ok variant after trying to unwrap it also does not work. Rust-c infers it return value as ```()``` and specify that the ```?``` operator cannot be used on it.
![5](https://user-images.githubusercontent.com/44993072/113484287-0e61bd80-94da-11eb-98ca-01d5b6375789.PNG)

Well since that did not help, I thought maybe the compiler is unable to infer the type, so I added type annotation to the inner function call to help it out. Well well, now rust-c infers that the return value of the inner function is actually ```()``` again instead of ```Result<(), CompileError>``` and prevents me from binding the return value to ```ret```
![2](https://user-images.githubusercontent.com/44993072/113484346-6bf60a00-94da-11eb-98b9-e9ace959fee1.PNG)

Ok so last resort was that, maybe just maybe, inline functions requires function type annotation.... so maybe.... if I use a closure instead, the problem will go away? Nope it did not 😅
![3](https://user-images.githubusercontent.com/44993072/113484376-947e0400-94da-11eb-8fb4-1231453b20db.PNG)

---

Ok, so to conclude, it seems like rust-c infers the type of the inner function's return value differently depending on its surrounding context? It seems like only when the function is called by itself on its on line/statement, then will its return value be correctly inferred.
Any advice on this? Is this even a compiler bug? I assume so, since the compiler is inferring different types for the same value. Or perhaps this is an issue with rust macros? Any help would be greatly appreciated, thanks! 😁🙏🏻

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-pc-windows-msvc
release: 1.50.0
```

**Comment by SNCPlay42** [comment]
I suspect that the types of `parse_fn` are inconsistent between different invocations of the macro. The diagnostics should have notes saying which invocations of the macro actually caused the error, but they don't appear to have their locations noted in your screenshots (rust-analyzer/rls bug? Are the locations themselves highlighted?). Are they indicated if you run `cargo check` in a terminal?

**Comment by eggyal** [comment]
It's also a bit odd that the `$parse_fn` meta-variable is of type `expr`, when it appears to be expanded as (a path to) a function name?

**Comment by Jaimeloeuf** [comment]
@SNCPlay42 thanks for getting back!

1. To prevent inconsistencies, I have already tested by removing all except 1 invocation of the macro. And made sure that the macro invocation does indeed match function type ```ParseBaseFn```
2. No the locations are not highlighted. Only the single line in the macro.
3. I stripped out all other invocations to the macro and reverted the macro code to be the same as the first pic, returning ```$parse_fn(compiler)``` implicitly directly, and ran ```cargo check```. Below is the attached picture, showing that it still treats the return value as ```()```

![7](https://user-images.githubusercontent.com/44993072/113488044-3824df80-94ee-11eb-817c-1dde1dce4710.PNG)

**Comment by Jaimeloeuf** [comment]
@eggyal thanks for pointing that out!

I am not exactly aware that I can use ```path```. So I gave it a try. After converting all to path, it the same issue still exists.

Also, from my understanding of [meta-variables](https://doc.rust-lang.org/reference/macros-by-example.html#metavariables) and [expr](https://doc.rust-lang.org/reference/expressions.html) meta-variable type, isnt a "function pointer" technically a [place expression](https://doc.rust-lang.org/reference/expressions.html#place-expressions-and-value-expressions)? Im not too familiar with the exact differences between the 2, but when I used expr in other places with functions/methods it seemed to work, so I assumed that expr meta-variable type applies to function/method references too! 😅

**Comment by Jaimeloeuf** [comment]
@SNCPlay42 and @eggyal I tried to add type annotations to it and now, the conflict/difference is better shown in the pictures below.

![8](https://user-images.githubusercontent.com/44993072/113514821-57ca0f80-95a3-11eb-92e5-09338aa79d9d.PNG)
![9](https://user-images.githubusercontent.com/44993072/113514822-5a2c6980-95a3-11eb-957b-647887e16775.PNG)

As you can see, when I annotate the return value to be ```Result<(), CompileError>```, it says that ```()``` is found, but when I change the type annotation to ```()```, it says that ```Result<(), CompileError>``` is found. I guess this way it shows the conflicting inference better? Let me know if you have any suggestions for me to test out 🙏🏻

**Comment by ExpHP** [comment]
I tried checking out the link-backed commit https://github.com/Jaimeloeuf/SS/commit/b056e8f87f99772b8bdff11d67d49a3e83491962 of your project as well as the commit before it, and was unable to reproduce the errors you are reporting.  (I did not get any error when annotating `let () = $parse_fn(compiler);`.  If you are still having trouble with this, you should provide a link to a minimized code sample or a commit or branch in your repository where the bug can be easily reproduced.

---


I will remark that I think it is *exceedingly* unlikely that this is an actual bug in type inference in the compiler, or we'd have much bigger problems.  (such as it miscompiling into something that corrupts the stack when you get it to compile by ignoring the return value)

What I see here is an error being reported inside a macro definition that causes a contradictory error to appear when fixed.  This is the sort of mundane thing that I run into on a daily basis when using macros, and&mdash;without fail&mdash;for me, it has always been because I forgot to fix one of its callsites or I forgot to hit Ctrl-S on a file somewhere.  (as for the possibility of being a bug in RLS or some other VSCode plugin&mdash;at least, I *assume* this is VSCode based on the visual style&mdash;I cannot comment)

---

> isnt a "function pointer" technically a place expression?

`:expr` is totally fine for functions; I'm not sure why @eggyal was confused by this.  I would even go so far as to say that `:expr` is the preferred matcher to use for a function you are calling in a macro, better than `:path` because `:expr` will also permit the user to supply a closure.

As for whether it is a "place expression" specifically; well, that's a tricky question.  But also somewhat off-topic.

<details>
<summary>Off-topic about place expressions</summary>

I suppose that, *technically,* any bare identifier is both a place expression (expressions like `(*a[0][3 * i].x).y`) and a path expression (expressions like `path::to::module::thing`).  But if you're talking about the name of an item like `fn foo()`, then in a lot of common discourse, we don't generally regard this as a place expression because it's not useful to regard it as a place; it's an item, and the general way to write the name of an item is with a path.  (and of course I am overgeneralizing, e.g. the path could refer to a `static` which is clearly a place...)

But anyways, this is all irrelevant.  You should use a matcher that reflects how you intend to *use* the matched tokens.

</details>

**Comment by Jaimeloeuf** [comment]
Hello all! Thanks for pitching in to help with this! After a short break I went to investigate the issue again and it was actually a bug with my code 😅😅😅

---

The issue was just that, unfortunately the 1 method I left to test the code with, had the wrong type signature..., although it is still kinda weird, because even though only 1 place invokes it, the inference still changes.

I missed the part of the code, because I was testing using multiple macros chained together, and got abit over my head so just missed it completely, turns out, it is hard to keep track of code having a macro called from a macro called from a macro called from code across modules... 😅😂

@ExpHP you are right about what caused the issue, should have investigated further before making the issue but was just so frustrated after a few days of trying and failing 😅

---

Once again, thanks for all your help and sorry for the inconvenience!
