### ISSUE TITLE
`cfg(wasm)` unifying `target_arch="wasm32"` and `target_arch="wasm64"`

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#83879]
In https://github.com/rust-lang/rust/pull/80525 we added to nightly a `cfg(wasm)` which is set when either wasm32 or wasm64 targets are used. We don't have top-level cfg values for other architectures in a similar situation, only for windows vs unix which is set based on the OS.

This ended up being an insta-stable addition due to oversight of mine.

This issue is in order to gather consensus from T-lang members that we do indeed want this `cfg`. I will make myself a note to either remove this `cfg` or put it behind a feature gate before the next nightly->beta rollover that happens on May 6th if such consensus is not gathered.

[Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Are.20we.20comfortable.20with.20adding.20an.20insta-stable.20cfg.28wasm.29.3F/near/233158441)
[PR adding the cfg](https://github.com/rust-lang/rust/pull/80525)

**Comment by nagisa** [comment]
@rfcbot merge

**Comment by nagisa** [comment]
@rfcbot fcp merge

**Comment by Amanieu** [comment]
Related: https://github.com/rust-lang/stdarch/pull/974

**Comment by joshtriplett** [comment]
Based on discussions on Zulip, it sounds like we don't want to have this be insta-stable. However, I do think we want to have `cfg(wasm)`, it just needs a feature-gate for a little while. (And we may want to stabilize it sooner rather than later, if there are no issues, so that people can start using it rather than writing wasm32-specific code.)

Gathering consensus on adding a feature-gated `cfg(wasm)` that's true on WebAssembly targets:

@rfcbot merge

**Comment by ehuss** [comment]
I'd like to note that having bare aliases like this can be confusing for some users. I occasionally run into users who get tripped up by unix/windows, and don't understand why other things like `macos` don't work, or just in general don't understand what "families" are. Having these bare aliases masks what the underlying fields are (`target_family`, `target_os`, `target_arch`), which I think contributes to that confusion. I'm concerned that adding more aliases like this will contribute to more confusion, as this would add a special case that is different from the family aliases.  Seeing this, users may try other arch names without 32/64 and get confused, or not understand the difference between a family and an arch.

**Comment by joshtriplett** [comment]
@ehuss I would be in favor of adding aliases for other common cases, to make them simpler to write and simpler to read.

**Comment by ehuss** [comment]
I agree that they look easier to read (and are more aesthetically pleasing), but I am concerned that they are harder to *understand*, especially when they are "common" exceptions.  Users sometimes learn by looking at existing code to build their mental model of how things work (instead of reading or remembering documentation), and when they try to apply their mental model to new situations (like writing `cfg(arm)`) it can be frustrating and confusing when it doesn't work. This is particularly insidious with `cfg` expressions because they don't necessarily fail at compile time, they are just ignored (baring [RFC 3013](https://github.com/rust-lang/rfcs/blob/master/text/3013-conditional-compilation-checking.md), which I don't think will necessarily help here, and may actually be made worse by this change).  Cargo in particular is unable to verify these things.

I don't want to oversell my objection here.  It is very difficult to predict how well users will understand a concept like this.  I can just say that there are some users who struggle with the current system caused by "unix" and "windows", and I am concerned this may contribute to more confusion.  Adding more aliases may make it even harder to understand when the thing you want to match on isn't part of that blessed set of aliases.

**Comment by devsnek** [comment]
One thing to note specifically in the case of wasm is that wasm32 and wasm64 are not actually separate architectures, it is just a weird abstraction in llvm to represent wasm memory64 types. I would like to provide a very ergonomic way for the rust ecosystem to quickly coalesce on wasm-supporting crates targeting the wasm architecture without having to write out `cfg(any(target_arch = "wasm32", target_arch = "wasm64"))`. I don't think it's reasonable for everyone who wants to target wasm architecture to know the specifics of how memory64 works and the choices that llvm made and that they should be making sure they're including all the wasm targets.

All that being said, I'm fine with other solutions besides the specific `cfg(wasm)` incantation, as long as we figure out something. For example, `cfg(target_arch ~= "wasm")` could also work (though I don't like that as much as `cfg(wasm)`).

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

Speaking personally, I am *so happy* I can write 'unix' vs 'windows', and I would be very happy to be able to type 'wasm'.

**Comment by nagisa** [comment]
An update on the current state:

We have removed the `cfg(wasm)` for reasons outlined in the PR above (#83981). We'll be looking into repurposing `target_family` for this purpose instead. Slightly more typing, but no backward compatibility hazards.

**Comment by nikomatsakis** [comment]
@nagisa should we cancel the FCP and close?

**Comment by nagisa** [comment]
Yeah.

**Comment by nikomatsakis** [comment]
@rfcbot fcp cancel
