### ISSUE TITLE
`doc.rust-lang.org/nightly/nightly-rustc` is down

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#83914]
I think it was working yesterday, but https://doc.rust-lang.org/nightly/nightly-rustc/ is giving a "Not Found" response for me. https://doc.rust-lang.org/beta/nightly-rustc/ works fine, however.

**Comment by Mark-Simulacrum** [comment]
Hm, I wonder if this is a similar bug to the one fixed due to link check failure during the bootstrap bump.

**Comment by camelid** [comment]
FYI, `/nightly/std` works fine—it seems to just be `/nightly/nightly-rustc`.

**Comment by Mark-Simulacrum** [comment]
Yeah, almost certainly the bootstrap bump. cc @ehuss (just a heads up, I plan to submit a patch soon, though haven't written it yet)

**Comment by Mark-Simulacrum** [comment]
My guess without too much investigation is that the symlink_dir_force which intends to share the compiler-doc directory between rustdoc and rustc docs is ending up clobbered. I likely won't get around to a fix tonight but may be able to do so tomorrow, we'll see how much time I have.

**Comment by ehuss** [comment]
I'm also happy to revert the change on beta, if you want, so there isn't a rush to fix things.

**Comment by Mark-Simulacrum** [comment]
Yeah, I think we should do that - there's enough stuff broken in rustbuild that's not really of the too unusual kind (well, really just two cases, but they seem fairly typical). I'd rather we drop it from beta and either pursue resource-suffix as suggested by @jyn514 or at least tackle the bugs in rustbuild on a less urgent timescale before relanding. (Ideally we should figure out what people should do; rustbuild's approach to just building twice seems pretty... suboptimal; I imagine that the fix for this newly found bug will end up similar if I do it quickly).

**Comment by ehuss** [comment]
OK, I have posted https://github.com/rust-lang/cargo/pull/9332.  I'll push through the changes, though it may take at least a few days to get beta updated and then bump the version.

**Comment by Mark-Simulacrum** [comment]
Yeah. I think I'm not sure there's as easy a fix in this case (unlike the simple add of a double core build), as the clobbering occurs over two different steps I believe. So I think we'll wait for that patch to land and bump beta. (We could also temporarily remove, say, rustdoc or rustc docs - but that doesn't seem like a real benefit).

**Comment by camelid** [comment]
Thanks for the speedy fix! The docs are back online now (because it's a bit after midnight UTC). I'm glad they're back :)
