### ISSUE TITLE
x.py test src/tools/clippy shouldn't build rustdoc

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#84036]
I tried this code: `x.py test src/tools/clippy`
I expected to see this happen: bootstrap builds the compiler and clippy
Instead, this happened: bootstrap builds the compiler, clippy, and rustdoc

### Meta

`git merge-base HEAD origin/master` is 69e1d22ddbc67b25141a735a22a8895a678b32ca

**Comment by ehuss** [comment]
This is normal for running `x.py test`, since it runs doctests on the libraries.

You can pass `--no-doc` to skip building rustdoc.

**Comment by jyn514** [comment]
@ehuss do you know why it uses the in-tree rustdoc instead of the bootstrap compiler? I was using --stage 1.

**Comment by ehuss** [comment]
The tests run with the in-tree rustc (stage1), which will also require using the in-tree rustdoc (stage1).  Using stage0 rustdoc would be testing against an older version, and I don't think would necessarily work. 

I'd imagine nobody considered it when clippy was brought in-tree, since that is all determined at a low level inside rustbuild.

However, taking a closer look, it appears that clippy doesn't have any doctests, so I imagine defaulting that to off would be reasonable (assuming clippy never intends to add doctests in the future).  It looks like rustbuild does not make that easy since it is a property of the `Builder`, so it would require some work to support that.

**Comment by jyn514** [comment]
> The tests run with the in-tree rustc (stage1), which will also require using the in-tree rustdoc (stage1). Using stage0 rustdoc would be testing against an older version, and I don't think would necessarily work.

Ok, I see the issue - this is using the "test with stage 1" meaning, not "build stage 1 and test it" like I thought (the first builds compiler/ twice, the second only once). `test --stage 0 src/tools/clippy` seems to be broken because of weird things with clippy's copy of compiletest: https://github.com/rust-lang/rust/issues/78717.

> However, taking a closer look, it appears that clippy doesn't have any doctests,

I see some in clippy_lints: https://github.com/rust-lang/rust/blob/1284da34da56a17ae368e4673920ec4120562cbd/src/tools/clippy/clippy_lints/src/methods/mod.rs#L98

**Comment by ehuss** [comment]
`x.py test src/tools/clippy` does not run any tests on clippy_lints.  It only tests the integration tests in the `tests` directory.  rust-lang/rust only does a subset of clippy's full suite of tests.
