### ISSUE TITLE
rustdoc: should we stop showing `#[lang = ...]` and some other attributes?

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#84309]
![image](https://user-images.githubusercontent.com/1617736/115153942-3a7a5400-a02d-11eb-8c04-7f39c8fcc48b.png)

It seems like we should not be showing `#[lang = ...]` (etc) attributes in rustdoc. Perhaps we should allowlist or denylist such attributes?

cc @rust-lang/rustdoc

**Comment by Manishearth** [comment]
Also perhaps we should truncate `must_use` to not include the full text

![image](https://user-images.githubusercontent.com/1617736/115154003-95ac4680-a02d-11eb-8e43-3f92f2355804.png)


I know we used to hide attributes unconditionally and now we show them unconditionally since it's almost always _one_ attribute so it's not a space saving thing, but there's the additional concern about it being distracting. We can probably allowlist to a set of attributes we care about (`must_use`, `repr`, `no_mangle`, `link`, ...)

cc @jsha

**Comment by jsha** [comment]
There's already an allow list of attributes, but `#[lang]` is on it: https://github.com/rust-lang/rust/blob/b021beeb6021d8885dc3f21e75a7f56502849633/src/librustdoc/html/render/mod.rs#L990-L998

I'm removing `lang` in https://github.com/rust-lang/rust/pull/84283/files, along with a reduction in visual weight for all attributes.

I've tried truncating `#[must_use]` to not include the full text, but I think actually the best thing is to not show `#[must_use]` at all. It's an attribute on a lot of functions very commonly used by beginners, and the attribute name is not at all self-explanatory. Also, even without must_use listed in the docs, its message will show up at just the time someone needs it - when it generates a compiler warning. In other words, when you're reading the docs, you don't need to know a function is `#[must_use]` in order to use it correctly.

**Comment by Manishearth** [comment]
Oh! I feel like I've even seen that list before :smile:, probably just forgot.

Reducing the visual weight is a great idea, thanks!

`must_use` is ... well, I still find it useful to know things are tagged as such, but I don't mind removing it from the allowlist, it doesn't impact semantics anywhere close to as much as the others do.

**Comment by camelid** [comment]
> `must_use` is ... well, I still find it useful to know things are tagged as such, but I don't mind removing it from the allowlist, it doesn't impact semantics anywhere close to as much as the others do.

Yeah, I agree. I wonder if we should remove `non_exhaustive` as well? Currently, we say that it's non-exhaustive in addition to showing the attribute:

![image](https://user-images.githubusercontent.com/37223377/115281093-7d0b6180-a0fd-11eb-9303-f031c9f7c40a.png)

**Comment by jyn514** [comment]
I think `#[non_exhausive]` is important to show. The variants are also duplicated between the declaration and the main docs, but we don't remove the declaration either.

**Comment by camelid** [comment]
> The variants are also duplicated between the declaration and the main docs, but we don't remove the declaration either.

Yeah, I find that duplication a bit annoying :)

**Comment by jsha** [comment]
@jyn514 said at https://github.com/rust-lang/rust/issues/83332#issuecomment-822942643:

> I think we should fix this by removing the documentation about what #[non_exhaustive] is and linking to the official docs instead: https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute

I agree that we should link all attributes to their official docs. For `#[non_exhaustive]`, that would make it the only clickable hyperlink in the declaration section. That would be a bit of inconsistency since the other items in that section would generally be clickable if they showed up elsewhere. We would also need to highlight it in some way to indicate that it's clickable, which would make it stand out a lot from the rest of the declaration.

**Comment by jyn514** [comment]
> That would be a bit of inconsistency since the other items in that section would generally be clickable if they showed up elsewhere.

I mean, I think it would also be useful to make items in the declaration clickable.

**Comment by camelid** [comment]
It might be nice to use syntax highlighting for the declaration too. I don't think we'd even have to use the rustc lexer because rustdoc knows that e.g. it's emitting an attribute vs visibility.

**Comment by GuillaumeGomez** [comment]
I think it can be closed now indeed.
