### ISSUE TITLE
rustdoc: Ctrl-Enter on search result should open link in new tab

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#84384]
Steps to reproduce:

1. Visit a rustdoc page, e.g. https://doc.rust-lang.org/nightly/std/
2. Hit 'S' to focus search.
3. Type a search, e.g. "String"
4. Press the down arrow once to highlight a search result.
5. Hold down Ctrl (incidentally, notice that the highlighting goes away).
6. Hit enter.

Expected result:

First search result is opened in a new tab.

Actual result:

Nothing happens.

In general, Ctrl-Enter works when an `<a>` is focused. The search results are `<a>`s. I think mainly we need two things:

1. Make modifier keys (shift, ctrl, etc) not remove the highlighting of search results.
2. Make sure highlighting search results with the arrow keys also focuses them.

Reproduces in latest Chrome and Firefox on Linux.

**Comment by GuillaumeGomez** [comment]
> Make sure highlighting search results with the arrow keys also focuses them.

This is not possible because it'd make us lose focus on the search input, preventing anything else to work. A workaround would be to add the focus on the search only if the ctrl key is pressed, but then what happens if you want to switch result tab instead? I don't think focus will work nicely here...

**Comment by GuillaumeGomez** [comment]
As for opening in new tab with ctrl+tab, it'd require a big rework of how we handle the events on the search because when we do it only from JS, on FF it asks confirmation to go to the new tab as "big security concern". If we want to focus on the elements with they keyboard arrows, we won't be able to bind the event for them because people want to scroll using them.

**Comment by jsha** [comment]
> If we want to focus on the elements with they keyboard arrows, we won't be able to bind the event for them because people want to scroll using them.

What I'm proposing is:
 - When search is focused, down arrow focuses the first search result
 - When a search result is focused, up/down focus the next/previous search result, or the search box if you press up from the first result.
  - When neither is focused, let the default action occur.
  
That way up/down would continue to work correctly when scrolling docs (I agree it would be very bad to break that behavior).

**Comment by GuillaumeGomez** [comment]
But then we couldn't switch between tabs anymore unless handling it from two places. Well, considering all the great work you did until now, I'm pretty sure you have already a plan in mind so I'll just wait for you to amaze me as usual. :p
