### ISSUE TITLE
Failure when updating stable to nightly, with component 'rustc-docs' missing

### ISSUE THREAD

**Issue by swzry** [rust-lang/rust#84416]
Failure when updating stable to nightly, with the error message above:

`
PS Z:\> rustup toolchain install nightly-2021-04-21
warning: downloading with complete profile isn't recommended unless you are a developer of the rust language
info: syncing channel updates for 'nightly-2021-04-21-x86_64-pc-windows-msvc'
info: latest update on 2021-04-21, rust version 1.53.0-nightly (6df26f897 2021-04-20)
error: component 'rustc-docs' for target 'x86_64-pc-windows-msvc' is unavailable for download for channel nightly-2021-04-21
Sometimes not all components are available in any given nightly. If you don't need the component, you can remove it with:

    rustup component remove --toolchain nightly-2021-04-21 --target x86_64-pc-windows-msvc rustc-docs
`

I noticed that the component which was missing is named "rustc-docs", but I never heard about it. It may be a typo of 'rust-docs'?

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-pc-windows-msvc
release: 1.51.0
LLVM version: 11.0.1
```

`rustup --version --verbose`:
```
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.51.0 (2fd73fabe 2021-03-23)`
```

**Comment by ehuss** [comment]
`rustc-docs` are the documentation for working on the compiler itself (https://doc.rust-lang.org/nightly/nightly-rustc/). They are not available for most platforms (I think they are only published on linux gnu?).

The key part is:

> warning: downloading with complete profile isn't recommended unless you are a developer of the rust language

Using the "complete" rustup profile is not recommended (see https://github.com/rust-lang/rustup/issues/2661 and https://github.com/rust-lang/rustup/issues/2706). We are considering removing it since it isn't very useful.  I would recommend changing your profile to default (or even minimal).  If you are not familiar with profiles, the documentation is at https://rust-lang.github.io/rustup/concepts/profiles.html.
