### ISSUE TITLE
Const-generic bounds should allow simple casts

### ISSUE THREAD

**Issue by aloucks** [rust-lang/rust#84526]
The `as_usize` wrapper function in the example below shouldn't be required.

@oli-obk
https://github.com/rust-lang/rust/pull/83278#issuecomment-825856425

```rust
#![feature(const_generics)]
#![feature(const_evaluatable_checked)]

use std::arch::x86_64::*;

pub const fn _MM_SHUFFLE(fp3: u32, fp2: u32, fp1: u32, fp0: u32) -> i32 {
    ((fp3 << 6) | (fp2 << 4) | (fp1 << 2) | fp0) as i32
}

pub const fn as_usize(a: i32) -> usize {
    a as usize
}

pub fn swizzle<const X: u32, const Y: u32, const Z: u32, const W: u32>(v: __m128) -> __m128
where [(); as_usize(_MM_SHUFFLE(W, Z, Y, X))]:
{
    unsafe {
        _mm_shuffle_ps(v, v, _MM_SHUFFLE(W, Z, Y, X))
    }
}
```

**Comment by oli-obk** [comment]
cc @rust-lang/project-const-generics 

Casts are infallible and could be allowed. I think they are sufficiently common for us to allow them

**Comment by nikomatsakis** [comment]
That makes sense to me

**Comment by memoryruins** [comment]
`fn as_usize` is no longer needed and the where clause can be written as `where [(); _MM_SHUFFLE(W, Z, Y, X) as usize]:`. Presumably fixed by https://github.com/rust-lang/rust/pull/86130

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=22e5e5b5e7cf9e6f93754fddeac964e5)
`1.55.0-nightly 2021-06-21 406d4a9cc3b9601cf98a`
