### ISSUE TITLE
unexplainable behavior

### ISSUE THREAD

**Issue by chuckcscccl** [rust-lang/rust#84801]
// I encountered the following strange behavior while trying to implement
// String-key'ed Tries in Rust.

// I've gotten rid of all the other code that doesn't matter, and have
// simplified the situation that caused the error as much as I can.  The
// commented-out version of the function 'getndoe2' will not compile,
// while getnode does compile.  The only difference is the 'if true ..'

// I get multiple mutable borrow errors on 'current' for getnode2, but
// none for getnode.  Besides the problem with the 'if true',
// are there supposed to be borrow errors or not?

```rust
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(unused_parens)]
//use std::mem::{replace};
use std::collections::HashMap;

// Part of code to implement string-keyed tries in Rust
struct Trienode<T>
{
   item : Option<T>,
   children : HashMap<char,Trienode<T>>,  
}

impl<T> Trienode<T>
{
  pub fn getnode(&mut self, key:&str) -> Option<&mut Trienode<T>>
  {
      let mut current = self;
      for c in key.chars()
      {
         match current.children.get_mut(&c) {
	   None => { return None; },
	   Some(child) => { current=child; },
	 }      
      }
      Some(current)
  }//getnode

/*  But this doesn't compile (only difference is the if true)

pub fn getnode2(&mut self, key:&str) -> Option<&mut Trienode<T>>
  {
      let mut current = self;
      for c in key.chars()
      {
         match current.children.get_mut(&c) {
	   None => { return None; },
	   Some(child) => { if true {current=child;} },
	 }      
      }
      Some(current)
  }//getnode
*/

}// impl Trienode

fn main()
{
}//main
```

**Comment by FabianWolff** [comment]
It is not unexplainable if you recall that before optimization, the compiler doesn't "know" that an `if true` will always take the then-branch: To the borrow checker, an `if true` looks like any other conditional branch, i.e. it will take both possible branches into account. I've changed your example to make this explicit, and also simplified it to not use any loops, hash maps, etc. `foo1()` below corresponds to your `getnode()` method, and `foo2()` to `getnode2()`. `foo1()` and `foo3()` should compile, whereas `foo2()` and `foo4()` should give errors about multiple mutable borrows:
```Rust
#![allow(unused_mut)]
#![allow(unused_variables)]
#![allow(dead_code)]

struct Foo {
    child: Option<Box<Foo>>,
}

fn rnd() -> bool {
    use rand::Rng;
    let mut rng = rand::thread_rng();
    rng.gen()
}

impl Foo {
    fn foo1<'s>(&'s mut self) -> Option<&'s mut Foo> {
        match self.child {
            None => None,
            Some(ref mut chld) => Some(self),
        }
    }

    fn foo2<'s>(&'s mut self) -> Option<&'s mut Foo> {
        match self.child {
            None => None,
            Some(ref mut chld) => Some(if rnd() { &mut *chld } else { self }),
        }
    }

    fn foo3<'s>(&'s mut self) -> Option<&'s mut Foo> {
        match self.child {
            None => None,
            Some(ref mut chld1) if !rnd() => Some(self),
            Some(ref mut chld2) => Some(&mut *chld2),
        }
    }

    fn foo4<'s>(&'s mut self) -> Option<&'s mut Foo> {
        match self.child {
            None => None,
            Some(ref mut chld1) if rnd() => Some(&mut *chld1),
            Some(ref mut chld2) => Some(self),
        }
    }
}

fn main() {}
```
When inferring the type for `chld` in `foo2()` (or the type of `child` in your `getnode2()` function), the compiler realizes that because the return value has a lifetime of `'s`, `chld` must also have at least this lifetime. But `self` also has lifetime `'s`, so `chld` is, perhaps somewhat counter-intuitively, live in the else-branch as well, and that's why you get an error about multiple mutable borrows (because both `chld` and `self` exist at the same time, which is fine as long as you're only using one of them, but you use both in the two arms of the `if`).

You can fix this by negating the condition and using a match guard, as in `foo3()`. Here, the compiler can infer two _different_ lifetimes for `chld1` and `chld2`, respectively; in particular, `chld1` can have an empty lifetime because it is never used. This way, by the time you get to the `chld2` mutable borrow, you don't need `self` anymore, and so you don't have overlapping mutable borrows.

`foo4()` (where the last two match arms have been swapped) is more subtle: `match` checks its patterns sequentially, and so it makes a difference which of the mutable borrows happens first. In particular, the mutable borrow of `self.child` (`chld1` in `foo4()`) will render `self` unusable, and so the match arm where `self` is used has to precede the other one (so that `self` is not yet unusable because of a second mutable borrow by the time it is needed), as in `foo3()`.
