### ISSUE TITLE
no_coverage feature-gated on function, not crate?

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#84836]
It looks like the no_coverage attribute was added by checking for feature(no_coverage) on the function, but this isn't how feature gating usually works. Additionally, I don't believe that restricts usage of this on stable/beta, since nothing is actually checking this feature gate.

Noticed based on the test case (https://github.com/rust-lang/rust/blob/master/src/test/ui/feature-gates/feature-gate-no_coverage.rs) and while looking at the feature-gating code.

cc @tmandry @richkadel

**Comment by Mark-Simulacrum** [comment]
cc https://github.com/rust-lang/rust/issues/84605

**Comment by richkadel** [comment]
> It looks like the no_coverage attribute was added by checking for feature(no_coverage) on the function, but this isn't how feature gating usually works.

Correct. The driving reason for adding the feature was to resolve #83601, and that issue occurred because `core`/`std` pushes a hidden function into everything that derives `Eq`, and we need to hide that function. So the only way to gate the issue at the crate level would be to automatically enable the feature in any crate that derives `Eq` (which is just about every crate).

Feature gating at the function level resolved the problem, even though it was non-standard.

I do allow feature-gating at the crate level as well, but it's not used by `Eq`.

> Additionally, I don't believe that restricts usage of this on stable/beta, since nothing is actually checking this feature gate.

I didn't realize this also needs to be checked. Is there an example of how to do this, so I can also implement it in the function-based feature-gate check?

**Comment by Mark-Simulacrum** [comment]
It should be possible to adjust the normal feature gating to correctly handle macro expanded sources - that is, allow the built-in derives to generate it without it being stabilized. We do this for the Structural trait impls somehow, for example; possibly enough to set the span appropriately. If necessary, I can either provide or track down someone who can, further hints. It might be good to look at how the structural equality worked before the move to the trait impls as it had a similar built-in attribute.

In the meantime we'll likely revert the PR on just branched beta (1.53) so we don't accidentally stabilize the feature.

**Comment by richkadel** [comment]
@Mark-Simulacrum: I just uploaded a PR to fix this, as an alternative to reverting: #84871 

Your call.

Thanks!

**Comment by nagisa** [comment]
`#[allow_internal_unstable]` is what we use extensively to utilize unstable features within macros-by-example, so there is definitely already means to enable unstable features within macro-expanded code.

In procedural macros and derive macros stability can be carefully handled (AFAIK) by setting the span (or more precisely its expansion id) up in such a way that it refers to the crate that has feature gates enabled. I'm confident there's somebody on T-compiler who can say something more precise.

I don't think we should be introducing new ways to enable unstable features (by e.g. allowing them to be specified as attributes on items) without a broader buy-in. The ability to have non-crate-level feature gates definitely sounds like at least a MCP material to me, primarily due to complications in the implementation of the compiler & tooling surrounding the unstable feature tracking and relative ease with which an oversight can happen and a feature accidentally stabilized.

**Comment by tmandry** [comment]
I should have caught this, sorry. #84871 can work as a stopgap, but if we need an MCP to use this mechanism at all we should probably revert.

**Comment by richkadel** [comment]
> In procedural macros and derive macros stability propagation can be carefully handled (AFAIK) by setting the span (or more precisely its expansion id) up in such a way that it refers to the crate that has feature gates enabled

Thanks @nagisa ! This was the hint I needed. I uploaded a revised PR commit with a change in line with your suggestion. All tests work as before (with the exception of test that enabled the feature at the function level; these are now removed).

**Comment by richkadel** [comment]
> if we need an MCP to use this mechanism at all

Just confirming, but I think @nagisa was only referring to function-level feature gating (now removed) as needing an MCP. But since this is gone, I think the feature-gated `#[no_coverage]` attribute is still OK.

Correct me if I'm wrong.

**Comment by apiraino** [comment]
Assigning P-critical for the record, as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2384836.20no_coverage.20feature-gated.20on.20function.2C.20not.20crate.3F) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-critical
