### ISSUE TITLE
Windows std::env::vars() uppercases environment variables

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#85242]
I tried this code:

```rust
    for v in std::env::vars() {
        println!("{:?}", v);
    }
```

I expected to see this happen: a case-sensitive list of environment variables and values, matching the output of `Environment.GetEnvironmentVariables` from C# and .NET and the output of `Get-ChildItem Env:` from PowerShell.

It seems we should align the `std::env::vars()` output to match the modern APIs for Windows that Microsoft provides.

Instead, this happened: `std::env::vars()` returns all environment variable names in all uppercase.

Rust via `std::env::vars()`:
```
SYSTEMDRIVE = C:
<snip>
```

C# via `Environment.GetEnvironmentVariables`:
```
SystemDrive = C:
<snip>
```

### Meta

`rustc --version --verbose`:
```
>rustc --version --verbose
rustc 1.51.0-nightly (04caa632d 2021-01-30)
binary: rustc
commit-hash: 04caa632dd10c2bf64b69524c7f9c4c30a436877
commit-date: 2021-01-30
host: x86_64-pc-windows-msvc
release: 1.51.0-nightly
LLVM version: 11.0.1
```

</p>
</details>

**Comment by ehuss** [comment]
I don't think this is related to *reading* environment variables, but is related to process spawning.  If you are spawning a process from a Rust program, then they will be uppercased.  But if the Rust program is spawned from something else (like PowerShell), then the env keys should be case-preserved.

The issue is [here](https://github.com/rust-lang/rust/blob/9daf546b77dbeab7754a80d7336cd8d00c6746e4/library/std/src/sys/windows/process.rs#L40).  This was originally added in #17249 to fix #16937.  I personally don't think that issue is all the important that all environment keys should be forced to be uppercase.  However, if there is a desire to fix both issues, then there would need to be a case-insensitive map (maybe just keep a separate set of uppercased keys?).

**Comment by jonathandturner** [comment]
@ehuss thanks for the pointer. For our case, Nushell should be able to spawn processes and keep the environment as expected rather than uppercasing. This allows Nushell to work just as PowerShell spawning a program.

As best as I can tell, it's the lookup of a single variable that should be case-insensitive and that listing of variables should maintain the case they had, though I'm far from an expert here.

**Comment by ChrisDenton** [comment]
Hm, the current code does look wrong. Windows environment variables are compared case-insensitive but when set they keep the same case. The simplest improvement here would be remove the `make_ascii_uppercase` and instead implement `Ord`, and `PartialEq` which ignores the case.

However, note that Windows uses Unicode casing, not just ASCII. There is [a Windows function](https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-comparestringex) for comparing but using it for `Ord` would mean lots of conversions from OsString to the Windows string type (and back again). Calling Rust's Unicode functions with a WTF-8 OsString looks tricky too (though maybe there's something I'm missing). I'm uncertain how to approach a proper fix.
