### ISSUE TITLE
"Auto-hide trait implementation documentation" does nothing

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#85411]
beta and nightly ignore the default-on configuration of "Auto-hide trait implementation documentation"

On stable [`std::future::Pending`](https://doc.rust-lang.org/stable/std/future/struct.Pending.html) looks like:

![image](https://user-images.githubusercontent.com/81079/118487717-497f1f80-b71b-11eb-8f1d-3206b570ff69.png)

While [on beta](https://doc.rust-lang.org/beta/std/future/struct.Pending.html) it looks like:

![image](https://user-images.githubusercontent.com/81079/118487777-5996ff00-b71b-11eb-8e8d-c031e79ea29c.png)

And [on nightly](https://doc.rust-lang.org/nightly/std/future/struct.Pending.html) (as of 2021-05-17):

![image](https://user-images.githubusercontent.com/81079/118487862-6d426580-b71b-11eb-8132-80d5308edb57.png)

Going to https://doc.rust-lang.org/nightly/settings.html and toggling "Auto-hide trait implementation documentation" off makes stable look the same as beta, so it definitely seems like beta/nightly are just ignoring this toggle.

**Comment by jsha** [comment]
This is due to the refactoring we've been doing with the expand / collapse toggles, wrapping them in `<details>` tags. The code that expands and collapses them based on settings is here: 

https://github.com/rust-lang/rust/blob/3e827cc21e0734edd26170e8d1481f0d66a1426b/src/librustdoc/html/static/main.js#L909-L911

https://github.com/rust-lang/rust/blob/3e827cc21e0734edd26170e8d1481f0d66a1426b/src/librustdoc/html/static/main.js#L927-L945

You can see there's an entry for handling "implementors" but not one for "implementations."

Right now, both implementors and implementations get wrapped in a `<details>` tag with `class=toggle-implementors`. We need to update this Rust code:

https://github.com/rust-lang/rust/blob/3e827cc21e0734edd26170e8d1481f0d66a1426b/src/librustdoc/html/render/mod.rs#L1542-L1549

So that it generates `toggle-implementors` for implementors and `toggle-implementations` for implementations. And then update the JS to add a clause for implementations.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2385411.20.22Auto-hide.20trait.20implementation.20documentation.22.20does.20.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-medium

**Comment by jsha** [comment]
I'm having trouble figuring out what fields to check in `render_impl` to figure out if we're rendering an implementor or an implementation. If someone's able to point me in the right direction I'd appreciate it!

**Comment by GuillaumeGomez** [comment]
Well, I think I handled it in #85548 (funny that I was noticed it and fixed it on my side and someone else find it out too).
