### ISSUE TITLE
doc tests fails to use modules

### ISSUE THREAD

**Issue by bilelmoussaoui** [rust-lang/rust#85433]
I tried this code:

```rust
/// ```rust
/// fn test_func() -> bool {
///     true
/// }
/// mod x {
///     use super::*;
///     fn x() {
///         assert!(test_func());
///     }
/// }
/// ```
fn hello_world() {
    println!("hello world");
}

```

I expected to see this happen: the doc test to be able to find the `test_func` as it's included inside the `x` module with `use super::*`

Instead, this happened: `cargo test --doc` complains that no such function `test_func` exists in current scope
```
---- src/lib.rs - hello_world (line 2) stdout ----
error[E0425]: cannot find function `test_func` in this scope
 --> src/lib.rs:9:17
  |
9 |         assert!(test_func());
  |                 ^^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
Couldn't compile the test.

failures:
    src/lib.rs - hello_world (line 2)

```

### Meta
`rustc --version --verbose`: 1.52.1 

Quick link for testing the issue https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ca9c823e231ee15d8cc267b43fe44ebc

**Comment by ehuss** [comment]
Yea, that definitely can be confusing.  This can be fixed by adding a `main` function to example. It can be prefixed with a `#` to hide it, something like this:

`/// # fn main() {}`

The reason this happens is because if there is no main function, then rustdoc will wrap the example in a `main` function. This means that your module exists within the `main` function.  Paths work a little strangely when modules are inside a function.  Adding a `main` function ensures that the module is defined outside the function.  There's more information [here](https://doc.rust-lang.org/rustdoc/documentation-tests.html#pre-processing-examples).

**Comment by bilelmoussaoui** [comment]
Oh I see. That indeed fixes my issue. Although, maybe the error could have been a bit clearer in such case? anyway, the issue can be closed if you want as my use case is properly working now :)

**Comment by bilelmoussaoui** [comment]
I'm going to go ahead and close this one, feel free to re-open if you think it's worth it. Thanks again! :)
