### ISSUE TITLE
Intervening type alias of GAT to causes incorrect E0581

### ISSUE THREAD

**Issue by elidupree** [rust-lang/rust#85533]
This code [[playground]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7299ed4b17607b0f5035ffbb871c96fd):

```rust
#![feature(generic_associated_types)]

trait Trait {
    type Assoc<'a>;
}

type AssocAlias<'a, T> = <T as Trait>::Assoc<'a>;

fn works<'a, T: Trait>(entity: T::Assoc<'a>) -> &'a i32 {&5}
fn fails<'a, T: Trait>(entity: AssocAlias<'a, T>) -> &'a i32 {&5}
```

Produces the following error on 1.54.0-nightly (2021-05-19 f94942d8421dc4b1da86):
```
error[E0581]: return type references lifetime `'a`, which is not constrained by the fn input types
  --> src/lib.rs:10:54
   |
10 | fn fails<'a, T: Trait>(entity: AssocAlias<'a, T>) -> &'a i32 {&5}
   |            
```

The version that uses `T::Assoc` directly works, but the one using the type alias (which should be identical) fails.

**Comment by jackh726** [comment]
This is a variation of #47511 and it isn't a GAT issue.

Essentially, the issue is that because of the way we assign a lifetime as late-bound or early-bound, we end up assigning `'a` as early bound in the first and late bound in the second. Then later once the type alias is expanded, we see that it's not actually constrained (where that requirement isn't there for early bound regions).

Although it's kind of not great, there are a couple workarounds:
```rust
fn fails<'a, 'b: 'a, T: Trait>(entity: AssocAlias<'a, T>) -> &'a i32 {&5}
fn fails<'a, T: Trait + 'a>(entity: AssocAlias<'a, T>) -> &'a i32 {&5}
```

Not going to remove the GAT label here (since I think this is an important consideration), but this is non-blocking for stabilization.

**Comment by jackh726** [comment]
GATs issue triage: not blocking. As mentioned previously, this is caused by us treating regions in type alias substs as constrained, but not in projections - leading to one function assigning a region as early-bound and the other as late-bound. Not a GATs issue, but keeping label for now, since we probably want to think about this diagnostics-wise at least at some point.
