### ISSUE TITLE
rustdoc doesn't include all text that cross attribute type boundaries in the summary

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#85763]
I tried this code:

```rust
#[doc = " Some text"]
#[doc = " that should"]
/// be concatenated.
pub fn main() {
    println!("Hello, world!");
}
```

I expected to see this happen: The entire first paragraph is used as the summary for the function in the module docs: "Some text that should be concatenated"

Instead, this happened: Only the unsugared doc attributes are used: "Some text that should"

![image](https://user-images.githubusercontent.com/81079/119900107-56ceb200-bf44-11eb-81fb-534a700d1163.png)

![image](https://user-images.githubusercontent.com/81079/119900125-5c2bfc80-bf44-11eb-997a-7e1586cd17a0.png)

### Meta
`rustc --version --verbose`:
```
rustc 1.54.0-nightly (4e3e6db01 2021-05-18)
binary: rustc
commit-hash: 4e3e6db011c5b482d2bef8ba02274657f93b5e0d
commit-date: 2021-05-18
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

**Comment by ben0x539** [comment]
This seems to be achieved here: https://github.com/rust-lang/rust/blob/1639a16ebfaad2aa74fd535c778fd1614475b53d/src/librustdoc/clean/types.rs#L1060 (probably from #80261?)

We're concatenating the text from doc attrs here, but only until we find one of a different kind. Seems intentional enough but I don't know what it's for.

To me naively it only makes sense to concatenate single-line doc comments to generate the summary; with either multiline doc comments or explicit attrs I would expect that where they end is a good place to end the summary.

**Comment by Nemo157** [comment]
My usecase is dynamically generating some words in the first sentence based on `cfg`. I don't see any reason that rustdoc should distinguish between attribute types here, it has markdown's concept of a _paragraph_ to determine how much to look at for the summary, there's no need to limit how users can construct that first paragraph.

**Comment by ben0x539** [comment]
Right, that's a compelling use case for sure! My take was "separate attributes are probably intended as separate paragraphs", but I didn't consider that you'd dynamically construct the set of attributes. I'm curious if that was the original motivation for the `kind` comparison or if it's needed for another reason.

**Comment by lolbinarycat** [comment]
> separate attributes are probably intended as separate paragraphs

however, they're *not* treated as separate paragraphs, in the full docs, it is one paragraph.

in my experience, the main use for `#[doc = ""]` attributes *is* dynamically generating docs via macros.

if anything, we should just ingest `clippy::too_long_first_doc_paragraph` into rustdoc.
