### ISSUE TITLE
Emscripten wasm32 compilation broken

### ISSUE THREAD

**Issue by creikey** [rust-lang/rust#85821]
I tried this code:

```rust
fn main() {
    println!("Hello, world!");
}
```

I expected to see this happen: Compiling with `rustc --target=wasm32-unknown-emscripten main.rs` , after the emsdk is activated and emcc works, to compile properly

Instead, this happened: Prints this error:
```
  = note: error: undefined symbol: __gxx_personality_v0 (referenced by top-level compiled C/C++ code)
          warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
          warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
          warning: ___gxx_personality_v0 may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
          Error: Aborting compilation due to previous errors
          emcc: error: 'C:/Users/camer/Documents/Tech/emsdk/node/14.15.5_64bit/bin/node.exe C:\Users\camer\Documents\Tech\emsdk\upstream\emscripten\src\compiler.js C:\Users\camer\AppData\Local\Temp\tmprxn1kc58.txt' failed (returned 1)
```

I've tried adding `-lstdc++` to no avail

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (f58631b45 2021-05-28)
binary: rustc
commit-hash: f58631b4503b5cd34163cf9c3ff19dc3e0c8a09e
commit-date: 2021-05-28
host: x86_64-pc-windows-msvc
release: 1.54.0-nightly
LLVM version: 12.0.1
```

<details><summary>Backtrace</summary>
<p>

```
error: linking with `emcc.bat` failed: exit code: 1
  |
  = note: "cmd" "/c" "emcc.bat" "-s" "DISABLE_EXCEPTION_CATCHING=0" "-L" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib" "-L" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\self-contained" "main.main.7rcbfp3g-cgu.0.rcgu.o" "main.main.7rcbfp3g-cgu.1.rcgu.o" "main.main.7rcbfp3g-cgu.2.rcgu.o" "main.main.7rcbfp3g-cgu.3.rcgu.o" "main.main.7rcbfp3g-cgu.4.rcgu.o" "main.main.7rcbfp3g-cgu.5.rcgu.o" "main.main.7rcbfp3g-cgu.6.rcgu.o" "main.main.7rcbfp3g-cgu.7.rcgu.o" "-o" "main.js" "-s" "EXPORTED_FUNCTIONS=[\"_main\",\"_rust_eh_personality\"]" "main.4s37gsrti678ik8u.rcgu.o" "-O0" "--memory-init-file" "0" "-g0" "-s" "DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[]" "-L" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libstd-fb3d38fb81b27f3a.rlib" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libpanic_unwind-d2cae8b45410ca8e.rlib" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libstd_detect-59eadd895a0069e7.rlib" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\librustc_demangle-034447b1a63c6379.rlib" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libhashbrown-3b180b71fa933791.rlib" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\librustc_std_workspace_alloc-5d053d604e1da3fd.rlib" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libunwind-835bbc670368e525.rlib" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libcfg_if-8111a663608e727d.rlib" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\liblibc-35dde82b6021f4d8.rlib" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\liballoc-a187fd59d7a86f05.rlib" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\librustc_std_workspace_core-81a0f0dbfa7b5ebf.rlib" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libcore-ced9603eedaff686.rlib" "C:\\Users\\camer\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libcompiler_builtins-2960d62a9b1d31c1.rlib" "-l" "c" "-s" "ERROR_ON_UNDEFINED_SYMBOLS=1" "-s" "ASSERTIONS=1" "-s" "ABORTING_MALLOC=0" "-Wl,--fatal-warnings"
  = note: error: undefined symbol: __gxx_personality_v0 (referenced by top-level compiled C/C++ code)
          warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
          warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
          warning: ___gxx_personality_v0 may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
          Error: Aborting compilation due to previous errors
          emcc: error: 'C:/Users/camer/Documents/Tech/emsdk/node/14.15.5_64bit/bin/node.exe C:\Users\camer\Documents\Tech\emsdk\upstream\emscripten\src\compiler.js C:\Users\camer\AppData\Local\Temp\tmp6dw5_wby.txt' failed (returned 1)


error: aborting due to previous error
```

</p>
</details>

**Comment by creikey** [comment]
```
emcc --check
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.23 (b15ca40ca02f469de3bf9a4de67a2655aede8974)
```

**Comment by creikey** [comment]
Also is broken on ubuntu with the same error message (at least windows subsystem for linux)

**Comment by strager** [comment]
rustc 1.53.0-nightly (42816d61e 2021-04-24)
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.12 (d0e647bf266caad50943e78c9841e05e9c499a5d)

Here's some info I gathered:

* Rust tries to [use `__gxx_personality_v0`](https://github.com/rust-lang/rust/blob/d2091147b16a1e3e1f9a73b6ee29fbe941c8abce/library/panic_unwind/src/emcc.rs#L116). I think Rust is assuming that this symbol comes from emscripten.
* emscripten has a [few different libc++abi implementations](https://github.com/emscripten-core/emscripten/blob/d0e647bf266caad50943e78c9841e05e9c499a5d/tools/system_libs.py#L887):
  * libc++abi.a: emscripten exceptions: this is what rustc is trying to use; [does *not* compile cxx_personality.cpp](https://github.com/emscripten-core/emscripten/blob/d0e647bf266caad50943e78c9841e05e9c499a5d/tools/system_libs.py#L929-L932)
  * libc++abi-noexcept.a: no exceptions: does *not* compile cxx_personality.cpp
  * libc++abi-except.a: wasm exceptions: experimental; [exports `__gxx_personality_wasm0`](https://github.com/emscripten-core/emscripten/blob/d0e647bf266caad50943e78c9841e05e9c499a5d/system/lib/libcxxabi/src/cxa_personality.cpp#L969)
* `git log` in emscripten's repo shows that cxa_personality.cpp was never compiled into libc++abi.a by tools/system_libs.py.
* This commit looks suspicious: https://github.com/emscripten-core/emscripten/commit/b43d3dee52dedd1ecbe2c99157d28740347d7bf9
* Prior to emscripten SDK version 2.0.10, I think `__gxx_personality_v0` has been [stubbed out for 6 years](https://github.com/emscripten-core/emscripten/blame/8e154f549c7c21b7aabae3dcb03790e51513decd/src/library.js#L755) and never did anything.
* Rust probably shouldn't be calling a stubbed function. emcc.rs seems untested if you ask me because I don't know how it could ever have worked.

**I successfully compiled hello world with emscripten SDK version 2.0.9.** That version still has the `__gxx_personality_v0` stub.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2385821.20Emscripten.20wasm32.20compilation.20broken) of the Prioritization Working Group. Let's find someone who can have a look at this.

@rustbot label -I-prioritize +P-high +I-nominated

**Comment by lopopolo** [comment]
I recall with the LLVM 11 upgrade, the compat notes mentioned which version of Emscripten to use when compiling with the `wasm32-unknown-emscripten` target.

https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1470-2020-10-08

> [Bumped the minimum supported Emscripten version to 1.39.20.](https://github.com/rust-lang/rust/pull/75716/)

Once this bug is resolved, can we add a similar note for the releases that upgrade Rust to LLVM 12?

**Comment by nosense-cz** [comment]
As @strager mentioned the panic=unwind strategy is broken on wasm32-unknown-emscripten. I recommend to switch default to panic=abort. Note that also rust std lib has to be rebuilt with panic=abort to fix the undefined symbol errors. Testing on my side showed that the problem could be fixed by changing TargetOptions on line 38 to "panic_strategy: PanicStrategy::Abort," in rust/compiler/rustc_target/src/spec/wasm32_unknown_emscripten.rs file. Unfortunatelly I do not have experience in preparing pull request and have no capacity to get into it now.

**Comment by tmarkovski** [comment]
This issue can be solved by setting the env var `export EMMAKEN_CFLAGS="-s ERROR_ON_UNDEFINED_SYMBOLS=0"` which will override any flags passed to emcc.

See this comment - https://github.com/rust-lang/rust/issues/41750#issuecomment-312510034

Passing these flags using the `.cargo/config` won't work, as they are not passed to the linker.

```
EMMAKEN_CFLAGS="-s ERROR_ON_UNDEFINED_SYMBOLS=0 --no-entry" cargo build --target wasm32-unknown-emscripten`
```

I received this error in two places, one for symbol `__gxx_personality_v0` and one for `main`, hence the added `--no-entry` flag.

**Comment by hoodmane** [comment]
Reported this on Emscripten: 
https://github.com/emscripten-core/emscripten/issues/17128
