### ISSUE TITLE
Run unit tests by passing a file path

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#86421]
Currently, we have to invoke the following to run specific unit tests:

```
./x.py test compiler/rustc_data_structures/ --test-args thin_vec
```

This isn't straightforward, it'd be great if we could do with:

```
./x.py test compiler/rustc_data_structures/src/thin_vec/tests.rs
```

But unfortunately, it fails currently:
```
thread 'main' panicked at 'error: no rules matched compiler/rustc_data_structures/src/thin_vec/tests.rs', src/bootstrap/builder.rs:225:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## meta

This happens on b17d9c1332693fc386f5374f0d63aae0ce5abab5.

(This was originally reported on https://github.com/rust-lang/rustc-dev-guide/issues/1138)

**Comment by fee1-dead** [comment]
I would like to work on this.

@rustbot claim

**Comment by asquared31415** [comment]
Curiously, passing a file like `./x.py test ./src/test/blah/file.rs` only **recently** started working for me, and never used to work.  The only difference I see in what you have as an example is the leading `./` in the test path, however it also works to omit that for me like `./x.py test src/test/blah/file.rs`

I understand "it works for me" is incredibly unhelpful, so if anyone can think of ways to try and narrow down why it only sometimes works for some people, I would be happy to assist in testing things.  I am on a x86_64 linux system, and it is definitely working at commit 9fef8d91b4a6c5bfe07c025c434f2d623ad83337 (June 16, 2021) which is *before* the commit in the issue here.  However the original issue was reported 14 days ago.  I highly doubt that something fixed and then re-broke the test runner, so I imagine it's something setup-dependent.

**Comment by fee1-dead** [comment]
@asquared31415 `src/test/*` stuff are suites and unlike normal unit tests on crates. I believe that is what makes the difference.

**Comment by asquared31415** [comment]
Ohhhh my bad, I misinterpreted

**Comment by fee1-dead** [comment]
I have made a pull request that accepts a file path but runs *all* tests in that crate. I could not figure out how to test only the path/file specified.

**Comment by Mark-Simulacrum** [comment]
As mentioned in https://github.com/rust-lang/rust/pull/86459#issuecomment-890534891, I'm going to go ahead and close this issue -- I don't think this is something we want to track as rustbuild work.
