### ISSUE TITLE
Match statement requires impossible to reach code/cases for clamped integer types

### ISSUE THREAD

**Issue by jweinst1** [rust-lang/rust#86482]
It seems that rust requires the handling of all cases in match statement even if the integer type is constricted or clamped such as in `match a & 0b11` , where the integer being matched must be , 0, 1, 2, or 3. I do understand that rust promotes the idea of accounting for all possible cases of a type in a match statement, but this particular scenario requires one to write unreachable code, which seems like a bug:

I tried this code:

```rust
   let a = 0b11010;
   match a & 0b11 {
       0b0 => println!("got 0!"),
       0b1 => println!("got 1!"),
       0b10 => println!("got 2!"),
       0b11 => println!("got 3!")
   }
```

I expected to see this happen: *I expected the code to function normally and write "got 2!" to the terminal*

Instead, this happened: * I got the below error*

```rust
error[E0004]: non-exhaustive patterns: `i32::MIN..=-1_i32` and `4_i32..=i32::MAX` not covered
 --> src/main.rs:4:10
  |
4 |    match a & 0b11 {
  |          ^^^^^^^^ patterns `i32::MIN..=-1_i32` and `4_i32..=i32::MAX` not covered
  |
  = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
  = note: the matched value is of type `i32`
```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.1 (9bc8c42bb 2021-05-09)
binary: rustc
commit-hash: 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
commit-date: 2021-05-09
host: x86_64-apple-darwin
release: 1.52.1
LLVM version: 12.0.0
```

**Comment by klensy** [comment]
Match works on type, not on value.

**Comment by Lonami** [comment]
This case if trivial, but as soon as the code is refactored (think a function producing the value) or even moved into another crate, the invariant could easily be lost on accident. There are ways around this, such as using a new-type that ensures the values are correct (think `NonZero`), or using `unreachable!()`:

```rust
match a & 0b11 {
    0b0 => println!("got 0!"),
    0b1 => println!("got 1!"),
    0b10 => println!("got 2!"),
    0b11 => println!("got 3!"),
    _ => unreachable!()
}
```

This is safe because at worst the code will `panic!()`, and the `match` is still an expression returning a value. The desired analysis can get really expensive, which I don't think is worth considering `unreachable!()` exists and is fine for cases like this (these are my opinions).

**Comment by jonas-schievink** [comment]
Yes, this is working as intended for now
