### ISSUE TITLE
.to_owned()   and .unwrap() can be ommited?

### ISSUE THREAD

**Issue by cnmade** [rust-lang/rust#86591]
.to_owned()   and .unwrap() can be ommited?

Did the compiler smart enought to know to_owned and unwrap for me ?

Why let me to type   `.to_owned()`  and `.unwrap()` again and again.

You guys genius.

```
/// # use ipc_channel::ipc;
/// #
/// # let (tx, rx) = ipc::channel().unwrap();
/// # let (embedded_tx, embedded_rx) = ipc::channel().unwrap();
/// # let data = [0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x00];
/// // Send the IpcSender
/// tx.send(embedded_tx).unwrap();
/// // Receive the sent IpcSender
/// let received_tx = rx.recv().unwrap();
/// // Send data from the received IpcSender
/// received_tx.send(data.clone()).unwrap();
/// # let rx_data = embedded_rx.recv().unwrap();
/// # assert_eq!(rx_data, data);
```
If .unwrap() should be in each line of the code, It should be auto do the great job. 
Why just let programmer coding hard work.

**Comment by fee1-dead** [comment]
`unwrap` shouldn't be used in production anyways - `?` should be used instead.

**Comment by cnmade** [comment]
@fee1-dead saddly i can see the code .unwrap everywhere, i can see most Rust project contain the .unwrap()

**Comment by the8472** [comment]
>  saddly i can see the code .unwrap everywhere

Yes, that's the point, you can *see* it. It makes the way error cases are handled explicit, i.e. it makes it visible that the code may panic in many places because that's the only way it's handling errors.

Code that handles errors differently will also look different. If you pass it to the caller (via `?`) it'll be more concise and better. If an error is recoverable it should be handled with a `match` instead.

**Comment by jhpratt** [comment]
Both `.to_owned()` and `.unwrap()` perform important functionality that should not be hidden from the person writing code.

**Comment by cnmade** [comment]
@jhpratt It's not means hide. just let compiler do dirty job. and other programming language will not do like this way. the compiler do jobs lots, the free the people will be.

**Comment by jhpratt** [comment]
@cnmade You're asking for it to be omitted — that's hidden. If it's wholly inferred, how will the user know that something could **panic**? Or that they're performing a heap allocation? Those are quite important details to not gloss over.

**Comment by cnmade** [comment]
@jhpratt even we do not write .unwrap, Rust can panic always, every sys call may occurs panic, i see too many panic, so what's the problem if we do not write .unwrap.

**Comment by jhpratt** [comment]
I take it you haven't written much Rust code? Genuinely asking. It is unidiomatic for Rust to do something without being asked. While, yes, this can panic, it also changes the type in a nontrivial way. This could actually lead to other inference issues, not the least of which due to autoderefencing.

If you truly believe you have something that is worth it (which frankly I would strongly oppose), you can open a thread on internals.rust-lang.org. Come prepared with evidence, an explanation of how this would work, potential issues, and much more. Without **all** of that, your idea will almost certainly get shot down immediately. The rust-lang issue tracker isn't the appropriate place to be asking for such a fundamental change to the language.

**Comment by cnmade** [comment]
@jhpratt To be honest, This is like feature request, not question or talking about. If you think we should close this feature request, just close it. thanks.

**Comment by jhpratt** [comment]
I don't have the permission to close it. My point is that a feature request without _anything whatsoever_ backing it up will inevitably get shot down. This is a fundamental change to the language you're talking about — just saying "please do this" isn't enough.
