### ISSUE TITLE
regression: infallible residual could not convert error

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#86831]
* https://crater-reports.s3.amazonaws.com/beta-1.54-1/beta-2021-06-23/reg/sierra-proc-demo-0.1.0/log.txt

I assume this is something subtle in the new Try trait -- would be good to investigate. Looks like only one case found in crater, so probably not too big a deal, but ideally we'd have zero regressions from the new design.

cc @scottmcm

**Comment by Mark-Simulacrum** [comment]
I'll put https://crater-reports.s3.amazonaws.com/beta-1.54-rustdoc-1/beta-2021-06-23/reg/twelf-0.1.7/log.txt under this issue for now as well since it looks like it caused by the try migration as well, though maybe distinct. Is that intentionally broken? I recall discussions about the NoneError conversions...

**Comment by the8472** [comment]
> Is that intentionally broken? I recall discussions about the NoneError conversions...

Looks like it https://github.com/rust-lang/rust/issues/46871#issuecomment-852663986

**Comment by scottmcm** [comment]
For the sierra thing, it looks like this is a place where they unwittingly used never type on stable, and that's the core of why it changed.

The code that broke is
```rust
let total_size_usize = group_size_usize
    .checked_mul(info.groups.len())
    .ok_or_else(host_memory_space_overlow)?;
```
where the function is
```rust
pub fn host_memory_space_overlow() -> ! {
    panic!("Memory address space overlow")
}
```
Repro: https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=f90e3876b81fc12b185284b5006457ba

It actually works fine if it's changed to
```rust
.ok_or_else(|| host_memory_space_overlow())?;
```
https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=f4b06b729fc59aa3226e64b1deaaaf4b

I'll send them a PR.

Aside: This is one of those spots that I think could be nice with `let`-`else`, since it would emphasize that the function called diverges:
```rust
let Some(total_size_usize) = group_size_usize
    .checked_mul(info.groups.len())
else { host_memory_space_overlow() };
```

---

The dhall one is known, and was fixed back in March, in https://github.com/Nadrieril/dhall-rust/commit/846c14f92bda2fb3e68c3debf940414628013574

So twelf should also be fixed as of https://github.com/bnjjj/twelf/commit/3ad9fc58498078d080b0eaed3cb7d72b91821fff (thought it's not clear to me what version that would be)

**Comment by yaahc** [comment]
We discussed this in today's @rust-lang/libs  meeting and decided that since we already approved this breakage during the RFC and the breakage has already been fixed in the repo that was caught by crater we're happy with the current status and should close this issue.

@rfcbot close

**Comment by Mark-Simulacrum** [comment]
Marking as relnotes per FCP.

**Comment by pthariensflame** [comment]
So…will this actually be closed then?
