### ISSUE TITLE
Prelude collision lint: invalid suggestion for T::from_iter when T is generic.

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#86940]
For generic types, the prelude collision lint can produce suggestions that do not compile:

Code:
```rust
struct Generic<T>(T);

trait Hey { fn from_iter(_: i32) -> Self; }

impl Hey for Generic<i32> { fn from_iter(x: i32) -> Self { Self(x) } }

impl std::iter::FromIterator<i32> for Generic<i32> { fn from_iter<T: IntoIterator<Item = i32>>(_: T) -> Self { todo!() } }

fn main() {
    Generic::from_iter(1);
}
```
Suggestion from the prelude collision lint:
```
warning: trait-associated function `from_iter` will become ambiguous in Rust 2021
  --> src/main.rs:10:5
   |
10 |     Generic::from_iter(1);
   |     ^^^^^^^^^^^^^^^^^^ help: disambiguate the associated function: `<Generic as Hey>::from_iter`
   |
   = note: `-W rust-2021-prelude-collisions` implied by `-W rust-2021-compatibility`
   = warning: this is accepted in the current edition (Rust 2018) but is a hard error in Rust 2021!
   = note: for more information, see issue #85684 <https://github.com/rust-lang/rust/issues/85684>
```
Error after applying the suggestion:
```
error[E0107]: missing generics for struct `Generic`
  --> src/main.rs:10:6
   |
10 |     <Generic as Hey>::from_iter(1);
   |      ^^^^^^^ expected 1 generic argument
   |
```

**Comment by m-ou-se** [comment]
cc @nikomatsakis @jam1garner

**Comment by jam1garner** [comment]
My guess is this should be a simple fix, just copying the code the lint already uses for adding unspecified generics (`Foo<_, _>`). Will try implementing a fix soon.

**Comment by nikomatsakis** [comment]
### Mentoring notes

The code related to this lint lives in the [prelude2021 module](https://github.com/rust-lang/rust/blob/master/compiler/rustc_typeck/src/check/method/prelude2021.rs). 

The relevant suggestion is generated here:

https://github.com/rust-lang/rust/blob/b9197978a90be6f7570741eabe2da175fec75375/compiler/rustc_typeck/src/check/method/prelude2021.rs#L264-L269

The "self type" string comes from here:

https://github.com/rust-lang/rust/blob/b9197978a90be6f7570741eabe2da175fec75375/compiler/rustc_typeck/src/check/method/prelude2021.rs#L258-L262

The code for traits is here:

https://github.com/rust-lang/rust/blob/b9197978a90be6f7570741eabe2da175fec75375/compiler/rustc_typeck/src/check/method/prelude2021.rs#L242-L251

This is actually just a *touch* tricky, because currently we are getting the "self type" just by copying the text the user wrote. Probably the *most correct* thing for us to do would be to examine the 'self expression' HIR and, if it is a plain path, then to append the `<_>` and otherwise skip it. 

Specifically, the other case that I am thinking about is code like this: 

```rust
#![warn(rust_2021_compatibility)]

struct Generic<T>(T);

trait Hey { fn from_iter(_: i32) -> Self; }

impl Hey for Generic<i32> { fn from_iter(x: i32) -> Self { Self(x) } }

impl std::iter::FromIterator<i32> for Generic<i32> { fn from_iter<T: IntoIterator<Item = i32>>(_: T) -> Self { todo!() } }

fn main() {
    <Generic<_>>::from_iter(1);
}
```

Currently [this test works](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7db386dac8db55428b05955df1bdeb0f), meaning that it offers the suggestion "disambiguate the associated function: `<Generic<_> as Hey>::from_iter`".

**Comment by nikomatsakis** [comment]
@Pyther99 great! Let us know if you need anything or make progress. This issue is fairly time sensitive.
