### ISSUE TITLE
Unrelated changes make multiple-definitions test fail spuriously

### ISSUE THREAD

**Issue by fee1-dead** [rust-lang/rust#87084]
The test was originally added in #86419, see the comments under that for more discussion.

#86922 and #86857 fails with this diff:
```diff
10 error: multiple definitions of external function `f` from library `foo.dll` have different calling conventions
-   --> $DIR/multiple-definitions.rs:8:5
12    |
12    |
- LL |     fn f(x: i32);
-    |     ^^^^^^^^^^^^^
+ LL |         fn f(x: i32);
```
#87075 was opened, removing the `^^^` and adding indentation (I did not see that it suggested removing `--> $DIR/...`). It fails with this diff:

```diff
10 error: multiple definitions of external function `f` from library `foo.dll` have different calling conventions
12    |
12    |
- LL |         fn f(x: i32);
+ LL |     fn f(x: i32);
14 
15 error: aborting due to previous error; 1 warning emitted
```

I just want to say that I don't think there was some nondeterministic code causing the span to be different (at least in the file that emitted the diagnostic), as shown on these lines, where they get sorted, deterministically:
https://github.com/rust-lang/rust/blob/a867dd4c7e65beb1453fcff9e252e7ab19f0e1d0/compiler/rustc_codegen_ssa/src/back/link.rs#L483-L487

@rustbot label A-spurious C-bug T-compiler

**Comment by joshtriplett** [comment]
At this point I think we may want to revert the addition of the test until this issue can be debugged, to avoid spuriously breaking other PRs.

**Comment by fee1-dead** [comment]
They are removed in #87087.

@rustbot label F-raw_dylib

**Comment by ricobbe** [comment]
In the interest of time feel free to assign this issue to me, in case anyone sees it before I can find the appropriate rustbot command.

**Comment by RalfJung** [comment]
> where they get sorted, deterministically:

Could the use of `sort_unstable` be the problem here?

**Comment by ricobbe** [comment]
> Could the use of `sort_unstable` be the problem here?

I don't think so, no.  The problem is that the error message only occurs when we have multiple `DllImport`s in the same `FxHashSet` that have the same name (plus a couple of other conditions that aren't important for this issue).  So sorting the elements of an `FxHashSet<DllImport>` based solely on their names, as is the case on master, isn't sufficient to guarantee a unique result when we select the second `DllImport` that has a duplicate name.  Just using a stable sort wouldn't help either, IIUC, since the original order in the hash set is effectively nondeterministic.

Sorting the `DllImport` values based on all of their fields instead of just the name, as in the linked PR, should remove this nondeterminism.
