### ISSUE TITLE
Experiment with using objects in the visitor walk routines to avoid code explosion

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#8715]
In an effort to reduce the number of duplicated methods, I made a branch that uses objects in the `walk` routines for the visitor. This, in combination with porting more visitors to avoid the `E` parameter (i.e., to use `Visitor<()>`), should help quite a bit. However, it currently encounters a crash.

**Comment by steveklabnik** [comment]
@nikomatsakis do you still have plans to do this? Is keeping this kind of issue open worthwhile?

**Comment by apasel422** [comment]
I'm not sure that this is possible due to object-safety. `Visitor` cannot be turned into an object without removing the `Sized` bound, but removing the `Sized` bound prevents `&mut self` from coercing to `&mut Visitor` in the default method bodies (without an additional `where Self: Sized`). It would only be possible by removing the default method bodies and requiring each visitor to implement them separately, which seems to defeat the purpose of this.

**Comment by nikomatsakis** [comment]
I think this is probably possible, but yeah it'd require some deep refactoring at this point. Given all the conversions that are going on (e.g., transition to MIR etc), I'd say this issue is probably just something we should close right now. (And I will do it!)
