### ISSUE TITLE
Decide whether `asm!` and/or `global_asm!` should be exported from the prelude. 

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#87228]
In https://github.com/rust-lang/rust/issues/84019 it was decided that `asm!` and `global_asm!` should be defined in `core::arch` rather than be defined in the crate root. Whereas anything defined in the crate root is essentially "in the prelude" by necessity, being defined elsewhere means that we have the option of deciding whether or not these macros should be exported from the prelude.

In the original Zulip thread regarding which module these macros should be defined in, there was a small amount of discussion as to whether or not these should additionally be exported from the prelude: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/namespacing.20.60asm!.60/near/233407632 . There did not seem to be a clear prevailing opinion.

Furthermore, I faintly recall from the most recent libs-api meeting someone mentioning that adding new macros to the prelude (or even the crate root) might be a compatibility hazard, and should only be done during an edition. I'm not sure if this is an official policy or not.

Note that this is not a blocker for `asm!` stabilization, as the item can be stabilized at `arch::asm` and exported from the prelude any time in the future.

**Comment by BurntSushi** [comment]
For me personally, it feels a little weird to put it in the prelude, especially if it's really just for marketing purposes. Inline assembly is a rarely used feature, so tucking it away into a module feels like the right thing to me.

Of course, making it easy to discover features is important too. My hope is that after inline assembly lands, doing a web search for "rust inline assembly" will (eventually) bring you to the right place. Maybe that's good enough?

**Comment by joshtriplett** [comment]
"marketing" is an interesting angle I hadn't considered.

Personally, I think these should be in the prelude for a different reason: to make them feel like innate language capabilities. You don't have to import a name from a module to use things like async and await, or closures, or (in the future) generators. I think inline assembly should feel the same way.

**Comment by thomcc** [comment]
My gut feeling is that inline assembly uses macro syntax might mean that it won't feel like an innate language capability even if it is in the prelude.

I think putting it in a module<sup>1</sup> is the right balance given how rarely it's used, and I say this as someone who uses it frequently, even in its current unstable state.

1: Well, fine so long as it's not a different module for each arch, which I believe is no longer being considered.

**Comment by Amanieu** [comment]
I feel ambivalent about this: I am probably one of the bigger users of `asm!` (78 uses over 10 files), but adding an import line for this is really very little effort that I don't mind it. In the end, I am happy with both options.

**Comment by npmccallum** [comment]
I'm a pretty big user of this (at least a few dozen invocations across a bunch of crates). I also don't mind an import line. I suspect that use of this feature is somewhat uncommon and I'd hate to litter the prelude for my minor inconvenience. Anyone who needs this feature knows they need it and can google it. I don't see a reason to advertise it.

I use `TryFrom` a *lot* more and it isn't (yet) in the prelude (this one does bug me...).

**Comment by thomcc** [comment]
> adding an import line for this is really very little effort that I don't mind it.

Ultimately, the fact that you'll be able to use it as `core::arch::asm!` is why I don't mind. If it required a separate import line (the way traits do), I'd not be a fan. (That said, this would be terribly inconsistent with how other macros work, so I don't think anybody else would be either)

**Comment by joshtriplett** [comment]
On Fri, Aug 13, 2021 at 10:46:17AM -0700, Thom Chiovoloni wrote:
> Ultimately, the fact that you'll be able to use it as `core::arch::asm!` is why I don't mind.

That feels obtrusive in modules that use many, many asm blocks. That
contributes to that feeling of "not a native Rust language feature" that
I'd like to avoid. You don't have to include a specific header to use
`__asm__` in C.

**Comment by BurntSushi** [comment]
@joshtriplett Could you say more about why you want it to feel like an innate language feature? Is it primarily because it feels that way in C?

**Comment by joshtriplett** [comment]
@BurntSushi Sure. Off the top of my head, trying to introspect on that feeling: I'm thinking about the mindset associated with one of the types of development that commonly invokes inline assembly: low-level OS/firmware/systems/etc programming. Much like many other compiler attributes that control binary sections, linker attributes, and similar, this feels like something that should have a direct straightforward meaning in code generation, with zero flexibility for the compiler. This is a "drop down to low-level assembly" mechanism, and it fits well into a mindset of thinking of *all* of your code in terms of the semantics of the underlying assembly.

In addition, assembly is a feature that fundamentally *must* integrate natively with the compiler's code generation, and can't be done purely using library mechanisms, because it has to handle things like clobbers, and arrange for the right inputs to be in the right registers. So it feels right for it to be built into the language. And something that's available via a specific library path doesn't feel like "part of the language".

(The other common case for inline assembly is optimization, for which I'd expect this to feel like less of an issue.)

**Comment by bstrie** [comment]
For people who would like to see `asm` in the prelude, what is your opinion on having `global_asm` in the prelude? Is only the former important enough to warrant it, or do you see them as a package deal?

(Also to reiterate, there is no urgency to this decision as it's not a blocker for stabilizing `asm`.)

**Comment by joshtriplett** [comment]
@bstrie I personally think the same logic applies to `global_asm`, and it's not like the name `global_asm` is likely to conflict with anything. I don't consider them a package deal, though, and I place more importance on having `asm` in the prelude.

**Comment by joshtriplett** [comment]
@rfcbot merge

In advance of the next time this gets discussed in a meeting, I'd like to use rfcbot to gauge consensus on keeping `asm!` (and `global_asm!`) in the prelude.

I personally believe they should be available without an import, to give them the appearance of a built-in language mechanism (which they inherently have to be).

**Comment by workingjubilee** [comment]
From the perspective of someone who previously used Python, having to import to do IO, when Python has `open` as a builtin, feels odd. From the perspective of someone who previously used JavaScript, having even trivial math and logging functions be (somewhat) scoped feels normal, but the rules around strings, arrays, and Vecs get quite strange. Rust makes `println!` available in the prelude, even though its cousin requires `#include <stdio.h>` in C. All of these have caused me odd little impedances when context switching between each of these languages and Rust. I always get the C compiler to yell at me about using a function that's not declared, and I try looking in a library instead of the builtins for `open()`, and... you get the idea.

And for x86 assembly... For Rust, libcore is really required to make things "go", but the parts that are injected into the prelude are rather arbitrary, based largely on frequency of use. A rather lot of things in libcore degrade to intrinsics which wind up being pretty direct invocations to the compiler, yet not all such things in libcore are in the prelude. I do not see how `asm!` or `global_asm!` is truly different from the compiler intrinsic functions in `core::arch`, for example, most of which have a direct 1:1 lowering, and are functionally almost-equivalent to injecting the equivalent assembly, even linking against LLVM IR that is target-arch-scoped.

I do not have any fundamental objection, however, to choosing either way.

**Comment by mark-i-m** [comment]
I would also like to see `asm!` in the prelude. My "feeling" is similar to Josh's. As a low-level programmer, `asm!` is a fundamental low-level utility; I feel about `asm!` how others might feel about `Vec` or `Option`. Requiring a special import for `asm!` makes it feel like systems program is a second class concern for rust. I'm not sure if that's reasonable or not, but that's my gut reaction.

Also, the primary objection seems to be cluttering up the macro namespace, but I don't think I have ever seen another macro called `asm!` or `global_asm!` before, so I'm skeptical this should be a concern.

**Comment by BurntSushi** [comment]
I personally did not tick my box because I'm not really convinced at all that either of these macros should be in the prelude, now that we have the ability to namespace macros. I just do not think inline assembly is anywhere _near_ common enough to be deserving of it. I do not think comparisons to `Vec` or `Option` are particularly good here, because the frequency of use across all domains is no where near the same.

I've stopped short of registering a blocking concern because I don't know that I feel strongly enough to go be a lone voice against this if everyone else wants it.

**Comment by workingjubilee** [comment]
> 
> 
> I would also like to see `asm!` in the prelude. My "feeling" is similar to Josh's. As a low-level programmer, `asm!` is a fundamental low-level utility; I feel about `asm!` how others might feel about `Vec` or `Option`. Requiring a special import for `asm!` makes it feel like systems program is a second class concern for rust. I'm not sure if that's reasonable or not, but that's my gut reaction.

C requires `#include <stdlib.h>` for `malloc` and `free`, Rust does not for Vec.
Actually, now I do have an objection, and not just a comment:

All of these comparisons propose Rust should define itself in terms of other languages when it is not one.
However, if we wish to make Rust more like other languages, such as C, then I see no deep reason not to.
Let us drop `std::vec::Vec` from the prelude and namespace `println!` when we add `asm!`, so we can make Rust more like C.

**Comment by workingjubilee** [comment]
Less flippantly: "I feel so-and-so is very fundamental to my concerns" applies for **every single function, type, and macro in std**. Why not Error? Why not Arc, or Mutex, as those are very often used in multithreaded programming? That's something Rust is **uniquely good** at, why not market those? Sure, I guess we don't like our Mutex much. How about the Atomics instead?

All of the proposed Simd types and the existing `std::arch` compiler intrinsic functions certainly require a lot of compiler assistance, so they fill that criteria. And for the portable versions, it will be a distinct capability, too, not something all languages get as strong a hand in, so it's quite "marketable". And graphics programming and digital signal processing use SIMD a lot,

And it occurs to me that moving something into the prelude has a serious drawback that no one seems to have discussed:
It makes it **much** harder to figure out where it is coming from.

It's quite possible **nothing** as rare in use as `asm!` should be in the prelude's namespace, because then it will not be **immediately** obvious from the file and tracing it to that fateful `use std::arch::asm;` where it comes from, and thus which module to look in.

Rust is a programming language already used by **millions**. Even if we see a few familiar faces in these discussions again and again, the question should be what we want **all** Rust programmers to find easier, and what legacy we wish to leave for the **next** generation of programmers, which will be **far** more numerous.

I am not sure that introducing something into the prelude's namespace is not merely about convenience. I think it is expressing an **expectation** that Rust programmers know what it is and where they can find it if they need to read up on it. This is a mental toll on learning Rust, and the toll is already high, with understanding the semantics of Vec, String, Option, and Result, From and Into.

**Comment by mark-i-m** [comment]
I actually wish those things were in the prelude, along with all the collection types. Importing them feels like a completely unnecessary papercut to me. (I'm inclined to say that nearly everything in std should be in prelude, but I haven't thought through the implications enough to go that far).

I don't really feel that putting something in the prelude makes it harder to find because I almost always search rustdoc by the name of the item, not the module. I think it should be considered poor style to define a type with the same name as a std type.

**Comment by workingjubilee** [comment]
"I do so-and-so" yes, I understand that, and what about someone new to Rust? What about someone who doesn't have IntelliSense assistance and doesn't know they should be searching using rustdoc specifically yet and is just throwing terms into Google to see what hits they get?

Why are we saying "if asm! isn't in the prelude, it's a sign it's not serious about systems programming" and in doing so suggesting that if someone doesn't interact with asm!, they aren't a systems programmer? How many contributors to even something like the Linux kernel have really diffed its files with assembly, inline or not, versus the many others who have worked almost purely in C? Or Perl or Bash, for that matter.

**Comment by mark-i-m** [comment]
> "I do so-and-so" yes, I understand that, and what about someone new to Rust? What about someone who doesn't have IntelliSense assistance and doesn't know they should be searching using rustdoc specifically yet and is just throwing terms into Google to see what hits they get?

I don't have intellisense either. And I believe for most std types if you google them, one of the top results is the std rustdoc for the appropriate type.


> and in doing so suggesting that if someone doesn't interact with asm!, they aren't a serious systems programmer? How many contributors to even something like the Linux kernel have really diffed its files with assembly, inline or not, versus the many others who have worked almost purely in C? Or Perl or Bash, for that matter.

I neither said nor implied any of this. My point was only that asm is an important and frequently used tool for an important subset of problems rust seeks to solve. Having unnecessary papercuts produces a sense that those use cases have been deprioritozed.

**Comment by workingjubilee** [comment]
>I neither said nor implied any of this.

My apologies for misunderstanding you, then. It is what I took from

> Requiring a special import for asm! makes it feel like systems program is a second class concern for rust. I'm not sure if that's reasonable or not, but that's my gut reaction.

generalized: "requiring an import makes so-and-so (Atomics, w/e) feel like a second class concern"
and "first-class treatment of asm is required for systems programming"
disjunctively "no asm means not systems programming".

I don't think you meant it directly per se, which is why I am asking... why? It's just... perplexing? as a line of reasoning? It's fine to cater to the needs of _assembly_ programmers, but...

> I don't have intellisense either. And I believe for most std types if you google them, one of the top results is the std rustdoc for the appropriate type.

I mean, my first hit for Option is investopedia, and my first hit for Future is the rapper's Wikipedia page... but you probably meant with additional qualifications. And that's kind of my point: `use core::arch::asm;` or `core::arch::asm!()` is so unmistakably Rust that you don't even have to know it came from an `.rs` file to know what language it is. And there are contexts you might not, but the search engine would always get it right if you had that much.

As far as importing std into the prelude: well, the portable SIMD project would probably break something if that happened, because we used some names that have... strong ecosystem conventions around them. So uh, while that API isn't settled yet, I can see it going... poorly? But I don't think I should be dissatisfied or feel like it is second class just because it requires a `use core::simd::*;` to work.

But if a single line for an import _is_ seen as a big papercut, shouldn't we look at that as a real concern on an ecosystem wide basis instead of an ad hoc one?

**Comment by matklad** [comment]
From IDE perspective, i’d prefer this to not be in prelude: unrelevant symbols pollute completion just a tiniest bit, but, adding that together across all completion invocations seems like it can add up.

Don’t have a strong opinion here: at the moment rust-analyzer has abysmal filtering&ordering of completions, so the diff from addition of `asm!` is hard to estimate.

**Comment by inquisitivecrystal** [comment]
I think the strongest argument in favor of including `asm!` in the prelude is that it's so fundamental. It feels like it's part of the language, even if it's syntactically a macro. It's not something a user would be able to reimplement. While it may not be used often enough to justify its inclusion on the basis of convenience, I think it would be more confusing to have to import a fundamental language construct.

**Comment by workingjubilee** [comment]
Rust is a systems language, though. I would hope that over time the argument that it is a "built-in language facility" applies less and less as we perfect the abstractions Rust currently offers, even for `asm!`. And a proc macro that parses the normal format for a `core::arch::asm!` invocation and re-emits a call to `core::arch::asm!` with some useful improvement, and is thus usable as a "drop-in" replacement for such if imported if someone wills it, should definitely be "in-scope" for code we can expect programmers to write. The following crates are mostly legacy at this point but there are several crates which made various attempts at inline assembly, using proc macros and a lot of creativity:

Using the "parse a sugared input and then re-emit to `llvm_asm!`" approach: https://crates.io/crates/rusty_asm
A... very creative usage of resectioning code and `#[no_mangle]`: https://crates.io/crates/direct-asm
Which itself was based on a fork of https://crates.io/crates/dynasm for runtime assembly.
And there is also this, which extracts and invokes `cc`: https://crates.io/crates/libasm

I suppose it's fine even with that, given that imported or defined macros **can** shadow, though it will remove the trace of the import in the common case and thus may remove attention to that import, as seen in this [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=aa7bd2419110b6cc7926b62f90a8ae20):

```rust
#[macro_use]
pub mod internal {
    macro_rules! format {
        ($x:tt) => { "hell world!" }
    }
}

fn main() {
    let x = format!("hello, world!");
    assert_eq!("hell world!", x);
}
```

**Comment by m-ou-se** [comment]
> if everyone else wants it.

@BurntSushi Most of the boxes were checked during the meeting last week, in which most of us expressed not feeling very strongly about this either way, but also not like we had to block this. So it's not so much "everyone else wants it", but more a "everyone else was okay with it".

The discussion above shiften my own opinion from 'slightly in favour' to 'slightly against'.

The accidental closing and re-opening of the issue 5 days ago seems to have removed the issue from rfcbot. Instead of restarting it and filing a concern, I'm going to take this opportunity to see if there might be consensus for the opposite decision: to *close this* without adding `asm!()` to the prelude:

@rfcbot close

**Comment by m-ou-se** [comment]
@rfcbot cancel

**Comment by m-ou-se** [comment]
@rfcbot close

**Comment by yaahc** [comment]
I'm happy either way, though I do find @matklad's IDE based reasoning to be somewhat compelling.

@rfcbot review

**Comment by joshtriplett** [comment]
@rfcbot concern

I do care enough about this to not want to close it. I still feel like this should feel like part of the language, and feel built in and available.

**Comment by thomcc** [comment]
I think `asm!`/`global_asm!` being in the prelude is a step too far — it's just a little bit *too* accessible there.

It is too easy of way to make your codebase non-portable, and failing to use the write options/clobbers can make it be a performance footgun if you don't know what you're doing (although it's still `unsafe`, which admittedly should be enough to discourage needless use).

That said, putting it in `core::arch` puts it with the rest of the parts of libcore which are "aggressively non-portable" (or something like this), which feels like the right place for it to me.

That is to say: putting it in the prelude seems like it gives a weird message to inexperienced users, and doesn't quite convey how architecture-specific and fiddly it is. Putting it in `core::arch` does, since everything else under `core::arch` is architecture-specific and fiddly.

**Comment by bstrie** [comment]
> And I also don't want this to block the stablisation of asm! (we don't have path stability yet)

Yes, this doesn't block the stabilization of `asm!`; I'm not sure what this is referring to by path stability, but this wouldn't be the first stable namespaced macro exported from libstd.

> I do care enough about this to not want to close it. I still feel like this should feel like part of the language, and feel built in and available.

Worth keeping in mind that the decision *not* to put `asm!` in the prelude is always reversible; obviously we shouldn't re-litigate things endlessly, but there's nothing stopping a sufficiently motivated libs team from putting `asm!` in the prelude in any future edition.

We should also think about how to transition if `asm!` is decided to not be in the prelude. Since it already exists in the nightly prelude, just removing `asm!` from the nightly prelude might be a jarring roadbump if it happens without any warning, since it would force each and every current user of `asm!` to start explicitly importing it. This might involve some teaching, since I suspect plenty of people may have never encountered a namespaced macro before! It seems like it would be less disruptive to leave an unstable `asm!` re-export in the nightly prelude, and just stabilize `core::arch::asm!` separately, so that users will only have to introduce the explicit import if they decide to switch from nightly to stable. (Remind me, stability attributes work on re-exports, right?)

**Comment by inquisitivecrystal** [comment]
> I think `asm!`/`global_asm!` being in the prelude is a step too far — it's just a little bit _too_ accessible there.
> 
> It is too easy of a way to make your codebase non-portable, and failing to use the right options/clobbers can make it be a performance footgun if you don't know what you're doing (although it's still `unsafe`, which admittedly should be enough to discourage needless use).
> 
> That said, putting it in `core::arch` puts it with the rest of the parts of libcore which are "aggressively non-portable" (or something like this), which feels like the right place for it to me.

I wanted to respond to this, specifically. I don't think making it too easy for someone to write assembly is something we should be worrying about. Like, assembly practically *screams* "this is terrifying dark magic". It's a whole extra language that's pretty arcane to the average programmer and is usually significantly more complex than doing things at a higher level. Plus it's unsafe, on top of that.

> Yes, this doesn't block the stabilization of `asm!`; I'm not sure what this is referring to by path stability, but this wouldn't be the first stable namespaced macro exported from libstd.

I agree that this shouldn't block stabilization (not that there's any reason my opinion in particular is relevant).

> We should also think about how to transition if `asm!` is decided to not be in the prelude. Since it already exists in the nightly prelude, just removing `asm!` from the nightly prelude might be a jarring roadbump if it happens without any warning, since it would force each and every current user of `asm!` to start explicitly importing it. This might involve some teaching, since I suspect plenty of people may have never encountered a namespaced macro before! It seems like it would be less disruptive to leave an unstable `asm!` re-export in the nightly prelude, and just stabilize `core::arch::asm!` separately, so that users will only have to introduce the explicit import if they decide to switch from nightly to stable. (Remind me, stability attributes work on re-exports, right?)

My understanding is that stability attributes **don't** work on reexports, per  #30827. It's one of those things that everyone agrees should work and no one is willing to actually do, on account of how complex it is. I could be wrong though.

**Comment by bstrie** [comment]
> My understanding is that stability attributes don't work on reexports, per #30827.

Ah yes, I forgot that `#[stable]` and `#[deprecated]` used the same machinery. Still, it should be possible to do the same thing via a nightly-specific macro defined in the prelude that delegates to `core::asm`, which could be turned into an ordinary re-export if the decision is made to stabilize `asm!` in the prelude.

**Comment by ssokolow** [comment]
> Requiring a special import for `asm!` makes it feel like systems program is a second class concern for rust.

If we're talking about "feel like" and concerns of comparisons with existing low-level languages, I'd like to raise a reminder that MSVC disables support for inline assembly on 64-bit x86 and ARM targets.

> Rust is a systems language, though.

I think it's important to define what is meant by "systems language" here, given that this is one of the areas where the two meanings of the term could have differing implications.

(As [Will Critchton wrote](https://willcrichton.net/notes/systems-programming/), the original definition from 1972 was concerned with maintainable construction of systems infrastructure... a definition which Go satisfies in this Internet age and which arrives at low-level programming more as a side-effect of how many decades it was before "infrastructural" outgrew being more or less synonymous with "needs low-level control".)

"Systems" in the "low-level" sense would argue for `asm!` to be front and center, while "systems" in the "maintainable infrastructure" sense is where some of the concerns *against* putting it in the prelude come from. (eg. onboarding new users, rust-analyzer completion clutter, etc.)

**Comment by jcrevier** [comment]
As someone who probably won't use this feature but is glad it it exists, putting this in the prelude feels very strange to me. It feels nowhere near as fundamental to average rust usage to justify not requiring an explicit import. I think perhaps the fact that asm is unlikely to cause name collision is a big reason this is even considered. But I think that's somewhat of a distraction and should be bracketed from how we justify inclusion in the prelude. In my mind, items in the prelude should have applicability for all or most rust users and I think it's a hard sell to argue asm does.

**Comment by Cyborus04** [comment]
> Like, assembly practically screams "this is terrifying dark magic". It's a whole extra language that's pretty arcane to the average programmer and is usually significantly more complex than doing things at a higher level.

If it's arcane dark magic, why does it need to be so easily accessible? 
If you want to do `asm!` (without the qualifying path), you can just `use std::arch::asm;` to say "gonna be doing some low-level stuff here"

**Comment by HindrikStegenga** [comment]
A many other people mention, this is a feature that is not something you should grasp for quickly and therefore I do not feel it should be put in the prelude. However, what I am more concerned about is that it would bloat IDE/editor suggestions unnecessarily. In particular I can imagine people attempting to write 'async' and the editor also suggesting 'asm!', as both start with the same letters. Especially for a feature that's _very_ rarely if ever used by most programmers.

**Comment by U007D** [comment]
As a user (and lover) of the `asm!` feature, I think it is not used often/broadly enough to be in the prelude.  It's worth pointing out that my favorite feature of Rust 2021 Edition is that `TryFrom` is in the prelude, so I do love me some prelude! 😃 

If it were included I would also worry about the precedent that would set over other 'nice to have' things and/or "marketing features" in the prelude (although I can't say I know anyone who discovered the existence of a feature they were looking for through the prelude).

It just doesn't seem to make the cut, to my eye.  Also a search for "inline assembly in rust" brings up the right results, so it's hard to see how someone looking to do inline assembly would not be able to discover this feature.

**Comment by jmillikin** [comment]
Soft preference for putting `asm!` in the prelude, with some admittedly fuzzy reasoning:
* The macros exported from `core` already include several that feel "less intrinsic" than inline assembly, for example the `assert!` series.
  * This feeling might be because I think of `asm!` as closer to a built-in language keyword like `extern` or `loop`, but expressed as a macro for syntactic reasons.
* Needing to import `asm!` from `core::arch` feels ceremonial, as if the forced import is intended to discourage use of inline assembly. Some of the comments in this thread about `asm!` being "too accessible" are along the same lines.
  * The obligate `unsafe` for inline assembly already serves as a warning and statement of intent.
* The issue of IDE auto-completion (for example `asm!` vs `async`) might be relevant in general, but in this specific case doesn't seem that important, because `assert!` already shadows the first two letters.
* If `asm!` were architecture-specific then I think it would make sense to export from the sub-modules of `core::arch` (similar to the arch-specific intrinsics). But because it's arch-independent, having it in `core::arch` at all feels a bit odd.
  * I would expect a stabilized `asm!` to be defined in the crate root like the other low-level macros, or in `core::macros::builtin` if the `core` root module is off-limits to new symbols.

**Comment by bstrie** [comment]
> I would expect a stabilized asm! to be defined in the crate root like the other low-level macros

@jmillikin , note that most macros are exposed from the crate root for historical reasons related to technological limitations. It's only recently that macros have gained the ability to be namespaced like any other item. Even in the event that the `asm` macro is added to the prelude, the rationale for defining it anywhere other than the crate root is the same reason for defining other prelude'd items like `std::iter::Iterator` or `std::string::String` or `std::marker::Unpin` anywhere other than the crate root.

**Comment by Cyborus04** [comment]
> as if the forced import is intended to discourage use of inline assembly
Actually, yes, I would like to discourage it. It's one of those things that should only be used if you know what it is and are very sure you should

**Comment by joshtriplett** [comment]
We discussed this again in today's @rust-lang/libs-api meeting.

Our consensus was, roughly:
- Many of us would like to avoid the friction of importing `asm` in every module that uses it (e.g. allowing modules to drop in an `asm!("int 3")` or an `outb` to a serial port or debugging device and similar debugging techniques that should be as easy as println debugging).
- However, many of us (an overlapping "many", not a disjoint one) also want to see macros in std/core become more sorted into modules, rather than all being exposed at the top level.
- We could resolve this tension if there were a language feature for "crate preludes", meaning that rather than every *module* having to `use std::arch::asm`, only the top-level module of a crate would need to declare that as being part of the crate's prelude for every module.

We agreed to postpone this library proposal and leave `asm!` and `global_asm!` out of the prelude, in favor of a language proposal for "crate preludes".

We can reconsider this as part of the tradeoffs for evaluating that language proposal.

@rfcbot cancel

@rfcbot postpone
