### ISSUE TITLE
Use u32 instead of usize in ArcInner to save memory

### ISSUE THREAD

**Issue by eloff** [rust-lang/rust#87294]
There's little point to using usize instead of u32 for Arc. There's no desirable reason to have more than 4 billion strong or weak references to an Arc. It's weird that 32bit and 64bit platforms would support different amounts of references, but fortunately because there's no reason to do that, nobody thinks about this in practice when targeting multiple platforms.

We can save 8 bytes on 64bit platforms per Arc (and the associated cache pressure) by switching to u32 instead. I don't see that this would impact any (valid) Rust programs in the wild, but it would give a widespread small efficiency boost for a comparatively small change.

It would also open up the possibility of storing both strong and weak count in the same 64bit word on 64bit platforms, which would speedup some of the methods like get_mut, make_mut, upgrade, etc - albeit at the cost of extra complexity by having different 32bit and 64bit code paths in some places. But that's an optional optimization and not required for this proposal to be beneficial.

I believe there may be one reason usize is used, and that's to avoid undefined behaviour if the ref count overflows. I don't think this is an issue for valid programs, and anyway, if it was an issue, it still is on 32bit platforms.

Thoughts? Is my reasoning too simplistic or flawed here?

**Comment by leonardo-m** [comment]
Note usize could be 16 bits too.

**Comment by eloff** [comment]
> Note usize could be 16 bits too.

That could be a reason why then, if one used 32bit ref counts on a 16 bit platform, it might not be atomic (or might be slow.) I don't think it's appropriate to make all platforms pay for the 16bit platform though - it's better to make a conditional implementation specifically for 16bit platforms in that case.

**Comment by Craig-Macomber** [comment]
> I believe there may be one reason usize is used, and that's to avoid undefined behaviour if the ref count overflows. I don't think this is an issue for valid programs, and anyway, if it was an issue, it still is on 32bit platforms.

Patterns where there is some root object which all your little objects have a reference to are pretty common. I actually hit an overflow for a 32 bit ref count due to this pattern once: I had an overflowing a COM ref counter for an ID2D1Factory which every allocated object referenced. We actually had a ref leak (so not all the object stayed in memory) but our test suite, and users, could easily allocate > 2 billion objects using that same ref count in under an hour. I can imagine a large workload that could hit it without a ref leak.

Note that an object owning a reference has a size, likely at least 4 bytes on a 32 bit system. This means overflow is actually impossible, since you would fill the whole space with Arcs before it overflowed.

On 64 bit, the Arc is at least 8 bytes. This means overflow of a 32 bit counter is possible, but overflow of 64 bits is not. On a 64 bit system with 64 GB of ram (or less ram but paging memory to either compressed ram or disk), you could allocate enough Arcs to hit this. To actually have some real data and to account for allocator overhead, you would likely need ~256 GB of ram. This amount is well within the quantity available on many servers today, and we need to be future proof beyond that as well.

Thus I think it makes sense that the number of allocated Arcs we support varies based on the size of the address space: platforms with larger address space can have more objects. Also 2^32 allocations is practical to actually do today, and overflowing ref counts is really, really painful.

**Comment by eloff** [comment]
> Patterns where there is some root object which all your little objects have a reference to are pretty common. I actually hit an overflow for a 32 bit ref count due to this pattern once: I had an overflowing a COM ref counter for an ID2D1Factory which every allocated object referenced. We actually had a ref leak (so not all the object stayed in memory) but our test suite, and users, could easily allocate > 2 billion objects using that same ref count in under an hour. I can imagine a large workload that could hit it without a ref leak.

That seems like a design flaw? Why would you ref count the object in that case - it would be better typically just to leak it for the duration of the program (or free it some other way, if possible.) I'm convinced that it's a bad idea to make everyone pay the price of supporting pathological programs.

> 
> Note that an object owning a reference has a size, likely at least 4 bytes on a 32 bit system. This means overflow is actually impossible, since you would fill the whole space with Arcs before it overflowed.

This is what I'm missing. So it's clear that using u32 on 64bit systems would actually result in different behaviour (potential for overflow).

> 
> On 64 bit, the Arc is at least 8 bytes. This means overflow of a 32 bit counter is possible, but overflow of 64 bits is not. On a 64 bit system with 64 GB of ram (or less ram but paging memory to either compressed ram or disk), you could allocate enough Arcs to hit this. To actually have some real data and to account for allocator overhead, you would likely need ~256 GB of ram. This amount is well within the quantity available on many servers today, and we need to be future proof beyond that as well.

Yes, it's certainly possible.

> 
> Thus I think it makes sense that the number of allocated Arcs we support varies based on the size of the address space: platforms with larger address space can have more objects. Also 2^32 allocations is practical to actually do today, and overflowing ref counts is really, really painful.

I would suggest an alternative approach - check for overflow (or close to overflow) and panic. No hard to track down bugs, and a couple pathological programs may need to be updated to benefit every rust program. That seems like a good tradeoff to me. Others with different values may disagree.

**Comment by Craig-Macomber** [comment]
> > Patterns where there is some root object which all your little objects have a reference to are pretty common. I actually hit an overflow for a 32 bit ref count due to this pattern once: I had an overflowing a COM ref counter for an ID2D1Factory which every allocated object referenced. We actually had a ref leak (so not all the object stayed in memory) but our test suite, and users, could easily allocate > 2 billion objects using that same ref count in under an hour. I can imagine a large workload that could hit it without a ref leak.
> 
> That seems like a design flaw? Why would you ref count the object in that case - it would be better typically just to leak it for the duration of the program (or free it some other way, if possible.) I'm convinced that it's a bad idea to make everyone pay the price of supporting pathological programs.

If someone wants to design program that way, it should work. There may be reasons to do it, and even if they are bad reasons, the rust standard library should support it. I gave a concrete example of an existing heavily used API that works that way (Microsoft's Direct2D Factories) and could realistically hit this problem. Std should not make optimizations which cause particular design patterns to break when scaled.

> > Note that an object owning a reference has a size, likely at least 4 bytes on a 32 bit system. This means overflow is actually impossible, since you would fill the whole space with Arcs before it overflowed.
> 
> This is what I'm missing. So it's clear that using u32 on 64bit systems would actually result in different behaviour (potential for overflow).

Yes. Currently there is no limit on number of refs (you would run out of address space first) so adding such a limit on 64 bit platforms would be a breaking change, which is not something the standard library does lightly.

> > On 64 bit, the Arc is at least 8 bytes. This means overflow of a 32 bit counter is possible, but overflow of 64 bits is not. On a 64 bit system with 64 GB of ram (or less ram but paging memory to either compressed ram or disk), you could allocate enough Arcs to hit this. To actually have some real data and to account for allocator overhead, you would likely need ~256 GB of ram. This amount is well within the quantity available on many servers today, and we need to be future proof beyond that as well.
> 
> Yes, it's certainly possible.
> 
> > Thus I think it makes sense that the number of allocated Arcs we support varies based on the size of the address space: platforms with larger address space can have more objects. Also 2^32 allocations is practical to actually do today, and overflowing ref counts is really, really painful.
> 
> I would suggest an alternative approach - check for overflow (or close to overflow) and panic. No hard to track down bugs, and a couple pathological programs may need to be updated to benefit every rust program using Arc. That seems like a good tradeoff to me. Others with different values may disagree.

I'm not sure 32 bit atomic are efficient or even supported on all 64 bit platforms, and certainly wouldn't want 32 bit atomic counters on 16 bit. See: https://stdrs.dev/nightly/x86_64-unknown-linux-gnu/core/sync/atomic/index.html

> Note that future platforms may be added that also do not have support for some atomic operations. Maximally portable code will want to be careful about which atomic types are used. AtomicUsize and AtomicIsize are generally the most portable, but even then they’re not available everywhere. For reference, the std library requires pointer-sized atomics, although core does not.

Given these issues, I don't think this change makes sense for the standard library: it doesn't get to make assumptions about platform and data-size so easily. If people really found value in such a space optimization (which might actually slow things down and increase code size due to alignment, integer extension, and overflow checking on some platforms), I think offering it as a third party crate might make sense, but I don't think these are the kinds of tradeoffs for std.

**Comment by jyn514** [comment]
It sounds like this has backwards-compability concerns for not much benefit, so I don't think it's a good fit for github issues - consider opening a thread on internals.rust-lang.org/ instead.

**Comment by eloff** [comment]
I think Craig is right, a smaller Arc would be best implemented a s a third-party library. I'll go that route.
