### ISSUE TITLE
Could not `allow(deprecated)` for deprecated variants in derived functions

### ISSUE THREAD

**Issue by qiujiangkun** [rust-lang/rust#87454]
I tried this code:

```rust
use serde::*;
#[derive(Serialize, Deserialize)]
#[allow(deprecated)]
enum Foo {
    #[deprecated]
    A,
}
```

I expected to see this happen: *compiles without warning*

Instead, this happened: 
```rust
warning: use of deprecated unit variant `Foo::A`
   |
54 |   enum Foo {
   |  ______^
55 | |     #[deprecated]
56 | |     A,
   | |_____^

```

`#[allor(deprecated)]` could be implemented in `serde` crate, but there are too many other crates.

### Meta
`rustc --version --verbose`:
```
rustc 1.55.0-nightly (e6b4c252e 2021-06-25)
binary: rustc
commit-hash: e6b4c252ea33e9f80ab8b8d7b3f6393e54166127
commit-date: 2021-06-25
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

**Comment by ThePuzzlemaker** [comment]
This is because serde and most other `#[derive(...)]` and proc macro crates generate code outside of the type definition, and as `#[allow(deprecated)]` only applies to the `enum Foo { ... }` definition and not the generated `impl` blocks, the warning applies.
It would probably be a good idea to report this to serde or other proc macro crates so that they can implement a check where if `#[allow(deprecated)]` is used on the type it'll pass through to the generated code.

**Comment by qiujiangkun** [comment]
I understand it. 
It seems the solution is to `#![allow(deprecated)]` or `#[allow(deprecated)] mod foo { enum Foo {...} } use foo::Foo;` without help from serde

**Comment by JohnTitor** [comment]
Going to close as this isn't an actual bug. Thanks for reporting!
