### ISSUE TITLE
return-type mismatch in async function gives "return type inferred" pointing to use of `?`

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#87461]
Given the following code ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a781a1a9802fef4d8fe8462fe746a1f4)):

```rust
async fn func() -> Result<u16, u64> {
    let _ = async {
        Err(42u64)
    }.await?;

    Ok(())
}
```

The current output is:

```
error[E0308]: mismatched types
 --> src/lib.rs:6:8
  |
6 |     Ok(())
  |        ^^ expected `u16`, found `()`
  |
note: return type inferred to be `u16` here
 --> src/lib.rs:2:13
  |
2 |       let _ = async {
  |  _____________^
3 | |         Err(42u64)
4 | |     }.await?;
  | |____________^

error: aborting due to previous error
```

An even more minimal example:

```rust
async fn func() -> Result<u16, u64> {
    Err(42u64)?;

    Ok(())
}
```

This similarly produces a note pointing to the `Err(42u64)?;` line.

The note seems entirely unhelpful here; the function's declared type doesn't match the `Ok(())`, and the use of `?` has nothing to do with it. An equivalent non-async function omits the note, and just reports the type mismatch.

The same output occurs on both stable and today's nightly.

**Comment by FabianWolff** [comment]
I think this is unrelated to both the `async` and the `?` (they just "hide" the problem), because I can reproduce the problem as follows:
```rust
fn main() {
    || -> Result<u16, u64> {
        if true {
            return Err(42u64);
        }
        Ok(())
    };
}
```
```
error[E0308]: mismatched types
 --> test.rs:6:12
  |
6 |         Ok(())
  |            ^^ expected `u16`, found `()`
  |
note: return type inferred to be `u16` here
 --> test.rs:4:20
  |
4 |             return Err(42u64);
  |                    ^^^^^^^^^^

error: aborting due to previous error
```
It is caused by the fact that `ret_coercion_span` (which is used for error reporting later) is set to the span of the first `return` statement here:
https://github.com/rust-lang/rust/blob/478126c0f3520ccd95a6f16be2812a78e3da711c/compiler/rustc_typeck/src/check/expr.rs#L725-L730

despite the fact that this only _partially_ defines the return type (it doesn't say anything about the `Ok` type).
