### ISSUE TITLE
Missed optimization when setting values of a mutable slice

### ISSUE THREAD

**Issue by adwhit** [rust-lang/rust#87510]
Compare two examples which simply set few values of a mutable slice via the index operator:

https://godbolt.org/z/TfanxhWYq
and
https://godbolt.org/z/P1Toa75hn

The only difference is the order in which the assignments are made. In both cases I would expect the slice bounds to be checked only once - but in the first case it is checked redundently for each index operation.

In the first case the compiler also fails to deduplicate the panic blocks (due to futzing around with `%edi`) which results in considerable code bloat, 83 lines vs 23 for the second case.

**Comment by Urgau** [comment]
In the first `set_vals` function you set incrementally (`+1`) a value in the slice but in the second function you start with the assignment put before the first one that means that in the second case the bounds checks can only be done once because `5 > [0, 1, 2, 3, 4]` but in the first function that not true, that the first reason why it's not optimize away.

The second reason is that in the first function the assignments will be done until there is no more assignments to be done, that means that if the slice has a length of 3, in the first function `s[0]`, `s[1]` and `s[2]` will be set but not in the second case because of the check of `5`.

The meaning of the assignments in the two case are not the same, so they cannot be optimize in the same way.

*You can see that an [equivalent code](https://godbolt.org/z/63an44vcT) in `C++` result in the roughly the same ASM code*

**Comment by adwhit** [comment]
Hmm, that makes sense, thanks. I think I was thrown by the fact that the first example only has three `cmpq` instructions, I was expecting six and concluded that it was partially but not completely optimizing the comparisons. But looking closer I can see that is not what is going on.

You could argue that since it is compiling with `panic=abort`, the assignments are not observable and therefore the second representation would be valid. However I'm venturing well beyond my understanding at that point.
