### ISSUE TITLE
Rule to use a capital letter at the beginning of error messages

### ISSUE THREAD

**Issue by vincent-herlemont** [rust-lang/rust#87556]
Rust source code mostly does not use capital letters in error messages. E.g: [core/src/cell.rs#L828](https://github.com/rust-lang/rust/blob/3bc9dd0dd293ab82945e35888ed6d7ab802761ef/library/core/src/cell.rs#L828).

However, there are some exceptions like: [core/src/future/ready.rs#L23](https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/core/src/future/ready.rs#L23).

Are there some reasons not to use a capital letter at the beginning of error messages?

**Comment by matklad** [comment]
For `std::error::Error` the docs recommend lowercase: https://doc.rust-lang.org/stable/std/error/trait.Error.html. that usually works better with chaining several messages together. 

Not sure if there are any guidelines for expect. I'd love to see some: I am always confused if I should `.expect("is non None")` or `.expect("is None")`.

**Comment by r00ster91** [comment]
> However, there are some exceptions like: [core/src/future/ready.rs#L23](https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/core/src/future/ready.rs#L23).

Isn't the exception in this case because it refers to the enum member `Poll::Ready`? This `Ready` is of course always capitalized and so in the error message too so I think that's a valid exception. I wonder if it would be better to change it to `` `Ready` `` but it's probably fine as it is.
In all other cases I believe the error should be lowercased as that seems to be the standard.
