### ISSUE TITLE
Confusing error message 

### ISSUE THREAD

**Issue by M4tsuri** [rust-lang/rust#87726]
I tried this code:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=efe6e56404094abbfbc3c1183587fe23

```rust
use std::collections::HashMap;

fn f<'a>(_: &'a mut HashMap<usize, &'a usize>) {}

fn main() {
    let mut scores = HashMap::new();
    f(&mut scores);
    let _ = &mut scores;
    // or let t = &scores;
}
```

I expected to see this happen: 

I expect compiling succeeds or give readable error message.

Instead, this happened:

```
     1     Compiling rust_try v0.1.0 (/Users/ctsinon/Projects/StaticAnalysis/rust_try)
     2  error[E0499]: cannot borrow `scores` as mutable more than once at a time
     3   --> src/main.rs:8:13
     4    |
     5  7 |     f(&mut scores);
     6    |       ----------- first mutable borrow occurs here
     7  8 |     let _ = &mut scores;
     8    |             ^^^^^^^^^^^
     9    |             |
    10    |             second mutable borrow occurs here
    11    |             first borrow later used here
       
    12  error: aborting due to previous error
       
    13  For more information about this error, try `rustc --explain E0499`.
    14  error: could not compile `rust_try`
       
    15  To learn more, run the command again with --verbose.
```

It seems that the code causing the error at line 11 is missing. 

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-apple-darwin
release: 1.54.0
LLVM version: 12.0.1
```

And I wonder if anyone can explain why this code can cause a second mutable borrow.

After changing the prototype of `f` to 

```rust
use std::collections::HashMap;

fn f(_: &mut HashMap<usize, &usize>) {}

fn main() {
    let mut scores = HashMap::new();
    f(&mut scores);
    let _ = &mut scores;
    // or let t = &scores;
}
```

the error disappears.

**Comment by SkiFire13** [comment]
> And I wonder if anyone can explain why this code can cause a second mutable borrow.

Your initial function `f` required that the references inside the `HashMap` had the same lifetime as the mutable reference to it. This pretty much means that it will be borrowed until it goes out of scope, which includes the second `&mut scores`, thus the error that you're trying to borrow something already borrowed.

This constraint is not present in your second defintion of `f`, because the two lifetimes will be different, which is why it compiles.

In general the pattern `&'a mut Something<'a>` is almost never what you want. There could be a warning against it, however there are rare cases where this is actually what you want, so there would be false positives that would be annoying. I wonder however if this could be shown as a note to the lifetime error though.

**Comment by M4tsuri** [comment]
Thank you very much. If I'm not mistaken, "sharing the same lifetime" means they can have reference to each other. So in function prototype, an object with the same lifetime of its field can lead to recursive reference, which lead to a borrow to itself. And the compiler always consider the worst case, so it throws an error even there are actually no self-borrowing in my code. I wonder if I'm not misunderstanding.

**Comment by ibraheemdev** [comment]
The message could probably point to the lifetime, indicating that it extends the first borrow.

**Comment by M4tsuri** [comment]
Thank you, I figured it out now. My bad.
