### ISSUE TITLE
GAT: lifetime mismatch when requiring lifetime bounds despite type not using the lifetimes at all

### ISSUE THREAD

**Issue by athre0z** [rust-lang/rust#87748]
Compiling this code:

```rust
#![feature(generic_associated_types)]

trait MyTrait {
    type Assoc<'a, 'b> where 'b: 'a;
    fn do_sth(arg: Self::Assoc<'_, '_>);
}

struct Foo;

impl MyTrait for Foo {
    type Assoc<'a, 'b> where 'b: 'a = u32;
    
    fn do_sth(_: u32) {}
    // fn do_sth(_: Self::Assoc<'static, 'static>) {}
    // fn do_sth(_: Self::Assoc<'_, '_>) {}
}
```

I'd expect all of these three versions to compile. The associated type has two lifetimes as well as a lifetime bound `'b: 'a`, but `u32` doesn't use the lifetime. However, I'm getting a compiler error:

```
error[E0478]: lifetime bound not satisfied
  --> src/lib.rs:13:5
   |
13 |     fn do_sth(_: u32) {}
   |     ^^^^^^^^^^^^^^^^^
   |
note: lifetime parameter instantiated with the anonymous lifetime #2 defined on the method body at 13:5
  --> src/lib.rs:13:5
   |
13 |     fn do_sth(_: u32) {}
   |     ^^^^^^^^^^^^^^^^^
note: but lifetime parameter must outlive the anonymous lifetime #1 defined on the method body at 13:5
  --> src/lib.rs:13:5
   |
13 |     fn do_sth(_: u32) {}
   |     ^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0478`.
error: could not compile `playground` due to previous error
```

Without the `where 'b: 'a`, all three compile fine. 

[Playground Link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ec5f5d95af1164b121b62cb130d2dced)

**Comment by jackh726** [comment]
So, I think this is *mostly* just "intended"; the `'b: 'a` bound is required to hold regardless of it's used.

That said, I would *expect* `Self::Assoc<'static, 'static>` to work. Looking into it.

**Comment by jackh726** [comment]
Err, no `Self::Assoc<'static, 'static>` shouldn't work...because that is "stricter" than the trait.

**Comment by athre0z** [comment]
Hmm, by "stricter", do you mean "more specific"? As in: because `Self::Assoc<'static, 'static>` is more specific than `Self::Asoc<'_, '_>`, it shouldn't work? I'd argue that this is "stricter" regardless of the presence of the `where 'b: 'a` and without the `where` constraint, it compiles fine.

**Comment by jackh726** [comment]
Okay, so I've convinced myself that example 3 should work based on implied bounds. This is just a bug.

Example 1 is a little weird. When we check the trait fn, we can use implied bounds to prove that `'b: 'a`. We can't actually normalize `Assoc` because `Self` isn't know. But, when we try to check that the impl fn matches the trait, we then use `Foo` as `Self`, and we *can* normalize `Self::Assoc<'_, '_>`, but we haven't generated the implied bounds needed to satisfy `'b: 'a` because the current function doesn't use the projection as an input type. We should probably be using the implied bounds of the *trait* fn when normalizing the trait fn input types. This is also, now that I think about, likely a bug too.

Example 2 (`Self::Assoc<'static, 'static>`) is indeed not supposed to be able to compile. Imagine we had `type Baz = impl MyTrait` with the defining use being `Foo`. We could then pass *any* lifetimes `'a` and `'b`, as long as `'b: 'a` to `do_sth`. Well, the impl on `Foo` expects that those are both `'static`, Normally, this is a problem because we could extend the the lifetime of the input types, but can't actually because the type is `u32`. Hmm. It's a bit dubious though; I would expect that we shouldn't want to look at the actual type of the associated type when doing WF checks on the fn sig. While we theoretically could, I don't think we want to change this.

**Comment by jackh726** [comment]
Okay I have a fix and the `Self:Assoc<'static, 'static>` example fell out naturally. Will make a PR shortly.

**Comment by jackh726** [comment]
GATs issue triage: not blocking. The implied bounds story here is not great. But the simple attempt to fix thing opened up soundness holes. It's also not backwards-incompatible to fix.
