### ISSUE TITLE
Rustdoc currently does not distinguish between public and private items

### ISSUE THREAD

**Issue by shivanandvp** [rust-lang/rust#87785]
**Rustdoc** currently does not _label_, _mark_, or otherwise _separate_ private items to distinguish them from public items, when the `--document-private-items` command-line argument is passed. The generated documentation hence can be confusing to the reader. I suggest enabling one or more of the below through **rustdoc**:

1. _Separate_ public and private items in the generated documentation
2. Enable toggling the _visibility_ of private items in the generated documentation.
3. _Label_ or _mark_ private items to clearly distinguish them from public items.

This issue was prompted by https://github.com/rust-lang/docs.rs/issues/304#issuecomment-893112510

**Comment by jyn514** [comment]
@shivanandvp so, I spoke a little too quickly before, rustdoc does in fact distinguish items with different visibility, you just have to click through to the item itself instead of the module where it's listed:
![image](https://user-images.githubusercontent.com/23638587/129989019-ce512243-b655-4902-a08c-240686511ef0.png)
![image](https://user-images.githubusercontent.com/23638587/129989027-a94f70ce-d914-4caf-9055-e14a911926ea.png)
![image](https://user-images.githubusercontent.com/23638587/129989036-ba7ea1d8-fdb8-4b9c-9398-7bf9fd212938.png)

**Comment by koehlma** [comment]
How about adding some opacity to the item names or would that be too subtle?

I think I would be able to contribute a PR making this happen.

**Comment by GuillaumeGomez** [comment]
Fixed by #95024.
