### ISSUE TITLE
Better docs for std::os::windows::fs::{symlink_dir, symlink_file};

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#88635]
At the moment (rustc 1.56.0-nightly (b7404c898 2021-09-03)) the docs for this two functions are identical, and the only difference is file/dir. As a developer with primarily unix background, I don't really understand why there are two functions, and when I should use one versus the other. It would be helpful if the docs explained windows/unix difference, or linked upstream docs.

**Comment by matklad** [comment]
see also https://github.com/rust-lang/rust/commit/3cc84efcdd5727c0749d766d8abd79d8077f9cec

**Comment by ChrisDenton** [comment]
Yes this could be improved. In Windows filesystems everything is either a file or directory, it doesn't have a separate category for symlinks (although the std sometimes tries hard to pretend otherwise). Therefore a file symlink must point to a file and a directory symlink must point to a directory. Otherwise the symlink will be broken.

**Comment by ChrisDenton** [comment]
It should probably also be documented that creating symlinks currently requires the user to enable developer mode (Win10 only) or have elevated privileges.
