### ISSUE TITLE
PartialOrd docs for generic tuples show the where clauses in a seemingly random order

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#88809]
On https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html:

The docs for PartialOrd on tuples show the `where` clauses in a weird order, obscuring the fact that the _last_ element of the tuple is allowed to be unsized.

```rust
impl<A, B, C, D, E> PartialOrd<(A, B, C, D, E)> for (A, B, C, D, E) where
    C: PartialOrd<C> + PartialEq<C>,
    E: PartialOrd<E> + PartialEq<E> + ?Sized,
    B: PartialOrd<B> + PartialEq<B>,
    A: PartialOrd<A> + PartialEq<A>,
    D: PartialOrd<D> + PartialEq<D>, 
```

**Comment by GuillaumeGomez** [comment]
Found the issue: it's because we use a `BTreeMap` using `Symbol` as key. Problem being that `Symbol` is making integer based comparison and not string based, hence the current result. Trying to write a test now.

**Comment by camelid** [comment]
Note that this bug is specific to cross-crate re-exports; the same documentation in `core` renders correctly. There also seems to be another "bug" related to cross-crate re-exports and `where` clauses: In the `core` docs, the impl looks like this (which is how it's actually written in the source):

![image](https://user-images.githubusercontent.com/37223377/134408031-f9f54201-6faa-43fc-97f7-d46444c47c7c.png)

But in the `std` docs, the impl looks like this, with all of the bounds expressed as `where` clauses:

![image](https://user-images.githubusercontent.com/37223377/134408070-e6cb807b-459c-490e-92c6-2a9ac6d4ffa0.png)

I think the re-exported version is actually better, because it's easier to read, but they should at least be consistent.
