### ISSUE TITLE
regression: Copy no longer implemented

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#88969]
Found by 1.56 crater - https://crater-reports.s3.amazonaws.com/beta-1.56-2/beta-2021-09-12/reg/gmorph-0.1.0/log.txt

```
[INFO] [stdout] error[E0204]: the trait `Copy` may not be implemented for this type
[INFO] [stdout]   --> src/enc.rs:16:17
[INFO] [stdout]    |
[INFO] [stdout] 16 | #[derive(Debug, Copy, Clone, PartialEq, Serialize, Deserialize)]
[INFO] [stdout]    |                 ^^^^
[INFO] [stdout] 17 | pub struct Enc {
[INFO] [stdout] 18 |     inner: Matrix3<Q231>,
[INFO] [stdout]    |     -------------------- this field does not implement `Copy`
[INFO] [stdout]    |
[INFO] [stdout]    = note: this error originates in the derive macro `Copy` (in Nightly builds, run with -Z macro-backtrace for more info)
[INFO] [stdout] 
```

Bisections seems to point at https://github.com/rust-lang/rust/commit/371f3cd3fe523d0b398ed1db1620667c53ba7d02, cc @Aaron1011

**Comment by Mark-Simulacrum** [comment]
Potentially related:

* https://crater-reports.s3.amazonaws.com/beta-1.56-2/beta-2021-09-12/reg/mpstthree-0.0.13/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.56-2/beta-2021-09-12/reg/shaku-0.6.1/log.txt

**Comment by Aaron1011** [comment]
This is caused by a bad interaction between `SelectionContex`'s 'intercrate' mode, the trait evaluation cache, and the `evaluate_root_obligation` added in https://github.com/rust-lang/rust/pull/85868

In PR https://github.com/rust-lang/rust/pull/85868, we create a new `SelectionContext` to 'speculatively' evaluate projection sub-obligations. If they evaluate to `EvaluatedToOkModuloRegions`, we discard them from the cached results, allowing future projections of the same predicate to avoid re-processing them. However, if the original `SelectionContext` was in 'intercrate' mode, then we'll end up using the same `InferCtxt` (and therefore the same local evaluation cache) in both intercrate and non-intercrate mode. The result of evaluation differs between these modes, so this leads to bugs like this issue.

There are several different ways of fixing this - fortunately, all of them are quite straightforward, and are suitable for backporting. I've opened https://github.com/rust-lang/rust/pull/88994 and https://github.com/rust-lang/rust/pull/88993 to check the performance of two approaches.

**Comment by Mark-Simulacrum** [comment]
Reopening -- @Aaron1011 can you make sure the appropriate PRs are beta-nominated?
