### ISSUE TITLE
Link a rustup toolchain automatically in `x.py setup`

### ISSUE THREAD

**Issue by Sl1mb0** [rust-lang/rust#89206]
Issue tracker for linking a rustup toolchain automatically in `x.py setup`.

**Comment by Mark-Simulacrum** [comment]
Can you say more about the motivation? Initially, I would say that it is pretty likely that we do not want to support this kind of "aggregation" in the x.py interface; it complicates the information and I'm not sure it improves the user interface.

**Comment by Sl1mb0** [comment]
I agree that I don't think it improves the user interface much, but I think that the interface for this specific feature could be made better. My only argument for why I think this capability should be added is that it's natural to create a toolchain for the compiler immediately after having built it, so why not give `./.xpy` the capability to do so? 

However, as I understand it you only need to run `rustup` once to create a toolchain for the build, and subsequent builds will always be used by the toolchain. So I can see why this is kind of pointless.

**Comment by Mark-Simulacrum** [comment]
I think streamlining the toolchain creation process is worthwhile to invest into; e.g., we could give a suggestion at the end of the first x.py build in a new build directory (with a stamp file just saying 'did that') to run rustup link .... with the appropriate path.

**Comment by Sl1mb0** [comment]
I like that idea. I'll wait for more feedback before I start looking into it though.

**Comment by jyn514** [comment]
Hmm, I would rather set up the toolchain automatically when running `x.py setup`, and give a warning if a toolchain named `stage1` already exists, along with the command to set it up yourself.

If we gave a warning the first time you run `x.py build`, then a) people who aren't developing locally get confused (e.g. distros building from source) because they don't actually care about this, and b) x.py has no way of knowing whether you actually add the toolchain or not; I can definitely see people missing it the first time and then never getting the warning again just because x.py is using a stamp file.

**Comment by Mark-Simulacrum** [comment]
Yeah, x.py setup seems better. I think rustup won't let you do it without the sysroot somewhat existing, though:

```
$ rustup toolchain link foo foo
error: not a directory: 'foo/lib'
```

But I think we have enough in setup that we can probably create the directory temporarily...

**Comment by jyn514** [comment]
Mentoring instructions: just after https://github.com/rust-lang/rust/blob/bf642323d621dcefeef1d8ab4711aae36e357615/src/bootstrap/setup.rs#L108, call `rustup toolchain link stage1 build/TARGET/stage1`, where `TARGET` is `builder.config.build`. If that errors, give a warning and suggest that the user do it themselves.

**Comment by Sl1mb0** [comment]
> where `TARGET` is `builder.config.build`

Could you clarify this? I assumed you were referring to the `build::Builder`, but there is no `config` field there..

**Comment by jyn514** [comment]
@Sl1mb0 it derefs to Build, which should have a Config field.

**Comment by workingjubilee** [comment]
It should be noted that the toolchain linking/unlinking rustup does is not always just a symlink, it is sometimes a hardlink, depending on the OS. This can cause issues because it makes the linkage inherently touchier. I am not saying this should not be done, merely that if someone finds this issue later after it causes trouble, then it should become special-cased by OS.
