### ISSUE TITLE
Wrong path is used in bootstrap

### ISSUE THREAD

**Issue by SparrowLii** [rust-lang/rust#89348]
Look at [this line](https://github.com/rust-lang/rust/blob/master/src/bootstrap/bootstrap.py#L1002)
Bootstrap uses the `.git` path, but the current source code path is `.github`. This makes it impossible to update the submodules. In addition, there are other `.git` path errors in bootstrap that need to be corrected

**Comment by ehuss** [comment]
Can you say more about what problem you are running into?  `.git` is the correct path. That is checking whether or not the current source tree was cloned from a git repository, or if it is extracted from an archive (ie, not a git repository).  If extracted from an archive, then there is no need to update submodules since it isn't inside a git repository to start with. The archive should include the necessary submodules.

**Comment by SparrowLii** [comment]
I think I know the reason. I downloaded the zip source package from the github webpage without using the `git clone` command. This will result in no `.git` path in the root directory after decompression. 
This means there is no problem here. I think this issue can be closed.
