### ISSUE TITLE
slice::align_to does not take into account length of the slice

### ISSUE THREAD

**Issue by jweinst1** [rust-lang/rust#89368]
The bug is that, the method described [here ](https://doc.rust-lang.org/std/primitive.slice.html#method.align_to) does not depend on the length of the slice itself, rather the memory where the slice is from. This is either a bug, or if intentional, quite misleading. Here is an example of the behavior:

```rust
fn main() {
    let numbers:[u8;33] = [44, 2, 0, 0, 0, 0, 0, 0, 76, 1, 0, 0, 0, 0, 0, 0, 8, 3, 0, 0, 0, 0, 0, 0, 81, 17, 0, 0, 0, 0, 0, 0, 1];
    let aligned = unsafe { numbers[0..32].align_to::<u64>() };
    println!("aligned: {:?}", aligned);
    
    let numbers2:[u8;32] = [44, 2, 0, 0, 0, 0, 0, 0, 76, 1, 0, 0, 0, 0, 0, 0, 8, 3, 0, 0, 0, 0, 0, 0, 81, 17, 0, 0, 0, 0, 0, 0];
    let aligned2 = unsafe { numbers2[0..32].align_to::<u64>() };
    println!("aligned2: {:?}", aligned2);
}
```

Which will print

```rust
aligned: ([44], [5476377146882523138, 576460752303423489, 5836665117072162819], [17, 0, 0, 0, 0, 0, 0])
aligned2: ([], [556, 332, 776, 4433], [])
```

The expected behavior here should be that the alignment takes place according to the type of the slice and the length of the slice.

Instead, the `align_to` method is aligning with respect to the memory in which the slice is from.

If this is not a bug and actually intentional, my concern here is because this method operates on a slice, it's practically useless as one does not know the alignment of the memory the slice is from just from the slice itself. It would make sense to either very clearly line this out in documentation.

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-apple-darwin
release: 1.54.0
LLVM version: 12.0.1
```

**Comment by the8472** [comment]
> The bug is that, the method described here does not depend on the length of the slice itself, rather the memory where the slice is from.

Well, it does depend on the length of the slice in a way. You can't align a slice with fewer elements than the larger type.

But that also depends on the address is quite intentional because the because an [u8] can sit at any memory address (having an alignment of 1), it's not guaranteed to be divisible by any particular number other than 1.
A [u64] on the other hand must be aligned to 8 bytes, which means `(slice_of_u64.as_ptr() as usize) % 8 == 0` must hold true. Which means a variable amount of bytes at the beginning must be skipped until the first chunk of data can be treated as `[u64]` is reached.

> The expected behavior here should be that the alignment takes place according to the type of the slice and the length of the slice.

Can you give an example what the desired outcome would be?

**Comment by jweinst1** [comment]
> Can you give an example what the desired outcome would be?

It would be for any `&[u8]` of where `.len() % 8 == 0` would be evenly aligned. In my example, both `numbers` and `numbers2` are `.len() == 32` , but because `numbers` comes from an `[u8;33]` , even though the slice is from `0..32`, it somehow thinks the slice is also length 33. The desired behavior would , from the same program, print this:

```rust
aligned: ([], [556, 332, 776, 4433], [])
aligned2: ([], [556, 332, 776, 4433], [])
```

**Comment by the8472** [comment]
>  even though the slice is from 0..32, it somehow thinks the slice is also length 33.

That's not what is happening. It's due to the address of the first byte of the arrays in memory not being properly aligned for the wider type.
If you're coming from a higher level language perhaps you're not familiar with pointers and memory alignment? I don't know of a good beginner tutorial in this area, here's the [wikipedia page](https://en.wikipedia.org/wiki/Data_structure_alignment) and a section in the [rust reference](https://doc.rust-lang.org/reference/type-layout.html)

Here's your example [with added pointer printing](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ebd703b4ecaba801daf1525945a5cc83). 

As a sidenote: Arrays are (unlike slices) owned types and arrays of primitives are copy types on top of that. So they may get moved and copied around as you work with them which will lead to them changing their address. This could lead to further confusion if you experiment with this. You might want to take a slice once and then work with that. It won't change its address as long as the borrow exists.

```rust
let ary: [u8; 80] = [0u8; 80];
// let ary2 = ary; // <- this would get a new address
let slice: &[u8] = ary.as_slice(); // <- this address won't change for the rest of the method
```

**Comment by jweinst1** [comment]
> That's not what is happening. It's due to the memory address of the first byte of the arrays not being properly aligned for the wider type.

Right, but the function takes a _slice_ as a parameter, not an _array_ . What it takes in as a parameter does not reflect what the output or return value actually works on. 

> If you're coming from a higher level language perhaps you're not familiar with pointers and memory alignment? I don't know of a good beginner tutorial in this area, here's the wikipedia page and a section in the rust reference

Coming from C++, but in C++, this can be done 

```cpp
#include <cstdio>
#include <cstdint>

int main() {
    alignas(64) uint8_t bytes[33] = {6, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 4};
    std::printf("align of bytes %zu\n", alignof(bytes));
    uint64_t* reader = reinterpret_cast<uint64_t*>(bytes);
    std::printf("%llu, %llu, %llu, %llu\n", reader[0], reader[1], reader[2], reader[3]);
    return 0;
}
```

In C++, alignment works on types such as arrays and structs, not pointers. 

The problem here is that one cannot use this function unless they are also aware of the alignment of the array the slice points to, which the slice has no method for.

**Comment by the8472** [comment]
> Right, but the function takes a slice as a parameter, not an array . What it takes in as a parameter does not reflect what the output or return value actually works on.

A `&[u8]` is just a reference (a pointer + length) into that array and the array isn't properly aligned for the widening, so it can't be turned into a `&[u64]`, at least not to one pointing at the first byte of the array.


> ```c++
> #include <cstdio>
> #include <cstdint>
> 
> int main() {
>     alignas(64) uint8_t bytes[33] = {6, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 4};
>     std::printf("align of bytes %zu\n", alignof(bytes));
>     uint64_t* reader = reinterpret_cast<uint64_t*>(bytes);
>     std::printf("%llu, %llu, %llu, %llu\n", reader[0], reader[1], reader[2], reader[3]);
>     return 0;
> }
> ```


That cast would not be valid without the `alignas(64)`.
`std::mem::align_of::<[u8; 33]>()` is 1. If you want the equivalent in rust you have to wrap it into a newtype and add `#[repr(align(8))]` to that newtype.

`align_to` has uses without knowing the alignment in advance. E.g. for vectorization where you have a prefix and suffix loop for the smaller type and then the vectorized main body for the middle part.

**Comment by jweinst1** [comment]
> align_to has uses without knowing the alignment in advance. E.g. for vectorization where you have a prefix and suffix loop for the smaller type and then the vectorized main body for the middle part.

Thats a good point actually. Perhaps wha I am looking for is actually a way to read unaligned data instead. Thanks

https://doc.rust-lang.org/std/ptr/fn.read_unaligned.html
