### ISSUE TITLE
`match` / expected expression, found `as`

### ISSUE THREAD

**Issue by Fn79** [rust-lang/rust#89519]
Using the `as` keyword in `match`

Like this.

```rs
fn main() {
    println!("{:?}", test! {} as u32);
                            //^^^^^^ work
    println!("{:?}", match true { true => 1, false => 2, } as u32);
                                                        //^^^^^^^^ work
    match true { true => 1, false => 2, } as u32;
                                        //^^^^^^^^ doesn't work

    (match true { true => 1, false => 2, }) as u32;
                                         //^^^^^^^^ work 
}

#[macro_export]
macro_rules! test {
    () => {
        $crate::t();
    };
}

fn t() -> i32 {
    10
}
```

Error:

```rs
error: expected expression, found `as`
 --> src/main.rs:6:43
  |
6 |     match true { true => 1, false => 2, } as u32;
  |     ------------------------------------- ^^ expected expression
  |     |
  |     help: parentheses are required to parse this as an expression: `(match true { true => 1, false => 2, })`
```

I want to know why this code is not working.

**Comment by JerryLiew** [comment]
i think maybe you need declare a variable to receive the return value

**Comment by JerryLiew** [comment]
like this :
`  let some_variable=  match true { true => 1, false => 2, } as u32;  \\new line here   
    println!("{}",some_variable);
`
by the way,how can i make a new line in the code block in comment?

**Comment by Fn79** [comment]
> 
> 
> like this : ` let some_variable= match true { true => 1, false => 2, } as u32; \\new line here println!("{}",some_variable);` by the way,how can i make a new line in the code block in comment?

Thanks for the good answer.

Code block can be created like this:
![image](https://user-images.githubusercontent.com/74909209/135849464-19fecb31-91e5-4e5c-bd88-d33fd172ffe9.png)

**Comment by DanielKeep** [comment]
Because "`match` in statement position" and "`match` in expression position" aren't quite the same.  In general, you have to end statements with a semicolon, but an exception is made for control flow statements like `for`, `if`, and `match`.  So, when the compiler sees the keyword `match` at the start of a statement, it assumes it's parsing it as a statement, and thus doesn't need a semicolon at the end.  As soon as it sees the closing `}`, it cuts off the statement and starts parsing a new one.

What you've *actually* written are two independent statements, where the second one is `as u32`, which isn't valid.  Remember, whitespace (including newlines) isn't syntactically meaningful.  In order for `match` to be parsed as an expression, it has to appear in a context where *only* an expression is valid (like inside parens, as the right-hand side of a `let` statement, *etc.*).  Otherwise, the compiler will assume it's a statement.

*If it's smart enough to realise I need to parenthesise the `match`, what doesn't it just let me do this?*

Presumably because it creates a situation where `match` (and other statements like it) *sometimes* parse as statements and *sometimes* parse as expressions, and it would be hard for a human reader to tell which is which.  Forcing you to explicitly disambiguate by adding parentheses is a smol thing to ask, and doesn't leave any room for ambiguity.

I imagine it would also complicate the parser, as it would have to be able to recognise when parsing a statement failed but *might* succeed if it it rolls back to the previous statement and re-interpreted it as an expression.  I believe there's a fairly strong desire to avoid these sorts of backtracking issues in the language, both to keep the compiler simpler and avoid performance issues.

**Comment by Fn79** [comment]
> 
> 
> Because "`match` in statement position" and "`match` in expression position" aren't quite the same. In general, you have to end statements with a semicolon, but an exception is made for control flow statements like `for`, `if`, and `match`. So, when the compiler sees the keyword `match` at the start of a statement, it assumes it's parsing it as a statement, and thus doesn't need a semicolon at the end. As soon as it sees the closing `}`, it cuts off the statement and starts parsing a new one.
> 
> What you've _actually_ written are two independent statements, where the second one is `as u32`, which isn't valid. Remember, whitespace (including newlines) isn't syntactically meaningful. In order for `match` to be parsed as an expression, it has to appear in a context where _only_ an expression is valid (like inside parens, as the right-hand side of a `let` statement, _etc._). Otherwise, the compiler will assume it's a statement.
> 
> _If it's smart enough to realise I need to parenthesise the `match`, what doesn't it just let me do this?_
> 
> Presumably because it creates a situation where `match` (and other statements like it) _sometimes_ parse as statements and _sometimes_ parse as expressions, and it would be hard for a human reader to tell which is which. Forcing you to explicitly disambiguate by adding parentheses is a smol thing to ask, and doesn't leave any room for ambiguity.
> 
> I imagine it would also complicate the parser, as it would have to be able to recognise when parsing a statement failed but _might_ succeed if it it rolls back to the previous statement and re-interpreted it as an expression. I believe there's a fairly strong desire to avoid these sorts of backtracking issues in the language, both to keep the compiler simpler and avoid performance issues.

Thank you so much for the great answer!
