### ISSUE TITLE
Fix performance regression from #89695

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#89732]
In #89695, we extended the usage of tera. However, it impacted the doc build time badly, so we need to fix it.

cc @jsha

**Comment by jsha** [comment]
From https://perf.rust-lang.org/compare.html?start=6928fafe06e4ab29317f75194e1bf67c119dccdc&end=c1cb97481a633bdfdf3d6b57c6dcebfdfadbcfdf (linked by @rust-timer in https://github.com/rust-lang/rust/pull/89695#issuecomment-939437179), it looks like these are the most-affected doc builds:

Name & Profile | Scenario | #89661 | #89695 | % Change | Significance Factor?
-- | -- | -- | -- | -- | --
externs-doc | full | 4189786474 | 4344364681 | 3.69% | 47.95x
stm32f4-doc | full | 56031165508 | 57091116514 | 1.89% | 18.54x
style-servo-doc | full | 59526418329 | 60422392129 | 1.51% | 20.36x
html5ever-doc | full | 5015123198 | 5043144386 | 0.56% | 6.64x

How can I find the commands I should run to reproduce these builds? In particular I'd like to try and reproduce the externs-doc build since that's most affected. I'd also appreciate any pointers on differential profiling so I can narrow in on the differences.

**Comment by the8472** [comment]
"externs-doc" means: benchmark running rustdoc on the externs crate. Select the crate with `--include externs` and the benchmark mode via `--runs Doc`

**Comment by GuillaumeGomez** [comment]
It was fixed in #92526 when we switched to askama.
