### ISSUE TITLE
rustdoc: Re-exported macro is not inlined

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#90068]
It looks like in both versions there's also a bug where `repro2` is not shown.

_Originally posted by @camelid in https://github.com/rust-lang/rust/issues/89852#issuecomment-942578032_

**Comment by GuillaumeGomez** [comment]
It is shown:

![Screenshot from 2021-10-21 13-37-32](https://user-images.githubusercontent.com/3050060/138269505-b1c145ae-a8bd-4a36-9cbf-1fad6ffc4bf0.png)

It doesn't have its own page and isn't included in the search index though. Should we fix both of them or keep it as is?

**Comment by jyn514** [comment]
@camelid they do behave like other re-exports: 
![image](https://user-images.githubusercontent.com/23638587/144122738-a228f4d2-8f30-41cb-b66c-07451bf94645.png)
Inlining doesn't happen because they're defined in the same crate; by default items are only inlined if the definition is private or in another crate.

I'm not sure what the bug here is?

**Comment by camelid** [comment]
Hmm, perhaps I forgot that inlining doesn't happen unconditionally.
