### ISSUE TITLE
WASM + Innative float parsing crash

### ISSUE THREAD

**Issue by SparkyPotato** [rust-lang/rust#90436]
### Code

I tried this code:

```rust
let float: f64 = "41.1".parse();
```

When compiled to target `wasm32-wasi`, and then compiled from WASM to a shared library by inNative with optimizations enabled in both steps, this causes the entire program to crash (not panic).

### Version it worked on

It most recently worked on: Any version before 2021-07-17

### Version with regression

`rustc --version --verbose`:
```
rustc 1.57.0-nightly (c1026539b 2021-10-15)
binary: rustc
commit-hash: c1026539bd22e9d070988deaa47b1360cbc76436
commit-date: 2021-10-15
host: x86_64-pc-windows-msvc
release: 1.57.0-nightly
LLVM version: 13.0.0
```

Commit 8752b403695a8830913571f0fd5ebfcf1483db37 seems to have caused the regression.

**Comment by Urgau** [comment]
I've tried to reproduce the issue with others WebAssembly runtimes ([wasmer](https://wasmer.io/) and [wasmtime](https://wasmtime.dev/)) by creating a shared library or a binary but failed reproduce the issue. They both work without a problem. As you wrote this seems to suggest that the problem is limited to the inNative WebAssembly runtime.

To help the Rust peoples can you give more information's like:
- When exactly the problem happen ? When compiling with inNative or when executing the code ?
- Does the issue reproduce with others combination of optimization ? (ex: Rust --release and inNative --debug; or Rust --debug and inNative --release)
- What kind of signals do you get ? (i'm not familiar with Windows, but on unix it's SIGSEGV, SIGINT, ...)
- Can you provide a backtrace where the program crash with gdb, lldb or WinDbg ?
- To simplify the investigation can you provide the shared library generated or even a program calling it ? (This will help the investigation by not having to install the inNative SDK.) If not, can you provide a step by step instructions with the flags you used.

*The commit that changed the float parsing is in stable*
@rustbot label +O-wasm +regression-from-stable-to-stable -regression-from-stable-to-nightly

**Comment by apiraino** [comment]
Seems this issue stills needs some feedback from the author, so I'll label as such

@rustbot label +s-waiting-on-author

**Comment by apiraino** [comment]
I'm going to remove the I-prioritize label for the moment, discussion can proceed in the [Zulip thread](https://zulip-archive.rust-lang.org/stream/245100-t-compiler/wg-prioritization/alerts/topic/.2390436.20WASM.20.2B.20Innative.20float.20parsing.20crash.html) of the Prioritization Working Group.

@rustbot label -I-prioritize

**Comment by SparkyPotato** [comment]
Seems to have been fixed by inNative.
