### ISSUE TITLE
What is Rust?

### ISSUE THREAD

**Issue by frogtile** [rust-lang/rust#90484]
> Rust is a programming language that is empowering everyone to build reliable and efficient software.

How many times we will hear this on release blog posts?

**Comment by bstrie** [comment]
For the purpose of communicating to a broad audience composed of people whose backgrounds we cannot assume, it is important to briefly summarize the project in every official blog post. Especially since we cannot know where the blog posts will be linked from, so we cannot assume that a visitor to the post has the benefit of any context at all. As an avid consumer of random release announcements I repeatedly find myself wishing that so-and-so project would have a one-sentence summary to establish context for what I'm about to read. It may be tiresome for people familiar with Rust, but the annoyance is minimal and the cost is well worth it for the sake of outreach.
