### ISSUE TITLE
"rustc_metadata::locator no metadata found: no `.rustc` section" warnings during compilation

### ISSUE THREAD

**Issue by farmaazon** [rust-lang/rust#90525]
When compiling our project, many warnings regarding "no .rustc section" are printed.

To reproduce, please check out https://github.com/farmaazon/bug-repro , go to `src/rust` directory and run `cargo build`.
You should see some warning similar to 
```
WARN rustc_metadata::locator no metadata found: no `.rustc` section in '<path-to-repo>/src/rust/target/debug/deps/libenso_shortcuts_examples.so'
```

As far as I checked, the warnings are not displayed when building crates separately. 

### Meta

`rustc --version --verbose`:
```
rustc 1.58.0-nightly (c390d69a6 2021-10-28)
binary: rustc
commit-hash: c390d69a615f095208ac94841f3310268521b2ee
commit-date: 2021-10-28
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0
```
The repository contains rust-toolchain file.

**Comment by ehuss** [comment]
Here is a reduced reproduction:

```sh
echo 'pub fn foo() {}' > foo_a_b.rs
echo 'pub use foo_a_b::foo;' > foo_a.rs
echo 'pub use foo_a::foo;' > foo.rs
echo 'fn main() { foo::foo(); }' > main.rs
rustc foo_a_b.rs --edition=2018 --crate-type=cdylib,rlib
rustc foo_a.rs --edition=2018 --crate-type=rlib --extern foo_a_b=./libfoo_a_b.rlib
rustc foo.rs --edition=2018 --crate-type=rlib --extern foo_a=./libfoo_a.rlib -L .
rustc main.rs --edition=2018 --extern foo=./libfoo.rlib -L .
```

When the crate loader needs to load `foo_a_b`, it scans for any potential candidates, and it picks up the cdylib (because it might possibly be a rust dylib). However, cdylibs don't have metadata.

There is more discussion of this at https://github.com/rust-lang/rust/issues/89795#issuecomment-940798190. I did a workaround for that particular issue, but I think I agree that the `warn!` log is too aggressive. I'll post a patch soon to propose to demote it.
