### ISSUE TITLE
Standard library test failure with `read_link` on Windows 10

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#90669]
```
---- fs::tests::read_link stdout ----
thread 'fs::tests::read_link' panicked at 'assertion failed: `(left == right)`
  left: `"c:\\ProgramData"`,
 right: `"C:\\ProgramData"`', library\std\src\fs\tests.rs:836:9
```
The failing assert is
```rust
        // directory symlink
        assert_eq!(
            check!(fs::read_link(r"C:\Users\All Users")).to_str().unwrap(),
            r"C:\ProgramData"
        );
```

I don't know why my Windows is special in this way and the `All Users` symlink contains the drive letter `C` in lowercase, this version of Windows was pre-installed on an HP laptop.
Anyway, the Rust test suite fails due to this easily fixable mismatch.

**Comment by petrochenkov** [comment]
Other links in the test have the same lowercase issue:
```diff
--- a/library/std/src/fs/tests.rs
+++ b/library/std/src/fs/tests.rs
@@ -835,17 +835,17 @@ fn read_link() {
         // directory symlink
         assert_eq!(
             check!(fs::read_link(r"C:\Users\All Users")).to_str().unwrap(),
-            r"C:\ProgramData"
+            r"c:\ProgramData"
         );
         // junction
         assert_eq!(
             check!(fs::read_link(r"C:\Users\Default User")).to_str().unwrap(),
-            r"C:\Users\Default"
+            r"c:\Users\Default"
         );
         // junction with special permissions
         assert_eq!(
             check!(fs::read_link(r"C:\Documents and Settings\")).to_str().unwrap(),
-            r"C:\Users"
+            r"c:\Users"
         );
     }
     let tmpdir = tmpdir();
```

**Comment by the8472** [comment]
It might not be a good idea to hardcode these paths in general. I'm not sure what the state of things is with windows 10 but with windows 7 it was at least possible to install on other drives than `C:\` and so they might not even exist.

**Comment by ChrisDenton** [comment]
Whichever drive you install Windows on, they system drive will be labelled `C:` from within the running system. And certain directories must be on the system drive, e.g. the Windows and Users folders. However those folders could, potentially, be called something different. It's happened before with "Documents and Settings" being renamed "Users", hence the existence of all the symlinks being tested. That said, I think it's pretty unlikely to change again anytime soon. But it is possible.

In any case the simple fix here is to compare `Path`s rather than `str`ings.
