### ISSUE TITLE
rustdoc: expand/collapse buttons look very strange in old versions of chrome

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#90705]
See https://docs.rs/opentelemetry/0.16.0/opentelemetry/struct.Context.html. ![image](https://user-images.githubusercontent.com/23638587/140791332-2621447c-1b51-4ed7-b888-34a27574d303.png)

There are a couple issues here:
- rustdoc is showing both `[+]` and the little arrow overlapping
- the toggles are on separate lines, making the docs much less compact

**Comment by camelid** [comment]
Two hypotheses:

- That crate has custom CSS.
- Its docs were built soon after the `details` cleanup landed, where there was a bug that has since been fixed.

**Comment by camelid** [comment]
Third hypothesis:

- There is something wrong with your browser, because it renders fine for me:

![image](https://user-images.githubusercontent.com/37223377/140796179-beb3d548-b92c-4499-b941-1071dc190b5b.png)

**Comment by jyn514** [comment]
@camelid yeah this is also happening for me on other crates: 
![image](https://user-images.githubusercontent.com/23638587/140797679-24156986-cb07-4d67-b5f6-da935b6f416c.png)

I'm using `Chromium 83.0.4103.116 built on Debian bullseye/sid, running on Debian bullseye/sid`

**Comment by jsha** [comment]
I can't reproduce on Chrome, Version 95.0.4638.69 (Official Build) (64-bit). @jyn514 does this happen for you on all crates? Does it happen on the nightly stdlib docs? Does it persist if you rebuild an affected crate?

I'd be interested to see the Chrome Devtools "Styles" panel you get if you right click that triangle and select "Inspect".

**Comment by jyn514** [comment]
@jsha yes, it also happens on nightly, starting in 1.54. I would be surprised if a rebuild helps but I haven't yet tried.
![image](https://user-images.githubusercontent.com/23638587/140834398-8e77d42d-6de5-40ea-b729-87d93167008d.png)

> I'd be interested to see the Chrome Devtools "Styles" panel you get if you right click that triangle and select "Inspect".

Not sure which styles exactly you're looking for, but here are some in that general area:
![image](https://user-images.githubusercontent.com/23638587/140834632-9c53f693-387c-4613-99b6-c9a96c8a2b28.png)

**Comment by jyn514** [comment]
Hmm like @camelid said it works fine in Firefox - maybe I should just bite the bullet and update chrome?
![image](https://user-images.githubusercontent.com/23638587/140834942-77e1f0f4-e349-459a-a996-7d787b7424f7.png)

**Comment by jsha** [comment]
The styles you showed are indeed the ones I wanted to see. This is the rule that's supposed to hide the default triangle icon (as copied from latest master):

```css
details.rustdoc-toggle > summary::-webkit-details-marker,
details.rustdoc-toggle > summary::marker,
details.undocumented > summary::-webkit-details-marker,
details.undocumented > summary::marker {
	display: none;
}
```

Does that show up anywhere in the styles panel?

I'm curious to I do think it's worth biting the bullet and updating Chrome on general principles - most browser releases contain fixes for vulnerabilities, and by virtue of publishing them, the release reveals they exist, which makes them much easier to exploit. So running an outdated browser version can be a big risk.

One likely-relevant thing: the `-webkit-details-marker` is a nonstandard thing that was supported by Chrome up until 88. The standardized replacement `marker` is supported since Chrome 86:

https://caniuse.com/mdn-css_selectors_-webkit-details-marker
https://caniuse.com/css-marker-pseudo

It seems likely that the standardized selector is working in our updated browsers, but the non-standardized selector is broken in some way.

What's our minimum supported Chrome version? If it's older than 86, that makes it worthwhile to dig in and find a fix.

**Comment by jyn514** [comment]
> What's our minimum supported Chrome version? If it's older than 86, that makes it worthwhile to dig in and find a fix.

https://rust-lang.github.io/rfcs/1985-tiered-browser-support.html

**Comment by camelid** [comment]
Assigning priority as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2390705.20rustdoc.3A.20expand.2Fcollapse.20buttons.20look.20very.20strange) in the prioritization working group.

**Comment by jyn514** [comment]
Ok, I updated chrome and this works fine now. Apparently `apt install chromium` on ubuntu gets you an ancient version and you need to use flatpak instead :facepalm:
