### ISSUE TITLE
Tracking issue for Vec::retain_mut and VecDeque::retain_mut

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#90829]
Feature gate: `#![feature(vec_retain_mut)]`

This is a tracking issue for adding the `retain_mut` method on `Vec`.

It'll provide a `retain_mut` method on the `Vec` and on the `VecDeque` types. It is the equivalent of the `Vec::retain` and `VecDeque` methods except that it'll expect a closure with a mutable argument instead of a const one. It'll allow to modify the elements of an array while filtering which elements we want to keep.

### Public API

```rust
pub fn retain_mut<F>(&mut self, mut f: F)
    where
        F: FnMut(&mut T) -> bool;
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/90772 and https://github.com/rust-lang/rust/pull/91215
- [x] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

None

**Comment by crumblingstatue** [comment]
Thank you! It's nice not to have to use a crate for this simple functionality.

**Comment by upsuper** [comment]
As I mentioned in https://github.com/rust-lang/rust/pull/90772#issuecomment-978772209 maybe we should add this for VecDeque as well.

**Comment by GuillaumeGomez** [comment]
I'll send a PR and we'll see if the libs team will agree or not. I'll update the issue afterward.

**Comment by elichai** [comment]
This is pretty neat. if anyone else is looking then it seems that the current best stable alternative is:
` vec = vec.into_iter().filter_map(|mut elem| {...}).collect()`

**Comment by GuillaumeGomez** [comment]
Should we start an FCP to stabilize it?

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by m-ou-se** [comment]
@rfcbot cancel

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by Mark-Simulacrum** [comment]
drain_filter:

> If the closure returns true, then the element is removed and yielded. If the closure returns false, the element will remain in the vector and will not be yielded by the iterator.

retain_mut:

> In other words, remove all elements e such that f(&mut e) returns false. This method operates in place, visiting each element exactly once in the original order, and preserves the order of the retained elements.

These methods are very similar in terms of functionality and behavior (drain_filter additionally provides access to removed elements via an iterator). That doesn't mean we shouldn't have both, but I think it makes sense to at least consider the two APIs somewhat together -- particularly when they have different behavior for identical closures (true removes the element in drain, but keeps it in retain).

**Comment by crumblingstatue** [comment]
drain_filter has been stagnating for a very long time because it has a lot of complexities.
In contrast, retain_mut is a very simple API. In fact, its implementation is exactly the same as Vec::retain. It's only due to a historical accident that Vec::retain doesn't take &mut T.

Vec::retain_mut has been delayed many times citing drain_filter, yet drain_filter is so complex that it hasn't been stabilized for so long. I don't think we should delay retain_mut any longer.

**Comment by jonhoo** [comment]
I wonder if we could change `retain` to be `retain_mut` at an edition boundary. Not actually _remove_ `retain`, mind you, but rather than for a crate with edition >=X, when you write `retain`, you get `retain_mut`.

**Comment by Mark-Simulacrum** [comment]
To be clear, I was not suggesting that retain_mut should be *delayed* in favor of drain_filter, but that it seems annoying that the current implementations result in a flipped conditional -- if you are refactoring and start to need the elements returned from retain_mut, and are now using drain_filter, then you need to be careful to flip the return value of your closure.

I suppose this is more of an argument to change drain_filter than retain_mut, since retain_mut should match retain for sure, though.

**Comment by the8472** [comment]
From [this zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/drain.20filters.20.28tracking.20issue.29/near/273279234):

There are two ways `retain_mut` could be generalized further

* it could take a range, this way one can operate on a small subset of a large vec, this is especially useful when another method appends something to a vec and then the caller wants to perform some cleanup of the appended elements. Of course it's less beneficial when doing it at the beginning of a vec since that'll incur additional moves, but it can still help when the closure is expensive
* it could move the item instead of providing a `&mut` and then the closure could return the item if it should be retained. This allows the closure to do things that require ownership. By splitting the iteration into two phases the compiler may be able to realize that those moves are a noop as long as no item has been dropped so far. And thus come at no additional cost compared to taking a `&mut` (might need some benchmarking).

**Comment by crumblingstatue** [comment]
I don't think either of those should be the job of retain_mut. retain_mut should behave exactly as retain, with the only exception of taking &mut.
Other APIs can be added later (after possibly a lot of bikeshedding). retain_mut should just be about correcting the mistake that retain doesn't take &mut. (which can't be directly fixed due to backwards compatibility issues)

**Comment by the8472** [comment]
> I don't think either of those should be the job of retain_mut.

Obviously the method could be renamed if it does more.

> Other APIs can be added later (after possibly a lot of bikeshedding).

If the performance is the same I don't see much of a benefit of having both.

**Comment by the8472** [comment]
Considering that things that go into std have to be maintained forever rushing things doesn't seem like a good plan either.

**Comment by the8472** [comment]
Tests, documentation and general clutter in the API surface have non-zero costs. Anyway, _I_ don't see urgency here and I would prefer not to spend more time on meta-discussion and instead discuss the API itself on its own merits rather than shutting down discussion on the ground that discussion is harmful because it delays things.

So, back to the API itself. Taking `&mut T` is a generalization here. I don't think it makes sense to generalize incrementally and leave intermediate steps behind as long as broader generalizations don't come with a performance or significant complexity cost.

As far as complexity for users goes I think `retain_mut_range(.., closure)` is easy enough to spell out if one wants to apply it to the full vec.

**Comment by crumblingstatue** [comment]
> Taking `&mut T` is a generalization here.

I argue that it qualifies as a fix rather than simply a generalization. There is no reason why it shouldn't take &mut T, so taking &T was a mistake. The merit of this change is to fix that mistake (without breaking backwards compatibility).

If a more general API is possible, it would deprecate `retain` as well by extension, since it's the exact same function.
So this discussion should also extend to whether retain should be deprecated for a more general API, but I think that should belong in a separate thread of discussion.

**Comment by faern** [comment]
I submitted a stabilization PR. #95491. Looks like that's the only remaining thing here. And I would appreciate if this made it into 1.61

**Comment by nashley** [comment]
Apologies if this is not the appropriate place to ask this.

I'd like to be able to call `async` code within `F`.
Would that (presumably in a new method based off of this one) be a good fit for inclusion into `std`?
