### ISSUE TITLE
Consider using a faster memset than glibc

### ISSUE THREAD

**Issue by LifeIsStrange** [rust-lang/rust#90831]
https://github.com/nadavrot/memset_benchmark

**Comment by the8472** [comment]
The benchmark isn't all that convincing. Only a single alignment and single offset tested. No hardware specs and presumably only a single platform was tested. Doesn't even mention against which glibc version was tested. Doesn't list variance of the results.

On top of that it doesn't show impact on a rust program either. Looking at a profile I happen to have open right now rustc is only spending 0.09% of its cycles on non-inlined calls to `memset`. For comparison, it's 1.26% on `memcpy`.

So maybe there are some small wins to be had, but this issue doesn't make a strong case for that.

**Comment by leonardo-m** [comment]
With better tests we could judge better :-)

**Comment by LifeIsStrange** [comment]
There is this alternative that can leverage SSE or AVX and should therefore be probably much faster.
https://github.com/moon-chilled/fancy-memset

**Comment by tschuett** [comment]
https://github.com/llvm/llvm-project/blob/main/libc/src/string/memory_utils/memset_implementations.h

resp. https://github.com/llvm/llvm-project/tree/main/libc

**Comment by the8472** [comment]
> There is this alternative that can leverage SSE or AVX and should therefore be probably much faster.

Current glibc versions already do runtime/dynamic-link-time detection of available instructions and will use AVX or SSE implementations when available.

**Comment by LifeIsStrange** [comment]
@the8472 I am aware that the Glibc has runtime feature detection mechanism for SIMD (HWCAPS, etc) but I am not aware whether they use it for a SIMD implementation of memset.
The second library I linked has the following result:
> 10-370% faster than glibc memset
Likely indicating that the Glibc do not use an explicit AVX 256 implementation even when supported.

**Comment by the8472** [comment]
> Likely indicating that the Glibc do not use an explicit AVX 256 implementation even when supported.

This commit indicates otherwise. https://github.com/bminor/glibc/commit/830566307f038387ca0af3fd327706a8d1a2f595

> Note that the author has tested on both AMD and Intel CPUs and show improvements for small, medium, and large memsets.

Well, glibc supports way more platforms than that. And the benchmark results only show a high-level summary so I'm not sure how realistic they are. The benchmark file doesn't seem to cover alignment differences. A comment even mentions that it didn't test randomized sizes i.e. all branches were quite predictable.


Anyway, a path forward would be to write a rust crate with a custom memset, at least for one platform, and then benchmark it on different CPU generations. And then link it into some larger rust program and benchmark that to see if it also yields improvements on real workloads. Testing memset in microbenchmarks is not sufficient because branch prediction, non-temporal stores not thrashing your caches can matter. I don't know if short memsets of known size would matter, the compiler probably substitutes its own implementation in those cases anyway.

Once it's proven to provide real speedups there would still be the question whether it's worth the maintenance effort to roll our own. Optimizing `memcpy` would probably more important than `memset`, if we could do better than glibc.

**Comment by workingjubilee** [comment]
As I understand it, LLVM already reserves the right to inline instructions for this purpose when it detects the mem* functions and idioms matching them. Picking a different implementation to call is rearranging deck chairs on the Titanic if we don't actually hit that code path most of the time.
