### ISSUE TITLE
Rustc complains about lack of indirection, when there is in fact indirection

### ISSUE THREAD

**Issue by T-O-R-U-S** [rust-lang/rust#91107]
I tried this code:

```rust
enum MyEnum {
  NotMyEnum,
  Is(MyEnum)
}
```

I expected to see this happen: since there is indirection in this enum (`NotMyEnum`), it should compile perfectly fine since this can be represented normally.

Instead, this happened: `rustc` complained that the type *must* be of infinite size, despite there being a source of indirection.

```rust
error[E0072]: recursive type `MyEnum` has infinite size
  --> src\parser.rs:42:1
   |
42 | enum MyEnum {
   | ^^^^^^^^^^^ recursive type has infinite size
43 |     NotMyEnum,
44 |     Is(MyEnum)
   |        ------ recursive without indirection
   |
help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to make `MyEnum` representable
   |
44 |     Is(Box<MyEnum>)
   |        ++++      +
```

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0-nightly (54bb4fec6 2021-10-08)
binary: rustc
commit-hash: 54bb4fec68cb592e23077896baea072919721573
commit-date: 2021-10-08
host: x86_64-pc-windows-msvc
release: 1.57.0-nightly
LLVM version: 13.0.0
```

<details><summary>Backtrace</summary>
<p>

The output with `RUST_BACKTRACE=1` does not differ from regular output (tested on Apple M1, on stable).
</p>
</details>

**Comment by fmease** [comment]
Rustc reporting an error is correct behavior since `MyEnum` has no fixed size. Consider `let x = f()` with `fn f() -> MyEnum { … }`. How much space should the compiler allocate for `x` on the stack? The idea of _unsized_ return values (along with unsized arguments and locals) has been floating around for some time but it's not implemented.

As far as I understand, even if we accepted your enum definition marking `MyEnum: !Sized`, one couldn't construct a value of this type directly, only through indirections and coercions (from which other type though?).

**Comment by leonardo-m** [comment]
There's no indirection (this means reference/pointer) in your enum.

**Comment by workingjubilee** [comment]
As this diagnostic specifies what it means by "indirection", I don't think this can be meaningfully improved further.
