### ISSUE TITLE
Investigate usages of `#[stable_hasher(project(name))]`

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#91921]
In several places, we use `#[stable_hasher(project(name))]` to skip hashing the `Span` of an `Ident`. For example:

https://github.com/rust-lang/rust/blob/404c8471aba60c2d837fa728e7c729a0f52d5830/compiler/rustc_hir/src/hir.rs#L205-L209

It's not obvious why this is correct. Assuming that this isn't causing any issues with incr comp invalidation, then we should add comments explaining why this is the right thing to do.

**Comment by petrochenkov** [comment]
IIRC, it was done purely as a bug-compatibility measure when `Ident`s were introduced to HIR instead of `Symbol`s to support hygiene.
Hashing spans caused either incremental errors or perf regressions.
This was long ago, so the issues preventing span hashing may be fixed now, we need to try to remove this annotations and check what happens.

**Comment by Aaron1011** [comment]
This is now causing a bug - since we now serialize the full `AdtDef` to disk, we may try to deserialize a stale `ExpnId` from a foreign crate, because we will incorrect end up thinking that an `AdtDef` is unchanged when one of its `Span` fields changes. See https://github.com/rust-lang/rust/issues/92192

**Comment by Aaron1011** [comment]
This was fixed in https://github.com/rust-lang/rust/pull/92534, https://github.com/rust-lang/rust/pull/93095, and https://github.com/rust-lang/rust/pull/92533
