### ISSUE TITLE
Insufficient diagnostic info when casting `usize` to fat pointer

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#92125]
Given the following code: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=76803b017be7f10f458ee6e4f6aac6d2)

```rust
fn main() {
    maybe_sized_t::<()>();
}

fn maybe_sized_t<T: ?Sized>() {
    let _ptr = 0 as *mut T; 
}
```

The current output is:

```
error[E0606]: casting `usize` as `*mut T` is invalid
 --> src/main.rs:6:16
  |
6 |     let _ptr = 0 as *mut T; 
  |                ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0606`.
error: could not compile `playground` due to previous error
```

```
error[E0606]: casting `usize` as `*mut T` is invalid
 --> src/main.rs:6:16
  |
6 |     let _ptr = 0 as *mut T; 
  |                ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0606`.
error: could not compile `playground` due to previous error

note: `*mut T` is a fat pointer, and can therefore not be built from a `usize`
```

Casting a `usize` to a regular pointer is possible, so it's a bit confusing at first that this doesn't work for fat pointers, especially if it's not obvious that `*mut T` is a fat pointer here.

**Comment by compiler-errors** [comment]
Perhaps it should say "`*mut T` may be a fat pointer", since it's `?Sized` (and so it could either be 1xusize or 2xusize depending on the choice of T).

Another possibly useful thing to point out for the programmer: tracking down the definition of the pointee type, and if it's a generic parameter, pointing to the `?Sized` bound.
