### ISSUE TITLE
Why is the semicolon after the return statement optional？

### ISSUE THREAD

**Issue by chenyang8094** [rust-lang/rust#92217]
What is the difference between these two pieces of code?

```
fn foo() -> i32 {
    return 3 // type is i32
}
```
and
```
fn foo() -> i32 {
    return 3; // type is unit ()
}
```

`return 3`  is an expression, its type is `i32` and value is 3
`return 3;`  is a statement, and its return type is unit  `()`
but the following two pieces of code can be compiled success, what is wrong with my understanding?

There is a more detailed discussion here, but I think we still haven't figured it out.

https://users.rust-lang.org/t/why-is-the-semicolon-after-the-return-statement-optional/68758/17

**Comment by Aaron1011** [comment]
@chenyang8094: The type of `return 3` is actually `!` - the [unstable `never` type](https://doc.rust-lang.org/std/primitive.never.html). Anything after a `!` type is produced is unreachable, so the compiler allows `!` to turn into any type (in this case, `i32`).

In the case with the semicolon, it's a little more subtle. The compiler knows that after a value of `!` is 'produced' by the `return` expression, the rest of the function is unreachable. Since there's no trailing expression, the compiler treats the function as though it returned an `i32` (since the rest of the function is unreachable).

Note that this code also compiles:

```rust
fn test() -> i32 {
    return 25;
    true;
}
```

illustrating that the compiler handles the function in a special way after `!` is produced.

**Comment by chenyang8094** [comment]
> 

Thank you , I am very satisfied with your answer, and I also found some corroboration in the relevant documents, thank you again for your answer. 

https://doc.rust-lang.org/stable/reference/types/never.html
https://github.com/rust-lang/rust/issues/35121

**Comment by chenyang8094** [comment]
If` return 3` is actually `!` type , why the following code can't work,  the compiler allows `!` to turn into any type , in this case, `() `unit type. ?
```
fn foo()  {
    return 3
}
```
or 
```
fn foo()  {
    return 3;
}
```
or
```
fn foo()  -> () {
    return 3
}
```

**Comment by Aaron1011** [comment]
@chenyang8094 Sorry, I forgot to post my reponse.

While the type of the expression `return 3`  is `!`, the compiler also checks that the type of the 'argument' to `return` (in this case, `3`) matches the return type of the function. This is similar to how the compiler checks that a `for` loop is actually iterating over an iterator (e.g. `for val in 30` does not compile)
