### ISSUE TITLE
Tracking Issue for comparing values in `const` items

### ISSUE THREAD

**Issue by fee1-dead** [rust-lang/rust#92391]
Feature gate: `#![feature(const_cmp)]`

This is a tracking issue for various `const` `PartialEq`, `PartialOrd`, `Ord` impls in the standard library

### Public API

```rust
// core::cmp

impl<T: ~const PartialOrd> const PartialOrd for Reverse<T> {}
impl const Ord for Ordering {}
impl const PartialOrd for Ordering {}
impl const PartialEq for Ordering {}
pub const fn min<T: ~const Ord + ~const Drop>(v1: T, v2: T) -> T;
pub const fn max<T: ~const Ord + ~const Drop>(v1: T, v2: T) -> T;
impl const PartialEq for {bool char usize u8 u16 u32 u64 u128 isize i8 i16 i32 i64 i128 f32 f64 () !}
impl const PartialOrd for {bool char usize u8 u16 u32 u64 u128 isize i8 i16 i32 i64 i128 f32 f64 () !}
impl const Ord for {bool char usize u8 u16 u32 u64 u128 isize i8 i16 i32 i64 i128 () !}


pub const fn min_by<T, F: ~const FnOnce(&T, &T) -> Ordering>(v1: T, v2: T, compare: F) -> T
where
    T: ~const Destruct,
    F: ~const Destruct;

pub const fn min_by_key<T, F: ~const FnMut(&T) -> K, K: ~const Ord>(v1: T, v2: T, mut f: F) -> T
where
    T: ~const Destruct,
    F: ~const Destruct,
    K: ~const Destruct;

pub const fn max_by<T, F: ~const FnOnce(&T, &T) -> Ordering>(v1: T, v2: T, compare: F) -> T
where
    T: ~const Destruct,
    F: ~const Destruct;

pub const fn max_by_key<T, F: ~const FnMut(&T) -> K, K: ~const Ord>(v1: T, v2: T, mut f: F) -> T
where
    T: ~const Destruct,
    F: ~const Destruct,
    K: ~const Destruct;

```

### Steps / History

- [x] Implementation: #92390 #101810 #102245
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by slightlyoutofphase** [comment]
One interesting thing to note is that you can currently _use_ all of those primitive types as fields inside structs, implement `const PartialOrd` / `const PartialEq` / etc for the structs, and then have `const fn`s defined with the appropriate `~const` bounds work completely fine with them.

However, `const` "free" functions attempting to operate _directly_ on the primitive types just do not work, as I inquired about / demonstrated [here](https://github.com/rust-lang/rust/issues/67792#issuecomment-1002675907) a bit earlier today.

I'm assuming this probably has something to do with the compiler likely just "special casing" primitive types in various scenarios without actually taking the trait system directly into account at all (which it seems as though it'd have to have done historically in order to avoid all sorts of runtime performance isssues popping up).

**Comment by raldone01** [comment]
Any reason why `impl const PartialEq for Ordering {}` is not added by this feature?

**Comment by raldone01** [comment]
Should I create a pull request that adds it to this feature or create a new feature?

**Comment by raldone01** [comment]
@fee1-dead Now that #101810 has been merged you should consider adding `impl const PartialEq for Ordering {}` to the tracking issue. Maybe also add it to `Steps / History -> Implementation`.

**Comment by tgross35** [comment]
@fee1-dead could this, or at least a subset, be moved to const stable at this point? I'm not sure if it's blocked on const traits, but the functions seem fairly uncontroversial

**Comment by fee1-dead** [comment]
No we are currently planning temporary removal of all things related to const traits in the standard library to allow a clean redesign of compiler implementation of const traits. Unless there's a way to make sure that it would remain stable even if we remove const traits entirely we can't stabilize anything that uses const traits. Also do note that const traits don't have an accepted RFC yet and is still experimental.

**Comment by Thomasdezeeuw** [comment]
For people following this tracking issue, it seems to be removed in https://github.com/rust-lang/rust/pull/110393, the removal is tracked in https://github.com/rust-lang/rust/issues/110395.

**Comment by RalfJung** [comment]
This has been removed by https://github.com/rust-lang/rust/pull/110393.
