### ISSUE TITLE
Backport Clippy changes

### ISSUE THREAD

**Issue by Alexendoo** [rust-lang/rust#92938]
commit: https://github.com/rust-lang/rust-clippy/commit/5d63a286383b0a0ed03aa2568e306a3a154e3fa9, context: https://github.com/rust-lang/rust-clippy/issues/8045

**Comment by flip1995** [comment]
Besides https://github.com/rust-lang/rust/commit/5d63a286383b0a0ed03aa2568e306a3a154e3fa9, we'd also like to backport https://github.com/rust-lang/rust/commit/cb384ff03b7a10bca10b962d9907c0d56ba3086f, which addresses a bug with our `useless_format` lint when it comes to implicit named arguments. This was fixed in https://github.com/rust-lang/rust-clippy/pull/8295 and synced to rustc in #93001. That will also need a beta backport.

**Comment by ehuss** [comment]
I think this can be closed with #93377 merged?  For some reason, GitHub didn't auto-close this.

**Comment by Mark-Simulacrum** [comment]
Seems right.
