### ISSUE TITLE
Windows: Reduce raciness of `spawn()`  vs. `SetCurrentDirectory`

### ISSUE THREAD

**Issue by briansmith** [rust-lang/rust#93133]
I was inspecting `resolve_exe()` specifically looking for racy coding patterns.

The code currently contains this:
```rust
    if !path::is_file_name(exe_path) {
        if has_exe_suffix {
            // The application name is a path to a `.exe` file.
            // Let `CreateProcessW` figure out if it exists or not.
            return Ok(exe_path.into());
        }
        let mut path = PathBuf::from(exe_path);

        // Append `.exe` if not already there.
        path = path::append_suffix(path, EXE_SUFFIX.as_ref());
        if path.try_exists().unwrap_or(false) {
            return Ok(path);
        } else {
            // It's ok to use `set_extension` here because the intent is to
            // remove the extension that was just added.
            path.set_extension("");
            return Ok(path);
        }
```
Consider what happens when we pass a relative path containing a path separator, e.g. "target/something". This code will check if the file `target/something.exe` exists, relative to the current working directory and if so, return `"target/something.exe"`.

This function is used by the implementation of `spawn()`. Roughly, spawn looks like this:

```rust
let program = resolve_exe(&self.program, || env::var_os("PATH"), child_paths)?;
...
let (dirp, _data) = make_dirp(self.cwd.as_ref())?;
...
let program = to_u16s(&program)?;
unsafe {
    cvt(c::CreateProcessW(
        program.as_ptr(),
        ...
        dirp, // lpCurrentDirectory
        &mut pi,
    ))
}?;
```

In theory the current working directory could change at any time. To minimize the effect that would have on `spawn()`, it seems like it could instead be written like this:

```rust
let cwd = self.cwd.as_ref();
let program = resolve_exe(cwd, &self.program, || env::var_os("PATH"), child_paths)?;
...
let (dirp, _data) = make_dirp(cwd)?;
...
let program = to_u16s(&program)?;
unsafe {
    cvt(c::CreateProcessW(
        program.as_ptr(),
        ...
        dirp, // lpCurrentDirectory
        &mut pi,
    ))
}?;
```
And then change `resolve_exe` so that it always returns an absolute path, where it always resolves any relative paths relative to the value of the `cwd` parameter passed in.

`spawn()` and `SetCurrentDirectory` would still be racy, but at least all the path resolution within `spawn` would be internally consistent with respect to the current directory at a point in time.

**Comment by ChrisDenton** [comment]
I think I did something along these lines in: https://github.com/rust-lang/rust/pull/91182/files

That PR is creating an absolute (verbatim) path before testing it for existence and returning the absolute path. I made it when I was testing for differences in symlink behaviour caused by `resolve_exe`. However, since the holiday season I appear to have left the PR to languish so I'll need to dust it off a bit.

**Comment by ChrisDenton** [comment]
The current code is: https://github.com/rust-lang/rust/blob/745efcc7d9b59d31674bf9445269924377019c5c/library/std/src/sys/windows/process.rs#L415-L416

That is it uses the absolute path returned by the program_exists call rather than the potentially relative path originally given, As you say, there is still some raciness here but it's inherent in trying to guess the path the user wanted and then spawning the new process. There are no public APIs that allow spawning a process by file handle so there's not much more that can be done here.
