### ISSUE TITLE
rustdoc: Margin below search results changes once the user starts typing a search in Safari

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#93184]
### Steps

1. Open (desktop) Safari
2. Click the search box here: https://doc.rust-lang.org/nightly/std/
3. Type a letter
4. Delete the letter
5. Type another letter
6. Notice how the empty space below the search bar changes size

cc @jsha – I think this is a recent regression; it's in nightly. I presume it has some connection to either your "All crates" change or your sidebar change. This bug is not present in beta.

**Comment by jsha** [comment]
Hm, I can't reproduce on desktop Safari 15.1. Can you share a video?

I _can_ observed a small change in the width of the sidebar between typing
a letter and deleting. I'll investigate that.

**Comment by camelid** [comment]
I'm on Safari 15.2, though I'm not sure if it matters. I'll see if I can get a video sometime soon but I'm a bit busy right now.

**Comment by gelfand** [comment]
https://user-images.githubusercontent.com/45895290/150622700-2c7662bd-7a10-430e-a6c1-12ff744f7455.mov

**Comment by camelid** [comment]
Thanks!

**Comment by jsha** [comment]
Thanks for the video @gelfand, that really helped me figure out what I was looking for.

I was able to bisect it to 8abb4bb698c9d74507adb9cd7b54a032f3c1b595 (moving the crate dropdown onto the search page).

Surprisingly, the minimum diff that causes the issue was not any of the CSS, but removing the dropdown element. So long as the search input has a previous sibling of any kind, the bumpiness does not happen. It's quite mysterious. I haven't been able to find a style that causes this.
