### ISSUE TITLE
Named format arguments can be used as positional

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#93415]
I [tried this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c93e0a6f62eb4c6f23a85912bbec861b):

```rust
fn main() {
    let what = "what?";
    println!("{a}{}", a=what);
}
```

I expected to see this happen:

```
error: 1 positional argument in format string, but no arguments were given
 --> <source>:3:18
  |
3 |     println!("{a}{}", a=what);
  |                  ^^
```

Instead, this happened: *explanation*

Standard Error
```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 1.94s
     Running `target/debug/playground`
```

Standard Output
```
what?what?
```

### Meta

This happens on current 1.60.0-nightly (2022-01-27 21b4a9cfdcbb1e76f4b3), and back to _rustc 1.12.0_[^1]. On rustc 1.11.0, it gives

[^1]: So I guess this would be considered regression-from-stable-to-stable? 🙃

```
<std macros>:3:11: 3:36 error: invalid reference to argument `0` (no arguments given)
<std macros>:3 print ! ( concat ! ( $ fmt , "\n" ) , $ ( $ arg ) * ) ) ;
                         ^~~~~~~~~~~~~~~~~~~~~~~~~
<std macros>:3:11: 3:36 note: in this expansion of concat!
<std macros>:2:27: 2:58 note: in this expansion of format_args!
<std macros>:3:1: 3:54 note: in this expansion of print! (defined in <std macros>)
<source>:3:5: 3:37 note: in this expansion of println! (defined in <std macros>)
```

Given _how old_ this "support" is, I don't know if this can be classified as a bug anymore, or if it's just more of a misfeature at this point. IMHO, this should at least get a lint, or even a future-compat lint if that's considered reasonable.

**Comment by klensy** [comment]
Perhaps #93378?

**Comment by CAD97** [comment]
Looks to be it, beat me to it by a day it looks like.

**Comment by CAD97** [comment]
I restricted this just to the "named arguments can be used as positional" case, since #93378 is getting fixed for the more obviously bad case of `println!("{what}{}")`.

**Comment by CAD97** [comment]
Note that if this gets upgraded to a hard error, #93394 can be backed out, as it exists just so that implicit captures don't count as positional arguments (but named arguments still do).

**Comment by m-ou-se** [comment]
I agree with @CAD97 said: While it can be confusing, I'm not sure it's something we should consider a bug, as this behaviour has been stable for almost six years.

A lint that warns about it could be reasonable. Maybe something like this:

```
warning: positional argument in format string refers to named argument
 --> <source>:3:18
  |
3 |     println!("{a}{}", a=what);
  |                  ^^
help: use its name to avoid confusion
  |
3 |     println!("{a}{a}", a=what);
  |                   +
```

**Comment by Veetaha** [comment]
> this behaviour has been stable for almost six years.

@m-ou-se I don't think this behavior was documented. I did stumble upon it even before opening #93378 when writing a derive with `thiserror`, but thought it could be a bug in that library. It surprised me to see the same unexpected behavior in standard formatting macros!

Since this behavior wasn't documented we shouldn't consider it as a valid usage of formatting macros. If we make it a hard error I am sure a ton of code will break, but we can make it at least a compatibility warning similar to how we got rid of `panic!("{}")` behavior, saying that it is considered a bug and we intend to remove this in future versions of the language.

**Comment by m-ou-se** [comment]
> make it at least a compatibility warning similar to how we got rid of `panic!("{}")` behavior, saying that it is considered a bug and we intend to remove this in future versions of the language.

Sure, that's basically the same lint that was already suggested. Whether we tag that as a future compaibility lint or not is debatable. I don't see any reason to make this stronger than a warning. A warning helps against bugs, but anything stronger doesn't really seem to have much extra value. I don't think it makes sense to warn if any of your dependencies trigger the lint, for example.

> But, I'd rather give it to `crater` before we make a decision.

As Rust usage outside of open-source grows, Crater is becoming less and less a reliable indicator for these sort of things. Especially since it mostly tests libraries, while `print!()`ing is probably way more common in binaries.

**Comment by SNCPlay42** [comment]
This also works with captured bindings:

```rust
fn main() {
    let a = "what?";
    println!("{a}{}");
}
```

Compiles and prints `what?what?`.

[(playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=df30532a5d964775f3225f5ff17737b3)

**Comment by estebank** [comment]
https://github.com/rust-lang/rust-clippy/pull/9040 will cover this case.

**Comment by CAD97** [comment]
This warns on the current stable (1.71):

```text
warning: named argument `a` is not used by name
 --> src/main.rs:3:23
  |
3 |     println!("{a}{}", a=what);
  |                  --   ^ this named argument is referred to by position in formatting string
  |                  |
  |                  this formatting argument uses named argument `a` by position
  |
  = note: `#[warn(named_arguments_used_positionally)]` on by default
help: use the named argument by name to avoid ambiguity
  |
3 |     println!("{a}{a}", a=what);
  |                   +
```

I think we should consider making this a hard error in edition2024, but otherwise this issue can be considered resolved.

**Comment by m-ou-se** [comment]
As [mentioned above](https://github.com/rust-lang/rust/issues/93415#issuecomment-1657240458), this is still accepted but gives a warning now. We can still consider making this a hard error in a future edition.

I don't think it's worth it doing anything edition-specific here. A warning seems just fine. I don't think we'd gain anything by changing `format_args!()` to completely reject these cases.

@rfcbot close

**Comment by CAD97** [comment]
Per FCP, closing as completed.
