### ISSUE TITLE
Drop tracking ignores borrows with projections

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#93648]
For example:

```rust
fn main() {
    let _ = async {
        let mut s = (String::new(),);
        s.0.push_str("abc");
        std::mem::drop(s);
        async {}.await;
    };
}
```

```console
$ rustc +nightly-2022-01-22 --edition=2021 b.rs
error: internal compiler error: compiler/rustc_mir_transform/src/generator.rs:755:13: Broken MIR: generator contains type (String,) in MIR, but typeck only knows about {ResumeTy, impl Future<Output = [async output]>, ()} and []
```

The `TryFrom<&PlaceWithHirId<'_>> for TrackedValue` fails for places with projections, so in that case borrow is never recorded:

https://github.com/rust-lang/rust/blob/4c55c8362de32be1530b2441c3e3a51e73edeb21/compiler/rustc_typeck/src/check/generator_interior/drop_ranges.rs#L133-L143

https://github.com/rust-lang/rust/blob/4c55c8362de32be1530b2441c3e3a51e73edeb21/compiler/rustc_typeck/src/check/generator_interior/drop_ranges/record_consumed_borrow.rs#L93-L102

**Comment by eholk** [comment]
Thanks for the test case and the analysis!

It looks like I got the logic around this wrong. Basically, to goal was to have it so that consumes of a projection (e.g. `drop(x.y)`) are ignored, and reinitializations (`x.y = foo`) count as reinitializing all of `x`. It seems the code that ignores projections is too aggressive in ignoring things.

I'll try to get a fix out soon!

@rustbot claim
