### ISSUE TITLE
Vec insert ignore semicolon

### ISSUE THREAD

**Issue by zjb0807** [rust-lang/rust#93811]
I tried this code:

```rust
#![allow(unused)]
fn main() {
    let mut vec = vec![1, 2, 3];
    if true {
        vec.insert(1, 4)
    }
    assert_eq!(vec, [1, 4, 2, 3]);
}
```

I expected to see this happen: build error in `vec.insert(1, 4)` without `;`

Instead, this happened: success.

**Comment by ehuss** [comment]
This is expected behavior. When the semicolon is not included as the last statement in a block, the value of the block is that last expression.  In this case, the value of `vec.insert()` is `()`.   An `if` expression evaluates to whichever block is executed, or `()` if neither is.  The `()` is effectively ignored.

I'm not sure if a warning would be worthwhile here.  For the most part, this is harmless, though I can see how it can look unusual.

**Comment by PatchMixolydic** [comment]
Clippy has an allow-by-default lint for this with a somewhat confusing name: [`clippy::semicolon_if_nothing_returned`](https://rust-lang.github.io/rust-clippy/master/#semicolon_if_nothing_returned).
