### ISSUE TITLE
Should format_args_nl! be #[doc(hidden)] ?

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#93904]
Initial title: format_args_nl! should link to format_args! where they mention it

----

https://doc.rust-lang.org/nightly/std/macro.format_args_nl.html currently contains:

> Same as `format_args`, but adds a newline in the end.

It would be nicer as:

> Same as [`format_args`](https://doc.rust-lang.org/nightly/std/macro.format_args.html), but adds a newline in the end.

… although I also find https://github.com/rust-lang/rust/pull/87410 which made it `#[doc(hidden)]`. It looks like that was undone at some point?

**Comment by name1e5s** [comment]
It seems that `#[doc(hidden)]` is removed in #92456

**Comment by danielhenrymantilla** [comment]
After some discussion in that PR, it was deemed that a macro being `unstable` did not warrant, _on its own_, marking the macro as `#[doc(hidden)]`. **Hence why a bunch of such macros were unhidden by that PR** (but maybe `format_args_nl!` shouldn't have been part of those?). I really don't have a strong opinion here myself, so lemme wash my hands 😄, but:

  - on the one hand, I do lean towards not hiding, in general, some of these `unstable` macros since it may reduce a bit too much their discoverability.

  - on the other hand, I'll grant that there is a difference, alas quite subtle / currently hard-to-express, between `unstable`-and-expected-to-eventually-be-stabilized, and perma-`unstable`; for the latter it seems more legitimate to mark them as `#[doc(hidden)]`.

    Given the description of the unstability of `format_args_nl`, it seems like it's the latter?

🤷

**Comment by danielhenrymantilla** [comment]
Yeah, I share the feeling: feel free to go and make it `#[doc(hidden)]` again then

**Comment by raindev** [comment]
One potential argument against hiding the macro from the docs is that it shows up in the compiler errors originating from the use of formatting macros (i.e. ``note: this error originates in the macro `$crate::format_args_nl```).

**Comment by jyn514** [comment]
This is being stabilized in https://github.com/rust-lang/rust/pull/97658, so I think the answer is pretty clearly "no" now (but the discussion here is interesting for other perma-unstable macros).
