### ISSUE TITLE
Inuktitut Brackets are not recognized 

### ISSUE THREAD

**Issue by AbleTheAbove** [rust-lang/rust#93931]
Given the following code: [Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0a009d396cb891704dbd8f2bd8aa78a2)

```rust
struct genericᐸTᐳ(T);
```

The current output is:

```
error[[E0412]](https://doc.rust-lang.org/stable/error-index.html#E0412): cannot find type `T` in this scope
 [--> src/main.rs:2:19
](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0a009d396cb891704dbd8f2bd8aa78a2#)  |
2 | struct genericᐸTᐳ(T);
  |                  -^ not found in this scope
  |                  |
  |                  help: you might be missing a type parameter: `<T>`
```

Ideally the output should look something like:

```
error: unknown start of token: \u{37e}
  --> src/wasm_jumploader/host_functions.rs:24:64
   |
24 |                 println!("SYSCALL: {} + {} = {}", a, b, result);
   |                                                                ^
   |
help: Unicode character ';' (Greek Question Mark) looks like ';' (Semicolon), but it is not
   |
24 |                 println!("SYSCALL: {} + {} = {}", a, b, result);
   |       
```

**Comment by VitalyAnkh** [comment]
The error disappears when using a capital struct name: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0a009d396cb891704dbd8f2bd8aa78a2). It looks like the parser utilizes [the naming conventions](https://github.com/rust-lang/rfcs/blob/master/text/0430-finalizing-naming-conventions.md).

**Comment by scottmcm** [comment]
Note that this already has a warning about the "brackets":

```
warning: identifier contains uncommon Unicode codepoints
 [--> src/main.rs:2:8
](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021#)  |
2 | struct genericᐸTᐳ(T);
  |        ^^^^^^^^^^
  |
  = note: `#[warn(uncommon_codepoints)]` on by default
```

So it's possible the current situation is fine as-is.

**Comment by AbleTheAbove** [comment]
While true about the warning I'd like a similar error to the Greek Question mark example.

If it's deemed good as is then that is alright.

**Comment by scottmcm** [comment]
I think this is largely an expected consequence of following Unicode for literals.  If you were writing code in that script, the error message is correct.  And warning about combinations of scripts was decided against, per https://rust-lang.github.io/rfcs/2457-non-ascii-idents.html#mixed-script-detection

And if you're not writing in such a script, you could always turn on the `non_ascii_idents` lint or make `uncommon_codepoints` more severe.  But non-ascii scripts not being an error by default is intentional.

So what I'd say is that while perhaps it's correct that it's not an *error*, maybe the warning should have more details, perhaps like

```text
warning: identifier contains uncommon Unicode codepoints
 --> src/main.rs:2:8
  |
2 | struct genericᐸTᐳ(T);
  |        ^^^^^^^^^^
  |
  = note: `#[warn(uncommon_codepoints)]` on by default
  |
2 | struct genericᐸTᐳ(T);
  |               ^ this `ᐸ` is U+1438 (Canadian Syllabics Pa)
```

But overall I'm not convinced it's worth doing too much fancy handling of something that's basically just a troll.  So long as it's linted to emphasize "hey, there's unusual unicode going on here", that's enough for me personally.

---

Some more details:

Per <https://rust-lang.github.io/rfcs/2457-non-ascii-idents.html#reference-level-explanation>, things are valid in non-leading position if they're in `XID_Continue`, which per https://www.unicode.org/reports/tr42/ is the `XIDC` attribute in ucdxml.

ᐸ is 'CANADIAN SYLLABICS PA' (U+1438), and if I look in https://www.unicode.org/Public/14.0.0/ucdxml/ that's

\<char cp="1438" age="3.0" na="CANADIAN SYLLABICS PA" JSN="" gc="Lo" ccc="0" dt="none" dm="#" nt="None" nv="NaN" bc="L" bpt="n" bpb="#" Bidi_M="N" bmg="" suc="#" slc="#" stc="#" uc="#" lc="#" tc="#" scf="#" cf="#" jt="U" jg="No_Joining_Group" ea="N" lb="AL" sc="Cans" scx="Cans" Dash="N" WSpace="N" Hyphen="N" QMark="N" Radical="N" Ideo="N" UIdeo="N" IDSB="N" IDST="N" hst="NA" DI="N" ODI="N" Alpha="Y" OAlpha="N" Upper="N" OUpper="N" Lower="N" OLower="N" Math="N" OMath="N" Hex="N" AHex="N" NChar="N" VS="N" Bidi_C="N" Join_C="N" Gr_Base="Y" Gr_Ext="N" OGr_Ext="N" Gr_Link="N" STerm="N" Ext="N" Term="N" Dia="N" Dep="N" IDS="Y" OIDS="N" XIDS="Y" IDC="Y" OIDC="N" XIDC="Y" SD="N" LOE="N" Pat_WS="N" Pat_Syn="N" GCB="XX" WB="LE" SB="LE" CE="N" Comp_Ex="N" NFC_QC="Y" NFD_QC="Y" NFKC_QC="Y" NFKD_QC="Y" XO_NFC="N" XO_NFD="N" XO_NFKC="N" XO_NFKD="N" FC_NFKC="#" CI="N" Cased="N" CWCF="N" CWCM="N" CWKCF="N" CWL="N" CWT="N" CWU="N" NFKC_CF="#" InSC="Other" InPC="NA" PCM="N" vo="U" RI="N" blk="UCAS" isc="" na1="" Emoji="N" EPres="N" EMod="N" EBase="N" EComp="N" ExtPict="N"/>

With, importantly, `XIDC="Y"`.  (As well as `XIDS="Y"`, so it'd be valid in leading position too.)

And thus `genericᐸTᐳ` is a completely valid and legal identifier -- albeit certainly an unusual one.

The greek question mark example is different in a couple of ways.  For one, it's neither `XID_Continue` nor `XID_Start`, so it's not affected by unicode identifiers.  But that position is also one where an identifier isn't allowed anyway, so even if it *were* allowed in identifiers it'd still be an error to put it there, the same way that `println!("hello")w` is an error.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/117685#issuecomment-1836343502
