### ISSUE TITLE
Firefox crashes on Windows because BCryptGenRandom fails

### ISSUE THREAD

**Issue by msmania** [rust-lang/rust#94098]
Hi, I'm an engineer working for Mozilla on Firefox.  We recently noticed we'd been getting crash reports indicating Firefox crashes during `env_logger` initialization.  Upon debugging, we found out it was caused by a failure of `BCryptGenRandom`, that was introduced by #84096.

Almost all reports are from Windows 7 32-bit.  We don't know the reason why `BCryptGenRandom` failed.  Possibly the cryptography settings in the registry was corrupted and the process couldn't find the module.

To mitigate this crash, can you add a fallback logic, using `RtlGenRandom` if `BCryptGenRandom` fails for whatever reason.  Probably we can limit it to Win7.

Here's the link to the tracking bug in Bugzilla.

https://bugzilla.mozilla.org/show_bug.cgi?id=1754490

**Comment by newpavlov** [comment]
Are you sure that `RtlGenRandom` will work in the case of `BCryptGenRandom` failure? I don't think it's correct to introduce such workaround hacks into `std`, since it's clearly an OS problem.

IIUC `RtlGenRandom` is deprecated in favor of `BCryptGenRandom` and ideally should not be used outside of Windows XP. Relevant discussion can be found in: https://github.com/rust-random/getrandom/issues/65

**Comment by Milo123459** [comment]
> Also note that we can not target only Win7 without affecting other Windows versions using only cfg gating, since Windows version is not part of target triplet.

Is there not some manual way we could check inside of the cfg block?

**Comment by marti4d** [comment]
Hi there! Sorry about the radio silence for a while on this issue -- The OP isn't able to continue working on this, and I've been asked to help resolve it.

I have added a PR that implements the idea of re-introducing `RtlGenRandom()` as a fallback API in the (very rare) case that `BCryptGenRandom()` doesn't work on a machine.

> Are you sure that `RtlGenRandom` will work in the case of `BCryptGenRandom` failure? I don't think it's correct to introduce such workaround hacks into `std`, since it's clearly an OS problem.

We are very certain of this, as we don't see equivalent crashes in Firefox in [our own use of RtlGenRandom](https://searchfox.org/mozilla-central/rev/5f88c1d6977e03e22d3420d0cdf8ad0113c2eb31/mfbt/RandomNum.cpp#25), and I don't see any issue reported for Chrome/Edge [in their code](https://source.chromium.org/chromium/chromium/src/+/main:base/rand_util_win.cc)

We are not convinced that it is an "OS problem", persay... We suspect that a virus scanner or other security software may be interfering with certain machines' ability to load the BCrypt library. We don't even know for certain that this issue only affects Firefox; it could just be that we're the only ones with beefy enough crash reporting to catch it.

I agree with you in principle that it's not great to have to introduce workarounds for things like "a virus scanner is breaking Rust code" into the standard library, but if we assume that Firefox is not the only piece of software that has this issue then where else should the change be made? Even if it is only Firefox, we're left with the options of either "seeing through" the abstraction that `std` offers and warming up with `getrandom`, continuing to crash, or forking `std`

The PR I have attached should make no difference in the 99.999%+ machines where this is not a problem, but in that small fraction of machines where BCrypt is broken, this only improves the robustness of StdLib.

> Also note that we can not target only Win7 without affecting other Windows versions using only `cfg` gating, since Windows version is not part of target triplet.

As it turns out, the name of this issue is perhaps a bit wrong. This issue is seen on multiple versions of Windows ([example crash on Windows 10](https://crash-stats.mozilla.org/report/index/f1908bd3-3a93-4f88-a363-c06db0220509)). My PR is agnostic to this anyway -- if `BCryptGenRandom()` fails for whatever reason, it will then use `RtlGenRandom()` for the rest of the runtime.

**Comment by ChrisDenton** [comment]
Thank you for following up on this issue. As you say, we are reliant on Firefox's data here. I've updated the title to better reflect that not just x86 Windows 7 is affected.

**Comment by nagisa** [comment]
>We are not convinced that it is an "OS problem", persay... We suspect that a virus scanner or other security software may be interfering with certain machines' ability to load the BCrypt library. We don't even know for certain that this issue only affects Firefox; it could just be that we're the only ones with beefy enough crash reporting to catch it.
>
>I agree with you in principle that it's not great to have to introduce workarounds for things like "a virus scanner is breaking Rust code" into the standard library, but if we assume that Firefox is not the only piece of software that has this issue then where else should the change be made?

If it is _indeed_ caused by essential snake oils, then I’d argue that Firefox as an application has just large enough of a profile to get the vendors to fix _their_ software. You all aren’t introducing workarounds to enable Firefox’s operation on systems with random memory bit-flips caused by unstable memory, are you? I would argue a similar line of thinking could apply here to at least some extent.

**Comment by marti4d** [comment]
> > We are not convinced that it is an "OS problem", persay... We suspect that a virus scanner or other security software may be interfering with certain machines' ability to load the BCrypt library. We don't even know for certain that this issue only affects Firefox; it could just be that we're the only ones with beefy enough crash reporting to catch it.
> > I agree with you in principle that it's not great to have to introduce workarounds for things like "a virus scanner is breaking Rust code" into the standard library, but if we assume that Firefox is not the only piece of software that has this issue then where else should the change be made?
> 
> If it is _indeed_ caused by essential snake oils, then I’d argue that Firefox as an application has just large enough of a profile to get the vendors to fix _their_ software. You all aren’t introducing workarounds to enable Firefox’s operation on systems with random memory bit-flips caused by unstable memory, are you? I would argue a similar line of thinking could apply here to at least some extent.

FWIW I agree, and we do generally try to get vendors to fix their software: we've worked with many companies like Symantec, AVG, McAfee, etc to fix their products, and I completely agree that this is preferable because it improves the software ecosystem for everyone.

In this case, we were unable to link the BCrypt issue to a specific source; it's still in our queue to investigate it, and once we do I could foresee a future where we push another change to Rust Std to undo the thing I did. In the meantime, someone in the chain has to unfortunately workaround this issue. Given that `HashMap` is an essential part of Rust Std, we assume that "almost every Rust program crashes on this small set of machines" is not really the kind of optics that the Rust community wants.

It would be nice, of course, if all vendors just followed the APIs they were given properly, but I doubt you'll find any popular language's standard library that doesn't contain a pile of workarounds for this kind of stuff
