### ISSUE TITLE
Typo in URL to 1.58.1 release notes in announcement blog post

### ISSUE THREAD

**Issue by paulmenzel** [rust-lang/rust#94278]
The URL to the 1.58.1 release notes in the [blog post *Announcing Rust 1.58.1*](https://blog.rust-lang.org/2022/01/20/Rust-1.58.1.html) is incorrect. Instead of

https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1581-2022-01-20

it should be

https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1581-2022-01-19

**Comment by Urgau** [comment]
Well now it should be: https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1590-2022-02-24

The is also a rendering issue with `unreachable!` not being a link due to an incorrect markdown:
![](https://puu.sh/IKY6P/0eb9f1532c.png)

cc @Mark-Simulacrum (for the release team)

**Comment by Mark-Simulacrum** [comment]
Since the announcement was made on the 20th, it probably makes sense to edit the release notes instead of the blog post.

The compatibility notes would indeed be nice to adjust, but I'm not likely to have another stable build in the next ~24 hours before a release, so we'll leave that for an upcoming forward-port to master.
