### ISSUE TITLE
Provide rust-lld on s390x (for the wasm target)

### ISSUE THREAD

**Issue by uweigand** [rust-lang/rust#94324]
Trying to build for the `wasm32-unknown-unknown` target on a s390x host fails with:
```
  `rust-lld` not found, please install it!
```

This seems to be because - unlike on other architectures - `rust-lld` is not built and packaged as part of the rust toolchain.

Now, it is true that LLD currently does not support the s390x architecture.  But that is only an issue when trying to use the s390x architecture as **target** - it is completely fine to build LLD on a s390x host and use it to link binaries for any **other** target architecture it supports, in particular including wasm.

Would it be possible to include `rust-lld` on s390x as well, to make building wasm binaries more straightforward?

**Comment by nikic** [comment]
I believe we don't build lld for most non-x86 hosts, though I don't see any particular issue with including it. I think all it would take is an `--enable-lld` in https://github.com/rust-lang/rust/blob/4b043faba34ccc053a4d0110634c323f6c03765e/src/ci/docker/host-x86_64/dist-s390x-linux/Dockerfile#L40

**Comment by Mark-Simulacrum** [comment]
Yep, if CI passes with it added it's generally fine to do so for tier 2 with host tools targets (or better), though it may get removed if it causes undue CI time burden (unlikely).

**Comment by uweigand** [comment]
Thanks for the comments!   Would you like me to submit a PR adding the `--enable-lld` flag as described above?  (I'm not really familiar with how the automated builds work, so I'm not sure how to verify this works correctly ...)

**Comment by nikic** [comment]
Normally, you'd be able to verify using `sudo src/ci/docker/run.sh dist-s390x-linux`. However, it's not possible to actually build this docker image anymore, due to the Ubuntu 16.04 certificate expiration issue. And unfortunately, this one doesn't upgrade to Ubuntu 20.04 cleanly, because it's on make 3 + old crosstool-ng. It would be nice to upgrade it, but probably this workaround would work in the meantime: https://github.com/rust-lang/rust/blob/4b043faba34ccc053a4d0110634c323f6c03765e/src/ci/docker/host-x86_64/dist-aarch64-linux/Dockerfile#L1-L14

**Comment by uweigand** [comment]
OK, I'll give it a try.

As an aside, Ubuntu 20.04 contains a full cross-toolchain targeting s390x out of the box, so I'm not sure we'd really need crosstool-ng at all - unless there's a particular reason the Rust build requires it?

However, if we update this to Ubuntu 20.04, would this have the side effect that the generated Rust toolchains would no longer install on older distros?   We really don't want that.
