### ISSUE TITLE
compiletest's 'SKIPPED 246746 BYTES' logic breaks tests

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#94322]
`src/tools/compiletest` truncates large outputs by replacing the middle by `<<<<<< SKIPPED {} BYTES >>>>>>`:

https://github.com/rust-lang/rust/blob/7ccfe2ff1d59666dc0188dfd5847304fec257565/src/tools/compiletest/src/read2.rs#L52

This can break the test runner which tries to parse the output as json, which will break on the `<<< .. >>>` message. For example here: https://github.com/rust-lang/rust/runs/4586149338?check_suite_focus=true:

```
thread '[ui] ui/suggestions/missing-lifetime-specifier.rs' panicked at 'explicit panic', src/tools/compiletest/src/json.rs:121:21
```

This is blocking https://github.com/rust-lang/rust/pull/92123 (A workaround for this PR could be to simply increase the threshold, but we should probably have a better solution.)

**Comment by Aaron1011** [comment]
See also https://github.com/rust-lang/rust/issues/92211

**Comment by Mark-Simulacrum** [comment]
#94327 should help with this specific instance, though is not a root cause fix. In general limiting the number of JSON bytes is a pretty poor estimate of the number of bytes in stderr files; it might make sense to avoid the abbreviated read abstraction for that part of compiletest. (Or, at least, set the limit to a few megabytes or so).
