### ISSUE TITLE
Unneccessary error

### ISSUE THREAD

**Issue by tema3210** [rust-lang/rust#94422]
I have the following snipset:
```
impl<'h,S: System<'h,Host> + Any> typemap::Key for S {
        type Value = SystemData<'h,S>;
}
```
The current stable gives me:
```
error[E0207]: the lifetime parameter `'h` is not constrained by the impl trait, self type, or predicates
  --> src\app\host_impls.rs:31:10
   |
31 |     impl<'h,S: System<'h,Host> + Any> typemap::Key for S {
   |          ^^ unconstrained lifetime parameter
```
the `System<...>` trait has a `'static` supertrait bound;

The point is that the `typemap::Key` trait is intended as type level function (of `* -> *` kind) and because of this error my code doesn't compile.

Can we define there an additional behavior like "usage of lifetime parameter in associated type constrains it"?

**Comment by wwylele** [comment]
I don't think this would work in the way you want. (non-generic) associated type is like the output of the type function defined by the trait implementation. It reads like "The function `typemap::Key` of `S` outputs the `Value = SystemData`". This is what distinguished associated type from a type parameter in trait (the type parameter would be the input of the type function). As an output, the associated type should have one defined "value" (type), instead of "for any `'h`" 

Maybe what you want is generic associated type (making it a type function itself), which makes `typemap::Key` a higher order type function.

**Comment by tema3210** [comment]
Like, can't we take this:
```
impl<'h,S: System<'h,Host> + Any> typemap::Key for S {
        type Value = SystemData<'h,S>;
}
```
as this:
`for<'h> for<S: ...> exists< Value = SystemData<'h,S> >`
?
;Here, two terms are introduced, two terms are used - no reason for error I guess.

**Comment by wwylele** [comment]
I think the direct translation of that is making `'h` an input of the type function. e.g. making it part of the trait generic `impl<...> typemap::Key<'h> for S`

**Comment by jyn514** [comment]
This looks like a fairly fundamental change to the language. The issue tracker is not an effective way to get feedback on language changes; consider instead posting on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122651-general) or [internals.rust-lang.org](https://internals.rust-lang.org/).
