### ISSUE TITLE
doctest regression in Rust 1.59.0.  doctest seems to be incorrectly triggered by 4 spaces inside comment.

### ISSUE THREAD

**Issue by bvinc** [rust-lang/rust#94757]
Playground link:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=49cbbdbc31452b20822c8753c67a13d3

### Code

I tried this code:

```rust
/// Some ascii art documentation
///  7 6 5 4 3 2 1 0
/// +-+-+-+-+-+-+-+-+
/// |               |
/// +     AB CD     +
/// |               |
/// +-+-+-+-+-+-+-+-+
pub struct SomeNetworkHeader;
```

I expected to see this happen: tests pass because there are no tests

Instead, this happened: A doctest fails with the following error

```
test src/lib.rs - SomeNetworkHeader (line 5) ... FAILED

failures:

---- src/lib.rs - SomeNetworkHeader (line 5) stdout ----
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `CD`
 --> src/lib.rs:6:4
  |
3 | AB CD     +
  |    ^^ expected one of 8 possible tokens

error: aborting due to previous error

Couldn't compile the test.

failures:
    src/lib.rs - SomeNetworkHeader (line 5)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.15s
```

### Version it worked on

It most recently worked on: I believe it worked on 1.58.0

### Version with regression

rust 1.59.0

**Comment by GuillaumeGomez** [comment]
It's not a bug. Try it [here](https://spec.commonmark.org/dingus/?text=Some%20ascii%20art%20documentation%0A%207%206%205%204%203%202%201%200%0A%2B-%2B-%2B-%2B-%2B-%2B-%2B-%2B-%2B%0A%7C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%2B%20%20%20%20%20AB%20CD%20%20%20%20%20%2B%0A%7C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%2B-%2B-%2B-%2B-%2B-%2B-%2B-%2B-%2B). The problem is that `+` starts a list and the indent behind it makes the text recognized as a code block. If you want to do ascii art, wrap it in a code block:

```rust
/// Some ascii art documentation
///  7 6 5 4 3 2 1 0
/// ```ascii
/// +-+-+-+-+-+-+-+-+
/// |               |
/// +     AB CD     +
/// |               |
/// +-+-+-+-+-+-+-+-+
/// ```
```

**Comment by bvinc** [comment]
I considered it clearly a bug because code that compiled previously no longer compiles with Rust 1.59.0.

Where can I find information about `+` starting a list?  What kind of list?

**Comment by GuillaumeGomez** [comment]
It's in the commonmark spec. I linked you the dingus but you can see the spec from the same website.

**Comment by apiraino** [comment]
> I considered it clearly a bug because code that compiled previously no longer compiles with Rust 1.59.0.

I think the source of confusion is that the commonmark library used (pulldown-cmark) was updated (perhaps in https://github.com/rust-lang/rust/commit/ecd39aae0ea07271181978494391c19e26bcb29b) and the linting/validation improved accordingly, now respecting more closely the spec, hence the new error correctly reported.
