### ISSUE TITLE
Add version header to -Zno-link .rlink files

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#95297]
This allows giving a better error when attempting to use the original source file with -Zlink-only rather than crashing and allows rejecting rlink files produced by a different rustc version.

**Comment by Kobzol** [comment]
@nnethercote I tried to look at this. `CodegenResults` is a struct that is serialized to `.rlink` files using the `Encodable/Decodable` machinery. I tried to create a wrapper struct that would serialize and deserialize a header to provide nicer messages, but it's not really easy to provide a custom message if decoding of the header fails currently, since you removed the `Result`s from `Decoder` methods :sweat_smile:

I see several solutions to this:
1) Catch panic that could be caused by invalid decoding of the header and provide a nicer message in that case (seems dubious).
2) Implement serialization and deserialization of the header using manual byte writes/reads, going around the `Encodable/Decodable` traits.
3) Return `Result` sto `Decoder` methods (probably not worth it because of this).

What do you suggest, solution 2)?

**Comment by bjorn3** [comment]
The crate metadata encodes and decodes the header separately from the contents. For crate metadata the header is of the form "rust" + 32bit be version number (currently 5 I believe) + 32bit offset of the crate root + rustc version string. During decoding the header is checked for "rust", the right version number and then the right rustc version. Only after that is a `Decoder` created to decode the contents.

https://github.com/rust-lang/rust/blob/07a461ad52b8485b184397b453b5436c70f9f460/compiler/rustc_metadata/src/rmeta/encoder.rs#L2173-L2177

https://github.com/rust-lang/rust/blob/07a461ad52b8485b184397b453b5436c70f9f460/compiler/rustc_metadata/src/rmeta/encoder.rs#L2201-L2202

The rlink header could work the same way except omitting the offset of the crate root and using say "rsld" (rust ld) or "rustlink" as start instead of "rust" like the crate metadata.

**Comment by Kobzol** [comment]
Thanks for the hint. I checked rmeta decoding and it basically decodes the magic header byte slice with `starts_with`, which should be easy, but then it uses `Lazy::<String>::decode` for decoding the rustc version, which will panic if the version is missing.

So with this approach we could have a nice error if header magic is missing, nice error if rust version is wrong, but weird error if rust version if missing. That is basically the same that we get for `rmeta` parsing, so I suppose that's ok?

**Comment by bjorn3** [comment]
> So with this approach we could have a nice error if header magic is missing, nice error if rust version is wrong, but weird error if rust version if missing.

Yeah, the header magic is supposed to be changed every time the rustc version needs to be decoded in a different way.

> That is basically the same that we get for rmeta parsing, so I suppose that's ok?

IMO it is ok.
