### ISSUE TITLE
Bug with associated type discovery

### ISSUE THREAD

**Issue by tema3210** [rust-lang/rust#95413]
I tried this code [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d0051a1af2b80b2828c669eb5265098c)

I expected to see this happen: resolve associated types and compile

Instead, this happened: visibility error with strange, broken suggestions

**Comment by SNCPlay42** [comment]
[Reduced some](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7240f031595c3dd9ebc16e548e62af01):

```rust
mod A {
    pub trait Trait {}
}

mod B {
    struct A<H: A::Trait>(H);
}
```

Which emits (ignoring the extra suggestion from a crate visible to the playground):

```
error[E0405]: cannot find trait `Trait` in `A`
 --> src/lib.rs:6:20
  |
6 |     struct A<H: A::Trait>(H);
  |                    ^^^^^ not found in `A`
  |
help: consider importing one of these items
  |
6 |     use crate::A::Trait;
  |

```

The *error* is correct - in `mod B` `A` refers to `struct A` itself, which has no associated item called `Trait`.

The *suggestion* is invalid - whether `Trait` is imported in the current module has no effect on the path `A::Trait`.

(Note that the playground's click-to-insert-`use`-statement feature also inserts the suggestion in the wrong position - at the top of the file instead of in `mod B` - which isn't a compiler issue.)

@rustbot label A-diagnostics A-resolve A-associated-items D-confusing D-invalid-suggestion
