### ISSUE TITLE
Adding private imports to a module can break downstream crates

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#95420]
I tried this code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7a55c241c30f1231a2711260adc95d22

```rust
mod a {
    pub type Result<T> = std::result::Result<T, ()>;
}

mod inner {
    pub use crate::a::*;
    use std::result::Result;
}

fn f() -> inner::Result<i32> {
    Ok(1)
}
```

I expected to see this happen: The code compiles fine, because `inner::Result` resolves to `a::Result`, just as it would without `use std::result::Result`.

Instead, this happened:
```rust
error[E0603]: enum import `Result` is private
   --> src/lib.rs:10:18
    |
10  | fn f() -> inner::Result<i32> {
    |                  ^^^^^^ private enum import
    |
note: the enum import `Result` is defined here...
   --> src/lib.rs:7:9
    |
7   |     use std::result::Result;
    |         ^^^^^^^^^^^^^^^^^^^
note: ...and refers to the enum `Result` which is defined here
```

### Meta

`rustc --version --verbose`:
```
1.59.0
```

I don't know if this is strictly a bug in the sense that it will break things, but it seems like an unfortunate side effect of the resolution rules ... cc @petrochenkov, do you have opinions on this?

**Comment by memoryruins** [comment]
I've seen this used before as an intentional way to hide items from `pub use` globs (for lack of a special syntax for hiding from globs) and have suggested it to someone else before (heh), which is something that a crater run might not catch if this was changed.

Curious about how long it's worked this way, before `1.15` it would error with "a type named `Result` has already been imported in this module", but `1.15` onward, [RFC 1560](https://github.com/rust-lang/rfcs/blob/master/text/1560-name-resolution.md) was stabilized. The current behavior appears to fall under the ["Explicit names may shadow implicit names"](https://github.com/rust-lang/rfcs/blob/master/text/1560-name-resolution.md#explicit-names-may-shadow-implicit-names) section. Although the section doesn't feature an example of importing from the same module, we can think of it similarly: the second `use` is the explicit import that shadows the glob's import of the item (so it uses explicit import's visibility).

In that sense, I do not think this is a bug, though I understand why it seems surprising at first.
