### ISSUE TITLE
use information about non-raw pointers being non-null

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#9546]
We can set this in arbitrary metadata, and then write an LLVM pass to consume it and mark them as non-null.

This is awful:

``` rust
pub fn foo(x: &int) -> bool {
    Some(x) == None
}
```

``` llvm
; Function Attrs: nounwind readonly uwtable
define i8 @_ZN3foo19h6e99b0040329bc59af4v0.0E({ i64, %tydesc*, i8*, i8*, i8 }* nocapture readnone, i64*) unnamed_addr #0 {
entry-block:
  %2 = icmp eq i64* %1, null
  %. = zext i1 %2 to i8
  ret i8 %.
}
```

**Comment by rkruppe** [comment]
I believe this issue should be closed. It's vague, and despite this vagueness addressed as much as we can hope to without fundamentally altering LLVM:

1. The example at the top is (still) optimized to a constant `false`.
2. We do emit `deferencable` attributes (which implies non-null) for function arguments and return values (at least when passed as immediates).
3. We emit `!nonnull` metadata on instructions that load a reference from memory. This covers arguments and return values not covered by the previous point (including aggregates that contain references), and also most locals, which are mostly codegen'd as stack slots that are loaded from on use.
4. We don't seem have any such metadata or attributes for SSA temporaries, but this is because LLVM doesn't have a good way to express those. There's `assume` but AFAIK we are deliberately conservative with those because they can cause performance regressions. LLVM also generally doesn't introduce assumes when it turns a stack slot with `!nonnull` loads into SSA values. It just loses the information.

[(playground for testing)](https://play.rust-lang.org/?gist=815be443c788834c1290d8356242d6e9&version=stable)

I'll also point out that non-nullness of references is a special case of communicating invalid values to LLVM. For example, that references are always aligned or that `bool` is 0 or 1. The latter is addressed with `!range` metadata on loads IIRC.
