### ISSUE TITLE
[strict provenance] make the compiler's tagged_ptr stuff conform

### ISSUE THREAD

**Issue by Gankra** [rust-lang/rust#95493]
This issue is part of the Strict Provenance Experiment - https://github.com/rust-lang/rust/issues/95228

tagged_ptr and everything that uses it is entirely provenance crimes

https://github.com/rust-lang/rust/blob/bb5c437a2ce9ccf2204c974300c5ea9eb32d3635/compiler/rustc_data_structures/src/tagged_ptr.rs#L52-L60

This is the precise point in updating std+compiler to conform to strict-provenance that I ran out of energy and just started marking the compiler as WONTFIX for the MVP. I believe @eddyb started working on this, but got a bit sidetracked because they ran into the fact that we're shifting pointers down so that we can high-bit-tag instead of low-bit-tag, and while this isn't *per-se* a problem for strict-provenance, it wasn't obviously portable to CHERI, which sucks.

Since then it's been clarified that e.g. Morello (CHERI on ARM) actually has allowances for high-bit tagging *and* pointer shifting, so it's possible that the code can just be changed to properly use pointers and `with_addr` and friends.

**Comment by HKalbasi** [comment]
Fixed by #110243 ?

**Comment by RalfJung** [comment]
Yes seems like it. :)

@WaffleLapkin do you know other places in the compiler that are still using "fuzzy provenance casts"?

**Comment by WaffleLapkin** [comment]
@RalfJung There are still https://github.com/rust-lang/rust/blob/92ad4b433a00852341019ad592ba9dfce17e9214/compiler/rustc_middle/src/ty/generic_args.rs#L34 https://github.com/rust-lang/rust/blob/92ad4b433a00852341019ad592ba9dfce17e9214/compiler/rustc_middle/src/ty/mod.rs#L846

I swear I was meaning to fix them... Maybe I forgot to open a PR? Will try to dig for it/write a new one.

Either way besides those two I don't remember and can't find any int2ptr casts in the compiler. Closing this as fixed by https://github.com/rust-lang/rust/pull/110243.

**Comment by RalfJung** [comment]
@WaffleLapkin are we tracking those last two somewhere?

**Comment by WaffleLapkin** [comment]
@RalfJung not to my knowledge, I can open an issue though

**Comment by WaffleLapkin** [comment]
For the record I've opened https://github.com/rust-lang/rust/issues/119217
