### ISSUE TITLE
[NLL] Poor spans for mismatched types

### ISSUE THREAD

**Issue by jackh726** [rust-lang/rust#95686]
The `src/test/ui/rfc1623.rs` test currently gives objectively worse output spans under NLL. Specifically, without NLL, we point to the specific field that isn't general enough. With NLL, we point at the outer struct creation.

Relevant excerpt with error labels:
```rust
struct SomeStruct<'x, 'y, 'z: 'x> {
    foo: &'x Foo<'z>,
    bar: &'x Bar<'z>,
    f: &'y dyn for<'a, 'b> Fn(&'a Foo<'b>) -> &'a Foo<'b>,
}
fn id<T>(t: T) -> T {
    t
}
static SOME_STRUCT: &SomeStruct = &SomeStruct {
    //[nll]~^ ERROR mismatched types
    //[nll]~| ERROR mismatched types
    //[nll]~| ERROR implementation of `FnOnce` is not general enough
    //[nll]~| ERROR implementation of `FnOnce` is not general enough
    foo: &Foo { bools: &[false, true] },
    bar: &Bar { bools: &[true, true] },
    f: &id,
    //[base]~^ ERROR implementation of `FnOnce` is not general enough
};
```

**Comment by Aaron1011** [comment]
This is caused by the way that we handle region constraints for promoteds. We change the location of all constraints to point to the location of the promoted: https://github.com/rust-lang/rust/blob/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/compiler/rustc_borrowck/src/type_check/mod.rs#L641-L644

However, the location is used for both borrow-checking and diagnostics. As a result, any errors that get 'blamed' on a promoted will have the span of the entire promoted. We should track the span separately from the location, so that we can adjust the (semantic) location and diagnostic span separately.

**Comment by jackh726** [comment]
Span here is better thanks to #96236. Now just a nearly duplicate error, which we can track in #96211.
