### ISSUE TITLE
"cannot construct with struct literal syntax due to inaccessible fields" could use an explain

### ISSUE THREAD

**Issue by QuineDot** [rust-lang/rust#95872]
[Given the following code:](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9f3e3c29a1dd0db9008d9683c108b330)
```rust
pub mod m {
    pub struct S {
        pub visible: bool,
        private: (),
        also_private: String,
    }
}

fn main() {
    let _ = m::S {
        visible: true,
        private: (),
    };
}
```

The current output is:
```
error: cannot construct `S` with struct literal syntax due to inaccessible fields
  [--> src/main.rs:10:13
](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9f3e3c29a1dd0db9008d9683c108b330#)   |
10 |     let _ = m::S {
   |             ^^^^
```

Ideally, the output should
* Explain more fully that there are private fields, perhaps via `--explain`
* [Not occlude E0451](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f5d9f7df78f71cb78471136384c92805) when some private fields are supplied (as in the above example)

In my opinion, the errors when you supply all the private fields are more understandable than those when you supply none or only some of the private fields.  See also [this URLO thread.](https://users.rust-lang.org/t/error-cannot-construct-animatedsprite-with-struct-literal-syntax-due-to-inaccessible-fields/74026)

I believe the current output is a result of #87872.

**Comment by compiler-errors** [comment]
I also agree that this seems like a regression. 

1. Firstly, I think that the word "inaccessible" is vague. I think "private" is pretty standard Rust terminology.
2. In both cases (where all fields are provided, even the provided ones, and when some are missing) we sould probably continue to mention that the struct can't be constructed due to private fields
3. In the case that not all private fields are provided, but some are, we should at least point at which ones _are_ private.

**Comment by lionellloh** [comment]
Hi @hadrizi are you still working on this?
