### ISSUE TITLE
regex should be part of the standard library and many others !

### ISSUE THREAD

**Issue by thechampagne** [rust-lang/rust#96338]
I believe that regex and many other crates should be native, e.g., `http client`. I heard that  the standard library supposed to be minimal but, come on 😐 I don't want to use 1 crate and end up with tens of dependencies of a "thing" that should be native.

**Comment by gimbles** [comment]
A dependency is simply a library shared between developers.

The standard library itself is also a dependency. Adding networking and regex utilities into the standard library would not "reduce" dependencies.

It'll just shift them from crate registries [crates.io] to the mainstream std.

> that should be native

Normal dependencies are just as native as the standard library my friend 😄

**Comment by thechampagne** [comment]
> Normal dependencies are just as native as the standard library my friend 😄

native means here, `part of the standard library`.

I'm aware that `would not "reduce" dependencies.` but such a utilities should be included into the standard library for its importance.

**Comment by SkiFire13** [comment]
This is not the first time that this question came up and a quick google search should give you tons of results. See for example:

- https://internals.rust-lang.org/t/expansion-of-standard-library/10475
- https://blog.nindalf.com/posts/rust-stdlib/
- https://www.reddit.com/r/rust/comments/gyyw80/does_anyone_feel_rusts_std_library_isnt_as/

just to name a few, but there are many others.

To sum up some of the common problems:
- this add dependencies, not reduce them, because now everyone depends on those features, even if they don't use them;
- it's really really hard to decide which design the stdlib should pick for those features;
- once added they can't change, as opposed to libraries which can just bump their major version and introduce breaking change.

As a common example, `python`'s stdlib has both a `liburl` and a `liburl2` package, and they're both discouraged in favour of `requests` , which has its own internal `liburl3`. Whatever proposal to add more features to our stdlib should provide a plan to avoid similar situations. Just look at the pain with our current `std::sync::mpsc` module, which has a suboptimal API and longstanding implementation issues. 

So, do you have something to add to those discussions?

**Comment by thechampagne** [comment]
**I'm hoping that it could be rich as golang standard library** 👀

**Comment by MultisampledNight** [comment]
How important something is depends on the view, unfortunately. For example, let's take the HTTP request. Somebody writing a desktop client for an app might find it useful — but for everyone else, people writing software for the embedded, WASM and computational domains for example, it's a huge load of unnecessary compile time and also toolchain size.

**Comment by nagisa** [comment]
Closing, as this is not the right venue to have this discussion. A proposal of this scope [warrants an RFC](https://github.com/rust-lang/rfcs#when-you-need-to-follow-this-process). If you think you have an idea on how to approach including such functionality to the standard library, I suggest you to submit an RFC. Otherwise I don't really see how this can be actionable given the outcome of the previous discussions.

**Comment by gimbles** [comment]
Late to the party, but this will push people into a single HTTP(S) client, while the person might benefit from using another crate depending on their use-case.

For eg. For size-efficient and sync tasks, `ureq` is a much better option than the fatter `reqwest`.

But when you're not in size constraints and want to perform concurrent requests, `reqwest` is a much more suitable option 

Diversity in the HTTP(S) clients in the overall Rust ecosystem might be affected a lot, as people will be pushed into "Use the std one"

https://lib.rs/web-programming/http-client

The `lib.rs` page for http(s) clients also elaborates on this point, on just how many different crates there are, a lot of them suitable for a unique use-case.

I only elaborate on the HTTP(S) clients part here, but my point also applies on stuff like regex engines in the standard library
