### ISSUE TITLE
rust complains about "const fn" which was never declared as such

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#97082]
Given the following code: 

```rust
fn f() { dbg!(); }
static A: fn() = f;
static B: () = A();

fn main() {
    println!("Hello, world!");
    B
}
```

The current output is:

```
error: function pointers are not allowed in const fn
 --> src/main.rs:3:16
  |
3 | static B: () = A();
  |                ^^^

error: could not compile `f` due to previous error
```

IMO it's a bit weird that rust tells me about a "const fn" since there is none in the code snippet...? :sweat_smile:

**Comment by mbartlett21** [comment]
@rustbot claim

Here's the relevant code:

https://github.com/rust-lang/rust/blob/f001f9301c889101d8a71358b64b96e9707c832b/compiler/rustc_const_eval/src/transform/check_consts/ops.rs#L85-L94

But then saying that function pointers aren't allowed in statics is just false, since there is a function pointer assigned to `A`.

**Comment by mbartlett21** [comment]
Note: The error message is now "function pointer calls are not allowed in statics"
