### ISSUE TITLE
pub use std::sys;

### ISSUE THREAD

**Issue by mrMiiao** [rust-lang/rust#97148]
Hi! Probably my opinion is wrong. I’ll share it with you though. I think making an unstable feature for using std::sys as public module is a good idea. Really! Such a good wrapper around OS, safe or unsafe, could be very useful for optimizations.

**Comment by the8472** [comment]
Closing on the same grounds as #97151

If you need *specific functionality*, such as an abstraction around an OS feature please discuss on URLO](https://users.rust-lang.org/) (there may be existing crates covering your needs) or propose a more specific feature rather than exposing all std-internals.

"Could be very useful" is not sufficient explanation for us to understand what you need and it also sounds speculative.

**Comment by mrMiiao** [comment]
> Closing on the same grounds as #97151
> 
> If you need _specific functionality_, such as an abstraction around an OS feature please discuss on URLO](https://users.rust-lang.org/) (there may be existing crates covering your needs) or propose a more specific feature rather than exposing all std-internals.
> 
> "Could be very useful" is not sufficient explanation for us to understand what you need and it also sounds speculative.

Ok, ok. I understood. Thanks for explanation ;)
