### ISSUE TITLE
Error while path patching libc as one of rustc's dependencies

### ISSUE THREAD

**Issue by ZetaNumbers** [rust-lang/rust#97209]
https://github.com/rust-lang/libc/issues/2794

**Comment by ZetaNumbers** [comment]
This can be fixed with `deny-warnings = false` in the `config.toml`, but i am not sure i it not a problem.

**Comment by ZetaNumbers** [comment]
This is not an actual issue.

**Comment by ehuss** [comment]
Yea, this is normal behavior with a path dependency. Using a path enables warnings. `unused_macro_rules` is a new lint that is unknown to the current beta bootstrap compiler.  As soon as the bootstrap compiler is updated, the warning should go away.  You can do that locally with `./x.py run src/tools/bump-stage0`.  Alternatively, you can just allow the warnings, or modify your local copy of libc to not include that allow lint.

I posted https://github.com/rust-lang/rustc-dev-guide/pull/1354 since I've seen a few people get confused by this.
