### ISSUE TITLE
[feature(adt_const_params)] `Bar` doesn't derive both `PartialEq` and `Eq`

### ISSUE THREAD

**Issue by psionic12** [rust-lang/rust#97278]
I'v read [the issue](https://github.com/rust-lang/rust/issues/94661) and [the issue](https://github.com/rust-lang/rust/issues/76183), and it seems that neither is my case. 

rust version: rustc 1.62.0-nightly (a707f4010 2022-04-29)

I tried this code:

```rust
#![feature(adt_const_params)]

use std::sync::Arc;

#[derive(PartialEq, Eq)]
enum Bar {
    Bar(Arc<i32>)
}

fn test<const BAR: Bar>() {}
```

I expected to see this the code to be compiled, but it's not:
```
error[E0741]: `Bar` must be annotated with `#[derive(PartialEq, Eq)]` to be used as the type of a const parameter
  --> src\main.rs:16:20
   |
16 | fn test<const BAR: Bar>() {}
   |                    ^^^ `Bar` doesn't derive both `PartialEq` and `Eq`
```
My guess is that the type `Arc` doesn't implement `StructuralPartialEq`, and I tried to use the feature newtype to wrap around the `Arc`, but still not working

So is it a bug or is there some limitations? Is there anyway I can make my code compile?

**Comment by b-naber** [comment]
Yeah the reason why this doesn't compile is that `Arc` doesn't implement `StructuralPartialEq`. Tried to make the error message somewhat less confusing.

**Comment by b-naber** [comment]
My understanding is that `StructuralPartialEq` was introduced to ensure that pattern matching on constants works correctly.  A constant is structurally equal to another constant if their fields are structurally equal, where primitive types are structurally equal if they represent the same value. Note that if you derive `PartialEq` you get exactly that, structural equality, whereas if you manually implement `PartialEq` you don't necessarily get that (depending on your impl). There's more information in [RFC 1445](https://rust-lang.github.io/rfcs/1445-restrict-constants-in-patterns.html).

I'm not entirely sure, but I think this might all change once we introduce ValTrees (a new type-system representation for constant values) and are able to use them in pattern matching.

**Comment by clarfonthey** [comment]
`StructuralPartialEq` is basically required for any reasonable implementation of const generics, since it essentially lets the compiler treat the constants as opaque bit strings, which makes for easy table lookups, etc.

There's also the additional security implications where, if this weren't the case, the compiler would have to run any crate's code for arbitrary constants, whereas right now, crate code is only run directly for build scripts and proc macros. Even if we changed from `StructuralPartialEq` to some other trait like `Hash` or `Ord`, the problem of running crate code would still exist.
