### ISSUE TITLE
2 lines of identical codes, one compiled, one failed.

### ISSUE THREAD

**Issue by cqlangyi** [rust-lang/rust#97273]
I tried this code:

```rust
use std::{
    future::Future,
    pin::Pin,
    task::{Context, Poll},
    time::{Duration, SystemTime, Instant},
};
use tokio::time::sleep;
use tokio::time::Sleep;

#[tokio::main]
async fn main() {
    let fut = MyFuture::new();
    println!("Awaiting fut...");
    fut.await;
    println!("Awaiting fut... done!");
}

struct MyFuture {
    sleep: Pin<Box<Sleep>>,
    now:Instant,
}

impl MyFuture {
    fn new() -> Self {
        println!("MyFuture new() will be called, then go sleeping");
        Self {
            now: Instant::now(),
            sleep: Box::pin(sleep(Duration::from_secs(1))),
        }
    }

    fn now(&self) -> u128{
        self.now.elapsed().as_millis()
    }
}

impl Future for MyFuture {
    type Output = ();

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        println!("before sleep.poll(), {}", self.now());
        let sleep = Pin::new(&mut self.sleep);
        // println!("before sleep.poll(), {}", self.now());  // compile error(already borrowed as mutable)， AAA
        let poll = sleep.poll(cx);
        println!("after sleep.poll(), {}", self.now());        // compile OK,  BBB
        poll
    }
}
```

I expected to see this happen: 
'AAA' and 'BBB' line should both work or not.

Instead, this happened: 
'AAA' line failed to compile,
but 'BBB' line passed with no error.

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-pc-windows-msvc
release: 1.61.0
LLVM version: 14.0.0
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by cqlangyi** [comment]
compile error output:

`
   |
43 |         let sleep = Pin::new(&mut self.sleep);
   |                                   ---- mutable borrow occurs here    
44 |         /// this line would not compile, says self already borrowed as mutable,
45 |         println!("before sleep.poll(), {}", self.now());  // compile error
   |                                             ^^^^^^^^^^ immutable borrow occurs here...
48 |         let poll = sleep.poll(cx);
   |                    ----- mutable borrow later used here

For more information about this error, try `rustc --explain E0502`.       
warning: `lawsuits` (bin "pin-poll") generated 3 warnings
error: could not compile `lawsuits` due to previous error; 3 warnings emitted
`

**Comment by wwylele** [comment]
Rust is full of case where simply changing the location of a statement would result in error. This is the expected interaction with exclusive borrows. The same error can be reproduced in the following simple case

```rust
struct S {
    a: i32,
    b: i32,
}

fn f0(s: &mut S) {
    println!("{}", s.a); // OK
    let r = &mut s.a;
    println!("{}", s.a); // ERROR
    drop(r);
}
```
The second println results in error because it is in the middle when `r` is holding the exclusive borrow on the same object. 

However, rust can understand disjoint borrows 
```rust
fn f1(s: &mut S) {
    let r = &mut s.a;
    println!("{}", s.b); // OK, because the exclusive borrow was only on s.a
    drop(r);
}
```
This code can compile, because r only exclusively borrows `s.a`. Other fields of `s` is still accessible

The posted code in the issue also *looks like* disjoint borrow. 
```rust
        let sleep = Pin::new(&mut self.sleep); // borrows self.sleep
        println!("before sleep.poll(), {}", self.now());  // technically only access self.now
        let poll = sleep.poll(cx);
```

But it doesn't work for two reasons:

### 1. Rust cannot see through disjoint borrow via `Pin`
Note that `self` is not a simple reference but a `self: Pin<&mut Self>`. The line `&mut self.sleep` actually invokes `DerefMut` on `Pin`, which exclusively borrows the entire `self` instead of a field. And then it borrows *again* of that field. While `sleep` is around, the entire `self` is exclusively borrowed

Using the simplified example above, we can show an analogy. The following doesn't compile
```rust
fn f2(mut s: Pin<&mut S>) {
    let r = &mut s.a; // looks like a disjoint borrow, but actually the entire s is borrowed
    println!("{}", s.b); // ERROR, s is not accessible here
    drop(r);
}
```
But the following compiles
```rust
fn f3(mut s: Pin<&mut S>) {
    let sr = &mut *s; // explicitly invoke Pin's DerefMut first. sr exclusively borrows the entire s
    let r = &mut sr.a; // r only borrows sr.a
    println!("{}", sr.b); // OK, because only sr.a was borrowed. We can still access sr.b
    drop(r);
}
```

### 2. Rust cannot see through disjoint borrow via full-borrowing functions
Even without `Pin`, the code in the issue won't compile. This is because `self.now()`, while technically only accesses `self.now`, actually requests the borrow of the entire `self` as indicated in its signature `fn now(&self)`. Like the following example
```
fn g(s: &S) {
    println!("{}", s.b);
}

fn f4(s: &mut S) {
    let r = &mut s.a;
    g(s); // ERROR trying to borrow the entire s, while s.a is exclusively borrowed by r
    drop(r);
}
```

**Comment by cqlangyi** [comment]
@wwylele Big thank for the detailed lines!

but i still have 2 questions, any suggestions would be appreciated.

1. line 'BBB' same have the same context with line 'AAA', at least below
lines seem not showing any 'borrow finished' move.
```rust
        let sleep = Pin::new(&mut self.sleep);
        // println!("before sleep.poll(), {}", self.now());  // compile error(already borrowed as mutable)， AAA
        let poll = sleep.poll(cx);
```
2. is there any way i could access the 'now' field in above code snippet?

thanks a lot!

**Comment by wwylele** [comment]
line 'BBB' does *not* have the same context as line 'AAA'. The line AAA has the context where `self` is exclusively borrowed by `sleep` in the range established by `let sleep =...  ... sleep.poll`. 

I suggest not using github issue as a place to discuss developing using rust in general.

**Comment by cqlangyi** [comment]
appreciated for the quick reply.
get it a little bit.
now would close this issue.
