### ISSUE TITLE
rust sorting algorithm

### ISSUE THREAD

**Issue by mmajass** [rust-lang/rust#97353]
I cannot figure out if I am mistaken or if rust built-in sort() with randomly unsorted Vec with the length of higher than 20 (inspired by timsort) is in some cases around 2x slower than a naive implementation of quicksort using the first element as the pivot?

for example this input:

```
    let mut rng = rand::thread_rng();
    let range = Uniform::new(-30000, 30000);
    let mut unsorted: Vec<i32> = (0..1000).map(|_| rng.sample(&range)).collect();
```

with the supplied sort:

```
pub fn system_sort(input: &mut Vec<i32>, _start: usize, _len: usize) {
    input.sort();
}
```

will take an average of 20.154 us to run:

> system_sort/2           time:   [20.112 us 20.154 us 20.202 us]                           
Found 12 outliers among 100 measurements (12.00%)
  5 (5.00%) high mild
  7 (7.00%) high severe

But using the same input with a naive implementation of quicksort using first element as pivot:

```
fn partition(input: &mut Vec<i32>, start: usize, len: usize) -> usize {
    //use first element as pivot
    let pivot= input[start];

    //low index points to partitioned section
    let mut index_l = start + 1;
    for index in start + 1..len {
        //if element is lower than pivot, swap
        if input[index] < pivot {
            let temp = input[index];
            input[index] = input[index_l];
            input[index_l] = temp;
            index_l += 1;
        }
    }
    //swap pivot to correct position
    input[start] = input[index_l - 1];
    input[index_l - 1] = pivot;

    index_l - 1
}

pub fn quick_sort(input: &mut Vec<i32>, start: usize, len: usize) {
    if start < len {
        //get pivot position
        let pivot_position = partition(input, start, len);
        //sorting lower section
        quick_sort(input, start, pivot_position);
        //sorting higher section
        quick_sort(input, pivot_position + 1, len);

    }
} 
```

will take an average of  9.6085 us to run:

> quick_sort/2            time:   [9.4894 us 9.6085 us 9.7560 us]                          
Found 18 outliers among 100 measurements (18.00%)
  8 (8.00%) high mild
  10 (10.00%) high severe

I am aware that trying to sort sorted Vec instead of unsorted Vec will make a huge difference in favor of timsort. Is this the reason why timsort is preferred? Also, to my surprise, rust merge_sort uses unsafe internally.

[quicksort.rs.txt](https://github.com/rust-lang/rust/files/8762626/quicksort.rs.txt)

**Comment by joboet** [comment]
Timsort's performance on random data is always quite bad, as in fact is the case for all merge sorts. An efficient quicksort will always be faster, because the partitioning stage can be implemented [branch-free and can be pipelined better in the CPU](https://blog.reverberate.org/2020/05/29/hoares-rebuttal-bubble-sorts-comeback.html) (multiple elements can be partitioned at the same time). In this case your quicksort has an extra advantage, because as the data is random, the pivot is likely to be good. If the data were to be reversed, however, your implementation (really, any quicksort without fallbacks) would have $O(n^2)$ complexity, which is really slow.
Why does `std` use a merge sort then? Because stability is a good thing for the default sorting algorithm, so quicksort is not a candidate. Why timsort in particular? Because in practice, most data encountered will be sorted or almost sorted, in which case timsort excels (it was designed for these cases).

By the way, the standard library also has [`sort_unstable`](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.sort_unstable), which uses pdqsort (a modified quicksort) for cases where stability is not needed, which performs extremely fast in nearly all cases.

As for the existence of `unsafe`, it is impossible to implement a normal merge sort without `unsafe` in Rust, as elements will need to be copied to a temporary buffer for the merging process, and we don't want to needlessly impose a `Clone` bound when all that is happening is the reordering of data. In principle, in-place merges such as [block sort](https://en.wikipedia.org/wiki/Block_sort) can be implemented without `unsafe`, but they are quite slow, and do very much benefit from external buffers for smaller blocks. Even quicksort uses `unsafe` for performance, as for less than ca. 32 elements insertion sort is the best, which needs `unsafe` for efficient reordering of elements (though that could be eliminated with a sufficiently smart optimizer).

**Comment by mmajass** [comment]
Thank you for the thorough answer and links to interesting articles. I wish your answer could be added to the documentation for everyone to enjoy.
