### ISSUE TITLE
could not compile `core`

### ISSUE THREAD

**Issue by vierzehnbyte** [rust-lang/rust#97404]
**cargo build --target custom-target.json -Z build-std**

error: could not compile `core`

Caused by:
  process didn't exit successfully: `rustc --crate-name core --edition=2021 /home/ubuntu/.rustup/toolchains/nightly-2022-05-25-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=597d7cfb9e1953ce -C extra-filename=-597d7cfb9e1953ce --out-dir /home/ubuntu/Home/Desktop/projects/caiman/target/x86_64-unknown-caiman/release/deps --target /home/ubuntu/Home/Desktop/projects/caiman/x86_64-unknown-caiman.json -Z force-unstable-if-unmarked -L dependency=/home/ubuntu/Home/Desktop/projects/caiman/target/x86_64-unknown-caiman/release/deps -L dependency=/home/ubuntu/Home/Desktop/projects/caiman/target/release/deps --cap-lints allow` (signal: 9, SIGKILL: kill)

toolchain `nightly-2022-05-25-aarch64-unknown-linux-gnu`
`rustc 1.63.0-nightly`

but works fine on `nightly-2022-05-25-aarch64-apple-darwin`

**Comment by 5225225** [comment]
I can't reproduce this on my x86_64-unknown-linux-gnu target, I'm trying `cargo run -Zbuild-std --target x86_64-unknown-linux-gnu` on the `cargo init` hello world. I just did a rustup update and got a `rustc --version` of `rustc 1.63.0-nightly (76761db59 2022-05-24)`. So at least building the stdlib isn't failing.

Maybe it's to do with the custom target .json? Can you share that? (same for the code you're compiling, but if it's failing on core, the codebase might not matter).

**Comment by jyn514** [comment]
SIGKILL usually happens because you ran out of memory. Are you sure this a deterministic? If you run this 3 times on the old and new toolchain, does it have the same behavior each time?

**Comment by vierzehnbyte** [comment]
> I can't reproduce this on my x86_64-unknown-linux-gnu target, I'm trying `cargo run -Zbuild-std --target x86_64-unknown-linux-gnu` on the `cargo init` hello world. I just did a rustup update and got a `rustc --version` of `rustc 1.63.0-nightly (76761db59 2022-05-24)`. So at least building the stdlib isn't failing.
> 
> Maybe it's to do with the custom target .json? Can you share that? (same for the code you're compiling, but if it's failing on core, the codebase might not matter).

I repeated this with `aarch64-unknown-linux-gnu` target but still got this error.
i use multipass to run linux.

**Comment by vierzehnbyte** [comment]
> SIGKILL usually happens because you ran out of memory. Are you sure this a deterministic? If you run this 3 times on the old and new toolchain, does it have the same behavior each time?

I used `nightly-2021-05-25` channel and it compiled successfully!

**Comment by ShubhInfotech-Bhilai** [comment]
Hi 
I found this 
Some errors have detailed explanations: E0412, E0425.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `core` due to 17 previous errors

Caused by:
  process didn't exit successfully: `rustc --crate-name core --edition=2021 /home/shubh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=120 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C metadata=abd5eda11a42b3b1 -C extra-filename=-abd5eda11a42b3b1 --out-dir /home/shubh/myapp/myapp-ebpf/../target/bpfel-unknown-none/debug/deps --target bpfel-unknown-none -Z force-unstable-if-unmarked -L dependency=/home/shubh/myapp/myapp-ebpf/../target/bpfel-unknown-none/debug/deps -L dependency=/home/shubh/myapp/myapp-ebpf/../target/debug/deps --cap-lints allow` (exit status: 1)
thread 'main' panicked at 'assertion failed: status.success()', xtask/src/build_ebpf.rs:61:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Every configuration is as per documentation

**Comment by workingjubilee** [comment]
@Subhash-Pal I'm sorry, but your bug seems unrelated as it is for a different target. Please report it separately!
