### ISSUE TITLE
`unreachable!()` or `unimplemented!()` for consts

### ISSUE THREAD

**Issue by m-cat** [rust-lang/rust#97973]
# ISSUE

## Overview

I ran into a situation where it would have been really useful to have something like <title>. Specifically, we have a `GENESIS_TIMESTAMP` const in a blockchain we're building, but as the chain hasn't been launched we cannot define this const right now. We can't run the risk of adding a dummy value, and it is a pain to comment it out because there is some code that relies on it. I suppose the latter is the best solution, though.

Anyway, I'm not sure if something like <title> is currently possible, but it would be a neat extension of the concept of `unimplemented!()`.

## Current Behavior

```
error[E0080]: evaluation of constant value failed
  --> src/consensus/difficulty.rs:13:43
   |
13 | const GENESIS_TIMESTAMP: BlockTimestamp = unimplemented!(); // TODO
   |                                           ^^^^^^^^^^^^^^^^ the evaluated program panicked at 'not implemented', src/consensus/difficulty.rs:13:43
   |
   = note: this error originates in the macro `unimplemented` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by eggyal** [comment]
If you just want a placeholder then I suppose you could use [`compile_error!("TODO")`](https://doc.rust-lang.org/std/macro.compile_error.html), but obviously compilation will fail so it's not really gaining you anything over `unimplemented!()`.

If you just want compilation to succeed, then perhaps something like `unsafe { std::mem::MaybeUninit::new().assume_init() }` (but obviously it'd be UB to then actually use that constant).

If you want to use the constant in running code, then you'll need to construct a valid value for it even if it's just a dummy/default/placeholder value during development.

**Comment by eggyal** [comment]
This isn't straightforward, because constants are evaluated during compilation whereas you're after a language item whose evaluation can be deferred to runtime (such that not having a value would then panic).

The most similar thing to this in Rust today would probably be a constant of `Option` type, where you immediately unwrap the constant at every usage site.  You would then have:

```rust
const GENESIS_TIMESTAMP: Option<BlockTimestamp> = None;
```

Of course, once you have a real value, you could change the type of this constant to remove the `Option` and it should be a pretty straightforward refactoring to remove the unwrapping at the usage sites.

**Comment by m-cat** [comment]
Thanks @eggyal! That's a good explanation and I totally see why something like <title> doesn't really make sense. I like that solution - nice and simple. I'll go with that.

Cheers!
