### ISSUE TITLE
Unsoundness due to where clauses not checked for well-formedness

### ISSUE THREAD

**Issue by aliemjay** [rust-lang/rust#98117]
This code does pass:  ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4225e75d1514837fb4df4d35ee880f55))
```rust
trait Outlives<'a>: 'a {} // without `: 'a`, it fails as expected.

fn t_is_static<T>()
where
    &'static T: Outlives<'static>,
{
}
```
But according to [RFC 1214](https://github.com/rust-lang/rfcs/blob/master/text/1214-projections-lifetimes-and-wf.md) functions are responsible for checking the well-formedness of their own where clauses. So this should fail and require an explicit bound `T: 'static`.

Here is an exploit of this unsoundness: ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4839e77e4f4058b1790a1e5ecf3f653e))
```rust
trait Outlives<'a>: 'a {}
impl<'a, T> Outlives<'a> for &'a T {}

fn step2<T>(t: T) -> &'static str
where
    &'static T: Outlives<'static>,
    T: AsRef<str>,
{
    AsRef::as_ref(Box::leak(Box::new(t) as Box<dyn AsRef<str> + 'static>))
}

fn step1<T>(t: T) -> &'static str
where
    for<'a> &'a T: Outlives<'a>,
    T: AsRef<str>,
{
    step2(t)
}

fn main() {
    let s: &'static str = step1(&String::from("blah blah blah"));
    println!("{s}");
}
```

@rustbot label C-bug T-compiler T-types A-lifetimes I-unsound

**Comment by steffahn** [comment]
This works, too
```rs
use std::fmt::Display;

trait Static: 'static {}
impl<T> Static for &'static T {}

fn foo<T: Display>(x: T) -> Box<dyn Display>
where
    &'static T: Static,
{
    Box::new(x)
}

fn main() {
    let s = foo(&String::from("blah blah blah"));
    println!("{s}");
}
```

**Comment by eggyal** [comment]
Also, it's on stable (unlike #98095).

**Comment by steffahn** [comment]
Seems to compile since `1.14` (obviously without the `dyn` keyword, and without the `"{s}"`).

**Comment by compiler-errors** [comment]
@steffahn's minimized example is much easier to work with:

```rust
use std::fmt::Display;

trait Static: 'static {}
impl<T> Static for &'static T {}

fn foo<T: Display>(x: T) -> Box<dyn Display>
where
    &'static T: Static,
{
    Box::new(x)
}

fn main() {
    let s = foo(&String::from("blah blah blah"));
    println!("{}", s);
}
```

Somewhere we're throwing bounds on the floor that we should be checking. Which function is responsible for ultimately checking that `T: 'static` is really is a mess to keep track of, honestly.

I guess it's worthwhile nominating this for T-types discussion.

**Comment by Dylan-DPC** [comment]
Marking this as p-high based on the [discussion here](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2398117.20Unsoundness.20due.20to.20where.20clauses.20not.20checked.20for.20wel.E2.80.A6)

**Comment by steffahn** [comment]
> Discussed in [t-types meeting](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.E2.9C.94.20.2398117.20Unsoundness.20due.20to.20where.20clauses.20not.20checked.20for.2E.2E.2E).

This link points to the prioritization discussion @jackh726

**Comment by lcnr** [comment]
@rustbot claim

already working in the area and want to take a closer look at this specific issue

**Comment by lcnr** [comment]
Summarizing what's going wrong in the minimized example:
```rust
use std::fmt::Display;

trait Static: 'static {}
impl<T> Static for &'static T {}

fn foo<S: Display>(x: S) -> Box<dyn Display>
where
    &'static S: Static,
{
    Box::new(x)
}

fn main() {
    let s = foo(&String::from("blah blah blah"));
    println!("{}", s);
}
```
We check that where-clauses of items when wfchecking that item, we do not recheck the where-clauses when using it. We assume this to be sound as instantiating a binder should not remove WF.

We check that `&'static S: Static` is WF in the `param_env` of the function. After elaborating super trait bounds this environment contains a `&'static S: 'static` bound, which gets destructures to result in a `S: 'static` clause. When now checking whether `&'static S` is well-formed, we are able to use that bound.

When calling that function we never check that `&'static &'a String` is well-formed. When applying the impl we also assume that the `trait_ref` is well-formed, as that should have been checked by wfcheck of the function. However, wfcheck of the function relied on the elaborated `S: 'static` bound which never gets proven here.

I think this should generally be fixed by also proving super trait bounds when using an impl (which is already part of our coinduction approach). TODO: explain issue with outlives opt for references

**Comment by lcnr** [comment]
actually: we can already elaborate any region constraints on traits when applying an impl. We can't check super traits because that requires coinduction, but adding a `TypeOutlives` constraint should already be possible.
