### ISSUE TITLE
rustdoc renders deprecated label in ambiguous location

### ISSUE THREAD

**Issue by rossmacarthur** [rust-lang/rust#98231]
rustdoc renders labels like "Deprecated" next to items like functions which is very useful. However, it sometimes places it ambiguously below an item where you're not sure if it refers to the above item or the below item.

[See here](https://doc.rust-lang.org/nightly/std/env/index.html)

For example in the following screenshot it is not sure whether `std::env::home_dir` is deprecated or `std::env::join_paths`.

![image](https://user-images.githubusercontent.com/17109887/174442274-3b009944-bcef-4210-9629-64ff48f998c0.png)

I get the same behaviour in both Firefox 101.0.1 and Chrome 102.0.5005.115. I'm on macOS.

Interestingly the column overflow behaviour for small screens and mobile is much better. For example

![image](https://user-images.githubusercontent.com/17109887/174442396-c02776c0-6697-43a8-a547-16226e6cdf37.png)

@rustbot label +A-rustdoc-ui +T-rustdoc

**Comment by jsha** [comment]
Thanks for filing! This was done in https://github.com/rust-lang/rust/issues/86578 and https://github.com/rust-lang/rust/pull/86594 but I agree it's not great. I think the "Deprecated" / "Unix" / "Experimental" badge should be moved back to be on the right-hand side (in desktop layout). But if we choose not to do that or it turns out to be challenging, we can also make things better by setting a min-width for the left-hand column. What's happening here is that the column size is being set too narrow, which causes the "Deprecated" label to wrap.

**Comment by jsha** [comment]
Also related: https://github.com/rust-lang/rust/pull/85651. And /cc @dns2utf8

**Comment by rossmacarthur** [comment]
This looks fixed :)
