### ISSUE TITLE
Leak if using `slice::fill`

### ISSUE THREAD

**Issue by ZetaNumbers** [rust-lang/rust#98425]
I tried this code:

```rust
#[repr(transparent)]
#[derive(Clone, Debug, PartialEq, Eq)]
struct Foo(i32);

impl Drop for Foo {
    fn drop(&mut self) {
        println!("Drop: {self:?}")
    }
}

fn main() {
    let len = 4;
    let layout = std::alloc::Layout::array::<Vec<Foo>>(len).unwrap();
    let base = unsafe { std::alloc::alloc(layout) };
    assert!(!base.is_null());

    {
        let base = base.cast::<Vec<_>>();
        for i in 0..len {
            unsafe { base.add(i).write(vec![Foo(i as i32)]) };
        }
        let slice = unsafe { std::slice::from_raw_parts_mut(base, len) };

        for (i, v) in slice.iter().enumerate() {
            let foo = [Foo(i as i32)];
            assert_eq!(v, &foo);
            drop(foo);
        }

        println!("Fill start");
        slice.fill(Vec::new());
        // slice.fill_with(Vec::new);
        println!("Fill end");

        assert_eq!(slice, vec![Vec::new(); len]);
    }

    unsafe { std::alloc::dealloc(base, layout) };
}

```

I expected to see this happen: no leaks

Instead, this happened:

<details>
<summary>cargo valgrind run</summary>

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `/home/zeta/.cargo/bin/cargo-valgrind target/debug/miri-core-fill-leak`
Drop: Foo(0)
Drop: Foo(1)
Drop: Foo(2)
Drop: Foo(3)
Fill start
Drop: Foo(0)
Drop: Foo(1)
Drop: Foo(2)
Drop: Foo(3)
Fill end
       Error leaked 12 B in 3 blocks
        Info at malloc
             at alloc::alloc::alloc (alloc.rs:89)
             at alloc::alloc::Global::alloc_impl (alloc.rs:171)
             at <alloc::alloc::Global as core::alloc::Allocator>::allocate (alloc.rs:231)
             at alloc::alloc::exchange_malloc (alloc.rs:320)
             at miri_core_fill_leak::main (main.rs:20)
             at core::ops::function::FnOnce::call_once (function.rs:248)
             at std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:122)
             at std::rt::lang_start::{{closure}} (rt.rs:145)
             at std::rt::lang_start_internal (function.rs:280)
             at std::rt::lang_start (rt.rs:144)
             at main
     Summary Leaked 12 B total
```

</details>

<details>
<summary>cargo miri run</summary>

```
Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `/home/zeta/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri target/miri/x86_64-unknown-linux-gnu/debug/miri-core-fill-leak`
Drop: Foo(0)
Drop: Foo(1)
Drop: Foo(2)
Drop: Foo(3)
Fill start
Drop: Foo(0)
Drop: Foo(1)
Drop: Foo(2)
Drop: Foo(3)
Fill end
The following memory was leaked: alloc1840 (Rust heap, size: 4, align: 4) {
    00 00 00 00                                     │ ....
}
alloc1954 (Rust heap, size: 4, align: 4) {
    01 00 00 00                                     │ ....
}
alloc2068 (Rust heap, size: 4, align: 4) {
    02 00 00 00                                     │ ....
}

error: the evaluated program leaked memory

note: pass `-Zmiri-ignore-leaks` to disable this check

error: aborting due to previous error
```

</details>

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0-nightly (dc80ca78b 2022-06-21)
binary: rustc
commit-hash: dc80ca78b6ec2b6bba02560470347433bcd0bb3c
commit-date: 2022-06-21
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
```

Backtrace: N/A

**Comment by Kolsky** [comment]
@RalfJung it's probably not `forget` to blame this time. `slice::fill` should drop old contents, but new contents are put behind the pointer and `unsafe { std::ptr::drop_in_place(slice) };` is never called. It's a bit puzzling why miri/valgrind reported 3 leaks instead of 4 and fill_with seems to not report any, but `const fn Vec::new` is used in both cases. As oli-obk mentioned in other issue that was just closed, `fill` calls `clone_from`, whlist `fill_with` uses provided fn, so I view it as both see 1 const/3 runtime objects in first scenario and 4 const (no drop needed at all) in second.

**Comment by ZetaNumbers** [comment]
So basically `slice::fill` uses `Clone::clone_from`, which allows this scenario:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=34b369bae47417cdf9b7cc063c12202b

`slice::fill_with` on the other hand uses assignment

**Comment by ZetaNumbers** [comment]
I think this should be mentioned somewhere or something.

**Comment by the8472** [comment]
Well, this isn't specific to `slice::fill`. Anything that takes a `T: Clone` and has some existing storage lying around may end up calling `clone_from` instead of `clone`.

**Comment by oli-obk** [comment]
I think when there is a `Clone` bound, the function is allowed to use `clone_from` instead of `clone` + assign. It's irrelevant that `fill` is called at all, as Ralf said

> You are creating a bunch of vectors in base.add(i).write(vec![Foo(i as i32)])and store them in some raw memory that you allocated yourself (base)

this is the relevant part. You did leak 4 vectors, it just happens that 3 of them still had capacity. If you leak a vector, it's going to leak its memory.

The problem with going down the road of mentioning the precise algorithm of functions taking `Clone` arguments is that people may rely on that algorithm and changing it to be smarter (allocate less) or simpler would become a breaking change. We would have to add such a disclaimer to each and every function taking a `Clone` argument, when imo it's implicit that `Clone` arguments may use `Clone::clone_from`.

I don't think there's much actionable here, as I think adding more documentation to `Clone` would likely not have avoided this confusion. I was confused by the example, too, and it took a bit of debugging to find out what happened, so this is definitely confusing, but ultimately correct and expected.

**Comment by ZetaNumbers** [comment]
The funny thing is, i was trying to eliminate a leak using only safe code, by using `mem::take`. Then i tried to be smart and short with `slice::fill`, but this time it didn't work. I thought that was a bug and spend some time on poloshing example and trying to investigate it by myself.

The point of this story is to ask someone before you try to figure it out yourself.

**Comment by ZetaNumbers** [comment]
Let this issue be reference for anyone in the future struggling with this.
