### ISSUE TITLE
evaluation error hides "impl item missing" error

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#98629]
```rust
trait Trait {
    const N: usize;
}

impl Trait for i32 {}

fn f()
where
    [(); <i32 as Trait>::N]:,
{}

fn main() {}
```
results in
```
error[[E0080]](https://doc.rust-lang.org/nightly/error-index.html#E0080): evaluation of constant value failed
 --> src/main.rs:9:10
  |
9 |     [(); <i32 as Trait>::N]:,
  |          ^^^^^^^^^^^^^^^^^ referenced constant has errors
```
without showing that `N` is missing in the trait impl.

Taken from the comment by @carado in https://github.com/rust-lang/rust/issues/74713#issuecomment-882408859

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2398629.20evaluation.20error.20hides.20.22impl.20item.20missing.22.20error)).

The missing diagnostic message in this case can possibly make fixing the code *quite* confusing.

@rustbot label -I-prioritize +P-high

**Comment by compiler-errors** [comment]
Hi @TaKO8Ki, are you working on this issue? I've been keeping tabs on this one for a bit and I decided to look into it since it's been a few weeks.

I think I may have found a bug in the way that we resolve `const` items and I would like to put up a PR, unless you've already found a solution. :smile_cat:
