### ISSUE TITLE
HTML Documentation doesn't load locally-saved fonts in macOS Safari

### ISSUE THREAD

**Issue by kadiwa4** [rust-lang/rust#98769]
When viewing locally-saved documentation (`file:///`), rustdoc's output website isn't able to load in any of the woff2 fonts. Since #96279 removed the woff versions of the fonts, the browser defaults to other fonts, and it turns out Times and Menlo don't look great in combination.
Update: since #115904 (1.75.0), the bold version of Source Serif 4 is now used.

Version: macOS 12.4 / Safari 15.5 (still an issue in 17.2.1)
Rust/Rustdoc version: 1.62.0, works fine on 1.61.0

Workaround script: https://gist.github.com/kadiwa4/8e81b820217fdb8d1fb70e2108d1a58d

Web console:
```
[Error] Origin null is not allowed by Access-Control-Allow-Origin. Status code: 0
[Error] Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin. Status code: 0 (SourceSerif4-Regular.ttf.woff2, line 0)

... (repeated for other woff2 fonts)
```

<img width="1512" alt="Screenshot 2023-12-31 at 17 49 45" src="https://github.com/rust-lang/rust/assets/25464294/6f7756fb-e4be-4f85-ab21-7a0b3a268a20">

**Comment by jsha** [comment]
Thanks for the report! That's strange - I could imagine reasons why Safari might refuse to load fonts, but I can't think of why it would affect both woff and woff2.

Since I don't have a Safari handy at the moment, could you do me a favor - check what happens if you remove the `<link rel="preload"...` tags at the beginning of the document? Preloading interacts in interesting ways with CORS; and the preloads are sometimes rejected when viewing file:// URLs. I'm wondering if the rejected preload prevents Safari from later loading the font the regular way. In this theory, fallback to the woff files might have been masking the problem.

**Comment by kadiwa4** [comment]
To clarify: woff files work just fine (even in combination with woff2 files), but they aren't shipped with rustdoc anymore.

Indeed, removing the `<link>`s you mentioned gets the fonts to work again! As soon as it encounters one of those tags, it seems to "curse" that specific browser tab (it refuses to load the woff2 files ever again in that tab).

**Comment by jsha** [comment]
Thanks for testing that! That confirms my suspicion: the problem isn't woff vs woff2, but that the `<link rel="preload" ...>` causes Safari to load the woff2 font with the `crossorigin` attribute, which [is needed for preloading fonts](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#cors-enabled_fetches). But `crossorigin` doesn't really make sense for local files (`file:///` URLs). On Chrome and Firefox, when loading `file:///` URLs the preload just gets ignored, and when the CSS later gets loaded, the font is loaded from there without any CORS properties.

But I'm guessing on Safari something different is happening: the first fetch "poisons" the URL as you say, so even once the CSS is loaded, Safari's attempt to load that font URL fails. This worked when there was also a .woff file in the CSS, because the .woff file wasn't preloaded and so wasn't poisoned.

I think this is a bug in Safari and it would be good to file it and get it fixed.

Working around the bug in rustdoc could mean putting a small block of inline JS in the `<head>` that `document.write(..)`s the preload links only if the URL is not `file:///`. I would also be fine with temporarily reverting #96279 as a workaround.

**Comment by kadiwa4** [comment]
WebKit issue: <https://bugs.webkit.org/show_bug.cgi?id=249887>

**Comment by kadiwa4** [comment]
@jsha @notriddle Yes, I have it enabled

**Comment by kadiwa4** [comment]
#122410 fixes the issue for everyone who has dev tools enabled.

Issue #85444 is used to find a solution for the general case (with or without dev tools enabled).
