### ISSUE TITLE
`./x.py test tidy` should reject additions of new binary files

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/rust#98792]
It would be great if the `tidy` check rejected commits of binary files, such as what happened in #97488 (removed in #98791). Ideally we would have an allowlist of binary files in the repo, so people can't sneak in rogue binaries...

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/bins.rs is what attempts to check for this -- I'm investigating what went wrong with it.

I think the root cause is that we run tidy on src/, library/ and compiler/, but not any other directories as far as I can tell. That won't cover the root directory, which is obviously a problem. Investigating a fix to that now.
