### ISSUE TITLE
move keyword not right 

### ISSUE THREAD

**Issue by cole-dda** [rust-lang/rust#98865]
I tried this code:

```rust


struct A{
    x:i32
}
fn main(){
    
    let mut a = A{x:1};

    //test1
    //use move keyword,all captured variables are moved 
    let mut f = move ||{
        //not move,but copy
        //rust may be let a = A{..a} ??
        a.x=2;
    };

    f();
    //why a not droped?,a is live
    println!("a.x={}",a.x);


    //test2
    let mut a = A{x:1};
    let mut f = move ||{
        a.x=2;
        a;//add line,rust let a = a ?
    };

    f();

    //compile error,a moved
    //println!("a.x={}",a.x);

}
```

I expected to see this happen: *test1 variable "a" dropped*

Instead, this happened: *test1 variable "a" live*

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0 (a8314ef7d 2022-06-27)
binary: rustc
commit-hash: a8314ef7d0ec7b75c336af2c9857bfaf43002bfc
commit-date: 2022-06-27
host: x86_64-apple-darwin
release: 1.62.0
LLVM version: 14.0.5
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by ChayimFriedman2** [comment]
This is an expected outcome of [disjoint captures in closures](https://doc.rust-lang.org/edition-guide/rust-2021/disjoint-capture-in-closures.html).

**Comment by workingjubilee** [comment]
As the problem seems to be "something worked", and that something is an intentional feature of Rust, and it is very hard to even improve diagnostics for "something worked on purpose", as it is definitionally not erroneous and we should not emit errors for things that are not erroneous...

Well. My apologies if this is confusing. If you have any requests for improvement of the non-successful routes which do emit errors, then we can revisit this. Until then, I am closing this.
