### ISSUE TITLE
could not find native static library `boost_iostreams`, perhaps an -L flag is missing?

### ISSUE THREAD

**Issue by goldwind-ting** [rust-lang/rust#98875]
`build.rs`:
```rust
println!("cargo:rustc-link-lib=static=boost_iostreams");
println!("cargo:rustc-link-lib=static=boost_serialization");
```
rust:
rustc 1.62.0
ubuntu 20.04

when I compile the code, it shows that `could not find native static library boost_iostreams, perhaps an -L flag is missing?`, 
I have installed the boost by `sudo apt-get -y install libboost-all-dev`, the location is `/usr/lib/x86_64-linux-gnu/`.

**Comment by workingjubilee** [comment]
This issue currently does not show a bug with Rust. Perhaps you meant to ask for technical support on https://users.rust-lang.org or on StackOverflow?

I say this because the error message does seem to address your problem. I assume you actually used `cargo build` instead of invoking `rustc` directly. Does your `PATH` include `/usr/lib/x86_64-linux-gnu`? If it does not, you have to [use the `-L` flag to add to the search path](https://doc.rust-lang.org/rustc/command-line-arguments.html#-l-add-a-directory-to-the-library-search-path). If it does, then maaaybe we have a bug here.

**Comment by goldwind-ting** [comment]
okay
