### ISSUE TITLE
Enable eager checks for memory sanitizer

### ISSUE THREAD

**Issue by nikic** [rust-lang/rust#99179]
The memory sanitizer supports "eager checks", which will check initialization for noundef parameters and return values. It can be enabled by passing true as the fourth parameter to MemorySanitizerOptions. The corresponding clang option is `-fsanitize-memory-param-retval`. Not sure whether we need an option or can just unconditionally enable it.

**Comment by 5225225** [comment]
If there's not a big performance hit, and it just changes behavior, then I think we should just unconditionally enable it, saves people the hassle of needing to know to enable that flag in CI as well if you want the better checks.

In any case, I'll try and implement this, we can probably get away with not changing the rust code side at all, and just always passing `EagerChecks` to be `true`.

**Comment by 5225225** [comment]
Also, looks like we're not emitting `noundef` for parameters and return values, we're only doing it for loads. But if you enable optimisations, params and return values seem to *get* noundef (if they're of a type that we say is noundef, like `char`). Also, the test required `#[no_mangle]` on the function that created the undef value. That could just be because it's a rather artificial test case?

**Comment by nikic** [comment]
We do emit noundef attributes for params and returns -- maybe you're testing `opt-level=0`? Not sure which test case you are referring to here.

**Comment by 5225225** [comment]
What I don't get is *how*. Does noundef have no effect on unoptimised builds / is it ignored? (As in, in order to get the effect of memory sanitizer here, do you *have* to run an optimized build?)

I see that we have `scalar_load_metadata` that sets noundef metadata, is that used not just for loads, but also for parameters and returns? I can't see anywhere else that calls `noundef_metadata`.

https://github.com/rust-lang/rust/blob/95e8b86c8c0aba65b2b0065265ce6d82d5a2c285/compiler/rustc_codegen_llvm/src/builder.rs#L467-L488

**Comment by tmiasko** [comment]
Attributes should be configured somewhere around here:

https://github.com/rust-lang/rust/blob/95e8b86c8c0aba65b2b0065265ce6d82d5a2c285/compiler/rustc_codegen_llvm/src/abi.rs#L46-L52
https://github.com/rust-lang/rust/blob/95e8b86c8c0aba65b2b0065265ce6d82d5a2c285/compiler/rustc_codegen_llvm/src/abi.rs#L75-L93

**Comment by nikic** [comment]
> What I don't get is _how_. Does noundef have no effect on unoptimised builds / is it ignored? (As in, in order to get the effect of memory sanitizer here, do you _have_ to run an optimized build?)

They are not set as a compile-time optimization. It would be fine to always emit them with memory sanitizer, as they impact its behavior.

**Comment by 5225225** [comment]
Ahhh! Thank you!

So https://github.com/rust-lang/rust/blob/master/compiler/rustc_middle/src/ty/layout.rs#L3223-3226= is where noundef is given to params/return values with validity invariants. And yeah, we don't tell LLVM that anything is noundef if we have no opts on.

Maybe we should, but only if memory sanitizer is enabled? (or unconditionally?) Since it's giving msan information it needs. Not sure how many people run msan in CI and *don't* run it in release, but it seems non-obvious that you would need to.
