### ISSUE TITLE
1.62.0 build on Solaris fails with - error: `-Csplit-debuginfo` is unstable on this platfor

### ISSUE THREAD

**Issue by psumbera** [rust-lang/rust#99208]
While building Rust 1.62.0 on Solaris SPARC it fails with:

```
Building stage0 tool unstable-book-gen (sparcv9-sun-solaris)
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /builds/psumbera/RUST/solaris-userland/components/rust/rustc/rustc-1.62.0-src/src/tools/rls/racer/Cargo.toml
workspace: /builds/psumbera/RUST/solaris-userland/components/rust/rustc/rustc-1.62.0-src/Cargo.toml
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/builds/psumbera/RUST/solaris-userland/components/rust/rustc/build/sparcv9/build/bootstrap/debug/rustc - --crate-name ___ --print=file-names --cfg=bootstrap -Csymbol-mangling-version=v0 -Zmacro-backtrace -Clink-args=-Wl,-z,origin '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Csplit-debuginfo=off -Ztls-model=initial-exec --target sparcv9-sun-solaris --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
  --- stderr
  error: `-Csplit-debuginfo` is unstable on this platform

Build completed unsuccessfully in 0:00:03
```

**Comment by ehuss** [comment]
Looks like this was caused by #95612 (cc @davidtwco).  It looks like that also caused issues with openbsd (#96597), I'm wondering if it would make sense to audit which platforms were affected to make sure they are all addressed?

Passing `-Zunstable-options` seems like a somewhat blunt solution. I would expect it to not pass `-Csplit-debuginfo` if the target does not support it and the user did not specify it. That is roughly what [Cargo does](https://github.com/rust-lang/cargo/blob/82a8fb41949bc1852dd2e77f82c8ebab54c78e62/src/cargo/core/compiler/build_context/target_info.rs#L175-L180), though I suspect that might be not as easy to do in bootstrap.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2399208.201.2E62.2E0.20build.20on.20Solaris.20fails.20with.20-.20error.3A.20.60-Csplit.E2.80.A6)).

@rustbot label -I-prioritize +P-high
