### ISSUE TITLE
`core::mem::transmute` doesn't list `const` in the signature

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#99398]
`core::mem::transmute` and `std::mem::transmute` are **both** listed as const in 1.56 according to the "since" info on the right, but **only** the `std` version lists `const` in the actual signature.

core:
```
pub unsafe extern "rust-intrinsic" fn transmute<T, U>(e: T) -> U
```

std:
```
pub const unsafe extern "rust-intrinsic" fn transmute<T, U>(e: T) -> U
```

**Comment by GuillaumeGomez** [comment]
I took this screenshot in [stable docs](https://doc.rust-lang.org/stable/std/intrinsics/fn.transmute.html):

![image](https://user-images.githubusercontent.com/3050060/192143009-2162f0bb-8fa4-45cd-9bc2-d548c7f88839.png)

So it's fixed. Closing then.

**Comment by taiki-e** [comment]
@GuillaumeGomez  I don't think this has been fixed yet. (note that this issue is about `core`, not `std`)

https://doc.rust-lang.org/stable/core/intrinsics/fn.transmute.html

<img width="1009" alt="core" src="https://user-images.githubusercontent.com/43724913/192143225-9cccf71f-ba62-4d55-bae2-8ced7f5b1d41.png">

**Comment by GuillaumeGomez** [comment]
Oh you're right. Re-opening.
