### ISSUE TITLE
Too lenient `#[may_dangle]` on `BTreeMap`; misses `PhantomData` for dropck

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#99408]
```rs
struct PrintOnDrop<'a>(&'a str);

impl Drop for PrintOnDrop<'_> {
    fn drop(&mut self) {
        println!("printint: {}", self.0);
    }
}

use std::collections::BTreeMap;

fn main() {
    let s = String::from("Hello World!");
    let map = BTreeMap::from_iter([((), PrintOnDrop(&s))]);
    drop(s);
}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=debf42bbc64eefd24b72cc3edeedd5e8))
```
printing: �J��UJ�
```

@rustbot label T-libs, I-unsound
@rustbot claim

**Comment by m-ou-se** [comment]
It's probably time we move https://forge.rust-lang.org/libs/maintaining-std.html#is-there-a-manual-drop-implementation to the std-dev-guide.

**Comment by RalfJung** [comment]
> So maybe https://github.com/rust-lang/rust/pull/64595 made a difference?

That PR sounds like it was meant to be an optimization, not changing behavior. There are no new tests. And yet it turns out that it did change behavior!
Cc @Mark-Simulacrum @pnkfelix 

Specifically, I think this is when dropck started exploiting that ManuallyDrop does not drop its fields. I will add a corresponding testcase to https://github.com/rust-lang/rust/pull/103413.

**Comment by RalfJung** [comment]
By "fixing" you mean bring back the original behavior? That does not seem to be entirely the case; as this issue shows, one change in behavior did remain in place.
