### ISSUE TITLE
? compile rustc, cargo and all components with cpu-native 🚩 

### ISSUE THREAD

**Issue by alexzanderr** [rust-lang/rust#99507]
hello

i know from rust flags that is possbile to compile your program with cpu native flag

can i do that will all the tools from the toolchain to maybe get faster compile times?

or can i opt for a flag while updating components from rustup to compile them locally with cpu native 🚩?

i guess everything will run faster and more efficient with cpu native and maybe get faster compile times, so i strongly believe this is a good question. 

btw, i didnt find any options to compile rustc with cpu native, from its Cargo toml 

sorry for bad formatting, im writing from github mobile. 

thanks in advance.

**Comment by workingjubilee** [comment]
We've experimented with it, and last time this was tried, it did not greatly improve compile times because the design of the compiler is not significantly advantaged by modern ISA extensions. You can probably squeak out 5%, but it complicates distribution by a lot more than 5%.

In particular, compiling the Rust standard library with `-Ctarget-cpu=native` will result in a standard library version that is incompatible with projects that are **not** compiled for `-Ctarget-cpu=native`.

**Comment by workingjubilee** [comment]
> Yes, 5% is better than nothing,

It can also fail to improve things at all, actually. It depends on your architecture.

We don't enable `panic = "abort"` because that would make the quality of the diagnostics that we get from users much worse, which would make it even harder to close the... let me see...

...8136 issues we have open, of the 44378 issues that have ever been opened against this repository. In particular, without high-quality diagnostics, we can't even verify that some issues are duplicates of each other, forcing us to leave some issues open and waste time investigating.

We already do quite a lot of tuning otherwise on the binaries we distribute, including profile-guided optimization in CI. You might be better off discussing this on [Zulip](https://rust-lang.zulipchat.com), possibly with the [compiler performance stream](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance).

> I was talking about the rust compiler, not the stdlib.

`rustc` is compiled using its own `std`, so there is less difference than you might think.

>  that will be built depending on the project, right ?
> So the std its not compiled with -Ctarget-cpu=native, the std its compiled when im building my projects (binaries) for my machine.

We don't rebuild `std` on a per-project basis, no.

**Comment by est31** [comment]
If you want to do it locally, you can add `cargo.rustflag("-Ctarget-cpu=native");` to `fn rustc_cargo_env` in `src/bootstrap/compile.rs` and then locally compile the compiler with that change. You will also have to enable all tools in config.toml. Then you can use it as a [local rustup toolchain](https://rust-lang.github.io/rustup/concepts/toolchains.html#custom-toolchains). But yeah you'll probably want to do `-Zbuild-std` to avoid the issues @workingjubilee talked about, and the things compilers do don't get much faster when you use autovectorization.

**Comment by workingjubilee** [comment]
There doesn't seem to be anything actionable, fixable, or resoluble here, so I am closing this.

**Comment by alexzanderr** [comment]
sure. i will play around on linux machine. thanks for time and responses.
