### ISSUE TITLE
Make MutexGuard Send?

### ISSUE THREAD

**Issue by smessmer** [rust-lang/rust#99613]
Since Rust 1.62 has a new Mutex implementation that doesn't use pthread anymore, can we now mark MutexGuard as `Send`?

**Comment by bjorn3** [comment]
We still use pthreads as fallback for platforms where futex based Mutexes are not yet implemented: https://github.com/rust-lang/rust/blob/22d25f21dc008785f52e7c2833de4f4236b1066b/library/std/src/sys/unix/locks/mod.rs#L24-L29

**Comment by RalfJung** [comment]
AFAIK the plan is to keep using pthreads on macOS. This means `MutexGuard` cannot be made `Send` on all tier 1 platforms. I doubt we want this to be a per-platform thing.

**Comment by thomcc** [comment]
I believe we could do this if we decided to implement [usync](https://github.com/kprotty/usync)-style locks based around thread parking. This has been discussed at one point but has various drawbacks, and I'm unsure if it's still on the table.

In general I don't think we should do this. It's reasonable for the OS to want to know which thread holds a lock, in order to be able to implement various schemes in its scheduler. I think this probably has more utility than the utility of being able to send mutexguards to other threads, and so we'd probably be better off leaving the option open of using locks that allow this, by not codifying it in our API.

Parking lot supports this behind the `send_guard` feature btw, so if you really need it you can get it by adding a dependency.

**Comment by Dylan-DPC** [comment]
Closing this as it has drawbacks as mentioned above and wouldn't be accepted and there are alternatives available
