### ISSUE TITLE
Suggest ```fn``` if ```fun```, ```func```, ```function``` or ```def``` is used instead

### ISSUE THREAD

**Issue by Rageking8** [rust-lang/rust#99751]
Given the following code: 

```rust
func foo() -> i32 {
    123
}

function foo() -> i32 {
    123
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `!` or `::`, found `foo`
 --> src/main.rs:1:6
  |
1 | func foo() -> i32 {
  |      ^^^ expected one of `!` or `::`

error: could not compile `playground` due to previous error
```

Ideally the error message should suggest replacing ```func``` or ```function``` with ```fn```.

**Comment by ypprog** [comment]
New to rustc community and wants to contribute code. 
Are there any options to debug rustc which line of which file the error abort happens.

**Comment by gimbles** [comment]
@rustbot label +E-easy +E-mentor

@ypprog Welcome to Rust! ✨
 
This might be some help -- 
This issue is *very* similar to #99903, so take a peek at the diff there. IMO the following tokens are enough to check against

- function (Julia/JavaScript/etc)
- func     (Go)
- fun      (Kotlin)

Have fun! <3

**Comment by gimbles** [comment]
Instructions -- 

- Add a check if prev_token is either `function`/`func`/`fun` [here](https://github.com/rust-lang/rust/blob/master/compiler/rustc_parse/src/parser/diagnostics.rs#L603)
- Emit a message, something along the lines of "use `fn` instead of <prev_token> to make a function"

Should be helpful to take #99903 as a reference

**Comment by Rageking8** [comment]
We can include ```def``` if necessary.

**Comment by adam-tokarski** [comment]
Hi guys, another rust newbie looking for something easy to get started here. @ypprog are you still on this or could go with my attempt here?

**Comment by gimbles** [comment]
@adam-tokarski ypprog does seem to be active and it hasn't been that long, if you'd like you can pick another issue. =)

Try going through the E-Easy and/or E-Mentor category for easy issues. However, to clarify, if an issue which is claimed doesn't seem to have any work done for a long period of time (A month or so is a good amount of time) -- Feel free to ping the assignee to confirm and handle it accordingly.

**Comment by akabinds** [comment]
With these changes, I also think it is important to implement improved error messages for when a user puts the return type at the start of the function instead of the end.

PS: I don't know how that issue was mentioned there. I am sorry lol.

**Comment by gimbles** [comment]
I feel like adding `auto` might also be helpful for C++ developers :)

**Comment by akabinds** [comment]
Is this still being worked on? @ypprog
