### ISSUE TITLE
Proc macros should limit symbol exports

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#99909]
`readelf --wide --syms build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps/libproc_macro_hack-cdb4209108fe6fa9.so  | grep GLOBAL | grep -v UND | wc -l` shows over 5500 exported symbols. It should limit exports to only those that are used, just like for cdylib's. This should decrease the size of proc macros by allowing more effecting garbage collection of dead code.

**Comment by eddyb** [comment]
I just about almost opened my own issue, as this looks like it could cause e.g. #59998:
```console
$ nm -C -D target/debug/deps/libserde_derive-eb8144d61a68af88.so | rg PANIC_
00000000005d31b8 B std::panicking::panic_count::GLOBAL_PANIC_COUNT
```
(noticed the excess of exports in [@fasterthanlime's latest blog post, about RA/proc macros](https://fasterthanli.me/articles/proc-macro-support-in-rust-analyzer-for-nightly-rustc-versions))

Frankly I think I got confused at some point and expected proc macros to get more `cdylib` treatment than they actually do, I even described them in the past as "`cdylib`+`rmeta`".

And there are certainly places where it looks like that was the intention: https://github.com/rust-lang/rust/blob/b4151a41a0b275dee59ffbbc115e7bfc5be8a8c3/compiler/rustc_codegen_ssa/src/back/symbol_export.rs#L23-L26 https://github.com/rust-lang/rust/blob/b4151a41a0b275dee59ffbbc115e7bfc5be8a8c3/compiler/rustc_codegen_ssa/src/back/symbol_export.rs#L142-L146

But also this seems to apply? So what's the actual crate type for a proc macro? https://github.com/rust-lang/rust/blob/b4151a41a0b275dee59ffbbc115e7bfc5be8a8c3/compiler/rustc_codegen_ssa/src/back/symbol_export.rs#L260-L267

<hr/>

Ah there it is! For some reason we just completely bypass symbol-hiding for proc macros:
https://github.com/rust-lang/rust/blob/9067d5277d10f0f32a49ec9c125a33828e26a32b/compiler/rustc_codegen_ssa/src/back/linker.rs#L651-L661

**Comment by bjorn3** [comment]
> (noticed the excess of exports in [@fasterthanlime's latest blog post, about RA/proc macros](https://fasterthanli.me/articles/proc-macro-support-in-rust-analyzer-for-nightly-rustc-versions))

That is exactly what I was reading when I opened this issue :)

**Comment by eddyb** [comment]
* #35957

(i.e. the original proc macro impl) is what appears to have added the proc macro case here (which seems to have been called `RustcMacro` back then):
https://github.com/rust-lang/rust/blob/7a26aeca77bcf334747eddb630e3b9475149b7f5/src/librustc_trans/back/linker.rs#L240-L248

So what happened was that proc macros were a lot more like `dylib`s than `cdylib`s originally, and this was consistently implemented.

However, at some point, @michaelwoerister refactored `symbol_export`, in:
* https://github.com/rust-lang/rust/pull/38117
* commit https://github.com/rust-lang/rust/commit/93da4f81bfb879eea9236d5fd16734a68836c97c **"Export the plugin registrar from proc-macro crates (and not much else)"**, to be exact, changed proc macros from being like `dylib`s to being like `cdylib`s, at least in terms of symbol exports

But that decision couldn't have changed anything (at least not in the way we might expect) because of the bail-out from export hiding that proc macros have been hit by.

Nowadays not even `dylib` crates complete ignore export hiding, only proc macros do.

I believe this also tripped me up in the past, since `crate_export_threshold` *looked* correct, and I guess I never looked in depth at what's actually being exported, welp.

**Comment by bjorn3** [comment]
Removing the gate at https://github.com/rust-lang/rust/blob/9067d5277d10f0f32a49ec9c125a33828e26a32b/compiler/rustc_codegen_ssa/src/back/linker.rs#L651-L661 seems to cause the .rustc section to be omitted.

**Comment by bjorn3** [comment]
Opened https://github.com/rust-lang/rust/pull/99944 with a fix.

**Comment by eddyb** [comment]
```console
$ rustup update nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2022-08-02, rust version 1.64.0-nightly (fe3342816 2022-08-01)
...
  nightly-x86_64-unknown-linux-gnu updated - rustc 1.64.0-nightly (fe3342816 2022-08-01) (from rustc 1.64.0-nightly (9067d5277 2022-07-28))
$ cargo build -p serde_derive
$ nm -D --defined-only -S target/debug/deps/libserde_derive-*.so
0000000000315f10 0000000000000010 D __rustc_proc_macro_decls_284a6d00fbf74d9e__
0000000000000000 0000000000008ca2 N rust_metadata_serde_derive_284a6d00fbf74d9e
```
Beautiful, thanks @bjorn3! :sparkles:

**Comment by est31** [comment]
> This should decrease the size of proc macros by allowing more effecting garbage collection of dead code.

I wonder what the impact of this reduction has been.

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rust/pull/99944#issuecomment-1200926150 shows quite significant build time improvements. [serde_derive debug](https://perf.rust-lang.org/detailed-query.html?commit=25bb1c13bd472b75ceebee3b8dcf4dcbc431a8be&base_commit=6423ab3a755fed97f75b2361849155d4e996d02f&benchmark=serde_derive-1.0.136-debug&scenario=incr-unchanged) got almost 3MB smaller (down to 23MB). Same for [serde_derive opt](https://perf.rust-lang.org/detailed-query.html?commit=25bb1c13bd472b75ceebee3b8dcf4dcbc431a8be&base_commit=6423ab3a755fed97f75b2361849155d4e996d02f&benchmark=serde_derive-1.0.136-opt&scenario=incr-unchanged) (down to 8MB). I don't think we benchmark compilation of any other proc macro on perf.rust-lang.org.
